### ISSUE TITLE
[typescript]: support emitDecoratorMetadata

### ISSUE THREAD

**Issue by Hotell** [codesandbox/codesandbox-client#1004]
# 🐛 bug report

## Description of the problem

Codesandbox will fail when decorators + injection-js are used with TypeScript

## How has this issue affected you? What are you trying to accomplish?

I cannot publish demos of my open source projects :) because they won't run on sandbox :(

The same setup - on localhost everything works.

![image](https://user-images.githubusercontent.com/1223799/43199547-adc5828c-9012-11e8-9203-b9004493b193.png)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser |  Chrome
| Operating System | OSX

**Comment by Hotell** [comment]
Interesting, it is enabled within [transpilers](https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/sandbox/eval/transpilers/typescript/typescript-worker.js#L46-L47), although [TS 2.7.2 is used](https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/sandbox/eval/transpilers/typescript/typescript-worker.js#L4-L6). That might be the issue ?

I would love to help if I could get some guidance @CompuIves  :) ✌️

**Comment by CompuIves** [comment]
That's probably it! Would you be interested in opening a PR for this? I think it would just be changing the URL of the transpiler to https://cdnjs.cloudflare.com/ajax/libs/typescript/2.9.2/typescript.min.js and it should work.

Lemme know if you have any questions!

**Comment by Hotell** [comment]
So I've played with it a little tonight. bumping to latest doesn't work. It completely breakes transpilation with strange error:

![image](https://user-images.githubusercontent.com/1223799/43229238-6bb34af8-9064-11e8-8a74-458f52d25628.png)


![image](https://user-images.githubusercontent.com/1223799/43229228-6227ffba-9064-11e8-9d3f-bddb68c63fc1.png)

**Comment by Hotell** [comment]
@lbogdan now we have another issue as well `"jsxFactory": "createElement",` is not supported, that's why you get that error. If you fall back to import `React` from 'react' the error is still there
