### ISSUE TITLE
React + TS build not working

### ISSUE THREAD

**Issue by diegolameira** [codesandbox/codesandbox-client#1014]
# 🐛 bug report

It's not possible to download and build React Typescript, just because of the wmonk/create-react-app-typescript recent changes.

Steps to reproduce:
1 - Create a React+TS sandbox
2 - Download it
3 - npm install & npm run build

Whats wrong?
1 - Failed to load tsconfig.json: Missing baseUrl in compilerOptions
2 - Cannot find "$PATH/tsconfig.prod.json" file.

Is there a related issue?
https://github.com/wmonk/create-react-app-typescript/issues/322

Actually, to solve this I made 2 simple steps:
1 - compilerOptions.baseUrl = '.'  >  tsconfig.json
2 - { 'extends': './tsconfig.json' } > tsconfig.prod.json

Although the sandbox is already using the fixed version ("^2.13.0" which resolves to "2.16.0") there are still missing files.

**Comment by vitkon** [comment]
`wmonk/create-react-app-typescript` is out of date.
It'd be better to use the latest `create-react-app my-app --typescript`.
Is there a pull request for it?

**Comment by diegolameira** [comment]
Man, I just sent on July, since then many things has changed. If some one is still having this issue and want to contribute go ahead.

**Comment by SaraVieira** [comment]
I am doing spring cleaning of all the issues and I noticed we no longer have the error mentioned here as weare now using CRA

**Comment by OldManMeta** [comment]
It's mid 23 and I'm seeing this issue.......
