### ISSUE TITLE
File names not correctly sanitized

### ISSUE THREAD

**Issue by samdenty** [codesandbox/codesandbox-client#1026]
# 🐛 bug report

## Description of the problem

Files / directories labelled `constructor` or `toString` are not properly handled (or blacklisted). As a result, some operations fail when they're used as input.

![image](https://user-images.githubusercontent.com/13242392/43681214-97bb446e-9845-11e8-8d33-676a5960a4d0.png)

**Comment by lbogdan** [comment]
@samdenty Is this still an issue? I tried to replicate it, but the sandbox you linked to is not there anymore.

**Comment by SaraVieira** [comment]
Closed on lack of reply, please re open if the issue persist :)
