### ISSUE TITLE
Is there any plan to publish the CodeSandBox theme to the Visual Studio Marketplace?

### ISSUE THREAD

**Issue by u3u** [codesandbox/codesandbox-client#1027]
I really like this theme and hope to use it in VSCode. 😄

**Comment by satyarohith** [comment]
Here https://marketplace.visualstudio.com/items?itemName=LudvigLundgren.StockholmTheme

**Comment by u3u** [comment]
@satyarohith Thank you, I have tried this theme before, it seems that there are some differences with the official color scheme. I have a little perfectionism obsessive disorder. 😅

I have found the [official color scheme](https://github.com/CompuIves/codesandbox-client/blob/master/packages/common/themes/codesandbox.json). If the official has no plan, maybe I can submit a PR to [vscode-stockholm-theme](https://github.com/ludviglundgren/vscode-stockholm-theme). It would be great if it could be made by the official!

**Comment by CompuIves** [comment]
Yes! That would be super nice @u3u! :smikl

**Comment by superandrew213** [comment]
Done here https://github.com/ludviglundgren/vscode-stockholm-theme/pull/3

**Comment by ngryman** [comment]
Hey guys, it seems that the Stockholm theme deviates from the original Codesandbox theme. So if you are interested, I took the liberty to publish a straight copy or the original theme here: https://marketplace.visualstudio.com/items?itemName=ngryman.codesandbox-theme.

**Comment by SaraVieira** [comment]
@ngryman Can you publish some screenshots ?

**Comment by buzinas** [comment]
It seems that `ngryman.code-sandbox-theme` is not up-to-date with the latest CodeSandbox theme?

**Comment by ngryman** [comment]
Sorry I didn't have time to get back to that theme 😅 The repo is here: https://github.com/ngryman/codesandbox-theme. Do you mind dropping suggestions or PRs there? Thanks!

**Comment by SaraVieira** [comment]
Awesome @ngryman!

Thank you! To anyone looking for this here is also the link for VSCode Extensions:https://marketplace.visualstudio.com/items?itemName=ngryman.codesandbox-theme

**Comment by buzinas** [comment]
Still not working for me @ngryman :(

![image](https://user-images.githubusercontent.com/7298695/61388130-ccb85b80-a88d-11e9-9e3c-93c843cb1197.png)

**Comment by ngryman** [comment]
@buzinas Do you mind opening an issue at https://github.com/ngryman/codesandbox-theme? Thanks.

**Comment by buzinas** [comment]
@ngryman Sure, done!

**Comment by ChalkPE** [comment]
It seems extensions are not up-to-date again, so here's a way to package extension from code

```sh
yarn global add vsce
git clone https://github.com/codesandbox/codesandbox-client
cd codesandbox-client/standalone-packages/vscode-extensions/out/extensions/codesandbox-black-0.0.1 
vsce package
code --install-extension codesandbox-black-0.0.1.vsix
```
