### ISSUE TITLE
parcel + postcss

### ISSUE THREAD

**Issue by gary149** [codesandbox/codesandbox-client#1030]
Is there any way to use parcel with a postcss.config.js file (https://parceljs.org/transforms.html) in codesandbox ?
It's seems the answer is no because the postcss config file is not recognized by codesandbox, am i missing something ?

**Comment by CompuIves** [comment]
Yep, that's right. We only use postcss for autoprefixer currently, but don't have something for custom plugins. This would be a good enhancement to add.

**Comment by cmnstmntmn** [comment]
@CompuIves  so a configuration like

**.postcssrc**

```json
{
  "modules": false,
  "plugins": {
    "postcss-css-variables": {},  
    "postcss-custom-media": {},
    "postcss-import": {},   
    "css-mqpacker":  true,  
    "perfectionist": true,      
    "autoprefixer": {
      "grid": false,
      "browsers": ["last 5 versions", "> 5%", "ie >= 11"]
    }
  }
}
```

won't work, right?

**Comment by adamwathan** [comment]
Noticed custom PostCSS plugin configuration works with the Nuxt preset:

https://codesandbox.io/s/w263lk042l

...but can't get it to work anywhere else. Trying to understand what's supported and what's not 🤔

**Comment by lbogdan** [comment]
Hey @adamwathan , I don't know if you're aware, but the nuxt template is actually a [server / container sandbox template](https://hackernoon.com/codesandbox-containers-5864a8f26715), which means it's like your local development environment, only running in a container in "the cloud". The majority of templates (the "Client Templates" from https://codesandbox.io/s/ ) are running directly in the browser, with the default configuration of their respective frameworks, which don't include PostCSS (+ plugins), as far as I know.

**Comment by adamwathan** [comment]
@lbogdan Ah that makes a lot of sense, thanks for clearing that up!

**Comment by pspeter3** [comment]
Is this still true?

**Comment by zxqfox** [comment]
> Is this still true?

Feels like ;-(

**Comment by equinusocio** [comment]
Please vote the main comment because Parcel support Postcss by default everywhere but not here.

**Comment by CompuIves** [comment]
@equinusocio Do you have a reproducable sandbox I can use while implementing this?

**Comment by equinusocio** [comment]
@CompuIves Yes, here the basic Vanilla Parcel sandbox with a postcss js config:
https://codesandbox.io/s/parcel-postcss-dmd9w?file=/src/styles.css

Additional info:
- As stated [here](https://parceljs.org/transforms.html), Parcel uses postcss and picks any valid postcss config found in project's root (.postcssrc, postcss.config.js, etc...)
- `.postcssrc` files get the correct icon, but `postcss.config.js` doesn't.
- PostCSS file common extensions are `.css` and `.pcss`, but the second one is preferred to help the editor recognizing the syntax language. Currently, Codesandbox doesn't recognize `.pcss` files and for `.css` files, it show warning about custom syntax (eg. using postcss-preset-env nesting).

**Comment by equinusocio** [comment]
@CompuIves Do you need more info? Is the sandbox sent ok?

**Comment by equinusocio** [comment]
@CompuIves Have you all the info?

**Comment by equinusocio** [comment]
Hey, bot, mind your business.

**Comment by equinusocio** [comment]
Hey, bot, mind your business.

**Comment by s4l4x** [comment]
Would love to use postcss-nesting in codesandbox please 🥺

**Comment by JamesACS** [comment]
@s4l4x - Added it to our feature request board!

**Comment by andrew-dotson** [comment]
> @s4l4x - Added it to our feature request board!

Any update on this? This feature is def needed...
