### ISSUE TITLE
Can't use redux-devtools through extension

### ISSUE THREAD

**Issue by reccanti** [codesandbox/codesandbox-client#1035]
# 🐛 bug report
![image](https://user-images.githubusercontent.com/10334948/44070731-8de24b26-9f53-11e8-8b3a-952637807841.png)

## Description of the problem

When I try to use the redux-devtools extension in chrome, I get a "no store found" error. It appears to load correctly on the latest version of firefox. It also works correctly with other sites on chrome, including when I download the project and run it locally.

## How has this issue affected you? What are you trying to accomplish?

This is preventing me from using the redux devtools in my project.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1533293248-4a97495
| Browser | 68.0.3440.106
| Operating System | MacOS

**Comment by KKS1** [comment]
Hi @reccanti , two steps fixed this for me.

1) Add `redux-devtools-extension`  and `redux-devtools` as dependencies in your sandbox.

2) In your store js, do this 
``` import { devToolsEnhancer } from "redux-devtools-extension" ```

    ```export default createStore(rootReducer, devToolsEnhancer())```

where `rootReducer` is simply default export from `combineReducers` output.
Here is a sandbox TodoApp I created https://codesandbox.io/s/z2m5305j0p.
And remember to open the output browser in new window. (https://z2m5305j0p.codesandbox.io/)

Hope it helps!

Best,
Kanwaljeet

**Comment by euZebe** [comment]
@KKS1 Why would `redux-devtools` be required ? It seems to work well without it.

**Comment by lbogdan** [comment]
I'm inclined to close this, as I [forked](https://codesandbox.io/s/6v3vppl9ok) @KKS1 's example, removed `redux-devtools-extension`, and it still works for me, even inside the editor preview, without opening it in a new window:

![image](https://user-images.githubusercontent.com/2083930/55028616-d7b25c00-5010-11e9-9118-7c4cf74e9f7f.png)

@euZebe Thoughts?

**Comment by abhigk** [comment]
I had the same issue and I solved it by clicking on the Redux-dev-tools extension on chrome and granting access to the webpage.
