### ISSUE TITLE
Console.log erroneous output

### ISSUE THREAD

**Issue by TheoL** [codesandbox/codesandbox-client#1043]
# 🐛 bug report

## Description of the problem

The following code should output `[1,2,3]` from the first console.log and `[1,2,3,4]` from the second, but instead I get `[1,2,3,4]` from both in the console of the Codesandbox (the browser's console displays the correct output). This happens no matter how you modify the array (push, pop, shift, splice etc). 

It also seems to happen when working with objects.

```
const arr = [1, 2, 3];
console.log(arr);
arr.push(4);
console.log(arr);
```

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1533293248-4a97495
| Browser | Chrome / Opera
| Operating System | Windows 10

**Comment by CompuIves** [comment]
Observing values over a set time frame is a bit more tricky. I'm not sure if we can make that work in short time (@samdenty do you know if this is feasible?).

In the meantime I think it makes most sense to use the browser console for checking observables.

**Comment by CompuIves** [comment]
Oh wait I seemed to miss the initial problem. So if I understand correctly, mutated objects are also mutated in the console? That is really weird indeed, I was expecting that the object would be cloned before being sent to the main thread to show it. Maybe we only send the console.log after the mutation happened?

**Comment by samdenty** [comment]
The log events block the main thread whilst serializing, so in order to prevent noticeable lag, they're deferred using setTimeout.

**Comment by lbogdan** [comment]
I was wondering if we can close this?

@samdenty Is there anything to fix / improve here, or is it just how things work?

**Comment by lbogdan** [comment]
@samdenty Ping?

**Comment by samdenty** [comment]
@lbogdan without a rewrite, it's a limitation. You could switch it to synchronous processing, but it will cause main thread to block.

**Comment by Jhonatangiraldo** [comment]
@samdenty is it possible to manually switch to synchronous processing? So for let's say for X exercise where I need a good trace of values in the console, I use the synchronous way

**Comment by SaraVieira** [comment]
As that is the way it at least for now I will close this issue and any other issues can be taken to the https://github.com/samdenty/console-feed repo
