### ISSUE TITLE
Target the default templates from the define API

### ISSUE THREAD

**Issue by kmelve** [codesandbox/codesandbox-client#1047]
# ❔ Question

I've read the documentation and tried to browse the issues thoroughly, but I haven't found an easy way to target [one of the default templates](https://codesandbox.io/s/) from the [define API](https://codesandbox.io/docs/importing#define-api). I haven't managed to figure out how I can via the define API create a new sandbox from a GitHub project either.

As far as I can see, I have to recreate the file structure(s) of these default sandboxes manually and add them to the `files`-key? 

It would be great if it was possible to create a new sandbox with one of the default templates by adding the parameter `template: '<react|vue|preact|angular|github-url|...>'`.

**Comment by fredj** [comment]
FYI, you can set the template by adding a `sandbox.config.json`, something like:
```
  files: {
    'sandbox.config.json': {
        content: '{"template": "parcel"}'
    },
    ...
}
```
