### ISSUE TITLE
About visual noise reduction through UI colour tweaks.

### ISSUE THREAD

**Issue by KelSolaar** [codesandbox/codesandbox-client#1052]
# 🌈 Feature

Hi,

First thanks for the great app, it is quite awesome and very well polished. I had an aesthetic suggestion which is obviously very subjective. What about reducing the luminance of the two elements highlighted in the following screenshot:

![image](https://user-images.githubusercontent.com/99779/44510321-7cca2680-a708-11e8-82d9-3e9c58c260ba.png)

The browser frame is quite bright and I find it very distracting, especially against the dark theme and my own stuff which is very dark. Same goes for the big blue *Add Dependency* button.

Cheers,

Thomas

**Comment by lewisvrobinson** [comment]
Seems like this has already been partially implemented with the dark address bar being the default.
https://github.com/codesandbox/codesandbox-client/blob/bd8254c75d4b610a5277d882fd9d089aa668bcbd/packages/common/src/components/Preview/AddressBar/elements.ts#L5
Does i still make sense to add a preference option for this?

**Comment by CompuIves** [comment]
Oh right! I think there's no need for a preference option for this, as this is now our core design and adding an option would add complexity.

Thanks for showing this issue! I forgot to close it.
