### ISSUE TITLE
Show Markdown preview for .md files in "current module view"

### ISSUE THREAD

**Issue by zocky** [codesandbox/codesandbox-client#1053]
When:
(a) "current module view" is selected in the preview window, and 
(b) a file with the `.md` extension is open in the current tab

Then:
The preview window should show a preview of formatted markdown, preferably github-flavored.

**Comment by ChrisBrownie55** [comment]
Hey, I'm interested in what the current status is on the possibility of adding in a feature to be able to preview markdown. It seems like @SaraVieira got started on MDX preview capability but the PR was closed without any comments.

**Comment by SaraVieira** [comment]
Hey!

We are still gonna build this but that PR had code that was waay too old to be merged :/

**Comment by ChrisBrownie55** [comment]
Glad to hear it's still on the radar 👍 I'd love to help with the development if at all possible

**Comment by SimplyComplexable** [comment]
I'd love to see this feature. Any progress? I'm also willing to help if it's needed.

**Comment by DannyFeliz** [comment]
I would love to see this feature

**Comment by Kassan424kh** [comment]
me too

**Comment by SSTPIERRE2** [comment]
This never got done?

**Comment by JamesACS** [comment]
Hey @SSTPIERRE2 - This is on our roadmap. Sorry for the delay!

**Comment by JamesACS** [comment]
Hey @SSTPIERRE2 this should now be live!

**Comment by f3r** [comment]
> Hey @SSTPIERRE2 this should now be live!

Hi there! I tried the feature today, but wasn't able to visualize the md preview, what are the steps to preview an md file?

Thanks so much!

**Comment by f3r** [comment]
@JamesACS 

When I try to activate the md preview view (right click on title, open preview), it doesn't load and the following error appears in the console, fyi

```
winston.pub.js:43 Uncaught (in promise) TypeError: this.editor.onDidDispose is not a function
	at new d (winston.pub.js:43:1)
	at Function.create (winston.pub.js:43:1)
	at l.createNewPreview (winston.pub.js:43:1)
	at l.preview (winston.pub.js:43:1)
	at i (winston.pub.js:43:1)
	at t.ShowPreviewCommand.execute (winston.pub.js:43:1)
	at e._executeContributedCommand (extensionHostProcess.js:1:413891)
	at e.$executeContributedCommand (extensionHostProcess.js:1:414379)
	at t._doInvokeHandler (extensionHostProcess.js:1:538998)
	at t._invokeHandler (extensionHostProcess.js:1:538670)
	at t._receiveRequest (extensionHostProcess.js:1:537283)
	at t._receiveOneMessage (extensionHostProcess.js:1:536126)
	at extensionHostProcess.js:1:533934
	at e.fire (extensionHostProcess.js:1:44843)
	at extensionHostProcess.js:1:39672
	at e.fire (extensionHostProcess.js:1:44843)
	at extensionHostProcess.js:1:161676
	at r._socketDataListener (extensionHostProcess.js:1:161706)
	at r.d.emit (events.js:146:5)
	at r.defaultListener (0.client-ext-host-worker.f0cbb12c.worker.js:46187:18)
```

Looking forward to this feature working! Thanks a lot!

**Comment by JamesACS** [comment]
Please could you link us to the sandbox in question @f3r ?

**Comment by f3r** [comment]
> Please could you link us to the sandbox in question @f3r ?

Hi there,

It happens with any sandbox, here you have one for reference:

https://codesandbox.io/s/17-css-intro-2-floats-clears-gou57t?file=/README.md

Using Chrome Version 103.0.5060.53 (Official Build) (arm64) in OSX 12.4 with M1

**Comment by JamesACS** [comment]
Thanks @f3r - Just wanted to confirm this is an existing issue we're aware of with the module/project view toggle.

**Comment by danielsharvey** [comment]
> Thanks @f3r - Just wanted to confirm this is an existing issue we're aware of with the module/project view toggle.

@JamesACS This still seems to be an issue.
