### ISSUE TITLE
Syncing code

### ISSUE THREAD

**Issue by johnhamm** [codesandbox/codesandbox-client#1054]
# 🌈 Feature

First of all, wow!  I'm blown away by Codesandbox.  Waaaaaaaaaaaaaay better than Stackblitz!
So this is an almost perfect online IDE.  

The one thing it is missing is the capability to easily sync with our Git repository.  I use asp.net core for my backend, but I want to use Codesandbox exclusively for my frontend IDE (private sandbox), but I need an easy way to sync my code with my source control.  Right now the only option is exporting from Codesandbox and extracting to my local repository.

I see there's already Github integration so it shouldn't be too difficult to modify it for private Git repositories right?

**Comment by johnhamm** [comment]
Not GitHub - just git :(

**Comment by tonister** [comment]
I'm fine with GitHub integration, just give me a "pull" button please :'(, or just gimme a terminal with git in it, anything that would enable me to grab changes or change branches, I've done a PR, but now the darn sandbox is stuck on the side-branch...

**Comment by lbogdan** [comment]
(labeled this as `github`, as it actually has a broader meaning; it's only called `github` because we only have GitHub integration ATM)
