### ISSUE TITLE
Better error when uploading an already existing file?

### ISSUE THREAD

**Issue by rowild** [codesandbox/codesandbox-client#1055]
When I upload a e.g. main.js file to the src folder of a Vue project, where a main.js already exists, I get the error "Internal server error". 
Is there any chance to get a better error feedback in this case? Would be great to read "file already exists."
Thank you!

**Comment by CompuIves** [comment]
Yeah definitely! This is an issue in our server that requires a manual check, currently the database constraint just throws.
