### ISSUE TITLE
Add sandbox configuration option to disable the virtual console

### ISSUE THREAD

**Issue by tannerlinsley** [codesandbox/codesandbox-client#1068]
# 🌈 Feature

A sandbox configuration option to disable the virtual console

How?
You should be able to set it in the optional config for a sandbox. When set, the virtual console will be disabled and defer all logging to the browser console.

Why?
The virtual console is extremely slow when working with larger datasets compared to the browsers native console. This setting would make it easier to debug projects with many log statements and large data models.

**Comment by CompuIves** [comment]
This is a very valid request, I imagine there must be a perf impact of serializing all console.log statements recursively. Did you notice a big impact on perf @tannerlinsley?

**Comment by tannerlinsley** [comment]
Absolutely. Even with just a few objects with deep nested data and
structure the sandbox quickly became unresponsive.

**Comment by tannerlinsley** [comment]
We could also look into doing Lazy rendering for the console too. Only
serialize the depth that is currently being displayed.

**Comment by hxuanhung** [comment]
Hi, I'm happy to work on it. Is this still valid?

**Comment by tannerlinsley** [comment]
As far as I know, yes. Absolutely. I have many boxes that deal with large datasets and often have to log large amounts of data to the console. This would really speed up the interface!

**Comment by hxuanhung** [comment]
Okie, I will try it out in a PR.

**Comment by hxuanhung** [comment]
@CompuIves @tannerlinsley please comment on my thoughts:
1. I will put this option let's say `Console Enabled` in Preview tab and set it by default to `True`. 
2. Either hide the Console tab in Dev tools or keep it and only display a message saying that: `You have disabled logging in this console. You can turn it on in Preferences/Preview/Console Enabled or you can use the broswer's console to view logs`.

**Comment by tannerlinsley** [comment]
Yeah definitely keep the tab with the notice that it has been disabled.
Everything else sounds great!

**Comment by hxuanhung** [comment]
@CompuIves What do you think?

**Comment by brennowilliam** [comment]
Is someone still working on this? I'm interested in contribute for the first time.

**Comment by DVLP** [comment]
It's a much needed feature. Custom handling of each console.log in a loop where there are thousands of elements is killing the browser. In such cases built-in console is the only way.

In the meantime a workaround is to create TamperMonkey script as follows(it has to match the actual sandbox not codesandbox IDE)

```javascript
// ==UserScript==
// @name         Restore console
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       Pawel
// @match        https://*.codesandbox.io/*
// @grant        unsafeWindow
// ==/UserScript==

unsafeWindow.restoreConsole = function () {
    unsafeWindow.console = window.console;
}

```

**Comment by dance2die** [comment]
## Question

**Is there a way to change "action icons"?**

I was playing around with toggling virtual console as shown in demos at the bottom, but wanted to switch icons depending on console enabled/disabled status.

## Enabled (top), Disabled (bottom)
![image](https://user-images.githubusercontent.com/8465237/59649801-da28db80-9151-11e9-88a1-a7175518db81.png)

## The code in question
I'd like to change `StyledPowerIsOnIcon` to another icon, when the console is disabled.
_My forked code can be found here-https://github.com/dance2die/codesandbox-client/blob/d88947f70de2241c45906ba1a0e112d070a76c1c/packages/app/src/app/components/Preview/DevTools/Console/index.tsx#L337_

```javascript
export default {
  id: 'codesandbox.console',
  title: 'Console',
  // @ts-ignore  TODO: fix this
  Content: withTheme<StyledProps>(Console),
  actions: [
    {
      title: 'Toggle Console',
      onClick: () => {
        dispatch({ type: 'toggle-console' });
      },
      Icon: StyledPowerIsOnIcon,
    },
    {
      title: 'Clear Console',
      onClick: () => {
        dispatch({ type: 'clear-console' });
      },
      Icon: StyledClearIcon,
    },
    // redacted for brevity
  ],
};
```

## Demos
### Toggling console on type
![toggle console demo 1](https://user-images.githubusercontent.com/8465237/59649500-efe9d100-9150-11e9-8cd0-e164f9747141.gif)

### Toggling console showing on-load messages

![toggle console demo 2](https://user-images.githubusercontent.com/8465237/59649649-6c7caf80-9151-11e9-84e4-583efcaaa914.gif)

**Comment by DVLP** [comment]
Unstale

**Comment by SaraVieira** [comment]
This has actually been fixed today it was closed by: https://github.com/codesandbox/codesandbox-client/pull/5187


And you can see the docs here: https://codesandbox.io/docs/configuration#sandbox-configuration
