### ISSUE TITLE
GraphQL Query Never Resolves When Jest Test Is Present

### ISSUE THREAD

**Issue by stolinski** [codesandbox/codesandbox-client#1074]
# 🐛 bug report

## Description of the problem

This is a weird one. I have a basic Apollo query that doesn't resolve on page load, it just sits in the loading state. @CompuIves Noticed in an email chain that the query successfully resolves when the default CRA test is removed. 

## How has this issue affected you? What are you trying to accomplish?

This is a CRA project used to show how to write Apollo queries and mutations. The code was imported into CodeSandbox and works 100% as expected outside of CSandbox. I'm cool with removing the CRA test and calling it a day, but I feel like there is probably something weird going on.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1536082527-76b9252 | 
| Browser | Chrome(68)/Firefox |
| Operating System | Mac OS High Sierra |

**Comment by CompuIves** [comment]
I think this is directly a result of running the tests in the same scope as the application itself. An intermediary fix may be to not run the tests right after the application has been loaded, but only after the user opens the `Tests` tab.

The longer term solution should be to run the tests in another iframe (from the sandbox iframe). I will take a look at this at the start of next week.

**Comment by christianalfoni** [comment]
this should have been resolved, closing now. Please reopen if still an issue
