### ISSUE TITLE
 CRA App With Jest / React Testing Library Refreshes Constantly 

### ISSUE THREAD

**Issue by stolinski** [codesandbox/codesandbox-client#1075]
# 🐛 bug report

## Description of the problem

A pen that was originally created via CRA and uploaded to Sandbox, refreshes constantly. Refreshes stop when tests are removed.

## How has this issue affected you? What are you trying to accomplish?

This app is to teach Jest & React Testing Library. This works 100% off CodeSandbox as expected. Originally created in CRA, constant refresh stops if tests are removed.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1536082527-76b9252 |
| Browser | Chrome(68)/Firefox |
| Operating System | MacOS High Sierra |

**Comment by arthurdenner** [comment]
Hi @stolinski! 👋 Could you verify if this is still happening? I tried to reproduce but I couldn't. If it's not, could you close the issue, please?

**Comment by lbogdan** [comment]
Closing this, as it's way old, there were lots of changes in the meanwhile, and can't replicate in the OP sandbox. @stolinski Please re-open if this is still an issue for you.
