### ISSUE TITLE
refreshing the github url will not fetch latest changes

### ISSUE THREAD

**Issue by ppisljar** [codesandbox/codesandbox-client#1077]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?
- link to github repository
- add a commit manually (not thru codesandbox)
- the `/s/github/` url will not show the latest version
- refresh the `/s/github/` url, still it shows the previous version 
- refresh the `s/github/` url with caching disabled (chrome dev tools), UI says fetching from github and then shows the latest version of file

it seems chrome does a bit too much of caching

### Your Environment
| Browser | Chrome
| Operating System | Ubuntu 16

**Comment by lbogdan** [comment]
Hey @ppisljar ,

Are you still seeing this?

**Comment by SaraVieira** [comment]
Closed on lack of reply, please re open if the issue persist :)
