### ISSUE TITLE
Middle Mouse button to close Tab

### ISSUE THREAD

**Issue by guaiamum** [codesandbox/codesandbox-client#1096]
# 🐛 bug report

## Description of the problem
When clicking with the middle button of the mouse to close a tab, the content from the clipboard is pasted in the tab that remained open

## How has this issue affected you? What are you trying to accomplish?
I was trying to close the tab only.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | editor@latest |
| Browser | Chrome |
| Operating System | Ubuntu |

**Comment by SaraVieira** [comment]
Hey!

Sorry can you explain the issue better?

**Comment by guaiamum** [comment]
Hey @SaraVieira ,
I just tested in a preact template and the problem seems to be resolved, although the _paste_ action with the middle button is not present anymore. The problem used to happen when closing a file tab, which would paste the clipboard content on the next file.
Thanks for the attention, and nice talk in the typeof conf, btw! ;)

**Comment by SaraVieira** [comment]
Hey!


We just use VSCode now so you should be able to add all the keybinds you want like this:

https://code.visualstudio.com/docs/getstarted/keybindings


> Thanks for the attention, and nice talk in the typeof conf, btw! ;)

Thank you :D

**Comment by SaraVieira** [comment]
Closed on lack of reply, please reopen if the issue persist :)
