### ISSUE TITLE
Excessive SW cache use (on chrome macOS at least)

### ISSUE THREAD

**Issue by renzo-s** [codesandbox/codesandbox-client#1097]
# 🐛 bug report

## Description of the problem
Codesandbox uses an excessive amount of Service Worker cache disk space. About 5 times more than any other cache in my case. How this may be related to Chrome specifically, I don't know, but I figured this is a thing easily overlooked, so I thought I'd mention it here. Imagining every site using that much disk space with SW's gives me the chills..

PS. I don't even use codesanbox (to create), but have encountered demo's etc using the platform.

![screenshot disk usage](https://i.imgur.com/A6tTWPB.png)

### Your Environment
Chrome 69.0.3497.92 
macOS 10.13.6

**Comment by CompuIves** [comment]
Good that you mention it. I'll take a look, it may be high because it automatically caches VSCode from the copied files
