### ISSUE TITLE
Allow microphone, and other apis access to the iframe

### ISSUE THREAD

**Issue by magicspon** [codesandbox/codesandbox-client#1112]
# 🌈 Feature

https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes

It would be super useful to be able to test things like MediaRecorder in codesandbox

[![Edit 4qmv2mv2y0](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4qmv2mv2y0)

By default, or maybe an option to allow certain features

I added `allow="microphone" to the iframe in dev tools which allowed me to do some testing

**Comment by SaraVieira** [comment]
Hey!

We actualy fixed this a while ago when someone needed this and we became available of a solution.

You can test here: https://codesandbox.io/s/74pzm9lkq6

We now have this in our iframe: 
```
allow="geolocation; microphone; camera;midi; vr; accelerometer; gyroscope; payment; ambient-light-sensor; encrypted-media; usb"
```
