### ISSUE TITLE
🌈 Clone project from GitHub into server mode

### ISSUE THREAD

**Issue by babakness** [codesandbox/codesandbox-client#1116]
# 🌈 Feature

## What is this feature? 
Clone from GitHub to server 
## How the feature should work? 
Copy-paste link to GitHub project and open it server mode instead of client mode

**Comment by lbogdan** [comment]
We have both the possibility of switching a client sandbox to a server one, and smarter heuristics for detecting server sandboxes when importing from GitHub on our short to-do list!
