### ISSUE TITLE
ReasonML template is missing css file

### ISSUE THREAD

**Issue by nhducit** [codesandbox/codesandbox-client#1118]
# 🐛 bug report

## Description of the problem
ReasonML template is missing css file depite of `ToDo.App` file have css classes
## How has this issue affected you? What are you trying to accomplish?
Don't know how to add css file to the codesandbox
###  Link to sandbox: [link]() (optional)
https://codesandbox.io/s/2072wonn4n
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | https://codesandbox.io/s/2072wonn4n
| Browser | Chrome 69
| Operating System | MacOS

**Comment by hikiRe** [comment]
Yes, the template is missing the css file.
FWIW, you can import a css file using raw js like this:
```re
[%% bs.raw {| require("./style.css") |}];
```

see this [sandbox](https://codesandbox.io/s/y7vy88j2mx).

**Comment by jthegedus** [comment]
These examples should probably now be https://rescript-lang.org/ instead of ReasonML
