### ISSUE TITLE
[bug] Pausing an app causes all connected editor sessions to freeze

### ISSUE THREAD

**Issue by mike-north** [codesandbox/codesandbox-client#1128]
# 🐛 bug report

## Description of the problem

Pausing a CSB application thread causes Live share participants' editors to lock up

## How has this issue affected you? What are you trying to accomplish?

When pair programming, my partner and I were investigating code around a breakpoint. 

Whenever I (the host of the session and owner of the sandbox) hit the breakpoint, my partner could no longer use his CSB editor (it would not even respond to user events like right click).

**Comment by SaraVieira** [comment]
@CompuIves Has this been fixed with rewrite?
