### ISSUE TITLE
ReasonML editor uses wrong comment syntax

### ISSUE THREAD

**Issue by ryuheechul** [codesandbox/codesandbox-client#1129]
# 🐛 bug report

## Description of the problem
ReasonML Editor uses wrong comment syntax (`//`)
FYI, `/* */` is the right comment syntax

## How has this issue affected you? What are you trying to accomplish?
It affected as showing wrong error below
```
Error
0,248,Playground_compiler_with_refmt.Reason_syntax_util.Error,160,0,0,,33,649,656,0,,33,649,657,0,0,1402: <UNKNOWN SYNTAX ERROR>
```
I tried to accomplish that editors short cut for commenting (`CMD+/`) to add `/* */` not `//`

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1538077445-546871f |
| Browser | Google Chrome Version 69.0.3497.100 (Official Build) (64-bit) |
| Operating System | macOS High Sierra 10.13.6 (17G65)
| Editor | Monaco (since I use vim) |

**Comment by jbranchaud** [comment]
I'd love to try fixing this issue. I think I could use a little guidance though as I'm new to the codebase.

I've already done a little digging. It seems like many languages have specific configuration files (located in [basic-languages](https://github.com/CompuIves/codesandbox-client/tree/cba4e442b57443ca0ad130362b571e4c10824794/standalone-packages/monaco-editor/release/esm/vs/basic-languages)) -- these dictate the [style of comments](https://github.com/CompuIves/codesandbox-client/blob/cba4e442b57443ca0ad130362b571e4c10824794/standalone-packages/monaco-editor/release/esm/vs/basic-languages/go/go.js#L7-L10). I believe this is in turn used by monaco-editor as part of [`lineCommentCommand.js`](https://github.com/CompuIves/codesandbox-client/blob/master/standalone-packages/monaco-editor-core/esm/vs/editor/contrib/comment/lineCommentCommand.js#L37).

It doesn't look like ReasonML has it's own language file. I imagine the comment config for Reason is either being defined somewhere else or there are some default settings that ReasonML is using.

Does it seem like I am going down the right path on this?

**Comment by jbranchaud** [comment]
@CompuIves I'd love to work on fixing this bug, but I could use a little bit of guidance.

**Comment by lbogdan** [comment]
It looks like with the recent move to VSCode as the default editor, we've lost ReasonML support completely?

Cc @CompuIves
