### ISSUE TITLE
Parcel with Pug doesn't work 

### ISSUE THREAD

**Issue by jjcm** [codesandbox/codesandbox-client#1135]
# 🐛 bug report

**Comment by SaraVieira** [comment]
Hey!

On normal sandboxes you don't really have a file system on node APIs .

Can you try this on a sse sandbox and see if it's still a problem

On a node one you will have a file system

**Comment by dragorwyin** [comment]
Still has same problems and do not know what to do

**Comment by lbogdan** [comment]
Here's an example of a server sandbox, hope this helps: https://codesandbox.io/s/qkp0ojk8pj .

**Comment by ta-run** [comment]
Not sure if this is related, but tried creating a vanilla-pug template - https://codesandbox.io/s/vanilla-and-pug-onj2c?fontsize=14 - which doesn't work.

Am I missing something trivial? or is a node container sandbox the only way to get this working?

**Comment by SaraVieira** [comment]
Hey!

For now a node sansbox container is the only way to get it to work :/

**Comment by SaraVieira** [comment]
Hey!

For now a node sansbox container is the only way to get it to work :/

**Comment by lordfpx** [comment]
This issue is still there, could you investigate that please ?
Thanks !

**Comment by b1m1nd** [comment]
Yes please can we get this working!! 
https://codesandbox.io/s/parcel-pug-noworky-7y5iu

**Comment by SaraVieira** [comment]
Hey!

As said previously we do not have a filesystem on client sandboxes so the only way you can make it work is container ones like Bogdan said:

Example: https://codesandbox.io/s/qkp0ojk8pj 
A template you can save: https://codesandbox.io/s/parcel-pug-0dncl

There is not a lot we can do about the not reloading but it will be fixed when version 2 of parcel comes out.

As said this is something that we have technical constraints on.

We would love to take a look at a PR but at the moment we do not have the ability to pursue this issue
