### ISSUE TITLE
[bug] SSE sandbox filesystem omits all empty files and their enclosing folders

### ISSUE THREAD

**Issue by mike-north** [codesandbox/codesandbox-client#1136]
# 🐛 bug report

## Description of the problem

When creating a sandbox that has empty files like
-  [`.gitkeep`](https://fileinfo.com/extension/gitkeep) files in otherwise empty directories
-  an empty css file, that's destined to be populated with the user's styles as they work on their sandbox

These files and any enclosing empty folders are not created in the SSE file system

## How has this issue affected you? What are you trying to accomplish?
I was trying to use CSB to work on a project that, when it starts, needs to contain certain folders (which begin empty) so that they can be watched for changes. When I run the project in CSB, the app crashes due to these empty files being pruned.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1538077445-546871f
| Browser | Chrome 70
| Operating System | OS X 10.14.1 Beta (18B45d)

**Comment by lbogdan** [comment]
Looks like an issue with the importer (or the API?), that returns `code: null` instead of `code: ""`:
```json
{
  "updated_at": "2018-09-29T21:58:47.257928",
  "title": "app.css",
  "source_id": "354c4de8-6a2d-4c40-a194-a0c51a3b38c8",
  "shortid": "ryNx1jHdaYX",
  "is_binary": false,
  "inserted_at": "2018-09-29T21:58:47.257915",
  "id": "2eb5fbb5-9d6f-4c28-abc6-5f52f33311cf",
  "directory_shortid": "B1BJjHuptQ",
  "code": null
}
```

Cc @CompuIves
