### ISSUE TITLE
codesandbox Vanilla crashes while working with console.logs

### ISSUE THREAD

**Issue by abdullahtariq1171** [codesandbox/codesandbox-client#1145]
# 🐛 bug report
Some weird behavior while working with Map() console logs (see screencast)

## Description of the problem
When user try to read map console.log (having `{}` as `key`) it crashes

```
let myMap = new Map();
myMap.set({}, "value associated with obj")

console.log(myMap)
```

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Vanilla / PROD-1538502683-656f795|
| Browser | Chrome/Version 69.0.3497.100 (Official Build) (64-bit)|
| Operating System | MacOS High Sierra|

**Comment by lbogdan** [comment]
I can confirm this is still happening.

@samdenty , do you have any idea?
