### ISSUE TITLE
ReasonReact - outdated API

### ISSUE THREAD

**Issue by dangdennis** [codesandbox/codesandbox-client#1147]
# 🐛 bug report

## Description of the problem
The method `ReasonReact.arrayToElement` has already been deprecated in the latest version of ReasonReact (0.5.3). It should be `ReasonReact.array`. Likewise for similar methods. However, in the codesandbox, the former works.

## How has this issue affected you? What are you trying to accomplish?
Building ReasonReact apps with the latest APIs will maintain consistency for new learners.

###  Link to sandbox: 
https://codesandbox.io/s/48xyj4z1nw

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Chrome  | Version 69.0.3497.100 (Official Build) (64-bit)
| Mac OS Mojave |

**Comment by Haroenv** [comment]
Yes, seems like the version of ReasonReact somehow isn't the one you ask for. See also `ReasonReact.string`

**Comment by dangdennis** [comment]
I tried to dig for the area where the Reason config files or maybe a `bsconfig.json` could be, but no luck. Was hoping I can fix this myself to use the latest stuff in ReasonReact.

**Comment by claytoncrockett** [comment]
Yeah looks like it is still outdated :/ ReasonReact.string still won't work

**Comment by dangdennis** [comment]
If someone can figure out where to update the reason-script, that'd be a good PR. I can't find it myself 😞

**Comment by claytoncrockett** [comment]
I'm thinking the problem is not having the bs-platform dependency, which is required now. I've tried to add it but it fails, possibly because no ocaml compiler? Gonna keep looking into it

**Comment by lbogdan** [comment]
Hey guys, is this still an issue? Maybe a [server sandbox](https://medium.com/@compuives/codesandbox-containers-out-of-beta-improvements-be79679df4cc) would help? If so, can you maybe close this? Thanks!

**Comment by dangdennis** [comment]
The client side template still has this problem. but I'll set up a reason react template with the server later this week.

**Comment by lbogdan** [comment]
Ok, nice, ping me whether you have any questions or issues!

**Comment by dangdennis** [comment]
Never got around to resolving this. But will close.
