### ISSUE TITLE
GitHub commits & PRs with Private Sandboxes

### ISSUE THREAD

**Issue by jthegedus** [codesandbox/codesandbox-client#1159]
# ❔ Question

Private Sandboxes do not seem to support the GitHub commit and PR feature.

Since server sandboxes mention they cannot be made private as yet, it would be nice to have the same warning about the GitHub commit/PR feature if that is the case.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | a private PROD-1538584147-1a00522 sandbox
| Browser | Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
| Operating System | Windows 10 1809

**Comment by lbogdan** [comment]
Hey @jthegedus , is this a docs issue, then?

**Comment by jthegedus** [comment]
It was a lack of docs at the time. I have not investigated whether this issue is resolved after subsequent CSB releases.

**Comment by medampudi** [comment]
this issue is not resolved. and currently exists in the platform. Can you Please look into it.

**Comment by jthegedus** [comment]
I feel https://github.com/codesandbox/codesandbox-client/issues/1928 is related

**Comment by SaraVieira** [comment]
Hey!

This seems to be working now, I made a private sandbox and when I created a github repo it actually made a private repo with no issues :D

**Comment by jthegedus** [comment]
Great news, thanks @SaraVieira :tada:
