### ISSUE TITLE
Support jsconfig.json

### ISSUE THREAD

**Issue by grant** [codesandbox/codesandbox-client#1207]
# 🐛 bug report

## Description of the problem

`jsconfig.json` isn't supported like VSCode. This could make autocompletion much better for certain apps.

Repro:

Use the Vanilla (+TS) template.

- Create a `jsconfig` file.
```json
{
  "compilerOptions": {
    "noLib": true
  }
}
```
- Notice how ts autocompletion is still huge despite us not wanting to use most libs.

## Examples

Code Sandbox:

<img width="368" alt="screen shot 2018-10-18 at 23 48 32" src="https://user-images.githubusercontent.com/744973/47201941-70d99a00-d330-11e8-9bb4-de1dbe253ba1.png">

VSC:

<img width="295" alt="screen shot 2018-10-18 at 23 50 08" src="https://user-images.githubusercontent.com/744973/47201992-9e264800-d330-11e8-8df6-c71d2f7cc898.png">

## How has this issue affected you? What are you trying to accomplish?

I'm trying to support a Google Cloud product, [clasp](https://github.com/google/clasp) with this tool.

**Comment by lbogdan** [comment]
Hey @grant ,

Did the recent switch to VSCode as the default editor fixed this for you? If so, could you please close this?

**Comment by grant** [comment]
It removes most autocompletion results, but for some reason there are Jest results and dom autocompletion results (`innerHTML`)

![Screen Shot 2019-03-26 at 16 09 47](https://user-images.githubusercontent.com/744973/55039566-d9b0f680-4fe1-11e9-999d-e5e4496fb34d.png)

I expect only valid TS symbols. Those other symbols are invalid.
As a result, I cannot close this.

**Comment by CompuIves** [comment]
Hmm, yes we auto install the jest types if `autoInstallTypes` is set to `true`  (which is the default). I'll need to make a check for automatic type acquisition to disable it.

**Comment by sbussard** [comment]
There's no support for `baseUrl`
https://codesandbox.io/s/cocky-frost-mi926

**Comment by markerikson** [comment]
Would love to see this added.  I just tried to turn https://github.com/markerikson/rsk-convert-todos-example into [a sandbox for the Redux Starter Kit docs](https://codesandbox.io/s/github/markerikson/rsk-convert-todos-example/tree/accc5896b5d092e736ec2d24d10246ff18aec7cf), but it's breaking due to not recognizing absolute imports :(
