### ISSUE TITLE
Add option to disable left scroll to go back in history

### ISSUE THREAD

**Issue by kube** [codesandbox/codesandbox-client#1208]
# 🌈 Feature
On macOS, browsers **go back in history on left scroll**.

It is often triggered in CodeSandbox when **scrolling in the editor**, which is kind of painful.

Maybe some users want this behaviour in CodeSandbox, but there could be **an option to disable it**.

*I know this can be disabled at the system level but find it useful on classical webpages though.*

## Implementation example

https://github.com/micho/jQuery.preventMacBackScroll/blob/master/jquery.preventMacBackScroll.js

**Comment by Glazy** [comment]
If you're going to disable back scrolling you may as well also disable forward scrolling. Scrolling either left or right on a trackpad is currently precarious and disabling it would make using Codesandbox with a trackpad a lot more enjoyable.

**Comment by CompuIves** [comment]
Which browser do you experience it in? We actually have the preventScroll you mentioned running right now. https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/pages/Sandbox/Editor/Content/prevent-gesture-scroll.js

**Comment by kube** [comment]
A simple solution today would be to apply `preventGestureScroll` to left panel too.

**Comment by nickbreaton** [comment]
I have experienced this on Chrome on macOS High Sierra, but not on Chrome on Mojave. Maybe a bug with Chrome on older versions of macOS is causing it? I will update if I find anything else.

**Comment by lbogdan** [comment]
@nickbreaton Any updates on this?

**Comment by nickbreaton** [comment]
@lbogdan No I don't currently have a convenient way to test on high sierra. I think this is edge case and may become less relevant overtime as people upgrade their OS, unless of course this is more widespread than I originally thought.

**Comment by ffxsam** [comment]
I'm on Catalina on a MacBook Pro (2018), and can hardly scroll horizontally at all in the code editor. It's quite problematic.
