### ISSUE TITLE
Manage project dependencies

### ISSUE THREAD

**Issue by ritz078** [codesandbox/codesandbox-client#122]
Followup to #121 

When I create multiple demos, sometimes I would like to upgrade the dependencies in all of them at once. Doing it manually in each will take a lot of time. It will be great if somehow I can update the dependencies of all demos in a project at once.

**Comment by lbogdan** [comment]
Hey @ritz078 ,

Thanks for your feature request. Do you have a proposal of how that should work?

**Comment by Achilles1515** [comment]
> Hey @ritz078 ,
> 
> Thanks for your feature request! Do you have a proposal of how should that work?

Something like how StackBlitz does it would be nice.

https://stackblitz.com/angular/yjjqrobmbdaj?file=app%2Fautocomplete-overview-example.ts

Hover over the "Dependencies" header on the left and a "refresh" icon appears to update all the dependencies to their latest version.

**Comment by Saeris** [comment]
Adding this to our public backlog. Please refer here for the current status of this request:

https://www.notion.so/Add-Upgrade-All-button-to-Dependencies-list-83955c29881f45a68fe8b28da0134009
