### ISSUE TITLE
@import rule

### ISSUE THREAD

**Issue by rajjejosefsson** [codesandbox/codesandbox-client#1231]
# 🐛 bug report

## Description of the problem
using CSS @import Rule doesn't import styles.

## How has this issue affected you? What are you trying to accomplish?

Trying to use the @import rule it in codesandbox without any success. Have tried to download it an run it, and works as expected in that case.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1540393420-ddc2da4 
| Browser | Chrome & Firefox
| Operating System | OSX Mojave

**Comment by cardiv** [comment]
Not tested this myself, but I think you will need to use [css-loader](https://github.com/webpack-contrib/css-loader) for React/Webpack.

And for that, you will need a server/container sandbox that [supports Webpack config](https://github.com/CompuIves/codesandbox-client/issues/1236#issuecomment-433174055).

**Comment by lbogdan** [comment]
Looks like we don't support `@import`ing local files, marking this as bug.
