### ISSUE TITLE
Cannot Import My Repository

### ISSUE THREAD

**Issue by gamedevsam** [codesandbox/codesandbox-client#1241]
# 🐛 bug report

## Description of the problem
When attempting to load the github repository the application freezes and never completes: https://github.com/gamedevsam/react-simple-chatbot

## How has this issue affected you? What are you trying to accomplish?
I'm trying to test out this sandbox with a pure static site (github pages).

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Google Chrome Version 70.0.3538.67 (Official Build) (64-bit) | 
| Windows 10 |

**Comment by lbogdan** [comment]
Hey @gamedevsam ,

Seems like your project is much better suited to using a [server sandbox](https://medium.com/@compuives/codesandbox-containers-out-of-beta-improvements-be79679df4cc). I forked your repo and made it into a server sandbox by adding the `sandbox.config.json` file, you can check it here: https://codesandbox.io/s/github/lbogdan/react-simple-chatbot . It doesn't show anything, though (also tested it locally, nothing shows, either).

Does this solves your issue, and if you, could you please close this? Thanks!

**Comment by SaraVieira** [comment]
Closed on lack of reply, please re open if the issue persist :)
