### ISSUE TITLE
Truly vanilla project template

### ISSUE THREAD

**Issue by justinfagnani** [codesandbox/codesandbox-client#1246]
# 🌈 Feature

I'd like to have a project that's not compiled at all, nor bundled with Parcel. This is necessary for demo'ing native JS modules and Custom Elements without any polyfills.

**Comment by CompuIves** [comment]
This one is coming in today as the `static` template!

There will be no bundling at all, we will just host the files of the sandbox.

**Comment by justinfagnani** [comment]
Awesome!

One additional request though... We still need module resolution, like unpkg.com does with the ?module query parameter. Right not that's done in the bundler I presume, instead of a Babel transform.

**Comment by justinfagnani** [comment]
To clarify the need here. Lots of modules are published to npm as nearly web-compatible, with the exception of the import specifier. They'll use "bare specifiers", like `import * as redux from 'redux';`. The specifiers need to be rewritten at either `npm install` time or serving time (what we do in `polymer serve`).

**Comment by CompuIves** [comment]
Hmm, in the current version we completely strip the bundler away in this case, including our package resolving/transpiling etc. 

I'll deploy it as it is now and we can look into making the use case work!

**Comment by lbogdan** [comment]
As @jhony1104 suggested in #1634 , we could take a look at [@pika/web](https://www.npmjs.com/package/@pika/web) .

**Comment by justinfagnani** [comment]
I'd rather have a truly static project, rather than doing the transforms that Pika does. Pika does some bundling for node_modules and is pretty opinionated about it. That might not be suitable for all projects. Either rewriting specifiers, or just relying on import maps to roll out, would be a much simpler and less opinionated transform.

**Comment by justinfagnani** [comment]
This would still be nice to have.

**Comment by SaraVieira** [comment]
Hey!

I don't quite understand what you mean, we have a truly vanilla template so the issue title is misleading, if you would like another type of template please create a new issue

**Comment by justinfagnani** [comment]
@SaraVieira the current vanilla template uses a bundler, which interferes with some modern native web APIs. The static template doesn't allow you to install any npm dependencies. To use dynamic `import()`, `import.meta.url`, custom elements, upcoming features like import maps or CSS modules, we need a project type that's not bundled, but still allows for dependencies.

**Comment by SaraVieira** [comment]
Then it is bundled since you need to install dependencies

You can always fetch them from unpkg instead of installing them since you don't want a bundler

**Comment by justinfagnani** [comment]
> Then it is bundled since you need to install dependencies

This is the problem. Bundlers mess with the semantics of native features. You don't need bundler to have dependencies. Native modules work fine. I would say that the current "vanilla" template is really a "Parcel" template - which is why I say I'd like to have an actually vanilla template.

I guess we can take this to https://github.com/codesandbox/codesandbox-client/issues/1757 and see if "static" can be the vanilla template?

**Comment by SaraVieira** [comment]
Yeah that's what I mean, I think that issue that is already open makes more sense for your case

**Comment by SaraVieira** [comment]
Closing this as it was moved to another issue
