### ISSUE TITLE
Listing sandboxes linked to the users Github on their Dashboard

### ISSUE THREAD

**Issue by dobromir-hristov** [codesandbox/codesandbox-client#1247]
# 🌈 Feature

This is a proposal for listing Github imported Sandboxes on the Dashboard. 

A user should be able to see all the Sandboxes that are linked to/created from their linked Github account. 

Once a sandbox is **imported from** or **exported to** a user's Github account, it can be listed as "Readonly" on the user's dashboard, noting it can only be "Forked". This would allow for easier tracking of Sandboxes.

Currently once you **export/import** a sandbox **from/to** your Github acc, its impossible to find said sandbox.

**Usage example**

1. You start working on a Sandbox and after some time, decide its good to export it as repo, to better track your progress.
2. You get redirected to a new sandbox that looks somewhat different. You continue work.
3. On editing, you create a fork of that new Sandbox. At that point, the only way to see the Github sandbox is to visit the one url on the just created Repository.

At this point you are left with:

1. The original Sandbox you had, that is bound to get outdated. Also it states nowhere that it was exported to a repo, 
2. The floating Github sandbox, that technically will auto-deploy it self on each commit, 
3. The Forked one from the changes  on the Guthub one,

I am not sure how much of this is possible, nor if I managed to write it out properly, but I wanted to explain a valid UX issue, that even I have clashed with a few times.

**Comment by CompuIves** [comment]
Thanks for this elaborate feature request, I completely agree with all your points and we should make it a priority.

I like the idea of read-only sandboxes in the dashboard, we should probably show this explicitly in the view to not confuse users.

**Comment by dobromir-hristov** [comment]
It should be noted that a sandbox is read-only, yes, be it by a distinct styling feature on the list item or by listing them separate in general. 

Can I help in any way with this? I realize its mostly Api related changes and a minor styling one probably.

**Comment by vivek12345** [comment]
@dobromir-hristov Regarding
Q) The original Sandbox you had, that is bound to get outdated. Also it states nowhere that it was exported to a repo
On the left sidebar, when you click on github icon, you can that a particular sandbox belong's to a repo.

Q) The floating Github sandbox, that technically will auto-deploy it self on each commit
Will the github linked codesandbox auto-deploy if you make any commit to the master repo? Sorry I am not very well aware of this part. can you elaborate here?

Q) The Forked one from the changes on the Github one
This is correct right? As you mentioned once I export a sandbox to github, it should become read-only and the only way to edit it should be creating a fork which would be a new sandbox altogether.

**Comment by dobromir-hristov** [comment]
@vivek12345 Hi. Thanks for taking your time.
1. Not entirely true. https://codesandbox.io/s/j2njmmmqr3 this one was exported here https://github.com/dobromir-hristov/vue-testing-challenge and now I if I dont forget, I can visit it here https://codesandbox.io/s/github/dobromir-hristov/vue-testing-challenge. Here now I have the "link" but thats because github is the "owner" of that sandbox, from what I gather.
2. As long as it is not "forked" it should auto deploy now. Thats the idea of having it attached to a repo.
3. Currently yes. If you edit it, it creates a new sandbox, forking the GH sandbox. If you save changes, they will be suggested as a commit message to be pushed to the Repo. From then on the original, "linked to GH" sandbox will update again, leaving all other forks outdated.

**Comment by vivek12345** [comment]
Thanks for answering @dobromir-hristov.
Regarding the first point of github link, I can see the repo name that the sandbox is linked to

<img width="1440" alt="screenshot 2018-11-06 at 8 29 39 pm" src="https://user-images.githubusercontent.com/4931048/48072619-f3a09700-e202-11e8-8fe7-98b718a72d8e.png">

Am I missing to understand something here?

**Comment by dobromir-hristov** [comment]
https://gyazo.com/c8f59a4aa2cda58d76305acb193959de I dont see it on mine 😞

**Comment by vivek12345** [comment]
So here are the steps that I did,
1) Created a sandbox 
2) exported in to github using that sidebar github link
3) sandbox gets forked into a github sort of url like this `https://codesandbox.io/s/github/vivek12345/react-hooks-demo`
4) I edit it and it get's forked into a new sandbox but still maintains the github repo name from which it was forked.

**Comment by dobromir-hristov** [comment]
Oh yeah. I was referring to the original Sandbox, from which I created the Github one :) The "Mother" one. Forks are connected to the repo, otherwise you wont be able to commit.

**Comment by vivek12345** [comment]
Ahh, that makes sense. Now I understand. That makes me think, should code sandbox retain the mother one if someone exports it to a github repo and creates a fork of it when trying to edit it.

**Comment by vivek12345** [comment]
@CompuIves In debugging, so far what I have seen is when I open the sandbox editor, the xhr call gives me a json response which has  forked_from_sandbox as one of the key.

Now I was thinking that on the dashboard, when we do a graphql query for recent sandbox, can we get this detail too?

For that I am struggling to find out the graphql schema, but the docs ain't loading.

Any help on this?

On a side note, whenever you get time I have sent you a DM on twitter around the same issue?

**Comment by SaraVieira** [comment]
Better late than ever but this a thing now with the new dashboard and the "Repositories tab":


![CleanShot 2020-09-02 at 14 48 07](https://user-images.githubusercontent.com/1051509/91982990-5560b800-ed2b-11ea-9a31-7a4e6c91b4c5.png)
