### ISSUE TITLE
Fix emoji encoding in uploaded files

### ISSUE THREAD

**Issue by mcanas** [codesandbox/codesandbox-client#1248]
# 🐛 bug report

## Description of the problem

Emoji's or special characters in uploaded JSON files not rendering correctly.

## How has this issue affected you? What are you trying to accomplish?

I'm trying to upload a JSON file that contains emoji's or special characters, and it's not rendering those emoji's or characters correctly.

###  Link to sandbox: [link](https://codesandbox.io/s/38mwp9qm81) (optional)

Take a look at the uploaded `src/test.json` file, the value of "foo" should be "😀". Seems like the encoding issue occurs during upload.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1540564451-5ce2475
| Browser | Chrome 69.0.3497.100
| Operating System | macOS High Sierra Version 10.13.6

**Comment by lbogdan** [comment]
Can confirm this still happens.

**Comment by karlhorky** [comment]
This doesn't just affect emoji - also characters like box drawing characters and non-Basic Latin multilingual characters are also affected:

https://codesandbox.io/s/xenodochial-cookies-igb34

<img width="241" alt="Screen Shot 2019-05-27 at 15 21 45" src="https://user-images.githubusercontent.com/1935696/58422660-6e43dd80-8093-11e9-8d63-a15d93b9c904.png">

<img width="330" alt="Screen Shot 2019-05-27 at 15 21 37" src="https://user-images.githubusercontent.com/1935696/58422665-73089180-8093-11e9-895d-237f79f0992f.png">

**Comment by Eliav2** [comment]
also have this problem when uploading a project which contains Hebrew.
any why solving this issue?

**Comment by karlhorky** [comment]
Not stale, still an open problem.

Just reproduced again with an upload to the previous sandbox:

https://codesandbox.io/s/xenodochial-cookies-igb34?file=/src/test.js
