### ISSUE TITLE
Parcel Absolute Path Module Resolution

### ISSUE THREAD

**Issue by jthegedus** [codesandbox/codesandbox-client#1249]
# 🐛 bug report

## Description of the problem

Parcel supports using Absolute Paths for module resolution - https://parceljs.org/module_resolution.html#absolute-paths which does not appear to be working - https://codesandbox.io/s/github/jthegedus/examples/tree/master/flow-with-absolute-module-resolution

Similarly, Parcel's Tilde path module resolution does also not work - https://codesandbox.io/s/github/jthegedus/examples/tree/master/typescript-react-with-tilde-module-resolution

## How has this issue affected you? What are you trying to accomplish?

I was planning on PRing Parcel's examples into the Docs using Codesandbox on the docs site (maintainer approval permitting), but cannot do so until the examples work on Codesandbox. I recently refactored all examples to use Absolute module resolution as most devs prefer this over relative paths. 

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1540564451-5ce2475
| Browser | Chrome Version 70.0.3538.77 (Official Build) (64-bit)
| Operating System | Ubuntu 18.10

**Comment by christiankaindl** [comment]
@jthegedus I had the same issue. Missing tilde support breaks my app on CSB; it works locally with Parcel.

As a workaround, you can add an alias to your `package.json`:
``` 
{
...,
"alias": {
    "~": "/src"
  }
}
```

After that tilde imports, e.g. `import placeImg from '~/assets/profile.svg';`, worked for me :fire:

Note: The Parcel docs don't recommend overriding the built in aliases with your own, but until it's fixed it seems like the only solution :)
_Relevant Parcel doc:_ https://parceljs.org/module_resolution.html#aliases
