### ISSUE TITLE
"Illegal value for token color" when using custom VSCode theme

### ISSUE THREAD

**Issue by Bassetts** [codesandbox/codesandbox-client#1262]
# 🐛 bug report

## Description of the problem
When generating a color theme using the `Generate Color Theme From Custom Settings` in VSCode and pasting the resulting output into the `Custom VSCode Theme` setting I get the error `Problem initializing template in editor: Illegal value for token color:`.

I am using the [Material theme](https://github.com/equinusocio/vsc-material-theme ) in VS Code.

The color theme that VSCode generates: https://gist.github.com/Bassetts/f824270f99d4fd205744a4aa213fe851

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3164568/47851808-a4f19800-ddd1-11e8-830d-12abf66ccadb.png">

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1541005726-0dba21e
| Browser | Firefox Nightly 65.0a1 (2018-11-01) (64-bit)
| Operating System | macOS Mojave 10.14.1
| Visual Studio Code | 1.29.0-insider

**Comment by CompuIves** [comment]
Found the issue here, VSCode has trouble handling the empty values (`""`).

Until we deploy a fix, a workaround would be to find all `""` values and delete those lines (I think there are 3).

**Comment by HaloWang** [comment]
Got same error when using VSCode, Jupyter Notebook and color theme Atom One Dark:
![9CE29D01005165B4F70B726766177F32](https://user-images.githubusercontent.com/7344724/58779358-3e06bc80-8608-11e9-99cc-d7f546ba4302.jpg)

VSCode default color theme is OK

**Comment by aht007** [comment]
![image](https://user-images.githubusercontent.com/46006573/58807916-3f4ae000-862e-11e9-88fe-da2e9992a322.png)
Same error using Atom one dark theme

**Comment by meandmymind** [comment]
@aht007 Same here with Material Theme Darker. Shouldn't we move this issue to main VSCode repository?
