### ISSUE TITLE
Global definitions in ESLint.

### ISSUE THREAD

**Issue by rhernandog** [codesandbox/codesandbox-client#127]
Hi,

I normally use GSAP in all of my projects which uses some classes (TweenLite/Max, TimelineLite/Max, Draggable, etc) which are not defined all the time. For reasons out of the scope of this particular issue I normally work with GSAP from the CDN links.

Is there a way to config within the Codesanbox editor global elements to avoid getting those errors displayed?

Thanks in advance,
Rodrigo.

**Comment by CompuIves** [comment]
This shouldn't be too hard to add. We could add an `Eslint` config section like `Prettier Config` and include the option to add globals like we do with dependency adding.

**Comment by chakrihacker** [comment]
I am working on this

**Comment by smiller171** [comment]
Could you not respect the eslint config files in the file tree?

**Comment by lbogdan** [comment]
Hey @chakrihacker , I saw that you closed the PR, are you still working on this?

**Comment by chakrihacker** [comment]
Nope, you can take it
