### ISSUE TITLE
let's add vega embed code project sandbox template

### ISSUE THREAD

**Issue by RandomFractals** [codesandbox/codesandbox-client#1274]
# 🌈 Feature
After a short chat with Dominik Moritz on VegaJS Slack (https://communityinviter.com/apps/vega-js/join) about your codesandbox.io and a quick recon of sandbox templates in code looking at templates: 

https://github.com/CompuIves/codesandbox-client/tree/master/packages/common/src/templates

we'd like to push a pre-flight PR for you to add vega-embed to your JS project teamplates to show up in this Templates list for all the JS dataViz Vega fans out there: https://codesandbox.io/search?query=vega

Should I just create a vega-embed-template PR with vega-embed.js in common/templatest for you to review and accept to make it prod?

Please advise on next/better ways to do it.

See https://github.com/vega/vega-embed for more info on that lib.

**Comment by domoritz** [comment]
I'm happy to provide support for this feature from the Vega and Vega-Lite side.

**Comment by RandomFractals** [comment]
@SaraVieira see this repo and let me know what else we need to do to make this happen:

https://github.com/RandomFractals/vega-template

cc @domoritz & @CompuIves

**Comment by RandomFractals** [comment]
also this vega-template sandbox I started from parceljs, but could not quite make it work on your platform. so, I resorted to simple vega-template repo that still needs some work for a proper vanilla vega proj. template, but at least it works local. Not sure what's up with this error from your sandbox:

https://codesandbox.io/s/y3xj8p2z81

something nodejs || babel config related?

**Comment by RandomFractals** [comment]
just a quick update on this: @CompuIves helped me resolve some sandbox quirks.

Here is a working vega-template sandbox for now:

https://codesandbox.io/s/6lzn1398wr

I'll look into creating templates on codesandbox for the final PR to make it legit on your stack soon

**Comment by RandomFractals** [comment]
was a good idea but I have not looked at any code sandboxes in months & never got more info on how to add 3rd party ext's to this plat. closing it :)
