### ISSUE TITLE
Bug: drag-and-drop hangs sometimes

### ISSUE THREAD

**Issue by manniL** [codesandbox/codesandbox-client#1282]
# 🐛 bug report

![drag-drop-fail-2](https://user-images.githubusercontent.com/640208/48088885-0c0cb380-e1fb-11e8-9782-058632f8984b.gif)

## Description of the problem

When dragging a CSB in your dashboard, it sometimes gets stuck on the "My Sandboxes" folder.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | latest?
| Browser | Firefox 63 (64 bit)
| Operating System | Ubuntu 18.04

**Comment by arthurdenner** [comment]
@manniL, could you check if this still happening? I tried to reproduce, but I couldn't. If it's not happening anymore, could you close the issue please?

**Comment by manniL** [comment]
Nope, looks fixed :+1: 	
Thanks for investigating @arthurdenner
