### ISSUE TITLE
bug: can't move CSB from subfolder back to top level

### ISSUE THREAD

**Issue by manniL** [codesandbox/codesandbox-client#1283]
# 🐛 bug report

![drag-back-to-top](https://user-images.githubusercontent.com/640208/48089029-686fd300-e1fb-11e8-8dd8-d586fda7ab9f.gif)

## Description of the problem

When I want to move a CodeSandbox from a sub-folder to the top level again, it does not move the Sandbox back and keeps it in the subfolder. Moving to other folders does work

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | latest?
| Browser | Firefox 63 (64 bit)
| Operating System | Ubuntu 18.04

**Comment by siddharthkp** [comment]
Hey! This is fixed in the new dashboard :)

Please reply back if it doesn't work for you and I'll open the issue back
