### ISSUE TITLE
bug: moving a sandbox to subfolder triggers visual glitch

### ISSUE THREAD

**Issue by manniL** [codesandbox/codesandbox-client#1284]
# 🐛 bug report

![folder-move](https://user-images.githubusercontent.com/640208/48089147-abca4180-e1fb-11e8-9a93-b2172708a7c0.gif)

## Description of the problem

When I move a Sandbox to a subfolder, it is moved (on the back end) but the 2nd sandbox in the row disappears.

The GIF should help to identify the problem clearly.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | latest?
| Browser | Firefox 63 (64 bit)
| Operating System | Ubuntu 18.04

**Comment by siddharthkp** [comment]
Hey! This is fixed in the new dashboard :)

Please reply back if it doesn't work for you and I'll open the issue back
