### ISSUE TITLE
Angular Template - test runner fails due to zone.js sourcemap missing  freezes environment

### ISSUE THREAD

**Issue by puddlecoded** [codesandbox/codesandbox-client#1285]
# 🐛 Environment becomes unusable after adding a failing spec to Angular project

- [ ] Given I've created a brand new Angular template app
- [ ] When I add app.component.spec.ts with the following

```
describe("app", () => {
  it("passing", () => {
    expect(2 + 2).toEqual(4);
  });

  it("make me fail", () => {
   expect(2 + 2).toEqual(4); // change this to 5
  });
  
`});`

```
 
- [ ] If I have the spec file opened in editor
- [ ] I modify the spec file so I have a failing spec

Then 
- [ ] I see an error about zone.js sourcemap missing
```
Unhandled Rejection (Error)
Cannot find a source map directive for https://8l0p79xmr0.codesandbox.io/node_modules/zone.js/dist/zone.js.
```
- [ ] The error continues to be added to Problems /Console
- [ ] Eventually the whole page becomes unresponsive (out of stack space??)

## Things I've tried (no luck)

 - [ ]  Adding specs to existing angular sandboxes and keep receiving same error. [checked if angular version mattered]
 - [ ] Installed karma and jasmine as dependencies [ mimic typical angular-cli setup] 

## Possible solution
 Modify the builder / test runner watcher  to ignore node_modules

## Sandbox URL
https://codesandbox.io/s/8l0p79xmr0

## Screenshot
![screenshot at 2018-11-06 14-31-13](https://user-images.githubusercontent.com/12360388/48092512-7ceba580-e1d2-11e8-8b7c-1bc85f6cea04.png)

**Comment by izikenmichael** [comment]
I am having a similar issue with my angular 7 app. When i import from GitHub repo.
[Angular 7 not working on codesandbox](https://github.com/izikenmichael/starwars-movies/issues/1
)
