### ISSUE TITLE
Unexpected behaviour regarding logout and automatically created forks.

### ISSUE THREAD

**Issue by remmythical** [codesandbox/codesandbox-client#1292]
# 🐛 bug report

## Description of the problem
i just ran into the case that i was working on my code and found out that i'm suddenly in a different sandbox id than before, the app showed me that i forked my old one.
I was confused by this, so i went to the link of the old version and pasted my changes there only to land in another fork.

The issue was that i was (automatically) logged out, so the sandbox didn't see me as the owner and automatically created a fork once i started to edit.
## How has this issue affected you? What are you trying to accomplish?
It's not a major problem since the forked versions still work and all, but i'd like to have some feedback from the UI here, because i only cought by chance that i was logged out, after creating two unneeded forks. It would be nice to not produce the clutter of countless forks of your own same project, just because you got automtically logged out after a while.

(I was logged in via github, if that matters)

### Your Environment
| Software         | Name/Version|
| -------------- | ---------- |
| Сodesandbox  | PROD-1541606022-b5eb8b5 |
| Browser | Chrome 70.0 |
| Operating System | macOS Mojave |

**Comment by remhume** [comment]
Oh there is apparently more to this issue?

Even after logging back in with the same account i'm not able to save the project without creating a new fork now? :(
Not sure what's happening there.

Link to (the first) sandbox: https://codesandbox.io/s/vjmnjlxvl
