### ISSUE TITLE
More options in the dashboard menu

### ISSUE THREAD

**Issue by johncokos** [codesandbox/codesandbox-client#1301]
# 🌈 Feature

In the drop down menu, add a clone/fork option

![screen shot 2018-11-15 at 11 57 04 am](https://user-images.githubusercontent.com/1766332/48578101-9de88080-e8cd-11e8-9f91-5c3cde55ccad.png)

- `Clone Sandbox` Menu Item -- Creates a fork of the sandbox in the folder you're currently in, and let me rename it immediately.

As an instructor, a key part of my workflow is to create assignments that build on one another in a stepped process.  The workflow of opening a sandbox, clicking fork, then going in and renaming it, and then going back to the dashboard to drag it where it needs to be is cumbersome.

**Comment by SaraVieira** [comment]
Hey

Better late than ever but we do have that option now and you can fork a sandbox from the dashboard 🚀
