### ISSUE TITLE
Could not find module in path: 'tslib' relative to '/src/App.tsx'

### ISSUE THREAD

**Issue by nick-vanvynckt** [codesandbox/codesandbox-client#1302]
# 🐛 bug report
## Description of the problem
When importing an existing React project into codesandbox, I get this strange compiler error. Can you take a look at this? Don't really know what I'm doing wrong here..
## How has this issue affected you? What are you trying to accomplish?
See above.
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Browser | Chrome |
| Operating System | Mac OSX |

**Comment by SaraVieira** [comment]
That+s weird because importing tslib fixes it 🤔

**Comment by kleva-j** [comment]
A simple fix would be to add this code snippet to the bottom of your `package.json` file.
```
"peerDependencies": {
  "typescript": "3.6.4",
  "tslib": "1.10.0"
}
```

**Comment by SaraVieira** [comment]
Hey!

I can't really see this error anymore and we don't use create-react-app typescript anymore since CRA now supports TS out of the box so I will close and feel free to reopen if you encounter it again
