### ISSUE TITLE
Bug: VS Code settings inaccessible in linux with Gnome (Fedora/Ubuntu)

### ISSUE THREAD

**Issue by rayfoss** [codesandbox/codesandbox-client#1304]
# 🐛 bug report

## Description of the problem
The shortcut for accessing the VS Code settings should be `Ctrl+Backtick` on Windows/Linux, on Mac it's `Cmd+Backtick`. 

## How has this issue affected you? What are you trying to accomplish?
I'm unable to configure VS Code or disable some of it's less useful features.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1541799550-1e6ec17
| Browser | Chrome 69
| Operating System | Fedora 29 and Ubuntu 18.6

Workaround... use a UA Spoofer to pretend to be running DOS

**Comment by andrasbacsai** [comment]
Hey, I'm using Ubuntu 20.04 and my shortcut to VS Code settings is `ctrl+,` in codesandbox & in standalone VS Code on my computer.

It's the [default](https://code.visualstudio.com/docs/getstarted/keybindings) binding:
![image](https://user-images.githubusercontent.com/5845193/91985023-a1f8c300-ed2c-11ea-9a0f-856a0745b118.png)

Are you sure it should be `ctrl+backtick`?
