### ISSUE TITLE
Angular 7 project does not open on Codesandbox. Continuously throws error to browser console 

### ISSUE THREAD

**Issue by izikenmichael** [codesandbox/codesandbox-client#1305]
# 🐛 bug report

## Description of the problem
My Angular 7 app can not open on codesandbox due to continuous error on console.
## How has this issue affected you? What are you trying to accomplish?
I want to import my angular 7 app to codesandbox so i can share for a job interview task. 
###  Link to sandbox: [link](
https://codesandbox.io/s/github/izikenmichael/starwars-movies/tree/master/) (optional)
### Your Environment
| Software         | Angular/7|
| ---------------- | ---------- |
| Сodesandbox  | 
| Chrome | 
| Windows 10 |

###Screens
***GitHub Import***
![codesandbox io_s_github](https://user-images.githubusercontent.com/13496643/48660038-9bb42c80-ea5b-11e8-8d29-517fbd534e30.png)

**Error on Console***
![starwars-movies_console error_after_github_import](https://user-images.githubusercontent.com/13496643/48660040-b25a8380-ea5b-11e8-9404-662243f4768f.png)

***Error on Browser***
![error on browser](https://user-images.githubusercontent.com/13496643/48660042-cbfbcb00-ea5b-11e8-8f9c-7840aaa2c756.png)

**Comment by garethx** [comment]
This looks to have been resolved as I'm unable to reproduce, re-open if you're still seeing this issue.
