### ISSUE TITLE
Updating Sandbox via api/cli?

### ISSUE THREAD

**Issue by OpherV** [codesandbox/codesandbox-client#1311]
# ❔ Question

I'm trying to assess how to use codesandbox for examples on the official documentation site of Eko: http://developer.helloeko.com

I want our examples to auto-update whenever we change APIs, but I couldn't find a way to update existing codesandboxes, only to create new ones. I'd like to avoid cluttering our account with hundreds of unused boxes. 

Is there a way to update boxes via API/CLI, rather than create new ones?

I saw that examples that run from Github are auto-updated, but didn't see a way to create those via the API?

**Comment by OpherV** [comment]
Maybe a mix of the two? Have an authenticated Define API, which creates sandboxes tied to the account (and use the same authenticated token to update them). That way we have a list of example sandboxes on our account which our support staff can link the URLs of in tickets.

Also it would be nice to be able to have an API endpoint that creates sandboxes from a Github repo or a zip file url (for authenticated, patron users)

**Comment by zxti** [comment]
Hello, just wanted to see if anything has changed in the past year.

I'm specifically interested in a use case similar to the [pagedraw stackblitz integration](https://pagedraw.io/fiddles/0ziyVbuEDB_s), where on page load, one creates a new sandbox, and then can continue to update various files in that sandbox from the hosting app.

Opening this up would encourage deep integration and adoption of CSB as a platform.  Thanks.
