### ISSUE TITLE
Honour Jest configuration in package.json

### ISSUE THREAD

**Issue by madflow** [codesandbox/codesandbox-client#1317]
# 🌈 Feature

*  What is this feature?

Jest allows configuration entries like: 

```
  "jest": {
    "testURL": "http://localhost",
    "setupTestFrameworkScriptFile": "<rootDir>/test/setup.js",
    "transform": {
      "^.+\\.(js|jsx)$": "babel-jest",
      "^(?!.*\\.(js|jsx|json)$)": "<rootDir>/test/fileTransform.js"
    }
  }
```

in the package.json file.

These configuration entries are ignored in codesandbox - leading to passing tests in a local copy - and failing tests in codesandbox.

*  How the feature should work? 

It will read and process the "jest" property from the package.json file.

* You have examples or an idea how it can be implemented?

This seems to be a server issue?

**Comment by SaraVieira** [comment]
Hey !

Can you provide a link to the sandbox?

Thanks :D

**Comment by madflow** [comment]
@SaraVieira 

https://codesandbox.io/s/3r0npo7r61

The jest configuration is ignored by codesandbox. When I change the path the the setup file in the `jest` entry in package.json - the tests still pass (they shouldn't).

Thanks!

**Comment by MichaelDeBoey** [comment]
Similar to #1980, but for Jest
