### ISSUE TITLE
Sublime Text Theme Port?

### ISSUE THREAD

**Issue by zpreston123** [codesandbox/codesandbox-client#1318]
# ❔ Question
Any plans on porting the default CodeSandbox theme to Sublime Text?

**Comment by SaraVieira** [comment]
Hey!

It's just CSS for now, if you know how to do themes in Sublimes text themes we can hack on this

**Comment by SaraVieira** [comment]
Here are the colors btw: https://github.com/CompuIves/codesandbox-client/blob/master/packages/common/themes/codesandbox.json

**Comment by zpreston123** [comment]
I don't know how to develop Sublime Text themes, but the format is pretty similar to codesandbox.json file.  See https://www.sublimetext.com/docs/3/color_schemes.html.

**Comment by SaraVieira** [comment]
If you wanna do it then you can as you please

I don't work with sublime but can help if you want :)

**Comment by zpreston123** [comment]
Here is a Gist for the theme:  https://gist.github.com/zpreston123/9e89cc3d28ffb2c8971d7a97ec3e759f.

It's not perfect, but hope it helps as a starting point.
