### ISSUE TITLE
Download CodeSandbox via wget or download URL

### ISSUE THREAD

**Issue by manniL** [codesandbox/codesandbox-client#1320]
# 🌈 Feature

Currently a Codesandbox has no dedicated download link. That means, downloading a CSB via console/terminal is practically impossible.

It'd be great if you could simply use `wget https://codesandbox.io/s/SANDBOX_ID` to download the CSB.

**Comment by SaraVieira** [comment]
That's a pretty good idea, maybe always append a /download

**Comment by iqno** [comment]
Has anything like this been added since the opening of the request? I tried a https://codesandbox.io/s/SANDBOX_ID/download request but its just a 404.

**Comment by manniL** [comment]
Unstale 🤚

**Comment by christianalfoni** [comment]
Hi there!

So this is certainly a good suggestion! I can confirm that I have put it into our backlog as a project, but I am not able to tell you when it will be prioritized. 

I will close this issue for now, but it is referenced in the project documents. That means we will reopen the issue when the project starts. 

Thanks again for the suggestion! 😄
