### ISSUE TITLE
Can you disconnect a repo from git?

### ISSUE THREAD

**Issue by johncokos** [codesandbox/codesandbox-client#1321]
# ❔ Question
I've got a few sandboxes that I connected to git, and I'd like to undo that. 

Why?

When someone forks your sandbox, it maintains that git connection, and I don't want them committing changes and PRs, I'd like my students to just get a copy of the sandbox for their own use.

**Comment by SergeyVolynkin** [comment]
This is really confusing.

**Comment by leonheess** [comment]
1. Open terminal
2. `rm -rf .git`
