### ISSUE TITLE
feat: improve error message when importing github repo

### ISSUE THREAD

**Issue by manniL** [codesandbox/codesandbox-client#1327]
# 🌈 Feature

Hey all! Just tried to import my GH repo and a cryptic error occurred

![image](https://user-images.githubusercontent.com/640208/48921478-f9031000-ee97-11e8-85ae-df90f0b6961d.png)

After a while, I realized that my `package.json` had a trailing comma and was invalid ([ref](https://github.com/manniL/nuxt-decouple-and-organize-api-calls/commit/caf95088596f1d6387d900e1883ea816d9a56886)).

Unfortunately, the error message only partly helps with recognizing this error.

:heavy_check_mark: Invalid JSON
:x: Position 315 (if you put all on one line maybe?)
:x: Reference to `package.json`

I'd love to see a more detailed error message, however, this is a less common error I think :man_shrugging:

**Comment by SaraVieira** [comment]
All the messages around importing and committing from Github repos need to be improved :(

**Comment by SaraVieira** [comment]
Better late than ever but we do have better error messages now and we also have waaay less error messages because a lot has been fixed 🎉
