### ISSUE TITLE
Cloudfront dependencies URL MaxSizeAllowed

### ISSUE THREAD

**Issue by samdenty** [codesandbox/codesandbox-client#1330]
# 🐛 bug report

## Description of the problem
If the combined length of all the package names along with versions exceed 1024 chars, cloudfront responds with 400 Bad Request.

## How has this issue affected you? What are you trying to accomplish?
Loading up a repo with quite a few dependencies

###  Link: [link](https://d1jyvh0kxilfa7.cloudfront.net/v1/combinations/mdx-js-loader@0.15.7%2Bmdx-js-mdx@0.15.7%2Bajv@6.5.5%2Bbabel-core@6.26.3%2Bbabel-jest@23.6.0%2Bbabel-loader@7.1.5%2Bbabel-polyfill@6.26.0%2Bbabel-runtime@6.26.0%2Bbody-parser@1.18.3%2Bclassnames@2.2.6%2Bclean-webpack-plugin@0.1.19%2Bconcurrently@3.6.1%2Bconnect-ensure-login@0.1.1%2Bconsole-feed@2.8.5%2Bcopy-webpack-plugin@4.6.0%2Bcss-loader@1.0.1%2Bdeep-equal@1.0.1%2Bdotenv@6.1.0%2Benzyme@3.7.0%2Benzyme-adapter-react-16@1.7.0%2Bexpress@4.16.4%2Bexpress-session@1.15.6%2Bfile-loader@1.1.11%2Bhbs@4.0.1%2Bhtml-loader@0.5.5%2Bhtml-webpack-plugin@3.2.0%2Bhttp-errors@1.7.1%2Bimmutability-helper@2.8.1%2Bjest@23.6.0%2Bmarkdown-loader@3.0.0%2Bmonaco-editor@0.14.3%2Bmonaco-editor-webpack-plugin@1.7.0%2Bmorgan@1.9.1%2Bnodemon@1.18.6%2Bpassport@0.4.0%2Bpassport-github@1.1.0%2Bpg-promise@8.5.2%2Bprettier@1.15.2%2Bprop-types@15.6.2%2Breact@16.6.3%2Breact-dom@16.6.3%2Breact-icons@3.2.2%2Breact-iframe@1.3.3%2Breact-monaco-editor@0.18.0%2Breact-redux@5.1.1%2Breact-remarkable@1.1.3%2Breact-router-dom@4.3.1%2Breact-test-renderer@16.6.3%2Bredux@4.0.1%2Bredux-thunk@2.3.0%2Bstyle-loader@0.22.1%2Burl-loader@1.1.2%2Bwebpack@4.26.1%2Bwebpack-cli@3.1.2%2Bwhatwg-fetch@2.0.4.json)

**Comment by samdenty** [comment]
I was opening a large repo via the github url, so it defaulted to non-sandboxed. Both the above would be ideal.

Maybe if the project throws errors / has a lot of dependencies, loading it in a server sandbox automatically would be useful?

**Comment by lbogdan** [comment]
@samdenty Can you maybe point us to the repo you were trying to open?

We'll soon add both the possibility of changing a client sandbox to a server one, and better auto-detection of imported git repos.
