### ISSUE TITLE
Codesandbox doesn't remember settings

### ISSUE THREAD

**Issue by alexdevero** [codesandbox/codesandbox-client#1331]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?
Codesandbox doesn't remember global and settings set via "preferences". Every time I log in, the settings for appearance, editor, prettier, etc. are set to defaults. It is then necessary to change the settings with every login, at least every day.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 2.0 (Probably)
| Browser | Vivaldi 2.1.1337.51 (Chromium-based, Chromium 70.0.3538.113)
| Operating System | Windows 10 (1803)

**Comment by CompuIves** [comment]
We store the settings in the `localStorage`. It may be because your disk is full that we cannot save.

Another solution would be to store it per user, that's something that I want to work on before 2019!

**Comment by alexdevero** [comment]
`localStorage`? So it can be also caused by using browser in anonymous mode? Then, fresh start of the browser would erase the data and reset settings. Correct?

**Comment by CompuIves** [comment]
Yep, that's correct!

**Comment by alexdevero** [comment]
Well, this is the root cause of this issue. I am using browser always in incognito mode.

**Comment by lbogdan** [comment]
Maybe it makes sense to have a global per user configuration saved in the API?

Cc @CompuIves

**Comment by alexdevero** [comment]
@lbogdan @CompuIves Another, maybe additional, option is storing configuration in a file in specific project. This would allow the user to have different default configuration across projects. This now works with prettier, now and sandbox. Or, what about extending the `sandbox.config.json`?
