### ISSUE TITLE
finding devDependancies for VUE

### ISSUE THREAD

**Issue by jimscarver** [codesandbox/codesandbox-client#1334]
# ❔ Question
What are the devDependancies for a VUE project?

The code runs in codesandbox but the package.json does not include the dev dependencies. We have been unable to get it running on ubuntu. We installed needed dependencies but do not know what version to load. Once the dependencies are resolved we get:

diglife@rhobot:~/DigLifePortal$ node run.js
/home/diglife/DigLifePortal/node_modules/@babel/core/lib/config/config-descriptors.js:178
    throw new Error(`Plugin/Preset files are not allowed to export objects, only functions. In ${filepath}`);
    ^
Error: Plugin/Preset files are not allowed to export objects, only functions. In /home/diglife/DigLifePortal/node_modules/babel-preset-stage-2/lib/index.js

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | na
| Browser | na
| Operating System | ubuntu 18.04

**Comment by jimscarver** [comment]
We currently have these dependencies:
 "name": "diglife-portal-dev",
  "keywords": [],
  "dependencies": {
    "@babel/runtime": "^7.1.5",
    "@johmun/vue-tags-input": "1.5.9",
    "axios": "0.18.0",
    "kinto-http": "4.6.1",
    "node-slack": "0.0.7",
    "particles.js": "2.0.0",
    "vue": "2.5.17",
    "vue-axios": "2.1.4",
    "vue-cookies": "1.5.7",
    "vue-material": "1.0.0-beta-10.2"
  },
  "description": "This is in sync with GitHub.",
  "devDependencies": {
    "@babel/core": "^7.1.6",
    "@babel/plugin-transform-modules-commonjs": "^7.1.0",
    "@babel/plugin-transform-runtime": "^7.1.0",
    "@babel/preset-env": "^7.1.6",
    "@babel/register": "^7.0.0",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-plugin-dynamic-import-node-babel-7": "^2.0.7",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-plugin-transform-vue-jsx": "^4.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-2": "^6.24.1"
  }

And get the error: Plugin/Preset files are not allowed to export objects, only functions

**Comment by lbogdan** [comment]
Hey @jimscarver ,

Looks like the sandbox you provided was deleted in the meanwhile.

Is this still an issue for you? If not, can you please close it? Thanks!

**Comment by SaraVieira** [comment]
Closed on lack of reply, please re open if the issue persist :)
