### ISSUE TITLE
How to get code from embed codesandbox?

### ISSUE THREAD

**Issue by zhaoyi0113** [codesandbox/codesandbox-client#1344]
I am creating a website and want to use cdoesandbox embed iframe. I am able to embed the iframe inside my webpage but is there an API I can use to get the source code in the iframe? I'd like to use the embed iframe to interactive with my web page. For example, when the user make any changes on the iframe, I want to listen on the code change and save user's code in my backend database. Is this a way to do that?

**Comment by CompuIves** [comment]
Hmm, I like this feature request. I'm working on a way to make interacting with the iframe a bit more smooth, I'll try to include this as well. Can't make any promises on when this will be released but it's on my radar!
