### ISSUE TITLE
setup jest enzyme with package.json setup failed?

### ISSUE THREAD

**Issue by thian4** [codesandbox/codesandbox-client#1346]
There are other few example using jest and enzyme in codesanbox but why this setup with package.json got error? 
```
https://codesandbox.io/s/3qrww057nm 

  "jest": {
    "setupTestFrameworkScriptFile": "src/setupTests.js"
  }
```
in package.json is ignored?

**Comment by loriculberson** [comment]
@thian4 Did you ever figure out how to setup enzyme to work with codesandbox?

**Comment by SaraVieira** [comment]
Hey!

We  currently do not support any options on the package JSON 😢

**Comment by loriculberson** [comment]
@thian4 I was able to get enzyme working in codesandbox!

https://codesandbox.io/s/31wr4mn881
