### ISSUE TITLE
Error using Jest test.each function in tests

### ISSUE THREAD

**Issue by blikblum** [codesandbox/codesandbox-client#1350]
# 🐛 bug report

## Description of the problem

Using [test.each](https://jestjs.io/docs/en/api#2-testeach-table-name-fn-timeout) on tests fails with an error:  "TypeError: test.each is not a function"

## How has this issue affected you? What are you trying to accomplish?

I'm trying to use Jest "cases" feature

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  PROD-1543715511-2cf33c46
| Browser |  Chrome
| Operating System | Window

**Comment by CompuIves** [comment]
Thanks for letting us know! Our Jest API in the browser is limited, it doesn't have everything from Jest. This is on the roadmap, but not a high priority currently.

An alternative is to create a node sandbox (https://codesandbox.io/s/node) and run Jest on there. Node sandboxes are executed on a server so in those sandboxes you can use everything from Jest.
