### ISSUE TITLE
Vue.js ZEIT Deployment doesnt work

### ISSUE THREAD

**Issue by soukypro** [codesandbox/codesandbox-client#1359]
When I am trying to deploy for example new Vue sandbox, always "An unknown error occurred when connecting to ZEIT", i tried that on multiple instances, for example on this:
https://codesandbox.io/s/r0qz0wlj0m
https://codesandbox.io/s/vv88x303zl

But for React instances it works fine.... 

I tried on Chrome and Edge

**Comment by SaraVieira** [comment]
Hey!

Looking at it they both give back the error: 

```
{"error":{"code":"invalid_files","message":"One or more file definitions contain errors in them","errors":[{"reason":"invalid_file"}]}}
```

Have you tried downloading and deploying locally ?

**Comment by soukypro** [comment]
I will try it today.
But my expectation was, that if I create new Sandbox with Vue and after creation deploy will be working, because there should not be problem with "invalid_files".

**Comment by soukypro** [comment]
I tried this localy and works fine https://codesandbox.io/s/r48wzzp98o ... but on ZEIT same problem @SaraVieira

**Comment by SaraVieira** [comment]
Dang, i will take a look at it, what a cryptic error too :/

**Comment by lbogdan** [comment]
Looks like a Now API bug, reported on their Spectrum, you can follow it here: https://spectrum.chat/?t=a95fc4d6-ccd8-432c-8dd2-8e2badd1d73d .

**Comment by soukypro** [comment]
They fixed that .. 
TEST OK ...
