### ISSUE TITLE
Accessing bundle when using sandpack/smooshpack as a standalone bundler

### ISSUE THREAD

**Issue by hobbes7878** [codesandbox/codesandbox-client#1363]
# ❔ Question

Hello! I'm trying out sandpack as a standalone bundler as recommended in  https://github.com/CompuIves/codesandbox-client/issues/496

I have a basic example setup and generating a preview correctly, but I'm wondering if there's any method on the manager to directly access the files output by the bundler process.

For example, if I set the `skipEval` option on the manager because I want to manage the execution of the transpiled code in my own app or, say, save it to a database, is there a way to listen for the code returned from the web worker?

**Comment by CompuIves** [comment]
You should get everything back from the `state` event, of you listen to all events it should come up:

```
{
   type: 'state',
   state: managerState,
}
```

**Comment by hobbes7878** [comment]
Sorry, is that something I can do from the perspective of a manager instance?

For example, if I have a simple instance like this...

```javascript
import { Manager } from 'smooshpack';

const manager = new Manager(
  '#preview',
  {
    files: {
      '/index.js': {
        code: `const myFunc = () => { console.log('Hello world'); }
myFunc();`,
      },
    },
    dependencies: {},
    entry: '/index.js',
  },
  { skipEval: true }
);
```

... how would I attach the listener so that I can retrieve the transpiled code, something like...

```javascript
// /index.js
'use strict';

var myFunc = function myFunc() {
  console.log('Hello world');
};
myFunc();
```

**Comment by hobbes7878** [comment]
Hi there. Still poking around at the standalone bundler.

Using react-smooshpack, I'm now seeing how to get at the `managerState` using the `SandpackConsumer` component. From there I can access the transpiled code like this:

```javascript
<SandpackConsumer>
    {sandpack => {
      const { transpiledModules } = sandpack.managerState;
      Object.keys(sandpack.managerState.transpiledModules).forEach((key) => {
        console.log(transpiledModules[key].source.compiledCode);
      });
      return null;
    }}
</SandpackConsumer>
```

I have 2 questions that I hope will get me further on the path:

1. While I can access my transpiled code, I'm not sure whether I can get at an _actual bundle_ that includes dependencies. I see that _fetching_ dependencies is actually part of the [sandbox](https://github.com/CompuIves/codesandbox-client/blob/5b91f8dce3e15a786fd8cd82f4034d74fa4bd37e/packages/app/src/sandbox/npm/fetch-dependencies.js), itself. So maybe that's outside the scope of sandpack?

2. I'm wondering if there's a better way to supply managerState configuration. For example, in order to get SCSS to transpile correctly, I needed to include `parcel-bundler` as a dependency, which I think I really ought to be including in the sandpack configuration as a devDependency, for example.

Again, I really appreciate any time you spare to point me in the right direction. Once I'm through the other side, I think I can at minimum contribute some documentation to help others find the way to using this really awesome standalone feature.

Just to keep my eventual goal in mind, I'm hoping to use sandpack as a way improve a [graphics builder](http://dallasmorningnews.github.io/chartwerk-editor/) I made that's used in a few US newsrooms today.

Thank you!

**Comment by lbogdan** [comment]
Pinging @CompuIves , as the only one that knows all the intricacies of smooshpack!

**Comment by gragland** [comment]
@hobbes7878 Trying to do something similar. Were you ever able to figure this out?

**Comment by SlavaMilin** [comment]
Also try to figure this. Is it any way to have access to rusult that render in iframe?

**Comment by YikaJ** [comment]
I am pretty sure that they need a bundler instead of eval in sandbox. Maybe Parcel can help it?
