### ISSUE TITLE
Using environment variables in browser sandboxes

### ISSUE THREAD

**Issue by homam** [codesandbox/codesandbox-client#1373]
# ❔ How can I use env variables in browser sandboxes?

I tried creating a `.env` file, and passing the variables in npm start script, none has worked for me.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  |
| Browser |  Chrome |
| Operating System | OSX |

**Comment by CompuIves** [comment]
Ah, yes, this only works in the CRA sandbox right now: https://codesandbox.io/s/km94jx6l3r

I'm going to replace the React+TS sandbox with the CRA sandbox soon, a solution right now would be to rename all the JS files to TS in the sandbox I just linked. That way it works.

**Comment by bz-stripe** [comment]
Is this a different ask from using secrets in the Server menu?

<img width="362" alt="Screen Shot 2019-12-11 at 11 32 15 AM" src="https://user-images.githubusercontent.com/53073303/70653898-2c7f1c80-1c0a-11ea-9042-dacc22293815.png">

*(note: must fork an imported sandbox to see the server menu)*
