### ISSUE TITLE
Full screen support via the fullscreen api

### ISSUE THREAD

**Issue by supasympa** [codesandbox/codesandbox-client#1395]
# 🌈 Feature
Codesandbox is awesome. Great job.

Add support within the application for making the IDE run full screen. This would make it feel almost native on a tablet / ipad.

Add a button to allow the user to view their workspace in full screen and implement the full screen API (which is now supported by Safari). 

https://www.w3.org/TR/fullscreen/

The guys here have implemented it and an example is available from this blog:
https://dev.to/marvindanig/fullscreen-web-apps-on-ipad-safari--3p9b

**Comment by simonwjackson** [comment]
I can "Save to Homescreen" but I cant sign in without it leaving the app for the github signin

**Comment by SaraVieira** [comment]
Hey!

Doing some spring cleaning and realized we already have this 🎉

if you tap `cmd + shift + p` and type full screen it will go into full screen mode :D
