### ISSUE TITLE
Just wanted to drop by and say "Thanks!!"

### ISSUE THREAD

**Issue by imbhargav5** [codesandbox/codesandbox-client#141]
I love codesandbox. I use it everyday. It's so cool! You save me tons of time every day as a developer and I am eager to help you guys out starting with the help-wanted issues. 

Thanks once again. You are awesome!!

**Comment by CompuIves** [comment]
Oooh this is so nice to hear! Thank you so much, you instantly made me happier 😄 .

**Comment by SaraVieira** [comment]
That was a mistake, let me open this again because it's amazing

**Comment by lbogdan** [comment]
Will keep this open and label it as awesome!
