### ISSUE TITLE
Typescript sandbox does not work in Firefox, fails with TypeError: Illegal constructor

### ISSUE THREAD

**Issue by blikblum** [codesandbox/codesandbox-client#1429]
# 🐛 bug report

## Description of the problem

Codesandbox does not work in firefox 64. Works on Chrome

## How has this issue affected you? What are you trying to accomplish?

Run the sandbox

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1546722433-8d9758e7
| Browser |  Firefox 64
| Operating System | Windows 10

**Comment by lbogdan** [comment]
Can confirm, this is the behavior I get in latest Firefox (66.0.1) on Windows 10:
- load https://codesandbox.io/s/l28p1lrj0m , the "Transpiling modules" screen barely flashes, and then the preview remains blank, with no related error in the console, either;
- if I refresh the preview, the same thing happens, but now I have an error in the console:
```
TypeError: Illegal constructor.[Learn More] sandbox.93b20a1f.js line 1 > eval:47:9
```
![image](https://user-images.githubusercontent.com/2083930/55020525-aaa97d80-4fff-11e9-943f-01fa0e00554f.png)
- clicking on the file where the error is gets me to a weird place:

![image](https://user-images.githubusercontent.com/2083930/55020647-ec3a2880-4fff-11e9-8399-e4c40bd4fa2b.png)
