### ISSUE TITLE
Hide browser and open terminal when embedding a CSB

### ISSUE THREAD

**Issue by nikolasburk** [codesandbox/codesandbox-client#1436]
I have a CSB with a bunch of scripts that I want to share. My requirements for the sharing/embedding URLs are:

- Hide the browser
- Have the terminal open

The closest I can get is by setting these query params: `expanddevtools=1&view=editor`

However, it seems that for sharing and for embedding, the results are different and in neither case match my requirements.

Embedding: [https://codesandbox.io/embed/github/prisma-csb/prisma-client-demo-js/tree/master/?expanddevtools=1&view=editor](https://codesandbox.io/embed/github/prisma-csb/prisma-client-demo-js/tree/master/?expanddevtools=1&view=editor)

![image](https://user-images.githubusercontent.com/4058327/50785996-8d8fc900-12b2-11e9-8951-8f5638ba0f50.png)

Sharing: [https://codesandbox.io/s/github/prisma-csb/prisma-client-demo-js/tree/master/?expanddevtools=1&view=editor](https://codesandbox.io/s/github/prisma-csb/prisma-client-demo-js/tree/master/?expanddevtools=1&view=editor)

![image](https://user-images.githubusercontent.com/4058327/50786054-b7e18680-12b2-11e9-9a6f-bb120792a0e3.png)

**Comment by siddharthkp** [comment]
Hey! You're right, that's a limitation of the embed right now. You can't show devtools/terminal without showing the browser.

We are going to do some work on embeds soon, I have added it on that list so that we don't forget 👍
