### ISSUE TITLE
Angular CLI template to have terminal

### ISSUE THREAD

**Issue by tcozzens** [codesandbox/codesandbox-client#1437]
# 🌈 Feature

## What is this feature?
Allow users to use Angular CLI to generate components, routes, services and pipes with a simple command.

## How the feature should work? 
Just like how it would if you had Angular CLI installed locally.

## You have examples or an idea how it can be implemented? 
I would like to be able to do the "ng generate [component name]" to create a whole Angular component, the same way it does locally. 

## Why?
Angular CLI is the mainstream development method for Angular and it seems like with the template called Angular CLI we (as a user) should be able to run the commands. Though I am not sure that this is possible

**Comment by SaraVieira** [comment]
Hey

We were actually just talking about this yesterday and it's something we plan to implement but unfortunately I don't have a timeline for you :/

**Comment by lbogdan** [comment]
Hey @tcozzens ,

Maybe my comment here https://github.com/CompuIves/codesandbox-client/issues/1646#issuecomment-475816695 helps.

I'll leave this open until we add the Angular server template.

**Comment by LucasZapico** [comment]
+1 this would be huge! I use code sandbox...well to sandbox 😉.  As you all know the Angular workflow is highly CLI dependent. Cheers!

**Comment by SaraVieira** [comment]
Hey!

After a while we changed how templates work so we now have a template with the angular CLI:

https://codesandbox.io/s/angular-cli-n61gs

You can bookmark it and you will always find it in the explore templates section of the explore tab in create new sandbox here:

![Screenshot 2019-12-12 at 15 46 07](https://user-images.githubusercontent.com/1051509/70721805-88bf6a80-1cf6-11ea-8ed6-1c13708fc55c.png)

Hope this helps

**Comment by tcozzens** [comment]
@SaraVieira this is awesome! Works great!

**Comment by asiahpolo** [comment]
For some reason I cant type anything on a new terminal tab.
