### ISSUE TITLE
Prettier + Vue + Pug, not working

### ISSUE THREAD

**Issue by quangv** [codesandbox/codesandbox-client#1440]
# 🐛 bug report

## Description of the problem

Prettier seems to mess up Vue's Pug syntax.

This valid pug:

```pug
<template lang="pug">
  #app
    img(width="25%" src="./assets/logo.png")
    HelloWorld/
</template>
```

Prettier turned into this: (not really what we want)
```pug
<template lang="pug">
  #app img(width="25%" src="./assets/logo.png") HelloWorld/
</template>
```

Is there any Prettier option to prevent this from happening? Thanks!

Also could be related to this: https://github.com/prettier/prettier/issues/5371

## How has this issue affected you? What are you trying to accomplish?

Trying to use Pug with Vue in codesandbox, with Prettier, but Prettier seems to not like it.

###  Link to sandbox: [link]() (optional)

https://codesandbox.io/s/l75l39o97l

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  https://codesandbox.io/s/l75l39o97l
| Browser |  chrome
| Operating System | windows 10

**Comment by quangv** [comment]
Could be related to this:

https://github.com/prettier/prettier/issues/5371

However I think the prettier version is higher than `1.15.2`

**Comment by lbogdan** [comment]
Hey @quangv ,

With the recent switch to VSCode as the default editor, this should be fixed. I just tested on your sandbox, and it looks like prettier is not messing with Pug code anymore. Please test and close this if everything's behaving as expected.

**Comment by SaraVieira** [comment]
Closed on lack of reply, please re open if the issue persist :)
