### ISSUE TITLE
Allow PayPal donations for Patron 

### ISSUE THREAD

**Issue by BartInTheField** [codesandbox/codesandbox-client#1441]
🌈 Feature
Allow PayPal donations for Patron

I want to donate to the Patron, but the requirement for a credit card is a limitation.

**Comment by oskarabc** [comment]
Hello Bart, we are not going to use PayPal as a payment option. We are interested though in using payment methods other than just credit cards, such as IDEAL or a SEPA Direct Debit option in The Netherlands – assuming this works for you and you are still based in NL. Apparently IDEAL isn't offered when creating a new subscription and we'll get this fixed. 

For customers in Germany we are considering SOFORT, GiroPay and a SEPA method.

Would any of the other two options be a good option for you?

**Comment by BartInTheField** [comment]
Hi,

iDeal would be perfect!

**Comment by BartInTheField** [comment]
Any payment options updates?

**Comment by oskarabc** [comment]
Hi, no progress but it's on the calendar for Sep! I'll update this thread as soon as I have a more specific ETA and our final choice of additional payment methods.

**Comment by BartInTheField** [comment]
Unfortunate to see this not implemented :(

**Comment by SaraVieira** [comment]
Hey!

Unfortunately, this is not on the roadmap for this year and no idea when/if it will come and as we are trying to keep GitHub with features we want to implement I am going to close this.

If we do put it in our roadmap in 2021 this issue will be linked

Thanks again for the suggestion!
