### ISSUE TITLE
Allow setting `initialpath` in sandbox.config.json

### ISSUE THREAD

**Issue by schickling** [codesandbox/codesandbox-client#1442]
Additionally to setting the `?initialpath=/feed` via as a query string it would be awesome to allow setting this option in the `sandbox.config.json` file

**Comment by ianschmitz** [comment]
Just ran into this as well. We provide an _Edit in Codesandbox link_ from documentation to allow developers to play with our samples. This link includes `initialPath`. However, when forking the sandbox, the param is no longer present and the preview navigates to the wrong initial path.
