### ISSUE TITLE
Enable opening additional terminal tabs when CSB is imported from GitHub

### ISSUE THREAD

**Issue by nikolasburk** [codesandbox/codesandbox-client#1443]
# 🌈 Feature

When importing a CSB from a GitHub repo, the project is immutable. In order to make changes to it, I need to fork it to have my own version of the CSB.

Similarly, it is currently not possible to open additional terminal tabs in the immutable CSB that's imported from GitHub. It would be awesome if there was a way to open additional terminal tabs even in the immutable CSB. 

My use case is that I want to let people run NPM scripts that are defined in `package.json`.

**Comment by manniL** [comment]
That's because nobody "owns" the CodeSandbox. And giving access to the server for many ppl doesn't sound like a nice idea 🙈 

Forking it shouldn't introduce a lot of overhead, right?
