### ISSUE TITLE
"Create Sandbox" and Profile Buttons not Visible on Phone for https://codesandbox.io

### ISSUE THREAD

**Issue by fabb** [codesandbox/codesandbox-client#1449]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

It's actually not a bug of the client, but from the website https://codesandbox.io, but I didn't know where else to post this.

When opening https://codesandbox.io on a narrow phone like iPhone 6, in the header, the buttons "Create Sandbox" and "<Username>" do not appear. When rotating the phone to landscape, they do appear. Maybe the buttons could rather be wrapped when the view is too narrow?

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Browser | Mobile Safari
| Operating System | iOS 12

**Comment by SaraVieira** [comment]
Hey !

I think this was intentional as we thought people would not be creating them on the phone but I can take a look and post some screenshots here to a new version with it 

Is that okay ?

**Comment by fabb** [comment]
The problem is that i also have no way to navigate to my dashboard and open any of my sandboxes.

Sure that‘s ok!

**Comment by SaraVieira** [comment]
That was I was thinking. Maybe just add the dashboard button

**Comment by christianalfoni** [comment]
We have a new version of this coming out shortly, will close this for now. Stay tuned for an update and please create a new issue if you find any challenges with the new UI :) Sorry, do not have exact ETA, but very soon
