### ISSUE TITLE
Problem serving MIME type="module"

### ISSUE THREAD

**Issue by AmyScript** [codesandbox/codesandbox-client#1458]
# 🐛 bug report

## Trying to add web components through:
```
<script type="module">
      import "./node_modules/@amyscript/dsg-info-card/dsg-info-card.js";
 </script>
```
getting this error:
![screen shot 2019-01-11 at 10 54 47 am](https://user-images.githubusercontent.com/24494020/51044942-58c09200-1590-11e9-8975-6c708e4fc2cf.png)

## How has this issue affected you? What are you trying to accomplish?
can't import the web component module via code sandbox even though it works perfectly on a local server

### Your Environment
| Software         | Name/Version|
| Сodesandbox  | Current
| Browser | Chrome
| Operating System | Mac

**Comment by SaraVieira** [comment]
Can you try this on the static template ?

https://codesandbox.io/s/github/codesandbox-app/static-template

**Comment by looeee** [comment]
I made a simple `<script type=module >` test, with the static template in browser modules are working fine. But I'm still getting the"failed to load script error" with node modules. 


https://codesandbox.io/s/4xxmx6opl4

**Comment by lbogdan** [comment]
@AmyScript Can you please provide another link, as the sandbox you pointed to doesn't exist anymore?

> I made a simple `<script type="module">` test, with the static template in browser modules are working fine.
> But I'm still getting the"failed to load script error" with node modules.

@looeee That's because the `static` template doesn't support using npm packages.

**Comment by CompuIves** [comment]
We could potentially add support for node_modules in `static` template, but this would require some server side changes. I think the best way to currently handle this is by creating a sandbox based on a container, like https://codesandbox.io/s/node. These sandboxes are run on a server and correctly host the node_modules.
