### ISSUE TITLE
Anchors in React do not fire onClick handlers in preview if a hash is present in the link

### ISSUE THREAD

**Issue by tannerlinsley** [codesandbox/codesandbox-client#1463]
# 🐛 bug report

## Description of the problem
When a hash is placed in the link of an anchor element in React, the onClick handler for the component doesn't fire. This only happens in the preview though. If you open the standalone window of the app, you'll see it works just fine.

###  Link to sandbox: [link](codesandbox.io/s/4w20jlxz0)

Possible Related Issues: #1226

**Comment by necheporenko** [comment]
Any updates or solutions to avoid this bug?
