### ISSUE TITLE
How to point dependency to a github branch 

### ISSUE THREAD

**Issue by sartaj10** [codesandbox/codesandbox-client#1466]
# ❔ Question

Hi,
I would like to point my dependency to a branch on github, rather than a particular version. In my package.json, I've pointed it like this : 

```
"react-timeseries-charts": "esnet/react-timeseries-charts#fix-355"
```

However, this doesn't work and I get this message

```
Could not fetch dependencies, please try again in a couple seconds: Unexpected token < in JSON at position 0
```

I saw an issue (#88) that suggests that this should work. Could you point me as to how to go about this?

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Chrome
| Operating System | macOS Sierra

**Comment by tomasfrancisco** [comment]
I'm facing the same issue. I cannot figure out how to add a GitHub dependency. 
Is it really supported?

I've tried the following:
`lightbasenl/lightbot.js`
`lightbasenl/lightbot.js#master`
`https://github.com/lightbasenl/lightbot.js`
`https://github.com/lightbasenl/lightbot.js#master`

None of them worked, unfortunately :(

**Comment by CompuIves** [comment]
Ahh, yeah, it's possible to install GitHub dependencies. Keep in mind that we just serve the source files of the GitHub repo (like `npm` and `yarn`), we do run the `postinstall` script, so if you want to build some files you can put it in that step.

Regarding `esnet/react-timeseries-charts#fix-355`, I just found out that our caching system doesn't support `#` in the paths, that's why it's showing those errors. I can take a look at that.

**Comment by dai-shi** [comment]
A workaround is to use tar.gz URL:
```
"react-timeseries-charts": "https://github.com/esnet/react-timeseries-charts/archive/fix-355.tar.gz"
```

**Comment by dabernathy89** [comment]
Using the `tar.gz` URL doesn't seem to work anymore. Anyone figured out a working solution for pulling in a dependency from a Github branch?

**Comment by perymimon** [comment]
It looks like Codesandbox using `https://www.jsdelivr.com/` to supply the dependency. 
and `jsdeliver` using git tag to find the repository.
so I end up with that steps for a solution :
1. push a new tag to my GitHub repository (tag v3.0.0) 
2. then check it to work  https://cdn.jsdelivr.net/gh/perymimon/react-anime-manager@v3.0.0/package.json in the browser. 
3. going to `codesandbox/package.json` 
4. under `"dependencies"`  add : 
   ` "@perymimon/react-anime-manager": "perymimon/react-anime-manager#v3.0.0"`
