### ISSUE TITLE
Is there a way to turn off strict mode?

### ISSUE THREAD

**Issue by moshemo** [codesandbox/codesandbox-client#1474]
# ❔ Question

I'm using a vanilla javascript editor -- it seems to me (although I may be wrong), that strict mode is automatically being applied.

If that is the case, is there any way for me to not use strict mode?  If so, how?

Thanks :).

**Comment by lbogdan** [comment]
Hey @moshemo , out of curiosity, can you please share what your use case is? As far as I'm concerned, you should **never** not use strict mode. 🙂

**Comment by akshaygarg834** [comment]
One of the ise case is when using particle js it thorws 
error.

**Comment by epamer** [comment]
> Hey @moshemo , out of curiosity, can you please share what your use case is? As far as I'm concerned, you should **never** not use strict mode. 🙂

Today I faced the same issue. I prepared materials for my student to explain how 'this' works in JS. But then I found that it's 'undefined' instead of 'window'.

**Comment by SaraVieira** [comment]
@akshaygarg834 @epamer Do you have any sandbox I can take a look?

**Comment by epamer** [comment]
@SaraVieira nope, I haven't. But you can just use console.log(this) in the global scope or inside a function. E.g.:

function boo() {
    console.log(this);
}
boo();

Then you will see 'undefined' in your browser console instead of 'window.' That's mean that the editor use 'use strict' mode and I didn't find how to switch it off.

**Comment by pikl-cz** [comment]
> @SaraVieira nope, I haven't. But you can just use console.log(this) in the global scope or inside a function. E.g.:
> 
> function boo() {
> console.log(this);
> }
> boo();
> 
> Then you will see 'undefined' in your browser console instead of 'window.' That's mean that the editor use 'use strict' mode and I didn't find how to switch it off.

I tried similar case.

```
function foo() {
  console.log(this.a);
}

var obj = {
  a: 2,
  foo: foo
};

var bar = obj.foo;

var a = "global";

bar();
```

**Comment by wasitshafi** [comment]
I am was reading this https://www.digitalocean.com/community/tutorials/understanding-hoisting-in-javascript article and tried to play with some hoisting code, then I noticed  **strict mode** is on can someone help to disable it. Thanks

**Comment by JamesACS** [comment]
Hey @wasitshafi - As above please could you let us know some more information about your use case and what issues you're running into? 

If you have an existing Sandbox you could link us too that would also be appreciated

**Comment by ryanvazquez** [comment]
@JamesACS I think most use cases will likely be similar to mine - devs wanting to explore JavaScript's quirks or analyze some snippet of compiled code in a sandboxed environment.

Makes sense to enable strict mode by default but it'd be nice to have the option to toggle it off.

**Comment by JamesACS** [comment]
Thanks @ryanvazquez - Those use cases definitely make sense. I've raised this as a feature request on this end!
