### ISSUE TITLE
TypeScript: no type errors during build

### ISSUE THREAD

**Issue by pjoe** [codesandbox/codesandbox-client#1475]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?
No build errors are generated from type errors when using typescript. I get the red squiggles in the editor but project still runs and shows - ignoring any type errors. Running similar project locally produces type error output.

For typescript to be really useful to me, it needs to error out on type errors, not just compile and run anyway.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Chrome 71
| Operating System | Windows 10

**Comment by SaraVieira** [comment]
Hey!

The problem is that React Scripts was not updated to the latest version for a while in some sandboxes, updating it manually fixes the issue:

https://codesandbox.io/s/387k3zzwr6

For new sandboxes this has been fixed

**Comment by SaraVieira** [comment]
Sorry, my misunderstaning of how create-react-app typescript, just downloaded and see what you mean. it's supposed to totally break

Reopening

**Comment by khoneychurch** [comment]
any chance of reopening this? This should kill the build
`let thing: string;
thing = 10;`
