### ISSUE TITLE
Malformed HTML breaks in-editor browser (iframe remains at opacity `0`)

### ISSUE THREAD

**Issue by tinymachine** [codesandbox/codesandbox-client#1489]
# 🐛 bug report

## Description of the problem
When previewing a static template project missing its closing `</body>` and `</html>` tags, the in-editor browser silently fails: the browser looks empty, but upon inspection the contents are being rendered — it's just that the opacity on the containing `iframe` is stuck at `0`:

```html
<iframe
  sandbox="allow-forms allow-scripts allow-same-origin allow-modals allow-popups allow-presentation"
  ...
  style="opacity: 0;z-index: 1;background-color: white;pointer-events: initial;"
>
```
When I open the preview in its own window, there's no problem; apparently the iframe preview can't recover from the malformed HTML in the same way. 

Not sure if related, but I'm also seeing this warning in the console for the page (not the editor's own console):

> Use `shouldComponentUpdate` in an `observer` based component breaks the behavior of `observer` and might lead to unexpected results. Manually implementing `sCU` should not be needed when using mobx-react.

Looks like the JS that's supposed to fade in the iframe contents isn't firing because of the invalid HTML.

## How has this issue affected you? What are you trying to accomplish?
Wasted time identifying the underlying issue; thought at first there was a bug with Code Sandbox itself! Ideally the in-editor browser would fail more visibly, pointing out the problem with the malformed HTML. (Perhaps this is more of a feature request than a bug report?)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  PROD-1548076483-7e4a81c2 |
| Browser | Chrome 71.0.3578.98, Safari 12.0.2 (14606.3.4), Firefox 64.0.2 |
| Operating System | macOS 10.14.2 |

**Comment by lbogdan** [comment]
Hey @tinymachine ,

As the sandbox you provided doesn't exist anymore, can you please point us to another one experiencing this?

**Comment by tinymachine** [comment]
Sorry! Restored it: https://codesandbox.io/s/91y8vz69pr

**Comment by SaraVieira** [comment]
This seems to have been fixed and working now 🚀
