### ISSUE TITLE
🐛: Can't go Offline and use CodeSandbox

### ISSUE THREAD

**Issue by BlueJYT** [codesandbox/codesandbox-client#1496]
# 🐛 bug report

## I don't have internet all the time, depending on this for coding.

I just want to know why I can't go Offline! Thanks!

**Comment by Mooninghnk** [comment]
same here, there need to be more documentation on this offline mode

**Comment by lbogdan** [comment]
@Chi7519 @Mooninghnk Can you please give us more details on this? What exactly are you trying to do, what happens, what do you expect to happen?

**Comment by NanobugXL** [comment]
Plain and simple? I think they've expressed it that they cannot go offline. If it is said, stated or advertised, it should be able to live up to the statement or documents. Even if a developer had made it as a statement. There-fore, if it dont work, it dont work is pretty much is what I got out of it. What more can these two say? I dont see anywhere that says can be used offline myself. Now, if you clone the repo and try to use it npm/yarn or whatever.......and it dont work, then.....

**Comment by lbogdan** [comment]
Well, it works offline, but with some common sense limitations, like you can't add dependencies, do API calls, use server sandboxes (which run in a container in the cloud, so you need network connectivity to work on them) etc.

**Comment by SaraVieira** [comment]
Closing this as per Bogdan's comment these limitations are pretty standard
