### ISSUE TITLE
🌈 Feature: Add a Run Button

### ISSUE THREAD

**Issue by Mooninghnk** [codesandbox/codesandbox-client#1500]
# 🌈 Feature

Button for code execution on demand

On click it would run the code

Place the button next to ShowBrowser/ShowConsole/Show Tests

**Comment by CompuIves** [comment]
We have an option currently to run the code on save, I'll look into a run button with the design changes I'm doing right now.

**Comment by Mooninghnk** [comment]
Thank you so much :), its just not comfortable to save the code each time to run it, if the code is the same with no changes it only runes once. run button will run the code when ever you want it to.

**Comment by flozia** [comment]
The option to run the code on save is great! Having an additional run button, as @Mooninghnk requested, is still a feature I wished for every now and then. In case @CompuIves decides to give it a shot – I’d be happy to contribute.

**Comment by babakness** [comment]
@CompuIves 

> We have an option currently to run the code on save,

I didn't notice this documented. I'd like code to run ONLY run on save, is this possible?
