### ISSUE TITLE
Issue: 🐛 I defined a function inside a jsfile, linked it with my html and it comes back ReferenceError log is not defined

### ISSUE THREAD

**Issue by Mooninghnk** [codesandbox/codesandbox-client#1502]
# 🐛 bug report

## Description of the problem
I defined a function inside a jsfile, linked it with my html and it comes back ReferenceError
log is not defined
HTMLButtonElement.onclick
## How has this issue affected you? What are you trying to accomplish?
im trying to link js and html together and created a button with on-click executes a function,
but it returns undefined, tested it in a regular vscode works just fine.
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | https://codesandbox.io/s/kxz558mzj7
| Browser | Chrome
| Operating System | MacOs

**Comment by CompuIves** [comment]
Hey! I can't find the example you mention, the only file

**Comment by lbogdan** [comment]
@Mooninghnk The sandbox you linked to doesn't exist anymore, is this still an issue? If not, please help us lower the number of opened issues by one! Thanks! 🙂

**Comment by shubhambattoo** [comment]
Facing the same issue in the vanilla sandbox, attaching a screenshot for more reference.

sandbox [link](https://codesandbox.io/s/sortable-list-0s8sx)

![codesandbox](https://user-images.githubusercontent.com/21199053/63669698-585fc900-c7f8-11e9-8449-cce9fbc9030d.PNG)

**Comment by notyeninja** [comment]
@Ibogdan This is still an issue. Here is a new codesandbox link for your reference.
https://codesandbox.io/s/ecstatic-solomon-mzf6b

**Comment by kokushkin** [comment]
Yeah, I was really surprised to know this basic functionality doesn't work. So, I have to use https://jsfiddle.net/ instead.

**Comment by lbogdan** [comment]
@notyeninja Don't have time right now to explain why it behaves like that, but here's a working sandbox: https://codesandbox.io/s/sleepy-sunset-w0wds .

**Comment by lbogdan** [comment]
Ok, so the explanation is that in the `vanilla` template / `parcel` environment we're doing module bundling, handling `src/index.js` as a module. Because modules are evaluated in their own (private) scope, if you want to access from html something inside the module, you can put it on the browser's global scope, which is `window`.

Alternatively you can use the `static` template / environment, where we don't do any bundling, like https://codesandbox.io/s/quirky-flower-rm20y (but then you lose the ability to `require` / `import`).

@Mooninghnk , @notyeninja , @kokushkin , does that answer your question / solve your issue?

**Comment by kokushkin** [comment]
Thank you @Ibogdan for the explanations. It's seems like ```static``` template was the right choice for us at the time. I just didn't pay attention it uses  modules bundling.

At the same time ```vanila```  template looks like kind of useless if you're doing at least something with html. First of all you have to correct this string:
![image](https://user-images.githubusercontent.com/9853656/74640020-96222680-5177-11ea-8439-9a41033e3b60.png)
what is a little bit boring.
And at the second, in fact, you don't have to do it. You can correct ```index.html``` straight away. Anyway, you'll end up with doing binding in the code:
```
document.getElementById("allertButton").onclick = triggerAlert;
// or
window.triggerAlert = triggerAlert;
```
In this case, why don't use React?) Sorry, maybe I've got used to React too much))
Maybe there are some others alternatives how to stay away from React, Angular and Vue, still using bundling, and have a good experience with html like with the ```static``` template?

**Comment by Explosion-Scratch** [comment]
Unclose

**Comment by Explosion-Scratch** [comment]
This is happening to me too. Codesandbox is awesome otherwise.

**Comment by lbogdan** [comment]
Hey @Explosion-Scratch ,

Did you read [my comment](https://github.com/codesandbox/codesandbox-client/issues/1502#issuecomment-584886419)? If that doesn't solve your issue, can you please give a bit more details and the URL to your sandbox? Thanks!

**Comment by afroguy16** [comment]
> Ok, so the explanation is that in the `vanilla` template / `parcel` environment we're doing module bundling, handling `src/index.js` as a module. Because modules are evaluated in their own (private) scope, if you want to access from html something inside the module, you can put it on the browser's global scope, which is `window`.
> 
> Alternatively, you can use the `static` template / environment, where we don't do any bundling, like https://codesandbox.io/s/quirky-flower-rm20y (but then you lose the ability to `require` / `import`).
> 
> @Mooninghnk , @notyeninja , @kokushkin , does that answer your question / solve your issue?

The sandbox link isn't working as expected. Input isn't focused, because the JS probably don't have access to the HTML file.

**Comment by Explosion-Scratch** [comment]
> Hey @Explosion-Scratch ,
> 
> Did you read [my comment](https://github.com/codesandbox/codesandbox-client/issues/1502#issuecomment-584886419)? If that doesn't solve your issue, can you please give a bit more details and the URL to your sandbox? Thanks!

Apologies! I was very new to github at the time, but yes, that fixes the problem! Thank you!

**Comment by Pushp1992** [comment]
> Yeah, I was really surprised to know this basic functionality doesn't work! So, I have to use https://jsfiddle.net/ instead.

Yes, it worked on jsfiddle but it is weird it did not worked on `codesandbox` `stackblitz` and others.
