### ISSUE TITLE
🐛: create-react-app: process.env.PUBLIC_URL is undefined

### ISSUE THREAD

**Issue by cristiano-belloni** [codesandbox/codesandbox-client#1504]
# 🐛 bug report

## Description of the problem
Trying to load a web worker (actually an audio worklet) from `public`. The way to programatically access the URL, described [here](https://facebook.github.io/create-react-app/docs/using-the-public-folder), is to access ` process.env.PUBLIC_URL`. However, the value seems `undefined` and it seems I can't load my worklet.

## How has this issue affected you? What are you trying to accomplish?
See above. Can't access public URLs, and can't load them as audio worklets.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1548340072-275bba4c |
| Browser | Version 68.0.3440.106 (Official Build) (64-bit) |
| Operating System | Windows 7 |

**Comment by lbogdan** [comment]
Hey @cristiano-belloni ,

You can access the files in a sandbox's `public` folder using the `https://sandbox_id.codesandbox.io/public/filename.ext` url, e.g. https://oxqwr38pyy.codesandbox.io/public/test.json .

We should probably look into defining the `PUBLIC_URL` environment variable for `create-react-app` sandboxes.
cc @CompuIves

**Comment by cristiano-belloni** [comment]
Hi @lbogdan - does this work with private sandboxes? Because I'm trying with one and it doesn't seem to work. Would this be part of the same bug report or should I open another?

**Comment by lbogdan** [comment]
@cristiano-belloni That's a known issue, and it's tracked in #630 .

**Comment by karlhorky** [comment]
For simple cases if your application is in the root, you can just use:

```js
// Temporary workaround for CodeSandbox
// Ref: https://github.com/codesandbox/codesandbox-client/issues/1504
process.env.PUBLIC_URL =  process.env.PUBLIC_URL || '';
```

That way, URLs derived from prefixing this variable before a root-relative path will work in both cases (isomorphic 😂):

```js
const url = `${process.env.PUBLIC_URL}/path/in/public/folder/to/my/image.jpg`;
```
