### ISSUE TITLE
SyntaxError Unexpected token <

### ISSUE THREAD

**Issue by ShimiSun** [codesandbox/codesandbox-client#1513]
# 🐛 bug report

## Description of the problem
Syntax Error pops on top of the app when opening the source code of code sandbox
<img width="850" alt="screen shot 2019-01-31 at 1 37 41 pm" src="https://user-images.githubusercontent.com/6320236/52083789-a744c900-255d-11e9-8969-311b3a1d8ed1.png">
<img width="1148" alt="screen shot 2019-01-31 at 1 28 02 pm" src="https://user-images.githubusercontent.com/6320236/52083796-a90e8c80-255d-11e9-9f5c-c0784000cecb.png">

## How has this issue affected you? What are you trying to accomplish?
viewing the rendered code is impossible until you clear manually the error message, and the error comes back after refresh
###  Link to sandbox: [link]() (optional)
https://codesandbox.io/s/6z14n5x8qn
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | latest
| Browser | chrome
| Operating System | MacOS Mojave 10.14.2

**Comment by ShimiSun** [comment]
I discussed this issue with @CompuIves on the `Grommet v2 launch` event. Please let me know if you need more info.

**Comment by lbogdan** [comment]
Hey @ShimiSun ,

This appears to be working now. Can you please confirm and help us lower the number of opened issues by one? Thanks! 🙂

**Comment by ShimiSun** [comment]
Looks good, thank you guys!

**Comment by ShimiSun** [comment]
This issue isn't completely solve, although there is a timeout that makes the error disappear, it is still there when opening the sandbox.

**Comment by derMart** [comment]
The issue is still existing for me. Testcase is here: https://codesandbox.io/s/thirsty-hooks-v8tfs?file=/src/App.vue

**Comment by CompuIves** [comment]
Hey @derMart, this is an interesting case. I haven't been able to find why it doesn't resolve the Vue files correctly yet in `primevue@3.0.1`, but it does seem to start working when you update `primevue`. Here's the updated sandbox: https://codesandbox.io/s/shy-star-7rhqi?file=/src/App.vue

**Comment by ShimiSun** [comment]
You can still view the error as you open the codesandbox https://codesandbox.io/s/6z14n5x8qn
![image](https://user-images.githubusercontent.com/6320236/116180219-c1869680-a6d5-11eb-8610-3ec20d16046e.png)

**Comment by KrishnaAsawa** [comment]
same issue persisting

**Comment by lbogdan** [comment]
Hey @ShimiSun ,

There were two issues with `index.html` in the [linked sandbox](https://codesandbox.io/s/6z14n5x8qn):
- a missing `}` inside the `<style>` tag (probably unrelated to the issue):

![image](https://user-images.githubusercontent.com/2083930/119478243-5245a600-bd58-11eb-9210-7dee01457857.png)

- an extra `<script>` tag, which is causing the issue:

![image](https://user-images.githubusercontent.com/2083930/119478392-72756500-bd58-11eb-965b-1748770498d5.png)

I forked your sandbox and fixed these issues, please let me know if it works for you: https://codesandbox.io/s/grommet-sandbox-forked-ldrk3 .

**Comment by lbogdan** [comment]
@KrishnaAsawa Can you please link to a sandbox having this issue?

**Comment by derMart** [comment]
@lbogdan Issue still persisting in my sandbox, when using primevue 3.0.1 https://codesandbox.io/s/thirsty-hooks-v8tfs?file=/src/App.vue

![Screenshot from 2021-05-25 13-22-06](https://user-images.githubusercontent.com/1069456/119489916-7efbbc80-bd5c-11eb-8dbc-d34268f8bb1c.png)

**Comment by lbogdan** [comment]
@derMart Although they look the same, your issue seems to have a different root cause. Could you maybe open a new issue for it? Thanks!

**Comment by DeMoorJasper** [comment]
cannot reproduce this anymore

**Comment by jlaluces123** [comment]
> Hey @ShimiSun ,
> 
> There were two issues with `index.html` in the [linked sandbox](https://codesandbox.io/s/6z14n5x8qn):
> 
> * a missing `}` inside the `<style>` tag (probably unrelated to the issue):
> 
> ![image](https://user-images.githubusercontent.com/2083930/119478243-5245a600-bd58-11eb-9210-7dee01457857.png)
> 
> * an extra `<script>` tag, which is causing the issue:
> 
> ![image](https://user-images.githubusercontent.com/2083930/119478392-72756500-bd58-11eb-965b-1748770498d5.png)
> 
> I forked your sandbox and fixed these issues, please let me know if it works for you: https://codesandbox.io/s/grommet-sandbox-forked-ldrk3 .

Hey @lbogdan great to meet you!

While investigating this issue, I noticed you removed the `<script async src = "index.js"></script>` . While it works in stopping the `Unexpected Token '<'` from popping up in the codesandbox environment, after testing this idea live in production the home page is stuck on the loading screen.

But after adding the script tag back in and trying to reproduce the Unexpected Token error (via refreshing the page like in the codesandbox) it doesn't show up and the site works like normal.

Do you think this could possibly be an issue on codesandbox's side? Feel free to check out the site I spun up here:
https://zen-lumiere-5f5869.netlify.app/

**Comment by ShimiSun** [comment]
Can we please reopen this issue or suggest or a workaround to help with the solution?

**Comment by jlaluces123** [comment]
Just reiterating, would it be possible to revisit this issue? It seems after the recent updates to the `grommet-sandbox`, the `Unexpected Token '<'` error has gone away so there could be a possibility of closing this issue.

**Comment by DeMoorJasper** [comment]
If someone can share a reproducible sandbox with this issue (or open a new issue with a reproducible case) we can look into this.

**Comment by mercurio** [comment]
[](https://codesandbox.io/s/stoic-alex-crijv) demonstrates the problem. It's based on a github repo that works locally. You may have to hit the refresh button on the browser pane to see the error.

**Comment by danieldanielecki** [comment]
@DeMoorJasper, basic HTML/CSS/JS example, and the same error in console: https://codesandbox.io/p/sandbox/03-exploring-the-dom-8kyhj7

**Comment by danieldanielecki** [comment]
> @DeMoorJasper, basic HTML/CSS/JS example, and the same error in console: https://codesandbox.io/p/sandbox/03-exploring-the-dom-8kyhj7

Today it's working, strange.
