### ISSUE TITLE
Cannot sign into Codesandbox

### ISSUE THREAD

**Issue by Ajar-Ajar** [codesandbox/codesandbox-client#1522]
# 🐛 bug report

### My Environment
Google Chrome | 71.0.3578.98 (Official Build) (64-bit) (cohort: Stable)
OS: Windows

![image](https://user-images.githubusercontent.com/2492303/52287422-cd5dd500-2972-11e9-89ec-73515776c76f.png)

**Comment by CompuIves** [comment]
Hey! Thanks for letting me know. Looking into it now

**Comment by CompuIves** [comment]
I saw some failed API requests to GitHub, but don't see any right now. Does it still happen for you?

**Comment by Ajar-Ajar** [comment]
Yes, very much so... :( 
I would've sent you more screenshots but they look the same...
Anything I can do to assist?

**Comment by CompuIves** [comment]
Okay! I might have a fix, does it work now?

**Comment by CompuIves** [comment]
Hmm, that's indeed weird. It may be related to the account. Could you send an e-mail to ives@codesandbox.io so we can discuss it there?

**Comment by Ajar-Ajar** [comment]
Sure. Thank you Ives.

**Comment by alemesa** [comment]
heys guys, any news about this issue? I'm running into the exact same problem @Ajar-Ajar @CompuIves

**Comment by lbogdan** [comment]
@Ajar-Ajar @alemesa Are you still experiencing this?

**Comment by crudfunc** [comment]
I have the same problem, It happened after I changed my GitHub Username. Pls Fix

**Comment by alemesa** [comment]
yep still happening for me @lbogdan

**Comment by alemesa** [comment]
I fixed it by changing back to my alternative email, I have two emails (personal && work), and a while back I changed the primary I think that's the issue @crudfunc @Ajar-Ajar

**Comment by CompuIves** [comment]
Hmm, these cases occur when both the GitHub username and email change at the same time, in that case we don't have an identifier to fall back on. I think we need to solve this on a case-by-case basis. So if you have an issue with this, please send an e-mail to ives@codesandbox.io so I'll try to fix it as fast as possible for you 😄.

**Comment by gokhantaskan** [comment]
Hi, before opening a new issue, I wonder if you can see this issue. It happens both in Chrome and Opera, I cannot sign in with GitHub. ![2019-07-19 15-52-41 Ekran görüntüsü](https://user-images.githubusercontent.com/45636599/61536462-5fe3c380-aa3d-11e9-820c-39683d314058.png)

**Comment by dmarshall83** [comment]
I'm having the same problem

**Comment by PHurst1** [comment]
having this issue still

**Comment by PHurst1** [comment]
I'm getting this problem. Email sent to ives@codesandbox.io.

**Comment by ruucm** [comment]
Same here. it lasts maybe 3month

**Comment by atchuta168** [comment]
Still i am facing the same issue, when i try to login it is showing login again and again

**Comment by omkarkolate** [comment]
I have changed my mail from my github account and now not able to sign in into codesandbox as i can not use my previous mail.

**Comment by sagarmainkar** [comment]
I cannot login into codesandbox.io from past 3-4 months with my github login.
<img width="753" alt="Screenshot 2020-09-15 at 3 24 20 PM" src="https://user-images.githubusercontent.com/5027785/93196040-8ac3c780-f767-11ea-9007-13621c7ff900.png">

**Comment by garethx** [comment]
@sagarmainkar Please email hello@codesandbox.io with the email you currently use on GitHub and your prior email address and we can get this updated on our system.

**Comment by dhanushkac** [comment]
> I cannot login into codesandbox.io from past 3-4 months with my github login.
> <img alt="Screenshot 2020-09-15 at 3 24 20 PM" width="753" src="https://user-images.githubusercontent.com/5027785/93196040-8ac3c780-f767-11ea-9007-13621c7ff900.png">

I am getting the same. Tried signing with Google, but it says have to login with GitHub.

**Comment by dhanushkac** [comment]
> > I cannot login into codesandbox.io from past 3-4 months with my github login.
> > <img alt="Screenshot 2020-09-15 at 3 24 20 PM" width="753" src="https://user-images.githubusercontent.com/5027785/93196040-8ac3c780-f767-11ea-9007-13621c7ff900.png">
> 
> I am getting the same. Tried signing with Google, but it says have to login with GitHub.

I tried using incognito mode in chrome, I was able login. I am using 87.0.4280.88.

**Comment by CodeSandboxTeam** [comment]
Hey!


Do you have any Cors extensions installed on Chrome? I had this issue for a couple of days where GitHub would not le me log in and it was because I had https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en turned on

—
Thank you
Sara Vieira

--- original message ---
On December 30, 2020, 9:12 PM GMT+1 notifications@github.com wrote:



>> I cannot login into codesandbox.io from past 3-4 months with my github login.



> I am getting the same. Tried signing with Google, but it says have to login with GitHub.


I tried using incognito mode in chrome, I was able login. I am using 87.0.4280.88.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by dhanushkac** [comment]
> Hey! Do you have any Cors extensions installed on Chrome? I had this issue for a couple of days where GitHub would not le me log in and it was because I had https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en turned on — Thank you Sara Vieira
> --- original message ---
> On December 30, 2020, 9:12 PM GMT+1 ***@***.*** wrote: > I cannot login into codesandbox.io from past 3-4 months with my github login. I am getting the same. Tried signing with Google, but it says have to login with GitHub.
> I tried using incognito mode in chrome, I was able login. I am using 87.0.4280.88. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. --- end of original message ---

Thank you for the info. I have `Bitdefender Anti-tracker`. I turned off. Now login success. Sad story xD

**Comment by SaraVieira** [comment]
That's weird but hey you can use https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

10/10 blocker, would recommend :)
