### ISSUE TITLE
React-Static static site generator Server Template

### ISSUE THREAD

**Issue by dance2die** [codesandbox/codesandbox-client#1528]
# 🌈 Feature

## What is this feature?

[react-static](https://github.com/nozzle/react-static) static site generator Server Template

![Server Templates](https://user-images.githubusercontent.com/8465237/52513686-6cd0d100-2bda-11e9-93f2-a5a127627118.png)

## How the feature should work?

It's a static site generator, which should create a static container like Gatsby, Next.js or Nuxt.

## You have examples or an idea how it can be implemented?

I honestly do not know how other static sites are implemented so I can only say `react-static` can be implemented similarly as Gatsby using Server Control Panel.

![server control panel](https://user-images.githubusercontent.com/8465237/52513706-8eca5380-2bda-11e9-9efb-8525838fd1df.png)

**Comment by lbogdan** [comment]
I tried creating a simple example here https://codesandbox.io/s/github/lbogdan/react-static-demo , but it has two issues:
- clicking on links doesn't seem to work (although navigating with the preview's next / previous buttons does)
- the dev server is listening on port 3000, but it looks like the webpack socket, used for HMR, is on port 4000, and we currently don't suport multiple ports in a server sandbox.

**Comment by lbogdan** [comment]
Hey @dance2die ,

I'm gonna close this for now, if you want to research this further, and need assistance, hit us up on [Spectrum](https://spectrum.chat/codesandbox).
