### ISSUE TITLE
Custom manifest.json

### ISSUE THREAD

**Issue by donavon** [codesandbox/codesandbox-client#1532]
# ❔ Question

I have `manifest.json` file in `public`.

![image](https://user-images.githubusercontent.com/887639/52536109-28514c80-2d24-11e9-850f-d6a566ad43ed.png)

But it seems to be overridden.

![image](https://user-images.githubusercontent.com/887639/52536127-5df63580-2d24-11e9-925e-584e07970569.png)

Is there a way that I can have my own `manifest.json` so I can have the name of my app on my Android home screen instead of "React App" (and why isn't it "CodeSandbox" like in the manifest)? Could this be a caching issue?

![image](https://user-images.githubusercontent.com/887639/52536057-dc9ea300-2d23-11e9-9c05-678706a80213.png)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | 
| Operating System |

**Comment by dtinth** [comment]
## Workaround for `create-react-app` template

We will use a custom manifest and service worker file:

- `public/pwa-manifest.json`
- `public/pwa-service-worker.json`

Edit `index.html` file to use a custom `pwa-manifest.json`:

```html
    <link rel="manifest" href="%PUBLIC_URL%/pwa-manifest.json" />
```

Add `<script>` tag to delete CodeSandbox’s auto-generated `<link rel="manifest" href="/manifest.json">` and block CodeSandbox’s service worker:

```html
    <script>
      // https://github.com/codesandbox/codesandbox-client/issues/1532
      // Delete CodeSandbox-generated manifest link tag.
      {
        const codesandboxManifest = document.querySelector(
          'link[rel="manifest"][href="/manifest.json"]'
        );
        if (codesandboxManifest) {
          codesandboxManifest.remove();
        }
      }

      // Replace CodeSandbox’s service worker with our own.
      if ("serviceWorker" in navigator) {
        navigator.serviceWorker.register = (original =>
          function(...args) {
            const [url] = args;
            if (url === "/sandbox-service-worker.js") {
              return new Promise(() => {});
            }
            return original.call(this, ...args);
          })(navigator.serviceWorker.register);
        window.addEventListener("load", () => {
          navigator.serviceWorker.register("/pwa-service-worker.js");
        });
      }
    </script>
```
