### ISSUE TITLE
Angular Cli not keeping ES6 JavaScript code

### ISSUE THREAD

**Issue by AmyScript** [codesandbox/codesandbox-client#1543]
# 🐛 bug report

## Description of the problem
When using the Angular CLI sandbox and a tsconfig.app.json file to configure the "target" to es6, the compiler still transpiles .js files to ES5.  In particular, if you look at the lit-element.js file which is a dependency, all the ES6 classes gets transpiled into ES5 causing the error:

updating-element.js? [sm]:75 Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

## How has this issue affected you? What are you trying to accomplish?
Trying to use web components in Angular CLI in codesandbox without the es5-adapter.  When I have this in my local enivonroment, using the same Angular CLI, I do not have this issue.
###  Link to sandbox: [link]() (optional)
Link to sandbox not working without es5-adapter:
https://codesandbox.io/s/nrxlzl8754
Link to sandbox working with es5-adapter, but the adapter shouldn't be needed is the typescript transpiler is working properly:
https://codesandbox.io/s/538491qzmx
### Your Environment
| Software         | Name/Version|
Angular CLI
| Сodesandbox  | 
| Browser | 
| Operating System |

**Comment by waterplea** [comment]
Any news on this? I also need to use ES6 in my code, but cannot configure it to compile to ES6

**Comment by waterplea** [comment]
Tried all sorts of tsconfig and browserslist placement and configurations. Please take a look, this issue is over a year old and not being able to use es2015 in 2020 is a darn shame. I'm limited to codesandbox because of all online Angular sandboxes it is the only one allowing uploading assets.

**Comment by HristoP96** [comment]
We also have problems with the lack of configuration for es2015 - [https://codesandbox.io/s/igx-grid-custom-summaries-jvpsf](https://codesandbox.io/s/igx-grid-custom-summaries-jvpsf).
And now, given the fact that with the [Angular 10](https://blog.angular.io/version-10-of-angular-now-available-78960babd41) release "The Angular Package Format no longer includes ESM5 or FESM5 bundles", the severity of this issue should be escalated.

**Comment by CompuIves** [comment]
Apologies for the delay, I'm looking at this today and I'm aiming to fix it today as well!

**Comment by HristoP96** [comment]
> Reopening to make sure that everyone can test before closing it, but the example of @HristoP96 is fixed with the last PR! I also saw that the sass transpiling is really slow, took a long time to compile that sandbox, so looking into that now.
> 
> The fix for this should be live in 20min!

@CompuIves The ES6/2015 configuration for Angular projects works as expected and thank you very much for looking into this and provide a fix for it so quickly :)! Also, big thanks for the sass compile optimization, this will really improve the user experience in our [topics](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html)!

**Comment by CompuIves** [comment]
Ahh that's awesome! Really cool, and great to hear that the issue has been resolved.

**Comment by zdrawku** [comment]
Thank you @CompuIves for the prompt reaction for both issues! 🙏
