### ISSUE TITLE
Elm support

### ISSUE THREAD

**Issue by BurntCaramel** [codesandbox/codesandbox-client#155]
Would be pretty amazing to get Elm support, with its simple language, handy libraries, and excellent errors. Currently on holiday but can have a stab at the end of September. There's a webpack plugin which I imagine would make it easier to integrate. However, I think the actual compiler is built using Haskell which would make offline support harder.

**Comment by CompuIves** [comment]
Interesting, I haven't worked with Elm yet, but do know an editor called [Ellie](https://ellie-app.com/new) that's built for Elm. I'm not sure if it's worth it to write an implementation in CodeSandbox, since it would require us to build logic for server side compiling and forces us to build exceptions into offline support.

But I'm open for discussion if there are more reasons, keeping this issue open for further discussion!

**Comment by gillchristian** [comment]
This would be a really awesome addition to CodeSandbox!

I know there's Ellie, but having Elm in CodeSandbox one could benefit from the `now` & GitHub integrations. Another benefit I see (personally it's the main reason why I would like Elm support) is to be able to use the same tool and have all your projects in the same place.

**Comment by BurntCaramel** [comment]
I understand is priority isn’t high. However I’ll just add some more points.

- The author of Ellie has said he will be just keeping it for editing a single file, like a playground, making it pretty unsuitable for ‘real’ projects
- I think Ellie managed to convert the Elm compiler into a web assembler version

Is there somewhere we can see how CodeSandbox works architecturally today, if we did want to add to it? I’ve seen articles mentioning technologies, but I know the bundler has been rewritten a few times so no idea if they are up to date.

**Comment by CompuIves** [comment]
With the current bundler we should be able to support Elm from what I know. I see two points:

1. Elm has its own packages/registry (right?), so we should find a way to support that.
2. We should let the user know that we only support WASM environments

Other than that, it should be possible. I'm interested to see the Elm transpiler, sounds really cool!

**Comment by Baudin999** [comment]
I would also like to see Elm support in CodeSandbox. CodeSandbox has changed the way I teach programming and Elm would be an extremely nice addition.

**Comment by CompuIves** [comment]
I recently saw that Parcel got support for Elm. I think we can learn from them to get support into CodeSandbox.

**Comment by jgrenat** [comment]
I've been trying to set up a codesandbox with Elm through Parcel (Vanilla) but failed. I'm not sure where it fails because Parcel should have support for Elm, right?

**Comment by julianpistorius** [comment]
It seems @SaraVieira got Elm working in mid-April:

https://codesandbox.io/s/pp965v4870

What else is missing besides Elm syntax support in the editor?

**Comment by jgrenat** [comment]
Ideally, being capable to run elm-format to reformat source on save, but I feel like this is something we can add ourselves inside the package.json file.

**Comment by SaraVieira** [comment]
I am gonna install the elm syntax highlighter so we can get full support
