### ISSUE TITLE
In Reason projects, adding `graphql_ppx` or `reason-apollo` from npm both trigger dependency error

### ISSUE THREAD

**Issue by sgrove** [codesandbox/codesandbox-client#1556]
# 🐛 bug report

After creating a fresh Reason sandbox, I tried adding `reason-apollo` to the `package.json` dependencies section, but seems like it triggered an error (mentioned below).

If I also add `"graphql_ppx": "0.2.8"` to the `devDependencies`, I get the *same* error. So if I have just `reason-apollo` or `graphql_ppx` I get 1 instance of the error, and if I have both, I get 2.

## Description of the problem

> Could not fetch dependencies, please try again in a couple seconds: Something went wrong while packaging the dependency reason-apollo@0.15.2: ENOENT: no such file or directory, scandir '/tmp/505487899/node_modules/reason-apollo/graphql-types'

## How has this issue affected you? What are you trying to accomplish?

I was trying to build an example reason-apollo GraphQL example so people could try [this kind of experience](https://www.youtube.com/watch?v=yMqE37LqRLA) much more easily.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1550571673-271bb38a |
| Browser | Chrome (and Safari) |
| Operating System | OSX |

**Comment by lbogdan** [comment]
Hey @sgrove , for Apollo / GraphQL you probably need to use a [server sandbox](https://hackernoon.com/codesandbox-containers-5864a8f26715) , something like https://codesandbox.io/s/apollo-server .

**Comment by sgrove** [comment]
@lbogdan Just to be sure, is that even if I'm doing a pure browser/client implementation?

**Comment by lbogdan** [comment]
Oh, right, if it's supposed to work in the browser, it should work. Looks like a bundler issue, cc @CompuIves .

**Comment by mlms13** [comment]
Have you been able to add _any_ dependencies to a Reason project @sgrove? I tried both `bs-decode` and `relude` and I get similar errors.
