### ISSUE TITLE
Github not working on local integration

### ISSUE THREAD

**Issue by evanoralph** [codesandbox/codesandbox-client#1558]
# ❔ Question

Already install the codesandbox and its really great but i think Im missing the github module when i go to login with git hub I just see this page 

![image](https://user-images.githubusercontent.com/13017438/53147770-895e0780-35e3-11e9-846b-af9a26da7d11.png)

do i have to install something ?

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  latest
| Browser |  chrome
| Operating System | mac os

**Comment by lbogdan** [comment]
Hey @evanoralph ,

Do you still have issues with logging in with GitHub? It should work without you having to install anything (which is the whole idea of using CodeSandbox 🙂 ). If you do, can you please tell us exactly what you're doing, step by step? Thanks!

**Comment by SaraVieira** [comment]
Closed on lack of reply, please re open if the issue persist :)
