### ISSUE TITLE
🌈 Feature: code review

### ISSUE THREAD

**Issue by dimaip** [codesandbox/codesandbox-client#1566]
Here's a usecase for you: I'm mentoring my cousin to do web development. Codesandbox helps him to get started writing code without having to setup local environment, which is cool!

Obviously he writes not very clean code, and so I'd like to be able to leave feedback on the code that he wrote, possible suggesting changes. In other words something similar to Github functionality.

**Comment by lbogdan** [comment]
Hey @dimaip ,

While a full-featured code review feature would be awesome, it's not really something we'll be pursuing in the foreseeable future. What you could do is fork his sandboxes and add lots of comments to them. 🙂 
Or even export them to github, commit the fixes there, and import them back into CodeSandbox.

**Comment by dimaip** [comment]
@lbogdan for now we go into Live mode and there I can leave comments in his code without forking.
Unfortunately it's not possible to keep the Live mode forever, so I have to keep on asking him to re-enable it when I want to leave feedback.

Anyways, I think the idea of online mentoring has a lot of potential, give it another thought ;)
