### ISSUE TITLE
Import git from url (Github, Gitlab, Bitbucket support, etc)

### ISSUE THREAD

**Issue by garygreen** [codesandbox/codesandbox-client#1567]
# 🌈 Feature

```js
import ArrowTable from 'https://github.com/garygreen/arrow-table' // ".git" is automatically added.

ArrowTable.blah();
```

It would be so cool if importing from urls could be supported. This means technically CodeSandbox would support ANY service that provides a git url, so Gitlab, Bitbucket, etc. It would make it easier to fork/collaborate/PR on projects

How I see this working is it would create a new folder for each cloned repository which is "sandboxed" from the standard/default folder of CodeSandbox. So basically almost like a `node_modules` folder but maybe called `repositories` or something. Then it can allow you to edit those repository, see changes and push back to Git that would be awesome.

![image](https://user-images.githubusercontent.com/1702638/53502997-236ff500-3aa7-11e9-95d1-b6f1a11feabd.png)

**Comment by rayfoss** [comment]
This is a duplicate of #829 a very popular issue, that also had bots go heywire and close it.

Bringing this up due to a fundamentally misguided marketing email:
```
Open a PR with a single
click as part of the tight
integration with Git.
```

The Git doesn't have a concept of PR... and you don't even remotely support git.
