### ISSUE TITLE
GitHub import then save changes fails - error's out with request entity too large

### ISSUE THREAD

**Issue by NawarA** [codesandbox/codesandbox-client#1581]
# 🐛 bug report

## Description of the problem
Can't push changes to GitHub. Your internal "diff" logic fails, and pops up to the user the following error: "request entity too large"

https://codesandbox.io/api/v1/sandboxes/yqq6jz70lj/git/diff
returns 
errors: {detail: ["request entity too large"]}

By the way, I have this same sandbox working, but I didnt import it from GitHub. It seems GitHub intergration works, unless you're importing from GitHub, in which case the software breaks, because everything is diff? Just connecting the dots

## How has this issue affected you? What are you trying to accomplish?
I imported my sandbox from GitHub. But if I make any changes, I cant save them back to GitHub. 

This makes the sandbox not savable to GitHub, which is a requirement for me.

###  Link to sandbox: [link]() (optional)
https://yqq6jz70lj.codesandbox.io/

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  Latest version
| Browser | Chrome 72.0.3626.119
| Operating System | Windows 10

**Comment by zommerfelds** [comment]
I'm also having this issue. Not being able to save changes back to GitHub makes me not able to use CodeSandbox for now.
Also Chrome on Windows.
![image](https://user-images.githubusercontent.com/1260622/57199948-6e195c00-6f85-11e9-9399-e37e4312d624.png)

**Comment by zommerfelds** [comment]
Looks like it's working for me now.

**Comment by edp-rolfs** [comment]
I'm having this issue, too. Small private org repo (Patron).

Latest Chrome version on Windows, but also latest version of Safari Browser on iOS 12.2 (iPad).

**Comment by garethx** [comment]
Can you try it again? We've made some changes, which will hopefully have resolved this. Thanks.
