### ISSUE TITLE
Github embeds have corrupted file tree

### ISSUE THREAD

**Issue by looeee** [codesandbox/codesandbox-client#1589]
# 🐛 bug report

This link works fine:
https://codesandbox.io/s/github/looeee/discoverthree.com-examples/tree/master/bare-template

However, this one displays a load of garbage characters while loading, and also after loading where the file tree should be:
https://codesandbox.io/embed/github/looeee/discoverthree.com-examples/tree/master/bare-template

The same happens when the embed link is actually embedded in a page:
https://discoverthreejs.com/book/1-first-steps/7-load-models/

Seems to be just github sandboxes, since both of these (new vanilla sandbox) work just fine:
https://codesandbox.io/s/r0p3qn54wq
https://codesandbox.io/embed/r0p3qn54wq

There's some error messages in the console that are not there in the /s/ version:

```
VM676 bare-template:1 Uncaught SyntaxError: Unexpected identifier
mobx.module.js:2652 Uncaught Error: [mobx] An invariant failed, however the error is obfuscated because this is an production build.
    at yt (mobx.module.js:2652)
    at mt (mobx.module.js:2647)
    at mobx.module.js:2877
```

Also some messages about "failed to parse sourcemap", I guess those are not relevant though. 

Tested on Chrome 73.0.3683.67 and FF 65.0.2 with all extensions disabled

**Comment by CompuIves** [comment]
Hey! Thanks for letting us know, I removed the preloading for now until I find a better fix.

**Comment by looeee** [comment]
Great, that's fixed it for now. Thanks!

**Comment by christianalfoni** [comment]
Closing this as it is fixed :)
