### ISSUE TITLE
Feature request: Working directory not a git repository

### ISSUE THREAD

**Issue by 00-1** [codesandbox/codesandbox-client#1590]
# 🌈 Feature

The working directory in a server sandbox isn't a git repository: 

```
sandbox@sse-sandbox- ... :/sandbox$ ls -a
.  ..  node_modules  package-lock.json  package.json  sandbox.config.json  src  yarn.lock
sandbox@sse-sandbox- ... :/sandbox$ git status
fatal: Not a git repository (or any parent up to mount point /sandbox)
```

I think it should be. There are a number of basic git features missing from the GUI (e.g. `git diff`), and allowing these to be run from the terminal seems like an easy win.

**Comment by lbogdan** [comment]
Hey @00-1 ,

I see this as a non-issue, while some users might find this useful, I'm not sure we should do this by default. It's only a matter of running `git init; git config user.email "janedoe@example.com"; git config user.name "Jane Doe"; echo node_modules >.gitignore; git add -A; git commit -m "initial commit"` when needed.

I'll leave this opened, though, as we might switch to git repositories as a source of truth for server sandboxes in the future.

**Comment by j-oshb** [comment]
Thanks for the reply @lbogdan 

By the way I did try that but I ran in to rate-limiting issues & gave up with it. But I guess that's for a different issue.

**Comment by lbogdan** [comment]
> but I ran in to rate-limiting issues
If you mean the "10 updates in less than 2 seconds" notification, that should be fixed now.
