### ISSUE TITLE
HMR is not working

### ISSUE THREAD

**Issue by lstkz** [codesandbox/codesandbox-client#1594]
# 🐛 bug report

## Description of the problem

Here I can see that HMR should be working properly in React + Redux apps
https://hackernoon.com/announcing-codesandbox-2-5-be767d15ffd. However, I can't find the example source code from the above demo.

Here is an example sandbox https://codesandbox.io/s/oxz2rjr2kz. HMR works properly if you run it locally.

### Steps
- open above sandbox
- click on the 'increase' button in the preview
- 'count' should increase from 0 to 1
- edit src/features/counter/components/Counter.tsx and change any text
- count is reset to 0

### Expected
- count should be still 1
 
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  latest
| Browser | Chrome 72
| Operating System | Mac 10.13

**Comment by lbogdan** [comment]
Hey @BetterCallSky ,

As we're trying to exactly mirror `create-react-app` features, there's no support for HMR in the CRA CodeSandbox template, either.

If you look closely at the image you pointed to, you'll see that we're explicitly using the `module.hot` API there.

 Closing this, as it's expected behavior.

**Comment by BetterCallSky** [comment]
I am also using `module.hot` in my example. It's custom code, but HMR is not working.
Can you provide a code sandbox link for this demo?

![image](https://cdn-images-1.medium.com/max/2400/1*H04vTxKLqhaSir2XGv-PYw.gif)

The blog post doesn't have any references to the example demo. There is only a vue app.

**Comment by lbogdan** [comment]
Reopening and marking it as (maybe) a bug.

**Comment by lbogdan** [comment]
I can confirm it works locally, so I guess the question now is what exactly does that `onHmr()` imported from `typeless` does?
cc @CompuIves

**Comment by BetterCallSky** [comment]
https://github.com/typeless-js/typeless/blob/master/packages/typeless/src/onHmr.ts

It doesn't do anything related to webpack or `module.hot`.
