### ISSUE TITLE
Quasar Vue.js framework repo

### ISSUE THREAD

**Issue by dann4566165** [codesandbox/codesandbox-client#1601]
I have yet to get any github repos to import through the wizard and actually work. The latest i've tried is here: https://github.com/quasarframework/quasar/tree/dev/app

And i get:

"Error
Could not fetch dependencies, please try again in a couple seconds: Your key is too long"

Any suggestions for getting this to work?

**Comment by lbogdan** [comment]
Hey @dann4566165 ,

What are you trying to achieve, exactly? From what I understand, that's the Quasar CLI app, so I'm a bit confused of why you would want to open it in CodeSandbox.

**Comment by SaraVieira** [comment]
Closed on lack of reply, please re open if the issue persist :)
