### ISSUE TITLE
browser entry of packages ignored

### ISSUE THREAD

**Issue by eps1lon** [codesandbox/codesandbox-client#1602]
# 🐛 bug report

## Description of the problem
Using [`object-hash`](https://www.npmjs.com/package/object-hash) is triggering 
> Cannot read property 'crypto' of undefined

in the client but not when running locally.
Edit: What I meant by locally is that that I can download the sandbox, start it locally and it does not crash in the browser.

It comes down to codesandbox ignoring the `browser` entry. It may not even implement `webpack`'s `mainFields` resolution at all. Searching through the repo ironically only found `mainFields` in their own webpack.config. 

## How has this issue affected you? What are you trying to accomplish?
Creating a hash for an object.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1552372285-96510b09
| Browser | Version 72.0.3626.121 (Official Build) (64-bit)
| Operating System | Ubuntu 18.04.2 LTS

**Comment by lbogdan** [comment]
Hey @eps1lon ,

That's because the `object-hash` package is using the [Node.js crypto API](https://nodejs.org/api/crypto.html), and as your sandbox is completely running in the browser, that's not available.

What you can do is use a server sandbox (which just [got out of beta yesterday](https://medium.com/@compuives/codesandbox-containers-out-of-beta-improvements-be79679df4cc)!), which runs in a container, and as such can fully replicate a local development environment. I made one starting from your sandbox here: https://codesandbox.io/s/y3j335o17x .

It's a bit cumbersome at the moment - you'll have to fork the [node sandbox](https://codesandbox.io/s/node) and copy files one by one, at least that's what I did -, but we'll make it easier to switch between browser and server sandboxes soon enough!

**Comment by lbogdan** [comment]
Also closing this, as it's expected behavior.

**Comment by eps1lon** [comment]
> That's because the object-hash package is using the Node.js crypto API, and as your sandbox is completely running in the browser, that's not available.

`object-hash` is supposed to run in the browser and has set the `browser` field in `package.json` specifically for that purpose. 

[`webpack` respects this by default](https://webpack.js.org/configuration/resolve/#resolvemainfields). I guess codesandbox is either ignoring this or changing the priority. Is there a reason for this?


@lbogdan Please consider re-opening this. I suspect that there are plenty more packages affected that use the `browser` field.

**Comment by lbogdan** [comment]
Ah, sorry, I completely missed the `browser` entry in `package.json`! I remember we honoring this, we'll take a look at why that doesn't work in this case. Reopening and marking this as a bug.

**Comment by lbogdan** [comment]
**Update**: after @CompuIves took a look at it, we're indeed honoring the `browser` entry, the bug seems to be related to the code in `/dist/object_hash.js`.

**Comment by eps1lon** [comment]
> Update: after @CompuIves took a look at it, we're indeed honoring the browser entry, the bug seems to be related to the code in /dist/object_hash.js .

I updated my initial post to clarify what I meant with "locally":
> Edit: What I meant by locally is that that I can download the sandbox, start it locally and it does not crash in the browser.

So there is a difference between `webpack` and `sandpack`. `object-hash` is running in the browser if bundled by `webpack` with a config from `react-scripts`.

**Comment by lbogdan** [comment]
Coincidentally, it's also working with our new packager, which we're yet to switch to. We'll let you know as soon as we have an update on that!

**Comment by eps1lon** [comment]
Confirmed that the issue still exists.

**Comment by SaraVieira** [comment]
Closing this as I just confirmed newer versions of the library work confirming what Bogdan said that we do support the browser option but there was a problem in that specific version 

Hope this makes sense to you

**Comment by eps1lon** [comment]
@SaraVieira That doesn't make sense to me. The codesandbox linked in the initial issue description still reproduces the original error with codesandbox version 7bf3f2414.

**Comment by lbogdan** [comment]
@eps1lon I guess what @SaraVieira was trying to say is that it works with a newer version of `object-hash`: https://codesandbox.io/s/object-hash-forked-u1zw1 .

**Comment by SaraVieira** [comment]
Yes, sorry. What I mean is that it works with newer versions of object hash

It was an issue with that specific version that's old
