### ISSUE TITLE
Storybook support in codesandbox

### ISSUE THREAD

**Issue by cherouvim** [codesandbox/codesandbox-client#1603]
Is it possible to run storybook in codesandbox?

**Comment by libetl** [comment]
Please join discord, this is exactly what I am doing.
https://discordapp.com/channels/486522875931656193/506368735376834560
(I work for storybook)

**Comment by libetl** [comment]
https://codesandbox.io/s/github/libetl/storybook-to-codesandbox-test

**Comment by cherouvim** [comment]
That test looks great. Is there a way to have the storybook UI which shows the list of stories on the left?

**Comment by libetl** [comment]
You should join our discord so we can chat

**Comment by lbogdan** [comment]
@cherouvim Did @libetl ask your question, can you / we close this?

@libetl An article / blog post showcasing how one can use Storybook in CodeSandbox would be awesome! 😉

**Comment by libetl** [comment]
Hi,

This is work in progress.
I first want to focus on compatibility with vue-cli, ember, preact and so on.
We will document and demo that then the feature is ready to ship.

**Comment by abumuawiyah** [comment]
@libetl the codesandbox is awesome!

**Comment by siddharthkp** [comment]
@libetl This is great! You should create a `template` from this so that others can also use this as a base (we are working on improving the discovery of templates 🤫)

**Comment by siddharthkp** [comment]
@libetl Is there a pull request / issue we can track along with this one. I'd like to keep an eye 👀 on the compatibility work so that we can help out if needed

**Comment by libetl** [comment]
Sorry, I did not put my eyes anywhere in storybook lately because we had some big team problems in my regular job.

The feature is in *very* stale status, because :
1) it is hard to keep the feature up to date with all the major compilation and build pipeline changes in the storybook repository
2) the sandpack project is in abandoned status
