### ISSUE TITLE
Chrash when using babel-plugin-macro with relay modern

### ISSUE THREAD

**Issue by sibelius** [codesandbox/codesandbox-client#1604]
# 🐛 bug report

## Description of the problem
I'm trying to setup a CRA + Relay Modern project on codesandbox but it is crashing

## How has this issue affected you? What are you trying to accomplish?

Here is the stackframe of the problem:

```jsx
▼ 10 stack frames were expanded.
X
https://codesandbox.io/static/js/sandbox.a4ae5fac.js:1:109446
Worker.<anonymous>
https://codesandbox.io/static/js/sandbox.a4ae5fac.js:1:112426
g
https://codesandbox.io/static/js/common-sandbox.429cae97.chunk.js:1:431249
Generator._invoke
https://codesandbox.io/static/js/common-sandbox.429cae97.chunk.js:1:431037
Generator.e.(anonymous function) [as next]
https://codesandbox.io/static/js/common-sandbox.429cae97.chunk.js:1:431428
o
https://codesandbox.io/static/js/common-sandbox.429cae97.chunk.js:1:8214
```

this only happen when I add the following

```
query={graphql`
          query AppQuery {
            me {
              id
              name
            }
          }
        `}
```

### Your Environment
| Software         | Name/Version|
| macOS Mojave |10.14.3 |
| Сodesandbox  | https://codesandbox.io/s/k03vr4q35v
| Browser | Chrome 
| Operating System |Mac

**Comment by sibelius** [comment]
I've got more errors logs

```jsx
TypeError: Cannot read property 'setAsyncMode' of undefined
	at Object.t.createSpdLogService (extensionHostProcess.js:1)
	at new t (extensionHostProcess.js:1)
	at new e (extensionHostProcess.js:1)
	at extensionHostProcess.js:1
```

```jsx
Object
found: false
id: 4169
type: "resolve-async-transpiled-module-response"
__proto__: Object
```

```jsx
Error
    at Q (worker-error-handler.js:22)
    at Worker.<anonymous> (worker-transpiler.js:134)
    at g (runtime.js:62)
    at Generator._invoke (runtime.js:288)
    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.7efdb2bf.chunk.js:1:475704)
    at o (asyncToGenerator.js:3)
    at i (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at Worker.<anonymous> (asyncToGenerator.js:21)
    at Worker.<anonymous> (worker-transpiler.js:129)
```

**Comment by siddharthkp** [comment]
@SaraVieira @CompuIves do you have an idea of what's happening here?

**Comment by CompuIves** [comment]
Seems like a vscode extension isn't working well, that's very weird. I'm taking a look tomorrow!

**Comment by thicodes** [comment]
works here, but i compiled local, after that i updated the file
https://codesandbox.io/s/create-react-app-relay-modern-gkr3t?file=/src/App.js

how can i works create-react-app and the terminal for i use the cli to compile the graphql?

**Comment by sibelius** [comment]
it looks like @thicodes got Relay working https://codesandbox.io/s/create-react-app-relay-modern-gkr3t?file=/src/App.js

one problem that we hit is that relay needs to run relay-compiler to regenerate __generated__ files

any ideas of how to achieve this in codesandbox?
