### ISSUE TITLE
Make the "Dashboard" button a Modal Toggle instead of a Navigation

### ISSUE THREAD

**Issue by Saeris** [codesandbox/codesandbox-client#1613]
Currently, when you click the new Dashboard icon in the upper-left hand corner of the Editor, it will navigate the user away from the current sandbox. I think this experience could be improved if instead it behaved like a modal toggle, as it becomes unclear how a user can get back to the sandbox they were just viewing. As a bonus, the Dashboard itself could become a more useful information hub that users could jump back and forth from while using the editor.

For an example of how this would work, consider a similar interaction to the "File" menu in the Microsoft Office family of products.

**Comment by SaraVieira** [comment]
Hey!

Its me again

Let me see if I understand: You mean a modal with the dashboard?

Something like the storage modal ?

![Screenshot 2019-03-19 at 17 11 46](https://user-images.githubusercontent.com/1051509/54622574-1d4bb380-4a6a-11e9-92fa-e34f87f2b10a.png)

**Comment by Saeris** [comment]
No I mean the new icon at the top left of the new Editor UI as pictured here:

![image](https://user-images.githubusercontent.com/3144549/54623533-eb662d00-4a28-11e9-9edf-c636ed0ded47.png)

**Comment by Saeris** [comment]
And by modal, I mean clicking that icon should open basically the same Dashboard page as it does now, except in the same place should be a return button, similar to the Office UI pictured here:

![image](https://user-images.githubusercontent.com/3144549/54623677-3e3fe480-4a29-11e9-9316-3b77118c438a.png)

**Comment by Saeris** [comment]
A full-screen modal would be fine, so long as there is some intuitive feedback as to how the user got to the page they are currently viewing and how to quickly get back to where they were. The Dashboard right now is just a list of recent projects, but it could also be a place for other features, such as say a contacts list (to quickly invite people to a shared code session), a feedback form (to quickly file issues), Account settings, etc.

**Comment by SaraVieira** [comment]
I see what you mean but by adding that we would remove any way for the user to go to the homepage 

The modal idea was what I understood, I don't think it would be very fitting for the dashboard since it has so many things going on

**Comment by SaraVieira** [comment]
Also the features for the dashboard would be amazing!

**Comment by Saeris** [comment]
Well, if features like that were to be added to the Dashboard (which would necessitate it needing a new layout anyways), then a link to the homepage could be put somewhere else, which would be a little more explicit about the fact that it's taking you to the homepage.

Though it should be noted that right now, if you're logged in and navigate to the home URL, you get redirected to the Dashboard anyways. It's only with `https://codesandbox.io/?from-app=1` can you navigate to the homepage while logged in, which in itself is frustrating.

But I do wonder, how often do people need to go to the homepage for anything? They can create new sandboxes straight from the Dashboard, and they can access search and navigate to the explore page. About all that's missing is a link to the documentation and github repository. Much of that could do with some re-thinking going forward, in my opinion at least.

The way I see it, the Editor is the core of the CSB experience, everything else is preferences, situational tools, and access to resources, much of which will direct a user back towards the Editor. So anything that minimizes the time it takes to move back and forth between the Editor and those other parts of the site should be a top priority. Anything that would explicitly navigate away from the currently active project should be explicit about leaving, and preferably, opening another sandbox will do so in a new window (much like if you were to open another project in VSCode, you'd have another window open).

To be fair, all of that is in consideration of the bigger picture. Take what I have to say as feedback. Overall it's not _that_ important to implement the original request.
