### ISSUE TITLE
🐛 "Import from GitHub" link in the "New Sandbox" modal shouldn't take the user to the documentation page.

### ISSUE THREAD

**Issue by Saeris** [codesandbox/codesandbox-client#1614]
As the title says, when a user clicks the "Import from GitHub" link in the "New Sandbox" modal menu, instead of asking you for a GitHub repository URL, it redirects the user to the documentation page, where it becomes unclear what the user should do next. They would have to then click the "Import Wizard" link in the documentation, which is another page navigation.

Similarly, the "Export with CLI" and "Create with API" links will take the user to the documentation page. These links should have an icon to indicate that they will take the user to another page.

**Comment by SaraVieira** [comment]
Fixed with the new Create Sandbox Modal 🎉
