### ISSUE TITLE
🌈 Allow users to move Console/Terminal/Problems UI to it's old position beneath the Code area

### ISSUE THREAD

**Issue by Saeris** [codesandbox/codesandbox-client#1616]
As the title says, with the V3 editor there doesn't seem to be a way to restore the previous layout where the "console" UI split with the code editor.  The current behavior, where it splits screen space with the browser preview/tests pane also breaks from the standard VSCode editor layout. In addition, the console is hidden entirely if the preview panel is toggled off. While users can resize the console to fill the entire preview panel, there is no option for a stacked view for code + console.

**Comment by Saeris** [comment]
Update: I found that by clicking View > Editor Layout > Flip Full Layout that I was able to get the "stacked" view which would allow for just the console + code areas. See screenshot below for example:

![image](https://user-images.githubusercontent.com/3144549/54627405-99290a00-4a30-11e9-839c-53d04632160b.png)

**Comment by vipzero** [comment]
> **Update:** I found that by clicking `View > Editor Layout > Flip Full Layout` that I was able to get the "stacked" view which would allow for just the console + code areas. See screenshot below for example:

I've been looking for this. Thank you.
This UI was very difficult to understand.

**Comment by Victor-Villacis** [comment]
There is no quick action to flip the preview to the fight or the bottom. One needs to go into the settings to find this. Very cubersome

**Comment by JamesACS** [comment]
Hey @Victor-Villacis - Thanks for the feedback - I'll add a more convenient action to this to our feature requests board!
