### ISSUE TITLE
No code actions available

### ISSUE THREAD

**Issue by donavon** [codesandbox/codesandbox-client#1619]
# 🐛 bug report

## Description of the problem

elint correctly detects missing dependencies, but the auto "Quick fix" feature is not working and gives a "no code actions available" message.

![codesandbox](https://user-images.githubusercontent.com/887639/54641274-2e93c080-4a68-11e9-9ebd-6b0607267804.gif)

## How has this issue affected you? What are you trying to accomplish?
trying to automatically add dependencies to hooks

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1553021361-2ab67983 
| Browser | Chrome 723 |
| Operating System | macOS |

**Comment by lbogdan** [comment]
Hey @donavon , is this working in VSCode? (I assume yes, but just wanted to make sure 🙂 )

**Comment by donavon** [comment]
yes, it's working just fine

**Comment by CompuIves** [comment]
This will be fixed once we install the `vscode-eslint` extension
