### ISSUE TITLE
🌈 Feature Request: Support SASS_PATH environment variable or includePaths

### ISSUE THREAD

**Issue by mlaursen** [codesandbox/codesandbox-client#1629]
# 🌈 Feature Request
Add support for the [includePaths](https://github.com/sass/node-sass#includepaths) option for compiling Sass either through the `SASS_PATH` environment variable or another way.

### What is this feature?
It would be extremely helpful if the `SASS_PATH` environment variable could be used so that when compiling Sass, you can include the `node_modules` folder. Right now, there is support for using a `~` with the imports to import from `node_modules`, but when the library you are using relies on the Sass include paths to contain `node_modules` (like [material-components-web](https://github.com/material-components/material-components-web) or [my library](https://github.com/mlaursen/react-md/tree/next)) it'll break.

This feature is also supported by create-react-app and is in their documentation for [adding a Sass stylesheet](https://facebook.github.io/create-react-app/docs/adding-a-sass-stylesheet). 

### How the feature should work?
Update the `.env` file to have:

```sh
SASS_PATH=node_modules:src

# any other supported environment variables
```

### Examples
I have [this sandbox](https://codesandbox.io/s/k3n3yqm1z7) as a good example for this use case. I currently have commented out all the `@import` statements so that it'll compile, but once the `SASS_PATH` environment variable is supported it should work when all/any have been uncommented.

If this feature has already been implemented in some other manner, I'd be happy to go down that route instead as well -- I searched for a bit and couldn't find any examples on how to do this. I have also tried doing the old documented way from create-react-app to have a separate node-sass watcher to compile, but that didn't seem to work either.

**Comment by bruqui** [comment]
Anything new on this? I would very much like to get the [material-components-web-react](https://github.com/material-components/material-components-web-react) library working so I don't get errors like this...

> Could not find /node_modules/@material/react-text-field/icon/node_modules/@material/textfield/icon/mdc-text-field-icon on line 23:9 of node_modules/@material/react-text-field/icon/index.scss
