### ISSUE TITLE
hidden .env variables in config

### ISSUE THREAD

**Issue by tgrrr** [codesandbox/codesandbox-client#1632]
# 🌈 Feature

Allow private `.env` (or other) variables to be added in the configuration section

It's a popular request, see:
https://github.com/CompuIves/codesandbox-client/issues/1373
https://github.com/CompuIves/codesandbox-client/issues/1629
https://github.com/CompuIves/codesandbox-client/issues/1119

Add UPPERCASE_VARIABLES in the configuration section
Variables are globally accessible in the sandbox as UPPERCASE_VARIABLES
This would allow us to demo things like a google map api, without exposing our keys to the world.

create react app, dotenv, etc are all fine.

Here's an example that I couldn't finish without exposing my keys to the world:
https://codesandbox.io/s/z3vrzpz7m

**Comment by SaraVieira** [comment]
Hey!

We don't support in all things but we do support it in create react app as you can see here:
https://codesandbox.io/s/94y2j24k3y

This is supported because its a default in create reacxt

**Comment by SaraVieira** [comment]
Sorry, my mistake!

Yeah, this has been something we been thinking of and could write to a .env file that would be inivisble

**Comment by Lathryx** [comment]
I see that _server sandboxes_ have the ability to contain secrets, but what about using secrets in something like the `create-react-app` template, which _isn't_ a server sandbox, but often uses secrets for `API keys` and such?

**Comment by andrasbacsai** [comment]
As @lbogdan wrote before:
> As sandboxes run in the browser, there's really no way to have secrets inside a sandbox because if the users' browser has access to them (and it of course needs access during execution), users will also have access to them. "Hiding" or obfuscating them somehow won't work, as security by obscurity is never a good idea.

If there will be such a feature in the browser sandboxes, it will be visible to everybody. That's why it is not implemented.
