### ISSUE TITLE
Rename variable w/F2 gives "Canceled: Canceled" toast

### ISSUE THREAD

**Issue by donavon** [codesandbox/codesandbox-client#1637]
# 🐛 bug report

## Description of the problem

Press F2 on a variable in JavaScript. Rename the variable. It works, but produces the folowing message:

![image](https://user-images.githubusercontent.com/887639/54759603-ce666100-4bc4-11e9-89cd-2bf6b8812ce3.png)

## How has this issue affected you? What are you trying to accomplish?

I'm deeply effected–emotionally.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1553110796-db8af2f08 |
| Browser | Chrome 73 |
| Operating System | macOS Mojave |

**Comment by CompuIves** [comment]
😂 I would be "deeply effected–emotionally" as well! I'll take a look 😄

**Comment by arthurdenner** [comment]
@donavon, does this still happening to you? If so, could you describe some steps to reproduce? I tried but it didn't happen, the variable was renamed as expected without alerts.

**Comment by donavon** [comment]
It appears to be working now. closing
