### ISSUE TITLE
Popup errors don't have high enough z-index

### ISSUE THREAD

**Issue by ffxsam** [codesandbox/codesandbox-client#1638]
# 🐛 bug report

## Description of the problem
Popup errors are obscured by other UI elements

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1553110796-db8af2f08
| Browser | Chrome 73
| Operating System | macOS 10.14.3

![image](https://user-images.githubusercontent.com/12532733/54761575-57c76480-4bc0-11e9-898a-d77441df69b7.png)

**Comment by SaraVieira** [comment]
Better late than ever but this has been fixed 🎉
