### ISSUE TITLE
unable to run simple Vue example in codesandbox

### ISSUE THREAD

**Issue by paramquery** [codesandbox/codesandbox-client#1643]
Hi

I'm new to codesandbox and vue, learning by working on few simple exercises.

codesandbox looks an awesome tool for code prototyping and sharing.

One such example is https://codesandbox.io/s/kyo4n5ylo 

It works fine in local environment but refuses to work in codesandbox with some clueless errors.

Can someone please help me out on this what's wrong here. Is it a bug or unsupported feature in codesandbox or I'm doing some silly mistake.

**Comment by lbogdan** [comment]
Hey @paramquery ,

At a first glance, it looks like `pqgridtest1` uses ES6 syntax (see https://unpkg.com/pqgridtest1@0.0.0/index.js ), which a "normal" npm module shouldn't (see my comment [here](https://github.com/CompuIves/codesandbox-client/issues/1631#issuecomment-475332461) ). Nevertheless, we're transpiling modules to ES5 whenever we see ES6 syntax, so this should work, in theory. We'll take a look and get back to you.

Also, I tried the sandbox locally, and this is all I got:

![image](https://user-images.githubusercontent.com/2083930/54810437-cd9a0180-4c8e-11e9-907d-2b7a22992f5f.png)

Looking at the source, I would've expected to see some kind of grid. Does the grid show for you?

**Comment by paramquery** [comment]
Hi Bogdan

Thanks for checking it out. 

Grid appears on http://localhost:8080/vue.html without any errors or issues.

pqgridtest1 module core is completely written in ES5, except few import and export statements ( ES6 syntax ) and require ( commonjs)

Any other clues?

Thanks a lot!
Paramvir

**Comment by paramquery** [comment]
I've replaced ES6 imports with commonjs require() in pqgridtest1 (v0.0.1)

I'm getting new set of errors, jQuery is not defined in jqueryui widgets. 

As jqueryui modules are AMD modules, I'm wondering whether codesandbox supports only commonjs modules.

**Comment by lbogdan** [comment]
Cc @CompuIves

**Comment by CompuIves** [comment]
It seems like this sandbox is working now! Let's open a new issue if there's still a problem coming up 😄 .
