### ISSUE TITLE
TypeScript Support Broken: API Lambda Failures

### ISSUE THREAD

**Issue by JasonGore** [codesandbox/codesandbox-client#1647]
# 🐛 bug report

## Description of the problem

TypeScript API lambda fetcher that CodeSandbox appears to use fails for NPM modules, resulting in `Cannot find module` errors.

![image](https://user-images.githubusercontent.com/26070760/54854758-3c885200-4cb1-11e9-9c8a-b237a11690eb.png)

![image](https://user-images.githubusercontent.com/26070760/54854707-0b0f8680-4cb1-11e9-82c2-e2447f817683.png)

As far as I can tell, the [API lambda](https://ata-fetcher.cloud/api) is failing in network calls. When I attempt to load the same links I see CodeSandbox requesting manually, I frequently get one of the errors shown in the image below.

Sample lambda links failing:
- https://ata-fetcher.cloud/api/v5/typings/office-ui-fabric-react@6.158.0.json
- https://ata-fetcher.cloud/api/v5/typings/@uifabric/experiments@6.64.2.json

![image](https://user-images.githubusercontent.com/26070760/54854552-8886c700-4cb0-11e9-949c-462510e46166.png)

Oddly sometimes these links also work but have a bunch of odd results in the bundle, like "Not enough storage available on device!". It makes me think there's some backend issue or error with the lambda. 

Sorry if this isn't the right place to report this issue, but I'm not sure who else to report it with.

[EDIT]
This is even failing for common modules like `react-dom`:

I got this response from this link: https://ata-fetcher.cloud/api/v5/typings/react-dom@16.8.4.json

```
{"status":"error","files":{},"error":"Command failed: cd /tmp && mkdir 50d04677 && cd 50d04677 && HOME=/tmp npm i --production react-dom@16.8.4 --no-save\nnpm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ENOSPC: ENOSPC: no space left on device, write\nnpm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.\nnpm ERR! code ENOSPC\nnpm ERR! errno -28\nnpm ERR! syscall write\nnpm ERR! nospc ENOSPC: no space left on device, write\nnpm ERR! nospc There appears to be insufficient space on your system to finish.\nnpm ERR! nospc Clear up some disk space and try again.\n\n┌──────────────────────────────────────────────────┐\n│             npm update check failed              │\n│       Try running with sudo or get access        │\n│       to the local update config store via       │\n│ sudo chown -R $USER:$(id -gn $USER) /tmp/.config │\n└──────────────────────────────────────────────────┘\n","stack":"Error: Command failed: cd /tmp && mkdir 50d04677 && cd 50d04677 && HOME=/tmp npm i --production react-dom@16.8.4 --no-save\nnpm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ENOSPC: ENOSPC: no space left on device, write\nnpm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.\nnpm ERR! code ENOSPC\nnpm ERR! errno -28\nnpm ERR! syscall write\nnpm ERR! nospc ENOSPC: no space left on device, write\nnpm ERR! nospc There appears to be insufficient space on your system to finish.\nnpm ERR! nospc Clear up some disk space and try again.\n\n┌──────────────────────────────────────────────────┐\n│             npm update check failed              │\n│       Try running with sudo or get access        │\n│       to the local update config store via       │\n│ sudo chown -R $USER:$(id -gn $USER) /tmp/.config │\n└──────────────────────────────────────────────────┘\n\n    at checkExecSyncError (child_process.js:601:13)\n    at Object.execSync (child_process.js:641:13)\n    at /var/task/user/api/typings.ts:2318:37\n    at step (/var/task/user/api/typings.ts:2212:23)\n    at Object.next (/var/task/user/api/typings.ts:2193:53)\n    at /var/task/user/api/typings.ts:2187:71\n    at new Promise (<anonymous>)\n    at module.exports.332.__awaiter (/var/task/user/api/typings.ts:2183:12)\n    at extractFiles (/var/task/user/api/typings.ts:2313:12)\n    at /var/task/user/api/typings.ts:2356:42"}
```

## How has this issue affected you? What are you trying to accomplish?

This prevents TypeScript from working properly in CodeSandbox.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | latest (not sure how to identify) |
| Browser | Chrome |
| Operating System | Windows 10 |

**Comment by Fi1osof** [comment]
Got ENOSPC error on react-app too.

**Comment by ESTrainer** [comment]
By the way what is `https://ata-fetcher.cloud`? Seems to be suspicious to our organization, and it was blocked and hence cannot get codesandbox working. Do we have any source code or more information about it?

**Comment by fnky** [comment]
@ESTrainer It is used to fetch and sync TypeScript typings for packages.
