### ISSUE TITLE
Could not find module in path: './apple-touch-icon.png?v1=00zQGABoWl' relative to '/src/index.html'

### ISSUE THREAD

**Issue by christiankaindl** [codesandbox/codesandbox-client#1658]
# 🐛 bug report

Hello!
I was trying to see if I could develop my web app on Codesandbox and ran into this issue.

## Description of the problem
In the `/src` directory are icon assets, which fail to load because of the versioning that is appended via the question mark (?) in the `src` attribute in the `index.html` file.

```
ModuleNotFoundError: Could not find module in path: './apple-touch-icon.png?v1=00zQGABoWl' relative to '/src/index.html'
```

Example icon link from the <head> of the HTML in `index.html` that fails:
``` html
<link rel="apple-touch-icon" sizes="180x180" href="./apple-touch-icon.png?v1=00zQGABoWl">
```

## How has this issue affected you? What are you trying to accomplish?
I use versioning for my web app icons (the part after the `?`), so that when I push a new icon the browser knows that it is a new one and doesn't display the old chached one.

I _think_ the correct behaviour would be to show the icon even though the name doesn't match literally. Running it locally with Parcel works and also in deployment.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Chrome 73.0.3683.86
| Operating System | Win 8

**Comment by lgraziani2712** [comment]
I'm having a similar problem:

In this sandbox: https://codesandbox.io/s/zvk44njrp, I loaded a lib which loads files dynamically.

These are the errors I'm having:

> ModuleNotFoundError: Could not find module in path: '@validate-me/core/dictionaries/en/_extras.js' relative to '/node_modules/@validate-me/core/dictionary.js'
> ModuleNotFoundError: Could not find module in path: '@validate-me/core/rules/required.js' relative to '/node_modules/@validate-me/core/rules.js'
 
I found something interesting too: when I revealed the file in the sidebar, I saw that the dynamic files aren't loaded:

![image](https://user-images.githubusercontent.com/15050200/56140406-37958600-5f71-11e9-940e-b78993afee89.png)

Although the files are in the package tarball.

**Comment by lgraziani2712** [comment]
BTW, it isn't a CRA specific bug. It also happens with a Vue sandbox: https://codesandbox.io/s/1zmyrmykrl

**Comment by lbogdan** [comment]
Hey @lgraziani2712 , it doesn't look like it's related, though, can you please copy/paste ^^ to a new issue? Thanks!

**Comment by lgraziani2712** [comment]
Hello @lbogdan! Done! https://github.com/CompuIves/codesandbox-client/issues/1774
