### ISSUE TITLE
[Feature] White theme for embeds

### ISSUE THREAD

**Issue by hpohlmeyer** [codesandbox/codesandbox-client#1663]
# 🌈 Feature

## What is this feature?
We use codesandbox embeds a lot for presentations. Unfortunately dark themes are way harder to read on a beamer. A white theme would improve the readability a lot. (We currently invert the screen colors to achieve that)

Support for themes (including white ones) came with #359 but [embeds do not have any parameters to configure a theme](https://codesandbox.io/docs/embedding).

## How the feature should work?
It would be nice to have a parameter to configure the theme of the embed.
If possible it would be nice to have it working with the monaco editor too, because having the more lightweight editor in presentations makes a big difference.

**Comment by SaraVieira** [comment]
This was actually realeased in the latest embed release!

https://codesandbox.io/post/codesandbox-ci-embeds
