### ISSUE TITLE
<img> tags with SVG source file break in Vue template

### ISSUE THREAD

**Issue by loilo** [codesandbox/codesandbox-client#1664]
# 🐛 bug report

## Description of the problem
When using an `<img>` tag with an SVG source file (using a relative path, so it's handled by webpack), CodeSandbox tries to inline the SVG code into the `src` attribute of the `<img>` tag, which naturally does not work.

## How has this issue affected you? What are you trying to accomplish?
I wanted to display an SVG image but I couldn't. 🙂 
(FWIW, it works to just put the SVG in the `public` folder and serve it from there, statically. However I think this is still a bug that should get fixed.)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1553733958-f0fde446a
| Browser | 72.0.3626.121
| Operating System | macOS 10.14.4 Beta

**Comment by PJCHENder** [comment]
Same issue in react template.

**Comment by PJCHENder** [comment]
Same here as in React template.

**Comment by loilo** [comment]
Bump @github-actions, issue still occurs.

**Comment by loilo** [comment]
This is still broken so should probably not be closed.

**Comment by loilo** [comment]
Still broken @github-actions.
