### ISSUE TITLE
Emptying trash with many sandboxes causes 504 Gateway Timeout

### ISSUE THREAD

**Issue by EmilTholin** [codesandbox/codesandbox-client#1665]
# 🐛 bug report

## Description of the problem
Trying to empty trash with ~200 sandboxes (sorry, I didn't realise trashing a sandbox didn't delete it permanently...) gives a `504 Gateway Timeout` error, with the following popup:

<img width="318" alt="empty_trash_error_popup" src="https://user-images.githubusercontent.com/11573167/55156241-b0b37180-5159-11e9-8d5d-f91cce572765.png">

## How has this issue affected you? What are you trying to accomplish?
It wasn't clear what happened at first with the popup message. Maybe the popup message could be changed, or maybe sandboxes could be removed ~50 at a time, or maybe a max limit of how many that can be removed at one time can be implemented?

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Browser | Chrome 73.0.3683.86
| Operating System | macOS High Sierra 10.13.6

**Comment by lbogdan** [comment]
Can you maybe take a look at the actual network request and paste / screenshot the response?

**Comment by EmilTholin** [comment]
<img width="687" alt="response_headers" src="https://user-images.githubusercontent.com/11573167/55156907-66cb8b00-515b-11e9-970b-0d68b6c09589.png">
<img width="717" alt="response_preview" src="https://user-images.githubusercontent.com/11573167/55156912-692de500-515b-11e9-8869-490a2ca71da2.png">

**Comment by lbogdan** [comment]
Thanks, looks like an API bug. I also agree we should be more eloquent in the error notification, too.
