### ISSUE TITLE
preferences not saving Safari ipad pro latest ver

### ISSUE THREAD

**Issue by jasonbronson** [codesandbox/codesandbox-client#1669]
The preferences will not stick or even change in safari window if I adjust our theme to light version. I’m stuck on darkmode and in sunlight I cannot even see the screen.

**Comment by SaraVieira** [comment]
Hey!

Are you using incognito mode ?

**Comment by jasonbronson** [comment]
no

**Comment by CompuIves** [comment]
Hmm, could be maybe related to the new theme properties in VSCode, it might be that it isn't applied properly in the case of CodeMirror. I can look into this next week.
