### ISSUE TITLE
RavenJS kills performance.

### ISSUE THREAD

**Issue by Genroa** [codesandbox/codesandbox-client#1671]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?
I'm working on a small game with PIXI and until quite recently, everything was fine. Then I started to get really poor performance. With Chrome, I ran a performance profiling. Here are the results:

![](https://image.noelshack.com/fichiers/2019/13/5/1553897425-capture.png)

Link to the picture: [Link](https://image.noelshack.com/fichiers/2019/13/5/1553897425-capture.png)

This was running in the "Open in New Window" tab, so it's not coming from the IDE. Every bump in the app performance is caused by what seems to be a call to a ravenjs library on a CDN. I downloaded my project and can confirm it isn't part of my package.json files and isn't installed nor included in my project when I build it. Why is it here? It **very** regularly make calls, and completely kills the app performance. What is going on here? I don't understand. Also, why are there 1200 listeners when my app only uses like 13? Why is the app consuming 200Mo while my local build consumes around 8Mo? There's something really strange going on, the online build doesn't act like the downloaded + built zip at all.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  latest
| Browser |  Chrome
| Operating System | Windows 10

**Comment by CompuIves** [comment]
Hey! Thanks for letting me know, that's unacceptable. I'm working on a fix.

**Comment by Genroa** [comment]
Thank you for your quick response !

**Comment by CompuIves** [comment]
Fix is live now!

**Comment by Genroa** [comment]
Hm... Sorry, but the problem remains exactly as it was before the fix, even after emptying my cache.

**Comment by CompuIves** [comment]
Hmm, that is weird. Do you have a sandbox I can look into?

**Comment by Genroa** [comment]
> Hmm, that is weird. Do you have a sandbox I can look into?

Here is my sandbox : [https://codesandbox.io/s/lp12832xwl](https://codesandbox.io/s/lp12832xwl)

**Comment by Genroa** [comment]
Update : RavenJS activity doesn't appear anymore in my sandbox app application profilings.

**Comment by CompuIves** [comment]
Yes, I deployed an update this morning that hopefully fixes this. Let me know if it works!

**Comment by CompuIves** [comment]
Closing this one as it seems to be fixed.
