### ISSUE TITLE
React components methods don't throw binding error

### ISSUE THREAD

**Issue by farskid** [codesandbox/codesandbox-client#1679]
# 🐛 bug report

## Description of the problem

When we use an ES6 class to create a React component, if there is an access to `this` reference in a class method, the method needs to be bound to the class instance in constructor or be written as an arrow function, otherwise, there would be an error thrown, indicating that the mentioned method doesn't have access to `this`.

## How has this issue affected you? What are you trying to accomplish?

When you reproduce such an unbound method in Codesandbox, the error wouldn't be thrown and there will be no warning or error in the console as well.

###  Link to sandbox
Use this sample sandbox that includes the bug. Also by uncommenting line 11, you can see that it works.
https://codesandbox.io/s/y0j101mjzx

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1553897973-43cec9c83
| Browser | Google Chrome 73.0.3683.86 (Official Build) (64-bit)
| Operating System | Mac OS Mojave

**Comment by samrith-s** [comment]
Hey @farskid, what error are you not getting?

Afaik, the below error you get in the console is the best that can be achieved. Or am I missing something here?

![image](https://user-images.githubusercontent.com/9032162/55554986-c13b8d00-5701-11e9-8783-766709d31623.png)

**Comment by SaraVieira** [comment]
Hey!

I tried it and it doesn't work, you can't slide it and I get the error on the console :/

**Comment by farskid** [comment]
@samrith-s The error is thrown and shown in browser console but not in sandbox console!
@SaraVieira Same experience for me on the mentioned sandbox.

**Comment by JonShort** [comment]
![image](https://user-images.githubusercontent.com/21317379/55687556-24c5f480-5966-11e9-807d-60aa5ddd9f1e.png)

Strangely enough the error is thrown correctly when running codesandbox locally 🤔
Could this be related to  #667?

**Comment by farskid** [comment]
This issue seems to be fixed on the sandbox initially shared so closing it. You can't see the error in codesandbox console but the error stuck is shown on the preview.
