### ISSUE TITLE
Upgrade to TypeScript version 3.4

### ISSUE THREAD

**Issue by hasparus** [codesandbox/codesandbox-client#1683]
TS 3.4 adds new syntax ([const contexts](https://github.com/Microsoft/TypeScript/pull/29510) and [readonly tuples](https://github.com/Microsoft/TypeScript/pull/29435)) which isn't supported now. [Repro on CodeSandbox](https://codesandbox.io/s/7w0pwz6lj6?fontsize=14&module=%2Fsrc%2Findex.ts)

Could be solved with #942 but this is smaller scope, so I've created separate issue.

**Comment by s-h-a-d-o-w** [comment]
On a related note, as illustrated by this very problem - why is typescript even listed as a dependency in `package.json` if that version is clearly not being used?
