### ISSUE TITLE
File got deleted after refresh

### ISSUE THREAD

**Issue by ivulovic** [codesandbox/codesandbox-client#1724]
# 🐛 bug report

File got deleted after app freezed
The sandbox just got stuck and after refresh i lost everything

https://codesandbox.io/s/movk61ky48

Environment
| React  |       
| Dragula |
| ---------------- | ---------- |
| Сodesandbox  | 
| Chromium | 
| Linux Mint |

**Comment by CompuIves** [comment]
Hey @ivulovic, could you check your localStorage to see if the file maybe is there? Normally we save a local "backup" of a file by saving it to `localStorage` and recover it whenever you refresh.

I think that #1709 will reduce this case a lot.
