### ISSUE TITLE
🐛 File Upload Buttons missing in v3 Editor?

### ISSUE THREAD

**Issue by Saeris** [codesandbox/codesandbox-client#1732]
It appears that since the latest editor update, the file upload buttons in the file explorer are missing, though drag-and-drop file uploads still work. I couldn't find an option under the "File" menu to open a file upload dialog either.

**Comment by SaraVieira** [comment]
Hey!

Isn't this the only file upload button we had?
![Screenshot 2019-04-16 at 00 38 58](https://user-images.githubusercontent.com/1051509/56169932-1a4bd080-5fe0-11e9-96c6-8493ef750b0a.png)

Is something else missing?

**Comment by Saeris** [comment]
Seems to be specific to container sandboxes. Regular sandboxes have the upload icons at the top of the explorer and on each folder when hovering. This isn't the case for containers. See the attached screenshots:

Container:
![image](https://user-images.githubusercontent.com/3144549/56233329-b2c16f80-6037-11e9-8d58-4dc6eb6a6be8.png)

Regular Sandbox:
![image](https://user-images.githubusercontent.com/3144549/56233375-c5d43f80-6037-11e9-8205-f301996f4448.png)
