### ISSUE TITLE
🐛 Open Sandbox throws an error & Open Sandbox in new tab opens in current window

### ISSUE THREAD

**Issue by dance2die** [codesandbox/codesandbox-client#1738]
# 🐛 bug report

I've spotted two issues

1. "Open Sandbox" doesn't open a sandbox and throws an error in console
1. "Open Sandbox in new tab" opens a sandbox in current tab

## 1st Error

Clicking on `Open Sandbox` does not open & throws following error in console.

> Uncaught TypeError: Cannot read property 'ctrlKey' of undefined
    at Object.action (index.js:287)
    at onMouseUp (index.js:132)
    at Object.<anonymous> (react-dom.production.min.js:14)
    at f (react-dom.production.min.js:15)
    at react-dom.production.min.js:15
    at C (react-dom.production.min.js:17)
    at E (react-dom.production.min.js:18)
    at j (react-dom.production.min.js:18)
    at M (react-dom.production.min.js:21)
    at kn (react-dom.production.min.js:84)

![error in console](https://user-images.githubusercontent.com/8465237/55662230-97f12e80-57df-11e9-95da-3d01ed2c3cb5.png)

You can see the interactive demo 👇 

![error demo](https://user-images.githubusercontent.com/8465237/55662241-a8a1a480-57df-11e9-8dcd-8630e18f9667.gif)

## 2nd Error

"Open Sandbox in new tab" opens a sandbox in current tab.
You can see the error in action in the GIF demo in the first issue above.

## How has this issue affected you? What are you trying to accomplish?

I'd like to open a sandbox in a new tab.

###  Link to sandbox

The sandbox opened in the GIF demo is [this sandbox](https://codesandbox.io/s/nkkm533npm).

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1554491263-be5b09e5c
| Browser | Version 73.0.3683.103 (Official Build) (64-bit)
| Windows 10 | Version 1803 (OS Build 17134.648)
| Ubuntu | 18.10

The same error/misbehaviors occur on latest version of Windows 10 & Ubuntu 18.10

**Comment by CompuIves** [comment]
This is probably a regression from #1687. Taking a look now.

**Comment by tinahir** [comment]
If no one is working on this bug, I would like to work on the bug.

**Comment by SaraVieira** [comment]
@CompuIves Did you look at this? OR should I fix this tomorrow?

**Comment by arthurdenner** [comment]
@dance2die, I think this problem was fixed. Could you check and close the issue if so?

**Comment by dance2die** [comment]
Fixed 🙂. Thank you @arthurdenner
