### ISSUE TITLE
Firefox and Chrome on IOS: Error Unexpected frame by generating stack

### ISSUE THREAD

**Issue by jimthedev** [codesandbox/codesandbox-client#1744]
# 🐛 bug report

## Description of the problem

- In Firefox on MacOS (or Chrome on iOS)
- Visit https://7zlm67770j.codesandbox.io/log-in,
- Change the email to bob@bob.co or some other nonsense email.  Click the login button (password should be pre-filled and generic).
- You will not see an error even though you should. If you look in the browser's dev tools you should see an error relating to `Unexpected frame by generating stack`. This only when viewing it on Codesandbox. When I deploy to now.sh you get the actual graphql error I'd expect which is specific to my backend.

## How has this issue affected you? What are you trying to accomplish?

I am trying to handle a known error but this one is being generated instead, but only on codesandbox. When I deploy it to my hosting provider I get my expected graphql error.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  PROD-1552372285-96510b09
| Browser | Firefox 66.0.1 (64-bit) on MacOS (or Chrome on iOS)
| Operating System | MacOS (or iOS)

**Comment by Jakobo** [comment]
Just adding to this thread that I was able to recreate this case with simply an intentionally failing Jest test. Firefox only (works in Chrome), which seems to imply an issue with the error polyfill.

Software | Name / Version
---|---
Codesandbox | `PROD-1556551783-3c533b67a`
Browser | Firefox 66.0.3 (64 bit)
Operating System | MacOS

* Sandbox: https://codesandbox.io/s/6xvrzj03xn

```
Unexpected frame by generating stack.

captureFrameStrings@https://codesandbox.io/static/js/common-sandbox.3dc7ca12.chunk.js:1:261314
e@https://codesandbox.io/static/js/common-sandbox.3dc7ca12.chunk.js:1:263064
[note: truncated for sanity, but this is the error thrown instead of a normal jest error]
```
