### ISSUE TITLE
Collab editing super flakey

### ISSUE THREAD

**Issue by lucasdellabella** [codesandbox/codesandbox-client#1747]
# 🐛 bug report
## Description of the problem

Collaborative editing for teams has flaked out ~90% of the time today, multiple different people in different teams have had client syncing issues when trying to use collab editing. text typed in one client doesn't show up in the other, shows up garbled etc. Issue seems to be significantly worse today than past few weeks where it has existed but not been insurmountable.  Payload for the socket events coming over is only this, instead of the payload for the character insertion as well as the cursor position change? Aware that this is only semi helpful. Thanks for the awesome software!

`[null,null,"live:B55pn","user:selection",{"selection":{"secondary":[],"primary":{"selection":[],"cursorPosition":257}},"moduleShortid":"BRJW2","liveUserId":"9c1bb902-2759-4cdb-915c-cbbe4a525f0e","_messageId":"585b1c01-42df-4d82-990c-a396b26f93ed846","live_user_id":"9c1bb902-2759-4cdb-915c-cbbe4a525f0e"}]`

## How has this issue affected you? What are you trying to accomplish?
Trying to work collaboratively :^)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1554569576-d688a852f |
| Browser | Chrome |
| Operating System | macOS 10.12.6

**Comment by CompuIves** [comment]
That's bad, I want to fix this as soon as possible. 

> Payload for the socket events coming over is only this, instead of the payload for the character insertion as well as the cursor position change?

This is super helpful! It seems like the problem is on the server, that the server doesn't process operations correctly. I'm going to take a closer look now.

**Comment by lucasdellabella** [comment]
Wish I could help more. I was investigating more and it _seemed_ that it might have been related to other clients not receiving the event for me entering the room, but not sure about that. Wish I could offer a way to repro  🤷‍♂️

**Comment by CompuIves** [comment]
Yeah, these issues are super hard to find out. It could also be because of server latency and a race condition. Would you maybe have time to do a quick test with me somewhere next week? Only if you have time! You can e-mail me at ives@codesandbox.io if you have time 😄.

**Comment by lucasdellabella** [comment]
Yep for sure, I'll send you an email in a bit. Pretty free outside of standard 9 - 5.
