### ISSUE TITLE
Trojan found in Docker image

### ISSUE THREAD

**Issue by taemon1337** [codesandbox/codesandbox-client#1748]
win.trojan.miner was found during a virus scan of the latest docker image.  I am looking into getting more details, but suggest you checkout your npm dependencies as that is a common vector.

**Comment by CompuIves** [comment]
Hey! We're taking a look, do you mean this docker image? `codesandbox/client:30f1fcb`

**Comment by taemon1337** [comment]
I believe so, I just requested to import the image which gets scanned as part of our process, but it should be the latest image and it was just done yesterday.

**Comment by lbogdan** [comment]
@taemon1337 How exactly did you scan the image?

**Comment by taemon1337** [comment]
![codemirrortroj](https://user-images.githubusercontent.com/2095857/55808000-3831a680-5ab1-11e9-89cd-6d206563ed95.png)
