### ISSUE TITLE
node_modules URL for the static template

### ISSUE THREAD

**Issue by justinfagnani** [codesandbox/codesandbox-client#1757]
# ❔ Question

I can't find the URL of the node_modules/ folder for the static template. In https://codesandbox.io/s/ov3vjqv9y9 I've installed lit-html, then try to load it like:

```html
    <script type="module">
      import { render, html } from "/node_modules/lit-html/lit-html.js";

      render(
        html`
          Hello
        `,
        document.body
      );
    </script>
```

But `/node_modules/lit-html/lit-html.js` is actually return the contents of _`index.html`_.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | 
| Operating System |

**Comment by CompuIves** [comment]
Yes! I'd love to add this functionality to CodeSandbox, it's currently not here yet. It's related to https://github.com/CompuIves/codesandbox-client/issues/1246.

You can already do this using a container sandbox: https://codesandbox.io/s/2p8ylq3rwr

But it would be nicer to make this a browser sandbox, so we can make it a bit more lightweight.

**Comment by justinfagnani** [comment]
Thanks for the container tip, that'll work for now. I hadn't used those yet.

**Comment by justinfagnani** [comment]
Hopefully this is still a good idea :)

**Comment by CompuIves** [comment]
Absolutely!
