### ISSUE TITLE
Editor not picking up CSS changes in Dojo templates

### ISSUE THREAD

**Issue by nicknisi** [codesandbox/codesandbox-client#1758]
# 🐛 bug report

## Description of the problem

![Napkin 04-10-19, 3 10 57 PM](https://user-images.githubusercontent.com/293805/55910015-f719bf00-5ba2-11e9-8af5-9397d9652f06.png)

When a .m.css file is changed in a Dojo template CodeSandbox, a new type definition is generated to represent the available classes in that css file, so that it can be imported and applied to a module. Previously, the editor was alerted to these changes via `dispatch({ type: 'add-extra-lib', path, code: toDefinition(exportTokens) });` [here](https://github.com/CompuIves/codesandbox-client/blob/5d76be57aa58d59150bf32aac5ba6261c770e535/packages/app/src/sandbox/eval/presets/dojo/transpilers/style.js#L32) but it looks like the listener within the editor is now a noop ([here](https://github.com/CompuIves/codesandbox-client/blob/5d76be57aa58d59150bf32aac5ba6261c770e535/packages/app/src/app/components/CodeEditor/VSCode/index.tsx#L234-L241)).

Looking at this locally, it looks like the `monaco` object is different from what it used to be and doesn't have the `monaco.languages.typescript.javascriptDefaults.addExtraLib(code, dtsPath);` method to call.

I'm interested in helping contribute a fix to this but I'm curious if there is a better way to handle this. This method relies on the editor reading the type definition that is added in this method and overlooking the `css.d.ts` file that exists in the sandbox. Would there be a way for the StyleTranspiler directly to the `css.d.ts` file in the sandbox?

Thanks for any help you can provide!

## How has this issue affected you? What are you trying to accomplish?

This makes Dojo sandboxes look like they might be broken.

###  Link to sandbox: [link](https://codesandbox.io/s/0y2160211n)

Look at the src/widgets/Hello.tsx file and notice that the editor is reporting an error using `css.foo`.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1554569576-d688a852f |
| Browser | Firefox 66 |
| Operating System | macOS 10.14.4 |

**Comment by CompuIves** [comment]
Ahh, I'm sorry for that. I actually do like your implementation very much with the `postMessage`. We now use the typescript extension, so it might be best to write a file or something in the method:

```
// BrowserFS is a global, you can use it like this
const fs = BrowserFS.BFSRequire('fs');

fs.writeFile('/path/to/types.d.ts', 'content', (err) => {
	// handle err if not null;
})
```

I think this would make it woork already.

**Comment by nicknisi** [comment]
Thanks for such a quick response! Is there a prefix required for the path? Something like `file:///` or `/sandbox/`?

**Comment by maier49** [comment]
@CompuIves Hi I picked this issue up and after trying to use BrowserFS it doesn't seem like the changes are picked up by the editor.

The log [here](https://github.com/maier49/codesandbox-client/commit/f01f32ad5ad528511719944fddd51b1191e7e348#diff-30c2e47700b548db61c6d327a099f5edR1267) comes through so it seems like the write is successful but the file is unchanged and the typings are not updated.

Using `setModuleCode` seems to work but only if the file is already open.

**Comment by CompuIves** [comment]
Hey! Ah I see, by default we don't build browserfs to save resources. If you go to standalone-packages/codesandbox-browserfs and run yarn build it should work.

Though I'm not sure if BrowserFS needs to be changed, I was thinking that writing the types to the fs would make it work already. Changes to BrowserFS are fine though if needed!

**Comment by maier49** [comment]
@CompuIves It does seem to be an issue with BrowserFS, or maybe a step that I'm missing. 
I [added some logging](https://github.com/maier49/codesandbox-client/commit/abb4edeb3d52fed4dd1285b25330f31fdb47768c#diff-30c2e47700b548db61c6d327a099f5edR1267) to read the file synchronously using BrowserFS in the callback after a write. The data read from the file is the same as it was before the write. I tried looking into this a bit and it appeared to be because the read is coming from the transpiled modules and the changes in the write never get reflected there, unfortunately I couldn't figure out what the appropriate fix would be here.
