### ISSUE TITLE
🐛 Terminal doesn't display anything when moved

### ISSUE THREAD

**Issue by Saeris** [codesandbox/codesandbox-client#1759]
See attached gif:

![codesadbox](https://user-images.githubusercontent.com/3144549/55912078-cc296e00-5b96-11e9-80c6-6f800e872dec.gif)

Appears that unless the terminal panel is in it's original position, it won't display any output when scripts are run from the server control panel. Steps to reproduce should be as simple as opening any container sandbox, dragging the terminal up next to the browser tab, and running any script from the server control panel to verify.

**Comment by MichaelDeBoey** [comment]
@CompuIves This one should  be reopened since #2040 is reverted by #2063

**Comment by lbogdan** [comment]
Thanks @MichaelDeBoey , reopening.

**Comment by CompuIves** [comment]
I think I fixed it in my refactor, will test it.
