### ISSUE TITLE
Import fonts using font-face from "assets" (built/compiled)

### ISSUE THREAD

**Issue by Shanery** [codesandbox/codesandbox-client#1763]
# 🌈 Feature

When doing a custom import of a font-face, we should support the file path in url("path/to/font.woff)... to be relative to src and not necessarily in public.

Currently you have to put the fonts in the "public" folder to be copied over during compiling. Then the url path for the css is handled by us. This has obvious problems.

It means that any boilerplate/tests I make and download, has to be edited later down the line. 

This should be able to be handled through file-loader and some other webpack config.

**Comment by mattfelten** [comment]
Ran into this issue today also. I'm importing a CSS file from a third-party node_module that is also importing a custom font. The font isn't being loaded. The paths in the CSS is correct, based on the CSS file's location, but if I copy the fonts to public, the CSS path will be wrong. It seems like a lose-lose situation.

FWIW, the projects I'm working on all have webpack set up to import relative to src, so haven't experienced this before.

Is there a way to override the default webpack config to enable this?

**Comment by thomasmikava** [comment]
I have the same issue

**Comment by leodevbro** [comment]
It's already 2021-04-09 and this issue is still not handled. I need fonts to work in "src" folder and not in "public" folder.
