### ISSUE TITLE
I suddenly can´t use codesandbox

### ISSUE THREAD

**Issue by anastl** [codesandbox/codesandbox-client#1764]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?
     It doesn´t let me type or edit anything and all the menus have a "&" included
### Your Environment
| Software         | Name/Version|
| Windows | XP |
| Сodesandbox  |  Vanilla
| Browser |  Chrome
| Operating System | Windows XP

**Comment by SaraVieira** [comment]
Hey!

Can you please provide more info or a link to sandbox?

**Comment by anastl** [comment]
The links wouldn't really provide more info because i can't even use the
"New" vanilla parcels.

If I open a new vanilla parcel, it should show me the default Doctype but
it doesn't even do that, it just tells me that there was a vscode error in
the html languages

**Comment by anastl** [comment]
Activating extension 'vscode.html-language-features' failed: Unexpected
identifier.

I get two or three notifications like this one

**Comment by SaraVieira** [comment]
You using chrome on windows XP?

So I can test this on browserstack

**Comment by anastl** [comment]
Yes, Chrome on Windows XP

**Comment by SaraVieira** [comment]
hey!

Is this still happening? It may be an issue with windows XP
