### ISSUE TITLE
Error when using CSS Grid

### ISSUE THREAD

**Issue by nikosolihin** [codesandbox/codesandbox-client#1765]
# 🐛 bug report

## Description of the problem
When using the naming option of `grid-template-columns`, I get this error: 
```
CompileError: Error: Invalid CSS after "...mplate-columns:": expected expression (e.g. 1px, bold), was "[sidebar] 1fr [cont" on line 3 of /stdin
>>   grid-template-columns: [sidebar] 1fr [content] 2fr;
```
I'm using the Parcel sandbox starter.

## How has this issue affected you? What are you trying to accomplish?
Trying to use CSS grid with Parcel.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  PROD-1554569576-d688a852f
| Browser |  Chrome
| Operating System | MacOS

**Comment by SaraVieira** [comment]
Hey!

Can you point me in the direction of an example of that syntax? I have never seen that syntax with the [] being used anywhere

**Comment by nikosolihin** [comment]
@SaraVieira  Sure thing! 

The MDN docs about it is [here](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Layout_using_Named_Grid_Lines#Naming_lines_when_defining_a_grid).

**Comment by SaraVieira** [comment]
uh! Thank you! That is awesome!

This is def a bug with our sass bundler, will take a look, probably needs updating :/

**Comment by SaraVieira** [comment]
New example http:// codesandbox.io/s/qx1ooj89y6

**Comment by gragland** [comment]
I'm seeing this issue today with projects that were loading fine before. Here's an example: https://codesandbox.io/s/2wjxzz707r

**Comment by Ni55aN** [comment]
The same error in https://codesandbox.io/s/9jp88p1jpy
