### ISSUE TITLE
Resolving Symbolic Links

### ISSUE THREAD

**Issue by kevinwarne** [codesandbox/codesandbox-client#1767]
# 🌈 Feature

Resolving symbolic links when pointing codesandbox to a github repository subdirectory.

I'm trying to load this repo subfolder into codesandbox: https://github.com/d2bjs/demos/tree/master/charts/sankey/basic

The package.json file here is a symbolic link, as all of the demos being built for this project will use the same config. I will probably go remove the symbolic links in order to get the demo to run properly. However it would be cool if codesandbox could resolve this and run the results. I.e with this url https://codesandbox.io/embed/github/d2bjs/demos/tree/master/charts/sankey/basic

**Comment by lbogdan** [comment]
@kevinwarne Looks like that repo and it's corresponding sandbox are not there anymore?
