### ISSUE TITLE
Typescript not showing all errors

### ISSUE THREAD

**Issue by adyz** [codesandbox/codesandbox-client#1769]
# 🐛 bug report

## Description of the problem

I've started a new "React/TypeScript" and added some code.
I am not an expert in TypeScript so I usually rely on its errors or warnings to write code.

After building this little sandbox: https://codesandbox.io/s/1yp6np05o4  and hit the deploy with Netlify I've noticed in the Netlify logs that there where some TypeScript errors and the build failed (in `Confirm/Confirm.tsx` file).

I can't say that this is just for that single error, I've noticed that there are always differences between the error I get in my VSCode vs Codesanbox when it comes to typescript

<img width="1568" alt="Screenshot 2019-04-14 at 11 41 42" src="https://user-images.githubusercontent.com/611174/56090375-51b86100-5eaa-11e9-9a37-cecf041b4c9a.png">
<img width="1075" alt="Screenshot 2019-04-14 at 11 41 31" src="https://user-images.githubusercontent.com/611174/56090376-51b86100-5eaa-11e9-9276-cbb0e7a1a908.png">

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | https://codesandbox.io/s/1yp6np05o4
| Browser | Chrome
| Operating System | MacOS

**Comment by JalilArfaoui** [comment]
Same here ....

I can see that there's a TypeScript error ... but I can't find a way to have some error info / message ...

![image](https://user-images.githubusercontent.com/3037833/61071267-edf1f580-a410-11e9-9aa8-7da5082ff969.png)

**Comment by karlhorky** [comment]
Which version of TypeScript are you using in your VSCode? It appears like the version on CodeSandbox is `3.3.3`:

<img width="393" alt="Screen Shot 2019-07-12 at 10 05 24" src="https://user-images.githubusercontent.com/1935696/61112669-ae68ef00-a48c-11e9-8bf0-16ad9b0b819f.png">
