### ISSUE TITLE
Editor completely not working

### ISSUE THREAD

**Issue by IAMtheIAM** [codesandbox/codesandbox-client#1780]
# 🐛 bug report

## Description of the problem

The editor simply does not work. It will not render this simple code
https://k1wj0x45p5.codesandbox.io/

The full screen version appears blank, not even the HTML renders.

## How has this issue affected you? What are you trying to accomplish?
I copied the code from http://demo.nimius.net/debounce_throttle/ and put both javascript files into the index.html - and still no success.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  Web
| Browser |  Chrome 73
| Operating System | Linux

**Comment by CompuIves** [comment]
Hey @IAMtheIAM, I checked the code of the sandbox and it seems like you're missing a `body` tag in the HTML and `</head>` and `</html>`. I added those parts and it seems to work now: https://codesandbox.io/s/qx0n82v7o4.

**Comment by IAMtheIAM** [comment]
Thanks!

**Comment by AliaNeedsHelp** [comment]
I am trying to make a matter.js simulator, but NOTHING shows

https://codesandbox.io/s/bathtub-simulator-b4cs6?file=/index.html

I did EVERYTHING correct, but it still doesn't work.
