### ISSUE TITLE
Axios get throwing error even when it shouldn't?

### ISSUE THREAD

**Issue by SumNeuron** [codesandbox/codesandbox-client#1781]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

I am trying to test a light bundle which creates an [axios instance](https://github.com/axios/axios#axioscreateconfig) as detailed in their docs. I have used this before without issue.
The bundle did not work so to help debug I loaded the bundle source files under the directory `assets/archidekt/`

The sandbox can be found here:
https://codesandbox.io/s/pyx14r6jpm?fontsize=14

See the component `HelloWorld`

So to make sure axios works at all I tried removing the instance and calling a link (which when posted in a browser works):

```js

async go() {
...
 await axios.get("https://archidekt.com/api/decks/65126/small/");
}
```

and the error is
```
"createError@https://pyx14r6jpm.codesandbox.io/node_modules/axios/lib/core/createError.js:16:15
handleError@https://pyx14r6jpm.codesandbox.io/node_modules/axios/lib/adapters/xhr.js:87:14
"}
```
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser |  Mozilla latest
| Operating System | Ubuntu 16.94LTS / MacOS 14

**Comment by lbogdan** [comment]
@SumNeuron I'm not sure I get what's wrong, exactly. Can you please tell us what are you expecting to happen vs. what's actually happening?

**Comment by SumNeuron** [comment]
I also do not get what is wrong. I think it might be codesandbox specific... but for whatever reason, the rolluped axios instance doesnt work there :upside_down_face:

**Comment by SaraVieira** [comment]
Hey!

From what I tested this sandbox seems to be working 

I will close this, please reopen if the issue persists

**Comment by shide1989** [comment]
Had the same Issue but using an HTTP endpoint.
And managed to Solve it by Enabling CORS on my server.
