### ISSUE TITLE
VSCode Auto-Save creates file conflict

### ISSUE THREAD

**Issue by CompuIves** [codesandbox/codesandbox-client#1785]
# 🐛 bug report

## Description of the problem
When you turn on auto-save it can give the notification "Contents on disk are newer", but we don't show the action to compare last version with new version.

It's most often noticed when using auto-save.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | 
| Operating System |

**Comment by AlienKevin** [comment]
I encounter the same issue of "contents on disk are newer" even when I **disabled auto-save**. Another problem is there's currently no way to resolve this error besides deleting the file and recreating it. When I click `compare`, there are no resolve conflict options on the editor toolbar like in [VS Code](https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_preventing-dirty-writes):

![](https://code.visualstudio.com/assets/docs/getstarted/tips-and-tricks/dirty-write.png)

# Screenshot of Codesandbox
![image](https://user-images.githubusercontent.com/22850071/57519674-dfd90900-72e9-11e9-8108-0c16e87e1534.png)

**Comment by rzjnzk** [comment]
I have the same issue, and it simply makes the service unusable.

**Comment by gabrilator** [comment]
Same issue here! What are you folks doing to go forward?

**Comment by AlCaTrAzzALZ** [comment]
also having the exact same issue, makes codesandbox unusable

**Comment by paurock** [comment]
The same sh*t

**Comment by CompuIves** [comment]
For now I recommend turning of the auto-save of VSCode to reduce the conflicts. I'm deploying a fix today or tomorrow for the other cases of merge conflicts, this week I'll take a look at auto-save as well.

**Comment by jonnyasmar** [comment]
It seems like the buttons/icons for handling conflicts are actually usable!

Thought they're invisible, if you hover your mouse to the left of the "Split Editor" button, you'll see alt text for using or reverting changes.

Hope this helps as a temporary solution!

**Comment by CompuIves** [comment]
Hey all! I'm deploying a possible fix for this issue right now, I wasn't able to reproduce the issue with this fix anymore. I'm curious if others also see this happening less frequently!

**Comment by blairanderson** [comment]
Hi @CompuIves i'm still seeing this issue with auto-save on. not sure if that specific bug has been researched yet. 

it does not show conflict resolution buttons. 

![codesandbox](https://user-images.githubusercontent.com/955736/61553574-8985f600-aa0f-11e9-9a48-7c61c56543d7.jpg)
