### ISSUE TITLE
Use new version of ReasonReact

### ISSUE THREAD

**Issue by lessp** [codesandbox/codesandbox-client#1787]
# 🌈 Feature

A new version of ReasonReact was recently released which pretty much maps 1-1 to vanilla React. It also brings a new API which should be more familiar to people using React with hooks today.

Would be really cool if the preset for ReasonReact was updated with the new version. 🙂

You can read more about the new API here:

https://reasonml.github.io/reason-react/docs/en/components

**Comment by fakenickels** [comment]
Any updates here?
It stills not possible to use the new syntax
https://codesandbox.io/s/3qpjw150ym

**Comment by sync** [comment]
yes would be amazing to have... how can we help ?

**Comment by eschaefer** [comment]
@sync I started looking at this last night. It seems like we need to build some new artifacts that were custom-tweaked by @jaredly. 

https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/sandbox/eval/presets/reason/reason-remap.js
https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/sandbox/eval/transpilers/reason/worker/index.js

**Comment by ozgunbal** [comment]
Hi, is there an update about this? In addition is there any plan on adding syntax highlight at `.re` files?
