### ISSUE TITLE
Click events during tests

### ISSUE THREAD

**Issue by Komar0ff** [codesandbox/codesandbox-client#1790]
# 🐛 bug report

## Description of the problem
I was testing the button for a click and noticed a mistake:
If the button is in the container and there is **onClick** in the props, the **onClick** function in the container is executed during the test

## How has this issue affected you? What are you trying to accomplish?
The **onClick** function in the test must be executed during the test

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1555328876-ca84dd686
| Browser | Google Chrome  73.0.3683.103
| Operating System | Windows 10

**Comment by CompuIves** [comment]
Hey! I'm not sure if I understand the issue, when I run the tests I do get the message `"container called"` twice in the console. This is intended behaviour, right?

**Comment by Komar0ff** [comment]
@CompuIves Hi Ives! No it's not intended behaviour. Must be 2 message "test container called" in console

**Comment by Komar0ff** [comment]
You can run my example locally and you'll know the difference

**Comment by CompuIves** [comment]
Ah, yep I understand now! We need to run the tests in a different context. I'll probably run the tests in a worker in a better version.
