### ISSUE TITLE
unrecoverable sandbox error

### ISSUE THREAD

**Issue by disjukr** [codesandbox/codesandbox-client#1802]
# 🐛 bug report

## Description of the problem

https://codesandbox.io/s/n08qvvxpj0

refreshed several times.. but it only shows `An unrecoverable sandbox error occurred. :-( Try refreshing the page.`

<img width="1113" alt="스크린샷 2019-04-23 오후 8 14 24" src="https://user-images.githubusercontent.com/690661/56576875-880d8300-6604-11e9-838c-5cef1b8b1e35.png">

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1555877577-92d70e914 |
| Browser | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 |
| Operating System | macOS Mojave 10.14.4 |

**Comment by lbogdan** [comment]
@disjukr Can you please try again now?

**Comment by disjukr** [comment]
now it works well. thank you :)
