### ISSUE TITLE
"Fork" button doesn't reset its state on fork error

### ISSUE THREAD

**Issue by lbogdan** [codesandbox/codesandbox-client#1803]
When there's an error forking a (server) sandbox (for example because the server sandboxes limit was reached), the "Fork" button doesn't reset its state and remains in the "forking" state:

![image](https://user-images.githubusercontent.com/2083930/56582505-14f21580-65e0-11e9-80d3-6075a607b781.png)

**Comment by lbogdan** [comment]
@ValentinH Can you maybe take a look?

**Comment by ValentinH** [comment]
The disabled/loading is shown when `store.editor.isForkingSandbox` is true. Thus, we probably need to reset it to false on error.

I'll have a look later today when I'm on the computer.
