### ISSUE TITLE
Console shows empty space in server sandboxes

### ISSUE THREAD

**Issue by lbogdan** [codesandbox/codesandbox-client#1804]
In server sandboxes the console has an initial empty space with a width equal to the parent panel width (see the scrollbar below):

![image](https://user-images.githubusercontent.com/2083930/56582790-c3965600-65e0-11e9-908c-9ed74f37fcc4.png)

Example sandbox: https://codesandbox.io/s/github/lbogdan/cs-vue-cli-3 .

**Comment by lbogdan** [comment]
Seems to be caused by #1740 .

@rabingaire Can you maybe take a look?

**Comment by lbogdan** [comment]
Looks like the terminal `div` is not hidden when the "Terminal" tab is not active (I manually added that `display: none`):

![image](https://user-images.githubusercontent.com/2083930/56583964-710a6900-65e3-11e9-864a-b94e1e416a52.png)

**Comment by rabingaire** [comment]
Sure I will look into it

**Comment by rabingaire** [comment]
@lbogdan I think we can close this issue now 👍

**Comment by SaraVieira** [comment]
Closed by #1805
