### ISSUE TITLE
Run code only on save

### ISSUE THREAD

**Issue by babakness** [codesandbox/codesandbox-client#1810]
# 🌈 Feature

## What is this feature? 

Ability to only run code on save

## How the feature should work? 

Save -> code runs

## You have examples or an idea how it can be implemented? 
Way to disable re-runs on typing and only re-run on save. Similar to an option found on codepen

**Comment by lbogdan** [comment]
Hey @babakness ,

User menu -> Preferences -> Preview -> disable "Preview on edit" should do just that.

**Comment by lbogdan** [comment]
Hey @babakness , did that ^^ answered your question? If so, can you please close this? Thanks!

**Comment by babakness** [comment]
That was super helpful! Thanks @lbogdan

**Comment by caesarsol** [comment]
Hi @lbogdan, after the last update is this still possible?

**Comment by garethx** [comment]
Yes, from the same menu item: User menu (top-right avatar menu) -> Preferences -> Preview -> disable "Preview on edit" should do just that
