### ISSUE TITLE
502: Bad Gateway

### ISSUE THREAD

**Issue by nrossi12** [codesandbox/codesandbox-client#1814]
502 Bad Gateway keeps appearing once I change a line in my http createServer function. No idea why as I expect it to produce results.

Completely confused as I think my code is correct
Trying to accomplish results with a date format in javascript

###  Link to sandbox: https://codesandbox.io/embed/2pzywqr6pn?fontsize=14
| Javascript         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Chrome | 
| Mac OS |

**Comment by lbogdan** [comment]
Hey @nrossi12 ,

You have an error in your code:
```
/sandbox/src/index.js:11
  if (current !== moment.isoWeekday(1)) {
                         ^

TypeError: moment.isoWeekday is not a function
    at getDates (/sandbox/src/index.js:11:26)
```

I'm not sure what you're trying to do, maybe you want `moment().isoWeekday(1)`?

**Comment by lbogdan** [comment]
Also, I'd suggest you keep the terminal open at all times when working with a server sandbox, you'll be able to see those errors yourself:

![image](https://user-images.githubusercontent.com/2083930/56729181-4e03c480-675d-11e9-95ba-45b8c823fde8.png)

Closing this, as it's expected behavior.

**Comment by nrossi12** [comment]
Hi @lbogdan ,

I did see this but not sure why it is an error. This is for a task I'm doing. I had to create a line that sets the day to monday in a conditional statement to check if is is not monday and use isoWeekday to do it. I looked on moment.js to find the command and came across this.

**Comment by lbogdan** [comment]
@nrossi12 If you want help with that you could maybe try on our Spectrum chat: https://spectrum.chat/codesandbox/help .
