### ISSUE TITLE
Download sandbox without opening it

### ISSUE THREAD

**Issue by theangrybagel** [codesandbox/codesandbox-client#1816]
# 🌈 Feature

<h1>Download sandbox without <i>opening</i> the actual sandbox</h1>

<p>When a user right clicks a sandbox in the dashboard, they should also have the option to download the sandbox to their computer. This would fix a <b>major issue</b> where users need to edit their sandbox, without opening it, because opening it crashes the tab.</p>

**Comment by lbogdan** [comment]
As a workaround, you can open the sandbox embed with the preview disabled, see my comment here: https://github.com/codesandbox/codesandbox-client/issues/1815#issuecomment-490261061 .

**Comment by arthurdenner** [comment]
@theangrybagel, in the dashboard we have the option to export a sandbox now.

Is that what you suggested? If so, could you close the issue?

**Comment by SaraVieira** [comment]
This has been fixed with the new dashboard 🎉

We now have an export sandbox
