### ISSUE TITLE
ionic4-start-theme not loading start page

### ISSUE THREAD

**Issue by Abinash3101** [codesandbox/codesandbox-client#1817]
# 🐛 bug report

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | 
| Operating System |

**Comment by Abinash3101** [comment]
https://codesandbox.io/s/m41y3zp378

**Comment by lbogdan** [comment]
Hey @Abinash3101 , looks like the sandbox you shared is not there anymore.

**Comment by SaraVieira** [comment]
Closed for lack of activity
