### ISSUE TITLE
Console Errors on the Main Website

### ISSUE THREAD

**Issue by co16353sidak** [codesandbox/codesandbox-client#1818]
# 🐛 bug report

## Description of the problem
When opening the website for CodeSandbox, I found that the console gave out a few about of errors,
1. A CodeSandbox API `https://codesandbox.io/api/v1/users/current` gives 404
2. docsearch API, `https://unpkg.com/docsearch.js@2.4.1/dist/cdn/dist/cdn/docsearch.min.js.map` gives 404
3. A TypeError in `https://codesandbox.io/static/browserfs3/browserfs.min.js`
4. An undefined error on an empty object `https://codesandbox.io/public/14/vs/editor/editor.main.js`

Screenshot:-
<img width="1280" alt="Screenshot 2019-04-26 at 8 02 10 PM" src="https://user-images.githubusercontent.com/35738138/56815133-3102ea80-685e-11e9-8727-00f74cad6a65.png">

It could be that these could be already known to the mods here, but I though I will open up and I issue for the same in an attempt to document the errors and their fixes (again hoping that this is not already done)
I am also new here and love the concept of a fully set IDE type environment for new-comers to work in.
Also I would really like to work on this issue 🥇

**Comment by lbogdan** [comment]
> Also I would really like to work on this issue
That would be nice, the first step would be to read the [contributing guide](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md) and setup a local development environment. Please let us know if you need any guidance with that!
