### ISSUE TITLE
Sandbox Container: /core is larger than maximum allowed file size (476160000 > 2097152), not synchronizing

### ISSUE THREAD

**Issue by KenzoBenzo** [codesandbox/codesandbox-client#1819]
# 🐛 bug report

## Description of the problem
Starting a GatsbyJS container, a toast error pops up saying it's too large.

## How has this issue affected you? What are you trying to accomplish?
I'm trying to work on a new website, with no prevail.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Chrome |
| Operating System | MacOS |

**Comment by lbogdan** [comment]
That `core` file usually means the program has crashed or it was OOM (out of memory) killed. Unfortunately the sandbox you shared is not there anymore, so I can't really diagnose this.
