### ISSUE TITLE
need update README.md for react-sandpack/react-smooshpack

### ISSUE THREAD

**Issue by loveky** [codesandbox/codesandbox-client#1821]
# ❔ Question

In the `Getting Started` section, the doc says I should install `@codesandbox/react-sandpack` as dependency.  But in [package.json](https://github.com/codesandbox/codesandbox-client/blob/master/packages/react-sandpack/package.json), the package name is `react-smooshpack`.  Then, in the example code, we are importing from both `react-smooshpack` and `react-sandpack`:

<img width="464" alt="Snipaste_2019-04-29_11-08-21" src="https://user-images.githubusercontent.com/1198651/56874845-3be09980-6a6f-11e9-830d-2fcebfedac18.png">

This makes me confused. Can we please update the doc with the latest usage?

Thanks

**Comment by nik72619c** [comment]
shall I make the required changes ? I'd love to make my first pr at codesandbox
