### ISSUE TITLE
Svelte 3 weird error

### ISSUE THREAD

**Issue by ValentinH** [codesandbox/codesandbox-client#1825]
I've just tried the new Svelte 3 template and I get a weird error: `Cropper component is not defined` (Cropper is my component coming from a npm package).

Is it related to codesandbox or the way the component is exported?

Demo: codesandbox.io/s/z2l9zqv73x

**Comment by SaraVieira** [comment]
Hey!

Svelte 3 has not been deployed yet, so you are still using version 2 for the compiler there 

I'm gonna close as we will deploy this tonight and please re open if you still have issues tomorrow

**Comment by ValentinH** [comment]
OK makes sense, I was too impatient! 😄 

I don't know if it changes anything, but I had the same error with the deployed branch at http://pr1820.cs.lbogdan.tk/s/z2l9zqv73x though.

**Comment by SaraVieira** [comment]
Makes sense because it's using the old template with version two of the svelte

We check what version svelte is in to show the accurate compiler :/

I will try your thing as soon as it's live and let you know :)

**Comment by SaraVieira** [comment]
Hey!

Updated with the new template I get an error in the module
https://codesandbox.io/s/xj4mr8zzxq

**Comment by ValentinH** [comment]
OK, then something is wrong on my module. I've actually noticed this behavior as well when manually importing the `index.js` (compiled code).

Just to share what I understand: when importing a Svelte shared module in a Svelte application, it should directly read the source file (the one pointed by [the `"svelte"` property of package.json](https://github.com/ValentinH/svelte-easy-crop/blob/master/package.json#L4)).
On Codesandbox, it behaves differently as it imports directly the `index.js` file (which is buggy in my case).

Don't know if it makes sense :)

**Comment by SaraVieira** [comment]
OHHH!

So we get these things from unpkg and that always redirects to the main in the package.json

https://unpkg.com/svelte-easy-crop

**Comment by ValentinH** [comment]
AH yes, I understand better now 🙂

How complex would it be to detect the `svelte` property of the package.json and retrieve the correct file? For instance, here it would be: https://unpkg.com/svelte-easy-crop@1.0.0/src/Cropper.svelte.

**Comment by ValentinH** [comment]
Hey @SaraVieira, I'm still stuck on this and I can't use CodeSandbox to demo my component 😢 Do you have any idea on how CodeSandbox could detect the `svelte` property and use it? I'd be happy to provide a PR but I'm not sure where to look at 😄
