### ISSUE TITLE
Dynamic import does not work with Svelte template

### ISSUE THREAD

**Issue by pshrmn** [codesandbox/codesandbox-client#1826]
# 🐛 bug report

## Description of the problem

Using dynamic `import()` in a Svelte sandbox results in the error:

> Support for the experimental syntax 'dynamicImport' isn't currently enabled

I believe that this is because the Svelte preset [uses an empty Babel config](https://github.com/codesandbox/codesandbox-client/blob/e48ce4192843b000a8fc5ccb2d8846a8acb75e57/packages/app/src/sandbox/eval/presets/svelte/index.js).

The quick solution is to add `@babel/plugin-syntax-dynamic-import` to the `babelOptions` defined in that file.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1556546209-62e6b14da |
| Browser | 
| Operating System |

**Comment by CompuIves** [comment]
Good catch, adding and testing now!

**Comment by SaraVieira** [comment]
Im already on it

**Comment by SaraVieira** [comment]
aaaaaaaaaa

**Comment by SaraVieira** [comment]
@pshrmn 

I get this error now

![Screenshot 2019-04-29 at 17 15 28](https://user-images.githubusercontent.com/1051509/56906392-6f88e700-6aa2-11e9-9e3d-c3fe4e1aa030.png)

Any idea why?

**Comment by pshrmn** [comment]
Does the f3b273e change work? I'm not seeing that default export error locally.

**Comment by CompuIves** [comment]
It works for me! Need to deploy it still
