### ISSUE TITLE
Using extreme amounts of RAM if left open

### ISSUE THREAD

**Issue by douglasg14b** [codesandbox/codesandbox-client#1827]
# 🐛 bug report

## Description of the problem

I left codesandbox open for a few days in a tab. Came back to it using 14GB of Ram...

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1555877577-92d70e914
| Browser | Firefox
| Operating System | Linux (Ubuntu 18.10)

![image](https://user-images.githubusercontent.com/1400380/56911921-fcac4b80-6a62-11e9-9648-5e0fb3644819.png)

**Comment by CompuIves** [comment]
It seems like the extension host of our vscode implementation is taking a looooot of memory. Makes me think that they use manual garbage collection or something. I'm taking a look now.

**Comment by douglasg14b** [comment]
mhm stale bot cancer best bot cancer.

**Comment by douglasg14b** [comment]
See above.

**Comment by andrasbacsai** [comment]
We changed things a lot since the last update. Can you please test if this still the case?

**Comment by lbogdan** [comment]
Hey @douglasg14b ,

Can you please run the test again and provide an updated memory dump if this is still an issue? Thanks!

**Comment by douglasg14b** [comment]
Unfortunately I do not have a test case for this. I would use the previously linked sandbox, but it appears to be borked.

**Comment by lbogdan** [comment]
Closing this for now, as @andrasbacsai said we went through a few refactoring since the issue was opened, and resource usage seems pretty stable in Chrome on Windows 10, at least for me.

Feel free to re-open or comment if you or someone else still experiences this kind of issues.

**Comment by mohiwalla** [comment]
![image](https://github.com/user-attachments/assets/ec2109c0-747c-4477-8fb6-9c9e9531e168)
