### ISSUE TITLE
Error: "Invalid regular expression... Range out of order in character class"

### ISSUE THREAD

**Issue by hodgef** [codesandbox/codesandbox-client#1828]
# 🐛 bug report

## Description of the problem
While visiting [one of my sandboxes](https://codesandbox.io/s/github/hodgef/simple-keyboard-npm-demos/tree/master/), I notice it is now outputting the following error:

"Invalid regular expression... Range out of order in character class".

![image](https://user-images.githubusercontent.com/25509135/56930865-1aea6980-6aac-11e9-8f50-562d96a14bf8.png)

Nothing has changed in my set-up. Even reverting the sole dependency to a previous version (which has worked before), yields the same problem. [Another sandbox](https://codesandbox.io/s/github/hodgef/angular-simple-keyboard/tree/master/?module=%2Fsrc%2Fapp%2Fapp.component.ts) I have however, is still working fine. 

Any help would be appreciated!

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | latest
| Browser | Chrome 73.0.3683.103
| Operating System | Win 10

**Comment by SaraVieira** [comment]
Hey!

This seems to be an issue with the new implementation we have of JSDom

Will take a look today

**Comment by hodgef** [comment]
@SaraVieira, this seems to be fixed now. Thanks!

I'll close the ticket and keep an eye out in case it comes back.

Best,
Francisco Hodge

**Comment by statianzo** [comment]
This error is still happening for me in the linked sandbox @SaraVieira included. Just click "Tests" tab and then back to the preview.

https://codesandbox.io/s/github/hodgef/simple-keyboard-npm-demos/tree/master/

It's also showing in the console
![image](https://user-images.githubusercontent.com/57737/68611476-747a1a80-0477-11ea-9ff5-5df48b76bca9.png)

**Comment by ashleemboyer** [comment]
I came across this error yesterday. I created some sandboxes for teaching people about Jest. They worked great before I shared them, and it seems like after people open them and start editing this error occurs. I haven't been able to confirm if turning off Live mode prevents the error or not.

**Comment by ashleemboyer** [comment]
I've had a few friends help me test this, and we're not getting this error when Live has been turned off for a sandbox.
