### ISSUE TITLE
Vanilla Sandbox Linting Errors

### ISSUE THREAD

**Issue by vrunjeti** [codesandbox/codesandbox-client#1833]
# Vanilla Sandbox Linting Errors

## Description of the problem
When creating a new vanilla sandbox, the entire html file has a bunch of linting errors. This is the default state without changing anything.

<img width="1003" alt="Screenshot 2019-05-01 14 46 46" src="https://user-images.githubusercontent.com/6979696/57044751-70e01e00-6c20-11e9-86b9-0124322ab87f.png">

## How has this issue affected you? What are you trying to accomplish?
This makes the vanilla sandbox very difficult to use from a UX perspective

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1556726411-05b9d025d
| Browser | Chrome 73.0.3683.103
| Operating System | macOS High Sierra 10.13.6

**Comment by CompuIves** [comment]
The svelte extension is leaking into the `html` files. We need to find a way to only enable it for `svelte` files.

(although this linting error is completely valid 😅)
