### ISSUE TITLE
React sandboxes: TypeError Cannot read property 'hasFileResolver' of undefined

### ISSUE THREAD

**Issue by DisasterMan78** [codesandbox/codesandbox-client#1835]
# 🐛 bug report

## Description of the problem
Unable to run React sandboxes - TypeError Cannot read property 'hasFileResolver' of undefined

###  Link to sandbox: [link]() (optional)
Every sandbox listed on this page [https://github.com/erikras/redux-form]()
New React sandbox started from scratch [https://codesandbox.io/s/y2x0orz40v]()

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | React
| Browser | Chrome 73.0.3683.103 (Official Build) (64-bit)
| Operating System | MacOS Mojave 10.14.4 (18E226)

### Full error stack

TypeError
Cannot read property 'hasFileResolver' of undefined
new e
https://codesandbox.io/static/js/sandbox.ae18ce59.js:1:205374
(anonymous function)
https://codesandbox.io/static/js/42.60d37360.chunk.js:1:4860
g
https://codesandbox.io/static/js/common-sandbox.87a36cb1.chunk.js:1:388753
Generator._invoke
https://codesandbox.io/static/js/common-sandbox.87a36cb1.chunk.js:1:388541
Generator.e.(anonymous function) [as next]
https://codesandbox.io/static/js/common-sandbox.87a36cb1.chunk.js:1:388932
t
https://codesandbox.io/static/js/common-sandbox.87a36cb1.chunk.js:1:379189
u
https://codesandbox.io/static/js/common-sandbox.87a36cb1.chunk.js:1:379399
(anonymous function)
https://codesandbox.io/static/js/common-sandbox.87a36cb1.chunk.js:1:379458
(anonymous function)
https://codesandbox.io/static/js/common-sandbox.87a36cb1.chunk.js:1:379340
A
https://codesandbox.io/static/js/42.60d37360.chunk.js:1:4665
(anonymous function)
https://codesandbox.io/static/js/42.60d37360.chunk.js:1:5729
g
https://codesandbox.io/static/js/common-sandbox.87a36cb1.chunk.js:1:388753
Generator._invoke
https://codesandbox.io/static/js/common-sandbox.87a36cb1.chunk.js:1:388541
Generator.e.(anonymous function) [as next]
https://codesandbox.io/static/js/common-sandbox.87a36cb1.chunk.js:1:388932
t
https://codesandbox.io/static/js/common-sandbox.87a36cb1.chunk.js:1:379189
u
https://codesandbox.io/static/js/common-sandbox.87a36cb1.chunk.js:1:379399

**Comment by SaraVieira** [comment]
Hey!

When I load these sandboxes everything seems okay, Can you please try and unregister the service worker here:

![Screenshot 2019-05-02 at 11 16 08](https://user-images.githubusercontent.com/1051509/57066153-b9a0e100-6ccb-11e9-820c-d2c8f6430a31.png)

Just to make sure it's not that :/

**Comment by lbogdan** [comment]
@DisasterMan78 Any updates on this, did you get a chance to clear application data / load the sandboxes in incognito?

**Comment by DisasterMan78** [comment]
Sorry for the delay in getting back to you - been in crunch hell.
Only came across this again as I wanted to set up something to test a package in isolation, got the same error, googled, and my own issue was the top hit!

So yes, I've unregistered the service worker as suggested, and it does indeed work! Brilliant. Thank you very much!
