### ISSUE TITLE
Changes made on githib are not picked back by codesandbox

### ISSUE THREAD

**Issue by vikasaditya** [codesandbox/codesandbox-client#1836]
# 🐛 bug report
note: I have looked at #1587
## Using nelifycms. 
Changes made in the CMS are committed to github, but are not reflected in sandbox. Also, made a direct commit but still not getting picked up. Changes made in sandbox are getting committed okey.
Tried - restart server & sandbox 

### Your Environment
nelifycms basic template for gatsby
macos, chrome

**Comment by CompuIves** [comment]
Hi! I believe you're looking at a fork of the original sandbox that's linked to GitHub, does the original sandbox (https://codesandbox.io/s/github/vikasaditya/gatsby-starter-netlify-cms/tree/master/) have the latest changes?

**Comment by vikasaditya** [comment]
hi,

Yes, you a right. The original has the changes.

It means that I wil need to always fork from the original for every change.
I thought that I would be able to  git pull to my sandbox.

So you would suggest that I need to keep track of changes to github and if
any changes then make a fork again and delete the existing sanbox?

I think we should document this work flow and it's benefits, as this is
sort of different from what is followed in local env.

Thanks for a great product and the great speed of getting back on the issue!

**Comment by styk-tv** [comment]
I think this ultimately counter-intuitive. We need to admit at some point that not having a serious Git implementation makes things confusing and a bit counter-productive. 

We should only be able to call something a FORK if it has a git structure we can make operations against.  What we have now is a DUPLICATION into a disconnected mechanism from which its very difficult to do further git operations. Solution? (delete and do it again, lost custom link)?? bad bad.

* I want to preview an existing repo from specified branch -> clone branch (not duplicate) into user space and preview, 
* I want to refresh from remote -> pull into existing clone (not possible, advised to delete instead)
* I want to refresh from remote but i have made changes -> pull into existing clone, merge (no merge capability nor conflict resolution, lots of UI work to get there)
* I want to push to specific branch and create pull request for merge > currently branch is autonamed, no choice

So not easy but we all feel in a gut this would be desired way forward no?

@lbogdan @vikasaditya @CompuIves
