### ISSUE TITLE
[Expo] Supporting the expo-cli start command.

### ISSUE THREAD

**Issue by EvanBacon** [codesandbox/codesandbox-client#1839]
When using the [expo-cli with code sandbox](https://codesandbox.io/s/pkkj56zrr7), the start command doesn't seem to work as expected. The preview doesn't seem to update with the project, if you scroll down you'll find a white box with "an unexpected error ".

How can we make the expo-cli start command more compliant with code sandbox? Are there some environment variables that should be parsed in order to serve as expected? Is there a way to determine if the process is running in the code sandbox environment, it'd be nice to disable everything related to native development like the QR code.

The majority of relevant expo-cli startup code can be found here btw: [`XDL.Webpack`](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Webpack.js)

**Comment by lbogdan** [comment]
Hey @EvanBacon ,

It looks like it's trying to connect to a websocket over http, can you somehow force https (wss)?

![image](https://user-images.githubusercontent.com/2083930/57331445-45c66480-7121-11e9-9687-524c8225bc4d.png)

**Comment by lbogdan** [comment]
> Is there a way to determine if the process is running in the code sandbox environment

There's two environment variables explicitly set inside a sandbox:
- `CODESANDBOX_SSE`, always set to the string "true";
- `SANDBOX_URL`, set to the sandbox public URL, e.g. `https://node.sse.codesandbox.io/` (notice the trailing `/`).

**Comment by EvanBacon** [comment]
Sorry for the delay, thanks for this. Will ensure that https can be passed through as a prop or set as an ENV variable like CRA.

**Comment by lbogdan** [comment]
Hey @EvanBacon ,

Any updates on this? I saw you closed the `expo-cli` PR. We're doing a bit of issue cleaning, let us know if we can assist you further, otherwise we'd appreciate if you could close this. Thanks!

**Comment by EvanBacon** [comment]
Seems stale at this point
