### ISSUE TITLE
Feature Request: Add deep link to file

### ISSUE THREAD

**Issue by TrevorSayre** [codesandbox/codesandbox-client#184]
It would be nice to be able to link directly to a file in my sandbox. This way I can control which file someone will see when they load the sandbox based on the link I give them.

**Comment by CompuIves** [comment]
Hmm, maybe we support this already if I'm not wrong. Here's an example:

https://codesandbox.io/s/new?module=/Hello.js

**Comment by TrevorSayre** [comment]
In that case, it would be nice to have the URL update when I click on a file to make this feature more discoverable :)

**Comment by CompuIves** [comment]
Ah, yes. I've added this at the beginning of CodeSandbox, but it puts the simulated browser in an inconsistent state. There is maybe an option to fix it, we're discussing it here: https://github.com/CompuIves/codesandbox-client/issues/110

**Comment by CompuIves** [comment]
Thanks to @lbogdan this becomes possible now!

**Comment by Saeris** [comment]
Closing as this appears to be implemented.
