### ISSUE TITLE
Allow users to see the forks made off their sandbox

### ISSUE THREAD

**Issue by desean1625** [codesandbox/codesandbox-client#1841]
# 🌈 Feature

Looking at the api requests I can see how many forks have been made, but I don't see any api calls that provide a listing of those forks.

It would be nice to be able to view the forks

**Comment by SaraVieira** [comment]
Hey!

We have a new design that will show this in some places. Where would you like to see this? In the editor?

**Comment by desean1625** [comment]
![image](https://user-images.githubusercontent.com/11495566/57303650-c480ba80-70ab-11e9-936e-8cfea2b61381.png)

![image](https://user-images.githubusercontent.com/11495566/57303875-407b0280-70ac-11e9-9f41-8d2551c04fef.png)


This links bring up the show forks page

**Comment by zurcacielos** [comment]
And vice-versa! I can't see the sandboxes that I liked, meaning my starred or favourites. May be I'm missing a menu option, couldn't find anything in the documentation either.
