### ISSUE TITLE
Allow to export sandboxes from dashboard

### ISSUE THREAD

**Issue by CompuIves** [codesandbox/codesandbox-client#1844]
# 🌈 Feature

Allow for exporting a sandbox (or multiple) from the dashboard by adding it as a context menu option ("Export Sandbox" or "Export ${count} Sandboxes"). Especially useful for creators that need to export their examples.

We already have the export zip behaviour: https://github.com/CompuIves/codesandbox-client/blob/496b15c47b35eee036a8b422b0eab00f4069b3b0/packages/app/src/app/overmind/effects/utils/create-zip/index.ts

**Comment by SaraVieira** [comment]
Closed by #1878

**Comment by borillo** [comment]
I would be great to also have this feature in the CLI. Now you can only push projects from local to codesanbox, but pull them would be really cool!!! @CompuIves @SaraVieira
