### ISSUE TITLE
yarn install is failing at node-gyp

### ISSUE THREAD

**Issue by sarbbottam** [codesandbox/codesandbox-client#1846]
# ❔ Question

Hello people,

Thank you for creating and maintaining codesandbox. It is fantastic. 👌 

I tried to set up [codesandbox-client](https://github.com/codesandbox/codesandbox-client/) locally, following [Setting Up the project locally]( https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md#setting-up-the-project-locally) instructions.

>`yarn` to install dependencies

I am not sure if this is a system issue but `yarn` fails at node-gyp phase for me.

Please find the complete `STDOUT` of running `yarn` [here](https://github.com/codesandbox/codesandbox-client/files/3144909/yarn.log)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | NA
| Browser | NA
| Operating System | macOS 10.14.4|
|node --version| 12.1.0|
|yarn --version|1.15.2|

Any pointer would be very helpful.

Best!

**Comment by SaraVieira** [comment]
Hey!

I got this too on linux, I am looking into what's causing this :(

**Comment by sarbbottam** [comment]
Thank you @SaraVieira for looking into the issue, please let me know if I can be of any help or provide any more information.

**Comment by lbogdan** [comment]
@sarbbottam Can you gist / pastebin the complete yarn install log? Does it fail on `codesandbox-browserfs` when trying to install /build `fsevents`?

**Comment by sarbbottam** [comment]
>Please find the complete `STDOUT` of running `yarn` [here](https://github.com/codesandbox/codesandbox-client/files/3144909/yarn.log)

Hi @lbogdan, does ☝️help?

**Comment by lbogdan** [comment]
Oh, I missed that, sorry! Can you maybe try with node 10?

**Comment by sarbbottam** [comment]
>try with node 10
I did it, I used `10.6.0`, I faced similar errors.

**Comment by jyotiarora2610** [comment]
Hi, I'm also facing the same issue with node v10.16.3 and here is my error log file 
[yarn-error.log](https://github.com/codesandbox/codesandbox-client/files/3730418/yarn-error.log)

**Comment by SaraVieira** [comment]
Hey!

This seemed to be an issue with `next-css` and that dependency has been removed

Is this still an issue?
