### ISSUE TITLE
Installing Java into node sandbox and setting JAVA_HOME

### ISSUE THREAD

**Issue by akhiljay** [codesandbox/codesandbox-client#1847]
#  Installing Java into node sandbox and setting JAVA_HOME

I am trying to setup a node server for Akamai Sandbox which is a JAVA based command line app. When I spin up the server and access it's bash to install java it doesn't allow me to do so. Is there any way we can allow java 9 or above into codesandboxes?

**Comment by lbogdan** [comment]
Closing this, too.
