### ISSUE TITLE
How to request a server template be added?

### ISSUE THREAD

**Issue by smolinari** [codesandbox/codesandbox-client#1850]
Hi,

I'd just like to know the process for requesting a new server template. 

Thanks!

Scott

**Comment by CompuIves** [comment]
Hey! We described the process of adding a new template here: https://github.com/codesandbox/codesandbox-client/blob/master/contributor-docs/adding-template.md. Let me know if any questions arise!

**Comment by smolinari** [comment]
Reading and thanks!

Scott

**Comment by smolinari** [comment]
@CompuIves - I need some advice please. Quasar has a CLI, and with it, it is possible to develop a number of different project types, which I am currently assuming are supposed to be the templates. I've gotten the SPA [version done and working](https://codesandbox.io/s/vv2l24mo0y) and have it "installed" in codesandbox-client locally as a template. 

![image](https://user-images.githubusercontent.com/3314957/57466802-a076d200-7281-11e9-89ff-eb1bded6caca.png)

But, Quasar also has a PWA project type and an SSR project type (similar to Nuxtjs). 

Is it possible to just have a CLI template and let the user use the terminal to generate a project (PWA, SSR or SPA)? 

Or should we create three different Quasar project templates?

If it is possible to create a CLI only version, can you point me to a best example to follow?
 
Thanks for any suggestions or advice in advance. 😄 

Scott

**Comment by smolinari** [comment]
One more note. The difference between the three is using a different start script. 

`quasar dev`
`quasar dev -m ssr`
`quasar dev -m pwa`

That's it. So, what to do? 😄 

Scott

**Comment by smolinari** [comment]
Ok. We've decided to just go with the SPA template, as it seems a pure CLI solution isn't possible or maybe even wanted. No biggy. We'll include instructions on how to run the two other modes of the template.

Here is the PR. https://github.com/codesandbox/codesandbox-client/pull/1888

Scott
