### ISSUE TITLE
Sandbox container shouldn't remove any installs or bash profiles that has been created

### ISSUE THREAD

**Issue by akhiljay** [codesandbox/codesandbox-client#1852]
# 🌈 Feature

Persistence within Sandbox containers

Once a user installs apps like an Akamai CLI or Java they shouldn't be removed once the container comes back after hibernation. You have two design choices, either 
a) allows users to add commands into dockerfile for their container OR 
b) ensure the sandbox containers are persistent when they wake up after hibernation

This could be a paid option and I don't mind paying $5 per month to get persistence within 5 sandbox containers.

**Comment by lbogdan** [comment]
We currently persist the `/sandbox` folder, so if you can place all your assets there, they'll be persisted between restarts. Also make sure you add the binaries / folders to `.gitignore`, so we will ignore them when syncing container changes back to the API sandbox contents.

**Comment by akhiljay** [comment]
Thanks Bogdan, I did observe that so thank you for the tip. The issue I am having is that I tried installing a binary into the sandbox and updated ~/.bashrc file to include an alias command for the binary. Once the sandbox came back from hibernation the ~/.bashrc file and anything under /home/sandbox got wiped out. 

I had the original binary under /sandbox but anything that was installed by the binary itself into /home/sandbox got wiped out.

**Comment by akhiljay** [comment]
Hi @lbogdan, not sure how this is closed since even mentioning ~/.bashrc within gitignore doesn't help persist the changes I make within the sandbox.

**Comment by akhiljay** [comment]
if the intent is to close it because it's been catalogued as an enhancement then that's fine.

**Comment by lbogdan** [comment]
I had no intention of closing this, I closed #1848 , which I assumes you already solved.

**Comment by akhiljay** [comment]
ah, my bad. Sorry. I misread the comment. Thank you for being diligent.
