### ISSUE TITLE
Display who liked/forked my sandbox

### ISSUE THREAD

**Issue by ValentinH** [codesandbox/codesandbox-client#1857]
While browsing my profile I noticed I had several likes and forks on some of my sandboxes, and I'd be curious to know who is behind these numbers. Also I'd like to see the content of the forks.

Is it something that you'd agree to implement (privacy concern?)? Do we already have the APIs behind to get this information?

**Comment by ValentinH** [comment]
It's partly a duplicate of #1841 though.

**Comment by SaraVieira** [comment]
Hey!

We have the API to see how many forks you have in a sandbox so we can implement that easily but I don't think we have the users, mostly because you can use codesandbox as a guest

@CompuIves ?

**Comment by zurcacielos** [comment]
I can't see the sandboxes that I liked, meaning my starred or favourites. So if the feature is not there, it should be bi-directional with this feature request.
