### ISSUE TITLE
Polyfill `fetch` in tests

### ISSUE THREAD

**Issue by kentcdodds** [codesandbox/codesandbox-client#1861]
I believe that jest does this by default. It'd be great if codesandbox did it too.

Here's an example:

[![Edit 0qy6ov8x10](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0qy6ov8x10?fontsize=14&module=%2Fsrc%2Ftest.test.js&previewwindow=tests)

The test that fails:

```javascript
test('fetch is defined on window', () => {
  expect(window.fetch).toBeDefined()
})
```

**Comment by kentcdodds** [comment]
Note, my temporary fix is to add a `src/setupTests.js` file that does this:

```javascript
import fetch from 'node-fetch'

if (!window.fetch) {
  window.fetch = fetch
}
```

[![Edit 0qy6ov8x10](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x7wlpwo7qp?fontsize=14&module=%2Fsrc%2Ftest.test.js&previewwindow=tests)

**Comment by CompuIves** [comment]
Good one! This one was an easy fix luckily 😄. I'm expecting to deploy it tomorrow morning if that's okay.

**Comment by kentcdodds** [comment]
That was fast!

![wow](https://media.giphy.com/media/4cUCFvwICarHq/giphy-downsized.gif)
