### ISSUE TITLE
🐛 Netlify Deployment breaks on Site Name Change

### ISSUE THREAD

**Issue by Saeris** [codesandbox/codesandbox-client#1863]
**Reproduction steps:**

1. Create a new sandbox and deploy to Netlify
2. When deployment is complete and the site is live, claim the site
3. In the Netlify site control panel, change the site name (General > Site Details > Change Site Name)
4. Refresh the Sandbox page, go to deployment tab. Deploying will create a new site instead of deploying to the existing site.

**Expected behavior:**

Netlify deployments should be linked to the Sandbox via the site's API ID (General > Site Details > API ID), not by the Site Name.

**Possible Solution:**

When a site is deployed to Netlify, the API ID should be saved to the Sandbox's internal database entry. This way for both client and container sandboxes, the API ID should always be used for future deployments by the Owner/Team Members of a sandbox. Additionally, users should be able to manually specify a Netlify Site ID through the UI, possibly under the Project Info tab, or as an option inside of the Netlify Deployment UI.

Originally I thought to follow Netlify's own CLI docs to figure out how to link a site, in which they recommend setting an environment variable named `NETLIFY_SITE_ID`, but this does not work with the Netlify deployment integration, nor would it work with client sandboxes (which do not support environment variables).

**Workaround:**

You can re-link your Sandbox and Netlify Site by renaming the site with the following pattern:

`csb-<sandbox id>`

At this time I haven't tested whether or not adding a custom domain would break the link to CodeSandbox.

**Comment by SaraVieira** [comment]
damn, you found my shame :(

**Comment by Saeris** [comment]
haha, ask me to test something for ya and you can bet I'm gonna find a way to break it!

It's okay! Looks like it should be a simple fix~

**Comment by FezVrasta** [comment]
Is there any update about this issue?

**Comment by LeanKhan** [comment]
Also having this issue, but when I tried to change it back to the former app name Netlify says it's 'already in use' :(
