### ISSUE TITLE
One file doesn't render it's tab correctly

### ISSUE THREAD

**Issue by cfjedimaster** [codesandbox/codesandbox-client#1873]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?
I'm noticing *one* particular file in my project has issues with the tab. In the screenshot below you can see how the close icon isn't rendered right:

![image](https://user-images.githubusercontent.com/393660/57466310-fded2d80-7245-11e9-8749-583933e01c74.png)

Yesterday while testing I even saw the close icon disappear and I couldn't close the file easiler.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser |  Firefox (latest)
| Operating System | Win10

**Comment by abdullahtariq1171** [comment]
hey @cfjedimaster could you share the project link or minimal reproducible example of the issue?

**Comment by cfjedimaster** [comment]
Here: https://codesandbox.io/s/5w5zvnj3mn. Does that help? Recreated it just now:
![image](https://user-images.githubusercontent.com/393660/57690873-4b7fe680-7608-11e9-9370-d5945995840f.png)

**Comment by abdullahtariq1171** [comment]
hey thank you @cfjedimaster. Its very helpful.

It causes issue on Firefox, works fine on Chrome and Safari. Will look into this.

**Comment by dfmartin** [comment]
Just ran across this as well.  And in my limited investigation I came across this using the devtools in Firefox:

css selector: 
`.monaco-workbench .part.editor>.content .editor-group-container>.title .tabs-container>.tab.sizing-fit`

uses `min-width: fit-content;` and it shows as an invalid property value.  Changing it to `min-width: min-content;` seems to fix it and continues to work in chrome.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/min-width) the `fit-content` value is supported in Firefox using the vendor prefix `-moz-`
