### ISSUE TITLE
Messy GitHub Commits

### ISSUE THREAD

**Issue by AlienKevin** [codesandbox/codesandbox-client#1880]
# 🐛 bug report

###  Link to sandbox:
1. A small [React demo](https://codesandbox.io/s/o43839o5r6) I worked on ([GitHub](https://github.com/AlienKevin/React-KeyEvents-Demo/commits/master)). For whatever reason, the initial commit is repeated and the newest commit is merged into master:

#### Screenshot of commit history
![image](https://user-images.githubusercontent.com/22850071/57520340-67734780-72eb-11e9-9281-01aa275c1a6e.png) 

2. A more complex [React app](https://codesandbox.io/s/o43839o5r6) ([GitHub](https://github.com/AlienKevin/Quizzer/branches)). Codesandbox this time created another branch for me and also have the weird merging and double initial commit problem:
#### Screenshot of commit history
![image](https://user-images.githubusercontent.com/22850071/57520633-216ab380-72ec-11e9-9c8e-59b06cf70c0d.png)
![image](https://user-images.githubusercontent.com/22850071/57520709-51b25200-72ec-11e9-9f68-1f5102d6afd2.png)
Most commits are made within codesandbox except the `Merge branch 'master' into csb-1557331649433`.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Current
| Browser | Chrome
| Operating System |Windows 10

**Comment by lbogdan** [comment]
Hey @AlienKevin 

Can you please give us a step-by-step account of what you did, and what happened vs. what you were expecting to happen?

**Comment by AlienKevin** [comment]
I don't remember the exact steps but currently, codesandbox is committing to a different branch (csb-1557489448219) than master and I would like a way to at least always commit to master. Or even better, maybe having more git commands like "pull", "push", "commit all", etc. like the ones in VS Code.

**Comment by SaraVieira** [comment]
Hey!

All of this should now be fixed with the new GitHub integration where we do give you the option to push to master and it also pulls from master and does all the merging magic
