### ISSUE TITLE
Feature request to use npm link

### ISSUE THREAD

**Issue by rg4real** [codesandbox/codesandbox-client#1883]
# 🌈 Feature

It would be awesome to use `nm link` functionality to swap some packages from node_modules. Or is it possible right now?

**Comment by lbogdan** [comment]
You can currently use `npm link` with a server sandbox (e.g. https://codesandbox.io/s/node ), by running it inside the terminal - you have to own the sandbox in order to open a terminal, so make sure you fork the `node` template first.
