### ISSUE TITLE
Can't commit to GitHub because "You need to save all modules before you can commit"

### ISSUE THREAD

**Issue by AlienKevin** [codesandbox/codesandbox-client#1884]
# 🐛 bug report

## All files are saved but Codesandbox denies a new commit and output error message: "You need to save all modules before you can commit".

<img src=https://user-images.githubusercontent.com/22850071/57536012-4aea0600-7311-11e9-9188-678b71c191b6.png width="300px"/>

 It also seems that `Save All` doesn't work. And if I **refresh the page then I can make commits**.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Newest
| Browser | Chrome
| Operating System |Windows 10

**Comment by KalinSav** [comment]
I have the exact same issue! Hope someone can help

**Comment by madnilo** [comment]
Had the same problem. **Reloading the page** solved it - without losing any changes. 

Thanks for sharing that info!

**Comment by suriyaaap13** [comment]
Just go to the respective files where it is showing changes is not done and press ctrl + s now you can commit by writing the summary
