### ISSUE TITLE
Dynamic import not working

### ISSUE THREAD

**Issue by AlienKevin** [codesandbox/codesandbox-client#1887]
# 🐛 bug report

## Dynamic import is not working
I'm using the following function to load codemirror mode based on user-selected language:
```js
async function loadModule(url) {
  console.log("loading module: " + url);
  try {
    await import(url);
    // await import("codemirror/mode/clike/clike");
    // await import("codemirror/mode/javascript/javascript");
  } catch (error) {
    console.log(error);
  }
  console.log("finished loading module: " + url);
  return;
}
```
I checked that the import path is correct because static imports work (this is my temporary workaround). However, when I tried to dynamically import using a variable like `await import(url);`, there's an error ModuleNotFound. If I replace the variable with a string like await `import("codemirror/mode/clike/clike");`, the error is gone but codemirror doesn't have syntax highlighting.

### Screenshots
using string as url in dynamic import:

![a0173c77-8c60-408e-85ef-a39aa4260b9c](https://user-images.githubusercontent.com/22850071/57576584-f9d13380-7430-11e9-8025-f86285c18864.gif)

Verification that the import path is correct:

![0d79e7ba-6fa4-42a3-9bd2-155447125328](https://user-images.githubusercontent.com/22850071/57576588-1cfbe300-7431-11e9-9051-0eeb667c2a4e.gif)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Latest
| Browser | chrome
| Operating System |windows 10

**Comment by tomayac** [comment]
This also affects us in https://github.com/excalidraw/excalidraw/issues/512.

**Comment by tomayac** [comment]
Update: it looks like Excalidraw is rather affected by https://github.com/codesandbox/codesandbox-client/issues/1774.

**Comment by silviubogan** [comment]
I would also love dynamic imports to work inside webpack. Currently this is how they show up as not working:

![image](https://user-images.githubusercontent.com/198924/98011985-3bae2080-1e01-11eb-9a7c-3c2b18cd0e44.png)

![image](https://user-images.githubusercontent.com/198924/98012118-65674780-1e01-11eb-950c-c956f1dfa0dd.png)
