### ISSUE TITLE
🐛 GitHub Importer fails to find package.json when Repository's default branch isn't Master

### ISSUE THREAD

**Issue by Saeris** [codesandbox/codesandbox-client#1891]
It appears that there is an issue with the GitHub Importer wherein if the main branch of the repository being imported is set to anything other than Master. When a user tries to import the sandbox, an error is thrown stating that `package.json` cannot be found.

Here's an example repository that's results in this error:

https://codesandbox.io/s/github/Saeris/Flickr-Wormhole

https://github.com/Saeris/Flickr-Wormhole

To reproduce and test, I would recommend testing against a different repository, as the one I linked here will throw a file limit error if you try to import a specific branch, as can be observed here:

https://codesandbox.io/s/github/Saeris/Flickr-Wormhole/tree/develop

Perhaps the importer should instead choose a repo's default branch instead of master when importing.

**Comment by beardedpayton** [comment]
I just tested with one of my older repos and it worked fine.

Default branch is test
https://codesandbox.io/s/github/beardedpayton/paytonburdette.com
https://github.com/beardedpayton/paytonburdette.com

**Comment by Saeris** [comment]
Your Master branch has a `package.json` though. The problem seems to be that the importer always attempts to import master, and not whatever the default branch is.
