### ISSUE TITLE
Tagged version is INVALID_VERSION / ENOSPC: no space left on device

### ISSUE THREAD

**Issue by lauriejim** [codesandbox/codesandbox-client#1892]
# 🐛 bug report

## Description of the problem

I'm trying to use a [Strapi](https://github.com/strapi/strapi) application on CodeSandbox and the dependence version is `3.0.0-next.1`, I got this error:

```
Could not fetch dependencies, please try again in a couple seconds: 
Something went wrong while packaging the dependency strapi@3.0.0-next.1:
INVALID_VERSION
```

What can I do to make my application works on CodeSandbox ?

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  https://codesandbox.io
| Browser | Chrome 74.0.3729.131
| Operating System | macOS Mojave10.14.2

**Comment by abdullahtariq1171** [comment]
https://ata-fetcher.cloud/api/v5/typings/strapi@3.0.0-next.1.json sometimes returns which  

```
{
  status: "error",
  files: { },
  error: "e4f744a6: Command failed: cd /tmp && mkdir e4f744a6 && cd e4f744a6 && HOME=/tmp npm i --silent --production strapi@3.0.0-next.1 --no-save Unhandled rejection Error: ENOSPC: no space left on device, write ",
  stack: "Error: e4f744a6: Command failed: cd /tmp && mkdir e4f744a6 && cd e4f744a6 && HOME=/tmp npm i --silent --production strapi@3.0.0-next.1 --no-save Unhandled rejection Error: ENOSPC: no space left on device, write at ChildProcess.exithandler (child_process.js:275:12) at emitTwo (events.js:126:13) at ChildProcess.emit (events.js:214:7) at maybeClose (internal/child_process.js:925:16) at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)"
}
```

**Comment by lauriejim** [comment]
Interesting! What is the server size available for a project on CodeSandbox ?

**Comment by joumichy** [comment]
Up

**Comment by lauriejim** [comment]
Random message to keep this issue open, since it's not fixed.
GitHub bot, you will not get me 🤪

**Comment by afroz1198** [comment]
![3](https://user-images.githubusercontent.com/30230183/93902890-b6b9ec80-fd15-11ea-917f-6e77b9a30376.png)

:(

**Comment by SaraVieira** [comment]
Can someone please share a sandbox with this error?

The first shared one is no longer active :(

**Comment by afroz1198** [comment]
It is Codesandbox on Hackerrank,I tested the same code on Codesandbox itself,it worked fine :)

![55](https://user-images.githubusercontent.com/30230183/94101914-7c079f80-fe4e-11ea-8cd1-24fa959ef9b2.png)
:(

**Comment by yannbf** [comment]
For anyone having similar issues what might solve is to open the terminal, then:
`rm -rf node_modules && yarn`

It solved for me :)

**Comment by lbogdan** [comment]
@yannbf That only works with server / container sandboxes, the initial issue was (most probably) with a client sandbox.

**Comment by marco910** [comment]
@yannbf In my case (with a Gatsby sandbox) it worked

**Comment by wintercounter** [comment]
> Can someone please share a sandbox with this error?
> 
> The first shared one is no longer active :(

https://codesandbox.io/s/ccss-demo-vanilla-js-bhw3z

Try to upgrade `ccss` to `5.0.0-alpha.5`

**Comment by wintercounter** [comment]
BTW it's not about the tagged version. It seems like the problem is the case when using a different format than `X.X.X`. I accidentally released an alpha as latest and that fails also.

**Comment by therealgilles** [comment]
I had a 535MB 'core' file left in my sandbox, recovered space after deleting it.

**Comment by duoluodexiaoxiaoyuan** [comment]
> For anyone having similar issues what might solve is to open the terminal, then:对于遇到类似问题的任何人，可以解决的方法是打开终端，然后： `rm -rf node_modules && yarn`
> 
> It solved for me :)它为我解决了:)

![image](https://github.com/user-attachments/assets/06a975e5-be67-4e1b-ab5b-5f5af24b6366)
i can't see terminal
