### ISSUE TITLE
Problem deployment with Zeit

### ISSUE THREAD

**Issue by dracero** [codesandbox/codesandbox-client#1895]
# 🐛 bug report

## Description of the problem
I'm trying to implement a sandbox to try backend functionality and found the following error:

An unknown error occurred when connecting to ZEIT
Could not authorize with ZEIT

The sandbox URL is:

https://codesandbox.io/s/zkq7wp41ll

Before last week I was deployed a lot a sandboxes without any problem.

If it is a well-known problem could you please give some directions in order to Solve It.

Thanks in advance for your help.

**Comment by lbogdan** [comment]
Hey @dracero ,

Are you still experiencing issues deploying to ZEIT Now?

**Comment by dracero** [comment]
Yes, the same authentication problem.

**Comment by SaraVieira** [comment]
Hey!

Sorry for the huuuge delay

Do you still have this?

Seems like it was a problem with the API on that time
