### ISSUE TITLE
GitHub import / commit issues with big files

### ISSUE THREAD

**Issue by HighOnDrive** [codesandbox/codesandbox-client#1900]
I have rather large collections of files I'd like to upload. I've already had to chop files up a fair amount and a few are more than a MB in size. Its a total guessing game trying to figure out the right size.

If I create a Github repo and place files in it and one of them happens to be to large I'm screwed. I have to wipe out the repo then chop up files some more and try with a new repo all over again!

Anyways, I get this error that "the requested entity is to large" or something to that effect. Any tips on how big files should be and how to not have one file mess up everything would be great :)

**Comment by HighOnDrive** [comment]
The largest file I'm presently trying to pull from Github to CodeSandbox 434 KB. Yet I'm getting "request entity to large" errors continually. What is the problem?

**Comment by lbogdan** [comment]
Hey @HighOnDrive ,

Can you please share your github repository URL?

Also, have you tried [exporting your project using the CLI](https://codesandbox.io/docs/importing#export-with-cli)?

**Comment by HighOnDrive** [comment]
I read about the CLI today but I'm not sure which terminal I'd use and how to open the exported files in CodeSandbox once they are exported or where the exported project would even be stored. Suppose I could use WSL or the terminal in VSCode? Maybe the CLI is for server container related projects only?

The specific repo I'd like to work on just has specification files. These are just straight text files that are tab indented so I can take advantage of the outliner in Monaco to manage sections of text. The files have no extension so they default to standard text. A client has given me these private files to turn into code but I've got to be able to view and work with them first. I'm not able to share these client files.

As a patron, what is the file size limit and how much can I store? I'd be interested in the CLI approach if that would work but I would not need a server to run my files for now.

**Comment by lbogdan** [comment]
> I'm not sure which terminal I'd use
Your local terminal, be it `cmd`, `Git Bash` `cmder`, or whatever your preferred terminal is on Windows.

**Comment by HighOnDrive** [comment]
Alright, does the CLI the automatically open the exported project in a CodeSandbox browser tab if the browser is open? Does the CLI produce a client side sandbox?

**Comment by lbogdan** [comment]
> does the CLI the automatically open the exported project in a CodeSandbox browser tab if the browser is open

It will show the newly created sandbox URL, I don't remember if it also opens it in the browser.

> Does the CLI produce a client side sandbox?

It uses the same logic to detect the template as the git importer. If you want to override the template, you can create a `sandbox.config.json` file in your project root folder with contents like
```json
{
  "template": "static"
}
```

**Comment by HighOnDrive** [comment]
It has been a long day, will try the CLI tomorrow...

**Comment by HighOnDrive** [comment]
The CLI works fine and creates a new sandbox. Creating a Github repository from CodeSandbox does not work. I still get the same error message "request entity is to large". Out of the nine files I'm using to test the CLI the largest is only 434 KB.

**Comment by HighOnDrive** [comment]
@Ibogdan Thanks for the nudge toward the CLI option. I am fortunate to have all this day job time to spend using CodeSandbox so this will work perfect for me. There does seem to be a Github and file size or something issue but it will not hold up my daily productivity.

Thanks also for your work on Containers, just learning more about them now.

**Comment by lbogdan** [comment]
Glad you sorted it out, although we should probably investigate the github file size issue.

> Thanks also for your work on Containers, just learning more about them now.

You're welcome, let me know if you have any questions or issues on our [Spectrum channel](https://spectrum.chat/codesandbox).
