### ISSUE TITLE
Express route params error

### ISSUE THREAD

**Issue by nithinm50** [codesandbox/codesandbox-client#1904]
# 🐛 bug report

## It returns the whole string that been appended followed by the URL rather than providing the string that is appended to the URL followed by '**:**'
example:
 **https://k3699kvq7v.sse.codesandbox.io/api/single-post:123** should return '**123**' when a req.parms.id is console logged rather than outputting '**:123**'

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Beta version
| Browser          | Chrome / 74.0
| Operating System | Windows 10 pro

**Comment by lbogdan** [comment]
Hey @nithinm50 ,

I'm not sure I get what the issue is. Is it a CodeSandbox issue, or an express one? To me, it looks more like the latter, did you try running that locally and checking that you get a different behavior?

**Comment by nithinm50** [comment]
Hey @lbogdan ,
The API request to the following endpoint http://localhost/api/single-post:123 print the parameter prints '123' without 'colon' whereas the same code in CodeSandbox prints ':123' and when a request to unregistered route made witch accepts parameters will result with an empty character followed with the parameter characters
example:
request to unregistered route https://k3699kvq7v.sse.codesandbox.io/api/single-posts returns ' s' as a parameter.
I see the error persisting on CodeSandbox rather than on my local system.

**Comment by lbogdan** [comment]
Just tested locally, got the same behavior as in the sandbox. Are you sure you're testing locally with exacly the same `express` version as in the sandbox - `4.16.4`?

**Comment by lbogdan** [comment]
Also, correct me if I'm wrong, but what you actually want is [route parameters](https://expressjs.com/en/guide/routing.html#route-parameters), and in this case the route should be `/single-post/:id` (notice the extra `/`), which would match URLs like `http://localhost/api/single-post/123`.

**Comment by nithinm50** [comment]
@lbogdan ,
Just now saw I was running different application routing file on localhost with the route as `/single-post/:id`. I overlooked it while comparing the code. thanks a lot for noting the error that was made by me.
