### ISSUE TITLE
Update Contributing Docs Getting Started Section with Build steps

### ISSUE THREAD

**Issue by benschac** [codesandbox/codesandbox-client#1905]
# 🐛 bug report

## Description of the problem
Document to start the project needs to be updated: https://spectrum.chat/codesandbox/help/yarn-start-cannot-find-module-codesandbox-common-lib-config-env~b4cd9ab3-1f7c-490d-b32a-5114173678fe
## How has this issue affected you? What are you trying to accomplish?
- I haven't been able to start the project locally from my machine.
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome 73
| Operating System | OSX 10.14.3

**Comment by Saeris** [comment]
Updated local development documentation is on the roadmap. I don't have an ETA for you right now but I am personally working on it.

If you are encountering specific build errors, please post them here. While there are some additional steps needed to get certain features working in a local environment, you should be able to start the client from the root directory by simply running `yarn && yarn start` (keep in mind the build can take quite a while).

**Comment by benschacprolific** [comment]
:D tyty @Saeris.  I did, I'll give it another go. I'm not sure if it's my version of node or `node-gyp` Please let me know if there's anything else I can do to help.

**Comment by Saeris** [comment]
Oh yeah, that reminds me! I found that the client will fail to build on Node 12, as some of our dependencies haven't been updated to run on it yet. Please stick to Node 10 to avoid these sorts of build errors!

**Comment by benschac** [comment]
This is very helpful! Ty

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by benschac** [comment]
@Saeris -- that worked! I'm running on localhost:3000

What I was doing wrong:
- The contributing docs say `yarn start to start the app`.  I thought that was for each individual package.
- I wasn't using node v. 10

Adding that to the docs now.

**Comment by benschac** [comment]
Thank you so much! I'm so happy I finally got this to run on my machine locally!

**Comment by lbogdan** [comment]
@benschac Nice, good job! 🔥 

Closing this, as it looks like it's solved.
