### ISSUE TITLE
Update README.md to better reflect the standard usage of the file

### ISSUE THREAD

**Issue by thecodingaviator** [codesandbox/codesandbox-client#1906]
I believe that we should update the `README.md` file and move the Contributors' name out of the file into a separate file. README.md can then reflect more about the project. Some ideas of which might include:

* The Code of Conduct
* A better organization of the sponsors' logos in a symmetrical form
* A re-write of the description of `codesandbox`
* Features of `codesandbox`

Among other things

I'd be glad to take this up if we decide that we want to go ahead with these things, as I believe this would give the project a more professional look while keeping it beginner-friendly.

**Comment by thecodingaviator** [comment]
Hi @lbogdan , wondering if this is still on the roadmap

**Comment by SaraVieira** [comment]
Hey!

About your ideas:

* The Code of Conduct - Should definitely be there
* A better organization of the sponsors' logos in a symmetrical form - We don't really do any more open collective logos and stuff 
* A re-write of the description of codesandbox - We already did that :)
* Features of codesandbox - That would be great too

Also a link to https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md would be amazing to link people to it :)
