### ISSUE TITLE
Can't access sandbox after adding alias in package.json

### ISSUE THREAD

**Issue by herrKlein** [codesandbox/codesandbox-client#1908]
# 🐛 bug report

## Description of the problem
Can't access my sandbox 
## How has this issue affected you? What are you trying to accomplish?
Black page when loading the sandbox. I added an alias in the package.json (probably at the wrong place in the package.json)

### Your Environment
OSX chrome

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 88zo93kxz0
| Browser          | Chrome
| Operating System |OSX

**Comment by Saeris** [comment]
Could you paste an example `package.json` file that would reproduce this or better yet share a repository that we can import to investigate the cause?

**Comment by herrKlein** [comment]
I have no repository of this project, I created this in codesandbox, and since I can't access the package.json I'm not able to reproduce that.

However, I included a link to the sandbox ( which I can't access ) maybe this can be used to recall the actual files?
