### ISSUE TITLE
Feature request: Sort by date

### ISSUE THREAD

**Issue by diegohaz** [codesandbox/codesandbox-client#1909]
# 🌈 Feature

Currently, it's possible to sort search results by number of views or likes. I would like to have the option to sort them by date as well.

I used to use CodeSandbox search to see how people were using my libraries so I could improve them based on some real usage. I found it much more effective than doing some kind of questionnaire.

Being able to sort search results by date (most recent first, for example) would ease this job. Right now, since the creation date has been removed from the cards, it's impossible to continuously check it.

**Comment by SaraVieira** [comment]
Hey!

This is a super valid request!

Working on it now :)

**Comment by diegohaz** [comment]
I see that the whole sort feature [was disabled a month ago](https://github.com/codesandbox/codesandbox-client/commit/23699a51e47b31e0c53ed3a30045761e21d04c8f). Are there plans to turn it on again any time soon?
