### ISSUE TITLE
hover content is blocked when the code is at the top of the file

### ISSUE THREAD

**Issue by newraina** [codesandbox/codesandbox-client#1910]
# 🐛 bug report

## Tooltip contents are blocked by editor tab:

![image](https://user-images.githubusercontent.com/10708802/57746523-135dce00-7704-11e9-8d8d-509e5f278408.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1557437664-2c65ca12f
| Browser          | Chrome 74.0.3729.131
| Operating System | MacOS 10.14.4

**Comment by nienkedekker** [comment]
I can reproduce this in Firefox and Safari as well. If no one else is claiming this, I'd like to take a swing at this :)

**Comment by tony19** [comment]
*Related:* #554

**Comment by divyenduz** [comment]
This does not happen anymore with the latest CodeSandbox 🎉
