### ISSUE TITLE
Codesandbox is not pulling most recent Github commit.

### ISSUE THREAD

**Issue by mattcarlotta** [codesandbox/codesandbox-client#1911]
# 🐛 bug report

I started working on a project through codesandbox and making commits to a Github repository. Due to some performance issues on the codesandbox platform, I switched to a local environment and started to add commits to the repository. Unfortunately, codesandbox is still pulling from the last known github commit that was pushed from within the codesandbox environment, which is about 10+ commits behind.

## How has this issue affected you? What are you trying to accomplish?

Codesandbox should update and stay in sync with a Github repository regardless of how a commit was made.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  PROD-1557437664-2c65ca12f
| Browser          |  Chrome  74.0.3729.157
| Operating System | LinuxMint 19.1 4.1.15.0-48

**Comment by lbogdan** [comment]
Hey @mattcarlotta ,

The sandbox you provided - https://codesandbox.io/s/2vxo7o870j is a fork of the github imported sandbox - https://codesandbox.io/s/github/mattcarlotta/react-hooks/tree/master/ . It is intended behavior that only github imported sandboxes are kept in sync with the github repository.

**Comment by mattcarlotta** [comment]
Ahhh. My bad. Thanks for the quick response!
