### ISSUE TITLE
Does sandbox has a git url

### ISSUE THREAD

**Issue by CITGuru** [codesandbox/codesandbox-client#1913]
# ❔ Question

I am trying to work on a new feature on codesandbox and I am wondering if there's a git repo url for each sandboxes.

**Comment by lbogdan** [comment]
Hey @CITGuru ,

There's not at the moment, but why would you need that?

**Comment by CITGuru** [comment]
I am working on deploying sandbox to heroku. Theres already a deploy to heroku button integration that only requires you to provide the repo url and some app schema through the url params.

**Comment by CITGuru** [comment]
@lbogdan sandboxes are exportable to github. Is there a way to check if a sandbox is exported and also get the repo url
