### ISSUE TITLE
Preview showing result from another sandbox when typing

### ISSUE THREAD

**Issue by lintonye** [codesandbox/codesandbox-client#1921]
# 🐛 bug report
## Description of the problem
It keeps showing me the result of an old project when I'm typing. I often need to manually refresh in the preview window to see the latest result.

Clicking Refresh on the entire sandbox seems to mitigate the issue.

## How has this issue affected you? What are you trying to accomplish?
Steps to reproduce:

- Fork a sandbox
- Make some changes in the code that cause an error (this seems to cause the issue to happen more often)
- Fix the error

### Link to sandbox: [link](https://codesandbox.io/s/mouseparallaxspringy-pt866) (optional)
I have seen it happen in multiple sandboxes.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome (Version 74.0.3729.131 (Official Build) (64-bit) / Firefox (66.0.5 (64-bit))
| Operating System | macOS X 10.14.4

**Comment by sp00x** [comment]
This happens to me also quite often. I mostly work with Vue projects, if that helps in shedding any light on things. Yesterday it was switching between the results of 2 other, older projects.
