### ISSUE TITLE
Copy-Pasting recursive react component can lead to chrome error and freezing

### ISSUE THREAD

**Issue by EyMaddis** [codesandbox/codesandbox-client#1923]
# 🐛 bug report

## Description of the problem
I tried to slightly adapt an existing [codesandbox](https://codesandbox.io/s/github/bvaughn/react-window/tree/master/website/sandboxes/variable-size-list-vertical) by copying 
```jsx
<List
    className="List"
    height={150}
    itemCount={1000}
    itemSize={getItemSize}
    width={300}
  >
    {Row}
  </List>
```

into Line 17.

This leads to the website becoming unresponsive and crashing of the chrome tab.
It only seems to happen if there is a dependency cycle. Pasting the following works:

```jsx 
<List
    className="List"
    height={150}
    itemCount={1000}
    itemSize={getItemSize}
    width={300}
  >
    {SomethingElse}
  </List>
```

## How has this issue affected you? What are you trying to accomplish?
I cannot paste the code I need, I need to manually write the code myself or replace `Row` which something else and then update it.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/github/bvaughn/react-window/tree/master/website/sandboxes/variable-size-list-vertical

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1557935916-f212746b9
| Browser          | Version 74.0.3729.157 (Official Build) (64-bit)
| Operating System | MacOS Mojave 10.14.4 (18E226)

**Comment by lbogdan** [comment]
Hey @EyMaddis ,

I don't really get what the actionable is here. For me, however I try to do it, either by directly copy-pasting that snippet, or replacing `{Row}` with something else, copy-pasting, and putting `{Row}` back, the result is the same - the tab crashes, which kinda makes sense for a recursive component with no bounds.

**Comment by EyMaddis** [comment]
Hmm... of course you are right.
I am not sure why it "worked" when I was writing it manually.
