### ISSUE TITLE
Adventures with the CLI and some subsequent questions

### ISSUE THREAD

**Issue by HighOnDrive** [codesandbox/codesandbox-client#1926]
The CLI is a great way to move files into sandboxes. Being a newbie I first tried moving a mess of text, fonts and images to sandboxes. This choked up the CLI and then I saw that the CLI showed me these static files in a nice list. I am now in the process of removing them because I am only interested in the text related files.

In the aftermath of my ignorance I now want to remove the static files that ended up in storage. The Storage Manager makes me select each and every static file one by one to delete them and also crashes half the time. Is there a way to bulk select all or at least regions of files and then delete them?

A little more insight on how to load projects via the CLI and how it handles the different files that might be included in one upload would be useful in the documentation, which I like to read if it is there to begin with. Right now images are choking the upload so I'm just removing them from directories prior to upload. That works okay for the files I'm dealing with now but it would be good to know more for future projects.

Any tips? If Storage is so easy to fill it should also be easy to empty!

**Comment by lbogdan** [comment]
Hey @HighOnDrive ,

Thanks for this detailed description, both are very good points, indeed! To easier follow them, could you leave this issue to be CLI related, and open another one related to deleting files? Thanks!
