### ISSUE TITLE
Allow private repository creation from the CodeSandbox

### ISSUE THREAD

**Issue by SergeyVolynkin** [codesandbox/codesandbox-client#1928]
# 🌈 Feature

![image](https://user-images.githubusercontent.com/34238697/57983687-957c2880-7a5d-11e9-8a56-317603090c31.png)
Allow creation of private repo from CodeSandbox

Checkbox "Private repository" under the "Repository Name" input field

–

**Comment by Saeris** [comment]
This would be nice! However we'd only be able to support this for Client Sandboxes, as currently we don't support private repositories for Containers.

**Comment by jthegedus** [comment]
@SaraVieira is this resolved alongside https://github.com/codesandbox/codesandbox-client/issues/1159#issuecomment-686480216 ?

**Comment by SaraVieira** [comment]
Not really, I mean we support creating private repos if the sandbox is private but it's not really a choice :/

**Comment by SaraVieira** [comment]
I'm gonna remove the stale label 

Thank you for pointing it out

**Comment by jthegedus** [comment]
>we support creating private repos if the sandbox is private

Is that not enough? I fear the option to configure the privacy of the repo independently of the sandbox would lead to people being confused about the visibility of their code and thus lead to people leaking sensitive information.

An issue for UI design I guess.

**Comment by SaraVieira** [comment]
That's also valid, you can then decide what you want to do in GitHub and we already have a pretty hard integration to grasp for a begginer

I'm gonna close this 

Thank  you
