### ISSUE TITLE
Embed on Medium does not work with urls with slug

### ISSUE THREAD

**Issue by flut1** [codesandbox/codesandbox-client#1929]
# 🐛 bug report

## Description of the problem
I've noticed that newer sandboxes now have a couple of words in the URL slug, rather than just a hash. For example:

https://codesandbox.io/s/confident-worker-3g2yt

In the 'share' dialog, I get the following share url under "Editor url (also works on Medium)":

https://codesandbox.io/s/confident-worker-3g2yt?fontsize=14

However, when pasting this into a Medium article, it inserted a regular link rather than an embed. I eventually figured out that the embed only works after removing the words from the URL, and including just the hash. Such as: https://codesandbox.io/s/3g2yt?fontsize=14

### Links to sandbox:

- [example sandbox with issue](https://codesandbox.io/s/confident-worker-3g2yt?fontsize=14)
- [reproduction on embed.ly tool](https://embed.ly/code?url=https%3A%2F%2Fcodesandbox.io%2Fs%2Fconfident-worker-3g2yt%3Ffontsize%3D14)
- [same example fixed on embed.ly tool](https://embed.ly/code?url=https%3A%2F%2Fcodesandbox.io%2Fs%2F3g2yt%3Ffontsize%3D14)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest
| Browser          | Google Chrome
| Operating System | Windows

**Comment by techlab23** [comment]
I encountered the same issue and it left me head scratching. Thanks for @flut1 for showing the workaround.

**Comment by Matt-Dionis** [comment]
Unfortunately, I can't get embeds on Medium to work now even after removing the initial words. This, for example, displays on Medium as a link rather than an embed:

https://codesandbox.io/s/fym98?codemirror=1&fontsize=20&hidenavigation=1&module=%2Fsrc%2FApp.js&view=editor&highlights=14

**Comment by flut1** [comment]
@Matt-Dionis  I'm getting the same result using the link you provided, and also if I create a new Sandbox. It now doesn't even show a link preview tile, but it just stays a regular link.

Strangely enough the example from my original post _does_ still work after removing the words. Maybe there is some kind of problem with newly created sandboxes?

**Comment by CompuIves** [comment]
Hey! Going to fix that today, sorry for this inconvenience!

**Comment by Matt-Dionis** [comment]
Thanks, @CompuIves! Looking forward to the fix.

**Comment by CompuIves** [comment]
Hey! It turns out that this was also happening for github urls. I just deployed the fix and it should work as expected now!

**Comment by Matt-Dionis** [comment]
Thank you, @CompuIves! I can confirm that these embed links work as expected now!
