### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by CITGuru** [codesandbox/codesandbox-client#1932]
# 🌈 Feature

Deploying to Heroku is now possible using my [codesandbox fork](https://github.com/CITGuru/codesandbox-client) with some little steps to follow. 

Deploying to heroku is kinda different from deploying to zeit or netlify. Heroku needs more settings file to define to be able to know how to run your code. Heroku either needs an `app.json` or `Procfile` to be able to run your app.

There are two ways we can make this work:

- Deploy to Heroku Url: We only need to provide the sandbox github url to achieve this and you will be taken to heroku page to deploy your app.
- Deploy Server: We need a special server that deploys it and send back logs.

I have written an article that explains everything and how to deploy your app right now: https://dev.to/oyetoket/how-i-deployed-codesandbox-apps-to-heroku-ndo

**Comment by Developerayo** [comment]
Did you create a Pull Request for this? because I cannot find it.
if not create the Pull Request and reference this opened issue.

**Comment by CITGuru** [comment]
@Developerayo its not ready yet for PR
