### ISSUE TITLE
GitHub: Set Root Folder?

### ISSUE THREAD

**Issue by karlhorky** [codesandbox/codesandbox-client#1972]
# 🌈 Feature

Instead of setting the sandbox root to the root of the repository, what is the opinion of CodeSandbox to allowing setting the root folder? For example, creating a sandbox based on the contents of a folder in a repo?

Would be interesting for monorepos...

**Comment by CompuIves** [comment]
Well, that's possible already 😄. Just add the path to the url:

https://codesandbox.io/s/github/reduxjs/redux/tree/master/examples/todomvc

**Comment by karlhorky** [comment]
Sweet, didn't know about that! Thanks for the quick answer! Sorry for the bother.
