### ISSUE TITLE
infiniteLoopProtection to be also a number

### ISSUE THREAD

**Issue by adyz** [codesandbox/codesandbox-client#1973]
# 🌈 Feature

I am working on a tree react component and it uses recursion and this `infiniteLoopProtection` setting helped me a lot, but I would like to test how performant is my code also and this auto limit breaks my code that I expect to run more than 10001 times, but not above 30000 let's say (depending on my tree depth).

I think for me it would be useful to have this infiniteLoopProtection as a number also so that I can test my tree, but still be protected if my code runs more than my tree code expectations.

Thanks a ton!

**Comment by SaraVieira** [comment]
Thas a very interesting option really, I will take a look at the implementation and let you know :)
