### ISSUE TITLE
Can no longer @import .sass files from node_modules

### ISSUE THREAD

**Issue by gragland** [codesandbox/codesandbox-client#1977]
# 🐛 bug report

## Description of the problem
You used to be able to import node_module SASS files within another SASS file like so: `@import "~bulma/bulma.sass";` but this now throws an error.

## How has this issue affected you? What are you trying to accomplish?
I need to be able to import a CSS framework's SASS files from inside my app's SASS file so that I can override variables.

### Link to sandbox: [link]() (optional)
Here are some affected sandboxes:
https://codesandbox.io/s/mydivjoyproject-9vd64
https://codesandbox.io/s/7wr7m3wqm1
https://codesandbox.io/s/j7y6wy9m09

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1558343146-fac713406
| Browser          | Chrome
| Operating System | maxOS 10.13.6

**Comment by lbogdan** [comment]
Hey @gragland ,

Looks like this was fixed in #2188 , at least I don't get any errors in the last two sandboxes (the first one was probably deleted in the meanwhile). I'll close this for now, please re-open if you still have issues.

**Comment by gragland** [comment]
@lbogdan Yup works for me now. Thanks!
