### ISSUE TITLE
Start React template with react-scripts@3.0.1

### ISSUE THREAD

**Issue by karlhorky** [codesandbox/codesandbox-client#1979]
# 🌈 Feature

At the moment, when I start a new sandbox, it pulls in `react-scripts@2.1.8` as a dependency.

<img width="297" alt="Screen Shot 2019-05-27 at 11 35 14" src="https://user-images.githubusercontent.com/1935696/58411065-bfdc7000-8073-11e9-9c36-d8b188262700.png">

Should it be using `3.0.1`? I did a bit of searching and found @Saeris's commit, which seems to be using `3.0.1`: https://github.com/codesandbox/codesandbox-templates/blame/a835bc2eee26731c728063c91e5d4038be933c04/packages/client/react-template/package.json#L8

Or am I doing something wrong maybe?

**Comment by Saeris** [comment]
Hey! So all of the templates in that repo aren’t running live on CSB yet. In this case I believe our React template is just out of date. We’re working on updating them in the near future.

**Comment by karlhorky** [comment]
Ok, sounds good. I was thinking that this `codesandbox-templates` codebase was not behind the actual templates that were being used in production.

I looked around a bit for the other templates but couldn't find where I could open a PR for bumping the deps. But if you're on it already, then sounds great! I guess we can just leave this open to track the change, if that's alright.

**Comment by SaraVieira** [comment]
Our templates work in very misterious ways and by that I mean we need to tell Ives and then magic happens 

We are thinking of moving all of them to GitHub

**Comment by SaraVieira** [comment]
Hey!

This has been added yesterday :D 

https://codesandbox.io/s/new

**Comment by karlhorky** [comment]
Awesome, thanks everyone!
