### ISSUE TITLE
Accept folders with upload button

### ISSUE THREAD

**Issue by karlhorky** [codesandbox/codesandbox-client#1981]
# 🌈 Feature

As mentioned in #493, it would be nice for CodeSandbox to accept folder uploads from the UI. Currently, clicking on the Upload button in the UI does not allow for uploading folders:

<img width="260" alt="Screen Shot 2019-05-27 at 15 14 07" src="https://user-images.githubusercontent.com/1935696/58422158-2a040d80-8092-11e9-9605-4ed3eed53e34.png">

<img width="408" alt="Screen Shot 2019-05-27 at 15 07 15" src="https://user-images.githubusercontent.com/1935696/58422161-2d979480-8092-11e9-87fe-5b50f8de9ee2.png">

As a workaround, a user can currently drag folders in to the tree.

**Comment by lbogdan** [comment]
Hey @karlhorky ,

I'm pretty sure a HTML `<input>` doesn't support selecting folders, so that's actually a platform limitation.

**Comment by lbogdan** [comment]
Actually, there's https://caniuse.com/#feat=input-file-directory , although the support is not that good. TIL. 🙂

**Comment by karlhorky** [comment]
Ah TIL too! Cool :) wonder if there's a polyfill for it...

**Comment by karlhorky** [comment]
Hm, there was originally a Chrome-only polyfill from WICG, but that was for a previous version of the spec.

I guess the latest advice (from [makandra dev](https://makandracards.com/makandra/54804-html-file-inputs-support-picking-directories)) is to use `webkitdirectory` along with the `multiple` attribute for older browsers:

> Although the property is called `webkitdirectory` and not `directory`, it is supported by Chrome, Firefox, Edge 14+, and Safari 11.1+.
Older browsers support `multiple`, so you should offer that as a fallback.
> 
> Your event handler needs to handle `event.target.files` just like for a multiple input.
> 
> I've seen examples using `directory` but there are no indications this attribute will become standard soon.

So maybe something like this?

```html
<input type="file" multiple webkitdirectory>
```

**Comment by karlhorky** [comment]
not stale
