### ISSUE TITLE
View > Appearance > Toggle Menu Bar requires using the Command Palette to restore the Menu Bar

### ISSUE THREAD

**Issue by chillydk147** [codesandbox/codesandbox-client#1982]
Hello, I was playing about with the layout settings and I somehow disabled all the links at the top for "File, Edit, View etc". The options to change layout setting was also contained in a link beside "File, Edit View". Does anyone know how to switch this back on??? I can no longer save changes to my code via the "File->Save All" option

**Comment by CompuIves** [comment]
Hmm, that is very weird. Is it now back for you @chillydk147?

**Comment by chillydk147** [comment]
No still gone, see attached screenshot
![ss](https://user-images.githubusercontent.com/9335909/58748637-d7509a00-8473-11e9-9c52-6dc384290a47.png)

**Comment by CompuIves** [comment]
Oh wow, the whole menu bar is gone. Does your console say anything in
particular?

**Comment by chillydk147** [comment]
Yep it's gone, no the console says nothing, even when I create a new sandbox the menu still does not show for me

**Comment by Saeris** [comment]
Hmm, you can still toggle this setting via the command palette (`CTRL/CMD+SHIFT+P`) and typing `toggle menu bar`. That should restore the menu bar for you.

Thanks for reporting this! We should consider rolling out a change to this behavior because it's definitelly a bad user experience!

**Comment by chillydk147** [comment]
Thanks for your solution, I've tried to enter "Ctrl+Shift+P" but it opens a Firefox for a private browsing session, I've also tried entering "toggle menu bar" in the console window field but it doesn't work either. I know i need to open this "Command Pallette" but can't see an option for it

**Comment by Saeris** [comment]
> I've tried to enter "Ctrl+Shift+P" but it opens a Firefox for a private browsing session

Ah, yeah I see that's a problem specific to Firefox then. We'll have to do something about that hotkey as it seems the browser won't let us override it.

Another workaround to get the Command Palette up is to press `CTRL/CMD+P`, which if you then add a `> ` character to the beginning will switch from navigating files to entering an editor command. See the example screenshot below:

![image](https://user-images.githubusercontent.com/3144549/58940784-473e7900-872f-11e9-92ac-a6510d7c111b.png)

This behavior should be exactly the same as Visual Studio Code, so the following documentation on it's UI should mostly apply to the CodeSandbox Editor too.

https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette

**Comment by chillydk147** [comment]
Thank so much, that has worked perfect now. The original thing I did was to click "View->Appearance->Toggle Menu Bar", I still don't see why this should be an option unless you can get the menu bar back without using the command pallette.

**Comment by karlmey** [comment]
> you can still toggle this setting via the command palette (CTRL/CMD+SHIFT+P) and typing toggle menu bar. 

@Saeris tried this (Chrome/Windows), not working, can't get my menu back
![image](https://user-images.githubusercontent.com/58620248/70371589-43a1cf80-18d5-11ea-969f-5182ba1f0df0.png)

**Comment by rodrigosanchezg8** [comment]
Had the same issue, hotkey didn't work, solved by clearing the localStorage.

**Comment by Zwornik** [comment]
This solution does not work on Firefox, Chrome and Edge. The menubar is not visible. 
Also, changing settings in File/Preferences/Settings and typing menubar and selecting 'visible' under Menu Bar Visibility does not change the appearance. Reloading the webpage doesn't help either. Help, please.

**Comment by DivyDeshmukh** [comment]
I am facing the same issue now and I am not even getting any options to commit also due to which I am unable to push changes also.
