### ISSUE TITLE
More obvious console clear icon

### ISSUE THREAD

**Issue by pshrmn** [codesandbox/codesandbox-client#1984]
# 🌈 Feature

Currently, the icon for clearing the console is three slightly offset bars (the material design `clear_all` icon). I had actually thought that there was no way to clear the console because the icon didn't really scream "clear" to me.

I'd like to suggest switching up the icons. I've included an image with some possible alternatives.

1. The current icon
2. The material design `clear` icon
3. The material design `block` icon, which is similar to the icon that Chrome's dev tools use
4. The FontAwesome `trash` icon, which is similar to the icon that Firefox's dev tools use

![codesandbox-clear-icon](https://user-images.githubusercontent.com/1127037/58434180-fe782780-807f-11e9-8a39-0220199f4909.png)

**Comment by CompuIves** [comment]
That makes sense! I would like the `block` icon, but a bit smaller. This seems like a good starting issue.

**Comment by pshrmn** [comment]
For whoever wants to give this a go, this is the module to make the change in:

https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/app/components/Preview/DevTools/Console/index.tsx

**Comment by halitogunc** [comment]
@CompuIves can I work on this?

**Comment by Saeris** [comment]
@halitogunc If you'd like to make this change go ahead and submit a PR and I'll review it!
