### ISSUE TITLE
CTRL/CMD + 1/2/3/4/5... to switch to another Chrome tab not working

### ISSUE THREAD

**Issue by alexluong** [codesandbox/codesandbox-client#1997]
# ❔ Question

I know it must be difficult to integrate editor's shortcuts and browser's ones. For example, `CTRL/CMD + W` is a known issue here and cannot be fixed.

My use case is actually the opposite of the situation above. I'd prefer Chrome's shortcuts to take precedence when using `CTRL/CMD + NUMBER` to switch tabs while editing. Is there anyway I can achieve this? Thank you!

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Browser          | Chrome
| Operating System | Mac OS

**Comment by Saeris** [comment]
Hey there!

You can remap keybindings inside the editor under File > Preferences > Keyboard Shortcuts (or by pressing CTRL/CMD + K, CTRL/CMD + S), where you should be able to unbind the hotkeys you're looking to use in Chrome. Finding all of them may take a bit of effort however.

![image](https://user-images.githubusercontent.com/3144549/58623310-8e85bf00-8282-11e9-87ef-faf8e00ed171.png)

If this workaround doesn't solve your issue then we may need to investigate a fix.

Hope this helps!

**Comment by alexluong** [comment]
@Saeris Hey thanks for the replies! It works for me now. I'll close the issue. Appreciate the help.
