### ISSUE TITLE
Comments are in cursive. Cursive! Cursive!??

### ISSUE THREAD

**Issue by conartist6** [codesandbox/codesandbox-client#2004]
Seriously though, how is this intended to improve anything?

**Comment by conartist6** [comment]
Monospace cursive too, so it's kerned poorly and the actual result is completely counter to the point of writing in cursive. Examples:

![This is a simple](https://i.imgur.com/GkD2KW6.png)
![automatically](https://i.imgur.com/Y3RxHxg.png)
![added](https://i.imgur.com/MXpoJ3n.png)
![it will](https://i.imgur.com/i06CrLY.png)

**Comment by CompuIves** [comment]
You can change the font in CodeSandbox, there's even a "no italics" theme. You can change these settings by pressing `CMD/CTRL+,`.
