### ISSUE TITLE
Disable inlining for static css files

### ISSUE THREAD

**Issue by neuefische-web** [codesandbox/codesandbox-client#2008]
# ❔ Question
Is there any way to disable the inlining of an external css file that has been linked in `index.html` via `<link rel="stylesheet" href="styles.css">` in the vanilla parcel template? 

When inspecting the `body` in the link below you see that styles appear twice.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by CompuIves** [comment]
Hmm good one, just noticed it too! We also include the inline css for hot module reloading support. Is having the styles twice in the html causing problems?

**Comment by neuefische-web** [comment]
Technically no... but I use Codesandbox for teaching a lot and noticed it while trying to build a demo for inline vs external stylesheet priority. Which I could not demo with this behavior ;)

**Comment by halitogunc** [comment]
@CompuIves can I work on this if no one is interested ?
