### ISSUE TITLE
How to use vue-cli project without App.vue?

### ISSUE THREAD

**Issue by Sogl** [codesandbox/codesandbox-client#2010]
# ❔ Question

I start from vue-cli template.
My code works on my project but I can't use it in Codesandbox. I see white screen only.
Another project with `App.vue` works fine: https://codesandbox.io/s/buefy-sidebar-duspv

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 
| Browser          | latest Chrome
| Operating System | Mac OS X

**Comment by lbogdan** [comment]
Hey @Sogl ,

I see you're creating the main Vue instance, but it's not rendering anything. What exactly would you expect to see?

**Comment by Sogl** [comment]
@lbogdan Please check 2nd link in my 1st issue comment.
