### ISSUE TITLE
Cursor not in the correct place in editor.

### ISSUE THREAD

**Issue by charlie632** [codesandbox/codesandbox-client#2012]
# 🐛 bug report

## Description of the problem

The cursor acts weird. It is not in the right place. Below is a video to my bug.

https://www.loom.com/share/3705b13c69524497925ce82d216376b0

Basically, every sandbox I do not own has this problem. Tried on a incognito tab and same result.

## How has this issue affected you? What are you trying to accomplish?

I cannot write anything because it is frustrating :(

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Google Chrome
| Operating System | Windows

**Comment by Saeris** [comment]
This appears to only be the case with embeds, as I opened your linked sandbox and changed the URL from:
https://codesandbox.io/embed/quizzical-ramanujan-kilwg
to:
https://codesandbox.io/s/quizzical-ramanujan-kilwg
and it appears to be working correctly in the full sandbox environment.

Marking this as a bug. We'll need to investigate to determine why there is a disconnect between the two versions of the editor.

**Comment by CompuIves** [comment]
Hmm, this is probably an issue with the Monaco editor. We load the editor before the font is loaded, so the dimension calculations are on the fallback font instead of the loaded font. I thought I had fixed it with this: https://github.com/CompuIves/codesandbox-client/blob/2be78d32ff8d906a052f73da18010619805c1a94/packages/app/src/app/components/CodeEditor/Monaco/MonacoReactComponent.js#L68-L83. But it seems like it's still happening.

**Comment by hodgef** [comment]
Hello @CompuIves, @Saeris,

Are there any updates on this issue? The embeds are really broken in this state.

![broken](https://i.imgur.com/zuL9Hfm.gif)

Thanks!
Francisco Hodge

**Comment by lbogdan** [comment]
Hey @charlie632 , @hodgef ,

I just tried this and couldn't replicate on my side. Is it still an issue for you?

**Comment by charlie632** [comment]
@lbogdan Hi! I just checked and it seems to be fixed. I'm gonna close it for now. If anyone still have this problem, feel free to comment.

**Comment by hodgef** [comment]
@lbogdan The issue seems to still happen. here's a repro:
https://fabulous-gooseberry.glitch.me/

**Comment by charlie632** [comment]
@hodgef hey! I tested your repro and everything works properly for me. I'm using Mac Catalina and latest Chrome. I can re open the issue if you want.

**Comment by hodgef** [comment]
Thanks for checking it out @charlie632 !
I have seen the issue on two different Windows 10 machines using latest Chrome.

Here's a recording, although you might have to see it full screen to notice the cursor:
https://imgur.com/a/xT9rCUa

If the mantainer can repro this on Windows, then I'd vote to reopen 😄

Regards,
Francisco Hodge

**Comment by lbogdan** [comment]
Win 10 + Chrome here, still can't replicate it. 🤷‍♂️

Just to make sure we're talking about the same behavior here, the issue is that you click on a line of code, and the cursor moves a few characters before the click location, instead of where you click?

**Comment by hodgef** [comment]
Indeed! In the video posted above you can see the editor's cursor not matching my mouse cursor when I click. However, this is not showstopper. If it can't be repro it's okay to leave it as is.

Regards,
Francisco Hodge
