### ISSUE TITLE
node_modules missing files published in the package

### ISSUE THREAD

**Issue by dekz** [codesandbox/codesandbox-client#2014]
# 🐛 bug report

## Description of the problem
Not all of the required files seem to be present in the `node_modules` folder.

i.e:
```
var rng = require('./lib/rng');
var bytesToUuid = require('./lib/bytesToUuid');
```
From https://unpkg.com/uuid@3.3.2/v4.js. This `./lib/rng` file is required but not present under `node_modules`.

![image](https://user-images.githubusercontent.com/27389/58809877-0e15e400-861d-11e9-9003-098687f8871b.png)

## How has this issue affected you? What are you trying to accomplish?

Unable to render correctly to demo.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by CompuIves** [comment]
Hey @dekz, that's true, we download files on-demand based on the requires. We do that to save bandwidth, otherwise people have to download hundreds of mbs to load the demo.

I took a look at your example, and I think that we're loading a wrong version of `uuid`, we load `2.0.3`:
![image](https://user-images.githubusercontent.com/587016/59038345-3139d100-8873-11e9-9281-1fa13f95ea81.png)

and the lib/rng logic seems to be in v3.

I'm looking into why we're loading `uuid@2.0.3`, in the meantime you can "fix" it by explicitly adding `uuid@3.0.4` to your dependencies.

**Comment by dekz** [comment]
@CompuIves thanks for the update. Did you get a successful compilation with hoisting the dependency up?

When adding `uuid@3.x`:
```
Could not find module in path: 'uuid/2.0.1/lib/rng' relative to '/node_modules/uuid/2.0.1/v4.js'
```

**Comment by CompuIves** [comment]
Ohhh, good point! I found out that we have trouble with a single dependency that has multiple transient dependencies of a specific dependency.

So in the case of `0x.js` there are two versions of `uuid`, and we only pick the `2.0.3` from it.

From what I've seen:

```
➜  t yarn why uuid
yarn why v1.16.0
warning package.json: No license field
[1/4] 🤔  Why do we have the module "uuid"...?
[2/4] 🚚  Initialising dependency graph...
warning No license field
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "uuid@3.3.2"
info Has been hoisted to "uuid"
info Reasons this module exists
   - Hoisted from "0x.js#@0x#contract-wrappers#uuid"
   - Hoisted from "web3-provider-engine#request#uuid"
   - Hoisted from "0x.js#@0x#subproviders#ganache-core#ethereumjs-wallet#uuid"
info Disk size without dependencies: "108KB"
info Disk size with unique dependencies: "108KB"
info Disk size with transitive dependencies: "108KB"
info Number of shared dependencies: 0
=> Found "ethers#uuid@2.0.1"
info This module exists because "0x.js#ethers" depends on it.
info Disk size without dependencies: "96KB"
info Disk size with unique dependencies: "96KB"
info Disk size with transitive dependencies: "96KB"
info Number of shared dependencies: 0
=> Found "ethereumjs-blockstream#uuid@3.2.1"
info This module exists because "0x.js#@0x#contract-wrappers#ethereumjs-blockstream" depends on it.
info Disk size without dependencies: "108KB"
info Disk size with unique dependencies: "108KB"
info Disk size with transitive dependencies: "108KB"
info Number of shared dependencies: 0
=> Found "web3-eth-accounts#uuid@2.0.1"
info This module exists because "0x.js#@0x#subproviders#ganache-core#web3#web3-eth#web3-eth-accounts" depends on it.
info Disk size without dependencies: "96KB"
info Disk size with unique dependencies: "96KB"
info Disk size with transitive dependencies: "96KB"
info Number of shared dependencies: 0
✨  Done in 0.44s.
```

We need to add support for this, allow for multiple transient dependencies of the same name with different versions. I'm thinking of what a workaround for now is.

**Comment by CompuIves** [comment]
It seems to work when removing `@0x/subproviders` from the dependency list, since it's also included in `0x.js`, but I can also understand that you don't want to change the sandbox that much.

**Comment by dekz** [comment]
Dang you found that quick. Removing the `@0x/subproviders` does indeed help with the issue. It is included in 0x.js, but not everything is exported out via `0x.js`. 

Good temporary workaround.
