### ISSUE TITLE
How to log in with GitHub running the Client Locally?

### ISSUE THREAD

**Issue by benschac** [codesandbox/codesandbox-client#2037]
# 🐛 bug report

## Description of the problem
When adding a JWT to the client project, where should you add it?
I added it to both the .env and package.json of the app without any luck :(

## How has this issue affected you? What are you trying to accomplish?
I can't log in on development.

Happy to add it to the contributing.md doc.  Thanks again.
### Your Environment
mac, node v.10
| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by Saeris** [comment]
You don't add it to a file, it's a key `jwt` in localstorage in the browser that you need to copy from the live client to the localstorage of your local client. Here are some screenshots:

Live:
![image](https://user-images.githubusercontent.com/3144549/59079807-50982480-889a-11e9-99ee-c140d0fcd087.png)

Local:
![image](https://user-images.githubusercontent.com/3144549/59079814-5a218c80-889a-11e9-8d77-4a9e12a26e4a.png)

In the future we may have a better process for doing this. It's not the easiest thing to do unfortunately.

For reference, Live Coding won't work when running local either. I believe there are some other features as well that don't quite work when running just the client on your local machine, but I can't remember which off the top of my head. It's unlikely that we will make the whole stack available anytime soon to run locally.

**Comment by benschac** [comment]
thank you for the quick reply! it worked! updating the docs now. 👍

**Comment by lbogdan** [comment]
It's already in the docs - https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md#code-organization , second paragraph. Closing.
