### ISSUE TITLE
package.svelte should be read for Svelte template

### ISSUE THREAD

**Issue by ValentinH** [codesandbox/codesandbox-client#2045]
# 🐛 bug report

## Description of the problem
When using the Svelte template, I cannot use a Svelte component imported from NPM. According to https://github.com/sveltejs/svelte/issues/2620 and #1825, this is because CodeSandbox does not import the file pointed by the `svelte` property of the package.json.

## How has this issue affected you? What are you trying to accomplish?
I'm trying to use CodeSandbox as a demo source for https://github.com/ValentinH/svelte-easy-crop. It works correctly using Svelte REPL: https://svelte.dev/repl/a6fc511aafd94e428d0bb6670f477abc?version=3.4.4

### Link to sandbox:

- https://codesandbox.io/s/k3xrkyyo2o
- https://codesandbox.io/s/inspiring-carson-o1eo2 (click "toggle" and then try to click outside and watch the console.)

**Comment by emirotin** [comment]
I have a different but similar issue. The default Svelte template worked fine for me before I tried to add a router component. Tried 3 different libs, all with different errors.
The most recent one: `'target' is a required option`

Sandbox: https://codesandbox.io/s/svelte-yrv-issue-zvelg

Identical app in the official Svelte REPL: https://svelte.dev/repl/c7a88bb217904abd9726c1f65dd3617a?version=3.18.2 (working)
Identical local app: https://github.com/emirotin/svelte-yrv-example
