### ISSUE TITLE
React library published using "tsdx" fails to load

### ISSUE THREAD

**Issue by dance2die** [codesandbox/codesandbox-client#2052]
# 🐛 bug report

## Description of the problem

I've released an alpha version of [react-use-localstorage@3.1.2-alpha.0](https://www.npmjs.com/package/react-use-localstorage/v/3.1.2-alpha.0), which works locally but shows following error messages on CodeSandbox.

_The library initially used `tsc` to compile TypeScript but I've migrated to use [tsdx](https://www.npmjs.com/package/tsdx) to output `es/umd/cjs` modules._

> TypeError
(0 , _reactUseLocalstorage.default) is not a function

Or sometimes I get the blank screen without any errors.

![blank screen](https://user-images.githubusercontent.com/8465237/59321395-d30c5400-8c9f-11e9-94c4-bd9dec91d1f5.png)

Below shows that alpha package works in local environment.

![working locally](https://user-images.githubusercontent.com/8465237/59321547-72314b80-8ca0-11e9-82ee-434c1208796c.gif)

### Chrome DevTools warning

Chrome DevTools console shows the following warning messages

> DevTools failed to parse SourceMap: https://r6moq.codesandbox.io/node_modules/react-use-localstorage/dist/react-use-localstorage.cjs.development.js.map
DevTools failed to parse SourceMap: https://codesandbox.io/extensions/node_modules/typescript/lib/typingsInstaller.js.map

FYI -  Refer to [v3.1.2-alpha.0 react-use-localstorage.cjs.production.js.map](https://unpkg.com/react-use-localstorage@3.1.2-alpha.0/dist/react-use-localstorage.cjs.production.js.map) on [Unpkg](https://unpkg.com/react-use-localstorage@3.1.2-alpha.0/).

![Chrome DevTools warning](https://user-images.githubusercontent.com/8465237/59473474-93b14500-8e10-11e9-9a01-62d8bcf13975.png)

## How has this issue affected you? What are you trying to accomplish?

I use a Sandbox within a [README](https://github.com/dance2die/react-use-localstorage/blob/master/README.md) to let people test out the library & fork it.
But I am unable to release the stable version as I can't create a working demo on the Sandbox.

### Link to sandbox:

- [Sandbox](https://codesandbox.io/s/09xj95vxl) included in the README, which uses stable version 3.1.1
- [Sandbox](https://codesandbox.io/s/react-use-localstorage-v3x-demo-r6moq) that generated the blank screen mentioned in the "description of the problem."
- [Sandbox](https://codesandbox.io/s/github/dance2die/demo.test-react-use-localstorage) generating the `TypeError (0 , _reactUseLocalstorage.default) is not a function` - I've imported the [GitHub repo](https://github.com/dance2die/demo.test-react-use-localstorage), which works in an local environment.

### Your Environment

Happens on both Windows 10 & Ubuntu 19.04

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1559903240-93ff18a72
| Browser          | Chrome Version 75.0.3770.80 (Official Build) (64-bit)
| Browser          | FireFox Quantum 67.0.2 (64-bit)
| Operating System | Windows 10 Version 1803 (OS Build 17134.829)
| Operating System | Ubuntu 19.04 (codename: disco)

**Comment by dance2die** [comment]
I am sorry but it's not not a CodeSandbox issue.
The issue was that I published the alpha version as CJS, not as ESM. 😅

**Comment by CompuIves** [comment]
I see... Lately we've seen more issues with different CJS builds, because almost all bundlers now use ESM. Maybe we should switch to ESM with the cost of worse performance.

**Comment by dance2die** [comment]
How does CSB resolve to load [UMD build](https://unpkg.com/react@16.8.6/)?
(_while the `main` for `React` points to a [CJS build](https://unpkg.com/react@16.8.6/index.js) within [package.json](https://unpkg.com/react@16.8.6/package.json)_.)
