### ISSUE TITLE
error: Cannot find module 'after'

### ISSUE THREAD

**Issue by anasshad** [codesandbox/codesandbox-client#2055]
# 🐛 bug report
error: Cannot find module 'after'

## Description of the problem
I am working with gatsby pulling data from firebase. As with gatsby, I need to restart the server every time there is new. So, I this time I restarted my server and it throws me this error.

## How has this issue affected you? What are you trying to accomplish?
I was trying to restart my server.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/survey-builder-9n8bu

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 
| Browser          | Chrome
| Operating System | Windows 10

**Comment by lbogdan** [comment]
Hey @anasshad ,

It looks like an issue with your `node_modules`. Try this:
- remove `yarn.lock`
- open a terminal, remove `node_modules`:
```
$ rm -fr node_modules
```
- use "Restart Sandbox" from the Server Control Panel:

![image](https://user-images.githubusercontent.com/2083930/59864488-8b688500-938f-11e9-8c0d-a69ef3a60318.png)
- if that doesn't work, also try "Restart Server"
- report back here 🙂

**Comment by lbogdan** [comment]
Here's a working sandbox which I forked from yours and applied the steps above: https://codesandbox.io/s/survey-builder-b2ycy . There's still a compile error, but that's from the app code.

**Comment by lbogdan** [comment]
Closing, as this is a package versioning issue, and there's nothing we can do on our side.
