### ISSUE TITLE
Cannot Open Another terminal (Ember)

### ISSUE THREAD

**Issue by jrock2004** [codesandbox/codesandbox-client#2062]
# 🐛 bug report

## Description of the problem
I have created an ember app and I want to open a tab so I can generate new ember files `ember g route home`. All I get it is this

<img width="959" alt="image" src="https://user-images.githubusercontent.com/655716/59521948-7bd2d300-8e9b-11e9-9bee-41b46da0a6f7.png">

## How has this issue affected you? What are you trying to accomplish?
I want to use the ember cli tool to generate new files

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/ember-international-rmjdz

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Not sure|
| Browser          | Firefox 67.0.2 | 
| Operating System | Mac Mojave |

**Comment by lbogdan** [comment]
Hey @jrock2004 , we're sorry for this, looks like it's a regression introduced by #2040, which I reverted in #2063, and already deployed. Can you please check again and let us know it works as expected? Thanks!

**Comment by jrock2004** [comment]
No worries, its now bring up the terminal. Thank you guys
