### ISSUE TITLE
ModuleNotFoundError - '@babel/runtime/helpers/interopRequireDefault'

### ISSUE THREAD

**Issue by William-Avery** [codesandbox/codesandbox-client#2072]
# 🐛 bug report

## Description of the problem
When creating a React project, after importing a dependancy, project throws a ModuleNotFoundError.
## How has this issue affected you? What are you trying to accomplish?
Not able to use any additional dependencies.
### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/patient-leftpad-pqjbv
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | https://codesandbox.io/s/patient-leftpad-pqjbv |
| Browser          | Chrome | 
| Operating System | Windows 10 |

**Comment by lbogdan** [comment]
Hey @William-Avery ,

Are you still experiencing this? The sandbox you linked to works just fine here. Can you please provide more details about your issue - copy/paste stack traces, screenshots etc.? Thanks!

**Comment by LilZcrazyG** [comment]
I am still having this problem.

**Comment by SaraVieira** [comment]
@LilZcrazyG Do you have a sandbox with this issue?

**Comment by SaraVieira** [comment]
Closed for lack of response and inability to reproduce
