### ISSUE TITLE
Updating dependencies

### ISSUE THREAD

**Issue by smolinari** [codesandbox/codesandbox-client#2075]
Hi,

We recently added the Quasar Framework server template to Codesandbox (thank you for that Codesandbox team!!) and I have a question about keeping it up-to-date in terms of dependencies. The Quasar framework is constantly being worked on and it seems the sandbox I create with the server template selection is "stuck" on the version that was current at the time the template was added (beta 24 and we are now at RC5). 

If I manually update the sandbox, it forks to a new sandbox and does update dependencies, which doesn't quite help, because, if I go back to the server template selection and select Quasar again, I get the version of the sandbox with the old dependencies....again. 

I guess my question is, why the extra step in forking to get the dependencies updated? I am expecting to get a fresh sandbox with the server template and not be reverted back to the original "old" sandbox I created the first time I selected Quasar. 

Maybe I'm just confused about something else or our template isn't setup properly? Any help on this would be greatly appreciated!!!

Scott

**Comment by lbogdan** [comment]
Hey @smolinari ,

How are you updating the framework in the template repo? I see no changes to `package.json` since the initial commit: https://github.com/quasarframework/quasar-codesandbox/commits/master/package.json .

**Comment by smolinari** [comment]
Would a change in package.json trigger a fresher sandbox? The packages are using the `^` symbol to represent "this version or higher". So, we aren't updating the template with newer versions. 

Scott

**Comment by smolinari** [comment]
BTW, I sort of get the "forking" bit too now. We set up a link to the template and it links straight to my template generated (old versions) sandbox, which I can then fork and start working on. I'm just now looking for a way to get my "master" sandbox updated. :)

Scott

**Comment by lbogdan** [comment]
So, how it works now is that when a server sandbox imported from github (which the Quasar template is) starts OR new commits are pushed, we update the container's contents, run `yarn install` and restart the dev server. If nothing changes in `package.json`, because of `yarn.lock` (which is persistent between sandbox restarts), `yarn install` will not do anything.

There's two solutions to that:
- update `package.json` (and it would be best to also add a `yarn.lock`) each time you want a new version to be available in the template - pro: more control, con: more work;
- do what Nuxt does, define a `post-update` script in `package.json` that will force upgrade all the packages, which we will run in the conditions mentioned above ^^:
https://github.com/nuxt/codesandbox-nuxt/blob/345056fae4ee1908c6a9cebd71e0331e6ab8c557/package.json#L12
pro: less work, con: less control, the forked sandboxes will also run the `post-update` script every time they start.

**Comment by lbogdan** [comment]
Also, forking works because the forked sandbox starts with no `yarn.lock`, so running `yarn install` will install the latest versions matching your `package.json`.

**Comment by Saeris** [comment]
So from what I can see in the Quasar Framework Template right now, here are the dependency versions:

![image](https://user-images.githubusercontent.com/3144549/59748758-a670b300-9230-11e9-955b-5c42b9483ab4.png)
https://codesandbox.io/s/github/quasarframework/quasar-codesandbox

If I'm reading this correctly, the Template now has the version you were expecting to find. Here's the thing: I've noticed in my own work on Sandboxes imported from GitHub that new commits aren't always picked up immediately, it can take some time for the two to sync up. It appears that was the case for you here.

You should be able to make changes to your Template in one of two ways: by committing to the Template repository directly, or from within CodeSandbox via forking the Template, making your changes, and committing those changes back to the repository via our GitHub integration. Either way should work just fine (I've done this before with my own personal projects).

Maybe there is a way we can speed up this detection so there isn't this gap period you've experienced. I'm not knowledgeable in how that part of our system works unfortunately. @lbogdan or @CompuIves would be better at answering whether that can be done.

**Comment by lbogdan** [comment]
@Saeris I don't know what gap you're talking about, we update the sandbox as soon as someone accesses it. 🙂

**Comment by Saeris** [comment]
I've noticed that when I make a commit to a GitHub repository, it's not immediately picked up, even if I use the GitHub importer. In some instances it's taken a good 15-20 minutes before the imported Sandbox will pick up the changes. Changes are only picked up immediately in your forks (in the case of you making a commit from within the app).

**Comment by smolinari** [comment]
Ok. Thanks for the info!! And, now I understand.

It would be cool if Codesandbox had a config parameter

`automatically-update-dependencies: true` 

😄 

In the mean time, updating out `packages.json` file got the master sandbox updated. Thanks again!

Scott

**Comment by smolinari** [comment]
Btw, we also added the post-update script. 

Scott
