### ISSUE TITLE
Is there a way to  connect to mongodb atlas?

### ISSUE THREAD

**Issue by vinothrao** [codesandbox/codesandbox-client#2077]
# ❔ Question

Not able to connect to MongoDB atlas from node js app. To connect to mongo db atlas the ip has to be whitelisted. Since the code sandbox ip cannot be identified not able to connect to MongDb Atlas. Is there a way?

### Your Environment

| Software         | Name/Version |
| Mongodb atlas | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by lbogdan** [comment]
Hey @vinothrao ,

We're currently using IPs from the `159.69.141.0/24` range on the worker nodes the server sandboxes run on. The only solution would be whitelisting this whole range (which will start breaking as soon as we change the provider / start to use more nodes in different ranges).

Does that answer your question?

**Comment by lbogdan** [comment]
Closing this, as there's no further actionable here.

**Comment by p2635** [comment]
Is the IP range still relevant in 2022?
