### ISSUE TITLE
Folder name cant use special characters like '#' that will be used in the url

### ISSUE THREAD

**Issue by rajjejosefsson** [codesandbox/codesandbox-client#2080]
# 🐛 bug report

## Description of the problem

When you name your folder with the character '#', will not let you open its subfolders

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome 74.0.3729.169
| Operating System | OSX

**Comment by CompuIves** [comment]
Hey! Is this for folders in the dashboard?

**Comment by oskarabc** [comment]
Dashboard. Applies also to other chars such as ?, !, % etc. Few other setbacks:
- Cannot rename a folder containing these types of chars. Use workaround for recovery.
- Renders any contents invisible

Workaround to retrieve any invisible Sandboxes: Delete the subfolder containing Sandboxes, it then moves them to Trash.

**Comment by CompuIves** [comment]
Hmm, maybe it can be fixed by using encodeURIComponent. Checking now.
