### ISSUE TITLE
popular templates entry for aurelia

### ISSUE THREAD

**Issue by myusrn** [codesandbox/codesandbox-client#2085]
# 🌈 Feature

Is there a popular templates entry for aurelia in the works and if not has anyone reached out to https://aurelia.io/ folks to provide them details on how to get one added?

When one visits codesandbox.io the popular templates includes an aurelia and aurelia+ts option as alternative to the angular, react, react+ts and vue ones currently present.

The https://aurelia.io/ site has examples of what the aurelia cli will crank out as recommendation for js and ts based default project setups.

**Comment by Saeris** [comment]
This is planned to be added! We have repos set up for both Aurelia and Aurelia Typescript based on the Aurelia CLI defaults here that you can open via the GitHub importer right now. They're untested though, so there may be some quirks.

https://github.com/codesandbox/codesandbox-templates/tree/master/packages/container/aurelia-template
https://github.com/codesandbox/codesandbox-templates/tree/master/packages/container/aurelia-typescript-template

And here's the Sandbox links:
https://codesandbox.io/s/github/codesandbox/codesandbox-templates/tree/master/packages/container/aurelia-template
https://codesandbox.io/s/github/codesandbox/codesandbox-templates/tree/master/packages/container/aurelia-typescript-template

**Comment by myusrn** [comment]
Great to hear this is planned and there are the links already available to be used. Thanks.

**Comment by SaraVieira** [comment]
Hey!

We no longer have popular templates and started going to an idea of community templates so I added a starter templates for aurelia in the explore section of the new modal that you can bookmark and have always in your modal:

![Screenshot 2019-12-12 at 16 02 30](https://user-images.githubusercontent.com/1051509/70723281-ece32e00-1cf8-11ea-8ab1-1b1a3913cdb5.png)

Here is the template link too: https://codesandbox.io/s/aurelia-iese9

**Comment by myusrn** [comment]
excellent thanks for the followup on this and the solution to allowing aurelia templates into the codesandbox.io experience.
