### ISSUE TITLE
Invariant Violation Target container is not a DOM element in Parcel project

### ISSUE THREAD

**Issue by AWolf81** [codesandbox/codesandbox-client#2087]
# 🐛 bug report
## Description of the problem
I'm getting an error message "Invariant Violation Target container is not a DOM element" for a Parcel project that I'm loading from Github. Not sure if it's related to my project setup.

#1737 looks related

After page load I'm getting that error message. Once I've edited a script file the preview reloads and it's rendering correctly.

## How has this issue affected you? What are you trying to accomplish?
Preview is not usable after page load.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox  | PROD-1561199685-a102c8493
| Browser          | Firefox 67.0.4 (64-Bit)
| Operating System | Windows 10 Pro (64bit)

**Comment by lbogdan** [comment]
Hey @AWolf81 ,

Our `parcel` bundler expects `index.html` to be in the project's root - although we should probably look for it in `src` as well. Here's exactly the same (working) project forked from that github repo and with `index.html` copied from `src` to `/`: https://codesandbox.io/s/use-counter-example-qlzgk .

**Comment by AWolf81** [comment]
@ibogdan thanks, I'll change the `index.html` location to the root folder. I think that's OK for the demo but it would be great to also have Codesandbox working with the file in `src` location.

A better error message would be good if that's possible. As I haven't seen that the location of the file is the problem.

**Comment by lbogdan** [comment]
Well, taking a better look at this, as far as `parcel` is involved, `src` is just an arbitrary folder with no special meaning. What we can do, though, is to look for an `.html` file in the `main` property of `package.json`.

As a side-note, explicitly loading the HTML also works: https://niclu.codesandbox.io/src/index.html .
