### ISSUE TITLE
Switching privacy back to public results in error

### ISSUE THREAD

**Issue by karlhorky** [codesandbox/codesandbox-client#2088]
# 🐛 bug report

## Description of the problem

Switching the privacy of a sandbox back to Public after it has been Private or Unlisted results in an error:

<img width="266" alt="Screen Shot 2019-06-24 at 11 30 00" src="https://user-images.githubusercontent.com/1935696/60008324-2d2ff080-9674-11e9-8b60-ff76f7fd1f87.png">
<img width="457" alt="Screen Shot 2019-06-24 at 11 30 05" src="https://user-images.githubusercontent.com/1935696/60008326-2d2ff080-9674-11e9-8183-7097741d1feb.png">
<img width="322" alt="Screen Shot 2019-06-24 at 11 30 34" src="https://user-images.githubusercontent.com/1935696/60008328-2d2ff080-9674-11e9-814a-ced16dbdb41e.png">
<img width="423" alt="Screen Shot 2019-06-24 at 11 30 39" src="https://user-images.githubusercontent.com/1935696/60008329-2d2ff080-9674-11e9-809d-e525aa3d7d48.png">

Setting the privacy works without errors when using the options in the context menu on the dashboard:

<img width="439" alt="Screen Shot 2019-06-24 at 11 28 27" src="https://user-images.githubusercontent.com/1935696/60008478-784a0380-9674-11e9-9eb2-a4320c998f1c.png">

## How has this issue affected you? What are you trying to accomplish?

My aim of trying to set the privacy of a sandbox back to Public from Private or Unlisted does not work.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | `PROD-1561199685-a102c8493` |
| Browser          | Chrome 75.0.3770.100 |
| Operating System | macOS 10.14.5 |

**Comment by CompuIves** [comment]
Ahh, big bug. Thanks for mentioning it! I fixed it, should work as expected now.

**Comment by karlhorky** [comment]
No problem, thanks for the quick fix!
