### ISSUE TITLE
Hotkey defaults that work in the browser (for common actions)

### ISSUE THREAD

**Issue by karlhorky** [codesandbox/codesandbox-client#2089]
# 🌈 Feature

Would the CodeSandbox team be interested in implementing hotkey defaults that work in browsers for common actions such as switching between tabs (VS Code Settings "View: Open Next Editor" and "View: Open Previous Editor").

For example, I would like to be able to switch to the next and previous tabs, but they are currently set to hotkeys like <kbd>cmd</kbd>-<kbd>option</kbd>-<kbd>left/right</kbd>, which collide with Chrome's bindings:

<img width="623" alt="Screen Shot 2019-06-24 at 17 30 08" src="https://user-images.githubusercontent.com/1935696/60032882-ca584c80-96a7-11e9-9268-5fd9182ddc76.png">

Since Chrome won't allow rebinding these keys, it would be cool if CodeSandbox had a binding for this out-of-the-box.

I know that I can just bind them myself, but I am suggesting to do this for all users to avoid having to do this.

## Un-rebindable Keybindings

A list of keybindings that do not work in various platform + browser combinations (I've been testing them with [JavaScript Event Key Tester](https://unixpapa.com/js/testkey.html) with all suppressions enabled):

#### macOS

- command-option-left (Previous Tab)
- command-shift-[ (Previous Tab)
- command-option-right (Next Tab)
- command-shift-] (Next Tab)
- command-w (Close Tab)
- command-t (Open New Tab)
- command-n (Open New Window)

---

**References:**

Prior Art: https://github.com/codesandbox/codesandbox-client/issues/1044#issuecomment-413623912

> I wish we could have native behaviour here, but Chrome doesn't allow us to override CMD + W. This is frustrating for me, for now I 'fixed' it by implementing CTRL + W for Mac as alternative...

Issue "Ctrl + Tab to switch between two files": #761 (PR with implementation: #817)

**Comment by CompuIves** [comment]
Hmm yes this seems like a good idea. No use of keybindings that don't work 😄. If you're interested in tackling this, could you compile a list of keybindings that need to be replaced with the corresponding replacements? We can then put that as default keybindings for VSCode.

**Comment by karlhorky** [comment]
Cool, I've started to compile a list above in the description, maybe we can put the "help wanted" label on this. It's going to be a bit of a job, especially for a cross-platform list.

**Comment by karlhorky** [comment]
Hm, just realized that installing CodeSandbox as a desktop PWA allows for use of some of these shortcuts! This is a great workaround for now! Maybe even good enough to supersede this issue...

**Comment by karlhorky** [comment]
I guess this is still current? There is however this experiment: #2716

**Comment by karlhorky** [comment]
not stale

**Comment by karlhorky** [comment]
don't close my features stalebot

**Comment by karlhorky** [comment]
bot

**Comment by karlhorky** [comment]
> Hm, just realized that installing CodeSandbox as a desktop PWA allows for use of some of these shortcuts!

@CompuIves would you be open to implementing overrides / `preventDefault` for <kbd>cmd</kbd>-<kbd>W</kbd> / <kbd>ctrl</kbd>-<kbd>W</kbd> in PWA mode? (to prevent closing of the CodeSandbox window)

https://twitter.com/youyuxi/status/1425883279014641666

This does work, just tested it:

https://twitter.com/karlhorky/status/1426070742064566276

**Comment by CompuIves** [comment]
I just tested, and if you set your keyboard shortcut to `CMD+W`, refresh and then go into fullscreen, you can close tabs with `CMD+W`. A bit cumbersome still, I wish there was a permission or something to override it 😅 .

Or do you mean something else?

**Comment by karlhorky** [comment]
Well as per [my tweet also linked above](https://twitter.com/karlhorky/status/1426070742064566276), overriding <kbd>cmd</kbd>-<kbd>W</kbd> is possible if you have installed CodeSandbox as a PWA (Progressive Web App).

So I'm not suggesting full screen - just to add some kind of event listener like the one below, which will work to prevent closing the whole window when CodeSandbox is installed as a PWA:

```js
document.addEventListener("keydown", (e) => {
  if ((window.navigator.platform.match("Mac") ? e.metaKey : e.ctrlKey)  && e.keyCode == 83) {
    e.preventDefault();
  }
});
```

**Comment by CompuIves** [comment]
Ahh, I see. We could even guard this with something like `window.navigator.standalone`, to make sure it's only enabled in PWA. It should not make a difference, but is a nice "guard". I think this would be a good thing to add.
