### ISSUE TITLE
static site template not displaying content

### ISSUE THREAD

**Issue by mtliendo** [codesandbox/codesandbox-client#2092]
# 🐛 bug report

## Description of the problem

When creating/viewing a simple static site, the following occurs:

1. The html content in `index.html` isn't displaying
1. The refresh button in the web-view isn't refreshing the page.
1. Clicking the "open in new window" button will show the correct content as intended

## How has this issue affected you? What are you trying to accomplish?

I am trying to display a static page as a training module for junior developers.  This impacts our learning as I now that to have them open the web view in a new tab/window and flip back and forth.

### Link to sandbox: [Sandbox LInk](https://codesandbox.io/s/static-chartjs-6okrn?fontsize=14)

> note: This behavior was fine as of a week ago, possibly a regression from the updates surrounding the shortened-url update?

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  Link provided
| Browser          | Chrome
| Operating System | Both mac and windows

**Comment by mtliendo** [comment]
twitter thread: https://twitter.com/mtliendo/status/1143222658185814016

**Comment by CompuIves** [comment]
We pinpointed the issue! Fix will be live within the next hour.

**Comment by lbogdan** [comment]
Hey @mtliendo 

We just fixed this in https://github.com/codesandbox/codesandbox-client/commit/ed898ddbbadf80d6d0a10052b36314733480ba85 , can you please check it works for you?

**Comment by mtliendo** [comment]
Looks great on my end! Thank you for the quick response time :)

**Comment by lbogdan** [comment]
Sweet! Closing, please reopen if need be.
