### ISSUE TITLE
ModuleNotFoundError Could not find module in path

### ISSUE THREAD

**Issue by hanzhangyu** [codesandbox/codesandbox-client#2093]
# ❔ Question

Running `npm start` locally works without any problems. Error only appears on CodeSandbox.

![image](https://user-images.githubusercontent.com/19344269/60068347-e52acf80-9740-11e9-8f0c-605eade44beb.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | https://codesandbox.io/s/zen-hooks-dcegq?fontsize=14
| Browser          | chrome  74.0.3729.169
| Operating System | Mac 10.14.0

**Comment by CompuIves** [comment]
Hmm, it doesn't find the file because of a casing issue. If you check unpkg.com you can see that `Dictionary.js` is named `DIctionary.js`: https://unpkg.com/highcharts-tree@0.1.3/lib/. I'm not sure why it works locally though, probably because the Mac FS doesn't see a difference in casing?

**Comment by CompuIves** [comment]
I'll close this one for now, since it seems to be something that can only be fixed by the library author by renaming `DIctionary.js` to `Dictionary.js`. We can re-open it if there's something that we can do!

**Comment by hanzhangyu** [comment]
Really thanks! I remember that I have changed it, this may cause by build cache (I haven't changed this file since rename it).
