### ISSUE TITLE
Feature/fix: don't append suffix to suffix when forking

### ISSUE THREAD

**Issue by mindplay-dk** [codesandbox/codesandbox-client#2094]
Just a minor feature or fix (or nitpick) depending on your point of view, but:

When you create a sandbox, it gets a random name like `random-sandbox-bkwibd`

When you fork a sandbox, the sandbox name gets a random suffix.

What you seem to end up with is sandbox names with suffix after suffix, e.g. `random-sandbox-bkwibd-flurp`.

Suggestion: track the random name *and* the random suffix separately in the model, so you can tell them apart. When generating a new name for a forked sandbox, something like `random-sandbox-flurp` would be preferable to two suffixes.

**Comment by lbogdan** [comment]
Hey @mindplay-dk ,

I can't replicate this, can you please provide a link to a sandbox that got that double random prefix?

**Comment by mindplay-dk** [comment]
Here's one:

https://codesandbox.io/s/optimistic-feather-qm9n1-qm9n1

And the original:

https://codesandbox.io/s/optimistic-feather-qm9n1

Actually, the explanation may be something else entirely than what I was guessing... it seems the double suffix is the *same* random string, not a new one.

I'm not sure *when* this happens... 🤨

But it has happened several times, basically whenever I fork my own sandboxes.

**Comment by lbogdan** [comment]
Hey @mindplay-dk ,

Were you able to pin this down? I just couldn't replicate it.

**Comment by mindplay-dk** [comment]
Is the ID `qm9n1` and the name `optimistic-feather` separate in the (client, server and UI) models?

Could it be that something unintended happens when you try to rename a sandbox? Like, the ID suffix gets somehow appended to the name or something?

**Comment by CompuIves** [comment]
I think that happens @mindplay-dk, we should probably check for the name and not save the title if nothing changed when renaming.
