### ISSUE TITLE
react-app-rewired

### ISSUE THREAD

**Issue by oliversturm** [codesandbox/codesandbox-client#2097]
# ❔ Question

Issue #869 asked for react-app-rewired compatibility and promises were made. I can't find any updates on the topic though and it seems that projects with react-app-rewired don't work correctly at the moment. I suspect that the changes mentioned in #869 have not actually been implemented. Am I missing something?

**Comment by SaraVieira** [comment]
Hey

In the client one we currently do not support that but you can run something like that on a container and here is an example: https://codesandbox.io/s/react-app-rewired-q7ye0


We will add this as a template in the next couple of days

**Comment by brunolemos** [comment]
Do you have a codesandbox example? The link above seems to be removed.

**Comment by dsanders1234** [comment]
@SaraVieira Any news on this feature?  Thanks.
