### ISSUE TITLE
Support Netlify for Dojo Sandboxes

### ISSUE THREAD

**Issue by agubler** [codesandbox/codesandbox-client#2098]
# 🌈 Feature

What would I need to do to get support for netlify deployments for Dojo sandboxes?

**Comment by SaraVieira** [comment]
Hey !

It was all in our side but all fixed and pushed, should be able to do it tomorrow or the day after :)

**Comment by SaraVieira** [comment]
closed by https://github.com/codesandbox/codesandbox-client/commit/472dafe6d9e1d2df417074fa02f3b1a7a9ee13be

**Comment by agubler** [comment]
Thanks @SaraVieira - Looking forward to it!
