### ISSUE TITLE
Ability to specify file and line number when sharing embed

### ISSUE THREAD

**Issue by CompuIves** [codesandbox/codesandbox-client#21]
Suggestion by jschr:

"Actually I do have one suggestion. It would be awesome to be able to link to a specific file and even line number so I can direct the reader to the appropriate spot when clicking on the "Edit on CodeSandbox" from an embed. You could take a page from Gist and do something like https://codesandbox.io/s/[id]#file-[filename]-L[linenumber].
This would allow me to link to specific areas of the code as I'm writing up a tutorial or post."

**Comment by ergunsh** [comment]
Hey!

I would like to work on this, do you think this is a good issue to dive into the codebase?

Also, how do you think `folder/file` structure should be handled?
https://codesandbox.io/s/[id]#file-[folder/filename]-L[linenumber] is good?

Aaaand, Thank you very much for this awesome tool! I'm amazed the things you've achieved as a student! 🎉

**Comment by Saeris** [comment]
Adding this to our public backlog. Closing this out for now, please refer to this link for the status of this request:

https://www.notion.so/Add-Line-Highlighting-to-Sandbox-Embeds-7b27118566454a3fa81cf6874b41405c
