### ISSUE TITLE
Preset React+TS is broken

### ISSUE THREAD

**Issue by Pomar81** [codesandbox/codesandbox-client#2101]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?
I can't find out real TS problem

### default enviroment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome 75
| Operating System | Windows 10

**Comment by MichaelDeBoey** [comment]
Hi @Pomar81!

Can you give a bit more context, please? 🤔
Opening the sandbox just works for me.
I also get no error in the preview or in console or "problems" tab.

**Comment by Pomar81** [comment]
Today at work from  I've opened it and it works correctly.
MacOS Chrome75. 
But yesterday I saw every JSX  was highlighted with error

**Comment by MichaelDeBoey** [comment]
The info you just provided could be helpful. 🙂
Some image could help too sometimes to make it a bit clearer what the exact problem is.

Let us know if the problem is still there.
If not, you can just close this issue. 🙂

**Comment by Pomar81** [comment]
I've reset the cache and everything become ok
