### ISSUE TITLE
Double Scrollbars with Terminal Tabs and Full-Height Terminal (in Container)

### ISSUE THREAD

**Issue by karlhorky** [codesandbox/codesandbox-client#2103]
# 🐛 bug report

## Description of the problem

In a CodeSandbox Container, the terminal receives two scrollbars when it's been expanded to the full height of a browser window.

It's kind of hard to see what I'm doing here, but I'm typing in the console while it appears that nothing is happening. You cannot see the input because it is scrolled off of the end of the screen 😞:

![ezgif com-resize (1)](https://user-images.githubusercontent.com/1935696/60250230-80997d00-98c6-11e9-9a69-2adc7ec2f43c.gif)

As soon as the user types something, the terminal is scrolled up, causing the typing to be obscured.

## Reproduction Steps

- open a CodeSandbox Container
- resize the terminal pane to the full height of the window (obscuring the browser preview)
- open a new tab in the terminal
- type in a lot of text so that a scrollbar appears
- notice that any new text entered is not visible on the screen
- to make the effect worse: resize the terminal pane again

Note: I have successfully reproduced this on a 13 inch Retina MacBook Pro on default resolution.

## Potentially Related

https://github.com/codesandbox/codesandbox-client/issues/1654 (and the pull request from that: https://github.com/codesandbox/codesandbox-client/pull/1740)

## How has this issue affected you? What are you trying to accomplish?

I would like to type in the terminal and have it show up.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | `PROD-1561557066-4a5dea6e4 ` |
| Browser          | Chrome 75.0.3770.100 |
| Operating System | macOS 10.14.5 |

**Comment by karlhorky** [comment]
Seems like it may be related to the incorrect `height` prop being passed down through the View system:

https://github.com/codesandbox/codesandbox-client/blob/e2a5180121af4e0d43e060313d71ceb402bb7a27/packages/app/src/app/components/Preview/DevTools/Terminal/index.js#L198

<img width="1147" alt="Screen Shot 2019-06-27 at 10 54 21" src="https://user-images.githubusercontent.com/1935696/60252236-30bcb500-98ca-11e9-9e9a-ed72c9100f5d.png">

**Comment by karlhorky** [comment]
Added reproduction steps. It makes the effect worse to resize the panel multiple times. Maybe there's something off in the height calculation during resize.

**Comment by lbogdan** [comment]
Hey @karlhorky ,

Thanks for the detailed description, this issue was too long standing already!

I (tried to) fixed it in #2105 , can you please test it here https://pr2105.build.csb.dev/s/new ? (it works with the same sandboxes as `codesandbox.io`). In order to be able to open terminals, you can login by copying the `jwt` local storage token from `codesandbox.io` to the PR build domain. Let me need if you need any assistance. Thanks!

**Comment by karlhorky** [comment]
Awesome @lbogdan, #2105 is working for me in the preview environment!

**Comment by lbogdan** [comment]
@karlhorky Did you also stress test it / try to break it? 😃

**Comment by karlhorky** [comment]
Yep, sure did! Spent a good 2 minutes trying a bunch of different things. Worked well!

**Comment by karlhorky** [comment]
For anyone following along, #2105 was reverted, and the new PR that is implementing a fix for this is #2060.
