### ISSUE TITLE
Always prompt user on ctrl/cmd-w (even with all files saved) to prevent accidental closing

### ISSUE THREAD

**Issue by karlhorky** [codesandbox/codesandbox-client#2107]
# 🌈 Feature

Always prompt user on ctrl/cmd-w (even with all files saved) to prevent accidental closing. Maybe with a setting, in case some people find it annoying?

I've closed the PWA so many times accidentally now, and it takes me a long time to get back in - need to go over the dashboard again each time :(

One way of doing this would be to always set `onbeforeunload`, even if a file hasn't been saved.

Related: https://github.com/codesandbox/codesandbox-client/issues/1044

**Comment by parkerault** [comment]
I second this. I reflexively hit ctrl-w to close an editor, and the user prompt catches it when I have an unsaved file open, but if everything is saved it closes the browser tab. This happens to me constantly and it drives me crazy.

**Comment by karlhorky** [comment]
not stale

**Comment by SaraVieira** [comment]
hey Karl, 

Same deal as the other two and moved to our backlog. This will be a setting when implemented since it's a super intrusive action to stop people from closing the tab without their consent but a setting that's off by default does not hurt

**Comment by karlhorky** [comment]
Ok, thanks for the heads up :)
