### ISSUE TITLE
Unable to use some modules from Dojo due to dependency error

### ISSUE THREAD

**Issue by agubler** [codesandbox/codesandbox-client#2108]
# 🐛 bug report

## Description of the problem

Using certain modules from `@dojo/framework` causes a dependency error for a module that doesn't exist, for example just importing `@dojo/framework/testing/harness` causes codesandbox to error with:

```
Could not find/install babel plugin 'transform-object-rest-spread': 
Cannot find module '@babel/plugin-transform-object-rest-spread' 
from '/node_modules/diff/dist'
```

Possibly related to https://github.com/codesandbox/codesandbox-client/issues/1178 or https://github.com/codesandbox/codesandbox-client/issues/1177

## How has this issue affected you? What are you trying to accomplish?

Unable to use certain modules from `@dojo/framework`

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1561557066-4a5dea6e4
| Browser          | Chrome Version 75.0.3770.100
| Operating System | macOS Mojave 10.14.5

**Comment by SaraVieira** [comment]
Hey!

Can you please fill in the sandbox with more code so that it shows something using that module?

I think I fixed it but I can't really know :(

**Comment by agubler** [comment]
@SaraVieira No problem! I have updated the sandbox to use the harness.

**Comment by SaraVieira** [comment]
Thank you!

Is this expected?
![Screenshot 2019-07-02 at 11 30 48](https://user-images.githubusercontent.com/1051509/60501776-def69f00-9cbc-11e9-9bf8-e1cb156d1b66.png)

**Comment by SaraVieira** [comment]
Im gonna assume yes and if so I added the babel plugin as an option for dojo and seems to be okay now :)

**Comment by agubler** [comment]
@SaraVieira yup that is the expected assertion error :)

**Comment by SaraVieira** [comment]
Awesome!! Gonna push it then :)

Babel was also updated to 7

**Comment by SaraVieira** [comment]
Both this and netlify should go live tomorrow

Sorry for the delay, we are working in a feature that's taking longer than expected

**Comment by agubler** [comment]
@SaraVieira No problemo! Thanks for the help :)

**Comment by SaraVieira** [comment]
ANy more issues with dojo please ping us here :)
