### ISSUE TITLE
TypeError (0 , _map.default) is not a function

### ISSUE THREAD

**Issue by luwes** [codesandbox/codesandbox-client#2110]
# 🐛 bug report

## Description of the problem

The default export of my library can't be reached producing this error,
`TypeError (0 , _map.default) is not a function`

## How has this issue affected you? What are you trying to accomplish?

Trying to load the default export of `sinuous/map`

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1561557066-4a5dea6e4
| Browser          | Chrome 75
| Operating System | MacOS 10.14.5

**Comment by lbogdan** [comment]
Hey @luwes ,

It looks like that's actually an issue with the `sinuous` package, which does this in [`map/src/index.js`](https://github.com/luwes/sinuous/blob/849653e9feb8de7d393ddde17d20f8e0db75c357/packages/sinuous/map/src/index.js#L1):
```js
export { default } from './map.js';

**Comment by lbogdan** [comment]
Also, if that ^^ fixes your issue, please help us lower the issue count by one! 🙂

**Comment by luwes** [comment]
Thanks @lbogdan, I forgot to close here sorry. 
Yes, it was indeed the `named` export configuration in rollup.

I do think this is valid `export { default } from './map.js';` to export the default export from that file though. Just the rollup option messed it up.

Thanks for looking at the issue and the help.

**Comment by lbogdan** [comment]
I must admit that I still get confused by all the `import` / `export` / `module.exports` / `require` and their interoperability between CJS and ESM... 🤷‍♂
