### ISSUE TITLE
Split Terminal Window/View from Browser Window

### ISSUE THREAD

**Issue by fkaminski** [codesandbox/codesandbox-client#2126]
I am very new to codesandbox and testing with a "node" template.
When i add the "bash" Terminal i would like to have a bigger Window. 

I have tried the possibilities under "View/Editor Layout" but have no luck to separate the Terminal Window from the Browser Window. 
How can i split the Terminal Window from the Browser/Preview?

**Comment by fkaminski-dev** [comment]
Ah - you can drag&drop the tabs as mentioned here:
https://hackernoon.com/announcing-codesandbox-v3-4febbaba1963

> Devtool View
> The browser preview has become multi-functional! We added tabs to the preview (devtool) view that you can use to switch between different devtools. Browser is the default devtool, but if you think that the console is more suitable for your example you can just drag the tab to the first place to make it the default!

Sorry & Thanks

**Comment by lbogdan** [comment]
Hey @fkaminski-dev ,

Closing this, as it seems you self-solved your issue. 🙂 Please re-open if that's not the case.
