### ISSUE TITLE
Option to directly publish the codesandbox as npm package

### ISSUE THREAD

**Issue by arunkumar413** [codesandbox/codesandbox-client#2134]
# 🌈 Feature

Can we have the option to directly publish a codesanbox as npm package to the npm registry. 

1) Users should be able to login to their npm account and publish the codesandbox
2) A button or drop down menu to publish to npm registry. 
3) Predefined package.json template to be consistent with the requirements (https://docs.npmjs.com/packages-and-modules/contributing-packages-to-the-registry) of the npm package.

**Comment by Saeris** [comment]
Hey! We've already got NPM Publishing on our roadmap. I can't give you a timeline on when that feature will land yet, but it is on our radar. Here's a related issue with more thoughts on this subject: https://github.com/codesandbox/codesandbox-client/issues/1731

**Comment by arunkumar413** [comment]
Nice. Good write up @Saeris
