### ISSUE TITLE
Px media queries don't seem to work

### ISSUE THREAD

**Issue by erikdstock** [codesandbox/codesandbox-client#2147]
# 🐛 bug report

## Description of the problem
Pixel-unit media queries [via a css-in-js library] don't seem to work

## How has this issue affected you? What are you trying to accomplish?
I was testing system-ui/theme-ui and thought I'd found a bug where `px` breakpoints were not detected correctly; It turns out they did work, but only when viewing the preview in its own window.
Original issue: https://github.com/system-ui/theme-ui/issues/159

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  PROD-1562230987-16b1bd596
| Browser          | Firefox developer edition
| Operating System | OSX

**Comment by lbogdan** [comment]
Hey @erikdstock ,

Can you please tell us exactly how to reproduce this? What to do, what's the current behavior, and what is the desired behavior? Thanks!

**Comment by erikdstock** [comment]
@lbogdan sure, I'll take another look and see if I can come up with a more minimal example. In short, the attached sandbox has a responsive `breakpoints` property in the `theme` in `theme.js`- this should trigger style changes on the `p` tag as shown here [*the jumping/black part of the window only happened in the gif, not the window- notice the purple text*]:
![2019-07-11 16 59 50](https://user-images.githubusercontent.com/9088720/61085068-6058da80-a3fd-11e9-8a80-0ab791cf42c3.gif)
-----
However, when using the preview tiled alongside the editor, those breakpoints don't seem to fire:
![2019-07-11 16 55 10](https://user-images.githubusercontent.com/9088720/61084866-f8a28f80-a3fc-11e9-801c-5fc560bcf300.gif)

**Comment by erikdstock** [comment]
Updated :)

**Comment by SaraVieira** [comment]
Hey!

Better late then ever but it seems to be working now 🚀
