### ISSUE TITLE
Parcel bundler fails in some projects but works fine in another

### ISSUE THREAD

**Issue by masputih** [codesandbox/codesandbox-client#2153]
# 🐛 bug report

## Description of the problem
Looks like Parcel fails to compile some of my projects, which is odd because those are months old projects that used to be working fine. I forked one of the failed project but the fork failed too. The project compiled just fine when I downloaded it & built it locally. The only "fix" that works for me on codesandbox is create (not fork) a new project  and copy everything from the failed one. Even stranger that my other Parcel-based projects are still working fine.

### Link to sandbox: 
I can't share the project in public but here's the failed output. There should be some `<div>` on the page but there are not. It's just an empty page now.
[Output](https://622w0o3nxk.codesandbox.io/) 

### Your Environment
Mac Chrome 75.0.3770.100

**Comment by lbogdan** [comment]
Hey @masputih ,

Looks like the sandbox you linked to (https://codesandbox.io/s/622w0o3nxk) is not there anymore. Can you please provide another sandbox where this happens? Thanks!

**Comment by masputih** [comment]
@lbogdan My bad... I mistakenly deleted the project but here's another one that exhibits the same issue : https://omkiq.codesandbox.io/

![image](https://user-images.githubusercontent.com/194357/61164905-feef5380-a543-11e9-8442-08a232c32128.png)

I just found out that this issue only affects my private projects. Unlisted & public projects are fine.

**Comment by lbogdan** [comment]
Hello again, and sorry for the delay! Indeed, that's a known issue with private sandboxes, as for a private sandbox you can't access its static assets, which include `index.html`. We have a few ideas of how to overcome this, but didn't get to play with them yet. I'll leave this open until we do.

**Comment by lbogdan** [comment]
A workaround (when not having really sensitive data) would be to use an unlisted sandbox.

**Comment by SaraVieira** [comment]
Closing as this is a known thing for security reasons :(
