### ISSUE TITLE
Tags are missing from sidebar

### ISSUE THREAD

**Issue by tony19** [codesandbox/codesandbox-client#2158]
# 🐛 bug report
<img width="421" alt="Screen Shot 2019-07-13 at 3 57 52 PM" src="https://user-images.githubusercontent.com/26580/61176480-359a8d80-a587-11e9-81e6-46826dd070a8.png">

## Description of the problem
The sandbox tags are no longer shown in the sidebar.

## How has this issue affected you? What are you trying to accomplish?
Tag sandboxes with specific topics

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | `PROD-1563015658-f1842cf7a`
| Browser          | Chrome `Version 75.0.3770.100 (Official Build) (64-bit)`
| Operating System | macOS Mojave `10.14.5`

**Comment by CompuIves** [comment]
Good catch! Committed a fix, expect a deploy tomorrow!
