### ISSUE TITLE
TS transforms array spread wrong

### ISSUE THREAD

**Issue by Haroenv** [codesandbox/codesandbox-client#2166]
# 🐛 bug report

## Description of the problem

the TS transform treats a spread into an array as a safe array; and thus just calls .slice() on it. However, a NodeList which works with spread in browsers does not have that method, and thus throws.

## How has this issue affected you? What are you trying to accomplish?

Confused on why a spread polyfill of a NodeList isn't working in a file which does when processing through babel (local setup)

### Link to sandbox: [link](https://codesandbox.io/s/thirsty-dew-d3yfv) (optional)

This will throw if you call `fnTS`, not if you call `fnJS`

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1563119635-be16eef20
| Browser          | Safari Tech Preview Release 86 (Safari 13.0, WebKit 14608.1.30.2)
| Operating System | MacOS Mojave 10.14.5 (18F132)

**Comment by briancodes** [comment]
It seems that this is a TypeScript configuration issue, but luckily CodeSandbox gives us access to the `tsconfig.json` via the `Configuration Files` gear icon on the side menu. If you click `Create File` for the `tsconfig.json` option, and add `lib: dom.iterable` and `downlevelIteration: true` it should work

```
"lib": [
      "es6",
      "dom",
      "dom.iterable"
 ],
 "downlevelIteration": true,
```

**Comment by Haroenv** [comment]
Thanks! I'll put the config, didn't think of that, because this was made from a path in a repo, which had the config at the root
