### ISSUE TITLE
Failed to launch chrome!

### ISSUE THREAD

**Issue by vinodhum** [codesandbox/codesandbox-client#2179]
# ❔ Question

Hi, I am trying to use puppeteer on node container on codesandbox and cannot get it to work.
I keep getting error failed to launch chrome and I did verified that .local-chromium is available.

here is the error
`(node:73) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/sandbox/node_modules/puppeteer/.local-chromium/linux-672088/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory`

### Link to sandbox: [link]() (optional)
https://codesandbox.io/embed/nextjs-with-puppeteer-mi42m
then go to /api/start

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by lbogdan** [comment]
Hey @vinodhum ,

That's expected, as we use a Docker image derived from the [official node image](https://hub.docker.com/_/node/), which doesn't include the graphical X libraries needed by Chrome(ium).

**Comment by SaraVieira** [comment]
Closed as it's something we do not support on conatiners
