### ISSUE TITLE
Unable to login with Github

### ISSUE THREAD

**Issue by vrunda-thacker** [codesandbox/codesandbox-client#2189]
# 🐛 bug report

## Signin with Github is broken
When clicking on signin getting this blank window:
<img width="1301" alt="Screenshot 2019-07-19 at 5 19 04 PM" src="https://user-images.githubusercontent.com/12512043/61533048-56f8ef00-aa49-11e9-8137-b4880871bb1c.png">

On checking, the console shows these errors:
<img width="1067" alt="Screenshot 2019-07-19 at 5 20 05 PM" src="https://user-images.githubusercontent.com/12512043/61533098-77c14480-aa49-11e9-9d85-ee3423241f8f.png">

**Comment by briancodes** [comment]
I have the same problem with Chrome and Firefox on Windows 10

![image](https://user-images.githubusercontent.com/15702512/61533441-d32d0b80-aa24-11e9-9860-53e14a08988a.png)

**Comment by serdartkm** [comment]
I also got stuck like above screenshot. I am using Google Chrome version 75.0.3770.142. and also tried on Firefox for mac version 68.0.1. It seems to the problem is with codesandbox, because I have no problem when  signing  in with github auth provider on other web sites like netlify.com for example.

**Comment by tarath** [comment]
same problem as above with same console errors, latest chrome on PC

**Comment by lbogdan** [comment]
Thanks for the reports, it's indeed an issue on our side, we're looking into it and will deploy a fix ASAP!

**Comment by CompuIves** [comment]
Fix is being built! Hopefully live within 10 minutes.

**Comment by CompuIves** [comment]
Sorry for the inconvenience here! Fix is now live and everything should work as expected again.

**Comment by briancodes** [comment]
That's was fast! Back up and running 👍
