### ISSUE TITLE
Vue environment mixing up dependencies

### ISSUE THREAD

**Issue by rayfoss** [codesandbox/codesandbox-client#2199]
# 🐛 bug report

## Description of the problem
The vue sandbox behaves unlike vue-cli-service serve. In my case, @feathersjs/commons 1.4.4 is used in codesandbox, but nowhere else. Not on my local install, not on 

## How has this issue affected you? What are you trying to accomplish?
Run feathers-hooks-common on codesandbox... does not work past 4.8.0. Its used in some very public demos.

### Link to sandbox: [https://codesandbox.io/s/fhc-bug-shared-7otk3](https://codesandbox.io/s/fhc-bug-shared-7otk3)
Working elsewhere same code! https://glitch.com/~codesandbox-bug1

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest
| Browser          | Chrome 75
| Operating System | Linux, Android

**Comment by lbogdan** [comment]
Hey @rayfoss ,

Are you still seeing this? I just forked your sandbox and upgraded `feathers-hooks-common` to latest `4.20.7`, and it seems to work just fine: https://codesandbox.io/s/fhc-bug-shared-gkzp4 .

**Comment by rayfoss** [comment]
@lbogdan Yes, it also happens on firefox
![Screenshot from 2019-08-05 08-38-18](https://user-images.githubusercontent.com/876076/62468776-7b004400-b75c-11e9-9f7a-93420f1229e1.png)

**Comment by SaraVieira** [comment]
Hey!


This seemed to be an issue with the old version of feathers and it does indeed still happen.

I am going to close this because if you update to a newer version it works without a hitch, I hope you understand why I am closing this and I am glad it works in the newer version

Thank you and please reopen if you do not agree
