### ISSUE TITLE
Not able to change sandbox name in Sandbox Info

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [codesandbox/codesandbox-client#2205]
# 🐛 bug report

## Description of the problem

When I try to change the name of the sandbox, the input field is resetting.

1. When the cursor reaches the last character while pressing backspace, the text is resetting.
2. When we press ``Ctrl + A`` and backspace, the input field is resetting.

## How has this issue affected you? What are you trying to accomplish?
I am trying to change the sandbox name, but the input field is resetting when I try to clear the name field.

### Link to sandbox: [link]() (optional)

I am attaching a screen recording, which might help you to understand the problem better.

![codesandbox-bug](https://user-images.githubusercontent.com/11075561/61782998-ad3ca800-ae24-11e9-8920-6792048f0412.gif)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  - 
| Browser          | Chrome 75.0.3
| Operating System | macOS - Mojave

**Comment by lbogdan** [comment]
Should be fixed by https://github.com/codesandbox/codesandbox-client/commit/84669141ea1ae1e49177df23c87747df712fc0a4 , closing.
