### ISSUE TITLE
CodeSandBox now entirely unreliable for Live coding and React

### ISSUE THREAD

**Issue by dejayc** [codesandbox/codesandbox-client#2208]
# 🐛 bug report

## Description of the problem

Our company has been using CodeSandBox for remote React coding interviews for about six weeks now.  The live coding feature has been amazing, and we've progressed towards supporting CodeSandBox via site patronage.

Within the past two weeks, however, the reliability of CodeSandBox for interactive React coding has taken a real nose dive.  It's now unusable to the point where we need to migrate from CodeSandBox to a more stable alternative.  This is the same reason we migrated from repl.it to CodeSandBox.

These problems started around the same time I first noticed the new templates feature.  I have no data to suggest that templates are responsible for our problems, but it's true that I switched from using forked sandboxes to using new sandboxes forked from templates.

Here are the problems I've encountered consistently over the past two weeks:

- Horrible synchronization problems occur with file editing.  What users see on their screen when editing a file is often not what I see when I open the same file to observe.  Typing in the same file sometimes results in entirely new segments of code popping into existence, not related to the characters I'm typing.  Code sometimes get duplicated.  Closing and reopening a file can cause the entire file contents to change.

- Non-owner users are often prevented from saving files within the code editor.  Popup errors appear:

<img width="460" alt="codesandbox-error-update-files" src="https://user-images.githubusercontent.com/1250841/61831005-95701e80-ae3a-11e9-9fac-eaafd52be63e.png">

## How has this issue affected you? What are you trying to accomplish?

I'm trying to collaboratively code with other users, and that functionality doesn't seem to work at all now.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Yes |
| Browser          | Version 75.0.3770.142 (Official Build) (64-bit) |
| Operating System | macOS Mojave 10.14.5 |

**Comment by djD-REK** [comment]
Hi DJ!
Sorry to hear about the reliability problems! React live coding interviews
sounds like a great use of the product!!! I'm brand new to the project, but
I'll be following this topic. Mind letting us know what alternative you
switch to for now so I can compare reliability myself ? Thanks!!!

Best,
Derek


--
Derek R. Austin, PT, DPT, MS, BCTMB, CSCS


Join me on LinkedIn: https://www.linkedin.com/in/derek-austin/

**Comment by CompuIves** [comment]
Hey, I'm sorry for this regression. This is a bad one, I'll take a look at this first thing tomorrow and make sure that it's fixed as soon as possible.

**Comment by dejayc** [comment]
We would probably switch to a paid product with an SLA, like CoderPad.

----- Original message -----

**Comment by djD-REK** [comment]
Cool! Well my plan is to help improve the test coverage for codesandbox, so
hopefully in a few weeks we will have a few end to end tests reproducing
the bugs you've reported so we can get them fixed. Thank you!!!

Best,
Derek


--
Derek R. Austin, PT, DPT, MS, BCTMB, CSCS


Join me on LinkedIn: https://www.linkedin.com/in/derek-austin/

**Comment by jaydgoss** [comment]
Please deploy this as soon as possible, hoping to use for a pair interview tomorrow morning.

**Comment by CompuIves** [comment]
I've deployed it yesterday around 11PM UTC. Let me know if it fixed your issues!

**Comment by jaydgoss** [comment]
@CompuIves All fixed, thank you!
