### ISSUE TITLE
Choose between codesandbox.io and csb.app for the preview

### ISSUE THREAD

**Issue by derekdon** [codesandbox/codesandbox-client#2210]
# 🌈 Feature

The organisation I'm working for currently has blocked access to csb.app, but not codesandbox.io. Every time I access my sandbox now the preview is running in csb.app, so doesn't load. It would be great if we could choose between the two.

**Comment by CompuIves** [comment]
Agree, hopefully we can have something working today.

I think we should:
- Ping csb.app on start of application
- If response is bad, we set the frame url in the store to codesandbox.io
- If response is good, we keep the defaults

**Comment by derekdon** [comment]
That would be great, thanks man!

Also if it helps, the internal scansafe at this place reports this after the fact:

`
Mixed Content: The page at 'https://codesandbox.io/s/some-sandbox' was loaded over HTTPS, but requested an insecure resource 'http://alert.scansafe.net/alert/process?a=....&blockedUrl=https%3A%2F%2Ff5knq.csb.app%2F'. This request has been blocked; the content must be served over HTTPS.
`

Cheers.

**Comment by lbogdan** [comment]
Hey @derekdon ,

We're not using any service with that URL, it's most probably injected by one of your installed extensions.

**Comment by derekdon** [comment]
@lbogdan yeah that's just the blocked page, all traffic goes though a scanner here internally, and if it detects something it doesn't like, in this case, the url csb.app preview page, it redirects it to a warning like this. Just added for reference. It's fine with the longer codesandbox.io url.
