### ISSUE TITLE
Failed to save 'index.html': Cannot read property 'updateFiles' of undefined

### ISSUE THREAD

**Issue by IPRIT** [codesandbox/codesandbox-client#2212]
# 🐛 bug report

## Description of the problem
Every time the interlocutor tries to save the project, he gets an error: "Failed to save 'index.html': Cannot read property 'updateFiles' of undefined".
There is only one way to save the project - is to save yourself as the Owner of the room. This error occurs even for Editors.

## How has this issue affected you? What are you trying to accomplish?
I can't do any interviews with this service. The error appeared about 2 weeks ago and still exist. It's actually fully broken for the interlocutor.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1563972488-ffbcd8857
| Browser          | Version 70.0.3538.110 (Official Build) (64-bit)
| Operating System | Ubuntu 16

**Comment by CompuIves** [comment]
I'm working on a fix for this today, sorry for the inconvenience!
