### ISSUE TITLE
File content is file url and not the actual content

### ISSUE THREAD

**Issue by shavyg2** [codesandbox/codesandbox-client#2222]
# 🐛 bug report

## Incorrect data for file content
The fork of the node template is loading the url of the file and not the actual file content as the content

### Fork from node, with file changed

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | LIVE?
| Browser          | chrome / firefox
| Operating System | windows/mac

**Comment by lbogdan** [comment]
Hey @shavyg2 ,

How did you get the files that have the URL instead of the contents inside the sandbox?

**Comment by shavyg2** [comment]
lol, i dragged and dropped the files over into the container.
I selected multiple files when uploading, since i don't upload folders,
i created the folders one by one and then i drag and drop the content

**Comment by shavyg2** [comment]
ps your podcast interview was jokes

**Comment by shavyg2** [comment]
This is still happening, and shouldn't be close or do i need to clear cache or something,
either way shouldn't be on the user to find the fix.

https://www.youtube.com/watch?v=diQnEbNJtqk&feature=youtu.be
