### ISSUE TITLE
Folder names not trimmed in editor

### ISSUE THREAD

**Issue by SaraVieira** [codesandbox/codesandbox-client#2229]
# 🐛 bug report

## Description of the problem
When adding a new folder if by accident I leave a space at the end of the folder name codesandbox won't trim it making it harder to link to things

## How has this issue affected you? What are you trying to accomplish?
Trying to link an image

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |PROD-1564153504-2b37aae59
| Browser          |Chrome
| Operating System |Mac

**Comment by jyash97** [comment]
Is this open for accepting PR?
