### ISSUE TITLE
Preview iframe doesn't load content on local dev environment

### ISSUE THREAD

**Issue by jchavarri** [codesandbox/codesandbox-client#2233]
# 🐛 bug report

## Description of the problem

While trying to run codesandbox in a local environment, the preview iframe is not loading any content.

In Firefox, it shows the server not found message ("Hm. We're having trouble finding that site").

In Chrome, it shows "Invalid Host Header".

## Note

This seems to be a recent regression as I was able to make everything work by checking out a random commit from a few weeks ago (aef206ac213e18bbfd698e0bae9c7665ee613d0e)

## How has this issue affected you? What are you trying to accomplish?

I was trying to run codesandbox locally, using `yarn` and then `yarn start`.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | master (253226833fb94d2b3a0156061d8c218e0586c054) |
| Browser          | Firefox 68.0.1 / Chrome 75.0.3770.142 (Official Build) (64-bit)
| Operating System | macOS 10.13.6

**Comment by lbogdan** [comment]
Hey @jchavarri ,

Is this still happening for you on the latest `master`?

**Comment by jchavarri** [comment]
hey @lbogdan,

I tried with latest `master` (38398c418a9b8897b09ecedf72275f68448f5f38) and it works perfectly :)
