### ISSUE TITLE
Codesandbox Containers are unstable when dependencies change.

### ISSUE THREAD

**Issue by NullVoxPopuli** [codesandbox/codesandbox-client#2236]
# 🐛 bug report

## Description of the problem

Started with https://codesandbox.io/s/my-app-5r141
and it was showing an error.
Forked to https://codesandbox.io/s/my-app-5dszw to debug
and everything worked.

## How has this issue affected you? What are you trying to accomplish?

I've noticed a metric ton of issues with container sandboxes and dependency changes. Seems very unstable.

### Your Environment

(not a UI issue)

**Comment by lbogdan** [comment]
Hey @NullVoxPopuli ,

As we already discussed on Spectrum, we're not doing anything more than installing packages using `yarn install` and running the dev server defined in `package.json` (which, in Ember's case, is `"start": "ember serve"`) inside a container, so it should work exactly as it works in a local environment.

Nevertheless, if you can provide a step-by-step reproduction, we will of course take a look!
