### ISSUE TITLE
Vue cannot find element to mount

### ISSUE THREAD

**Issue by luckylooke** [codesandbox/codesandbox-client#2238]
# 🐛 bug report

## Description of the problem
If I rename id="app" to anything else, Vue app is not able to find element
error:
```
[Vue warn]: Cannot find element: #example
```
locally it works like a sharm... when I download the project to my machine and run `npm i` and `npm run serve`, it does not have problem to find the element

## How has this issue affected you? What are you trying to accomplish?
I was showing colleagues how vue works and I wanted to show them that ID can be customized, and even that it can be class... or other css selector.. al of this worked locally, but not in codesandbox.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/embed/vue-cannot-find-element-3i7mm
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser       | Chrome Version 75.0.3770.142 (Official Build) (64-bit)  |
| Operating System | Mac High Sierra |

Thank you :)

**Comment by cristianbogdan** [comment]
I could not get any other setup to work than the one in the Codesandbox template. Unless a root component is defined with the 
id #app, things will fail.

This would almost be acceptable but Components with an ID seem to defeat the purpose of composition.
