### ISSUE TITLE
Activating extension 'vscodevim.vim' failed: Invalid regular expression: invalid group specifier name.

### ISSUE THREAD

**Issue by nikitavoloboev** [codesandbox/codesandbox-client#2244]
# 🐛 bug report

## Description of the problem

I get `Activating extension 'vscodevim.vim' failed: Invalid regular expression: invalid group specifier name.` error when trying to use Vim mode with VSCode in Safari

## How has this issue affected you? What are you trying to accomplish?

Want to use Vim mode but can't.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  Latest I think
| Browser          | Safari 12.1.2
| Operating System | macOS 10.14.6

**Comment by CompuIves** [comment]
Hmm yes, I think this is caused by a regexpression that's used by the VIM Extension that's only supported in Chrome. I opened a PR for the vim extension to remove this logic, I'll check if it got merged so we can update the extension!

**Comment by lbogdan** [comment]
@CompuIves Can you link the PR, please?

**Comment by nikitavoloboev** [comment]
Any way I can help fix this?

**Comment by nikitavoloboev** [comment]
This is an annoying issue for me as I can't copy things in CodeSandbox on Safari too. I assume due to VIM that doesn't even work. 😞

**Comment by nikitavoloboev** [comment]
I can't edit the code now. What do I do? I tried resetting the cache and that doesn't fix it.

cc @CompuIves @lbogdan

**Comment by CompuIves** [comment]
Hey @nikitavoloboev, did you try resetting your `localStorage`? That is where we set the extension settings.

**Comment by nikitavoloboev** [comment]
That helped, can type now.

Still would love to use Vim extension with Safari.

**Comment by SaraVieira** [comment]
Hey!

This will work as soon as Safari supports lookbhind expressions: https://caniuse.com/#feat=js-regexp-lookbehind

Right now it's lagging behind and there is really not a lot we can do

I am closing this issue since the error is now gone, I hope you understand :/
