### ISSUE TITLE
💥 Crash Report: Users cannot view live session

### ISSUE THREAD

**Issue by ddruker** [codesandbox/codesandbox-client#2253]
# 🐛 bug report

## Description of the problem

When users, other than the creator of the repository, attempt to join a live session, the app crashes with the following error. I believe they are able to join the session but cannot view it.

![img](https://d2ddoduugvun08.cloudfront.net/items/250n3I3F1z1c0h223r1z/Image%202019-08-05%20at%205.28.52%20PM.png?X-CloudApp-Visitor-Id=2665712)

## How has this issue affected you? What are you trying to accomplish?
Attempting to share a live session for pairing!

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by iwoodruff** [comment]
Getting this as well – users entering the sandbox log in but hang on the "Joining Live Session" interstitial page. Seeing this in all browsers on mac (haven't tried other OS).

Thanks for all the good work :)

**Comment by eric-personal** [comment]
Same issue as both iwoodruff and ddruker anyone know a fix to this ?

**Comment by chrissnyder** [comment]
Also experiencing this. Happy to provide any other details that would be helpful.

**Comment by ookblah** [comment]
Also seeing this issue on mac

**Comment by CompuIves** [comment]
A fix for this is live! Sorry for the delay here.
