### ISSUE TITLE
Cloudfront.net loaded resources for paid users in China, access is too slow

### ISSUE THREAD

**Issue by janryWang** [codesandbox/codesandbox-client#2254]
# 🐛 bug report

## Description of the problem

Cloudfront.net loaded resources for paid users in China, access is too slow. It usually takes 5 to 10 minutes to complete the resource loading.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | codesandbox.io
| Browser          |  chrome
| Operating System | mac

**Comment by djD-REK** [comment]
Hey @janryWang sorry would you mind fixing your sandbox link?  It's linking back to this issue.  What are you loading the resources for?  Could you speak a little more about the issue??  Thanks!!

**Comment by janryWang** [comment]
![image](https://user-images.githubusercontent.com/4060976/62601559-37f0cd00-b924-11e9-831a-59c97df90e0d.png)
![image](https://user-images.githubusercontent.com/4060976/62601594-4dfe8d80-b924-11e9-9a30-de414021091f.png)

@djD-REK very slow.
