### ISSUE TITLE
502: Bad Gateway due to Github commit

### ISSUE THREAD

**Issue by NickCarducci** [codesandbox/codesandbox-client#2255]
I integrated my codesandbox with Github and received "_502: Bad Gateway We had trouble connecting to the server, try restarting it or check the logs to see what happened._" in the browser with nothing in console or terminal.

https://github.com/NickCarducci/Thumbprint - it committed itself to Github well right away

https://codesandbox.io/s/new-mo0d3?fontsize=14 - but something is wrong with the sandbox as of today 8/6/2019

###Environment
| React | v16.8.6 |
| Сodesandbox  |
| Chrome Browser  |
| Mac OS |

**Comment by lbogdan** [comment]
Hey @NickCarducci ,

From a quick look, you don't have `react-scripts` in your `(dev)dependencies`.

**Comment by lbogdan** [comment]
You also have
```json
  "engines": {
    "node": "^7.10.0"
  },
```
in your `package.json`, but we're running node 10.x inside the container, which leads to an error running yarn:

![image](https://user-images.githubusercontent.com/2083930/62550380-75911f80-b86a-11e9-8223-d7b175af5a43.png)

**Comment by lbogdan** [comment]
Removing `engines` and adding `react-scripts` to `devDependencies` will get you to https://codesandbox.io/s/new-6ogp5 (which still doesn't work, but that seems to be more like an app issue).

**Comment by NickCarducci** [comment]
1) Why do we need 
  "devDependencies": {
    "typescript": "3.3.3",
    "react-scripts": "^3.0.1"
  },
for committing to github?  _Is there documentation with this instruction that you want to leave for people viewing this thread?_
2) I copied that node version from a tutorial this morning... fixed

**Comment by lbogdan** [comment]
Well, as long as you're using the `react-scripts` CLI to run the devserver, as configured here https://github.com/NickCarducci/Thumbprint/blob/86db2d358cc4c3b81f9fb989df09928d74bf0605/package.json#L32 , you need to have `react-scripts` in `(dev)dependencies`. It's also worth mentioning that `react-scripts` is part of `create-react-app`, and it's added to `devDependencies` when you create a new project using CRA. You can read more about that in [CRA's documentation](https://facebook.github.io/create-react-app/docs/getting-started).

**Comment by NickCarducci** [comment]
I don't understand the difference between (dev)dependencies and dependencies yet, I'll do that research.  I made that change anyway and just removed engine {node} for now but still get 502 badgateway.  Do I have to commit, wait for auto-commit, or is there something else wrong with code/packages when it integrates with github? It was running well on codesandbox servers before committing to github.

**Comment by lbogdan** [comment]
Hm, I don't see any new commits in the GitHub repo, where exactly did you make the change?

**Comment by NickCarducci** [comment]
Now I'm getting a "reguest entity too large" error
<img width="1479" alt="Screen Shot 2019-08-06 at 11 32 29 AM" src="https://user-images.githubusercontent.com/12148373/62553782-f554c500-b83d-11e9-92b4-055e8a618035.png"> I guess it didn't commit.  Does the browser in codesandbox (((this example: https://mo0d3.sse.codesandbox.io/ read from github and not store on codesandbox servers anymore since I first commit it?  Seems to be so I guess since the gateway must be referring to the github connection & it ran well before connection.

Anyway, I put react-scripts into devDependencies & deleted node, it just now says "request entity too large" to commit to github(fetching...)

**Comment by NickCarducci** [comment]
I'm still getting this newest "_request entity too large_" error in my last comment above**;** _but I fixed my own bug (it was the .ttf for my header), it didn't throw an error yet before I switched to github because_ I guess react hasn't had to source it in a component until the switch to github.

**Comment by NickCarducci** [comment]
I just deleted the repository on github and recommitted, & now there is no size error, and it updates real-time. Case closed

**Comment by BabithaSujannaDatagaps** [comment]
I faced the same issue while committing data in GitHub private repository (free version), got  502 BadGateWay while using https://api.github.com/repos/{owner}/{repo}/git/trees service, if the payload is approximately above 2.5MB and when I tried the same with Enterprise cloud problem resolved, able to commit more MB files without any issue.
