### ISSUE TITLE
"Editor within an editor" issue when importing Node project from GitHub

### ISSUE THREAD

**Issue by tylerbrostrom** [codesandbox/codesandbox-client#2256]
# 🐛 bug report

## Description of the problem

Importing a project from GitHub with `template` property in `sandbox.config.json` set to `node` results in a weird "editor in editor" codeception as depicted in the below screenshot.

![screenshot](https://dzwonsemrish7.cloudfront.net/items/2i2J2L37150b3p3n3U2O/Screen%20Shot%202019-08-06%20at%201.42.10%20PM.png?v=3bc5ca82)

## How has this issue affected you? What are you trying to accomplish?

I am trying to run a Parcel project inside a Node container template sandbox. This project has a bit of custom config (e.g. `.htmlnanorc`, `.posthtmlrc`, `postcss.config.js` ) which rules out using a vanilla (Parcel) sandbox template.

Ideally, I'd like to be able to use this sandbox to run Parcel in both development mode and production mode (in this project, that's `yarn start` and `yarn build`, respectively).

### Prior (unsuccessful) troubleshooting
- Added a `start` script to `package.json`
- Switched package managers from `npm` to `yarn`
- Changed `start` script to use port `8080`

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1565017826-4f295f72c
| Browser          | Version 75.0.3770.142 (Official Build) (64-bit)
| Operating System | macOS 10.14.6 (18G84)

**Comment by lbogdan** [comment]
Hey @bro-strummer ,

It looks like the linked sandbox was deleted, can you please provide a link to the GitHub repository you're trying to import?

**Comment by bro-strummer** [comment]
Hi @lbogdan,

Sorry about that! I actually had the sandbox set to private. I’ve made sandbox public for the time being. [Here’s the public link.](https://codesandbox.io/s/ale-stray-forth-site-3dbdp)

**Comment by SaraVieira** [comment]
Hey!

Doing some spring clean up

Is this still happening? Seems that sandbox was also deleted :(

**Comment by tylerbrostrom** [comment]
Ah shoot. Must’ve absent-mindedly deleted that sandbox. I can’t confirm if it is still happening or not. I apologize about that @SaraVieira.

**Comment by SaraVieira** [comment]
No worries, is it okay if I close it?

**Comment by tylerbrostrom** [comment]
Go for it! I’ll update if I encounter this issue in the future.

**Comment by SaraVieira** [comment]
Thanks and yeah please re open :)
