### ISSUE TITLE
'module' is not defined(no-undef)

### ISSUE THREAD

**Issue by chunzhenzyd** [codesandbox/codesandbox-client#2258]
# 🐛 bug report

## Description of the problem
I add vue.config.js, the content is:

module.exports = {
  css: {
    loaderOptions: {
      less: {
        modifyVars: {
          "primary-color": "#1DA57A",
          "link-color": "#1DA57A",
          "border-radius-base": "2px"
        },
        javascriptEnabled: true
      }
    }
  }
};

There will be an error in console: 
'module' is not defined(no-undef)

main.js:

import Vue from "vue";
import App from "./App.vue";
import Button from "ant-design-vue/lib/button";
import "ant-design-vue/dist/antd.less";

Vue.component(Button.name, Button);
Vue.config.productionTip = false;

new Vue({
  render: h => h(App)
}).$mount("#app");

BTW, I have add dependencies: @vue/cli 3.10.0, less, less-loader

## How has this issue affected you? What are you trying to accomplish?
Can't use personal theme in ant-design-vue project.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by lbogdan** [comment]
Hey @chunzhenzyd ,

Can you please provide a link to the sandbox experiencing this issue?

**Comment by chunzhenzyd** [comment]
Hi @lbogdan,

Is this one : https://codesandbox.io/s/vue-template-e7b28

**Comment by lbogdan** [comment]
We don't currently support `@vue/cli` 3 in client sandboxes, which run completely in the browser. What you could do is use a server sandbox, having https://codesandbox.io/s/github/lbogdan/cs-vue-cli-3 as a starting point, for example.

**Comment by chunzhenzyd** [comment]
Hi @lbogdan,

The 'module' no-undef problem still occurs in server sandbox.

![FireShot Capture 004 - cs-vue-cli-3 - CodeSandbox - codesandbox io](https://user-images.githubusercontent.com/26733398/62690153-c6398180-b9fe-11e9-999e-336cd3bd5d0c.jpg)

**Comment by lbogdan** [comment]
Oh, you can safely ignore that, it's just an `eslint` quirk.

**Comment by chunzhenzyd** [comment]
Hi @lbogdan,

OK, thanks!
