### ISSUE TITLE
Embed Option: Hide Header Bar?

### ISSUE THREAD

**Issue by karlhorky** [codesandbox/codesandbox-client#2259]
# 🌈 Feature

Would the CodeSandbox team be open to introducing an [embed option](https://codesandbox.io/docs/embedding#embed-options) for hiding the header bar in the embeds?

To be clear, this is the element that I mean:

![Screen Shot 2019-08-07 at 10 26 13](https://user-images.githubusercontent.com/1935696/62609734-94db8b80-b902-11e9-8b88-e8cd467da43a.png)

If there are some important buttons there (such as the hamburger button) then maybe they could be moved elsewhere (or a "header toggle" button added)? Such as down on the bottom bar:

![Screen Shot 2019-08-07 at 10 57 28](https://user-images.githubusercontent.com/1935696/62609978-00bdf400-b903-11e9-89c2-d687d92dce7f.png)

**Comment by karlhorky** [comment]
**Workaround:** Add an element with `position: absolute; z-index: 1;` to act as a layer over top of the iframe to obscure the top navigation bar (47px high to leave a 1px top border):

![Screen Shot 2019-08-07 at 11 30 25](https://user-images.githubusercontent.com/1935696/62611978-e71eab80-b906-11e9-8dfb-8a4769ab550f.png)

**Comment by siddharthkp** [comment]
Hi 👋 

We started work on an embed redesign recently and this is one of the customisations we're looking at. 

No promises yet, but will keep this thread updated!

**Comment by siddharthkp** [comment]
Hey @karlhorky, we got rid of the header in the new redesign. Instead of opting for a minimal resizer between code and preview.

More here: https://codesandbox.io/post/codesandbox-ci-embeds#a-new-look-for-embeds

Let us know what you think about that!

**Comment by karlhorky** [comment]
@siddharthkp Sweet, that's great to have more space by default, thanks!
