### ISSUE TITLE
Sandbox crashes when trying to add dependencies that start with 'clust...'

### ISSUE THREAD

**Issue by gargantuan** [codesandbox/codesandbox-client#2262]
# 🐛 bug report

Try to add a dependecy to a sandbox
Type the words 'clust'
Sanbox crashes

## How has this issue affected you? What are you trying to accomplish?
I was trying to test this module
https://www.npmjs.com/package/set-clustering#algorithm

but I can't

### Link to sandbox: 
Occurs on any sandbox as far as I can tell

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1565017826-4f295f72c
| Browser          | Firefox, Chrome, Safari
| Operating System | MacOS

**Comment by gargantuan** [comment]
Console error
```
common.f4fb500d.chunk.js:14 TypeError: Cannot use 'in' operator to search for '0.0.0' in undefined
```

**Comment by SaraVieira** [comment]
Hey!

Thank you for making the issue, we were always seazrching for the version and someone made a package without any idk how and it broke it :(

Just made a PR
