### ISSUE TITLE
Add things from "External Resources" to code

### ISSUE THREAD

**Issue by Rulikkk** [codesandbox/codesandbox-client#2268]
# 🌈 Feature

Idea is to add things from "External Resources" somewhere to code. E.g. to `index.html`.

Currently, these resources aren't reflected anywhere in code files, and if you download sandbox as ZIP, you have to fix it by hand.

`Package.json` has entry point for the app. Most likely, this will be HTML, so external resources can be added to `head`, depending on their type, as css or js.

**Comment by oskarabc** [comment]
We should be able to include this in one of our next releases and include those lost resources into the downloadable zip.
