### ISSUE TITLE
Two identical code sandboxes, one works, one doesnt

### ISSUE THREAD

**Issue by ryanto** [codesandbox/codesandbox-client#2269]
# 🐛 bug report

## Description of the problem

I have two identical code sandboxes, both forked from a github repo. On one of the code sandboxes the tests fail to load. On the other they pass.

Sandbox 1 (working): https://codesandbox.io/s/react-mirage-demo-mq14e
Sandbox 2 (not working): https://codesandbox.io/s/react-mirage-demo-hkce3

Repo: https://github.com/miragejs/react-demo

## How has this issue affected you? What are you trying to accomplish?

Trying to share an example demo app

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1565017826-4f295f72c
| Browser          | Chrome 76
| Operating System | OSX

**Comment by shiftyp** [comment]
FWIW both sandboxes showed me a page with users with no errors. This is the second one in Chrome 76 on OSX.

<img width="1108" alt="Screen Shot 2019-08-09 at 3 58 51 PM" src="https://user-images.githubusercontent.com/131928/62805665-a4073880-babe-11e9-97e6-7c6c30c9d0be.png">

**Comment by ryanto** [comment]
Hi @shiftyp, Thanks for looking... The problem is on the "Tests" tab.

**Comment by shiftyp** [comment]
> Hi @shiftyp, Thanks for looking... The problem is on the "Tests" tab.

In both the tab loads, the tests run, and I get this failure:

```
Could not find module in path: '@testing-library/react/cleanup-after-each' relative to '/src/setupTests.js'
```

Is that what you're seeing?

**Comment by ryanto** [comment]
Now I see the error in both sandboxes.

When I posted this issue, one of the sandboxes was working and the other was not. I haven't edited either of the sandboxes since posting the original issue.
