### ISSUE TITLE
🐛 Bug Report: Some problems when using Monaco editor

### ISSUE THREAD

**Issue by R4M80MrX** [codesandbox/codesandbox-client#2273]
# 🐛 Bug Report: Some problems when using Monaco editor

1. \<Configuration\> and \<ImageViewer\> doesn't have prop sandbox, so 
![image](https://user-images.githubusercontent.com/29365693/62818078-62d16000-bb74-11e9-8e0b-2431f3b6b444.png)
will happen in disposeModuleHandler at
```javascript
if (
            currentSandbox.id !== store.editor.currentSandbox.id &&
            editor.changeSandbox
          ) 
```
I just give sandbox props to these two components.

2. \<Configuration\> can't fully displayed.
![image](https://user-images.githubusercontent.com/29365693/62818147-9b256e00-bb75-11e9-83a2-7c0cbc91987a.png)

3. Uncaught (in promise) Error: ModelService: Cannot add model because it already exists!
This happened when I switched from \<Configuration\>\<ImageViewer\> to \<Monaco\>, 
I'm trying to figure out why, all model and editor itself disposed when component unmout, 

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest commit
| Browser          | Chrome 76
| Operating System | Win10 64

**Comment by SaraVieira** [comment]
Closing as we moved completly to VSCode
