### ISSUE TITLE
"Could not find module in path" error even though installed

### ISSUE THREAD

**Issue by gragland** [codesandbox/codesandbox-client#2276]
# 🐛 bug report

## Description of the problem
I have the npm module `analytics` installed but I'm seeing the following error in a new React CodeSandbox.
```
Could not find module in path: 'analytics' relative to '/src/index.js'
```
The only code I've added to the default React CodeSandbox is this in `src/index.js`:
```js
import Analytics from 'analytics';
```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1565017826-4f295f72c
| Browser          | Chrome 76
| Operating System | macOS 10.13.6

**Comment by lbogdan** [comment]
Hey @gragland ,

It seems to work fine here:

![image](https://user-images.githubusercontent.com/2083930/62826537-bcaa4800-bbbd-11e9-9636-f07b1d79c390.png)

**Comment by gragland** [comment]
Oh, weird, working for me now as well. Will close this and re-open if I see the issue again.

**Comment by gragland** [comment]
Okay seeing this issue again and have error details:

```
Uncaught (in promise) TypeError: Failed to fetch
sandbox.9b5dc6d7.js:1 GET https://cdn.jsdelivr.net/npm/analytics@0.1.16/lib/analytics.browser.cjs.js net::ERR_FAILED
```

**Comment by gragland** [comment]
@lbogdan Is there any other info I can provide on this? I'm currently using this analytics library in the code that divjoy.com exports to CodeSandbox and seeing a lot of users export broken projects to CodeSandbox. Wondering if there's an issues somehow with the analytics lib (although not sure that would make sense given it seems to be an intermittent problem) or if it relates to CodeSandbox or cdn.jsdelivr.net. Happy to provide any info if it's still not happening on your end with https://codesandbox.io/s/4pe06

**Comment by gragland** [comment]
Okay figured out the culprit with the help of @DavidWells. uBlock Origin was blocking the script from being loaded from unpkg, even with it set to "allow all scripts" (presumably because it's loaded from the csb.app domain). Guess it doesn't like anything with the term "analytics" in the path. @lbogdan Not sure if there's an elegant fix here on the CodeSandbox side, but maybe you have an idea.
