### ISSUE TITLE
How do I enable vim ?

### ISSUE THREAD

**Issue by a-eid** [codesandbox/codesandbox-client#2281]
I'm unable to find away to enable vim but unable to, 

trying to follow this from the docs but not sure where to find vim... 
```
We also include the VSCodeVim extension by default, you can enable it by opening preferences and going to Editor.
```

**Comment by baremetalfreak** [comment]
1. Click your avatar icon in to top right corner
1. Select Preferences
![Screenshot 2019-08-15 at 08 02 18](https://user-images.githubusercontent.com/19686979/63075772-1fd80980-bf33-11e9-9541-13b83998112f.png)
1. On the left side of the preferences dialog click on `</> Editor`
1. Click on the flipswitch to enable vim mode
![Screenshot 2019-08-15 at 08 02 29](https://user-images.githubusercontent.com/19686979/63075843-4f871180-bf33-11e9-967b-766e86c4a860.png)

**Comment by CompuIves** [comment]
Thanks a lot for this clear explanation @baremetalfreak, really useful! I'll close this one now, if there are any other questions feel free to open a new issue!

**Comment by haexyh** [comment]
Nowadays you can do it here:
<img width="446" alt="image" src="https://github.com/codesandbox/codesandbox-client/assets/22192159/ca96a9cc-02d2-4a32-a52d-61a7a7fd4150">
<img width="1189" alt="image" src="https://github.com/codesandbox/codesandbox-client/assets/22192159/e436343a-b32e-44e5-958d-ab2fb31d6b2b">
