### ISSUE TITLE
How to sync github changes back to sandbox?

### ISSUE THREAD

**Issue by Rulikkk** [codesandbox/codesandbox-client#2282]
# ❔ Question

During following scenario:
- Open sandbox from github repo
- Try making some edits—codesandbox will fork to do this
- Do some edit in a forked sandbox—it will stay "connected" to github repo and allow committing, new commits stay synced with codesandbox
- Do some edits in github repo (not from sandbox)—**how to import github changes back to sandbox?**

Overall, I'm trying to do "full dev in browser", with github to netlify for publishing changes and kepping commits + issues + PRs and Codesandbox for personally doing stuff in that repo.
However, lack of "import changes back from github" breaks this (almost complete otherwise) style.

**Comment by Rulikkk** [comment]
There's probably a way to start off each time with "codesandbox/github/repo/name" link and for each time—but I don't want to create too much sandboxes and load up servers too much.

**Comment by SaraVieira** [comment]
Hey!

This actually already works withe new GH integration and it's automatic
