### ISSUE TITLE
Dependencies cache issue on the server

### ISSUE THREAD

**Issue by oliviertassinari** [codesandbox/codesandbox-client#2284]
# 🐛 bug report

## Description of the problem

I believe there is a caching issue with the server-side containers. Running the following url https://codesandbox.io/s/github/mui-org/material-ui/tree/master/examples/nextjs should start a project with the latest version of the dependencies. It seems that it's not the case for Material-UI. From what I can observe, it pulls our v3 instead of v4.

## How has this issue affected you?

The problem was reported by one of our users in https://github.com/mui-org/material-ui/issues/16979.

### Link to sandbox

- buggy: https://codesandbox.io/s/github/mui-org/material-ui/tree/master/examples/nextjs
- After forcing a fresh install of the dependencies: https://codesandbox.io/s/nextjs-6j8u7

**Comment by lbogdan** [comment]
Hey @oliviertassinari ,

Does this https://github.com/codesandbox/codesandbox-client/issues/2075#issuecomment-503450482 maybe addresses your issue?

**Comment by oliviertassinari** [comment]
Ok, I think that we can try `"post-update": "yarn upgrade"` to workaround the limitation.

**Comment by lbogdan** [comment]
Nice! Closing this for now, please reopen if you have further issues. Also, for more general questions, please open a thread on [Spectrum](https://spectrum.chat/codesandbox).

**Comment by oliviertassinari** [comment]
We went for not applying this patch. The example is optimized for people starting a new project, we shouldn't mix the concerns.

**Comment by oliviertassinari** [comment]
Is they a way to solve this problem without leaking the concern outside codesandbox?

**Comment by lbogdan** [comment]
We're always open to suggestions. :-)

**Comment by oliviertassinari** [comment]
I was wondering, maybe we could use an env variable to conditionally apply the command?

```diff
 "scripts": {
    "dev": "next",
    "build": "next build",
-   "start": "next start"
+   "start": "next start",
+   "post-update": "[[ -n $CODESANDBOX ]] && yarn upgrade --latest"
  }
}
```

But then, what about Windows 🙃 cc @garethx

**Comment by lbogdan** [comment]
But `post-update` has not meaning outside CodeSandbox, anyway?

**Comment by oliviertassinari** [comment]
@lbogdan I didn't know that. I thought it was a npm command I wasn't aware of. I think that if it were prefixed with `codesandbox-post-update`, it would have been trivial to figure it out, as well for our users to feel confident removing the line once they clone the examples :).

**Comment by lbogdan** [comment]
Yeah, we modeled it after `post-install`, which **is** a npm thing, and named it like that because it's supposed to run whenever the git repo updates. Whether we should have namespaced it with the `codesandbox-` prefix I think it's up for debate. 🙂

**Comment by oliviertassinari** [comment]
@garethx what do you think about reopening the pull request, for all our demos with this approach?

```diff
 "scripts": {
    "dev": "next",
    "build": "next build",
-   "start": "next start"
+   "start": "next start",
+   "post-update": "echo \"codesandbox preview only, need an update\" && yarn upgrade --latest"
  }
}
```

@lbogdan Thanks for the help.
