### ISSUE TITLE
Disable Preview Refresh?

### ISSUE THREAD

**Issue by anaknickerbocker** [codesandbox/codesandbox-client#2285]
# ❔ Question

Is it possible to disable refreshing the preview until I'm done writing code? The errors are distracting.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1565698141-72e49c6fa
| Browser          | Chrome
| Operating System | Mac OS

**Comment by susanschen** [comment]
File 
Preferences
Codesandbox Settings
Preview
Turn off "Preview on edit"
Turn off "Instant preview"

**Comment by anaknickerbocker** [comment]
👍

**Comment by jzevin** [comment]
if anyone comes across this looking to disable the auto preview of a stuck sandbox you can add ```?runonclick=1``` as a param https://github.com/codesandbox/codesandbox-client/issues/1815#issuecomment-581345116

**Comment by milesholt** [comment]
> GIF for good measure
> 
> ![Peek 2021-10-08 21-41](https://user-images.githubusercontent.com/8305511/136643079-4a20c164-65eb-42be-93bd-bfe0e12ceaa0.gif)

Where is this for IOS App and Web?

**Comment by misimpso** [comment]
@milesholt It's in the new "User Preferences" section. I changed it to "On-save" than turned off the "Auto Save".

https://github.com/codesandbox/codesandbox-client/assets/16249360/c2bba13f-3e47-428b-b02c-07d1130e034a
