### ISSUE TITLE
Breakpoints and debugging

### ISSUE THREAD

**Issue by karlfus** [codesandbox/codesandbox-client#2294]
# 🌈 Feature
VSCode allows debugging in Node and Chrome, or even within an embedded browser, with breakpoints etc.

Is there any plan for this? If so, it should work more-or-less like VSCode, or at least like it does in the Chrome web tools.

**Comment by howel52** [comment]
😬 Has any progress  ?   @SaraVieira

**Comment by timshaw9791** [comment]
do we have a plan for it?

**Comment by nezort11** [comment]
You can debug in Chrome:

1. Right click on the preview browser and choose inspect
2. Go to sources tab
4. Expand `sandboxid.csb.app` (e.g. `wgy19d.csb.app`) (it is iframe sources)

If using TypeScript:

5. Expand ~/src
6. You'll see all your files there.

For me `index.ts` is a compiled JavaScript and `index.ts [sm]` is source code.

7. Then put a breakpoint in devtools, make a change in source code to trigger breakpoint stop and debug your sources 👍 

![image](https://user-images.githubusercontent.com/59317431/208272436-a5564c82-6cf2-47bd-9623-714de06384a6.png)

![image](https://user-images.githubusercontent.com/59317431/208272463-4cf7384a-02c6-4d6c-a62d-62f41419c327.png)
