### ISSUE TITLE
Latest release prevents the iFrame preview window from falling below 644px width.

### ISSUE THREAD

**Issue by technicallynick** [codesandbox/codesandbox-client#2298]
# 🐛 bug report

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  https://codesandbox.io/s/media-query-failure-8u6pw
| Browser          | Chrome Version 76.0
| Operating System | Mac OS 10.14.6

**Comment by eldrgeek** [comment]
When I clik on the "Problems" button or React Devtools the window resizes to a minimum of 450 on my machine.
Clicking on "Console" resizes back to minimum of 659 on my setup.
This may be calcualaged from window.screen.availWidth

**Comment by garethx** [comment]
I mentioned this on Spectrum, but just for info here too: It only happens with the layout flipped, so as a temporary workaround you can try View > Editor Layout > Flip full layout and the preview will then appear beneath the editor, and can be resized without issue. Meanwhile, we'll look into the cause of this. Thanks for raising.

**Comment by garethx** [comment]
Video of issue: https://www.hippovideo.io/video/play/NLGv8mVq1zP1BEnLr-EcQw
