### ISSUE TITLE
I have a question about EntryTitleInput

### ISSUE THREAD

**Issue by R4M80MrX** [codesandbox/codesandbox-client#2301]
# ❔ Question

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |local dev
| Browser          |chrome 73
| Operating System |mac OS && win10

local dev
![屏幕快照 2019-08-18 下午4 50 04](https://user-images.githubusercontent.com/29365693/63222273-45d20800-c1d8-11e9-8eb1-c25836ad5396.png)

codesandbox.io
![屏幕快照 2019-08-18 下午4 50 44](https://user-images.githubusercontent.com/29365693/63222275-55515100-c1d8-11e9-8eae-faf7fdd8ecb9.png)

**Comment by R4M80MrX** [comment]
![屏幕快照 2019-08-18 下午5 29 28](https://user-images.githubusercontent.com/29365693/63222710-c8a99180-c1dd-11e9-8b92-8ef7ee374b28.png)
// top: 0.1rem;
// bottom: 0.1rem;
// margin: 0.2rem;

**Comment by CompuIves** [comment]
Ahh, so that's it! Would you be interested in opening a PR to fix this? This is clearly unwanted behavior 😅 .

**Comment by R4M80MrX** [comment]
> Ahh, so that's it! Would you be interested in opening a PR to fix this? This is clearly unwanted behavior 😅 .

Of course, it's my pleasure.

**Comment by arthurdenner** [comment]
@R4M80MrX, since you've fixed the error (thank you for that), can you close this issue, please?
