### ISSUE TITLE
bug: Codesandbox.io + WebUSB = 💔

### ISSUE THREAD

**Issue by keepkeyjon** [codesandbox/codesandbox-client#2304]
# 🐛 bug report

## Description of the problem

Inside Codesandbox examples, WebUSB `requestDevice` doesn't open the device picker as it should, and the promise it returns never resolves. This means you can't talk to WebUSB devices from Codesandbox.

## How has this issue affected you? What are you trying to accomplish?

I'd love to write some simple sandbox demos of our cross-vendor hardware wallet support library: https://github.com/shapeshift/hdwallet, but not being able to talk to WebUSB devices puts a real damper on the usefulness of anything built in against this.

### Link to sandbox: https://codesandbox.io/s/new-cache-99vis?fontsize=14

Clicking on the button should open a device picker similar to this:

![image](https://user-images.githubusercontent.com/35975617/63229939-490ec900-c1c3-11e9-99aa-4241463e3936.png)

To repro that, and check that WebUSB is actually working, open up the browser console in Chrome and enter:

```
window.navigator.usb.requestDevice({ filters: [{ vendorId: 0x2b24, productId: 0x0002 }] })
```

Note that you will need a browser that supports WebUSB in order to try this out. Current best options are Chrome and Brave. The device picker should open, even if you don't have a KeepKey connected. It'll just be empty in that case.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | https://codesandbox.io/s/new-cache-99vis?fontsize=14 |
| Browser          | Chrome Version 75.0.3770.142 |
| Operating System | macOS High Sierra 10.13.6 |

**Comment by lbogdan** [comment]
Hey @keepkeyjon ,

From https://developers.google.com/web/updates/2016/03/access-usb-devices-on-the-web , it seems like the `iframe` in which we load the preview needs an `allow="usb"` attribute.

Nevertheless, it should work if you open the preview in a new window (either by clicking on the "Open In New Window" button - this will keep the preview synced to the code, or by loading https://99vis.csb.app/ in a new tab).

**Comment by keepkeyjon** [comment]
> open the preview in a new window

Oh, fantasic! That works great. Thanks for the suggestion!

**Comment by CompuIves** [comment]
If someone wants to pick up `allow="usb"` adding in the iframe that would be greatly appreciated! The component with the iframe is `Preview`.

**Comment by keepkeyjon** [comment]
I wouldn't mind taking a crack at it.

**Comment by keepkeyjon** [comment]
https://github.com/codesandbox/codesandbox-client/pull/2309
