### ISSUE TITLE
Why is Sandpack not ready for use?

### ISSUE THREAD

**Issue by carloslfu** [codesandbox/codesandbox-client#2306]
# ❔ Question

Hi. I want to integrate Sandpack into a project I'm working on but I found the "DON'T USE THIS YET!" advice in the README. So, I want to know if there is a roadmap or something I would help in to make Sandpack production-ready. Also, is it used in Codesanbox?

**Comment by MichaelDeBoey** [comment]
CC @CompuIves

**Comment by carloslfu** [comment]
For anyone with stability concerns, I think this package is stable enough. Here some context:
- It's used by Gitlab in production: https://twitter.com/compuives/status/1032697802676027392?lang=en.
- It's used by CodeSandbox in production.
