### ISSUE TITLE
Jest Tests Fail to Run on Codesandboxes Opened with Github Import Wizard

### ISSUE THREAD

**Issue by Cooperbuilt** [codesandbox/codesandbox-client#2311]
# 🐛 bug report
Codesandboxes opened with the Github Import Wizard do not run included Jest tests - the tests hang / never show in the "tests" panel. 

## Description of the problem
The opened codesandbox does not run tests as expected. As of a few days ago, this functionality worked fine. The expected behavior is that these tests run and fail, and users fix the tests as part of our educational site [Awesome Learning](https://wayfair.github.io/awesome-learning/). 

One potentially related or unrelated issue is the console error of `test is not defined`, although this has been a consistent issue for a month or more and the tests worked as expected. Only today did our users start complaining of a broken test environment. 

## How has this issue affected you? What are you trying to accomplish?
We built our entire education platform on codesandbox. Currently none of our users can use our app at all because all of our exercises rely on tests for users to know if they solved the exercises or not. 

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/github/wayfair/awesome-learning-exercises/tree/master/array-methods/foreach?fontsize=14&previewwindow=tests

### Your Environment
Tested in safari, chrome, and firefox.

**Comment by SheaBelsky** [comment]
Relevant console error from the browser console:

![Screen Shot 2019-08-19 at 5 17 18 PM](https://user-images.githubusercontent.com/15164473/63300027-38368400-c2a5-11e9-95b5-5ab0bff2e58a.png)

**Comment by SheaBelsky** [comment]
It seems to be crashing in this line:

https://github.com/codesandbox/codesandbox-client/blob/a3852efc177bc7f2f046603091f73bd7e8c35b6a/packages/app/src/app/components/Preview/DevTools/Tests/index.tsx#L386

**Comment by sag1v** [comment]
I have the same issue but not related to github import.

**Comment by CompuIves** [comment]
A fix is underway!

**Comment by Cooperbuilt** [comment]
Thank you! Let me know if there is something I can do to assist.

**Comment by Cooperbuilt** [comment]
Hey @CompuIves, any idea of a timeline on this? Our platform is currently borked by this and I'd like to give an idea to our users when they may be able to use it again. If not, no worries! Thank you for the work you do and this amazing tool!

**Comment by sag1v** [comment]
Seems like its already fixed...

**Comment by SheaBelsky** [comment]
@sag1v I can confirm that running the unit tests from the link in the original post work again.

@Cooperbuilt Can you confirm they work for you too?

**Comment by SaraVieira** [comment]
@Cooperbuilt Can you confirm it's fixed so the issue can be closed? Thank you :)

**Comment by Cooperbuilt** [comment]
Looks good! Closing.
