### ISSUE TITLE
Auto-forking sandbox leaves iframe on http://vanilla.csb.app

### ISSUE THREAD

**Issue by djD-REK** [codesandbox/codesandbox-client#2312]
# 🐛 bug report

## Description of the problem
I started typing after creating a vanilla sandbox, I was wondering why I wasn't seeing my code changes reflected, and then I realized the iframe was still on http://vanilla.csb.app and not the correct sandbox URL.

## How has this issue affected you? What are you trying to accomplish?
When I forked a new sandbox automatically by just editing the code, with the standard view (code and iframe preview both on), it did not seem to refresh the iframe link.

### Link to sandbox: [link]() (optional)
Not that it matters but here https://codesandbox.io/s/sleepy-browser-70rs3

### Your Environment

```
| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1566231367-0f2424913
| Browser          | Mozilla Firefox Quantum 68.0.2 (64-bit)
| Operating System | Windows 7 SP1 (64-bit)
```

**Comment by CompuIves** [comment]
I believe I fixed this one recently! Thanks for opening the issue 😄
