### ISSUE TITLE
No link to log-in on mobile phone

### ISSUE THREAD

**Issue by djD-REK** [codesandbox/codesandbox-client#2313]
# 🐛 bug report

## Description of the problem
With a really small screen (i.e. cell phone size), the responsive display is wonderful and great and the website is practically usable!

(OK, the text editor bugs out a little on my keyboard and won't let me copy-paste, but I can at least type into it.)

BUT! There's no log-in button. It gets hidden when the window width is too small.

## How has this issue affected you? What are you trying to accomplish?
I was trying to write up and test a brief code demo for a Medium article while traveling. I ended up just borrowing a friend's laptop instead.

### Please assign to me! @djD-REK
This would be a great **first issue** for me, and I should be able to fix it within a week. Thanks!

I think a fail-safe fix would be to fix the responsive behavior for the top-right element but also add the Create Sandbox links to the page footer at the very bottom.

### Your Environment
```
| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1566231367-0f2424913
| Browser          | Mozilla Firefox Quantum 68.0.2 (64-bit)
| Operating System | Windows 7 SP1 (64-bit)
```

### Screenshots
Normal: Login
![image](https://user-images.githubusercontent.com/53202242/63302540-4edfd980-c2ab-11e9-9c84-4dd257c2eef5.png)

Small: No Login
![image](https://user-images.githubusercontent.com/53202242/63302855-34f2c680-c2ac-11e9-8660-1e173b9d221e.png)

Mobile: No Login
![image](https://user-images.githubusercontent.com/53202242/63302882-463bd300-c2ac-11e9-9226-abc88507ea54.png)

### Is there a workaround?
If you get to the Create Sandbox section, you may be able to login, maybe:
Normal / Small: Login
![image](https://user-images.githubusercontent.com/53202242/63302607-89497680-c2ab-11e9-94ed-5a867d0675a9.png)

Mobile: No login
![image](https://user-images.githubusercontent.com/53202242/63302814-1db3d900-c2ac-11e9-8ad5-d6504af7ac07.png)

**Comment by SaraVieira** [comment]
Hey!

Thank you so much for wanting to fix this issue. I have assigned you the issue.

Let me know if you need any help :)
