### ISSUE TITLE
Is Jest run in the browser or server?

### ISSUE THREAD

**Issue by JohnAllen** [codesandbox/codesandbox-client#2320]
Does Codesandbox run tests on the client or server?

I see that it was run in the browser early last year.  Is it still the case?

**Comment by djD-REK** [comment]
I heard on a podcast about Code Sandbox that almost everything is run
client-side, which is why the project has been able to scale, but I'm not
sure 100%

Best regards,
Derek

Derek R. Austin, PT, DPT, MS, BCTMB, CSCS

Join me on LinkedIn: https://www.linkedin.com/in/Derek-Austin

**Comment by CompuIves** [comment]
Yep! That's the case, unless you run a container sandbox (codesandbox.io/s/node), it's run in the browser.
