### ISSUE TITLE
Stop chrome back/forward two finger swipe

### ISSUE THREAD

**Issue by dchebakov** [codesandbox/codesandbox-client#2321]
# 🌈 Chrome swipes
Please, disable the two-finger swipe that causes Chrome going back or forward. This greatly complicates the writing of code on narrow monitors.

The most easies solution is add this styles to `body`:
```
body {
  overscroll-behavior-x: none;
}
```

**Comment by CompuIves** [comment]
Woow, how have I never heard of this? Would be good to add this CSS, does someone want to take this?

**Comment by JayBee007** [comment]
Just opened a pull request, @CompuIves I add the above css rule only to the app pacakge's index.html, are there any other places where it is also needed? Thanks!
