### ISSUE TITLE
Does codesandbox still use bundlephobia?

### ISSUE THREAD

**Issue by pastelsky** [codesandbox/codesandbox-client#2326]
# ❔ Question

👋 I'm the author of bundlephobia. Lovely work on codesandbox. I noticed that when I open a codesandbox project, a bunch of requests get fired to bundlephobia – one for each of the dependencies. 

However, I couldn't see the size data being used anywhere in the UI. Did I miss something?

Size calls to bundlephobia can be cheap / expensive depending on whether the package in question is present in bundlephobia's cache. If the data isn't being used, would it be possible to remove the API calls that go out to bundlephobia? If it is being used, it would be awesome if codesandbox can throttle concurrency of these calls, and / or make it when a higher intent is shown by the user to see the size data.

**Comment by pastelsky** [comment]
Ah I see here's how it gets used -

https://github.com/codesandbox/codesandbox-client/pull/1197

@SaraVieira Would it be possible to fetch the sizes lazily once a user expands to see more information?

**Comment by SaraVieira** [comment]
Hey!

That's what I am building now! Sorry, this was when I was starting at codesandbox

**Comment by pastelsky** [comment]
Thanks!
