### ISSUE TITLE
Parcel + JSX

### ISSUE THREAD

**Issue by eirikb** [codesandbox/codesandbox-client#2327]
It would be great with support for jsx in parcel template (vanilla). I believe parcel only needs to be upgraded to a newer version and it should work out of the box.

Working demo:
```bash
echo '<script src="app.jsx"></script>' > index.html
echo 'console.log(<div/>)' > app.jsx
npx parcel index.html
```
^ Parcel version `1.12.3`

**Comment by CompuIves** [comment]
Hey! I believe this should work already: https://codesandbox.io/s/react-in-parcel-kscul.

**Comment by eirikb** [comment]
Hi. Your codesandbox works, but if I try this myself manually (by creating a vanilla project) it won't transpile JSX code. I don't use React, I'm going to use another JSX library not related to React. I tried adding .babelrc identical to yours.

**Comment by eirikb** [comment]
Sorry, I was missing `react` preset from `.babelrc`. Rest of the babel config is automatically populated. Thanks!
