### ISSUE TITLE
Github export limitation "64 characters" in title

### ISSUE THREAD

**Issue by djD-REK** [codesandbox/codesandbox-client#2330]
*** Please assign to me ***
Please assign this issue to me, I think I can find the error and at least add a descriptive warning.  The bug can't be fixed (as it is a Github limitation), but users should know how to fix it.

# 🐛 bug report
I kept not being able to figure out why my forked codesandboxes wouldn't let me export, and I would get a pop-up saying "_ must be less than 64 characters" -- and there's no information as to what is the problem.  I thought it was the repository name, but it turns out it's the title.

## Description of the problem
You can't export a codesandbox to Github if the title of the sandbox exceeds 64 characters.  This is a Github limitation, but because the error message is unclear I've had it happen to me a lot.

## How has this issue affected you? What are you trying to accomplish?
I write overly descriptive 

Basically, the title of the code sandbox is smushed and hyphenated, assumedly into the .json file.
"3 Card Tarot Reading by Dr. Derek Austin 🥳 (Github master)" becomes
"3-card-tarot-reading-by-dr-derek-austin-github-master"

And this has to be less than 64 characters.  If we throw the 64 characters error, we should say it's the title. (Easy fix)

AND/OR 

Put in a character counter and limit the title input to 64 characters for sandboxes linked to Github (Harder fix)

### Link to sandbox: [link]() (optional)
I got this one working by shortening the title:
https://codesandbox.io/s/3-card-tarot-reading-by-dr-derek-austin-github-master-nejui

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by CompuIves** [comment]
Good one! I'll make sure to raise the limit.

**Comment by CompuIves** [comment]
I raised the limit, will deploy it later today!

**Comment by arthurdenner** [comment]
@CompuIves, I saw that the limit was increased to 128 characters but I noticed that the error message doesn't say _what_ should be limited to 128 characters and the error key is wrong too.

`{"errors":{"alias":["should be at most 128 character(s)"]}}`

I think that the error key should be `title` instead of `alias` and the message could contain "title should be at most 128 character(s)" or something like that.
