### ISSUE TITLE
Can't delete file 

### ISSUE THREAD

**Issue by geeogi** [codesandbox/codesandbox-client#2331]
# 🐛 bug report

## Description of the problem

Unable to delete files. No action occurs when clicking "delete" and the modal will not close.  

### Your Environment

Browser: Chrome, Safari

![cant delete](https://user-images.githubusercontent.com/35661160/63804744-bdf2a900-c90f-11e9-9119-b22d35304d47.gif)

**Comment by akoskm** [comment]
Same thing happens for other files and directories as well.

**Comment by CalvinWalzel** [comment]
I'm experiencing this as well.

**Comment by CompuIves** [comment]
I'm so sorry for the slow response on this. A bad combination of circumstances, I'll try to make sure that the chance of this happening will be lower.

**Comment by lbogdan** [comment]
Fixed in #2332 .
