### ISSUE TITLE
🌈 Clean "Add Dependency" popup description HTML

### ISSUE THREAD

**Issue by dance2die** [codesandbox/codesandbox-client#2334]
# 🌈 Feature

## What is this feature?

Extract Non-HTML content as the "Add Dependency" search popup.

Current behavior returns first `N` number of texts from README regardless whether it starts with an HTML content or not.

### Screenshot

Below shows the current behavior

![current behavior](https://user-images.githubusercontent.com/8465237/63900909-57818f80-c9d0-11e9-94d2-a1c05ba0c85c.png)

## How the feature should work?

Extract text content from HTML instead of using raw HTML.

## You have examples or an idea how it can be implemented?

Below is the beginning of [README](https://raw.githubusercontent.com/framer/motion/master/README.md) of `framer-motion` library searched in the screenshot above.

We could attempt to extract first non-HTML content, `Motion is an open source, production-ready library that's designed for all creative developers.` as a description because any decoded HTML would look like gibberish.

```markdown
<p align="center">
  <img src="https://user-images.githubusercontent.com/38039349/60953119-d3c6f300-a2fc-11e9-9596-4978e5d52180.png" width="176" height="170" alt="Framer Motion" />
</p>

<h3 align="center">
  An open source and production-ready motion<br>library for React on the web.
</h3>

<br>

<p align="center">
  <a href="https://www.npmjs.com/package/framer-motion" target="_blank">
    <img src="https://img.shields.io/npm/v/framer-motion.svg?style=flat-squar" />
  </a>
  <a href="https://www.npmjs.com/package/framer-motion" target="_blank">
  <img src="https://img.shields.io/npm/dm/framer-motion.svg?style=flat-square" />
  </a>
  <a href="http://twitter.com/framer" target="_blank">
  <img src="https://img.shields.io/twitter/follow/framer.svg?style=social&label=Follow"  />
  </a>
  <a href="https://spectrum.chat/framer" target="_blank">
  <img src="https://withspectrum.github.io/badge/badge.svg" />
  </a>
</p>

<br>

Motion is an open source, production-ready library that's designed for all creative developers.

It looks like this:
```

## Additional Info

Sandbox Version: PROD-1566993699-8a410f172
_Reported as a feature not a bug as it's an enhancement._

**Comment by CompuIves** [comment]
Hmm, this is a good one. It seems like the index uses the readme if it can't find a description for the package. I'm not sure how much information we get from the Algolia index to determine the rest of the README, we could try to use the alt maybe, but it would also make sense to me if the library would set a description for the library instead or we use nothing.

**Comment by dance2die** [comment]
It looks like Algolia doesn't sanitize HTML unfortunately.

> Algolia returns all data in your index as is

https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/in-depth/data-sanitization/#clean-your-user-search-input

Not sure if sanitizing in the user-land would be worth or not though.

**Comment by SaraVieira** [comment]
Hey!

I am gonna check if there is html and if so I will not show the description
