### ISSUE TITLE
为啥创建一个react项目，一开始有光标，可是页面点击一下，光标就没了，不可编辑了啊，是哪里有问题吗?很喜欢你们这个项目，希望看一下吧

### ISSUE THREAD

**Issue by weiweixuan** [codesandbox/codesandbox-client#2335]
# ❔ Question

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by MichaelDeBoey** [comment]
Title translation (via [Google Translate](https://translate.google.com/#view=home&op=translate&sl=auto&tl=en&text=%E4%B8%BA%E5%95%A5%E5%88%9B%E5%BB%BA%E4%B8%80%E4%B8%AAreact%E9%A1%B9%E7%9B%AE%EF%BC%8C%E4%B8%80%E5%BC%80%E5%A7%8B%E6%9C%89%E5%85%89%E6%A0%87%EF%BC%8C%E5%8F%AF%E6%98%AF%E9%A1%B5%E9%9D%A2%E7%82%B9%E5%87%BB%E4%B8%80%E4%B8%8B%EF%BC%8C%E5%85%89%E6%A0%87%E5%B0%B1%E6%B2%A1%E4%BA%86%EF%BC%8C%E4%B8%8D%E5%8F%AF%E7%BC%96%E8%BE%91%E4%BA%86%E5%95%8A%EF%BC%8C%E6%98%AF%E5%93%AA%E9%87%8C%E6%9C%89%E9%97%AE%E9%A2%98%E5%90%97%3F%E5%BE%88%E5%96%9C%E6%AC%A2%E4%BD%A0%E4%BB%AC%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%EF%BC%8C%E5%B8%8C%E6%9C%9B%E7%9C%8B%E4%B8%80%E4%B8%8B%E5%90%A7)):
> Create a react project for 啥, there is a cursor at the beginning, but the page clicks, the cursor is gone, can't be edited, is there a problem? I like your project, I hope to see it.

**Comment by lbogdan** [comment]
Hey @weiweixuan ,

Can you please try to describe what your problem is in English (we didn't quite understand what it is from the automatic translation), and also provide a sandbox where the problem occurs? Thanks!

**Comment by weiweixuan** [comment]
Thank you, I used the Chrome plugin myself, which made it impossible to edit in the framework. Thank you very much.

**Comment by muescha** [comment]
Which chrome plugin caused the error?

**Comment by weiweixuan** [comment]
Tampermonkey
this chrome plugin

**Comment by SaraVieira** [comment]
Hey!

I have Tampermonkey and everything seems to work fine, I am going to close this as we do not enough information to understand what is happening
