### ISSUE TITLE
Embedding a container needs an option to start with the terminal closed.

### ISSUE THREAD

**Issue by looeee** [codesandbox/codesandbox-client#2338]
Here's my embed code, for a Node container.

``` html    

<iframe class="codesandbox" src="https://codesandbox.io/embed/github/looeee/discoverthreejs_examples_v2/tree/master/?codemirror=1&hidenavigation=0&expanddevtools=0&view=preview&initialpath=%2Fviews%2Ffirst-steps%2Ffirst-scene%2Findex.html&module=%2Fviews%2Ffirst-steps%2Ffirst-scene%2Fjs%2Fapp.js"
    sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin"></iframe>

```

In particular, I've set these options:

* `moduleview=0`
* `expanddevtools=0`
* `view=preview`

I want as clean a view as possible. But the embed starts with the terminal open which takes up about 1/3 of the frame:

![embed](https://user-images.githubusercontent.com/5307958/63942051-228c4000-ca97-11e9-908e-a8cae8a4ccf8.png)

I've gone through the list of embed options, but it doesn't look like there are any related to the terminal. Have I missed one? 

Even better would be a way to hide the bottom bar completely. 

EDIT: I've switched back the above repo to use a static template so it doesn't demonstrate this issue anymore. However I'll leave this issue open as would still be a useful setting to add.

**Comment by siddharthkp** [comment]
Hi @looeee again! 

We've fixed this issue, now the console opens only when you ask it to open from settings or with `expanddevtools=1`

![Screenshot 2019-09-06 at 10 56 15 AM](https://user-images.githubusercontent.com/1863771/64415151-0f7c0000-d095-11e9-9fd9-eb853f6d29f0.png)

If you have any other feedback, please reach out to us! 😄

**Comment by looeee** [comment]
Hey, you guys rock! Thanks so much for the speedy fix :D

**Comment by siddharthkp** [comment]
And girls 😉
