### ISSUE TITLE
Request Entity Too Large when trying to access github changes

### ISSUE THREAD

**Issue by JoshGore** [codesandbox/codesandbox-client#2341]
# 🐛 bug report

## Description of the problem
I have forked my CRA repository on Github, code displays however when I click the  GitHub button I get a "Request Entity Too Large" error.  Similar to (closed) #1430.
## How has this issue affected you? What are you trying to accomplish?
Trying to edit my Typescript CRA app on sandbox and commit changes
### Link to sandbox: [link]() (optional)
[The sandbox](https://codesandbox.io/s/walk-the-yorke-client-ikrbl)
### Your Environment
Chrome on Windows 10

**Comment by danielvanc** [comment]
Hi @JoshGore are you still receiving this? I've just encounterd it on a project as well...

**Comment by JoshGore** [comment]
unsure sorry, ended up using a different service

**Comment by seanthaswan** [comment]
I am still experiencing this issue with a very basic create-react-app example repo. Any developments related to this error?

**Comment by garethx** [comment]
Please provide a link to the sandbox you're having problems with. Thanks.

**Comment by garethx** [comment]
Can you try it again? We've made some changes, which will hopefully have resolved this. Thanks.
