### ISSUE TITLE
Collapsible file tree in embeds

### ISSUE THREAD

**Issue by looeee** [codesandbox/codesandbox-client#2342]
# 🌈 Collapsible file tree in embeds

File trees in the embeds are fully expanded and cannot be collapsed. If you have more than 20 or so file it can be a bit noisy. This is an issue for me since I'm using the embeds in a tutorial setting, and I want them to be a clean as possible. 

![image](https://user-images.githubusercontent.com/5307958/64003614-cb3dac80-cb36-11e9-8489-d71a36dfa651.png)

Add some embed options like "startcollapsed=1" and make the file tree work like a normal file tree.

**Comment by oskarabc** [comment]
We started work on an embed redesign recently and we are considering a solution of these sorts. Will keep this thread updated as we are closing in on release.

**Comment by siddharthkp** [comment]
Hi @looeee! 

We pushed an update, now embeds only open the active folder (the one that contains the open file)

![Screenshot 2019-09-06 at 10 27 50 AM](https://user-images.githubusercontent.com/1863771/64413064-1d2f8680-d091-11e9-8e78-5ced1580f3a2.png)

ℹ️ Tip: You can also change which file (and it's folder) should be open by default in embed settings ✨ 

If you have any other feedback, you know where to find us 😄
