### ISSUE TITLE
Cloudflare message: Worker exceeded resource limits

### ISSUE THREAD

**Issue by looeee** [codesandbox/codesandbox-client#2343]
# 🐛 bug report

Trying to load this embed, which was working a few minutes ago: 

https://codesandbox.io/embed/discoverthreejs-examples-v2-k10cq

And I see this error message:

![cloudflare error](https://user-images.githubusercontent.com/5307958/64009421-0396b800-cb42-11e9-83ac-b77219531a46.jpg)

Is that something to do with my sandbox, or is it a sitewide issue you guys are having?

**Comment by CompuIves** [comment]
Sorry for this! We now only put the sandbox on the window if it's small enough. A fix should be live!
