### ISSUE TITLE
Lost styles when importing a bootstrap template

### ISSUE THREAD

**Issue by jacobhamilton12** [codesandbox/codesandbox-client#2360]
Tried to import from https://github.com/jacobhamilton12/website and it does not load any of the styles.

**Comment by lbogdan** [comment]
Hey @jacobhamilton12 ,

Unfortunately, that's not how client sandboxes and static assets work, so you can either restructure everything in maybe a `vanilla` sandbox, which should be compatible with the `parcel` bundler), or you can run it in a server sandbox, by adding `sandbox.config.json` to your repo root like I did [here](https://github.com/lbogdan/website-1/blob/master/sandbox.config.json), and you can see the result sandbox here: https://codesandbox.io/s/github/lbogdan/website-1 .

**Comment by SaraVieira** [comment]
Closed for lack of activity
