### ISSUE TITLE
setImmediate has a different signature

### ISSUE THREAD

**Issue by RubenVerborgh** [codesandbox/codesandbox-client#2368]
# 🐛 bug report

## Description of the problem

`setImmediate` in Node has a signature in which arguments can be provided for the callback: https://nodejs.org/api/timers.html#timers_setimmediate_callback_args
CoseSandbox ignores those arguments.

## How has this issue affected you? What are you trying to accomplish?

use `setImmediate` with > 1 parameter

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest
| Browser          | all
| Operating System | all

The root cause is in the implementation here: https://github.com/codesandbox/codesandbox-client/blob/65ebde961865b9444087bd95d119387914317c92/standalone-packages/codesandbox-browserfs/src/generic/setImmediate.ts

**Comment by RubenVerborgh** [comment]
I gave it a go myself in https://github.com/codesandbox/codesandbox-client/pull/3317

**Comment by SaraVieira** [comment]
Closing as you seem to have fixed the issue

Thank you so much!
