### ISSUE TITLE
is jest available in sandbox containers/server? 

### ISSUE THREAD

**Issue by Nilegfx** [codesandbox/codesandbox-client#2369]
# ❔ sandbox containers/server?

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by garethx** [comment]
The Jest integration, which auto-detects your tests only works in client-side sandboxes. For containers, Jest will still work (you're able to use whichever test framework you want) but you'd need to set it up yourself as you normally would. I'll update our docs to make this clear.
