### ISSUE TITLE
React Apps -- no more preview on save?

### ISSUE THREAD

**Issue by johncokos** [codesandbox/codesandbox-client#2373]
# 🐛 bug report

## Description of the problem

The preview panel no longer seems to update on save.  I've disabled the preview on edit and instant preview options, but now I seem to have to press the refresh button in the preview browser manually.

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/suspicious-kowalevski-lgyv1

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 
| Browser          | Chrome |
| Operating System | Mac Mojave

**Comment by CompuIves** [comment]
Sorry for this! Just put a fix on master, will deploy in 2 hours.

**Comment by NawarA** [comment]
@CompuIves Is Codesandbox supposed to update the preview window when the user `saves` in their window?
