### ISSUE TITLE
"failed to save" - Everything's broken

### ISSUE THREAD

**Issue by chasebank** [codesandbox/codesandbox-client#2374]
# 🐛 bug report
Sorry for the ambiguous issue title, but I've gotten so many errors in this project that I really don't know what to hone in on.

Everything was working fine, and then it suddenly wasn't.

The current state of things is I can't save or delete any files.

`Failed to save 'package.json': Cannot read property 'updateFiles' of undefined`

I also can't restart the server or sandbox. Both buttons are disabled.

This started with an ambiguous 502 error, seemingly at random. There was an error, `Error: EIO: i/o error, open '/sandbox/package.json'` which I can't reproduce now.

Now I'm stuck with "A sandbox error occurred, you can refresh the page to restart the container." Refreshing the page unsurprisngly does nothing.

https://codesandbox.io/s/nuxt-markdown-blog-starter-g83c5

**Comment by lbogdan** [comment]
Hey @chasebank ,

There was indeed an issue with that sandbox's persistent storage. Can you please try again now?

**Comment by chasebank** [comment]
@lbogdan Thanks for checking it out, looks like everything's working now.

Is there anything specific that I did to break it? Or is there something I can do in the future to fix it myself?

**Comment by boraoren** [comment]
Is there anything specific that I did to break it? Or is there something I can do in the future to fix it myself?

**Comment by chasebank** [comment]
@lbogdan  I'm getting this again, with the same project. I don't even think I changed anything to cause it. It was working last night, but now when I pull it up, the server is failing to start.

"A sandbox error occurred, you can refresh the page to restart the container."

The restart server and sandbox buttons are disabled, and refreshing the page results in the same error.

If I try saving a file, I get "Failed to save '...': Cannot read property 'updateFiles' of undefined"
