### ISSUE TITLE
Structure needs cleaning

### ISSUE THREAD

**Issue by paulbrie** [codesandbox/codesandbox-client#2381]
# 🐛 Structure needs cleaning (Next container)

## Description of the problem
I deleted some files from the `static/` folder (next project) and it crashed my instance

## How has this issue affected you? What are you trying to accomplish?
It crashed the instance (that's when in happened, not sure if is necessarily related) and I can't recover get or back to a working state.
![image](https://user-images.githubusercontent.com/3997538/64266933-29ef9580-cf3e-11e9-8bfe-6b16d7c94dcf.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1567437574-dd109d005
| Browser          | Chrome
| Operating System | Mac

**Comment by paulbrie** [comment]
As a workaround, I forked the sandbox to get a clean start.

**Comment by lbogdan** [comment]
Yeah, unfortunately this happens once in a while, where a sandbox's persistent storage gets corrupted and the storage volume needs to be deleted and re-created (which is something I can only do manually at the moment).
_Notice that doesn't influence sandbox's contents, as that is stored in the API, too._

I recreated the volume, it should work now (although you probably worked in the fork in the meanwhile, in which case you can remove it).
