### ISSUE TITLE
Git Commit Error 422 - Unprocessable Entity

### ISSUE THREAD

**Issue by ianfabs** [codesandbox/codesandbox-client#2383]
# 🐛 bug report

## Description of the problem
When I attempt to commit changes, I get a 404 error toast. Upon further inspection, the actual error is a 422 error returned by a POST to [this endpoint](https://codesandbox.io/api/v1/sandboxes/rxl6x/git/commit), with a request body of: 
```json
{
"id": "rxl6x",
"message": "Fixed bug"
[, "description": "**optional description**"]
}
```
note: the square brackets around the description are to emphasize that it is optional

## How has this issue affected you? What are you trying to accomplish?
This issue has prevented me from working on a project

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Current |
| Browser          |  Chrome  |
| Operating System |  Windows 10 (Virtual Workstation) |

**Comment by letsbelopez** [comment]
I'm also getting a 422 error after forking a Sandbox and trying to see the changed files to I can make a PR on my own repo. This is happening in the Github tab.

The endpoint: https://codesandbox.io/api/v1/sandboxes/ghrrj/git/diff

This error message: `{"errors":{"detail":["Request failed with status code 422"]}}`

**Comment by ianfabs** [comment]
I am still experiencing this issue
