### ISSUE TITLE
Next.js box is crashing when changing .js extentsion to .tsx

### ISSUE THREAD

**Issue by paulbrie** [codesandbox/codesandbox-client#2387]
# 🐛 bug report

## Description of the problem
Next.js box is crashing when changing .js extentsion to .tsx.

## How has this issue affected you? What are you trying to accomplish?
The box is in a broken state and does not recover. I have to restart the server.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1567608482-3373eb24f
| Browser          | Chrome
| Operating System | Mac

**Comment by lbogdan** [comment]
Hey @paulbrie ,

Can you please copy-paste / screenshot the error / crash, please?

**Comment by paulbrie** [comment]
I think that what happens is that the instance is crashing because the hot reload does not find anymore the file (even though the main name is the same). 

I don't have a screenshot but basically React is complaining of not finding a module.

**Comment by lbogdan** [comment]
Oh, I see. I don't think there's much we can do, as you'd have the same problem running locally, too and would need to restart the dev server.

What you can do in CodeSandbox when the dev server gets in an inconsistent state you can either restart it by clicking "Restart Sandbox", which is faster, or restart the container using "Restart Server" (I guess we could work a bit on wording here 🙂 ).

**Comment by paulbrie** [comment]
![image](https://user-images.githubusercontent.com/3997538/64342335-f589e100-cff2-11e9-9858-df39b35e99f2.png)

**Comment by paulbrie** [comment]
Yes, restart server does it. ;)
