### ISSUE TITLE
A sandbox error occurred, you can refresh the page to restart the container.

### ISSUE THREAD

**Issue by boraoren** [codesandbox/codesandbox-client#2389]
# 🐛 bug report

## Description of the problem
When I try to open Sandbox that is opening recursively in its browser

## How has this issue affected you? What are you trying to accomplish?
It doesn't work. And I see tooltip 
**Container Error
Error fetching sandbox.**

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/3ecwz

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | I couldn't find|
| Browser          | Version 76.0.3809.132 (Official Build) (64-bit)|
| Operating System | MacOs High Sierra|

**Comment by lbogdan** [comment]
Hey @boraoren ,

I can't access that sandbox, is it a private one? If so, we don't yet support private server sandboxes.

**Comment by boraoren** [comment]
Hello @lbogdan I changed it to unlisted.

**Comment by boraoren** [comment]
Hello @lbogdan I don't know how but after restart browser to get a new version of codesandbox, it is fixed. Now my sandbox is working.

**Comment by lbogdan** [comment]
Nice! If everything's working as expected, can you please close the issue? Thanks!
