### ISSUE TITLE
Container: How to download all files in sandbox?

### ISSUE THREAD

**Issue by jsejcksn** [codesandbox/codesandbox-client#2399]
For example, I recently experimented with [Realm database](https://realm.io/products/realm-database): I cannot see the database file in the file explorer, and when I download a zip archive of the sandbox, that file is not included. However, when I `ls -al` in the terminal, I can see the file of interest.

**How can I download all files in a sandbox?**

> I am purposefully not linking to the sandbox of interest because I intend to delete it and don't want to provide a dead example link for anyone who might view this issue in the future.

**Comment by jsejcksn** [comment]
@lbogdan Thanks for responding. The file in question is not ignored and is reported to be `4.0K` using the command `ls -alFh`. Does that mean that 4 KB exceeds the size limit for synchronization?

**Comment by jsejcksn** [comment]
Still looking for clarity on what "a certain size threshold" is. Thanks!

**Comment by jsejcksn** [comment]
Not stale. Still waiting for a response from @lbogdan

**Comment by lbogdan** [comment]
Hey @jsejcksn , the sync thresholds are 512kB for text and 2MB for binary files. If you have a sandbox in which the sync is not working, give me the URL and I can take a look at the logs to see what's happening.

**Comment by jsejcksn** [comment]
@lbogdan Thanks. This is related to #2400, and I'm also still awaiting a response from you there. You asked me to message you via Spectrum, and I did. You should find a message from me (same username as here on GitHub) in your inbox from 2019/09/14 and again on 2019/09/25. All the details are contained there.

**Comment by jsejcksn** [comment]
@lbogdan Thanks for responding.

I don't see a `.gitconfig` file in the sandbox filesystem. The exported sandbox still does not contain all the files (even though they are within the size threshold).

```
/sandbox$ ls -alFh
total 128K
drwxr-xr-x   5 sandbox sandbox  167 Sep  4 13:20 ./
drwxr-xr-x   1 sandbox sandbox 4.0K Sep  4 13:44 ../
-rw-r--r--   1 sandbox sandbox 4.0K Sep  4 13:20 blog.realm
-rw-r--r--   1 sandbox sandbox 1.5K Sep  4 13:45 blog.realm.lock
drwxr-xr-x   2 sandbox sandbox    6 Sep  4 13:20 blog.realm.management/
prw-------   1 sandbox sandbox    0 Sep  4 13:20 blog.realm.note|
drwxr-xr-x 366 sandbox sandbox  12K Sep  4 13:20 node_modules/
-rw-r--r--   1 sandbox sandbox  341 Sep  4 13:44 package.json
drwxr-xr-x   5 sandbox sandbox   88 Sep  4 13:20 src/
-rw-r--r--   1 sandbox sandbox  96K Sep  4 13:20 yarn.lock
```

None of the files beginning with `blog.realm` are included except for `blog.realm.lock`. Do you know why that might be?

**Comment by lbogdan** [comment]
Is this the same sandbox as in #2400 ? If not, can you email me the sandbox id?

**Comment by jsejcksn** [comment]
@lbogdan It is the same sandbox.

**Comment by lbogdan** [comment]
Did you try updating those files? We only sync when the files change, not retroactively.

**Comment by jsejcksn** [comment]
> Did you try updating those files?

Is there a way to "update" a file without modifying the binary contents of the file? (e.g. using `touch` in the console to update the modified date of the file). I don't want to modify the contents of the file before downloading it.

**Comment by lbogdan** [comment]
`touch` should do it, I think. I'm currently looking at that sandbox's logs, try to run it on one of the files and let's see if that works!

**Comment by jsejcksn** [comment]
> `touch` should do it, I think

That worked. Any insight about why they weren't synced to the sandbox previously?
