### ISSUE TITLE
Container sandbox: How to debug startup issue?

### ISSUE THREAD

**Issue by jsejcksn** [codesandbox/codesandbox-client#2400]
### Environment:

Node container sandbox

### Scenario:

In the _Server Control Panel_, when I select _Restart Server_, the status progresses to "Container is starting...", but then never changes after that, and the preview window progress indicator advances to "Installing Packages", but never moves beyond that point. I also notice that if I create a new interactive terminal tab during startup, I am never presented with an input prompt.

If I copy the file contents of the sandbox and upload them to a new Node sandbox, the new sandbox starts successfully.

How can I debug the cause of the startup hang in the scenario container?

I don't have a sandbox link to publicly provide.

**Comment by SaraVieira** [comment]
Hey!

This may be something with the docker server running your node code but there is a not a lot we can tell you to do besides forking the sandbox without a link :/

**Comment by jsejcksn** [comment]
@SaraVieira Is there a way to provide you with a link privately?

**Comment by jsejcksn** [comment]
@lbogdan Thanks—I just sent you a message.

**Comment by jsejcksn** [comment]
@lbogdan I sent you a message on 14 Sep and a follow up message on 25 Sep, but never heard back from you. Are you able to look at this now or should I consider it below the priority threshold and close it?

**Comment by lbogdan** [comment]
Hey @jsejcksn ,

Sorry for not getting back to you on this, somehow I didn't get any Spectrum notifications for your messages, I've just read them now. I manually restarted the sandbox on our side, and it looks like it's working. Can you confirm?

**Comment by jsejcksn** [comment]
@lbogdan The sandbox looks like it's started now. If there's any diagnostic information that you can provide to me via Spectrum which I could use to understand how to help myself in a future similar situation, I would like to see it. Thanks.

**Comment by lbogdan** [comment]
We don't (yet) expose any sort of debugging information for containers, please e-mail me at bogdan at codesandbox.io if you encounter further issues.
