### ISSUE TITLE
Can't get example React Native Progress Bar Example to run, dependencies won't load

### ISSUE THREAD

**Issue by faddah** [codesandbox/codesandbox-client#2411]
# 🐛 bug report

## Description of the problem

I opened CodeSandbox and opened the React Native Progress Bar Example (https://codesandbox.io/s/react-native-progress-bar-example-3gwxzlwx). When that opened the first time, it said that `react-native-web` dependency was missing, so I added it. It then tried loading again, and then kept

```
Could not fetch dependencies, please try again in a couple seconds: Something went wrong while packaging the dependency react-native@0.60.5: Command failed: mkdir -p /tmp/321981739 && cd /tmp/321981739 && HOME=/tmp node /var/task/node_modules/yarn/lib/cli add react-native@0.60.5 --ignore-scripts --no-lockfile --non-interactive --no-bin-links --ignore-engines --skip-integrity-check warning react-native > create-react-class > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2. warning " > react-native@0.60.5" has unmet peer dependency "react@16.8.6". warning "react-native > metro-react-native-babel-transformer@0.54.1" has unmet peer dependency "@babel/core@*". error An unexpected error occurred: "ENOSPC: no space left on device, copyfile '/tmp/.cache/yarn/v1/npm-hermesvm-0.1.1-bd1df92b4dc504e261c23df34864daf24b844d03/win64-bin/icudt64.dll' -> '/tmp/321981739/node_modules/hermesvm/win64-bin/icudt64.dll'".
```

...this asks you to wait a few minutes and re-load the app so the dependencies will then load properly. I waited and did this, several times. No matter what, the dependencies would not load and I'd get the same error. 

## How has this issue affected you? What are you trying to accomplish?

I can't get the dependencies for this React Native App example to load, ever.

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/react-native-progress-bar-example-3gwxzlwx

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | current version on web
| Browser          |  Google Chrome 77.0.3865.75 (Official Build) (64-bit)
| Operating System | Mac OS 10.14.6 with latest security update, on a Mid-2012 MacBook Air, 1.8 GHz Intel Core i5 processor, 4 GB of RAM

**Comment by Saeris** [comment]
I've seen errors like this before, and I think in Faddah's case it came up in an older sandbox. However it would be good to know why certain dependencies fail to load like this.

**Comment by itsezc** [comment]
I can confirm, I have the same issue only occurs when using the `react-native` package.

@Saeris any updates on this so far?

**Comment by siddharthkp** [comment]
For anyone who lands on this issue, this works now ✨ 

Here's a sandbox - https://codesandbox.io/s/react-native-web-progress-r03p4
