### ISSUE TITLE
Svelte V3 - auto-subscriptions don't work

### ISSUE THREAD

**Issue by tjinauyeung** [codesandbox/codesandbox-client#2415]
# 🐛 bug report

## Description of the problem

The app crashes while using the shorthand for subscribing to the store in Svelte V3. 

For context in Svelte V3 we can create store variables

```svelte
<script>
  import { onDestroy } from 'svelte'
  import { writable } from 'svelte/store'

  const count = writable(0) 

  let _count;
  count.subscribe(c => {
    _count = c;
  });

  onDestroy(() => count.unsubscribe());
</script>

<p>{count}</p>
```

The above mentioned code can be shortened to:

```svelte
<script>
  import { writable } from 'svelte/store'
  const count = writable(0)
</script>

<!-- `$` prefix will auto subscribe to the variable -->
<p>{$count}</p>
```

See https://svelte.dev/tutorial/auto-subscriptions

## How has this issue affected you? What are you trying to accomplish?

I'm working on a small [form library](https://github.com/tjinauyeung/svelte-forms-lib) for Svelte V3 and was looking to create the examples in Codesandbox. However it seems that this is not supported yet. It's returning `TypeError: store.subscribe is not a function`.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 
| Browser          | Chrome
| Operating System | MacOS

**Comment by ryanking1809** [comment]
This might be related. I'm having trouble with the spring animation subscriptions.
`Button.svelte` fails: https://codesandbox.io/s/happy-brook-cfe3c
But the same code has no issues in the Svelte REPL https://svelte.dev/repl/a6d5be50d777483c8051a424fbd45752?version=3.12.1
