### ISSUE TITLE
💥 Crash Report: I crashed when I tried to expand the console message Map object.

### ISSUE THREAD

**Issue by sinack** [codesandbox/codesandbox-client#2435]
<h1>💥 Crash Report</h1>

<h2>What were you trying to accomplish when the crash occurred?</h2>

> Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

<h3>Link to sandbox: [link](https://codesandbox.io/s/interesting-driscoll-tzrkt)</h3>

<h3>Crash Details</h3>

<details>
<summary>Environment</summary>

| Browser |  Version  | Operating System |
| ------- | --------- | ---------------- |
| chrome | 76.0.3809 | OS X 10.14.6           |

**Route:**
https://codesandbox.io/s/interesting-driscoll-tzrkt

</details>

<details>
<summary>Error Message</summary>

```bash
Error: Minified React error

**Comment by yeion7** [comment]
I've tracked the issue to react-inspector

https://github.com/storybookjs/react-inspector/pull/88
