### ISSUE TITLE
Unable to create template

### ISSUE THREAD

**Issue by gordonnl** [codesandbox/codesandbox-client#2452]
# 🐛 bug report

## Description of the problem
Clicking on 'Create Template' produces errors in the console and does not perform the task.
I think this may be part of a larger issue with my account, as I'm also unable to delete or edit existing templates, nor clear the trash. Prior to this I have been doing a number of creating templates, renaming, editing, deleting etc.

## How has this issue affected you? What are you trying to accomplish?
I am unable to create a template to be used in a series of sandboxes for an upcoming article.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome 77
| Operating System | MacOS 10.13.6

### Screenshot
![Screen Shot 2019-09-18 at 1 42 40 PM](https://user-images.githubusercontent.com/3521882/65146565-74801000-da1c-11e9-8bb9-e8f9798c850a.png)

**Comment by CompuIves** [comment]
Good find! We just merged a fix, should be live in 15-20min. Sorry for the inconvenience!

**Comment by gordonnl** [comment]
Thanks very much for your reactivity! Tested and confirmed 👍
