### ISSUE TITLE
Codesandbox is not in sync with GIt Repo

### ISSUE THREAD

**Issue by Harshu53** [codesandbox/codesandbox-client#2454]
# 🐛 bug report
I am expecting the git repo changes on codesandbox automatically but it is not happening.

## Description of the problem
I have committed some code from my local computer to git and when I tried to access the codesandbox attached with the same git repo, doesn't have the updated code. It is not in sync with the code which I have uploaded from my home computer.

## How has this issue affected you? What are you trying to accomplish?
I am not getting the updated code on codesandbox.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/crown-clothing-g6fhz

### Your Environment
WINDOWS 10

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | https://codesandbox.io/s/crown-clothing-g6fhz
| Browser          | CHROME 
| Operating System | WINDOWS 10

**Comment by lbogdan** [comment]
Hey @Harshu53 ,

Only the sandbox directly imported from the GitHub repo - which in your case is https://codesandbox.io/s/github/Harshu53/crown-clothing - is kept in sync with the repo, all other sandboxes forked from it - like the [one you provided](https://codesandbox.io/s/crown-clothing-g6fhz)] - are not. You can think of a forked sandbox as a git branch, it doesn't automatically sync to the branch it was created from.

**Comment by lbogdan** [comment]
You can read more about how the GitHub integration works in CodeSandbox here: https://codesandbox.io/docs/git .

**Comment by Harshu53** [comment]
@lbogdan Thanks for the information but I can't find [https://codesandbox.io/s/github/Harshu53/crown-clothing](https://codesandbox.io/s/github/Harshu53/crown-clothing) into my code sandbox listing, Why so ?

**Comment by lbogdan** [comment]
Because it's technically not your sandbox, you can think of it as "owned" by GitHub, as it will change every time the repo changes.

**Comment by Harshu53** [comment]
Great! Thank you
