### ISSUE TITLE
Cannot unfreeze a template

### ISSUE THREAD

**Issue by davidsavoie1** [codesandbox/codesandbox-client#2468]
# 🐛 bug report

## Description of the problem
I create a custom template from a project, but then cannot unfreeze it to make some changes from the *Template Info* menu. The unfreeze button doesn't do anything and the console prompts an error:
```
Uncaught TypeError: r is not a function
    at onClick (Frozen.tsx:36)
```
If I create a project from the template and try to save, I get a modal asking me to unfreeze of clone. If I unfreeze from there, it works.

## How has this issue affected you? What are you trying to accomplish?
It makes it difficult and unintuitive to work with custom templates.

### Link to sandbox: [link]() (optional)
[Template](https://codesandbox.io/s/baseproject-o4ry72ox9y)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1568892529-f7854c1d2 (I guess this is the version)
| Browser          | Chrome 76.0.3809.132 64-bits
| Operating System | Windows

**Comment by arthurdenner** [comment]
@davidsavoie1, I noticed that the linked sandbox is unavailable. Can you confirm if this is still happening? I couldn't reproduce it. If it is, could you provide a new sandbox? If it's not, could you close the issue, please?

**Comment by davidsavoie1** [comment]
Oh! Sorry about that! Nope, everything seems to be working fine now. Thanks a lot for this awesome tool!
