### ISSUE TITLE
Add a "Stop Container" button.

### ISSUE THREAD

**Issue by NullVoxPopuli** [codesandbox/codesandbox-client#2476]
# 🌈 Feature

I've been running in to a plethora of bugs related to the containers, and would love to be able to stop containers, to put them in to whatever state they get in to when no one looks at them for a while. 
This is to help me debug, and figure out exact reproduction steps.

It could go right next to the restart sandbox / restart server buttons

**Comment by lbogdan** [comment]
Hey @NullVoxPopuli ,

As the "Restart Server" does exactly this - it first stops the container, and then start it again, I find having a "Stop" button a bit redundant.
