### ISSUE TITLE
Can't restart container if there are no open ports detected

### ISSUE THREAD

**Issue by NullVoxPopuli** [codesandbox/codesandbox-client#2478]
# 🐛 bug report

## Description of the problem
![image](https://user-images.githubusercontent.com/199018/65345123-85a95800-dba7-11e9-888f-8039d21dc77b.png)

If I did something to crash the web dev server, I should still be able to restart things.

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1568987124-9eefb01c2
| Browser          |
| Operating System |

**Comment by lbogdan** [comment]
Closing this, as I can't replicate, and it was most probably fixed with the multiple ports update, when we completely decoupled the container started status from the port(s) being open.
