### ISSUE TITLE
A lot of error messages after not using codesandbox for some time

### ISSUE THREAD

**Issue by stnwk** [codesandbox/codesandbox-client#2481]
Hi! :)

Everytime on every browser I come to codesandbox.io after some time not using it, this is my experience of the first screen:

![image](https://user-images.githubusercontent.com/2981250/65352327-aa72ef00-dbea-11e9-929d-75c22955b049.png)

Then I reload and everything is fine again - can you make this experience nicer please?

Thanks :)

**Comment by garethx** [comment]
Does this happen when you visit the homepage at codesandbox.io? Or are you landing on a project or dashboard? Thanks

**Comment by stnwk** [comment]
Happens on Dashboard :)

**Comment by CompuIves** [comment]
Hmm, we might have fixed this already in a newer update, but it still needs to be installed here 😅. I remember fixing the auth error, so I think we can close this one and open again if it still happens.
