### ISSUE TITLE
File hasn't been transpiled yet error.

### ISSUE THREAD

**Issue by blitz-research** [codesandbox/codesandbox-client#2488]
My project in codesandbox has started giving me this mysterious error:
```
[Vue warn]: Error in mounted hook: "Error: /src/assets/Duck.glb hasn't been transpiled yet."

value@https://codesandbox.io/static/js/sandbox.a28300af.js:1:160858
```
The project uses vue.js and three.js and is supposed to just load a GLB 3d model. It was working fine this morning but then just started giving me this error and failing to load the model.

A simple version of the project is here:
https://c5oon.csb.app/

**Comment by blitz-research** [comment]
I think I've come up with a fix for this (or discovered the right way to do it!). I just needed to add a require("/src/assets/Duck.glb") to the main <script> block.

I'm new to all this so I'm not really sure what require actually does, but it's something to do with 'vue' I think as I have seen raw .js examples that just load data directly from file.

Is there a way I don't have 'require' files like this? It's a bit of a pain, and since I'm not doinmg any cross-site stuff it should be safe to just load my own data shouldn't it?

Please feel to close this issue though I've at least got something to go on now.

**Comment by CompuIves** [comment]
Great to see it resolved! I'm closing this one now.

**Comment by boyet007** [comment]
any solve this trouble???

**Comment by bhomaidan1990** [comment]
> @boyet007 - The fix is above :)

I have the same problem even after using `require`, here is my [codesandbox](https://codesandbox.io/s/draggablelist-t6mmq7?file=/src/components/PlanLego.vue) to reproduce the problem.

**Comment by tripolskypetr** [comment]
Still not solved. I am getting that problem on my mobile phone when trying to open [this codesandbox](https://codesandbox.io/s/short-content-asynccomponent-mfqisi?file=/src/pages/GoodCode/GoodCode.tsx)
