### ISSUE TITLE
I18n support

### ISSUE THREAD

**Issue by CompuIves** [codesandbox/codesandbox-client#25]
CodeSandbox is used by a lot of users in China and Russia, I think it'll be very valuable to have an i18n system in place that people could contribute to.

This will make CodeSandbox much more accessible.

Thinks that need to happen:

- [ ] Change build system to use [i18n-next](https://github.com/i18next/react-i18next/)
- [ ] Add a world icon to the header with a dropdown to select language, store preference in `localStorage` for now using preferences reducer
- [ ] Move all text to `t()` calls
- [ ] Move existing text to `en.json`

**Comment by Arthelon** [comment]
I've previously used react-intl (FormatJS) for as an i18n library and transifex for managing translations (free for OSS). React-intl is more popular at the moment and has better in-built formatting but it's great that i18n-next comes with its own compatible translation management system.

I'd love to give this a try!

**Comment by Arthelon** [comment]
Their docs are also much nicer! This [essentials section](https://www.i18next.com/essentials.html) is quite neat.

**Comment by CompuIves** [comment]
That would be really awesome @Arthelon! This is a major feature and would benefit a lot for CodeSandbox.

I propose that we first store the translations in the repo as json files, because most developers that will translate already know github and so the barrier is lower to contribute in translations. 

I'm open to any suggestion though, let me know what you think or if you have any questions!

**Comment by haraldur12** [comment]
Hey guys, I would love to help you out with i18n as well. Wouldn't it be good to first strip all the text from the code and then use a localisation service that offers free service to open source projects ?

**Comment by steppefox** [comment]
@CompuIves what is the status of this issue? Is it still relevant? Looks like related PR was closed because it was too outdated.

**Comment by vblazenka** [comment]
@CompuIves @steppefox I would also like to help with integrating i18n into the codesandbox.
I think the project will benefit because languages can open new markets in China and Russia (like mentioned before)

**Comment by Saeris** [comment]
Adding this to our public backlog. Closing this out for now, please refer to this link for the status of this request:

https://www.notion.so/Add-i18n-Support-8be1d832f709428ebe5c06bd85bc7640
