### ISSUE TITLE
Renaming file in the SideBar does not update the file name in the edit tab

### ISSUE THREAD

**Issue by haquezameer** [codesandbox/codesandbox-client#2500]
# 🐛 bug report

## Description of the problem
Renaming the file name in the sidebar does not make the name of the file update in the main code area.

## How has this issue affected you? What are you trying to accomplish?
No major issues. Inconsistency in naming may result in conflicts when importing.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Not able to find
| Browser          | 76.0.3809.87
| Operating System | MacOS 10.14.2

**Comment by arthurdenner** [comment]
@haquezameer, could you elaborate on what is the issue? Were you expecting the name on the tab to change or the import? I tried here and the first scenario happens. If you were expecting the second, I don't think it's a feature we can work on since it's inside VSCode.

**Comment by lbogdan** [comment]
Hey @haquezameer ,

Any updates on this?

**Comment by haquezameer** [comment]
@lbogdan @arthurdenner Nope this does not seemed to be happening later. It was an intermittent issue, where renaming the file name on the sidebar did not change the name of the file if its open in one pane.

**Comment by arthurdenner** [comment]
@haquezameer, nice. Could you please close the issue then? Thanks!
