### ISSUE TITLE
netlify claim site not work

### ISSUE THREAD

**Issue by Wenangsani** [codesandbox/codesandbox-client#2513]
# 🐛 bug report

### Environment

Static

"babel-cli": "6.26.0",
"babel-preset-minify": "0.5.1",
"babel-preset-react": "6.24.1",
"babel-preset-stage-2": "6.24.1",
"child_process": "1.0.2",
"concat-files": "0.1.1"

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | chrome
| Operating System | windows

**Comment by SaraVieira** [comment]
Hey!

Can you please send us the sandbox id?

**Comment by Wenangsani** [comment]
> Hey!
> 
> Can you please send us the sandbox id?

https://codesandbox.io/u/Wenangsani
https://codesandbox.io/s/referenseaweb-nfrwi

**Comment by SaraVieira** [comment]
I took a look and there seems to be something wrong with the claim in general

I am taking a look and will keep you updated

Sorry about the issue
