### ISSUE TITLE
Dynamic routing in next.js project does not work 

### ISSUE THREAD

**Issue by mrispoli24** [codesandbox/codesandbox-client#2516]
# 🐛 bug report

## Description of the problem

When trying to build the file structure to create dynamic routes using the new style in next9 the app keeps throwing you to the 404 page. When I download the sandbox and run locally everything works fine.

## How has this issue affected you? What are you trying to accomplish?

I was trying to build a nextjs app and collaborate with some people on it but we ended up using VS code local live view to get around it but it would be great if it worked inside code sandbox. I've tried restarting the sandbox and the server as well as a few configurations for the folder structure. Both configurations work locally.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | |
| Browser          | Chrome |
| Operating System | macOS |

**Comment by lbogdan** [comment]
Hey @mrispoli24 ,

First of all, sorry for the delayed response!

If it works locally, it should most probably work in a server (container) sandbox, too. Can you maybe share your project in a GitHub repository, so I can take a look at it? Thanks!

**Comment by SaraVieira** [comment]
Closed for lack of activity
