### ISSUE TITLE
Trying to resize the console minimizes it

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#2522]
# 🐛 bug report

## Description of the problem
Resizing the console doesn't work in the editor. When you select the console edge and try to drag it to resize the panel, it immediately closes/minimizes on click.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1569330198-771afd31e
| Browser          | Chrome
| Operating System | OS X

**Comment by Saeris** [comment]
Can confirm, I've run into this problem recently too. @christianalfoni might this be related to the Overmind refactors?

**Comment by dance2die** [comment]
Can confirm as well with the demo below.

![demo](https://user-images.githubusercontent.com/8465237/65810580-fb9a5a00-e179-11e9-91c2-68a93db9bb8e.gif)

**Comment by siddharthkp** [comment]
It's not overmind, even more unrelated, fixing it now

**Comment by CompuIves** [comment]
@siddharthkp and @yeion7 fixed this one!
