### ISSUE TITLE
Search in all sandbox files

### ISSUE THREAD

**Issue by viankakrisna** [codesandbox/codesandbox-client#258]
Will help to debug this sandbox https://codesandbox.io/s/52pqxnprp4.

I think we can add a search icon in folders and open a modal to search/replace for text

**Comment by CompuIves** [comment]
Wow, that sandbox is beautiful! 

I think I want to implement a search similar to vscode, with a sidebar with buttons. That would be very powerful, but maybe overkill? It's the most clear solution.

**Comment by sw-yx** [comment]
i would really like a search capability as well. is this on roadmap somewhere?

**Comment by wpitallo** [comment]
Plus one vote!

**Comment by Saeris** [comment]
Adding this to the public backlog. Closing this for now. Please refer to this page for the status of this feature request:

https://www.notion.so/Add-Find-All-multi-file-search-3cf33a3beb30450faf7349cb7ebadccd

**Comment by FatehAK** [comment]
Is this feature (search in all files) available? It would be very helpful since it would make searching the codebase much easier.

**Comment by alexnm** [comment]
Yes, this feature is available in the editor
