### ISSUE TITLE
Crashing while trying to connect to a friend's live sandbox to check their code

### ISSUE THREAD

**Issue by maboyd1** [codesandbox/codesandbox-client#2604]
<h1>💥 Crash Report</h1>

  <h2>Trying to connect to a friend's live sandbox to check their code</h2>

  <h3>Link to sandbox: https://codesandbox.io/live/pRjMy</h3>

  <h3>Crash Details</h3>

  I clicked the link in Firefox and Chrome and both times I ended up with a CodeSadBox message. On my friend's end, they claimed it appeared I was joining then disappearing.
  Windows 7 (64-bit)
Firefox v 69.0.1 (64-bit)
Chrome v 77.0.3865.90 (Official Build) (64-bit)

**Comment by CompuIves** [comment]
Sorry about this! Should be fixed.
