### ISSUE TITLE
Support from iframely

### ISSUE THREAD

**Issue by EisenbergEffect** [codesandbox/codesandbox-client#2605]
# 🌈 Feature

I know this isn't primarily up to you all, but I wanted to drop a note here about it. The service iframely provides a way to embed all sorts of providers in web page. GitBook, a popular documentation platform, leverages iframely. We're looking to move our vNext technical docs for Aurelia to GitBook, and we'd really like to continue using CodeSandbox. Unfortunately, iframely doesn't support CodeSandbox at this time. I've requested that they add you as a provider, but it might be good to follow up with them to ensure they add support for you correctly.

**Comment by CompuIves** [comment]
Heyo! I've done their URL check just now, but it seems to work here? https://iframely.com/embed/https%3A%2F%2Fcodesandbox.io%2Fs%2Fnew

Is there anything else we have to do?

**Comment by EisenbergEffect** [comment]
Looks like they fixed it already. Excellent! Closing this 😄
