### ISSUE TITLE
Support for Opal Ruby + Hyperstack

### ISSUE THREAD

**Issue by catmando** [codesandbox/codesandbox-client#2612]
# 🌈 Feature

Opal Ruby is a transpiler that translates Ruby in JS.  The transpiler can be included and run in the browser (see try http://opalrb.com/try for an a simple online editor.)

It would be great to support this in codesandbox.

Implementation should be very straight forward, just adding the appropriate dependencies, and then detecting the file type and using the appropriate editor.  Everything should work well.

When that is working it would be great to then include the https://hyperstack.org dependencies so you could have a full system.

I would be very happy to fork and implement this, if it would be something accepted as PR.

**Comment by catmando** [comment]
WOAH... sorry, but I see that .rb files are already supported.  Perhaps its just a matter of adding the right dependencies.  Sorry if I was previous...

**Comment by CompuIves** [comment]
Wow, this is interesting! Right now we hardcode the bundler settings, meaning that eg. the React environment has hardcoded settings to make it work like create-react-app. I was thinking of making it possible to change the bundler settings by adding the possibility to create your own environment of some sort, but need to think a bit more about that.

What we can do in the meantime is running the transpiler in the app itself, this also demos nicely how it actually works. Is there a package on npm that can act as the transpiler of rb -> js?

**Comment by catmando** [comment]
Yes there is opal-runtime and opal-compiler npm packages. 

I have discovered the "Vanilla Template" and am getting that set up using the above.  Hopefully that will make a great "demo".

The only thing I don't like is that the modules transpile after every couple of keystrokes.  Seems like there might be a setting to only transpile on file save?

**Comment by CompuIves** [comment]
Yes! You can change this in user settings (under your image and then Preferences).
