### ISSUE TITLE
Console log persists even after switching sandbox.

### ISSUE THREAD

**Issue by yashguptaz** [codesandbox/codesandbox-client#2626]
# 🐛 bug report

## Description of the problem
- Created a new sandbox in a folder.
- The previous sandbox console logged some stuff.
- As soon as I begin writing in the new sandbox's js file the console logged stuff of the previous sandbox appears.
- It goes away as soon as I reload the browser in the sandbox
- It reappears as soon as I type something and the JS file is unsaved.

This is happening with Vanilla JS sandbox for me I haven't tried out other sandboxed templates.

## How has this issue affected you? What are you trying to accomplish?
It confuses me a lot.

### Link to sandbox: [link]() (optional)
Previous sandbox
- https://codesandbox.io/s/js-debugging-tips-and-destructuring-d7tye

The sandbox I'm currently working with.
- https://codesandbox.io/s/upbeat-fast-ynk52

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser - Firefox 69.0.1 (64 Bit)  |
| Operating System - Windows 10|

Here's a screenshot.
I would like to work on the issue, also I'm new here, this is my first time contributing to something technical. Thank You for looking into this.
![image](https://user-images.githubusercontent.com/36479718/66129781-3125c400-e60e-11e9-82fd-b83227303142.png)

**Comment by CompuIves** [comment]
Hey @yashguptaz! This is a good report, we would absolutely appreciate your help! We normally clear the console with this code: `dispatch({ type: 'clear-console' });`. We could add this code here I think: https://github.com/CompuIves/codesandbox-client/blob/d15f9e7c51f159ab429002a577cbfd3de43f27a7/packages/common/src/components/Preview/index.tsx#L240-L263 to fix it.

**Comment by yashguptaz** [comment]
I have set up my project locally, I have made the required changes but I cannot test them.
I don't know why this is happening.

![image](https://user-images.githubusercontent.com/36479718/66220867-779d2080-e6eb-11e9-9763-92b45855dd46.png)

Can you tell me how can I log in to codesandbox using GitHub? 
I want to test this thing with folders but I'm unable to create folders because I cannot log in.

![image](https://user-images.githubusercontent.com/36479718/66221046-ccd93200-e6eb-11e9-8604-d80416c24671.png)

I have added `dispatch({ type: 'clear-console' });`  just after the `resetState()` function at line 244.
I hope it should be good.
I haven't ran any tests yet, I will once I can test my changes.

**Comment by yashguptaz** [comment]
I  am having some issues with `Yarn test`
@Saeris @CompuIves  Can you help me with that?
![TptI9162 png medium](https://user-images.githubusercontent.com/36479718/66254048-8092fe00-e78e-11e9-8099-4001e477b5b3.png)

**Comment by jyash97** [comment]
Hey @yashguptaz 
For testing login features you can do the following: 

You can log in on https://codesandbox.io/ and copy the contents of the `jwt` local storage key over to your development environment on http://localhost:3000/. 

Read the last paragraph [here](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md#code-organization) for more details.

**Comment by yashguptaz** [comment]
@CompuIves I cannot replicate the bug now, was there a patch that fixed that?
I find it strange. If there was a PR that fixed it I'm closing this issue and my PR.

**Comment by arthurdenner** [comment]
@yashguptaz, I believe that [your PR](https://github.com/codesandbox/codesandbox-client/pull/2660) fixed. Can you close the issue, please?

**Comment by yashguptaz** [comment]
Closing it right now :)
Will be looking forward to more contributions from my side.
