### ISSUE TITLE
Can't resolve all parameters for ApplicationModule: (?)

### ISSUE THREAD

**Issue by Riccardo-Andreatta** [codesandbox/codesandbox-client#2634]
# 🐛 bug report

## Description of the problem

Importing a fresh Angular 8 project inside Codesandbox is causing this issue:

```
Error
Can't resolve all parameters for ApplicationModule: (?).
▶ 16 stack frames were collapsed.
evaluate
main.ts:11:25
   8 |     enableProdMode();
   9 | }
  10 | 
> 11 | platformBrowserDynamic().bootstrapModule(AppModule)
     |                         ^
  12 |     .catch(err => console.error(err));
  13 | 
View compiled
▶ 19 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.
```

Steps to reproduce:
- Delete everything from the default Codesandbox starter project.
- Create an Angular 8 project from scratch in your local machine.
- Upload all the files from this new project inside the empty Codesandbox project.

## How has this issue affected you? What are you trying to accomplish?

I am trying to recreate an Angular 8 environment inside Codesandbox.

### Link to sandbox: [link](https://codesandbox.io/s/angular-8-environment-k6jo3
) 

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | |
| Browser          | Chrome |
| Operating System | Mac |

**Comment by lbogdan** [comment]
Hey @Riccardo-Andreatta ,

Here's an article about how to make Angular 8 work in CodeSandbox: https://scotch.io/@mathieu-vacher/how-to-build-a-template-with-angular-material-v8 . Following the steps there I ended up with a working Angular 8 sandbox: https://codesandbox.io/s/angular-9hbmc . Does that address your issue?

**Comment by rlee1990** [comment]
I have the same issue

**Comment by rlee1990** [comment]
@lbogdan that didn’t help me at all

**Comment by waterplea** [comment]
Happened to me too. I wanted to deploy my github demo for a library like I used to do but for some reason I'm getting this error (

**Comment by garethx** [comment]
As a workaround, if you upload your locally exported app to a blank node container sandbox rather than the Angular client sandbox then it works. See https://codesandbox.io/s/patient-pond-zx5rx for example.

**Comment by waterplea** [comment]
Looks like adding this:
`import "core-js/proposals/reflect-metadata";`
to main.ts helps. However I still cannot make my sandbox compile in ES2015 :(

**Comment by ChristianGalvez23** [comment]
Same problem, but in my case, I just created a Angular CodeSandbox and everything was going well but suddenly solution threw the error which until now I don't know what it means or what caused this.

**Comment by alsharifnahas** [comment]
I had the same issue in the begging, then i added:
     import "core-js/proposals/reflect-metadata";
To the main.ts file
I also added core-js dependency. It worked for me after adding the dependency.
