### ISSUE TITLE
Possibility to create snapshots as commits in a Github repository

### ISSUE THREAD

**Issue by lwxbr** [codesandbox/codesandbox-client#2651]
# 🌈 Feature

### What is this feature?
The feature is basically utilize Github that is already used to make the templates of Codesandbox to save states of the sandbox making a timeline of states previously saved by the users.

### How the feature should work? 

Well, in the interface, can have a button called 'save state' or 'create commit', when you click it will appear a dialog to put a message in the state you are saving (that is nothing more than git commit message). So when you save it will create the state of the sandbox at that point.

### You have examples or an idea how it can be implemented?
Well, JSfiddle does that in a simple way adding incremental versions in the url:

https://jsfiddle.net/rcomk6Le/4/,
https://jsfiddle.net/rcomk6Le/5/
https://jsfiddle.net/rcomk6Le/6/
etc.

**Comment by siddharthkp** [comment]
Hi!

That's a pretty good idea! Do you think it would make sense to use the existing GitHub integration and add a way to go through the commits?

That way, you can use the already working commit mechanism and also get a nice history

**Comment by lwxbr** [comment]
Hi, @siddharthkp! Yes, initially could be Github integration, but if it all goes well it can have another integrations like Bitbucket, Gitlab, etc. But Github itself is a good start and is the environment Codesandbox is already immersed.
