### ISSUE TITLE
Development using remote ssh

### ISSUE THREAD

**Issue by steventsao** [codesandbox/codesandbox-client#2673]
# ❔ Question

I am unable to leverage remote development with the current setup and am wondering if there is a recommended way of doing it? [Remote SSH](https://code.visualstudio.com/docs/remote/ssh) helps me offload the computation of building to a remote box while using my local editor. On init, the app tries to connect to a WebSocket on `ws://localhost:3031`, which goes to my local machine instead of the remote box in which the app is built and fails. I've thought about changing all the usages of `localhost` in app, ie. in `packages/app/scripts/start.js`, and the IP in `localhost` in `/etc/host`, but neither feels convenient. Is there a recommendation on this? If so, I would like to try it out and add it to the development doc. Thanks.

### Link to sandbox: [link]() (optional)
N/A
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | N/A
| Browser          | Chrome | 
| Operating System | Mac 10.14 |

**Comment by lbogdan** [comment]
Hey @steventsao ,

Have you tried the [port forwarding](https://code.visualstudio.com/docs/remote/ssh#_forwarding-a-port-creating-ssh-tunnel) feature of Remote SSH?

**Comment by steventsao** [comment]
Thank you. I need to forward both `:3000` and `:3031` to my remote to work.
