### ISSUE TITLE
SyntaxError Unexpected token 'export' (ES6 export not first on the line)

### ISSUE THREAD

**Issue by pskelin** [codesandbox/codesandbox-client#2679]
# 🐛 bug report

## Description of the problem
If I import a valid ES6 file (but minified), I get the following error:
```SyntaxError
Unexpected token 'export'
```
even though the export statement is correct. While the same kind of file, but beatified so that the export statement is on its own line works correctly:

Here is a link to the broken import:
https://codesandbox.io/s/lucid-kilby-t8zhs
And the file causing it:
https://unpkg.com/@ui5/webcomponents@1.0.0-rc.3/dist/generated/i18n/i18n-defaults.js

The same file (conent-wise) but pasted in the project itself works correctly (comment the first import and uncomment the second one in index.js)

If the file is consumed via NPM and not minified, it works as expected:
https://codesandbox.io/s/optimistic-buck-ciswk
And the similar file (just not minified):
https://unpkg.com/@ui5/webcomponents@1.0.0-rc.2/dist/i18n/defaults.js

So this is only an issue if a minified ES6 file with an export statement at the end of the file is consumed via node modules.

not minified, or minified by hand in the same project (instead of node_modules) both work as expected.

## How has this issue affected you? What are you trying to accomplish?
The whole application breaks during compilation. Somehow this file does not get recognized as an ES6 module, so the following processing steps on it say that `export` is an unexpected token.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/lucid-kilby-t8zhs

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1570108289-8e70564ca
| Browser          | Chrome - Version 77.0.3865.90 (Official Build) (64-bit)
| Operating System | MacOS 10.14.6 (18G103)

**Comment by lbogdan** [comment]
Hey @pskelin ,

This is probably because we don't properly detect the `exports` in those files; btw, npm packages should only expose ES6 code if under `module` field in `package.json`, we only added support for it because there's quite a few improperly authored npm packages. 🙁 It works when you copy it to the project because we always transpile ES6 in project files.

**Comment by pskelin** [comment]
Thanks for the explanation @lbogdan 

We changed the code to have the export on a single line so now it works.

I just wanted to point out a legitimate reason to ship ES6 modules via npm and not have a `module` field in `package.json`.

Our project https://www.npmjs.com/package/@ui5/webcomponents ships a set of UI web components, so developers are expected to only import the ones they use (we ship 30, they use 5 or 10, not all).

The web component has to register itself via the browser APIs as part of its import (a best practice when shipping web components). This registration happens with a method call on the top level of the module, which is considered by build tools as a side effect of the import and the code of the component cannot be considered unused and does not get tree-shaken.
https://github.com/SAP/ui5-webcomponents/blob/b1334686c44f2fc4c49ef2fc6dfe4cf6e7090da6/packages/main/src/Button.js#L332

If we reexport all components as part of a main module, build tools consider all of them used (as they called a method that is considered a side effect). So event if a consumer imports just one named module from the main module, all of them get bundled. So the only way to provide consumers with the possibility of having a more optimal bundle is for them to directly import the modules.

I hope that explanation makes sense and I think it is a legitimate usage you might want to consider. Are there other ways to mark packages as ES6 without having a `module` field?

**Comment by heswell** [comment]
I have the same problem, I'm trying to consume packages authored in ES6 (using 'module' attribute in package.json) , using a CRA project. Works fine if I clone the repo and run it locally, but in codesandbox I get unexpected token 'export'
