### ISSUE TITLE
Forking a sandbox shows empty error/warning snackbars

### ISSUE THREAD

**Issue by ndresx** [codesandbox/codesandbox-client#2684]
# 🐛 bug report

## Description of the problem

Trying to save a sandbox through one of the "Save" options shows two additional empty snackbars. This doesn't happen when trying to fork it by clicking the "Fork" button directly.

![image](https://user-images.githubusercontent.com/27507295/66340483-88e16980-e945-11e9-9a40-3092497b7527.png)

This console error log might be related to this issue:

```
Uncaught TypeError: Cannot read property 'stack' of null
```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | ?
| Browser          | Google Chrome 
| Operating System | Windows 10

**Comment by jyash97** [comment]
Hey @ndresx 
I have created a PR for this issue on #2683
