### ISSUE TITLE
Monaco Editor bundling failture

### ISSUE THREAD

**Issue by rebornix** [codesandbox/codesandbox-client#2712]
# 🐛 bug report

## Description of the problem

Monaco Editor is not bundled successfully one way or another 

## How has this issue affected you? What are you trying to accomplish?

Bundle Monaco Editor into a vanilla project

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome
| Operating System | macOS

Clone https://github.com/microsoft/monaco-editor-samples/tree/master/browser-esm-parcel and follow steps to install parcel and bundle the project, it runs successfully. However if the same code was copied to Codesandbox, it throws errors.

**Comment by lbogdan** [comment]
Hey @rebornix ,

We only support a limited set of `parcel` features inside client sandboxes, but you could try with a container sandbox - see my comment [here](https://github.com/codesandbox/codesandbox-client/issues/2354#issuecomment-527564461) for reference. Let us know if that works or you encounter further issues.

**Comment by SaraVieira** [comment]
Closed as this is a limitation of client sandboxes and can be achieved in container ones
