### ISSUE TITLE
Live mode - Switch "Hide notifications" doesn't have any effect

### ISSUE THREAD

**Issue by imagoiq** [codesandbox/codesandbox-client#2719]
# 🐛 bug report

## Description of the problem

In live mode, we tried to hide notifications in classroom mode. Professors and students could still see all the notifications about people joining and leaving the session (which is very annoying).

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1570545059-ce110646c
| Browser          | Firefox 70.0b13
| Operating System | Windows 10

**Comment by siddharthkp** [comment]
Hi @imagoiq, thanks for reporting this bug! We're on it.
