### ISSUE TITLE
Patron: cannot change visibility of my sandboxes

### ISSUE THREAD

**Issue by Ajdija** [codesandbox/codesandbox-client#2721]
# 🐛 bug report

## Description of the problem
Cannot change visibility of my sandboxes to "unlisted".
## How has this issue affected you? What are you trying to accomplish?
suddenly after a page refresh... (around 9:00 pm 9 October 2019 CEST) must have been latest rollout
https://codesandbox.io/u/Ajdija

### Link to sandbox: [link]() (optional)
any of my sandboxes
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1570545059-ce110646c
| Browser         | Chrome
| Operating System | MacOS

**Comment by lbogdan** [comment]
Hey @Ajdija ,

What exactly happens when you're trying to change the visibility? Do you get any error in the UI or the devtools console?
