### ISSUE TITLE
CodeSandbox will break with next Firefox release

### ISSUE THREAD

**Issue by aem** [codesandbox/codesandbox-client#2726]
# 🐛 bug report

## Description of the problem

CodeSandbox does not render anything on the next version of Firefox (`v70.0b7`, currently in beta, but reaching stable soon). I've confirmed that the same apps render fine in the current stable release (v69.0.1). I see a blurry image of the text in the rendered starter app and then just a blank white screen.

Console errors:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/1909883/66582592-0b3d7980-eb50-11e9-88a4-99766ef6291f.png">

It appears that Firefox in v70 is introducing some new cross-frame security measures that are interfering with how CodeSandbox renders the output of the app. 

## How has this issue affected you? What are you trying to accomplish?

Can't use CodeSandbox 😄 

### Link to sandbox

Any new sandbox, even a new sandbox with no changes renders nothing ([create new](https://codesandbox.io/s/new)). This isn't a library-specific bug, I see it with both React and Vue starters (haven't tested others but I imagine it's similar) 

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  Not sure how to tell 😬 
| Browser          |  Firefox 70.0b7
| Operating System | macOS 10.14.3

**Comment by CompuIves** [comment]
Hmm, interesting. This seems to reside in our BrowserFS implementation, I'll take a look!

**Comment by CompuIves** [comment]
Hmm, do you still experience this in Firefox 70.0b14? I can't seem to reproduce this right now.

**Comment by christianalfoni** [comment]
Yeah, just tested: `71.0a1 (2019-10-14) (64-bit)` , opens fine? 

Maybe they have fixed the issue already? :)

**Comment by Zaldos** [comment]
Just had a look into this as I was directed here. Seems that with version 71.0b1 (64-bit) of developer this still happens. Whenver the tracking protection is on and you set it to custom -> block cookies -> unvisited websites, it causes the sandbox to not load:
![image](https://user-images.githubusercontent.com/350699/67040887-52150b80-f11c-11e9-9d6c-29400c5838fb.png)
First error is 
![image](https://user-images.githubusercontent.com/350699/67041082-c3ed5500-f11c-11e9-9e43-5e4d6756fe77.png)
And that line of code is: 
`var Tt = m.indexedDB || m.mozIndexedDB || m.webkitIndexedDB || m.msIndexedDB;` though I am not if that can help you.

**Comment by maniac0s** [comment]
It's still not working in Firefox

**Comment by Landen13** [comment]
Will this be fixed? Some open-source libraries use codesandbox to provide code examples in their docs, and It is not working at all in Firefox...

**Comment by SaraVieira** [comment]
Hey

I just opened the website in Firefox and everything seems fine
![CleanShot 2020-08-31 at 14 36 09](https://user-images.githubusercontent.com/1051509/91720469-7f817100-eb97-11ea-9b14-c7a28b57025f.png)
![CleanShot 2020-08-31 at 14 39 00](https://user-images.githubusercontent.com/1051509/91720616-b9eb0e00-eb97-11ea-949e-96ed19463edd.png)

**Comment by nahojd** [comment]
Still not working in 84.0b5

**Comment by SaraVieira** [comment]
Can you share your settings? Just shared mine above and it seemed to be working

**Comment by stefanprobst** [comment]
@SaraVieira things seem to break with a custom cookie setting of "Cookies from unvisited websites" or "All third-party cookies".

**Comment by Pauan** [comment]
This is still an issue in Firefox 90.0b6.

![Screenshot 2021-10-04 13:10:22](https://user-images.githubusercontent.com/97238/135841462-e0a03d19-e6c8-4bd8-b6ff-21d990331520.png)

**Comment by anjannair** [comment]
I can confirm this issue still persists. However the same thing works on Chrome.

**Comment by 416d72** [comment]
I solved this issue by allowing `https://csb.app` and `https://codesandbox.io` in Firefox Cookie exceptions settings.
