### ISSUE TITLE
CodeSanbox is already crashing in Opera 

### ISSUE THREAD

**Issue by renanborgez** [codesandbox/codesandbox-client#2730]
# 🐛 bug report

## Description of the problem
The codesanbox starts to load properly 
![image](https://user-images.githubusercontent.com/1863024/66650025-e6203800-ec2f-11e9-9d8a-cdc28150e39f.png)

However it breaks just few secs later even not changing anything in the page
![image](https://user-images.githubusercontent.com/1863024/66649369-43b38500-ec2e-11e9-8a8d-aeeef2b26f01.png)

- Tested in anonymous tab with all extensions disabled and still crashing
- I have cleared the Application's data (cookies, localstorage, etc..) and the problem persists

## In Google Chrome it works
![image](https://user-images.githubusercontent.com/1863024/66649966-c25cf200-ec2f-11e9-8f77-4dd767859133.png)

## How has this issue affected you? What are you trying to accomplish?
Trying to create new sandbox

### Link to sandbox
https://codesandbox.io/s/new

### Your Environment
![image](https://user-images.githubusercontent.com/1863024/66649452-7d848b80-ec2e-11e9-851d-099c86b3076d.png)

Version (i think)?
![image](https://user-images.githubusercontent.com/1863024/66650292-8bd3a700-ec30-11e9-9080-a83e1fb0f078.png)

**Comment by burtek** [comment]
Same here

**Comment by burtek** [comment]
Looks like Opera's issue: https://www.reddit.com/r/operabrowser/comments/di67hf/codesandbox/

**Comment by renanborgez** [comment]
Yes, I've tested with Opera version 66 and it works pretty well.

**Comment by renanborgez** [comment]
Opera fixed this issue in last stable release
![image](https://user-images.githubusercontent.com/1863024/67480883-0ce36300-f661-11e9-9bab-cb5aa53f12d6.png)

So, I'm closing this issue
