### ISSUE TITLE
Minor UI issue: Button text overflows when left pane resized.

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [codesandbox/codesandbox-client#2733]
# 🐛 bug report

## Description of the problem

I like to make the leftmost pane narrow to maximize the editor pane. However, I noticed this leads to a noticeable overflow of the text:

![image](https://user-images.githubusercontent.com/19352442/66668762-f4685700-ec23-11e9-97b0-b864c53fb165.png)

This actually happens on a couple other buttons, too:

![image](https://user-images.githubusercontent.com/19352442/66668905-5032e000-ec24-11e9-8e00-d1a01f531af6.png)

Adding `overflow: hidden` and `text-overflow: ellipsis` fixes it:

![image](https://user-images.githubusercontent.com/19352442/66669055-aacc3c00-ec24-11e9-883f-d92e8a3556ea.png)

## How has this issue affected you? What are you trying to accomplish?

It's a **very** minor UI issue that may not even be worth considering, so it's up to you guys if you want to fix it or not. Like, it's not even an annoyance; it's just a noticeable visual bug. I also imagine it's not even an issue for people with bigger monitors.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1570545059-ce110646c (I think?)
| Browser          | Chrome
| Operating System | MacOS

**Comment by theghostyced** [comment]
If this issue is approved, I would love to take it up

**Comment by AleksandrHovhannisyan** [comment]
That helps a lot! Thanks :)
