### ISSUE TITLE
Importing JSON files in TS config reports error but it still works

### ISSUE THREAD

**Issue by BPScott** [codesandbox/codesandbox-client#2735]
# 🐛 bug report

## Description of the problem

In a project that uses typescript but without a tsconfig file you can do:

```js
import jsonDoc from "./data.json";
```

This works and you can access the content is loaded from the json file (I assume because the react template actually uses babel/webpack to parse and build ts files instead of the typescript compiler).

However the typescript type checker suggests that there is an error on that line, stating:

> Cannot find module './data.json'. Consider using '--resolveJsonModule' to import module with '.json' extension

Should that option be added to the default compilerOptions that are used in typescript projects so that false error is stops being reported?

## How has this issue affected you? What are you trying to accomplish?

This reduces confidence as it reports an error for something that isn't actually an issue.

**Comment by am1rb** [comment]
Hey guys, I have a similar issue. Any updates on this?

**Comment by JamesACS** [comment]
If you're encountering this now @am1rb - Please could you create a new issue with reproduction steps?

**Comment by BPScott** [comment]
It seems that the reproduction sandbox in the original issue still triggers the error expected.

The reproduction steps are:

- Open https://codesandbox.io/s/testing-json-imports-in-typescript-j62fp
- See that index.ts's line 3 `import jsonDoc from "./data.json";` has a red squiggly line that when you mouse over it claims`Cannot find module './data.json'. Consider using '--resolveJsonModule' to import module with '.json' extension`

**Comment by heath-freenome** [comment]
I also see this... Maybe adding something into a `tsconfig.json` will fix things?
