### ISSUE TITLE
Patron page -- billing day is incorrect

### ISSUE THREAD

**Issue by hasparus** [codesandbox/codesandbox-client#2739]
# 🐛 bug report

## Description of the problem

The day when the Patrons are billed is a little bit off.

> **You will be billed now and on the 285th of each month thereafter.**

![image](https://user-images.githubusercontent.com/15332326/66699883-111b9200-eceb-11e9-87fc-85d8400e1041.png)

## How has this issue affected you? What are you trying to accomplish?

I wanted to finally send some 💲 for the excellent app I'm using for a long time. I think I'll wait with becoming a Patron and try helping with contributions instead.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | codesandbox.io? |
| Browser         | Brave |
| Operating System | Windows |

**Comment by oskarabc** [comment]
Thanks for this catch @hasparus and we'll be shipping a fix as soon as we can.

**Comment by hasparus** [comment]
Thanks :)

**Comment by oskarabc** [comment]
This should have been fixed with the latest deploy. Thanks!
