### ISSUE TITLE
Performance issues in editor

### ISSUE THREAD

**Issue by CompuIves** [codesandbox/codesandbox-client#274]
I've been pulling my hair out with this. On my Macbook Pro 13" the editor is much slower than the embed:

https://codesandbox.io/s/new
https://codesandbox.io/embed/new

For me the embed is twice as fast.

I want to know if others experience the same, and if anyone knows what the editor does to make it so slow. This is frustrating!

**Comment by kvklink** [comment]
Looking at the Chrome performance tool, /embed/new takes ~3500ms and /s/new takes ~3700ms on Linux.
How relatively small the difference may be, it's definitely there. What kind of loading times are you having?

**Comment by Anenth** [comment]
@CompuIves editor loads pretty fast for me, but the preview takes ages to load

**Comment by crazyyi** [comment]
How did you measure the page loading?
I use https://tools.pingdom.com to measure.
Took 1.51s to load 594 kB for https://codesandbox.io/s/new.
It took 1.11s to load 426.3kB for https://codesandbox.io/embed/new.

But to be honest I don't feel too much difference on my computer (Macbook pro 2017)

**Comment by lbogdan** [comment]
@CompuIves Is this still an issue?

**Comment by drcmda** [comment]
@CompuIves I was just about to open an issue, then i saw this ... I've noticed it for a while now and it's still there. I tried to capture it, but i'm not sure if it's visible there:

![perf](https://user-images.githubusercontent.com/2223602/40278137-c370a2f8-5c2b-11e8-82c2-7ff2f23f1813.gif)

The editor gets really janky, though, the embed is fine.

I tried to profile it and the only difference i can see there seems to be mouse events looking somewhat more heavy in the editor.

**Comment by CompuIves** [comment]
That's very interesting. I'm curious what the cause could be of longer composite layer drawing in the editor vs the embed, maybe the amount of elements or the amount of css on a page? I think that @tkh44 has done some research on this.

If we know the cause and can fix it we will get a muuch smoother editor experience.

**Comment by tkh44** [comment]
Just saw this. Is this still an issue you are looking into?

**Comment by CompuIves** [comment]
Yes, I've looked at it some moments but couldn't find the root cause of the big difference between embed/app. It's really frustrating because it feels like there is one root cause here.

**Comment by tkh44** [comment]
If you put the embed in an iframe on another page how does it perform? This would be a relatively easy way to test the performance in a relative manner.

**Comment by vvo** [comment]
We need @samccone to do a performance audit of CodeSandbox :D

**Comment by CompuIves** [comment]
Oh @tkh44 in our case the embed is actually faster than the editor! I don't know what causes such big composite drawing times, maybe more elements?

**Comment by drcmda** [comment]
Maybe starting out with the editor, running a base profile, then switching off regions in it with the h-key in devtools to circle in on the area that's causing it. Debugging browser specific stuff is otherwise hard to track down.

**Comment by Saeris** [comment]
Closing this issue as it's been nearly a year since there was any discussion and the codebase has change significantly since this was first opened.
