### ISSUE TITLE
relative urls in codesandbox

### ISSUE THREAD

**Issue by NANASHI0X74** [codesandbox/codesandbox-client#2771]
# Relative Urls in codesandbox

- ## What is this feature?
if I use relative urls anywhere in the html document, that should work or there should be a setting which enables redirecting relative paths to the right static path on codesandbox (if the files are present in the sandbox)
- ## How the feature should work?
relative paths to any sort of resource (img, stylesheet,, script, document...) should be found by the preview renderer so it can display the page correctly (and possibly, you should be able to activate or deactivate this feature somewhere in a settings menu)
- ## You have examples or an idea how it can be implemented?
example: redirect relative path /resources/img.jpg to data:image/jpg/base64 etc (which is aparently how images work in codesandbox currently :p)
or simply have the files be stored at the right path relative to the codesandbox base url, but I imagine that might be tricky to do.
- ## why tho?
I was working on a small project (not using react or  any framework, but just plain html and css) with github and vs code locally, but then I remembered codesandbox and wanted to  use that with the intention of having sort of an ide for the web which I can just use in the browser, so not just locally on my device, but on other computers too, maybe even on a phone. Unfortunately my relative paths that were in index.html weren't found by the preview renderer, so the whole page really was broken. Adjusting the paths manually isn't really an option for me for one because of scaling issues, by which I mean this would introduce lots of overhead when I'd like to use a new resource and even more overhead when I'd like to edit a resource (with data urls). Also, it simply alters the behavior of the page... Maybe I'd really like to keep the urls relative on some deployments for whatever reason having to do with the setup of the hosting server. And in that case, that would effectively introduce different development environments, defeating the purpose of having one cross-platform, shared environment that I can use on any device via the browser.
There's been a pull request, #463 I believe, but unfortunately  was closed due to inactivity.

**Comment by NANASHI0X74** [comment]
simply looking at the commit messages in the pr, the original developer might have actually finished his work, but then didn't respond to a maintainer engaging with him a few months later

**Comment by lbogdan** [comment]
Hey @NANASHI0X74 ,

I don't think #463 is related, though, that was about having relative URLs in the preview's address bar.

**Comment by NANASHI0X74** [comment]
https://codesandbox.io/embed/rians-html-cv-n8cxj?codemirror=1
this is the sandbox I'm struggling with. It uses relative urls for a stylesheet and some graphics

**Comment by garethx** [comment]
It looks like the problem is caused by the use of the create-react-app environment (which importing from GitHub seems to default to) for a static site. If you use a static environment then the relative URLs work correctly. See https://codesandbox.io/s/static-i2y9l
