### ISSUE TITLE
Error: Cannot find module './config'

### ISSUE THREAD

**Issue by khanakia** [codesandbox/codesandbox-client#2788]
# 🐛 bug report
Error: Cannot find module './config'

## Description of the problem
I have simple node.js program and when i run the command in TERMINAL i get this error. I have config.js file already in the same directory.
`node src/pubsub/subscriber.js`

## How has this issue affected you? What are you trying to accomplish?
I have just created a simple node.js program.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/redis-example-p4ywk

### Your Environment
| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome
| Operating System | Mac OSX

**Comment by garethx** [comment]
You're seeing the error 'Error: Cannot find module './config'' in the terminal after running `node src/pubsub/subscriber.js`? Is this still the case? I'm not able to reproduce in a fork of the linked sandbox. Thanks.

**Comment by khanakia** [comment]
It's seems working now.
