### ISSUE TITLE
Preferences items still show if not signed in

### ISSUE THREAD

**Issue by CompuIves** [codesandbox/codesandbox-client#2793]
# 🐛 bug report

## Description of the problem
If you're not signed in, we show items. I think this was introduced in a refactor?
![image](https://user-images.githubusercontent.com/587016/66825878-dcf6da00-ef53-11e9-8593-796e7288474e.png)

**Comment by rohitjindal18** [comment]
@CompuIves What items need to be removed for not signed in users?
