### ISSUE TITLE
DependencyNotFoundError: Could not find dependency: '' relative to <path/file>'

### ISSUE THREAD

**Issue by dotnetspec** [codesandbox/codesandbox-client#2794]
# 🐛 bug report

## Description of the problem
import {
  render
} from "@testing-library/react"
causes error:
'DependencyNotFoundError: Could not find dependency: '' relative to <path/file>''
in a file at src/app/js level in a Create-React-App.
The same import in files lower down in the project structure cause no error.
Codesandbox reports:
````
Suggested solutions:
Add @testing-library/react as dependency
````
But it has already been added.

## How has this issue affected you? What are you trying to accomplish?
Prevents application from loading in codesandbox so that React Test Library support cannot help with an issue I have with testing.
I am trying to get codesandbox to display the 'home' page of the app so they can see how it currently functions and troubleshoot

### Link to sandbox: [link]() (optional)
https://codesandbox.io/embed/github/dotnetspec/sportrank-CRA/tree/dev/

### Your Environment
| Software         | Name/Version |
| @testing-library/react
| Сodesandbox  -    https://codesandbox.io/embed/github/dotnetspec/sportrank-CRA/tree/dev/ |
| Browser    Chrome Version 77.0.3865.90 (Official Build) (64-bit)      |
| Operating System | Linux Mint | 18.3 |

**Comment by CompuIves** [comment]
Ah, this is because we don't process `devDependencies` right now for bundle size reasons. One quick fix is moving `@testing-library/react` to `dependencies` in `package.json`. We have to fix this in the future, or move detected big projects automatically to containers.

**Comment by dotnetspec** [comment]
Ok, thanks for the notification. Done that and all works now.
Codesandbox is great, BTW ...

**Comment by danpantry** [comment]
Hi, this appears to still be present and the workaround does not appear to work: https://codesandbox.io/s/trusting-sammet-llee1

**Comment by KasiaSmolarska** [comment]
the same problem here :
[https://codesandbox.io/s/elated-driscoll-gpp3x](https://codesandbox.io/s/elated-driscoll-gpp3x)

**Comment by theRealEmu** [comment]
Had this too, just reload the page

**Comment by adamwong246** [comment]
+1 to @theRealEmu. Sometimes the deps don't load as you add them. Reload the page and they are now present. Seems buggy and inconsistent. I was not able to consistently replicate.

**Comment by abdulquadir77** [comment]
I am also facing the Same issue.
