### ISSUE TITLE
Recovered changes can't be discarded

### ISSUE THREAD

**Issue by siddharthkp** [codesandbox/codesandbox-client#2796]
# 🐛 bug report

Thanks to @wolverineks for the detailed repro. I have copy pasted some of the feedback they gave us.

## Description of the problem

Paraphrased: When you close the editor without saving changes (intentionally) and come back later, codesandbox recovers the changes for you but does not let you discard the changes (or go back to the saved state with undo)

## How has this issue affected you? What are you trying to accomplish?

use case: sometimes i open templates to try something out, but not to start new projects, like, offering support in forums. if i make changes without saving, then close, uh oh.....

steps to reproduce:
1. open template
2. make changes
3. close without saving
4. reopen tempate

result: 
recovered unsaved files, but cannot undo changes to get back to original template state

expected result:
no recovered unsaved changes

possible solution:
a) do not allow user to leave unsaved changes
b) abandon unsaved changes

**Comment by CompuIves** [comment]
Right now it's possible, but too hidden. You can do it this way:

![image](https://user-images.githubusercontent.com/587016/66832449-9c528d00-ef62-11e9-8d5f-1227dc535688.png)


Or this way:

![image](https://user-images.githubusercontent.com/587016/66832493-b42a1100-ef62-11e9-9205-5ab1ae2cf243.png)


BUT, it's disabled here for some reason:

![image](https://user-images.githubusercontent.com/587016/66832514-be4c0f80-ef62-11e9-8f7b-0e94812a3bf1.png)


Maybe we should add something in the explorer? cc @DannyRuchtie

**Comment by siddharthkp** [comment]
I recommend adding it to the notification itself:

![Screenshot 2019-10-15 at 2 48 07 PM](https://user-images.githubusercontent.com/1863771/66832752-d4ee6880-ef5a-11e9-946e-6402b20c1b8f.png)
