### ISSUE TITLE
Github sign in doesn't work in localhost

### ISSUE THREAD

**Issue by kushagra12** [codesandbox/codesandbox-client#2801]
# 🐛 bug report

## Description of the problem

As part of hacktoberfest, I was making testing my code for PR #2800. I observed a bug where if you have not authorized GitHub in main site, sign in via Github in localhost doesn't work.  

## How has this issue affected you? What are you trying to accomplish?

Wasn't able to test my code but as stated, problem is only there in localhost.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1570545059-ce110646c |
| Browser          | Chrome |
| Operating System | macOS Majave |

![Screen-Recording-2019-10-15-at-8 25 30-PM](https://user-images.githubusercontent.com/446695/66845227-4ba45980-ef8d-11e9-9b35-9d392713fa87.gif)

**Comment by armujahid** [comment]
You can copy the contents of the jwt local storage key from production to dev environment. 
Quote from [CONTRIBUTING.md](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)

> If you're working on a feature that needs you to be logged in, you can login on https://codesandbox.io/ and copy the contents of the jwt local storage key over to your development environment on http://localhost:3000/. Be very careful with how you handle the token, as anyone who knows it can login as you and have read/write access to all your CodeSandbox content!

**Comment by kushagra12** [comment]
I can see this behaviour was recently changed in #2750. I am using the build with that change.

**Comment by lbogdan** [comment]
Closing this, as it was addressed in #2750 . @kushagra12 If this is still an issue, please make sure your PR is merged with latest master.
