### ISSUE TITLE
Implement shortcut for popping up terminal or console

### ISSUE THREAD

**Issue by theghostyced** [codesandbox/codesandbox-client#2813]
# 🌈 Feature

## What is this feature?
So after playing around with codesandbox, I found out that though it had a console/terminal no shortcut was provided as we have in `VSCode` . After trying to implement this myself and fail 😅 decided to raise the issue here and hopefully someone would implement it.

## How the feature should work?
Given a user of codesandbox uses the shortcut `Ctrl + ,` it should toggle the terminal or console.

## Given Implementation?
An implementation can be seen in VSCode where hitting `Ctrl + ,` toggle the in-built terminal.

**Comment by SaraVieira** [comment]
closed by #3738
