### ISSUE TITLE
Cannot use JSX unless the '--jsx' flag is provided as soon as new dependency is added

### ISSUE THREAD

**Issue by zivanovicb** [codesandbox/codesandbox-client#2822]
# 🐛 bug report

## Description of the problem
I create a React + TS sandbox, and everything looks fine - no errors. As soon as I add a new dependency [this](https://imgur.com/a/ITCHHxT) appears. If I refresh, there are no errors. Then I add a new package, and the error is there again.

## How has this issue affected you? What are you trying to accomplish?
Red is annoying.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1571237038-a19d42751
| Browser          | Chrome -  Version 77.0.3865.90 (Official Build) (64-bit)
| Operating System | macOS Mojave 10.14.5

**Comment by shobhitg** [comment]
+1 I am seeing this issue too. I am using Chrome Version 77.0.3865.90.

**Comment by SAPikachu** [comment]
+1 My project had been working fine until today, and then this error happens in all TSX files. I also see "Module XXX can only be default-imported using the 'esModuleInterop' flag" error in some of the files. I am using Firefox 69. Weirdedly it is working if I try to open the sandbox without logging in.

**Comment by burtek** [comment]
+1 same here

**Comment by 8clever** [comment]
+1

**Comment by wolverineks** [comment]
have you checked the version of typescript in package.json?
i had this error, then i changed it to `"typescript": "3.6.2"` and this error went away

**Comment by joshuaaron** [comment]
+ 1 for this and the esModuleInterop flag error, even though I've set this to true in my tsconfig. Pretty annoying bug.

**Comment by acerola1** [comment]
+1

**Comment by zizizheng** [comment]
+1
