### ISSUE TITLE
Preview fail when Instant preview enabled (Show preview on every keypress) in preferences. 

### ISSUE THREAD

**Issue by kishanbhimani** [codesandbox/codesandbox-client#2823]
## There are two scenarios:

1. With **Preview on edit** enabled
        Preview works fine when **_Instant preview_** disabled, But it **fails** when it's enabled
(as shown in attached screen recording)
2. With **Preview on edit** disabled
        Preview works fine on save.

[codesandbox_instant_preview_issue.mp4.zip](https://github.com/codesandbox/codesandbox-client/files/3737622/codesandbox_instant_preview_issue.mp4.zip)

**Comment by garethx** [comment]
I can reproduce this in a fork of the recorded sandbox at https://codesandbox.io/s/relaxed-thompson-yn6up
