### ISSUE TITLE
tsconfig options ignored after saving

### ISSUE THREAD

**Issue by jeremy-deutsch** [codesandbox/codesandbox-client#2836]
# 🐛 bug report

## Description of the problem

When tsconfig has strictness flags in `compilerOptions` (such as `strictNullChecks`, `strictBindCallApply`, or just `strict`), after you save the file, the editor stops showing type errors that reflect those flags. If unsaved changes are made to `tsconfig.json` in a separate tab, the tab with code will show the correct errors until the files are saved again.

## How has this issue affected you? What are you trying to accomplish?

TypeScript's `strictNullChecks` compiler flag is one of the main reasons I use TypeScript. Not being able to use it makes it a lot harder to safely traverse complicated data structures.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1571237038-a19d42751
| Browser          | Firefox 69.0.2 (64-bit)
| Operating System | ubuntu 16.0.4 LTS

**Comment by lbogdan** [comment]
Hey @jeremy-deutsch ,

Can you please detail a bit what's the current vs. expected behavior? I here see the expected `null` check errors inside your sandbox:

![image](https://user-images.githubusercontent.com/2083930/67100040-ab864480-f1c7-11e9-993e-22ffa46dd342.png)

**Comment by jeremy-deutsch** [comment]
That’s odd. I’ll look into it more and post screenshots once I’m at a computer, but for now, could you try opening `index.ts` and hitting ctrl-s/cmd-s, potentially after making some trivial edits? That tends to make the type errors disappear for me.

**Comment by jeremy-deutsch** [comment]
Yeah, confirmed that (I'll update the description).

Before hitting ctrl-s:
![Screenshot from 2019-10-18 09-18-05](https://user-images.githubusercontent.com/13303900/67110746-4bbc7900-f188-11e9-940e-180f596386ed.png)

After hitting ctrl-s:
![Screenshot from 2019-10-18 09-18-31](https://user-images.githubusercontent.com/13303900/67110748-4c550f80-f188-11e9-817c-de65e3b9b02a.png)

**Comment by lbogdan** [comment]
Closing this, as it should be fixed in #2913 , and we just deployed it. Please reopen if it's still an issue for you.
