### ISSUE TITLE
Explorer won't rescan

### ISSUE THREAD

**Issue by kai-wanders** [codesandbox/codesandbox-client#2840]
# 🐛 bug report

## Description of the problem

The file explorer doesn't refresh and there isn't/I can't find a way to force it to rescan. The files exist, I can link them, use them, and see them in the terminal, but there's no way to make the explorer see them.

## How has this issue affected you? What are you trying to accomplish?

They're not files I need to edit, so not being able to open them is only mildly annoying, but the download as zip option doesn't download what's actually there, it downloads what the explorer sees. So I get ghosts of files that should have been deleted and no sign of what should be there. The files I get in the download are always the latest version

I figured it was just a cache problem or similar, but no amount of clearing data/refreshing/restarting is making it go away

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome 79.0.3940.0
| Operating System | ChromeOS / Ubuntu 19.04

**Comment by lbogdan** [comment]
Hey @kai-wanders 

That's expected behavior under certain use-cases. A link to the sandbox would help to investigate further.

**Comment by smfils1** [comment]
@lbogdan I'm having the same issue. I'm using the node template so I can have the ability to use the terminal for a react project. However, if I create a file or clone a GitHub react project from the terminal only the package.json file shows on the file explorer. It would be great if codesandbox had the ability to sync with files in the sandbox directory so we will not have to manually create files from the file explorer.

**Comment by lbogdan** [comment]
Hey @smfils1 ,

We actually do, but there's scenarios in which we intentionally don't, of which you can read more about here: https://spectrum.chat/codesandbox/help/codesandbox-container-is-not-handling-package-changes-well~e42fa1e1-53b3-420f-9335-ae5e8a8422fa (not the OP, but my comment below).
