### ISSUE TITLE
Error "Uncaught ReferenceError: BrowserFS is not defined " in preview when create react sandbox 

### ISSUE THREAD

**Issue by zx6658** [codesandbox/codesandbox-client#2842]
# 🐛 bug report

## Description of the problem
`"Uncaught ReferenceError: BrowserFS is not defined "` Error in browser preview when make app with create react sandbox .
<img width="544" alt="스크린샷 2019-10-18 오후 9 24 37" src="https://user-images.githubusercontent.com/26598542/67094022-dc797000-f1ed-11e9-92d1-53020896e74e.png">
<img width="785" alt="스크린샷 2019-10-18 오후 9 23 37" src="https://user-images.githubusercontent.com/26598542/67094024-ddaa9d00-f1ed-11e9-9e9b-b6b13d8bb318.png">

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by lbogdan** [comment]
Hey @zx6658 ,

It seems to work here:

![image](https://user-images.githubusercontent.com/2083930/67094583-d4550c80-f1bc-11e9-9143-1482b1e6292f.png)

Can you also take a look at the "Network" tab, maybe requests are blocked by you ad-blocker or some other browser extension?

**Comment by bryceosterhaus** [comment]
I'm also seeing this issue. And I don't see anything being blocked in the network tab, I've disabled all browser extensions as well.

Codesandbox: PROD-1571237038-a19d42751
OS: Catalina, 10.15
Browser: Chrome(77.0.3865.120)

**Comment by bryceosterhaus** [comment]
I am no longer seeing this issue on `PROD-1571674162-0e9c0cfe9`

**Comment by NickCarducci** [comment]
I have this problem without Chrome extensions. Here is my "Network" inspect-tab.
<img width="812" alt="Network Codesandbox BrowserFS Screen Shot 2023-06-16 at 10 20 25 AM" src="https://github.com/codesandbox/codesandbox-client/assets/12148373/533ad94b-ec4a-4e53-a7c8-895595dc01a5">
