### ISSUE TITLE
Invalid "cannot find module" warning

### ISSUE THREAD

**Issue by mindplay-dk** [codesandbox/codesandbox-client#2870]
# 🐛 bug report

I seem to run into this error a lot lately:

![image](https://user-images.githubusercontent.com/103348/67147202-09339300-f293-11e9-8b55-c70639c58e57.png)

It must be a false positive? I am able to import the function and run it, so. 🤷‍♂️

Here's a link to the sandbox:

https://codesandbox.io/s/ant-design-playground-p5lvj

**Comment by caesarsol** [comment]
I get it when types definitions cannot be found. 
Example: same error with `lodash`, installing `@types/lodash` fixed the problem. 

Is that your case?

**Comment by mindplay-dk** [comment]
Oh, sorry!

The package was *written* in TS, so I just assumed... But apparently the author forgot to actually emit and publish the typings. 😶
