### ISSUE TITLE
compiler error question for the project of master branch

### ISSUE THREAD

**Issue by bingjianguo** [codesandbox/codesandbox-client#2875]
# ❔ Question
Is there something wrong for the  compilation error for master branch. For example:

1. in the file "packages/notifications/tsconfig.json" and packages/common/tsconfig.json
It missed the skipLibCheck: true in the compilerOptions section, if not, it will cause "Duplicate identifier" ts compilation errors

2. in the file "standalone-packages/monaco-typescript/src/lib/emmet/expand/extract-abbreviation.js"
About the line 300, there are spread operator of es6, but the compiler process does not include the babel deps. They will also cause compilation errors.

could you help to resolve these problem?

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by lbogdan** [comment]
Hey @bingjianguo ,

This is really strange, as we're all working on master without any issues. Can you please tell us what steps you followed to setup your local development environment?

**Comment by SaraVieira** [comment]
Closed for lack of activity
