### ISSUE TITLE
Display an helpful error message when Privacy protections may break the app preview pane

### ISSUE THREAD

**Issue by Akryum** [codesandbox/codesandbox-client#2877]
# 🌈 Feature

In some cases, Privacy protections from the browser may break the app preview pane. Currently it displays nothing (blank). It would be nice to have an error message instead.

When the App Preview iframe doesn't load, display an error message like:

```
App couldn't be loaded
Please check you are not blocking third-party cookies
```

To reproduce this, you can go to Firefox settings, under the Privacy & Security > Content blocking section, select Custom and then select Cookies > All third-party cookies

![Screenshot from 2019-10-20 11-21-21](https://user-images.githubusercontent.com/2798204/67159074-1f4b5d00-f340-11e9-829e-98a6a61d9e5f.png)

**Comment by arthurdenner** [comment]
@Akryum, is there a way to know if this config is active?

**Comment by Akryum** [comment]
I guess an error is thrown like in the OP?
