### ISSUE TITLE
Cannot copy and paste even any browser

### ISSUE THREAD

**Issue by changicho** [codesandbox/codesandbox-client#2904]
# 🐛 bug report

## Description of the problem

![error](https://user-images.githubusercontent.com/38618187/67269985-b3f5bc80-f4f2-11e9-9033-10773a37ca53.gif)

i cannot copy and paste in editor even in any of my brower...

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Crhome, Edge ...
| Operating System | windows 10 edu

**Comment by lbogdan** [comment]
Hey @changicho ,

What if you use the keyboard shortcuts (Ctrl-C / Ctrl-V) instead?

**Comment by changicho** [comment]
> Hey @changicho ,
> 
> What if you use the keyboard shortcuts (Ctrl-C / Ctrl-V) instead?

Sadly, it does not work either

**Comment by changicho** [comment]
i can copy & paste using my desktop, but i cannot in my laptop. even it is exactly same OS (windows 10 edu).

> Hey @changicho ,
> 
> What if you use the keyboard shortcuts (Ctrl-C / Ctrl-V) instead?

**Comment by seta-hungDang** [comment]
Yes I have the same issue and it's been like this for months. Anyone has a solution?
