### ISSUE TITLE
Cannot set property 'innerHTML' of null

### ISSUE THREAD

**Issue by Nasdan** [codesandbox/codesandbox-client#2907]
# 🐛 bug report

## Description of the problem

Getting error (Cannot set property 'innerHTML' of null) when create new plain vanilla project. It looks like it doesn't wait for the document to be mounted

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  
| Browser          | Chrome / Versión 77.0.3865.120 (Build oficial) (64 bits)
| Operating System | Windows 10

**Comment by lbogdan** [comment]
Hey @Nasdan ,

We had some temporary issues which might be related. Is this still happening for you?

**Comment by Nasdan** [comment]
Hi @lbogdan, it looks like it's working now, even if I refresh the example. Thank you.

![image](https://user-images.githubusercontent.com/4374977/67313950-2ae78100-f504-11e9-8703-b368e8671d02.png)

It was weird because the react examples was working and it doesn't the plain vanilla ones.
I don't know if it makes sense for you.

Thank you :)

**Comment by DallasCarraher** [comment]
I may be doing something wrong here but I noticed this is still happening, at least for me.

my index.js looks like this
```javascript
let header = document.getElementById("content");
header.innerHTML = changeArray(myArray);
```
my html looks like this
```html
<html>
  <body>
    <div id="app">
      <h1 id="content"></h1>
      <input type="text" />
    </div>
  </body>
  <script src="src/index.js"></script>
</html>
```

If I click the refresh button on the repl browser I get a typeError:
`Cannot set property 'innerHTML' of null`

**Comment by DallasCarraher** [comment]
this seems to be due to not having a <head> element. I thought in HTML5 however this could be omitted?
