### ISSUE TITLE
¿How to set which port is considered the main one?

### ISSUE THREAD

**Issue by hacknlove** [codesandbox/codesandbox-client#2909]
# ❔ Question
¿How to set which port is considered the main one?

https://codesandbox.io/s/piano-wkfoe

This open two ports, the GraphQL 4000 and the client 3000.

4000 get opened first and then becomes Main.

I couldn't find anythis about this nor in the documentation, neither here, nor in Internet. 

It would be great to be able to set this up in codesandbox.config.json

**Comment by hacknlove** [comment]
Now I am delaying 5 seconds the GraphQL server start, so the client port opens first and becomes the main port.

But it is an ugly way to do it, and very prone to problems with race conditions.

**Comment by CompuIves** [comment]
Hey @hacknlove, you can force a default port in the sandbox by creating `sandbox.config.json` and setting the contents to:

```
{
  "container": {
    "port": YOUR_PORT
  }
}
```

I hope this helps! I'll close the issue now, please open a new issue if you have a new question 😄 .

**Comment by hacknlove** [comment]
Yes. It works.

Thank you very much!
