### ISSUE TITLE
Typescript: modules not founds

### ISSUE THREAD

**Issue by dagatsoin** [codesandbox/codesandbox-client#2911]
# 🐛 bug report

## Description of the problem
I reopened a project wrote two weeks ago. All my typescript modules became not founds.

## How has this issue affected you? What are you trying to accomplish?
![image](https://user-images.githubusercontent.com/3670794/67411775-6fcfee00-f5be-11e9-9bbd-191472d39845.png)
As soon I make a modification, all my typescript modules becomes not found.
If I refresh the page, I got back my modules back. But it return not found as soon I make a change.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/ravioli-mrenz

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1571674162-0e9c0cfe9
| Browser          | Chrome Version 77.0.3865.120 
| Operating System | OSX High Siez

**Comment by lbogdan** [comment]
Closing this, as it should be fixed in #2913 , and we just deployed it. Please reopen if it's still an issue for you.
