### ISSUE TITLE
Next.js - custom _app.js not being detected in pages directory

### ISSUE THREAD

**Issue by eckmLJE** [codesandbox/codesandbox-client#2917]
# 🐛 bug report

## Description of the problem

In a Next.js sandbox, adding a `_app.js` file to the pages directory to override/extend the default is not being detected by the sandbox. `_app.js` is not being included in the next.js build / dev process.

## How has this issue affected you? What are you trying to accomplish?

I'm trying to experiment with persisting / manipulating components between page changes by adding layout and header components to `_app.js`

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1571674162-0e9c0cfe9
| Browser          | Chrome 77.0.3865.120 (Official Build) (64-bit)
| Operating System | Mac OS Catalina 10.15

**Comment by lbogdan** [comment]
Hey @eckmLJE ,

Did you get this to work in the meanwhile? It seems to be working now:

![image](https://user-images.githubusercontent.com/2083930/67951736-bf34a080-fbf4-11e9-9626-736a35a42bbd.png)

**Comment by siddharthkp** [comment]
I can guess what happened here.

When you add `_app.js`, you have to restart nextjs (as far as I know, it doesn't restart itself on `_app.js` creation)

On CodeSandbox, you can restart the server from the Server tab on the left.

![Screenshot 2019-10-31 at 3 05 38 PM](https://user-images.githubusercontent.com/1863771/67953805-1c7a2300-fbf0-11e9-8143-0ada5e9dd01f.png)

**Comment by siddharthkp** [comment]
If it doesn't work for you or if there is any additional context you'd like to add, feel free to reply here and we'll re-open this issue.

**Comment by bfunc** [comment]
Thanks! ```Restart Server``` button makes a lot of sense. Good to know that it exists 👍
