### ISSUE TITLE
Not able to Type/Edit in the editor.

### ISSUE THREAD

**Issue by sowmyy** [codesandbox/codesandbox-client#2919]
# 🐛 bug report

Not able to type/edit in the editor.

Сodesandbox  
Google Chrome | Version 78.0.3904.70 (Official Build) (64-bit)
Ubuntu

[CodeSandbox_Type_Bug.zip](https://github.com/codesandbox/codesandbox-client/files/3766648/CodeSandbox_Type_Bug.zip)

**Comment by garethx** [comment]
I'm unable to open the video, but do you still get the same issue when viewing in a private or incognito window?

**Comment by SaraVieira** [comment]
Closed for lack of response
