### ISSUE TITLE
Unable to delete ZEIT integration

### ISSUE THREAD

**Issue by fauna-ryan** [codesandbox/codesandbox-client#2935]
# 🐛 bug report

## Description of the problem
Red "X" next to ZEIT integration at `Preferences` | `Integrations` does nothing. Error in console: 405 response to `DELETE` request to https://codesandbox.io/users/current_user/integrations/zeit

## How has this issue affected you? What are you trying to accomplish?
Unable to delete ZEIT integration

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Browser          | Chrome/77.0.3865.120 (Official Build) (64-bit)
| Operating System | macOS Mojave/10.14.6

**Comment by garethx** [comment]
Trying to reproduce - have you been able to use the Zeit integration or does it not work with your current account linked? when first connecting Zeit to CodeSandbox did you exit at some stage before finishing the OAuth flow?

**Comment by fauna-ryan** [comment]
thanks for looking into it!
- i can use the ZEIT integration
- i did not exit the OAuth flow when first connecting; completed without error
