### ISSUE TITLE
repo not associated with github repo anymore

### ISSUE THREAD

**Issue by mrblog** [codesandbox/codesandbox-client#2936]
# 🐛 bug report

## Description of the problem

I have a sandbox at https://zhuym.codesandbox.io/. I used the "Create repo" option in the Github tab of the sandbox to create the repo https://github.com/mrblog/devMission-Laptimes-ReactJS but now the Sandbox doesn't appear to be associated with the repo anymore. Under the Github tab on the sandbox it doesn't have the PR or commit options anymore but instead has an option to create a repo. I tried to create new repo from the sandbox and it fails with an error "Page not found"

## How has this issue affected you? What are you trying to accomplish?

I no longer have a github repo syncing with the sandbox. I want to have a github repo for students to review and fork.

### Link to sandbox: [link]() (optional)

https://zhuym.codesandbox.io/

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | idk? |
| Browser          | Chrome |
| Operating System | Mac OS X |

**Comment by siddharthkp** [comment]
Hey @mrblog It seems like a different sandbox: https://codesandbox.io/s/new-9bvmo is linked to the repo you mentioned.

Not sure what happened here. Can you repeat the steps and list them down for me here so I have more context on digging up the bug?

**Comment by mrblog** [comment]
Yeah, I was able to import the repo to a new Sandbox and rename the old broken one. I don't know how to duplicate what happened that made the sandbox no longer be associated with the github repo that it created it because it just stopped working as far as I can tell. At least I'm back working again with the new sandbox for now.

**Comment by danielo515** [comment]
I am facing this same exact issue.
In my case I think it is because codesandbox it is getting confused by the fact that I forked from a public repo? Then, in some way, despite I open my own fork, codesandbox was still pointing to the public sandbox, or something like that.

**Comment by danielo515** [comment]
Here is my repo if you want to take a look:
https://codesandbox.io/s/timer-app-prototype-0c38z

and this is the associated github repository (I created it from codesandbox):

https://github.com/danielo515/Time-track-prototype

**Comment by danielo515** [comment]
If I open the link that is on the generated repository I can see this:

![image](https://user-images.githubusercontent.com/2270425/73263351-aa09e680-41d0-11ea-95c3-eaf516faa3a7.png)

As you can see, it still points to the Material demo sandbox, instead of my actual sandbox.
That "Material demo" is a sandbox that I started as an anonymous user, when I realized I was not logged in I just log in and I had to for that sandbox. Since then I have been working on my own sandbox and I created the repository from it, not sure why it still points to the old one.
