### ISSUE TITLE
Cannot load the result in the right side browser

### ISSUE THREAD

**Issue by ez-dev** [codesandbox/codesandbox-client#2942]
# 🐛 bug report

## Description of the problem
When I open any sandbax, the browser on the right which shows the result tries to load xxxx.csb.app which the dns of this domain cannot be resolved.

for example for this sandbox:
https://codesandbox.io/s/64pw7275nw
the browser tries to load "https://64pw7275nw.csb.app/" which is not working.

This problem happens at my workplace. When I try it on my cell phone on a different network, browser side, loads "https://64pw7275nw.codesandbox.io/" not "64pw7275nw.csb.app" which works perfectly

### Your Environment
Windows 10, Firefox, Chrome and Edge

**Comment by garethx** [comment]
Sorry about that - this should be resolved now!
