### ISSUE TITLE
API call Proxy redirection issue for React in codesandbox

### ISSUE THREAD

**Issue by iamdileepkumar** [codesandbox/codesandbox-client#2944]
# ❔ Question

Hi, 

Proxy redirection for api calls is not working in the react project present in codesandbox, but working fine in my local. And the app is behaving wierd and getting 405 status code for api call.

Am trying to call the api that is present in codesandbox (https://codesandbox.io/s/devconnector-api-1y5l4). I have kept the codesandbox hosted api link in proxy field in my react package.json.("proxy": "https://1y5l4.sse.codesandbox.io")

When i give the codesandbox hosted api link in react client present in my local, it is working fine.

But when i give the same codesandbox hosted api link in react client present in codesandbox, it is not working, getting 405 code in network call, and app is behaving wierd .
 
P.S: Enabled cors in my backend

### Link to sandbox: React Client - https://codesandbox.io/s/devconnector-client-uqunk
Node API - https://codesandbox.io/s/devconnector-api-1y5l4

**Comment by lbogdan** [comment]
Hey @iamdileepkumar ,

This is expected behavior, as `create-react-app` sandboxes run in the browser, so there's no way to support the API proxy feature. You could however use a server sandbox for the client project, too, as shown in my comment here: https://github.com/codesandbox/codesandbox-client/issues/2354#issuecomment-527564461.

Does that address your issue?

**Comment by lbogdan** [comment]
> Were you telling to create 'sandbox.config.json' file in the react client root, and 'template' key in it or 'proxy' key in it?

No, just create `sandbox.config.json` in the repo root, with
```json
{
  "template": "node"
}
```
and re-import (reload) the sandbox in CodeSandbox, that should turn it into a server sandbox.

> And i have tried without proxy, by adding the api link(sandbox hosted api url) directly in the actions, but failed to do api call, got the same 405 status code.(but working fine in local without proxy).

Can you link me to a sandbox in which this happens?

**Comment by lbogdan** [comment]
Ok, but how can I actually trigger an API request and see the `405` response you're referring to?

**Comment by iamdileepkumar** [comment]
Jus open the below codesandbox's in two tabs,

React Client - https://codesandbox.io/s/devconnector-client-uqunk
Node API - https://codesandbox.io/s/devconnector-api-1y5l4

Then in the react sandbox, in the browser, in the app, click on login link, give some random cred and click login. Then see in the network tab, api/auth call is rejected with status code 405.

**Expected**: It should throw an error to give correct credentials

**Comment by lbogdan** [comment]
What I see right now is that it users the client sandbox URL, which would be right when using an API proxy:

![image](https://user-images.githubusercontent.com/2083930/67967682-b4870500-fc0e-11e9-8fa6-4454982f6d64.png)

You should use the server sandbox URL, like `POST https://1y5l4.sse.codesandbox.io/api/auth`.

**Comment by iamdileepkumar** [comment]
Hey @lbogdan , the concept of proxy in CRA is to redirect the API call to the proxy set in the package.json.

Eventhough api call seen in network tab is https://uqunk.csb.app/api/auth, but the actual API call that was done from our app is like POST https://1y5l4.sse.codesandbox.io/api/auth.

Request u to please, go through below links for better understanding of proxy particularly in CRA
https://create-react-app.dev/docs/proxying-api-requests-in-development/
https://coursework.vschool.io/setting-up-a-full-stack-react-application/

So the actual API call as per the given docs is POST https://1y5l4.sse.codesandbox.io/api/auth, and getting 405 rejection.

**Comment by iamdileepkumar** [comment]
Hey @lbogdan , 


> No, just create `sandbox.config.json` in the repo root, with
> 
> ```json
> {
>   "template": "node"
> }
> ```

This is super cooool. This is working absolutely fine when creating sandbox.config.json with 'template' key in it. And a big thanks !!

But eager to know why this proxy doesn't work in the create-react-app sandbox and why does it work in server sandbox? 
Can you explain in breif ? :)

**Comment by lbogdan** [comment]
Glad the server sandbox is working!

> But eager to know why this proxy doesn't work in the create-react-app sandbox and why does it work in server sandbox?

As I said in my first comment, `create-react-app` sandboxes run entirely in the browser, which is a limited environment, and there's no (easy) way of implementing the API proxy feature that local `create-react-app` apps support. Server sandboxes solve this issue by running the sandbox inside a container, pretty much mirroring your local development environment.

**Comment by iamdileepkumar** [comment]
Yeah I got it now. It is the container which is making the difference where we host our apps in container like AWS or Azure.

Thanks for your support @lbogdan  :)
Closing the issue.
