### ISSUE TITLE
Support git repos other than Github

### ISSUE THREAD

**Issue by yoonwaiyan** [codesandbox/codesandbox-client#296]
Not sure if it's being requested before, but I would like CodeSandbox to be able to import any public repo other than Github(by just providing a git repo HTTPS link maybe), is that possible? I've came to this idea because I have a repo to demo during tutorials sessions but I don't want to flood my Github repo with small repos so I'm using Gitlab for the repo for now.

**Comment by Piterden** [comment]
I use gitlab too. Also bitbucket sometimes.
I think, the best would be the universal client for any `git` server.

**Comment by shovelend** [comment]
Bitbucket support would be amazing 👍 Great demo on the React-Europe conf!

**Comment by nicdinh** [comment]
@CompuIves is there any timeline or updates for adding this enchancement? I am currently interested in using Bitbucket along with codesandbox and I am wondering if this currently in the works.

**Comment by brandonmikeska** [comment]
Our company uses Bitbucket, and it would be a huge time saver if CodeSandbox supported it :)

**Comment by yoonwaiyan** [comment]
@jensMG I believe this could be done through a local clone from CodeSandbox as long as a git repo gives public access. For private repos and in this case of using BitBucket, CodeSandbox users would need to authorize access to their BitBucket account through OAuth so that CodeSandbox could get the list of repos and clone it through the [API](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D).

**Comment by Saeris** [comment]
Added this to our public backlog. Closing for now, please refer here for the status of this feature:

https://www.notion.so/Add-alternative-Git-repositories-support-7edda4f23a9041fca27cb0d752447ed7
