### ISSUE TITLE
editor is not running the code

### ISSUE THREAD

**Issue by saachibhayani** [codesandbox/codesandbox-client#2964]
# 🐛 bug report
I wrote most of this code on codepen.io and then I uploaded it to github so I could transfer it to codesandbox.  In codesandbox, the preview is just a blank screen.  

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/new-gvc1k?fontsize=14

**Comment by Austinmoore1492** [comment]
You just need to change welcome.html to index.html and it should work.

**Comment by saachibhayani** [comment]
This partially worked.  The css is not working like it should.  When I run it on codepen the css does work.

**Comment by Austinmoore1492** [comment]
@saachibhayani I think it has to do with your environment being create-react-app. I downloaded the files and used the Static template, under client templates and it works.

**Comment by SaraVieira** [comment]
Hey!

This was indeed a problem with the enviroment, we default to `create-react-app`, I chamnged it to static and indeed it does work

https://codesandbox.io/s/eportfolio-qb92c

The issue with the css is that you were missing the `./` in the start and adding that makes the css work
