### ISSUE TITLE
Parcel with Pug doesn't work

### ISSUE THREAD

**Issue by kidonng** [codesandbox/codesandbox-client#2965]
# 🐛 bug report

## Description of the problem

Using Pug with Parcel doesn't work, preview shows a blank screen. I checked preview's HTML and found no output but CodeSandbox's own template.

## How has this issue affected you? What are you trying to accomplish?

I want to move one of my repo to CodeSandbox but can't make it work. I've also tried Node envrionment but can't connect to the sandbox which is another story 👀

### Link to sandbox: [link](https://codesandbox.io/s/silly-payne-i2let) (optional)

Linked sandbox comes from [another person](https://github.com/codesandbox/codesandbox-client/issues/1135#issuecomment-534224029) that appears to have the same problem.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1572624626-def377908 |
| Browser          | Chrome 80.0.3955.4|
| Operating System | Windows 10 19013.1000|

**Comment by SaraVieira** [comment]
Hey!

Yeah this i still an issue but I am gonna close in favor of https://github.com/codesandbox/codesandbox-client/issues/1135 as it was there and change the title in it :/
