### ISSUE TITLE
Can I integrate codesandbox in my project?

### ISSUE THREAD

**Issue by chj-damon** [codesandbox/codesandbox-client#2966]
# ❔ Question

I want to preview some code in my project, I know codesandbox can do the same thing, so I think it would be perfect if I can use codesandbox directly in my project.
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by crazymousethief** [comment]
See this https://www.npmjs.com/package/smooshpack

**Comment by siddharthkp** [comment]
@chj-damon Hi 👋 

Can you add a little more info about what you're trying to accomplish.

If you'd like to show the preview of a snippet of code, you might want to embed a sandbox. Docs here: https://codesandbox.io/docs/embedding

Are you also looking at modifying the code programmatically, via options/props?

**Comment by SaraVieira** [comment]
Closed by lack of response
