### ISSUE TITLE
Cannot import GitHub repository

### ISSUE THREAD

**Issue by Strahinja** [codesandbox/codesandbox-client#2972]
# 🐛 Cannot import GitHub repository

## Description of the problem

When trying to import a repository from GitHub (created by exporting to GitHub from Codesandbox container which was deleted, with emptied trash), I get the following message:

> A sandbox error occurred, you can refresh the page to restart the container.

Upon refresh, I get the same error again, and my sandbox container can't start.

## How has this issue affected you? What are you trying to accomplish?

Create a test example on Codesandbox linked to a GitHub repository.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest
| Opera          | Latest
| Windows 10 | Latest

**Comment by lbogdan** [comment]
Hey @Strahinja ,

There's an ongoing issue with [githack](https://raw.githack.com), a 3rd party service we're using for binary static assets for sandboxes from GitHub. We just added a fallback to GitHub raw URLs, can you please try again and confirm it's working?

**Comment by Strahinja** [comment]
I just tried it from Opera Touch on my phone, it works now. I was able to create the sandbox. Thanks for the help.

**Comment by realDeve** [comment]
Perhaps your repo is private. you will need to make it public or upgrade to Pro.
