### ISSUE TITLE
Support `codesandbox` field in `package.json`

### ISSUE THREAD

**Issue by CompuIves** [codesandbox/codesandbox-client#2973]
# 🌈 Feature

Similar to how we handle the `browser` field in `package.json`, we would support a `codesandbox` field. Some files don't work in CodeSandbox, like the `worker-loader`, and this would allow the library author to give a different version that works in CodeSandbox. The nice idea behind this is that we would still be able to make it work when exporting to zip, which is the most important goal.

Reference: https://twitter.com/james_k_nelson/status/1190468271511728128

**Comment by lbogdan** [comment]
I was also thinking of using the `codesandbox` field in `package.json` as an alternative to `sandbox.config.json`, so maybe we can somehow conflate the two.

**Comment by MichaelDeBoey** [comment]
Maybe use [`cosmiconfig`](https://github.com/davidtheclark/cosmiconfig) so most commonly used config file types are supported? 🤔

**Comment by flickz** [comment]
Hey guys, I'm interested in helping with this. I'm currently looking for how `browser` field in `package.json` is handled, I'm thinking it should be within [`addNpmDependency`](https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/app/overmind/namespaces/editor/actions.ts#L108-L131) action but it isn't I need a pointer here.

**Comment by luisherranz** [comment]
Would this mean that we could add the fields that now need to be added to the `sandobx.config.js` file to the `codesandbox` field of the `package.json`? For example, something like this:

```json
// package.json
{
  "codesandbox": {
    "infiniteLoopProtection": true,
    "hardReloadOnChange": false,
    "view": "browser",
    "template": "node"
  }
}
```

**Comment by luisherranz** [comment]
The issue has not been resolved 🙂

**Comment by SaraVieira** [comment]
Hey!

Thank you for bringing this to our attention, I have just added it to our internal backlog that we do want to make public but for now, it's all in notion.

I will be closing but to make sure what we have in GitHub is just issues and all our feature requests are tracked in our roadmap.

The people needed have also been pinged to make sure this gets done as soon as possible

Again, thank you!
