### ISSUE TITLE
🐛 Sandboxes with large packages in dependencies don't work

### ISSUE THREAD

**Issue by BingoRUS** [codesandbox/codesandbox-client#2983]
# 🐛 bug report

## Description of the problem

Sandboxes with large packages in dependencies don't work anymore because jsdelivr has a 50Mb limit of package size. Previously, those sandboxes downloaded modules from unpkg. I think the issues appeared after [this commit](https://github.com/codesandbox/codesandbox-client/commit/7d3d90d43ec09df5f8aef8c55f0878c71e22d2d7#diff-d226da871ae5532ae042e1a98dca55c5).

**Comment by MartinKolarik** [comment]
We are currently looking into ways of significantly increasing this limit at jsDelivr, but in the meantime, I'd recommend falling back to unpkg for requests that return `403` status.

**Comment by MartinKolarik** [comment]
We increased the limit to 100 MB (will consider increasing it further soon) so the sandbox should work now.

**Comment by siddharthkp** [comment]
Can confirm, the sandbox in the issue is opening 💯
