### ISSUE TITLE
Nuxt preview is constantly reloading

### ISSUE THREAD

**Issue by MarcelloTheArcane** [codesandbox/codesandbox-client#2991]
# 🐛 bug report

## Description of the problem

I'm trying to run the Layouts example on the Nuxt documentation: https://nuxtjs.org/examples/layouts/ 

When I try to view it in the browser, the page flashes (constant reloading, which you can see from the repeated console logs)

See for yourself! https://gofile.io/?c=nHQGJT 

## How has this issue affected you? What are you trying to accomplish?

The sandbox is unresponsive ☹️ 

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1572970344-b89511c06 |
| Browser          | Chrome 78.0.3904.70 (Official Build) (64-bit) (cohort: Stable) |
| Operating System | Windows 10 Pro, 1903 |

**Comment by MarcelloTheArcane** [comment]
Of note, it _only_ happens inside the https://nuxtjs.org/examples/layouts/ embedded page. Viewing on [codesandbox.io](https://codesandbox.io) is fine.

**Comment by lbogdan** [comment]
Hey @MarcelloTheArcane ,

Thank you very much for this report, it helped us pinpoint an issue we were chasing for a couple of days now! We just deployed a fix, can you please test and let us know if this is still happening?

**Comment by MarcelloTheArcane** [comment]
Hello @lbogdan,

Awesome, looks like your fix has sorted it! I'm not getting an issue on that URL any more.
