### ISSUE TITLE
CORS error deploying to Netlify

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#2992]
# 🐛 bug report

## Description of the problem
The following errors occur when trying to deploy https://codesandbox.io/s/mycoal-uixmf to Netlify ![Screenshot 2019-11-06 at 10 39 23](https://user-images.githubusercontent.com/1830035/68291519-efab8d00-0081-11ea-9936-b10a0d9684a1.png)

## How has this issue affected you? What are you trying to accomplish?
Unable to deploy sandbox to Netlify

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  PROD-1572970344-b89511c06
| Browser          | Chrome
| Operating System | OS X

**Comment by garethx** [comment]
Same with https://codesandbox.io/s/zealous-chatelet-vn9ie

**Comment by lbogdan** [comment]
Looks like the root issue here is that `POST` request returns 413, which means "Payload Too Large". The CORS error is probably because of their error response not having CORS headers, which looks like a bug on their part.

**Comment by lbogdan** [comment]
Oh, nevermind Netlify, I didn't pay attention to the hostname, it's actually our deployment microservice. 🙂

**Comment by OlaoyeVic** [comment]
Please I'm also having a problem deploying to netlify. Please help urgently

![codesandbox](https://user-images.githubusercontent.com/52793798/133582785-6e0ce4c0-1563-4d2f-9506-8830c745bc38.png)

[https://codesandbox.io/s/coldstone-order-app-bpyw1](url)
