### ISSUE TITLE
How to open the ‘web box model preview’ function？like chrome

### ISSUE THREAD

**Issue by ottopan** [codesandbox/codesandbox-client#2996]
# ❔ Question

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest
| Browser          | Chrome
| Operating System |Win 10

![image](https://user-images.githubusercontent.com/18224971/68374516-ffa99680-017f-11ea-9484-d39053fab910.png)
![image](https://user-images.githubusercontent.com/18224971/68374544-0d5f1c00-0180-11ea-9fa9-fdd3950be74d.png)

**Comment by SaraVieira** [comment]
Hey!

Sorry this is not something we support also because of browser constrains :(
