### ISSUE TITLE
Svelte/SCSS not working

### ISSUE THREAD

**Issue by reed-jones** [codesandbox/codesandbox-client#3012]
# 🐛 bug report

## Description of the problem
Svelte preprocessing is not working. whenever i use scss feature I got `ParseError: Identifier is expected` in the console (since its not valid css anymore). I have tried several preprocessors but the all fail in the same way

## How has this issue affected you? What are you trying to accomplish?
I was trying to use scss in a svelte project. The same config works fine locally.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | frosty-dream-i4jti |
| Browser          | Chrome v78.0.3904.97 |
| Operating System | Windows 10 Pro 1903 |

**Comment by frederikhors** [comment]
Also if I wanna import a simple `style.css` both in a svelte file or in `index.html` with a simple `import "./style.css" nothing happens.

Why?

**Comment by garethx** [comment]
@frederikhors do you have an example sandbox?

**Comment by frederikhors** [comment]
> @frederikhors do you have an example sandbox?

https://codesandbox.io/s/githubcom-codesandbox-client-issues-3012-pc62l
