### ISSUE TITLE
Could we get `strict: true`for vanilla-ts and react-ts Sandboxes?

### ISSUE THREAD

**Issue by phryneas** [codesandbox/codesandbox-client#3013]
# ❔ Question

Right now, new vanilla-ts and react-ts sandboxes are missing the line `"strict": true` in their `tsconfig.json`. And unfortunately, without this line, the strict compiler option defaults to `false`, leaving a very inconsistent development experience.

Now, one could argue that this being the default value for that option, it should also be the default. But I guess that this is just the default for historic reasons and to prevent breakage in existing projects.  
Executing `tsc --init` to get a new `tsconfig.json` defaults to include `strict: true` since I can remember (at least for a few years now) - and nowadays I believe that this behavior is what devs would be expecting when bootstrapping a new TypeScript project.

So: would you consider adding this line? 

If so, I'd be more than happy to do a PR against the templates, if you point me to the right direction - the https://github.com/codesandbox/codesandbox-templates repository doesn't seem to reflect current base templates correctly, so I might be looking at the wrong spot.

PS: from [the TS 2.3 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#new---strict-master-option), `strict: true` has been included by default on new `tsconfig.json` files as generated by `tsc --init` as long as the option itself exists and as I had suspected only defaults to `false` to prevent breakage.

**Comment by SaraVieira** [comment]
Hey!

Good idea and added in both, any new projects from either `react-ts` or `vanilla-ts` will have that option added in the config

**Comment by phryneas** [comment]
Thank you very much, now I can delete my custom template :)

**Comment by phryneas** [comment]
@SaraVieira unfortunately, this is still not active the vanilla+ts or react+ts sandboxes. 

Is this just still waiting for the next release/deploy or is this a regression/bug/whatever?

**Comment by phryneas** [comment]
Okay, seems that react+ts now has it, but it's still missing in vanilla+ts - I just created this sandbox: https://codesandbox.io/s/vigorous-bhaskara-f3sle

**Comment by phryneas** [comment]
Also, this is solved wrongly.. :/

```json
{
    "strict": true,
    "include": [
        "./src/*"
    ],
    "compilerOptions": {
        "lib": [
            "dom",
            "es2015"
        ],
        "jsx": "react"
    }
}
```

should be 

```diff
{
-    "strict": true,
    "include": [
        "./src/*"
    ],
    "compilerOptions": {
+        "strict": true,
        "lib": [
            "dom",
            "es2015"
        ],
        "jsx": "react"
    }
}
```

instead.

@SaraVieira could you please take another look?
