### ISSUE TITLE
🌈 Customize container starter script

### ISSUE THREAD

**Issue by maritaria** [codesandbox/codesandbox-client#3020]
# 🌈 Feature

Be able to specify a specific yarn script to run as main for backend container projects.
The main reason being that `now` (zeit) and codesandbox both use the same `yarn start` script for running the application. While developing code in codesandbox this is fine but if you then want to deploy the project to production the same main is used.

I like to use nodemon to auto-rebuild my typescript backend project. But I dont want this to also be the behaviour to run on production deployments on zeit.

**Comment by lbogdan** [comment]
Hey @maritaria ,

We're looking for the script to start in this exact order: `dev`, `develop`, `serve`, `start`, so you can use `dev` to run inside the sandbox container, and `start` to run on Now.

**Comment by maritaria** [comment]
That resolves my issue
