### ISSUE TITLE
Cannot delete sandboxes after moving to trash

### ISSUE THREAD

**Issue by cdevguy117** [codesandbox/codesandbox-client#3026]
Cannot delete sandboxes after moving to trash, getting the error:
"Network Error: ServerParseError: Unexpected end of JSON input"

**Comment by aptrov** [comment]
Any update on this issue? I need to recover a couple of sandboxes from Trash but getting the same error, regardless of OS or browser.

**Comment by arthurdenner** [comment]
@cdevguy117, can you check if this is still happening to you? It's not happening for me anymore - it used to. @aptrov, could you test it too?

If it's not happening anymore, could you please close the issue? Thanks!

**Comment by aptrov** [comment]
Not happening to me anymore neither.

**Comment by arthurdenner** [comment]
cc @lbogdan. I think you can closed this.

**Comment by cdevguy117** [comment]
Hi everyone, sorry for not responding, I didn't use this account for a while, I've just checked and the
projects I've tried to delete has been deleted successfully, also tested it again by creating another Node.js project and delete it and it seems to work properly.

Thanks
