### ISSUE TITLE
What does the "Project view" toggle do?

### ISSUE THREAD

**Issue by mark-friedman** [codesandbox/codesandbox-client#3027]
# ❔ What does the "Project view" toggle do?

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by garethx** [comment]
The toggle turns module view on and off - when it's off it's in project view. Module view allows you to show just the component you're working on in the preview. When it's in project view it shows the full project in preview.

**Comment by SaraVieira** [comment]
Closed as the answer was given :)
