### ISSUE TITLE
Stuck in Transpiling Modules 

### ISSUE THREAD

**Issue by ogonzal87** [codesandbox/codesandbox-client#3036]
# 🐛 bug report

## Description of the problem
The app is stuck in Transpiling Modules.. and does not give me an error. 

## How has this issue affected you? What are you trying to accomplish?
I am building an app that showcases my personal design system and I need to way for people to see the code. I am not able to continue as I am not sure how to fix the issue.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1573738286-c05030adf
| Browser          | all of them
| Operating System | MacOS Mojave

**Comment by yeion7** [comment]
hey @ogonzal87 👋

the root of this problem is the sandbox has a few recursive renders, and these generate an infinite loop in the compiler

`LeftNav` renders `ColorPage` and `ColorPage` renders `LeftNav`
`HomePage` renders `LeftNav` and `LeftNav` renders `HomePage`

I forked your sandbox and remove those loops and seems works

https://codesandbox.io/s/oskrhq-playground-app-k3r2w

**Comment by ogonzal87** [comment]
Ohhhhh! Thank you so much!! Makes sense. Any way of catching that in the future would be super helpful. Like an error message or something like that. 

Thanks for your help!

**Comment by ogonzal87** [comment]
Ohhhhh! Thank you so much!! Makes sense. Any way of catching that in the future would be super helpful. Like an error message or something like that. 

Thanks for your help!

**Comment by yeion7** [comment]
I'm not sure if is possible, codesandbox eval each file and we can't know if the evaluation is done or fall in an infinite loop, I think this is an example of [Halting Problem](https://www.youtube.com/watch?v=macM_MtS_w4), but maybe @CompuIves knows

**Comment by hildakh** [comment]
I have the same problem in my app. I'm trying to load the components for now but the transpiling modules phase won't change. 

### [link to sandbox ](https://codesandbox.io/s/compassionate-mendeleev-b5xpu)

**Comment by junedchhipa** [comment]
Same issue.
I can't seem to find any recursive renders in my sandbox. 

[Link to sandbox](https://codesandbox.io/s/apx-line-basic-o2mwb)

**Comment by Ankhtepot** [comment]
I have same problem. Code works in Webstorm and is from Udemy course without modifications. Codesandbox is stuck on Transpiling Modules.

[link to codesandbox](https://codesandbox.io/s/recipeswithrouting-mni3b)

**Comment by garethx** [comment]
@Ankhtepot your sandbox loads ok for me - did you resolve your issue?

**Comment by Ankhtepot** [comment]
Thats the worst case scenario, I guess. It loaded once this morning but when I clicked to other tab in the app I got Transpiling.... and since then I cant load it, even now, when I tried, it wont load.

**Comment by garethx** [comment]
Can you try in an incognito/private browser window?

**Comment by Ankhtepot** [comment]
Hi. That works! Is there a way how to make it work without incognito window? 
Either way, thank you!

**Comment by garethx** [comment]
@Ankhtepot If it works in an incognito window, then it suggests either a problem with your cached version or a plugin. I'd try clearing the cache and if problems persist, go through plugins to see which cause an issue. Ad blockers for example, sometimes get a bit carried away and block useful scripts.

**Comment by Ankhtepot** [comment]
Thank you for your advice. I understood its issue with cookies. Clearing cache (ctrl+F5 in Crome?) didnt helped. But addblock could be the culprit. As I'm a bit wiser now, I should figure it out. Cheers!

**Comment by jp3492** [comment]
Same issue here, codesandbox keeps itself locked in transpiling modules screen and work cannot be done :( I guess im trying codepen

**Comment by garethx** [comment]
@jp3492 Please provide a link to the sandbox you're having problems with, otherwise we can't look into the cause for you. Thanks.

**Comment by justaplan** [comment]
Stuck in transpiling module like forever!
https://codesandbox.io/s/movie-search-app-wvq8p?file=/src/App.js:238-257

**Comment by garethx** [comment]
@justaplan are you still seeing this? Loaded ok for me.

**Comment by giscafer** [comment]
Transipling Modules 
https://codesandbox.io/s/jv8oq

**Comment by JamesACS** [comment]
Hey @giscafer - It would be worth creating a new issue for this so it doesn't get lost - It looks as though there is an issue with @roothub/components. We're investigating internally!

**Comment by giscafer** [comment]
@JamesACS  it's weird, it is working for this example:
https://codesandbox.io/s/jcu3i 

almost the same dependencies
