### ISSUE TITLE
250 limit

### ISSUE THREAD

**Issue by distinctperspective** [codesandbox/codesandbox-client#3039]
I paid for patron and cant load my project....something about 250 limit....but I thought patron was unlimited??

**Comment by MichaelDeBoey** [comment]
Hi @distinctperspective!

Thanks for raising the issue.

As @CompuIves already explained in https://github.com/codesandbox/codesandbox-client/issues/563#issuecomment-513249892, the team is working on a solution for this problem. 🙂

Closing this in favor of #563
