### ISSUE TITLE
Lost all codesandbox projects when I converted my github account into an organisation

### ISSUE THREAD

**Issue by gregg-cbs** [codesandbox/codesandbox-client#3043]
# 🐛 bug report

## Description of the problem
I used to login to codesandbox with my github account.
I then updated my account to an organisation.

Now my email address for github is different as I am a user on this organisation.
When i log into codesandbox with my account, everything is blank.

Which makes sense, but how do I now access my old codesandbox account?
I am also a patron, so now if I cannot access that sandbox account anymore then what happens to my patronship?

## How has this issue affected you? What are you trying to accomplish?
All my projects and templates are gone.
The codesandbox account is still there but I cant access it.

Link to the codesandbox account that I want access to: [link](https://codesandbox.io/u/coldbrewstudios)

**Comment by CompuIves** [comment]
Heyo! Can you send an email to hello@codesandbox.io with your old email and new email? I'll make sure to move the sandboxes!

**Comment by abdulmalikhakam** [comment]
i have  been having issue with my GitHub account . i submitted my assignment through sandbox in alx projects but now i cant find them in my list in all my assignment

**Comment by filipelima18** [comment]
> i have been having issue with my GitHub account . i submitted my assignment through sandbox in alx projects but now i cant find them in my list in all my assignment

Hi @abdulmalikhakam. Can you share more details (including screenshots or videos) of your issue so we can investigate this? If you prefer to do so privately, please fill out our [Support form](https://codesandbox.io/support).
