### ISSUE TITLE
Embed: Mobile Experience

### ISSUE THREAD

**Issue by jyash97** [codesandbox/codesandbox-client#3045]
# 🐛 bug report
Mobile Experience in Embed

## Description of the problem

- Editing File

1. There is a cursor mismatch when typing fast which leads to incorrect spelling. Replicate by typing fast.
2. When IntelliSense popup is shown, backspace doesn't seem to work.
![Screenshot_20191119-121914](https://user-images.githubusercontent.com/22376783/69123304-0234b600-0ac7-11ea-8616-eb421c6c0a22.jpg)
3. Preview gets refresh on every keypress, so consider I am writing `console.log` it will throw error till the syntax is correct. This creates many errors on the terminal and thus the Device slows down and the site becomes unresponsive for a small time interval when we open the console tab. You can see the logs in the below screenshot. ( It was having around 420 errors )
4. Sometimes we can see the syntax information on the preview tab as well. Check the screenshot: 
![Screenshot_20191119-120500](https://user-images.githubusercontent.com/22376783/69122549-1ecfee80-0ac5-11ea-8918-9e8f3315fc15.jpg)

- Sidebar and navbar

1. The size (area to touch/interact) of the file and folder is too compact on mobile and sometimes the touch isn't recognized or a different file gets opened.

- Editor

1.  There is a small space at the bottom usually visible when we scroll vertically.
2. Toggling from preview to editor shows a blank editor for around 20 - 30s. This happens every time.
3. The default font size for embed is too big for mobile, have to always scroll horizontally for understanding the statement.

- Preview

1. If the background is white ( for eg in react template ) we cant see the toggle button and it becomes difficult to toggle to code editor back.

## How has this issue affected you? What are you trying to accomplish?
Read and edit on the mobile browser

### Your Environment
Android v10

`Note:` I am ready to help on a few issues if they make sense and making the mobile experience seamless :)

**Comment by jyash97** [comment]
Ping @siddharthkp

**Comment by siddharthkp** [comment]
@jyash97 👋 

that's a long list 🙃, i'm going down the list slowly

**Comment by jyash97** [comment]
Awesome, thanks for taking time to look into this :)

Let me know if you need any help from my side.

**Comment by limitlessloop** [comment]
Hi, I just want to add some feedback with an issue I'm experiencing trying to use the embed preview.

In Chrome on Android, scrolling the editor is very difficult. The only way to fix this was to switch to CodeMirror.

Also would it possible for you to remove the border on the div with calss `elements__Moving-vemxx9-2 kcaoOC`? It doesn't look very good and doesn't go all the way around the embed so it looks like a mistake.

Left side
<img width="276" alt="Screenshot 2020-03-24 at 14 20 04" src="https://user-images.githubusercontent.com/5551/77435768-99de4400-6dda-11ea-906d-ac9a9be69a5c.png">

Right side
<img width="276" alt="Screenshot 2020-03-24 at 14 20 54" src="https://user-images.githubusercontent.com/5551/77435886-bda18a00-6dda-11ea-9b9a-84bcd175a662.png">

What it looks like with border removed
<img width="479" alt="Screenshot 2020-03-24 at 14 22 11" src="https://user-images.githubusercontent.com/5551/77436015-e033a300-6dda-11ea-849c-6515b2985bf1.png">

All the best.

**Comment by jyash97** [comment]
@siddharthkp 
 The UI looks better without borders, is it something I can take up? 

Also, I can help with other issues that were reported by me over the weekends.

**Comment by siddharthkp** [comment]
Hey!

I haven't had the chance to jump back into this, but I'll have some time next week. Let's talk about it!

**Comment by jyash97** [comment]
Sure sounds good :)
