### ISSUE TITLE
Tooltips overlap reference elements in console UI

### ISSUE THREAD

**Issue by atomiks** [codesandbox/codesandbox-client#3059]
# 🐛 bug report

![overlapping tippy](https://i.imgur.com/jObyzgh.png)

You can fix this by setting `boundary="window"` prop on your tippy tooltips. 

Popper v2 will have a smarter default to prevent this: https://github.com/FezVrasta/popper.js/pull/793 🎉

**Comment by atomiks** [comment]
Also if you update to latest Tippy you can have singleton tippies that look cool and improve the UX of delayed tooltips: 

gif: https://twitter.com/thekitze/status/1196864091786223617
docs: https://github.com/atomiks/tippy.js-react#-singleton
demo: https://atomiks.github.io/tippyjs/#singleton-1

I'm working on a PR for these two things, but might take a while as I'm learning the codebase and where to find things 😆

**Comment by siddharthkp** [comment]
Singleton tippies look great!

> I'm working on a PR for these two things, but might take a while as I'm learning the codebase and where to find things 😆

 I'll add it to my list but to be honest, same here 😄
