### ISSUE TITLE
I want to create a react project and introduce the internal component library. What should I do

### ISSUE THREAD

**Issue by 792472461** [codesandbox/codesandbox-client#3060]
I want to create a react project and introduce the internal component library. What should I do

**Comment by MichaelDeBoey** [comment]
Hi @792472461!

Can you explain a bit what you mean with “the internal component library” please?

**Comment by 792472461** [comment]
> Hi @792472461!
> 
> Can you explain a bit what you mean with “the internal component library” please?
For example, some component packages can only be downloaded in the local area network

**Comment by 792472461** [comment]
> Hi @792472461!
> 
> Can you explain a bit what you mean with “the internal component library” please?


For example, some component packages can only be downloaded in the local area network

**Comment by SaraVieira** [comment]
Hey!

At the moment we don't siupport any type of custom npm rc that would allow you to say what is the custom url to download from so you can either upload it to codesandbox or to github and use github as a dependency but if you can only acess it in your network I would say you need to upload the bundles :(

Sorry

**Comment by CompuIves** [comment]
Let's keep a reference to this issue, this is definitely something we want to implement in the near future, but we don't support it right now.

**Comment by lanpangci** [comment]
> Let's keep a reference to this issue, this is definitely something we want to implement in the near future, but we don't support it right now.
> 
> > For example, some component packages can only be downloaded in the local area network
> 
> Are those components hosted in an internal npm registry?


The same problem bothers me,  our components are hosted in internal registry, do you have any solution?

**Comment by garethx** [comment]
Not currently, but this is something we're actively looking into. Do you use a service for your private npm registries? (Like GitHub Package Registry) Do they run within a VPN?
