### ISSUE TITLE
Chose installed version of TypeScript for editor

### ISSUE THREAD

**Issue by Hotell** [codesandbox/codesandbox-client#3078]
# Question / Bug

I'm not able to choose installed TypeScript version in editor. is this a bug or missing feature ?

Thanks!

![image](https://user-images.githubusercontent.com/1223799/69501463-7e832b00-0f05-11ea-8eca-bb30dc940ffc.png)

**.vscode/settings.json**

```json
{
    "files.autoSave": "onFocusChange",
    "typescript.suggest.autoImports": true,
    "typescript.tsdk": "node_modules/typescript/lib"
}
```

**package.json**
```json
{
  "name": "parcel-sandbox",
  "version": "1.0.0",
  "description": "Simple Parcel Sandbox",
  "main": "index.html",
  "scripts": {
    "start": "parcel index.html --open",
    "build": "parcel build index.html"
  },
  "dependencies": {},
  "devDependencies": {
    "typescript": "3.7.2",
    "parcel-bundler": "^1.6.1"
  }
}
```

related https://github.com/codesandbox/codesandbox-client/issues/942

**Comment by SaraVieira** [comment]
Hey!

On client sandboxes we don't really install node modules so you have to use the one on VSCode, this is most likely possible with a container as the node modules will be installed there.

It's a missing feature on client sandboxes as node modules folder doesn't exist

**Comment by Hotell** [comment]
> Hey!
> 
> On client sandboxes we don't really install node modules so you have to use the one on VSCode, this is most likely possible with a container as the node modules will be installed there.
> 
> It's a missing feature on client sandboxes as node modules folder doesn't exist

right, so with that said, there is no option to use different version of TS, except that one which is shipped with client?

thx!
