### ISSUE TITLE
TypeScript const assertions cannot be used with CRA

### ISSUE THREAD

**Issue by Hotell** [codesandbox/codesandbox-client#3079]
# 🐛 bug report

## Description of the problem

Unable to use `as const` cast with CRA

## How has this issue affected you? What are you trying to accomplish?

Standard TS features cannot be used.

The culprit is probably that CRA template uses typescript 3.3 and because [`as const` was introduced in `3.4`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions) , it doesn't work ( as bumping TS version doesn't work in Codesandbox it seems -> https://github.com/codesandbox/codesandbox-client/issues/3078).

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome
| Operating System | OSX Mojave

**Comment by lbogdan** [comment]
Hey @Hotell ,

Closing this, as we upgraded to TypeScript 3.6.2 in the meanwhile, and the OP sandbox now works:

![image](https://user-images.githubusercontent.com/2083930/73878857-066da580-4864-11ea-844c-25f1529418a2.png)
