### ISSUE TITLE
Show status of view items in the menu

### ISSUE THREAD

**Issue by elomid** [codesandbox/codesandbox-client#3080]
# 🌈 Feature

It would be helpful to show the status of all items in the view menu so that it is easier to know what items are toggled on or off. Currently, some items like `Toggle Minimap` indicate their status with a checkmark but others like  `Toggle Side Bar` don't.

<img width="478" alt="Screen Shot 2019-11-24 at 4 20 08 PM" src="https://user-images.githubusercontent.com/3935236/69504328-ac9d4680-0ed6-11ea-8ab1-5eea47725d84.png">

**Comment by siddharthkp** [comment]
@CompuIves correct me if i'm wrong, we borrow that functionality from vscode, right?

So, to implement this change, we would need to modify the vscode codebase, not just ours?

**Comment by elomid** [comment]
@siddharthkp thanks for the reply. For what it's worth, VS Code does show the checkmarks for these items. Here is a screenshot from VS Code:

<img width="491" alt="Screen Shot 2019-11-26 at 3 07 31 PM" src="https://user-images.githubusercontent.com/3935236/69680064-a2a64f80-105e-11ea-890b-b57af9a66424.png">

**Comment by siddharthkp** [comment]
Oh this is a learning experience, _my vscode_ doesn't show the same checkmarks 😅 

<img width="404" alt="Screenshot 2019-11-27 at 2 22 48 PM" src="https://user-images.githubusercontent.com/1863771/69726758-7d2e4a00-1121-11ea-8e99-487793e9afa5.png">

My guess is this is about versions, what VS Code version are you on?

**Comment by elomid** [comment]
@siddharthkp ha interesting! I am on version 1.40.2
