### ISSUE TITLE
JSON file not loaded correctly in sandbox

### ISSUE THREAD

**Issue by huy-nguyen** [codesandbox/codesandbox-client#3082]
# 🐛 bug report

## Description of the problem

In the linked Sandbox, the `require` statement generates an error: 
```
SyntaxError
JSON.parse: unexpected character at line 1 column 1 of the JSON data
``` 
but the JSON data (`646.json`) is actually valid. When I clicked on `646.json` in Codesandbox's file browser, instead of seeing the actual file content, I see this:
```
https://rawcdn.githack.com/huy-nguyen/pheweb-manhattan-plot/91b641586d866f529db05eba2e4a306242f1f839/src/646.json
```
which I take to mean Codesandbox is doing some performance optimization by loading the file content from GitHub instead of storing it inside the sandbox. This is definitely a good idea but it seems to have the effect of making JSON parsing fail. If you copy `646.json`'s real content from GitHub and paste it into the corresponding file in Codesandbox, the app works correctly. It also works on my local machine.

## How has this issue affected you? What are you trying to accomplish?
My UI doesn't work at all in codesandbox.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |Not sure how to find it|
| Browser          |Firefox, Chrome|
| Operating System | Mac OS 10.14

**Comment by siddharthkp** [comment]
Hi @huy-nguyen 👋 

> which I take to mean Codesandbox is doing some performance optimization by loading the file content from GitHub instead of storing it inside the sandbox. This is definitely a good idea but it seems to have the effect of making JSON parsing fail. 

Yep, you got that right. 

It's meant to be an optimisation because the file is too big to be usable inside codesandbox. But, instead of replacing the contents, we could look at making it ready only. That will increase the load time of the sandbox but it will work after it loads.
