### ISSUE TITLE
Document the `container` option

### ISSUE THREAD

**Issue by pjhanzlik** [codesandbox/codesandbox-client#3088]
# 🌈 Document the `container` option

## The feature
Expand Sandbox Configuration documentation to explain the `container` option of `sandbox.config.json`.  (Assuming a good set of sub-properties, like `port`, are ready for use.)

## How it could work
The [Codesandbox Documentation on Configuration](https://codesandbox.io/docs/configuration) should be updated to show the `container` option currently exists.  Since it is an object option and applicable only to containers, it should probably have a special section after the Sandbox Configuration section. The layout can be very similar to the Sandbox Configuration section. Every sub-option of `container` could be listed with option, description, default value, and possible values columns.

## An example of what the documentation might look like

**Container Configuration**
If your sandbox is a container environment, then you also have access to the `container` option in  `sandbox.config.json`. We support these properties:

Property | Description | Possible Values | Default Value
--- | --- | --- | ---
`port` | The port which the IDE browser window listens to | `0 - 65535` | `random*`

Currently accessing the `container` option requires manually editing the `sandbox.config.json`. As an example:
```json
{
  "template": "node",
  "container": {
    "port": 1234
  }
}
```

*I'm not actually sure what the default config value for `port` is 😅 

## An example of why it is useful
If you manually edit `sandbox.config.json` you can currently  declare the `container` property. This allowed me to achieve [existing client-side parcel environment behavior in a node container](https://codesandbox.io/s/elated-dew-je4cj). [The default port parcel serves pages under is 1234](https://parceljs.org/cli.html#port), so the trick was to tell the container to listen to that port.

```json
{
  "template": "node",
  "container": {
    "port": 1234
  }
}
```
This example illustrates no `codesandbox-client` code needs to be updated to use the `container` option.  Documenting that the option exists, and that it can be set via raw editing, should prove helpful to some users.

**Comment by SaraVieira** [comment]
Thannk you for pointing this up! I will work on this tomorrow
