### ISSUE TITLE
Cannot find module `cldrjs` in codesandbox CI sandbox

### ISSUE THREAD

**Issue by agubler** [codesandbox/codesandbox-client#3092]
# 🐛 bug report

## Description of the problem

Experiencing an error with a sandbox deployed via codesandbox CI, seemingly a missing dependency/missing module. However the dependency is correctly in the `package.json` for the sandbox.

Error:

`Could not find module in path: 'cldrjs' relative to '/node_modules/globalize/dist/globalize/message.js'`

## How has this issue affected you? What are you trying to accomplish?

Unable to use codesandbox CI for the `github.com/dojo/widgets` library

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1573738286-c05030adf
| Browser          | Chrome 78.0.3904.108
| Operating System | Mac OS Catalina

**Comment by tajo** [comment]
Same problem with react-view in this [sandbox](https://codesandbox.io/s/i3dbn?fontsize=14&hidenavigation=1&theme=dark)

**Comment by agubler** [comment]
Good morning, does anyone have any information for this issue? I would dearly love to use codesandbox ci for the dojo widgets library but at the moment this is a blocker unfortunately.

**Comment by agubler** [comment]
Hello everyone! Has any one had any luck with this issue?
