### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by siccoo** [codesandbox/codesandbox-client#3093]
I get an internal server error when trying to make commits to my Github 
I don't really know where this problem is but I've made 32 commits to my github before to a projects and later deleted it due to this internal server error that was yesterday, I even sent a message to Code Sand Box
Please help me because I'm in a test task and my pc doesn't have the necessary modules installed to enable gatsby, so thats why I had to use an online code editor.

**Comment by garethx** [comment]
Unfortunately, since you deleted the sandbox we're unable to look into the issue. If you run into this again, please provide a link to the sandbox and do not remove it. Thanks.
