### ISSUE TITLE
Svelte 3.12+ stuck transpiling modules

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#3094]
# 🐛 bug report

## Description of the problem
Any version of Svelte 3.12 and above hangs on transpiling modules and never loads.

## How has this issue affected you? What are you trying to accomplish?
Unable to use most recent versions of Svelte

### Link to sandbox: [link](https://codesandbox.io/s/modest-wind-fpzv0)

**Comment by az67128** [comment]
Are there any news on this issue?
