### ISSUE TITLE
snippets working?

### ISSUE THREAD

**Issue by epfromer** [codesandbox/codesandbox-client#3110]
# 🐛 bug report

## Description of the problem

Not sure if related to deployment today, but snippets stopped working for me on codesandbox.io.  I can't bring them up either through the menu.

## How has this issue affected you? What are you trying to accomplish?

Trying to use several personal Vue snippets.  Then, try to bring up snippet list via menu.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | codesandbox.io
| Browser      | latest Chrome
| Operating System    | Windows 10

**Comment by iamhenry** [comment]
I am also having this issue. I had set some custom snippets for React and they are no longer working.

Browser: Mac OS Brave 1.1.2.0

**Comment by tayelno** [comment]
Yup me too here is my **WIP Snippet: ** https://atayel.netlify.com/slides/react-hooks/
sandbox itself is here https://codesandbox.io/s/github/tayelno/react-hooks-demo

On Brave guarding against cross-site trackers will make the iframe hang on an empty editor.

### Link to website: https://atayel.netlify.com/slides/react-hooks/
### Link to sandbox:  https://codesandbox.io/s/github/tayelno/react-hooks-demo
### Environment

 Software	Name/Version
 Сodesandbox	codesandbox.io
 Browser	Brave (Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit))
 Operating System	Mac OS 10.15

### Console output on page load:

```
A cookie associated with a cross-site resource at http://codesandbox.io/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
utils.js:78 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.../common/lib/utils/analytics/utils.js (https://codesandbox.io/static/js/default~app~embed.2cbb87f7.chunk.js:408:92493)
    at s (https://codesandbox.io/static/js/embed.f2cb871b.js:1:571)
    at Object.../common/lib/utils/analytics/amplitude.js (https://codesandbox.io/static/js/default~app~embed.2cbb87f7.chunk.js:408:81421)
    at s (https://codesandbox.io/static/js/embed.f2cb871b.js:1:571)
    at Object.../common/lib/utils/analytics/index.js (https://codesandbox.io/static/js/default~app~embed.2cbb87f7.chunk.js:408:85562)
    at s (https://codesandbox.io/static/js/embed.f2cb871b.js:1:571)
    at Module../src/embed/index.js (https://codesandbox.io/static/js/embed.f2cb871b.js:27:60853)
    at s (https://codesandbox.io/static/js/embed.f2cb871b.js:1:571)
    at Object.6 (https://codesandbox.io/static/js/embed.f2cb871b.js:27:81584)
    at s (https://codesandbox.io/static/js/embed.f2cb871b.js:1:571)

```

screenshot:

<img width="1280" alt="Screen Shot 2020-01-02 at 00 00 24" src="https://user-images.githubusercontent.com/14842622/71646551-0a515980-2cf3-11ea-8c8e-07db84d5ab68.png">

**Comment by garethx** [comment]
From sventhevenn in 3569: "When entering user snippets through the menu (file -> preferences -> user snippets), nothing happens.

When entering user snippets using ctrl + shift + p, and entering "Preferences: Configure User Settings" I get this error: TypeError: Cannot read property 'addEventListener'

 image

I did manage to get into the snippets files on Chrome 79, but the snippets did not work.

On Firefox 73 I got it working by not being logged in (can't remember if I used the menu or command). After logging into CodeSandbox on Firefox I can't get it to work again."

In my testing the user snippets menu _does_ work in Chrome - it fails to open the first time you click the user snippets menu, but if you go back and try again then it opens.

**Comment by iamhenry** [comment]
I'm still having this issue after all these months. Has anyone been able to figure out a workaround?

**Comment by CompuIves** [comment]
Hey! I'm going to take a look at this issue over this and the next week, I'm sorry for the wait on this! You can follow progress here: #3754

**Comment by CompuIves** [comment]
Hey! Snippets should be working as expected now again! Apologies for the wait time on this!

**Comment by tayelno** [comment]
> Hey! Snippets should be working as expected now again! Apologies for the wait time on this!

Confirmed the issue I had with Brave and Safari is now fixed.

Thank You :)
