### ISSUE TITLE
Bug: reloads on every keypress, instead of file save, even when `Instant Preview Disabled` disabled

### ISSUE THREAD

**Issue by NawarA** [codesandbox/codesandbox-client#3129]
# 🐛 bug report
`Preview` bug

## Description of the problem
Behavior
* `Preview on edit` enabled
* `Instant preview` disabled

Software reloads on every keystroke, even on up arrow and down arrow. As a result, the sandbox constantly reloads, so often it crashes.

`Instant preview` (reload on every keypress) is disabled, so this is not expected behavior.

Expected behavior -> preview reloads when `ctrl + s` is hit

Am I missing something? Is there way to make the editor `reload on save`? 
## How has this issue affected you? What are you trying to accomplish?
* Crashing the tab
* constantly reloading means, constant reading from my db, costing me $$

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by lbogdan** [comment]
Hey @NawarA ,

I can't replicate this on my side, is it still happening for you?

**Comment by NawarA** [comment]
Yes. To be precise, 
`Codesandbox Settings -> Preview` has 3 options:
1. `Preview on Edit` (Preview the latest code without saving)
2. `Clear Console`
3. `Instant Preview` (show preview on every keystroke)

I currently have `Preview on Edit` enabled and `Instant Preview` disabled. Yet when I hit any keystroke, the preview renderer has to go through the build process again. Again, this is with "preview on every keystroke" disabled. 

It seems `Preview on Edit` and `Instant Preview` do the same thing, or really, `Preview on Edit` is actually preview on keystroke? If this is intended, then why the two different options?

Finally, the expected behavior with...
1. `Preview on Edit` - Off
2. `Clear Console` - N/A
3. `Instant Preview` - Off

...is that when saving (such as CTRL + S), the preview window updates. Instead, the settings above stop any kind of preview from occurring, and a developer / user must manually refresh the entire browser window to see an update. 

So the expected behavior is missing, is far as I can tell. 

Would you a link a to sandbox that demonstrates what I'm stating above?

**Comment by NawarA** [comment]
The case is still open and shouldnt be marked as stale :)

**Comment by christianalfoni** [comment]
Hi @NawarA and sorry for not following up on this! We have done a few changes to how we prioritize and follow up on support, so lets figure this one out now!

Yes, please give me a link to a sandbox where this behaviour occurs 😄
