### ISSUE TITLE
Weird typescript linting issue with class public/private/protected properties

### ISSUE THREAD

**Issue by jfmmm** [codesandbox/codesandbox-client#3133]
# 🐛 bug report

## Description of the problem
Codesandbox throws an error when trying to add public, private or protected in front of a class attribute. It works fine if you export the sandbox and open it in vscode.

![Screen Shot 2019-12-05 at 5 06 55 PM](https://user-images.githubusercontent.com/2498456/70278413-36c09700-1782-11ea-9a48-085a869a152e.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome |
| Operating System | Mac |

**Comment by jfmmm** [comment]
if I don't have any attribute in my class it complains about the first method with a public modifier.

![image](https://user-images.githubusercontent.com/2498456/70285394-56ad8600-1795-11ea-8b29-aefb9adb663a.png)

**Comment by CompuIves** [comment]
Hey! Do you have a link to a repro sandbox?
