### ISSUE TITLE
Add Fastify Node.js backend template 

### ISSUE THREAD

**Issue by Ethan-Arrowood** [codesandbox/codesandbox-client#3135]
# 🌈 Feature

I'd like to add some templates for a Node.js backend framework called [Fastify](https://fastify.io)

Are public template contributions okay? If so where would I get started?

**Comment by CompuIves** [comment]
Hey @Ethan-Arrowood, absolutely! Just send a template url to me and I'll add it to the Template Universe. I was planning on highlghting more node servers there anyways

**Comment by Ethan-Arrowood** [comment]
Wonderful! I'll get to work on something and reply back here when it is complete. Thank you @CompuIves 😄

**Comment by mcollina** [comment]
I'm happy to review!

**Comment by Ethan-Arrowood** [comment]
Here is the simplest example:
https://codesandbox.io/s/fastify-starter-luepu

@mcollina what are some other things we should include in the starter template?

**Comment by mcollina** [comment]
I would add some form of tests, and change the code to have a `build()` function that returns the server but don't call `listen()`

```js
const fastify = require('fastify')

function build () {
  const app = fastify()
  app.get('/', async (request, reply) => {
    return { hello: 'world' }
  })
  return app
}

async function start () {
  try {
    const app = build()
    await app.listen(3000)
  } catch (err) {
    app.log.error(err)
    process.exit(1)
  }
}

if (require.main === module) {
  start()
}

start()
```

**Comment by Ethan-Arrowood** [comment]
Awesome, I like these ideas. I'll make the changes shortly.

**Comment by Ethan-Arrowood** [comment]
Okay made updates let me know what you think: https://codesandbox.io/s/fastify-starter-luepu

**Comment by mcollina** [comment]
A few notes:

1. `npm start` is often used inside `Dockerfile`s and other system to start the application in production. Using `nodemon` there is something to avoid, as restarting is better done at the infra level. I'm not sure how this interacts with the codesandbox environemnt, so this is worth a chat.
2. Please put "use strict" everywhere. Those are not ESM.
3. Run tap with `--no-esm`.
4. Have each test create and destroy its own server. You can possibly do that with a quick helper like this:

```js
function createServer (t) {
  const server = build()
  t.tearDown(() => server.close())
}
```

**Comment by Ethan-Arrowood** [comment]
Okay made the updates. I used `t.beforeEach` and `t.afterEach` instead of the helper function

**Comment by mcollina** [comment]
Is there any codesandbox feature to have it run `npm run dev` with nodemon installed?

I think `got` is a spurious dependency.

You can use async in `afterEach`. I would do `return server.ready()` or `await server.ready()` in `beforeEach`.

You'll need to add some form of eslint config to the editor to avoid the `'use strict' is unnecessary inside of modules. (strict)eslint` warning.

**Comment by lbogdan** [comment]
> Is there any codesandbox feature to have it run npm run dev with nodemon installed?
@mcollina We're not that opinionated on which watch manager you'd like to use 🙂, so if you want to use `nodemon`, add it to `devDependencies` and also to the `dev` script.

**Comment by Ethan-Arrowood** [comment]
@lbogdan @CompuIves how soon is custom ESLint configs or ESLint overrides coming? 

> we don't currently support custom ESLint configs in the editor itself.
> - [CodeSandbox Environments](https://codesandbox.io/docs/environment)

Looks like `sourceType` is set to `module` when we would need it to be `script`

and @mcollina i've updated the code to use async in the `beforeEach` and `afterEach`

**Comment by SaraVieira** [comment]
Hey!

We don't have a plan for that because that would require some really hacky work and we had some issues with that :(

**Comment by Ethan-Arrowood** [comment]
Okay! I'll include a comment then. Thank you 😄

**Comment by Ethan-Arrowood** [comment]
Added comments and a readme. I believe this is ready to be shipped now

**Comment by SaraVieira** [comment]
👋

Let us know when done so we can add it in the template universe

**Comment by Ethan-Arrowood** [comment]
ping @mcollina for a final review

**Comment by mcollina** [comment]
code lgtm.

Why are you using precise version on package.json instead of `^` prefix?

**Comment by Ethan-Arrowood** [comment]
I think that was something CodeSandbox did when I installed the deps. I'll update that now. 

Also @SaraVieira this is good to go 😄

**Comment by lbogdan** [comment]
Wouldn't it better to have this in a GitHub repo, though?

**Comment by Ethan-Arrowood** [comment]
I'm not entirely sure how CodeSandbox would prefer it. We'd be happy to make it a repo in the fastify org if that is compatible. Most importantly we want the template easily available on CodeSandbox 😄

**Comment by lbogdan** [comment]
Well, all GitHub repos are easily accessible on CodeSandbox, e.g. this Vue CLI 4 template I created today: https://codesandbox.io/s/github/lbogdan/cs-vue-cli-4 .

**Comment by lbogdan** [comment]
Oh, I see yours is already working, too: https://codesandbox.io/s/github/Ethan-Arrowood/fastify-starter .

**Comment by lbogdan** [comment]
The repo doesn't have to be created from inside CodeSandbox, **all** GiHub repos can be imported in CodeSandbox.

**Comment by Ethan-Arrowood** [comment]
I'll transfer the repo to Fastify then on the GitHub side

**Comment by Ethan-Arrowood** [comment]
Okay here is the final url: https://github.com/fastify/fastify-starter-codesandbox/tree/master

Let me know if anything needs changing. Thank you!

**Comment by lbogdan** [comment]
Hey, sorry for the delay, we just added https://codesandbox.io/s/github/fastify/fastify-starter-codesandbox to our official template list:

![image](https://user-images.githubusercontent.com/2083930/73137668-5b8b0980-4063-11ea-8d12-2c8a1b947542.png)

I'm closing this for now, please reopen if we forgot anything.

**Comment by mcollina** [comment]
You might want to use the fastify logo: https://github.com/fastify/graphics

**Comment by SaraVieira** [comment]
That needs an update to a module we have with the so it may take a while but we will update it :)

**Comment by mcollina** [comment]
thanks
Il 26 gen 2020, 18:40 +0100, Sara Vieira <notifications@github.com>, ha scritto:

**Comment by Ethan-Arrowood** [comment]
Thank you for adding this ❤️🎉
