### ISSUE TITLE
I keep getting crashes while working in React Testing Library 

### ISSUE THREAD

**Issue by JacobMGEvans** [codesandbox/codesandbox-client#3149]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 78.0.3904 | OS X 10.15.1           | PROD-1575721600-9ec7e52a1          |

  **Route:**
  https://codesandbox.io/s/nervous-river-y50pt

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'tests' of undefined
  TypeError: Cannot read property 'tests' of undefined
    at https://codesandbox.io/static/js/default~app~embed.93549ce0.chunk.js:437:102060
    at F.produce (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:903383)
    at t.<anonymous> (https://codesandbox.io/static/js/default~app~embed.93549ce0.chunk.js:437:102023)
    at Ro (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1659868)
    at Po (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1660129)
    at ma (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1679763)
    at Ks (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1715193)
    at Fs (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1699559)
    at Ns (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1696579)
    at Bs (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1695139)
  
    in t
    in div
    in t
    in elements__ContentContainer
    in div
    in t
    in elements__Container
    in t
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in xe
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in Unknown
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Hey! I pushed something that might fix your issue, I haven't been able to repro it yet. It'll go live tomorrow 🤞

**Comment by lbogdan** [comment]
Hey @JacobMGEvans ,

Any updated on this?

**Comment by JacobMGEvans** [comment]
I'll follow up and see if I can still reproduce.

**Comment by lbogdan** [comment]
Closing this, it should be fixed by https://github.com/codesandbox/codesandbox-client/commit/fc10d12cc8c8be2105ea6be397c4c70a54ca23bb .

@JacobMGEvans Please re-open if this is still happening for you.
