### ISSUE TITLE
No longer able to successfully rename sandbox via app bar

### ISSUE THREAD

**Issue by ryancogswell** [codesandbox/codesandbox-client#3175]
# 🐛 bug report

## Description of the problem

When I try to rename a sandbox from the auto-generated name, I get the following error message:

> alias: has already been taken

To reproduce:

* Need to be logged in. The behavior does not seem to be present when using it as an anonymous user. I have a patron account and I sign in using GitHub.
* Start a new React sandbox via https://codesandbox.io/s/new
* Make a change to index.js and save so that the title portion of the app bar changes from "React <kbd>Template</kbd>" to "My Sandboxes / generated-name-as6df"
* Click on the generated name in the app bar and edit it (it doesn't seem to matter what I change it to)

If instead I edit the name via clicking the pencil icon in the "SANDBOX INFO" side bar, I am able to successfully change the name, and after changing the name that way I am then able to make further changes to the name successfully using the app bar.

## How has this issue affected you? What are you trying to accomplish?

I rename my sandboxes so that I can tell the purpose of each one when looking through my sandboxes later. Over the past week I have been unable to do this (only when writing up this bug report did I discover that it was possible to successfully rename via the "SANDBOX INFO" side bar).

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome 78
| Operating System |

**Comment by CompuIves** [comment]
Thanks for the clear description! I'm taking a look now.
