### ISSUE TITLE
Add optional chaining for TypeScript

### ISSUE THREAD

**Issue by verydanny** [codesandbox/codesandbox-client#3188]
Current Issue:

![Screen Shot 2019-12-11 at 2 33 51 PM](https://user-images.githubusercontent.com/13333822/70653881-4bd67380-1c23-11ea-930c-9cf8919e7056.png)

It works, as in it compiles, but the TSServer (I'm guessing) is outdated.

**Comment by dwelle** [comment]
It also applies to nullish coalescing operator `??`, added in the same ES/TS version.
