### ISSUE TITLE
Unable to sign in with Github, stuck on this screen.

### ISSUE THREAD

**Issue by rizdaprasetya** [codesandbox/codesandbox-client#3191]
# 🐛 bug report

## Description of the problem
Env: 
- Chrome 78.0.3904.108 (Official Build) (64-bit)
- Mac OS Mojave

Unable to sign in, stuck on this page:
<img width="1225" alt="Screen Shot 2019-12-12 at 16 38 39" src="https://user-images.githubusercontent.com/13027142/70700841-f3c06f80-1cfd-11ea-91a8-c7db0f6777ab.png">

Console log doesn't print anything, no error, no log, etc.

Have tried:
- clearing cookies for codesandbox site
- clearing site data from Chrome dev tool "application" menu

Still no luck

## How has this issue affected you? What are you trying to accomplish?

Unable to sign in

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest
| Browser          | Chrome 78.0.3904.108 (Official Build) (64-bit)
| Operating System | MacOS mojave

**Comment by davidchanho** [comment]
I had this issue as well. I remember turning off my pop up and ad blocker for the sign in. It seemed to work.

**Comment by rizdaprasetya** [comment]
Ah thanks for the advice @davidchanho 

**It works** after I disable Chrome Extension [Adblock Plus](https://chrome.google.com/webstore/detail/adblock-plus-free-ad-bloc/cfhdojbkjhnklbpkdaibdccddilifddb)

So the issue is because of adblocker.
Tho nothing seems to be blocked:
```
Number of items blocked
0 on this page
```
