### ISSUE TITLE
Why isn't there a paste option in right click and edit menu?

### ISSUE THREAD

**Issue by davidchanho** [codesandbox/codesandbox-client#3197]
# ❔ Question
I think its inconsistent not to have paste right click and edit menus but have copy and cut there. Also its inconsistent with other websites and applications.

![image](https://user-images.githubusercontent.com/33166931/70750975-739a0a00-1cfd-11ea-9ae3-43a7ac680918.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest
| Browser          | Chrome & Firefox
| Operating System | Windows 10

**Comment by wojciechczerniak** [comment]
Only in native context menus. You can't have a custom context menu with `paste` option. Paste API was removed from web-browsers for security reasons.

**Comment by davidchanho** [comment]
Ok, thank you.

**Comment by davidchanho** [comment]
Ok, thank you
