### ISSUE TITLE
Deleted files come back

### ISSUE THREAD

**Issue by davidchanho** [codesandbox/codesandbox-client#3198]
# 🐛 bug report

## Description of the problem
After deleting a file through the explorer menu and then closing it in the editor menu, the files comes back in the explorer menu.
 
Also when you move a file into a different folder, it marks the file in the editor as deleted. However, when you close it in the editor menu, it will come back in the explorer menu where it was before. Then you end up with two copies. 

## How has this issue affected you? What are you trying to accomplish?
Not a huge deal but it is a minor inconvenience to delete files a couple of times.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome
| Operating System | Windows 10

**Comment by andrasbacsai** [comment]
I cannot reproduce it. Can you please show me a small video of the problem?
