### ISSUE TITLE
Is there any way to extract the code from the sandbox except for downloading as a zip or using the github?

### ISSUE THREAD

**Issue by zerosheepmoo** [codesandbox/codesandbox-client#3219]
# ❔ Question

My question is exactly same to the issue title. Especially, I wanted to extract the code or files from the iframed-sandbox or embedded one and I couldn't find the way. Is there any API or functionality to get the source files or code from sandbox or editor? It is not supposed to be directly copy and paste, downloading as a zip, and save the code on github.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | chrome  / 78.0.3904.108
| Operating System | MacOS / Sierra 10.12.6

**Comment by garethx** [comment]
Not at the moment, what is it that you're trying to do?

**Comment by zerosheepmoo** [comment]
Thanks! I am trying to combine the codesandbox with [draft.js](https://draftjs.org/) as a tool or plugin.

**Comment by lbogdan** [comment]
@zerosheepmoo Actually, if the sandbox is public, you can get its contents using the API endpoint `https://codesandbox.io/api/v1/sandboxes/[id]` , where `id` is the sandbox id - for example for the sandbox https://codesandbox.io/s/eager-cherry-s1ii2 you can get the contents from https://codesandbox.io/api/v1/sandboxes/s1ii2 .

**Comment by zerosheepmoo** [comment]
@lbogdan 
Oh, that's what I expected. It would be enough to be used to achieve my goal. Thanks.
By the way, is this info mentioned on docs? If you know where it is, please, reply with the link.

**Comment by lbogdan** [comment]
Unfortunately the API is not (yet) documented.

**Comment by zerosheepmoo** [comment]
@lbogdan 
Thanks.
It was really helpful.
One more then, — this is not related the issue — is it available to edit the sandbox on the embed?
I mean, edit and save the code.

**Comment by lbogdan** [comment]
As far as I know, you can't edit / save code from the embed, you can only open the full editor and edit / save code there. @siddharthkp knows more, he's the "embeds jedi". 🙂

**Comment by siddharthkp** [comment]
Sorry, we don't save the code in embeds. You'd have to open sandbox in editor.

What's your use case? Sounds like you want a minimal ui with codesandbox's functionality 😇

**Comment by zerosheepmoo** [comment]
@siddharthkp 
Thanks, jedi! 😄 
Actually, you may right. Only the code editor, live-view, and storage functionality are enough.

What I intended is making a component that shows someone's demonstration and can be shared. Then, creating it as a plugin of draft-js, and on the rich-editor, making a demo—which can be shared and stored on codesandbox flatform.

**Comment by lbogdan** [comment]
@zerosheepmoo Looks like you could make use of the define API, which is documented here: https://codesandbox.io/docs/importing#define-api .
Also, if you don't have any more questions, we'd appreciate you closing this, to keep the list of issues clean! 🙂 Thanks!

**Comment by zerosheepmoo** [comment]
Sure. Thanks.

**Comment by siddharthkp** [comment]
Don't forget to show us what you build! <3
