### ISSUE TITLE
Dependency missing for CI project

### ISSUE THREAD

**Issue by CompuIves** [codesandbox/codesandbox-client#3222]
# 🐛 bug report

## Description of the problem
Can't find the transient dependency of a root dependency.

## How has this issue affected you? What are you trying to accomplish?

Link to sandbox: https://codesandbox.io/s/lucid-ui-basic-app-9fkvu

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by jhsu** [comment]
here's a side-by-side of a next.js project and a create-react-app project using the same build:
https://ci.codesandbox.io/status/jhsu/lucid/pr/1/builds/5169

**Comment by jhsu** [comment]
taking a look at the network requests, the requests to unpkg (several `package.json` requests including  https://unpkg.com/d3-time-format@2/package.json) get a `429` (too many requests).

**Comment by jhsu** [comment]
@CompuIves did the cdn switch to jsdelivr? seems like the errors are gone with this cdn

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. If the problem still persists, please reopen the issue. Thanks!
