### ISSUE TITLE
Right clicking projects in dashboard not closing the menu appeared in previous click

### ISSUE THREAD

**Issue by alanlal** [codesandbox/codesandbox-client#3225]
# 🐛 bug report

## Description of the problem
If you goto the dashboard and right click different sandbox previews , all the right click menus persists on the screen

## How has this issue affected you? What are you trying to accomplish?
As a better user experiencem the menu from the previous right click should dissapear in the next right click

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Firefox 72.0b6 (32-bit) 
| Operating System | Windows 10

### Steps to recreate
1. go to you code sandbox dashboard
2. right click on one of the sandbox previews
3. right click again on a different sandbox preview

**if you right click on the side bar before doing step 1 ,  the sidebar menu also persists**

### Screenshot

![csbsissue](https://user-images.githubusercontent.com/26851904/71066731-3b7d4600-2199-11ea-8751-6e2ad0092769.PNG)

**Comment by SaraVieira** [comment]
This has been fixed with the new dashboard 🎉
