### ISSUE TITLE
Svelte template returns undefined counter

### ISSUE THREAD

**Issue by jonaskkristensen** [codesandbox/codesandbox-client#3226]
# 🐛 bug report
I was exploring Svelte in a new sandbox, and can see that the counter is returning undefined after first click. I'm not well known with svelte, so can't tell what makes the error

## Description of the problem
Counter returns undefined after first click

<img width="1112" alt="Screenshot 2019-12-18 at 09 01 58" src="https://user-images.githubusercontent.com/26645731/71067784-78374600-2175-11ea-89fd-11a20b731ac4.png">

**Comment by garethx** [comment]
I've updated to the latest version and this resolve the issue. Thanks for reporting.
