### ISSUE TITLE
Unable to edit in Live mode

### ISSUE THREAD

**Issue by shiftyp** [codesandbox/codesandbox-client#3228]
# 🐛 bug report

## Description of the problem

In live mode (classroom) there came a point where noone in the room could edit the file.

## How has this issue affected you? What are you trying to accomplish?

Trying to teach using Live Mode

### Link to sandbox: [link]() (optional)

I don't have the sandbox link anymore, but [here](https://dev.to/shiftyp/introducing-emoji-island-2n7d) is a video recorded during the session. Go to 11 min to see things start to get wonky (I think). 

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Unknown (12/18/19 11pm EST build) |
| Browser          | Google Chrome Version 78.0.3904.108 (Official Build) (64-bit) |
| Operating System | OSX 10.14.16 |

**Comment by andrasbacsai** [comment]
There were a lots of changes with the Live mode, so I think it's not relevant anymore.
Closing now. If you have any question, let us know!
