### ISSUE TITLE
.gitignore not honoured for Git commits

### ISSUE THREAD

**Issue by CompuIves** [codesandbox/codesandbox-client#323]
Git ignored files still get committed.

**Comment by cloggy45** [comment]
Any information as to what is causing this?

**Comment by cloggy45** [comment]
Further to our little discord chat, I will look into this!

**Comment by ckhicks** [comment]
This appears to still be happening - I had to remove files manually from my repo due to my gitignore not being respected. Any ideas?

**Comment by cloggy45** [comment]
I looked into this problem, but I've recently been swamped with coursework.

**Comment by ckhicks** [comment]
No worries, I'm a proud/paid supporter of this amazing framework so this is a small issue in light of how great the toolset is overall! Thanks for looking into it.

**Comment by simplywondrous** [comment]
I'm having this same issue, where the .gitignore isn't working.

**Comment by sun2rise** [comment]
Sure this is not a big issue, but if you want to use codesandbox for real projects with real data (like me), the fact that it will push to github all your keys is probably something quite limiting at the moment

**Comment by janweinen** [comment]
Tried it today but the problem persists.

**Comment by webskydavid** [comment]
Github support on codesandbox is still in beta phase. I think it will be fully supported in the future. It will be nice to have this option, and also a way to select files that are committed. :)

**Comment by MichaelDeBoey** [comment]
Closed by #3003

**Comment by srguiwiz2** [comment]
This still seems not to be working right, as described https://github.com/codesandbox/codesandbox-client/pull/3003#issuecomment-782754885 .  Not sure whether that deserves a new issue or reopening.

**Comment by rayfoss** [comment]
@srguiwiz2 You set up an automatic clone of the CSB repo on another computer, just to fix Git issues? Care to elaborate on the architecture, is it headless, are you using the CSB API, do you need to re-authenticate occasionally, are you running into issues?

I've found that the .gitignore file is very special in CSB, the sync daemon ignores changes to it in the container working directory, but changes are sent down from CSB. I'm personally dealing with issues regarding #4504 , the images aren't corrupting, but it appears that CSB injects metadata to all images, modifying them, meaning I can never have the git repository and the CSB have  the same version of images. Which complicates workarounds like [rsync'ing the git repo](https://www.npmjs.com/package/g4c) with scripts
