### ISSUE TITLE
Stripe checkout-single-subscription

### ISSUE THREAD

**Issue by fcdeveloper** [codesandbox/codesandbox-client#3230]
# ❔ Question

I am getting this error "root path required"
but don't see where I have to set this value? 

Code with sandbox on Window 10

**Comment by garethx** [comment]
You can have to add the environment variables specified in .env.example, which you can do from the server control panel on the left in the editor, under Secret Keys, in-particular `STATIC_DIR`, which is '../../client' in their example app.

**Comment by fcdeveloper** [comment]
Yes I did.. but still getting the same error message when I try to launch the server

**Comment by fcdeveloper** [comment]
Done.. Thank You!
