### ISSUE TITLE
ENOSPC: No Space Left on Device with yarn-workspaces and typescript

### ISSUE THREAD

**Issue by Shriram-Balaji** [codesandbox/codesandbox-client#3235]
# 🐛 bug report

## Description of the problem

Error: Could not write file '/sandbox/packages/core/dist/api/client.d.ts': ENOSPC: no space left on device, mkdir '/sandbox/packages/core/dist'.

Is there a way to increase the space on the device, using sandbox configuration maybe? Could be related to https://github.com/codesandbox/codesandbox-client/issues/1892, but I'm not sure if the cause for the issues are same, hence creating a new one.

## How has this issue affected you? What are you trying to accomplish?
I'm trying to run an app with yarn workspaces, but I'm currently unable to build it. I had a sandbox a couple of months back though, which worked without any issues.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1576768350-cec6282cd
| Browser          | Chromium / Brave
| Operating System | Windows x64

**Comment by lbogdan** [comment]
Hey @Shriram-Balaji ,

Unfortunately we have a hard storage limit of 1GB, which your sandbox seems to be reaching:
```
Filesystem                                                            Size  Used Avail Use% Mounted on
[...]
/dev/rbd24                                                           1014M 1014M  176K 100% /sandbox
```
There's currently no way of increasing this limit.
