### ISSUE TITLE
`console.dir()` doesn't work

### ISSUE THREAD

**Issue by asimdahall** [codesandbox/codesandbox-client#3238]
# 🐛 bug report

## The `console.dir()` method doesn't  log any information in the console

Wanted to see the dom object structure but didn't show up in the console. I had to use the browser's console to see the information.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest
| Browser          | Chrome latest
| Operating System | MacOS Catalina

**Comment by SaraVieira** [comment]
Hey!

We use https://github.com/samdenty/console-feed to support the console output shown in the page and at the moment they don't support `console.dir` so maybe make an issue there and I can work with Sam on it
