### ISSUE TITLE
Website is showing as a mobile interface - it's unusable

### ISSUE THREAD

**Issue by adamkleingit** [codesandbox/codesandbox-client#3241]
# 🐛 bug report
The website is showing as a mobile interface on desktop web - it's unusable.

## Description of the problem
See image:
![image](https://user-images.githubusercontent.com/889418/71595703-670f1180-2b45-11ea-8403-52d5ba924b0d.png)

## How has this issue affected you? What are you trying to accomplish?
Can't use the website

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 
| Browser          |  Chrome
| Operating System | Mac OS High Sierra

**Comment by SaraVieira** [comment]
Hey!

Can you share your browser dimensions?

**Comment by adamkleingit** [comment]
Hi!

I just checked again and I was zoomed in. But I understand how that happened - I hit cmd+0 but that doesn't work on Codesandbox' dashboard page, so I was sure I was at baseline zoom. Funny...

Anyway - closing :)

**Comment by SaraVieira** [comment]
Ohhh, but it is weird that the dashboard won't let you do that :/
