### ISSUE TITLE
Embedded sandbox shows only Preview on the width less than 816px

### ISSUE THREAD

**Issue by NataliaTepluhina** [codesandbox/codesandbox-client#3244]
# 🐛 bug report

## Description of the problem

When trying to add an embedded sandbox into the container with the width less than 816px, it shows the Preview tab only even if 'Editor+Preview' was selected

## How has this issue affected you? What are you trying to accomplish?

I am trying to add sandboxed to the documentation based on VuePress and the main container there is 740px width (a good example could be https://router.vuejs.org/). I wonder if it's possible to show both editor+preview tab on this container width

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome 79.0
| Operating System | MacOS Catalina

**Comment by SaraVieira** [comment]
👋👋

Gonna ping @DannyRuchtie and @siddharthkp as they worked on the new embeds

**Comment by siddharthkp** [comment]
👋 

Yeah, we try to be smart (sometimes too smart) to use the space as well as we can. 
Under 800px, we start showing only preview. You can override that behaviour by passing `?view=split` which will then always show both editor and preview

**Comment by NataliaTepluhina** [comment]
@siddharthkp thank you for the answer, that's exactly what I needed! Closing the issue 👍
