### ISSUE TITLE
Console messages not showing up in console.

### ISSUE THREAD

**Issue by briandeheus** [codesandbox/codesandbox-client#3246]
# 🐛 bug report

## Description of the problem
Messages sent to console via `console.log`, `console.debug`, `console.warn` et cetera are not showing up in the console section of codesandbox.

When opening the sandbox in a separate window, outside of the codesandbox GUI, it does show up in the native browser console.

In the browser native console the message does show up, but then inexplicably codesandbox clears the console and my console becomes empty again except for the message `Console was cleared.`.

## How has this issue affected you? What are you trying to accomplish?
I'm trying to understand how my application works by sending log messages to console. 

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1577119298-c52f70238 |
| Browser          | Firefox 71.0 (64-bit) |
| Browser          | Chrome 79.0.3945.88 |
| Operating System | Ubuntu 18.04.3 LTS |

**Comment by SaraVieira** [comment]
Hey!

This is a bug but you can fix half of it by removing the console clearing, you can do that by

* clicking on your avatar
* Clicking preferences
* Select Preview
* Turn off "Clear console"

This only fixes it in a new window, it's still a bug in the codesandbox window :(

**Comment by danielvanc** [comment]
Is there any update on this yet? I too am not getting console messages when I should. Opening in a new window and in the browsers console, i get the error: 

"POST https://codesandbox.io/api/v1/sandboxes/9f5vv/cache 404"

Mine is a private sandbox linked to a private repo.

**Comment by danielvanc** [comment]
Also, If i run the project locally, on my machine, I get the console messages so the problem definately points to codesandbox.

**Comment by lbogdan** [comment]
Hey @briandeheus ,

The sandbox you linked to no longer works. Is this still an issue for you?

**Comment by briandeheus** [comment]
Hi @lbogdan I think the issue has been resolved. I attempted to recreate the issue [here](https://codesandbox.io/s/pensive-mendeleev-9ozdc) and I can no longer reproduce.

**Comment by HartS** [comment]
Not sure if there was a regression, or it's browser-related. In Chrome 88 the above link (https://codesandbox.io/s/pensive-mendeleev-9ozdc) doesn't show anything in the console tray for me, though the message (and a whole bunch of errors) show up in my Chrome Devtools console

**Comment by HartS** [comment]
@CompuIves are you the maintainer? I don't have the ability to reopen this issue.

**Comment by diegoMontesinos** [comment]
The issue remains. See the sandbox shared by @briandeheus.

**Comment by diegoMontesinos** [comment]
Any news on this issue @lbogdan ?

**Comment by EtErNaLiFe12** [comment]
I still have same issue with this..... any upcoming update yet?

**Comment by jodavaga** [comment]
Hey could anyone please help us. console logs are not being displayed on the integrated console window.

**Comment by andrasbacsai** [comment]
Yeah, I can confirm it's still an issue on the [linked](https://codesandbox.io/s/pensive-mendeleev-9ozdc) example.

**Comment by lbogdan** [comment]
Closing, as this now works fine in the linked sandbox:

![image](https://user-images.githubusercontent.com/2083930/119505588-c6db0d80-bd75-11eb-9fa6-c0634f3c3521.png)

(most probably) Fixed by https://github.com/codesandbox/codesandbox-client/commit/546f4d042df5650119142d6c7ed96fcdbc252818 .

**Comment by ArtMooney** [comment]
Happens here and then still for me

**Comment by Lastrick1** [comment]
Happening today for me.

**Comment by sannek** [comment]
@Lastrick1  -- could you make a new issue and include a link to the sandbox that is giving you trouble?

**Comment by Moloantoa2205** [comment]
Hi

Console logs are not being displayed. How do I go about fixing this?

**Comment by pavveu** [comment]
happened today as well ;)
