### ISSUE TITLE
[CI] typings of built library not working in CI-generated Sandbox (Cannot find module, TS2307)

### ISSUE THREAD

**Issue by phryneas** [codesandbox/codesandbox-client#3249]
# 🐛 bug report

## Description of the problem
When the CI builds our library on a PR, the library cannot be used in the resulting CodeSandboxes as the types cannot be found.

> Cannot find module '@reduxjs/toolkit'. ts(2307)

### Links
[PR that is being built](https://github.com/reduxjs/redux-toolkit/pull/294)
[CI build info](https://ci.codesandbox.io/status/reduxjs/redux-toolkit/pr/294/builds/5984)
[unmodified sandbox from CI](https://codesandbox.io/s/thirsty-dhawan-h4l21)
[fork of the above, trying to import @reduxjs/toolkit](https://codesandbox.io/s/jolly-hopper-ebsuq)

**Comment by brabeji** [comment]
[Can reproduce](https://codesandbox.io/s/black-water-e5lwg?file=/src/index.ts) with `@glimmer/syntax`

**Comment by brabeji** [comment]
This seems to be some "backend" issue. When I open both reproductions now, everything works. I'm positive that both reproductions were failing 2 hours ago on build `666e3d0d8` of client.
