### ISSUE TITLE
Editor not loading

### ISSUE THREAD

**Issue by slutske22** [codesandbox/codesandbox-client#3251]
# 🐛 bug report

## Description of the problem

https://codesandbox.io/dashboard is rendering a blank page.  It was working just fine until about 2 hours ago and then it just stopped.  The console gives these errors:

`Uncaught SyntaxError: Unexpected token '<'`

`The resource https://codesandbox.io/public/vscode26/vs/editor/codesandbox.editor.main.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.`

`The resource https://codesandbox.io/public/vscode26/vs/editor/codesandbox.editor.main.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.`

Trying to make a new sandbox, at url https://codesandbox.io/s/, also renering a blank page, with the same errors as above, plus this one:

`Failed to load resource: the server responded with a status of 404 (Not Found)`

Is anyone else having issues today?  I've been using codesandbox for weeks (months maybe?) on various machines and its been working great, I love it.  Not sure if this is just happening to me on my machine or if there is an issue going on...?

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser      | Chrome|
| Operating System | Windows 7 Professional|

**Comment by anyexinglu** [comment]
@slutske22  How did you solve it? I've encountered with the same error: 

![image](https://user-images.githubusercontent.com/8243326/74590468-a805ab80-5049-11ea-9c9a-25273061c999.png)


Software | Name/Version
-- | --
Сodesandbox |  
Browser | Chrome
Operating System | MacOS Mojave 10.14.6

**Comment by slutske22** [comment]
Honestly I don't remember.  It just started working again the next day - that's why I closed the issue.  It was most likely something on their end is what I'm guessing.  Its working just fine for me at the moment.  But considering this happened to you again just now, I'll reopen with this comment and maybe someone can take a look at it?

**Comment by nksabertooth** [comment]
It was not working for me on chrome. I used firefox. started working.

**Comment by oktheniguess** [comment]
The same Is happening to me. I load the page just fine, then get in to practice some new things I learned, and instead of loading with the usual screen, it has a dark outcrop of that and there is no text, nothing

**Comment by SaraVieira** [comment]
Can you please let me know if you get any errors? Or send us a screenshot :)

**Comment by oktheniguess** [comment]
It has the screen as if It were still loading in, no matter how long it had
been open

**Comment by SaraVieira** [comment]
Can you please clear the cache and service workers?

I don't really have any more information

**Comment by oktheniguess** [comment]
I tried clearing cookies, cache, even site data to reset the entire page.
Nothing has worked, its just the same page. I can send you a screenshot of
it if you want?

**Comment by SaraVieira** [comment]
Yes pls, one with the erros in the console pls

**Comment by oktheniguess** [comment]
[image: image.png] That is all I see when I open a new or existing sandbox

**Comment by SaraVieira** [comment]
The image did not upload :(

**Comment by oktheniguess** [comment]
[image: image.png]
Did it work this time?

**Comment by garethx** [comment]
@oktheniguess sadly no

**Comment by mwmwmw** [comment]
If you're here having the same issue. Try opening codesandbox.io in an incognito tab. Can you log in normally from there? 

Lately, I've been having a lot of problems with Codesandbox.io, and I'm only able to use it by logging in using an incognito window. 

It started with me not being able to load the editor. But now I can't even load the site. It just spins. 

I had a gazillion service workers that I cleared out. But it still won't load.

**Comment by SaraVieira** [comment]
Hey

Do you get any errors? This is not good :(

**Comment by Bigted99** [comment]
> 

Same issue i used edge and it works fine just that i cant fork
