### ISSUE TITLE
Is the CodeSandbox server open source?

### ISSUE THREAD

**Issue by veeral-patel** [codesandbox/codesandbox-client#3258]
Hi - thanks for open sourcing this repo! I didn't find the Phoenix API server in this repo...is it here or open sourced somewhere else? Thanks!

**Comment by lbogdan** [comment]
Hey @veeral-patel ,

Currently the API server, and all other supporting microservices, are not open-source.

**Comment by veeral-patel** [comment]
@lbogdan No worries. The reason I ask is because I'm trying to generate preview images for a list of todo lists in my React application. See this issue:

https://github.com/facebook/react/issues/17770

Someone suggested CodeSandbox had solved this problem, sending me this screenshot:

![71753154-81dbd180-2e36-11ea-9edf-431b8e633e5e](https://user-images.githubusercontent.com/12554095/71770488-cc665800-2ee1-11ea-8f36-3402bed7ce33.png)

Do you think you could please share how you're doing this? I would really appreciate it!! I've thought about server rendering each todo list and taking a screenshot with puppeteer, so far.

**Comment by lbogdan** [comment]
We have a microservice that uses [puppeteer](https://github.com/puppeteer/puppeteer) to load the sandbox and take a screenshot.

**Comment by veeral-patel** [comment]
@lbogdan got it. By load the sandbox, do you mean render it on the server with ReactDOMServer?

**Comment by lbogdan** [comment]
No, I mean loading the sandbox (preview), like https://vue.csb.app/ .

**Comment by veeral-patel** [comment]
@lbogdan Oh, so for https://vue.csb.app/, you would just open https://vue.csb.app in a headless browser and take a screenshot of it?

What if it's a private CodeSandbox?

**Comment by lbogdan** [comment]
We don't take screenshots of private sandboxes, because the screenshot images are publicly hosted on a CDN.

**Comment by veeral-patel** [comment]
@lbogdan got it. In my application, our screenshots will be stored in a private S3 bucket, so that's not a concern.

How would you take screenshots of private sandboxes, if your team decided to?

**Comment by lbogdan** [comment]
Probably using a global secret token that would allow to load a private sandbox.

**Comment by veeral-patel** [comment]
@lbogdan got it, thank you!
