### ISSUE TITLE
Nullish-coalescing operator support for CRA

### ISSUE THREAD

**Issue by dwelle** [codesandbox/codesandbox-client#3260]
# 🌈 Feature

Recently a support for optional chaining in CRA apps has [been added](https://github.com/codesandbox/codesandbox-client/commit/7acb6fc8de00e1fc57a97252fe19f76bed2b63bd). Can we also enable nullish-coalescing operator, which has been added in the same [3.3.0](https://github.com/facebook/create-react-app/releases/tag/v3.3.0) CRA release?

**Comment by CompuIves** [comment]
Yep, that sounds good! I'll add it now.

**Comment by dwelle** [comment]
Thanks! :heart_eyes:
