### ISSUE TITLE
oEmbed URL in sandbox metadata is broken for some projects

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#3266]
# 🐛 bug report

## Description of the problem
For example, the oEmbed url in the metadata of https://codesandbox.io/s/0joolkowp is:
```
<link rel="alternate" type="application/json+oembed" href="https://codesandbox.io/oembed?url=https://codesandbox.io/s/&amp;format=json" title="Force Graph ❤️">
```
Visiting that URL produces: `{"error":"Not found"}`. A correct URL is produced for most others I tested, and I couldn't work out what differs between those where it works and doesn't. Perhaps the code will have the answers 🔮

**Comment by CompuIves** [comment]
I've deployed a fix for this! The problem was on the server side: sandboxes without an alias would get the wrong url in these cases.
