### ISSUE TITLE
Uploading animation continues to show after upload has failed

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#3272]
# 🐛 bug report

## Description of the problem
If you try and upload a file larger than the maximum static file upload size of 7Mb, you still see the ‘Uploading Files…’ animation. The upload silently fails with a 413 error after some time, but the animation continues to show as if it were still uploading.

## How has this issue affected you? What are you trying to accomplish?
Sitting waiting for an upload that will never finish :)

**Comment by lbogdan** [comment]
This was fixed in #3273 , although the error notification looks weird, as it includes the error response that we get back from the server:

![image](https://user-images.githubusercontent.com/2083930/73464919-49250e80-4388-11ea-9b3f-0ae9eb68ddf3.png)

I addressed this issue in #3425 .

**Comment by lbogdan** [comment]
Closing this, as both PRs were merged and deployed.
