### ISSUE TITLE
CSS classes are showing as undefined in preview.

### ISSUE THREAD

**Issue by rmarquardt1** [codesandbox/codesandbox-client#3275]
# 🐛 bug report

## Description of the problem
The preview of my react app is not working correctly. All of the class properties show undefined instead of the class name after being built. Everything was working fine until yesterday and everything works fine when I run the code in my local dev environment. I am using css modules, I'm not sure if that is where the problem is occurring. But I have been using css modules for the past month or so without any issues.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/profileimage-283gi

### Your Environment
Browser: Chrome
OS: Windows 7 and Windows 10

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by gabriel-peracio** [comment]
I can confirm this was happenning yesterday as well, I am using css modules with sass in my create-react-app project and it isn't returning the class names.

I tried opening previous projects that were working before (just to confirm it wasn't my code that changed or a dependency) and they are broken as well.

No errors in the console

**Comment by davidlukerice** [comment]
Happening to me as well on a fresh project with just the `styles.css` updated to `styles.module.css`
https://codesandbox.io/s/great-moon-1ve44

**Comment by gabriel-peracio** [comment]
Issue appears to have been resolved
