### ISSUE TITLE
CSS Modules broken in Create React App template

### ISSUE THREAD

**Issue by davidlukerice** [codesandbox/codesandbox-client#3278]
# 🐛 bug report

## Description of the problem
Trying to import a css modules file no longer seems to work. I had an app that used them and it stopped working the past week or so in codesandbox.

## How has this issue affected you? What are you trying to accomplish?
Just importing a css module

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1578405578-554e4be5e ?
| Browser          | Chrome 79.0.3945.88 
| Operating System | Mac OS X 10.15.2

**Comment by gabriel-peracio** [comment]
Duplicate of #3275

**Comment by davidlukerice** [comment]
Good catch! I'll close this out and watch that one.
