### ISSUE TITLE
Transpiling hangs (as of 1.5 days ago -- patch had breaking changes?)

### ISSUE THREAD

**Issue by NawarA** [codesandbox/codesandbox-client#3285]
# 🐛 bug report

## Description of the problem
As of yesterday / the day before, my sandbox started taking 15 mins to transpile. I've used the sandbox as my IDE daily, for months, so I can tell when it stops working.

Because codesandbox now hangs on "transpiling", I believe the issue is related to two things:
1) a module being loaded by my app, has a babel issue with codesandboxes babel backend config
2) a codesandbox update (such as the recent nullish-coalescing babel plugin) that was added to codesandbox has slowed down all transpile times. If true, medium size apps would transpile more slowly as their complexity increases.

To test these hypotheses, I've removed every NPM dep to isolate which dep (which were all recently working perfectly) is now triggering the "transpiling hang". I isolated it to Material-UI Icons which is a few megabytes. I've tried several versions of material-ui-icons, but they all seem to make codesandbox hang. Again this dep was transpiling perfectly 2 days ago. So it's not that module, but the way it, or modules of similar structure or size, are being transpiled.
 
Links below as evidence of "transpile hang":

## How has this issue affected you? What are you trying to accomplish?
I can no longer use Codesandbox as my IDE. I have to search for alternatives to codesandbox or try to spend time figuring out what changed in the most recent codesandbox released that caused the issue to surface.

Also, perhaps other React apps using material UI are running into the issue? I'm not certain, but I imagine maybe the case.

This is a critical issue, because the IDE no longer loads the application as of 1.5 days ago

### Link to sandbox: [link]() (optional)

1) Sandbox with deps removed, and loading material-icons hangs transpile
https://codesandbox.io/s/frontend-c9jwk
** `Please go the "/feed" path to see the app load`
2) Github import https://codesandbox.io/s/github/NawarA/Frontend
** `Has been working until now`

### Your Environment

| Software         | Name/Version |
| Сodesandbox  | PROD-1578405578-554e4be5e  
| Browser | Chrome 78 (latest) |
| Operating System | Windows 10 |

**Comment by NawarA** [comment]
Tried creating a new react app, installing material ui, transpiler now hangs.

https://codesandbox.io/s/async-paper-f102b

**Comment by CompuIves** [comment]
I can verify this. Taking a look now...

**Comment by CompuIves** [comment]
It should be fixed now! Could you verify? 

The issue was that we had an old cached version of BrowserFS on the specific URL, I don't know how though. BrowserFS would just hang on initialization, so our promises would never resolve. Weird. Need to take a more in-depth look later when I have more time.

**Comment by NawarA** [comment]
Looks like it worked 👍 

Yes, strange

Good job isolating the issue 💪
