### ISSUE TITLE
Two duplicate files in 'packages/common/src/theme/__snapshots__/'

### ISSUE THREAD

**Issue by R4M80MrX** [codesandbox/codesandbox-client#3286]
![image](https://user-images.githubusercontent.com/29365693/71964102-eaacba80-3237-11ea-9ce0-f839f20eb4ac.png)

**Comment by R4M80MrX** [comment]
@SaraVieira

**Comment by soorajshankar** [comment]
The last one is having a space in the file, raising a PR now.

**Comment by MichaelDeBoey** [comment]
Closed by #3303
