### ISSUE TITLE
When I type in the terminal, every entry gets double

### ISSUE THREAD

**Issue by dauledk** [codesandbox/codesandbox-client#3300]
# 🐛 bug report

Please see attached:

![problem](https://user-images.githubusercontent.com/9967422/72053144-c0560e00-32c6-11ea-8059-ccf15b6ddf17.gif)

**Comment by CompuIves** [comment]
Hey! Do you still get this? Which sandbox are you experiencing this on? 

I can't reproduce the problem right now, but it might be under specific conditions.

**Comment by dauledk** [comment]
It was [this](https://codesandbox.io/s/re-produce-funs-is-not-function-error-8jiqe?fontsize=14&hidenavigation=1&theme=dark) sandbox, but seems like the issue is resolved now. I will update if it happens again 🙃 Thanks for an awesome tool 🙌
