### ISSUE TITLE
Typeface dropdown(in side panel) is broken

### ISSUE THREAD

**Issue by rramaa** [codesandbox/codesandbox-client#3304]
# 🐛 bug report

### Apollo Server Template

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1578492405-52217bc8c
| Browser          | Version 79.0.3945.88 (Official Build) (64-bit)
| Operating System | MacOS Catalina

![image](https://user-images.githubusercontent.com/16651792/72136689-5cf3db00-33af-11ea-9a6a-18582123f352.png)

**Comment by SaraVieira** [comment]
Hey!

We actually moved to only using a standard browser dropdown for this so this UI has been removed in the new sidebar :)
