### ISSUE TITLE
Bug: Silent error in the console when not signed in and trying to fork a server template

### ISSUE THREAD

**Issue by LoganArnett** [codesandbox/codesandbox-client#3310]
# 🐛 bug report

## Description of the problem
When trying to create a Node HTTP Server sandbox nothing happens, no error, no feedback at all.

Looking at the console in the Network tab I see the error come back for the fact that I need to be signed in to create a server template but the UI never reflects that

https://cloudapp.loganarnett.com/yAuL1DAR

## How has this issue affected you? What are you trying to accomplish?
Just trying to create a Node HTTP Server sandbox

### Link to sandbox: [link]() (optional)
N/A

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest
| Browser          | Chrome
| Operating System | OSX 10.15.1

**Comment by arthurdenner** [comment]
@LoganArnett, can you check if this still happening and if you have the latest version? I tried to reproduce it, but when I click on a template, I navigated to its URL, it didn't try to fork. If it's not happening anymore, can you close the issue, please?

### My environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1579516524-d2848195c
| Browser          | Chrome Version 78.0.3904.97 (Official Build) (64-bit)
| Operating System | macOS Mojave Version 10.14.6
