### ISSUE TITLE
CRA & TypeScript readonly

### ISSUE THREAD

**Issue by dwelle** [codesandbox/codesandbox-client#3316]
# 🐛 bug report

## Description of the problem

CRA app on CodeSandbox doesn't work with TypeScript `readonly` modifier:

```js
function x (x: readonly number[]) {}
```

Results in error:

![image](https://user-images.githubusercontent.com/5153846/72202750-65a5e900-3463-11ea-9656-1c553bda1c1a.png)

(in non-CRA app, [it works](https://codesandbox.io/s/peaceful-hodgkin-dw51c)).

Relates to #3260 and recent fix for optional chaining.

Should I investigate and compile a list of all TS features that don't work in CRA context?

Thanks!

### Link to sandbox:

https://codesandbox.io/s/pedantic-thompson-3gmcf

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1578672633-2548a0612
| Browser          | Chrome
| Operating System | Win7

**Comment by CompuIves** [comment]
Thanks for the headsup! I'm looking now at what the cause is. Do you think it could be because of an old preset? I'm not sure which version of `@babel/preset-typescript` we currently use, I'll take a look!

> Should I investigate and compile a list of all TS features that don't work in CRA context?

That would be super useful.

**Comment by CompuIves** [comment]
Yep, that's it. We're on Babel 7.3.4, while readonly was added in 7.4.0. I'll look into updating now!
