### ISSUE TITLE
Embeds: Buttons Obscure Preview Content

### ISSUE THREAD

**Issue by karlhorky** [codesandbox/codesandbox-client#3321]
# 🐛 bug report

## Description of the problem

The **Like**, **Open Sandbox**, **Refresh**, and **Open in New Window** buttons obscure the content in the preview, and prevent easy interaction with elements far down on the page:

![Kapture 2020-01-13 at 13 26 20](https://user-images.githubusercontent.com/1935696/72255991-6461f100-3608-11ea-92d6-82a9a24e34d3.gif)

The **Refresh**, and **Open in New Window** buttons come from the `hidenavigation=1` option.

Would it be possible to add some space at the bottom of the preview content, so that the very bottom is not obscured when scrolled down all the way?

## How has this issue affected you? What are you trying to accomplish?

I would like to see and interact with the whole page in the preview.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| СodeSandbox      | PROD-1578672633-2548a0612 |
| Browser          | Chrome 79.0.3945.117 |
| Operating System | macOS Catalina 10.15.2 (19C57) |

**Comment by karlhorky** [comment]
Ah, this also happens with the console content:

![Kapture 2020-01-13 at 13 56 59](https://user-images.githubusercontent.com/1935696/72257777-b9a00180-360c-11ea-84bc-fbe7e09fb540.gif)

**Comment by CompuIves** [comment]
Great feedback! I like the idea of adding a bit of margin to the bottom, but like you said, it wouldn't solve the console. Maybe we could integrate it with the devtools, but then it seems that a bar would be the most simple solution. Would like your thoughts as well @DannyRuchtie and @siddharthkp

**Comment by siddharthkp** [comment]
By bar, you mean stack it on the top of the console?

**Comment by karlhorky** [comment]
Not the most polished design, but just as an idea for discussion: would it be possible to get everything in a single bar?

<img width="893" alt="Screen Shot 2020-01-13 at 16 33 41" src="https://user-images.githubusercontent.com/1935696/72268691-91bb9880-3622-11ea-9bb4-21502eb98bfe.png">

Two points with this:

1. Need to figure out what to do with the Clear button, Filter textbox and Error Type dropdown. In this design above, they disappear even more than they did before.
2. This raises the question of what happens when the `hidedevtools=1` option is specified... Maybe the bar stays for the "Open Sandbox" and other buttons, but the buttons and functionality for the devtools disappear?

**Comment by SaraVieira** [comment]
Do you mind if I close this?

We need that button for phishing sandboxes and also for allowing you to open the sandbox ina new window?

**Comment by karlhorky** [comment]
Yep, if there's reasons that CodeSandbox embeds need to have it, then sounds good - just want to have it documented.

Closing.
