### ISSUE TITLE
unable to type

### ISSUE THREAD

**Issue by aidanh958** [codesandbox/codesandbox-client#3325]
# 🐛 bug report

## Description of the problem
 I cannot type the code I wish when I try my cursor just turns into a white box and I cant type when I press backspace it just moves back one.

## How has this issue affected you? What are you trying to accomplish?
 I am trying to create code for a school projects but I cant because I cant even type!!!

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | all
| Browser          |  chromebook

**Comment by t0lkman** [comment]
Looks like it's the same issue as in #3228

**Comment by andrasbacsai** [comment]
There were a lots of changes with the Live mode, so I think it's not relevant anymore.
Closing now. If you have any question, let us know!
