### ISSUE TITLE
Error: /src/styles.css hasn't been transpiled yet.

### ISSUE THREAD

**Issue by mloffer** [codesandbox/codesandbox-client#3326]
# 🐛 bug report
When adding CSS assets to angular-cli.json, the console reports `Error: /src/styles.css hasn't been transpiled yet.`.

## Description of the problem
Steps to reproduce:

1. Start a new CodeSandbox
2. Add `mgl-mapbox-gl` and `mapbox-gl` dependencies
3. Add required CSS files to angular-cli.json
`"./node_modules/mapbox-gl/dist/mapbox-gl.css",
 "./node_modules/@mapbox/mapbox-gl-geocoder/lib/mapbox-gl-geocoder.css"
`
4. Error in console: `Error: /src/styles.css hasn't been transpiled yet.`

## How has this issue affected you? What are you trying to accomplish?
I'm trying to use CodeSandbox to highlight a bug in another app. Funny, that. 😏

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/polished-shadow-sfdsf

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Version 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)
| Operating System | Windows 10 x64 build 1909

**Comment by CompuIves** [comment]
Hey! Thanks for this report, I'm working on a fix now.
