### ISSUE TITLE
Not able to switch Themes

### ISSUE THREAD

**Issue by DannyRuchtie** [codesandbox/codesandbox-client#3329]
# 🐛 bug report
I'm not able to switch themes in Safari

## Description of the problem
When trying to switch themes I get the following error:
 TypeError: null is not an object (evaluating 'this._node.addEventListener')

## How has this issue affected you? What are you trying to accomplish?
I can not user different themes 

### Link to sandbox: [link]() (optional)
All my sanddboxes
https://codesandbox.io/u/DannyRuchtie

MacOS Cataline 
Safari (Version 13.0.4 (15608.4.9.1.3)

**Comment by justKD** [comment]
It's annoying, but you can still change the theme in your own settings.

file > preferences > settings

Then search for "Workbench: Color Theme". It's just a dropdown with the available themes. Which is all the menu shortcut throwing that error around should be showing.

**Comment by CompuIves** [comment]
This one has been fixed!
