### ISSUE TITLE
Dashboard sandbox actions hidden

### ISSUE THREAD

**Issue by TomPradat** [codesandbox/codesandbox-client#3330]
# 🐛 bug report

## Description of the problem

- Go to the dashboard page [https://codesandbox.io/dashboard/recent](https://codesandbox.io/dashboard/recent)
- Click on the 3 dots of a sandbox card

=> sometimes the menu is displayed on the bottom and some actions are hidden

![Capture d’écran de 2020-01-14 13-57-29](https://user-images.githubusercontent.com/16164512/72346819-f801f300-36d6-11ea-8ba9-37a050bfe671.png)

## How has this issue affected you? What are you trying to accomplish?

I was trying to delete a sandbox

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |   |
| Browser          | Firefox 72.0.1 |
| Operating System | Ubuntu 18.04 |

**Comment by garethx** [comment]
Follow https://github.com/codesandbox/codesandbox-client/issues/3274 for updates
