### ISSUE TITLE
502 Bad Gateway, no further details

### ISSUE THREAD

**Issue by oliversturm** [codesandbox/codesandbox-client#3336]
# 🐛 bug report

## Description of the problem

I'm trying to run my GitHub project here: https://codesandbox.io/s/github/oliversturm/sudoku-solver

It uses react-app-rewired, so I added `sandbox.config.json` and set the template to `node`. This is based on information from an old issue - you used to have a working sample somewhere of this setup, but it's broken now. Maybe there's a trick here I'm missing?

I receive this:

> 502: Bad Gateway

> We had trouble connecting to the server, try restarting it or check the logs to see what happened.

I read various other threads about the same error. I double-checked my references and scripts - needless to say, everything works fine locally. The way I understand it, CSB should run the `start` script and I believe that should work correctly.

Clearly something doesn't work, but I have no idea how to figure out what it is. The error message mentions "logs", but there are no logs - the only output in the Terminal window is this:

```text
> Sandbox Container: Starting sandbox nj3s7...
> Sandbox Container: Sandbox nj3s7 started
```

The message also suggests "restarting the server", but I don't know how to do that either. I can reload the page of course, but it just comes up again with the same error (and the same sandbox id - does that mean nothing even restarted?).

How do I figure out what's going wrong here?

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  ? |
| Browser          | Tried latest Firefox and Chrome |
| Operating System | Fedora Linux |

**Comment by lbogdan** [comment]
Hey @oliversturm ,

The issue was that we were using `yarn`, and for some reason your project doesn't work with it - after installing packages with `yarn` and doing `yarn start`, it errors with
```
$ yarn start
yarn run v1.21.1
$ react-app-rewired start
Cannot find module 'babel-loader'
Require stack:
- D:\work\codesandbox\repro\sudoku-solver\config-overrides.js
- D:\work\codesandbox\repro\sudoku-solver\node_modules\react-app-rewired\config-overrides.js
- D:\work\codesandbox\repro\sudoku-solver\node_modules\react-app-rewired\scripts\start.js
error Command failed with exit code 1.
```
I just pushed an update which looks for `package-lock.json` and uses `npm install` instead, now it kind of works, but there's still and issue with `webpack`'s HMR websocket, which tries to connect to

![image](https://user-images.githubusercontent.com/2083930/72380387-f6a7e900-371d-11ea-953e-d1edffbc7b59.png)

instead of `wss://zjiek.sse.codesandbox.stream/sockjs-node` (notice the `wss` - secure websocket - protocol).

**Comment by lbogdan** [comment]
Looks like this is related: https://github.com/facebook/create-react-app/issues/8075 .

**Comment by oliversturm** [comment]
> The issue was that we were using yarn, and for some reason your project doesn't work with it 

True. Not sure why that is, but apparently a project created with CRA and using `--use-npm` doesn't contain the references required by yarn. I have added them manually so the project works both with yarn and npm now, but thanks also for your fix!

> issue with webpack's HMR websocket
> Looks like this is related: facebook/create-react-app#8075

Yes, thank you. Since the patch mentioned in that issue is not released yet, I downgraded to react-scripts 3.2.0 and now the my project works correctly in CSB.

Just a final question on this issue - it would be great if CSB gave me access to the information you discovered. That output created by `yarn start` wasn't visible anywhere. Maybe this could be improved?

**Comment by lbogdan** [comment]
> That output created by yarn start wasn't visible anywhere.

Yes, we only show the logs as they happen - so you can see them while the sandbox starts, but not if it's already started. As they're not purely text (we run commands in a virtual tty, and they usually output control characters), it's not trivial to store / display them after the fact. If you're in a sandbox you own, you can always click "Restart Sandbox" (which restarts the dev server running inside the container) or "Restart Server" (which actually restarts the container the sandbox runs in), and see the logs again.

While GitHub imported sandboxes are not owned by you (you can say they are "owned" by the GitHub repo, as they mirror it), you can't do those actions above, but you can fork it and then you can investigate on it.

I'll go ahead and close this for now, please reopen / open a new issue if having further issues.

**Comment by oliversturm** [comment]
> While GitHub imported sandboxes are not owned by you (you can say they are "owned" by the GitHub repo, as they mirror it), you can't do those actions above, but you can fork it and then you can investigate on the fork.

That's interesting to know, but I'm afraid I'll probably forget by the time I need it again. It's also quite cumbersome to do ... I really enjoy CSB but I rarely do any development there since I prefer working locally. So I'll be using GitHub imported sandboxes almost all the time. I think it would be a very important addition if the "restart" actions could be made available for this scenario, it would make the hunt for such issues much easier.

**Comment by lbogdan** [comment]
Well, in 99% of cases, if it works locally, it should also work inside a server sandbox, so it was never a priority, I guess. 🙂

**Comment by oliversturm** [comment]
Understood. It's just one of those things... as a casual user of CSB, my first reaction to an error coming up on load is "hey, let's try again". So I refresh the page, maybe more than once, and any initial info is gone. I see a message that mentions logs (which I don't see) and restarting (which I can't do). Quite unfortunate, even though I accept that this shouldn't happen too often...

> As they're not purely text (we run commands in a virtual tty, and they usually output control characters), it's not trivial to store / display them after the fact.

It comes to mind that various command line gif generators I've used have no trouble storing such output, including control characters. On that basis, you could add a "replay startup output" feature and I could see what happened even without restarting the sandbox or server.
