### ISSUE TITLE
How to use the verticallayout when embedding iframes?

### ISSUE THREAD

**Issue by junedchhipa** [codesandbox/codesandbox-client#3338]
I want to have the editor and preview to have a vertical layout (top/bottom). Somehow, it doesn't work as it says in the docs.

```html
<iframe
src="https://codesandbox.io/embed/apx-zoomable-timeseries-5681o?fontsize=14&hidenavigation=1&theme=light&verticallayout=1"
style="width:100%; height:800px; border:0; border-radius: 4px; overflow:hidden;"
title="apx-zoomable-timeseries"
allow="geolocation; microphone; camera; midi; vr; accelerometer; gyroscope; payment; ambient-light-sensor; encrypted-media; usb"
sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin"
></iframe>
```

As specified in the docs, I am using `verticallayout=1` but I am seeing this
![Screen Shot 2020-01-15 at 6 20 27 PM](https://user-images.githubusercontent.com/17950663/72435284-b9963200-37c3-11ea-919f-86333e167d83.png)

Am I missing something?

**Comment by garethx** [comment]
No, you're not missing anything. The `verticallayout` option is no longer supported, and there's a PR awaiting deployment to remove that option from the docs. Sorry for the confusion.

**Comment by CompuIves** [comment]
I might want to add the feature back, as this is a good use case. Both the graph view and the code view have 50% empty space left. I'll get back on this today, will re-open if we want to add it back!

**Comment by junedchhipa** [comment]
@CompuIves Yes, on small screen sizes, the graph gets squeezed and doesn't look pretty. As there is a lot of empty space below, `verticallayout` would work best in such cases.
Thanks for reconsidering this.

**Comment by dustinlacewell** [comment]
Doh!

**Comment by hilmanski** [comment]
anyone know any update around this verticallayout?

**Comment by tristandubbeld** [comment]
Hey @hilmanski, I dug into it a bit but it looks like `verticallayout` wasn't brought back. Do you need it for anything in particular?

**Comment by hilmanski** [comment]
Just for embedding it on my blog. It's not urgent/fatal without it though. Thanks
