### ISSUE TITLE
Angular 8 container

### ISSUE THREAD

**Issue by TaiyouFTW** [codesandbox/codesandbox-client#3343]
# ❔ Question

Hello, is there any way to import a sample angular 8 project from github into a container to use the terminal? (for use cli commands)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Opera
| Operating System | windows 10

**Comment by lbogdan** [comment]
Hey @TaiyouFTW ,

Sorry for the delayed answer!

Yes, you need to add a `sandbox.config.json` file to your repository, with the contents you can see here: https://github.com/lbogdan/cs-angular-starter/blob/master/sandbox.config.json . You can check out how that repository works inside a container in CodeSandbox here: https://codesandbox.io/s/github/lbogdan/cs-angular-starter .

Closing this for now, for any further questions you can find us on [Spectrum](https://spectrum.chat/codesandbox/).
