### ISSUE TITLE
Angular app has stopped working

### ISSUE THREAD

**Issue by MarsiBarsi** [codesandbox/codesandbox-client#3349]
# 🐛 bug report

## Description of the problem

I have a demo page for my Angular library on codesandbox that I start through link from Github source code such way: https://codesandbox.io/s/github/TinkoffCreditSystems/ng-polymorpheus/tree/master/projects/demo

Link to Github source code: https://github.com/TinkoffCreditSystems/ng-polymorpheus/tree/master

There is an error: 
`Could not find module in path: '@tinkoff/ng-polymorpheus' relative to '/src/app/modules/comboBox/comboBox.module.ts'`
But a package '@tinkoff/ng-polymorpheus' is available and works fine

The package did not change. This demo had worked fine on codesandbox with the package of current version before.

## How has this issue affected you? What are you trying to accomplish?

My demo page does not work

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | current
| Browser          | Chrome 79.0.3945.117
| Operating System | MacOS Mojave 10.14.6 / Windows 10 / Ubuntu 18

**Comment by CompuIves** [comment]
Hey! I took a look at the error and the dependency [here](https://unpkg.com/browse/@tinkoff/ng-polymorpheus@1.0.3/), and it seems like that latest version (`1.0.3`) doesn't have a `main` or `module` field in the `package.json` and no `index.js`. I think that's the reason why it couldn't find any files. When changing it back to `1.0.2` it starts to work again.

Could that be the issue?

**Comment by MarsiBarsi** [comment]
Thank you for your answer @CompuIves. I republished the package with module and main and it works now

I thought that version 1.0.3 works because demo requests 'latest' version and it seems like codesandbox caches 'latest' version as previous for several days
