### ISSUE TITLE
JavaScript Only template

### ISSUE THREAD

**Issue by the-spyke** [codesandbox/codesandbox-client#3351]
# 🌈 Feature

I want to create a sandbox for a pure library. There will be only JS files and console output from it. No browsers/css/etc. 

The `Vanilla` template doesn't allow hiding the browser and it consumes a half of the space (especially in embed). Removing those features will make it more lightweight too. And, of course, there should be parcel/babel to be able to import ESM packages and write in modern syntax.

**Comment by garethx** [comment]
It is possible to hide the browser panel and leave just the console - you can do this by dragging the console tab to the top so that it's before the browser tab. In an embed, you can use the `expanddevtools` option (https://codesandbox.io/docs/embedding#embed-options).

**Comment by the-spyke** [comment]
@garethx Of course, I don't want all users to manually resize console tab too. `expanddevtools` means browser preview will occupy 1/4 of the window instead of 1/2. I don't heed it at all: there is no `html` file.

**Comment by garethx** [comment]
> I don't want all users to manually resize console tab too
They don't need to, the change is saved in the sandbox.

**Comment by garethx** [comment]
> browser preview will occupy 1/4 of the window instead of 1/2. I don't heed it at all:

So set `previewwindow=console`

**Comment by the-spyke** [comment]
> So set `previewwindow=console`
@garethx Oh, thanks, missed this somehow.
