### ISSUE TITLE
Using Quick Open (Ctrl+P) to goto a file doesn't move cursor focus to the selected file

### ISSUE THREAD

**Issue by alanlal** [codesandbox/codesandbox-client#3354]
# 🐛 bug report
Using Quick Open (Ctrl+P) to go to a file doesn't move cursor focus to the selected file

## Description of the problem
While using the Quick Open feature (Ctrl+P) and selecting a file (Using Enter key), No cursor is shown in the selected file.

## How has this issue affected you? What are you trying to accomplish?
I was trying to use this feature as in vs-code. There the cursor focus will be moved to the file selected and I could start typing directly. Here, I tried typing after selecting a file from Quick Open and it didn't work.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Browser          |Chrome 79
| Operating System | Win 10

**Comment by jessmartin** [comment]
This was driving me crazy today. Also seeing this same behavior in Chrome 80 on Mac OS Catalina.
