### ISSUE TITLE
React DevTools takes over cmd+f  when opened (no focus)  

### ISSUE THREAD

**Issue by DannyRuchtie** [codesandbox/codesandbox-client#3355]
# 🐛 bug report
React DevTools takes over cmd+f  when opened (no focus)  

## Description of the problem
Small UX bug where the React DevTools takeover the cmd+f keyboard shortcut.

## How has this issue affected you? What are you trying to accomplish?
Breaks Dev experience. Need to close the DevTools to do search.
A solution would be to check if the DevTools has focus  

### Link to sandbox: 
All react sandboxes

### Your Environment
Macos  (Chrome, Safari,  etc)

**Comment by lbogdan** [comment]
Might not be related, but Ctrl+F does not work for me in the dashboard, either (although I have no idea who is taking it over 🙂). @DannyRuchtie , can you please check if this also applies for you?

**Comment by DannyRuchtie** [comment]
@lbogdan Same for me
