### ISSUE TITLE
Latency between switching files and split windows.

### ISSUE THREAD

**Issue by rmarquardt1** [codesandbox/codesandbox-client#3359]
# 🐛 bug report

## Description of the problem
When I switch to another file or move between split windows in my project, it can take up to 20 seconds before I can start editing the file.

## How has this issue affected you? What are you trying to accomplish?
I love using this site. It makes working on my project from multiple environments very easy. But it's taking me much longer to work on my project because of the latency between switching files.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Chrome         |
| Windows XP / 10 |

**Comment by CompuIves** [comment]
That is very interesting. Does this happen in every sandbox? If it only happens in one sandbox, would you mind sharing that sandbox?

**Comment by rmarquardt1** [comment]
It seems to be happening in all my sandboxes. The sandbox is https://codesandbox.io/s/cool-night-9o58q. Thanks!

**Comment by garethx** [comment]
I haven't been able to reproduce in the linked sandbox. Can you confirm whether the issue continues when you're in an incognito window?

**Comment by CompuIves** [comment]
Hmm, I'm able to reproduce now. It seems like one of our components is rerendering excessively, diving in!
