### ISSUE TITLE
Being able to link to a folder as a collection with context information

### ISSUE THREAD

**Issue by drcmda** [codesandbox/codesandbox-client#3362]
# 🌈 Feature

We can put sandboxes into folders in our dashboard, but there seems to be no way to share the link. It would be extremely useful if we could create collections or sandboxes where it takes the **title and description** of each box and shows it underneath the thumbnail.

Something like this: https://threejs.org/examples

Only that it could be the regular folder view + description so that users can see what the boxes are about.

Keywords and a keyword filter would also be super valuable.

**Comment by CompuIves** [comment]
This is a very nice feature request! We've been wanting to create this for a while (the folders are even called "Collections"), but didn't opt for it because we thought people also wanted to make collections of sandboxes owned by other people. What is your opinion on this?

**Comment by drcmda** [comment]
i think if someone wanted to create collections of public boxes, for instance collecting boxes that are inspiring, i think why not. personally i would love to take a bunch of mine and make specific collections, for libraries, where i could collect all the demos that crop up, with keywords like the technologies that have been used or entry level, expert level tags, etc. 

im reaching a point where i have so many, and no place to put them publicly, that i think it's a waste because new users never get to see them (the boxes usually have been created as a response to some request in some forum etc). if i had a publicly available spot for demos, inspirations and learning resources that would be a big help. 🎁

**Comment by drcmda** [comment]
PS. i think generally, this could be a very useful feature for library maintainers. maintaining examples is a huge churn, and codesandbox already made it very easy for us due to the team features. but we still have to gather them somehow and somewhere - and having tried myself, i don't think i can compete against CSB's folder view. it's almost perfect, just descriptions and a keyword filter, and it would be an incredible assets.
