### ISSUE TITLE
Failed to construct 'Image': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

### ISSUE THREAD

**Issue by mantou132** [codesandbox/codesandbox-client#3363]
# 🐛 bug report

## Description of the problem
`import '@mantou/gem'` an error occurred
https://codesandbox.io/s/misty-framework-yf7gh?fontsize=14&hidenavigation=1&theme=dark

## How has this issue affected you? What are you trying to accomplish?
Cannot create examples using `@mantou/gem`

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |N/A      |
| Browser          |Chrome      |
| Operating System |macOS      |

**Comment by mantou132** [comment]
Seems to be caused by incorrect compiled code

**Comment by lbogdan** [comment]
Hey @mantou132 ,

Is this still an issue for you? I opened the linked sandbox, but I'm not sure what should I look at?

**Comment by mantou132** [comment]
@lbogdan seems to work now

**Comment by CompuIves** [comment]
Ah good one! I fixed this last Sunday, but forgot to close the issue. Whoops!
