### ISSUE TITLE
Could not fetch dependencies – ENOENT on CHANGELOG.md

### ISSUE THREAD

**Issue by parkerziegler** [codesandbox/codesandbox-client#3371]
# 🐛 bug report

## Description of the problem

👋 Hey folks, thanks so much for all the hard work on CodeSandbox ❤️I've had some issues getting a new package a few of us @FormidableLabs just recently published to work on CodeSandbox. Specifically getting this error when trying to resolve [`renature`](https://github.com/FormidableLabs/renature) as a dependency:

```
Error: Could not fetch dependencies, please try again in a couple seconds:
Something went wrong while packaging the dependency renature@0.1.0:
  ENOENT: no such file or directory, lstat '/tmp/3207168890/node_modules/renature/tmp/3207168890/node_modules/renature/CHANGELOG.md'
```

## How has this issue affected you? What are you trying to accomplish?

I'm trying to get `renature` to build in CodeSandbox so we can make examples there to help users. I set up a barebones repo on GitHub just to verify that everything works as expected locally: https://github.com/parkerziegler/renature-demo. Running that locally does indeed work as expected.

The path specified in the error message is quite concerning to me. It almost looks like CodeSandbox has somehow duplicated the `/tmp/3207168890/node_modules/renature` portion, which I think may be the culprit. I've included the CodeSandbox link below.

It is also worth noting that the package was only published a few hours ago, so perhaps could be something with it being a recent publish and `unpkg` being a bit weird? I've verified that everything that should be on unpkg is indeed there: https://unpkg.com/browse/renature@0.1.0/

Thanks for any help you may be able to provide, and let me know if I can provide more info!

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  PROD-1579516524-d2848195c
| Browser          | Chrome 79.0.3945.117 and Firefox 72.0.1
| Operating System | macOS 10.14.6 (Mojave)

**Comment by CompuIves** [comment]
Need to deploy still, sorry!

**Comment by lbogdan** [comment]
Closing this, as we deployed the fix during the weekend and the linked sandbox now works. Please reopen if you have further issues.
