### ISSUE TITLE
Creating sandbox from GitHub commits returns 422

### ISSUE THREAD

**Issue by dwelle** [codesandbox/codesandbox-client#3379]
# 🐛 bug report

Note: for me personally, this has low priority since there's a workaround (see at the end).

## Description of the problem

Creating a Sandbox from a GH commit doesn't work.

Since the UI specifically says that linking to commits is supported (see highlight in the image below), I assume this is a bug.

![image](https://user-images.githubusercontent.com/5153846/72907302-eef6ce80-3d33-11ea-8aab-b18b9527c774.png)

Results in:

![image](https://user-images.githubusercontent.com/5153846/72907255-dab2d180-3d33-11ea-854d-0c91c1e32d7d.png)

example commit: https://github.com/excalidraw/excalidraw/commit/dc0a4f4cb8bf85a541a9a1a85c7cf60dfac362c9

## How has this issue affected you? What are you trying to accomplish?

Trying to debug CodeSandbox issues by creating a sandbox from given commit, to locate the problem. Had to revert to creating a branch from that commit and creating a sandbox from that branch.

But, as I later found out (I figured since git commits are basically trees), replacing the `/commit` with `/tree` [actually works](https://codesandbox.io/s/github/excalidraw/excalidraw/tree/dc0a4f4cb8bf85a541a9a1a85c7cf60dfac362c9) as a workaround --- but this is a non-obvious workaround from user perspective.

### Link to sandbox:

https://codesandbox.io/s/github/excalidraw/excalidraw/commit/dc0a4f4cb8bf85a541a9a1a85c7cf60dfac362c9

**Comment by lbogdan** [comment]
Hey @dwelle ,

Thanks for the report, we just deployed a new version that should fix this!

**Comment by dwelle** [comment]
Works like a charm. Thank you @lbogdan & @CompuIves!
