### ISSUE TITLE
strict option in `tsconfig.json` is set incorrectly (react-ts and vanilla-ts sandboxes)

### ISSUE THREAD

**Issue by phryneas** [codesandbox/codesandbox-client#3380]
# 🐛 bug report

## Description of the problem

I already posted this over in https://github.com/codesandbox/codesandbox-client/issues/3013, but since that is already closed I fear you might not see it, so I'm opening a new issue.

Unfortunately, the modification to the `tsconfig.json` in the react-ts sandbox was done incorrectly.

This change would be required.
This would fix it:

```diff
{
-    "strict": true,
    "include": [
        "./src/*"
    ],
    "compilerOptions": {
+        "strict": true,
        "lib": [
            "dom",
            "es2015"
        ],
        "jsx": "react"
    }
}
```

Also, this is still missing in the `vanilla-ts` sandbox although you said in #3013 that you had added it. Could you please add that option there, too?

**Comment by SaraVieira** [comment]
That was definitely on me and my lack of TS knowledge, on it now

**Comment by SaraVieira** [comment]
Should be up on both now? Can you please test?

**Comment by phryneas** [comment]
`const x: string = undefined;` now errors out in both `vanilla-ts` and `react-ts`.

Thank you very much, now I can sleep again without rotating :)

Have a nice day!

**Comment by SaraVieira** [comment]
You too! Sorry again :/
