### ISSUE TITLE
Github fetching in CodeSandbox is not working (after merging)

### ISSUE THREAD

**Issue by zerosheepmoo** [codesandbox/codesandbox-client#3383]
# 🐛 bug report

## Description of the problem

I committed the changes and pushed them to the linked github.
The github was up to date, but still editor in codesandbox detects changes already gone.
This happens after merging branches with codesandbox github commits and external github commits.

Do I need to forbid myself to commit outside of sandbox?

## How has this issue affected you? What are you trying to accomplish?

normally committing situation if there is nothing special to merge.
and after it, codesandbox must be updated.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome
| Operating System | Mac OS Catalina 10.15.2

**Comment by CompuIves** [comment]
Hmm, yes the sandbox should update normally after merging. Does the link to the sandbox start with `/s/github`?

**Comment by zerosheepmoo** [comment]
Here are the examples: [codesandbox](https://codesandbox.io/s/trusting-perlman-f3gkb) and corresponding [github](https://github.com/zerosheepmoo/csb-merge-t)

I thought codesandbox would be up to date after merging on the github.

**Comment by lbogdan** [comment]
@zerosheepmoo The [sandbox you linked to](https://codesandbox.io/s/trusting-perlman-f3gkb) is actually a fork, the "original" imported sandbox is always at https://codesandbox.io/s/github/zerosheepmoo/csb-merge-t .

You can read more about our current GitHub workflow [here](https://codesandbox.io/docs/git).

**Comment by zerosheepmoo** [comment]
@lbogdan 
Oh thanks. I understood.

Then, is there any way to sync codesandbox with github except for forking again when commits are directly pushed at github? I want to handle with already forked sandbox.

**Comment by zerosheepmoo** [comment]
@lbogdan 
if there is not, please close the issue. (for the issue management)

Actually, the question was out of scope and even the reply is no longer needed. I already solved the issue related to this.
