### ISSUE TITLE
DependencyNotFoundError. Could not find dependency.

### ISSUE THREAD

**Issue by dialoguewise** [codesandbox/codesandbox-client#3384]
I'm getting the issue:

```
DependencyNotFoundError
Could not find dependency: 'jsSHA' relative to '/node_modules/dialogue-wise/bundles/dialogue-wise.umd.js'
```

https://codesandbox.io/s/dialoguewise-demo-fjd67

**Comment by lbogdan** [comment]
Hey @dialoguewise ,

There's no such npm package named `jsSHA`, by looking at the version in your [package.json](https://unpkg.com/browse/dialogue-wise@0.0.4/package.json) I'm guessing you're trying to use [jssha](https://www.npmjs.com/package/jssha), but package names are case sensitive.

**Comment by lbogdan** [comment]
I saw you published a new `dialogue-wise` version with the correct dependency name, so I'm closing this.

**Comment by dialoguewise** [comment]
Thanks. As you said, the issue was the package name being case sensitive.
