### ISSUE TITLE
React Enzyme Tests with setupTests.js fail

### ISSUE THREAD

**Issue by johncokos** [codesandbox/codesandbox-client#3385]
# 🐛 bug report

## Description of the problem

With the latest version of React/create-react-app, setupTests.js doesn't seem to be loading and allowing test wiring. You will see that the linked sandbox implements the latest version of react, enzyme and uses the correct location/content of setupTests.js

Every test fails with this error

```
      Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none.
      To configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`
      before using any of Enzyme's top level APIs, where `Adapter` is the adapter
      corresponding to the library currently being tested. For example:

      import Adapter from 'enzyme-adapter-react-15';
```

**Comment by farebord** [comment]
Can confirm this is happening.
