### ISSUE TITLE
IDE has slowed to crawl (Explorer to blame, and maybe something else too)

### ISSUE THREAD

**Issue by NawarA** [codesandbox/codesandbox-client#3389]
# 🐛 bug report
IDE has slowed to crawl. 

I'm using a `create-react-app` template with some dependencies.

## Description of the problem
When `Explorer` is open:
- Clicking (in Explorer) to open an existing file takes 3 seconds before a new tab is opened
- Clicking to switch tabs takes 9 seconds (!) before the tab is switched. That's too slow
- Closing a tab takes ~7 seconds (during that time the IDE is unresponsive to user input)
- Is `Explorer` the cause?
When turning off File Explorer or switching to different sidebar options (ie. such as switching from Explorer to Sandbox Info / Configuration Files /Deployment / Github /Live) makes switching tabs take 2 seconds, instead of 9 seconds. This leads me to believe that perhaps Explorer is coded with some kind of subscriptions on every folder/file. If true, because my sandbox has many folders and files (it's a React SaaS app after all), then that would cause everything to slow down, and could explain the why Codesandbox is becoming slower as my app grows.

`Transpiles` performance
Another performance issue is that Transpiles are frequent and slow. For example, if the app preview is fully rendered, then I press `enter` in the IDE, then the browser preview begins reloading. Going from => "downloads dependencies" => to => "transpiling modules". After that, a white screen is rendered (the preview didnt work). I'm forced to manually refresh the browser after in order to re-render the preview. All of that occurs when pressing enter on the keyboard. This seems to be a recent issue, as I've been using codesandbox for ~1.5 years on this project without these issues.

Transpiling takes ~12 seconds (sometimes >20 seconds). Even though Codesandbox has the setting "Preview without saving" enabled, sometimes transpiling occurs every time I type in a character (even though I have that feature disabled in the Candsandbox => Preview settings). The net effect of continous re-rendering on every key stroke (even though the option is disabled) is that it makes the IDE feel unresponsive, which is visible in the half-minute lag between what I type and what I see in the preview window. Furthermore, transpiling feels like it slows down the IDE (service-worker is effecting the main window?).

## How has this issue affected you? What are you trying to accomplish?
I'm forced to develop without the File Explorer window open, since its slowing things to a crawl.

The IDE is moving so slow, I may have to switch. There's gotta be a solution, so I can keep using Codesandbox...what would you do if switching tabs took 9 seconds and you're constantly waiting a half minute before you see changes? Meanwhile, I can isolate the issue to Explorer and perhaps something with transpiling, resolving these issues would be good for me, other patrons, and the community at large.

<3 

### Link to sandbox: [link](https://codesandbox.io/s/frontend-c9jwk) (optional)
https://codesandbox.io/s/frontend-c9jwk

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1579516524-d2848195c |
| Browser          | Chrome 79 (latest) |
| Operating System | Windows 10 |

**Comment by garethx** [comment]
I haven't been able to reproduce this in a fork of the linked sandbox. Can you confirm whether these problems still occur in an incognito window? Thanks

**Comment by CompuIves** [comment]
We've made this now a bit faster, but we're not there yet. We could do a lot more, like setting the selected state as a prop to prevent rerenders, and the biggest help will be using windowing. I'll keep this open as a reference.

**Comment by NawarA** [comment]
Good to see you're continuously improving your architecture. 

The best software is made with love and vision ❤️
