### ISSUE TITLE
Invalid Host header

### ISSUE THREAD

**Issue by Kreyren** [codesandbox/codesandbox-client#3392]
# 🐛 bug report

## Description of the problem

I seem to have same/similar issue to https://github.com/codesandbox/codesandbox-client/issues/2233 on commit https://github.com/codesandbox/codesandbox-client/commit/775355592dbfe497c3856332b592852fc6c77d2b

![image](https://user-images.githubusercontent.com/11302521/73054997-0a74ed00-3e8c-11ea-9dc0-b07fa60a6e29.png)

Diagnosed the issue to be triggered on
```js
  setupCheckHostRoute() {
    this.app.all('*', (req, res, next) => {
      if (this.checkHost(req.headers)) {
        return next();
      }

      res.send('Invalid Host header');
    });
  }
```

Which is located in `node_modules/webpack-dev-server/lib/utils/Server.js` after `yarn && yarn build` suspecting change in dependency that broke the runtime

## How has this issue affected you? What are you trying to accomplish?
Affects testing of a new contribution

### Link to sandbox: [link]() (optional)
Codesandbox doesn't support changes in codesandbox (https://codesandbox.io/s/github/codesandbox/codesandbox-client).

Configured gitpod on https://github.com/Kreyren/codesandbox-client/tree/84e0aece9aa6abc8bf5bf5f81493cc6bbd0f34a3 (takes around 5 min to set up since the build is not yet cached due to pebcak(?) https://github.com/gitpod-io/gitpod/issues/1138)

### Your Environment
- **Software:** GitPod
- **Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
- **Operating System:** Kreyrock ~~Linux~~ Anubis 9999 x86_64 (Bedrock-inspired franken-kernel system from scratch with experimental Zernif package manager) - Same issue on Debian Linux using different device

**Comment by lbogdan** [comment]
Hey @Kreyren ,

You probably need to set https://webpack.js.org/configuration/dev-server/#devserverdisablehostcheck . We're all working on `localhost`, that's why we never had this issue.

**Comment by lbogdan** [comment]
Will close this for now, as there's no actionable here. If you need further assistance in setting up your development environment, you can find us on [Spectrum](https://spectrum.chat/codesandbox/).

**Comment by skygreenman** [comment]
> Hey @Kreyren ,
> 
> You probably need to set https://webpack.js.org/configuration/dev-server/#devserverdisablehostcheck . We're all working on `localhost`, that's why we never had this issue.

For those using Webpack 5, I used `allowedHosts' ` instead of `disableHostCheck` 
[source](https://stackoverflow.com/a/70246125/5616770)

`module.exports = {
  //...
  devServer: {
    allowedHosts: ['.preview.csb.app'] // < **this is the domain Codebox pointed me to when rendering my app; copy and paste the domain from the URL Codebox provides you 
  },
};`
[source](https://webpack.js.org/configuration/dev-server/#devserverallowedhosts)

**Comment by silence1018** [comment]
> **Situation** I was getting this same error while using codesandbox.io. I created a new cloud sandbox for a Vue3 project.
> 
> After seeing this solution, I tried it but creating a new file `webpack.config.js`. Didn't work.
> 
> I changed the file name to `vue.config.js`. Restarted the sandbox. worked.
> 
> **EXPLANATION** If there is a webpack.config.js file present, Vue CLI will use that instead, but it can sometimes cause conflicts or issues if the configuration is not compatible with Vue CLI.
> 
> By default, Vue CLI looks for a file named vue.config.js in the root of the project directory to configure its build process.
> 
> By renaming the file to vue.config.js, we are ensuring that Vue CLI will use the correct configuration file and that there are no conflicts with the build process.
> 
> **My code:**
> 
> ```js
> module.exports = {
>   // disable the host check on sandbox
>   devServer: {
>     disableHostCheck: true
>   }
> };
> ```

Great, solved my problem, but I still don't understand what this cloud is for

**Comment by Alexei87K** [comment]
> ```js
> module.exports = {
>   // disable the host check on sandbox
>   devServer: {
>     disableHostCheck: true
>   }
> };
> ```

it didn't work for me... I also use codesandbox

**Comment by rostik32** [comment]
> > ```js
> > module.exports = {
> >   // disable the host check on sandbox
> >   devServer: {
> >     disableHostCheck: true
> >   }
> > };
> > ```
> 
> it didn't work for me... I also use codesandbox

same with me

**Comment by Arthur-1702** [comment]
> > ```js
> > module.exports = {
> >   // disable the host check on sandbox
> >   devServer: {
> >     disableHostCheck: true
> >   }
> > };
> > ```
> 
> it didn't work for me... I also use codesandbox

After tried those solutions and none worked for me, I found this:

In webpack 5 is changed, please check:

```
 devServer: {
    allowedHosts: 'all',
 }

```

**Comment by CompuIves** [comment]
I will make sure to also create a documentation page about this, as it's a problem that happens more frequently. 

`disableHostCheck` or `allowedHosts: 'all'` should both work. If you want something more specific than `'all'`, then `'.csb.app'` should also work, and that domain won't change any time.

**Comment by Sovai** [comment]
does not work after I use the new AI feature

**Comment by manusoftar** [comment]
> Hey @Kreyren ,
> 
> You probably need to set https://webpack.js.org/configuration/dev-server/#devserverdisablehostcheck . We're all working on `localhost`, that's why we never had this issue.

What does that have to do anyway, CodeSandBox is an online service, we shouldn't need to be setting things up anyway... When I log on CodeSandBox.io and generate a devbox I expect it to work out of the box, not to start erroring with these kind of things. Is it that hard to just fix the God damn thing??!
