### ISSUE TITLE
How to ignore particular file using nodemon in CodeSandbox (node/express)

### ISSUE THREAD

**Issue by szymonzrybnika** [codesandbox/codesandbox-client#3394]
Hi
I am a newbie in node. I use CodeSandbox to learn node with express. I need to force nodemon to ignore some files (especially one named "products.json") in my node/express app:

This is my package.json:
`{
  "name": "new-express-app",
  "version": "1.0.0",
  "description": "",
  "main": "src/index.js",
  "scripts": {
    "start": "nodemon src/index.js localhost 8080",
    "dev": "nodemon --ignore data/products.json"
  },
  "dependencies": {
    "ejs": "3.0.1",
    "express": "4.17.1",
    "lodash": "4.17.15"
  },
  "devDependencies": {
    "nodemon": "1.18.4"
  },
  "keywords": []
}
`
but it does not work.

My workflow:
```
- data
- src
-- index.js
```

Do you have any idea how to configure nodemon in CodeSandbox?

**Comment by garethx** [comment]
Try combining the start and dev commands into one start command, like `nodemon --ignore data/products.json src/index.js`

As an example, we do similar in this starter app https://codesandbox.io/s/lowdb-json-file-database-example-starter-pldy5, where nodemon only looks for file changes in the `src` directory, ignoring everything else.

**Comment by szymonzrybnika** [comment]
Thanks for your answer, butit does not work in my case at all. I have tried it in many ways, for example:
`"scripts": {
    "start": "nodemon --ignore data/* --watch src src/index.js localhost 8080"
  },`

or

`"scripts": {
    "start": "nodemon --ignore data/products.json --watch src src/index.js localhost 8080"
  },`


Any other ideas?

**Comment by garethx** [comment]
The example in the linked sandbox should work `nodemon --watch src src/index.js` just as well. Failing that, please supply a sandbox URL and I can take a closer look.

**Comment by szymonzrybnika** [comment]
I have tried, but id doesn`t. Please, here is my sanbox URL:
[https://codesandbox.io/s/new-express-app-y8rm5?fontsize=14&hidenavigation=1&theme=dark](url)

**Comment by garethx** [comment]
It seems to work fine in a fork of that sandbox. You need to save package.json and make sure the server is restarted between edits so that it can pick up and apply those changes (click restart server from the server control panel to the left)

**Comment by szymonzrybnika** [comment]
Thanks a lot, now it works! :)
