### ISSUE TITLE
Wiping incoming request headers

### ISSUE THREAD

**Issue by pPanda-beta** [codesandbox/codesandbox-client#3403]
# 🐛 bug report
For SSE based sandboxes, codesandbox is wiping out incoming request headers.

## Description of the problem
1. **Some headers are wiped from incoming request (e.g. accept-encoding)**
2. Some unwanted X-... headers are added

## How to reproduce ?
1. Create a node based sandbox (SSE)
2. Use the following body as package.json
```js
{
  "name": "node-echo-server",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "start": "http-echo-server"
  },
  "dependencies": {
    "http-echo-server": "2.1.1"
  }
}
```
3. Hit the server with 
```sh
curl -v 'https://lhy8h.sse.codesandbox.io/proxy/https://www1.nseindia.com/corporates/common/getCompanyList.jsp' \
        -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36' \
        -H 'accept: */*' \
        -H 'accept-encoding: gzip, deflate, br' \
        -H 'accept-language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7' \
        -H 'connection: keep-alive' \
        -H 'x-requested-with: XMLHttpRequest' \
        -H 'origin: https://www1.nseindia.com' \
        -H 'referer: https://www1.nseindia.com/corporates/listDir/listDirectory.html' \
        -H 'content-type: application/x-www-form-urlencoded' \
        --data 'query=INFY'
```

## Expected Behavior
HTTP req to the actual node server : 
```
POST /proxy/https://www1.nseindia.com/corporates/common/getCompanyList.jsp HTTP/1.1
Host: localhost:3000
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7
connection: keep-alive
x-requested-with: XMLHttpRequest
origin: https://www1.nseindia.com
referer: https://www1.nseindia.com/corporates/listDir/listDirectory.html
content-type: application/x-www-form-urlencoded
Content-Length: 10

query=INFY%
```

## Actual Behavior 
```
POST /proxy/https://www1.nseindia.com/corporates/common/getCompanyList.jsp HTTP/1.1
Connection: upgrade
Host: 192.168.12.230:82
Content-Length: 10
X-Request-ID: 8dd39b3f0328a24107261a6d7b303bc9
X-Real-IP: 106.77.220.172
X-Forwarded-For: 106.77.220.172
X-Forwarded-Host: lhy8h.sse.codesandbox.io
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Original-URI: /proxy/https://www1.nseindia.com/corporates/common/getCompanyList.jsp
X-Scheme: https
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
accept: */*
accept-language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7
x-requested-with: XMLHttpRequest
origin: https://www1.nseindia.com
referer: https://www1.nseindia.com/corporates/listDir/listDirectory.html
content-type: application/x-www-form-urlencoded

query=INFY%
```

## How has this issue affected you? What are you trying to accomplish?
It is loss of information, some http servers may produce incorrect result if headers from request are missing.
If `accept-encoding` is not sent to the server, it wont be able to turn on compression. 

# Neither codesandbox, nor any cloud provider or any reverse proxy reserves rights to MODIFY HTTP HEADERS

### Your Environment
happens on https://codesandbox.io/

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | https://codesandbox.io/
| Browser          |  Any
| Operating System | Doesn’t matter

**Comment by lbogdan** [comment]
Hey @pPanda-beta ,

While you're technically right, please take into account that CodeSandbox provides a remote **development** environment, and not a feature-full production hosting service.

The request goes through a couple of reverse-proxies (which add those `X-...` headers), I'm gonna take a look and see if this is something easily fixable.

Also, is this a real problem (something expected to be working is not working), or just a theoretical "it should not behave like that" issue?

**Comment by pPanda-beta** [comment]
Hi @lbogdan 
This is a real problem. I was trying to develop a generic purpose proxy like `https://yacdn.org/proxy/<uri>` 
Here is the actual codebase : https://codesandbox.io/s/generic-reverse-proxy-2pwjj

1. Addition of headers : This is not a big problem, only a few cases this can produce a different result. e.g. If I do https://2pwjj.sse.codesandbox.io/proxy/https://ipinfo.io/json then it produces the same result as https://ipinfo.io/json, and ipinfo.io is able to detect the source ip using "X-Real-IP". So hiding identity is not possible with this proxy. But this is not a requirement altogether, and I can live with it.

2. Deletion of headers :  This is a huge problem. I had to add this hack at `index.js` to add default headers since the set of reverse proxies are deleting essential headers. As I mentioned in the original issue, a lot websites don’t work if `accept-encoding` is not present in the request. e.g. https://www1.nseindia.com hangs and gives no response if this header is missing.

**Comment by pPanda-beta** [comment]
# KeepFresh
