### ISSUE TITLE
how to copy  and paste

### ISSUE THREAD

**Issue by SeHo62** [codesandbox/codesandbox-client#3415]
# ❔ Question

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by CompuIves** [comment]
Hey! You can copy/paste with `CTRL+C` and `CTRL+V` on Windows and `CMD+C` `CMD+V` on OSX. If that doesn't work, could you then open an issue with some more info to reproduce the issue?

**Comment by SeHo62** [comment]
Problem solved! Thank you
