### ISSUE TITLE
Receiving Error 422 when package.json is not present 

### ISSUE THREAD

**Issue by irasanchez** [codesandbox/codesandbox-client#3418]
# 🐛 bug report

## Description of the problem
Cannot import GitHub repo

## How has this issue affected you? What are you trying to accomplish?
I was trying to import a repo but kept getting the following error:
Request failed with status code 422
Response in Network tab says there is no package.json in the details

I'm uncertain if this is spelled out in the docs (didn't see it when debugging), but getting an error that tells you you need a package.json for the importer to work would be helpful. 

### Link to sandbox: [link]() (optional)
N/A

### Your Environment
Windows 10 
Firefox Developer Edition

Thanks for this tool!

**Comment by lbogdan** [comment]
Closing this, as we fixed the vague error message in #3430 , e.g. https://codesandbox.io/s/github/lbogdan/empty .
