### ISSUE TITLE
loader to resolve font-face url's inside css file

### ISSUE THREAD

**Issue by marlin12** [codesandbox/codesandbox-client#3419]
# ❔ Question

I've created a vue sandbox to test vue-slick. When I import the "slick-theme.css" file to the related SFC, it seems that sandbox failed to resolve the font-face url's in the css file. Is there a dependency I can add to correct this problem ?

Note:- I've downloaded that repository and run it with @vue/cli. It works well without problem.
![captured](https://user-images.githubusercontent.com/17764296/73422130-ecfbc380-4362-11ea-9d22-49aade81eebf.jpg)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | vue | 
| Browser          | chrome | 
| Operating System | Windows 10 |

**Comment by CompuIves** [comment]
Good one! We didn't resolve @imports yet properly. I've created a PR with a fix for this issue, now waiting for integration tests and will deploy it after!

**Comment by marlin12** [comment]
Thanks for your help !


從 Outlook<http://aka.ms/weboutlook> 傳送

________________________________
寄件者: Ives van Hoorne <notifications@github.com>
寄件日期: 2020年2月4日 18:08
收件者: codesandbox/codesandbox-client <codesandbox-client@noreply.github.com>
副本: marlin12 <coves741@hotmail.com>; Author <author@noreply.github.com>
主旨: Re: [codesandbox/codesandbox-client] loader to resolve font-face url's inside css file (#3419)


Closed #3419<https://github.com/codesandbox/codesandbox-client/issues/3419> via #3459<https://github.com/codesandbox/codesandbox-client/pull/3459>.
