### ISSUE TITLE
Editor view not working on medium rather shows the preview view

### ISSUE THREAD

**Issue by VinayakNivalkar** [codesandbox/codesandbox-client#3422]
# 🐛 bug report

## Description of the problem
     Medium shows only preview view even though I have chosen editor view while producing the 
     link over codesandbox, I suspect the error occurred after I changed the name of my sandbox,

## How has this issue affected you? What are you trying to accomplish?
     Unable to use editor view just to show some important backend code

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | NuxtJs |
| Browser          |  Chrome |
| Operating System | Windows |

**Comment by garethx** [comment]
Can reproduce. This example Medium post https://medium.com/@_gw/-1d12bb1057b3 should show a mixture of editor only and editor+preview sandboxes - all show preview only.

**Comment by siddharthkp** [comment]
That's really interesting!

@CompuIves seems like the query params aren't passed ahead to /embed when embedding a /s link for medium

**Comment by CompuIves** [comment]
H, this might be out of our control. It seems like Medium replaces the query params. You can double check here: https://codesandbox.io/oembed?url=https://codesandbox.io/embed/new?view=preview, the code is still an iframe with the embed params added.

**Comment by siddharthkp** [comment]
That has all the params 🤔
