### ISSUE TITLE
Error trying to use jade with express

### ISSUE THREAD

**Issue by ItsMeRTXYZ** [codesandbox/codesandbox-client#3445]
# 🐛 bug report

### Your Environment

| Software         | Name/Version |
| Jade (Pug), express | Jade (Pug), ExpressJS |
| Сodesandbox      |
| Chrome          |
| Windws 10, Latest |

**Comment by lbogdan** [comment]
Closing this, as it's not a CodeSandbox issue, you just need to set some `express` options related to using a template engine, as described [here](https://expressjs.com/en/guide/using-template-engines.html). As an example, here is a working sandbox: https://codesandbox.io/s/hopeful-nobel-llcjo .
