### ISSUE TITLE
Empty page when accessing https://codesandbox.io homepage

### ISSUE THREAD

**Issue by shotforsky** [codesandbox/codesandbox-client#3447]
# 🐛 bug report

## Description of the problem
Type `https://codesandbox.io/` into browser location bar and hit `Enter`, got nothing shown on the page.
After a simple investigate, found there were several errors thrown in browser Console as following:

![image](https://user-images.githubusercontent.com/14038117/73603252-6beb3900-45bb-11ea-902c-c845b02b381f.png)

It happened only when homepage(https://codesandbox.io) was accessed, while a sandbox sample can be loaded as normal:

![image](https://user-images.githubusercontent.com/14038117/73603359-7528d580-45bc-11ea-8b42-b45e82fb71ec.png)

## How has this issue affected you? What are you trying to accomplish?

Expected is that I can access the home page as normal. 

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | N/A |
| Browser          | Google Chrome@79.0.3945.130 |
| Operating System | Window 10 |

**Comment by nerdyman** [comment]
I'm also getting this in a Linux VirtualBox VM, WebGL doesn't work on anything. It would be good to get it to catch the context error since WebGL isn't required for the page to operate.

**Comment by shotforsky** [comment]
Error is gone now, do not know what was changed, close this issue since homepage is back for 

PS: the Environment is still the same.

@nerdyman , you could check yours to see if everything is good.

Thanks~
