### ISSUE TITLE
convert-esmodule exports default class before initialisation

### ISSUE THREAD

**Issue by atepoorthuis** [codesandbox/codesandbox-client#3448]
# 🐛 bug report

## Description of the problem
The logic in the `convert-esmodule` transpiler treats default class and function exports equally: 
https://github.com/codesandbox/codesandbox-client/blob/304a43823fe4ac1e63bdebdc8eb7129876d8ed38/packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.ts#L162-L165

However, this results in classes being exported in the temporal dead zone, before they are initialised:
https://github.com/codesandbox/codesandbox-client/blob/304a43823fe4ac1e63bdebdc8eb7129876d8ed38/packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/__snapshots__/index.test.ts.snap#L3-L10

This will give a `Cannot access x' before initialization` error for any imports that use `export default Class`.

## How has this issue affected you? What are you trying to accomplish?
Import any es6 modules with `export default Class` statements.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  any |
| Browser          | Chrome |
| Operating System | Mac |

**Comment by lbogdan** [comment]
Hey @atepoorthuis ,

Can you please share a sandbox experiencing this issue? This seems like it would break a lot of use-cases, but you're the first one to report it.

**Comment by atepoorthuis** [comment]
> Can you please share a sandbox experiencing this issue? This seems like it would break a lot of use-cases, but you're the first one to report it.

Sure! You can see a sandbox with a minimal reproduction here: https://codesandbox.io/s/optimistic-mayer-8y548.

I created a simple gh repo with a single default class export (https://github.com/atepoorthuis/export-default-class/blob/master/index.js) that I'm importing in that sandbox. The original es6 export:
```js
export default class Rectangle {
    constructor(height, width) {
      this.height = height
      this.width = width
    }
}
```

Gets transpiled to:
```js
(function evaluate(require, module, exports, process, setImmediate, global, __dirname, __filename) {Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = Rectangle;
class Rectangle {
  constructor(height, width) {
    this.height = height;
    this.width = width;
  }
}
//# sourceURL=https://8y548.csb.app/node_modules/export-default-class/index.js
})
```
You can see this in the test snapshot too:
https://github.com/codesandbox/codesandbox-client/blob/304a43823fe4ac1e63bdebdc8eb7129876d8ed38/packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/__snapshots__/index.test.ts.snap#L3-L10

That yields an error because the class gets exported/referenced before it is initialised. I would think that the solution is as simple as switching the order of the export and class declaration but don't completely understand all the logic in `convert-esmodule` so am afraid I would break something if I'd start a PR.

**Comment by CompuIves** [comment]
Thanks for the clear repro, looking at it now!

**Comment by atepoorthuis** [comment]
Wonderful - thank you for the quick fix!
