### ISSUE TITLE
Left panel does not collapse

### ISSUE THREAD

**Issue by jsejcksn** [codesandbox/codesandbox-client#3449]
# 🐛 bug report

## Description of the problem

Left panel does not collapse (its width can only be resized)

![cs-left-panel](https://user-images.githubusercontent.com/868251/73615735-50d6f400-45d0-11ea-91b9-812351d901f9.gif)

## How has this issue affected you? What are you trying to accomplish?

Trying to increase usable area for editor panel, but this bug prevents using available viewport space

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | `PROD-1580490943-2f3fa90ea`
| Browser          | Chrome `79.0.3945.130`
| Operating System | macOS `10.15.3`

**Comment by jsejcksn** [comment]
Unrelated to this issue: Where can the _Codesandbox version_ be viewed? The issue template asks for this, and I included a string from the bottom left of my sandbox as a best guess, but I have no idea where to look.

**Comment by lbogdan** [comment]
Hey @jsejcksn ,

Your guess was spot on, the current version is `PROD-1580490943-2f3fa90ea` - with `1580490943` being the timestamp when the app was built, and `2f3fa90ea` is the commit sha of `codesandbox-client` repository that was built: https://github.com/codesandbox/codesandbox-client/commits/2f3fa90ea .

**Comment by siddharthkp** [comment]
Fixed in https://github.com/codesandbox/codesandbox-client/pull/3453 (not deployed yet)
