### ISSUE TITLE
Wrong codesandbox embeds on Medium

### ISSUE THREAD

**Issue by JoostKiens** [codesandbox/codesandbox-client#3457]
# 🐛 bug report

## Description of the problem
The wrong codesandbox gets embedded on Medium

## How has this issue affected you? What are you trying to accomplish?
I am trying to embed this awesome sandbox (https://codesandbox.io/s/winter-monad-y6gn8) in an article Im writing on Medium. However a different sandbox by the same author gets embedded (https://codesandbox.io/s/xenodochial-mountain-yhrmm). I tried forking, but the same thing happens.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/winter-monad-y6gn8

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1580471432-1c3b33b77
| Browser          | Chrome  79.0.3945.130
| Operating System | MacOs 10.15.3

**Comment by CompuIves** [comment]
Hmm, that is weird. When checking the data we give to Medium we seem to be giving the right url: https://codesandbox.io/oembed?url=https://codesandbox.io/s/winter-monad-y6gn8. Could you try it again? Maybe Medium caches a block or something.

**Comment by lbogdan** [comment]
Hey @JoostKiens ,

Is this still happening for you? If so, can you please share the article URL?

**Comment by JoostKiens** [comment]
Hi @lbogdan, it's still happening. 

The article is still in draft, but [here's the draft URL](https://medium.com/@joostkiens/how-i-transitioned-from-ease-to-spring-animations-5a09eeca0325).

It's the embed just above "Spring animations are very useful for UI animations."

**Comment by lbogdan** [comment]
@JoostKiens Unfortunately I get a 404:

![image](https://user-images.githubusercontent.com/2083930/73831032-5457be80-480e-11ea-8558-b05e0ba8a3e5.png)

**Comment by JoostKiens** [comment]
Hmm, very weird. 

Just checked with a coworker, they get a 404 when not logged in on Medium, when logged in the link works. 

Are you logged in?

**Comment by lbogdan** [comment]
Oh, OK, it worked when I logged in.

I don't exactly know how embedding in Medium works, but I can see that `<iframe>`'s `src` is set to `https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fcodesandbox.io%2Fembed%2F732j6q4620&display_name=CodeSandbox&url=https%3A%2F%2Fcodesandbox.io%2Fs%2F732j6q4620&image=https%3A%2F%2Fcodesandbox.io%2Fapi%2Fv1%2Fsandboxes%2F732j6q4620%2Fscreenshot.png&key=a19fcc184b9711e1b4764040d3dc5c07&type=text%2Fhtml&schema=codesandbox` , which is the embed of the https://codesandbox.io/s/732j6q4620 , so I don't really get what the issue is?

**Comment by JoostKiens** [comment]
Thanks for taking the time!
The issue is that I use the embed code of a different sandbox: https://codesandbox.io/s/winter-monad-y6gn8

**Comment by lbogdan** [comment]
Can you maybe try to embed it again, while taking a look at the network requests to `codesandbox.io`, and look for anything weird?

**Comment by JoostKiens** [comment]
Hmmm, I see a bunch of requests with the 'wrong' slug: `F732j6q4620`, none with the one I entered `winter-monad-y6gn8`

Also I just noticed that the sandbox I try to embed is a fork of the one that gets embedded.

Do you want me to upload a .har file with the relevant requests?

**Comment by lbogdan** [comment]
Sure, that would be nice, you can send them to hello_at_codesandbox.io. The weirdest thing is that the requests don't seem to be correlated to what you're entering in the UI? Can you maybe also share a screenshot of how you're trying to add the embed in Medium?

**Comment by JoostKiens** [comment]
Sure! I sent an email with the .har file and a screen recording.

**Comment by JoostKiens** [comment]
Hi @lbogdan, just curious, did you have a chance to look at this?

**Comment by nfailla** [comment]
Hello! This is still happening. Just as @JoostKiens mentioned, it happens on sandboxes created by forking :/

**Comment by JamesACS** [comment]
Hey @nfailla - Please could you create a new issue if you're still encountering this behaviour and fill out the bug report template?

**Comment by JaneGaid** [comment]
Hello Everyone, this is still happening.

**Comment by sannek** [comment]
#6838 is a more recent version of a similar issue -- we are in touch with Embedly support about this, since we are not the ones developing the Embedly provider.
