### ISSUE TITLE
Bit.dev Integration

### ISSUE THREAD

**Issue by WassimBenzarti** [codesandbox/codesandbox-client#3467]
# 🌈 Feature

How about we add an integration with [Bit.dev](https://bit.dev/) ?

Imagine we could change Bit.dev components on the fly using CodeSandbox. Imagine we could launch CodeSandbox right from Bit platform. Imagine we could create and export components as fast as possible using this amazing tool.

I think this is a huge step towards UI reusability. I'm willing to contribute to make this happen if there are no technical obstacles!

## How it works
In the creation of the sandbox, we can choose to have the bit module installed.
Using the command palette we can choose one of these options:
- Init bit project
- Add a component
- Add a compiler
- Tag a component
- Export a component

## Implementation
Currently Bit doesn't have a Rest API for these features. So we should implement this using the Bit CLI. We can map the commands (features mentioned above) in the command palette to some Bit CLI commands.

I think Bit CLI commands are less likely to change over time.

I would love to hear your feedback!

**Comment by RSSfeed** [comment]
Any update on this?

**Comment by SaraVieira** [comment]
Hey!

Thank you for bringing this to our attention, I have just added it to our internal backlog that we do want to make public but for now, it's all in notion.

I will be closing but to make sure what we have in GitHub is just issues and all our feature requests are tracked in our roadmap.

We will definitely make a release when this is done :)
Again, thank you!
