### ISSUE TITLE
Parcel don't support React Fragment short syntax `<></>`

### ISSUE THREAD

**Issue by csr632** [codesandbox/codesandbox-client#3470]
# 🐛 bug report

Parcel don't support React Fragment short syntax `<></>`

demo: 
https://codesandbox.io/s/console-components-demo-dl2tf

**Comment by garethx** [comment]
If you add a babelrc file from the Configuration Files menu in the left sidebar, and add the following line after pragma in the default setup it will work: `"pragmaFrag": "React.Fragment"`
