### ISSUE TITLE
Inline import module

### ISSUE THREAD

**Issue by quangminhit94** [codesandbox/codesandbox-client#3471]
# 🐛 bug report

## Description of the problem
I try to use `<script type="module">` on Code Sandbox but it doesn't work
```js

// 📁 ./src/sayHi.js
export function sayHi(user) {
  alert(`Hello, ${user}!`);
}
```

```html
// 📁 index.html
<!doctype html>
<script type="module">
  import { sayHi } from "./src/sayHi.js";

  document.body.innerHTML = sayHi('John');
</script>
```

I am following this tutorial: https://javascript.info/modules-intro

## How has this issue affected you? What are you trying to accomplish?

demo: https://plnkr.co/edit/rZprEnNmZyqNtNqxtijS?p=preview

I downloaded demo source, it works on my local but not working on Code Sandbox

**Comment by garethx** [comment]
Setting the project to use the static template works as expected, see https://codesandbox.io/s/how-use-import-in-vanilla-z6z6h

**Comment by quangminhit94** [comment]
> Setting the project to use the static template works as expected, see https://codesandbox.io/s/how-use-import-in-vanilla-z6z6h

Thank you
