### ISSUE TITLE
Can't change theme 

### ISSUE THREAD

**Issue by DannyRuchtie** [codesandbox/codesandbox-client#3479]
# 🐛 bug report
TypeError: Cannot read property 'addEventListener' of null

## Description of the problem
I can't change themes (chrome, Safari)
I get the following error:  TypeError: Cannot read property 'addEventListener' of null

### Your Environment
macOS
Chrome (Latest)
Safari (Latest)

**Comment by lbogdan** [comment]
Hey @DannyRuchtie ,

You already reported this 23 days ago in #3329 . 🙂
