### ISSUE TITLE
"Repo is too big to import"

### ISSUE THREAD

**Issue by dgennetten** [codesandbox/codesandbox-client#348]
Consistently getting "Repo is too big to import" for all links launched from v2.grommet.io.

Example: https://codesandbox.io/s/github/grommet/grommet-site?initialpath=button&module=%2Fscreens%2FButton.js

**Comment by CompuIves** [comment]
Thanks for letting me know! The line throwing the error is here: https://github.com/codesandbox-app/git-extractor/blob/master/src/routes/github/api.ts#L479. The zip of the repo is 112MB, which was above the 30MB limit we set, we set this limit to make sure we don't hit any memory limit. I raised the limit to 128MB now, but there seems to be another limit that's hit. I can check tomorrow what limit that is and maybe raise it, I think it may be the file count limit (is set to 100 right now).

The `public/img/image*.js` files are the files that causes it to hit the limit now, so if they are not important you can also delete those files and it'll work.

Regardless, we should re-evaluate our limits from time to time. I can check tomorrow if we can raise any other limits 😄 .

**Comment by ryanpcmcquen** [comment]
Did the limits ever get raised here @CompuIves? Curious for this and: https://github.com/CompuIves/codesandbox-client/issues/1007

**Comment by CompuIves** [comment]
Yes! It's now double if I'm not mistaken (200 files)

**Comment by ryanpcmcquen** [comment]
@CompuIves, any plan to raise it more? I must have hit the 200 module limit for my repo ...

**Comment by rowild** [comment]
This error message appears after uploading one simple, small vue file already...

**Comment by rowild** [comment]
Wow! Thanks for reacting so quickly! But just to let you know: this also happens with a regular CSS or js file, not only vue...

**Comment by rowild** [comment]
Thanks! What about my questions though? The closed folder, the update button... Any info for me? ;-)

**Comment by CompuIves** [comment]
> What about my questions though? The closed folder, the update button... Any info for me? ;-)

Do you mean with this that we should auto open a folder if you hover long enough on it?
