### ISSUE TITLE
Cannot edit React code, every character input is overriden to previous state

### ISSUE THREAD

**Issue by lenmorld** [codesandbox/codesandbox-client#3487]
# 🐛 bug report

I have this sandbox that I couldn't edit
with create-react-app, not ejected
It's not happening to all of my sandboxes though, just this one
Same thing after reloading the browser

Forking the sandbox works though

Let me know if you can repro on your side
I can give more info
## Description of the problem

![codesandbox_bug](https://user-images.githubusercontent.com/14609656/74086433-c0296980-4a50-11ea-8109-01370191dca8.gif)

## How has this issue affected you? What are you trying to accomplish?
Just trying to type

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/react-state-example-tweets-1-g7ym5

### Your Environment

Google Chrome | 79.0.3945.130 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1809 (Build 17763.973)
JavaScript | V8 7.9.317.33

**Comment by CompuIves** [comment]
Hey! Thanks for letting me know! I think I have pinpointed why this happens, working on a fix and deploying it today. I think it has to do with the emoji (length of char on server is not the same as on client).

**Comment by CompuIves** [comment]
The fix for this is live now!

**Comment by arnaudNYC** [comment]
I had the same issue and just came here to report it, just to find out it's already been fixed, thanks so much!
