### ISSUE TITLE
react-sandpack doesn't work

### ISSUE THREAD

**Issue by anyexinglu** [codesandbox/codesandbox-client#3489]
# 🐛 bug report

## Description of the problem

I tried to use react-sandpack, following the [getting-started](https://github.com/codesandbox/codesandbox-client/tree/master/standalone-packages/react-sandpack#getting-started)

But there were many errors:

(1) When I run `yarn add @codesandbox/react-sandpack `, an error occurred:
An unexpected error occurred: "https://registry.npmjs.org/@codesandbox%2freact-sandpack: Not found".

![image](https://user-images.githubusercontent.com/8243326/74096763-f42e8880-4b3d-11ea-9d35-063ed34fe162.png)

(2) Then I try `yarn add react-sandpack react-smooshpack`, it works. But when I write a demo as the readme:
```js
import React from 'react';
import { render } from 'react-dom';
import {
  FileExplorer,
  CodeMirror,
  BrowserPreview,
  SandpackProvider,
} from 'react-sandpack/es/components';
import 'react-smooshpack/dist/styles.css';

const files = {
  '/index.js': {
    code: "document.body.innerHTML = `<div>${require('uuid')}</div>`",
  },
};

const dependencies = {
  uuid: 'latest',
};

const App = () => (
  <SandpackProvider files={files} dependencies={dependencies} entry="/index.js">
    <div style={{ display: 'flex', width: '100%', height: '100%' }}>
      <FileExplorer style={{ width: 300 }} />
      <CodeMirror style={{ flex: 1 }} />
      <BrowserPreview style={{ flex: 1 }} />
    </div>
  </SandpackProvider>
);

render(<App />, document.getElementById('root'));
```

A new error encountered:
`Failed to compile.
./src/demo/Code.tsx
Module not found: Can't resolve 'react-sandpack/es/components' in '/Users/xx/xx/xx/cssinjs/src/demo'`

![image](https://user-images.githubusercontent.com/8243326/74096830-bd0ca700-4b3e-11ea-87bd-30ed06b29b6e.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | "react-sandpack": "^1.0.0" & "react-smooshpack": "^0.0.62",
| Browser          | Chrome 79
| Operating System | macos Mojave 10.14.6

**Comment by CompuIves** [comment]
Oh yes, I see now that the imports are wrong in the example. We haven't published to `react-sandpack` yet, everything should be named `react-smooshpack`. If you rename everything to that it should work as expected.

**Comment by anyexinglu** [comment]
> Oh yes, I see now that the imports are wrong in the example. We haven't published to `react-sandpack` yet, everything should be named `react-smooshpack`. If you rename everything to that it should work as expected.

Oook, It works
