### ISSUE TITLE
Can't export to Github nor can't delete the current Github connection

### ISSUE THREAD

**Issue by Nases** [codesandbox/codesandbox-client#3491]
# 🐛 bug report

## Description of the problem
I have deleted the Github repo then my codesandbox Github integration got stucked.
I can not delete the current Guthub connection nor I can not export to a new Github repo.

## How has this issue affected you? What are you trying to accomplish?
I would like to delete the current Github connection and make a new connection to Github repo.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/hasansefaozalpcom-u2r51

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by garethx** [comment]
If you fork the sandbox then you should be able to export to GitHub and create a new repo.
