### ISSUE TITLE
Mobx observer component works fine in local CRA but not in codesandbox

### ISSUE THREAD

**Issue by uriklar** [codesandbox/codesandbox-client#3495]
# 🐛 bug report

## Description of the problem

When hovering over a block and clicking the + button, it should add a new block. It works fine with the exact same code in a local CRA app, but in codesandbox it doesn't

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome
| Operating System | OSX Catalina

**Comment by CompuIves** [comment]
Well that's interesting, for me it works when trying it out. Do you get any errors in the console?

**Comment by uriklar** [comment]
Sorry... Looks like I got things mixed up.
