### ISSUE TITLE
ModuleNotFoundError on  'generate-random-data/lib/random/boolean'

### ISSUE THREAD

**Issue by guiyep** [codesandbox/codesandbox-client#3499]
# 🐛 bug report

## Description of the problem

ModuleNotFoundError
Could not find module in path: 'generate-random-data/lib/random/boolean' relative to '/node_modules/generate-random-data/lib/index.js'

The package module is not being loaded and I see it on the dependencies list with the correct version. This happens the same to 10 different sandboxes I have.

**Comment by garethx** [comment]
Do you have a link to a sandbox where you're experiencing this issue? You seem to be using faker without issue in the sandbox linked above.

**Comment by guiyep** [comment]
I had to change the library t make it work. All good now with the new library.
