### ISSUE TITLE
Tests fail when run more than once

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#3505]
# 🐛 bug report

## Description of the problem
When I run some tests the first time then the tests pass. When I run (using the run button) the tests twice or more it seems that the rendered html does not start with a fresh html page and the tests fail. Same happens with refresh button.

### Link to sandbox: [link](https://codesandbox.io/s/5z6x4r7n0p)

**Comment by MichaelDeBoey** [comment]
I know @kentcdodds has already experienced problems with using `react-testing-library` in the past.
Not sure if this is the same problem, but maybe he can elaborate.

**Comment by kentcdodds** [comment]
Nothing to add. I've definitely experienced it though.
