### ISSUE TITLE
Permissions issue editing imported private repo

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#3514]
# 🐛 bug report

## Description of the problem
When importing a private repo the sandbox template is created. If you then make an edit and save it, you get a pop-up saying that the sandbox was frozen and to unfreeze it. When you then click to unfreeze, you get warning messages in the lower right corner of the window saying the session expired and there was an error while saving even though the session wasn't ended.

![Screenshot 2020-02-13 at 15 51 29](https://user-images.githubusercontent.com/1830035/74452250-bbade800-4e78-11ea-8953-17ff3ddf88ba.png)

If you click the 'sign in' as prompted, you still get errors trying to save edits to the sandbox as it looks like it's trying to save changes to the un-forked template sandbox.

## How has this issue affected you? What are you trying to accomplish?
Unable to work effectively with imported private repos

### Link to sandbox: [link]() (optional)
It's a private repo

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest
| Browser          | Chrome
| Operating System | Mac OS X

**Comment by CompuIves** [comment]
Hmm, this is really weird. I think the latest version of the client was not properly refreshed in the service worker or something, because it does work on master.build.csb.dev...

**Comment by CompuIves** [comment]
Fix for this is now deployed and live!
