### ISSUE TITLE
Unable to require parcel-bundler

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#3515]
# 🐛 bug report

## Description of the problem
I always see 'Could not find dependency: 'parcel-bundler'' when requiring parcel-bundler, even if that dependency has been added or you use the suggested 'add parcel-bundler dependency' link in the error. Prior versions don't work either, nor does using a different environment. I've tried the same code in eager-proskuriakova-379rw elsewhere and it works ok.

### Link to sandbox:
Simple: https://codesandbox.io/s/eager-proskuriakova-379rw
Other: https://codesandbox.io/s/github/TNThacker2015/electric-boi/tree/develop/

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest
| Browser          | Chrome
| Operating System | Mac OS X

**Comment by TNThacker2015** [comment]
+1, this issue has been breaking my programs.

**Comment by TNThacker2015** [comment]
https://codesandbox.io/s/intelligent-snyder-gyo36
Importing from typescript doesn't seem to work either.

**Comment by TNThacker2015** [comment]
Has anyone found a workaround for this?
