### ISSUE TITLE
Add the ability to kill or disconnect the preview 

### ISSUE THREAD

**Issue by rohan-deshpande** [codesandbox/codesandbox-client#3527]
# 🌈 Feature

I'd like the ability to kill or disconnect the preview app from the editor. The problem is, right now if you are writing code that does things inside a loop, for example, `requestAnimationFrame` loops, and you have an error inside that loop, codesandbox crashes completely and the app is perhaps unrecoverable because you cannot save or edit. The whole thing totally freezes. 

I think the feature should work by adding a "toggle preview update" button or something to the preview view which, if toggled off, kills the preview app process completely and frees up the editor for changes

I think a button like I mentioned would be good. The current way to go into preferences doesn't work because the sandbox is totally frozen/broken.

**Comment by garethx** [comment]
You can add runonclick=1 argument to the sandbox's URL, e.g.  https://codesandbox.io/s/lr21yjkvv7?runonclick=1, allowing you to stop the preview while you fix up your code.

**Comment by rohan-deshpande** [comment]
Oh wow that’s a great tip, thanks! 

Still, this would be good as a UI feature, maybe even just a button that refreshes the page but adds that query string as a stop gap.

**Comment by fletcherist** [comment]
@garethx There's no way to do it while working in PWA mode

**Comment by tylerlwsmith** [comment]
@garethx Your tip just saved me, thank you!

I'd love if there was a way to do this from the Dashboard. Maybe an option for "Open Without Preview" when you click the three dots for extra options when opening the project.

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. If you can provide us the required info, we will investigate further.
