### ISSUE TITLE
Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled

### ISSUE THREAD

**Issue by kopax** [codesandbox/codesandbox-client#3535]
# 🐛 bug report

## Description of the problem

When I try to create a codesandbox for react-native, I get the following error: 

`Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled`

![image](https://user-images.githubusercontent.com/1866564/74715554-33a45580-525f-11ea-835e-ef1305f88d80.png)

## How has this issue affected you? What are you trying to accomplish?

expo seems to have issue with the version of terser and the minified code for the web makes my app crash.

I wanted to use codesandbox but I hit this bug.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | web
| Browser          | Chrome
| Operating System | Debian Stretch

**Comment by andrasbacsai** [comment]
I'm currently having a different error in the linked sandbox. Do you have an example sandbox which is not working or is this problem still relevant?
