### ISSUE TITLE
Polymer 2 project

### ISSUE THREAD

**Issue by quangminhit94** [codesandbox/codesandbox-client#3542]
# 🌈 Feature

I am doing on a project using **Polymer 2** so I would like to create a Code Sandbox Template using **Polymer 2**
Currently, Code Sandbox can create Polymer 3 template, please help me to create a Polymer 2 Sanbox

**Comment by andrasbacsai** [comment]
Hey, do you still need a Polymer 2 template sandbox?

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. If you can provide us the required info, we will investigate further.
