### ISSUE TITLE
node-sass module not found error despite being a peer dependency in Gatsby Sandbox

### ISSUE THREAD

**Issue by dtownsend** [codesandbox/codesandbox-client#3546]
# 🐛 bug report

## Description of the problem
When trying to build Gatsby project there is a Webpack sass error saying that it can not find node sass

## How has this issue affected you? What are you trying to accomplish?
yes
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by garethx** [comment]
node-sass is a required peer-dependency of the gatsby-plugin-sass dependency, so it should just work. I'll reflect that in the issue title.

In the meantime, adding node-sass as a dependency works around this issue.

**Comment by dtownsend** [comment]
That fixed the issue.  Thank you.

**Comment by garethx** [comment]
Great to hear - I'll keep this open though, so we resolve the peer dependency issue. Thanks.

**Comment by apolopena** [comment]
Has the peer dependency issue been addressed?
