### ISSUE TITLE
Restoring deleted sandbox results in ServerParseError

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#3549]
# 🐛 bug report

## Description of the problem
When trying to recover a deleted sandbox from the trash in the dashboard, I get the following error: Network Error: ServerParseError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data.

<img width="521" alt="Screenshot 2020-02-19 at 12 26 18" src="https://user-images.githubusercontent.com/1830035/74834454-55f7ab00-5313-11ea-94ab-70a881bcaaf9.png">

## How has this issue affected you? What are you trying to accomplish?
Unable to restore deleted sandbox.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest
| Browser          | Chrome
| Operating System | Mac OS X

**Comment by jyash97** [comment]
I have created a PR to fix this: #3524 . Can you confirm if this happens on the deployed link as well ?

**Comment by garethx** [comment]
@jyash97 nice job! - it worked for me with the deployed link.
