### ISSUE TITLE
Add support for Vue Dev Tools in Preview

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#3551]
# 🌈 Feature

It'd be handy to integrate Vue DevTools (https://github.com/vuejs/vue-devtools) into the preview. Currently vue-devtools doesn't work with iframes (https://github.com/vuejs/vue-devtools/issues/353) and remote devtools doesn't look like the best solution since it requires an IP.
 

Similar to React DevTools (see preview tab in https://codesandbox.io/s/new for example).

See the approach used for React DevTools: https://github.com/codesandbox/codesandbox-client/commit/23a1f8816f117fbabc35fd1dac806542710b9ea4

**Comment by RyanHavoc** [comment]
Is anyone working on this yet or is it just a plan? 

I currently can't use devtools with Storybook. 😕

**Comment by Ishaan28malik** [comment]
@RyanHavoc are you onto this or should I give it a try?

**Comment by SaraVieira** [comment]
Reopening as this something I would love to add

**Comment by sharpninja** [comment]
This is really bad.  Our app is in transition from WebForms to more modern frameworks, one of which is Vue.  Our base website in WebForms opens all content windows in an iframe allowing for any page to be rendered in any framework.  I cannot get the extension to recognize our Vue-based pages in the iframes..
