### ISSUE TITLE
Support a directory of HTML files

### ISSUE THREAD

**Issue by kentcdodds** [codesandbox/codesandbox-client#3554]
# 🌈 Feature

I'm updating my Beginner's Guide to React on egghead.io. One of my core beliefs is that it's best if we teach people from index.html files. The very last video shows how to use Codesandbox in the typical way.

For the code samples that will appear below the videos on egghead.io, I *want* to use codesandbox embeds, but I can't use the React template because it's index.html files. So I'm going to have to just link to the github repo which isn't as cool as a codesandbox embed.

So I tried the vanilla template and was able to make this work! https://codesandbox.io/s/hidden-architecture-4ynub

[Here's the embed URL](https://codesandbox.io/embed/hidden-architecture-4ynub?hidenavigation=1&initialpath=%2Ffoo.html&module=%2Ffoo.html&theme=dark) that I plan to use:

```
https://codesandbox.io/embed/hidden-architecture-4ynub?hidenavigation=1&initialpath=%2Ffoo.html&module=%2Ffoo.html&theme=dark
```

There are a few problems with this though. I've tried to capture it in this little video: https://twitter.com/kentcdodds/status/1230309488546045952

Hopefully you notice a few of the things that would make this an awkward workflow for people if I were to do this.

The real repo is here: https://github.com/kentcdodds/beginners-guide-to-react

I'm happy to add a package.json to make this work (but it'd be awesome if I didn't need one).

Let me know if you have any questions. Thank you for all you do!

**Comment by garethx** [comment]
Assuming static when no package.json is present is something we're looking into. In the meantime, you'll get a better experience with our static template: https://codesandbox.io/s/github/codesandbox-app/static-template/tree/master/

**Comment by kentcdodds** [comment]
Thanks @garethx! I didn't realize there was a static option.

This *almost* works: https://codesandbox.io/embed/github/kentcdodds/beginners-guide-to-react/tree/codesandbox/?fontsize=14&hidenavigation=1&initialpath=%2F01-document-create-element.html&module=%2F01-document-create-element.html&theme=dark

The problem is that people can't play around with the code (and see their changes reflected in the output) unless they *save* and they can't save in the embedded iframe, they have to open the sandbox and fork it.

If there were some way to make the page reload as the person makes changes (rather than waiting for save) then that would solve my problem.

**Comment by garethx** [comment]
>> If there were some way to make the page reload as the person makes changes (rather than waiting for save) then that would solve my problem.
Do you mean within an embed or in the editor itself?

**Comment by kentcdodds** [comment]
Both. I'd love it to work the same way it does with a JavaScript file, where updates are reflected as I type and I don't have to save/fork to see my changes.

**Comment by kentcdodds** [comment]
Bump

**Comment by glebec** [comment]
I would like some kind of support for this. I want to use a single sandbox to produce many embeds for a presentation, where each embed starts editing a separate static HTML file with corresponding preview.

- If I try the "Vanilla" template, then upon edit, Parcel dumps the user back to the "main" or top HTML file, i.e. it only shows the `initialpath` file once.
- If I try the "Static" template, then editing the HTML in the embed appears to do nothing, even if the user clicks the reload button.

This is pretty frustrating as I think my only alternative at this point in time is several dozen separate CodePen embeds, which is difficult to manage (also CodePen embeds require a Pro account for users to edit them, but that's a separate matter…).
