### ISSUE TITLE
When using node.js to lookup directories, deleted directories are also found.

### ISSUE THREAD

**Issue by wpitallo** [codesandbox/codesandbox-client#3557]
# 🐛 bug report

## Description of the problem
So when I try to get a list of all directories from using node fs. The existing directories are returned but also directories that have been previously deleted. 

## How has this issue affected you? What are you trying to accomplish?
I want to only list valid directories

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | chrome
| Operating System | node.js

**Comment by garethx** [comment]
Are you referring to directories deleted via the editor UI as opposed to via the terminal?

**Comment by wpitallo** [comment]
@garethx yes, so I deleted them via the UI, when searching directories in node.js they are still returning the deleted ones.
