### ISSUE TITLE
Build error when rebuilding Gatsby project

### ISSUE THREAD

**Issue by dtownsend** [codesandbox/codesandbox-client#3559]
# 🐛 bug report

## Description of the problem
After making a modification to gatsby-node.js and then rebuilding the project caused an error in the console:
 ERROR

UNHANDLED REJECTION Not supported

  Error: Not supported

  - gatsby-node.js:8 Object.<anonymous>
    /sandbox/gatsby-node.js:8:14

  - v8-compile-cache.js:178 Module._compile
    [sandbox]/[v8-compile-cache]/v8-compile-cache.js:178:30

  - loader.js:789 Object.Module._extensions..js
    internal/modules/cjs/loader.js:789:10

  - loader.js:653 Module.load
    internal/modules/cjs/loader.js:653:32

  - loader.js:593 tryModuleLoad
    internal/modules/cjs/loader.js:593:12

  - loader.js:585 Function.Module._load
    internal/modules/cjs/loader.js:585:3

  - loader.js:692 Module.require
    internal/modules/cjs/loader.js:692:17

  - v8-compile-cache.js:159 require
    [sandbox]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - resolve-module-exports.js:126 module.exports
    [sandbox]/[gatsby]/dist/bootstrap/resolve-module-exports.js:126:26

  - validate.js:120 flattenedPlugins.forEach.plugin
    [sandbox]/[gatsby]/dist/bootstrap/load-plugins/validate.js:120:31

  - Array.forEach

  - validate.js:113 collatePluginAPIs
    [sandbox]/[gatsby]/dist/bootstrap/load-plugins/validate.js:113:20

  - index.js:62 module.exports
    [sandbox]/[gatsby]/dist/bootstrap/load-plugins/index.js:62:13

  - index.js:181 module.exports
    [sandbox]/[gatsby]/dist/bootstrap/index.js:181:34

not finished onPreInit - 0.082s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.19.1
$ gatsby develop
success open and validate gatsby-configs - 0.022s
success load plugins - 0.311s

 ERROR

UNHANDLED REJECTION Not supported

  Error: Not supported

  - gatsby-node.js:8 Object.<anonymous>
    /sandbox/gatsby-node.js:8:14

  - v8-compile-cache.js:178 Module._compile
    [sandbox]/[v8-compile-cache]/v8-compile-cache.js:178:30

  - loader.js:789 Object.Module._extensions..js
    internal/modules/cjs/loader.js:789:10

  - loader.js:653 Module.load
    internal/modules/cjs/loader.js:653:32

  - loader.js:593 tryModuleLoad
    internal/modules/cjs/loader.js:593:12

  - loader.js:585 Function.Module._load
    internal/modules/cjs/loader.js:585:3

  - loader.js:692 Module.require
    internal/modules/cjs/loader.js:692:17

  - v8-compile-cache.js:159 require
    [sandbox]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - resolve-module-exports.js:126 module.exports
    [sandbox]/[gatsby]/dist/bootstrap/resolve-module-exports.js:126:26

  - validate.js:120 flattenedPlugins.forEach.plugin
    [sandbox]/[gatsby]/dist/bootstrap/load-plugins/validate.js:120:31

  - Array.forEach

  - validate.js:113 collatePluginAPIs
    [sandbox]/[gatsby]/dist/bootstrap/load-plugins/validate.js:113:20

  - index.js:62 module.exports
    [sandbox]/[gatsby]/dist/bootstrap/load-plugins/index.js:62:13

  - index.js:181 module.exports
    [sandbox]/[gatsby]/dist/bootstrap/index.js:181:34

not finished onPreInit - 0.044s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.19.1
$ gatsby develop
success open and validate gatsby-configs - 0.018s
success load plugins - 0.307s

 ERROR

UNHANDLED REJECTION Not supported

  Error: Not supported

  - gatsby-node.js:8 Object.<anonymous>
    /sandbox/gatsby-node.js:8:14

  - v8-compile-cache.js:178 Module._compile
    [sandbox]/[v8-compile-cache]/v8-compile-cache.js:178:30

  - loader.js:789 Object.Module._extensions..js
    internal/modules/cjs/loader.js:789:10

  - loader.js:653 Module.load
    internal/modules/cjs/loader.js:653:32

  - loader.js:593 tryModuleLoad
    internal/modules/cjs/loader.js:593:12

  - loader.js:585 Function.Module._load
    internal/modules/cjs/loader.js:585:3

  - loader.js:692 Module.require
    internal/modules/cjs/loader.js:692:17

  - v8-compile-cache.js:159 require
    [sandbox]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - resolve-module-exports.js:126 module.exports
    [sandbox]/[gatsby]/dist/bootstrap/resolve-module-exports.js:126:26

  - validate.js:120 flattenedPlugins.forEach.plugin
    [sandbox]/[gatsby]/dist/bootstrap/load-plugins/validate.js:120:31

  - Array.forEach

  - validate.js:113 collatePluginAPIs
    [sandbox]/[gatsby]/dist/bootstrap/load-plugins/validate.js:113:20

  - index.js:62 module.exports
    [sandbox]/[gatsby]/dist/bootstrap/load-plugins/index.js:62:13

  - index.js:181 module.exports
    [sandbox]/[gatsby]/dist/bootstrap/index.js:181:34

not finished onPreInit - 0.075s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## How has this issue affected you? What are you trying to accomplish?
Yes
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by garethx** [comment]
Your code needs to be valid. Try ```const path = require("path")

exports.onCreateNode = ({ node, actions }) => {
  const { createNodeField } = actions

  if (node.internal.type === "MarkdownRemark") {
    const slug = path.basename(node.fileabsolutePath, ".md")
    console.log("@@@@@@@@@@@@@@@@@", slug)
  }
}```
