### ISSUE TITLE
Support lit-html highlight

### ISSUE THREAD

**Issue by mantou132** [codesandbox/codesandbox-client#3562]
# 🌈 Feature

[lit-html](https://github.com/Polymer/lit-html) template example:
```js
html`
  <div></div>
`
```

More and more applications use es string templates to write HTML, hope to support html highlighting

**Comment by SaraVieira** [comment]
Can you please tell me what is the best vscode extension to support this?

**Comment by mantou132** [comment]
@SaraVieira 
https://github.com/mjbvz/vscode-lit-html
https://github.com/runem/lit-analyzer/tree/master/packages/vscode-lit-plugin
The former is simpler, the latter is more powerful
