### ISSUE TITLE
<Button /> components should have title="acronym"

### ISSUE THREAD

**Issue by anuraghazra** [codesandbox/codesandbox-client#3563]
# 🐛 bug report

## Description of the problem
I'm not sure if this is a bug but i feel like that Button elements should have a title attribute, here's why

## Without title attribute: :-1: 
![csb-button1](https://user-images.githubusercontent.com/35374649/75088597-935b7300-5575-11ea-9431-f64cccd2107f.png)

## With title attribute: :+1: 
![csb-button2](https://user-images.githubusercontent.com/35374649/75088607-a79f7000-5575-11ea-926d-4c4dbc0a536d.png)

## How has this issue affected you? What are you trying to accomplish?
As we can see that the "deploy" button is truncating the text to fit in size, but when hovering over the button we don't know what that button do, thus setting title attribute will show the button text in a small popup.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Google Chrome 
| Operating System | Windows 7 64bit

**Comment by MichaelDeBoey** [comment]
I think we could make the button full-length when there’s not enough room.

Can be done with the redesign @SaraVieira & @siddharthkp are implementing.

**Comment by SaraVieira** [comment]
Hey!

This has been implemented in the redesign of the sidebar 🎉🎉

You can turn it on by clicking on your avatar > settings > experiments > sidebar redesign

This will be the default next week :)

**Comment by anuraghazra** [comment]
Oh okay! new redesign looks CLEAN! nice. 

closing this then.

**Comment by SaraVieira** [comment]
Thank you 🙏
