### ISSUE TITLE
User snippets are not working (in most use cases, most of the time)

### ISSUE THREAD

**Issue by sventhevenn** [codesandbox/codesandbox-client#3569]
# 🐛 bug report

## Description of the problem
User snippets won't open most of the time, and no user snippets are working.

## How has this issue affected you? What are you trying to accomplish?
I'm trying to add standard react snippets and some custom ones to my user.

When entering user snippets through the menu (file -> preferences -> user snippets), nothing happens.

When entering user snippets using ctrl + shift + p, and entering "Preferences: Configure User Settings" I get this error:

![image](https://user-images.githubusercontent.com/36860992/75124400-39f75f00-56af-11ea-8d04-b9060a666c91.png)

I did manage to get into the snippets files on Chrome 79, but the snippets did not work.

On Firefox 73 I got it working by not being logged in (can't remember if I used the menu or command). After logging into CodeSandbox on Firefox I can't get it to work again.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1581626805-0394eb371
| Browser          | Chrome 79
| Operating System | Windows 10

**Comment by garethx** [comment]
Duplicates #3110 but I'll add the extra info as a comment. Thanks for reporting.
