### ISSUE TITLE
Shouldn't typescript error result in failed tests?

### ISSUE THREAD

**Issue by adrianmroz** [codesandbox/codesandbox-client#3570]
# Shouldn't typescript error (from builtin config) result in failed test (with builtin support for jest)?

### Link to sandbox: [sandbox with typescript and jest](https://codesandbox.io/s/muddy-meadow-9tjqv?fontsize=14&hidenavigation=1&theme=dark)

I started sandbox with basic support for typescript and jest. I created source file with function in ts and test file for it. I would expect that if I get compilation error in source file, test would fail - function can't compile so it can't have desired behaviour. 

Am I missing something? Or maybe I need to add something to configuration?

**Comment by CompuIves** [comment]
Hah, interesting one this one. We don't do any type verification in the bundler right now, which is what we need to do to make this work.
