### ISSUE TITLE
Default selected file text not always shown in embed

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#3572]
# 🐛 bug report

## Description of the problem
The text of the default selected file isn’t always shown if it’s not visible at load until you interact with it, like selecting it from the menu bar.

See https://www.loom.com/share/2a49ae33cbde43b9b92f48062e2764e6

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest
| Browser          | Chrome
| Operating System | Mac OS X

**Comment by lbogdan** [comment]
For me the code shows as soon as I release the mouse button after dragging.
