### ISSUE TITLE
Runtime error "can't convert undefined to object" while trying to fork a fork.

### ISSUE THREAD

**Issue by mcalus3** [codesandbox/codesandbox-client#3586]
# 🐛 bug report

## Description of the problem

When tried to fork my sandbox that is a fork, a runtime error occured:

internalActions.ts:403:12:
TypeError: "can't convert undefined to object"
    e internalActions.ts:380
    d runtime.js:45
    _invoke runtime.js:271
    o runtime.js:97
    t asyncToGenerator.js:3
    i asyncToGenerator.js:25

## How has this issue affected you? What are you trying to accomplish?

I'm creating a series of embedded snippets for a blog post and wanted to fork each step from a previous one. I don't know if it is possible, or should I create new sandboxes and copy-paste code from previous step instead.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox | PROD-1582498771-d91b0f8b1 |
| Browser | Firefox 73 |
| Operating System | Windows 10 |

**Comment by mcalus3** [comment]
Never mind, it works now. I'll leave this, because someone could want look into this specific line of code and try to figure out if there is any suspicious code.

Feel free to close.

**Comment by garethx** [comment]
I'm seeing this too when trying to fork my own fork, so I will leave open.

**Comment by mcalus3** [comment]
One more thing - Now I realized that these forks were in fact being created, but I wrongly interpreted this runtime error notification as "action failed" message.
