### ISSUE TITLE
fetch types file error

### ISSUE THREAD

**Issue by KieSun** [codesandbox/codesandbox-client#3593]
# 🐛 bug report

## Description of the problem

We are @muya-ui/core developer.

In [demo](https://codesandbox.io/s/muya-ui-demo-7kgx4), we found fetch @muya-ui/core types file will cause error.

![](https://qhstaticssl.kujiale.com/newt/100759/image/png/1582874742538/2F014FD1E23F9F14EB12FAA1ACB5456B.png)

But when we delete some deps of package.json and publish the new version,  error is gone.

So we presume that this fetch API can't handle large file. 

In your [type-fetcher repo](https://github.com/codesandbox/type-fetcher/blob/master/api/typings.ts), we found the `MAX_RES_SIZE` is 5.8 MB.

## How has this issue affected you? What are you trying to accomplish?

Can't find types.

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/muya-ui-demo-7kgx4

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | 80.0.3987.122
| Operating System | macOS 10.15.1

**Comment by SaraVieira** [comment]
Hey!

This was closed but seems like it has also been fixed in the meantime :D
