### ISSUE TITLE
Upgrade TypeScript to 3.7 or greater

### ISSUE THREAD

**Issue by gamedevsam** [codesandbox/codesandbox-client#3597]
# 🌈 Upgrade TypeScript version to 3.7 or greater

TS 3.7 brings along some MAJOR improvements to the language, including:

- Optional Chaining
- Nullish Coalescing
- Assertion Functions
- Recursive Type Aliases (my personal favorite)

My imported project doesn't work properly because I make use of recursive types and assertion functions: https://codesandbox.io/s/react-typescript-type-safe-redux-with-immerreducer-tdl7w

Ship TypeScript 3.7 or greater with the editor, please.

**Comment by stnwk** [comment]
What is blocking that from being possible? How can we help?

**Comment by garethx** [comment]
The version of TypeScript comes from VS Code, so we need to upgrade the version of VS Code we've integrated in order to enable this. As you might imagine, that's a significant amount of work. We've made good progress and I think we'll be able to do this soon, though I don't have dates to share yet.

**Comment by stnwk** [comment]
Thanks for the explanation! All the best with it :)

**Comment by FredyC** [comment]
I wonder, would it be impossible to somehow enable the use of TypeScript version installed through `package.json`? The VSCode allows but this option is missing in CS for some reason. That way you wouldn't need to update VSCode with every new TS version that brings important changes.

![image](https://user-images.githubusercontent.com/1096340/77222424-3db5be80-6b53-11ea-8caf-d79de6922ea5.png)

**Comment by CompuIves** [comment]
Heyo! We've updated TypeScript to v3.8.3 🎉! I like your suggestion @FredyC, this is definitely possible, I'll create an issue for it. https://github.com/codesandbox/codesandbox-client/issues/3904

In the meantime, we can close this one!
