### ISSUE TITLE
React project render twice?

### ISSUE THREAD

**Issue by zpc7** [codesandbox/codesandbox-client#3598]
# 🐛 bug report

## Description of the problem
When I do some optimization about react project, I found the react function 'render' execution twice, no matter when the Initialization process and the react state change. It make me very confusion +_+
![image](https://user-images.githubusercontent.com/15316908/75620911-e01ff900-5bc8-11ea-80d5-3d5c1e7772b8.png)

## How has this issue affected you? What are you trying to accomplish?
I cannot observed the project correct behavior.. The function should be execution only once.
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1582498771-d91b0f8b1
| Browser          | Chrome 80.0.3987.122
| Operating System | macOS 10.15.3 (19D76)

**Comment by jyash97** [comment]
Hey @zpc7 

This is because you are wrapping the component with `React.StrictMode` and it re-renders intentionally. Check the thread here: https://github.com/facebook/react/issues/12856.

Also removing StrictMode renders as expected. Link: https://codesandbox.io/s/react-sandbox-render-twice-hbixn

**Comment by zpc7** [comment]
@jyash97 Oh It's Cool ! 
Not careful enough for myself. Thank you very much.
I will close the issue also.
