### ISSUE TITLE
Resource interpreted as stylesheet but transferred with MIME type text/html

### ISSUE THREAD

**Issue by SergioBota** [codesandbox/codesandbox-client#3603]
# 🐛 bug report

## Description of the problem
no css for my htmls :(
## How has this issue affected you? What are you trying to accomplish?
 i wass workinng on my sandbox happily and sundely  no css were loaded, i did not changed how it wass loaded.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/musing-framework-sqcr7
### Your Environment
static

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome , Edge
| Operating System | win 10

**Comment by CompuIves** [comment]
Hey @SergioBota,

Is this still happening for you? I can't seem to repro the issue, but I do know that the server was having some issues with responding to network requests when you had this problem. These two things might be related in this case.

**Comment by sergiobotavividseats** [comment]
nope, it fixed itself, sorry
