### ISSUE TITLE
Suddenly no public assets folder access

### ISSUE THREAD

**Issue by marko-x** [codesandbox/codesandbox-client#3612]
# 🐛 bug report
Is exact the same as: https://github.com/codesandbox/codesandbox-client/issues/805

## Description of the problem
No access to public folder to load images.

## How has this issue affected you? What are you trying to accomplish?
i didn't do anything.  This bug occurred for just some minutes ago.

**Comment by CompuIves** [comment]
Hey! Do you have an example sandbox? I can't repro the issue

**Comment by marko-x** [comment]
This is really strange. I forked my codesandbox (to give you a copy without unneccassary stuff). *In the forked version all things going right.* But the original CSB has this bug (described above).

In the original CSB i found out: 
Some svg still loading, some redirecting to index. Some pngs not loading, and redirecting to index, but some other pngs redirecting to something like https://uploads.codesandbox.io/uploads/user/****/

Mh. so i should use the forked version.
