### ISSUE TITLE
Chrome 80 SameSite=Lax change broke private sandboxes

### ISSUE THREAD

**Issue by jonnyasmar** [codesandbox/codesandbox-client#3617]
# 🐛 bug report

## Description of the problem

It looks like the SameSite=Lax change in Chrome 80 has broken private sandboxes. When accessing a private sandbox, the app never loads and the page continues to reload tons of network assets (network tab goes nuts).

If you set [chrome://flags/#same-site-by-default-cookies](chrome://flags/#same-site-by-default-cookies) to `Disabled`, everything goes back to normal. I've tried this with every scale of app, from the most basic, `document.write('test')` app to a complex React CRA-based SPA and get the same symptoms.

The only cookie I see that's affected by this change is `_cfduid`, but I'm not 100% sure.

## How has this issue affected you? What are you trying to accomplish?

It's broken my heart. I'm not sure I'll ever recover 😭 

For real, though -- we leverage CodeSandbox for our organizations FE tech screens. We're able to work around this by instructing our candidates to use Firefox, but we are really averse to any added friction at the start of a tech screen.

### Link to sandbox: [link]() (optional)

Useless since you can only see the issue in private sandboxes. Should be easy enough to repro, though.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Current |
| Browser          | Chrome 80+ |
| Operating System | Mac OS X Catalina |

**Comment by garethx** [comment]
I'm having problems reproducing this. Do you have issues when accessing your own private sandbox directly or do problems occur for invited folks during a live session?

**Comment by jonnyasmar** [comment]
@garethx Are you using Chrome 80+? I'm having the issue for my own private sandboxes.

**Comment by garethx** [comment]
Yes, 82. Which specific version are you using? I'll try matching.

**Comment by jonnyasmar** [comment]
Thanks, @garethx -- I'm on Chrome 80.0.3987.132

**Comment by jonnyasmar** [comment]
Hmm -- I just had a chance to test on my Windows machine and it actually seems like the issue is specific to Mac... On Mac I can only test against Catalina, so I'm not sure if previous versions are having the same problem.

**Comment by jonnyasmar** [comment]
Ahhh -- nope... strangely, it seems like on Windows, the default for chrome://flags/#same-site-by-default-cookies is `Disabled`. If I explicitly set it to `Enabled` I'm able to repro in Windows.

(Same Chrome version on both machines)

**Comment by jonnyasmar** [comment]
Update here: just discovered that the change to make [chrome://flags/#same-site-by-default-cookies](chrome://flags/#same-site-by-default-cookies) default to `Enabled` is being gradually rolled out:

https://www.chromium.org/updates/same-site

So, in order to repro this, you may have to explicitly set that flag to `Enabled`.

**Comment by JesseHGerard** [comment]
I was able to reproduce the behavior:
Chrome 80.0.3987.132,  macOS Catalina 10.15.03

Chrome flag needed to be turned on for me: chrome://flags/#same-site-by-default-cookies 

codesandbox reloaded so fast it's hard to tell what's going on. It seems like the JSX parser worker is related.

![Screen Shot 2020-03-10 at 5 14 27 PM](https://user-images.githubusercontent.com/25722880/76360101-c1b9ac00-62f2-11ea-8a86-bc8eeb2433a0.jpg)
![Screen Shot 2020-03-10 at 5 14 49 PM](https://user-images.githubusercontent.com/25722880/76360107-c54d3300-62f2-11ea-866b-682cb4d19bdf.jpg)

**Comment by garethx** [comment]
@jonnyasmar Ah, great catch - that explains why I couldn't reproduce in 80 either. Will flag to the team!

**Comment by CompuIves** [comment]
Deploying now, should be live within 15 min!

**Comment by jonnyasmar** [comment]
Can confirm the fix is live and working! Thanks so much @CompuIves
