### ISSUE TITLE
Feature request: support package aliasing (@npm)

### ISSUE THREAD

**Issue by xugao** [codesandbox/codesandbox-client#3627]
# 🌈 Feature

## What is this feature?
Allow install a package with different package name. Like how we can do with `npm` or `yarn`:
`npm install react-foo@npm:react`
currently it doesn't seem to be supported: https://codesandbox.io/s/spnnz

## How the feature should work?
In codesandbox.io, user should be able to add dependency such as: `react-foo@npm:react`
then they can `import ... from react-foo` in code

**Comment by jamime** [comment]
I have the same issue, @xugao did you find a solution?

**Comment by xugao** [comment]
@jamime - i don't think there is a way to do this currently. Need to be implemented.
