### ISSUE TITLE
Console.log in web worker does not appear in sandbox console

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#3631]
# 🐛 bug report

## Description of the problem
Web Workers can send but can't log output messages in a sandbox console. 
https://codesandbox.io/s/web-worker-example-34xy2 posts to the worker and the onmessage doesn't seem to update to the console. Running it locally it works. 

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest

**Comment by mohinderps** [comment]
Hey @garethx, It seems to be working.

Check the following sandbox:
https://codesandbox.io/s/web-worker-example-49f3o

**Comment by tchardin** [comment]
Hey, you're right. Looks like the issue is just with logging and should be reframed as: 
**console.log in web worker does not appear in sandbox console.** (It does show in the browser console)
Thanks clearing that out!

**Comment by mohinderps** [comment]
Yes, definitely some issue with console.
