### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by arhoy** [codesandbox/codesandbox-client#3643]
Just trying to run my project in Codesandbox.
It says 502 bad gateway. I have no errors in local host so not sure what the issue is

Can someone please help? This is my first time uploading to codesandbox
https://codesandbox.io/s/zeitlify-test-whz0n

**Comment by garethx** [comment]
When do you encounter this error? It seems to load ok for me.

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. If you can provide us the required info, we will investigate further.
