### ISSUE TITLE
Multiple CodeSandbox embeds still crashing on iOS Safari/Chrome

### ISSUE THREAD

**Issue by Anemolo** [codesandbox/codesandbox-client#3646]
#3645  🐛 bug report

## Description of the problem
Having multiple codesandbox embeds crashes iOS safari/chrome

## How has this issue affected you? What are you trying to accomplish?
Exact same issue as in #839, I have a blog with multiple Codesanbox embeds on a single page. And adding more than 3 embeds crashes on iOS safari/chrome. All my sandboxes have "runOnClick" by default.

### Link to sandbox: [link]() (optional)
- Replicated here https://codesandbox.io/s/recursing-newton-9rgc1

#### Sandboxes i'm trying to embed:
- https://codesandbox.io/s/spheres-mehses-b5v1m
- https://codesandbox.io/s/instanced-geometry-final-rcryp
- https://codesandbox.io/s/instanced-geometry-no-animation-8312p
- https://codesandbox.io/s/instanced-geometry-no-animation-xhojw
- https://codesandbox.io/s/instanced-geometry-no-positioning-excy3
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |  iOS Safari/Chrome
| Operating System | iOS 12.4.1

**Comment by machadcm** [comment]
Hi,

Similar problem when open https://codesandbox.io/s/map-0m9ti on ipad with iOS 13.3.1, browser keeps crashing.

Thanks
