### ISSUE TITLE
Can't share csb.app links to facebook

### ISSUE THREAD

**Issue by anuraghazra** [codesandbox/codesandbox-client#3651]
# 🐛 bug report

## Description of the problem
Can not share csb.app links in facebook. it says "Your post couldn't be shared, because this link goes against our Community Standards"

*note: normal https://codesandbox.io/s/ links are working*

## How has this issue affected you? What are you trying to accomplish?
![csbapp-fb](https://user-images.githubusercontent.com/35374649/76165262-92346380-617b-11ea-9209-e2689d5871b9.PNG)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by garethx** [comment]
Thanks for reporting, we'll contact Facebook about their error.

**Comment by anuraghazra** [comment]
Okay looks like the issue is resolved, i can share csb.app links now. should we close it @MichaelDeBoey ?
