### ISSUE TITLE
Hi team, when i try to login to codesandbox it is showing login again and again after i login by using github

### ISSUE THREAD

**Issue by atchuta168** [codesandbox/codesandbox-client#3654]
# ❔ Question

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by garethx** [comment]
Sorry to hear that. Have you changed your GitHub username or default email address since registering on CodeSandbox? If so, if you email hello@codesandbox.io with your GitHub username and new and old email address, then we’ll get it updated for you

**Comment by atchuta168** [comment]
No, I have not changed email address

**Comment by MichaelDeBoey** [comment]
Closed by #3659
