### ISSUE TITLE
codesandbox.io is not working when third party cookies are disabled

### ISSUE THREAD

**Issue by derMart** [codesandbox/codesandbox-client#3666]
# 🐛 bug report

## Description of the problem

Codesandbox is not working when third party cookies are disabled

## How has this issue affected you? What are you trying to accomplish?

Codesandbox should work without third party cookies.

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/dreamy-austin-04lwp

### Your Environment

Firefox 73, Windows x64
If third party cookies are disabled codesandbox.io just displays a white preview pane.

**Comment by garethx** [comment]
This isn't a bug, but we can certainly do a better job of informing the user as to the problem, which https://github.com/codesandbox/codesandbox-client/issues/2877 is open to track.
