### ISSUE TITLE
[Share/Embed] Multiple modules not supported in link to sandbox (only embed)

### ISSUE THREAD

**Issue by jsejcksn** [codesandbox/codesandbox-client#3668]
# 🐛 bug report

## Description of the problem

#1315 was implemented, which allows linking to multiple modules when sharing. Here's what [the docs](https://codesandbox.io/docs/embedding#embed-options#:~:text=multiple,tabs) say:

> **Embed options**
>
> `module`: Which module to open by default. Multiple paths comma separated are allowed, in that case we show them as tabs

Multiple modules don't work when linking to a sandbox (paths beginning with `/s/`). They only work for links to embeds (paths beginning with `/embed/`).

Here are example links demonstrating this:

Sandbox:
https://codesandbox.io/s/481l76l2x9?module=/src/Todo/TodoController.js,/src/Todo/TodoList.js

Embed:
https://codesandbox.io/embed/481l76l2x9?module=/src/Todo/TodoController.js,/src/Todo/TodoList.js

## Expected

Including multiple modules in a link to a sandbox opens those modules in editor tabs

## Observed

Only the first comma-separated module path opens in a tab

(But works as expected for embeds)

## Additional info

Perhaps it is intended that only some embed options will work for links to sandboxes and only some will work for links to embed views, but if that is the case, it is not documented.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | any
| Browser          | any
| Operating System | any

**Comment by garethx** [comment]
This is intentional, it's an embed-only option and the linked docs are for embeds. However, adding the ability to link to specific files (and lines) within a sandbox is something we want to add, so it could take this into account.

**Comment by jsejcksn** [comment]
@garethx Will you clarify which embed options work for sandboxes? (One example: linking to an individual module)

**Comment by garethx** [comment]
Aside from module as you've described, expanddevtools, moduleview, previewwindow and runonclick work in the editor. I'll find some place to include this in the docs.
