### ISSUE TITLE
How are reproducible sandboxes decided?

### ISSUE THREAD

**Issue by jamime** [codesandbox/codesandbox-client#3674]
# ❔ Question

When installing the codesandbox-ci app it says

> Bug reports with reproducible sandboxes are automatically created using the new PR build to review online.

1. How do you determine what is a reproducible? I would assume it is any PR body that contains a codesandbox link? But it's not clear.

2. How do you make the association between the Github PR and the Github Issue? I would assume it is anything that uses a [keyword to link](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). But it's not clear.

Thanks for building a great product :tada:

**Comment by garethx** [comment]
Thanks @jamime, glad you like it. It's yes and yes: we traverse the body of the PR and the linked issues and check for CodeSandbox links and fork those.
