### ISSUE TITLE
Stuck at Creating Repository

### ISSUE THREAD

**Issue by mohasinac** [codesandbox/codesandbox-client#3675]
# 🐛 bug report

## I am trying to host the code on a github repository , but the loading is endless.

![image](https://user-images.githubusercontent.com/61693321/76397460-1c114600-63a1-11ea-93b6-322c212748bb.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Google Chrome|
| Windows |

**Comment by garethx** [comment]
The linked sandbox is private or has been removed, so I'm not able to look into it. Do you have a public sandbox I can try?

**Comment by mohasinac** [comment]
Sorry ,I deleted that sandbox.
I cannot find any way to make it public.
But you can re-create the bug by creating a new solution using the default React template.
And then under github source control selecting export to github 
Then giving a repo name.
After that the shown loading continues infinitely.

**Comment by simoroshka** [comment]
I have the same problem. The repository is created at github but has only an initial README file

**Comment by simoroshka** [comment]
The request fails with status 422 and this response
```
{"errors":{"detail":["Request failed with status code 409"]}}
```

**Comment by kshitijzutshi** [comment]
I am struggling with the exact same problem!! ANY FIX YET?

**Comment by garethx** [comment]
Do you have a public sandbox I can try?

**Comment by kshitijzutshi** [comment]
Never mind, I managed to resolve this by First making a repo in github and then going to codesandbox.

**Comment by garethx** [comment]
We have a fix going out for creating a repo from a private sandbox.

**Comment by garethx** [comment]
This should now be resolved - let us know if you still experience issues.

**Comment by CreeTar** [comment]
Still there, new bug or reopen?

**Comment by garethx** [comment]
@CreeTar Are you having problems creating a repo from a private sandbox?

**Comment by CreeTar** [comment]
> @CreeTar Are you having problems creating a repo from a private sandbox?

nevermind, now it works for some reason. I got the 422, which was a problem in a similar issue. But now it's creating a repo and keeping it. Thanks though.
