### ISSUE TITLE
How to disable/suspend the client to the right?

### ISSUE THREAD

**Issue by OnkelTem** [codesandbox/codesandbox-client#3679]
Is there a way to stop it?

I haven't finished editing my script, (moreover, it just went into some kind of infinite loop and isn't allowing me to do any edit. I cannot even access the Menu: details are [here](https://github.com/codesandbox/codesandbox-client/issues/3678)), **I don't need to get it running/rebuilding/transpiling/whatsoever.** 
So how to basically pause/suspend or stop it?
Also, I don't feel good with having the half of my screen eaten off by the client to the right.

**Comment by garethx** [comment]
Add `runonclick=1` to the end of the sandbox URL and your site will wait to be executed e.g. https://codesandbox.io/s/new?runonclick=1

Please just create a single issue to report a problem - you don't need to add comments to several related issues to get help with this one thing. Thanks.
