### ISSUE TITLE
Math.sign(-0) returns 0, but should be returning -0

### ISSUE THREAD

**Issue by rsabhishek** [codesandbox/codesandbox-client#3694]
# 🐛 bug report

## Description of the problem
Math.sign(-0) returns 0, but should be returning -0

## How has this issue affected you? What are you trying to accomplish?

I was doing some work, where i wanted to check if the value is negative or not, but in the case of zero it fails.

### Your Environment
Vanilla JS
| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome
| Operating System | Mac

**Comment by garethx** [comment]
Confirmed - example sandbox since once wasn't supplied in the original report: https://codesandbox.io/s/elated-lehmann-d7ix7
