### ISSUE TITLE
Unable to open sand-boxes on Safari

### ISSUE THREAD

**Issue by loreanvictor** [codesandbox/codesandbox-client#3697]
# 🐛 bug report

## Description of the problem
A typical sandbox does not open in safari. Either via the direct link of the sandbox, or via the dashboard link. Checked for a few different sandboxes, trying to create a new sandbox from a template, etc. The result is the same. Everything seems to be working perfectly fine on Chrome and Firefox.

Screenshots:
<img width="1440" alt="Screen Shot 2020-03-15 at 6 10 25 PM" src="https://user-images.githubusercontent.com/13572283/76706523-5738af80-66e8-11ea-8de8-ab352d9b026d.png">
<img width="1440" alt="Screen Shot 2020-03-15 at 6 10 44 PM" src="https://user-images.githubusercontent.com/13572283/76706527-661f6200-66e8-11ea-93cd-5ebb13a5c617.png">

## How has this issue affected you? What are you trying to accomplish?
I was trying to open my sandboxes using Safari.

### Link to sandbox: 
[link1](https://codesandbox.io/s/connective-sdh-hellow-world-deom3)
[link2](https://codesandbox.io/s/connective-sdh-static-components-r3b8i)
[link3](https://codesandbox.io/s/connective-sdh-9k53z)
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  latest web version 15-03-2020
| Browser          | Safari 12.1 (14607.1.40.1.4)
| Operating System | macOS Mojave 10.14.4

**Comment by garethx** [comment]
I'm not able to reproduce in Safari 13, are you able to upgrade?

**Comment by CompuIves** [comment]
Hmm, I think that this version of CodeSandbox is really old, as it still uses mobx-state-tree. Could you try deleting all your caches in Safari and try again?

**Comment by loreanvictor** [comment]
@CompuIves thanks, that resolved the issue.

**Comment by CompuIves** [comment]
Great to hear!
