### ISSUE TITLE
Unable to load external json schemas using url field in settings.json

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#3701]
# 🐛 bug report

## Description of the problem
When trying to specify an external json schema, I just see 'Loading...' when hovering over what should be an error description.
![Screenshot 2020-03-16 at 14 18 14](https://user-images.githubusercontent.com/1830035/76767760-02517380-6792-11ea-857e-9fe286e4ed07.png)

Specifying a local file works.
![Screenshot 2020-03-16 at 14 25 23](https://user-images.githubusercontent.com/1830035/76767770-067d9100-6792-11ea-962c-333c48e074af.png)

### Link to sandbox:
External URL fails: https://codesandbox.io/s/openfin-template-9plup
Local file works: https://codesandbox.io/s/openfin-template-542dk

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  PROD-1584286840-fb6c3818b
| Browser          | Chrome
| Operating System | Mac OS X

**Comment by johnman** [comment]
Is it possible to get this fixed?
