### ISSUE TITLE
Code Sandbox infinite loop since Last few weeks

### ISSUE THREAD

**Issue by hiteshsahu** [codesandbox/codesandbox-client#3712]
My sandbox preview is  went into infinite loop. I can't use it anymore. It keep on reloading preview so I cant use it anymore even though I am a Patron and paying every month for it.

**Comment by CompuIves** [comment]
Hey @hiteshsahu. Do you experience this in private sandboxes? It might be related to #3617, I'm going to take a look at that today.

**Comment by hiteshsahu** [comment]
Yes its a private Sandbox

**Comment by CompuIves** [comment]
I just pushed a fix, will deploy it later today!

**Comment by CompuIves** [comment]
Deploying now, should be live within 15 min.

**Comment by hiteshsahu** [comment]
It has been resolved now . Thanks
