### ISSUE TITLE
No Terminal on React apps?

### ISSUE THREAD

**Issue by dalmo3** [codesandbox/codesandbox-client#3733]
# 🐛 bug report
Or is it a *feature*?

## Description of the problem
I'd like to be able to use the Terminal but it doesn't show up.
![image](https://user-images.githubusercontent.com/33860060/77207017-31366380-6b5d-11ea-94cd-bfc196503a3c.png)

Tried setting `"view": "terminal"` at `sandbox.config.json` but to no avail.

### Link to sandbox: [link](https://codesandbox.io/s/react-new) (optional)
Fully reproducible by forking the basic React template https://codesandbox.io/s/react-new

**Comment by garethx** [comment]
A terminal is only available in container sandboxes, whereas React sandboxes are client sandboxes. See https://codesandbox.io/docs/environment for more detail on the difference. Thanks.
