### ISSUE TITLE
Dependency not being installed due to failed request to https://ata-fetcher.cloud/

### ISSUE THREAD

**Issue by crux153** [codesandbox/codesandbox-client#3736]
# 🐛 bug report

## Description of the problem

<img width="691" alt="Screen Shot 2020-03-22 at 4 28 14 PM" src="https://user-images.githubusercontent.com/10908841/77244620-36c5a380-6c5a-11ea-8b6f-457c1ca1a3b2.png">

<img width="789" alt="Screen Shot 2020-03-22 at 4 29 30 PM" src="https://user-images.githubusercontent.com/10908841/77244632-72f90400-6c5a-11ea-8bae-55070555e0a6.png">

I can't install `@elastic/eui` as dependency due to the failed request to [https://ata-fetcher.cloud/api/v5/typings/@elastic/eui@21.1.0.json](https://ata-fetcher.cloud/api/v5/typings/@elastic/eui@21.1.0.json)

<img width="572" alt="Screen Shot 2020-03-22 at 4 31 24 PM" src="https://user-images.githubusercontent.com/10908841/77244645-9ae86780-6c5a-11ea-8e21-860d66b2e838.png">

It seems ata-fetcher.cloud is a serverless service related to typings, but directly invoking it via url results in an 502 error.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 
| Browser          |  Google Chrome 80.0.3987.149
| Operating System | macOS Version 10.14.6

**Comment by garethx** [comment]
I see 'ENOSPC: no space left on device' when trying to load the dependency, so it looks like it's too big for the service we're using. https://github.com/codesandbox/codesandbox-client/issues/3502 Is already open to workaround this. Please follow that for updates.
