### ISSUE TITLE
Option to hide menu on embed

### ISSUE THREAD

**Issue by limitlessloop** [codesandbox/codesandbox-client#3747]
# 🌈 Option to Hide Menu on Embed

It would be useful to be able to hide the main menu which appears when the code editor gets to a certain size using embeds.

I'm using it on my blog and it becomes too distracting.

<img width="1585" alt="Screenshot 2020-03-24 at 14 31 19" src="https://user-images.githubusercontent.com/5551/77437092-26d5cd00-6ddc-11ea-92ad-9a5b5fb00d75.png">

It should work by being able to set a flag on the embed URL such as `&menu=0`.

**Comment by avelinocneto** [comment]
Can you share the css? I want to test here.. I would like too hide too!

**Comment by limitlessloop** [comment]
Hi @avelinocneto, what CSS are you referring to?

**Comment by avelinocneto** [comment]
Hi @limitlessloop , the style.css file that you used in a feature.
The image attached only have a partial code.

**Comment by limitlessloop** [comment]
Hi @avelinocneto, yep no problem.

https://gist.githubusercontent.com/limitlessloop/b1dfb1344c947bfaf63fb23cfcae2414/raw/f3f3ca7b4f41b253774dbfcb05c3c485772f07fd/leading-trim.css
