### ISSUE TITLE
define API no longer works: blocked by CORS policy

### ISSUE THREAD

**Issue by csr632** [codesandbox/codesandbox-client#3750]
# 🐛 bug report

## Description of the problem

https://codesandbox.io/s/9loovqj5oy?from-embed

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by CompuIves** [comment]
Hey! Sorry for the inconvenience, we changed our ingress which didn't take the CORS headers into account. It should be fixed now.
