### ISSUE TITLE
How to know preview url address

### ISSUE THREAD

**Issue by zerosheepmoo** [codesandbox/codesandbox-client#3753]
# ❔ Question

I found that recent updates change the url address `*.csb.app` to `*.codesandbox.io`
The web app my team created judges whether it is legal or illegal usage by comparing license with domain. One of the concerns is that unknown preview url address can cause an error when we make the demo via codesandbox platform. Because of that, my team should monitor every single time changes (even though only for demo management).

Thus, I hope there is a way or api to access to the preview address.

**Comment by CompuIves** [comment]
Hey @zerosheepmoo, 

Generally everything is hosted on *.csb.app, however, Google Domains blocked our csb.app domain yesterday without notice. We're talking with them to unblock the domain, and are now falling back to our backup domain. More info on this is here: #3751.

After we've resolved this issue we'll make sure that this can't happen again. So from then on, csb.app will be reliably available.

**Comment by CompuIves** [comment]
I'll close this issue now so we can discuss further on #3751!
