### ISSUE TITLE
Infinite loop protection crashes in web workers

### ISSUE THREAD

**Issue by drcmda** [codesandbox/codesandbox-client#3761]
# 🐛 bug report

Here's the box: https://codesandbox.io/s/r3f-basic-demo-jo738

And that's the piece of code that crashes (we're in a worker):

```jsx
for (var i = 0; i < numValues; i++) {
  if (_loopIt5++ > 10001) {
    global.infiniteLoopError = new RangeError('Potential infinite loop: exceeded '
      + 10001
      + ' iterations. You can disable this check by creating a sandbox.config.json file.');
    throw global.infiniteLoopError;
  }
  array[i] = dracoArray.GetValue(i);
}
```

And the error, `global` to my knowledge doesn't exist in workers:

````
ReferenceError: global is not defined
  at decodeAttribute (87245e34-a5c9-4fe9-8a17-164a49ee3617:319)
````

The bad part is that the error means nothing (to the end-user). It doesn't get to warn us about infinite loops since the warning itself crashes. 

Switching off loop protection makes it work again.

Thanks! :-)

**Comment by CompuIves** [comment]
Good find! Thank you, will update!
