### ISSUE TITLE
A lot of community sandboxes are no longer compiling

### ISSUE THREAD

**Issue by MohammadElbanna** [codesandbox/codesandbox-client#3764]
# 🐛 bug report
Various community sandboxes are no longer working.
Examples:
- https://codesandbox.io/s/list-transitions-ju549
from [react-flip-toolkit](https://github.com/aholachek/react-flip-toolkit) library.
- https://codesandbox.io/embed/r3f-floating-diamonds-prb9t
from [react-three-fiber](https://github.com/react-spring/react-three-fiber) library.

On a side note: The same examples were compiling fine yesterday.
## Description of the problem
When Checking the above example, the following error is returned:
```
TypeError: /node_modules/three/build/three.module.js: 
Property body[0] of BlockStatement expected node to be of a type ["Statement"] 
but instead got undefined
```

## How has this issue affected you? What are you trying to accomplish?
I can no longer compile and run examples and demos for these JS open source libraries:
- [react-flip-toolkit](https://github.com/aholachek/react-flip-toolkit)
- [react-three-fiber](https://github.com/react-spring/react-three-fiber) 

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  `Couldn't manage to get this info`
| Browser          |  Chrome for macOS/ v80.0.3987.149 (Official Build) (64-bit)
| Operating System | macOs Catalina/v10.15.3

**Comment by TechQuery** [comment]
Same error...
https://codesandbox.io/s/webcell-demo-9gyll

**Comment by CompuIves** [comment]
Looking at it now, and working fix!

**Comment by CompuIves** [comment]
Fix should be live in 15 min

**Comment by fletcherist** [comment]
Fast reproduce. 
```
class Foo {
  async bar() {}
}
```
insert it somewhere in your sandbox to get this bug

**Comment by kotarella1110** [comment]
@CompuIves Looks like it has been fixed. Thanks!
