### ISSUE TITLE
Dependency sizes

### ISSUE THREAD

**Issue by mindplay-dk** [codesandbox/codesandbox-client#3772]
# ❔ Question

I just discovered the "sizes" drop-down in the dependencies panel:

![image](https://user-images.githubusercontent.com/103348/77825248-594b3700-7108-11ea-8480-31770d63f462.png)

In this example, `date-fns` is estimated at 17 KB, which is way too high - I'm only importing a single function from a submodule.

On the other hand, sinuous is estimated at 170 bytes, which is way too low - I've imported two submodules, so somewhere between 1.4 and 4.5 KB.

Just wondering, what are these sizes based on?

Maybe it doesn't work for packages with submodules? Those are becoming increasingly common, and people who are mindful of package footprint are likely using submodules to control how much they import and bundle.

I tried bundlephobia, and it also gets the size of these modules wrong - but CS actually has access to information from the build tool, right? So I wonder if it's possible to more accurately measure the net size of contributions from actually imported submodules and summarize by package? I'm pretty sure I've seen some webpack modules that provide more accurate stats?

**Comment by mindplay-dk** [comment]
Looks like this feature is actually just [pulling size information from bundlephobia](https://github.com/codesandbox/codesandbox-client/pull/1197/files#diff-e1b58f7add4b85cdc529e94c2a4af73bR45), so I guess that's why the results are similarly inaccurate. Bundlephobia naturally can't know what you've actually imported from a given package and is probably just basing this on `main` in `package.json` or something. 🤔

**Comment by garethx** [comment]
Yes, that's right it just comes from Bundlephobia

**Comment by mindplay-dk** [comment]
Totally useless and misleading feature, but, whatever. Apparently.
