### ISSUE TITLE
Browser Preview at bottom of screen

### ISSUE THREAD

**Issue by idkjs** [codesandbox/codesandbox-client#3773]
# How does one move the the browser preview to the bottom of the screen

### ScreenShot
This is the effect I am trying to achieve from the @CompuIves Egghead course.

<img width="1280" alt="Screen Shot 2020-03-28 at 10 43 37 AM" src="https://user-images.githubusercontent.com/2370391/77825790-0a8aa680-70e2-11ea-9587-5b943d16bedf.png">

Note the `preview` is under the code.

### Your Environment

```sh
~ ❯❯❯ swvers
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E266
```
I have searched the docs but I might be looking for the wrong key word.

Thank you.

**Comment by CompuIves** [comment]
Hey! You can flip the layout from the command pallette or the menu bar, this way:

![image](https://user-images.githubusercontent.com/587016/77826302-e0031280-710e-11ea-9554-9d608658dd50.png)

Let me know if it works for you!

**Comment by idkjs** [comment]
So `flip layout` is what it is called! That works. Thank you for your prompt response, sir!
