### ISSUE TITLE
Custom Theme not working as in #3139

### ISSUE THREAD

**Issue by Luxcium** [codesandbox/codesandbox-client#3777]
### Description of the problem (similar to #3139)
I can't change the color theme in the preferences also it is said to set as custom but the option is not available in safari (so I am using chrome)...
option available ->
`"workbench.colorTheme": "Custom Theme"`
option required in the documentation ->
`"workbench.colorTheme": "custom",`
### How has this issue affected you? What are you trying to accomplish?

I would like to be able to accomplish something similar to my own user experience on my vs code with my theme I have created [using Pop N' Lock Theme by Luxcium ✨ ](https://marketplace.visualstudio.com/items?itemName=Luxcium.pop-n-lock-theme-vscode )

[<img width="1239" alt="Capture d’écran, le 2020-03-29 à 03 36 35" src="https://user-images.githubusercontent.com/42672814/77843822-ba0d5a80-716e-11ea-8e82-5c4196e35e68.png">](https://marketplace.visualstudio.com/items?itemName=Luxcium.pop-n-lock-theme-vscode )
#### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| **Сodesandbox**      | online version as of As of March 28th 2020, 15:15 EST |
| **Browser**          | Chrome / 80.0.3987.149 (Build officiel) (64 bits) |
|  **Operating System** | macOS Mojave |

[Pastebin of used theme](https://pastebin.com/L9xDFAhd)

[<img width="949" alt="Capture d’écran, le 2020-03-29 à 03 30 49" src="https://user-images.githubusercontent.com/42672814/77843729-0e640a80-716e-11ea-92fb-150c06c1ac26.png">](https://pastebin.com/L9xDFAhd)

might be related (or not) to:
#3357
#3139
#1262
#918

**Comment by Luxcium** [comment]
also not working in other browsers **FireFox Nightly:** `76.0a1 (2020-03-27) (64 bits)`  and/or **FireFox Browser:**  `74.0 (64 bits)`

**Comment by Luxcium** [comment]
and now that I have refreshed properly on **Safari:** `Version 13.1 (14609.1.20.111.8)` it is still not working ... as the others so I assume it is not related to the browser anyway ...

**Comment by CompuIves** [comment]
Fixed with 062f4839a4bddeac585ae6f8589a20a98bd23809!

**Comment by Luxcium** [comment]
Merci! @CompuIves  Is there a way (now or in the near future) to have my theme (or syntax) in the embed ???

**Comment by garethx** [comment]
It's not currently possible, we have a choice between a light and dark theme at the moment. It has been discussed as something we'd like to get to, probably as a pro feature.
