### ISSUE TITLE
Lazy loading (ES) imports in dependencies error due to transpilation to commonJS

### ISSUE THREAD

**Issue by maximilianMairinger** [codesandbox/codesandbox-client#3778]
# 🐛 bug report

## Description of the problem

Some transpilation tool (I assume it is babel) parses all ES imports **in imported modules** to CommonJS by default. This works fine in most cases, except when an imported module is trying to lazy load another one via [`import("mod")`](https://parceljs.org/code_splitting.html). I am not super familiar with babel, thus I dont know how to disable module resolution (in order to let parcel handle it).

## How has this issue affected you? What are you trying to accomplish?

I tried to use a [module](https://github.com/maximilianMairinger/edom) which uses lazy loading imports.

This is the printed warning:

> Error when converting '/node_modules/extended-dom/app/dist/lib/polyfill.js' esmodule to commonjs: this[e.object.type] is not a function

The unexpected token is `import("mod")`

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | @ 29/03/20 |
| Browser          | chrome |
| Operating System | win |

**Comment by CompuIves** [comment]
Hey @maximilianMairinger! If I understand correctly you expect that we only start parsing the import statement once it's called?

**Comment by maximilianMairinger** [comment]
@CompuIves  Im sorry no. As far as I know no browser does natively support basic esImports not to mention lazy-loading (via `import()`) as of now. Bundlers (e.g. parcel / webpack) resolve those by splitting the build into chunks and injecting those via new `<script>` tags into the html once another chunk is lazyly imported (via `import()`) in your code. This process must happen at compile time since the built files cannot be resplit during runtime. But the actual loading & execution of those split files can be decided during runtime. So that one can first check if a polyfill is needed and only then load it (in order to not impact users on modern browsers (already natively supporting the required features)).

Maybe I did not elaborate sufficiently. 

## The issue

I am trying to use a npm [module](https://github.com/maximilianMairinger/edom) which uses (lazy-loading) `import()` statements to load some polyfills as needed. Both [webpack](https://webpack.js.org/guides/code-splitting/) and [parcel](https://parceljs.org/code_splitting.html) support those (as code-splitting). Using the module on local projects (using webpack as bundler and typescript [**without module resolution**](https://github.com/maximilianMairinger/labAuth/blob/79954569176c583d2f88f94eecc8330241b22cd0/tsconfig.json#L4)) works as expected. However in codesandbox importing (not lazy-loading, just importing) the module breaks the build. Here is a [sandbox](https://codesandbox.io/s/smoosh-snowflake-20d6i) displaying the issue.

## My observations

I just spent a good while trying to debug this problem; here is what I found. Please note that I am not familiar with this repository so correct me if I am wrong. 

I assume you are using the transpilers in following sequence in order to build 

 * **Babel**
    Maybe to inject some code and / or minifiy
    *To convert esImportes **in external modules** to commonJS*
 * **Typescript**
    With the option `"module": "commonjs"` 
 * **Parcel as bundler** 

I am not sure why you are converting esModules to commonJS via babel nor why you are only doing so for external modules. The thing confusing me is that lazy-loading imports do work locally (when not in a module but written in the sandbox itself (here an [example sandbox](https://codesandbox.io/s/elated-keller-tkvlb))). Hence, I am wondering if this is even intended behaviour.

I deducted that this might be an issue with babel by viewing the error messages in the (native) console.

![image](https://user-images.githubusercontent.com/42389740/78035964-0a044100-736a-11ea-8b11-4f8d007db6ef.png)

Note how the first waring states that there there was an issue converting esmodules to commonjs (which ofc fails since lazy-loading `import()` statements are not supported in commonJS) and the second one displays that the transpilation of babel (since it is thrown by babel-worker.js) faild at the unexpected token `import()`.

This suggests to me that babel parses all imports *in external modules* to commonjs before parcel can handel those. 

## Suggestion

As stated in my inital comment I am not familiar with babel, thus dont know how to disable the module resolution in babels config. But I think this would fix part of the problem. Parcel does understand commonJS as well as esImports thus there is no benefit in parsing it prior (it just limits what parcel can do, since treeshaking & lazy-loading wont work in commonJS). Setting the module resolution as modern as possible (`"esnext"`) for all transpilation tools prior to parcel will let pacel have the most freedom about how to handel it. Parcels main job is to resolve imports in order to make them work in browsers, hence I am sure the output **will** work regardless if the input is in commonJS or ES.

The option ts option `"module": "commonjs"` might be an issue as well that did not get registerd yet, since babel failed first. Id suggest setting this to `"esnext"` as well.

**Comment by maximilianMairinger** [comment]
@CompuIves  Sorry for the endless comment. I did some more research and turns out, I am kind of an idiot sometimes. There was in fact something wrong with babel, but not the config is malformed, instead `@babel/core` isnt installed at all in the `vanilla-ts` template. Simply adding it to the `devDependencies` solved the issue.

Regardles, the `"module": "commonjs"` option (in tsconfig) is still an issue as all lazy-loaded imports get just thrown together into one bundle. This is because typescript parses all modules to commonjs, which does not support lazy-loading (nor tree-shaking), before parcel can resolve them properly.

I would be interested in make myself familiar with the project in the following days and fixing this myself if you dont mind.
