### ISSUE TITLE
Can't make a template a normal sandbox.

### ISSUE THREAD

**Issue by turnipjs** [codesandbox/codesandbox-client#3779]
Once I make a sandbox into a template, I can't make it a normal sandbox again.

When I try to do this, dialogue pops up that says this:  
"Network Error: ServerParseError: Unexpected end of JSON input"

Probably related to #3026.

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | ??? 2019-03-29
| Browser          | Chrome 80.0.3987.132
| Operating System | macOS Catalina

**Comment by garethx** [comment]
To add some additional detail - this issue occurs when on the dashboard and using the right-click menu and selecting 'Convert to Sandbox'. You can still remove the template without error in the editor.

**Comment by CompuIves** [comment]
Hey! Thanks for bringing up this issue, it has now been fixed!
