### ISSUE TITLE
Could not find module in path

### ISSUE THREAD

**Issue by diegohaz** [codesandbox/codesandbox-client#3782]
# 🐛 bug report

## Description of the problem

I'm trying to create a CodeSandbox with two dependencies: A and B, where B is also a dependency on A, but with a different version.

It works locally on a fresh create-react-app install. But on CodeSandbox it's throwing this error:

```
ModuleNotFoundError
Could not find module in path: 'reakit/1.0.0-beta.16/Toolbar' relative to '/node_modules/@wordpress/components/build/toolbar-item/index.js'
```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest?
| Browser          | Chrome 80
| Operating System | MacOS 10.15.3

**Comment by CompuIves** [comment]
Thanks for the clear description on the dependency graph! Definitely a problem on our side, will take a look.
