### ISSUE TITLE
Cannot save files without logging in the github

### ISSUE THREAD

**Issue by ElaineRosenberg** [codesandbox/codesandbox-client#3788]
# 🐛 bug report

## Description of the problem
Previously when using our code-sandbox, we were able to have users access the sandbox and when they saved anything in the sandbox, it would automatically fork the sandbox and all would be fine. They did not need to log in.

Now, in order to edit a file in a sandbox, users must sign in, and then explicitly fork the sandbox before they can make edits to files in the sandbox.

This behavior has changed recently and we are getting questions from our users attempting to use the sandbox.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/github/neo4j-contrib/training-v2/tree/master/Courses/AppliedGraphAlgorithms/react-app

### Your Environment

OS X
| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by CompuIves** [comment]
Hey @ElaineRosenberg! This is definitely a bug, I'll try to repro the problem now.

**Comment by CompuIves** [comment]
Okay, found the issue on this. It is fixed now! Sorry for the inconvenience.
