### ISSUE TITLE
Poor text contrast in the "Add dependencies" modal when using light themes

### ISSUE THREAD

**Issue by hexrcs** [codesandbox/codesandbox-client#3796]
# 🐛 bug report

## Description of the problem

The text is in white inside the "Add dependencies" modal when a light theme is used, as shown below.

![image](https://user-images.githubusercontent.com/26751752/77989440-1a42fe80-731f-11ea-9ca2-d67cab6609c8.png)

## How has this issue affected you? What are you trying to accomplish?

I use light themes during the daytime, and it's difficult to read any text when I'm trying to add dependencies to my sandbox due to the poor contrast.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest (not sure where to check)
| Browser          | Chrome/80.0.3987.149
| Operating System | macOS 10.14.6

**Comment by CompuIves** [comment]
Heyo! This is definitely a bug, thanks for letting us know!
