### ISSUE TITLE
CSS and Javascript files not linking it HTML file

### ISSUE THREAD

**Issue by mike-lloyd03** [codesandbox/codesandbox-client#3806]
# 🐛 bug report

## Description of the problem
Upon import of a Github repo, my HTML is rendering to the page with no CSS or Javascript being imported. These files work fine when editing locally in VS Code but I'm having no luck when using codeSandbox.

CSS is linked in HTML:
`<link rel="stylesheet" type="text/css" href="./stylesheet.css">`

JS is imported as a module in HTML:
`<script src="./index.js" type="module"></script>`

Link to to sandbox:
[https://codesandbox.io/s/serene-mclean-t92mf](https://codesandbox.io/s/serene-mclean-t92mf)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome 80.0.3987.149
| Operating System | Windows 10 64 bit

**Comment by garethx** [comment]
Your imported project is defaulting to using the create-react-app environment, whereas you don't seem to be using React despite including it in package.json. Adding a config file to force the use of the vanilla (Parcel) template, will help to fix this up e.g. https://codesandbox.io/s/white-browser-wh6i0

See more info on config files here: https://codesandbox.io/docs/configuration

**Comment by mike-lloyd03** [comment]
Cool thank you!
