### ISSUE TITLE
Sandbox breaks completly

### ISSUE THREAD

**Issue by davidbernegger** [codesandbox/codesandbox-client#3807]
# 🐛 bug report

## Description of the problem

- Does not load sandbox and gets following error
![image](https://user-images.githubusercontent.com/16232537/78072011-aea07600-739e-11ea-86e1-c463ce1f8885.png)

## How has this issue affected you? What are you trying to accomplish?

- wanted to access sandbox > can't

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | https://codesandbox.io/s/design-system-vf77t |
| Browser:  | Chrome Version 83.0.4093.3 |
| Operating System:  | Windows 10 |

**Comment by CompuIves** [comment]
Hey! The error that you're seeing is from the `index.js` of the sandbox on line 31. It seems like the error originates from user code in this case.

**Comment by davidbernegger** [comment]
Yeah I guess so but I can't even access the sandbox to change the code as it won't load as it gets stuck and freezes (Chrome Dev Version 83.0.4093.3, incognito with no extensions and no active flags - maybe it's possible that it's on my side though if it loads for you.): 
![image](https://user-images.githubusercontent.com/16232537/78120113-b5180780-7409-11ea-9bb5-abdca43ed6a7.png)

**Comment by garethx** [comment]
@davidbernegger Add `runonclick=1` to the editor url to stop the preview from loading and preventing infinite loop e.g. https://codesandbox.io/s/design-system-vf77t?runonclick=1

**Comment by davidbernegger** [comment]
Ahh, didn't knew about this option! If that is common knowledge and the usual way to stop infinite loops in codesandbox then i'm gonna close this now! Thank you for being patient, taking time and helping, really appreciate it!
