### ISSUE TITLE
CodeSandbox embed throws forbidden errors before loading.

### ISSUE THREAD

**Issue by gandhimonik** [codesandbox/codesandbox-client#3811]
# 🐛 bug report

## Description of the problem

While loading CodeSandbox in embed mode, the editor takes forever to run successfully. It keeps making calls to the below given service and keeps getting 403 forbidden error until after a while it succeeds.

https://prod-packager-packages.codesandbox.io/v1/combinations/apollo-boost@0.4.7%2Bbabel-runtime@6.26.0%2Bcsbbust@1.0.0%2Bgraphql@0.11.7.json

![image](https://user-images.githubusercontent.com/17691756/78087489-21e1c200-7376-11ea-9099-82c2381d6d0c.png)

On checking the Network tab, I found that the service call throws 'Access Denied' error.

![image](https://user-images.githubusercontent.com/17691756/78087559-489ff880-7376-11ea-997c-4834bbde54a5.png)

I use official Vanilla JS template to load all the sandboxes. After a while the editor loads successfully but it takes almost a min to complete loading. This only happens the first time, if I reload the page, it loads instantly.

## How has this issue affected you? What are you trying to accomplish?
This issue is causing latency in my application. I'm trying to embed sandbox editor in my application. I'm using CodeSandbox API to load dynamic code in the editor.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | https://codesandbox.io/s/tender-violet-6xxnu?from-embed
| Browser          | Chrome
| Operating System | MacOS Catalina

**Comment by garethx** [comment]
Is this still a problem for you? I'm not able to reproduce

**Comment by gandhimonik** [comment]
Yes it is and it happens only the first time. If I try the same Codesandbox again, I believe due to some kind of caching it doesn't throw any error.

**Comment by garethx** [comment]
I still haven't been able to reproduce this, unfortunately, even when loading the first time it's taking 5-6 seconds with no errors. Does the same occur in an incognito window for you? Which specific version of Chrome are you using? Thanks.

**Comment by gandhimonik** [comment]
My Chrome version is **Version 80.0.3987.149**.  I tried it with Incognito mode and still the same problem. Here's my link. 

https://libstack.dev/

I'm building an app to search Node.js packages. You can search for any package with more than 1000 Github stars. I got the same problem for **vue-carousel** but now if you try it, you won't get it as its cached so try a different package.

https://libstack.dev/#/search?query=vue

**Comment by garethx** [comment]
ah ok, I can see the problem when embedded in your site. I'll flag to the team and see if we need any additional info to resolve. Thanks.

**Comment by gandhimonik** [comment]
Thanks @garethx , appreciate the help.
