### ISSUE TITLE
Can't turn off mini map

### ISSUE THREAD

**Issue by moritzWa** [codesandbox/codesandbox-client#3814]
# 🐛 bug report

## Description of the problem

When trying to toggle mini map in the ui setting of vscode i get this error: 

<img width="885" alt="Screenshot 2020-04-01 at 15 53 48" src="https://user-images.githubusercontent.com/42035131/78145292-fbcd2800-7430-11ea-90c4-2bb67b879247.png">

After going into the vscode settings ui nothing changes.

## How has this issue affected you? What are you trying to accomplish?
I have multiple windows with only little code in so I don't need the mini map.
It's not a big issue because after re-opening the sandbox all settings kicked in and the minimap is gone.

### My Sandbox:
https://codesandbox.io/s/exit-intent-popup-2zfuk

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  
| Browser          | Chrome Version 80.0.3987.149 (Official Build) (64-bit)
| Operating System | macOS

**Comment by CompuIves** [comment]
Heyo! Can you try this again? I think I deployed a fix for this around ~30 minutes, but I'm not sure if it has propagated.

**Comment by moritzWa** [comment]
Heyo! Yup, have tested a few combinations of toggling in the UI and via the codesandbox UI and vscod settings UI. Everything work fine.
