### ISSUE TITLE
Github Repo Creation Error

### ISSUE THREAD

**Issue by ttseng** [codesandbox/codesandbox-client#3820]
# 🐛 bug report

## Description of the problem
I am trying to sync my private sandbox with a private Github repo.  This is actually the reason I purchased a Pro membership, but it is not working as expected.

This is what I tried:
1. I had previously tried to connect it with a public repo.  I made the repo private on Github and then tried to connect to the codesandbox to it.  The UI in codesandbox only has the option to create a new repo.  I try entering the name of the existing private Github repo into the UI, but it hangs in creating the repo and never completes.

2. I deleted the existing Github repo to try to create the repo from scratch in Codesandbox.  When it finishes creating the repo in codesandbox, it restarts the container and the Github icon disappears.  When I reload the editor, the Github repo reappears but the app does not seem to know it's connected to a repo already.  See video here: https://youtu.be/VfQ5M_t7DuE

## How has this issue affected you? What are you trying to accomplish?
This is the first step I need to set up a proper git workflow with my collaborators.  Without it, I'm unable to proceed.  This is also the reason I purchased Pro membership (to sync a private sandbox with a private Github repo).

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/canvas-to-svg-7b82x

### Your Environment
I'm using Codesandbox in Chrome 80.0.3987.149 on a Mac

**Comment by garethx** [comment]
Thanks for the report, Tiff.

1 wouldn't work, at least you can't enter the name of an existing repo in the create repo box. However, we should produce an error rather than silently failing. 

I've been able to reproduce the issue in 2 and we have a fix about to deploy for that.

**Comment by fletcherist** [comment]
@ttseng +1 same thing, exactly same steps

**Comment by garethx** [comment]
This should now be resolved - let us know if you still experience issues.

**Comment by KarnTech** [comment]
This is still not working as of today. I tried to create a github repo and it failed.

**Comment by garethx** [comment]
@KarnTech Did you get an error message? Check the repo you're creating doesn't already exist with the same name.

**Comment by annycarolinne** [comment]
A mensagem de erro:

![image](https://user-images.githubusercontent.com/28895872/105522349-e412a900-5cbb-11eb-835b-557fa860c25a.png)

Ainda está ocorrendo o problema
