### ISSUE TITLE
CodeSandbox Auto Close Tags

### ISSUE THREAD

**Issue by awesomeness0133** [codesandbox/codesandbox-client#3823]
When I Was Writing Code On Codesandbox I changed the settings so that whenever I made an opening tag a closing tag would pop up as it does in all HTML editors. After Changing the setting 5 times the settings still wouldn't work I I would have to make a closing tag myself. Please help!

**Comment by AbagayleShane** [comment]
Were you able to figure out this problem? I'm having the same problem.

**Comment by chenxizhang** [comment]
same issue here. every time I reopen the sandbox, the settings lost
