### ISSUE TITLE
Accessibility: Almost invisible line number color

### ISSUE THREAD

**Issue by karlhorky** [codesandbox/codesandbox-client#3824]
# 🐛 bug report

## Description of the problem

The default `workbench.colorTheme` of `CodeSandbox Black` has almost invisible line numbers. They are almost invisible, even without any eyesight issues:

<img src=https://user-images.githubusercontent.com/1935696/78273896-b6cbf300-750f-11ea-859d-16a1205d3d2e.png width=153>

I would suggest changing the line number color settings below, so that they are more visible like in the following screenshot:

<img src=https://user-images.githubusercontent.com/1935696/78273984-d6631b80-750f-11ea-8d85-7c37d430359b.png width=153>

### Recommended Settings

These colors have been selected based on muted versions of the existing colors in the interface (feel free to use the existing `#999999` and `#e6e6e6` though):

```js
  "workbench.colorCustomizations": {
    "editorLineNumber.foreground": "#888888",
    "editorLineNumber.activeForeground": "#cccccc"
  },
```

## How has this issue affected you? What are you trying to accomplish?

I cannot see the line numbers.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by karlhorky** [comment]
## Workaround

The VS Code line number color settings mentioned in [this Super User answer](https://superuser.com/questions/1166483/vscode-change-linenumber-color#comment2335694_1205455) work in CodeSandbox as well.

Apply them like this:

1. Open your Command Palette with <kbd>cmd / ctrl</kbd> + <kbd>shift</kbd> + <kbd>P</kbd>, type in `Open Settings`, and select `Open Settings (JSON)`.
2. Find the `workbench.colorCustomizations` object, if there is one, and add (or modify) the values to those in the code below.
3. Save the settings file and refresh the browser.

```json
  "workbench.colorCustomizations": {
    "editorLineNumber.foreground": "#888888",
    "editorLineNumber.activeForeground": "#cccccc"
  },
```

**Comment by CompuIves** [comment]
Yes, I would agree with this change. What do you think? @DannyRuchtie @siddharthkp?

**Comment by siddharthkp** [comment]
I agree we need to change them, would pick something from our design language 👍

**Comment by karlhorky** [comment]
Thanks @siddharthkp and @DannyRuchtie !
