### ISSUE TITLE
create-react-app: Import SVG paths with default import

### ISSUE THREAD

**Issue by karlhorky** [codesandbox/codesandbox-client#3825]
# 🐛 bug report

## Description of the problem

In `create-react-app` I would like to be able to import SVG image paths using the syntax below:

```js
import img from './img.svg'
```

This works in a normal `create-react-app` application.

In CodeSandbox it results in a broken image:

![Screen Shot 2020-04-02 at 17 58 25](https://user-images.githubusercontent.com/1935696/78275870-8043a780-7512-11ea-886f-cd4857af82be.png)

### Alternatives I've Tried

I know that there is the `ReactComponent` named export from SVGs, which is great!

```js
import { ReactComponent } from "./resources/calendar.svg";
```

But sometimes I want to import the paths to the SVGs instead.

## How has this issue affected you? What are you trying to accomplish?

I would like to use SVGs with the paths instead of the ReactComponent.

Importing images from 

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by karlhorky** [comment]
not stale

**Comment by SaraVieira** [comment]
Your sandbox is working tho

https://codesandbox.io/s/small-framework-sjkrq
