### ISSUE TITLE
React Router Bootstrap showing 404 error after Refreshing when gone to routed page

### ISSUE THREAD

**Issue by Karthi0505** [codesandbox/codesandbox-client#3826]
# ❔ Question

### Link to sandbox: [https://codesandbox.io/s/upbeat-hypatia-3pre9]
https://codesandbox.io/live/BBrB4Q

### React Bootstrap 

| react | react-bootstrap/^1.0.0-beta.16|
| ---------------- | ------------ |
| qconstruct.in      |
| Chrome          |
| Windows 10|

**Comment by CompuIves** [comment]
Heyo! Do you still get this? I can't seem to repro. I'm going to a link in the menu, then press refresh on the in-browser preview, everything seems to work.

**Comment by SaraVieira** [comment]
The sandbox has also been deleted :/

Gonna close with lçack of response and also being unable to reproduce
