### ISSUE TITLE
Image URLs in require don't work

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#3845]
# 🐛 bug report

## Description of the problem
If you `require` an image, loading it from a dependency doesn't seem to work well... We should in that case open a URL from a CDN.

e.g.
```require('leaflet/dist/images/marker-icon-2x.png')```

results in: ```<img src="�PNG IHDR))i�}1IDATx�҅��@�
3��33�
s�Ҕ������p�T۝~��N��ܐ7d������~��_������&quot;cP\�	
�W��Aq�4�^	�W�$Aq�C�Q�_�R�Cfd7&amp;�d՚�H͞_i�8�H�n���I���0bG�i(#T!�F1�	2�o�D$G��)��ɸ��*���	/��etԀZ�P��Hu����r�e��Q��-��ʘ&quot;��~���aK,�Y��vG%�����Q������t���+˜Sd+^�Q��/0&amp;�����MM�<�8�����k̸��$��M
��c�.� u$G��:I�q�}��i�D\ȷ�Dt�~�@���jKe��W�zRB�p�8�|�\Ŕ�$�zR��%)�C9���fR(E�W@���],WK!����~�Rt��r�H�A˄���P�À�a{�Ad$ٱ�+(R�g��Z��dG&quot; \��4��b�'|�|&amp;y$�):0&quot;�q!�P�;>��彁_ِ3����L5N��=�S� ����@`D�
�h���c�Ƨ��ġaM^�q�����#�R�t�_�3�8�@bIEND�B`�" class="leaflet-marker-shadow leaflet-zoom-animated" alt="" style="margin-left: -12px; margin-top: -41px; width: 41px; height: 41px; transform: translate3d(640px, 749px, 0px);">```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest
| Browser          | Chrome
| Operating System | Mac OS X

**Comment by colbyfayock** [comment]
thanks for this report 😃 any idea on if this would be something that would be expected to get fixed sooner or later? just wondering if I need to pivot in the short term
