### ISSUE TITLE
A sandbox error occurred, you can refresh the page to restart the container.

### ISSUE THREAD

**Issue by afrazchelsea** [codesandbox/codesandbox-client#3848]
# 🐛 bug report

## Description of the problem

"A sandbox error occurred, you can refresh the page to restart the container."

I've been getting this error. I'm use Netlify to deploy my site. The site gets deployed properly. But the browser in the sandbox doesn't work.

## How has this issue affected you? What are you trying to accomplish?

Sandbox browser doesn't work. Always gives the above error.

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/afraz-gatsby-blog-sktil

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome |
| Operating System | Windows |

**Comment by garethx** [comment]
We're taking a look into this - the sandbox works fine when forked, so do that if this is a blocker in the meantime.

**Comment by garethx** [comment]
Back working - sorry for the hassle.

**Comment by afrazchelsea** [comment]
Thank you mate. Appreciate it :)
