### ISSUE TITLE
Tests failed on codesandbox  but work fine locally

### ISSUE THREAD

**Issue by lednhatkhanh** [codesandbox/codesandbox-client#3849]
# 🐛 bug report

## Description of the problem

Tests pass locally but fail on codesandbox

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Online
| Browser          | Chrome 80
| Operating System | MacOS

**Comment by lednhatkhanh** [comment]
So basically codesandbox doesn't run my test command at all thus doesn't pick up the `setupTests.js` file

**Comment by garethx** [comment]
Your issue isn't clear - are the tests failing or not running? Assuming the same issue as https://spectrum.chat/codesandbox/help/codesandbox-doesnt-pick-up-custom-test-command~2ef86580-76b6-4207-a4b5-09cde288343em, then for performance reasons we ignore any specified scripts in client sandboxes, instead using a default script. If you need to control the scripts, then we recommend using a container sandbox.
