### ISSUE TITLE
Can't import .mjs files of dependency

### ISSUE THREAD

**Issue by Kauto** [codesandbox/codesandbox-client#3854]
# 🐛 bug report

## Description of the problem
I want to import a mjs-file of my dependency. It seems as it is handeled as a text-file.

### Link to sandbox: [link](https://codesandbox.io/s/funny-williams-fhgx6?file=/src/index.js)
(remove line 9 and remove comment from line 4 to test)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Parcel
| Browser          | Firefox/Chrome
| Operating System | Windows/MacOS

**Comment by garethx** [comment]
Where's the mjs file you're trying to import?

**Comment by Kauto** [comment]
It's commented out in line 4.
```
import Scene from "animationvideo/Scene.mjs";
```
