### ISSUE TITLE
Support keyboard shortcut changes going into effect without refreshing

### ISSUE THREAD

**Issue by lirbank** [codesandbox/codesandbox-client#3863]
# 🌈 Feature

It seems you can't change keyboard shortcuts, it would be awesome to be able to do some user defined mappings. 

*Use case:*

I'm on a Swedish Magic keyboard and in VSCode you `Toggle Line Comment` with `shift+cmd+7` instead of `cmd+/` (slash is in `shift+7` on a Swedish keyboard).

VSCode seems to pick up that I'm on a Swedish keyboard and have set the shortcut correctly by default:

![image](https://user-images.githubusercontent.com/2538130/78842965-5547d080-79b6-11ea-8b20-dd25ef374fb2.png)

In CodeSandbox it is set to the english default:

![image](https://user-images.githubusercontent.com/2538130/78843002-6bee2780-79b6-11ea-8b9d-ac3a2a913623.png)

*Proposed solution:*

I understand shortcuts, keyboards, browser, etc is a jungle, so I figured the flexible solution would be to allow the user to change keyboard shortcuts, but it doesn't seem to work. I manage to change the shortcut, but when I hit enter it just resets back to `Default`. Unless I'm missing something?

`Toggle Line Comment` is really an important shortcut that I guess is among one of the most used ones for any programmer so would be really cool to find a solution to how to use it, even with a Swedish keyboard.

Alternatively this issue could be a bug issue with the request to handle Swedish keyboards correctly.

**Comment by lirbank** [comment]
So, now I'm really confused. I just noticed that cmd+shift+7 creates a block comment all of a sudden (think I restarted the CodeSandbox PWA). So I went and checked the keyboard shortcuts and now cmd+shift+7 is configured for two different commands, and as user defined config too:

![image](https://user-images.githubusercontent.com/2538130/78861190-0c5d3f80-79e9-11ea-958e-8cc169f55326.png)

![image](https://user-images.githubusercontent.com/2538130/78861207-18e19800-79e9-11ea-9195-cbf80bc80a49.png)

These were not there before... so no I just want to remove the binding for Toggle Block Comment, but nothing happens...

There is something I'm missing here...

**Comment by lirbank** [comment]
Oh! 1) Change the keybinding, 2) restart the CodeSandbox PWA, 3) profit!

**Comment by garethx** [comment]
Glad you got it sorted!

**Comment by lirbank** [comment]
@garethx - thanks! 

I don't think this should be closed though, but either renamed or split into two issues: 

1) "Support Swedish default keyboard shortcuts" (I can live without this)
2) "Keyboard shortcuts does not go into effect without restarting the app" (this seems important to me)

/M

**Comment by EloB** [comment]
@lirbank That second bulletpoint +1

**Comment by YoungElPaso** [comment]
Agreed. There should at least be a warning.
