### ISSUE TITLE
blog article shows in the browser even when I deleted it from the source files

### ISSUE THREAD

**Issue by afrazchelsea** [codesandbox/codesandbox-client#3864]
# 🐛 bug report

## Description of the problem
blog article shows in the browser even when I deleted it from the source files

## How has this issue affected you? What are you trying to accomplish?
A blog article that I intended to write initially still exists in the CodeSandbox browser. I decided to no longer work on it and have deleted the folder which had its markdown file. The article persists even after deleting it. I have also tried adding a new folder, nothing works

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/afraz-gatsby-blog-sktil?file=/src/pages/index.js

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome |
| Operating System | Windows |

**Comment by MichaelDeBoey** [comment]
I've been getting this one myself too

**Comment by afrazchelsea** [comment]
Solved it. Re-create the folder with the same name as before. Then delete it. Worked for me.
