### ISSUE TITLE
HTTP 422 Can't create a new fork, unusable.

### ISSUE THREAD

**Issue by cluelessperson** [codesandbox/codesandbox-client#3870]
# 🐛 bug report

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | current
| Browser          | chrome current

![image](https://user-images.githubusercontent.com/5635253/78910575-08a5d900-7a3a-11ea-88c9-d7f09e6378e9.png)

**Comment by CompuIves** [comment]
Hey! Thanks for letting us know, I've fixed this now by showing the right error instead. It's being deployed now!
