### ISSUE TITLE
in live session can not switch to "Everyone can edit"

### ISSUE THREAD

**Issue by zba** [codesandbox/codesandbox-client#3874]
# 🐛 bug report

## Description of the problem
When creating live session in created with "Classroom mode", so the only option to change it, it is to select "Everyone can edit", but this not works, if you open same livesession, you will see it still have "Class mode"

## How has this issue affected you? What are you trying to accomplish?

I tried to host  interview with live session

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox     | latest ? (not found version on website) 
| Browser      | Chromium 81.0.4044.92   
| Operating System | linux

**Comment by CompuIves** [comment]
Hey! Thanks for letting us know, I fixed this with the latest commit and it should work as expected now!
