### ISSUE TITLE
Invalid Dependency Versions

### ISSUE THREAD

**Issue by jyash97** [codesandbox/codesandbox-client#3876]
# 🐛 bug report

## Description of the problem
Add `prsimjs` as dependency and in the version selection we can see there are `2` versions which points `9000.0.1` & `9000.0.2`

Screenshot: 
![image](https://user-images.githubusercontent.com/22376783/79008199-7822e200-7b7a-11ea-8347-a8001e779f31.png)

Selecting those dependency breaks the preview. Screenshot: 
![image](https://user-images.githubusercontent.com/22376783/79008240-8a9d1b80-7b7a-11ea-9b8b-33504d146ec2.png)

## How has this issue affected you? What are you trying to accomplish?
Hasn't affected in a major way but had to confirm this on `npm` if those versions were present.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  Not able to find the hash at the bottom |
| Browser          | Chrome 80.0.3987.163
| Operating System | Mac OS |

Let me know if I can help with this issue, but this seems to be a Backend Issue.

**Comment by jyash97** [comment]
cc @garethx can you confirm if this is a known issue?

**Comment by MichaelDeBoey** [comment]
This looks to be a bug indeed
https://www.npmjs.com/package/prismjs

**Comment by SaraVieira** [comment]
After looking at this, it seems to be a bug with algolia weirdly enough

We get these values from an algolia search of npm and its returning this data wrong :(

**Comment by SaraVieira** [comment]
Confirmed its a bug in the algolia replication tool, will filter on our end until issue is fixed

**Comment by Haroenv** [comment]
Those versions were deleted, but that wasn't being recognised by our indexer. It has now been fixed :)

**Comment by SaraVieira** [comment]
Thank you so much for your help in fixing this 🌈
