### ISSUE TITLE
Content Overflow in vscode hint 

### ISSUE THREAD

**Issue by jyash97** [codesandbox/codesandbox-client#3882]
# 🐛 bug report

## Description of the problem
Content overflow in hints. 

Screenshot: 
![image](https://user-images.githubusercontent.com/22376783/79071696-bba45a00-7cfa-11ea-9470-cc83ac381301.png)

## How has this issue affected you? What are you trying to accomplish?
Difficult to read the hint properly.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | |
| Browser          | Chrome v80 |
| Operating System | Mac OS Catalina |

@CompuIves  I could not find the file where we add the custom CSS for VS Code, though I can confirm if we add `overflow-y: scroll`. This works properly. 

I am open to creating a PR if I can get some pointer on how to add the styles for VS specific elements.

**Comment by CompuIves** [comment]
Oh yes! I'd love to have a fix for this!! I think the css needs to be added to this file: `packages/app/src/app/components/CodeEditor/VSCode/workbench-theme.css`.

**Comment by jyash97** [comment]
Just confirming isn't this file for monaco-editor styles?

**Comment by CompuIves** [comment]
We also use it for vscode styling, it's called this way because vscode uses monaco as their core editor 😁
