### ISSUE TITLE
Cannot find module when imported with absolute-path and baseUrl defined

### ISSUE THREAD

**Issue by tjlav5** [codesandbox/codesandbox-client#3884]
# 🐛 bug report

## Description of the problem
While I can properly import modules relative to the root of my project as evidenced by the project building, intellisense fails as evidenced by a "cannot find module"-error message.

![image](https://user-images.githubusercontent.com/1452216/79091952-4b5b0000-7d1d-11ea-8c03-e333dfc1d54f.png)

## How has this issue affected you? What are you trying to accomplish?
I'm trying to not import modules with too-many relative jumps e.g.

```
/** file: /src/components/foo/bar/baz/index.ts */
import {utilFn} from "../../../../utils
```

instead, I want to import from my project-root

`import {utilFn} from "/utils`

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1586703599-a607be77e
| Browser          | Chrome 80.0.3987.162
| Operating System | Chrome OS

**Comment by CompuIves** [comment]
Hey!  I found that after changing the `tsconfig.json` to add the paths it started to work, example here: https://codesandbox.io/s/suspicious-tree-bdnjg?file=/tsconfig.json:89-206.

Let me know if this answers the question, if it's the case I'll close it!

**Comment by tjlav5** [comment]
That totally worked. Sorry for the false alarm, I thought I had tried that - different permutation I guess. Thanks for the quick feedback and love CSB!

**Comment by deadcoder0904** [comment]
Hey @CompuIves, am I doing it right?

It works locally.

# App.tsx

```tsx
import { Konva } from '@/components/index'
```

# tsconfig.json

```json
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@/*": [
                "src/*"
            ]
        },
    }
}
```

I also tried:

```json
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@/*": [
                "./src/*"
            ]
        },
    }
}
```

And this is how Next.js does it:

```json
{
    "compilerOptions": {
        "baseUrl": "node_modules",
        "paths": {
            "@/*": [
                "../src/*"
            ]
        },
    }
}
```

But alas, nothing worked 🤷‍♂️
