### ISSUE TITLE
Bug in a requestAnimationFrame auto-running in preview will cause browser to hang; no protection from infinite loops

### ISSUE THREAD

**Issue by LimeWub** [codesandbox/codesandbox-client#3899]
# 🐛 bug report

## Description of the problem
If there is a bug in the code in a fast repeating loop like a `requestAnimationFrame` there is 0 protection from CodeSandbox's preview.
There is no way to start a sandbox without javascript running in the preview (CodePen has a flag for that for example) or request preview always closed AFAIK.
When the borked sandbox loads the browser immediately hangs and there is no way to access the code to amend the problem. 
Been trying to clutch close the preview for the past half hour at least to rescue the code to no avail, the code is basically trapped in a faulty sandbox.

## How has this issue affected you? What are you trying to accomplish?
Was working exclusively on CodeSandbox - now I can't access ANY of the code as the browser hangs before I can close the preview.
I am trying to access my code to resolve the bug or just get it into GitHub or something. Basically want to get to my code.

If only there was a way to stop the preview onLoad or run with blocked JS in the preview this would be kind of fixed; Please help :)

Edit: THANKFULLY I can at least "export" the sandbox so can probably fix the code locally and reupload. But still...

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest
| Browser          | Chrome Version 80.0.3987.163 (Official Build) (64-bit)
| Operating System | MacOs Catalina

**Comment by garethx** [comment]
You can add runonclick=1 to the editor URL to stop the preview auto-loading e.g https://codesandbox.io/s/new?runonclick=1
