### ISSUE TITLE
App URL suffix has changed from `.csb.app` to `.codesandbox.io`

### ISSUE THREAD

**Issue by ShahAnuj2610** [codesandbox/codesandbox-client#3902]
# 🐛 bug report

## Description of the problem

All csb examples app URL has changed from `.csb.app` to `.codesandbox.io`

## How has this issue affected you? What are you trying to accomplish?

Wherever the app is used as demo, it says the site can't be reached

### Link to sandbox: [link](https://codesandbox.io/s/hopeful-river-pbd0x?from-embed=&file=/src/index.js) (optional)

URL has changed from **https://pbd0x.csb.app/** -> **https://pbd0x.codesandbox.io/**

**Comment by oskarabc** [comment]
This is temporary due to domain suspension. Routing this discussion to issue [3751](https://github.com/codesandbox/codesandbox-client/issues/3751)
