### ISSUE TITLE
Allow for using workspace TypeScript version

### ISSUE THREAD

**Issue by CompuIves** [codesandbox/codesandbox-client#3904]
# 🌈 Feature

Allow for using the TypeScript version of the project itself inside VSCode. 
![image](https://user-images.githubusercontent.com/587016/79314575-1fe53a80-7f02-11ea-85a6-29ce623c3e38.png)

To make this work we need to write TypeScript to `node_modules` of the project. We can do this by running:
```js
const fs = BrowserFS.BFSRequire('fs');

// ... Now write all files of TS to the folder, we should probably fetch them from a tar from npm registry or from unpkg.com
fs.writeFileSync('/sandbox/node_modules/typescript');
// And repeat...
```

We could implement this maybe within our sandbox fs syncer: https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/app/overmind/effects/vscode/SandboxFsSync/index.ts#L1

**Comment by diegohaz** [comment]
That would be nice! I just tried adding a `.vscode/settings.json` with `typescript.tsdk` pointing to `node_modules/typescript/lib` for TypeScript 4.0, but it's not working. Looks like it doesn't find the `tsserver.js` file.

**Comment by SaraVieira** [comment]
Hey!

We are keeping track of all our features in a backlog in notion so I am gonna move this over there.

It gets more visibility to us there
