### ISSUE TITLE
File upload is broken

### ISSUE THREAD

**Issue by iongion** [codesandbox/codesandbox-client#3905]
# 🐛 bug report

## Description of the problem

Cannot upload any file. Storage is clean, no files exist.

## How has this issue affected you? What are you trying to accomplish?

Use a static file inside the app

### Your Environment

![image](https://user-images.githubusercontent.com/867609/79327026-11a01a00-7f14-11ea-9034-162d44c54e02.png)

**Comment by SaraVieira** [comment]
Hey!

Do you have any idea how big the file is?

**Comment by iongion** [comment]
These are the files

**Comment by iongion** [comment]
[grapher.zip](https://github.com/codesandbox/codesandbox-client/files/4480630/grapher.zip)

**Comment by iongion** [comment]
mpeg-ts files, they do have ts extension and might confuse as typescript

**Comment by SaraVieira** [comment]
Hey!

Yeah that is what is up, it thinks you are uploading a TS file and it bugs out :/

Imma ping @CompuIves since this is a backend issue

**Comment by CompuIves** [comment]
Ah yes, we should upload the file instead. We need to change the client to detect it's not a text file but a binary file instead. This is the error: `ERROR 22021 (character_not_in_repertoire) invalid byte sequence for encoding "UTF8": 0x00`, so we might be able to just add a check for a null byte here: https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/app/overmind/namespaces/files/internalActions.ts#L90-L107. Or we should find another way to detect whether it's text.

**Comment by CompuIves** [comment]
Yep, I think that's it. We should check whether there is a null byte in the contents, if that's the case we should upload instead of create. Or, alternative is that we use this to check: https://unpkg.com/istextorbinary/.

For now you can rename the file to .mp4 for example, and then rename back to .ts once uploaded.

**Comment by CompuIves** [comment]
Just saw that `istetorbinary` also checks for the extension first, so we should probably check for a null byte in the buffer instead.
