### ISSUE TITLE
"Go Live" button causes the file to reset back to previous save.

### ISSUE THREAD

**Issue by anuraghazra** [codesandbox/codesandbox-client#3909]
# 🐛 bug report

## Description of the problem
On a new sandbox when i create a new file and save it with some content and then "Stop session" and again start writing some content in that file and save it and then press "Go live" button the file resets back to the previous save.

**Youtube Video Link: https://youtu.be/XHArTmDnQt8**

Steps to reproduce:
1. Create new sandbox
2. Create new file and write some stuff and save it.
3. Stop live session
4. write some more stuff in that file and save it.
5. press "Go live" button

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1586961769-06082c941
| Browser          | Chrome Version 79.0.3945.130 (Official Build) (64-bit)
| Operating System | Windows 7 64bit

**Comment by siddharthkp** [comment]
Tracked as CSB-48 😄

**Comment by andrasbacsai** [comment]
I cannot reproduce it, so I'm closing this issue. Please reopen if you have any questions.
