### ISSUE TITLE
Taking very long to fetch changes, so it can commit to github

### ISSUE THREAD

**Issue by inderjeetbhagat** [codesandbox/codesandbox-client#3911]
# 🐛 bug report

## Description of the problem
Taking very long to fetch changes, so it can commit to github. Before it asked me to connect to github which i did but after that it taking ver long to fetch changes

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by garethx** [comment]
Please include a link to a sandbox where you're seeing this issue along with the requested browser and OS version details, so that we can try and reproduce the problem. Thanks.

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. If you can provide us the required info, we will investigate further.
