### ISSUE TITLE
"Open Sanbox" button appears over content on mobile

### ISSUE THREAD

**Issue by jsejcksn** [codesandbox/codesandbox-client#3912]
# 🐛 bug report

## Description of the problem

<kbd>Open Sandbox</kbd> appears on top of the sandbox content when viewed on a mobile device:

![IMG_0289](https://user-images.githubusercontent.com/868251/79410050-fc9fa700-7f64-11ea-950a-afbd4b9880a3.PNG)

## How has this issue affected you? What are you trying to accomplish?

In the attached screenshot (unmodified React template) the button does not cover any content (there is no meaningful content), but this button appears on all sandboxes when viewed on mobile devices in any kind of browser web view, and interrupts activity with content in lots of cases.

The button does not appear on desktop devices, or in emulated device views in Chrome.

**How can I prevent this button from appearing?**

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Not sure where to retrieve this anymore. It doesn't appear in the place that it used to.
| Browser          |  Safari, Chrome, embedded web view
| Operating System | iOS

**Comment by garethx** [comment]
This isn't a bug but something we’re experimenting with to help protect the safety of those being targeted by some folks creating phishing sites on our platform. It doesn’t show if you open the window from the editor or are on a pro plan.

**Comment by CompuIves** [comment]
We think the bottom right location is the least disruptive place to place this button, if you know a better suggestion we'd like to hear it too!

**Comment by jsejcksn** [comment]
Injecting content into a sandbox presentation is obtrusive.

I understand the desire to counter malicious users deploying phishing sites on CodeSandbox. This is bad for you guys, and bad for us (the community of legitimate users). However, doing it in a way that interrupts viewing or interacting with content doesn't seem like a very good idea, and is more an annoyance to legitimate users than a counter to bad actors. Content injection is easily defeated as long as the sandbox can execute JavaScript. Here is a trivial counter to your existing watermark button:

```js
const removeWatermark = () => {
  const ids = [];
  const iframes = document.body.querySelectorAll('iframe');
  for (const iframe of iframes) {
    if (iframe.id.startsWith('sb__open-sandbox')) ids.push(iframe.id);
  }
  for (const id of ids) {
    const node = document.createElement('div');
    node.style.setProperty('display', 'none', 'important');
    node.id = id;
    document.getElementById(id).remove();
    document.body.appendChild(node);
  }
};

setTimeout(removeWatermark, 1000);
```

If you decide that you must inject something visual into the presented sandbox, rather than utilize another (more effective) anti-phishing strategy, it would be better to do it in a way that doesn't interrupt the content on the page, but is presented alongside it.

For example, a less obtrusive method would be a banner at the top or bottom of the page, so that it's separate from the content, and neither conflicts with the other.

An even better method would be a banner at the top or bottom which slides in **temporarily** and then slides back out, leaving the user with just the sandbox content.

**Comment by jsejcksn** [comment]
Any thoughts? @garethx @CompuIves

**Comment by CompuIves** [comment]
We're working on better ways to counter phishing by detecting it automatically, we had to get something out so less people would become victims of phishing in the short term.

I think that a banner would be more obtrusive than a small button, and while I do understand that the button can overlap with content, the banner would do this even more so since sandboxes that use fixed or absolute positioning would get their elements hidden. It would work if we use an iframe for the sandbox, but that would remove the advantage of the standalone url.

The best solution is to detect when there's a phishing sandbox and add a big banner or overlay, and that's what we're working on right now. We just have to get something out in the meantime against the surge of phishing sandboxes that are popping up.

**Comment by jsejcksn** [comment]
> The best solution is to detect when there's a phishing sandbox and add a big banner or overlay, and that's what we're working on right now. We just have to get something out in the meantime against the surge of phishing sandboxes that are popping up.

So is the plan to stop injecting content into all non-abusive sandboxes once that happens?

**Comment by jsejcksn** [comment]
Still waiting for a response @CompuIves @garethx

**Comment by TotalJabroni** [comment]
@garethx 
> It doesn’t show if you open the window from the editor or are on a pro plan

I'm on a pro plan and it still shows for me.

**Comment by garethx** [comment]
@TotalJabroni Can you link to an example, I've tried to reproduce without success. Thanks.

**Comment by julienreszka** [comment]
I have an app where I have a send button exactly where the "Open Sandbox" button appears. My app is unusable because of this.
At least there should be a way to position the button where it won't be obtrusive.

**Comment by imganpat** [comment]
> Injecting content into a sandbox presentation is obtrusive.
> 
> I understand the desire to counter malicious users deploying phishing sites on CodeSandbox. This is bad for you guys, and bad for us (the community of legitimate users). However, doing it in a way that interrupts viewing or interacting with content doesn't seem like a very good idea, and is more an annoyance to legitimate users than a counter to bad actors. Content injection is easily defeated as long as the sandbox can execute JavaScript. Here is a trivial counter to your existing watermark button:
> 
> ```js
> const removeWatermark = () => {
>   const ids = [];
>   const iframes = document.body.querySelectorAll('iframe');
>   for (const iframe of iframes) {
>     if (iframe.id.startsWith('sb__open-sandbox')) ids.push(iframe.id);
>   }
>   for (const id of ids) {
>     const node = document.createElement('div');
>     node.style.setProperty('display', 'none', 'important');
>     node.id = id;
>     document.getElementById(id).remove();
>     document.body.appendChild(node);
>   }
> };
> 
> setTimeout(removeWatermark, 1000);
> ```
> 
> If you decide that you must inject something visual into the presented sandbox, rather than utilize another (more effective) anti-phishing strategy, it would be better to do it in a way that doesn't interrupt the content on the page, but is presented alongside it.
> 
> For example, a less obtrusive method would be a banner at the top or bottom of the page, so that it's separate from the content, and neither conflicts with the other.
> 
> An even better method would be a banner at the top or bottom which slides in **temporarily** and then slides back out, leaving the user with just the sandbox content.

Hello! I want to know what is this process called like you inject some js code in the browser. How can i learn this. Name the process so i can youtube it please help
