### ISSUE TITLE
package.json dev script is started instead of start

### ISSUE THREAD

**Issue by marekrozmus** [codesandbox/codesandbox-client#3916]
# 🐛 bug report

## Description of the problem
I've created sandbox for:
https://github.com/sandstreamdev/react-swipeable-list/tree/master/examples

In console it says `yarn start` but in next line it displays my command from "dev" script

```
yarn run v1.21.1
$ webpack-dev-server --config webpack.config.dev.js
ℹ ｢wds｣: Project is running at http://localhost:3000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /sandbox
ℹ ｢wds｣: 404s will fallback to /index.html
ℹ ｢wdm｣: wait until bundle finished: /
✖ ｢wdm｣: Hash: 9e38753fb8bf64dbc150
Version: webpack 4.42.1
```

on my local machine yarn starts correct script:
```
yarn run v1.22.4
$ webpack-dev-server
ℹ ｢wds｣: Project is running at http://localhost:3000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /c/_git_/react-swipeable-list/examples
ℹ ｢wds｣: 404s will fallback to /index.html
ℹ ｢wdm｣: wait until bundle finished: /
ℹ ｢wdm｣: Hash: 32c9b8482868aa56b254
Version: webpack 4.42.1
```

**Comment by SaraVieira** [comment]
Hey!

That's the intended behavior we run the scripts in the following order: 'dev', 'develop', 'serve', 'start'.

If you want to run the start script you can open a new terminal and run npm start

**Comment by marekrozmus** [comment]
@SaraVieira OK, thanks. It seems that something has changed (or a lot) for the past few months ;) I need to update my project in this case. I was just misled by popup saying: 

`The main terminal is read-only and runs what's defined in package.json#start, you can create a new terminal to input commands`

**Comment by lbogdan** [comment]
Hey @marekrozmus ,

Yeah, that message is misleading, we should probably update it!

Otherwise, the order we start scripts in didn't change since we launched server sandboxes, so I'm not sure what you're talking about. 🙂

**Comment by marekrozmus** [comment]
@lbogdan No worries 🙂 Maybe I've messed something up. 
Just saying that same project worked before and now it stopped. But I see that a lot has changed as I haven't seen those fancy terminals earlier. Maybe my previous sandbox was created before those new features.
Anyway, thank you for great product and your time. I'll just change names of my scripts.

**Comment by lbogdan** [comment]
As an insight, we chose that order because CodeSandbox is mostly used for development, so it makes sense to prefer `dev` over `start`, if both are defined. 🙂

**Comment by SaraVieira** [comment]
That is a very good point, I made a PR to change this message :)
