### ISSUE TITLE
Live Share Links Not Working

### ISSUE THREAD

**Issue by Kensuga** [codesandbox/codesandbox-client#3938]
# 🐛 bug report

## Description of the problem
Sharing a link with another user from the 'You're live' section, going to the link returns JSON for an error with page not found

## How has this issue affected you? What are you trying to accomplish?
Work with another user without inviting them as a collaberator

### Link to sandbox: [link]() (optional)
Project Link: https://codesandbox.io/s/proud-wind-n6i6r?file=/src/index.js
Live Share Link: https://codesandbox.io/live/lmOJg

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Live Version |
| Browser          | Firefox |
| Operating System | Windows 10 |

**Comment by lbogdan** [comment]
Hey @Kensuga ,

Thanks for reporting, it was a configuration issue on our part, it should be fixed.

Sorry for the inconvenience, please let us know if it now works as expected!
