### ISSUE TITLE
Cannot use "navi" and "react-navi" packages

### ISSUE THREAD

**Issue by OnkelTem** [codesandbox/codesandbox-client#3940]
# 🐛 bug report
Despite I import both packages - `navi` and `react-navi` I cannot use any of them in a **React + TS** sandbox, getting this error:

**Cannot find module 'react-navi'.ts(2307)**

## Description of the problem

I import two packages: `navi` and `react-navi` but I cannot import from there.

## How has this issue affected you? What are you trying to accomplish?

I import two packages: `navi` and `react-navi` but I cannot import from there.

## Steps to reproduce

1. Create a React + TS sandbox
2. Add depdencies: `navi` and `react-navi`
3. Try using any import from those.
4. Get the error.

**Comment by garethx** [comment]
Are you still experiencing this problem? I don't see that error on loading the linked sandbox.

**Comment by OnkelTem** [comment]
Hi @garethx 
Yeah, now it's gone which is both good and werid :-/ 
So what was that then?

**Comment by garethx** [comment]
It's to difficult to tell without being able to see the issue, let us know if you run into it again and we can dig in.
