### ISSUE TITLE
How to install codesandbox in local server

### ISSUE THREAD

**Issue by agaitan26** [codesandbox/codesandbox-client#3944]
I followed the documentation and when i run: yarn start i cant create sandbox it shows me

you have to sign in to create more than three sandboxes

what im doing wrong?

i did it following: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md#setting-up-the-project-locally

We were unable to fork the sandbox
You need to sign in to create more than 3 sandboxes

And also i saw this: https://github.com/codesandbox/codesandbox-client/pull/2750

but still getting this **Error: This token is not registered by any user**

**Comment by SaraVieira** [comment]
Hey! 

Do you mind recording a video showing how you are doing the local auth? It would help us debug

I have seen a bunch of people use this for recording
https://www.loom.com/

**Comment by agaitan26** [comment]
hi https://www.loom.com/share/28faf1cae6804fc69cd46e131ada615c

**Comment by agaitan26** [comment]
also i saw this in chrome console:

index.tsx?ac50:18 GET http://localhost:3000/api/v1/auth/verify/Jm6vBaxi-niKEeQXgztlaDZWIImGKtRX 422 (Unprocessable Entity)

**Comment by agaitan26** [comment]
can you help me please :)

**Comment by SaraVieira** [comment]
Hey

I am so sorry, this slipped through. I think the issue is that you are not using localhost so it thinks you are trying to really sign in and you are already signed in
