### ISSUE TITLE
Cannot navigate search input with arrow keys

### ISSUE THREAD

**Issue by anuraghazra** [codesandbox/codesandbox-client#3947]
# 🐛 bug report

## Description of the problem

"Create Sandbox" modal's search input isn't accessible with arrow keys.

![image](https://user-images.githubusercontent.com/35374649/79756467-465b0980-8338-11ea-9a24-8fd1470282bc.png)

## How has this issue affected you? What are you trying to accomplish?
I was trying to navigate that search box with my arrow keys but its not working.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Version: ,0c063c3df
| Browser          | Google Chrome
| Operating System | Windows 7 64bit

**Comment by andrasbacsai** [comment]
If you search for anything and press `TAB`, you can move between templates with your arrow keys
![arrows](https://user-images.githubusercontent.com/5845193/92112687-7b9b5c00-edee-11ea-8365-aa6adb147925.gif)

Closing now. If you have any questions, let us know!

**Comment by anuraghazra** [comment]
> If you search for anything and press TAB, you can move between templates with your arrow keys

Oh i see okay nice.

Although i would probably say we can use [Composite](https://www.w3.org/TR/wai-aria-1.1/#composite) & [aria-activedescendant](https://www.w3.org/TR/wai-aria-practices/#kbd_focus_activedescendant) and have a virtual focus to those items so users can navigate while searching, just like a combobox.

**Comment by siddharthkp** [comment]
Yep, a11y best practice would be to allow arrow keys and Tab (and shift + tab) as well. Would be a good addition to the big polish list
