### ISSUE TITLE
codesandbox failed successfully

### ISSUE THREAD

**Issue by SimonSiefke** [codesandbox/codesandbox-client#3951]
# 🐛 bug report

## Expected behaviour
It doesn't show "Successfully initialized" when it has failed.

## Current behaviour
It shows "Successfully initialized" when it has failed:

![Screenshot from 2020-04-20 21-09-04](https://user-images.githubusercontent.com/23744935/79791426-9395a600-834d-11ea-83da-2713438008bb.png)

**Comment by oskarabc** [comment]
I'm getting a 502 for this now, @andrasbacsai can you take a look at what's happening perhaps, please?

**Comment by lbogdan** [comment]
Hey @SimonSiefke ,

Inside the container we try to run one of the following scripts from `package.json`, in this order: `dev`, `develop`, `serve`, `start`. You have neither in your `package.json`
https://github.com/pitlet/pitlet/blob/e44f94afa4aed13b0306191c023c0fd2b1537dd5/package.json#L6-L9
so we don't know what to do after we initialize the container.

**Comment by SimonSiefke** [comment]
There isn't really anything that needs to be done. I was just trying out the codesandbox github integration and editing some files. Maybe codesandbox could hide the preview window if there is no `dev`, `develop`, `serve` or `start` script.

**Comment by andrasbacsai** [comment]
Unfortunately, that is a very specific use case for codesandbox.
You can always do a `ctrl+shift+d` to close the preview with a keyboard shortcut.

Closing now. If you have any question, let us know.
