### ISSUE TITLE
Virtual Server Cancel Button missing

### ISSUE THREAD

**Issue by mwesencr** [codesandbox/codesandbox-client#3963]
# 🐛 bug report

Environment

OS: Windows
Browser: Chrome
Version: 80

Account
PayGo

Describe the bug

If you are using a Display Resolution of 1366 x 768, your are not able to cancel a virtual server, due to a layout error.

Steps to Reproduce

Ensure that your are using a Display Resolution of max. 1366 x 768.

    You need a running Virtual Server Instance

    Please open the Resource menu
    https://cloud.ibm.com/resources

    In the device list please select your running server e.g. this was the URL to my server
    https://cloud.ibm.com/gen1/infrastructure/virtual-server/97955272/details#main

    In the device menu, select in the blue "Actions" drop-down menu the entry for "Cancel device"

    Select "I acknowledge that data loss might occur as a result of canceling."

    You will observe that there is no button to confirm the cancellation of your server. Please take a closer look, there is only a small stripe of the red button visible.

Expected behavior
The layout error should be fixed for Display Resolution of 1366 x 768 and the Confirmation button should be visible.

Severity
medium

![Annotation 2020-03-06 113359](https://user-images.githubusercontent.com/36452478/79885289-87adf080-83ee-11ea-929b-7c5f52a6e51a.png)

**Comment by garethx** [comment]
@mwesencr Was this meant for CodeSandbox? It reads like an IBM Cloud bug.

**Comment by mwesencr** [comment]
@garethx I believe so :) I was asked to create here https://github.com/carbon-design-system/carbon/issues/5890#issuecomment-617237252

unless its the wrong repo

**Comment by tw15egan** [comment]
@mwesencr I think they were asking you to create a reproducible example using CodeSandbox so we could debug it 🙂 

@garethx I believe this issue can be closed
