### ISSUE TITLE
Electron Dependency Errors

### ISSUE THREAD

**Issue by t36campbell** [codesandbox/codesandbox-client#3968]
# 🐛 bug report

## Creating a new sandbox from existing git repo
Once the app was pulled down from GitHub it failed to run due to "Electron failed to install correctly, please delete node_modules/electron and try installing again" so I deleted and reinstalled the dependencies. After which I got this "Could not find dependency: 'electron' relative to '/main.js.'" 
To ensure this was not an issue with my repo, I used the electron-quick-start template which also resulted in the same errors. Screenshots below:

![image](https://user-images.githubusercontent.com/43715528/79901871-883e8b00-83de-11ea-865b-538b992caf03.png)

![image](https://user-images.githubusercontent.com/43715528/79901611-136b5100-83de-11ea-80be-594281f86da4.png)

![image](https://user-images.githubusercontent.com/43715528/79901032-2df0fa80-83dd-11ea-9bd7-9ff1673d6333.png)

I verified that this was also not an issue with my system/broswer by testing 2 in each OS I use. 

Im new to this service, so maybe Im missing something. Thank you in advance for your help. 
 
### Link to sandbox:
- https://codesandbox.io/s/awesome-wozniak-1ovmd
- https://codesandbox.io/s/competent-sun-zvh77

### Your Environment
| Windows | 1809|
- | Chrome | 81.0.4044.113 (Official Build) (64-bit) |
- | FireFox | 73.0 (64-bit)|

| macOS | 10.15.4 |
- | Chrome | 81.0.4044.113 (Official Build) (64-bit) |
- | Safari | 13.1 |

**Comment by SaraVieira** [comment]
Hey!

Unfortunately we can't install electron for you as it needs a file system to run and we simply fetch our dependencies to run in the browser and electron does not run in the browser
