### ISSUE TITLE
Cursor jumps when autosave on for indented line

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#3973]
# 🐛 bug report

## Description of the problem
Cursor is jumping to the beginning of the line automatically when autosave is on for an indented line
https://www.dropbox.com/s/7n2zrkuydmosj41/cursor%20jump.mov?dl=0

### Your Environment
| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest
| Browser          | Brave (including Incognito mode) Version 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit) & Chrome (81.0.4044.113)
| Operating System |

**Comment by jamirvin** [comment]
You can fix this behavior by disabling "Editor: Trim Auto Whitespace" in the VSCode settings.

This should probably be disabled by default, or made to work without affecting the currently active line on autosave.
