### ISSUE TITLE
Svelte, router, error: Cannot read property 'removeChild' of null

### ISSUE THREAD

**Issue by frederikhors** [codesandbox/codesandbox-client#3974]
# 🐛 bug report

## Description of the problem

I'm using [this amazing router](https://github.com/ItalyPaleAle/svelte-spa-router) on many Codesandbox projects to show issues in other svelte's projects.

I have to report an oddity that is happening on Codesandbox.

**Reproduction steps**:

1. go to [this CSB REPL](https://codesandbox.io/s/svelte-spa-router-cannot-read-property-removechild-of-null-mfy1s)

1. navigate from "Home" to "Posts"; it works, but

1. as soon as I edit something and try to change the page I get the error below:

```
TypeError
Cannot read property 'removeChild' of null
```

![image](https://user-images.githubusercontent.com/41120635/79968270-29394e80-8490-11ea-85b4-c6cc5a82bb16.png)

Is there anything we can do?

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Version: ,b60a4ef7a
| Browser          | Chrome 81
| Operating System | Windows 10

**Comment by garethx** [comment]
It looks like this is resolved by adding a sandbox config with the 'Hard Reload on Change' option set.

**Comment by frederikhors** [comment]
It works now also without that option.
