### ISSUE TITLE
 CodeSandbox for nuxt are broken with 502: Bad Gateway 

### ISSUE THREAD

**Issue by SumNeuron** [codesandbox/codesandbox-client#3977]
# 🐛 bug report

## Description of the problem
Some reason browser never loads but if it does it is 502

## How has this issue affected you? What are you trying to accomplish?
Just tryinng to deploy nnuxt

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/vrecordstable-84e2v?file=/codesandbox.js

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest?
| Browser          | latest?
| Operating System | maxOs

**Comment by garethx** [comment]
In a fork of the linked sandbox, I see the following error: Module not found: Error: Can't resolve '@/static/json' in '/sandbox/pages'. I'm not sure there's a resource at the linked path.

**Comment by SumNeuron** [comment]
@garethx 
I try to import a static file
```
import json from "@/static/data.json";
```
which works locally but not on sandbox?

Where do you see that erro? I don't see it anywhere

**Comment by garethx** [comment]
I saw the error on forking the linked project above. The line originally had `import json from "@/static/json";` but it looks like this has since been changed, so I wouldn't expect to still see the error.

**Comment by SumNeuron** [comment]
@garethx yes, I changed it to not even import a file and the error perisists. where are you finding the error logs?
