### ISSUE TITLE
Incorrect precedence in the CodeSandbox console

### ISSUE THREAD

**Issue by benaston** [codesandbox/codesandbox-client#3983]
# 🐛 bug report

## Description of the problem

When evaluating an expression in the console, the overall result of the expression is printed before the output of any preceding function calls.

To reproduce, run the following in the CodeSandbox console:

```
!function() { console.log('foo')}()
```

Expected:

`foo` should be printed, followed by `true` (negated boolean coercion of `undefined`).

Actual:

`true` is printed, followed by `foo`.

## How has this issue affected you? What are you trying to accomplish?

The behavior is surprising.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 
| Browser          | Brave Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
| Operating System | MacOS 10.15.4

**Comment by garethx** [comment]
Do you have a link to a reproduction? I can't reproduce the above in a static sandbox: https://codesandbox.io/s/adoring-haze-ncw8p?file=/index.html

**Comment by roblight** [comment]
@garethx you need to run `!function() { console.log('foo')}()` directly within the console of the IDE not from a project file.  Hope this helps!
