### ISSUE TITLE
React project that works locally does not work in codesandbox

### ISSUE THREAD

**Issue by kentcdodds** [codesandbox/codesandbox-client#3985]
# 🐛 bug report

## Description of the problem

I have [this repo](https://github.com/kentcdodds/react-fundamentals) that works locally with regular react-scripts, but does not work in codesandbox.

The specific error is: `Loader 'mdx-loader' could not be found.`

The way it works is I have a package `@kentcdodds/react-workshop-app` which reads the filesystem to know which files are available and generates code for the entry file. Markdown files are loaded via mdx-loader using inline loader syntax.

I've attempted adding `mdx-loader` as a dep explicitly and that didn't fix the issue. Same error either way.

## How has this issue affected you? What are you trying to accomplish?

I have 8 of these repositories for teaching people React and I'd love to be able to let people work through this stuff directly in codesandbox without having to pull things down locally.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Codesandbox.io
| Browser          | Chrome 81
| Operating System | macOS (latest)

Thanks!

**Comment by CompuIves** [comment]
Hmm, this is an interesting one. We don't have `mdx-loader` in our bundler, and we can't really use the webpack loader since we're not running Webpack itself.

I think the best solution would be to add `mdx-loader`, but it's quite an involved loader (https://unpkg.com/browse/mdx-loader@3.0.2/index.js), using 12 dependencies by itself. 

Ideally we'd support loading webpack loaders from dependencies. I think that would work with 90% of the loaders if we write a converter that can make webpack loaders behave like sandpack loaders. In the meantime, we should probably make a custom `mdx-loader` for sandpack to make this case work. I can work on that after React Europe/.

**Comment by kentcdodds** [comment]
Ah! That's new information to me. I didn't realize that webpack loaders didn't work out of the box.

Getting this update would be spectacular!

**Comment by kentcdodds** [comment]
What can I do to get this prioritized?

**Comment by kentcdodds** [comment]
Awesome to see some progress on this issue @CompuIves! Thanks.

Unfortunately, the linked project still does not work on codesandbox 😬

**Comment by CompuIves** [comment]
Yep, that's true! There are some other things I need to resolve as well, which are in PR #4191. Aiming to merge that today.

**Comment by CompuIves** [comment]
It works now if you add `mdx-loader` to the dependencies!

**Comment by kentcdodds** [comment]
Sweet! Thanks a bunch!

I think it would make more sense if I didn't have to add `mdx-loader` to the deps because that dep comes from `@kentcdodds/react-workshop-app`.

Also, the "isolated pages" don't seem to be working either. Would you like a separate issue for this?

For example:

- [Codesandbox](https://otsfu.csb.app/isolated/final/01.html) | [Production](https://react-fundamentals.netlify.app/isolated/final/01.html)
- [Codesandbox](https://otsfu.csb.app/isolated/final/05.js) (this one seems to work sometimes, but not others) | [Production](https://react-fundamentals.netlify.app/isolated/final/05.js)

It's odd because when it doesn't work, I see the app up and working, and then it disappears and we get "Transpiling Modules" for a second and then a white screen (and nothing's mounted to the root).

Here's the codesandbox: https://codesandbox.io/s/hardcore-hertz-otsfu (it's basically [the github repo](https://codesandbox.io/s/github/kentcdodds/react-fundamentals) just with `mdx-loader` added to the dependencies).

**Comment by CompuIves** [comment]
> I think it would make more sense if I didn't have to add mdx-loader to the deps because that dep comes from @kentcdodds/react-workshop-app.

Yes, I agree. I'm not sure why it can't find the dependency, I have a hunch that it's related to the dynamic import (`import()`), so we can't find the dependency statically and don't install it. 

Interesting that those pages don't work, they're just supposed to load the main app? Could you open a separate issue for it? I only see a single warning: `Node cannot be found in the current page.`.

**Comment by CompuIves** [comment]
Oh I see more dynamic imports! I was thinking of fixing that today, so maybe this will be fixed today!

**Comment by kentcdodds** [comment]
Awesome! Thanks!

--- original message ---
On Mon, Jun 1 at 03:02 AM, <notifications@github.com> Ives van Hoorne wrote:



Oh I see more dynamic imports! I was thinking of fixing that today, so maybe this will be fixed today!

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by CompuIves** [comment]
New fix is live! I got a different error though: `Failed to resolve module specifier '!babel-loader!mdx-loader!./exercise/01.md'`. Do you recognize this @kentcdodds ?

**Comment by CompuIves** [comment]
Oh, no, nevermind, I think I know what causes this!

**Comment by CompuIves** [comment]
Fix going live for that to master now

**Comment by CompuIves** [comment]
Wow, it works now!!

**Comment by kentcdodds** [comment]
Fantastic! I just tried as well and it works stupendously! Thank you so much!

One _little_ thing is the URL doesn't not update when I click the "Open on Isolated page" link (it does locally).

![image](https://user-images.githubusercontent.com/1500684/83461379-ca1f1000-a425-11ea-8de8-a9f567eb0193.png)

That's not using a client-side router, that's a regular `<a>` tag, so maybe that has something to do with it? However, the good news is that I *can* link directly to that URL (like so: https://codesandbox.io/s/affectionate-bird-icmbi?fontsize=14&hidenavigation=1&initialpath=%2Fisolated%2Fexercise%2F06.js&module=%2Fsrc%2Fexercise%2F06.js&theme=dark) so that works out ok for my use cases.

Thank you so much for prioritizing this and getting it fixed 🎊🎉👏

**Comment by CompuIves** [comment]
Great to hear!! Clicking the `a` tag works now for me! Maybe something changed, but if it still doesn't work for you, which browser are you using?
