### ISSUE TITLE
Add Dev Dependency Column just like Dependency

### ISSUE THREAD

**Issue by deadcoder0904** [codesandbox/codesandbox-client#3989]
# 🌈 Feature

## Description of the feature
I often find myself wanting to add dev deps but there's no place to add it. A simple input below dependency would be much better.

## What are you trying to accomplish?
For example, I'm using `react-table` with TypeScript. I want to add `@types/react-table` so TypeScript stops complaining. Then I have to add it to the dependency column. When I export the project locally, I get the `@types/react-table` in `package.json`'s `dependency` object rather than in `devDependency`.

So locally I have to move them around. It's a minor nitpick but happened to me quite a few times. Have kept this issue to myself for >6 months thinking it would be fixed as it's an obvious one but it hasn't so finally opened one haha

**Comment by garethx** [comment]
This isn't a bug report, but a feature request. I've adjusted the issue accordingly. Thanks for submitting it, it will be considered in a future release.
