### ISSUE TITLE
Strange Behavior

### ISSUE THREAD

**Issue by progettazionemauro** [codesandbox/codesandbox-client#3990]
# ❔ Question

### Link to sandbox: [https://ypmt7.csb.app/](url)

[https://kmcyd.csb.app/](url)

### Your Environment

| Software         | vue.js |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| I've in the first link a trivial code that it does'nt work. But it works in the other link. Why? |

**Comment by garethx** [comment]
The first is using the create-react-app environment, which involves bundling and is optimized for React apps. The latter is a using a static environment, which isn't bundled.
