### ISSUE TITLE
Getting "Command failed with exit code 137" error how do I prevent this?

### ISSUE THREAD

**Issue by dtownsend** [codesandbox/codesandbox-client#3991]
# ❔ Question

I am getting "Command failed with exit code 137" error on my Gatsby project. I have googled enough to know it is a memory error.  

I also know sandboxes currently only use 1GB of memory per sandbox.

Am I able to pay for an increase of memory or what is the easiest way to my project to my local computer? 

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by garethx** [comment]
No, we don't currently have an option to pay for more memory. You can export a project to zip from File > Export to ZIP.
