### ISSUE TITLE
Copy and Paste does not work in Firefox

### ISSUE THREAD

**Issue by pmmmwh** [codesandbox/codesandbox-client#3992]
# 🐛 Bug Report

## Description of the problem

Copy and Paste (and related functionalities like Cut) do not work in Firefox (only tested on macOS, but I suspect that the issue might affect non-Chromium-based browsers and iOS too).

## How has this issue affected you? What are you trying to accomplish?

Basically just want to copy code to and from CodeSandbox, especially useful when creating examples and sharing code snippets with setup. Both the keyboard shortcuts and the item within the right-click menu will not work.

### Your Environment

| Software         | Name/Version   |
| ---------------- | -------------- |
| Сodesandbox      | ,9ad4b4259     |
| Browser          | Firefox 75.0   |
| Operating System | mac OS 10.15.4 |

**Comment by garethx** [comment]
I haven't been able to reproduce this in the same version and OS. Does the problem still occur for you in an incognito window? Do you see any errors reported in the browser devtools console>? Thanks

**Comment by pmmmwh** [comment]
> Does the problem still occur for you in an incognito window?

It now works partially. Copying stuff from outside into CodeSandbox works, but the cut/copy functionality within CodeSandbox still doesn't work.

> Do you see any errors reported in the browser devtools console?

Specifically, when I focus the editor window, a few `unreachable code after return statement` warnings (originated from `***.worker.js`) will pop up shortly. Not sure if that's related though.

**Comment by garethx** [comment]
To clarify, it works for you partially in a normal window or in an incognito window as I suggested you try?

**Comment by pmmmwh** [comment]
> To clarify, it works for you partially in a normal window or in an incognito window as I suggested you try?

Both only works partially.

**Comment by pmmmwh** [comment]
I have investigated further - this problem happens when clipboard events are disabled (`oncut`, `oncopy`, `onpaste`) - and it seems that upstream (i.e. Monaco) have fixed it in their latest iteration. (Confirmed on [their playground](https://vscode-web-test-playground.azurewebsites.net/))

**Comment by SaraVieira** [comment]
Hey!

Can you still reproduce this?

I think I remember this also being an issue with firefox specifically on mac

I can't seem to reproduce it anymore

Thank you

**Comment by pmmmwh** [comment]
> Can you still reproduce this?

Thanks for following up!

I can still reproduce this with the steps below:

1. Go to `about:config` on Firefox, then set `dom.event.clipboardevents.enabled` to `false`
2. Test on CodeSandbox, Cut/Copy both doesn't work when I want to extract content from a sandbox
3. Test on [Monaco's playground](https://vscode-web-test-playground.azurewebsites.net/), both Cut and Copy works there.

**Comment by SaraVieira** [comment]
Hey!

I can confirm that but it seems that `dom.event.clipboardevents.enabled` is defaulted to true so I am gonna put this as a very extreme edge case that we will fix when updating VSCode (no eta)

Mind if I close it?

**Comment by pmmmwh** [comment]
> Mind if I close it?

No problem - please do!

**Comment by SaraVieira** [comment]
Thank you! Have a great week :)

**Comment by razzeee** [comment]
This seems to still affect firefox on linux (has been bugging me for months)
