### ISSUE TITLE
Import from another sandbox?

### ISSUE THREAD

**Issue by ryanpcmcquen** [codesandbox/codesandbox-client#400]
Maybe this is already a feature, but I cannot seem to figure out how to do it. Is there a way to import from another sandbox? The idea here is import a React component from one sandbox to the next.

**Comment by CompuIves** [comment]
There's no way yet. But definitely an interesting concept, we wanted to do something like this at the beginning of CodeSandbox, but decided to not to do it in initial release to keep our use cases broad.

**Comment by AlessandroAnnini** [comment]
This could be just useful!

When using React Sandbox we could end the `index.js` with
```js
export default App
```
if we want to reuse that project as component inside another one.
