### ISSUE TITLE
Weird Web animations API behavior when reversing an animation

### ISSUE THREAD

**Issue by jlkiri** [codesandbox/codesandbox-client#4000]
# 🐛 bug report

## Description of the problem

Reversing an animation with `reverse` makes the animation jump in weird ways when used in the codesandbox browser in Firefox. This behavior is not observed e.g. in JSFiddle. It also appears to work fine in Chrome.

Here's a related stackoverflow: https://stackoverflow.com/questions/61472983/why-does-web-animation-api-reverse-cause-my-animation-to-jump

Here are two implementations of the same animation in codesandbox and JSFiddle:

1. codesandbox: https://codesandbox.io/s/small-browser-1bkdt?file=/src/index.js
2. JSFiddle: https://jsfiddle.net/tobpf841/

To reproduce:

1. Click Play
2. Click Reverse(fn) while the animation is playing
3. Observe that animation in not reversed smoothly

## How has this issue affected you? What are you trying to accomplish?

Animation should be reversed smoothly

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Firefox
| Operating System | Windows 10

**Comment by garethx** [comment]
If you add a sandbox.config.json file and disable the infinite loop protection then it seems to function as expected. See https://codesandbox.io/docs/configuration for details.

**Comment by jlkiri** [comment]
Still jumps with `"infiniteLoopProtection": false` disabled...

**Comment by jlkiri** [comment]
Somehow got it working smoothly after also enabling Hard Reload On Change
