### ISSUE TITLE
Cannot sign up

### ISSUE THREAD

**Issue by kurt-hardy** [codesandbox/codesandbox-client#4007]
# 🐛 bug report

## Description of the problem
Sign up button doesn't do anything. Log request in the network, no logs in the console.

## How has this issue affected you? What are you trying to accomplish?
I cant use the site

### Link to sandbox: [link]() (optional)
https://codesandbox.io/

### Your Environment
Chrome - Version 81.0.4044.122 (Official Build) (64-bit)
Windows 10
uBlock chrome extension installed but disabled

None of these buttons work.
![image](https://user-images.githubusercontent.com/1193203/80569886-b715bc00-89f1-11ea-9f7e-55ecc9a79468.png)
![image](https://user-images.githubusercontent.com/1193203/80569909-c0068d80-89f1-11ea-9ae8-3397b54a9e31.png)

**Comment by kurt-hardy** [comment]
Also, just tried Edge and got the same issue.

**Comment by garethx** [comment]
Does the same happen if you try and sign in when using an incognito window?

**Comment by gijosso** [comment]
Any additional info in your browser console ?

**Comment by artemirq** [comment]
@gijosso @garethx Try sign in from Chrome Mobile (with cleared cache)

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. If you can provide us the required info, we will investigate further.
