### ISSUE TITLE
A sandbox error occurred, you can refresh the page to restart the container

### ISSUE THREAD

**Issue by warwickgrigg** [codesandbox/codesandbox-client#4034]
# 🐛 bug report

## Description of the problem

A sandbox error occurred, you can refresh the page to restart the container

## How has this issue affected you? What are you trying to accomplish?

Can't start webapp on codesandbox (although been working on it OK previously all day). It runs fine if I clone it from git onto google cloud shell, install it and run

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/nextjs01-87c21

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | c9aacf14e
| Browser          | Chrome Version 79.0.3945.130 
| Operating System | Windows 10

**Comment by garethx** [comment]
Closing as duplicate - contact by email separately, which is in progress
