### ISSUE TITLE
Deploys break Google Fonts

### ISSUE THREAD

**Issue by redreceipt** [codesandbox/codesandbox-client#4048]
# 🐛 bug report

## Description of the problem

Google Fonts don’t work when using the Zeit or Netlify deploy. It switches to the default

## How has this issue affected you? What are you trying to accomplish?

Have the deploy match the sandbox

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest
| Browser          | Safari
| Operating System | iPadOS

**Comment by JamesACS** [comment]
Hey @FletcherCutting - This is a known issue with React/Netlify to do with them reading google font URLs within a file component. 

If you move it up to a CSS file it should resolve the issue
