### ISSUE TITLE
The "path" argument must be of type string

### ISSUE THREAD

**Issue by FredyC** [codesandbox/codesandbox-client#4061]
# 🐛 bug report

## Description of the problem

![image](https://user-images.githubusercontent.com/1096340/80804210-c133e800-8bb4-11ea-9e0e-bfa6487ef62a.png)

## How has this issue affected you? What are you trying to accomplish?

Trying to use `wonka` library but failing with this error every time I add it to the sandbox. No other _sandbox-like_ app seems to suffer from this so it doesn't seem like a problem in `wonka` itself.

I tried older versions of `wonka` too, but no luck.

### Your Environment

It doesn't seem to matter since it's easily reproducible with a clean sandbox.

**Comment by andrasbacsai** [comment]
It looks like the source of the issue is related to [dependency-packer](https://github.com/codesandbox/dependency-packager). 

Error:
`GET https://prod-packager-packages.codesandbox.io/v2/packages/wonka/4.0.11.json 403`

**Comment by FredyC** [comment]
This is still a problem, just looks differently now (see [codesandbox](https://codesandbox.io/s/mystifying-flower-2t50p?file=/src/index.js))

![image](https://user-images.githubusercontent.com/1096340/92239073-aeab2180-eeba-11ea-8f4d-1fb03d4bfa60.png)

**Comment by SaraVieira** [comment]
Thank you! Pinging @CompuIves  as this seems to be an issue with the bundler

**Comment by FredyC** [comment]
The problem still exists. Please, can you mark this issue somehow so it's not going to stale?

https://codesandbox.io/s/mystifying-flower-2t50p?file=/src/index.js

**Comment by SaraVieira** [comment]
Hey

As soon as you comment the tag gets taken out no worries 
but the bot only goes around once a day

**Comment by FredyC** [comment]
Well, is it necessary for me to keep reminding it here it's still an issue? Usually, there is some label to acknowledge it as a bug and keep around until it's resolved.

**Comment by SaraVieira** [comment]
I only added crash report for that porpuse, should add a new one but for now yeah just added the crash report label and it won't happen again

**Comment by SaraVieira** [comment]
@FredyC Actually ives just fixed the issue

Should be all good, can you please test using the library?

**Comment by FredyC** [comment]
Yes, looks good to me. Thanks!
