### ISSUE TITLE
setting in embed config for "Word Wrap" in the embedded CodeSandBox instance

### ISSUE THREAD

**Issue by davidvandenbor** [codesandbox/codesandbox-client#4063]
# 🌈 Feature

Is there some kind of config you can set up for the **embedded editor** to be **word wrapped**?
```
Editor: Word Wrap
Controls how lines should wrap.
```

Now you have to scroll horizontally all. the. time. to get to all of the code. I'm trying to get the word wrapping to be on by default in embeds! (Plunker has it on by default)

Kind regards and thanx in advance :-)
David van den Bor

**Comment by subins2000** [comment]
Yes, the scrollbar is annoying. Allow word wrap please
