### ISSUE TITLE
Cursor flying around and not typing

### ISSUE THREAD

**Issue by rifkijones** [codesandbox/codesandbox-client#4065]
# 🐛 bug report

### mac

| Software         | Name/Version |
| macOs | Catalina 10.15.4|
| Сodesandbox      |
| Browser  CHROME        |
| MacOs Cantalina|

**Comment by garethx** [comment]
Thanks for the report. Can you expand upon the behaviour you're seeing, with perhaps a video? It's difficult to understand from the description and I can't reproduce in an equivalent environment. It'd be useful to know whether this still happens in an incognito window, and if you have auto-save enabled. Thanks.

**Comment by rifkijones** [comment]
Hi thanks for getting back to me. I have resolved this by completely
clearing the cache on my Chrome browser. Not sure why this fixed the issue?
Anyway all good now.

Thanks again
Lee
