### ISSUE TITLE
Editor keeps entering read-only mode

### ISSUE THREAD

**Issue by NawarA** [codesandbox/codesandbox-client#4067]
# 🐛 bug report
Editor loses the user session, which disables user keyboard input.

The editor displays the error: `Cannot edit in read-only editor`

## Description of the problem
Above

## How has this issue affected you? What are you trying to accomplish?
I'm using the editor, and then it randomly loses the user session. I have to open another editor instance in order to continue my work. This distrupts workflow by breaking your focus from work, to focus on the editor's bug; and it further makes me lose my tabs that are open, etc. 

This happens consistently, and breaks the usability of the editor, since it keeps locking me out of my coding.

### Link to sandbox: [link]() (optional)
Its all sandboxes. Not a single sandbox. I'm guessing its related to the last two releases, which somehow tied user session to a variable, allow a user session to appear, and then disappear?

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | ec9e6ba33 |
| Browser          | Chrome 81 |
| Operating System | Windows 10 |

**Comment by CompuIves** [comment]
Hello! Thanks for reporting this, does this happen consistently, between refreshes? My hunch is that we invalidate the user jwt, which causes the inconsistent state. We're working on fixing that issue right now, so hopefully it will be a two birds one stone.

**Comment by NawarA** [comment]
Hmmm, it just happened again. It seems to occur when I'm typing.

Two states may occur as I type:
- I'm typing and the sandbox is "soft" refreshing, aka refresh without transpiling.
- I'm tying and the sandbox is "hard" refreshing, aka refresh with re-transpiling modules.

I think it may be happening during soft refreshes. The bug just occurred again. I'll try to keep an eye out to observe in which cases it occurs

Definitely losing user token->
![image](https://user-images.githubusercontent.com/2067616/82611992-a8e13880-9b76-11ea-97de-f76d0e89e721.png)

**Comment by CompuIves** [comment]
Oh yes, wow that's interesting. Did you see any notification with a failed request or something?

**Comment by NawarA** [comment]
I'll keep an eye out next time it happens and let you know about any additional console logs that may occur. 

Typically your avatar disappears and your editor locks saying something along the lines of: _cannot edit in read-only mode_, requiring you to restart the editor. Restarting the editor makes you lose your tabs that were open, so thats annoying :)

Im keeping an eye out and will report back to you if I find anything new

**Comment by NawarA** [comment]
It looks like it just occurred during what I called a "soft refresh". 

Also, my wifi connection switched during the "soft refresh". I'm not sure if that effected anything, but its important to mention all things when isolating issues.

**Comment by NawarA** [comment]
Havent seen this occur in a while. I'm going to close the issue 👍

**Comment by Nina241o** [comment]
It just happened to me... Very annoying!

**Comment by Lord-Aman** [comment]
Happening to me. Still not resolved...

**Comment by emmanuelkorir** [comment]
I am facing similar problems.

**Comment by lt353** [comment]
I have the same issues still.
