### ISSUE TITLE
Live Mode - automatically turning on

### ISSUE THREAD

**Issue by NawarA** [codesandbox/codesandbox-client#4069]
# 🐛 bug report
This has been happening for several releases, but whenever I load any of my sandboxes, the editor automatically starts recording a Live session. 

## Description of the problem
Live sessions automatically turn on. Previously, Live Sessions would only turn on if a user chose to kick off a Live Session. As of a few releases ago, Live Sessions began turning on, without user input. This feels like you're always being monitored and recorded during your coding sessions.

## How has this issue affected you? What are you trying to accomplish?
It feels like Codesandbox is monitoring my sessions above and beyond whats required to provide the codesandbox service. Why are you recording a user session without the user expliclity kicking off live mode? If Live Mode is supposed to be enabled by default, and on all the time, remove it from the left hand menu. It feels like you're forcing live mode on everyone.

The take away is:
* Bug: Live mode is accidently enabled by default, as a few releases ago
* Bug: Your team decided Live Mode should be on 100% of the time, unless a user disables live mode; in which case, it feels like a bad user experience, since it feels like a user is being monitored without consent or choice. Which is a bug in UX, and a bug in your brand.

Either way, please patch "live mode" so its not enabled by default; or if you've chosen to make live mode on by default as a design choice, then please release a setting so I can opt-out of live mode; or finally, if you've chosen to give users zero choice on live mode, and you want it always on by default, then remove the Live Mode menu button, so users dont feel like they have a feature that's monitoring them without choice.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | ec9e6ba33 |
| Browser          | Chrome 81 |
| Operating System | Windows 10 |

**Comment by MichaelDeBoey** [comment]
Hi @NawarA!

Since the latest release, Live Mode is enabled by default as you could see in the latest blogpost: https://codesandbox.io/post/redefining-code-collaboration#live-by-default
> All sandboxes are now live by default. Making collaboration seamless is key to its efficacy, so it's no longer a mode you enable but something that's on all the time. This means team members can come together and work on sandboxes with ease, and guests can be invited to view or edit outside of a specific session.

The team chose to make this an opt-out instead of an opt-in for the reasons mentioned in the blogpost, so if you want, you can always opt-out of Live Mode in the settings of the sandbox.
