### ISSUE TITLE
Carbon Integration

### ISSUE THREAD

**Issue by mfix22** [codesandbox/codesandbox-client#407]
This issue is to discuss integration with carbon.now.sh 😄 

Here is a link [the original tweet from @CompuIves](https://twitter.com/CompuIves/status/942399628863041537) 

Initial ideas:
- [ ] Link that opens current file up in a new tab to `carbon.now.sh?code=<your_code>` (currently supported, including colors and themes 👍)
- [x] Embedded Carbon editor view

Please feel free to leave your thoughts and other ideas!

**Comment by CompuIves** [comment]
Great! I love Carbon, generated images are beautiful.

I think we can fit this perfectly with our redesign, maybe this also works together with #390. The coolest thing would be to have an embedded carbon view, that would make it seamless to share. Do you think it would perhaps be possible to make an embeddable version for it?

**Comment by mfix22** [comment]
@CompuIves I think we definitely could! We definitely want to keep the Carbon brand apparent (much like Zeit has done with the Now integration 😄).

I am going to start extracting the editor out into it's own component, and I don't think it should be too hard. I will update here on my progress.

**Comment by mfix22** [comment]
Hey @CompuIves,
Just published `carbon-editor@0.0.2`. I haven't tested it _too_ extensively, but it encapsulates the carbon editor into a React component.

Will post more updates and thoughts on integration when I get to them!

**Comment by CompuIves** [comment]
That's greaat @mfix22! I'm currently working on a redesign of the CodeSandbox editor, would be cool to put this in the same release. I'll play some with it!

**Comment by mfix22** [comment]
Right now the component that is exported can be instantiated without any props, but we can probably play with it and add more configuration as a stand-alone component. 

Let me know if you see any issues, or if you would like any help integrating it in one of your repos as well. We are here to help.
