### ISSUE TITLE
Can't change the dependency version in Chrome App version of CodeSandbox

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#4097]
# 🐛 bug report

## Description of the problem
It's not possible to change the dependency version in Chrome App version of CodeSandbox. The drop-down menu immediately closes after opening so you're unable to change version.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 1bfd7722f
| Browser          | Chrome
| Operating System | Mac OS X

**Comment by SaraVieira** [comment]
MY CHROMEBOOK COMES TO THE RESCUE
