### ISSUE TITLE
Svelte template watch/reload only works in a Container (not Web sandbox)

### ISSUE THREAD

**Issue by tjlav5** [codesandbox/codesandbox-client#4104]
# 🐛 bug report

## Description of the problem

Livereload after changing JS/CSS/etc in the default Svelte sandbox-template does not work. The code is properly transpiled as evidenced by manually clicking on the refresh button with the sandbox's preview pane.

## How has this issue affected you? What are you trying to accomplish?

Have to manually click the refresh button after every save.

### Link to sandbox: [https://codesandbox.io/s/serene-christian-e909c?file=/package.json]() (optional)
Just forking the default template should produce the same issue.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 1bfd7722f
| Browser          | Chrome 81.0.4044.127
| Operating System | ChromeOS

**Comment by andrasbacsai** [comment]
The default Svelte template ([example](https://codesandbox.io/s/pedantic-voice-7znjz)) does not use server side sandbox, but your example is. Do you really need a server side sandbox for the example?

## Possible cause
Rollup finishes later than the livereload websocket established. So the mini browser sees the old code, not the modified. Not all the time, but I could reproduce it with 3-4 tries.

> Rollup: 11:42:51 (UTC)
> Websocket: 13:42:49 (UTC+2)

![image](https://user-images.githubusercontent.com/5845193/82119025-6507c100-977b-11ea-96f0-572f5ce053c4.png)
