### ISSUE TITLE
Sandbox not loading anymore - VueJS/Bootstrap-Vue

### ISSUE THREAD

**Issue by arthurmcgregor** [codesandbox/codesandbox-client#4109]
# 🐛 bug report

## Description of the problem
The sandbox that I was using on Friday is no longer working come Monday morning! I tried to create a new sandbox from scratch like I did on Friday (see below), and that also didn't work. I have tried different computers/browsers, still doesn't work. Other sandboxes, created in other ways, did work.

To reproduce:
1. Go to https://bootstrap-vue.org/play
1. Click Export to CodeSandbox
1. Looks like so:
![codesandbox](https://user-images.githubusercontent.com/24260476/81512872-3e5f1a00-9378-11ea-802d-b0381065d0eb.png)

## How has this issue affected you? What are you trying to accomplish?
I had successfully created (and shared) a codesandbox prototype on Friday. However, it is not working today!

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |?|
| Browser          |Chrome|
| Operating System |Windows|

**Comment by CompuIves** [comment]
Oh, I found the issue on this! Something going wrong with parsing the HTML. If you  change `index.html` to 

```
<body>
  <div id="app></div>
</body>
```

it should work for now. I'm also committing a fix, so that should be live today. Sorry for the inconvenience!

**Comment by CompuIves** [comment]
This has been fixed now! Thanks for the patience.

**Comment by arthurmcgregor** [comment]
Cheers - thanks for your time :-)
