### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by obaseki1** [codesandbox/codesandbox-client#4114]
# 🐛 bug report

## Description of the problem
I suddenly got this error from code sandox saying "ModuleNotFoundError: Could not find module in path: 'dom-helpers/matches' relative to '/node_modules/react-overlays/cjs/Dropdown.js'" any help would be appreciated.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest
| Browser          | Google chrome
| Operating System | Windows 10

**Comment by andrasbacsai** [comment]
Does the error still exists?

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. If you can provide us the required info, we will investigate further.
