### ISSUE TITLE
Opening sandbox.config.json file in an embed produces blank screen + errors

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#4120]
# 🐛 bug report

## Description of the problem
If you click on a sandbox.config.json file in an embed, the result is a blank screen and multiple errors in console.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 178914795
| Browser          | Chrome
| Operating System | OS X

**Comment by SaraVieira** [comment]
Created a linear app that will fix this and will pick it up this week

https://linear.app/issue/CSB-191/add-theme-provider-to-embed
