### ISSUE TITLE
CodeSandbox not working the same on first load vs saving

### ISSUE THREAD

**Issue by coldshower** [codesandbox/codesandbox-client#4128]
# 🐛 bug report

## Description of the problem

When I first load this sandbox https://codesandbox.io/s/phone-browser-example-kcbdk?file=/src/index.js

I see the desired behavior, with the input being validated, but then it quickly gets cleared away. The app then doesn't work, as if the listeners were not attached. However, if I make any changes, even comments, to the `index.js` code, it starts working as intended.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome Latest
| Operating System | Mac OS Mojave

**Comment by garethx** [comment]
I'm not able to reproduce the problem here - the validation works consistently for me with the same setup. Can you show in a video what it is that you're seeing? (loom.com makes it easy) It'd also be useful to know whether the problem still happens in an incognito window. Thanks.

**Comment by coldshower** [comment]
Hey @garethx Thanks for replying!

I've done some more testing of this issue on multiple machines and noticed that it does not happen every single time, more often on my slower Macbook. On my 2019 Macbook it never happens so I suspect it has something to do with performance.

Here is what it looks like when it does happen:

https://share.getcloudapp.com/NQuDBmr7

I've put a `console.log` inside `validate` but sometimes, what happens is that the console shows the `log`, but then clears it right after by itself.

On the 3rd refresh, it does not clear it, and the grey `code` block is populated (desired on load behavior). 

On the next refresh, it breaks again, and the `console.log` gets cleared away, and the grey `code` block is empty.
