### ISSUE TITLE
Help me make my Context Menu Paste extension work in Chrome...FF is working

### ISSUE THREAD

**Issue by PAEz** [codesandbox/codesandbox-client#4147]
# 🌈 Feature

I made a simple extension to bring paste back to the context menu of the Monaco editor.

Install my extension and paste should be back.

My extension works with most of the few pages I tried, but not in Codesandbox in Chrome.
FF works because its simpler than the Chrome version.  There is a line in Monacos source somewhere that hard checks if its running in chrome and if it is then doesnt even bother checking if paste is supported by the browser.  Because of this I had to find another way in.  My way works on most pages, but your doing something different and its all beyond me ;P.  Is there any chance someone more knowledgeable could make it work, or would you be open to adding another way for an extensions to do this....I really miss paste

Below will be the source for the extension and Ive attached a zip of the extension and here's a link to the FF version (which works)....
https://addons.mozilla.org/en-US/firefox/addon/paste-for-monaco/

Extension (unpack and load)
[paste_for_monaco-1.0.zip](https://github.com/codesandbox/codesandbox-client/files/4641533/paste_for_monaco-1.0.zip)

Source
```javascript
exec(function() {
    const isChrome = navigator.userAgent.indexOf("Chrome") >= 0;
  
    if (!isChrome) {
      // hijack the query and report paste supported
      var copyQuery = document.queryCommandSupported;
      document.queryCommandSupported = function(arg) {
        if (arg != "paste") return copyQuery.apply(document, arguments);
        return true;
      };
  
      // hijack the exec for paste and make it message back here to paste
      var copyExec = document.execCommand;
      document.execCommand = function(arg) {
        if (arg != "paste") return copyExec.apply(document, arguments);
        window.postMessage(
          {
            command: "paste"
          },
          "*"
        );
      };
  
    } else {
      
      var monaco;
      Object.defineProperty(window, "monaco", {
        get() {
          return monaco;
        },
        set(newValue) {
          monaco = newValue;
          var copyCreate = monaco.editor.create;
          monaco.editor.create = function(arg,arg1,arg2) {
            
            var editor = copyCreate.apply(monaco.editor, arguments);
            
            editor.addAction({
              // An unique identifier of the contributed action.
              id: "my-unique-id",
              // A label of the action that will be presented to the user.
              label: "Paste",
              // A precondition for this action.
              precondition: null,
              // A rule to evaluate on top of the precondition in order to dispatch the keybindings.
              keybindingContext: null,
              contextMenuGroupId: "9_cutcopypaste",
              contextMenuOrder: 3,
              // Method that will be executed when the action is triggered.
              // @param editor The editor instance is passed in as a convinience
              run: function(ed) {
                window.postMessage(
                  {
                    command: "paste"
                  },
                  "*"
                );
                return null;
              }
            });
            return editor;
          };
          return monaco;
        },
        enumerable: true,
        configurable: true
      });
    }
  });
  
  window.addEventListener("message", function(event) {
    if (event.source == window && event.data && event.data.command == "paste") {
      document.execCommand("paste");
    }
  });
  
  function exec(fn) {
    var args = "";
    if (arguments.length > 1) {
      for (var i = 1, end = arguments.length - 2; i <= end; i++) {
        args +=
          typeof arguments[i] == "function"
            ? arguments[i]
            : JSON.stringify(arguments[i]) + ", ";
      }
      args +=
        typeof arguments[i] == "function"
          ? arguments[arguments.length - 1]
          : JSON.stringify(arguments[arguments.length - 1]);
    }
    var script = document.createElement("script");
    script.setAttribute("type", "application/javascript");
    script.textContent = "(" + fn + ")(" + args + ");";
    document.documentElement.appendChild(script); // run the script
    document.documentElement.removeChild(script); // clean up
  }
```

**Comment by CompuIves** [comment]
Ah wow, this is interesting. So `document.execCommand("paste");` doesn't work? Really weird, is there a way to read the clipboard of the user? Because in that case we could maybe trigger it manually on the model itself (`CSEditor.editor.getActiveCodeEditor().getModel().applyEdits` in console).

**Comment by PAEz** [comment]
Browsers removed the ability to paste for security reasons.  With access to the clipboard people can sniff it looking for lazy people copying their passwords or woteva.  JS in the extension space do have access to it tho.  So this extension just gets paste to message back to itself and then executes it from there.  
So codesandbox (monaco) cant access the clipboard, so you cant get what to paste, only an extension can do that unless you implement your own cut/copy routine.  So without creating your own cut/copy/paste code the solutions I see are.....  
Your code checks to see if an extension (mine or yours) exists and if so add the paste code like above.  Simple to do, you just message the extension to see if its there.  Messaging can target an extension by its ID so you dont have to worry about security if you target your own extension....wouldnt have to worry about mine either, but you dont know me so I wouldnt expect you to.
The other is to tell me some way to hijack the creation of editors like Im doing now.  By targeting the creation part I dont have to worry about getting all the editors after the fact which can be hard some times.  The way you use editor.create is totally different from elsewhere and I don't get it ;P  
Or, show me a way to access all the editors after they are created and how to add a menu option.  Things are done different here and I cant find an easy way just by peeking around the objects.  
  
Ive got this working for me (been using this for months) as I use FF lately and the FF works.  But I thought Id finally get around to putting out extensions as Ive noticed none made yet and feel for all those people putting up issues wanting paste to work for them as well.  So Im putting off releasing the chrome one until I hopefully can get this sorted.  I originally wrote this for your site as I eFn love it (you've all done some amazing work here), so really want it to work.
