### ISSUE TITLE
shortcut to quick search/open your sandboxes?

### ISSUE THREAD

**Issue by yangkennyk** [codesandbox/codesandbox-client#4160]
Is there a shortcut to search/open your own sandboxes? I've looked through the docs and can't seem to find anything on how I can quickly open my sandboxes without using my mouse to open the dashboard and clicking a sandbox

**Comment by garethx** [comment]
Where are you hoping to use the keyboard shortcut, when you're on the dashboard to navigate it via keys or when in the editor to avoid going to the dashboard at all?

**Comment by yangkennyk** [comment]
when I'm in the editor and want to switch sandboxes. it's not a huge issue. I just try to avoid leaving my keyboard
