### ISSUE TITLE
Load html files from Github

### ISSUE THREAD

**Issue by deadcoder0904** [codesandbox/codesandbox-client#4172]
# 🌈 Feature

I have to share this file https://github.com/pqina/flip/blob/master/example/index.html with some modifications.

I tried appending `example/index.html` to the URL of codesandbox but it didn't work.

I think it's easier to do it on Codesandbox rather than asking someone to clone the repo & edit the HTML file.

It also references files with relative path like `../dist` inside it so it should work too. Not sure if it's possible but it's a completely game changer since many repos have `example/index.html` files

**Comment by garethx** [comment]
If you're just wanting to import a single file, is it really any easier to copy paste the URL rather than copy pasting the file's content?

**Comment by deadcoder0904** [comment]
Not sure what you mean? There are no script tags here linking to CDN. They are linking to current repo through relative path like `../dist/styles.min.css` or something like that.

**Comment by garethx** [comment]
I took your feature request to mean you want to import individual files from GitHub into CodeSandbox to modify and share, is this not the case?

**Comment by deadcoder0904** [comment]
Nope, because then I that `index.html` can't reference `dist/css` & `dist/js` which would break the whole thing.

Take a look at https://github.com/pqina/tick/ for example. I typed https://githubbox.com/pqina/tick/ in the URL, appended `example/index.html` to Codesandbox URL, wishing for it to worked. It didn't. So I thought this might be a cool feature request.

**Comment by garethx** [comment]
Ah ok, I see what you want. There's a couple of blockers to this working. We're working on one right now, enabling static sites to be imported from GitHub without a package.json file. However, even with that this example wouldn't work since it's referencing resources above it in the file hierarchy, whereas we currently assume the imported directory is root. So we'd somehow have to understand that and import those resources too.

**Comment by deadcoder0904** [comment]
Yeah it's a feature request. Just an idea. Definitely not blocker. Codesandbox has gotten so much better & easier, no complaints at all.
