### ISSUE TITLE
Version Control Codesandbox or Save State like a Git Branch

### ISSUE THREAD

**Issue by deadcoder0904** [codesandbox/codesandbox-client#4173]
# 🌈 Feature

Sometimes when I'm debugging a library, I find an issue. So I file it on the repo & link to the codesandbox while also simultaneously trying to find the solution myself.

So the linked version keeps getting changed.

Here, something like a Git Branch would help. Like `test-1` branch where some `for...loop` isn't working & I can link to it from the repo without worrying about changing state to something else.

This is better than duplicating a sandbox I think.

**Comment by mattchess** [comment]
codesandbox stopped displaying after 2 minutes of creation

**Comment by garethx** [comment]
@mattchess how does this relate to the above feature request? If you'd like to report a different issue, please create a separate one for it.

**Comment by deadcoder0904** [comment]
@mattchess not the right place mate 😂

**Comment by brentgti** [comment]
Any chance of this being implemented? Even something like local history would be helpful. Linking to my GitHub account may make this unnecessary, but I don't actually want (and my company may not allow me) to give access to my GitHub repos to CodeSandbox.

**Comment by garethx** [comment]
Yes, we're thinking through the options here as we want to better support larger projects and have more flexibility here.

**Comment by vvscode** [comment]
Sorry, any progress on this? I see the request is closed, but I don't see anything related to the functionality in the codesandbox UI

**Comment by JamesACS** [comment]
Hey @vvscode - We've got a number of improvements/changes that we're going to be releasing next year - they should address this request :) 

At the moment, the only way of preserving one version of code in CodeSandbox while creating another version to continue working is by forking the Sandbox.
