### ISSUE TITLE
Sandboxes do not open in Microsoft Edge. 

### ISSUE THREAD

**Issue by sguzunov** [codesandbox/codesandbox-client#4184]
# 🐛 bug report

## Description of the problem
Sandboxes cannot be opened in Microsoft Edge. Instead a blank page is displayed. There is an error in the console that says "SCRIPT1028: SCRIPT1028: Expected identifier, string or number".
![sandbox-ms-edge](https://user-images.githubusercontent.com/10837541/82680325-c684cf80-9c54-11ea-9b7a-5a626be3d565.PNG)

## How has this issue affected you? What are you trying to accomplish?
We started using Codesandbox in order to embed examples in our documentation and having links to the sandboxes. In that case, it look like that the links are going to broken in Edge.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Microsoft Edge 44.18362.449.0  |
| Operating System | Windows 10 |

**Comment by garethx** [comment]
We made this change (https://github.com/codesandbox/codesandbox-client/pull/4196), are you still seeing the issue?

**Comment by sguzunov** [comment]
No, I don't see the issue. The sandbox pages open successfully. Thank you!
