### ISSUE TITLE
window load event not working

### ISSUE THREAD

**Issue by carlotrimarchi** [codesandbox/codesandbox-client#4192]
# 🐛 bug report

## Description of the problem

I'm trying to using the window load event but any code that I try to run inside of it is not working.

I'm linking to a sample sandbox with just a console.log() inside.

Am I missing something?

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/window-load-test-m4e3v

**Comment by garethx** [comment]
I'll flag this to the team, in the meantime if you use a static template then this works as expected, see https://codesandbox.io/s/window-load-test-3ejgh?file=/index.html
