### ISSUE TITLE
Add `autoplay` to Feature Policy

### ISSUE THREAD

**Issue by smatysik** [codesandbox/codesandbox-client#4193]
# 🌈 Feature
Similar to https://github.com/codesandbox/codesandbox-client/issues/1112, add `autoplay` to the iframe Feature Policy so that codesandboxes testing muted autoplay HTML5 video function as expected: https://codesandbox.io/search?query=autoplay&page=1&configure%5BhitsPerPage%5D=12

**Comment by CompuIves** [comment]
That sounds good! I think we need to change this:

https://github.com/codesandbox/codesandbox-client/blob/esm-test/packages/app/src/app/pages/common/Modals/ShareModal/getCode.ts#L71

and

https://github.com/codesandbox/codesandbox-client/blob/esm-test/packages/common/src/components/Preview/index.tsx#L612

and

https://github.com/codesandbox/codesandbox-client/blob/esm-test/standalone-packages/react-sandpack/src/components/SandpackProvider/SandpackProvider.tsx#L277

and

https://github.com/codesandbox/codesandbox-client/blob/esm-test/standalone-packages/sandpack/src/manager/index.ts#L120

If anyone's interested in helping on this, that would be greatly appreciated!

**Comment by flickz** [comment]
@CompuIves I gat this.
