### ISSUE TITLE
Last Modified timestamp

### ISSUE THREAD

**Issue by shipstar** [codesandbox/codesandbox-client#422]
We're planning to use CodeSandbox as part of a hiring process to provide candidates with a starter project, have them fork it and make a few updates, then submit their fork. I'm trying to figure out a good way to check that candidates are not editing a sandbox after submission.

It seems like a lightweight approach might be capturing a "Last Updated" timestamp. If we capture the same on our side, we could compare those timestamps to determine if a sandbox was edited. It looks like `updated_at` timestamps are not currently returned in the JSON payload when fetching a sandbox, but I'm guessing you're tracking this server-side anyway. This could be useful on a per-sandbox or per-file basis.

Versioning could solve this problem as well, although that seems like a heavier lift. Another idea we had was downloading a zip file of the repo upon submission.

Am I missing something obvious and there's a good solution already in place? If not, I'm happy to submit a PR, although there would need to be server-side changes and it seems like that repo is private.

P.S. Thanks for all the hard work on CodeSandbox! This is a great tool and I'm excited to use it for both personal and professional projects.

**Comment by CompuIves** [comment]
Hey @shipstar. I love to hear that you want to use CodeSandbox for the hiring process, happy to help in any way!

Right now we provide the field `version` on the sandbox payload to determine if a sandbox changed, I can also add `updated_at` to the payload if that's easier for you.

**Comment by shipstar** [comment]
I think `updated_at` would be ideal for our current use case, although we might be able to leverage `version` down the road as well.

Thanks for the prompt response!

**Comment by CompuIves** [comment]
I added the `updated_at` field to the sandboxes! 😄

**Comment by shipstar** [comment]
_And_ you put it in ISO8601 format?

![ezgif-5-1641133877](https://user-images.githubusercontent.com/115918/34548326-7a96de3e-f0cf-11e7-81e6-984310d8eaf1.gif)

If anyone else might be interested in this, I'm happy to submit a PR to add an unobtrusive "Last modified at: {timestamp}" to the frontend.

Either way, thanks for all of the help and feel free to close this issue if you'd like!

**Comment by SaraVieira** [comment]
Hey!

We could add this to the info box.

What do you think of something like this ?
<img width="568" alt="screenshot 2018-10-12 at 23 08 13" src="https://user-images.githubusercontent.com/1051509/46894142-bbac6b00-ce73-11e8-96a1-df07e97642d7.png">

**Comment by lbogdan** [comment]
@shipstar Do you still need this?

**Comment by oorestisime** [comment]
can i play with this? seems like fun to get a feel of the codebase

**Comment by Saeris** [comment]
@oorestisime if you would like to try adding a `Last Updated at` field to the Project component, please submit a PR and I'd be happy to review it. You can find those two components in this directory:

https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/index.js

Please be aware that we are in the middle of implementing a refactor across all of the Workspace components, so I may request some changes if conflicts come up. Should be pretty straight forward though.

Sara's screenshot above looks like the right direction for this. My only other request would be to add a timestamp in addition to the date. This could be shown on hover. Use your best judgement!

**Comment by oorestisime** [comment]
Nice thanks for the directions, will give it a go in the next days!

**Comment by SimonVanherweghe** [comment]
> I added the `updated_at` field to the sandboxes! 😄

Has it been removed? I can't find it.

I'm working on a PR for this, would be a nice feature when we review student submissions as a lecturer.

**Comment by SaraVieira** [comment]
Hey!

At the moment we are trying to reduce the amount of stuff we have in the editor but this field is still available in the API if you need it

https://codesandbox.io/api/v1/sandboxes/fastify-starter-luepu

replace fastify-starter-luepu with the sandbox url or id and you can see when it was last updated :)
