### ISSUE TITLE
prettier config not working in vue example

### ISSUE THREAD

**Issue by OculusMode** [codesandbox/codesandbox-client#4231]
# 🐛 bug report
The config changes of prettier in vue sandbox doesn't change anything
## How has this issue affected you? What are you trying to accomplish?
Was trying to change tabsize and override rule of bracket spacing

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/immutable-water-vcw48?file=/.prettierrc

### Your Environment
Gnome

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome|
| Operating System | Linux |

**Comment by siddharthkp** [comment]
That's strange! Will look into the difference in how we run prettier on vue sandboxes. Thanks for taking the time to report it!

**Comment by nikhil-varma** [comment]
@siddharthkp This has happened to me as well for a React project a while back. It started working later though. Just thought you should know in case it helps 😄

**Comment by CompuIves** [comment]
Hey @OculusMode, I just tested the repo, and for me it does prettify the Vue files correctly (with 4 spaces). Can you still reproduce this issue?

**Comment by OculusMode** [comment]
@CompuIves checking

**Comment by OculusMode** [comment]
@CompuIves Okay that seems to be working now in new repo i created. I'll just give a rest to this bug then :)
