### ISSUE TITLE
Unable to commit the codes to GitHub

### ISSUE THREAD

**Issue by DreamsOfImran** [codesandbox/codesandbox-client#4249]
# 🐛 bug report

## Description of the problem
Usually, it will create a new sandbox whenever I push into GitHub. But now it's not creating a new sandbox and not linking the sandbox with GitHub. However, the new repo is created in GitHub from the sandbox.

## How has this issue affected you? What are you trying to accomplish?
Unable to commit the changes on the existing repo which is created from the sandbox.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |-|
| Browser          | Chrome|
| Operating System | MacOS Catalina|

**Comment by garethx** [comment]
Please provide a link to the repo and/or sandbox so we can look into this for you.

**Comment by DreamsOfImran** [comment]
Please find the sandbox link below which I tried to push it to GitHub.
https://codesandbox.io/s/guvi-redux-tm3qk

**Comment by garethx** [comment]
I'm not able to reproduce your issue - see https://github.com/garethx/4249-test/tree/master/. Are you forking the sandbox after committing to GitHub? You need to in order to make commits back to GitHub.

**Comment by DreamsOfImran** [comment]
Previously, it will auto-fork once created a repo and pushed into GitHub from the sandbox. That's the issue now.
Thank you for your help @garethx.

**Comment by garethx** [comment]
We auto-fork if you select a template in Template Universe, but it's not been the case that it'd auto-fork on creation of a repo that I remember. At least, what happens now is the intended functionality. We're working on some improvements to the GitHub workflow which will make knowing what action to perform next clearer.
