### ISSUE TITLE
Cannot Un-freeze Sandbox That Is Frozen After Import from Github

### ISSUE THREAD

**Issue by cynthiateeters** [codesandbox/codesandbox-client#4251]
# 🐛 bug report

## Description of the problem

Using the Import Wizard, I import from a github repo and it comes in Frozen. I go to the Info panel and click on the Frozen slider. It shows that I am turning it off but it really stays on. If I refresh the page, the slider shows it remains Frozen.

The documentation says that I can un-freeze a frozen sandbox but thisappears not to be the case when doing an import.

I guess this is because it comes in as a Template, but I do not want it as a Template. I want it as an editable sandbox linked back to my repo. 

I just found out that I can fork it and work from the fork but this is not intuitive to me. 
 
## How has this issue affected you? What are you trying to accomplish?

I cannot edit my repo files as they are considered read-only when imported into a sandbox and there is no way to un-freeze. I have to take the extra step of creating a fork, but that it is not discussed in the documentation.

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/github/IDMX225/codesandbox-test-cynthiateeters

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | https://codesandbox.io/
| Browser          | Chrome
| Operating System | MAC OSX Catalina

**Comment by garethx** [comment]
If you want to edit the GitHub import, then you need to fork the template. The forked sandbox retains its link back to the repo and you can commit changes to it. See the docs for more info: https://codesandbox.io/docs/git#base-concept

We appreciate this isn't intuitive and are in the latter stages of re-working this workflow.
