### ISSUE TITLE
We were unable to fork the sandbox ( Sandbox not found )

### ISSUE THREAD

**Issue by anilkumarbp** [codesandbox/codesandbox-client#4264]
# 🐛 bug report

## Description of the problem
Using the [Import Wizard](https://codesandbox.io/s/github) to load a [repo](https://github.com/anilkumarbp/oauth2-react-intuit) from Github. After import I noticed :

1.) Left Nav options are missing for the sandbox/template:
- Github
- Deployment
- Live
2.) When I click on `fork` i get an error : 
[image](https://ibb.co/jvNWvxh)

## How has this issue affected you? What are you trying to accomplish?
I cannot deploy my app. Every time I import the repo, there is a temporary sandbox that is created but it's not saved. As a result, I am unable to fork the sandbox. The error is : 
```
We were unable to fork the sandbox
Sandbox not found
```

For what its worth, here's the logs from the failed call : 
Request
```
Request URL: https://codesandbox.io/api/v1/sandboxes/exh3o/fork
Request Method: POST
Status Code: 404 
Remote Address: 104.18.23.207:443
Referrer Policy: no-referrer-when-downgrade
```
Response Headers:
```
access-control-allow-credentials: true
access-control-allow-origin: https://codesandbox.io
alt-svc: h3-27=":443"; ma=86400
cache-control: private, max-age=0, no-cache, no-store
cf-cache-status: DYNAMIC
cf-ray: 59c4a452de659394-SJC
cf-request-id: 030ec507c200009394340da200000001
content-length: 17
date: Sun, 31 May 2020 23:58:15 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
status: 404
vary: origin
via: 1.1 google
x-request-id: FhRCU7AWbYXz_nsXQseh
```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |https://codesandbox.io|
| Browser          |Chrome Version 83.0.4103.61|
| Operating System |macOS High Sierra|

**Comment by moaz-gad** [comment]
Same is here.
