### ISSUE TITLE
ModuleNotFoundError with react-stick

### ISSUE THREAD

**Issue by mattfelten** [codesandbox/codesandbox-client#4275]
# 🐛 bug report

## Description of the problem
The project my team works on is using [`react-stick`](https://github.com/signavio/react-stick/) as a dependency and we recently noticed our project no longer works in CodeSandbox. We get a `ModuleNotFoundError` when loading it. Also tried importing it directly (see sandbox link below), and still getting the error.

Not sure if something changed recently with how CodeSandbox handles imports but this used to work fine. I also reported an issue with `react-stick` here https://github.com/signavio/react-stick/issues/84

## How has this issue affected you? What are you trying to accomplish?
Our project can no longer be demoed in CodeSandbox. Pretty painful.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/kind-chatterjee-id2c8?file=/src/App.js

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Whatever is live right now?
| Browser          | Chrome 83.0.4103.61
| Operating System | MacOS

**Comment by CompuIves** [comment]
Heyo! I think the `es` folder is missing in the library: https://unpkg.com/browse/react-stick@4.0.1/ while it's refered as the `module` field. I will make sure that we fallback to `main` if we can't find it, but it might also be worth adding it to the lib!

**Comment by CompuIves** [comment]
A workaround for now would be to refer to `react-stick` as `react-stick/lib`. Which forces it to use the commonjs version.

**Comment by mattfelten** [comment]
Oh cool! Thanks for the reply. That's helpful. I'll crosspost that to the `react-stick` folks.

The strange thing was, this was working a couple weeks ago when we were demoing something using this library. It recently stopped. Maybe there used to be a fallback?

**Comment by yoavniran** [comment]
hey @CompuIves 
I have the same problem with a library of my own (react-uploady)
the module prop is set to the src/index.js but src folder isnt published to npm.
main is set to lib/index.js which is published.
this worked fine in codesandbox up until recently so the fallback was in place but now isnt?
When can we expect this to be fixed?
thanks!

**Comment by CompuIves** [comment]
This should be fixed now!

> The strange thing was, this was working a couple weeks ago when we were demoing something using this library.

We recently moved our bundler to resolve `module` by default instead of `main`, exactly for the type of issue like this one. Local bundlers already resolve `module` by default, and because of that more and more packages referred to a `main` that didn't exist (which gave the same error as the one you're seeing here). From now on we support both!

**Comment by mattfelten** [comment]
Thank you!
