### ISSUE TITLE
ModuleNotFoundError with react-pdf

### ISSUE THREAD

**Issue by IsaacGHoward** [codesandbox/codesandbox-client#4276]
# 🐛 bug report

## Description of the problem
Up until today I've been working on a project that utilizes @react-pdf/renderer but now as of today it has given me an error: 

Could not find module in path: '@react-pdf/unicode-properties' relative to '/node_modules/@react-pdf/textkit/engines/scriptItemizer/index.js'

I know this is a codesandbox issue as I exported the project and it didn't get any errors locally.
## How has this issue affected you? What are you trying to accomplish?

Prevents me from working on my project on codesandbox, which is a pain.
### Link to sandbox: [link](https://codesandbox.io/s/dank-dream-4yuhn) (optional)
Link goes to an example I made to show the issue
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest |
| Browser          | Chrome 83.0.4103.61|
| Operating System | Windows 10 Version 10.0.19041 Build 19041 |

**Comment by yoavniran** [comment]
I've been having the same problem since yesterday.
With a sandbox of my own: https://codesandbox.io/s/hello-react-uploady-edvv3

It worked just fine until very recently. 
The same import works fine on my dev machine or in another editor like stackblitz

**Comment by CompuIves** [comment]
Hm yes, this happens because the library with the issue has a `module` field that refers to a file that doesn't exist. So in this case the library is misconfigured.

I didn't expect this to happen this often, so I'm going to build a check and fallback (so if `module` file doesn't exist default to `main`).

**Comment by CompuIves** [comment]
This should be fixed now!
