### ISSUE TITLE
SyntaxError /src/App.js: Unexpected token 'export'

### ISSUE THREAD

**Issue by ben-rogerson** [codesandbox/codesandbox-client#4277]
# 🐛 bug report

## Description of the problem

I'm seeing the following error in CodeSandbox:

>SyntaxError
/src/App.js: Unexpected token 'export'

The error is new, and the sandbox was working a few days ago. I wonder if a dependency has changed or some rule within code sandbox but there's no visibility within the stack trace.

## How has this issue affected you? What are you trying to accomplish?

My sandboxes refuse to load and display the error above.

### Link to sandbox: [here](https://codesandbox.io/s/react-tailwind-emotion-starter-3d1dl?file=/src/App.js) and [here](https://codesandbox.io/s/react-styled-components-tailwind-twin-starter-f87y7?file=/src/App.js)

**Comment by CompuIves** [comment]
Thanks for the report! I found the issue and have committed a fix now, it should be live in 20min.

**Comment by cristianbote** [comment]
Hey @CompuIves, that is awesome! Thank you! Is there something else that one needs to do, so the error would go away? Like recreate the sandbox and such? I am still getting the error and not sure where to look or what to do.

Thank you so much!

**Comment by CompuIves** [comment]
Ah yes, deploy failed, retrying now!

**Comment by CompuIves** [comment]
Now it's live, sorry for the delay!

**Comment by cristianbote** [comment]
Oh yeah! 💪 Thank you for the deploy!

**Comment by ben-rogerson** [comment]
Thanks for the quick fix, all is working perfectly again :)
