### ISSUE TITLE
Order of imports is reversed, breaks Prism imports

### ISSUE THREAD

**Issue by layershifter** [codesandbox/codesandbox-client#4287]
# 🐛 bug report

## Description of the problem
```
ReferenceError
Prism is not defined
```

In our code we have following:

```js
import * as Prism from 'prismjs/components/prism-core';
import * as PropTypes from 'prop-types';
import * as React from 'react';

// Order of PrismJS imports there is sensitive
import 'prismjs/components/prism-clike';
import 'prismjs/components/prism-json';
import 'prismjs/components/prism-markup';
import 'prismjs/components/prism-bash';
import 'prismjs/components/prism-javascript';
import 'prismjs/components/prism-jsx';
```

On CodeSandbox the order of imports is reversed:

![image](https://user-images.githubusercontent.com/14183168/83512341-5c7bee00-a4d0-11ea-9603-3e3f648381b5.png)

## How has this issue affected you? What are you trying to accomplish?

All our CodeSandboxes are broken :( Prism plugins rely on order (and they are not real CJS/ESM modules), but as you may see it's reversed for some reason.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | https://codesandbox.io/s/jynde |
| Browser          | Chrome |
| Operating System | Windows |

**Comment by CompuIves** [comment]
Thanks for the report! A fix should be live in around ~20min
