### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by miukimiu** [codesandbox/codesandbox-client#4292]
# 🐛 bug report

## Description of the problem

Hello CodeSandbox team! 👋 

Yesterday after https://github.com/codesandbox/codesandbox-client/pull/4269 was merged we could finally link a **codesandbox** from our [live documentation](https://eui.elastic.co/pr_2728/#/).

But today it stopped working and we are running into a different error:

- Chrome: `Unexpected token 'export'` 
- Firefox: `export declarations may only appear at top level of a module`.

Not sure this issue is related with https://github.com/codesandbox/codesandbox-client/issues/4277.

### Link to sandbox: https://codesandbox.io/s/xo3y5

Thanks!

**Comment by CompuIves** [comment]
Hey! Yep, I think that's true. I just merged the PR that fixed it, which should be live within ~15min.

**Comment by miukimiu** [comment]
Thanks again @CompuIves! 😄
