### ISSUE TITLE
Dojo 7 not working. Widget styles is not loading.

### ISSUE THREAD

**Issue by pereibex** [codesandbox/codesandbox-client#4305]
# 🐛 bug report

## Description of the problem
The codesandbox samples in widgets.dojo.io don't work. When doing a cli-create-app and uploading it in codesandbox it does not give errors but styles are not loaded.
everything seems to work but it doesn't load the css of some of the widgets.

## How has this issue affected you? What are you trying to accomplish?
Create a project with Dojo 7

**Comment by garethx** [comment]
Do you have a link to a sandbox where you're seeing the problem? Thanks.

**Comment by pereibex** [comment]
New project with dojo-create-app:
https://codesandbox.io/s/github/pereibex/dojo-create-sample

Widgets demo:
https://codesandbox.io/s/github/dojo/widgets/tree/master/src/examples?fontsize=14&initialpath=%23%2Fwidget%2Fbutton%2Fsandbox%2Fbasic?theme=dojo&module=%2Fsrc%2Fwidgets%2Fbutton%2FBasic.tsx

**Comment by pereibex** [comment]
It is a deployed version of dojo-create-sample with Vercel using codesandbox
https://csb-20wi7-9bvngbct6.now.sh
