### ISSUE TITLE
Crashes when importing @testing-library/react in a test

### ISSUE THREAD

**Issue by eps1lon** [codesandbox/codesandbox-client#4315]
# 🐛 bug report

## Description of the problem

codesandbox is patching `exports` in a way that is incompatible with babel transforms.

```js
Object.defineProperty(exports, "fireEvent", {
  enumerable: true,
  get: function get() {
    return fireEvent;
  }
});
// ...
Object.keys($csb__dom_).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  // @eps1lon: exports.fireEvent only has a getter
  exports[key] = $csb__dom_[key];
});
```

This code is generated from 

Input:
```js
import { fireEvent } from '@testing-library/dom'

export { fireEvent };
```

Output:
```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
Object.defineProperty(exports, "fireEvent", {
  enumerable: true,
  get: function get() {
    return _dom.fireEvent;
  }
});

var _dom = require("@testing-library/dom");
```

-- [babel playground](https://babeljs.io/repl#?browsers=defaults&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzgM2FApgUQG7oHbwC-KUEIcA5AAIzoDOMweA5gLQA2wARlAIZQBPAPQATMhQBQE9AA9IsRCjRZcBOIQDcQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cenv&prettier=false&targets=&version=7.10.2&externalPlugins=)

## How has this issue affected you? What are you trying to accomplish?

use `@testing-library/react` in a test

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 40d9241ff
| Browser          | Chrome 83
| Operating System | Ubuntu 18.04

**Comment by CompuIves** [comment]
This is a really great bug report, looking into it now!

**Comment by CompuIves** [comment]
Hmm, the input you mentioned generates this in our compiler:

```js
"use strict";
Object.defineProperty(exports, "fireEvent", {
  enumerable: true,
  get: function get() {
    return $csb__dom.fireEvent;
  }
});
Object.defineProperty(exports, "__esModule", {
  value: true
});
var $csb__dom = require("@testing-library/dom");
```

I'm going to check if there's a file that does a star export, because that's when we do the `Object.keys` you mentioned in the output.

**Comment by CompuIves** [comment]
Found the issue! It didn't work on this code:

```js
import { fireEvent as fireEvent$1, configure, prettyDOM, getQueriesForElement } from '@testing-library/dom';
export * from '@testing-library/dom';

var fireEvent = function () {
  return fireEvent$1.apply(void 0, arguments);
};


export { fireEvent };
```

since in this case, `fireEvent` is exported twice. Once from `@testing-library/dom` and once from this file. I pushed a fix that will make sure that `fireEvent` of this file will be exported, and that the one of `@testing-library/dom` will be ignored by checking what has been exported already.

**Comment by eps1lon** [comment]
> Hmm, the input you mentioned generates this in our compiler:

Should've clarified the transpilation process:

Original source:
```js
import { fireEvent } from '@testing-library/dom'

export { fireEvent };
```

published, transpiled code:
```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
Object.defineProperty(exports, "fireEvent", {
  enumerable: true,
  get: function get() {
    return _dom.fireEvent;
  }
});

var _dom = require("@testing-library/dom");
```

when inspecting in codesandbox:
```js
Object.defineProperty(exports, "fireEvent", {
  enumerable: true,
  get: function get() {
    return fireEvent;
  }
});
// ...
Object.keys($csb__dom_).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  // @eps1lon: exports.fireEvent only has a getter
  exports[key] = $csb__dom_[key];
});
```

**Comment by CompuIves** [comment]
Ah, yep, that was the exact problem! The fix for this should be live now, could you verify whether it works?

**Comment by eps1lon** [comment]
Works. Thanks :+1:
