### ISSUE TITLE
Can not find a module relative /src/App.js

### ISSUE THREAD

**Issue by vivek12345** [codesandbox/codesandbox-client#4322]
# 🐛 bug report

## Description of the problem
Even though I have installed the dependency `@viveknayyar/re-promise`, I am still facing this error on codesandbox.
```
ModuleNotFoundError
Could not find module in path: '@viveknayyar/re-promise' relative to '/src/App.js'
```

This works perfectly when I npm install it on my machine.

## How has this issue affected you? What are you trying to accomplish?
I am creating an example sandbox for users to look into when they are trying to use my npm package.

### Link to sandbox: [link](https://codesandbox.io/s/focused-paper-42xer?file=/src/App.js) (optional)
https://codesandbox.io/s/focused-paper-42xer?file=/src/App.js

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome Version 83.0.4103.61
| Operating System | macOS Catalina

**Comment by CompuIves** [comment]
Hey! It seems like this package refers with the `browser` field to a file that doesn't exist: https://unpkg.com/browse/@viveknayyar/re-promise@0.0.2/. I think we should fix this on our side, but if you're the owner this is also to let you know 😄 .

**Comment by vivek12345** [comment]
Thank you @CompuIves. That was a great help. I missed changing the filename for the browser field. Thank you for pointing that out. 
Also we can close this issue.

**Comment by vivek12345** [comment]
Closing this issue as it was the library pointing to a non-existent file in it's  browser field specified inside package.json.
