### ISSUE TITLE
CodeSandbox CI: Naming Sandboxes

### ISSUE THREAD

**Issue by wojciechczerniak** [codesandbox/codesandbox-client#4332]
# 🌈 Feature

### Add an option to set names for the sandboxes

Current configuration options does not allow to set a name for each sandbox:
```json
{
  "sandboxes": ["vanilla", "new", "/examples/todomvc"]
}
```

So after they are published by the Codesandbox CI bot it's hard to distinguish which is which:
![Screenshot 2020-06-08 at 22 14 46](https://user-images.githubusercontent.com/4718998/84076164-961f8e00-a9d5-11ea-96a0-0b063b01207f.png)

Would be cool to add names to each entry:

|Sandbox| Source |
|--|--|
|[solitary-morning-4xcih](https://codesandbox.io/s/solitary-morning-4xcih)| Configuration: Vanilla |
|[quirky-gauss-0w133](https://codesandbox.io/s/quirky-gauss-0w133)| Configuration: React |
|[rough-flower-39fd3](https://codesandbox.io/s/rough-flower-39fd3)| Configuration: Vue |
|[quirky-stallman-j4urs](https://codesandbox.io/s/quirky-stallman-j4urs)| Configuration: Angular |

No idea how the syntax could look like. Up to you.

**Comment by SaraVieira** [comment]
Hey!

Thank you for bringing this to our attention, I have just added it to our internal backlog that we do want to make public but for now, it's all in notion.

I will be closing but to make sure what we have in GitHub is just issues and all our feature requests are tracked in our roadmap.

The people needed have also been pinged to make sure this gets done as soon as possible

Again, thank you!
