### ISSUE TITLE
Document how to restart the sandbox and the server

### ISSUE THREAD

**Issue by dandv** [codesandbox/codesandbox-client#4350]
I was looking at https://codesandbox.io/docs/deployment and couldn't find documentation on how to restart the container or the server. I was looking because I've done that before, but today I no longer see those options in the left sidebar. Have they been removed?

**Comment by garethx** [comment]
I responded to your in-app feedback, but just in case this is useful to others too. The project you submitted your message on is a client sandbox, which has no server and therefore those options are not shown. You're only able to restart the server in a container sandbox, like when using the Node environment. See https://codesandbox.io/docs/environment for details on the differences between client and container sandboxes.

**Comment by flickz** [comment]
@garethx Check the docs url again, something is wrong.

**Comment by garethx** [comment]
A bug in github discussions it seems:

https://codesandbox.io/docs/environment

**Comment by dandv** [comment]
Thanks for clarifying the difference between environment types.

Would it worth documenting how to restart containers then?

**Comment by dustinlacewell** [comment]
Too bad this was never addressed.

**Comment by andrasbacsai** [comment]
Containers could be done restarted from the menu. Only works in the container environment.

![image](https://user-images.githubusercontent.com/5845193/114144549-bc73ca00-9915-11eb-959d-d8e435953baf.png)

**Comment by dytra** [comment]
for the latest version of codesandbox, click on the main menu and click restart "Restart Devbox"
![Screenshot 2024-05-14 at 15 57 37](https://github.com/codesandbox/codesandbox-client/assets/3460109/e8cb4adb-ddaf-42ba-af88-87f65365b54c)

**Comment by loopmode** [comment]
Don't have that (anymore?):
![image](https://github.com/user-attachments/assets/fd39e70d-2848-4e3e-a575-a18e7f06d509)

**Comment by CompuIves** [comment]
Right, for sandboxes we don't have this option because they don't run on a server (they completely run in the browser).

Note that in the latest version, you can now also manually hibernate a devbox. When that happens, we create a snapshot (similar to closing your laptop) and when you come back it will continue exactly where it left off.
