### ISSUE TITLE
Organizing templates in dashboard

### ISSUE THREAD

**Issue by cyberbiont** [codesandbox/codesandbox-client#4353]
# 🌈 Feature
Can we have a possibility to organize templates by folders, just like regular sandboxes? To differentiate from regular sandboxes, they could use some special flag.
When you have lots of them, having them all piled up in one "Templates" folder doesn't really help. Also, is you create thematic folders, it's logical to have templates under the same folder together with the sandboxes that are made with the use of it. Then, user should have an ability to filter the dashboard by 'template' flag. 
Even more advanced approach would be to organize everything by tags (Evernote- or Gmail-like).

For now, especially problematic is dealing with Github-synchronized templates, I need to maintain a good number of them, while not being able to see them in dashboard at all. They show up only in "template universe" (if you know their name to search by) and cannot be organized in any way.
So far the only workaround that I came up with is to manually keep some organized list of links to them in a text file, which is not optimal, as you can guess.

**Comment by garethx** [comment]
We're already working on github synced templates. We'll be adding a repos section in an upcoming redesign of the dashboard.

Template folders is something I've wanted myself, let's see who else is interested in this.

**Comment by cyberbiont** [comment]
Fantastic! Can you give me a hint about when this feature is due to arrive?

**Comment by SaraVieira** [comment]
I would say in about a month :/
