### ISSUE TITLE
Illegal invocation error - ESM bundle without export default/module.exports interop

### ISSUE THREAD

**Issue by ryanking1809** [codesandbox/codesandbox-client#4355]
I'm getting an `illegal invocation` error with some library in csb.
Try clicking a button in this sandbox for example useing the `wana` package https://codesandbox.io/s/wana-global-undoredo-2eyk0?file=/src/App.js

I'm told it's because csb is compiling the ESM bundle without `export default`/`module.exports` interoperability. I'm not having issues using the library in other environments.

**Comment by CompuIves** [comment]
Interesting, we do compile the esm bundle with interoperability, but it seems to hang on a native function? Looking into it more...

**Comment by CompuIves** [comment]
Ah, I think I know what needs to happen. For default exports we need to call it without context. We convert it like this:

input:
```js

import queueMicrotask from 'queue-microtask';

let isQueued = false;

function flushAsync() {
  if (!isQueued) {
    isQueued = true;
    queueMicrotask(() => {
      isQueued = false;

      if (flushSync()) {
        flushAsync();
      }
    });
  }
}

```

our output:
```js
"use strict";

var _queueMicrotask = _interopRequireDefault(require("queue-microtask"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var isQueued = false;

function flushAsync() {
  if (!isQueued) {
    isQueued = true;
    _queueMicrotask.default(function () {
      isQueued = false;

      if (flushSync()) {
        flushAsync();
      }
    });
  }
}
```

It's supposed to be:

```js
"use strict";

var _queueMicrotask = _interopRequireDefault(require("queue-microtask"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var isQueued = false;

function flushAsync() {
  if (!isQueued) {
    isQueued = true;
    (0, _queueMicrotask).default(function () {
      isQueued = false;

      if (flushSync()) {
        flushAsync();
      }
    });
  }
}
```

I can take a look this evening to update the transpiler.

**Comment by ryanking1809** [comment]
Great, thanks Ives.
