### ISSUE TITLE
Custom terminal shows, double characters while typing

### ISSUE THREAD

**Issue by soorajshankar** [codesandbox/codesandbox-client#4360]
# 🐛 bug report
## Description of the problem
1. fork nodejs express sandbox using firefox 
2. create new custom terminal
3. type commands, 

current behavior: each character is displayed twice (but it works as single character) 
expected behavior: text should be exact same as we type

<img width="528" alt="image" src="https://user-images.githubusercontent.com/8408875/84498977-44298180-accf-11ea-9ea7-282dc202d65b.png">

## How has this issue affected you? What are you trying to accomplish?
gives incorrect information to the user while typing on the terminal, 
### Link to sandbox: [link](https://codesandbox.io/s/recursing-kilby-1tps8?file=/routes/users.js) (optional)
any sandbox on Firefox 
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Current production
| Browser          | Firefox 
| Operating System | mac os catalina

**Comment by lbogdan** [comment]
Hey @soorajshankar ,

Thanks for the report, unfortunately I can't replicate this in latest Firefox `77.0.1` on Windows 10. Have you tried using a different browser?

**Comment by soorajshankar** [comment]
It works fine now! 
Not sure what happened that time(did not get any error logs), I tried restarting the browser and it was showing the same 😞

**Comment by lbogdan** [comment]
That's very weird, indeed. I'll close this for now, please re-open if it starts happening again.

**Comment by Doomd** [comment]
hi, I was able to replicate this error. I forked a package, made no changes, and opened up a new terminal tab. Here's a screenshot of the problem"
https://www.dropbox.com/s/1rj02a51zolsxkj/screen%20shot%202021-01-23%20at%208.22.17%20am.png?dl=0

This is on MacOS Big Sur 11.1, Chrome Version 87.0.4280.141

**Comment by nnnnicholas** [comment]
I have this problem too! I also started typing in the (a bit confusing) read-only terminal first, too.
