### ISSUE TITLE
ModuleNotFoundError: Could not find module in path: 'readable-stream/writable.js'

### ISSUE THREAD

**Issue by Velenir** [codesandbox/codesandbox-client#4363]
# 🐛 bug report

## Description of the problem
When I add `web3` of versions `>=1.2.7` Codesandbox produces the following error:
```sh
ModuleNotFoundError: Could not find module in path: 'readable-stream/writable.js' relative to '/node_modules/stream-browserify/index.js'
```

Everything works with `web3@<=1.2.6`
Locally all versions work as expected.

**Comment by CompuIves** [comment]
Hm, yes something is going wrong here. It seems that `stream-browserify` requires `readable-stream@^2`, but `readable-stream@^3` is resolved.

**Comment by cherryrap** [comment]
I've got the same bug. Could anyone help to resolve it? Please...

**Comment by fnky** [comment]
I also ran into this issue when trying to import/require [`pouchdb-adapter-memory`](https://github.com/pouchdb/pouchdb/tree/master/packages/node_modules/pouchdb-adapter-memory).

**Comment by CompuIves** [comment]
This case is slightly different, because it's related to handling the resolving of transient dependencies. I have the feeling that here it doesn't work 100% because `readable-stream` is actually included in a hardcoded dependency as well. Looking into it...

**Comment by siddharthkp** [comment]
Hi!

We just deployed a fix yesterday which resolves some of the issues related to nested dependencies. If you're curious, here's [the long version](https://github.com/codesandbox/codesandbox-client/issues/4957#issuecomment-702138887). 

The sandbox mentioned in the description ([web3@1.2.9](https://codesandbox.io/s/web3129-error-otzsx)) now works perfectly now 💯 

Sorry it took a while to figure this out, this was a sneaky bug!
