### ISSUE TITLE
Error while trying to navigate from the Sandbox to Create New Sandbox

### ISSUE THREAD

**Issue by ross-u** [codesandbox/codesandbox-client#4366]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 83.0.4103 | OS X 10.15.5           | 26943d313          |

  **Route:**
  https://codesandbox.io/s/busy-bas-87msp

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'title' of undefined
  TypeError: Cannot read property 'title' of undefined
    at https://codesandbox.io/static/js/app.09a226fa8.js?_sw-precache=b75608997b4f8822e157831b2aa584e0:571:924362
    at ua (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1733563)
    at Ka (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1741828)
    at qa (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1741647)
    at Es (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1782301)
    at ml (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1764402)
    at hl (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1764327)
    at il (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1761655)
    at https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1719838
    at https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1795174
  
    in Unknown
    in DropTarget(Component)
    in div
    in Kc
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in Files___StyledCollapsible
    in hl
    in is
    in div
    in je
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by lbogdan** [comment]
`directories.find()` returns `undefined` here:

https://github.com/codesandbox/codesandbox-client/blob/66714e552553a38475a9386e34b281a201dbddb1/packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/index.tsx#L309

and here:

https://github.com/codesandbox/codesandbox-client/blob/66714e552553a38475a9386e34b281a201dbddb1/packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/index.tsx#L339

**Comment by CompuIves** [comment]
I wonder how that can be `undefined`, something must be happening to get in an intermediate state or something... or wait... I have an idea

**Comment by CompuIves** [comment]
Why do we even find title there if it's already in props?
