### ISSUE TITLE
Cannot set up the project locally on Windows

### ISSUE THREAD

**Issue by glenkitchen** [codesandbox/codesandbox-client#4367]
# 🐛 bug report

## Description of the problem
Running CodeSandbox locally on Windows has some pitfalls and does not work. 

1. Instructions at [Setting Up the project locally](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md#setting-up-the-project-locally) should highlight these issues on windows:
* Use [nvm-windows](https://github.com/coreybutler/nvm-windows) instead on [fnm](https://github.com/Schniz/fnm) to manage the node version on Windows.
* Use a Unix shell like bash, or cross platform Powershell, to run the scripts. A native windows shell like Command.exe will not work because some of the Npm scripts contain single quotes which is not supported on a windows shell. E.g. The watch and build scripts [here](https://github.com/codesandbox/codesandbox-client/blob/master/packages/template-icons/package.json)

2. Webpack does not compile
app: [HPM] Proxy created: /  -> wss://codesandbox.io
app: [HPM] Proxy created: /  -> https://codesandbox.io
@codesandbox/components: 9:12:33 AM - Found 0 errors. Watching for file changes.
@codesandbox/common: 9:12:44 AM - Found 0 errors. Watching for file changes.
@codesandbox/common:
9:12:44 AM - File change detected. Starting incremental compilation...
@codesandbox/common: 9:12:46 AM - Found 0 errors. Watching for file changes.
app: √ Webpack: Compiled with some errors in 37.68s
dbox/common: 9:12:46 AM - Found 0 errors. Watching for file changes.
app: √ Webpack: Compiled with some errors in 37.68s
app: Failed to compile after 37.853s.
app: Error in c:/dev/codesandbox-client/packages/app/src/app/utils/prettify.js 10:22
app: Module parse failed: Unexpected token (10:22)
app: You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https
app: | } from './monaco-index-converter';
app: |
app: > function getMode(title: string) {
app: |   if (/\.jsx?$/.test(title)) {
app: |     return 'babylon';
app:  @ ./src/app/overmind/effects/vscode/index.ts 20:0-50 166:81-89
app:  @ ./src/app/overmind/effects/index.ts
app:  @ ./src/app/overmind/index.ts
app:  @ ./src/app/index.js
app:  @ multi webpack-dev-server/client?/ ./config/polyfills.js ./src/app/index.js
app: Error in c:/dev/codesandbox-client/packages/app/src/sandbox/compile.ts 34:11
app: Module parse failed: Unexpected token (34:11)
app: You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https            

## How has this issue affected you? What are you trying to accomplish?
Unable to run CodeSandbox locally

### Link to sandbox: [link]() (optional)
N/A

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | NA
| Browser          |  NA
| Operating System | Windows 10 Pro
| Node Version | v10.16.2
| Yarn Version | v1.22.4
| Lerna Version |  v3.16.4

**Comment by glenkitchen** [comment]
Ok, got it working, with fresh setup that followed these steps.
* Ensured my local node version was the same one specified in `.nvmrc`
* Removed the single quotes around `.ts,.tsx` in the `watch` and `build` script [here](https://github.com/codesandbox/codesandbox-client/blob/master/packages/template-icons/package.json)
* Ran `yarn` and `yarn start` with Git bash shell.

CodeSandBox team. I can add some notes on local Windows setup to the CONTRIBUTING doc, if you feel this is worthwhile?

**Comment by pedroblanc** [comment]
This issue helped me a lot. Spent a whole day trying to build before finding it and fixing the single quotes problem. 


It seems that removing the single quotes would avoid breaking the build in windows but I will not have access to a linux box in the coming weeks to validate if it breaks the linux build.    :(
