### ISSUE TITLE
Vue / Vuex sandbox behaviour seems to have changed

### ISSUE THREAD

**Issue by davestewart** [codesandbox/codesandbox-client#4376]
# 🐛 bug report

## Description of the problem

A Vue/Vuex getter used to display the derived value, but perhaps a recent update displays the string value of the function instead:

![image](https://user-images.githubusercontent.com/132681/84691484-1f861180-af3c-11ea-8be1-9413d489f466.png)

## How has this issue affected you? What are you trying to accomplish?

My demos for Vuex Pathify no longer seem to work on Code Sandbox (they have worked for the last few years).

This demo user to display "Hello World" on screen, now it displays "function get() { return get; }":

https://codesandbox.io/s/vuex-pathify-main-demo-vmgsd?file=/src/store.js

This is the actual function returned by the Vuex Pathify helper, rather than the derived value the getter gets.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest
| Browser          | Chrome
| Operating System | OSX

**Comment by CompuIves** [comment]
Ohh wow this is really peculiar. Two vars conflicting, taking a look if I can fix this easily now.

**Comment by davestewart** [comment]
WFF! (World's Fastest Fix!)

Thanks @CompuIves.

How long before things go live in CS World?

**Comment by CompuIves** [comment]
Should be ~10-15min!

**Comment by davestewart** [comment]
Legend. Thanks for the hard work!
