### ISSUE TITLE
Array destructuring a non-iterable fails obscurely

### ISSUE THREAD

**Issue by vcarl** [codesandbox/codesandbox-client#4377]
# 🐛 bug report

## Description of the problem

Array destructuring fails with an obscure Babel helper error. [Babel recently improved the error](https://github.com/babel/babel/pull/11264) emitted here, so this might be solved by updating deps.

Partial stack trace:
```
TypeError: arr[Symbol.iterator] is not a function
    at _iterableToArrayLimit (https://5otb7.csb.app/node_modules/@babel/runtime/helpers/iterableToArrayLimit.js:8:39)
    at _slicedToArray (https://5otb7.csb.app/node_modules/@babel/runtime/helpers/slicedToArray.js:8:33)
    at Object.eval (https://5otb7.csb.app/src/index.test.js:14:53)
    at https://codesandbox.io/static/js/vendors~jest-lite.d7cf4386a.chunk.js:1:199229
```

## How has this issue affected you? What are you trying to accomplish?

I was building an interview problem sandbox, and while refactoring a Jest test I hit a wall because of this error. Pointed me to line 1 column 1, I ultimately found it by disabling sourcemaps, hunting through network tab for likely source files, and setting breakpoints until I narrowed it down.

### Link to sandbox: 

[minimal reproduction](https://codesandbox.io/s/brave-silence-vigik?file=/src/index.js)

[minimal Jest reproduction, with broken highlighted line](https://codesandbox.io/s/awesome-http-5otb7?file=/src/index.test.js)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest |
| Browser          | Chrome latest |
| Operating System | MacOS |

**Comment by christianalfoni** [comment]
Hi there @vcarl and thanks for taking the time to dive into the issue! 😄 

We will update our babel dependencies and let you know when it is done!

**Comment by christianalfoni** [comment]
Hi there @vcarl,

Just wanted to say that this is currently a bit down on our list as there is no pressing issue with the babel dependency. Really appreciate this report as it did bump the issue up on our list, but it will probably take a while to get this specific issue fixed... unless we meet a more pressing issue which forces us to put this way up on the list 😄 

I will close this issue for now, but please reopen if you meet other issues.
