### ISSUE TITLE
[CI] Types not working in codesandbox CI build

### ISSUE THREAD

**Issue by phryneas** [codesandbox/codesandbox-client#4378]
# 🐛 bug report

## Description of the problem

The sandboxes built by the CodeSandbox CI for `@reduxjs/toolkit` seem to contain the built library, but accessing anything from the library gives error messages, as apparently the types are not recognized.
Runtime code works, so it seems to be a TypeScript problem.

This is not a problem when installing the CSB build locally.

### Link to sandbox:
[This is an example sandbox with the problem](https://codesandbox.io/s/sweet-wave-sbn3n?file=/src/index.ts), built from [this PR](https://github.com/reduxjs/redux-toolkit/pull/610#issuecomment-643658806).

Doing a `yarn add https://pkg.csb.dev/reduxjs/redux-toolkit/commit/0f880090/@reduxjs/toolkit` locally does not have the same problems.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | CI
| Browser          | Firefox, Chrome, Edge
| Operating System | Linux, Windows

**Comment by CompuIves** [comment]
Thanks for the notice and sorry for the inconvenience! It should work as expected now!
