### ISSUE TITLE
Menu moves right before clicking on an item

### ISSUE THREAD

**Issue by chancestrickland** [codesandbox/codesandbox-client#4407]
# 🐛 bug report

## Description of the problem

When clicking on the menu button for a sandbox in my dashboard, right after moving the pointer into the menu it repositions itself, meaning that unless I wait for that to happen I end up clicking the wrong menu item. Sad panda is sad.

![GIF reproduction](https://media.giphy.com/media/ggiv0r39ti943aOCGp/giphy.gif)

Seems like the kind of thing that @siddharthkp would fix up nicely, eh?

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Firefox Developer 77.0
| Operating System | MacOS 10.15.3

**Comment by chancestrickland** [comment]
One additional detail I noticed is that this only seems to happen if the menu positions itself to expand up rather than down, presumably to avoid collisions in the bottom of the window. By default the menu expands towards the bottom and it doesn't move in that case.

**Comment by garethx** [comment]
We're working on a design update to the dashboard, so I'll flag this to make sure it's no longer an issue in the new version. Thanks

**Comment by siddharthkp** [comment]
@chancestrickland hey! I forked the menu-button from reach to create a context menu ;) So this is fixed in the new dashboard

**Comment by siddharthkp** [comment]
This is now solved with the new dashboard :)
