### ISSUE TITLE
Frequently getting "It looks like your session has expired" error

### ISSUE THREAD

**Issue by sunnyssr** [codesandbox/codesandbox-client#4432]
# 🐛 bug report
![image](https://user-images.githubusercontent.com/41870839/85211546-f1536800-b367-11ea-9276-2cb55bb6a21c.png)

## Description of the problem
I am getting an error that your session has expired when I try to open a specific branch from GitHub Repo. But when I edit a file and save it. Then fork take place without any issue.
This means it shows me that session has expired when it is not.

## How has this issue affected you? What are you trying to accomplish?
It makes me feel like I have not used CSB for days that's why it is asking me to log in but that's not a case. Issue still persists after clearing cache.
### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/nkdem?file=/package.json
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
Chrome
| Operating System |

**Comment by christianalfoni** [comment]
Hi there @sunnyssr and thanks for the issue!

This was an unfortunate consequence of a new feature we are releasing. It did not really have an affect, as you point out, but very confusing! 

We deployed a new version yesterday that fixed this 😄

**Comment by DavidQuartz** [comment]
I face this problem of "Your session seems to be expired, please log in again..." when I try to make any of my sandboxes private. Makes it impossible to do so.

**Comment by christianalfoni** [comment]
Hi there @DavidQuartz,

You have to be a PRO user to make sandboxes private, so this button should actually not be available, a mistake by us 😄 

This is being fixed now so that the button is disabled. Please sign up for PRO if you want private sandboxes.

And thanks for bringing it to our attention! 😄  👍

**Comment by DavidQuartz** [comment]
Haha okay then.
