### ISSUE TITLE
Renaming folder causes all items in folder to appear as deleted without possibility of recovery.

### ISSUE THREAD

**Issue by vurghus-minar** [codesandbox/codesandbox-client#4435]
# 🐛 bug report

## Description of the problem
Renaming folder causes every items in folder to appear as deleted. It is not possible to open any renamed folder item after the parent folder has been renamed. 

See screenshot

![download](https://user-images.githubusercontent.com/32111718/85253508-62ca0e00-b46f-11ea-8f3d-70fc89f34314.png)

The project has to be reloaded to be able to use the updated scaffolding.

## How has this issue affected you? What are you trying to accomplish?
This is a real no go since this takes away the ability to modify any project scaffolding without having to reload the entire project.

### Link to sandbox: [link]() (optional)
(https://codesandbox.io/s/react-calendar-vytpi)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Google Chrome Version 83.0.4103.106 (Official Build) (64-bit)
| Operating System | Windows 10 Pro v1909

**Comment by CompuIves** [comment]
I'm able to reproduce this problem. Will come up with a fix today!
