### ISSUE TITLE
Cannot create repository from Static Sandbox

### ISSUE THREAD

**Issue by canal874** [codesandbox/codesandbox-client#4436]
# 🐛 bug report

## Description of the problem

The input field and button for "Create Repository" are always not shown for forked sandbox when creating Static Sandbox.

Only "Commit changes" button is shown.

It worked correctly 4 days ago.

## How has this issue affected you? What are you trying to accomplish?

I would like to create new repository from forked sandbox.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 0f9c97992 |
| Browser          |   chrome  83.0.4103.106 |
| Operating System | Windows 10 |

**Comment by christianalfoni** [comment]
Hi @canal874 and thanks for reporting!

Sorry, we are officially releasing the new Github flow shortly and we missed this part 😄 

It should be fixed and live already!
