### ISSUE TITLE
Wrong branch name shown on GitHub Section

### ISSUE THREAD

**Issue by sunnyssr** [codesandbox/codesandbox-client#4439]
# 🐛 bug report
![image](https://user-images.githubusercontent.com/41870839/85280867-a2f8b300-b4a6-11ea-9e8c-3a8af0f38f3e.png)

## Description of the problem
On GitHub section, it shows wrong text that I am commiting to master even though sandbox is of different branch.
## How has this issue affected you? What are you trying to accomplish?
It shows that I am commiting changes to master but actually changes are being committed to different branch. While the text in upper area says clearly that I can commit directly to `branch-name`.
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by christianalfoni** [comment]
Hi @sunnyssr and thank you for your report!

We have a pending fix on this now and will be merged soon 😄 👍

**Comment by CompuIves** [comment]
Fixed 😄 !!
