### ISSUE TITLE
Codesandbox didn't build after update with master

### ISSUE THREAD

**Issue by KatarzynaQA** [codesandbox/codesandbox-client#4441]
# 🐛 bug report

## Description of the problem

Codesandbox build failed and Codesnadbox link didn't build.
When we trying update branch to the master for our project on GitHub, error appears.
```pmcarbon-react-30.1.0.tgz
{ [Error: EACCES: permission denied, mkdir '/tmp/output/carbon-react']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/tmp/output/carbon-react' }
Done in 456.40s.
```

### Link to sandbox: [link]() (optional)
https://ci.codesandbox.io/status/Sage/carbon/pr/3002/builds/34014
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome
| Operating System | CI - GitHub actions

**Comment by jamime** [comment]
some other examples
https://ci.codesandbox.io/status/Sage/carbon/pr/3007/builds/34034
https://ci.codesandbox.io/status/Sage/carbon/pr/3006/builds/33616
https://ci.codesandbox.io/status/Sage/carbon/pr/3006/builds/33592
https://ci.codesandbox.io/status/Sage/carbon/pr/3002

We're also getting a different error
https://ci.codesandbox.io/status/Sage/carbon/pr/3006
```
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1592831236470-0.3024168853098106/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> carbon-react@30.1.0 copy-files /tmp/192f050a
> cpx "src/**/!(*.js|*.md|*.mdx|*.stories.*|*.snap|docgenInfo.json)" lib

sh: 1: cpx: not found
```

`cpx` is a dev-dependency so it should be available.

**Comment by lbogdan** [comment]
Hey @KatarzynaQA , @jamime ,

We indeed had some issues with CodeSandbox CI during the weekend and part of today, causing weird build failures. They should be fixed now, and I also triggered a rebuild of those two PRs - 3006 and 3007 - so everything should be green now. Thanks for reporting and sorry for the inconvenience!

Closing this for now, please re-open if the issues come back.
