### ISSUE TITLE
Preview refreshes without re-initializing the scripts.

### ISSUE THREAD

**Issue by jansiegel** [codesandbox/codesandbox-client#4448]
# 🐛 bug report

## Description of the problem
In some cases, after refreshing the page, the preview doesn't contain changes made in the `.js` files. For example, when I include a `index.js` file at the bottom of the `<body>` tag, and:

index.html:
```html
<div class="example">
  Original content.
</div>
```

index.js:
```js
document.querySelector(".example").innerHTML = "Updated content";
```

I can see "Original content" in the preview.

I did some research, and it looks like initially the scripts are invoked (in my example, the `.example` div gets its contents changed) and then DOM gets re-rendered, but the scripts included in the HTML don't get re-run (so my `.example` div is reverted to its original value).

The problem is, this issue is hard to reproduce - the same sandbox works different in different browsers and incognito/regular browser modes, which makes me think it might have something to do with stuff stored in localStorage maybe...?

## How has this issue affected you? What are you trying to accomplish?
It makes the sandboxes fail randomly.

### Link to sandbox: [link]() (optional)
I can prepare a link to a sandbox, but it won't make any difference, as it is really random.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome
| Operating System | macOS Catalina

**Comment by garethx** [comment]
Does the problem persist if you enable the hardReloadOnChange option in a sandbox config file? ( Details in https://codesandbox.io/docs/configuration#sandbox-configuration)

**Comment by jansiegel** [comment]
> Does the problem persist if you enable the hardReloadOnChange option in a sandbox config file? ( Details in https://codesandbox.io/docs/configuration#sandbox-configuration)

@garethx, thanks for responding so quickly! No, it doesn't seem to have an effect on the issue whether I have it enabled or disabled. 

BTW, I didn't mention it in the description, but maybe it helps - after refreshing the preview iframe or changing anything in the editor section, the preview refreshes properly and works fine until the next page refresh.
