### ISSUE TITLE
css module doesn't work in Vanilla Typescript template

### ISSUE THREAD

**Issue by csr632** [codesandbox/codesandbox-client#4452]
# 🐛 bug report

## Description of the problem

css module doesn't work in Vanilla Typescript template

### Link to sandbox

https://codesandbox.io/s/css-module-ts-7b4ff?file=/src/index.ts

The style object from `.module.css` is an empty object.
If I change `index.ts` to `index.js`, css module works.

**Comment by christianalfoni** [comment]
HI @csr632 and thanks for reporting!

I have booked a session tomorrow to look into this, will keep you posted 😄

**Comment by christianalfoni** [comment]
Hi @csr632 and sorry for the late response,

Css modules is a feature enabled in certain CLIs. For example create-react-app, vue etc. Your sandbox is based on parcel, which does not support css-modules out of the box.

Codesandbox actually uses its own bundler, which actually does support css-modules, and we are working on how to make it more explicit to our users how the bundling works and how they can turn on and off features related to the bundler.

The "parcel template" is a bit misleading, we are not actually bundling with parcel.

Let reopen if you have any questions related to this, but you will see changes to this in the future 😄
