### ISSUE TITLE
Keys not working

### ISSUE THREAD

**Issue by BullDogPatch** [codesandbox/codesandbox-client#4457]
# 🐛 bug report

## Description of the problem

Sorry if this sounds a little noob.
I was searching how to get emmet to work for jsx, and I played in settings and now when I try to type anything in the sandbox none of my laptop keys are working properly.
for example if I press D, it is deleting lines.
Also in the bottom left corner it says --INSERT--
Nothing seems to be working properly now

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by lbogdan** [comment]
Hey @BullDogPatch ,

Can you please provide some more details about this, which keys are you referring to? Thanks!

**Comment by BullDogPatch** [comment]
Sorry if this sounds a little noobish.
I was searching how to get emmet to work for jsx, and I played in settings and now when I try to type anything in the sandbox none of my laptop keys are working properly.
for example if I press D, it is deleting lines

**Comment by BullDogPatch** [comment]
Also space bar isn't working, instead of space, it is going through letters as if right arrow key would. Hope this makes sense

**Comment by BullDogPatch** [comment]
Fixed the issue
