### ISSUE TITLE
Saving issue after reloading editor

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#4460]
# 🐛 bug report

## Description of the problem
If you make an edit to a file, switch to a different file and don’t save, then reload the editor. After reloading you see the file having an unsaved change indicator, but hitting ‘save all’ doesn’t save the file and thus it blocks being able to commit the change to GitHub. If that edited file is a ‘normal’ file like index.html, if you go to the file then you can save the change. But if it’s a file like .prettierrc, then you can’t save the change even if you open the file in the editor, and ‘save all’ still doesn’t work. It seems like you have to discard the change to progress.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest
| Browser          | Chrome
| Operating System | Mac OS X

**Comment by christianalfoni** [comment]
Got a PR on a fix here 😄  : https://github.com/codesandbox/codesandbox-client/pull/4486
