### ISSUE TITLE
We were unable to create your commit. Please try again or report the issue. Request entity too large

### ISSUE THREAD

**Issue by Eventect** [codesandbox/codesandbox-client#4463]
# 🐛 bug report

## Description of the problem
Not able to commit changes to existing branch on github. A message stating: "We were unable to create your commit. Please try again or report the issue. Request entity too large" appears.

## How has this issue affected you? What are you trying to accomplish?
Trying to commit changes to GitHub private repo from a private sandbox. The sandbox was created by checking out the same repository

### Your Environment
macOS 10.15.5, Chrome 83.0.4103.116 
<img width="861" alt="Screenshot 2020-06-24 at 22 13 24" src="https://user-images.githubusercontent.com/470638/85622973-f49c6b80-b667-11ea-83c1-127631bbe77a.png">

**Comment by SaraVieira** [comment]
Hey!

Were you trying to commit large files?

**Comment by Eventect** [comment]
<img width="399" alt="Screenshot 2020-06-24 at 22 49 26" src="https://user-images.githubusercontent.com/470638/85626227-ffa5ca80-b66c-11ea-83cc-87425cbf8787.png">

**Comment by Eventect** [comment]
19 files of text, let's say 50 LOC each... I would say no...

**Comment by Eventect** [comment]
Tried again now, I was able to commit successfully the changes.

**Comment by SaraVieira** [comment]
We just deployed a fix :)
