### ISSUE TITLE
Token commits autocompletion on period (.) rather than enter key

### ISSUE THREAD

**Issue by mruzekw** [codesandbox/codesandbox-client#4464]
# 🐛 bug report

## Description of the problem

Token commits autocompletion on period (.) rather than enter key

All I did was type `action.` and it autocompleted to `applicationCache.`. I did not press enter or tab.

See video:

https://drive.google.com/file/d/1M_aB60AIzOE0IyNp7Y9W2Ah5KX8hYXvl/view?usp=drivesdk

## How has this issue affected you? What are you trying to accomplish?

I was trying to write `switch(action.type)` for a reducer I was writing.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome Version 83.0.4103.106 (Official Build) (64-bit)
| Operating System | MacOS 10.15.4

**Comment by garethx** [comment]
I've requested access to the video since it seems like it's private.

**Comment by mruzekw** [comment]
Updated the video link. Should have access now. Let me know if you’re still can’t get to it.

**Comment by garethx** [comment]
Thanks @mruzekw, I can view it now. Will take a look.
