### ISSUE TITLE
Could not find module in path

### ISSUE THREAD

**Issue by snide** [codesandbox/codesandbox-client#4470]
# 🐛 bug report

## Description of the problem

Hello again :wave:

Looks like the issue with dynamic imports that was fixed in #4294 and #4269 came back around last week. Thanks again for the great work on this repo. I'm sure dynamic imports are tricky in such a dynamic environment.

cc @miukimiu who reported the last two

### Link to sandbox: [https://codesandbox.io/s/vigorous-snow-ts3ce?file=/index.js](https://codesandbox.io/s/vigorous-snow-ts3ce?file=/index.js)

**Comment by CompuIves** [comment]
Ah, I'm so sorry for that! I'm going to add that sandbox to our integration tests so it won't happen again. A fix will be live in probably ~20 minutes!

**Comment by snide** [comment]
No worries! Appreciate the speedy fix.
