### ISSUE TITLE
Invalid left-hand side expression in prefix operation

### ISSUE THREAD

**Issue by supersonicclay** [codesandbox/codesandbox-client#4476]
# 🐛 bug report

## Description of the problem

Getting an error: "Invalid left-hand side expression in prefix operation" when running in codesandbox.io. However, if you download as a zip and run locally, it works (no error).

## How has this issue affected you? What are you trying to accomplish?

Trying to import the `h3-js` npm library. 

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome
| Operating System | OSX
| Local node version | 10.16
| Local npm version | 6.9

**Comment by CompuIves** [comment]
Hey! Thanks for reporting this, I found the fix and will commit it any moment!

**Comment by amannn** [comment]
@CompuIves I just got the same error when importing the latest `d3` version: https://codesandbox.io/s/sparkling-glitter-lgz8n?file=/src/App.js`.

It seems to already be the case when you import from `d3-zoom`.

Is this a new error or was there potentially a regression?

**Comment by CompuIves** [comment]
Interesting, definitely seems like a new one. Going to do some testing on this today...
