### ISSUE TITLE
Document has a typo on an image?

### ISSUE THREAD

**Issue by sedgwickz** [codesandbox/codesandbox-client#4480]
When I read the codesandbox document just now, I found maybe there is a typo on an image there. Due to I am not good at PS, so if it is true, please assign UI guys to correct it. 

The button text should be `Resetart -> Restart`?
[https://codesandbox.io/docs/secrets#what-are-secrets?]()
![](https://codesandbox.io/static/5de2ac787740f1a4a0a597e69a7eb3ed/6ff5e/secrets-2.png)

**Comment by DannyRuchtie** [comment]
Hi @sedgwickz ,
Thx for pointing this out. A fix is on the way
https://github.com/codesandbox/codesandbox-client/pull/4482
