### ISSUE TITLE
Unable to create the repo. Please refresh and try again or report issue. Request failed with status code 500

### ISSUE THREAD

**Issue by esau-morais** [codesandbox/codesandbox-client#4481]
![Captura de Tela (55)](https://user-images.githubusercontent.com/55207584/85929861-7968ce80-b88e-11ea-8d3a-455f2642f762.png)
# 🐛 bug report

## Description of the problem

I'm trying for a long time and continue with that

### Link to sandbox: [link](https://codesandbox.io/s/cursocarolina-134el)

**Comment by garethx** [comment]
Thanks for reporting. The linked sandbox is either private or has been removed. Do you have a public or unlisted link to a sandbox you can provide? Thanks

**Comment by esau-morais** [comment]
I removed, but I'll provid here again:
[**sandbox link**](https://codesandbox.io/s/festive-hugle-8k3oo)

**Comment by garethx** [comment]
I can't reproduce in a fork of the project. Does the repo name you're providing already exist in your GitHub account?

**Comment by esau-morais** [comment]
Nop. I tried many times **with different names**, but the error continues. I really don't know what's the problem.

**Comment by esau-morais** [comment]
I tried with the codesandbox react template and I got it.

**Comment by martinoroma88** [comment]
I have similar issue with a static template. Not able to create GitHub repo from Sandbox.

**Comment by nwohater** [comment]
I have same problem with new repos (static and react).

**Comment by armchairdeity** [comment]
Having the same problem now... this exact issue. Thing is, it creates thee repo, but tells me it didn't/couldn't, and I can't force it to use the repo, or supply an existing one, so the process of pushing my codebase to GitHub is just broken.

**Comment by chaseadamsio** [comment]
I realized this happened because the new repository was getting created with `master` and it seems like the sandbox I was forking expected it to be `main`. 

I updated it in my [repository settings](https://github.com/settings/repositories) and now I no longer get this error and forking works as expected.

![image](https://user-images.githubusercontent.com/1024544/113484315-85587100-945c-11eb-916f-846bbd39c705.png)

**Comment by p-dabrowski** [comment]
Same here, still the same bug since April 2020? :o

**Comment by nchathu2014** [comment]
Change the repository default branch to 'main'. It worked for me as explained in https://github.com/codesandbox/codesandbox-client/issues/4481#issuecomment-812886655

**Comment by JakariaJishan** [comment]
i changed the repository default branch to 'main'. but its not working

**Comment by jineeshjohn** [comment]
Following this [comment](https://github.com/codesandbox/codesandbox-client/issues/6556#issuecomment-1078777593) fixed for me

**Comment by Lumi785** [comment]
my github repository default branch is 'main', but still got this error,

**Comment by Simonomi5** [comment]
> I realized this happened because the new repository was getting created with `master` and it seems like the sandbox I was forking expected it to be `main`.
> 
> I updated it in my [repository settings](https://github.com/settings/repositories) and now I no longer get this error and forking works as expected.
> 
> ![image](https://user-images.githubusercontent.com/1024544/113484315-85587100-945c-11eb-916f-846bbd39c705.png)

This works!
