### ISSUE TITLE
Support for official create-react-app templates

### ISSUE THREAD

**Issue by nickmccurdy** [codesandbox/codesandbox-client#4485]
# 🌈 Feature

## create-react-app's template support

Create React App now has official support for [custom templates](https://create-react-app.dev/docs/custom-templates/). Instead of getting the usual stuff in `src`, you can customize the generated files by using your own package to generate dependencies, JS files, and other project setup files. The default CRA template has since been moved to the `cra-template` package, and the `--typescript` flag has been migrated to the `cra-template-typescript` package. It's also easy to specify a custom template at the command line: you just need to run `create-react-app` with `--template` and then the suffix of the package (`cra-template-` is used as the prefix). There's already a growing community of templates for CRA based on TS, Redux, UI libraries, more minimal file structures, and more.

## Limitations with Code Sandbox's template support

Code Sandbox also has its own separate templating system. As far as I understand, Code Sandbox templates either need to be created officially or as normal sandboxes in template mode. This works well for basic templating, but I've been noticing some limitations that can make it feel less productive than native CRA templates.

My main issue is that the default React and React TypeScript templates seem to generate very few files, which can make it more difficult to set up things like tests and service workers, which are usually generated with CRA's official default templates. This also makes it more difficult to migrate to a "full" React app on GitHub. While Code Sandbox's GitHub export feature is very easy to use, I often need to generate a new CRA app and copy over files to the GitHub repository as it scales, so it would be convenient if I could just have that template from the start in Code Sandbox.

It would also be nice to take advantage of custom CRA templates like Redux's. Even if it's possible to manually copy these files to a Code Sandbox and mark it as a template, it would be easier to just maintain the original template package and have Code Sandbox rely on it directly.

## User interface suggestions

Code Sandbox already has convenient package search for dependencies, it would be great to reuse this to discover CRA templates on npm. It would also be nice to highlight some CRA templates in another sidebar tab on the Code Sandbox template selector (in theory the existing templates could even be migrated eventually). Finally, CRA templates could be pinned just like normal Code Sandbox templates making them easier to use frequently.

## Implementation suggestions
Code Sandbox could run CRA with the template package in a container and then copy the files into a new sandbox or imported template. Alternatively, files could be statically analyzed from the template package to make it easier to run the template generation, but that would require reimplementing parts of CRA's templating system, like how it can merge template.json into the default generated package.json. Overall from a technical perspective, the biggest advantage would be that you'd only have to develop a template once for both CRA and Code Sandbox, and Code Sandbox users would just get the benefits of the template without having to import or copy files. This also means that Code Sandbox could rely on mature community templates directly rather than having to maintain React templates separately.

**Comment by nickmccurdy** [comment]
Issue not resolved.

**Comment by SaraVieira** [comment]
Hey!

Thank you for bringing this to our attention, I have just added it to our internal backlog that we do want to make public but for now, it's all in notion.

I will be closing but to make sure what we have in GitHub is just issues and all our feature requests are tracked in our roadmap.

As for the fact that the template has a lot of missing files that was at the time requested by the react team to make it less confusing for new users. 

If you want a quick fix you can also use the cli: https://github.com/codesandbox/cli to upload the files

Again, thank you!
