### ISSUE TITLE
💥 Crash Report

### ISSUE THREAD

**Issue by fantasticsoul** [codesandbox/codesandbox-client#4491]
code demo link 
https://codesandbox.io/s/concent-guide-xvcej

it seems jsconfig.json 's compilerOptions.baseUrl not works any more
```
{
  "compilerOptions": {
    "baseUrl": "src",
    "experimentalDecorators":true
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by CompuIves** [comment]
Looking into this! Will have a fix in ~1 hour.

**Comment by CompuIves** [comment]
Should be live in 20min!

**Comment by fantasticsoul** [comment]
thx
