### ISSUE TITLE
Sandpack package not working out of the box

### ISSUE THREAD

**Issue by NinoMaj** [codesandbox/codesandbox-client#4497]
# 🐛 bug report

## Description of the problem
Packages `sandpack` or `react-sandpack` don't work without setting older version of bundlerURL  `bundlerURL="https://sandpack-0-0-61.codesandbox.io/"`. Packages by default will use current package version which is `0.0.62`.

### Your Environment
Operating system: Newest version of macOS
Browser: tried all browsers. 

[Example repo](https://github.com/NinoMaj/sandpack-not-working)

**Comment by CompuIves** [comment]
Hey! Yep, seeing it now too, seems like a bad build has been published. I just republished as `0.0.63`, and everything seems to work now!
