### ISSUE TITLE
Console.trace does not display anything in the console window

### ISSUE THREAD

**Issue by rlhaben** [codesandbox/codesandbox-client#4500]
# 🐛 bug report

## Description of the problem
I am used to using console.trace to checkout how the context of a function call. But when I use that in codesandbox, nothing is displayed. I can use console.error to get a trace and it seems to work ok but I should be able to use console.trace. It seems that this should just be there since it is based on Chrome devtools.
## How has this issue affected you? What are you trying to accomplish?
Diagnostics on call sequences iin ReactJs
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Current Live 
| Browser          | Chrome Version 83.0.4103.116 (Official Build) (64-bit)
| Operating System | Windows 10

**Comment by siddharthkp** [comment]
Hi!

Thanks for your feedback!

We use https://github.com/samdenty/console-feed to support the console output shown in the page and at the moment they don't support `console.trace`. (see [supported methods](https://github.com/samdenty/console-feed/blob/6f5737a5fb7ba09f8670288ca08cfc7cda7a76c0/src/definitions/Methods.ts#L1-L13))

I have added your feature request to our internal backlog which we use to prioritize what to build next. We can't make any promises about the timing, but it's on the list!

If you'd like to work on this feature, creating an issue on the console-feed repository would be a good start to see how samdenty feels about accepting a pull request. No pressure if you don't have the time.
