### ISSUE TITLE
Image corrupts after activating github sync

### ISSUE THREAD

**Issue by danielo515** [codesandbox/codesandbox-client#4504]
# 🐛 bug report

## Description of the problem

After activating github sync (also, after waiting few days because it was broken) my image file become a mess. There is a picture attached.

## How has this issue affected you? What are you trying to accomplish?

Well, the image is no longer an image, it cot corrupted when sync got activated

### Link to sandbox: [link]() (optional)

I already fixed it, but anyway: 
https://codesandbox.io/s/fervent-night-ns30d

Screenshot
![image](https://user-images.githubusercontent.com/2270425/86393686-af96bb80-bc9d-11ea-80bc-a195ed46f6c7.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | not sure |
| Browser          | Chrome |
| Operating System | OSX |

**Comment by garethx** [comment]
@danielo515 how did you fix it?

Original github sandbox has a broken version: https://codesandbox.io/s/github/danielo515/dot-count-prototype/tree/master/?file=/public/camera.png

**Comment by danielo515** [comment]
I didn't fixed it, it corrupts the image every time it syncs. That's why it is corrupt on the github and on the sandbox only if it syncs back.

**Comment by sweetyclem** [comment]
I'm getting the same issue, every time I create a repo the image file gets corrupted on both CodeSandbox and Github. The workaround is to delete the image, commit that, and then upload the image again and commit it. I have to do 2 commits otherwise it thinks there is no change since the files have the same name.
![image](https://user-images.githubusercontent.com/20025944/89188637-eeee4b80-d56c-11ea-971d-a301d391be10.png)

**Comment by christianalfoni** [comment]
Hi @sweetyclem ,

We have been tracking down how to deal with binaries and believe we have found a good solution now. The PR is still pending, but we will have something in very soon. Will let you know!

**Comment by sweetyclem** [comment]
@christianalfoni Amazing thank you for the update!

**Comment by hayatbiralem** [comment]
@christianalfoni I'm waiting for this fix too. Thank you.

**Comment by christianalfoni** [comment]
Hello there!

We have done several fixes to binaries in our Github Integration. This should now work.

It is recommended to create a new fork from your Github Source Sandbox. 

If you are working on a PR and can not create a new fork you will have to update any corrupt binaries directly on Github/locally and sync your Sandbox again.

**Comment by andrasbacsai** [comment]
I can still reproduce it with any image. :cry:

**Comment by guillaume-dorczynski** [comment]
Hello,

I have the same issue, it's always corrupting my favicon.ico file (it's the only image file I use). It's replacing the content of the file with a few dozen of bytes like ```†Ûi³ÿî¦ZvÇ(uëÖèÆ*?º™hiÛ?ºÇ«ý­wõ¶¶ïŽvÓ‡¸Õ½¸ïÞxsN}öÞïýãÚ¾'(ž'(```

I HAD to delete the file from CodeSandbox, re-upload it and sync Github, but it's no longer working, now the favicon.ico file on github contains ```https://uploads.codesandbox.io/uploads/user/a139ba27-4520-4e41-b247-954c04effbe7/0M4w-favicon.ico``` and there is always "favicon.ico" showing in the github tab on codesandbox, like it doesn't want to sync.

I can't find a way to solve it.

**Comment by Rishabhk06** [comment]
facing the same problem. How to solve this?

link to sandbox: [https://codesandbox.io/s/github/Rishabhk06/Counter_Project](url)
@christianalfoni

**Comment by lbogdan** [comment]
Hey @ksocks ,

Sorry this is an issue for you! I'm determined to look into this and get to the root issue during the week, it would help me greatly if you could provide your desired workflow step-by-step, in order to reproduce it on my side. Thanks!

**Comment by ksocks** [comment]
thanks @lbogdan for your attention to this! The issue is that when synced with a project on github, after one or two pushes to the remote repo image files in the repo become corrupted. I believe this is happening even when the image files were all ready in the repo and had no reason to be updated in the commit from codesandbox. In a project where I'm using codesandbox as the primary development tool, it's a mess when this happens because I have to keep separate copies of the images on my computer to resync them to the server and manually override the commit of the corrupted images on every commit. It also makes it difficult to use the preview on codesandbox, as often the images will be corrupted after I sync with the repo.

**Comment by ksocks** [comment]
@lbogdan here is a simple process to reproduce bug:

1) Create a new sandbox with the "Vue by codesandbox" template
2) In the github panel, name the repo and hit 'create new repository on Github'
3) After finishing syncing with the repo, the image assets/logo.png will be corrupted to a short text string like "��i����Zw��g���+��"�*^v&�r���{?���[��x" and display in the preview as an image load error

**Comment by lbogdan** [comment]
@ksocks I was indeed able to reproduce this, and I opened an issue in our API (private) repository. I'll keep this issue posted with any developments there.

**Comment by adamalbsoul** [comment]
This is still an issue

**Comment by sbinlondon** [comment]
@adamalbsoul @ksocks We just merged the fix right after you commented Adam, so please let us know if this continues! You might need to delete the corrupted files/reupload one last time to make sure the old files don't cause problems - sorry for that. We have a few places in the codebase where we import/export to and from Github and I think we've covered them all now with the `blobToBase64` function, but definitely let us know if that's not the case and we'll hunt it down again 💪
