### ISSUE TITLE
Listen for test outputs outside of CodeSandbox iFrame?

### ISSUE THREAD

**Issue by hhimanshu** [codesandbox/codesandbox-client#4516]
# 🌈 Feature

Consider that I am creating a quiz app and I want to leverage Codesandbox to embed the quiz questions and write tests in jest.

Now, I can embed the quiz (using iframe) on my domain and let users write code in codesandbox embedded iframe.

Currently,  On every change, tests run and the user has to click on tests tab to find out whether or not all tests pass. As a quiz app developer, I would like to listen to messages from embedded iframe container ([possible way](https://stackoverflow.com/questions/9153445/how-to-communicate-between-iframe-and-the-parent-site)) and show a message on the web page itself (on my domain). This is useful for multiple purposes

1. The user continues to write code and app continues to display (outside of iframe), how many tests pass or fail.
2. If all tests pass, a nice animation could be show to user (such as kudos!) and a way to continue in the quiz.

In the absence of having this information to the app, all of these nice features are not possible.

I am happy to chat more if more details are needed. 

Thank you for CodeSandbox, it is such a pleasure to work with!

**Comment by Kohze** [comment]
we like to see that feature aswell!
