### ISSUE TITLE
Infinite loop on almost every runtime error

### ISSUE THREAD

**Issue by lukigarazus** [codesandbox/codesandbox-client#4517]
# 🐛 bug report

## Description of the problem

Sandbox goes into infinite loop on almost every runtime error, eg.:

```javascript
let a = b + 1 // Error, b is not defined
```

After that the error gets thrown infinitely, blocking any changes to the code.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 4f1198026
| Browser          | Chrome 83.0.4103.116
| Operating System | Ubuntu 20.04

**Comment by CompuIves** [comment]
Hey! Do you have a repro sandbox? I can't reproduce this problem.
