### ISSUE TITLE
Cube animations messed after switching tabs.

### ISSUE THREAD

**Issue by radi-cho** [codesandbox/codesandbox-client#452]
## Is this bug or feature request?
The great mystery of the frenzied cubes. - bug

## Current behavior and how to reproduce?
If you open codesandbox.io switch the tab and return back after few seconds the Cube animations are bit messed.

![image](https://user-images.githubusercontent.com/12954909/34916267-25f172b4-f93e-11e7-9e53-b35009e09526.png)

**Comment by cannap** [comment]
i think this is because when you switch the tab  animation is paused and when you switch back it resumes
this can have unexpected side effects and then does not look right anymore for some small ms

**Comment by SaraVieira** [comment]
@radi-cho Can you still reproduce this? I tried on chrome and couldn't anymore

**Comment by radi-cho** [comment]
@SaraVieira Yup, I'm still able to reproduce it in Chrome 69, Win 10.
Screenshot captured a minute ago:
![image](https://user-images.githubusercontent.com/12954909/46905510-7cc2f780-cefd-11e8-9b7c-02f587131cd9.png)

**Comment by lbogdan** [comment]
I'm gonna name this "The great mystery of the [frenzied cubes](https://github.com/CompuIves/codesandbox-client/issues/799)". 🙂 

@radi-cho Is this still happening for you?

**Comment by radi-cho** [comment]
@lbogdan Yes ;) 
![image](https://user-images.githubusercontent.com/12954909/55088307-31b82d80-50b4-11e9-83d8-f727ffb96e18.png)

**Comment by christianalfoni** [comment]
These cubes are being expired shortly 😉
