### ISSUE TITLE
loading github

### ISSUE THREAD

**Issue by Advitya-sharma** [codesandbox/codesandbox-client#4521]
# 🐛 bug report

## Could not load the source Sandbox for this GitHub sandbox, please refresh or report the issue.

https://codesandbox.io/s/condescending-varahamihira-xymox

| Browser          | firefox 
| Operating System | windows

**Comment by oskarabc** [comment]
It's loading here now @Advitya-sharma, can you please confirm this is fixed?

**Comment by Advitya-sharma** [comment]
> 
> 
> It's loading here now @Advitya-sharma, can you please confirm this is fixed?

yes, but I'm still having trouble in resolving changes that I made in the github repository

**Comment by oskarabc** [comment]
That can be tricky! Imported sandboxes should stay in sync, or if you would want to commit changes to a GitHub repo, our recently released feature would allow you to push it to a newly created GitHub repo. This may help you resolve some of the changes quicker hopefully. Read more here: https://codesandbox.io/docs/git#creating-a-repository.
