### ISSUE TITLE
IFrame features are failing because Chrome does not parse sandbox due to allow-autoplay

### ISSUE THREAD

**Issue by adeelraza** [codesandbox/codesandbox-client#4525]
# 🐛 bug report

## Description of the problem
Drag-n-drop inside our Codesandbox does not work on Chrome. This probably started when you added `allow-autoplay` to iframe `sandbox` attribute because now Chrome throws an error:

<img width="429" alt="Screen Shot 2020-07-08 at 10 17 04 PM" src="https://user-images.githubusercontent.com/272548/86999975-c428f700-c168-11ea-8c0e-bcf42a07c8b6.png">

## How has this issue affected you? What are you trying to accomplish?
All our playground demos are failing because our product is a drag-n-drop builder.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/embed/github/unlayer/playgrounds/tree/master/javascript/basic

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Browser          |  Chrome
| Operating System | Mac OS X

**Comment by CompuIves** [comment]
Hey! This is a good find, I've created a PR that hopefully fixes this. I'll merge the PR regardless of the outcome, because you're right that the property should not be there. When the PR has been deployed we can test if this fixes the dnd too. My other hunch is that maybe drag and drop might not work 2 iframes deep, but I'm not sure yet.

**Comment by adeelraza** [comment]
@CompuIves Although after more digging, I found that something else in the way Codesandbox adds the iframe is making drag-n-drop to not work in Chrome. Any idea what that maybe?

**Comment by CompuIves** [comment]
Ohh, that's super interesting!! I'm testing now locally as well, with an iframe, slowly adding more sandbox properties, but it could indeed be something with layout.

**Comment by adeelraza** [comment]
If I replace the div above with the iframe, drag n drop works fine. You can try it in the Chrome inspector.

<img width="1202" alt="Screenshot 2020-07-10 07 49 27" src="https://user-images.githubusercontent.com/272548/87167668-2e818a80-c282-11ea-9642-9ceffb4a0fef.png">

**Comment by CompuIves** [comment]
Hmm, weird. Locally it only doesn't work for me if the height of the iframe is my screen height...

**Comment by adeelraza** [comment]
@CompuIves yes, that's exactly what I found in my local testing too. As soon as I change the width or height to be less than my viewport, it starts to work fine.

**Comment by CompuIves** [comment]
This seems to be a bug related to Chrome, I'm not sure how we can fix this exactly, maybe the only way would be to render the embed preview with a height of (100% - 1px)?
