### ISSUE TITLE
Local Anchor Tags not working.

### ISSUE THREAD

**Issue by moekhalil** [codesandbox/codesandbox-client#4527]
# 🐛 bug report

## Description of the problem
I simply was trying to create anchor tags that would navigate to the section with the same id as the anchor but it would not work. Spent too much time trying to see what was wrong -- thinking it was on my end -- but when I copied and pasted my code into a file on my local computer, it just worked. Also, I copy and pasted the index.html from my sandbox into other online HTML code editors, and again, they just worked.

## How has this issue affected you? What are you trying to accomplish?
Click on a local anchor/bookmark tag and have the page navigate to it. No JS.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox        |   https://codesandbox.io/s/xenodochial-darkness-b7gsw
| Browser                 |   Microsoft Edge Version 83.0.478.61 [Tried Chrome as well]
| Operating System |   Windows 10

**Comment by SaraVieira** [comment]
Hey!

Thank you for your report 

We already have an issue with the same bug so I will be closing to give a follow up to https://github.com/codesandbox/codesandbox-client/issues/2231

Can you please comment something like :+1: there so it bumps it up?

Thank you
