### ISSUE TITLE
helloworld nextjs template; Runtime errors type error Object not function

### ISSUE THREAD

**Issue by shriharip** [codesandbox/codesandbox-client#4533]
# 🐛 bug report

## Description of the problem

use the hello world template of nextjs 
change the link to the button with option of using next router.
and results in type error

## How has this issue affected you? What are you trying to accomplish?

Not able to work on MVP

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/mutable-silence-37zx1?file=/pages/index.js 

### Your Environment

| Software         | Name/Version |

Nextjs latest

| Сodesandbox      |

**Comment by andrasbacsai** [comment]
It looks like the `next` version you (or the template) used is pretty old (8.0.3). 
Can you please link me the template?
The official [one](https://codesandbox.io/s/github/zeit/next.js/tree/master/examples/hello-world) looks fine for me.

If you update the `next` package to the latest (9.4.4) in your sandbox, it will work (and also update `onclick` handler to `onClick`). ([example](https://codesandbox.io/s/nifty-cray-p8in7?file=/package.json))

**Comment by shriharip** [comment]
thanks looks good !
