### ISSUE TITLE
react_1.useRef is not a function

### ISSUE THREAD

**Issue by GiancarlosIO** [codesandbox/codesandbox-client#4536]
# 🐛 bug report

## Description of the problem
When you try to use the useMachine hook (from xstate), it throws the error "react_1.useRef is not a function".
I think this is a problem with typescript but I can't say if the problem is with codesandbox or with my code.

![image](https://user-images.githubusercontent.com/17274950/87230794-ae3d5100-c377-11ea-9b91-2010ada62f5b.png)

## How has this issue affected you? What are you trying to accomplish?
Can't create a react calculator example for the xstate docs.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/react-xstate-calculator-typescript-bug-mtipv?file=/tsconfig.json

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
typescript          |     3.9.5
xstate                  |    4.11.0
react/react-dom  |   16.10.2

**Comment by CompuIves** [comment]
Heyo! Do you still get this? I can't seem to repro the problem in the sandbox.

**Comment by GiancarlosIO** [comment]
@CompuIves Yes. I fixed the first one by changing my tsconfig (just adding/removing some fields). But I still have the bug with the first version of my tsconfig. I have updated the issue with the link of the CodeSandbox that has the bug.

**Comment by GiancarlosIO** [comment]
🤔

**Comment by andrasbacsai** [comment]
I can still reproduce it. We will take a look into this issue.
