### ISSUE TITLE
Infinite loop on package import statement

### ISSUE THREAD

**Issue by gunnnnii** [codesandbox/codesandbox-client#4562]
# 🐛 bug report

## Description of the problem
When I `import xlsx from 'xlsx'` the sandbox spins out into an infinite loop(or at least warns about it..) when importing it into the React template.

## How has this issue affected you? What are you trying to accomplish?
This means I can't do anything involving the xlsx package

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  Default sandbox opened through the website.. Not sure where I can see the version
| Browser          | Brave (shields down also) Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
| Browser          | Firefox 76.0.1 (64-bit)
| Operating System | MacOS Catalina 10.15.5

**Comment by gunnnnii** [comment]
I noticed that I get this message when I click the console error message:
`Unable to open 'cpexcel.js': File not found (file:///sandbox/node_modules/xlsx/dist/cpexcel.js).`

**Comment by CompuIves** [comment]
Ah, hmm, it seems like there's a loop with more than 10k iterations. I'm going to remove this check in the future, but for now you can disable the check by creating a `sandbox.config.json` file in the project.
