### ISSUE TITLE
Unauthenticated user unable to create new sandbox

### ISSUE THREAD

**Issue by scherbo** [codesandbox/codesandbox-client#4564]
# 🐛 bug report

## Description of the problem
I was trying to create a new sandbox and I was constantly getting an error (screenshot provided)
Everything was fine after I logged in

![Screenshot from 2020-07-17 15-03-25](https://user-images.githubusercontent.com/47299867/87784622-50a97880-c83f-11ea-9931-f5e1b15aef4a.png)

## How has this issue affected you? What are you trying to accomplish?
I wasn't able to create new sandbox

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome 84.0.4147.89
| Operating System | Ubuntu 20.04, macOS 10.14.6

**Comment by SaraVieira** [comment]
Sorry about your issues, fixing this now

**Comment by SaraVieira** [comment]
just pushed a fix to master and should be live in about 20m

**Comment by scherbo** [comment]
Everything seems fine, thanks!
