### ISSUE TITLE
CANVAS DOES NOT SHOW UP, IT DOES ON OTHER SITES, BUT NOT ON CODESANDBOX. FIX THIS SHIT, BROKEN SITE.

### ISSUE THREAD

**Issue by andreplaranja** [codesandbox/codesandbox-client#4574]
# 🐛 bug report

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by SaraVieira** [comment]
First of all please be nice, there is no need to be rude

Second you are literally not giving us any information on what is wrong, I just tried a canvas example and it worked fine: https://codesandbox.io/s/cocky-knuth-vg3cn?file=/index.html

Either explain what you are saying in actual words or I am closing this issue

**Comment by SaraVieira** [comment]
btw we have a code of conduct: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md

**Comment by CompuIves** [comment]
Closing this one, since there's literally no information besides breaking the code of conduct.
