### ISSUE TITLE
ts(2307): Cannot find module 'otion' – Only with CRA, but not Gatsby and Next.js

### ISSUE THREAD

**Issue by kripod** [codesandbox/codesandbox-client#4576]
# 🐛 bug report

## Description of the problem

While trying sandboxes created out of GitHub repo directiries, I came across the following observations:

- My [CRA example](https://codesandbox.io/s/github/kripod/otion/tree/main/packages/example-cra?file=/src/App.tsx) for using [otion](https://github.com/kripod/otion) throws `Cannot find module 'otion'. ts(2307)` in the editor, but outputs bundles without any issue
- My [Gatsby](https://codesandbox.io/s/github/kripod/otion/tree/main/packages/example-gatsby?file=/src/pages/index.tsx) and [Next.js](https://codesandbox.io/s/github/kripod/otion/tree/main/packages/example-nextjs?file=/pages/index.tsx) examples seem to work fine, despite using configurations very similar to the CRA project

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 679a96f5d
| Browser          | Firefox 78.0.2 (64-bit)
| Operating System | macOS Catalina 10.15.6

**Comment by CompuIves** [comment]
Hey! It should work as expected now, our type fetcher was full and couldn't fetch any new types.

**Comment by kripod** [comment]
Wonderful, thank you! 😊
