### ISSUE TITLE
Vertical Layout for Embeds

### ISSUE THREAD

**Issue by oskarabc** [codesandbox/codesandbox-client#4579]
# 🌈 Feature

Vertical Orientation of Editor and Preview in CodeSandbox Embeds as opposed to current horizontal.

Add `verticallayout=1` parameter to Embed Options as described in https://codesandbox.io/docs/embedding#embed-options.

None, although I believe this used to be an option. I see the option in the React Embed Sandbox Code: https://github.com/codesandbox/codesandbox-client/search?q=verticallayout&type=Code.

**Comment by innerdaze** [comment]
Just being able to move panes around in general would be great. Right now it seems you can drag the tabs around but you can't drop them anywhere.

**Comment by SaraVieira** [comment]
Hey

Thank you for bringing this to our attention, I have just added it to our internal backlog that we do want to make public but for now, it's all in notion.

I will be closing but to make sure what we have in GitHub is just issues and all our feature requests are tracked in our roadmap.

We will definitely make an announcement when this is done 

Again, thank you!
