### ISSUE TITLE
Unable to upload images

### ISSUE THREAD

**Issue by AndyCErnst** [codesandbox/codesandbox-client#4580]
# 🐛 bug report

## Description of the problem
I'm unable to upload images successfully on any of my sandboxes. I've tried the upload button and dragging files in, but in either case I usually see the file contents turn into the Access Denied error below
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message></Error>
```
or on occasion I've seen this.
<img width="448" alt="Screen Shot 2020-07-20 at 9 15 01 AM" src="https://user-images.githubusercontent.com/6656575/87961096-18d24900-ca6a-11ea-843d-ccb252cfb77b.png">

Text and html files seem to upload fine, but I've had this issue with uploading images for several weeks. I've tested with pngs and jpgs.

### Link to sandbox: [link](https://codesandbox.io/s/dreamy-wave-v87ni) (optional)
I've repro'd this in several of my sandboxes.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  not sure how to find a version, but using the React or React TS template
| Browser          | Chrome 83.0.4103.116 (Official Build) (64-bit)
| Operating System | OSX 10.15.6

**Comment by sannek** [comment]
Do the file names for your images have spaces in them? There's a known issue with spaces in image file names that I'm currently working to fix. Until that's done, the easiest workaround for you might be to make sure the files don't have spaces in them. 

If this issue also occurs with filenames without spaces, could you share some of the file names with me so I can see if I can reproduce your issue?

**Comment by AndyCErnst** [comment]
Yes, I hadn't noticed it, but it does seem related to spaces in the filename. I'm able to upload images that don't have spaces in the filename.

**Comment by AndyCErnst** [comment]
This means I have a workaround for my immediate issue. Thank you.
