### ISSUE TITLE
Github repository : can not switch between branches once you create PR and merge 

### ISSUE THREAD

**Issue by AJ-7885** [codesandbox/codesandbox-client#4587]
# 🐛 bug report

## Description of the problem
If the user create PR and merge into the master branch in Github, the GitHub section in codesandbox shows nothing and there is no possibility to switch to master or do anything with git sync. 

## How has this issue affected you? What are you trying to accomplish?
This is going to unlink the codesandbox from the repository and you need to create another codesandbox and that is not nice.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/webchanneldev-1jfls

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | https://codesandbox.io/s/webchanneldev-1jfls
| Browser          | chrom
| Operating System | MacOS 10.15.01

**Comment by oskarabc** [comment]
We're inspecting this @AJ-7885 thank you for reporting. As of now I can't create a repo at all, so there's work to be done here. Due to limited availability it may take some time though. Please hang on.

**Comment by AJ-7885** [comment]
Many thanks for the help and support 👍

**Comment by christianalfoni** [comment]
Hi there @AJ-7885 ,

Before making adjustments here I wanted to ask you how you would expect this to work? 😄 

Would you like to continue on the same Sandbox and create a new PR?

There should be an indication that the PR is merged if you were to refresh the Sandbox after the PR is merged on Github. We did not want to poll Github to get this information live, as there are limits to have many requests we can make. But maybe we could find a good way to get this information live.

Let me know about your expectations on this feature and I will get back to you on how we will solve it 😄

**Comment by AJ-7885** [comment]
Dear @christianalfoni,

Many thanks for your questions and looking into this issue, 

I do expect I can able to switch and update the sandbox from a different branch, That means, I can see a list of branches from GitHub and sync my Codesandbox with that branch in need. 

As you know currently, if I continue on master branch I can push the code into master and continue with the same Codesandbox, But when I push my code with PR into Github and PR close/Merge even if the branch has not been remove from Github, there is no a possibility to pull from Github at all and need to remove the existing Codesandbox and make a new one. I am not sure which action would be a more expensive action for your system. remove/keep the existing Codesandbox and create a new one or allow to pull from branched into the same Codesandbox with the same resources which are using?

IMO, allowing the user to switch between the branched will be a great option and solve lot of issues and less expensive operation. But maybe I don't know fully all your architecture and strategy.

**Comment by christianalfoni** [comment]
Hi again @AJ-7885 and thanks a bunch for your input!

We have a pending "polish" that will on the Github sidebar show a dropdown of Sandboxes forked from the main Github Sandbox. This will allow you to quickly jump between the main Github Sandbox and your other "work in progress". You will also have the ability to directly fork a new sandbox off `master` from this dropdown, which will be useful in the scenarios where you are done with PR and want to do something new off of the latest `master` 😄

**Comment by AJ-7885** [comment]
Many thanks, working fine, the only side issue which many not directly related to this issue I can noticed, is why CodeSandBox is removing the https://github.com/AJ-7885/WebChannel/blob/master/.github/workflows/codeql-analysis.yml

![image](https://user-images.githubusercontent.com/42003122/89650827-4a00a500-d8c3-11ea-9049-555742ee01ec.png)

Besides this, I notice we can not select which fine need to include the commit or revert the changes.

**Comment by christianalfoni** [comment]
Hi @AJ-7885 and sorry for late response.

This is very strange. The reason it appears this way is that your sandbox has become out of sync. So your `master` has this file, but somehow a needed sync has not been detected. So when it sees this file in your `master`, but not in this sandbox it thinks you deleted it.

Do you remember how you got into this state? Were you doing a sync before it happened?

**Comment by AJ-7885** [comment]
I did add this file via github.com editor and try to sync, I am not sure this is the problem, I did try to make new codesandbox with the same repository but still with new codesandbox also remove this file, I thought maybe there is something on codesandbox which generally does not like this file and try to remove it no matter it is sync or nor sync, even when I try to recreate the file with codesandbox, it's not working fine.

**Comment by christianalfoni** [comment]
Hi again @AJ-7885 ,

I found the issue and created an issue for one of our developers to fix it: https://github.com/codesandbox/codesandbox-client/issues/4866 😄

**Comment by christianalfoni** [comment]
Okay, so a fix has been deployed to production now 😄  Sorry for the delay on this!
