### ISSUE TITLE
A sandbox error occurred, you can refresh the page to restart the container

### ISSUE THREAD

**Issue by LimaBruno** [codesandbox/codesandbox-client#4591]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

Error Initializing Sandbox Container. 
I'm using NPM with Gatsby
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | I couldn't find
| Browser          | Google Chrome  84.0.4147.89 64 bits
| Operating System | Windows 10 64

**Comment by LimaBruno** [comment]
How can I solve the problem?

UNHANDLED REJECTION ENOSPC: no space left on device, mkdir '/sandbox/.cache'

Error: ENOSPC: no space left on device, mkdir '/sandbox/.cache'

**Comment by lbogdan** [comment]
Hey @LimaBruno ,

Sorry for the inconvenience, container sandboxes have a persistent storage limited to 1GB, which your sandbox reached (because of a very large `node_modules`). Unfortunately there's no way to increase that at the moment.

**Comment by LimaBruno** [comment]
@lbogdan 

Thank you very much for your reply, is there a way to delete the files in this folder?

**Comment by lbogdan** [comment]
Yes, you can open a shell (by clicking the "+" button in the `Terminal` tab) and just run Linux commands, e.g. `rm -fr /sandbox/node_modules`.

![image](https://user-images.githubusercontent.com/2083930/88432256-84b70780-ce04-11ea-805e-d7e60101377e.png)

**Comment by LimaBruno** [comment]
@lbogdan 

I changed my application because of space.

Thank you!
