### ISSUE TITLE
Angular template fails, requiring non-latest tslib to work

### ISSUE THREAD

**Issue by oskarabc** [codesandbox/codesandbox-client#4594]
# 🐛 bug report

## Description of the problem
ModuleNotFoundError (tslib) when starting from the angular template in the universe.

## How has this issue affected you? What are you trying to accomplish?
Starting an angular project!

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/hopeful-hamilton-zdkw4 for error
add dep tslib-2.0.0 and syntaxerrors are shown, downgrade to 1.13.0 and it works.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 1ed71a491
| Browser          | Brave/Chrome
| Operating System | OSX

**Comment by brendanm-stripe** [comment]
Thanks for filing from my feedback email 😀

**Comment by leaopedro** [comment]
+1

**Comment by CompuIves** [comment]
This one is now fixed with #e53d68b35c038628ce18c53efdbff37204623ede!
