### ISSUE TITLE
Sandbox fails in incognito: "Error: No available storage method found." from localforage

### ISSUE THREAD

**Issue by thisismydesign** [codesandbox/codesandbox-client#4596]
# 🐛 bug report

## Description of the problem

Related: https://github.com/localForage/localForage/issues/722

The error I'm seeing:

![image](https://user-images.githubusercontent.com/3299948/88390751-2b75b680-cdb9-11ea-90ad-babf51a2f41b.png)

![image](https://user-images.githubusercontent.com/3299948/88390812-4811ee80-cdb9-11ea-8bbd-46bc768b8be4.png)

![image](https://user-images.githubusercontent.com/3299948/88390863-637cf980-cdb9-11ea-84ab-fa793d4779c2.png)

`localforage` is not in my `package-lock` which is why I think this is (also) an issue with CodeSandbox.

## How has this issue affected you? What are you trying to accomplish?

Trying to get my project to run in incognito mode as well. Unclear if it's broken due to CodeSandbox but in any case CodeSandbox has errors.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |  Version 84.0.4147.89 (Official Build) (64-bit) |
| Operating System | Win 10 |

**Comment by christianalfoni** [comment]
Hello @thisismydesign,

Opening the Sandbox I can not see any issues? You mention incognito mode. Does this happen in incognito mode? I would suggest opening the Sandbox detached from the coding environment by clicking the "Open in new window" button at the top right of the preview. Now you can run incognito mode without affecting your Codesandbox session.

I hope this helps, but please let me know if I misunderstood something 😄

**Comment by thisismydesign** [comment]
Yep, this is explicitly in incognito. We have sandboxes embedded on our website that fail in incognito mode, so I especially don't want to detach from the sandbox. Opening just the app in incognito works so I assume the issue is with the sandbox environment.

**Comment by christianalfoni** [comment]
Hi again!

The sandbox environment is the same inside Codesandbox as when you open it detached. The only difference is the it is no longer running in an iframe. So I am leaning towards this being an issue with Firebase + Incognito + Iframe. 

Could this be the reason? https://github.com/firebase/firebase-js-sdk/issues/3004

**Comment by thisismydesign** [comment]
Thanks for looking into it, however, I don't think that's the problem. This is the repo in question https://github.com/componently-com/firebase-html-auth-starter and I can use it directly in incognito mode. As soon as it's embedded via Codesandbox though, it fails.

**Comment by christianalfoni** [comment]
Hi again,

So the problem is not incognito? It is rather running in an iframe (embed or inside codesandbox)? 😄 

Cause Firebase does not support auth in iframes. https://stackoverflow.com/a/48375427/3845247. I am running a stream building an app on Codesandbox and had the same problem, can not log in inside Codesandbox (or embed). Had to first detach and go directly to log in. It is a security thing by Firebase.

**Comment by thisismydesign** [comment]
The problem is incognito. It does work perfectly well embedded or
non-embedded in non-incognito. As well as non-embedded incognito. It's the
combination of incognito and embed that is the problem.

But I'd propose to look at the actual error and see if that's caused on
your side or not.

Again, the error is coming from localforage that's isn't a dependency of
mine or firebase. therefore it should be a dependency of code sandbox.

**Comment by christianalfoni** [comment]
Hello there and so sorry for being late on following up on this!

The Firebase error and the google search referencing mostly Firebase issues got me stuck on that being the issue, but we have an early implementation I was not aware of using `localforage`. That said, we wrap everything in a `try/catch`. You can see the error:

```sh
Problems consuming cache
Error {}
```

I found this issue: https://github.com/firebase/firebase-js-sdk/issues/3004 , which is related to the following error:

https://user-images.githubusercontent.com/3299948/88390863-637cf980-cdb9-11ea-84ab-fa793d4779c2.png

So my mind still points to Firebase Auth being the core issue here.

**Comment by thisismydesign** [comment]
I still think there was an issue here but I'm not working with this and can't support it anymore. Closing.

**Comment by SaraVieira** [comment]
Hey

To give an update here, we had this issue on brave aswell and it was fixed by adding in browser storage 

I hope it fixed this aswell, will test in a bit
