### ISSUE TITLE
Github container links no longer working

### ISSUE THREAD

**Issue by IanKBovard** [codesandbox/codesandbox-client#4597]
# 🐛 bug report

## Description of the problem
About four days ago it was reported that our links stopped working.
I noticed previously a slash was added between io and box ..io/box)

[link](https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=box&module=%2Fsrc%2FBox.js)

the current link has none.
<img width="330" alt="Screen Shot 2020-07-24 at 11 28 47 AM" src="https://user-images.githubusercontent.com/21990914/88413520-f493a680-cda0-11ea-8292-a040cc974780.png">

and when i manually correct the link i get this error.
<img width="360" alt="Screen Shot 2020-07-24 at 11 32 18 AM" src="https://user-images.githubusercontent.com/21990914/88413757-59e79780-cda1-11ea-91ac-d7f7524e42c1.png">

My assumption is that it's an issue with webpack(maybe there was an update and i need to update my webpack config?)

Has anyone else come across this issue. The links were working early last week. I can't say for certain exactly when they broke, but I know it was at least four days ago.
Appreciate the help.

webpack config
```
const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');

const plugins = [
  new CopyWebpackPlugin([{ from: './public' }]),
  new CleanWebpackPlugin(['dist']),
];

module.exports = {
  devtool: 'hidden-source-map',
  devServer: {
    contentBase: './dist',
    historyApiFallback: true,
    port: 8576,
  },
  entry: './src/index.js',
  output: {
    path: path.resolve('./dist'),
    filename: 'index.js',
    publicPath: '/',
  },
  resolve: {
    extensions: ['.js', '.json'],
  },
  plugins,
  node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
      },
    ],
  },
};

```
## How has this issue affected you? What are you trying to accomplish?
Links stopped working, unable to link to examples.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Container
| Browser          | Chrome Version 84.0.4147.89 (Official Build) (64-bit)
| Operating System | Mac

**Comment by lbogdan** [comment]
Hey @IanKBovard ,

Yes, that's usually a `webpack-dev-server` issue, you should probably set `devServer.disableHostCheck` to `true`, see https://webpack.js.org/configuration/dev-server/#devserverdisablehostcheck .

**Comment by IanKBovard** [comment]
@lbogdan Thanks for the quick response. I have tested with that, and it is shown to fix the invalid host header error (mostly, i refrained from commiting to this, because it is not recommended). However, i'm curious why it stopped working around 4 days ago, and why the links no longer work.

https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=box&module=%2Fsrc%2FBox.js
does not create the correct path, asi it used to, in the browser view on codesanbox.

it makes this
https://rr9mw4j36q.sse.codesandbox.iobox

when it should be this
https://rr9mw4j36q.sse.codesandbox.io/box

thanks again for the help!

**Comment by lbogdan** [comment]
That's very weird, as there was no recent change in how we generate the preview URL, and with server / container sandboxes, it never worked without a `/` prefix in `initialpath`, e.g. `https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=/box&module=%2Fsrc%2FBox.js` .

**Comment by IanKBovard** [comment]
Thanks for discussing this with me. 

this is the current link on the site - links to a container - not working
https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=box&module=%2Fsrc%2FBox.js

this is a similar link to a non container - working
https://codesandbox.io/s/charming-sun-oefh8?initialpath=box&module=%2Fsrc%2FBox.js

both have the same `?initialpath=box&module=%2Fsrc%2FBox.js` appended to them. yet, the client version adds a `/` to the browser side(makes me believe webpack might be the cause, although still don't know why it just suddenly stopped working).

just to clarify are you saying `initialpath` is always supposed to have the `/` in it?

thank again, appreciate the help.

**Comment by lbogdan** [comment]
The logic to generate the preview URL is different between container and non-container sandboxes, and for container ones `initialpath` always need(ed) `/`.

If curious, you can check the logic here:

https://github.com/codesandbox/codesandbox-client/blob/1ed71a4910b21fc5f4b782567b1b638fbfc7436c/packages/common/src/components/Preview/index.tsx#L71-L76

and for non-container sandboxes:

https://github.com/codesandbox/codesandbox-client/blob/1ed71a4910b21fc5f4b782567b1b638fbfc7436c/packages/common/src/utils/url-generator.ts#L126-L128

and they're both called from here:

https://github.com/codesandbox/codesandbox-client/blob/1ed71a4910b21fc5f4b782567b1b638fbfc7436c/packages/common/src/components/Preview/index.tsx#L211-L215

**Comment by lbogdan** [comment]
(just to be clear, I'm not saying this behavior is consistent (it's more a bug IMO), just that I'm pretty sure that it never worked without the `/`)

**Comment by IanKBovard** [comment]
Ah, interesting. Thanks for that. So, the github sandbox links are supposed to have the `/`. I can't say with 100% certainty, but I'm fairly sure the link worked before without the `/`. We have not changed the links in some time.

Here's the page with the link, probably not helpful, but just as reference.
https://v2.grommet.io/box

From our conversation so far, I assume the best fix at the moment, is to add a `/` to all the broken links and `disableHostCheck: true` to the webpack config.

**Comment by lbogdan** [comment]
The only explanation I can think of is that it was initially detected as a non-container sandbox, so it was working without the `/`, and then something happened (either on our end or in your repo), and we're now detecting it as a container sandbox, so it doesn't work anymore (which btw would also explain the "Invalid Host header").

> From our conversation so far, I assume the best fix at the moment, is to add a / to all the broken links and disableHostCheck: true to the webpack config.

Yes, either `disableHostCheck`, or you can try with `allowedHosts: ['.sse.codesandbox.io']` (with the downside that it would stop working if we decide to change the hostname / add hostname aliases).

**Comment by IanKBovard** [comment]
> I can think of is that it was initially detected as a non-container sandbox, so it was working without the /, and then something happened (either on our end or in your repo), and we're now detecting it as a container sandbox

I'm very inclined to believe this. It would explain a lot of things. Thank you for your help. I'll close this issue.
