### ISSUE TITLE
Console doesn't work in Vue

### ISSUE THREAD

**Issue by TheDutchCoder** [codesandbox/codesandbox-client#4598]
# 🐛 bug report

## Description of the problem
`console.log` doesn't work in a Vue project

## How has this issue affected you? What are you trying to accomplish?
logging things to the console doesn't work. Normal JS project works fine.

### Link to sandbox:
[broken Vue](https://codesandbox.io/s/ecstatic-silence-ivfdq?file=/src/App.vue)
[working JS](https://codesandbox.io/s/clever-violet-lo5zu?file=/src/index.js)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | No idea (whatever is the current one)
| Browser          | Chrome
| Operating System | Mac OS Mojave

**Comment by lbogdan** [comment]
Hey @TheDutchCoder ,

As far as I know `@click` only works on DOM elements, if you want to use it on components you have to use `@click.native`, which starts working if I update your sandbox:

![image](https://user-images.githubusercontent.com/2083930/88459186-17ef4c00-ce9c-11ea-8fd0-2e0333d38399.png)

**Comment by TheDutchCoder** [comment]
You're right of course, not sure what I was thinking :|
