### ISSUE TITLE
Typescript nullish coalescing and optional chaining breaks auto-formatting

### ISSUE THREAD

**Issue by rareyesdev** [codesandbox/codesandbox-client#4601]
# 🐛 bug report

## Description of the problem
When using Typescript, using **nullish coalescing** or **optional chaining** makes the auto-formatting to stop working.

## How has this issue affected you? What are you trying to accomplish?
This is annoying because in order to keep auto-formatting working I had to stop using those features.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 3.8.0
| Browser          | Chrome 84.0.4147.89 (Official Build) (64-bit)
| Operating System | macOS Catalina 10.15.5

**Comment by christianalfoni** [comment]
HI @rareyesdev ,

We are running an old version of prettier, which is being updated as we speak. Look out for a fix for this very soon 😄
