### ISSUE TITLE
I get "Your session seems to be expired, please log in again..." when I try to make a sandbox private.

### ISSUE THREAD

**Issue by DavidQuartz** [codesandbox/codesandbox-client#4604]
# 🐛 bug report

## Description of the problem
I get "Your session seems to be expired, please log in again..." when I try to make a sandbox private.

## How has this issue affected you? What are you trying to accomplish?
I am trying to make a sandbox private. This problem makes it impossible to do so.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/stoic-raman-0mzpx

### Your Environment
React

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome
| Operating System | macOS Catalina

**Comment by christianalfoni** [comment]
Hi @DavidQuartz ,

The button should actually only be available to PRO users. It should not be available anymore. Sorry for the confusion! 😄
