### ISSUE TITLE
codesandbox "static" template serves content for non-existent files

### ISSUE THREAD

**Issue by trusktr** [codesandbox/codesandbox-client#4608]
# 🐛 bug report

Choosing the "static" template ends up serving content for non-existent content.

## Description of the problem

For example, visit https://69kb1.csb.app/path/to/place/that/does/not/exist.html and it will return an HTML payload with a 200 response.

## How has this issue affected you? What are you trying to accomplish?

This causes things not to work as expected, because the code is relying on failed network requests or 404 responses in order to then proceed to do certain things.

### Link to sandbox:

As an example, go to https://69kb1.csb.app then click on "Overview" in the sidebar, and the app will load HTML content into the sidebar because the app believes that the response is the content that the user intended to place in the sidebar.

I believe this behavior should be configurable, and it should be off by default, just like all static servers. This is the first time I've seen a static server do this by default.

**Comment by trusktr** [comment]
I took a look at https://github.com/codesandbox/static-template, and I see it uses the `serve` package. I tried running `serve .` locally, and it correctly 404s on me for unknown paths.

**Comment by SaraVieira** [comment]
Hey!

We wil take a look at this, seems to be a backend issue where we return the main HTML in vanilla because of SPA's but we definitely should not do that in static

Btw we do not run serve in our transpilation, that's mostly there for deployment and for running locally, this template has no tranbspilation at all
