### ISSUE TITLE
Can´'t make lib work

### ISSUE THREAD

**Issue by randomcoggles** [codesandbox/codesandbox-client#4616]
# 🐛 bug report

## Description of the problem
I'm trying to use a lib called IBM loopback(v3) but I can't make it work. It works fine on any (local)machine. But seems to crash on CodeSandbox.
Could somebody provide me any help?
## How has this issue affected you? What are you trying to accomplish?
Yes, it does. I'm trying to create a mock server using a better lib than json-server.
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome
| Operating System | Mac OS

**Comment by lbogdan** [comment]
Hey @randomcoggles ,

As your project uses Node.js APIs, you need a [container sandbox](https://codesandbox.io/docs/environment#container-environment). I forked your repo and added a [config](https://github.com/lbogdan/mocks/blob/master/sandbox.config.json) to set the sandbox template to `node`, and it seems to be working: https://codesandbox.io/s/github/lbogdan/mocks .

**Comment by lbogdan** [comment]
(note that you'll have to open the preview in a new window, because your app seems to be setting the `X-Frame-Options: DENY` header so it can't be loaded in the preview iframe:

![image](https://user-images.githubusercontent.com/2083930/88796211-f945c980-d1a9-11ea-82af-132d36590acc.png)

)

**Comment by SaraVieira** [comment]
Closing as a solution was provided by @lbogdan

**Comment by randomcoggles** [comment]
@lbogdan , Thank you so much. It really works! You saved the day :)
