### ISSUE TITLE
Cannot use normal script tags

### ISSUE THREAD

**Issue by MajorMeerkatThe3rd** [codesandbox/codesandbox-client#4617]
# 🐛 bug report

## Description of the problem
When I try to use the script tag in the html file, it doesn't get executed.

## How has this issue affected you? What are you trying to accomplish?
I try to load different scripts via the scripts tags. Even just a console.log doesn't work.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | bef7486a2
| Browser          | Chrome
| Operating System | Windows

**Comment by SaraVieira** [comment]
Hey!


Can you please provide a sandbox example?

**Comment by MajorMeerkatThe3rd** [comment]
Sure thing, I just edited my initial report. Now the link there should work.

**Comment by snabela** [comment]
@SaraVieira this is a serious problem for us, could you help please?

**Comment by andrasbacsai** [comment]
Hey,

I found 2 problems with your example sandbox.
- It's created with `create-react-app` environment. It should be `Vanilla/parcel`.
![image](https://user-images.githubusercontent.com/5845193/89437490-f289fa00-d747-11ea-9d2e-25da4e6f289a.png)
- Index.html should include the `dist/bundle.js` in a script tag.

[Here is an example](https://codesandbox.io/s/compassionate-stallman-wmcqg?file=/package.json) or you could check the official template for [Vanilla JS](https://codesandbox.io/s/vanilla).

Let me know if you need anything else.

**Comment by MajorMeerkatThe3rd** [comment]
Thank you @andrasbacsai !
The issue was that the github repo that we forked from wasn't detected properly (therefore fallback to `create-react-app`). After creating a sandbox.config file and some more tinkering, everything works now.
