### ISSUE TITLE
Screen Sharing prompt is not triggered in firefox causing NotAllowedError error

### ISSUE THREAD

**Issue by dceballos1991** [codesandbox/codesandbox-client#4618]
# 🐛 bug report

## Description of the problem
Using getDisplayMedia( ) for screen recording purposes does not trigger a screen sharing prompt on firefox which results in a NotAllowedError. Prompt is triggered in both edge and chrome and code runs as expected  

## How has this issue affected you? What are you trying to accomplish?
Cannot record screen
### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/sharp-mestorf-qumzf?file=/src/index.js
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| FireFox     |78.0.2 
| Windows | 10

**Comment by CompuIves** [comment]
Hey @dceballos1991. Could you try opening the sandbox in its own window (https://qumzf.csb.app)? I don't think this is an issue with CodeSandbox, rather a security thing with Firefox.

**Comment by SaraVieira** [comment]
Hey

As Ives said when you open in a new tab without the iframe it does work (https://qumzf.csb.app/), this is not really something we can fix.

Firefox does not allow you to trigger screen sharing from inside an iframe as a security measure
