### ISSUE TITLE
A WebSocket based live-reload dev server not working (Node Environment)

### ISSUE THREAD

**Issue by saurabhdaware** [codesandbox/codesandbox-client#4619]
# 🐛 bug report

## Description of the problem

Hi, I am working on a static-site-generator that uses WebSocket, and HTTP server for a live-reload dev server. It works fine locally.

I tried to run its code on CodeSandbox and it does log the change event in the terminal but does not reload the page. In console, it says `SecurityError: The operation is insecure` at `new WebSocket(url)`

If I manually click the reload button after making changes, it does reflect the new code.

## How has this issue affected you? What are you trying to accomplish?

In the CodeSandbox Link below, you will see a `.abell` file (which is a template engine for my static-site-generator). If you make changes, a `Theme Changed` event will be logged in the terminal. Normally, this will trigger WebSocket to send a reload message to the HTTP server which then calls `location.reload()` and reloads the page.

Apparently, CodeSandbox is not allowing WebSocket.

To work, If the HTTP server is on `https://example.com`, Abell expects a WebSocket running on `ws://example.com`

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/abell-hello-world-zit90?file=/src/index.abell

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Node Template
| Browser          |  Firefox
| Operating System | Ubuntu

If allowing WebSockets is not possible, is there any other workaround to get it working? how do other reload servers work?

Thanks! and I loveee using codesandbox 🌻

**Comment by lbogdan** [comment]
Hey @saurabhdaware ,

I'm not really sure how to replicate your issue, but generally, if the site is served over `https`, which is the case here, the websocket has to also be secure, so `wss://...`.

**Comment by saurabhdaware** [comment]
uh ohhh my baddd. Yes yes it worked after `wss`. Thank you so much!
