### ISSUE TITLE
crash during signing in

### ISSUE THREAD

**Issue by alainbaz** [codesandbox/codesandbox-client#4622]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | firefox | 66.0.0 | Ubuntu           | 99ce9d5d4          |

  **Route:**
  https://codesandbox.io/signup/c2f77f3e-1c78-4221-94b8-006ac0d60c95

  **Error Code:**
8017db8b091b46d3b0b00314916c94a0

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: window.opener is null
  i/<@https://codesandbox.io/static/js/page-signup.a529256ae.chunk.js:1:377
ps@https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1754261
Cl@https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1779074
../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.production.min.js/t.unstable_runWithPriority@https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1797332
qo@https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721705
wl@https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1778835
_l/<@https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1778746
z@https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1796713
../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.production.min.js/A.port1.onmessage@https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1795457

  
    in i
    in o
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by oskarabc** [comment]
Feel free to re-open when this reoccurs. For now there's too little steps known to reproduce.
