### ISSUE TITLE
Getting "Cannot set property" error on codesandbox but not locally

### ISSUE THREAD

**Issue by bduffany** [codesandbox/codesandbox-client#4630]
# 🐛 bug report

## Description of the problem

See the linked bug here: https://github.com/Tonejs/Tone.js/issues/699

When running `import "tone"` there is an error:

```
Cannot set property Transport of #<Object> which has only a getter
```

## How has this issue affected you? What are you trying to accomplish?

Trying to create sandbox examples / minimal repro cases for Tone.js, but can't.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest (production)
| Browser          | Chrome/83
| Operating System | Linux (Ubuntu 20.04)

**Comment by SaraVieira** [comment]
Hey

This is super interesting, turns out we have some issues with tone 14, I will keep digging.

https://codesandbox.io/s/laughing-shaw-to2du?file=/index.js

This one uses tone 13 and it works if that helps a bit

**Comment by CompuIves** [comment]
Hmm, seems to be related I think to how we convert our `node_modules` to `commonjs`, I think I can take this one!

**Comment by bduffany** [comment]
(Commenting so it doesn't get closed.)

**Comment by SaraVieira** [comment]
The issue is fixed in the latest version of codesandbox, here is a sandbox example: https://codesandbox.io/s/laughing-shaw-to2du and your sandbox has no issues either

closing
