### ISSUE TITLE
Formatting failed: "Error: Cannot find module 'prettier' from '/sandbox/package.json'"

### ISSUE THREAD

**Issue by Spunkie** [codesandbox/codesandbox-client#4641]
# 🐛 bug report

## Description of the problem

I just now tried to create a new pro account and then fork a private repo as a new sandbox on the website. Everything looks like it forks and install correctly but when I go into a file and save I get the error message
```
Formatting failed: "Error: Cannot find module 'prettier' from '/sandbox/package.json'"
```
![chrome_DPSCsOehSKKQ7GeqiZS5RGZFdWFYmp4e](https://user-images.githubusercontent.com/27828090/89301686-32a58b80-d627-11ea-8a70-d74017f760b3.png)

I'm not really sure where `/sandbox/package.json` is coming from since I don't have one of those in the repo and I can't find anything about that in the docs. So I'm guessing that is some kind of internal codesandbox.io error. Which I imagine explains why when I click on the `Manage Extension` nothing happens and the errors never go away. 
___
Also in my own `package.json` I do have prettier @ `^2.0.5` as a dev dependency already 
```json
}
	...
	"dependencies": {
		"@nuxt/content": "^1.3.2",
		"@nuxtjs/axios": "^5.11.0",
		"dotenv": "^8.2.0",
		"monday-sdk-js": "^0.1.0",
		"nuxt": "^2.13.0",
		"nuxt-i18n": "^6.13.1"
	},
	"devDependencies": {
		"@babel/core": "^7.10.5",
		"@babel/plugin-transform-runtime": "^7.10.5",
		"@nuxtjs/eslint-config": "^3.0.0",
		"@nuxtjs/eslint-module": "^2.0.0",
		"@semantic-release/changelog": "^5.0.1",
		"@semantic-release/git": "^9.0.0",
		"@vue/test-utils": "^1.0.3",
		"babel-eslint": "^10.1.0",
		"babel-jest": "^26.0.1",
		"core-js": "2",
		"cross-port-killer": "^1.2.1",
		"eslint": "^7.2.0",
		"eslint-config-prettier": "^6.11.0",
		"eslint-plugin-html": "^6.0.2",
		"eslint-plugin-nuxt": "^1.0.0",
		"eslint-plugin-prettier": "^3.1.4",
		"git-branch-is": "^4.0.0",
		"husky": "^4.2.5",
		"jest": "^26.0.1",
		"lint-staged": "^10.2.11",
		"ngrok": "^3.2.7",
		"node-sass": "^4.14.1",
		"prettier": "^2.0.5",
		"sass-loader": "^9.0.2",
		"semantic-release": "^17.1.1",
		"vue-docgen-cli": "^4.27.0",
		"vue-jest": "^3.0.4",
		"vue-styleguidist": "^4.27.0"
	},
	...
}
```
___
Maybe related to https://github.com/codesandbox/codesandbox-client/pull/4640

## How has this issue affected you? What are you trying to accomplish?

Codesandbox,io isn't really usable for my project if prettier isn't working.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | ?
| Browser          | Chrome 84.0.4147.105
| Operating System | Win 10 1809 LTSC

**Comment by christianalfoni** [comment]
Hi there @Spunkie, 

We suspect this to be related to some interruption in the download of the package. Are you still having issues with this, cause we are not able to reproduce.

**Comment by bitpod-io** [comment]
Can confirm this issue is happening for us too. Url: https://codesandbox.io/s/quirky-mendeleev-8myud?file=/pages/index.vue

**Comment by Spunkie** [comment]
@christianalfoni To be quite frank this "works-for-me" response is far too little too late. My boss has already decided to put in for a chargeback and she added codesandbox to our banned services list. 

And I really can't blame her, my experience has been fucking atrocious. This is seemingly the only support channel, even for pro users. And even though I went out of my way to put in a good detailed support request here, I've been ignored for more than half a billing cycle while my account sits unusable.

**Comment by christianalfoni** [comment]
Hi @Spunkie and thanks for giving direct feedback!

I am sorry to hear about your bad experience. We have certainly not balanced our priorities correctly in this case and need to do better. I am sorry to see you go, but thanks again for pointing out a lack of priority so that it is clear to us where more work is needed!
