### ISSUE TITLE
Console/Problems not working

### ISSUE THREAD

**Issue by thisVioletHydra** [codesandbox/codesandbox-client#4648]
# 🐛 bug report

## Description of the problem
Object does not open in console
## How has this issue affected you? What are you trying to accomplish?
I cannot open the object in the console, when I try to do this, the console is cleared
Animation of my actions
![](https://i.ibb.co/YW6CfxR/codesandbox-issue.gif)
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | https://codesandbox.io/s/weathered-monad-bbrtv?file=/src/index.js |
| Browser          | GoogleChrome 84.0.4147.89 |
| Operating System | windows 10 x64 ver 2004  |

**Comment by thisVioletHydra** [comment]
up
I found that if you change this mode from one value to another, then the tank disappears ...
With what it can be connected?
![image](https://user-images.githubusercontent.com/11839238/89640119-947c2480-d8b7-11ea-9ec8-047ea16f9f1a.png)

**Comment by SaraVieira** [comment]
Hey!

Does this still happen to you? I cannot reproduce it on chrome

**Comment by thisVioletHydra** [comment]
> Hey!
> 
> Does this still happen to you? I cannot reproduce it on chrome

I don't know, maybe this is a chrome bug
But I found another bug, after I unfrozen the template, I cannot save the new changes

```js
const close: AsyncAction<T> = async ({ state }, payload) => {
      state.modals.current = null;
      Object.keys(modal.state).forEach(stateKey => {
        state.modals[name][stateKey] = modal.state[stateKey];
      });
      if (resolver) {
        resolver(payload || modal.result);
      }
    };

```
![image](https://user-images.githubusercontent.com/11839238/89932107-ca057280-dc15-11ea-8e5a-e0559b999bb4.png)

**Comment by christianalfoni** [comment]
@thisVioletHydra Great stuff, thanks for the detailed explanation! This is fixed and should be out shortly! 😄

**Comment by thisVioletHydra** [comment]
i think trouble is gone , ty
