### ISSUE TITLE
Dart support

### ISSUE THREAD

**Issue by Nufflee** [codesandbox/codesandbox-client#465]
I've been playing around with [Dart](https://www.dartlang.org/) lately and this could be a nice addition but I'm sure it'll involve a ton of work. I may or may not try to do it myself ;).  [Dart](https://www.dartlang.org/) is a programming language developed by Google which compiles to JS but also runs on a VM (virtual machine) and mobile (with Flutter). A one complication here might be that I didn't really find a reliable way of invoking [Dart](https://www.dartlang.org/) to JS compiler from JS code other than starting the Dart CLI as a child process.
_This is here only so I can keep track of what I want to do next_

**Comment by pahosler** [comment]
I would very much like to see Dart, Flutter, and Dart Web (aka AngularDart) environments. This may be easier when Google releases [Hummingbird](https://techcrunch.com/2018/12/04/googles-flutter-toolkit-goes-beyond-mobile-with-project-hummingbird/)

**Comment by sanketsahusoft** [comment]
I think it's high time to support Flutter Web. How can I get involved?

**Comment by CompuIves** [comment]
That's awesome @sanketsahusoft! We could definitely use help here, we have instructions here: https://github.com/codesandbox/codesandbox-client/blob/master/contributor-docs/adding-template.md. Let me know if you have any questions!

**Comment by satvikpendem** [comment]
Any update on Flutter support?
