### ISSUE TITLE
Dozens of error reports in Console, even just looking at Dashboard

### ISSUE THREAD

**Issue by LeadDreamer** [codesandbox/codesandbox-client#4655]
# 🐛 bug report

## Description of the problem
I'm seeing dozens of error reports in console simply at the Dashboard for CodeSandBox - running Chrome (Version 84.0.4147.105 (Official Build) (64-bit)) on Win7 (the latter may be my largest problem).

I'm seeing dozens of 
````
scheduler.production.min.js:11 Uncaught TypeError: r is not a function
    at u (scheduler.production.min.js:11)
    at f (scheduler.production.min.js:12)
    at MessagePort.<anonymous> (scheduler.production.min.js:16)
````
and 
````
VM675:1 POST https://sentry.io/api/2071895/store/?sentry_key=f595bc90ce3646c4a9d76a8d3b84b403&sentry_version=7 429 
(Too Many Requests)
````
and
````
Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
````
(the latter also references sentry.io)

Since I use the console fairly extensively, I know I have not been seeing these until recently.

## How has this issue affected you? What are you trying to accomplish?

Rather difficult to debug code issues when dozen of errors continuously show up in the console, regardless of whether I'm at dashboard or in the sandbox.  I thought at first my codebase was getting too large for the IDE (about 750KB across 151 files), but the errors are present on dashboard even after re-start.  I also turned off *all* chrome extensions - no change.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome (Version 84.0.4147.105 (Official Build) (64-bit)) |
| Operating System | Win 7 & Chromebook (Checked on both)

**Comment by CompuIves** [comment]
Seeing it too, I've committed a revert that should solve the issue now. Should be live in a couple min!

**Comment by SaraVieira** [comment]
Revert worked and the errors are now gone :D
