### ISSUE TITLE
react-phone-number-input works outside of codesandbox but crashes in codesandbox

### ISSUE THREAD

**Issue by SCasarotto** [codesandbox/codesandbox-client#4669]
# 🐛 bug report

## Description of the problem

For a while `react-phone-number-input` worked fine on codesandbox. The reason I know this is because I had my component library docs setup in [codesandbox](https://codesandbox.io/s/react-tec-examples-di382?from-embed=&file=/package.json) and some months ago it stopped working all of a sudden. I worked to figure out why it broken and realized when I removed `react-phone-number-input` everything worked like it did previously.

Related: https://gitlab.com/catamphetamine/react-phone-number-input/-/issues/11

## How has this issue affected you? What are you trying to accomplish?

I have tried adjusting the typescript version, tried to change version of other dependencies with no luck.

### Link to sandbox: [link]() (optional)
[Minimal Reproduction](https://codesandbox.io/s/react-phone-number-input-breaks-codesandbox-example-pf32l)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | caab652ef |
| Browser          | Chrome 84.0.4147.105|
| Operating System | 10.15.5 |

**Comment by CompuIves** [comment]
Oh interesting! This file: https://unpkg.com/input-format@0.3.0/modules/react/Input.js is importing from a path with a space. I never thought of that! Fixing...

**Comment by SaraVieira** [comment]
Should be live in about 30m :)
