### ISSUE TITLE
Error if import is not on a top-level

### ISSUE THREAD

**Issue by web2033** [codesandbox/codesandbox-client#4670]
Hello! Who's to blame [here](https://codesandbox.io/s/blue-brook-plcsk)?
[Vite](https://github.com/vitejs/vite#hot-module-replacement) or csb?

First reported here https://github.com/posva/vite-tailwind-starter/issues/75

**Comment by SaraVieira** [comment]
It was on us, we were still not redirecting Vite sandboxes to run in containers with node.

It is now fixed in production, your sandbox won't update but if you open https://codesandbox.io/s/github/posva/vite-tailwind-starter/tree/master you can now fork it no problem
