### ISSUE TITLE
Cannot "Sign In" to connect GitHub repo with CodeSandbox

### ISSUE THREAD

**Issue by smithki** [codesandbox/codesandbox-client#4673]
# 🐛 bug report

## Description of the problem

1. Create a sandbox
2. Select "GitHub" from the sidebar
3. Click "Sign In"
4. `404` - URL shows `https://codesandbox.io/auth/undefined?version=2`

## How has this issue affected you? What are you trying to accomplish?

I am trying to integrate a CodeSandbox with a GitHub repo. Currently blocked on this.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 4730aaaf0 |
| Browser          | Chrome 84.0.4147.105 |
| Operating System | macOS 10.15.5 |

**Comment by SaraVieira** [comment]
Hey!

So sorry for the issue, just pushed a fix, should be live in 20m

**Comment by SaraVieira** [comment]
Fixed :)
