### ISSUE TITLE
Netlify Deploy Build Issue - CSS file(s)

### ISSUE THREAD

**Issue by LeadDreamer** [codesandbox/codesandbox-client#4682]
# 🐛 bug report

## Description of the problem
When deploying to Netlify, quote characters are being removed from:
````
@import url("https://fonts.googleapis.com/css?family=Abril Fatface");
````
changing it to
````
@import url(https://fonts.googleapis.com/css?family=Abril Fatface);
````
Examined file in Console tools, Network tab post-deploy to Netlify

## How has this issue affected you? What are you trying to accomplish?
Unable to use google font on Netlify deployed sandbox.  Can't make it pretty!

### Link to sandbox: [link]() (optional)
can't share sandbox at this time

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome Version 84.0.4147.125 (Official Build) (64-bit)
| Operating System | Win 7

**Comment by LeadDreamer** [comment]
oooo, now we get weird!
this
````
@import "https://fonts.googleapis.com/css?family=Abril Fatface";
````
get replaced by
````
@import url(https://fonts.googleapis.com/css?family=Abril Fatface)
````
I'm looking into if/how I can hand-modify the resulting file directly at Netlify to get around this (but I'd rather have it fixed)

**Comment by LeadDreamer** [comment]
OK, folks, this is a workaround (although NOT a fix):
````
@import "https://fonts.googleapis.com/css?family=Abril+Fatface";
````
becomes
````
@import url(https://fonts.googleapis.com/css?family=Abril+Fatface)
````
which works!

**Comment by SaraVieira** [comment]
Interesting

Are you using any post or pre processors in CSS?

Asking because we don't touch the CSS unless a post or pre processor is used

Is it a CSS file or SASS?

Thank you

**Comment by LeadDreamer** [comment]
Straight CSS (with CSS variables, but that shouldn't matter?)

Build Scripts:
````
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
````

**Comment by SaraVieira** [comment]
yeah, I don't think css variables matters in this case.

Gonna take a look at our CSS Variables

Gonna take a look at this tomorrow

**Comment by LeadDreamer** [comment]
NP, as noted above, I have a pretty easy work around.  Somehow, the quoted string becomes a url() call  - adding the "+" helps it work both ways.
