### ISSUE TITLE
onload event handler not firing

### ISSUE THREAD

**Issue by nibble0101** [codesandbox/codesandbox-client#4683]
# 🐛 bug report

## Description of the problem
I am trying to test something small  but the `onload` event handler doesn't fire. I  added the event handler to the `window` object using `window.addEventListener("load", callback)` and `window.onload = callback` but  handler wouldn't fire in both cases.
 ### Using `window.addEventListener("load", callback)`
```javascript
window.addEventListener("load", function (event) {
  console.log("Page is fully loaded");
});
```
### Using `window.onload = callback`
```javascript
window.onload = function(){
  console.log('Page is fully loaded');
}
```
It is important to point that `onclick` event fires when i add it to a `button` element.

## How has this issue affected you? What are you trying to accomplish?
I want to invoke a function on page load to trigger an animation but the `onload` event handler wouldn't fire.
```javascript
window.onload = function(){
  typeWriterAnimation();
}
```
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Vanilla
| Browser          |  Chrome Version 84.0.4147.105 (Official Build) (64-bit)
| Operating System |  Windows 10. 64-bit operating system

**Comment by smithki** [comment]
This is happening for us, too. We rely on CodeSandbox to share demos of our products to developers, making this a pressing issue for us. Right now our "hello world" demo is in a broken state: https://codesandbox.io/s/github/MagicLabs/example-hello-world

**Comment by smithki** [comment]
Sorry to add further interruptions to those subscribed to the thread, but this is having real-world, negative business impacts for my team. I would appreciate if it was considered a high-priority issue. I can work with the interim solution I described, but ultimately this is a make-or-break scenario for my usage of the CodeSandbox platform.

**Comment by CompuIves** [comment]
This is a tricky one. The code in the `vanilla` template needs to be transpiled and bundled before we can execute it, because of this the code often executes only _after_ the `load` event has been dispatched.

I'm looking at ways we can delay the `load` event until the code actually has been executed, working on it today!

**Comment by guillaume-dorczynski** [comment]
Hello, I have the same problem. As far as I know, it worked until recently, something broke. The sandbox linked by nibble0101 still demonstrating the problem.

I think it's related to this error shown in browser's console:
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
The resource https://codesandbox.io/static/js/babel.7.12.12.min.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

**Comment by rasti9** [comment]
Hello, I have the same problem. It fires from time to time, but not everytime

**Comment by infinite4evr** [comment]
Can we please re-open this issue? Does not work on the Vanilla Js template as well.

**Comment by darkgraycat** [comment]
Hello, have same problem. Please fix.
I love codesandbox.io, and dont want to use another platform (jsfiddle for ex). [onload event](http://jsfiddle.net/1ga2x0vj/)

**Comment by kopax-polyconseil** [comment]
Why is this close ? I just experience the same issue.

**Comment by VanquishedWombat** [comment]
Still a problem today. I googled for a solution but all I can see is setTimeout() hacks. 

Can we have recognition of the issue and information about any possible WAR or FIX? Even if it will not be fixed some kind of response would be good to see.

**Comment by RubenLawkwang** [comment]
Hello just sort the same problem on codePen the onload() function won't start
