### ISSUE TITLE
Crashing repeatedly while accessing sandbox info

### ISSUE THREAD

**Issue by shivamjjha** [codesandbox/codesandbox-client#4690]
<h1>💥 Crash Report</h1>

  <h2>Crashing sandbox while trying to access sandbox info</h2>

  <h3>Link to sandbox: [Sandbox Link](https://codesandbox.io/s/react-google-maps-demo-nqrkm?file=/src/App.js)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 84.0.4147 | Windows 10           | 9fe27eb74          |

  **Route:**
  https://codesandbox.io/s/react-google-maps-demo-nqrkm?file=/src/Map.js

  

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Failed to construct 'URL': Invalid URL
  TypeError: Failed to construct 'URL': Invalid URL
    at Fi (https://codesandbox.io/static/js/app.4cb763821.js?_sw-precache=7ae713067cc964d2e3bd8d4f09f17aeb:306:935334)
    at ua (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1772874)
    at Es (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1818137)
    at ml (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1803713)
    at hl (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1803638)
    at il (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1800966)
    at https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1759149
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1834485)
    at qo (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1758858)
    at $o (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1759094)
  
    in Fi
    in p
    in root
    in y
    in div
    in Markdown___StyledElement
    in Vi
    in div
    in styled.div
    in section
    in Styled(styled.div)
    in div
    in styled.div
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in $m
    in div
    in div
    in ProjectInfo___StyledStack
    in project
    in div
    in je
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by oskarabc** [comment]
Hello @shivamjjha are you still getting this crash? App seems to boot here properly.

**Comment by shivamjjha** [comment]
@oskarabc not while booting, but while accessing sandbox information, i.e., details

**Comment by oskarabc** [comment]
@shivamjjha I see now after forking the box and then access Sandbox Info from the activity bar leads to a crash report!

**Comment by shivamjjha** [comment]
@oskarabc so, how to fix it? How do I change the info?

**Comment by SaraVieira** [comment]
Hey

The error should be fixed, just deployed a fix it will be live in about 20m

It was a super weird error, we read the markdown in the description, and our parser wasn't liking empty links.

Sorry for the issue

**Comment by shivamjjha** [comment]
@SaraVieira Cool, now it is fixed. Thank you for the same✌
