### ISSUE TITLE
Loading GitHub repository fails for repos without master branch

### ISSUE THREAD

**Issue by saurabhdaware** [codesandbox/codesandbox-client#4691]
# 🐛 bug report

## Description of the problem

Hi, I am trying to open https://github.com/abelljs/abell-starter-portfolio in CodeSandbox from https://codesandbox.io/s/github/abelljs/abell-starter-portfolio but it fails with error "Something went wrong. No commit found for SHA: master"

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/github/abelljs/abell-starter-portfolio

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Firefox
| Operating System | Ubuntu

**Comment by SaraVieira** [comment]
Hey

We default to master and we are working on fixing that and checking what is the person's default branch 

For now you need to put /tree/main like so

https://codesandbox.io/s/github/abelljs/abell-starter-portfolio/tree/main

**Comment by saurabhdaware** [comment]
Awesome! Thank you, Sara

**Comment by SaraVieira** [comment]
Gonna leave this open to have a reference to fixing the underlying issue

**Comment by CompuIves** [comment]
We just merged and deployed a fix for this!

**Comment by rayfoss** [comment]
... Now if you do have a master branch but Github does something dumb and makes your default branch feat-darkmode. Deleting that branch and setting master as the default results in `No commit found for SHA: feat-darkmode` Seems to be stuck on the old default branch.
