### ISSUE TITLE
Invalid link markdown (possible any invalid markdown) in sandbox description results in app crash

### ISSUE THREAD

**Issue by VitalyKrenel** [codesandbox/codesandbox-client#4698]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

Hey! The app has crashed after I added an empty markdown link `[some text]()` to the description of my sandbox template and I tried to save it. Looks like using link markdown without actually providing URL results in a thrown exception that is caught anywhere.

There's a room on improving UX by displaying a validation error or a small notification for such a case? Most likely, there are some other possible issues with markdown parsing (i.e. when incomplete or invalid markdown is filled in the description). 

The issue does not seem a huge priority - I just accidentally clicked "Save" button -  but there still might users falling into similar issues with invalid markdown resulting in the crashed app.

  <h3>Link to sandbox: </h3>
<a href="https://codesandbox.io/s/housework-undoer-vue-8752y">Housework Undoer (Vue) template</a>
  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 84.0.4147 | Linux x86_64           | 4be4a4c85          |

  **Route:**
  https://codesandbox.io/s/housework-undoer-vue-8752y

  

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Failed to construct 'URL': Invalid URL
  TypeError: Failed to construct 'URL': Invalid URL
    at Fi (https://codesandbox.io/static/js/app.534b783ed.js?_sw-precache=573bb161a53b93806c66f85bcec4cb73:306:935352)
    at ua (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1772874)
    at Es (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1818137)
    at ml (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1803713)
    at hl (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1803638)
    at il (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1800966)
    at https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1759149
    at https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1834485
    at qo (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1758858)
    at $o (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1759094)
  
    in Fi
    in p
    in root
    in y
    in div
    in Markdown___StyledElement
    in Vi
    in div
    in styled.div
    in section
    in Styled(styled.div)
    in div
    in styled.div
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in $m
    in div
    in div
    in ProjectInfo___StyledStack
    in project
    in div
    in je
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by VitalyKrenel** [comment]
Alright, the issue is worse than I expected: 

When I try to open the "Template info" tab in the template, I experience the crash again, So there's no clear way to get to that tab. I'll try to clear the cache and uninstall the SW and see whether the issue is reoccurring because it got cached somewhere.

**Comment by VitalyKrenel** [comment]
With the cleared storages, I can access the tab - it opens by default when I access the template link - but when I log in and try to open that tab (it does not open by default anymore) I experience the app crash.

Interesting, that while I'm logged out, I see the description containing the empty markdown link `[starting repository]()` in the packge.json description, while when I'm authenticated, it is not present there any more :thinking:

I'm logged out (i.e. after clearing the storage):
![image](https://user-images.githubusercontent.com/17354709/90459882-4bc03900-e10b-11ea-8a72-6eb85ac9e13b.png)


I'm logged in:
![image](https://user-images.githubusercontent.com/17354709/90459819-0c91e800-e10b-11ea-99aa-637221682352.png)

**Comment by VitalyKrenel** [comment]
I've renamed the repository and in the meanwhile use a new template based on the fork, but would be great if somebody could take a look into this bug :female_detective:

**Comment by SaraVieira** [comment]
Hey!


I am so sorry I completely missed this but the good news is that it was fixed a couple of days ago in: https://github.com/codesandbox/codesandbox-client/pull/4785


Sorry for the issues
