### ISSUE TITLE
link to forks when you click the fork icon or count

### ISSUE THREAD

**Issue by faceyspacey** [codesandbox/codesandbox-client#47]
to display the forks, probably a modal makes the most sense and is the easiest.

**Comment by CompuIves** [comment]
Good point, I'll need to build an API endpoint for it, so I'll add it to the list.

**Comment by pkanal** [comment]
@CompuIves did you end up making an API endpoint for this? Is there anyway I can contribute or help make this feature?

**Comment by Saeris** [comment]
Adding this to our pubic backlog. Closing this out for now. Please refer to the link below for the current status of this request:

https://www.notion.so/Add-View-Forks-link-to-Sandbox-Project-Info-2cb75c71809e4f7e8902905f55851735
