### ISSUE TITLE
Dashboard crashing and unable to create new sandboxes

### ISSUE THREAD

**Issue by MinimumViablePerson** [codesandbox/codesandbox-client#4718]
<h1>Unable to reach dashboard or create new sandboxes</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>
Reach the dashboard or create a new sandbox

Even though the status page shows CSB to be 100% operational:

![image](https://user-images.githubusercontent.com/16916098/90526433-4e04b080-e168-11ea-86e6-e7009e654a8d.png)

Trying to reach my dashboard ends up in this:

![image](https://user-images.githubusercontent.com/16916098/90526465-565ceb80-e168-11ea-9d4e-22fba6301bcd.png)

Clicking on the CREATE NEW SANDBOX button does nothing.

**Comment by SaraVieira** [comment]
Hey!

It was a code issue that's why it didn't say

closed by 002236c

Sorry for the issues
