### ISSUE TITLE
Not all dependencies found by TypeScript

### ISSUE THREAD

**Issue by dbartholomae** [codesandbox/codesandbox-client#4734]
# 🐛 bug report

## Description of the problem

The red squiggly lines of TypeScript show that three packages are not installed and TypeScript in the interface acts as if they weren't installed. The code itself runs fine though, which means that the dependencies are installed.
Running the same code locally does not cause any issues.

## How has this issue affected you? What are you trying to accomplish?

I'm trying to set up a codesandbox to explain the TypeScript-side of a library, allowing users to live-edit it.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Yes
| Browser          | Google Chrome
| Operating System | Windows 10

**Comment by SaraVieira** [comment]
@CompuIves this seem to be an issue with the type fetcher

**Comment by CompuIves** [comment]
Oh yes! This slipped, there was an issue with the type fetcher (out of disk space), but that has been resolved now. I verified the sandbox and it works as expected now!
