### ISSUE TITLE
 sandbox not working

### ISSUE THREAD

**Issue by fourneau** [codesandbox/codesandbox-client#4735]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 84.0.4147 | Windows 10           | 17ade25cd          |

  **Route:**
  https://codesandbox.io/u/fourneau/sandboxes

  

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1793951)
    at ms (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1791952)
    at ys (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1793688)
    at yl (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1812953)
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1834485
    at qo (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1758858)
    at bl (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1810838)
    at il (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1801165)
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1759149
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1834485
  
    in div
    in Kn
    in t
    in t
    in div
    in elements__Margin
    in div
    in styled.div
    in div
    in styled.div
    in Unknown
    in div
    in elements__Container
    in Ht
    in r
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by Haroenv** [comment]
Hi @fourneau, could you clarify what is not working?

**Comment by fourneau** [comment]
Bonjour,  le message "quelque chose c est cassé "apparaît a chaque tentative de téléchargement d images et chaque fourchette alors qu'il est mentionné qu un bac a sable à été créer mais n apparaît pas Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Haroen Viaene <notifications@github.com> Date : 19/08/2020  09:33  (GMT+01:00) À : codesandbox/codesandbox-client <codesandbox-client@noreply.github.com> Cc : fourneau <cathyjulien14@orange.fr>, Mention <mention@noreply.github.com> Objet : Re: [codesandbox/codesandbox-client] bac à sable ne fonctionne pas (#4735) 
Hi @fourneau, could you clarify what is not working?

**Comment by SaraVieira** [comment]
Translation:

Hello, the message "something is broken" appears with each attempt to download images and each fork while it is mentioned that a sandbox has been created but does not appear

You are unable to create sandboxes?
