### ISSUE TITLE
always throw errors with target container is not a DOM element.

### ISSUE THREAD

**Issue by janryWang** [codesandbox/codesandbox-client#4736]
# 🐛 bug report

## Description of the problem

![image](https://user-images.githubusercontent.com/4060976/90586989-f1a69d00-e20a-11ea-85fe-643aa6c72947.png)

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/formlily-schema-editor-forked-zu6d3?file=/index.js

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by CompuIves** [comment]
Hey! Apologies for this, it should be fixed now with ae439e5583728daba47b3882172dabcadddf1851.

The problem was with our detection of the index.html file, we normally looked into `public/index.html` for it and didn't account for other cases.
