### ISSUE TITLE
index.html in the root is ignored

### ISSUE THREAD

**Issue by eps1lon** [codesandbox/codesandbox-client#4737]
# 🐛 bug report

## Description of the problem

When I put an `index.html` in the root it is now ignored. Only `public/index.html` seems to work i.e. in

```
codesandbox:.
+---index.html
+---index.js
+---package.json
```

we can't render a React tree since the root element is never injected

## How has this issue affected you? What are you trying to accomplish?

All demos programmatically created from material-ui.com stopped working.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 17ade25cd
| Browser          | Chrome 84
| Operating System | Ubuntu 18.04

**Comment by eps1lon** [comment]
>  CompuIves closed this in ae439e5 4 minutes ago

Reloaded and it works. Much appreciated :heart:  Though it displays 71608d68d as the used codesandbox version which is 17 hours old according to github.

**Comment by CompuIves** [comment]
Ah yes that's true, I first did a rollback to ensure that we have a fix live before the build is done!
