### ISSUE TITLE
Github import exceeds maximum project size

### ISSUE THREAD

**Issue by 98sean98** [codesandbox/codesandbox-client#4738]
# 🐛 bug report

## Description of the problem

I have been trying to import a relatively small [repository](https://github.com/sjyurbanlab/sjyurbanlab.github.io.git) from Github to CodeSandbox, but it keeps failing due to
```
code: This project has reached its maximum size of 10MB
```

I have made sure that the project's default branch is far lesser than 10MB with `node_modules` git-ignored obviously. About 3 weeks ago, I was able to successfully import and create a template out of the same project; but this week importing is no longer possible.

The project is deployed using Github Pages within the same repository in a `master` branch. The default branch that should be imported to CodeSandbox is the default `build` branch. Note that the `master` branch is a lot larger, easily more than `100mb`.

## How has this issue affected you? What are you trying to accomplish?

I want to make the project files easily updatable for the content writers of my team, who are not and do not have to be fluent with the software architecture.

They should be able to import or work on an existing sandbox in a CodeSandbox workspace belonging to the team.

If CodeSandbox is not able to deliver, the team may need to resort to using the Github browser editor, which is not ideal because they cannot see the files they are updating without React hot-reloading.

### Link to previously created template from 3 weeks ago: [link](https://codesandbox.io/s/sjyurbanlabsjyurbanlabgithubio-6x9gf)

N/A

### Your Environment

This is a `React-Gatsby-Typescript` project.

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest on browser
| Browser          | Chome Version 84.0.4147.125 (Official Build) (64-bit)
| Operating System | MacOS Catalina 10.15.5

Appreciate the help.

**Comment by CompuIves** [comment]
Hey @98sean98! It seems like we're importing the `master` branch here, which is around 70MB. If you're meaning to import the `build` branch here, it should work with this link: https://codesandbox.io/s/github/sjyurbanlab/sjyurbanlab.github.io/tree/build.

This is a limitation on our side, we should rather import the default branch instead of assuming we need to import `master`. This is something that we still need to fix!

**Comment by 98sean98** [comment]
@CompuIves Thanks for pointing that out. As a workaround, I have shifted the source code to a different repository, and CodeSandbox is able to import that instead, without any problems.

A suggestion I have for the maintainers is to make the documentation clearer by including the precise limitation to github imports like individual file maximum size, overall project size, maximum number of files, etc. To a lot of people, and from the list of issues I've seen, there have been too many cases where unexpected hiccups related to such limitations occurred.
