### ISSUE TITLE
 Downloading is disabled in Chrome in the Preview window

### ISSUE THREAD

**Issue by DevExpressSupportTeam** [codesandbox/codesandbox-client#4739]
## Description of the problem

We use CodeSandBox to demonstrate export in our online demos.

Steps:
Open the demo
Click the `Export` button.

Results:

Export doesn't work in Chrome because `iframe` doesn't have the allow-downloads attribute. You'll see the corresponding warning in the browser console:

>Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details.

## How has this issue affected you? What are you trying to accomplish?

This behavior confuses our customers. So, two questions here:
-  Is it possible to add "allow-downloads" by default ? Though it looks unsafe in a common case
- Is it possible to add an option to CLI so that we can enable  "allow-downloads" when we use your API to generate CodeSandBox in our [demos](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/ExportCustomMarkup/Vue/Light/).

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox   |    |
| Browser          |  Chrome 84 |
| Operating System | Windows 10 |

**Comment by christianalfoni** [comment]
Hi there @DevExpressSupportTeam ,

I am sorry, but I am not able to reproduce the issue. I open the demo page and click export. The file downloads.

Maybe you fixed it? If not, please let me know 😄

**Comment by KuznetsovVN** [comment]
Hi guys,

I faced a similar problem. I've created a simple example to demonstrate this:
https://codesandbox.io/s/react-filesaver-example-wc1k9
https://i.gyazo.com/d261852bedfa902409705cba0c7ea212.gif

**Comment by SaraVieira** [comment]
Hey!

Adding the allow download tags since browsers will not let downloads start automatically, will not be added to any embedded for security reasons and only to the sandbox inside codesandbox.io
