### ISSUE TITLE
Preview Not Working

### ISSUE THREAD

**Issue by erichung426** [codesandbox/codesandbox-client#4741]
# 🐛 bug report

### Link to sandbox: https://codesandbox.io/s/sharp-forest-chvrt

**Comment by SaraVieira** [comment]
Hey!

I am so sorry for the issue you had, it seems top be fixed now

Can you please confirm?

**Comment by erichung426** [comment]
Hi Sara,

Yes, it has been fixed now. Thank you so much!

Best regards,
Eric

**Comment by SaraVieira** [comment]
Awesome!

Thank you

**Comment by MSid01** [comment]
I was facing codesandbox crashes. Make sure that you have typed correctly. I mistyped  latitude as "slatitude" it was crashing again and again because of that.
