### ISSUE TITLE
Codesandbox not recognizing sass modules with @use when using dart-sass

### ISSUE THREAD

**Issue by jjloneman** [codesandbox/codesandbox-client#4742]
## Problem

[Sass released a module system](https://sass-lang.com/blog/the-module-system-is-launched) where `@use` can replace `@import` amongst other features.

Unfortunately, [`node-sass` does not support the new module system, only `dart-sass`](https://github.com/sass/node-sass/issues/2886#issuecomment-634510168).

[The `sass` npm module](https://www.npmjs.com/package/sass) is the implementation of `dart-sass`, which is supported by `create-react-app`.

## Code Sandbox Example

* [codesandbox reproduction](https://codesandbox.io/s/codesandbox-react-scss-bug-hqu4x)

Using the `react` template in codesandbox and adding the `bootstrap` and `sass` packages, adding `styles.scss` with the `@import` rule works:

```scss
@import "~bootstrap/scss/bootstrap";
```

but using the `@use` rule does not work:

```scss
@use "~bootstrap/scss/bootstrap";

.App {
  @include bootstrap.float-right();
}
```

and displays the following error:

![image](https://user-images.githubusercontent.com/16791848/90673924-65a26e80-e226-11ea-84d0-b8defaf3e353.png)

## Local Example

Exporting the sandbox to a zip through `File > Export to Zip` and running `npm install` and `npm start` works (the text is supposed to float right):

![image](https://user-images.githubusercontent.com/16791848/90674275-e95c5b00-e226-11ea-922b-276e331c2c7b.png)

**Comment by SaraVieira** [comment]
Hey!

We currently do not support `dart-sass` as we run all the sass compilations through node and web workers

As soon as this is supported in `node-sass` it will be added, I subscribed to the issue mentioned so we can upgrade as soon as it's added

Sorry for the issue

**Comment by Donov4n** [comment]
Sadly, `node-sass` is [deprecated](https://github.com/sass/node-sass#node-sass) and the module support will probably never be implemented.   

Is a migration to `dart-sass` being considered?

**Comment by wesgro** [comment]
Could this be re-opened?

node-sass is dead and not being able to use sass modules in a codesandbox gives me bad feels.

**Comment by jjloneman** [comment]
Regarding @Donov4n's and @wesgro's comments, `node-sass` is indeed deprecated. As per their [GitHub](https://github.com/sass/node-sass#node-sass):

> **Warning**: LibSass and Node Sass are deprecated. While they will continue to receive maintenance releases indefinitely, there are no plans to add additional features or compatibility with any new CSS or Sass features. Projects that still use it should move onto Dart Sass.

@SaraVieira, you mentioned:

> We currently do not support `dart-sass` as we run all the sass compilations through node and web workers

but is there a specific reason that sass compilations through node can't use `dart-sass`? According to their readme, their [JavaScript api is **fully compatible with Node Sass**](https://github.com/sass/dart-sass/blob/master/README.md#javascript-api):

> When installed via npm, Dart Sass supports a JavaScript API that's **fully
> compatible with [Node Sass][]** (with a few exceptions listed below), with support
> for both the `render()` and `renderSync()` functions. See [the Sass
> website][js api] for full API documentation!
> 
> [Node Sass]: https://github.com/sass/node-sass
> [js api]: https://sass-lang.com/documentation/js-api
> 
> Note however that by default, **`renderSync()` is more than twice as fast as
> `render()`** due to the overhead of asynchronous callbacks. To avoid this
> performance hit, `render()` can use the [`fibers`][fibers] package to call
> asynchronous importers from the synchronous code path. To enable this, pass the
> `Fiber` class to the `fiber` option:
> 
> [fibers]: https://www.npmjs.com/package/fibers
> 
> ```js
> var sass = require("sass");
> var Fiber = require("fibers");
> 
> sass.render({
>   file: "input.scss",
>   importer: function(url, prev, done) {
>     // ...
>   },
>   fiber: Fiber
> }, function(err, result) {
>   // ...
> });
> ```

They also have a [standalone executable](https://sass-lang.com/dart-sass) to compile sass files:

> Dart Sass's stand-alone command-line executable uses the blazing-fast Dart VM to compile your stylesheets. To install Dart Sass on the command line, check out the installation instructions. Once you've got it running, you can use it compile files:
>
> ```bash
> sass source/index.scss css/index.css
> ```

**Comment by Aleksandyr** [comment]
Why don't you reopen this issue as more and more people rely on the new dart-sass compiler?

**Comment by SaraVieira** [comment]
@CompuIves @christianalfoni Should this be reopened? Is there a way to get dart sass in CodeSandbox?

**Comment by CompuIves** [comment]
Yes that'd be good! Jasper is looking into this. So far we haven't found a
reliable way to get dart-sass to run in the browser.

**Comment by Aleksandyr** [comment]
@CompuIves @SaraVieira at least we can reopen the issues so that the users know you are working on it.

**Comment by SaraVieira** [comment]
If there is a way then sure! It's reopened!

**Comment by CompuIves** [comment]
Thanks a lot @SaraVieira ❤️ . This is a good place to track @DeMoorJasper 😄
