### ISSUE TITLE
EJS error unexpected token

### ISSUE THREAD

**Issue by keinydev** [codesandbox/codesandbox-client#4746]
# 🐛 bug report

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 
| Browser          | All
| Operating System |

**Comment by SaraVieira** [comment]
Hey!

It seems you sandbox doesn't exist anymore, but at the moment we do not support EJS in client sandboxes only in containers (https://codesandbox.io/docs/environment#container-environment) as this is a docker container where you can install the compilers
