### ISSUE TITLE
Error: "$csb__dommodule.DomModule.import is not a function" on webcomponent import

### ISSUE THREAD

**Issue by armujahid** [codesandbox/codesandbox-client#4747]
# 🐛 bug report

## Description of the problem
Sandbox with webcomponent import (e.g. vaadin-button) isn't working on codesandbox although same sandbox works fine locally if I export it and do `npm i` and `npm start`

### Link to sandbox: https://codesandbox.io/s/recursing-swartz-tbe4y?file=/src/index.js

Linked question: https://stackoverflow.com/q/63472052/2073920

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Production version as of 2020-08-21 (I think v3.9.1)|
| Browser          | All |
| Operating System | Windows |

**Comment by CompuIves** [comment]
Ah, yep, this is a valid issue. The `import` is renamed while it shouldn't be, I will take a look at fixing this this week!

**Comment by armujahid** [comment]
This issue is still there so we should keep this thread open.

**Comment by CompuIves** [comment]
I think this one has been solved now! 🎉 

Could you verify @armujahid ?

**Comment by armujahid** [comment]
@CompuIves yes. it's fixed :tada: Thanks :)
