### ISSUE TITLE
POST method used for loading websites fails, cannot load non-index HTML pages

### ISSUE THREAD

**Issue by ScholarlyGaming** [codesandbox/codesandbox-client#4750]
# 🐛 bug report

## Description of the problem

I have multiple static sandboxes that I store websites on. When I attempted to view my webpages, it tried and succeeded in loading a non-index site (here https://wg0pq.csb.app/creator.html), but after a second it will fail and load data from the index page instead. It appears to load the head of the desired HTML page but the body of the index page. I am currently using Chrome running Chrome OS Version 81.0.4044.141 but I also tested it on a Windows 10 PC using Edge to get the same effects. 

Checking using the developer mode, I saw that a POST fetch command failed to load, which I am guessing is the underlying issue here. Specificially, it tries to connect to https://col.csbops.io/data/sandpack. 

## How has this issue affected you? What are you trying to accomplish?

Because of this, my static websites that previously worked are basically completely broken now. However, this has only started recently - around August 9 it was clearly working as intended. None of my code has changed since then (except for after I noticed this and tried some debugging), so some client change must have introduced this.

### Link to sandbox: [link](https://wg0pq.csb.app/engine.html?blueDeck=&redDeck=&version=current&order=true&maxElixir=10&elixirR=1) (optional)

It will attempt to load a Processing.js program, succeed for about a second, and then load an entirely different page - the index page with incorrect styling.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 0d15157e6 |
| Browser          | Chrome |
| Operating System | Chrome OS Ver. 81.0.4044.141 |

(Again, also fails on current Windows 10 with Edge.)

**Comment by CodeSandboxNotifications** [comment]
Hey!


This has just been fixed this morning

—
Thank you
Sara Vieira

--- original message ---
On August 28, 2020, 10:29 AM GMT+2 notifications@github.com wrote:



Closed #4750 via 71d7b12.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---
