### ISSUE TITLE
ModuleNotFoundError Could not find module in path (no space left on device)

### ISSUE THREAD

**Issue by auszug** [codesandbox/codesandbox-client#4753]
# 🐛 Codesandbox can't download npm dependency

## Description of the problem

[The following sandbox](https://codesandbox.io/s/purple-lake-z3lqw?file=/src/App.js) doesn't work, because one of the dependencies cannot be imported:

```
GET https://ata.codesandbox.io/api/v8/okdb-client%40%5E1.2.2.json
```

Fails with 422 status code, and the 'no space left on device' message in the response text:

```
Extracting tar content of undefined failed, the file appears to be corrupt: \"ENOSPC: no space left on device, write\"\n",
```

## How has this issue affected you? What are you trying to accomplish?

The sandbox doesn't function and cannot be used.

### Link to sandbox: 

[Link to the affected codesandbox](https://codesandbox.io/s/purple-lake-z3lqw?file=/src/App.js)

### Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Cloud |
| Browser          | Chrome 84.0.4147.89 |
| Operating System | MacOS |

**Comment by auszug** [comment]
@CompuIves @SaraVieira - will be happy about your feedback.

**Comment by CompuIves** [comment]
Hey! I fixed the other issue with ata.codesandbox.io, but I think there's another issue with `react-designer`. It seems like the `lib` folder wasn't published (of `react-designer`), when looking here: https://unpkg.com/react-designer/.

**Comment by auszug** [comment]
Many thanks! Ok, will try to publish it on my own.
