### ISSUE TITLE
Global snippets file does not show up on other machine

### ISSUE THREAD

**Issue by mokanfar** [codesandbox/codesandbox-client#4755]
# 🐛 bug report

## Description of the problem
Create a global snippets file on 1 machine, switch over to another machine, access my codesandbox workspace, try to pull up the global snippets file, global snippets file does not exist. Tried in incognito mode as well.

## How has this issue affected you? What are you trying to accomplish?
Yes. Have universal snippets configuration on my codesandbox.io account

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox    |  latest|
| Browser         | chrome 84 |
| Operating System  | windows 7|

**Comment by SaraVieira** [comment]
Hey!

Right now all your settings are stored on your machine only for security reasons so that's why when you go in incognito or change the computer you need to start over in terms of settings

You can save it in a gist and copy and paste it at least for now until we come up with a way for you to sync on demand

**Comment by mokanfar** [comment]
Thanks for your response but that is baffling. An account should be able to preserve custom settings on any machine. That's kind of like the point to your service isn't it? Code anywhere on any machine?

If an account possesses custom sandbox projects that is available on any machine, their settings above all else should be available on any machine as well. What's stopping me right now from making a private sandbox with all my snippets in JSON files and just transporting it that way instead of a gist?

**Comment by SaraVieira** [comment]
Oh definitely, we do intend to fix this, my idea was a gist just to not save it in the database as that feels like too much.

I wanted to create a system that works like vscode settings sync where you have a main machine and the other machines can get those settings
