### ISSUE TITLE
How to make a self deployed codesandbox in local intranet network

### ISSUE THREAD

**Issue by liudonghua123** [codesandbox/codesandbox-client#4756]
# 🌈 Feature

Due to the speed of network problems, I want to run a locally deployed codesandbox on my own intranet server. And from the readme, I find this repo is just a client part, the server part is not open source. Is there any plans for make the server part open source, or is there some repos which have implement the server part.

Make a self deployed codesandbox possible and easy deployable.

I hope the basic core and/or basic parts of codesandbox could be open source, then anyone intrested in could make contributes, improve it, and enrich the ecological environment.

**Comment by SaraVieira** [comment]
Hey

For security reasons, it is not possible for us to make the server open source as we are also a company and as bad as that sounds we need to make money.

I am sorry for your issues but for now, you can access all the other repos but need to connect to our backend so we can make sure that we provide a safe service
