### ISSUE TITLE
Unable to login to Codesandbox on an in private window

### ISSUE THREAD

**Issue by quantum-devcraft** [codesandbox/codesandbox-client#4758]
# 🐛 bug report

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by sannek** [comment]
Hi, as far as I know this was a temporary issue that affected more people but has now been resolved. I'm closing it for now, but please let me know if you're still having trouble!
