### ISSUE TITLE
Blank lines in empty Sass files trigger compilation error

### ISSUE THREAD

**Issue by HristoP96** [codesandbox/codesandbox-client#4760]
# 🐛 bug report

## Description of the problem
Having a sandbox with blank lines in an empty scss file results in compilation error -  **Expected 'styles' to be an array of strings.**

## How has this issue affected you? What are you trying to accomplish?
The sandbox gets broken and it is not very clear what the problem might be.

### Link to sandbox: [link](https://codesandbox.io/s/scss-empty-line-error-rev4r)
The problem is in the sandbox's SCSS file - [link-to-scss-file](https://codesandbox.io/s/scss-empty-line-error-rev4r?file=/src/app/app.component.scss)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome - 84.0.4147.135 (Official Build) (64-bit)
| Operating System | Windows 10

**Comment by siddharthkp** [comment]
Hi!

Seems like this is a bug in `angular-cli`: [angular-cli #7245](https://github.com/angular/angular-cli/issues/7245) 🤔 

We don't have an angular expert on the team. Reading through the above issue, I don't see any workaround either - other than not having an empty scss file 😓

**Comment by HristoP96** [comment]
> Hi!
> 
> Seems like this is a bug in `angular-cli`: [angular-cli #7245](https://github.com/angular/angular-cli/issues/7245) 🤔
> 
> We don't have an angular expert on the team. Reading through the above issue, I don't see any workaround either - other than not having an empty scss file 😓

@siddharthkp  Thank you for looking into this and for the provided information :).
