### ISSUE TITLE
422 error - Git Repository is Empty

### ISSUE THREAD

**Issue by bobziroll** [codesandbox/codesandbox-client#4763]
# 🐛 bug report

## Description of the problem
I'm attempting to fork/PR someone's GitHub repo (or a subfolder therein), make some comments, and submit a PR. Not every time, but many times I get a 422 error and a message that says "Git repository is empty".

## How has this issue affected you? What are you trying to accomplish?
I'm hoping to use Codesandbox to provide feedback to our students code by pulling in their repositories, making comments and changes, and submitting a PR to them.

### Link to sandbox: (One of many that are having similar problems)
[link](https://codesandbox.io/s/unruffled-proskuriakova-pjje8)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  ??
| Browser          |  Chrome Version 84.0.4147.135 (Official Build) (64-bit)
| Operating System | MacOS 10.15.6

**Comment by SaraVieira** [comment]
Hey!

First of all, can you confirm that this is still happening, please?

Also are these repositories empty or is it an issue where we don't detect that they do have things in them?

**Comment by bobziroll** [comment]
Yes, it is still happening. I'm trying to fork and PR against [this repo](https://github.com/PhoenixTilea/assignments/tree/master/module1/dj-js)

Receiving this error toast message:

<img width="445" alt="Screen Shot 2020-08-31 at 7 33 17 AM" src="https://user-images.githubusercontent.com/6244647/91725700-55f72400-eb5c-11ea-95a5-719e145bbf4c.png">

My first thought would be that it has something to do with this folder being a nested subfolder of the actual top-level repo, but I've been able to successfully do this with other of our students' repos without any issues. I can't tell offhand what the differences between the ones that work and the ones that don't work are.

[Here's another](https://github.com/nathanspnsrd/module1/tree/master/dom1/dj-js) one of our students' assignments (same assignment linked above, different repository & GitHub user) that works just fine to PR from CodeSandbox

**Comment by SaraVieira** [comment]
I am going to ping @christianalfoni as he may know what is happening

Thank you so much for all your info

**Comment by christianalfoni** [comment]
Hi there @bobziroll !

I was not able to reproduce forking and creating PR of: https://github.com/PhoenixTilea/assignments/tree/master/module1/dj-js , typical 😉 

I am a bit unsure what is happening here, but I wanted to ask you a couple more questions:

1. How does your students create their repos? Using Github UI? I would suggest initializing them with a README (checkbox when you create). This is related to properly initializing the repo. I am not sure how much this affects repo creation these days, but previously it was a requirement. It should not really be the reason, but I wanted to mention it

2. Does it start working after a while or is it consistent with certain repos? Do you know how long since the student made the commits you try to make a PR on them?

**Comment by bobziroll** [comment]
@christianalfoni Ugh, yeah that's frustrating that it's working for you lol 😝 . But it does give me hope that it _could_ work for me! I just tried that same repo that worked for you in an incognito window (in case it was an extension causing the issue) and it still didn't work for me. 😢 

1. We have our students create a single repository for all their assignments when they first start the class. They add folders to the repo for each new assignment and commit them as they're working on them and when they're done. They do this entirely with command-line Git (at least, I assume that's the case because that's what we teach them). I usually recommend they not create a README in case they created the local repo first and run into "unrelated histories" issues, but if this solves the problem I could change that.
2. It appears to be consistently broken for some repositories, and consistently working for others. Below you can find a list of working and broken ones.

---

### PRs Working
* [Nate's assignment](https://github.com/nathanspnsrd/module2/tree/master/css2/dj2) - [Sandbox](https://codesandbox.io/s/dreamy-curran-y7rop)
* [Mia's assignment](https://github.com/mia-jane/school/tree/master/module-1/flags) - [Sandbox](https://codesandbox.io/s/morning-monad-4zn3b)
* [Mack's assignment](https://github.com/Mackers802/V_School-Assignments/tree/master/Mod_1/Flags) - [Sandbox](https://codesandbox.io/s/flamboyant-haslett-2crrc)

### PRs Broken
* [Zach's assignment](https://github.com/zheckert/Assignments/tree/master/arrayReduceExercies) - [Sandbox](https://codesandbox.io/s/relaxed-cerf-kk6j3)
* [Sabelyn's assignment](https://github.com/PhoenixTilea/assignments/tree/master/module1/moms-shopping-list) - [Sandbox](https://codesandbox.io/s/red-leftpad-2gi3x)

---

Also, [I recorded a video](https://youtu.be/2a0p3CBRX5s) of how I went about trying to Fork/PR these projects, in case I happen to be doing something wrong or in case it helps somehow.

Hopefully that helps! Sorry it's taken me awhile to respond. Going to see if I can turn on notifications for this thread because finding a fix for this would be the best ever.

**Comment by bobziroll** [comment]
@christianalfoni I know you're probably swamped, but I was just curious if there had been any updates? Since you didn't seem to have any problems submitting the PR on your side, I assume something about the way I'm doing it or my setup is causing the problem somehow.

Let me know if you have any insights! And thanks again for looking in to this.

**Comment by bobziroll** [comment]
Ah, that makes so much sense! Thanks for finding that @christianalfoni. I'll test out those options for a workaround to see which solution will be best for us.

**Comment by bobziroll** [comment]
@christianalfoni I was about to close this issue, but realized it may be a good improvement to make in the future. If you'd like to close it though, you're welcome to.
