### ISSUE TITLE
An API to programatically or dynamically start codesandbox container

### ISSUE THREAD

**Issue by warrencaruana** [codesandbox/codesandbox-client#4767]
# 🌈 Feature

**Comment by SaraVieira** [comment]
You mean by an API call?

**Comment by andrasbacsai** [comment]
Please take a look at this discussion: https://github.com/codesandbox/codesandbox-client/discussions/4759
It's written in details how you can start container sandboxes with API call.

I'm closing this issue now, as the feature you are requesting is probably already implemented.
If not, please reopen this issue and provide more details of your feature request.
