### ISSUE TITLE
 console.log() not working inside a functional component.

### ISSUE THREAD

**Issue by ankur29mac** [codesandbox/codesandbox-client#4769]
# 🐛 bug report

## console.log is not logging anything into the console when used anywhere inside Functional Component.

I was trying to log in the value of the state inside my functional component(using React Hooks) into the console but there is no output. I tried the same code on my local react development environment and there was no issue, it worked fine.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 51a77aed1
| Browser          |  Google Chrome
| Operating System | Elementary OS

**Comment by russelldc** [comment]
Your problem is caused by Line 5 of your `index.js`:

```js
// import App from "./App";
import FxApp from "./App";
```

That second line should be importing from `"./FxApp"` instead.

**Comment by ankur29mac** [comment]
Thank you. I can't believe i totally missed that.
