### ISSUE TITLE
GitHub commit not working

### ISSUE THREAD

**Issue by marco910** [codesandbox/codesandbox-client#4770]
Hi,

Since a few weeks I have a problem with my Gatsby sandbox on Codesandbox. If I open the sandbox in my browser (Chrome, latest version) it shows me, that some changes are not committed to the GitHub-repo. If I commit them only a few of them are pushed to GitHub but not all. Now the list of new, added or deleted files in Codesandbox is empty. But if I refresh the page it shows me exactly the same changes, which "should" be not committed.

If I create new files or edit existing one in the sandbox they are showed as changes in the GitHub-tab of the sidebar. When I try to commit them they disappear in the changes-list but not being pushed to GitHub.

**Comment by christianalfoni** [comment]
@marco910 Hi Marco!

Is this a private sandbox or a public one? Could you link to the sandbox?

We have gotten reports on this, but are unable to reproduce the issue so we really just need a Sandbox where we can see the problem 😄

**Comment by marco910** [comment]
Hi @christianalfoni !

The sandbox was a private one.
In the meantime I also tried to solve the problem. For that I deleted the sandbox, created a new one from the GitHub repo and then exported all to a new repo. This seems to work now. 😄
