### ISSUE TITLE
Problem with inline JavaScript

### ISSUE THREAD

**Issue by happyCoda** [codesandbox/codesandbox-client#4776]
# 🐛 bug report

When I try to use an inline script in html and do something with DOM in that script it works ok, but then DOM re-renders and all my changes disappear of course. If I move my js to separate file and use it via src everything works as it should.

I was trying to use web components on my page and all shadow dom disappears

Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |5459ae02b
| Browser          |84
| Operating System |macOS

**Comment by SaraVieira** [comment]
Hey!

Can you please provide an example sandbox?

**Comment by happyCoda** [comment]
Hi @SaraVieira,
Sorry for the long response but it seems that I can't reproduce this behaviour anymore. May be one of the latest commits fixed that bug. I'll be observing on this and close issue for now.

**Comment by SaraVieira** [comment]
Thank you for checking it out :)
