### ISSUE TITLE
Vue3 + TS "Could not find module in path: 'vue/dist/vue.common.js' relative to '/src/main.ts'"

### ISSUE THREAD

**Issue by andy3520** [codesandbox/codesandbox-client#4781]
# 🐛 bug report

## Description of the problem
Could not find module in path: 'vue/dist/vue.common.js' relative to '/src/main.ts'

## How has this issue affected you? What are you trying to accomplish?
Run vue3+ ts example

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |latest|
| Browser          | 84.0.4147.135 (Official Build) (64-bit)|
| Operating System | MacOS Mojave|

**Comment by CompuIves** [comment]
Ah, yep this might be related to an alias that we set. It probably works for Vue2 but doesn't work for Vue3, I can take a look later today or next week on whether we can make it conditional for Vue 3 vs Vue 2.
