### ISSUE TITLE
Preview on edit setting gets ignored

### ISSUE THREAD

**Issue by OnkelTem** [codesandbox/codesandbox-client#4784]
I disabled "preview on edit" setting, reloaded the page but it continues to update the preview slowing down editing to almost unusable state. How to properly DISCONNECT my editor with the preview window? I really don't want it to get updated while I'm editing.

**Comment by CompuIves** [comment]
Hey @OnkelTem, when you disable "Preview on edit", does it still update the preview on changing code? Or only on save? The intended behaviour is to still update on saving, but we probably should clarify that better. You don't want to update it at all?

Another trick that you could do is hide the preview while writing code. You can do this by pressing `(Ctrl/CMD)+Shift+D`.

**Comment by SaraVieira** [comment]
Hey

Closing this as it seems fixed :)

When working on things like this closing the preview is the best idea. There is also a button here: 
![CleanShot 2020-12-02 at 16 30 59](https://user-images.githubusercontent.com/1051509/100893588-d0b53f80-34bb-11eb-81f4-c694aa840898.png)
