### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by ad99526** [codesandbox/codesandbox-client#4788]
# 🐛 bug report

## Description of the problem
The auto-save toggle feature doesn't  work properly. When I'm turning it off still it auto-saves my code and re-loads the page. 

## How has this issue affected you? What are you trying to accomplish?
This consumes a lot of my production time. I love to use sandbox. Please resolve this issue.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/vibrant-bartik-itd1j?file=/src/App.js

### Your Environment
I'm use mostly React
| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
https://codesandbox.io/s/vibrant-bartik-itd1j?file=/src/App.js
| Browser          |
Brave
| Operating System |
Linux/ Ubuntu 19.10

**Comment by SaraVieira** [comment]
Hey!

Do you mean autosave for the code or auto preview?

The preview settings are here:
![CleanShot 2020-08-31 at 14 32 53](https://user-images.githubusercontent.com/1051509/91720134-df2b4c80-eb96-11ea-8dbd-fe9177c85b0d.png)


But the autosave for VSCode is in their settings

**Comment by SaraVieira** [comment]
Hey,

You seem to have either "Preview on edit" or "Instant preview" on in your preferences, by turning those off your code should only run when you save it.

You can do that by going to preferences:



and then going to the preview settings:



Please let me know if this fixes it for you

**Comment by SaraVieira** [comment]
Sorry, I forgot how to githb

**Comment by ad99526** [comment]
> Hey!
> 
> Do you mean autosave for the code or auto preview?
> 
> The preview settings are here:
> ![CleanShot 2020-08-31 at 14 32 53](https://user-images.githubusercontent.com/1051509/91720134-df2b4c80-eb96-11ea-8dbd-fe9177c85b0d.png)
> 
> But the autosave for VSCode is in their settings

I meant autosave for the code and preview both. I'll explain. If I make a change in my code, the preview re-renders which I dont want to happen. Also I cant find the settings you shown in image.

**Comment by SaraVieira** [comment]
Oh sorry 

To access those settings you need to click on your face, then preferences and then navigate to preview

Let me know if adding the settings I showed fixes it

**Comment by SaraVieira** [comment]
Closing this for lack of response and seems to be a settings issue
