### ISSUE TITLE
Dragging a tab around is causes the codesandbox crashing every time, like this video shows below.

### ISSUE THREAD

**Issue by iblueer** [codesandbox/codesandbox-client#4793]
# 🐛 bug report

## Description of the problem

I found that if dragging a tab around, codesandbox crashes every time, like this video shows below.

## How has this issue affected you? What are you trying to accomplish?

I want move the arrangement of tabs, it is really usual on VSCode but hard on codesandbox, it should be fixed for user experience I think.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | the online version |
| Browser          | Chrome 85 |
| Operating System | macOS Catalina and Big Sur |

## Video

![screen-recording](https://user-images.githubusercontent.com/3581944/91793994-70a8c600-ec4c-11ea-9ac4-a2c864c20d97.gif)

**Comment by CompuIves** [comment]
Wow, I can't reproduce this issue, which is really weird. Do you only see this in the PWA? Or do you see it on the website as well?

**Comment by iblueer** [comment]
> Wow, I can't reproduce this issue, which is really weird. Do you only see this in the PWA? Or do you see it on the website as well?

It only appears in the PWA.

**Comment by iblueer** [comment]
Actually, this bug has been fixed.
