### ISSUE TITLE
Code Sandbox Rendering Blank Page, No Errors

### ISSUE THREAD

**Issue by crickschmelz** [codesandbox/codesandbox-client#4798]
# 🐛 bug report

## Description of the problem

The program is rendering a blank page, but there are no errors listed. I've checked my index.html, index.js, and my Router component, and I don't see anything wrong (although I could be missing something). React DevTools doesn't show any of the components either.

### Link to sandbox: [link]() (optional) 

https://codesandbox.io/s/dog-walker-website-fkinn?file=/src/components/HomePage.js

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by SaraVieira** [comment]
Hey!

Can you please let me know what browser you are using?

**Comment by crickschmelz** [comment]
Yep! I'm using Google Chrome, and all my other projects on Code Sandbox are
working just fine.

**Comment by SaraVieira** [comment]
Interesting, I am also using Chrome and seems to work can you please tell me what is the version?

**Comment by crickschmelz** [comment]
I'm using  Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by SaraVieira** [comment]
I have tried and I cannot reproduce this issue, I can see the page just fine 
![CleanShot 2020-09-03 at 14 30 25](https://user-images.githubusercontent.com/1051509/92114983-06ca2100-edf2-11ea-89e3-3d047c1121ed.png)
![CleanShot 2020-09-03 at 14 30 21](https://user-images.githubusercontent.com/1051509/92114985-0762b780-edf2-11ea-898b-dc5f275f2b1f.png)

Does it work in incognito? It may be an extension

**Comment by crickschmelz** [comment]
I restarted my whole computer, and now I can see it. Not sure what the
issue was (likely a missing update I guess?) - sorry for the trouble, but I
appreciate your help!

**Comment by SaraVieira** [comment]
No worries, glad we got this fixed :)
