### ISSUE TITLE
GitHub integrations show `Bad Credentials` error in incognito

### ISSUE THREAD

**Issue by smithki** [codesandbox/codesandbox-client#4799]
# 🐛 bug report

## Description of the problem

We use CodeSandbox extensively for open-source demoing. Unfortunately, our sandboxes that rely on the built-in GitHub integration are showing a "Bad Credentials" error on every browser:

<img width="776" alt="Screen Shot 2020-09-01 at 11 57 25 AM" src="https://user-images.githubusercontent.com/22753882/91889720-85d12500-ec4b-11ea-8530-a99fe6e34f77.png">

## How has this issue affected you? What are you trying to accomplish?

Our demos/onboarding is completely broken. First impressions are hard to fix.

### Link to sandbox:

https://codesandbox.io/s/github/MagicLabs/example-hello-world

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | `e3a6940fd` |
| Browser          | Firefox/Chrome/Safari |
| Operating System | macOS 10.15.6 |

**Comment by SaraVieira** [comment]
Hey

This is weird, it works well in my computer using both Chrome and Firefox.

I tried opening the links from the docs and they all seemed fine, are there any more clues you can give me?

<img width="1790" alt="CleanShot 2020-09-01 at 20 12 45@2x" src="https://user-images.githubusercontent.com/1051509/91890269-82f82380-ec8f-11ea-9b77-e3793917fbdd.png">


<img width="1647" alt="CleanShot 2020-09-01 at 20 12 12@2x" src="https://user-images.githubusercontent.com/1051509/91890227-71af1700-ec8f-11ea-9261-114ceb974a2b.png">

**Comment by smithki** [comment]
Try in incognito. This bug does not occur if the CodeSandbox service worker cache is already installed.

**Comment by SaraVieira** [comment]
Indeed yeah it does not work, this seems an issue with the GitHub service, @CompuIves @christianalfoni

**Comment by CompuIves** [comment]
Hey @smithki, thanks for letting us know! It should be fixed now, apologies for the inconvenience!

**Comment by smithki** [comment]
Always so quick and on top of things! Much appreciated CodeSandbox team 😄

**Comment by mdarif** [comment]
Still happening outside incognito..

**Comment by jineeshjohn** [comment]
Try this [https://github.com/codesandbox/codesandbox-client/issues/6556#issuecomment-1078777593](url) fixed for me

**Comment by Lumi785** [comment]
I also used incognito, but error message persist. Also, my github default branch is 'main' already.

**Comment by Lumi785** [comment]
> Following this [comment](https://github.com/codesandbox/codesandbox-client/issues/6556#issuecomment-1078777593) fixed for me

works for me as well
