### ISSUE TITLE
Two identical SSE sandboxes with different results

### ISSUE THREAD

**Issue by karlhorky** [codesandbox/codesandbox-client#4806]
# 🐛 bug report

## Description of the problem

Two different Node.js SSE sandboxes have different results:

### Sandbox 1: https://codesandbox.io/s/shiki-starter-forked-tub3o?file=/src/index.js

Result: 502 Bad Gateway

<img width="846" alt="Screen Shot 2020-09-03 at 10 31 30" src="https://user-images.githubusercontent.com/1935696/92091571-3b79b080-edd1-11ea-86ef-00a62904526e.png">

### Sandbox 2: https://codesandbox.io/s/priceless-liskov-fzzzg?file=/src/index.js

Result: working server

![Screen Shot 2020-09-03 at 10 31 22](https://user-images.githubusercontent.com/1935696/92091625-50eeda80-edd1-11ea-8be5-b377e88b9c8e.png)

## How has this issue affected you? What are you trying to accomplish?

Trying to create a demo for Shiki: https://github.com/shikijs/shiki/pull/82#issuecomment-686182578

The errors are causing low confidence in the reproducibility of the sandbox.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | b0052520f |
| Browser          | Chrome 85.0.4183.83 |
| Operating System | macOS Catalina 10.15.6 |

**Comment by lbogdan** [comment]
Hey @karlhorky ,

That's pretty weird, they both work for me at the moment.

**Comment by karlhorky** [comment]
@lbogdan Yep, now it works for me too! Didn't change anything - they are both frozen.

I think what happens (what I've seen sometimes) is that the sandbox starts incorrectly and this state is cached remotely. There is no way to get out of this state (refreshing both the preview on the right and the browser itself doesn't help). Even using a different browser shows this broken state.

Once the sandbox goes to sleep and then has to wake up again (going through the procedure below), it works:

![Screen Shot 2020-09-04 at 09 46 16](https://user-images.githubusercontent.com/1935696/92213442-d89d1d80-ee93-11ea-9388-9d8ab0aad905.png)

My suggestion for a solution would be to offer the user a way to restart the sandbox manually, ideally very visibly right down in the bottom Terminal area.

**Comment by karlhorky** [comment]
Oh oops, just read your comment over here: https://github.com/shikijs/shiki/pull/82#issuecomment-686692670

It seems there is a way already! Would it be possible to surface this more visibly down in the bottom right Terminal area?

If so, I can open a new issue for that.

**Comment by lbogdan** [comment]
Hey @karlhorky ,

I'm gonna close this for now, please reopen if you still have issues.

> Would it be possible to surface this more visibly down in the bottom right Terminal area?
It surely would, please open a feature request!

**Comment by karlhorky** [comment]
Great, open here: #4920
