### ISSUE TITLE
Unable to load sandboxes (cors issue with sockets/container issue?)

### ISSUE THREAD

**Issue by aMadReason** [codesandbox/codesandbox-client#4810]
# 🐛 bug report

## Description of the problem
When trying to view a sandbox it hangs not displaying anything but the basic layout.

## How has this issue affected you? What are you trying to accomplish?
I am unable to use codesandbox at all.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/mod-map-rw5y1

### Your Environment
firefox (tried in chrome too) & windows 10

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | in the browser
| Browser          | Chrome Canary and Firefix Quantum
| Operating System | Win 10

**Comment by SaraVieira** [comment]
Hey!

Can you please provide a screenshot, I seem to be able to open the sandbox

**Comment by aMadReason** [comment]
This seems to have resolved itself, just my luck it would after i bothered you guys. Sorry about that!

**Comment by SaraVieira** [comment]
Oh nice!!!

Closing this and sorry for the issue
