### ISSUE TITLE
Sandbox CI not generating deployments

### ISSUE THREAD

**Issue by pablopunk** [codesandbox/codesandbox-client#4850]
# 🐛 bug report

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Description of the problem

In [this PR](https://github.com/pablopunk/nextjs-redirect/pull/8), codesandbox stopped deploying the app in the last commit. It worked for the previous commits, but check the last edited comment, it removes the link to the deployment:

![Captura de pantalla 2020-09-07 a las 18 44 24](https://user-images.githubusercontent.com/4324982/92407294-6bf77c80-f13a-11ea-9d40-8c7f1fb5c58e.png)

Also, on new PRs, the link doesn't appear either. Example: https://github.com/pablopunk/nextjs-redirect-locale/pull/1

Is there some limitation for free accounts? I couldn't find that in the docs.

**Comment by CompuIves** [comment]
Hey @pablopunk! There shouldn't be a limitation, it seems like the CI in this instance had trouble with forking an existing sandbox. We're looking into why that happened, does CI work for the other PRs/commits.

**Comment by pablopunk** [comment]
hi @CompuIves! I just unfroze the sandbox and made another commit, and it worked, maybe that was the issue? Anyway, thanks for checking! ❤️

**Comment by lbogdan** [comment]
Hey @pablopunk ,

It was an issue on our end which had nothing to do with the sandbox being frozen, so you can safely freeze it back. 🙂

**Comment by pablopunk** [comment]
@lbogdan ok, got it, thanks again!
