### ISSUE TITLE
Can't find module in path with acalanche package

### ISSUE THREAD

**Issue by harryEth** [codesandbox/codesandbox-client#4873]
# 🐛 bug report

## Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Description of the problem
When I load the avalanche npm package in my project it shows the error `Could not find module in path: 'avalanche' relative to '/src/App.js'`

Anyone knows what happened with this. this project works well on local and production env. Just not working on the codesndbox.

## How has this issue affected you? What are you trying to accomplish?
Try to publish a demo app with codesandbox.

### To Reproduce
Just go to the project, you’ll see the error immediately.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/github/MagicLabs/example-avalanche

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser            |   Google Chrome Version 85.0.4183.83 (Official Build) (64-bit)
| Operating System | macOS catalina Version 10.15.3 (19D76)

**Comment by CompuIves** [comment]
Hey! In the package.json of `avalanche` (https://unpkg.com/browse/avalanche@2.4.3/package.json) the `browser` field refers to `dist/lib/avalanche.js`, but upon checking I don't think that folder exists. Only the `dist` folder exists, but it doesn't contain a `lib` folder: https://unpkg.com/browse/avalanche@2.4.3/dist/.

I think that might be the issue, I'm surprised it works locally. maybe the bundler tries to use the `main` field if it can't find a `browser` field, I will check whether we should also start doing this behaviour.
