### ISSUE TITLE
Importing `@testing-library/dom` crashes tests

### ISSUE THREAD

**Issue by eps1lon** [codesandbox/codesandbox-client#4887]
# 🐛 bug report

## Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Description of the problem

Importing from `@testing-library/dom` crashes the test suite with `SyntaxError: Identifier 'test' has already been declared`

Original report: https://github.com/testing-library/dom-testing-library-template/issues/4

### To Reproduce
```js
import { queryByRole } from "@testing-library/dom";
```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 18e4e9fb9
| Browser          | Chrome 84
| Operating System | Ubuntu 18.04

**Comment by InventingWithMonster** [comment]
Another repro: https://codesandbox.io/s/dazzling-hugle-ivxej?file=/src/__tests__/index.test.js:99-589

**Comment by danawoodman** [comment]
Another test repo https://codesandbox.io/s/billowing-framework-2z1tp?file=/src/Editor.test.js

**Comment by eduardo6722** [comment]
another one https://codesandbox.io/s/old-thunder-my79z?file=/src/__tests__/index.tsx

**Comment by ivstudio** [comment]
I ran into the same issue. I used "it" instead of "test" to make it work for now.

**Comment by p-clem** [comment]
I was able to reproduce it too.

It seems that `@testing-library/react` version `11` is the issue.

Switching it to the previous version `10.4.9` works!
