### ISSUE TITLE
Inner browser blank

### ISSUE THREAD

**Issue by eliotolhoek** [codesandbox/codesandbox-client#4890]
# 🐛 bug report

## Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Description of the problem
Very often, the inner browser shows a blank screen instead of the expected content that is written or drawn with JavaScript.

## How has this issue affected you? What are you trying to accomplish?
Sandbox becomes almost unusable. I've seen this happen on several different systems, in almost all popular browsers.

### To Reproduce
I've managed to reproduce the issue right after creating a new sandbox with the Vanilla JS template. 
Sometimes the issue occurs immediately after creating the sandbox, sometimes it occurs after I put a blank line somewhere in the HTML or JS file in the project.
Another way to reproduce the issue is to from your working sandbox, use the 'Open in new window' button. This then opens a new tab. When this tab is closed, the sandbox inner browser shows up empty.

Sometimes, but definitely not always a refresh of the sandbox fixes the issue for a moment.

### Link to sandbox: (optional)
https://codesandbox.io/s/busy-wilbur-s6cvu?file=/index.html

<img width="1088" alt="csb_issue" src="https://user-images.githubusercontent.com/69851486/93055601-82866200-f66b-11ea-9f52-c1a9ce16f8b5.PNG">

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Web version
| Browser          | Chrome
| Operating System | Windows 10

**Comment by LeadDreamer** [comment]
FYI, I see this fairly frequently with a project a React project with about 750K bytes of code.  Always associated in the console with a 413 error from sentry.io "payload too large"

**Comment by LeadDreamer** [comment]
![NewPicture228](https://user-images.githubusercontent.com/7422762/93835578-8e0df600-fc34-11ea-8fe5-ce74aa41aab0.jpg)

**Comment by MuhammadKaifNazeer** [comment]
![Screenshot (138)](https://github.com/user-attachments/assets/56d04da1-96a7-4624-bd1d-4b9a3c1f9d8b)
I have the same issue, it's just showing a blank screen and also there's no error console, everything is fine, but it still showing a blank screen, I'm facing this problem consistently in past few projects.

**Comment by filipelima18** [comment]
Hi @MuhammadKaifNazeer. Most editor errors like this typically go away after clearing your browser's cache + cookies. Can you let me know if that fixes it for you?

**Comment by aruneshapk** [comment]
<img width="1913" height="912" alt="Image" src="https://github.com/user-attachments/assets/8213fe5b-67b7-4374-a666-22f598074b88" />

I'm having the same issue @filipelima18
