### ISSUE TITLE
CodeSandbox CI failed by  Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by WUSO01** [codesandbox/codesandbox-client#4891]
# 🐛 bug report

## Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Description of the problem
buildCommand will excute shell file,

part of code:
```sh
sassfiles=(`find packages -name "*.scss"`)
```
but each failed `Syntax error: "(" unexpected`, I guess it is caused by the Linux environment,  and where i can cat the err_debug.log.
For example, how i open this `/home/node/.npm/_logs/2020-09-15T09_51_57_066Z-debug.log` file

## How has this issue affected you? What are you trying to accomplish?

I try add `#!/usr/bin/env bash` at the top position,  but still not work

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by lbogdan** [comment]
I think that syntax is only supported by `bash`, not `sh`, can you try changing `"build:scss": "bash scripts/build-scss-ts.sh",` in `package.json`?
