### ISSUE TITLE
no template-icons in packages/common 

### ISSUE THREAD

**Issue by Rainmen-xia** [codesandbox/codesandbox-client#4895]
# 🐛 bug report

## Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Description of the problem

can not run start in local
## How has this issue affected you? What are you trying to accomplish?

want to run in local;
### To Reproduce

ERROR! 404 Not Found - GET https://registry.npmjs.com/template-icons - Not found

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | master branch latest
| Browser          | local build
| Operating System | mac os

**Comment by y912765390** [comment]
Brother, I also met this problem. Have you solved i

**Comment by y912765390** [comment]
good  brother ！I solved that you should install @codesandbox/template-icons
