### ISSUE TITLE
Codesandbox preview failed with antd

### ISSUE THREAD

**Issue by zombieJ** [codesandbox/codesandbox-client#4898]
# 🐛 bug report

## Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Description of the problem

ref https://github.com/ant-design/ant-design/issues/26728

### To Reproduce

https://codesandbox.io/s/z4tp0

<img width="490" alt="截屏2020-09-16 下午8 59 34" src="https://user-images.githubusercontent.com/5378891/93340566-8c70b680-f85f-11ea-96b5-c7aa79fe8a74.png">

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest |
| Browser          | Chrome |
| Operating System | Mac |

**Comment by SaraVieira** [comment]
Thank you!
