### ISSUE TITLE
Someone is using your site to host possibly malicious scripts

### ISSUE THREAD

**Issue by biltongza** [codesandbox/codesandbox-client#4899]
I got sent a link in Facebook Messenger that looked like a legit youtube embed:
![image](https://user-images.githubusercontent.com/2845704/93439904-65ea6400-f8cf-11ea-87aa-bf8b669dd747.png)

So I clicked on it. Instead of youtube I was met with this sketchy looking video player:
![image](https://user-images.githubusercontent.com/2845704/93440048-903c2180-f8cf-11ea-8501-cd42c89a8cbb.png)

I inspected source and found my way to the sandbox that hosts this: https://codesandbox.io/s/295u7?file=/index.html

It looks like some nicely obfuscated shell code (?):

![image](https://user-images.githubusercontent.com/2845704/93440488-c2e61a00-f8cf-11ea-9328-4f817eb02902.png)

I'm not really sure what it does and I'm not sure what the correct way of reporting things like this is, so I figured I would start here.

**Comment by garethx** [comment]
Thanks, we've removed this sandbox.
