### ISSUE TITLE
Deploy to Netlify Failing; Chrome enforcing CORS policies

### ISSUE THREAD

**Issue by LeadDreamer** [codesandbox/codesandbox-client#4917]
# 🐛 bug report

## Preflight Checklist
- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Description of the problem
Deploy to Netlify starting failing TODAY; console indicating failing CORS policy (Screen Grab to be attached)

## How has this issue affected you? What are you trying to accomplish?
Need to deploy from standard github-controlled source to shared Netlify site for FUNDING

### To Reproduce

Simply deploy from Master GitHub to Netlify

### Link to sandbox: [link]() (optional)
Proprietary.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest, web
| Browser          | Chrome 85.0.4183.102 (Official Build) (64-bit)
| Operating System | Win 7

![NewPicture229](https://user-images.githubusercontent.com/7422762/93835915-b518f780-fc35-11ea-9e36-c6d9c46878b0.jpg)

**Comment by LeadDreamer** [comment]
Exact same error on Firefox (latest)

**Comment by garethx** [comment]
I haven't been able to repro this with a public or private linked repo (on Mac at least). Are you able to provide a public version of the repo you're trying to deploy?

**Comment by LeadDreamer** [comment]
The particular repo, alas , no, BUT I could try another, smaller repo.  I could *also* try it over on a Mac.  Is there a particular repo you'd recommend as a solid test-bed you use repeatedly for such trials?

**Comment by LeadDreamer** [comment]
FYI, I tried it also with one of my branch repo's (as opposed to the Master direct from GitHub), which failed in precisely the same way with precisely the same issues. 

I should note I've been getting many many warnings (hundreds) about the CORS policy for months.  It looks like Chrome decided to actually enforce the policy on it's brand-spanking-new latest release

**Comment by LeadDreamer** [comment]
I'll also note it seems*unlikely* to to be repo-dependent - it never even *starts* the process.

**Comment by LeadDreamer** [comment]
whelp, I'm apparently wrong about the repo-dependence - I opened your React template, and that *did* deploy (with some errors)
![Uploading NewPicture230.jpg…]()

**Comment by LeadDreamer** [comment]
Same result on a Mac - process won't even start:
<img width="1440" alt="Screen Shot 2020-09-22 at 9 26 02 AM" src="https://user-images.githubusercontent.com/7422762/93910453-f51fbf00-fcb5-11ea-98f1-36af7b976694.png">

**Comment by LeadDreamer** [comment]
Stripping down app to create a share-able repo - some signs pointing to a CSS *file* issue (even when none of them are actually imported into the code)

**Comment by LeadDreamer** [comment]
Answer: size.  After stripping various parts and getting various failures/successes, I ended up deleting one small file - failed to start deploy before; deployed after.  Downloaded ZIP of Failed deploy: 1027K.  Downloaded ZIP of Successful Deploy: 1022K.

I ran into this because I had downloaded foundation-icons, which included the font files and the svgs, and added it in.  Actually ended up using only the css, and getting the font files & svgs from CDN.  font-files and svgs took project from 782K to 1,523K.

That's now another issue, which I will take up in another bug report: I can't actually upload files, nor upload to Storage. see next issue.

I consider this closed, with a request for the caveat to users about total size of files in a project.

**Comment by garethx** [comment]
Oh, thanks for taking the time to look into this. I'll discuss the size problem with the team to see what we can do.

**Comment by LeadDreamer** [comment]
BTW, the *other* issue - that, for some reason, neither file upload NOR Static Storage are working for me, which would be the perfect place to put the bulky font files...

**Comment by garethx** [comment]
Can you confirm the version you're on? You'll see a version id in the bottom-left of the editor e.g. b5aacc6b2. Only we had a version that caused that, but it was reverted, so should no longer be a problem.

**Comment by LeadDreamer** [comment]
In the chrome "app", it show version 00ab46656.  When I click "Storage Management you can see the screen-cap:

![NewPicture232](https://user-images.githubusercontent.com/7422762/94605846-819a2680-024e-11eb-9d2b-4cbc42d8fd99.jpg)

 and when I click "Upload Files" you can see (well, you can't; nothing happens, but here's the screen cap anyway)

![NewPicture233](https://user-images.githubusercontent.com/7422762/94605960-a8585d00-024e-11eb-8a37-55f4da7db74f.jpg)

**Comment by LeadDreamer** [comment]
Not dreadfully surprising, the web-page does exactly the same thing - I *assume* you were talking about the upload/storage issue?

**Comment by garethx** [comment]
hmm, that is the latest. Are you able to upload files by dragging them from your local computer onto the file system section in the editor?

**Comment by LeadDreamer** [comment]
Yes, I can drag to upload into the file system (just did it in the app), but NOT into the storage system - and it's the latter I was hoping to use for font files, etc.

**Comment by garethx** [comment]
Anything you upload in the app gets listed in the storage system, there's not a way to upload to it directly.

**Comment by LeadDreamer** [comment]
then this is...?

![NewPicture236](https://user-images.githubusercontent.com/7422762/94712439-5707a680-02fe-11eb-874c-345b4701c3dd.jpg)

![NewPicture237](https://user-images.githubusercontent.com/7422762/94712467-5ff87800-02fe-11eb-90cb-174a9dfe2e62.jpg)

**Comment by garethx** [comment]
Have you uploaded static binary assets to your app? I can't see any at least in the partial file system in the screenshot.

**Comment by LeadDreamer** [comment]
OK, then I'm confused (not exactly a surprise) - where, precisely , in that tree would I upload such? Root? Public? src?  external resource?

I note under external resources, there's a google font section - who is that incorporated... into the index.html file?

Is there more detailed documentation somewhere other than the "documentation" link - which, honestly, calling skeletal would be a tad much...

**Comment by LeadDreamer** [comment]
(I'm guessing the answer is "look in the npm/node documentation - this is just a web-hosted node/npm environment", which is actually a pretty good answer)

**Comment by LeadDreamer** [comment]
I'll answer some of my own questions: I see the Google Font included as a <link></link> in the header (I've been using @import in my css). My CSS files show up as <style...>...</style>.

**Comment by LeadDreamer** [comment]
continuing over here: #4930
