### ISSUE TITLE
Got error while switch Vue 2.6.12 to Vue 3.0.0

### ISSUE THREAD

**Issue by steveyang331** [codesandbox/codesandbox-client#4918]
# 🐛 bug report

## Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Description of the problem
Got error while switch Vue 2.6.12 to Vue 3.0.0
## How has this issue affected you? What are you trying to accomplish?
1. Create vue template 
2. Go to package.json file . 
![image](https://user-images.githubusercontent.com/16850883/93844939-86e8f580-fcd1-11ea-9723-ab21d21cde14.png)

3. Upgrade vue to 3.0 
![image](https://user-images.githubusercontent.com/16850883/93844963-ab44d200-fcd1-11ea-9e37-a5f315c36f1f.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |Latest
| Browser          |Chrome 
| Operating System | Win 10

**Comment by steveyang331** [comment]
I think it allows to create Vue 3 template will be fixed.

**Comment by SaraVieira** [comment]
@CompuIves is working on this now in here #4916 :)
