### ISSUE TITLE
Auto complete html/jsx tags doesn't work, its huge pain to close all those tags manually.

### ISSUE THREAD

**Issue by sahilrajput03** [codesandbox/codesandbox-client#4921]
# 🐛 bug report

## Preflight Checklist

- [x] I [have](url) read the
      [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

It seems like we do have autoclose of html tags in vscode settings page, but it doens't work for some reason idk why, I am using codesandbox for over a few months and I would love if it could feature this thing please, autclose of tags in jsx doesnt' work at all.

## How has this issue affected you? What are you trying to accomplish?

I just need to close all the html/jsx tags in my react projects and that's a huge chore that I need to do every minute, and it would be so amazing if you guys could fix this feature, or add this functionality by some how. For e.g., https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag this extension in vscode works perfectly fine. Please see to this problem/bug/feature.

Thanks 
~ Sahil

**Comment by NairasLT** [comment]
yeah it's really annoying.

**Comment by sahilrajput03** [comment]
Is there a way we this can be achieved with some trick/hack or by feature development, if yes, how should I progress?
Thanks!

**Comment by mattrossman** [comment]
Heads up to anyone else who finds this in the future: you can actually enable this in Codesandbox since it runs VSCode.

To do so, click the menu in the top left and go to File > Preferences > Settings or press `Ctrl + ,`

Search for `html.autoClosingTags` and enable it. More info on the VSCode setting [here](https://code.visualstudio.com/docs/languages/html#_close-tags).

**Comment by kaimul1984** [comment]
"emmet.includeLanguages": {"javascript": "javascriptreact"},
Please add this line into settings.json.  save and reload the window. hope Problem solve.
