### ISSUE TITLE
Loading npm package results in unterminated string constant error during load

### ISSUE THREAD

**Issue by gmurray81** [codesandbox/codesandbox-client#4929]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
When I try to load this sandbox: https://codesandbox.io/s/hardcore-faraday-4ofny?file=/index.html
I get an unterminated string constant error. I do not receive this error if I download the zip and npm run start locally.

## How has this issue affected you? What are you trying to accomplish?
We have options to execute our github product samples in codesandbox. We've switched to pointing our module endpoint to a different bundle than usual and are now receiving this error. This might impact our ability to direct folks at codesandbox to play with our samples.

### To Reproduce
load this sandbox: https://codesandbox.io/s/hardcore-faraday-4ofny?file=/index.html
Note the error:
```text
/node_modules/igniteui-webcomponents-core/fesm2015/igniteui-webcomponents-core.js: Unterminated string constant (25191:6)

  25189 |   No: "[²³¹¼-¾৴-৹୲-୷௰-௲౸-౾൰-൵༪-༳፩-፼៰-៹᧚⁰⁴-⁹₀-₉⅐-⅟↉①-⒛⓪-⓿❶-➓⳽㆒-㆕㈠-㈩㉑-㉟㊀-㊉㊱-㊿꠰-꠵]",
  25190 |   Zs: "[   ᠎ -   　]",
> 25191 |   Zl: "[
        |      ^
  25192 | ]",
  25193 |   Zp: "[
  25194 | ]",
```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | https://codesandbox.io/s/hardcore-faraday-4ofny?file=/index.html
| Browser          | Edge (chromium)
| Operating System | Windows 10

**Comment by gmurray81** [comment]
To provide a bit of context here, I'm aware that codesandbox would probably really rather use one of the other entry points in our package.json. This issue arose because we are experimenting with pointing our module entry point at ES2015 level logic, as most people seem to be running stuff through babel anyhow, and since this library contains custom elements, we can forgo a bunch of polyfilling if we keep everything es2015 unless someone explicitly transpiles us down or picks one of the es2015 entry points.

I assume codesandbox may load quite a bit slower if we were to get past this bug, based on the perf I'm seeing compiling our react stuff if I change the entry point.

Is there any package entry point that codesandbox would pick up for its templates that I could use to call out an ES5 entry point for it to use? browser, I don't think can work, because some of the tooling we are trying to prevent loading the ES5 logic would look there.

**Comment by CompuIves** [comment]
Hey! This is a great report, I just created a commit to fix this. Should go live either today or tomorrow!

**Comment by gmurray81** [comment]
Awesome, thanks!

**Comment by gmurray81** [comment]
BTW, I have been further experimenting with where to point our module entry point and hit a rather interesting problem documented here #4942
