### ISSUE TITLE
I don't get why my start script isn't getting executed.

### ISSUE THREAD

**Issue by sahilrajput03** [codesandbox/codesandbox-client#4936]
![image](https://user-images.githubusercontent.com/31458531/94233406-79c44480-ff25-11ea-994a-f3de4baf2f59.png)

https://codesandbox.io/s/json-servermultiple-files-decoded-amazing-dv0pm?file=/package.json:289-321

What could be the problem??

**Comment by SaraVieira** [comment]
Hey!

Can you explain what you mean? Your server starts and runs the start script

Also please follow the template we have for issues, that would have saved this question

**Comment by lbogdan** [comment]
Hey @sahilrajput03 ,

After changing the `start` field in `package.json`, you need to restart the sandbox in order for that to be applied. You can do that by going to the "Server Control Panel" in the sidebar and clicking on "Restart Sandbox":

![image](https://user-images.githubusercontent.com/2083930/94248143-b93f6080-ff26-11ea-9dff-4747f32a454c.png)

Will close this for now, as it's working as expected, but feel free to reopen if you still have issues.

**Comment by sahilrajput03** [comment]
> Hey @sahilrajput03 ,
> 
> After changing the `start` field in `package.json`, you need to restart the sandbox in order for that to be applied. You can do that by going to the "Server Control Panel" in the sidebar and clicking on "Restart Sandbox":
> 
> ![image](https://user-images.githubusercontent.com/2083930/94248143-b93f6080-ff26-11ea-9dff-4747f32a454c.png)
> 
> Will close this for now, as it's working as expected, but feel free to reopen if you still have issues.

Thanks mann, its really great, I already knew that for some things I need to refresh the page to get the sandbox get the curretly changed settings like chagning keybindings, and browser window position changing.

You saved me. Amazing! Thanks a lott!! :+1:  :100:

**Comment by sahilrajput03** [comment]
> Hey!
> 
> Can you explain what you mean? Your server starts and runs the start script
> 
> Also please follow the template we have for issues, that would have saved this question

Okay, sorry for that, but I though its really some bug, so put it directly. Also, almost 90% of software is working amazing. 
Thanks though. :100:  Will definitely follow the template from next time. Thanks!!
