### ISSUE TITLE
csb.app and custom domain option.

### ISSUE THREAD

**Issue by johnman** [codesandbox/codesandbox-client#4937]
When csb.app was blocked the issue was raised and I suggested supporting custom domains so people wouldn't be impacted because of the behaviour of someone else. csb.app is currently still running but I am now getting emails rejected when I try to send a link to a sandbox sample:

"550 A URL in this email (csb . app) is listed on https://spamrl.com/. Please resolve and retry"

This is influencing whether or not csb should be used because this problem seems like it will always occur (I understand it is not fully in your control but a custom domain would get around this for paying subscribers).

Thanks,

John

"Liking your suggestion @johnman. For now suspension has been lifted. Our First priority is to: (1) either change the way our current domain registrar (brute) forces its policies, or (2) transfer the domain to a more cooperative registrar. That should prevent this from happening altogether. We've made progress, but no commitment to date on (1)."

_Originally posted by @oskarabc in https://github.com/codesandbox/codesandbox-client/issues/3751#issuecomment-614292579_

**Comment by garethx** [comment]
Thanks for the suggestion. To unblock you right now, you can replace csb.app with codesandbox.io in the URL and I've requested delisting on spamrl, which should be active in a few hours. But I take your point above and think it's something we should consider longer-term.
