### ISSUE TITLE
Add custom transpiler support

### ISSUE THREAD

**Issue by ClassicOldSong** [codesandbox/codesandbox-client#4941]
# 🌈 Feature

Add custom transpiler support.

e.g. Adding transpilers in packags.json with proper configuration in sandbox.config.json and it should work.

As mentioned [here](https://twitter.com/compuives/status/1309233818755387392), it should be fairly easy to implement using the same method dealing with Vue 3.

**Comment by ClassicOldSong** [comment]
Currently I can only have my own template engine running in container sandboxes, which is quite able to be running completely in-browser, and is not quite convenient to work offline. Having the ability to add custom transpilers to the project can greatly extend the ability of showcasing new technologies with codesandbox.
Here is my container sandbox template: https://codesandbox.io/s/github/TheNeuronProject/ef-starter-template?file=/src/hello.eft

**Comment by ClassicOldSong** [comment]
Also adding custom code highlighting could be another great thing.

Like https://github.com/codesandbox/codesandbox-client/pull/4628 , it's quite difficult to add a custom highlighting and it seems the process is no more than copying an existing vscode extension into codesandbos's preset.

Doing so by creating a PR could cause the waste of public bandwidth resources for every new language wants to add it to codesandbox but not very much people will actually use it.

Loading extensions on demand should be better.

**Comment by siddharthkp** [comment]
That sounds pretty amazing!

**Comment by siddharthkp** [comment]
Hi @ClassicOldSong, Thanks again for your feedback

I have added your feature request to our internal backlog which we use to prioritize what to build next. Can't make any promises about the timing, but it's on the list!

For others landing on this issue, feel free to add more context or simply leave a thumbs up 👍 on this comment if you find this feature useful.
