### ISSUE TITLE
Large performance disparity between a large single ES5 module and many smaller ES5 modules

### ISSUE THREAD

**Issue by gmurray81** [codesandbox/codesandbox-client#4942]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

We've been experimenting with how to structure our module entry point for our npm packages for good performance with being directly ingested into various browser based and node based tools. For many of the tools we can achieve best performance by providing a flattened/hoisted (rollup style) single large module, but, at the same time this seems to provide much worse performance in codesandbox compared to many smaller modules (but potentially a smaller total amount of code, due to preemptive elimination of unimported modules).

## How has this issue affected you? What are you trying to accomplish?

There is a large performance penalty incurred in codesandbox if we point our module entry point at a flat ES5 module compared to pointing our module entry point at a barrel file pointing at many smaller modules. Codesandbox claims to be spending this time transpiling, however the code is already ES5 level code, so I'm guessing this is just referring to removing the import/export statements remaining in the flattened module, rather than any downleveling of code.

Ideally we'd like this scenario to perform just as well as the non flattened module scenario. Based on information in other issues, I suspect that codesandbox is not caching the resulting transpiled file for this scenario. Perhaps it should be? Failing that, perhaps if we had a package.json entry point other than module, that codesandbox could notice, but not other tooling, then we could direct codesanbox at the entry point that is most optimal for codesandbox to use?

### To Reproduce

https://codesandbox.io/s/vigilant-stonebraker-5udl4?file=/src/index.ts

This codesandbox uses the 1.1.3 version of our npm packages that pointed "module" at a barrel entry point file that re-exported tons and tons of other modules. This loads very very quickly, in several seconds. Since this is quite a bit more complicated of a task than dealing with a single large module, I have to assume that this is due to the transpiled results being _cached_ somewhere.

https://codesandbox.io/s/wandering-morning-s352r?file=/index.html

This codesandbox uses the 1.1.5 version of our npm packages that point "module" at a single flattened module with hoisted imports. This waits for over 30 seconds in the "transpiling modules" step. 

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | https://codesandbox.io/s/wandering-morning-s352r?file=/index.html
| Browser          | Edge (chromium)
| Operating System | Windows 10

**Comment by CompuIves** [comment]
Hey @gmurray81! I noticed this as well while fixing #4929, it turns out that we wrongly detected JSX in the file, which made the bundler send the file to be parsed by Babel (v6) instead of going through the fast path which is incredibly slow. I fixed it in the same PR, and it should now work fast and as expected.

Also, on another note, you can possibly up the performance another bit by adding `"@babel/core": "^7.0.0"` to your dev dependencies, that will make our bundler use Babel 7 instead of 6 for transpilation.

**Comment by gmurray81** [comment]
Awesome, thanks for the really quick fix!
