### ISSUE TITLE
Create sandbox with POST but without getParameters()

### ISSUE THREAD

**Issue by oyejorge** [codesandbox/codesandbox-client#4948]
# 🌈 Feature

It would be nice if it were possible to create a sandbox by POSTing data encoded with JSON.stringify() instead of getParameters()

Currently, new sandboxes can be created by POSTing JSON encoded with getParameters()

For example, [this sandbox from the API docs](https://codesandbox.io/s/define-api-post-request-qzlp7nw34q?from-embed) 

When modifying this example slightly to use JSON.stringify() instead of getParameters(), the result is an "Internal server error"

[Example of the internal server error](https://codesandbox.io/s/define-api-post-request-forked-6iz77?file=/index.js)

**Comment by siddharthkp** [comment]
Hi!

From what I understand, we need to perform one additional step before we stringify and send it over to the API. I'm not sure if we can defer that task to the API without losing information.

Reference: https://github.com/codesandbox/codesandbox-importers/blob/master/packages/import-utils/src/api/define.ts

Tagging @CompuIves to confirm
