### ISSUE TITLE
Consider publishing the bundler as a separate package

### ISSUE THREAD

**Issue by viankakrisna** [codesandbox/codesandbox-client#496]
Hi! I'm currently working on a CMS that store their asset source in the database, the idea is to make the assets editable on the dashboard UI and save the generated file to the server, that way the server does not need to have any bundler/transpiler running/installed.

Looking through the source of this repository, I think it would be beneficial for my use case to have https://github.com/CompuIves/codesandbox-client/tree/master/packages/app/src/sandbox/eval published as a separate npm package. Right now I'm planning to just copy the source and bundle it myself, but I think this would be an opportunity for a great npm package.

@CompuIves would this be something that you consider?

**Comment by CompuIves** [comment]
Hey @viankakrisna, I actually was working on this for some time. But stopped when I got other things to work on.

It would be perfect if we create a separate package for the sandbox, it would also fit perfectly with our workspaces. 

I started working on it in this branch https://github.com/CompuIves/codesandbox-client/tree/playground, I had a post about it here https://medium.com/@compuives/announcing-playground-toolkit-9808b549f11e.

Would you be interested in helping with finishing this project? I think it would help a lot of people.

**Comment by viankakrisna** [comment]
@CompuIves nice! I'm a bit tight for time recently, but I'll see if I can do it :)

**Comment by lbogdan** [comment]
@viankakrisna Is this https://www.npmjs.com/package/smooshpack what you were thinking of?

**Comment by hobbes7878** [comment]
> I think it would help a lot of people.

Just want to raise my hand here. For my team, having a browser-based editor that can bundle scripts would really change the game.

In case it's at all useful to point out a concrete use case, here's a simple one: an open source [chart builder](http://dallasmorningnews.github.io/chartwerk-editor/) we made. Chart templates are developed by designers entirely in the browser and then tweaked as users build individual charts. But being able to develop those templates in the browser the same way we would build them locally would unlock *a lot* of potential for that tool.

Again, just want to encourage development of the standalone bundler. Love to help out where I can, even if I'm not sure exactly where to start. But again, really love where this idea is headed. Will be eagerly awaiting what comes of sandpack/smooshpack. Thanks!

**Comment by CompuIves** [comment]
That is a perfect case for Sandpack @hobbes7878. Really nice to hear this, I will dedicate the coming week to release everything so you can start using it!

**Comment by hobbes7878** [comment]
@CompuIves Just to say we're still eagerly checking in every now and again on sandpack. Can't wait to kick the tires once it's ready!

**Comment by hobbes7878** [comment]
@Compulsives Anything I can do to help this project along? I think it's something really unique and I'm really eager to put it to use on our team. We'd be happy to pitch in to get it across the line, but would need a little direction on where best to help. Thanks, again!

**Comment by hobbes7878** [comment]
Just cross-referencing some prospective work the folks at parcel.js are doing to make their bundler work in the browser: https://github.com/parcel-bundler/parcel/issues/1253

Whoever gets their first, I really think this is a tool that's going to change the game for a lot of us. 

@CompuIves any update on whether you're still interested in separating the sandpack bundler for general use?

**Comment by CompuIves** [comment]
Sandpack already released! @hobbes7878 

I just never wrote a Medium post/tweet about it. You can find it here: https://github.com/CompuIves/codesandbox-client/tree/master/packages/sandpack

**Comment by hobbes7878** [comment]
Great! Didn't realize it was ready.

I'll give it a run through. Thanks very much!
