### ISSUE TITLE
<script setup> block does not support exposing Vue components

### ISSUE THREAD

**Issue by tony19** [codesandbox/codesandbox-client#4960]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Vue's `<script setup>` block allows [exposing components](https://github.com/vuejs/rfcs/blob/sfc-improvements/active-rfcs/0000-sfc-script-setup.md#exposing-components) for local component registration, but no registration seems to occur in Codesandbox.

## How has this issue affected you? What are you trying to accomplish?

It prevents me from using the `<script setup>` block to register components.

### To Reproduce

```html
<template>
  <MyComponent />
</template>

<script setup>
<!-- XXX: no registration, no browser console errors -->
export { default as MyComponent } from '@/components/MyComponent.vue'

<!-- XXX: no registration, but browser console error: unknown component -->
import MyComponent from '@/components/MyComponent.vue'
export { MyComponent }
</script>
```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |a5f244dc7|
| Browser          | Chrome 84 |
| Operating System | macOS Catalina |

**Comment by SaraVieira** [comment]
Hey

You seem to be using a sandbox that is using vue version 2 

Can you please try with this one https://codesandbox.io/s/vue-3

This one already uses the new vue 3

**Comment by tony19** [comment]
Oops. Sorry, you're right!

[working demo](https://codesandbox.io/s/charming-feistel-b2s9d)

**Comment by SaraVieira** [comment]
Awesome! Thank you for the quick reply :D
