### ISSUE TITLE
Console error not shown in console

### ISSUE THREAD

**Issue by siddharthkp** [codesandbox/codesandbox-client#4963]
# 🐛 bug report

## Description of the problem

Found this while debugging a different issue. There are errors visible on the developer tools console that are not visible on the codesandbox console.

![image](https://user-images.githubusercontent.com/1863771/94818327-48a0b400-03fe-11eb-9e47-2f52dc41d01a.png)

## How has this issue affected you? What are you trying to accomplish?

Wasn't able to debug with the codesandbox console. Spent a bunch of time messing around with code until I realised there was a descriptive error message, but it wasn't shown in the codesandbox console.

### Link to sandbox: [Repro](https://codesandbox.io/s/missing-error-firebase-5rlbf)

Not sure if this is related to the specific error itself, need to use repro to dig deeper.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | bcd308d83
| Browser          | Chrome 85
| Operating System | MacOS 10.14.6

**Comment by jtheisen** [comment]
I see this also. There is no display of an exception if the error was caused directly in the html and thus outside the bundle.

I used codesandbox just for hosting a bit of direct html for some fun with iframes.
