### ISSUE TITLE
Showing version numbers for transitive deps 

### ISSUE THREAD

**Issue by ZeeCoder** [codesandbox/codesandbox-client#497]
I experiment a lot on the platform, and I often times notice weird behaviours where I can't be sure whether it's a caching issue on your side, or it's just that dependencies were not resolved the way I thought they would be.

I basically find myself a lot of times wondering whether I got the right dep versions or not.

Take this for example:
https://codesandbox.io/s/l4xny9m59q

here, `@zeecoder/react-container-query` has `@zeecoder/container-query@^2.4.0` as a dependency, so I shouldn't have to explicitly install it as a direct dependency, and yet if I remove it, the numbers in the red rectangle are no longer calculated.
(Which is actually the expected behaviour, if the container-query version is lower than 2.4)

So now I'm left wondering:
- Is it that react-container-query got the wrong container-query dependency? (<2.4.0) Which seems to be the case since when I add 2.4.0 as a direct dep, it starts working.
- Or is it that there's some caching issue, and although the right version **should** be served, it is not.

In situations like these, it would be very helpful to at least know the exact version that react-container-query uses.

**Comment by CompuIves** [comment]
Hey @ZeeCoder,

We cache by dependency combinations, the example you've shown is an interesting one. `@zeecoder/cq-demo-utils` requires 2.3.0 and `@zeecoder/react-container-query` requires 2.4.0. I'll do some more investigating on why the sizes are not shown now.

**Comment by ZeeCoder** [comment]
Sizes?
You mean versions, right?

So that must've been it, but that's still weird because react-container-query should then use it's 2.4.0 version, while cq-demo-utils is not even using that dependency in this example.

But yeah, so here I could've probably resolved the issue sooner by adding the caret version range to cq-demo-utils - although it's probably a good thing that we seem to have noticed a weird dep. resolution issue -, if I could check that I was actually getting two different versions of container-query without realising it. 

I won't fix it for now, to have something to check when potential fixes land. 👍

Thanks again for the great tool btw 🎉
I think I'll soon hit the project limit and become a backer. 😀

**Comment by CompuIves** [comment]
That's awesome @ZeeCoder! I found the issue, there was a bug in our dependency conflict resolver for scoped packages. I'll deploy a fix now.

**Comment by CompuIves** [comment]
I agree with showing all dependency versions, I'll keep this issue open as a reference to that.

**Comment by CompuIves** [comment]
Reopening for reference!

**Comment by ZeeCoder** [comment]
Yep, demo works now, awesome work as usual  🙌

I'll leave the issue open then until that feature lands, can't wait 👍

**Comment by SaraVieira** [comment]
It has been deployed probably about two years ago 😂
