### ISSUE TITLE
Error when creating the repo. Error::Unable to create the repo. Please refresh and try again or report issue. Repository creation failed.

### ISSUE THREAD

**Issue by tiavina-mika** [codesandbox/codesandbox-client#4970]
![image](https://user-images.githubusercontent.com/42656064/94926746-eca36180-04c9-11eb-8d06-1125663cf9ac.png)

I have this error when creating new repo to my codesandbox: https://codesandbox.io/s/heuristic-maxwell-3gkfo?file=/src/App.tsx

I'm using React with TypeScript

**Comment by garethx** [comment]
Thanks for reporting - GitHub have made a change and we're working on an update to work with that change. This should be fixed shortly.
