### ISSUE TITLE
Export to new GitHub repository does not work for server sandbox

### ISSUE THREAD

**Issue by maksimr** [codesandbox/codesandbox-client#4971]
STR:

- Create a server sandbox (node template)
- Try to export it as a new GitHub repository

AR: Repository is created but only with README file and with only one **branch main**
ER: Create a repository with all code and branch **master** by default

![image](https://user-images.githubusercontent.com/616193/94960976-766c2280-04fc-11eb-8300-dd40945c274a.png)

[Example codesandbox](https://codesandbox.io/s/aidbox-example-c729x?file=/package.json)

**Comment by CompuIves** [comment]
Hey! Just found the issue, a fix should be live in about 4 minutes!

**Comment by sannek** [comment]
This should be fixed now, so closing the issue. Feel free to reopen if you run into any further issues.
