### ISSUE TITLE
built-in console wrongly prints null for vue component ref

### ISSUE THREAD

**Issue by yairEO** [codesandbox/codesandbox-client#4980]
# 🐛 bug report

## Preflight Checklist

- [X] I have read the
      [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md)
      for this project.
- [X] I agree to follow the
      [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I have created a very small `vuejs` demo which illustrate the issue. I never in those wasted hours have thought to double-check the console using the browser's one.

## How has this issue affected you? What are you trying to accomplish?

I have been wasting my whole day trusting the built-in console of codesandbox.
apparently it's untrustworthy as it prints `null` where an Object should be printed.

All I wanted was to print the `ref` for a vue child-component in another parent vue-component.

### To Reproduce

Open the built-in console vs browser console and see:

![image](https://user-images.githubusercontent.com/845031/95265354-52c51700-0831-11eb-8ef2-fcb16ca2231e.png)

 
https://codesandbox.io/s/vue-example-to-print-ref-1spu6?file=/src/App.vue

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 
| Browser          | Chrome Version 81.0.4044.122 (Official Build) (64-bit)
| Operating System | MacOS 10.15.7

**Comment by sannek** [comment]
Thanks for you bug report (especially the reproducable example, that helps a lot!). It looks like this might be a bug in the dependency we use for our console, so I've opened an issue with them, and hopefully we can get it fixed as soon as possible.

I'm sorry for the annoyance and confusion!

**Comment by yairEO** [comment]
Can you paste here a reference to the issue you've opened for the dependency?

**Comment by sannek** [comment]
Oh sorry - I thought that was visible in the issue feed here (it is for me) but here's [the issue](https://github.com/samdenty/console-feed/issues/55)
