### ISSUE TITLE
sandboxes/define API does not infer name/description

### ISSUE THREAD

**Issue by eps1lon** [codesandbox/codesandbox-client#4983]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Creating a CodeSandbox with https://codesandbox.io/api/v1/sandboxes/define does not infer name and description from the `name` and `description` fields in `package.json`.
This should works when importing (https://codesandbox.io/docs/api/#setting-inference).
I'm fairly certain this used to work (though we used the `title` field in `package.json`).
I don't know when/if this regressed.

## How has this issue affected you? What are you trying to accomplish?

We're creating a CodeSandbox from a demo displayed in our component documentation. If these are used for repros we get non-descriptive page titles and sandbox names.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 687f9a330
| Browser          | Chrome 85
| Operating System | Ubuntu 18.04

**Comment by sannek** [comment]
As far as I can tell this isn't a regression, but just a feature the `/define` endpoint doesn't have (it follows a different flow than the importing flow).

I've marked it as a feature request for now, because it does make sense to have the same behaviour in both cases. It will go on our internal backlog and we can figure out how/when/if we can implement this. I can't make any promises on the timeline for this though.

For others landing on this issue, feel free to add more context or simply leave a thumbs up 👍 on this comment if you find this feature useful.

**Comment by eps1lon** [comment]
I'm now certain this used to work: https://codesandbox.io/s/material-demo-smkqh

This is definitely a demo created from our documentation which sets name and description via `title` and `description` field from `package-json`. The codesandbox has the appropriate name and description.

What is odd is that this is still working for our `master` branch: https://5f7dc5d61cfa4d0008032eb3--material-ui.netlify.app/components/rating/#simple-ratings (concrete netlify deploy for permalink) (click on the edit icon below the demo). However, for our `next` branch it's not working: https://5f7d6fecf260b900074350ff--material-ui.netlify.app/components/rating/#basic-rating.

<details>
<summary>Payload from `master`</summary>

```json
{
  "title": "Material demo",
  "description": "https://github.com/mui-org/material-ui/blob/master/docs/src/pages/components/rating/SimpleRating.js",
  "files": {
    "index.html": "\n<body>\n  <!-- Fonts to support Material Design -->\n  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap\" />\n  <!-- Icons to support Material Design -->\n  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" />\n  <div id=\"root\"></div>\n</body>\n      ",
    "demo.js": "import React from 'react';\nimport Rating from '@material-ui/lab/Rating';\nimport Typography from '@material-ui/core/Typography';\nimport Box from '@material-ui/core/Box';\n\nexport default function SimpleRating() {\n  const [value, setValue] = React.useState(2);\n\n  return (\n    <div>\n      <Box component=\"fieldset\" mb={3} borderColor=\"transparent\">\n        <Typography component=\"legend\">Controlled</Typography>\n        <Rating\n          name=\"simple-controlled\"\n          value={value}\n          onChange={(event, newValue) => {\n            setValue(newValue);\n          }}\n        />\n      </Box>\n      <Box component=\"fieldset\" mb={3} borderColor=\"transparent\">\n        <Typography component=\"legend\">Read only</Typography>\n        <Rating name=\"read-only\" value={value} readOnly />\n      </Box>\n      <Box component=\"fieldset\" mb={3} borderColor=\"transparent\">\n        <Typography component=\"legend\">Disabled</Typography>\n        <Rating name=\"disabled\" value={value} disabled />\n      </Box>\n      <Box component=\"fieldset\" mb={3} borderColor=\"transparent\">\n        <Typography component=\"legend\">Pristine</Typography>\n        <Rating name=\"pristine\" value={null} />\n      </Box>\n    </div>\n  );\n}\n",
    "index.js": "\nimport React from 'react';\nimport ReactDOM from 'react-dom';\nimport Demo from './demo';\n\nReactDOM.render(<Demo />, document.querySelector('#root'));\n    "
  },
  "dependencies": {
    "react": "latest",
    "@material-ui/lab": "latest",
    "@material-ui/core": "latest",
    "react-dom": "latest"
  }
}
```
</details>

<details>
<summary>Payload from `next`</summary>

```json
{
  "title": "Material demo",
  "description": "https://github.com/mui-org/material-ui/blob/next/docs/src/pages/components/rating/BasicRating.js",
  "files": {
    "index.html": "\n<body>\n  <!-- Fonts to support Material Design -->\n  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap\" />\n  <!-- Icons to support Material Design -->\n  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" />\n  <div id=\"root\"></div>\n</body>\n      ",
    "demo.js": "import * as React from 'react';\nimport { makeStyles } from '@material-ui/core/styles';\nimport Rating from '@material-ui/core/Rating';\nimport Typography from '@material-ui/core/Typography';\n\nconst useStyles = makeStyles((theme) => ({\n  root: {\n    '& > legend': {\n      marginTop: theme.spacing(2),\n    },\n  },\n}));\n\nexport default function BasicRating() {\n  const classes = useStyles();\n  const [value, setValue] = React.useState(2);\n\n  return (\n    <div className={classes.root}>\n      <Typography component=\"legend\">Controlled</Typography>\n      <Rating\n        name=\"simple-controlled\"\n        value={value}\n        onChange={(event, newValue) => {\n          setValue(newValue);\n        }}\n      />\n      <Typography component=\"legend\">Read only</Typography>\n      <Rating name=\"read-only\" value={value} readOnly />\n      <Typography component=\"legend\">Disabled</Typography>\n      <Rating name=\"disabled\" value={value} disabled />\n      <Typography component=\"legend\">No rating given</Typography>\n      <Rating name=\"no-value\" value={null} />\n    </div>\n  );\n}\n",
    "index.js": "\nimport * as React from 'react';\nimport ReactDOM from 'react-dom';\nimport Demo from './demo';\n\nReactDOM.render(<Demo />, document.querySelector('#root'));\n    "
  },
  "dependencies": {
    "react": "latest",
    "@material-ui/core": "next",
    "react-dom": "latest",
    "@emotion/core": "latest",
    "@emotion/styled": "latest"
  }
}
```
</details>

So this is either a bug or some behavior from codesandbox that I'm unaware of.

**Comment by CompuIves** [comment]
Hey! There was indeed an issue with the packager, I've opened a PR to fix it.

**Comment by CompuIves** [comment]
Fix is being deployed now! I'll keep this open for testing, we have very aggressive caching on the define call (for every call of the same files we re-use the sandbox) so you won't see any changes until you change a file in the payload.

**Comment by eps1lon** [comment]
It is working for us now.
