### ISSUE TITLE
setupFilesAfterEnv seems to be ignored when using Angular

### ISSUE THREAD

**Issue by yjaaidi** [codesandbox/codesandbox-client#4987]
# 🐛 bug report

## Preflight Checklist

- [X] I have read the
      [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md)
      for this project.
- [X] I agree to follow the
      [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Hi there, I am trying to run some Angular jest tests on jest-lite. In order to make it work, we just have to set up the TestBed. This can be done manually or by importing `jest-preset-angular`. I tried to add the setup file (`setup-jest.ts` that imports `jest-preset-angular`) to `package.json`'s `jest.setupFilesAfterEnv` but it is apparently ignored. It is quite surprising because while looking up codesandbox-client's source code, it feels we should call the code below as it is not a react or react-ts project: https://github.com/codesandbox/codesandbox-client/blob/c971e58d41781938423aee469e67b42e81e68f18/packages/app/src/sandbox/eval/tests/jest-lite.ts#L287-L306 

Thank you in advance.

## How has this issue affected you? What are you trying to accomplish?
Running Angular jest tests on codesandbox.

### To Reproduce

You can see the tests are failing with the following error `Cannot read property 'getComponentFromError' of null` because TestBed is not initialized.

**Comment by christianalfoni** [comment]
Hi @yjaaidi and thanks for writing up an issue!

The `jest` implementation in CodeSandbox is not really extensible, as you have discovered. It was implemented as a way to do simple prototyping tests. We are currently working on a new environment where you will be doing actual development on projects, where `jest` works exactly as you expect to. Please stay tuned for this and we will update our documentation to make this more clear in the meantime 😄

**Comment by yjaaidi** [comment]
😲 cool! 🎉

**Comment by yjaaidi** [comment]
Hi @christianalfoni! I hope you're fine.
Is there anything new on this topic?
Thank you in advance.
