### ISSUE TITLE
Crashed when opening a sandbox folder

### ISSUE THREAD

**Issue by NearHuscarl** [codesandbox/codesandbox-client#4991]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  * Go to [one](https://codesandbox.io/dashboard/all/React%20-%20AgGrid?workspace=74102a37-7dc4-4d7c-9afb-96e64dc698a4) of my sandbox folders

  * Page crashed, I tried to go back and it works as usual again (only crashed one time)

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | firefox | 81.0.0 | Windows 10           | 365c65549          |

  **Route:**
  https://codesandbox.io/dashboard/all/React%20-%20AgGrid?workspace=74102a37-7dc4-4d7c-9afb-96e64dc698a4

  **Error Code:**
e940fa92cd9b424bb3a7e95ee00e91c2

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: f[0] is undefined
  $s@https://codesandbox.io/static/js/app.39f8f05fb.js:272:240349
ua@https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1769943
Ka@https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1778208
Es@https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1816396
ml@https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1800784
hl@https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1800707
il@https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1798035
Xo/<@https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1756218
../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.production.min.js/t.unstable_runWithPriority@https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1831554
qo@https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1755927
Xo@https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1756165
Yo@https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1756098
se@https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1825306
Sn@https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1739726

  
    in $s
    in nu
    in Unknown
    in t
    in t
    in div
    in Content___StyledElement
    in Unknown
    in withRouter()
    in main
    in Dashboard___StyledElement2
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in De
    in Unknown
    in lp
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by lbogdan** [comment]
`selectedItems[0]` is `undefined` here:

https://github.com/codesandbox/codesandbox-client/blob/365c65549d7ef50b56288bcc4a35d8d8ab9f1b99/packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenu.tsx#L101-L106

**Comment by christianalfoni** [comment]
PR here: https://github.com/codesandbox/codesandbox-client/pull/5049
