### ISSUE TITLE
I can’t open CodeSandBox React.js projects via links in Chrome or Edge on mobile device (Android)

### ISSUE THREAD

**Issue by cybodt** [codesandbox/codesandbox-client#5006]
# 🐛 bug report

## Preflight Checklist

- [x ] I have read the
      [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md)
      for this project.
- [x ] I agree to follow the
      [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

The problem is when i click on links to projects made by React.js on CodeSandbox on Google Chrome or Microsoft Edge on mobile browsers. In my case on Android phone. On Firefox mobile its works fine.
Also if you type or paste address from link there is no problem. Only if you click on project link on Chrome or Edge on mobile device.

### To Reproduce

For simplicity i made test pen to put the external CodeSandbox links:

[click to test ](https://codepen.io/emil-iliev/full/NWrGdLB)

There are two buttons: first button point to CodeSandbox react.js project - this is standard welcome project.
When i click this button on Chrome or Edge on mobile device - nothing happens.
For comparison i add second button which point to CodeSandbox static HTML project. - in this case everything work on all browsers, both mobile and desktop.
It seems that the problem is related to projects built with react.js
 

 

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox   | v3.9.3|
| Browser app versions: Chrome 85.0.4183.127,  Edge 45.08.2.5074  |
| Operating System  |Android 9|

**Comment by SaraVieira** [comment]
I can confirm with a one plus one it did not open on my android but it did open on my wife's iphone

**Comment by lbogdan** [comment]
Tested on two Android phones (and two iPhones, where it works), in Chrome, and I have a bit different behavior on both - the React sandbox (https://1x86r.csb.app/) opens in a new tab, but it doesn't seem to "start", so I'm left staring at a blank page. If I go ahead and manually open it in a new tab, it works as expected. Weird browsers are weird. 🤷‍♂️

**Comment by christianalfoni** [comment]
We identified the issue here and created an issue that you can follow here: https://github.com/codesandbox/codesandbox-client/issues/5048
