### ISSUE TITLE
Codesandbox is not running postinstall hooks for npm packages when package is installed via the UI in container sandbox

### ISSUE THREAD

**Issue by pantharshit00** [codesandbox/codesandbox-client#5009]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Codesandbox container instances are not running postinstall hooks on npm packages installed via the web UI. This is causing Prisma client(https://github.com/prisma/prisma) to be uninitialised and fail.

## How has this issue affected you? What are you trying to accomplish?

I work at Prisma and this affect our users and potentially users of other packages which bootstrap things in postinstall script. This issue was caught recently by our end to end tests and codesandbox is the only platform failing there: https://github.com/prisma/e2e-tests/pull/878

### To Reproduce

1. Fork the https://codesandbox.io/s/upbeat-faraday-10lck 

2. Install `@prisma/cli@2.9.0-dev.82` and `@prisma/client@2.9.0-dev.82` from the web ui.

3. Open a new terminal tab and run `test.js`. It will throw this error:
![image](https://user-images.githubusercontent.com/22195362/95874925-117fba80-0d8f-11eb-8f33-7f6f9e79a54c.png)
Postinstall hook runs `prisma generate` so this should not happen.

(PS: this doesn't happen if you install the deps via provide terminal and npm cli on the sandbox)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 34a94fb16
| Browser          | Chrome 85.0.4183.121
| Operating System | MacOS 10.15.7

**Comment by lbogdan** [comment]
Hey @pantharshit00 ,

We're using `yarn` by default (and more so in sandboxes that already contain a `yarn.lock` file, like the sandbox you linked to), and run `yarn [install]` whenever the `package.json` changes. I'm not sure what we could do different.

**Comment by lbogdan** [comment]
Is it failing consistently?

**Comment by divyenduz** [comment]
Yes, we fixed it by adding `yarn prisma generate` in prestart script but it was working without this 2 days ago for many months already.

**Comment by lbogdan** [comment]
And are you sure this is not a regression in your packages?

**Comment by divyenduz** [comment]
Yes, we are sure about it, we validated it by removing `yarn prisma generate` from all the E2E tests on all the platforms via https://github.com/prisma/e2e-tests/pull/878/files

Only CodeSandbox failed https://github.com/prisma/e2e-tests/actions/runs/304012826

All of these platforms/test are using the same Prisma CLI and Client version.

**Comment by lbogdan** [comment]
I did some more digging, and I found this as the root-cause: `yarn --non-interactive` (the exact command we run when `package.json` is changed) does not add the required files in `node_modules/.prisma/client`:

```sh
# yarn
sandbox@sse-sandbox-qxivo:/sandbox$ rm -fr node_modules

sandbox@sse-sandbox-qxivo:/sandbox$ yarn
yarn install v1.22.4
warning package.json: No license fieldwarning node-http-server@1.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 4.11s.

sandbox@sse-sandbox-qxivo:/sandbox$ ls -al node_modules/.prisma/client
drwxr-xr-x 2 sandbox sandbox      122 Oct 15 12:31 .
drwxr-xr-x 3 sandbox sandbox       20 Oct 15 12:31 ..
-rw-r--r-- 1 sandbox sandbox    22539 Oct 15 12:31 index.d.ts
-rw-r--r-- 1 sandbox sandbox    18337 Oct 15 12:31 index.js
-rw-r--r-- 1 sandbox sandbox       77 Oct 15 12:31 package.json
-rwxr-xr-x 1 sandbox sandbox 23018344 Oct 15 12:31 query-engine-debian-openssl-1.1.x
-rw-r--r-- 1 sandbox sandbox      190 Oct 15 12:31 schema.prisma

# yarn --non-interactive

sandbox@sse-sandbox-qxivo:/sandbox$ rm -fr node_modules

sandbox@sse-sandbox-qxivo:/sandbox$ yarn --non-interactiveyarn install v1.22.4
warning package.json: No license field
warning node-http-server@1.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 2.35s.

sandbox@sse-sandbox-qxivo:/sandbox$ ls -al node_modules/.prisma/client
total 8
drwxr-xr-x 2 sandbox sandbox   40 Oct 15 12:32 .
drwxr-xr-x 3 sandbox sandbox   20 Oct 15 12:32 ..
-rw-r--r-- 1 sandbox sandbox 1197 Oct 15 12:32 index.d.ts
-rw-r--r-- 1 sandbox sandbox  332 Oct 15 12:32 index.js
```

Not knowing the internals, I'm not sure if it's a `yarn` bug or a bug in whatever copies those files in `node_modules/.prisma`.

**Comment by lbogdan** [comment]
Being quite intrigued by what might be happening, I followed up with @arcanis and asked him what the difference is between a "normal" `yarn` run and a non-interactive one. 

He pointed me to this code https://github.com/yarnpkg/yarn/blob/a3b1294c22043cd8868b6a1decb77b673e764efd/src/util/execute-lifecycle-script.js#L277 and suggested that "perhaps Prisma checks if the terminal is a TTY before running stuff?".

**Comment by divyenduz** [comment]
Thank you for digging further into this. Is using `yarn --non-interactive` new from your side or has it always been like that?

**Comment by lbogdan** [comment]
We changed to `--non-interactive` a long time ago (commit date is Dec 4, 2018), because there were cases where `yarn` would block indefinitely waiting for user input, resulting in sandboxes not starting.

**Comment by SaraVieira** [comment]
Hey!

Do you have any updates here? Seems there is not a lot we can do in our side :/

**Comment by pantharshit00** [comment]
We haven't received any user reports so far so I am just going to close this.
