### ISSUE TITLE
Define user-owned, private Sandbox

### ISSUE THREAD

**Issue by den1k** [codesandbox/codesandbox-client#501]
I looked into the `define` API but didn't see a way to a) define a sandbox for a particular user and b) set it to be private? Is this possible?

**Comment by CompuIves** [comment]
Ah, sorry for the late reply @den1k. The define API can only create sandboxes manually currently, to save the hassle of handling with authorization tokens.

It would definitely be good functionality to have though. We already have support of creating user sandboxes in the CodeSandbox CLI, so I don't see a reason not to support this.

**Comment by tknickman** [comment]
I second this request! Not being able to define a private sandbox via the API is currently blocking my teams use of codesandbox.

**Comment by CompuIves** [comment]
@tknickman That’s really interesting, what’s your use case of this? Maybe we should allow for an API key er something...

**Comment by lbogdan** [comment]
Or maybe add a `--private` flag to the CLI?

**Comment by buryndin** [comment]
@CompuIves 
Are there any updates on this improvement? We also need to define private sandbox via API in our team workspace.
