### ISSUE TITLE
Bug report: Maximum call stack size exceeded when destructuring certain packages

### ISSUE THREAD

**Issue by NawarA** [codesandbox/codesandbox-client#5022]
# 🐛 bug report
Hi, a recent update to Codesandbox is now causing this error. 

![image](https://user-images.githubusercontent.com/2067616/96295401-ae667180-0fa2-11eb-93d4-82c535e533a0.png)

I can confirm that this error was not present a few days / last week...aka, its a recently appearing issue, likely with your latest last two releases.

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
We traced the bug down to this line of code (which again, worked a few days ago). 

![image](https://user-images.githubusercontent.com/2067616/96295717-f4bbd080-0fa2-11eb-849a-65377d018c50.png)

Meanwhile, doing simple destructuring causes infinite loops from certain packages, see below:

![image](https://user-images.githubusercontent.com/2067616/96296074-8c212380-0fa3-11eb-882f-78d119287e45.png)

## How has this issue affected you? What are you trying to accomplish?
We had to switch from Codesandbox to VSCode, becuase VSCode loads this normally...haha

Please patch your recent updates, so we can switch our team back to Codesandbox

### To Reproduce

1. Go the sandbox link below 
2. Go to the file `/src/Card.js`
3. Comment out the two lines and you'll see one loads and the other causes infinite loops
4. Recognize, this wasnt an issue a few days ago

See the screenshots above.

Thanks for your hardwork. Much love 🎸 

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/epic-http-pht19?file=/src/Card.js

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 8afa3a48b|
| Browser          | Chrome 86 |
| Operating System | Win 10, Ubuntu 18.04, Ubuntu 20.04 |

**Comment by tjxnor** [comment]
Hi @NawarA, I'm facing the same issue. 
Can you suggest how you were able to trace the error down to the offending lines? I have many different files with imports from material-ui/icons and have updated a few, but the error still persists.

Thanks!

**Comment by NawarA** [comment]
I commented everything out. I then proceeded to see what was source of the issue by commenting things back in, one line at a time.

I created a demo sandbox to keep things simple and show what was causing the overflow (import aliasing). 

That being said, I have a large app that I can't develop in codesandbox right now, because it'd be ludicrous to change every import alias for temporary bug on codesanbox's side. That'd produce a lot of development waste. 

Our team is now using vs code, which doesn't have the issue.

**Comment by tjxnor** [comment]
Yup, it's going to be a nightmare if the codebase is large, which I'm approaching too.
I really like the ability to code in the browser in a "no-install" setup, but guess it's time to move on.
Thanks for the approach!

**Comment by mordechaim** [comment]
Having the same issue in https://codesandbox.io/s/sharp-tereshkova-ppn4e?file=/src/App.js

Removing the icon import resolves this.

**Comment by NawarA** [comment]
Yeah, looks like `destructing` is screwing up the CSB transpiler

**Comment by lbogdan** [comment]
Hey @NawarA & all,

Sorry for the inconvenience and the delayed response! We'll take a look at this first time tomorrow, and get it fixed ASAP!

**Comment by NawarA** [comment]
Thanks @lbogdan 

works now: 

![image](https://user-images.githubusercontent.com/2067616/96627269-783c3100-12c5-11eb-8d8e-6bfd3ba1e359.png)

lgtm 👍

**Comment by tjxnor** [comment]
awesome! 👍

**Comment by lbogdan** [comment]
@NawarA You should thank @CompuIves , he was the one that fixed it. 🙂
