### ISSUE TITLE
bug in Clear console button

### ISSUE THREAD

**Issue by Devgupta0** [codesandbox/codesandbox-client#5023]
Hi there,
The Bug that I find when I click on clear console button so on multiple times I click then it clean and most of the time clear button doesn't work. I'll do with that work using problems-button then it clear the screen. so I think there may some bugs in clear button. please fix these because it takes time to clear the console. Another option to refresh the screen then it works.

**Comment by SaraVieira** [comment]
Hey

Please do not delete the template and follow it so we can reproduce it
