### ISSUE TITLE
Scroll Bar in Problems(Error) Window.

### ISSUE THREAD

**Issue by Anmol53** [codesandbox/codesandbox-client#5024]
# 🌈 Feature

There is no scrollbar in the "Problems" window.
There should be a scrollbar similar to a scrollbar in a Console tab.
It will help to find the bug in the coded smoothly.

**Comment by SaraVieira** [comment]
Can you please share a sandbox? 

We have a template for issues to help with this, please follow it or you issue will be closed 

Thank you

**Comment by Anmol53** [comment]
https://codesandbox.io/s/infallible-chebyshev-pm0hn?file=/src/index.js

I just created this sandbox for showing error.

There are 32 errors in this code, but I can see only a few of them.
