### ISSUE TITLE
Error 413 : Request Entity Too Large

### ISSUE THREAD

**Issue by Kimyeiseok** [codesandbox/codesandbox-client#5025]
https://codesandbox.io/s/wetube-forked-mt8ex

Whenever I try to upload file over 1MB, it returns me Error413: Request Entity Too Large
It seems that only file under 1MB is allowed. 

How can I increase limit of file size? 
Should I subscribe to Patron or Pro account?

**Comment by christianalfoni** [comment]
Hi @Kimyeiseok ,

You should be able to upload files up to 20MB. Could you drop your file here on GitHub so we can verify? 😄 

As Patron/Pro you can upload files up to 500MB, https://codesandbox.io/docs/uploading

**Comment by snickell** [comment]
@christianalfoni This appears to be occurring on Pro accounts too. For example, I'm trying to upload a 52.3MB JSON file, and I'm logged in with a pro account, I'm getting a 500 from the uploads endpoint (https://codesandbox.io/api/v1/users/current_user/uploads):

![image](https://user-images.githubusercontent.com/223277/102155241-3fc95700-3e1f-11eb-81cb-2c90816c201a.png)

The `Error 413 : Request Entity Too Large` is actually later (a "downstream" error), and is thrown from sentry, appears to actually be a cascaded error thrown by an exception handler which traps exceptions and uploads the backtrace to sentry:
```
instrument.js:136 POST https://sentry.io/api/2071895/store/?sentry_key=f595bc90ce3646c4a9d76a8d3b84b403&sentry_version=7 413 (Request Entity Too Large)
```

**Comment by snickell** [comment]
I tried slurping the response to the `current_user/uploads` POST request, but statusText is blank, so whatever triggered the 500 will probably require server side logs to figure out.

**Comment by snickell** [comment]
I tried uploading different file sizes:
```
➜  Downloads> head -c 22000000 52MB.dat > 22MB.dat
➜  Downloads> head -c 29000000 52MB.dat > 29MB.dat
➜  Downloads> head -c 9000000 52MB.dat > 9MB.dat  
➜  Downloads> head -c 900000 52MB.dat > 900kb.dat
```

ONLY the 900kb file succeeded, the rest (larger) returned the same 500 error behavior.

**Comment by snickell** [comment]
OK, `6MB.dat` works, `7MB.dat` returns a 500. 

HOWEVER, this is with highly compressible JSON, so the wire size is probably quite a bit smaller (e.g. a 10x compression factor wouldn't surprise me on JSON, maybe the limit is 1024MB). If the limit is in an HTTP reverse proxy, ingress, etc that's receiving compressed HTTP, its possible the limit is actually lower. I'll retry with random noise to figure out the real file size that breaks.

I suspect if there's not more useful information available to @christianalfoni in the server side logs, sometimes you can pinpoint which layer is having trouble based on what size it breaks at.

**Comment by snickell** [comment]
OK, whatever is rejecting is after HTTP compression is stripped off, I switched to using incomressible (random) data, and the break still occurs between 6MB and 7MB:
```
➜  Downloads> head -c 6M /dev/urandom | upload-to-codesandbox.sh
HTTP response code: 200
➜  Downloads> head -c 7M /dev/urandom | upload-to-codesandbox.sh
HTTP response code: 500
```

Hope this helps! If it helps to diagnose, I'm https://codesandbox.io/u/snickell, and in case the logs are keyed by sandbox, the sandbox I've been uploading to is: https://codesandbox.io/s/confident-tree-vghxy

**Comment by snickell** [comment]
I'd suggest renaming the issue "Uploads larger than 6MB receiving 500 error", since the "Error 413" is just a cascaded error related to sentry.io

**Comment by snickell** [comment]
I believe this is the same issue as: https://github.com/codesandbox/codesandbox-client/issues/4167
