### ISSUE TITLE
Codesandbox preview failed with antd again

### ISSUE THREAD

**Issue by zombieJ** [codesandbox/codesandbox-client#5028]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Since #4898 back again

<img width="545" alt="截屏2020-10-19 下午6 34 15" src="https://user-images.githubusercontent.com/5378891/96439883-bab82c00-1239-11eb-8a92-75428d7c36f9.png">

### To Reproduce

https://codesandbox.io/s/jiben-ant-design-demo-forked-51t64

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest|
| Browser          | Chrome |
| Operating System | Mac|

**Comment by zombieJ** [comment]
hi @SaraVieira @CompuIves, could you pls help to take a look : )

**Comment by CompuIves** [comment]
Oh this is an interesting one. This file `https://unpkg.com/@babel/runtime@7.12.1/helpers/esm/unsupportedIterableToArray.js` is requesting something from `@babel/runtime`, but we had hardpinned that dependency on a version that doesn't have the file. I've now changed the pin to be a caret instead, and it seems to work. opening a pr...
