### ISSUE TITLE
Opening CSB urls can cause blank screen

### ISSUE THREAD

**Issue by christianalfoni** [codesandbox/codesandbox-client#5048]
When you open a `.csb.app` using a hyperlink creating a child tab or window, the `csb.app` detects this as being a "detached preview" from CodeSandobx, where it waits for a message from CodeSandbox to start bundling.

A couple of suggestions to solve it:

- Create a timeout to wait for the message
- When in CodeSandbox, open the detached mode with a query to identify that it indeed should wait for a message before doing the first bundle

**Comment by cybodt** [comment]
I can confirm that the problem is already solved.  React.js links opened in new tabs in Chrome and Edge on mobile device (Android) already works!
This issue already can be closed!

**Comment by juanrozo89** [comment]
Hi, I'm still facing this issue but I don't understand how should I create a timeout to wait for the message
or open the detached mode with a query to identify that it indeed should wait for a message before doing the first bundle.

Thanks in advance
