### ISSUE TITLE
`now.json` for Vercel deployment is now deprecated

### ISSUE THREAD

**Issue by AryanBeezadhur** [codesandbox/codesandbox-client#5052]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

![image](https://user-images.githubusercontent.com/34424160/97047799-6979a680-1571-11eb-998d-68bf70cf21a6.png)

You can see in the image above, there is a button to create a `now.json` file. But since ZEIT rebranded to Vercel, ZEIT/now was renamed to Vercel/Vercel, and the `now.json` file is now a `vercel.json` file.

The button should create a `vercel.json` file instead of `now.json`.

**Comment by andrasbacsai** [comment]
Hey @AryanBeezadhur . 

You are right, but as Vercel does not deprecate `now.json.`, I don't think it's an urgent issue. I've added to our internal list of todos, though we have a long list of prioritized problems, so we need "to get there." Sorry for the wait, but it will be fixed eventually!
