### ISSUE TITLE
Can't scroll horizontally in Firefox

### ISSUE THREAD

**Issue by ffxsam** [codesandbox/codesandbox-client#5054]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Horizontal scrolling in Firefox triggers the browser back/forward actions. Works fine in Chrome.

### To Reproduce
1. Open any sandbox.
1. Scroll left/right. I'm using a trackpad, not sure if that makes a difference.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | ???
| Browser          | Firefox 81
| Operating System | macOS 10.15.7

**Comment by ffxsam** [comment]
This is still an issue.

**Comment by SaraVieira** [comment]
Hey

I am not sure we can do anything about this, the same thing happens in safari, it seems like default browser behaviour, chrome just doesn't have that behaviour.

you can turn it off in the settings like so:

![CleanShot 2021-01-27 at 19 41 46](https://user-images.githubusercontent.com/1051509/106038073-c2f4f280-60d7-11eb-9398-20e290f7b212.png)

but I don't think we can change browser behaviour, we already have 

```
overscroll-behavior-x: none;
```

to solve that issue but it seems to not work anymore, our emebed also has that and seems to have the same experience. It's quite a bad experience but it's just the limitations of working in a browser

**Comment by ffxsam** [comment]
Browser gestures for back/forward usually kick in when the event that captures the gesture isn't doing     `event.preventDefault()`. It's also worth mentioning that I'm able to scroll to the right, but I have to scroll like mad by swiping a bunch before it works.

Having horizontal scroll in web-based code editors is definitely doable (and cross-platform), as with AWS's Cloud9:

![Cloud9](https://user-images.githubusercontent.com/12532733/106057805-1e15ed80-60b6-11eb-92df-4aacc3e612aa.gif)

It would be great if this issue could be looked into!

**Comment by SaraVieira** [comment]
I just realized that our problem is in the editor and I only tested outside when I answered you, on the editor is not okay as there are ways to fix, I will take a look on Monday

Sorry for not seeing it before, I honestly assumed it would work on our editor since I thought it was the default

**Comment by SaraVieira** [comment]
After looking for a bit more it seems the issue is that VSCode does not rely on using overflow auto but instead makes everything hidden and uses probably JS to show some fancy scroller thus not making the property work since firefox cannot tell it's a scrollable element

Will keep investigating this on monday

**Comment by ffxsam** [comment]
Thanks!

**Comment by danilowoz** [comment]
Hey, I dived into this issue and I found out a couple of things:

It seems that the `wheel` event fires this behavior to back and forth the browser navigation. Preventing this event might be a possible way to solve this, which would avoid unexpected events in the code editor. However, once we disable the `wheel` event on `body`, every part of the UI that depends on that event stop working.

For example:
```js
body.addEventListener("wheel", e => e.preventDefault(), { passive: false });
```

Doing this, it prevents both Chrome and Firefox from browser navigation (and even other issues), but the code-editor, file explorer, and other parts of the UI stop scrolling. The bottom line, it'd require a considerable effort to create an internal scroll event for each part of the UI.

I'll figure out here how to proceed in order to solve this issue.

**Comment by ffxsam** [comment]
@danilowoz Couldn't you just apply the wheel event on the editor div itself? (thinking about the `div.editor-container`). I just tried it myself, and I was able to prevent scroll & browser back/forward in that editor pane only, but normal wheel behavior still works everywhere else.

**Comment by danilowoz** [comment]
I did here the same thing to the `.editor-container`, which prevented the back/forward navigation, however, I wasn't able anymore to scroll into the code editor. Were you able? 

I'm going to investigate more here, how to fix it.

**Comment by ffxsam** [comment]
Oh yes, of course - it does disable all scrolling. I assumed you would manually code the scrolling behavior into the editor.

However, I did solve the entire problem by adding this CSS to the `<html>` element:

```css
{
  overscroll-behavior-x: none;
}
```

**Comment by danilowoz** [comment]
Yeah, it worked! 
As `<body />` also has this property, I thought it wouldn't need to add it twice in the `<html />` as well.

I'll address it tomorrow, or at least by Friday, I know that this bug is terribly annoying.

**Comment by ffxsam** [comment]
@danilowoz Thanks!

It's weird, it seems that the Monaco editor automatically blocks back/forward gestures out of the box: https://microsoft.github.io/monaco-editor/

So I'm not sure why CodeSandbox has this issue. Might be worth investeigating.. or maybe not, since this fix seems to work. 😁
