### ISSUE TITLE
TS Sandbox compiles and executes invalid code?

### ISSUE THREAD

**Issue by IgnusG** [codesandbox/codesandbox-client#5057]
# 🐛 bug report

## Preflight Checklist

- [X] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [X] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Running the following code works even though it shouldn't?

```typescript
try {
  const a = 'I should not be logged?';

  throw new Error();
} catch (error) {
  console.log('1', a);
} finally {
  console.log('2', a);
}
```

Since variable a is block scoped this should fail. This is the output of repl.it:

![image](https://user-images.githubusercontent.com/6438760/97166855-33614000-1786-11eb-8c15-a02726bd6166.png)

This is the output of codesandbox:

![image](https://user-images.githubusercontent.com/6438760/97166877-3bb97b00-1786-11eb-9712-89a5b0527810.png)

## How has this issue affected you? What are you trying to accomplish?
I was messing around with error handling. It does not rely affect me

### To Reproduce

Browser Preview: https://snzo8.csb.app/
Sandbox: https://codesandbox.io/s/crazy-water-snzo8?file=/src/index.ts:0-144

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Web Version?
| Browser          | Edge
| Operating System | Windows

**Comment by CompuIves** [comment]
Hey! Yep, that looks very weird. The reason for the code working is because how we compile TS to be compatible in older browsers.

The compiled code is this:
```js
(function evaluate(require, module, exports, process, setImmediate, global, __dirname, __filename, $csbImport) {"use strict";

try {
    var a = 'I should not be logged?';
    throw new Error();
} catch (error) {
    // @ts-ignore
    console.log('1', a);
} finally {
    // @ts-ignore
    console.log('2', a);
}
console.log('Last');
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJpbmRleC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOztBQUFBLElBQUk7QUFDRixRQUFNLEFBQUMsSUFBRyxBQUF5QixBQUFDO0FBRXBDLFVBQU0sSUFBSSxBQUFLLEFBQUUsQUFBQztBQUNuQixFQUFDLE9BQU8sQUFBSyxPQUFFO0FBQ2QsQUFBYTtBQUNiLEFBQU8sWUFBQyxBQUFHLElBQUMsQUFBRyxLQUFFLEFBQUMsQUFBQyxBQUFDO0FBQ3JCLFVBQVM7QUFDUixBQUFhO0FBQ2IsQUFBTyxZQUFDLEFBQUcsSUFBQyxBQUFHLEtBQUUsQUFBQyxBQUFDLEFBQUM7QUFDckI7QUFFRCxBQUFPLFFBQUMsQUFBRyxJQUFDLEFBQU0sQUFBQyxBQUFDIiwic291cmNlc0NvbnRlbnQiOlsidHJ5IHtcbiAgY29uc3QgYSA9ICdJIHNob3VsZCBub3QgYmUgbG9nZ2VkPyc7XG5cbiAgdGhyb3cgbmV3IEVycm9yKCk7XG59IGNhdGNoIChlcnJvcikge1xuICAvLyBAdHMtaWdub3JlXG4gIGNvbnNvbGUubG9nKCcxJywgYSk7XG59IGZpbmFsbHkge1xuICAvLyBAdHMtaWdub3JlXG4gIGNvbnNvbGUubG9nKCcyJywgYSk7XG59XG5cbmNvbnNvbGUubG9nKCdMYXN0Jyk7XG4iXX0=
//# sourceURL=https://snzo8.csb.app/src/index.ts
})
```

And here the Babel transpiler converted the `const` to a `var`, because of that it will be a variable in the global scope, and it can be references by other scopes.
