### ISSUE TITLE
Vue 3 + component jsx template syntax 

### ISSUE THREAD

**Issue by mayoujin** [codesandbox/codesandbox-client#5059]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Vuejs 3 app with component using jsx template syntax (https://github.com/vuejs/jsx-next/tree/dev/packages/babel-plugin-jsx#readme) causes error.
```
TypeError Cannot read property '$createElement' of undefined
```
<img width="1278" alt="Снимок экрана 2020-10-27 в 15 25 17" src="https://user-images.githubusercontent.com/5278097/97301417-cd011e00-1868-11eb-9985-deee94e75a8f.png">

## How has this issue affected you? What are you trying to accomplish?
I could not run Vuejs 3 application code with jsx template component syntax.

### To Reproduce
Provided component's code of `App.vue`
```
// App.vue
<script>
import { defineComponent } from "vue";

export default defineComponent({
  setup() {
    return () => <div>App</div>;
  }
});
</script>
```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome 86.0.4240.75
| Operating System | MacOS Catalina 10.15.7 (19H2)

**Comment by andrasbacsai** [comment]
Good catch. Unfortunately, we only support .babelrc atm, not dynamically evaluated babel.config.js. We will add it to our backlog!

Thanks for the bug report!

**Comment by mayoujin** [comment]
Ok. I get it.
It is make sense to fix "Vuejs 3" project's template provided by "Create Sandbox" dialog. Cause current template provides `babel.config.js`  file by origin.

<img width="1204" alt="Снимок экрана 2020-10-31 в 10 17 15" src="https://user-images.githubusercontent.com/5278097/97773641-9d049400-1b62-11eb-97b0-2d7416e20273.png">

**Comment by andrasbacsai** [comment]
@CompuIves Could you please take a look at this?
