### ISSUE TITLE
 Codesanbox won't let me upload changes to a repository of which I am a contributor

### ISSUE THREAD

**Issue by lauracosorio** [codesandbox/codesandbox-client#5066]
# 🐛 bug report

## Description of the problem

I am a contributor in a repository, I'm trying to import that repository in codesanbox and it works, but when I'm going to commit the changes it brings up an alert that says " You do not seem to have access to commit to Problemas-Ambientales/EQUIPO3_RU_PPI2020. Please read the documentation to grant access." But I know that I have access, I also try to make the commit with the administrator account but it brings up the same error.

**Comment by christianalfoni** [comment]
Hi there!

This can seem a bit confusing.

Go to:

1. GitHub
2. Profile
3. Settings
4. Applications
5. Authorized OAuth Apps (It is a tab)
6. Find CodeSandbox and click it

Give access to the repo in question 😄 

We will update the documentation with this information!

**Comment by lauracosorio** [comment]
Thank you a lot !!

**Comment by SaraVieira** [comment]
Hey!

Did this fix your issue?

Can I close this? We added it to the docs here: https://codesandbox.io/docs/git#committing-to-organizations

**Comment by lauracosorio** [comment]
> Hey!
> 
> Did this fix your issue?
> 
> Can I close this? We added it to the docs here: https://codesandbox.io/docs/git#committing-to-organizations

Yes it worked, you can close it.
