### ISSUE TITLE
No puedo subir cambios al github

### ISSUE THREAD

**Issue by lauracosorio** [codesandbox/codesandbox-client#5067]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Soy colaboradora en un repositorio y quiero trabajar desde codesanbox, importo el repositorio y puedo codificar, pero a la hora de subir cambios al github me sale una alerta diciendo que no tengo permiso para subir cambios, yo soy colaboradora del repositorio, de igual manera he tratado de subir los cambios desde la cuenta del administrador y tampoco me deja, me sale el mismo error y no entiendo por qué si el administrador del repositorio tiene acceso ha realizar todos los cambios que quiera. 
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by garethx** [comment]
Dupe of #5066
