### ISSUE TITLE
Versioning with prefix `v` seems to break network calls

### ISSUE THREAD

**Issue by marina-mosti** [codesandbox/codesandbox-client#5069]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Adding library prefixed by `v` seems to break the prod-packager.

## How has this issue affected you? What are you trying to accomplish?

The lib is not useable due to the error :)

### To Reproduce
Reproduction found here when adding `formvuelate v2.0.0-beta.3`
https://codesandbox.io/s/async-cdn-ukr1p?file=/src/App.vue

Calls to https://prod-packager-packages.codesandbox.io/v2/packages/formvuelate/v2.0.0-beta.3.json get a 403, we're guessing its due to the v prefix, or the beta suffix

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  
| Browser          | Firefox 82.0.1
| Operating System | MacOS

**Comment by SaraVieira** [comment]
Hero! Thank you 🙌

**Comment by SaraVieira** [comment]
No closey

**Comment by lbogdan** [comment]
As far as I know, `vx.y.z` is not valid semver semantics, so if you're using it for your packages, you might get some unexpected behavior here and there.

**Comment by marina-mosti** [comment]
Hey @lbogdan 

I've never seen any issues with this type of versioning, but regardless if you pull the package from NPM with just 2.2.0 without the v it works just fine, not sure how ya'll are doing the parsing.

It seems though, that this only breaks when declaring a non fixed version. If I add the lib with 2.2.0 it works, but if I add it like ^2.2.0 it breaks, your API seems to be trying to parse something that isnt there.

I'll consider changing the versioning to not have the `v` as an internal fix, but just letting you know where its flinching.

**Comment by marina-mosti** [comment]
Im not entirely sure to be honest, its been a while since we came out of beta versions. I've just updated our semver to 2.2.1 and it seems to be working fine with your UI. So as far as my personal issue, this is fixed. Just wanted to let you know just in case. Thanks for the support

**Comment by andrasbacsai** [comment]
Closing now. If you have any further questions, let us know!
