### ISSUE TITLE
403 after adding a package

### ISSUE THREAD

**Issue by xqwtsz** [codesandbox/codesandbox-client#5071]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Getting a CORS error then a 403 after adding any package, its `styled-components` in the linked sandbox.

## How has this issue affected you? What are you trying to accomplish?
Cant run the sandbox after adding packages.

### To Reproduce
Go to the link.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Firefox 82.0.2 (64-bit)
| Operating System | Windows 10

**Comment by xqwtsz** [comment]
**Screenshot**

![1](https://user-images.githubusercontent.com/3916893/97783564-f2f42e80-1b98-11eb-9aaf-72fcf5a4a57e.png)

**Comment by sannek** [comment]
Hi!
Thanks for your bug report. Could you confirm that this is still happening for you? I cannot see any CORS errors when I open this sandbox in any browser.

**Comment by xqwtsz** [comment]
> Hi!
> Thanks for your bug report. Could you confirm that this is still happening for you? I cannot see any CORS errors when I open this sandbox in any browser.

Hi @sannek!

Still happening on my Windows machine using Firefox, no problems in my Mac in any browser.

**Comment by sannek** [comment]
Ah - that explains why I can't reproduce it! Let me see if anyone on our team has a Windows machine where they can investigate. To be continued...

**Comment by SaraVieira** [comment]
Hey!

I am the windows carrying person but I was on vacation

I can open it on my windows machine

![image](https://user-images.githubusercontent.com/1051509/98716502-f606d000-238b-11eb-845b-2925a416112d.png)

DOes it still happen in your computer?

**Comment by xqwtsz** [comment]
> 
> 
> Hey!
> 
> I am the windows carrying person but I was on vacation
> 
> I can open it on my windows machine
> 
> ![image](https://user-images.githubusercontent.com/1051509/98716502-f606d000-238b-11eb-845b-2925a416112d.png)
> 
> DOes it still happen in your computer?

Hi! It still does. I will try disabling all security options one by one to find out which one is causing it then.

**Comment by SaraVieira** [comment]
Thank you!

Let me know if it fixes it

**Comment by xqwtsz** [comment]
Got it! It was not Firefox itself but `DuckDuckGo Privacy Essentials` addon. 🤦 Weirdly it doesn't affect anything on Chrome or @ my macOS - Firefox. Thank you for the help! @sannek & @SaraVieira

**Comment by SaraVieira** [comment]
That makes sense, sometimes the blocked things are just random

I am glad we figured this out :D
