### ISSUE TITLE
CodeSandbox CI is not starting build

### ISSUE THREAD

**Issue by phryneas** [codesandbox/codesandbox-client#5073]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I am trying to get codesandbox builds for my unpublished package (not sure if this makes a difference?) so people can already try it & experiment with it.

Codesandbox does not seem to start the build, it just hangs on "Loading".

### To Reproduce

See https://ci.codesandbox.io/status/phryneas/rtk_simple-query/pr/1

**Comment by sannek** [comment]
Thanks for your bug report. Did you perhaps move or rename your repository? Could you try deleting and re-adding your project to the CI? I'm also checking if it matters if your package is unpublished, but since the repo is public I don't think it _should).

**Comment by phryneas** [comment]
Yes, I moved the package yesterday. I'll readd the new one to the CI and post an updated link here.

**Comment by phryneas** [comment]
Okay, these are running now: https://ci.codesandbox.io/status/rtk-incubator/simple-query/pr/1/builds/69251

This should not be any correlation though - at the time I moved the repo, the build had already been "loading" for 20+ hours.

**Comment by sannek** [comment]
That's odd - though i am glad it is working now! I'll see if I can figure out what went wrong in the first place, but as it is working now I think it was maybe just a hiccup.

**Comment by phryneas** [comment]
The weird thing is that this occured multiple times over many hours. The oldest build is loading for 40:57 hours now, while the newest one is at 36:50 hours. So if it was just a hiccup - shouldn't *lots* of repos be affected by this?

**Comment by sannek** [comment]
Hm, that is weird indeed. We haven't gotten any other reports as far as I know, but I'm going to look into it, and will reopen the issue if I find anything / or feel free to reopen if someting goes wrong again!
