### ISSUE TITLE
MutationObserver is not working in jest

### ISSUE THREAD

**Issue by keiya01** [codesandbox/codesandbox-client#5074]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I have run test to try to check that MutationObserver is worked in My React Component. But test was failed and logs were outputted like the following.

```
Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
```

### To Reproduce

1. run test

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome v86.0.4240.111
| Operating System | Mac

**Comment by sannek** [comment]
Thanks for your report. I can reproduce your issue on my end. We'll look into it to see what's wrong and will update here!
