### ISSUE TITLE
React Fragment shorthand no longer works with react-scripts 4.0.0

### ISSUE THREAD

**Issue by lintonye** [codesandbox/codesandbox-client#5087]
# 🐛 bug report

## Preflight Checklist

- [ x ] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [ x ] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [ x ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

CodeSandbox reports "Unexpected token" for React fragment shorthand (`<>`). The project is created with CRA (react-scripts 4.0.0), and it runs fine locally.

## How has this issue affected you? What are you trying to accomplish?

The code should run without such error.

### To Reproduce

Try to open the sandbox: https://codesandbox.io/s/strange-glitter-dx08z

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/strange-glitter-dx08z

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System | macOS 10.15.6

**Comment by SaraVieira** [comment]
Hey

Seems we were still not tracking React scripts 4 so it would revert back to version 1

Just made a PR
