### ISSUE TITLE
react-script v3.3.0 works in csb but fails in local.

### ISSUE THREAD

**Issue by paritosh149** [codesandbox/codesandbox-client#5088]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Refer to React Template, I used 1-2 weeks ago, I found it working fine at csb. Today, I downloaded the project and ran locally. It failed with following error;
```TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined```

## How has this issue affected you? What are you trying to accomplish?
It did not work seemless. I wished it ran in similar way, based on package.json, locally or on csb.
### To Reproduce
Steps are: 
1. start on csb with React TypeScript Template.
2. Export as ZIP
3. Extract the files on local PC
4. Run ```npm install```
5. Run ```npm start```
6. In case not reproducable please fork [Github Repo](https://github.com/paritosh149/toy-robot-tsx)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox   |f4616bb72   |
| Browser          |MS Edge 86|
| Operating System |Win 10 Pro 64bit|

**Comment by paritosh149** [comment]
It worked in local after upgrading react-scripts to 3.4.3. Refer [StackOverflow](https://stackoverflow.com/questions/60234640/typeerror-err-invalid-arg-type-the-path-argument-must-be-of-type-string-re).

**Comment by SaraVieira** [comment]
Hey

I am gonna close this since it looks like an NPM fighting yarn and react scripts issue :(

We don't really build using NPM or yarn so that's why we don't have that issue.

Sorry for the problem, let me know if you want me to  keep it open

**Comment by paritosh149** [comment]
Thanks for the info. A side question; If not npm or yarn, how does csb build the source code?
