### ISSUE TITLE
Codesandbox preview shows blank

### ISSUE THREAD

**Issue by gelu89** [codesandbox/codesandbox-client#5094]
Ive searched all the internet and cant find anything. Im writing a code but i cant see the result in the browser and no erros are shown, the code works fine in my VSC app, cookies are not blocked and chrome is up to date
![Screenshot_67](https://user-images.githubusercontent.com/72707691/98436601-5f18ea00-20e5-11eb-9e99-6bdffb1d5978.png)

**Comment by BakuTempora** [comment]
I was here hopping 4 an answer... i have the same problem:(
