### ISSUE TITLE
File icons on tab not rendering correctly

### ISSUE THREAD

**Issue by jyash97** [codesandbox/codesandbox-client#5096]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Icon present in tab seems to be distorted
![image](https://user-images.githubusercontent.com/22376783/98442912-fb66df00-212d-11eb-8d18-8137ccfa4fb7.png)

### To Reproduce
Go to any sandbox and open/create any JS file.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 50accd694 |
| Browser          | Chrome v86.0.4240.183 |
| Operating System | macOS Catalina |

### Solution:

Looks like removing the `content` from below styles fixes the issue:

```
.show-file-icons .javascript-lang-file-icon.file-icon::before, .show-file-icons .js\.map-ext-file-icon.map-ext-file-icon.ext-file-icon.file-icon::before, .show-file-icons .es-ext-file-icon.ext-file-icon.file-icon::before, .show-file-icons .es5-ext-file-icon.ext-file-icon.file-icon::before, .show-file-icons .es7-ext-file-icon.ext-file-icon.file-icon::before {
    color: #cbcb41;
    content: '\E048';
}
```

Happy to create a PR if someone can confirm the issue & the proposed solution :)

**Comment by MichaelDeBoey** [comment]
JS icon looks normal to me (on 50accd6)
<img width="135" alt="Schermafbeelding 2020-11-07 om 17 34 51" src="https://user-images.githubusercontent.com/6643991/98446721-b5a31a00-211f-11eb-95c6-da99e029dd07.png">
<img width="126" alt="Schermafbeelding 2020-11-07 om 17 36 37" src="https://user-images.githubusercontent.com/6643991/98446733-d23f5200-211f-11eb-82fe-5c578f9edd67.png">

**Comment by jyash97** [comment]
Hmm, this is kind of weird. I tried to check other icons and all the icons look different, check below for ref:
![image](https://user-images.githubusercontent.com/22376783/98446911-1b56cc80-2147-11eb-8842-0df6e67b25a5.png)

Also, icons on the tab are messed up, file icons look correct

**Comment by MichaelDeBoey** [comment]
Maybe it's because of a browser extension?

**Comment by MichaelDeBoey** [comment]
@jyash97 does it work in incognito mode and in another browser?

**Comment by jyash97** [comment]
Hey @MichaelDeBoey 👋

I did check this on incognito and it works. Also, I cleared up local storage and on refresh the icons rendered correctly.

Though I noticed that the icons were fluctuating i.e different set of icons were rendered first and than the correct icons were rendered. You can verify this by opening any sandbox in incognito mode.

**Comment by SaraVieira** [comment]
Hey

We had this issue but it does seem to be fixed as @MichaelDeBoey said, about the jump there is not a lot we can do since we need to wait for the browser to load the file and then to tell VSCode what file that is :(

I am going to close this and hopefully one day we can have custom icons
