### ISSUE TITLE
import not working in parcel project

### ISSUE THREAD

**Issue by lake2** [codesandbox/codesandbox-client#5098]
see: https://codesandbox.io/s/vibrant-forest-17hr3?file=/index.js

**Comment by SaraVieira** [comment]
Hey!

We seem to have an issue with dynamic imports in that sandbox and will take a look tomorrow

On the meantime using require instead seems to work

https://codesandbox.io/s/vibrant-sun-p6nj8?file=/index.js

**Comment by lake2** [comment]
require("./index.js") seems not return a promise ?
single-spa need import("./index.js") return a promise，otherwise it will not work.

see : https://single-spa.js.org/error/?code=33&arg=app

**Comment by lake2** [comment]
> require("./index.js") seems not return a promise ?
> single-spa need import("./index.js") return a promise，otherwise it will not work.
> 
> see : https://single-spa.js.org/error/?code=33&arg=app

sorry about that, require("./index.js") return a promise , ()=>require("./index.js") do not return a promise.

**Comment by SaraVieira** [comment]
Will work on the underlying issue tomorrow
