### ISSUE TITLE
Git Data API error

### ISSUE THREAD

**Issue by kkh975** [codesandbox/codesandbox-client#5099]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Toast said:
![스크린샷 2020-11-09 오전 10 57 28](https://user-images.githubusercontent.com/1680132/98492176-5efe2300-227a-11eb-8a60-51f738f19e19.png)
"This API returns blobs up to 1 MB in size. The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size."

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by SaraVieira** [comment]
Hey!

Can you please follow the template and tell us how to reproduce this?
