### ISSUE TITLE
CORS failure when opening my sandboxes based on nuxt template

### ISSUE THREAD

**Issue by athrunsun** [codesandbox/codesandbox-client#5104]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Starting from yesterday, when I open [my sandbox based on nuxt template](https://codesandbox.io/s/vue-map-store-state-in-component-55xze), it reported "Error fetching sandbox".

![image](https://user-images.githubusercontent.com/1920454/98649242-5721aa00-2372-11eb-9028-7fe26a599563.png)

As shown in the above screenshot, I open my browser's developer tools, and I keep getting these CORS errors:

```
Access to XMLHttpRequest at 'https://55xze-lsp.sse.codesandbox.io/socket.io/?type=go-to-definition&EIO=3&transport=polling&t=NMnGxgJ' from origin 'https://codesandbox.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

```
GET https://55xze-lsp.sse.codesandbox.io/socket.io/?type=go-to-definition&EIO=3&transport=polling&t=NMnGxgJ net::ERR_FAILED
```

```
Access to XMLHttpRequest at 'https://55xze-lsp.sse.codesandbox.io/socket.io/?type=language-server&pid=0&EIO=3&transport=polling&t=NMnGyfb' from origin 'https://codesandbox.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

## How has this issue affected you? What are you trying to accomplish?
My sandbox is not usable at all.

### To Reproduce
Just open up the sandbox I provided.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |5778b26eb|
| Browser: Edge|86.0.622.63 64bit|
| Operating System: Windows 10|Version 2004 (OS Build 19041.572)|

**Comment by SaraVieira** [comment]
Hey!

Sorry for the issue, seems that this sandbox comes from a GitHub sandbox that has been forked a couple of times, and that repo got deleted and so what happens is the images are always linked to GitHub and since that image did not exist on Github anymore the sandbox wouldn't start and give you errors.

This is a bug, the sandbox should start anyway and give you a 404 on images but for now, I forked it and deleted the images and the sandbox is back up: https://codesandbox.io/s/vue-map-store-state-in-component-forked-g1idv?file=/README.md


I will for now close this and add this issue to our backlog

Thank you and again, sorry for the problem

**Comment by athrunsun** [comment]
@SaraVieira By saying "images", do you mean container images? Am I able to delete them myself?

**Comment by SaraVieira** [comment]
Yeah, anything that is an image, including the favicon.

Then I just reloaded the page and it worked

Let me know if it works for you

**Comment by athrunsun** [comment]
@SaraVieira Ah, we're talking about different things - I was referring to sth. like a docker image (which is used to create a docker container).

But never mind, I understand now. Thank you for your help!

**Comment by SaraVieira** [comment]
ohhh, valid point, can see how confusing that was, we do not have the ability to change the docker images so far

Glad it worked :)
