### ISSUE TITLE
codesandbox official website doesn't load

### ISSUE THREAD

**Issue by Enjoy2Live** [codesandbox/codesandbox-client#5105]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
the website doesn't load at all since 2 months now. I'm based in Saudi Arabia (in case this is going to help!)
## How has this issue affected you? What are you trying to accomplish?
I had some projects on codesandbox and I always use it and of course I want to access codesandbox normally again!
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | codesandbox.io
| Browser: Edge          | 88.0.685.3 (Official build) dev (64-bit)
| Operating System: Pop os | 20.10

**Comment by SaraVieira** [comment]
Hey!

What is your browser? Did you try in another one?

Or another isp

**Comment by Enjoy2Live** [comment]
I tried it in every browser and I don't think it's related to the browser it's about where I am located.

**Comment by SaraVieira** [comment]
Hey

I do not think this is on us tho, one of the things we use must have a restriction we do not know about and I am sorry.

Can you test opening this for me pls: https://codesandbox.stream/ or https://pr5102.build.csb.dev/s/new

Does it open?

**Comment by Enjoy2Live** [comment]
Yup they work just fine. Can I use them instead of the main one?

**Comment by SaraVieira** [comment]
Those ones don't have the production database or a way to sign in without accessing the production website to get a token :/

I'm sorry for the problem, we are trying to see if it could be cloudflare or something else we only use in production

**Comment by b3of** [comment]
I thought it's down everywhere! Same issue here..

Any updates?

**Comment by SaraVieira** [comment]
Hey

Sorry for the issue, are you also from Saudi arabia?

**Comment by b3of** [comment]
@SaraVieira Yes. I'm from Saudi Arabia

**Comment by SaraVieira** [comment]
Will keep digging, so far I can't really tell why this is happening

**Comment by garethx** [comment]
What error message do you see, if there is one, and can you also let us know which internet service provider you use? Thanks.

**Comment by b3of** [comment]
@garethx Common "This site can’t be reached" message.

Full message:

> This site can’t be reachedcodesandbox.io’s server IP address could not be found.
> Try:
> 
> Checking the connection
> Checking the proxy, firewall, and DNS configuration
> ERR_NAME_NOT_RESOLVED 


Internet service provider is STC

**Comment by garethx** [comment]
Thanks @b3of. Do you use STC too @Enjoy2Live ?

**Comment by Enjoy2Live** [comment]
hey @garethx , yes it's STC. for some reason the website doesn't load with fiber connection only. I tried it with all other connections and all ISPs (including STC!) and it works just fine. so issue only occurs on fiber connection!

**Comment by b3of** [comment]
@Enjoy2Live I tried it with 4G and still not loading, so, for me, it's not only fiber connection..

**Comment by garethx** [comment]
Thanks for the details here. What we have seen before are ISP-specific blocks, where they've blocked the whole domain due to phishing reports, and in some of those cases, rather than show a screen explaining they just let it error out. This might be the case here too, so I'll take a look and see if we've been mistakenly added to some blocklist.

Can you access https://new.csb.app/? I just want to make sure it's just codesandbox.io only.

**Comment by Enjoy2Live** [comment]
I see a blank page

**Comment by Enjoy2Live** [comment]
@garethx @SaraVieira the website works at this moment. just wanted to let you all know!

**Comment by SaraVieira** [comment]
That's awesome!

It must have been an ISP again, it happened it spain 😭

**Comment by Enjoy2Live** [comment]
the issue still persist, I started to believe that it's a lost cause!
thanks for your time and effort and hopefully this will get fixed soon :)

**Comment by adotnusiyan** [comment]
@SaraVieira @garethx This shouldn't be closed.
I still have the same issue. _from Saudi Arabia_

**Comment by TBuryanek** [comment]
Exactly same issue. Location Europe. Chrome, Edge, VPN on/off does not matter. Website cannot be open - ERR_TUNNEL_CONNECTION_FAILED

**Comment by kishoreandra** [comment]
The educational site, docs uses the codesandbox and they wont run when we are connected via BIG-IP Edge client or similar ones ... how do we go about this 😟

**Comment by CompuIves** [comment]
Hm, we shouldn't treat proxy/vpn differently 🤔. It's sometimes possible that a company, school or even ISP blocks *.csb.app. We often try to email the ISP to lift the ban, but we're dependent on the ISP to ultimately do this.

**Comment by kishoreandra** [comment]
> Hm, we shouldn't treat proxy/vpn differently 🤔. It's sometimes possible that a company, school or even ISP blocks *.csb.app. We often try to email the ISP to lift the ban, but we're dependent on the ISP to ultimately do this.

Thanks but if that is a company how do you go about it, or atleast an alternative 🥲😛 ... 

For this reason, atleast I'm trying to download and run the sandbox in local but had no luck 😵‍💫 .. [opened a new discussion here, indeed looking for help !!](https://github.com/codesandbox/codesandbox-client/discussions/8671#discussion-7627426)

your help is appreciated ☺️

**Comment by filipelima18** [comment]
@kishoreandra - In case you suspect that your company's firewall might be blocking one of our domains, you can try whitelisting the following domains: `codesandbox.io`, `*.csb.app`, `worker.codesandbox.io`.

**Comment by kishoreandra** [comment]
> @kishoreandra - In case you suspect that your company's firewall might be blocking one of our domains, you can try whitelisting the following domains: `codesandbox.io`, `*.csb.app`, `worker.codesandbox.io`.

Thanks for the suggestion @filipelima18, I will try that out .... do you have any idea on running the sandbox locally ? since this would help as workaround 😅
