### ISSUE TITLE
Devtools: CSS support

### ISSUE THREAD

**Issue by jyash97** [codesandbox/codesandbox-client#5118]
# 🌈 A better support for inspecting CSS

## What is the feature?
Develop an experience for inspecting styles.

## Alternative solution 
Currently, there is no in-house tool to inspect CSS for an element, the only way to inspect the styles is to right-click on the iframe and inspect the element which opens the native Devtools. I have been doing this for a long time and the experience is a bit laggy because there are many DOM elements [ CodeSandbox UI ] and the elements present in iframe [user sandbox] which makes the inspecting slow and difficult.

## How the feature should work? 

We can have a toggle option at the right side of the URL bar in preview to toggle CSS Inspector and here are 2 implementations that I can think of: 

1. Show the styles in the preview itself on a tooltip. Ref: https://www.producthunt.com/posts/css-scan-2-0
2. Create a CSS Inspector tab in dev tools and show the styles for the selected element there.

## Implementation

We can make use of `document.stylesheets` which have all the rules and applied properties present which can be helpful to find all the selectors applied to a particular element. 
____
If this sounds good I would love to help on making these experience live :)

**Comment by SaraVieira** [comment]
Hey

This is definitely an amazing idea!

It would have to be thought on how to implement it because honestly, I don't have a clear idea how

**Comment by Explosion-Scratch** [comment]
> It would have to be thought on how to implement it because honestly, I don't have a clear idea how

What if if highlighted the styles associated with in in the CSS that the user was currently viewing? E.g. an eyedropper at the side of the preview pane or somewhere that would allow you to select elements, and then it would jump to the place in the current file where that element was, if it was CSS it could jump to the style that related to this. Possible cons of this include if the user did something like ```* { padding: 0; } ``` then that would apply to everything so it may jump there.

**Comment by Explosion-Scratch** [comment]
Wait, am I understanding this correctly? Do you do something in the CSS file which highlights the element it applies to or do you select an element in the HTML and it'll show the CSS that applies to it?

**Comment by SaraVieira** [comment]
oh sorry, I meant how to check what css is applied ahah

So it would be the second one.

Also apparently this idea was already in our backlog :D

I will be closing but to make sure what we have in GitHub is just issues and all our feature requests are tracked in our roadmap.

We will definitely make an announcement when this is done
