### ISSUE TITLE
MJS files not served with correct MIME

### ISSUE THREAD

**Issue by 00ff0000red** [codesandbox/codesandbox-client#5122]
# 🐛 bug report

## Preflight Checklist

- [ x ] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [ x ] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [ x ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Module JavaScript files (.mjs) are not served properly through the server.

## How has this issue affected you? What are you trying to accomplish?

This prevented the execution of any attached ECMAScript on a web page.

### To Reproduce

Create an .mjs file, attempt to view the file.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Website
| Browser          | Google Chrome 86
| Operating System | ChromeOS

**Comment by sannek** [comment]
Hi, 
Thanks for your comment. I can reproduce your issue, but am not yet sure exactly what causes it and how I can fix it. We're investigating, and will get back to you on this.

**Comment by sannek** [comment]
I just deployed a fix for this, so your `.mjs` files should now execute normally. Let me know if you have any further problems.

**Comment by 00ff0000red** [comment]
> I just deployed a fix for this, so your `.mjs` files should now execute normally. Let me know if you have any further problems.

Awesome, great to hear!

Works flawlessly, thank you for the quick response.
