### ISSUE TITLE
Error: You gave us a visitor for the node type StaticBlock but it's not a valid type

### ISSUE THREAD

**Issue by deadcoder0904** [codesandbox/codesandbox-client#5131]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I just tried opening https://github.com/tailwindlabs/blog.tailwindcss.com on Codesandbox by using `githubbox`.

I have updated the dependencies & 1 file `_document.js` a little bit as Next.js had some breaking changes. I also changed some layout (mostly CSS)

## How has this issue affected you? What are you trying to accomplish?

It doesn't run the repo & gives weird errors. I can't figure out what the error is.

### To Reproduce

Clone the Tailwind Blog repo & update the dependencies & see the error or just click the link to my sandbox to see it crashing.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Idk where to find it
| Browser          | Version 86.0.4240.193 (Official Build) (x86_64)
| Operating System | Mac OS Catalina 10.15.7 (19H15)

**Comment by deadcoder0904** [comment]
Forgot to write the error that I get in the terminal

```bash
event - build page: /next/dist/pages/_error
wait  - compiling...
error - ./node_modules/next/dist/client/next-dev.js
Error: You gave us a visitor for the node type StaticBlock but it's not a valid type
{ Error: Cannot find module '/sandbox/.next/server/pages-manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at getPagePath (/sandbox/node_modules/next/dist/next-server/server/require.js:1:657)
    at requirePage (/sandbox/node_modules/next/dist/next-server/server/require.js:1:1062)
    at loadComponents (/sandbox/node_modules/next/dist/next-server/server/load-components.js:1:807)
    at DevServer.findPageComponents (/sandbox/node_modules/next/dist/next-server/server/next-server.js:72:296)
    at DevServer.renderErrorToHTML (/sandbox/node_modules/next/dist/next-server/server/next-server.js:128:120)
    at DevServer.renderErrorToHTML (/sandbox/node_modules/next/dist/server/next-dev-server.js:34:974) code: 'MODULE_NOT_FOUND' }
error - ./node_modules/next/dist/client/next-dev.js
Error: You gave us a visitor for the node type StaticBlock but it's not a valid type
```

which is unreadable to me 🙈

**Comment by SaraVieira** [comment]
Hey!

I forked it and it seems to work now :/

https://codesandbox.io/s/magical-currying-nrg53

I think by changing these things next may have needed to have the server restarted to see the new files can you please try to restart the sandbox and/or server here and see if it start returning the actual values?
![Screenshot 2020-11-14 215549](https://user-images.githubusercontent.com/1051509/99157798-8d418f80-26cc-11eb-9ca9-bbd46d8bdcd3.png)

Thank you

**Comment by deadcoder0904** [comment]
Hey Sara, I tried to `Restart Sandbox/Server` option on my Codesandbox but it didn't work.

But I forked yours & it works fine so I'll close this for now.
