### ISSUE TITLE
Add Docusaurus to official templates

### ISSUE THREAD

**Issue by slorber** [codesandbox/codesandbox-client#5135]
# 🌈 Feature

Hi,

As proposed by @Saeris [here](https://github.com/facebook/docusaurus/issues/1699), we created an official codesandbox template for Docusaurus.

It seems we can ask to get it added to the official template list, so I'm asking here :) 

We have multiple example folders, but the primary one should be: https://github.com/facebook/docusaurus/tree/master/examples/classic

We commit to maintaining this folder up to date over time, and have semi-automated the process to regenerate the example folder from our init cli.

I'll also see if we can have a docusaurus.new domain

Let me know what's the process and if I can do anything to make this happen

**Comment by SaraVieira** [comment]
Hey!

Thank you so much for making this template, just made a PR to create a new template for Docusaurus, it was easier than usual since we already had the icon :D

We still need a bit of work on the backend but should not be long :)

**Comment by slorber** [comment]
Hi

Great, thanks, will subscribe to the PR to know when it's ready then :)

**Comment by sammychinedu2ky** [comment]
Awesome. So I guess I would have to wait till it's ready before I document. Since I would be making reference to the official template in codesandbox

**Comment by slorber** [comment]
yes @sammychinedu2ky , let's wait until it's merged :) but you can already think where we should document it

**Comment by sammychinedu2ky** [comment]
Sure would do that🤠

**Comment by slorber** [comment]
Hi @SaraVieira 

Was wondering, after this PR is merged, do we get a dedicated codesandbox url or something?

We are going to document this, and probably create a domain redirecting. to this codesandbox, maybe like `playground.docusaurus.io` or `docusaurus.new` or something else. Wonder if you have advice on how to do so? How  others like React did this?

**Comment by SaraVieira** [comment]
👋 

Yes, you do! When we get this merged you get a link that is the starter template for docusaurus :)

About the links they were actually set by us, we bought the domains and just set up a redirect to certain sandboxes

**Comment by sammychinedu2ky** [comment]
Okay cool. Please any idea about when it would be merged?

**Comment by SaraVieira** [comment]
I will try to get it merged this week but I can't really make any promises since it also needs API work :(

**Comment by sammychinedu2ky** [comment]
Alright thanks a lot I appreciate. I'll be waiting

**Comment by slorber** [comment]
Thanks

So we'll do the same and just put a _redirects file on Netlify :)

**Comment by sammychinedu2ky** [comment]
Hello good evening, please is there any update on the pull request so that we can commence with documentation. We have been waiting.
