### ISSUE TITLE
Sandbox linked to subdirectory in GitHub repo doesn't deal well with conflicts

### ISSUE THREAD

**Issue by stefandesu** [codesandbox/codesandbox-client#5141]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I have imported a sandbox from a subfolder of a GitHub repository and linked the sandbox to that subfolder. Commits work perfectly well. However, when there were changes in the root of the repository (i.e. unrelated to the sandbox), and I tried to push my changes from the sandbox to GitHub without pulling on CodeSandbox, weird conflicts were shown with the files in the root folder that had nothing to do with the sandbox. Not sure if this would have happened if I knew there were changes in the repo and pulled them beforehand.

## How has this issue affected you? What are you trying to accomplish?

It caused weird merge conflicts and added files from the root of the repo to the sandbox which I had to remove before I could commit my actual changes.

### To Reproduce

I would say:
- Create a GitHub repo with a subfolder
- Create a new sandbox from that subfolder, link the sandbox to that subfolder
- Make some changes in the sandbox, but also commit changes to some file in the root folder of the repo outside of the sandbox
- Try to commit the changes on CodeSandbox

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | website
| Browser          | Safari 14.0.1
| Operating System | macOS 10.14.6

**Comment by SaraVieira** [comment]
Hey

Thank you so much for your report, I can definitely reproduce this with this test repo: https://github.com/SaraVieira/csb-test/tree/main/csb-test-main

Will take a look at this but can't really give you a time frame of when this will be fixed since I never really touched this part of the code

**Comment by stefandesu** [comment]
Thanks for looking into it!

I just encountered a (probably) related issue: I changed files inside the linked subfolder, but CodeSandbox did not update those files, but instead showed them as conflicts as if it was a subfolder inside the subfolder. I said to delete those files (because they don't exist), was able to make a commit to a different file, and now it shows the other files as changed inside CodeSandbox because it still has the old versions and didn't update from the new versions on GitHub.

Looks like it isn't feasible to work with this until it is fixed, except if you exclusively commit via CodeSandbox.

**Comment by SaraVieira** [comment]
Yeah, it's probably the same issue, seems like something we missed when making the integration

It has a lot of ironing to be done and a lot that has already been done, we hope one day to just use git instead of the GitHub API to clear these small inconsistencies.

These two should be fixed at the same time, sorry for the issues, I understand how it can be frustrating

**Comment by codebryo** [comment]
@JensDll thanks for the ping on this -- we work on some git importer updates at the moment. I'll take this as a data point to look into as well if we can make improvements there. Thanks.

**Comment by gpichot** [comment]
Hi @codebryo,
Any update on this one? The same issue as @JensDll happened to me today.
Best,
Gabriel
