### ISSUE TITLE
Sandbox based on Vue repo linked to GitHub repo shows constant changes in /public/favicon.ico

### ISSUE THREAD

**Issue by stefandesu** [codesandbox/codesandbox-client#5142]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I have a Vue.js demo project linked to a subfolder in a GitHub repo. On CodeSandbox, `/public/favicon.ico` is constantly shown as a changed file. If I commit the file, it will create an empty commit (see https://github.com/gbv/coli-conc-examples/commit/59838facdd6064def4af92bbce15236077be5970).

## How has this issue affected you? What are you trying to accomplish?

It's just slightly annoying to have the file constantly shown as changed. Not a big deal though because if you commit actual changes, the commit won't include the file.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | website
| Browser          | Safari 14.0.1
| Operating System | macOS 10.14.6

**Comment by SaraVieira** [comment]
Seems related to https://github.com/codesandbox/codesandbox-client/issues/4504


We are still working on improving how were deal with images on GH repos
