### ISSUE TITLE
Save VSCode settings (And user snippets!) on CSB's server.

### ISSUE THREAD

**Issue by Explosion-Scratch** [codesandbox/codesandbox-client#5145]
# 🌈 Feature/Bug
## The Bug
Currently after closing Codesandbox or clearing the cache, the user snippets and VSCode settings are cleared. This is a particularly annoying bug, this means that I have a JSON file in a sandbox where I store my VSCode settings.

The fact this doesn't exist makes things like snippets almost useless

## The solution
Save settings.json and user snippets server side.

**Comment by Explosion-Scratch** [comment]
This also means user snippets are useless.

**Comment by SaraVieira** [comment]
Hey!

Our idea was to use the same idea as VSCode as in to default your setup every time you use a new computer but we have been getting a lot of requests over this and it is a good feature request.

I added it to our backlog and will write a scope and tech specs for it to be implemented, can't really give you a time frame but it is something we will implement.


If you have any ideas over implementation details, let me know, my main idea would be to do something like VSCode settings sync, where you could sync your settings.



As we are trying to use our backlog for features and GitHub for issues I am going to close this but it is added to our internal backlog in Notion

Thank you

**Comment by Explosion-Scratch** [comment]
Sounds good! I think that a VSCode settings sync type thing would be great but probably very complicated, especially because in VSCode you can choose what to sync, maybe just a tick mark in settings to sync/not everything.

**Comment by SaraVieira** [comment]
I was mostly thinking of the fact in VSCode you can choose when to sync and I think that is the best approach because you may not want to sync a random computer and this way you can always make changes and revert if you do something you don't like
