### ISSUE TITLE
Ability to download build folder from react sandboxes (for use in localhost, etc.)

### ISSUE THREAD

**Issue by jsejcksn** [codesandbox/codesandbox-client#5146]
# 🌈 Feature

[Related discussion](https://github.com/codesandbox/codesandbox-client/discussions/5133)

This is a request to support exporting (downloading) the build folder from a react sandbox after doing the vanilla react-scripts build script.

Basically, I'm looking for "Deploy to localhost" (and "Deploy to GitHub pages" would also be a great option).

Since CodeSandbox is already building my project in the browser, it is a huge pain to have to:

- download the sandbox zip
- decompress the sandbox zip
- install node and npm
- install all the npm deps in package.json
- run the react scripts build script

just to get a static site bundle for use on my `localhost` server.

All of this functionality is already in the CodeSandbox client, but just needs to be exposed.

I haven't thoroughly researched it, but I think you'd just need to support the `.env` file with the "[advanced configuration](https://create-react-app.dev/docs/advanced-configuration/)" options and [the `homepage` property](https://create-react-app.dev/docs/deployment#building-for-relative-paths) in `package.json` when exporting with this option.

**Comment by siddharthkp** [comment]
I like the feature request, especially deploying to GitHub pages.

> Since CodeSandbox is already building my project in the browser

This is where it gets tricky 😅 CodeSandbox doesn't use webpack to build the project on the client side, it uses a dev bundler (sandpack) which is only useful for development environments not a deploy-ready build. To deploy the app, you'd still have to run `react-scripts build`.

If you're curious, here's a [talk about development bundlers](https://www.youtube.com/watch?v=Yu9zcJJ4Uz0&t=36s&ab_channel=ReactEurope) that Ives gave recently.

To deploy to GitHub pages, I imagine we'd have to build it on a server and then commit it to GitHub (similar to what you would do with GitHub actions today - here's [an example](https://github.com/marketplace/actions/deploy-react-app-to-github-pages)) 

I have added the `Deploy to GitHub pages` as a feature request to our internal backlog which we use to prioritize what to build next. We can't make any promises about the timing, but it's on the list!

Hope that helps!

**Comment by jsejcksn** [comment]
@siddharthkp Thanks for taking time to explain some of the process.

> I have added the `Deploy to GitHub pages` as a feature request to our internal backlog

That's secondary to the request for a build option for `localhost`.

**Comment by siddharthkp** [comment]
> That's secondary to the request for a build option for localhost.

Yep, similar process for a downloadable build as well - It will have to be built with `react-scripts` on the server because the client build doesn't exist as a downloadable

**Comment by jsejcksn** [comment]
@siddharthkp Will you share some sort of backlog identifier here for the item corresponding to the `localhost`-related export so that I can reference it in the future if needed?

**Comment by siddharthkp** [comment]
this issue id is the best identifier

(we don't use jira/Trello, so I don't have a different generated id for you)

**Comment by siddharthkp** [comment]
Tracking internally 👍
