### ISSUE TITLE
ModuleNotFoundError on sandbox start but once I fork the sandbox it works again

### ISSUE THREAD

**Issue by derberg** [codesandbox/codesandbox-client#5149]
# 🐛 bug report

## Preflight Checklist

- [x ] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x ] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

When I run [this](https://codesandbox.io/s/asyncapi-react-component-in-action-forked-53d6s) sandbox, I get error 
```
ModuleNotFoundError
Could not find module in path: '@jsdevtools/ono/esm/isomorphic.node' relative to '/node_modules/@jsdevtools/ono/esm/extend-error.js'
```

- When I use it locally, it works fine
- When I fork it, it works fine
- When I refresh the page on a forked sandbox, it stops working again 🤦 

It just doesn't make sense to me and have no idea how to even investigate it. 

## How has this issue affected you? What are you trying to accomplish?

I basically cannot share the sandbox with others. I have to tell them, that they have to make some modification inside (add new line) and save, so they will create their own copy that will work 😞 

### To Reproduce

Just do what I described above:
1. Access the [link](https://codesandbox.io/s/asyncapi-react-component-in-action-forked-53d6s) -> you see error
2. Make a change in js file -> you see it works
3. Refresh the page -> fails again

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | https://codesandbox.io |
| Browser | Firefox 82.0.2 (64-bit) |
| OS | macOS Catalina 10.15.7 |

**Comment by SaraVieira** [comment]
Hey!

We just pushed a fix for this 🎉 

You will probably still have cache, you can clear everything but you can also test in an incognito window and see it always loads now

**Comment by derberg** [comment]
That was super fast, thanks a bunch, works lika a charm
