### ISSUE TITLE
Using NPM Workspaces with Codesandbox CI.

### ISSUE THREAD

**Issue by jansiegel** [codesandbox/codesandbox-client#5150]
# 🌈 Feature

Is there a possibility to use `npm` instead of `yarn` in Codesandbox CI? Specifically, I'm thinking of `npm@7` and its `workspaces`.
Currently, when deploying a project with the `workspaces` key in `package.json`, CI recognizes it as a `yarn workspaces`-enabled project, and:
1) forces the main `package.json` to be `private`, by throwing an error: `Workspaces can only be enabled in private projects.`
2) installs dependencies using `yarn`'s logic, which can diverge from `npm`'s logic, resulting in a different build.

Is it/will it be supported? Thanks!

**Comment by CompuIves** [comment]
Hey! We automatically use `npm` if we detect a `package-lock.json`, but I'm not sure which version of npm is still installed on CI. Do you know this @lbogdan?

**Comment by jansiegel** [comment]
>We automatically use `npm` if we detect a `package-lock.json`

Oh, that'd make sense, I was testing it on a fresh, simplified repo, with no `package-lock`. That's great news, thanks!

**Comment by SaraVieira** [comment]
Awesome! Going to close this as that seemed to be the issue :)
