### ISSUE TITLE
TypeScript cannot import scoped packages containing types

### ISSUE THREAD

**Issue by nfarina** [codesandbox/codesandbox-client#5154]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

It appears that the TypeScript Language Server can't handle importing "scoped packages".

## How has this issue affected you? What are you trying to accomplish?

I'm unable to get completion with imported scoped packages that contain types, even though the project builds fine.

### To Reproduce

I created a new TypeScript React sandbox using the provided template, then added `@angular/core` as a dependency. (I've tried with other scoped packages as well). Importing anything from `@angular/core` shows the following errors in the VSCode-based editor, and language completion doesn't work:

<img width="751" alt="Screen Shot 2020-11-18 at 2 56 52 PM" src="https://user-images.githubusercontent.com/117280/99598414-5611fd80-29ae-11eb-971b-967aae46d1bc.png">

Note that running `codesandbox-client` locally does not exhibit this problem, nor does downloading the project as a ZIP and running it in VSCode directly.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | c937e63ed
| Browser          | Chrome 86
| Operating System | MacOS Catalina

**Comment by SaraVieira** [comment]
Hey!

I am not getting that error anymore, it must have been a cache issue with the type fetcher resolver we use to get the types.

Seeing as it's not an issue I will close for now but keep following this issue, please let me know any  if this surfaces again

**Comment by nfarina** [comment]
Yep it seems to have fixed itself. Thanks!
