### ISSUE TITLE
window.localStorage is null

### ISSUE THREAD

**Issue by donavon** [codesandbox/codesandbox-client#5157]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
When I run this app in the IDE window, `localStorage` is `null. When I run it in its own window, it is properly set.

## How has this issue affected you? What are you trying to accomplish?

I'm deeply hurt by this.

### To Reproduce

Run this sandbox and it will display `localStorage is null`
https://codesandbox.io/s/wonderful-hawking-8ql3h?file=/src/index.js

Run it here and it will display `localStorage is [object Storage]`
https://8ql3h.csb.app/

### Link to sandbox: [link]() (optional)

see above

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  c937e63ed |
| Browser          | Brave Version 1.16.76 Chromium: 86.0.4240.198 (Official Build) (x86_64) |
| Operating System | macOS Big Sur 11.0.1 |

**Comment by donavon** [comment]
More info...

It turns out this only happens with Brave if the shields are up.

![image](https://user-images.githubusercontent.com/887639/99733679-87162f00-2a8f-11eb-8524-6d9eaf479127.png)

Brave is reporting this:

![image](https://user-images.githubusercontent.com/887639/99733741-a1e8a380-2a8f-11eb-895b-4d22cd6490ae.png)

As a workaround, I will just lower the shields when using CodeSandbox.

**Comment by SaraVieira** [comment]
Hey!

So, they block local storage and literally everything, I had this issue a while ago where I had to fix the complete website in brave because their shields blocked it and we had no storage to save the cache of our bundler:

https://github.com/codesandbox/codesandbox-client/pull/5102

There is really not a lot we can do here unfortunately because probably saying: "This is because you got your shields up on brave would be kinda creepy"

Sorry about the issue :(

Mind if I close it?

**Comment by SaraVieira** [comment]
What's weird is that I always use codesandbox with uBlock that also blocks those two scripts and it has no effect so they block waaay more than just that

**Comment by donavon** [comment]
After I discovered that the shields were cause it, I didn't think there was much you could do. Not at least it's documented for the future. Closing.

**Comment by SaraVieira** [comment]
yap! Thank you again for making the issue 👍
