### ISSUE TITLE
Alt clicking corner clicks instead of opening links

### ISSUE THREAD

**Issue by Explosion-Scratch** [codesandbox/codesandbox-client#5166]
# 🐛 Alt alt clicking has the same effect as corner clicking when opening links in code.

## Description of the problem

In multi-cursor editing there is an option to use control click to add a cursor. Then, links in code say to 'Alt + Click to follow link' but alt clicking them corner clicks. This does not happen when alt is used as the multi cursor modifier as control clicking follows the links. 

## How has this issue affected you? What are you trying to accomplish?

I'm trying to follow the link.

### To Reproduce

1. Go into VSCode settings and change the multicursor modifier key to control/command
2. Hover over a link, it'll say this:
![image](https://user-images.githubusercontent.com/61319150/99885768-ed6c9000-2bfc-11eb-8692-42ae7d11edbc.png)
3. Alt click on it and it'll do this:
![image](https://user-images.githubusercontent.com/61319150/99885798-0aa15e80-2bfd-11eb-9e9c-5523bd911a9b.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest |
| Browser          | Chrome |
| Operating System | ChromeOS |

**Comment by SaraVieira** [comment]
Hey!

This is a problem with the version of VSCode we are using and we need to update it and this will be fixed along with a bunch of different things about VSCode.

This is already in our backlog to update :)

I also tried and could not replicate, might be an issue in ChromeOS

**Comment by Explosion-Scratch** [comment]
Hmm. That's wierd. I tried on a mac and it also did not happen. It must be with ChromeOS.

**Comment by SaraVieira** [comment]
yeah, I had a chromebook and found a LOT of issues where from ChromeOS :/
