### ISSUE TITLE
I cant log in anymore with my Git after accidently creating a google account. 

### ISSUE THREAD

**Issue by Lumenw** [codesandbox/codesandbox-client#5167]
Last week I quickly had to check something on CodeSandBox and because I didn't know my git password on top of my head I decided to just make a quick Google account since it only takes 1 minute. The issue I'm having now Is that CodeSandBox won't let me enter anymore with my Git so now I can't access my own files anymore. 

Is this fixable?

**Comment by SaraVieira** [comment]
Hey!

Can you please email us all the info at hello@codesandbox.io?

It's easier to fix these delicate things from there
