### ISSUE TITLE
Repo works locally, has NPM package errors in CodeSandbox web client

### ISSUE THREAD

**Issue by mattfelten** [codesandbox/codesandbox-client#5177]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I'm getting an error with one of our projects being imported into CodeSandbox. An error appears about `react-transition-group` which has [a number](https://github.com/react-bootstrap/dom-helpers/issues/51) [of issues](https://github.com/reactjs/react-transition-group/issues/556) around. I'm trying to debug that which is where this issue comes up.

My issue is that I pulled a CodeSandbox down, and it runs completely fine locally. `npm start` and `npm run build` work perfectly. I turned it into a GitHub repo and imported back into CodeSandbox, the error appears again. I have no idea what's different about the project besides it being in the CodeSandbox client.

This was originally a [Discussion](https://github.com/codesandbox/codesandbox-client/discussions/5172#discussioncomment-137338) but @SaraVieira asked me to make an Issue.

### To Reproduce

GitHub Repo: https://github.com/mattfelten/2dde3

### Link to sandbox: [link]() (optional)

CodeSandbox: https://codesandbox.io/s/github/mattfelten/2dde3

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Safari/latest Chrome/latest |
| Operating System | MacOS Big Sur

**Comment by SaraVieira** [comment]
👋 

Thank you so much for making an issue

This helps us keep things clean. I will take a look to see what is wrong with @CompuIves
