### ISSUE TITLE
Settings save successfully, but upon reload, dangling commas are added so they can't be loaded properly...

### ISSUE THREAD

**Issue by kentcdodds** [codesandbox/codesandbox-client#5183]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

In the file tabs, I see a Jenkins icon instead of the JS icon:

![image](https://user-images.githubusercontent.com/1500684/100235448-ad9df500-2ee9-11eb-9183-d7c31e7d20a2.png)

It's a correct icon in the file explorer though:

![image](https://user-images.githubusercontent.com/1500684/100235519-c4dce280-2ee9-11eb-94a3-08567739dea1.png)

## How has this issue affected you? What are you trying to accomplish?

I want it to look correct.

### To Reproduce

Open a codesandbox js file and look at the tabs. Not sure if others notice this or if I'm just special

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 24441de1e
| Browser          | Chrome
| Operating System | macOS

**Comment by kentcdodds** [comment]
Ah, I've fixed this!

I had a dangling comma in my editor settings (something VSCode supports but not codesandbox apparently?)

After fixing that, the problem went away!

Maybe this issue could be changed to support comments and commas like vscode does?

**Comment by kentcdodds** [comment]
Hmmm.... Actually, when I save the file with valid JSON, then refresh, the settings are wrong (it looks like I'm getting default settings) (also, I see the Jenkins icon). If I go to the settings, then dangling commas were *added* 🤔

**Comment by kentcdodds** [comment]
I've verified there are no error messages when I save... I'm retitling this issue.

**Comment by gabrielsanttana** [comment]
I'd like to join this conversation, since I've also noticed this issue a few times, but didn't realized it was actually a bug.

In my case, I simply created JS files in the client and they just appeared with the Jenkins icon on the file tab:

![image](https://user-images.githubusercontent.com/47339825/100238626-33806700-2f0f-11eb-9ecc-a87231e96bee.png)

![image](https://user-images.githubusercontent.com/47339825/100238670-3d09cf00-2f0f-11eb-97f0-3efd448c44a6.png)

**Comment by jyash97** [comment]
Maybe these thread helps with the icon issues: #5096

**Comment by gabrielsanttana** [comment]
@github-actions, apparently it has been fixed.
