### ISSUE TITLE
Duplicate folders are created in Explorer in Node Template 

### ISSUE THREAD

**Issue by saurabhdaware** [codesandbox/codesandbox-client#5188]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success. (I see #1455 which is closed now and I'm not sure if the issue is same)

## Description of the problem

![3 folders with name .debug](https://user-images.githubusercontent.com/30949385/100372817-d29c8000-302f-11eb-8e97-5d2a3b2343b2.png)

In my node-based static-site-generator, I build site in `.debug` folder while running dev-server. Before building it checks if .debug folder is present, deletes it, and then creates a new .debug folder to write files into. 

However on CodeSandbox sometimes I end up getting multiple `.debug` folders.

### To Reproduce

I am not really sure how to reproduce this as this has been very random.

You can try to edit something in this template, then save it, refresh the page or go back and forth a few times, and then edit something again. 
https://codesandbox.io/s/abell-scss-dcw2m?file=/theme/home.scss

The multiple folders are later cleared when I refresh the page again.

### Link to sandbox: [link]() (optional)

Mentioned above

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 
| Browser          | Firefox and Chrome
| Operating System | Ubuntu

**Comment by SaraVieira** [comment]
yeah, this seems like the issue we sometimes get on VSCode of not recognizing, we should refresh the explorer more often on server sandboxes :/
