### ISSUE TITLE
Module not found error when using TypeScript vanilla sandbox with a project that includes d.ts definitions

### ISSUE THREAD

**Issue by KrofDrakula** [codesandbox/codesandbox-client#5191]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Adding an NPM package to the default Vanilla TypeScript sandbox template and using it via `import` with an absolute path results in a compilation error in the editor:

`Cannot find module 'parzec' or its corresponding type declarations.ts(2307)`

When running the preview, however, you can still use the imported code and the console logs the object correctly. Even when the package contains `.d.ts` type declarations (which the `parzec` library in the example does), it still doesn't pick up types from it and shows errors.

## How has this issue affected you? What are you trying to accomplish?

In local projects, VSCode correctly picks up types from the library, but Codesandbox's editor seems to have trouble resolving either the package or the types, which results in the error shown in the editor and Intellisense not picking up any type information from imports

### To Reproduce

I've set a minimal reproduction in this project, along with proof that the exports are actually present, just the editor isn't picking them up. The object is written to HTML for illustration purposes.

### Link to sandbox: [link]() (optional)

[wandering-paper-hkxjc](https://codesandbox.io/s/wandering-paper-hkxjc?file=/src/index.ts)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Production version of codesandbox.io |
| Browser          | Chrome 86.0.4240.198 |
| Operating System | Windows 10 64-bit |

**Comment by SaraVieira** [comment]
Hey

Thank you for the issue, this seems to be an issue with out type fetcher, @CompuIves can you confirm?

**Comment by SaraVieira** [comment]
Just going back to this and it seems to be fixed. Let me know if it happens again
