### ISSUE TITLE
Setting a light custom theme does not work properly

### ISSUE THREAD

**Issue by pahund** [codesandbox/codesandbox-client#5193]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem / steps to reproduce

I would like to customize the provided color theme “Quiet Light”. For this purpose, I've gone through the following steps:

* Executed the command “Developer: Generate Color Scheme From Current Settings”

![image](https://user-images.githubusercontent.com/1639313/100591727-715a0280-32f6-11eb-94c9-7451a5265c9b.png)

* Copied the resulting code into the “Custom VS Code Theme” text box in Preferences → CodeSandbox Settings → Appearance

![image](https://user-images.githubusercontent.com/1639313/100591826-977fa280-32f6-11eb-9a95-55a4890abddb.png)

* Reloaded CodeSandbox in the browser
* Selected the color theme “Custom Theme”

At this point, I would expect the UI of CodeSandbox to look the same as before, since all I did was copy the preset color theme to a custom theme.

**However** the colors of the menus, file explorer, etc. all have light text on light background now, making them unusable.

![image](https://user-images.githubusercontent.com/1639313/100592406-589e1c80-32f7-11eb-9854-907fb8ff33a3.png)

I suspect this is because CodeSandbox ignores the fact that this is a light theme and interprets it as a dark theme instead, thus rendering the text of the menus in light colors.

The fact that “Custom Theme” is listed under dark themes is strong evidence for this:

![image](https://user-images.githubusercontent.com/1639313/100592541-86836100-32f7-11eb-9f01-4ac032d0a5a3.png)

## How has this issue affected you? What are you trying to accomplish?

I cannot customize the existing light color themes to my liking, nor can I use any other light theme copied over from VS Code.

**Comment by SaraVieira** [comment]
Hey!

Can you send me the theme pls?

**Comment by SaraVieira** [comment]
Nevermind, you said the name, working on this now

**Comment by SaraVieira** [comment]
That was EXACLY the issue, making a PR now

**Comment by pahund** [comment]
Awesome, I can confirm that it works now! Thank you for the great work, I love CodeSandbox!

**Comment by SaraVieira** [comment]
Awesome! You are very welcome, sorry we are all dark theme users ahah
