### ISSUE TITLE
Dynamic import(URL.createObjectURL(blob)) does not work

### ISSUE THREAD

**Issue by heri16** [codesandbox/codesandbox-client#5208]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Dynamic import does not work.

```
DependencyNotFoundError
Could not find dependency: 'blob:https:' relative to '/src/App.js'
```

## How has this issue affected you? What are you trying to accomplish?

I'm trying to dynamically import a js module from a blob.

### To Reproduce

```js
const code = `
export default function Component() {
}
`

const file = new File([code], "component.js", {
    type: "application/javascript",
})

const url = URL.createObjectURL(file)

import(url).then(component => {
  console.log(new Component())
})
```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest |
| Browser          | Chrome |
| Operating System | Manjaro Rolling |

**Comment by nickscamara** [comment]
Can we reopen this issue? I'm having the same issue with dynamic imports in a npm package.

**Comment by mojojoji** [comment]
@nickscamara Can you provide more details about the issue. Is the steps to reproduce same as the original post?
