### ISSUE TITLE
Error: ENOENT: No such file or directory., '/url'

### ISSUE THREAD

**Issue by ben-rogerson** [codesandbox/codesandbox-client#5216]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Description of the problem

I'm experiencing an error when loading some of my sandboxes and they work fine locally.

```js
Error: ENOENT: No such file or directory., '/url'
```

I'm a package author that uses CodeSandbox to show examples and I'm getting reports that it's not working.

### Link to sandbox: [react-emotion](https://codesandbox.io/embed/github/ben-rogerson/twin.examples/tree/master/react-emotion?file=/src/App.js) / [cra-styled-components](https://codesandbox.io/embed/github/ben-rogerson/twin.examples/tree/master/cra-styled-components?file=/src/App.js)

**Comment by ben-rogerson** [comment]
Fixed-  it due to the missing tailwindcss dependency

**Comment by ben-rogerson** [comment]
Hey folks, I'm seeing this error pop up again on most of my sandboxes. 
I'm not sure how to fix it - could you please take a quick look at why this error is displayed?

Thanks!

**Comment by ben-rogerson** [comment]
I'd really like to use codesandbox again to show twin.macro - can I get a fix/workaround for the error displaying on my sandboxes?

`Could not find path: 'twin.macro'.`

I'm guessing the above error is because twin.macro is a devDependency?

[react-emotion](https://codesandbox.io/embed/github/ben-rogerson/twin.examples/tree/master/react-emotion?file=/src/App.js) / [cra-styled-components](https://codesandbox.io/embed/github/ben-rogerson/twin.examples/tree/master/cra-styled-components?file=/src/App.js)

**Comment by lbogdan** [comment]
Hey @ben-rogerson ,

Thanks for your report!

In browser sandboxes we ignore `devDependencies`, and since `twin.macro` is listed as one, we can't find it. Moving it to `dependecies` leads into another issue, though: https://codesandbox.io/s/macrotwin-issue-zh2i6 .

We'll take a better look at this and get back to you.

**Comment by ben-rogerson** [comment]
@lbogdan Cheers for looking into that. 

The second issue you found there would be great to fix, the workaround is to add a file named `empty.js` in the root.

Feature request: Being able to specify which devDependencies aren't ignored via `sandbox.config.json` 👍

**Comment by lbogdan** [comment]
In this particular case, though, because you're importing from `twin.macro`, it actually needs to be in `dependencies`, not `devDependencies`.

**Comment by DeMoorJasper** [comment]
Appears to work now
