### ISSUE TITLE
Unexpected errors from Vue 3 project

### ISSUE THREAD

**Issue by wobsoriano** [codesandbox/codesandbox-client#5222]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

After importing a Vue 3 project from GitHub, the console logs:

```
...
Error when converting '/node_modules/primevue/components/datatable/DataTable.vue' esmodule to commonjs: s[t.type] is not a function 
Error when converting '/node_modules/primevue/components/datatable/ScrollableView.vue' esmodule to commonjs: s[t.type] is not a function
...
```

## How has this issue affected you? What are you trying to accomplish?

Deploying it to vercel gave me no errors. https://vue-rtk-query-demo.vercel.app/

### To Reproduce

Create a new SandBox from this repo https://github.com/wobsoriano/vue-rtk-query

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Browser          | Version 86.0.4240.198 (Official Build) (x86_64)
| Operating System | macOS Big Sur

**Comment by ChrisAckerman** [comment]
Also having this problem with my sandbox: https://codesandbox.io/s/react-css-in-js-iup6f

**Comment by SaraVieira** [comment]
Hey @ChrisAckerman  I cannot reproduce in yours

@wobsoriano Can definitely see the issue there, will work on it

**Comment by SaraVieira** [comment]
Hey @ChrisAckerman  I cannot reproduce in yours

@wobsoriano Can definitely see the issue there, will work on it

**Comment by wobsoriano** [comment]
> Hey @ChrisAckerman  I cannot reproduce in yours
> 
> @wobsoriano Can definitely see the issue there, will work on it

Great! Thanks

**Comment by ChrisAckerman** [comment]
I discovered my bundle accidentally contained optional chaining (and possibly other ESNext syntax). I'm not sure why that resulted in that particular error, but fixing the babel config to down level made the warning go away.

**Comment by SaraVieira** [comment]
hmm, let me send to ives and see if that would cause that any issues
