### ISSUE TITLE
Angular library styleIncludePaths not working

### ISSUE THREAD

**Issue by vaalgrind** [codesandbox/codesandbox-client#5227]
I'm developing two projects in one angular application. One is angular library, in _ng-package.json_ for this library I set styleIncludePaths, in local and production environment it works, but when I migrated project into codesandbox, I start encoutering problems with scss files import. Any suggestions how to fix this? :)

**Comment by SaraVieira** [comment]
Hey!

Can you please follow the template and add a sandbox that I can test this? I don't have that much experience with angular :/

**Comment by vaalgrind** [comment]
@SaraVieira sorry, I'll prepare better example ;) 
# 🐛 bug report

## Description of the problem
I'm developing two projects in one angular application. One is angular library, the second is angular application.
 in ng-package.json for this library I set styleIncludePaths. In local and production environment it works, but when I migrated project into codesandbox, I start encoutering problems with scss files import. The same situation is with _stylePreprocessorOptions_  (you can find this option in angular.json) for regular angular app (second one), it also doesn't work in codesandbox environment. In local or production mode - it works.

## How has this issue affected you? What are you trying to accomplish?
We cannot migrate our company project because we use this path aliasing. I'm trying to migrate our project into codesanbox environment with full functionalites. 
### To Reproduce
Go to _app.component.scss_ or _project/sample-library/lib/src/cat/cat-componet.scss_, imports don't work until you pass relative long path.

### Link to sandbox: [link](https://codesandbox.io/s/pk5ot?file=/src/app/app.component.scss)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox     https://codesandbox.io/s/pk5ot?file=/src/app/app.component.scss |
| Browser   Chrome |
| Operating System Window 10 |

**Comment by SaraVieira** [comment]
Hey

This makes perfect sense, thank you for taking the time.

Yeah we don't support that in any template :/

I would say a good option would be to make the template `node` in Github and you can see some docs here:

https://codesandbox.io/docs/configuration

This will make the sandbox a container environment

https://codesandbox.io/docs/environment

Hope this helps and I am sorry we do not support this for now :/
