### ISSUE TITLE
tailwindcss@2.0.1: The engine "node" is incompatible with this module. Expected version 

### ISSUE THREAD

**Issue by mhmmr** [codesandbox/codesandbox-client#5233]
I get an error when using tailwind v2

*error* tailwindcss@2.0.1: The engine "node" is incompatible with this module. Expected version ">=12.13.0". Got "10.23.0"

**Comment by SaraVieira** [comment]
Hey

We just added support for changing the node version in the sandbox config.

You can see the discussion here: https://github.com/codesandbox/codesandbox-client/discussions/5221 and adding that key to your config and restarting the server should work

Also please follow the template when creating issues
