### ISSUE TITLE
Tests only run a small percentage of the time.

### ISSUE THREAD

**Issue by ryanpcmcquen** [codesandbox/codesandbox-client#5241]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Tests only run a small percentage of the time.

## How has this issue affected you? What are you trying to accomplish?

I'm trying to use the built in Jest support.

### To Reproduce

Visit the link below in Firefox or Chromium.

<img width="805" alt="Screen Shot 2020-12-07 at 10 57 44 AM" src="https://user-images.githubusercontent.com/772937/101392828-12a70280-387b-11eb-9aa2-f8ef447b86a0.png">

### Your Environment

| Software         | Name/Version                      |
| ---------------- | --------------------------------- |
| Сodesandbox      | f4dd58cf8                         |
| Browser          | Firefox 83 / Brave (Chromium) 87  |
| Operating System | Mac OS 10.15 / Windows 10         |

**Comment by SaraVieira** [comment]
oh no, seems it's a general problem, also in chrome :/ 

Will take a look

**Comment by Explosion-Scratch** [comment]
Same here. Chrome, ChromeOS. (Latest)
