### ISSUE TITLE
Codesandbox CI does not work with npm workspaces.

### ISSUE THREAD

**Issue by jansiegel** [codesandbox/codesandbox-client#5249]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Since Codesandbox CI works on `npm@6.x`, it does not support `npm workspaces`. 

(I mentioned this in #5150, but my main issue there was something else, so I might not have been making myself clear - sorry for the duplicate issue.)

The main problem is -`npm ci` on `npm@6.x` doesn't install dependencies properly, when `package-lock.json` was generated using `npm@7` with workspaces. This causes sub-projects to not recognize their dependencies and any cross-references between them.

## How has this issue affected you? What are you trying to accomplish?
I'm creating a monorepo using `npm workspaces`, and currently can't figure out how to use Codesandbox CI along with it.

### To Reproduce
I created a sample repo with a PR: https://github.com/jansiegel/monorepo-testing/pull/5.

There are 3 packages here, defined in both `package.json` (for npm) and in `.codesandbox/ci.json`:
```
  "packages": [
    "./",
    "packages/lib1",
    "packages/lib2"
  ],
```

`lib2` has a dependency (`randomstring`), and additionally, relies on `lib1` from the same repo in its `index.js`

**The result on Codesandbox CI:**
```
Error: Cannot find module 'randomstring'
```
and if the `randomstring` dependency is removed, then:
```
Error: Cannot find module 'lib1'
```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Anything that's currently on https://ci.codesandbox.io/
| Browser          | Chrome 87.0.4280.88
| Operating System | macOS 10.15.7

**Comment by SaraVieira** [comment]
Hey!

Unfortunately, we do not yet have support on CodeSandbox CI for NPM7

We will add it but I don't really have a date for you

**Comment by jansiegel** [comment]
> We will add it but I don't really have a date for you

Alright, I'll be keeping my eyes peeled then.
