### ISSUE TITLE
Unable to import quasara project from github

### ISSUE THREAD

**Issue by rowild** [codesandbox/codesandbox-client#5256]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I want to import my Quasar project from this url:
https://github.com/rowild/quasar-todo-app

When the import process starts, the error "template: invalid template file specified" pops up soon.

## How has this issue affected you? What are you trying to accomplish?

Simply fork a Quasar project to collaborate with others...

### To Reproduce

Just try importing the project yourself, it is not private.

### Link to sandbox: [link]() (optional)

Since the project isn't imported yet there is no usable link

![Screen Shot 2020-12-10 at 09 11 42](https://user-images.githubusercontent.com/213803/101740267-e54f9400-3ac8-11eb-8cc6-4509d8e9465d.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 3.9.3
| Browser          |  Chrome 87
| Operating System | macos 10.13.6

**Comment by SaraVieira** [comment]
Hey!

This seems to be an API issue, we are on it

Should be fixed by tomorrow 👍

**Comment by rowild** [comment]
https://youtu.be/GC5E8ie2pdM

**Comment by SaraVieira** [comment]
Hey!

My PR will fix the import but the GitHub repo does not have a start or dev script so it won't run unless you open a new terminal or fork it to add a start script and restart it

Hope this makes sense and ping me with any issues

**Comment by rowild** [comment]
Thank you so much for your quick reaction! Awesome!
I'll add the missing npm scripts - thanks for bringing that to my attention!

All the best, stay safe and healthy!

**Comment by SaraVieira** [comment]
Of course and no problem!

Here is a working version btw: codesandbox.io/s/9jjtl

Have a great weekend :)
