### ISSUE TITLE
VERY wierd bug.

### ISSUE THREAD

**Issue by Explosion-Scratch** [codesandbox/codesandbox-client#5284]
![image](https://user-images.githubusercontent.com/61319150/102131133-608dae80-3e17-11eb-8f2f-eeb80a8bc09e.png)
 ChromeOS, Chrome Latest.

**Comment by Explosion-Scratch** [comment]
Just happened out of the blue. Reloading is not fixing it.

**Comment by SaraVieira** [comment]
Hey!

Please follow the template we have and give us a testing sandbox and also we need your check on the other stuff

**Comment by Explosion-Scratch** [comment]
@SaraVieira Sorry, turns out it was another extension I had installed, my apologies! (I'll follow the template next time too! :)  )
