### ISSUE TITLE
CRA TypeScript Project Fails to Compile After Importing from GitHub

### ISSUE THREAD

**Issue by pahund** [codesandbox/codesandbox-client#5288]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I have created a code sandbox with the React/TypeScript template and exported it to GitHub. I've made some changes outside of CodeSandbox, among other things updating the npm dependencies to *react-scripts* and *typescript* to the latest versions. The code compiles and works just fine when running locally ([check it out on GitHub](https://github.com/nuffshell/nuffshell-blog-11-example)).

I then tried importing this project back into CodeSandbox by using the [import wizard](https://codesandbox.io/s/github).

After importing, the sandbox shows a lot to syntax error messages in the browser panel:

![Bildschirmfoto 2020-12-15 um 09 22 53](https://user-images.githubusercontent.com/1639313/102189574-24aa2600-3eb7-11eb-8def-b6f2d1084e6d.png)

👉🏻 [See code sandbox](https://codesandbox.io/s/github/nuffshell/nuffshell-blog-11-example)

## How has this issue affected you? What are you trying to accomplish?

I can't continue to work on my project with CodeSandbox because I can't get it to compile.

### To Reproduce

* Go to the [import wizard](https://codesandbox.io/s/github)
* Enter URL of a GitHub repository that was created with *create-react-app* using the latest version of *react-scripts* and *typescript*
* Observe compilation errors in the browser panel

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | d00f3b4ac |
| Browser          | Google Chrome 87.0.4280.88 (official build) |
| Operating System | macOS 10.15.7 (Catalina) |
| react-scripts | 4.0.1 |
| typescript | 4.1.3 |

**Comment by SaraVieira** [comment]
Hey paul

Question about this:

Was that syntax added in the latest version of TS?

**Comment by pahund** [comment]
Who's Paul? 😃

The syntax `export type` was introduced with TS version 3.8 in March 2020: https://blog.logrocket.com/whats-new-in-typescript-3-8/

So it's not a brand new feature, only “new-ish”.

Best regards,
Patrick

**Comment by pahund** [comment]
Take a look at this sandbox: https://codesandbox.io/s/step-25-interactivity-6b43h?file=/src/storage/appConfig/index.ts

The TS compiler explains that `export { default as AppConfig }` is wrong and tells me to use `export type`:

<img width="662" alt="Bildschirmfoto 2020-12-17 um 10 18 54" src="https://user-images.githubusercontent.com/1639313/102468037-4ccd8c80-4051-11eb-9aa3-ecadde608c29.png">

The app works, though.

When I follow the compiler's advice and change it to `export type { default as AppConfig }`, the app crashes:

<img width="1321" alt="Bildschirmfoto 2020-12-17 um 10 20 23" src="https://user-images.githubusercontent.com/1639313/102468178-7edeee80-4051-11eb-8a05-faca130f3564.png">

**Comment by SaraVieira** [comment]
Idk man, I thought your name was paul by the handle.

It's the last time I try that 😂

Will check if we have that version of the ts server installed

**Comment by pahund** [comment]
@SaraVieira any update on this? has it been fixed?

**Comment by lbogdan** [comment]
Closing this, as we upgraded to TypeScript 4.1.2 in the meanwhile, and the linked sandbox https://codesandbox.io/s/github/nuffshell/nuffshell-blog-11-example works fine.

Feel free to re-open if this is still an issue for you.
