### ISSUE TITLE
it crashed

### ISSUE THREAD

**Issue by patriklindstrom** [codesandbox/codesandbox-client#5315]
# 🐛 bug report

## Preflight Checklist

- [ ] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [ ] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [ ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by SaraVieira** [comment]
Hey!

Sorry but we need more information
