### ISSUE TITLE
Sandpack tutorial doesn't work without setting bundlerUrl - using localhost:3000 for src

### ISSUE THREAD

**Issue by joshp-f** [codesandbox/codesandbox-client#5318]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
When using the npm package "smooshpack" (files under standalone-packages/sandpack), the package is supposed to create an iframe using "src" attribute of https://sandpack-" + version_1.default.replace(/\./g, '-') + ".codesandbox.io"  
Instead it uses "http://localhost:3000", I think because of this code in manager.js:  
`var BUNDLER_URL = true 
    ? 'http://localhost:3000'
    : "https://sandpack-" + version_1.default.replace(/\./g, '-') + ".codesandbox.io";`
perhaps this flag was set incorrectly during build - process.env.CODESANDBOX_ENV;
## How has this issue affected you? What are you trying to accomplish?
I used the bundlerUrl option to override the src value, but this means that the default tutorial will fail without setting bundlerUrl.

### To Reproduce

Follow the default tutorial. The iframe created will load localhost:3000, not the bundler path.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by SaraVieira** [comment]
Hey

Can you tell me what tutorial you were following?

**Comment by joshp-f** [comment]
Hi, I used the tutorial in the markup visible at https://github.com/codesandbox/codesandbox-client/tree/master/standalone-packages/sandpack

**Comment by alexnm** [comment]
Hey @joshp-f,

Which version of `smooshpack` are you using? version `0.0.66` is the last stable one published from `master`. Try to fix your version to that, it should not have the localhost:3000 fallback. 

https://github.com/codesandbox/codesandbox-client/blob/master/standalone-packages/sandpack/src/manager/index.ts

I think there's a 0.0.67 which should not have been published like that, which messes things up.

Keep in mind, we are in the middle of a full revamp of these packages as `sandpack` and `react-sandpack`. it is still heavily work in progress, but in a couple of weeks we should have some beta versions out there.

**Comment by joshp-f** [comment]
HI Alex, My mistake. I fixed it by installing the latest version.
