### ISSUE TITLE
Create new repository on Github fails

### ISSUE THREAD

**Issue by Damiaou** [codesandbox/codesandbox-client#5323]
Hi there 👋🏼 
# 🐛 bug report

## Description of the problem
I have a sandbox with a react environment, everything is fine with it.
When I try to click the button `Create new repository on Github`. I got this
![oups](https://user-images.githubusercontent.com/7759894/103177928-d1ed4880-487e-11eb-9e39-b20a12201a46.png)
A repo is created but it is empty, and codesandbox does not seem to link with it.

## How has this issue affected you? What are you trying to accomplish?
I cannot create repo from codesandbox or at least link them to my sandboxes.

### To Reproduce
In a sandbox
1. Click the github icon 
2. Write the repo name
3. Click the button below
You need a github account link to your profile. I connect to codesandbox via github.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox    |  not sure where to find |
| Browser     |   Chrome  |
| Operating System | Windows|

If you need more information do not hesitate to ask. I really like your product by the way. 😄

**Comment by Damiaou** [comment]
Hello again, 
Found out my issue was my default branch name in github. It was set to *futur*.
Setting it to *main* resolved my problem. 
I'm going to close the issue because I can live with another default branch name.

**Comment by KeitoKat** [comment]
Hi all, if your issue stem from a different cause (like mine), try this:
https://www.youtube.com/watch?v=RuM4JIoO0lQ&ab_channel=CodeSandbox

Basically, I didn't export it correctly.
Hope that helps :)
