### ISSUE TITLE
npm package alias

### ISSUE THREAD

**Issue by privatenumber** [codesandbox/codesandbox-client#5324]
# 🌈 Feature

npm has [package aliasing](https://docs.npmjs.com/cli/v6/commands/npm-install#description) via:

```
npm install <alias>@npm:<name>
```

which creates a dependency entry in `package.json` like:

```
"alias": "npm:name@semver"
```

This doesn't seem to be supported right now:
<img width="1050" alt="Screen Shot 2020-12-28 at 10 17 22 PM" src="https://user-images.githubusercontent.com/1075694/103256248-7ee8c380-495a-11eb-9863-4dcb007fbe13.png">

**Comment by reuwi** [comment]
Came cross same problem, this feature is supported after npm version 6.9.0. It seems that codesandbox is not supported to sustom npm version
