### ISSUE TITLE
Add a way to view test output

### ISSUE THREAD

**Issue by halcarleton** [codesandbox/codesandbox-client#5331]
# 🌈 Feature

What is this feature?
Add a way to view test output in the/a console.

How the feature should work?
When running tests there should be a way to view output of the test runner in addition to the formatted UI view that currently exists.

You have examples or an idea how it can be implemented?
no

**Comment by SaraVieira** [comment]
Hey!

Our console is a mirrored version of the browser console not of the terminal you would find on your computer so this would be confusing for people who always had a normal browser console

This is supported in container sandboxes like the https://codesandbox.io/s/node as in there you have a terminal and not a console and you can see all the node output and errors
