### ISSUE TITLE
Can't  Codesandbox parse Ts file ?

### ISSUE THREAD

**Issue by iam-frankqiu** [codesandbox/codesandbox-client#5335]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

In my local repository. Tsconfig.json can be parsed.

### To Reproduce
Following is the Codesandbox URL:
https://codesandbox.io/s/delicate-browser-7s5m0?file=/src/App.tsx

This is my original repository URL:
https://github.com/iam-frankqiu/snowpack-react-ts-app/tree/babel_config_influence_err

The err showed between my local repository and Codesandbox is not the same.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/delicate-browser-7s5m0?file=/src/App.tsx

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | fork form my GitHub url
| Browser          | Chrome
| Operating System | macOS

**Comment by SaraVieira** [comment]
We don't support JSON with comments, I'm still trying to understand how this works locally

**Comment by SaraVieira** [comment]
did some digging and turns out it's completely valid to have comments in tsconfig files, had no idea.

Made a PR to add support to it

**Comment by iam-frankqiu** [comment]
> did some digging and turns out it's completely valid to have comments in tsconfig files, had no idea.
> 
> Made a PR to add support to it

Thank you! You are so efficient.
