### ISSUE TITLE
Could not find bundled tsserver.js

### ISSUE THREAD

**Issue by ntucker** [codesandbox/codesandbox-client#5347]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

TypeScript doesn't work in editor.

"VS Code's tsserver was deleted by another application such as a misbehaving virus detection tool. Please reinstall VS Code."

And

"Could not find bundled tsserver.js"

## How has this issue affected you? What are you trying to accomplish?

Looking at types on hover or seeing type errors with red underlines.

### To Reproduce

1) visit https://codesandbox.io/s/rest-hooks-github-hinux
2) open any ts or tsx file
3) See errors popup

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | e1a24a434
| Browser          | SWIron 74.0.3850.0
| Operating System |  Windows 10

**Comment by SaraVieira** [comment]
Hey!

Can you still reproduce this in a private window? Cause I downloaded that browser and everything seems to work

![image](https://user-images.githubusercontent.com/1051509/104112539-72685180-52f0-11eb-8663-9d6a9eaa6144.png)


Or do you have any specific settings turned on?

**Comment by ntucker** [comment]
Private browsing didnt' change anything.

However, upgraded browser to Version 87.0.4450.0 and this fixed it.
