### ISSUE TITLE
Failing to load vanilla javascript sandbox

### ISSUE THREAD

**Issue by Zalcherei** [codesandbox/codesandbox-client#5349]
# 🐛 bug report

## Preflight Checklist

- [ x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [ x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [ x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Failing to load vanilla javascript sandbox after it's creation.

## How has this issue affected you? What are you trying to accomplish?
Can't really edit anything and see the results since the preview window does not load the sandbox.

### To Reproduce
Created vanilla javascript sandbox.

the list of errors/warning if it helps:
https://pastebin.com/at77eVqB

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Brave (Version 1.18.78 Chromium: 87.0.4280.141 (Official Build) (64-bit))
| Operating System | Windows 10

**Comment by SaraVieira** [comment]
Hey

I'm so sorry but in order to find out what's wrong we need the sandbox or an example of the error on another sandbox
