### ISSUE TITLE
Loader 'worker-loader' could not be found.

### ISSUE THREAD

**Issue by HillLiu** [codesandbox/codesandbox-client#535]
Could you point me how to resolve it?

I use inline worker-loader in my code, such as.

```
            import('worker-loader!../../src/worker').then( workerObject => {
                if (workerObject) {
                    worker = new workerObject();
                    initWorker(worker);
                }   
            }); 
```

**Comment by CompuIves** [comment]
Hey! We don't have support for the worker-loader yet, I'm thinking whether it would be possible to support it.

Looking at the Webpack loader (https://github.com/webpack-contrib/worker-loader/blob/master/src/index.js) we'd need to emit a file, which we then need to require externally. We would require something like a service worker to make it seemingly statically available...

Interesting, I'll think some more about this!

**Comment by HillLiu** [comment]
Cool, thanks @CompuIves

**Comment by mervynwee** [comment]
I'm trying to get worker-loader working on codesandbox, and I'm running into a ModuleNotFoundError where worker-loader is not able to find the web worker JavaScript file. Is the error related to this issue or did I configure my webpack.config.js file wrongly?

https://codesandbox.io/s/o78xxl5x76
