### ISSUE TITLE
Malware Warning (Malicious Website Suspected) LinkedIn

### ISSUE THREAD

**Issue by riya0408** [codesandbox/codesandbox-client#5358]
![Capture](https://user-images.githubusercontent.com/41470699/104455836-234c4600-55a8-11eb-891b-f72c72cfc13e.PNG)
Malware Warning (Malicious Website Suspected) LinkedIn

**Comment by SaraVieira** [comment]
Hey

What is the link?

**Comment by riya0408** [comment]
My company name is conferenzia world . website: https://conferenziaworld.com/ . but when I am trying to visit my website through Linkedin I am geting : Malicious Website Suspected
Sorry, there was a problem with the following link: http://www.conferenziaworld.com
This link has been reported as participating in malicious behavior or abuse.

For your safety, we've blocked access to this link from LinkedIn.

![image](https://user-images.githubusercontent.com/41470699/104457451-627b9680-55aa-11eb-9c63-147575ef65c8.png)

**Comment by SaraVieira** [comment]
I'm sorry, I don't understand how this is related to CodeSandbox
