### ISSUE TITLE
Allow account deletion

### ISSUE THREAD

**Issue by Explosion-Scratch** [codesandbox/codesandbox-client#5360]
# 🌈 Allow account deletion
Currently there is no way to delete CodeSandbox accounts. This is a feature in almost every other major website.

This feature would (obviously) allow people to delete their own accounts. There should be account settings in the "CodeSandbox settings" menu across the website, this would have the option to delete your account, followed by a prompt to confirm (Maybe even a "Type [username here] to confirm" like in GitHub). This feature could possibly also be merged with  the "Integrations" panel, and renamed to "Account Settings"

**Comment by LucaSorvillo** [comment]
i want to delete my account

**Comment by kettanaito** [comment]
Hey, @LucaSorvillo. 

Sure thing. I'd love to help you with that. Could you please email us at [support@codesandbox.io](mailto:support@codesandbox.io), mentioning your CodeSandbox username? Let's follow up there. Thanks.

**Comment by imageck** [comment]
@kettanaito this has got to be some kind of a joke, right?
