### ISSUE TITLE
Allow people to change/hide their "Name"

### ISSUE THREAD

**Issue by Explosion-Scratch** [codesandbox/codesandbox-client#5361]
# 🌈 Allow people to change/hide their "Name"

Many people code under a certain username, but they don't reveal their real name. This is revealed in CodeSandbox profiles when users signup with Google. (In GitHub it's their username). This should be kept private and/or be able to be changed. In addition to this there is no way to delete accounts, (#5360 ) meaning that real names could be leaked forever.

**Comment by andrasbacsai** [comment]
Hey, we recently shipped a feature that lets you change your name/username on your profile. 
Also, there is a delete button that requests to delete your account.

I think these two are enough for your needs, right?

**Comment by lbogdan** [comment]
Hey @Explosion-Scratch ,

Can you please let us know if the features highlighted by @andrasbacsai above address your issue? Thanks!

**Comment by Explosion-Scratch** [comment]
> Hey, we recently shipped a feature that lets you change your name/username on your profile.
> Also, there is a delete button that requests to delete your account.
> 
> I think these two are enough for your needs, right?

Epic! They work perfectly! Super cool!

**Comment by Explosion-Scratch** [comment]
> Hey @Explosion-Scratch ,
> 
> Can you please let us know if the features highlighted above by @andrasbacsai address your issue? Thanks!

Apologies for the late reply! The new features work great! Thanks to both of you for your help!

**Comment by nitrocode** [comment]
I still cannot hide my name from my profile.

**Comment by JamesACS** [comment]
Hey @nitrocode , you can't hide it but you can change it to whatever you wish :)

**Comment by nitrocode** [comment]
@JamesACS You're technically right but.... not according to a company I work for. I had to create a separate github and set the name as my personal name as that is the requirement of some audit. It would be nice to hide your name in Github which you're not able to do.

This ticket should remain open.

**Comment by JohnWolfson** [comment]
How do we change them? I have my Display name but my real name shows in brackets on my profile. I want to change/hide my rename from public view

**Comment by JamesACS** [comment]
Hello @JohnWolfson, you can do this from your dashboard [settings](https://codesandbox.io/t/overview), just hit the edit icon by the username
