### ISSUE TITLE
Vue 3 template Babel throws on Firefox

### ISSUE THREAD

**Issue by LeBenLeBen** [codesandbox/codesandbox-client#5366]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Sandbox using Vue 3 template started to throw on Firefox recently (not sure exactly when):

> TypeError
> [BABEL] /src/main.js: t[2].getFileName is not a function (While processing: "base$0.overrides[0]$5")

## How has this issue affected you? What are you trying to accomplish?

The demo does not run anymore; it used to work perfectly and nothing has been changed since.

### To Reproduce

https://codesandbox.io/s/ctabs-ik4zk
https://codesandbox.io/s/calert-3j3ve
https://codesandbox.io/s/ccollapse-w80b1

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 7e55ec6d5
| Browser          | Firefox 84.0.2
| Operating System | macOS 10.15.7

**Comment by CompuIves** [comment]
Hey @LeBenLeBen! Interestingly I did update Babel recently, but I can't repro the issue you're facing. Does the sandbox work for you if open in an incognito browser? My hunch is that it might be cache, in the meantime I'll try to repro some more.

**Comment by CompuIves** [comment]
Actually, I can repro this on Firefox. Looking at the issue now.

**Comment by LeBenLeBen** [comment]
That was fast! Thank you

**Comment by LeBenLeBen** [comment]
@CompuIves I hope that’s not me having caching issue or something but despite it being fixed on Firefox, it seems to be still impacting Safari on iOS and macOS. I saw your fix mentioning this browser as well, but not the commit, so I’m not sure if this is intended or not.

**Comment by SaraVieira** [comment]
Hey!

Just tested it on Safari desktop and seems like a caching issue, after a hard reload it started working


I don't know how to clear cache on iOS :(

**Comment by SaraVieira** [comment]
I tested this one sandbox: https://codesandbox.io/s/ctabs-ik4zk

**Comment by LeBenLeBen** [comment]
Can confirm, it works now! Sorry for the noise and thank you for double checking.

**Comment by SaraVieira** [comment]
No worries, Safari tends to be a special boy so it's always good to double check there

**Comment by tonjohn** [comment]
I created a new Vue project today and immediately hit this error in Safari on my m1 MacBook Air. https://codesandbox.io/s/gifted-sky-kke9k?file=/src/App.vue

Not sure if it is related but I had tried a new Nuxt project before that and HMR would reload the page infinitely after making a change (happened 100% of the time if I added a page) - https://codesandbox.io/s/elegant-river-m9ier

**Comment by SaraVieira** [comment]
Hey!

I tested it on Safari and it seems to work, you may need to update the service worker to the latest version at the top right of your app.

About the nuxt app it also seems good on this side, let me know if the service worker fixes it that issue too otherwise let's make a new issue and see it
