### ISSUE TITLE
Add support for different code formatters

### ISSUE THREAD

**Issue by poweredbylinux** [codesandbox/codesandbox-client#5390]
# Feature request: Add support for different code formatters

Adding support for different code formatters would be nice. I don't like Prettier's HTML formatting, especially because it adds the end slashes on empty tags which is not required in HTML5.

An option in the settings to change the default formatter would be helpful.

**Comment by SaraVieira** [comment]
Hey!

Thank you for your request, we are adding all feature requests to the backlog to have it all in one place and it's now added. I see that right now it's even impossible to turn off prettier just for HTML files so a first step would be adding support for a prettier ignore in my opinion
