### ISSUE TITLE
Dependency version select closes too fast

### ISSUE THREAD

**Issue by jeferson-sb** [codesandbox/codesandbox-client#5394]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

When you click on the dependency version select and move your mouse over the options it closes too fast 
See gif below

![select](https://user-images.githubusercontent.com/30840709/105616005-65e4fe00-5db2-11eb-835d-bdb99fbd055d.gif) 

## How has this issue affected you? What are you trying to accomplish?

Change a dependency version on my project

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Browser          | Microsoft Edge 87 |
| Operating System | Windows 10 |

**Comment by SaraVieira** [comment]
This is super weird we have not changed this code in about 6 months and only happens in Edge and Firefox.

Seems like it's CSS but honestly we are kinda lost here, it's not even a custom dropdown, just a good old <select> tag

**Comment by jeferson-sb** [comment]
@SaraVieira Yes, it seems to happen only on edge,
taking a look closer there's a little gap between the select and the list of options

![image](https://user-images.githubusercontent.com/30840709/105780212-b6915e00-5f4e-11eb-9adf-884a5d3afef5.png)

**Comment by SaraVieira** [comment]
Also happens on Firefox :(

I guess the gap is just a default drop-down style there but the issue seems to be hover over something that has a clickable element
