### ISSUE TITLE
Lets and consts are initialised before declaration

### ISSUE THREAD

**Issue by aditya2337** [codesandbox/codesandbox-client#5396]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Lets and consts are initialized before the declaration in vanilla JS.

## How has this issue affected you? What are you trying to accomplish?
This invalidates the logic of a "const" it can be in 2 types now (undefined and any other type), which is not allowed in any other js platform. This is a different behaviour which shouldn't exist.

### To Reproduce
```
console.log(typeof x);
const x = "";
console.log(typeof x);
```

### Your Environment
Vanilla JS

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Vanilla JS
| Browser          | Chrome
| Operating System | MacOs

**Comment by aditya2337** [comment]
Cuz nobody cares 😢

**Comment by DeMoorJasper** [comment]
@aditya2337 sorry for the late reply. I've just looked into this and it does appear to be a bug, don't have time today to look into this. But if it still blocking you in some way I can have a look at it tomorrow.

For future reference, this is the behaviour in chrome console:
![Screen Shot 2021-05-05 at 16 42 28](https://user-images.githubusercontent.com/2175521/117160105-21a9c680-adc1-11eb-8d02-f41e7751ce23.png)

**Comment by aditya2337** [comment]
@DeMoorJasper thanks for following up, it's not blocking me in anyways, just that while trying to understand JavaScript better I was trying out this in codesandbox, got confused because of the behaviour would be helpful for for someone else trying the same but certainly nothing that can't wait, maybe just keep it in the backlog with low priority 🤗
