### ISSUE TITLE
csb url works but codesandbox.io url is not working

### ISSUE THREAD

**Issue by ad1992** [codesandbox/codesandbox-client#5401]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I am using `create-react-app` to create a code sandbox example. Since CRA recommends adding static assets to the `public ` folder, I have added assets to the `public/static/js` path.
However, for assets that are lazily loaded the URL is prefixed with `https://codesandbox.io` which gives a 404 error but If you check the same asset with prefixed URL `https://oc6un.csb.app/` it will work.

<img width="469" alt="Screenshot 2021-01-25 at 7 55 43 PM" src="https://user-images.githubusercontent.com/11256141/105719737-a70f1680-5f48-11eb-8999-060e90d68796.png">

However, if you check [https://oc6un.csb.app/static/js/excalidraw-assets/vendor.js](https://oc6un.csb.app/static/js/excalidraw-assets/vendor.js) it loads the file

Also downloading the example and running in local works fine.

looks like code sandbox is configured to load the assets from CSB URL when the public folder is used. If this is configured to use codesandbox.io then the issue will be fixed.

### To Reproduce

Try it out [here](https://codesandbox.io/s/excalidraw-v02-oc6un)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by SaraVieira** [comment]
Hey!

Can you tell where you are using the files that are being linked? I cannot seem to find any reference to them

**Comment by ad1992** [comment]
@SaraVieira these files are lazily loaded by the npm package `aakansha-excalidraw` and by default the files get loaded from `{rootUrl}/static/js` path hence added to `public/static/js` path.

**Comment by CompuIves** [comment]
Ah, interesting. The Webpack loader tries to guess the `publicPath` by checking the script it's currently loading (which is `codesandbox.io/static/js/sandbox.js`. In reality that should be `https://oc6un.csb.app/`, but we use the `codesandbox.io` domain so we can reuse the bundler cache. I think the solution here is to set `publicPath` to the right value (current location.href). I'll check if we can set an environment variable or something in the bundler.

**Comment by CompuIves** [comment]
Oh you were one step ahead of me! I was also looking into using this:
`window.__webpack_public_path__ = "https://bar.com";`

But yeah, it will be interesting to see if this will make it work: https://github.com/excalidraw/excalidraw/pull/2835. We need to find a way that Webpack doesn't go in "auto-detect" mode for the `publicPath`. We can set a variable or env var in the bundler, but it would be good to see if we can find a long-term solution. I think this also won't work with unpkg for example.

**Comment by ad1992** [comment]
@CompuIves for CRA `PUBLIC_URL` can be set to the URL from where we need the assets to be loaded but still, it will try to load it from `{PUBLIC_URL}/js/` path instead of just `{PUBLIC_URL}`. 
`window.__webpack_public_path__ ` can be used for (non-CRA apps using webpack) to serve the assets from a different URL.

Will you be pushing a fix for this so code sandbox loads it from the correct URL?

**Comment by CompuIves** [comment]
So a fix for this would be to set the environment variable `PUBLIC_URL` in the bundler? I can set `process.env.PUBLIC_URL` to the sandbox url, if that would fix this loading logic I can add that. I can also add `window.__webpack_public_path__` to the bundler.

**Comment by ad1992** [comment]
@CompuIves CRA supports setting `PUBLIC_URL`  when the URL needs to be changed but it should set the default URL correctly which is not happening(only in code sandbox). If you download the zip file from the code sandbox link and try running in local it works completely fine hence the issue here is the url needs to be fixed (the csb url as mentioned above works but code sandbox tries to read from codesandbox.io url which is not working as mentioned [here](https://github.com/codesandbox/codesandbox-client/issues/5401#issue-793440147) ) so if that URL is fixed it will be fine.

**Comment by CompuIves** [comment]
Right, I'll try to set the environment variable `PUBLIC_URL`. The reason that it currently doesn't work in CodeSandbox while it works in others is that Webpack tries to "guess" the public URL from the script it's executing on, which in this case is not from `*.csb.app` but from `codesandbox.io` for performance reviews.

The reason that specifically works locally is that the script is running on the same domain as where it's loaded from (which is `localhost` most probably). But this won't work if you're loading the dependency from `unpkg.com` for example, which makes this more challenging.

The fix to this is to let Webpack explicitly know what the `publicUrl` is, so it doesn't guess wrongly. I'll try updating the environment variable to see if it stops the guessing.

**Comment by ad1992** [comment]
got it. Yes, that makes sense. 

To add on to the `unpkg` example you mentioned, updating `PUBLIC_URL` and running `npm run build` in local will load the assets from `/{PUBLIC_URL}/static/js` folder but in dev mode, it doesn't work though looks like support were added in CRA for dev in [v3.4.0](https://github.com/facebook/create-react-app/pull/7259).

**Comment by ad1992** [comment]
@CompuIves got a chance to check this?

**Comment by ad1992** [comment]
Any update on this?

**Comment by parys-github** [comment]
The website with codesandbox.io is not loading at all. The browser return the message: 
**This site can’t be reached**
_codesandbox.io refused to connect._

**Comment by JamesACS** [comment]
Hey @parys-github - We've not had any issues on this end. Is it still not working for you?
