### ISSUE TITLE
Could not find module in path: 'react/jsx-runtime'

### ISSUE THREAD

**Issue by dbeidle** [codesandbox/codesandbox-client#5407]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Exact Error: Could not find module in path: 'react/jsx-runtime' relative to '/src/modal.js'

## How has this issue affected you? What are you trying to accomplish?

Creating a modal with tabs

### To Reproduce
There was a "new version" button on the top codesandbox tool bar next to my name which I clicked. 

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome 87.0.4280.141
| Operating System | MacOS Big Sur

**Comment by SaraVieira** [comment]
Hey

Sorry about this, I think I know what the issue is, will get on it now

**Comment by dbeidle** [comment]
Thanks @SaraVieira, I did have to bump the react and react-dom version up to 17.0.1 to get it to work. It did not want to work under utilizing 16.13.1 for both packages...

**Comment by SaraVieira** [comment]
We added the new babel transform for all react versions if the react scripts was version 4. We thought that was the only dependency, our mistake 😅

**Comment by dbeidle** [comment]
No worries, glad to help with providing the useful information for you to resolve it... I really appreciate your quick responses. Hope you have an awesome day!

**Comment by SaraVieira** [comment]
No problem, my pleasure, and thank you for making an issue that was easy to follow

Have a great day! :)

**Comment by hannakim-outreach** [comment]
Hi @SaraVieira - I'm experiencing this same issue (but relative to path `/src/index.js`. I tried bumping `react` and `react-dom` versions but still seeing the error (ModuleNotFoundError: Could not find module in path: 'react/jsx-runtime' relative to '/src/index.js')

I wasn't sure if I should make a separate issue for this?

**Comment by JamesACS** [comment]
Hey @hannakim-outreach - As this thread hasn't been used in over a year it'd be best to create a new issue with as much detail as you can about the issue you're experiencing.
