### ISSUE TITLE
Support tailwind.config.js

### ISSUE THREAD

**Issue by deadcoder0904** [codesandbox/codesandbox-client#5415]
# 🌈 Feature

Would love to have `tailwind.config.js` support inside of Codesandbox.

Everything else works just fine but I can't seem to get `tailwind.config.js` working at all. Is this feature not supported or have I missed anything?

**Comment by SaraVieira** [comment]
Hey!

Can you tell me what template you were using when trying to use it?

**Comment by deadcoder0904** [comment]
I tried 2-3 popular templates (the one by Jared Palmer `formik guy` is the most popular one) → React + TS + Tailwind I think.

I also have custom Codesandboxes where I've set up Tailwind just fine but `tailwind.config.js` doesn't work. 

Also, read a `dev.to` post on how to make it work. They said you've to setup something container like Express or Next but yeah there's not a quick way to make it work.

Ideally, what I'd like is Tailwind + React + TS with `tailwind.config.js` that just works ✨

As Tailwind is gaining more popularity, I think it'll be good to have ready-made templates just for Tailwind.

Also, there should be guides on Codesandbox on how to set up Tailwind with React, etc... I tried googling & finding it but alas there was none. The Google SERPS were filled with codesandboxes which don't have `tailwind.config.js`. It'll also be good for your SEO :)

Is there any way to search for files on Codesandbox? Because I also typed `tailwind.config.js` in Search but didn't get any results lol so not sure if it worked or not.

**Comment by SaraVieira** [comment]
> Also, there should be guides on Codesandbox on how to set up Tailwind with React

We are actually working on it! I had the same idea :D 

In general for now tailwind.config.js only works in containers. I can send you one if you want but I do agree with you that we could have a tailwind version of at least react and vue cli that support tailwind configs by default, will run this by ives to see how hard it would be and will get back to you on Monday :)

**Comment by deadcoder0904** [comment]
Thanks Sara. I have solved my problems for now but yes this will definitely be helpful in the future (which means like a week for me 😂)

Thanks for Codesandbox otherwise I would've had to create Github repo for every single problem I faced 😭

**Comment by SaraVieira** [comment]
I mean that's why I have like 300 repos, life was hard before 😂

I am gonna close this as it's already in our backlog and we are been only keeping bugs in the github so we can focus and as soon as we have a specific template or the blog post I will post it here :)
