### ISSUE TITLE
React template throws "ReferenceError - Can't find variable: React"

### ISSUE THREAD

**Issue by Yan-rlathotep** [codesandbox/codesandbox-client#5416]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

When I create a new sandbox using the React template, the preview immediately throws this error: `ReferenceError - Can't find variable: React`. The deployed version is not affected.

## How has this issue affected you? What are you trying to accomplish?

I cannot preview my React sandboxes anymore, including new ones based on the React template, on both PC and iPad.

### To Reproduce

Just create a sandbox using the React template. I got the same result on both Windows 10 (Chrome) and iPadOS (Safari), even in private browsing mode without logging in.

Example of a [sandbox that is just the React template](https://codesandbox.io/s/purple-glade-vhemy).

**Comment by SaraVieira** [comment]
Hey!

We just pushed a fix for this, so sorry for this.

Should be live in 20m

**Comment by SaraVieira** [comment]
Its live and your sandbox seems to now work
