### ISSUE TITLE
Deleting PR branch after merging creates errors

### ISSUE THREAD

**Issue by WeersProductions** [codesandbox/codesandbox-client#5432]
# 🐛 bug report

## Preflight Checklist

- [ x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x ] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Deleting the PR branch that the CodeSandbox project was referring to creates a weird state for the CodeSandbox project. 

## How has this issue affected you? What are you trying to accomplish?
Trying to work using PRs with main branch, instead of directly committing to main. I expect CodeSandbox to fall back to the main branch (or allow me to choose a branch), even unlinking with any github repo would work (as long as I can relink it again).

### To Reproduce
Link a CodeSandbox project to a GitHub repository.
Inside CodeSandbox, make changes.
Instead of committing directly to main, create a PR branch.
Merge PR branch using GitHub, delete branch afterwards.
CodeSandbox project cannot be linked anymore and is stuck :( 

Result: https://codesandbox.io/s/priceless-nightingale-y4m71

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Browser          | Chrome 88.0.4324.104 (Official Build) (64-bit)
| Operating System | Windows 10 Pro, OS Build 19041.746

**Comment by SaraVieira** [comment]
Hey!

I could definitly reproduce this, right now it's impossible to unblink a sandbox from a branch so we can really do it when you load the page and we check the source.

I made a PR that will fix this until we have our own implementation of git and when this happens it will tell you your branch is gone and send you to main branch of your repo so you can keep working
