### ISSUE TITLE
Image corrupts on uploading Codesandbox project to github

### ISSUE THREAD

**Issue by Rishabhk06** [codesandbox/codesandbox-client#5447]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem 
Everytime i try to upload one of my projects on codesandbox to github, the Image in the project corrupts and hence cannot be seen. I have tried resyncing github to codesandbox and have even tried deleting and recreating the repo.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      Not sure|
| Browser          Google Chrome|
| Operating System Windows |

**Comment by SaraVieira** [comment]
Hey

We are aware of this issue and we are trying to fix it, it's being already tracked in #4504 so I am gonna close this one to have it all in one place

Thank you

**Comment by Rishabhk06** [comment]
By when it is expected to be fixed..
Nearly?

**Comment by SaraVieira** [comment]
I'm sorry but I don't have an answer for you, we are still trying to figure out why this is happenig

**Comment by Rishabhk06** [comment]
Alright..however i found something which might be useful

If you fork the sandbox from github and make changes by re uploading the
image file and pushing changes makes it work.

**Comment by SaraVieira** [comment]
The issue seems to be with downloading  the images from the github API :(

**Comment by Rishabhk06** [comment]
Hey, when is this issue expected to be fixed? It has been months..and I
can't even upload my projects and all.. the Image corrupts everytime I
upload it on Github using CodeSandBox...Please solve this at the earliest.
