### ISSUE TITLE
react-jsx

### ISSUE THREAD

**Issue by artola** [codesandbox/codesandbox-client#5448]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

The editor does not support the new `react-jsx` flag, it shows `Cannot use JSX unless the '--jsx' flag is provided.ts(17004)`.

By the way, the container code if downloaded and used locally shows up right.

![image](https://user-images.githubusercontent.com/11500763/107010095-2fd25180-6796-11eb-9560-75fdbe9c3212.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by artola** [comment]
@SaraVieira You wrongly link to the same issue number. But, yes the problems still is happening.

**Comment by SaraVieira** [comment]
Oh sorry, I meant to link #5316 

We will work on trying to figure this out next week, can you please follow the other issue, I'm closing this one as they are the same when it comes to the fix

Thank you
