### ISSUE TITLE
Suggest a search in all sandboxes if no results within workspace

### ISSUE THREAD

**Issue by WeersProductions** [codesandbox/codesandbox-client#5451]
# 🌈 Feature

I've seen various people (including me) use the search bar in the dashboard as if it searches through **all** codesandboxes on the website, not just within the organization/team.

As can be seen below, the text in the box also suggests that it does not only search through your own sandboxes:
![image](https://user-images.githubusercontent.com/22612711/107116961-37b5f280-6877-11eb-9e16-84caaa629434.png)

If a user searches for something, either a simple button should allow the user to do the same search for all codesandboxes, or it should already fetch these results and show them in the same window. The following image shows the page I'm talking about, especially when no results are found.
![image](https://user-images.githubusercontent.com/22612711/107116999-79469d80-6877-11eb-9f60-b7361ead8879.png)

A button that would redirect to `https://codesandbox.io/search?query=` instead of `https://codesandbox.io/dashboard/search?workspace=xxx&query=` would already be really helpful.
A fancier, but maybe more confusing solution would be to include results of all sandboxes in the 'workspace-search'. A quick and dirty mockup would be something like the following:
![image](https://user-images.githubusercontent.com/22612711/107117096-1275b400-6878-11eb-9017-7ebe8e18be1f.png)

Thanks!

**Comment by SaraVieira** [comment]
Hey!

This is actually the intent of it and it was part of the scope when it came to the dashboard that's why that is the wording there but we could never really pin down a good UX for this.

Let get @DannyRuchtie opinion here.

This is tho something we will definitely implement
