### ISSUE TITLE
 I am unable to deposit my file in the desired depository. I ask urgently to intervene.

### ISSUE THREAD

**Issue by GiuseppeSoraci** [codesandbox/codesandbox-client#5453]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by SaraVieira** [comment]
Closed by lack of info

If you need help please let us know all the info you can including the sandbox, file and what is the repo

Thank you
