### ISSUE TITLE
Unable to view sandbox, container stuck starting with an "Error fetching sandbox" msg

### ISSUE THREAD

**Issue by dawn-stripe** [codesandbox/codesandbox-client#5462]
# 🐛 bug report

## Preflight Checklist

- [ x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x ] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
I am update to run my sandbox, which is a template from a GH import using the wizard. I suspect the issue may be that there might have been an older template with the same GH repo, and instead of creating a new template the import wizard is opening that one? idk, but I'm speculating b/c the deploy URL is a URL that existed before I tried to create my template. 

Within the browser in the Dashboard the generated URL https://fqizg.sse.codesandbox.io/  shows a "Error fetching sandbox" . 

 After showing a notification that says 'Container error: error fetching sandbox', the terminal just shows: Sandbox Container: Starting sandbox fqizg...  

There is nothing under the console or problems tabs. 
The Server Control Panel says "Container is starting..."

The restart server and restart Sandbox options under the Control Container are greyed out. 

## How has this issue affected you? What are you trying to accomplish?
I'm stuck and a bit lost. I see no error messages to debug an issue with the code or dependencies and running the repo locally is working. 
 I'd be happy to start a sandbox from scratch, but I'm unable to, using the wizard just seems to reopen this sandbox instead of creating a new one associated with the repo.  

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | ? Not sure how to tell, sorry
| Browser          | Chrome 88.0.4324.146
| Operating System | MacOS Catalina 10.15.7

**Comment by lbogdan** [comment]
Hey @dawn-stripe ,

Thanks for your report, and sorry for the late reply! I see the linked sandbox no longer exists, is this still an issue for you?

**Comment by lbogdan** [comment]
@dawn-stripe Any updates on this?
