### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by idjuradj** [codesandbox/codesandbox-client#5464]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
When trying to transpile to project, codesandbox throws an error `Cannot use import statement outside a module`, which points to the following import
`import { BrowserRouter, Route, Switch, Redirect } from "react-router-dom";`

## How has this issue affected you? What are you trying to accomplish?
I am trying to run the project.

### To Reproduce
Go to provided sandbox link.

### Link to sandbox: [link](https://codesandbox.io/s/magical-worker-r3ikv) (optional)
https://codesandbox.io/s/magical-worker-r3ikv

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | react 17.0.1, react-router-dom 5.2.0
| Browser          | Chrome Version 88.0.4324.146 (Official Build) (x86_64)
| Operating System | MacOS Catalina

**Comment by CompuIves** [comment]
Hello! This definitely seems like a bug, react router is not transpiled, so the feature detection doesn't work here. I'm not sure why though. I'll be able to look at this on Friday!

**Comment by CompuIves** [comment]
Ah, interesting, it seems like our transpiler is tripping over `import "./assets/scss/light-bootstrap-dashboard-react.scss?v=2.0.0";`, it tries to use a Webpack loader there, and tries to run the files before they're transpiled... Very interesting, is this `?v=2.0.0` added for cache busting?

**Comment by jsejcksn** [comment]
I started seeing this today, too (with Grommet: https://github.com/grommet/grommet)

Reproduction sandbox: https://codesandbox.io/s/import-bug-reproduction-v6rct?file=/src/App.tsx

**Comment by xnn3** [comment]
![image](https://user-images.githubusercontent.com/83642434/121618200-5c2e0f80-caa1-11eb-924a-d4b1ad34427b.png)
Hi :) It happens to me too

**Comment by DeMoorJasper** [comment]
@jsejcksn thanks for reporting gonna look into this right away

**Comment by DeMoorJasper** [comment]
@jsejcksn fixed it in https://github.com/codesandbox/codesandbox-client/commit/a566285e0bac46978f5a3efd6796caef41762f44 grommet uses require statements in ESModules which is actually invalid but other bundlers support it so fixed it

**Comment by jsejcksn** [comment]
> grommet uses require statements in ESModules

I saw where each of the components uses a conditional check for NODE_ENV to see if it's dev or production in order to load them in some kind of wrapped documentation function.

Is there a non-runtime way (e.g. some kind of package.json config or alt import map) to use different modules during bundling based on that env value?

**Comment by jsejcksn** [comment]
> There's a couple ways, the runtime way would probably be using an `import(...)` instead of require, but top level await isn't really supported properly yet so can't really await that.

Yeah, I encountered issues using top-level await: I suspected that it's an issue with React (since it's supported by Node [>=14.8](https://nodejs.org/en/blog/release/v14.8.0/)), but I couldn't find any documentation to support or contradict that idea.

- [Google search](https://www.google.com/search?q=react+top+level+await)
- [GitHub issues search](https://github.com/facebook/react/issues?q=is%3Aissue+%22top-level+await%22+OR+%22top+level+await%22)

> In pkg#json there is the `exports` field https://nodejs.org/api/packages.html#packages_conditional_exports where you can define various versions.

Thanks for sharing this—it's exactly what I was looking for. I was aware of conditional exports, but [custom conditions](https://nodejs.org/api/packages.html#packages_resolving_user_conditions) weren't implemented yet the last time I looked at the docs.

**Comment by DeMoorJasper** [comment]
Cannot reproduce the original issue anymore, does it still happen?

**Comment by eltorio** [comment]
> Cannot reproduce the original issue anymore, does it still happen?

Hi, Jasper I have the same issue https://codesandbox.io/s/sctg-sidebar-cohelk in a vue based template
SyntaxError
Cannot use import statement outside a module

**Comment by karl-police** [comment]
why can't one use ``await``

if I open Google Chrome and type something pointless like ``await console.log("HI")`` it does not throw me an error

**Comment by filipelima18** [comment]
> why can't one use `await`
> 
> if I open Google Chrome and type something pointless like `await console.log("HI")` it does not throw me an error

It looks like a fix for this was merged a few hours ago as discussed in [this issue](https://github.com/codesandbox/codesandbox-client/issues/8433). Please let us know if you're still experiencing any issues.

**Comment by karl-police** [comment]
> > why can't one use `await`
> > if I open Google Chrome and type something pointless like `await console.log("HI")` it does not throw me an error
> 
> It looks like a fix for this was merged a few hours ago as discussed in [this issue](https://github.com/codesandbox/codesandbox-client/issues/8433). Please let us know if you're still experiencing any issues.


https://github.com/codesandbox/codesandbox-client/issues/8435

this still doesn't work
