### ISSUE TITLE
Command + N keyboard shortcut for new file doesn't work

### ISSUE THREAD

**Issue by catarak** [codesandbox/codesandbox-client#5468]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

In the "File" dropdown, there's an item called "New File". It works when you select it from the dropdown, but if you try to use the keyboard shortcut <kbd>Command</kbd> + <kbd>N</kbd>, it opens a new browser window as this is the default behavior for most (if not all?) browsers.

## How has this issue affected you? What are you trying to accomplish?

There's no working keyboard shortcut to create a new file. Should it override the browser behavior (my instinct says no). What's a reasonable substitution keyboard shortcut?

### To Reproduce

1. Open a new sandbox
2. Type <kbd>Command</kbd> + <kbd>N</kbd> (on Mac)
3. A new browser window opens, rather than a new file created.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  6acecf4f1
| Browser          |  Chrome
| Operating System | Mac OSX

**Comment by SaraVieira** [comment]
Hey!

We cannot override that unless you install the PWA. We also have some issues in that when it comes to Firefox and CMD+Shift+P.

We will work on making some work on the PWA to make it more usable on desktop and try to override these keys for both and make the ctrl instead 

Sorry about the issue but unfortunately we cannot override it. Will create an umbrella issue for all the keys I know and replace them all with ctrl instead
