### ISSUE TITLE
Chezz

### ISSUE THREAD

**Issue by Rochee88** [codesandbox/codesandbox-client#5475]
# 🐛 bug report

## Preflight Checklist

- [x ] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x ] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

### Your Environment

| Win 10        | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome
| Operating System | Win 10

**Comment by SaraVieira** [comment]
Hey!

I downloaded the project and it also does not work locally so the issue is most likely with your code and not with our product

**Comment by Rochee88** [comment]
Thanks for looking at this Sara. 
This project works well on the scratch site. Do you have any ideas on how I can make it work on codesandbox?
