### ISSUE TITLE
Some examples have stopped working

### ISSUE THREAD

**Issue by dmitrykurmanov** [codesandbox/codesandbox-client#5487]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
We are using CodeSandbox for the examples in our project. We are using CodeSandbox API. And for some time now the examples stopped working. 

### To Reproduce

I can give a lot of examples, but here some:

* https://codesandbox.io/s/61f7f - vue
* https://codesandbox.io/s/sb299 - angular
* https://codesandbox.io/s/n6d1u - react

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | codesandbox.io
| Browser          | Chrome the latest
| Operating System | Windows 10 64
| Nodejs | v.14.15.0

**Comment by dmitrykurmanov** [comment]
Sorry now I realized that examples work if I open them from github, but doesn't work if I open it from our site. So the problem at our side.

**Comment by declan-warn** [comment]
I think this issue I raised might be the same thing you are experiencing: https://github.com/codesandbox/codesandboxer/issues/72

I currently believe it's an issue with `codesandboxer`. Are you using that library?

**Comment by dmitrykurmanov** [comment]
@declan-warn no, if I understand it correctly I use API directly without any additional libs, e.g.

```html
    <form id="codeSandboxForm" style="display:none !important;" method="post" action="https://codesandbox.io/api/v1/sandboxes/define" target="_blank">
        <input type="hidden" name="parameters" />
    </form>
```

**Comment by dmitrykurmanov** [comment]
I believe this is the fix https://github.com/codesandbox/codesandbox-client/pull/5489
