### ISSUE TITLE
When saving the code it adds a new empty new line to the code

### ISSUE THREAD

**Issue by haneenmahd** [codesandbox/codesandbox-client#5491]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
The codesandbox editor add new empty line when saving it using ctrl + S

## How has this issue affected you? What are you trying to accomplish?
The issue is really annoying as it adds a empty line of code.

### To Reproduce
Go to CodeSandBox Code Editor and write some code and press ctrl + S.
[My CodeSandBox Which was Effected](https://codesandbox.io/s/random-quote-generator-kk91j?from-embed=&file=/src/App.js)

### Link to sandbox: [link]() (optional)
[My CodeSandBox Which was Effected](https://codesandbox.io/s/random-quote-generator-kk91j?from-embed=&file=/src/App.js)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest
| Browser          | Chrome Version 88.0.4324.150 (Official Build) (64-bit)
| Operating System | Windows 10

**Comment by kasipavankumar** [comment]
This happens due to the setting `Editor: Format on Save` being enabled. To disable it, go to `File → Preferences → Settings (CTRL + ,)`, search for `Format On Save`, uncheck `Editor: Format on Save`. Additionally, you can create `.vscode/settings.json` and add the following snippet to disable _Format on Save_.

```json
{
    "editor.formatOnSave": false
}
```

**Comment by haneenmahd** [comment]
> This happens due to the setting `Editor: Format on Save` being enabled. To disable it, go to `File → Preferences → Settings (CTRL + ,)`, search for `Format On Save`, uncheck `Editor: Format on Save`. Additionally, you can create `.vscode/settings.json` and add the following snippet to disable _Format on Save_.
> 
> ```json
> {
>     "editor.formatOnSave": false
> }
> ```

😊

**Comment by haneenmahd** [comment]
It formats the code.But, it should not add a new line

**Comment by SaraVieira** [comment]
It should actually, that's a prettier default setting, the only way to format with prettier is that it will also add a new line: 

https://github.com/prettier/prettier/issues/2575
https://github.com/prettier/prettier/issues/6360

Prettier does not support changing that setting as it is an opinionated tool
