### ISSUE TITLE
The add() method of Set returns wrong values in webpage IDE console panel

### ISSUE THREAD

**Issue by akasuv** [codesandbox/codesandbox-client#5493]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
I was reading *JavaScript: The Definitive Guide*, and trying some `Set` methods with CodeSandbox, and found the `add()` method returns different values in IDE console panel and Chrome build-in console.
 > The add() method takes a single argument; if you pass an array, it adds the array itself to the set, not the individual array elements. add() always returns the set it is invoked on

**IDE console**

![image](https://user-images.githubusercontent.com/30253166/108471754-d1918c80-72c6-11eb-838b-ab93f9a15ca0.png)

**Chrome built-in console**

![image](https://user-images.githubusercontent.com/30253166/108471796-e2420280-72c6-11eb-81c2-087e0ee1894b.png)

## How has this issue affected you? What are you trying to accomplish?

I think it's a language implementation level problem.

### To Reproduce

Check the link below

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Webpage |
| Browser          | Version 90.0.4422.0 (Official Build) canary (x86_64)|
| Operating System | macOS Big Sur Version 11.2.1

**Comment by lbogdan** [comment]
Hey @akasuv ,

Thanks for your report!

The linked sandbox no longer exists, but I replicated this in https://codesandbox.io/s/console-feed-set-issue-z7p2k and will open an issue against the upstream dependency, [console-feed](https://github.com/samdenty/console-feed).
