### ISSUE TITLE
Codesandbox for React is broken right now

### ISSUE THREAD

**Issue by righttracklearning** [codesandbox/codesandbox-client#5506]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
When creating a new fresh React sandbox, it generates an error instantly without modification of the files.
![image](https://user-images.githubusercontent.com/59032238/108788913-eee98380-7570-11eb-9964-56239cfeb2d6.png)

## How has this issue affected you? What are you trying to accomplish?
Can't start a React project.
### To Reproduce
Create a fresh React sandbox.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | fb32368e7
| Browser          | Chrome
| Operating System | MacOS

**Comment by puneetsingh99** [comment]
Same error, for me even opening the previous reactjs sandboxes shows the same error, and creating new ones as well
Browser: Brave
OS: Windows 10

**Comment by Joshua131313** [comment]
lmao same issue, I was going crazy cuz I asked my brother if he had the same issue and he said it worked for him. At least I'm not the only one :D

**Comment by dwivedithedev** [comment]
+1 for this. I am facing the same issue today. 
Browser: Microsoft Edge
OS: Windows 10

**Comment by ron4stoppable** [comment]
Same issue, confirmed for
Browser: Chrome & Safari
OS: MacOS

**Comment by fouadlee** [comment]
Same issue for:
Browser: Chrome
OS: Windows 10

**Comment by garethx** [comment]
Now resolved
