### ISSUE TITLE
Vercel deployment not working

### ISSUE THREAD

**Issue by softmarshmallow** [codesandbox/codesandbox-client#5508]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## How has this issue affected you? What are you trying to accomplish?
when running yarn && yarn build on root, the www directory created will be deployed on vercel. But the problem is, when i access /s (create sandbox), it will throw 404.

But also running the same command yarn && yarn start will just work fine.

Maybe somethings happening inside build script?

Also on local, running yarn start under packages/app willl work fine, but setting the vercel out-dir to packages/app/www will not even draw the website.

### To Reproduce
1. remove now.json
2. deploy on vercel with out dir - www set
3. visit the website

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |     fb32368e7f309d33e1b2f55711b2af07d1cf4ef8
| Browser          | All
| Operating System | All

CC @GwonHeeJun

**Comment by SaraVieira** [comment]
Hey!

Can you tell us a sandbox that's having this issue?

**Comment by softmarshmallow** [comment]
No. that's not the issue. the issue is that i can build this repository, but i can't deploy this repository on the web as expected.
as described.

**Comment by SaraVieira** [comment]
You mean the codesanbdbox repo?

**Comment by softmarshmallow** [comment]
Yup!

**Comment by SaraVieira** [comment]
Oh sorry, that was a mistake, it's an old file that should have been deleted.

Deleting it here: https://github.com/codesandbox/codesandbox-client/pull/5434/files

Sorry for the confusion, we have not used vercel in a while for codesandbox :(

**Comment by softmarshmallow** [comment]
Nono please re open the issue.

I want to: deploy codesandbox on vercel (doesnt relate to now.json)
I managed to: delete now.json and made it deplyable on vercel.
But, : the deployed web only shows the packages/homepage and packages/app section (/s) doesnt show up (404)

**Comment by SaraVieira** [comment]
That is impossible to do, we have a very complicated deployment system since they are all in different packages. We use docker since it's not deployable in with static deployment.

**Comment by lbogdan** [comment]
Deploying CodeSandbox to production depends on a lot of infrastructure assumptions, so the behavior you're seeing is expected. Because of this, we have never supported CodeSandbox production deployments, except for `codesandbox.io`.

**Comment by softmarshmallow** [comment]
Than what does packages/app/www contains and why is it not simply hostable?
is yarn build command only for codesandbox's internal usage? 

I'm was trying to deploy it on my private vercel to understand how the app works.

**Comment by lbogdan** [comment]
> Than what does packages/app/www contains and why is it not simply hostable?

Because, as I said, CodeSandbox depends on a lot of infrastructure assumptions (like the hostname it can be accessed at - `codesandbox.io`) and external components (like the GitHub importer microservice, the API server etc.), some of which are not open-source.

> is yarn build command only for codesandbox's internal usage?

That's correct.

> I'm was trying to deploy it on my private vercel to understand how the app works.

You can still understand how it works by running it inside a local development environment.

**Comment by softmarshmallow** [comment]
So the final say from codesandbox's team will be "don't try to deploy it. it won't work. run it locally for contribution and anything else" (because of the private resources and maybe some security reasons.) Will this be correct? 

(No offence. Just double checking)
