### ISSUE TITLE
add stylesheet in html doesn't work

### ISSUE THREAD

**Issue by lili21** [codesandbox/codesandbox-client#5527]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
the stylesheet add by `link` within the HTML file has no effect

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by jhoffner** [comment]
I have the same problem, not just for `link` but `script` & `style`. It would be nice to have a more true "static" option, because when trying to demonstrate to students how to write a simple and proper HTML file on CSB, it's not really possible due to everything being setup to be bundled instead.

**Comment by jhoffner** [comment]
From what I can tell, an attempt to extract links and scripts was made with the [getHTMLInfo()](https://github.com/codesandbox/codesandbox-importers/blob/master/packages/import-utils/src/create-sandbox/index.ts#L16) method, however I can't find anyplace that it is actually consumed.

**Comment by lili21** [comment]
You can make it work through external resources. a workaround. @jhoffner
