### ISSUE TITLE
next.config.js is not being used in Next.js app

### ISSUE THREAD

**Issue by ajonp** [codesandbox/codesandbox-client#5536]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Next.js application not using the next.config.js while using next/image component

## How has this issue affected you? What are you trying to accomplish?
I am trying to show an image and it is unable to use the base configuration
### To Reproduce
Check the repo and copy

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/nextjs-image-cloud-provider-osikp?file=/next.config.js

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | https://codesandbox.io/s/nextjs-image-cloud-provider-osikp?file=/next.config.js
| Browser          | Chrome
| Operating System | MacOS

**Comment by SaraVieira** [comment]
Hey!

I just opened and it's working, you need to restart the server after changing the config

**Comment by ajonp** [comment]
Oh wow so sorry thanks so much!
