### ISSUE TITLE
Codesandbox preview failed with antd

### ISSUE THREAD

**Issue by zombieJ** [codesandbox/codesandbox-client#5541]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [ ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Seems `@babel/runtime` breaks again. ref #5028

reproduce: https://codesandbox.io/s/irp9w

<img width="559" alt="截屏2021-02-28 下午9 07 34" src="https://user-images.githubusercontent.com/5378891/109419552-fd201f80-7a08-11eb-8d02-ac5071362c18.png">

Manually install will work: https://codesandbox.io/s/type-antd4130-forked-m6hov

### To Reproduce

https://codesandbox.io/s/irp9w

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest|
| Browser          | Chrome |
| Operating System | Mac|

User report: https://github.com/ant-design/ant-design/issues/29545

**Comment by zombieJ** [comment]
hi @SaraVieira @CompuIves, could you pls help to take a look : )

**Comment by CompuIves** [comment]
Good point, I had to pin because babel runtime was broken for a while. I can unpin back in about an hour
