### ISSUE TITLE
why `npm run build` can not compile ts files

### ISSUE THREAD

**Issue by hongrunhui** [codesandbox/codesandbox-client#5544]
# 🐛 bug report

## Preflight Checklist

- [ ] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [ ] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I downloaded the repository but I can't run it

when I run `npm run build`, the packages/components always got errors like this:

![image](https://user-images.githubusercontent.com/9162319/109529781-008ed600-7af1-11eb-8b81-f9e05e14d202.png)

it is `tsc` to compile the ts files , but the ts file wrote wrong 

can you fix them ?

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by SaraVieira** [comment]
Hey

We use babel never tsc

Please follow the instructions here to build locally: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by hongrunhui** [comment]
OK, I got the build way like this (use yarn instead of npm i):

# nvm use 10

# 安装依赖
yarn

# 构建依赖库
yarn run build:deps

**Comment by SaraVieira** [comment]
okay perfect!

Yarn start will also run yarn:build:deps first :)
