### ISSUE TITLE
New error with emotion pragma: Pragma and pragmaFrag cannot be set when runtime is automatic.

### ISSUE THREAD

**Issue by maltenuhn** [codesandbox/codesandbox-client#5576]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
In new projects, adding emotion support for the jsx pragma leads to an error "pragma and pragmaFrag cannot be set when runtime is automatic". I don't know when this regressed.

It appears related to similar problems with Gatsby, Vercel (https://github.com/vercel/next.js/issues/18461) and ThemeUI (https://github.com/system-ui/theme-ui/issues/1160). Root cause seems changes in Babel (?) (https://github.com/babel/babel/pull/11324) , but I'm not clear what the work-around for Codesandbox should be 

## How has this issue affected you? What are you trying to accomplish?
I'm trying to use the Emotion pragma

### To Reproduce

1. Add `@emotion/react` npm package to a new Codesandbox React Template project.
2. Insert the following lines at the top of the file:
```
/**@jsx jsx */
import { jsx, css } from "@emotion/react";
import React from "react";
```

Expected: works
Actual: fails with `Pragma and pragmaFrag cannot be set... ` error

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |a80797ffc (default as of 10 March 2021)
| Browser          | Chrome, latest as of 10 March 2021
| Operating System | MacOS

**Comment by DeMoorJasper** [comment]
Seems to be working now
