### ISSUE TITLE
Import & Fork doesn't work for private GitHub repos

### ISSUE THREAD

**Issue by CompuIves** [codesandbox/codesandbox-client#5578]
If you go to the import wizard, and try to import using the wizard here:

![image](https://user-images.githubusercontent.com/587016/110640769-81b13180-81b1-11eb-9858-b059dd113fd2.png)

You will get an error that the repo cannot be imported in some cases. This is because you're missing the additional GitHub authentication. If you go directly to the URL generated by that form (https://codesandbox/io/s/github), we show a better error message asking you to sign in with additional permissions. I think a good first solution to this would be to redirect to the page if the importing fails, because then we at least show a better error message if the import fails because of lack of permissions.

**Comment by Eventect** [comment]
I am experiencing the same issue. Additionally, on https://codesandbox/io/s/github/reponame, I get a "Request failed with status code 500" message.
Any workaround or solution?

**Comment by quentinlagache** [comment]
Same issue. I try to import a private repo using [https://codesandbox.io/s/github/username/reponame](https://codesandbox.io/s/github/) and get a "Request failed with status code 500" message everytime.

I am on the Personnal Pro plan and codesandbox seems to have full permissions on my private repo.

Any help on this @CompuIves ?

<img width="484" alt="Capture d’écran 2021-04-05 à 11 05 52" src="https://user-images.githubusercontent.com/15960401/113558271-a4dbcf00-95ff-11eb-88d8-aa3bbbb6f73c.png">
<img width="791" alt="Capture d’écran 2021-04-05 à 11 07 40" src="https://user-images.githubusercontent.com/15960401/113558274-a60cfc00-95ff-11eb-99ad-ce001a7e4395.png">

**Comment by sbinlondon** [comment]
@CompuIves @Eventect @quentinlagache We recently made some changes to our Github import that might fix this. I just tried importing one of my repos and it went fine. Please let me know if y'all are still running into the 500 error.

**Comment by quentinlagache** [comment]
> @CompuIves @Eventect @quentinlagache We recently made some changes to our Github import that might fix this. I just tried importing one of my private repos and it went fine. Please let me know if y'all are still running into the 500 error.

I confirm that it solved the issue on my side too ! Thanks @sbinlondon and your team

**Comment by tylerc137** [comment]
I am hitting the same error right now, anybody facing the same issue? Importing private repo, confirmed CodeSandbox permissions both are granted

**Comment by quentinlagache** [comment]
> @sbinlondon I am hitting the same error right now, anybody facing the same issue? Importing private repo, and confirmed CodeSandbox permissions both are granted

This feature is limited to paid plan only. You can take a look to available features on the [codesandbox pricing page](https://codesandbox.io/pricing)

If you're already on a paid plan, it should work find once codesandbox have full permissions on github's private repos.

**Comment by tylerc137** [comment]
Am on Personal Pro plan, is that sufficient?

**Comment by quentinlagache** [comment]
> @quentinlagache Am on Personal Pro plan, is that sufficient?

Sure, I'm on the same plan and works like a charm. Maybe you can try to reset the permission of the codesandbox application on your GitHub account and redo the permission process.

**Comment by tylerc137** [comment]
After revoking permission from Github, importing in codesandbox I'm getting 
{"errors":{"detail":["Bad credentials"]}} , which is correct.

After that I re-link my github account on codesandbox, and its getting the same error 500

Network inspect shows the url starts with `https://codesandbox.io/api/v1/sandboxes/fork/github/tylerc137` , 
meaning its codesandbox side's API throwing 500 error .. might not be related to Github

**Comment by tylerc137** [comment]
I finally get it working. 

Instead of importing an existing project, I tried 
- Create an empty private project in Github and import into code sandbox
_(to make sure both Pro and Codesandbox permission is working)_
- Manually copy and paste from my existing project, file by file, folder by folder into that project

All good, until i come to a file which has the following gibberish
<img width="401" alt="Screenshot 2021-07-07 at 9 35 00 AM" src="https://user-images.githubusercontent.com/86952204/124687367-52b08f80-df07-11eb-9bdc-684ddec186b9.png">

Once delete the said code, all is working well.

Just leaving it here in case anybody encounters the same error.

To simulate, the said code in base64 is UXrvv73vv70= . Convert base64 to string using encode/decode vscode plugin to get the actual string.

**Comment by sannek** [comment]
Hi, glad to hear you got it working somehow - apologies for the trouble.

Thank you so much for the elaborate report, that will be a lot of help for us to investigate what is going wrong with the string parsing here.
