### ISSUE TITLE
Sometimes page is not loaded 

### ISSUE THREAD

**Issue by cihadturhan** [codesandbox/codesandbox-client#5581]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Sometimes page is stuck with loading screen
![image](https://user-images.githubusercontent.com/3739536/110715147-beaf0f80-8215-11eb-82e5-6c63c03301b9.png)

## How has this issue affected you? What are you trying to accomplish?
I can't use it.

### Link to sandbox: [link]() (optional)

- Go https://codesandbox.io/s/m94xb
Here is the console log
![image](https://user-images.githubusercontent.com/3739536/110715213-da1a1a80-8215-11eb-8b6a-3f0d04abd604.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Current live version
| Browser          | Chrome
| Operating System | Mac OS (Catalina)

**Comment by andrasbacsai** [comment]
It looks like the repository has been moved from https://github.com/react-spring/react-postprocessing to https://github.com/pmndrs/react-postprocessing (or at least it redirects me to the new one).

If I clone the new repository, it works.

**Comment by cihadturhan** [comment]
Closing it's related to that repository
