### ISSUE TITLE
[Embed Mode] Forced Collapsed Editor section in Bootstrap Tabs

### ISSUE THREAD

**Issue by GrapeCityKR-Marketing** [codesandbox/codesandbox-client#5597]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Code editor section of Embedded CodeSandBox.io editor in iframe is automatically collapsed with Bootstrap tab container. 

## How has this issue affected you? What are you trying to accomplish?

if end user goes to the second tab of bootstrap containing Embed CodeSandbox editor, it only shows preview section, not code editor section.

### To Reproduce

Test link:
https://codepen.io/GrapeCity-Korea/pres/yLVrorJ

Image:
![Bootstap_Tab_issue](https://user-images.githubusercontent.com/57697032/111559415-d1a47f80-87d3-11eb-9889-7733ee1f8478.gif)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by CompuIves** [comment]
Hello! Could you maybe share the CodeSandbox link as a reproducable?

**Comment by GrapeCityKR-Marketing** [comment]
> Hello! Could you maybe share the CodeSandbox link as a reproducable?

Hello :)
I thank you for your support
Here is the link for you to replicate the issue.

- https://jm5ov.csb.app/
- https://codesandbox.io/s/iframe-bootstrap-issue-jm5ov

**Comment by andrasbacsai** [comment]
Thanks for the example! We will investigate!
