### ISSUE TITLE
Update TypeScript to 4.2+

### ISSUE THREAD

**Issue by acd02** [codesandbox/codesandbox-client#5598]
# 🌈 Feature

Hello, would it be possible to bump the TS version used by the editor to 4.2+ please, to avoid some false positive errors to occur ^^

**Comment by andrasbacsai** [comment]
Hey, could you please show us some false positive errors? IMO, downgrading is not a good option.

**Comment by acd02** [comment]
Actually, I can't seem to be able to reproduce those errors 😅

But I was talking about upgrading, not downgrading (actually, the editor uses TS@4.1.2)

**Comment by andrasbacsai** [comment]
Ah sorry, I misunderstood that. Ooops.

**Comment by satanTime** [comment]
There is a working project which fails on codesandbox: https://codesandbox.io/s/github/ng-mocks/examples?file=/src/test.spec.ts

The same project on SB works (but requires optional dependencies): https://stackblitz.com/github/ng-mocks/examples?file=src/test.spec.ts

**Comment by satanTime** [comment]
Aha, so in my case it was actually about core-js: `3.11.3` works correctly, `3.12.0` is broken.

**Comment by rayfoss** [comment]
Here is a small sampling of the litter of false-possitive flags that almost make me want to disable IDE typechecking... these are caused when I use node12 in compilerConfig.module and/or moduleResolution. These errors don't occur on the up to date version of TypeScript that the container is actually running:

![Screenshot 2021-10-07 19 53 25](https://user-images.githubusercontent.com/876076/136481861-43eb42d0-a563-4c67-bfdb-13860e7af614.png)
![Screenshot 2021-10-07 19 50 11](https://user-images.githubusercontent.com/876076/136481864-a7531567-6aa4-45c4-8d25-23dab1bfdf30.png)

**Comment by JamesACS** [comment]
Hey @rayfoss - We've now pushed a fix for this - please could you confirm whether everything is working as expected now? :)

**Comment by Shakeskeyboarde** [comment]
Well, it's now using 4.4.4, which is nice. But it's still ignoring the version included in the `dependencies`/`devDependencies`. I think the long term solution would be to use that version, no?

**Comment by acd02** [comment]
I think this issue can be closed, since TS has been upgraded to v4.4.4 👍 

Now ofc, it would be even better if one could select the TS version of its choice, but it's discussed in #942

**Comment by JamesACS** [comment]
Thanks @acd02 - I've got being able to change the version as a feature request on our end as well :)
