### ISSUE TITLE
Magically not rendering my react components, the next day I opened my files.

### ISSUE THREAD

**Issue by Devil-codes** [codesandbox/codesandbox-client#5599]
# 🐛 bug report

## Preflight Checklist

- [ x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [ x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [ x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Out of nowhere , my react components are not getting rendered and only showing a blank page.
Its not only with one file or folder but all my drafts are not rendering any code that I had previously wrote.

## How has this issue affected you? What are you trying to accomplish?
I had all my codes in the sandbox , I like CodeSandbox and dont wanna go creating react app locally . If solved that will be awesome.

### To Reproduce
![Screenshot (28)](https://user-images.githubusercontent.com/63944778/111810059-9bfab600-88fb-11eb-8876-a7200846fbd2.png)

### Your Environment

| Software         | Name/Version |
|React | 17.0.1 |
| Сodesandbox      |
| Edge          |
| Windows 10 |

**Comment by sannek** [comment]
Hi! We had a bit of an issue just now, but as far as we can tell it has been resolved. Could you try reloading and seeing if it works again. If the version number in the bottom left says `f98ee776a` (instead of the `950...` in your screenshot), you're on the most recent version that should work just fine.
Let me know if anything is still wrong? 
Thanks

**Comment by Devil-codes** [comment]
> Hi! We had a bit of an issue just now, but as far as we can tell it has been resolved. Could you try reloading and seeing if it works again. If the version number in the bottom left says `f98ee776a` (instead of the `950...` in your screenshot), you're on the most recent version that should work just fine.
> Let me know if anything is still wrong?
> Thanks

You guyz are awesome!!!!! Its working perfectly...Admire your work and keep it up 💯

**Comment by sannek** [comment]
Glad it works again! Closing thos one now :)
