### ISSUE TITLE
create repo in github showing Not Found error

### ISSUE THREAD

**Issue by thoushif** [codesandbox/codesandbox-client#5638]
# 🐛 bug report

## Preflight Checklist

- [ ] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [ ] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [ ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by andrasbacsai** [comment]
Hey, can you please share the sandbox link, so we can start investigating?

Thanks in advance.

**Comment by SiddheshKukade** [comment]
### refresh you stupid @thoushif

**Comment by thoushif** [comment]
My apologies. Repo is private in git. So the error. 

Basically the message is not good. We can close the issue.
