### ISSUE TITLE
[Feature]: default new project template

### ISSUE THREAD

**Issue by sag1v** [codesandbox/codesandbox-client#564]
Hi, Thanks for this great tool.

Is there a way we can configure or create a default project snippet instead of the built in one?  
For example, i often find myself editing the default react `App` component from a stateless component to a `class` component with a `state` etc.

I would love to configure my own starting template or maybe even have some snippets of code.

**Comment by lbogdan** [comment]
A workaround I use is to have "template" sandboxes from which you then fork. The only drawback is that sometimes I open a "template" sandbox and forget to fork it, so I end up overwriting the template, so it needs some getting used to, but over all it works.

**Comment by CompuIves** [comment]
I think we could have the 'Mark as Template' functionality. Wouldn't be too
hard to build too.

**Comment by lbogdan** [comment]
So that when you open it, make changes and save, it should automatically fork it?

**Comment by sag1v** [comment]
@lbogdan This is exactly what I'm doing and exactly the problems i face with this approach.  
I end up overriding the "template". 😞

**Comment by sag1v** [comment]
@CompuIves Sounds great, you will need a special "Edit Template mode" though.

**Comment by CompuIves** [comment]
> So that when you open it, make changes and save, it should automatically fork it?

Yep, and we could also show all 'marked' as templates sandboxes when you open 'Create New Sandbox' modal 😄

**Comment by sag1v** [comment]
Is anyone working on this feature yet? 
Is there something i can help with? 🙂

**Comment by CompuIves** [comment]
I think this is the perfect time to start building this feature!

No one started yet, so feel free to start @sag1v!

I think what we need is a new switch in the Project sidebar, called 'Mark as template'. When you change the switch we should do a `POST` call to 

`/api/v1/sandboxes/:id/template` with body `{ "template": true/false }`. I can write the backend for it in the meantime.

The next step would be to add them to the `new sandboxes` list, but let's do the first step first 😄

**Comment by sag1v** [comment]
@CompuIves Ok, i just started the process [you can take a look](https://github.com/sag1v/codesandbox-client). 
I hope it will go as expected as i never used `mobx` nor `Cerebral` :thinking:

**Comment by sag1v** [comment]
@CompuIves Did you take a look? let me know if this is going in the write direction...

**Comment by lbogdan** [comment]
@sag1v Can you please create a PR for this, as it would be easier to follow?

**Comment by sag1v** [comment]
@lbogdan oops i was sure i created it already. anyway PR created #816
