### ISSUE TITLE
Deleting the folder causes the file which name is similar to the one be disappeared.

### ISSUE THREAD

**Issue by vantm** [codesandbox/codesandbox-client#5640]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

When I delete a folder and if there is any file that has a similar name to its name (exclude the extension), they are disappeared until I refresh the browser.

### To Reproduce

1. Create a folder
2. Create some files that have a similar name to the folder (for instance, `randomName.js`, `randomName.css`, etc)
3. Delete the folder

Actual: all the files are disappeared.

https://user-images.githubusercontent.com/6279921/113857260-7f4ff080-97cc-11eb-9b33-199627c011e0.mp4

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 64d938c3a
| Browser          | Edge Version 89.0.774.68 (Official build) (64-bit)
| Operating System | Windows 10 Pro

**Comment by andrasbacsai** [comment]
That is weird! We will take a look at this one!

**Comment by andrasbacsai** [comment]
We fixed it with #5675, so I'm closing this for now.

If you have any questions, just let us know.
