### ISSUE TITLE
Unable to create the repo. Please refresh and try again or report issue.  Repository creation failed

### ISSUE THREAD

**Issue by volta2016** [codesandbox/codesandbox-client#5643]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem:

![Screen Shot 2021-04-08 at 17 34 50](https://user-images.githubusercontent.com/20877256/114102575-8858c480-9895-11eb-9265-1c35aaf26573.png)
Hello team, and you let me create repositories or make the first commit, I already gave you the respective authorization, you can help me with this problem

## How has this issue affected you? What are you trying to accomplish?

it won't let me commit I get the following error

Unable to create the repo. Please refresh and try again or report issue. Repository creation failed

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by volta2016** [comment]
Hello I need help to solve this issue please.


[image: volta2016munoz99639] ***@***.***> *Giovanni
Muñoz*

Desarrollador Web
<https://github.com/volta2016>
+56920095168https://voltauxui.cl

**Comment by volta2016** [comment]
I need a solution for this soon, please always work with codesanbox to do
my tests, but it won't let me commit, I already synchronized it with
github, and I get that message.


[image: volta2016munoz99639] ***@***.***> *Giovanni
Muñoz*

Desarrollador Web
<https://github.com/volta2016>
+56920095168https://voltauxui.cl

**Comment by andrasbacsai** [comment]
Hey, we are already investigating the problem!

**Comment by volta2016** [comment]
> > Software Name/Version
> > Сodesandbox
> > Browser
> > Operating System

https://codesandbox.io/s/context-practice-itwu4
codesanbox
chrome
Mac osx Mojave 10.14.6


[image: volta2016munoz99639] ***@***.***> *Giovanni
Muñoz*

Desarrollador Web
<https://github.com/volta2016>
+56920095168https://voltauxui.cl

**Comment by volta2016** [comment]
@andrasbacsai thanks I remain pending

**Comment by nocksock** [comment]
I just had the same issue. I tried to create a repo (fork of docusaurus) with a domain-like name (eg: `example.wiki`). That did not work. However `examplewiki` worked. Hope that helps either as a workaround or for investigation. Seems like it has issues with `.` in the name.

**Comment by volta2016** [comment]
Thanks, I'll try if it works out @nocksock

**Comment by lbogdan** [comment]
Hey @volta2016 ,

Did you get a change to try @nocksock 's suggestion? Is this still an issue for you?
