### ISSUE TITLE
Simplify adding multiple dependencies

### ISSUE THREAD

**Issue by pshrmn** [codesandbox/codesandbox-client#565]
Currently, dependencies must be added one at a time, which leads to the dependency modal opening and closing multiple times. It would be nice to queue a number of dependencies to be added at once to simplify this workflow.

**Comment by lbogdan** [comment]
Would showing a notification that the package has been added and not closing the dependency modal after that suffice?

**Comment by pshrmn** [comment]
A notification would probably work too. My one concern with a notification is that I'm not sure how the user would indicate that they are done adding deps (so that the modal can be closed). With building a list of dependencies to add, I think that a "finish" button would make sense to add to the flow.

![modal-idea](https://user-images.githubusercontent.com/1127037/36353679-06126dce-148f-11e8-9dbf-6a4730420d72.png)

**Comment by CompuIves** [comment]
Hmm, yes. I think we could do this in the dependency window:

<button>Add Dependency</button>
          or
<input>dependency names</input>

This way users have a choice to either search or enter directly.

**Comment by Saeris** [comment]
Added this to our public backlog. You can view the progress of this request here:

https://www.notion.so/Allow-Adding-Multiple-Dependencies-at-once-9bf613b8fdf6431997e50f018caebaa2
