### ISSUE TITLE
Could not load the source sandbox for this GitHub sandbox, please refresh or report the issue. API rate limit exceeded for app ID ##########.

### ISSUE THREAD

**Issue by rohan9896** [codesandbox/codesandbox-client#5655]
# 🐛 bug report

## Preflight Checklist

- [ ] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [ ] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [ ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by andrasbacsai** [comment]
Hey, sorry about this. We are aware of our Github Integration issue and we are working on it.

**Comment by rohan9896** [comment]
It automatically worked after some time! Thanks

**Comment by rafgraph** [comment]
@andrasbacsai I'm still having this issue.
`API rate limit exceeded for app ID #############`
For example: https://codesandbox.io/s/github/rafgraph/react-interactive/tree/main/demo

**Comment by andrasbacsai** [comment]
Yeah, we are continuously investigating the cause. Github API has some rate limits, but we are implementing some workarounds which could help in these kinds of issues.
