### ISSUE TITLE
Text appears twice in the terminal.

### ISSUE THREAD

**Issue by swapnadeepmohapatra** [codesandbox/codesandbox-client#5674]
# 🐛 bug report

While using the bash terminal in the codesanbox, the text appears twice. While typing as well as the log messages, it appears twice.

![Screenshot 1](https://user-images.githubusercontent.com/41564532/115137738-6e617380-a045-11eb-8739-e273ee13864d.jpeg)
![Screenshot 2](https://user-images.githubusercontent.com/41564532/115137742-73262780-a045-11eb-849e-b2d5fbaddb34.jpeg)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Browser          | Chrome |
| Operating System | Windows |

**Comment by LeadDreamer** [comment]
In my experience, it indicates the container hasn't successfully started.

**Comment by alexnm** [comment]
hi @swapnadeepmohapatra, can you please let us know if this still happens to you? and maybe share with us your sandbox? or is this behavior happening on all container sandboxes?

**Comment by swapnadeepmohapatra** [comment]
Hi @alexnm , I checked again. The issue is not reproducing again.

**Comment by fish-404** [comment]
I meet the same issue. 
And this issue occurs sometimes. I can't be solved even when I open a new terminal. 
But if I reload the whole CodeSandbox page, it almost return normal behavior.
