### ISSUE TITLE
EFF PrivacyBadger blocks it on Medium by default, but not GitHub gists

### ISSUE THREAD

**Issue by benatkin** [codesandbox/codesandbox-client#568]
I added an embed to Medium and it wasn't working, and I found it was because of EFF's Privacy Badger. It doesn't block GitHub gists so I think maybe there's a way they have to keep track of legit embedded documents like CodeSandbox vs share buttons. [Here's my post which fails to load CodeSandbox with the default Privacy Badger settings.](https://medium.com/@batkin/making-an-infinity-symbol-with-svg-6ec50cc8074d)

**Comment by rakannimer** [comment]
Hey !

I get this error too when in publishing mode. 

Gists works as expected. 

I attached screenshots below in case it helps.

<img width="667" alt="screen shot 2018-09-07 at 3 06 58 pm" src="https://user-images.githubusercontent.com/1270909/45218293-cb9ec100-b2af-11e8-9c99-387fd195d10b.png">
<img width="620" alt="screen shot 2018-09-07 at 3 05 57 pm" src="https://user-images.githubusercontent.com/1270909/45218294-cb9ec100-b2af-11e8-8a2f-708ddeedb5c8.png">

**Comment by CompuIves** [comment]
I really don't know what we need to do here. We do comply with the DNT Policy to my knowledge, I will send Medium an email asking how we can comply.

**Comment by jlarmstrongiv** [comment]
@CompuIves any update on that email to Medium?

I found a codepen [tweet](https://twitter.com/codepen/status/586536926473285634?lang=en) about how they become an embedly [provider](https://embed.ly/providers/new) for medium.

**Comment by CompuIves** [comment]
Yes, we're an Embedly provider as well. Privacy Badger flagged us because some sandboxes (so user-written code) save cookies. I'm not sure if we can anything about this, as we can't restrict users from writing cookies when DNT is disabled.
