### ISSUE TITLE
`Run all Test` & `Toggle file watching` button is not working.

### ISSUE THREAD

**Issue by Rakhisharma** [codesandbox/codesandbox-client#5685]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I am trying to run test for a small sandbox, When I click on any of `Run all Test` & `Toggle file watching` button, nothing happens. UI seem to say running Test Suites for forever, even if I refresh the code-sandbox or reopen it.

<img width="276" alt="Screenshot 2021-04-20 at 18 12 51" src="https://user-images.githubusercontent.com/9638740/115429818-10c75580-a204-11eb-9589-a7f70b7f6217.png">

### To Reproduce

Click on any of these buttons `Run all Test` or `Toggle file watching` in these examples [[1]](https://codesandbox.io/s/wq2lmm3378?from-embed) and [[2]](https://codesandbox.io/s/affectionate-fast-23fnb?file=/src/Demo.tsx): 

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Browser          | FireFox and Chrome
| Operating System | Mac OS 10.15.5

**Comment by hco** [comment]
This does even happen in the example repo that is linked in the [docs about testing](https://codesandbox.io/docs/tests): https://codesandbox.io/s/n9m2w9q8x0

I think it was working ~20 hours ago.

**Comment by ofergoli** [comment]
Looks like the issue resolved suddenly.. you can check the test jest example page at codesandbox

**Comment by Rakhisharma** [comment]
Closing it, as it seems to be resolved. Thank you code sandbox team anyway, for your amazing work on code-sandbox :)
