### ISSUE TITLE
Support _redirects file when deploying to netlify

### ISSUE THREAD

**Issue by bensoutendijk** [codesandbox/codesandbox-client#5686]
# 🌈 Support _redirects file when deploying to netlify

When deploying a SPA framework to netlify, one must add a `_redirects` file with proper rules to redirect requests to `/index.html` so that the SPA can use the browser history routing

When deploying to Netlify from CSB, include any file named `_redirects` or `netlify.toml` in the ZIP file exported to Netlify.

**Comment by smhutch** [comment]
Thanks for this request @bensoutendijk 🙂

Do you have an example sandbox which we can use to look into this?

**Comment by bensoutendijk** [comment]
https://codesandbox.io/s/netlify-deploy-fsltz?file=/src/index.js

This sandbox has an example `_redirects` file. When I go to netlify.com and download the zip file that was deployed, the `_redirects` file is not included.

You can also see that the redirects don't work by visiting the site https://csb-fsltz.netlify.app/foo

**Comment by andrasbacsai** [comment]
Thanks for the example. I will implement it and let you know when it's ready to be tested.

**Comment by andrasbacsai** [comment]
I've deployed a new version, which supports the `_redirects`.
Tested it with https://csb-8p8n8.netlify.app/ (https://codesandbox.io/s/netlify-deploy-forked-8p8n8)

Could you please test it as well @bensoutendijk?

**Comment by lbogdan** [comment]
Closing this as implemented in #5834 .

Please re-open or comment if it doesn't work as expected.
