### ISSUE TITLE
Cursor jumps to line beginning

### ISSUE THREAD

**Issue by chexxmo** [codesandbox/codesandbox-client#5697]
Hi,
I'm using codesandbox and I have a problem which is really bothering me.
When I press the enter/return key, the cursor always jumps to the beginning of the line. But it should jump to a different position depending on its previous position. For example, it the code snippet below, after the closing curly braces the cursor should be one the position as the curly braces. But instead it jumps with a short delay always to the very beginning of the new line.
And if I press the tab key, it automatically goes back again to the beginning of the line.
How can I fix it?
Thank you and kind regards.

      .page-intro {
        margin-bottom: 20px;
        background-color: lightblue;
        padding: 5px 2px 5px 15px;
      }

**Comment by CompuIves** [comment]
That's very weird... Could you share what browser and operation system you're experiencing this on?

**Comment by lbogdan** [comment]
Hey @chexxmo ,

Can you please provide a bit more information about your environment - operating system, browser etc.? Thanks!

**Comment by sbinlondon** [comment]
This happens due to autoformatting when autosave is turned on. We've recently turned autosave off as it was causing some issues, so this shouldn't happen anymore unless you turn it back on in your user settings in the editor.
