### ISSUE TITLE
InvalidCharacterError Failed to execute 'createElement' on 'Document': The tag name provided ('%=') is not a valid name.

### ISSUE THREAD

**Issue by 9mm** [codesandbox/codesandbox-client#5700]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

A vanilla Vue 3 sandbox from the homepage produces the following Error:

```
InvalidCharacterError
Failed to execute 'createElement' on 'Document': The tag name provided ('%=') is not a valid name.
```

## How has this issue affected you? What are you trying to accomplish?

I cannot use any sandboxes I've created.

### To Reproduce

Here's an existing sandbox, but it works with a 100% fresh Vue 3 one as well.

https://codesandbox.io/s/2-forms-vee-issues-ncy2c

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome latest
| Operating System | OSX latest

**Comment by DeMoorJasper** [comment]
Should be fixed with https://github.com/codesandbox/codesandbox-client/commit/08ea435bfb4cdf298e38f6ef713b6b3e5a5d95ae apologies for the inconvenience, will add vue 3 to our integration tests to prevent this in the future.
