### ISSUE TITLE
Getting run-time error for new next.js page file, but others work

### ISSUE THREAD

**Issue by kylemh** [codesandbox/codesandbox-client#5704]
# 🐛 bug report

## Preflight Checklist

- [X] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [X] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I forked a code sandbox. The existing Next.js page file routes work well, but a new one I'm trying to create seems to fail to transpile.

## How has this issue affected you? What are you trying to accomplish?

Just trying to create a repro for another bug in another library.

### To Reproduce

Go to `/` page and see no issue.
Go to `/login` page see the following run-time error: `TypeError: Object(...) is not a function`

### Link to sandbox: [link](https://codesandbox.io/s/swr-auth-forked-6q8s0?file=/pages/login.js)

**Comment by smhutch** [comment]
Thanks for reporting @kylemh. This is certainly an issue.

While testing I found that:

- The runtime error occurs because `useRouter` is undefined
- This is not a code problem, cloning the project and running locally it works fine

@DeMoorJasper is this something you can help out with? I wonder if this could be related to https://github.com/codesandbox/codesandbox-client/issues/5632

**Comment by DeMoorJasper** [comment]
I don't think this is a codesandbox issue, might just be an incompatible node_module that lives in node_modules of the sandbox but doesn't get downloaded? Or maybe even next.js cache?

To fix it I changed the dependency to "next": "10.2.0" and restarted the sandbox which causes a reinstall of node_modules and restart of the server. Not entirely sure how this all works internally, I think @lbogdan implemented most of the container sandbox logic
