### ISSUE TITLE
SVGs Briefly Display Then Dissapear

### ISSUE THREAD

**Issue by princefishthrower** [codesandbox/codesandbox-client#5722]
# 🐛 bug report

## Preflight Checklist

- [ X ] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [ X ] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [ X ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

SVGs in HTML markup render momentarily, then disappear.

## How has this issue affected you? What are you trying to accomplish?

I Expect the SVG to render as expected.

### Link to sandbox: [https://codesandbox.io/s/condescending-shaw-hge19?file=/index.html](https://codesandbox.io/s/condescending-shaw-hge19?file=/index.html)

This SVG is directly a copy-paste from the [MDN Web Docs on SVGs](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg), so I assume it is quite valid and should work everywhere, and you _do_ see the SVG flash for a second, if you refresh the in-client 'browser'. It then disappears after milliseconds.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Current Client Version? Not sure, see sandbox link |
| Browser          | Chrome 90.0.4430.85 (Official Build) (x86_64) |
| Operating System | OSX |

**Comment by DeMoorJasper** [comment]
Reverted changes to bundler that caused this, should be resolved once deploy is finished
