### ISSUE TITLE
Support GitHub branch as npm package

### ISSUE THREAD

**Issue by goranurukalo** [codesandbox/codesandbox-client#5725]
# 🌈 Feature

## What is this feature?

Currently when u wanna install some package from GitHub repository, u have ability to do it so by writing
```js
// package.json
{
 "dependencies": {
    "redux-injectors": "goranurukalo/redux-injectors",
  },
}
```
By default this grabs default (master) branch and use it.
All good and nice.

It would be nice if we can implement different <branch/commit/tag> etc... (jsdelivr supports all of this [jsdelivr](https://www.jsdelivr.com/?docs=gh))

## How the feature should work?

I would like to implement and provide PR in case this makes sense and that there was not issues while this was made or there are some issues that wasn't able to find

By quick search or check, file: [jsdelivr-gh.ts](https://github.com/codesandbox/codesandbox-client/blob/master/packages/sandpack-core/src/npm/dynamic/fetch-protocols/jsdelivr/jsdelivr-gh.ts) was right (or not 😅) place.

We can parse, extract values after hashtag and provide it to jsdelivr as specific field that they support.

This part of code where we can extend and provide value to "jsdelivr" to understand how and what to serve
I would like to know more about cache and stuff like that

## You have examples or an idea how it can be implemented? 

User/Developer is writing
```js
// package.json
{
 "dependencies": {
    "redux-injectors": "goranurukalo/redux-injectors#dev",
  },
}
```
And now it can use specific branch in codesandbox

`convertGitHubURLToVersion` function could filter out (by regex?) hashtag (`#`) 
and return always just repo name
and new function can be provided to extract value after hash and added as part of first argument `url` for `fetchWithRetries` method?

## My questions
-  caching of files (how it works for this app)
-  what about `JSDelivrGHFetcher.meta` method?

## End
Thank you for reading ❤️

**Comment by rezendeneto** [comment]
Plus, the request will fail when trying to set a version from a GitHub repository:

![image](https://user-images.githubusercontent.com/607961/118251737-5206fa00-b47e-11eb-9ee3-d9110f452364.png)

![image](https://user-images.githubusercontent.com/607961/118251768-5d5a2580-b47e-11eb-807c-85fea5ef802c.png)

As you can see, the package defined as `rezendeneto/apexcharts.js@3.26.3` produces a weird request, which I think is a bug: https://data.jsdelivr.com/v1/package/gh/rezendeneto/apexcharts.js@3.26.3@undefined/flat
