### ISSUE TITLE
prettify does not prettify within vue <template> 

### ISSUE THREAD

**Issue by bigstoef** [codesandbox/codesandbox-client#574]
This does behave the same as a clean setup of visual studio code with vetur locally, but locally it's configurable by adding: "vetur.format.defaultFormatter.html": "js-beautify-html"
to user or workspace (and probably project) settings. I Could not find any references to Vetur in the repository so not sure how the single file components are supported within codesandbox.

Is html formatting within vue sfc's possible and configurable in codesandbox? And if not might it be an option to add this and optionally make it configurable in the prettify settings?

**Comment by CompuIves** [comment]
Good one! I'm not sure how Vetur handles prettifying the HTML, it seems like it takes everything within template, runs the prettify and then puts prettified code back in there?

Hmm, the question is if we should write this functionality, or wait for Prettier to support it (https://github.com/prettier/prettier/issues/1882). If anyone's interested, we do prettifying here currently: https://github.com/CompuIves/codesandbox-client/blob/fix/remounting/packages/app/src/app/utils/prettify.js.

**Comment by sebastianmacias** [comment]
I have been waiting a long time for prettier to support this. If it isn't too much work I think an implementation like you mentioned:

> runs the prettify and then puts prettified code back in there

Would be very helpful. I have been looking for a web based IDE to work on Vue projects for a while and as far as I can tell this is currently the only important (for my needs) feature codesanbox is missing.

**Comment by SaraVieira** [comment]
Better late than ever but this does work now:

In your settings by using "js-beautify-html" or prettier in the Vetur settings

![CleanShot 2020-09-02 at 14 57 25](https://user-images.githubusercontent.com/1051509/91985094-a624e080-ed2c-11ea-97aa-5252886ba60d.png)
