### ISSUE TITLE
Can we add tailwind extension?

### ISSUE THREAD

**Issue by suhailibnnisar** [codesandbox/codesandbox-client#5757]
# 🌈 Feature

**Comment by smhutch** [comment]
@suhailibnnisar Please could you share some more details on what features you would find helpful when working with Tailwind?

**Comment by suhailibnnisar** [comment]
Hmm.. Most of the time I am using vscode to write code and there is an
official tailwind extension that helps me to
*autocomplete/autosuggest/IntelliSense*  *HTML/CSS class names*. If I could
use the same extension inside code sandbox as well it would be a whole
different experience.

**Comment by VladSez** [comment]
+1
this [extension ](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) will enable autocomplete, syntax highlighting, and linting, when using tailwindcss

**Comment by placu97** [comment]
any news?

**Comment by JamesACS** [comment]
Hey @placu97 - We're not actively working on this right now - but may return to it in the future
