### ISSUE TITLE
"Could not find module in path"

### ISSUE THREAD

**Issue by sAbakumoff** [codesandbox/codesandbox-client#5763]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

The error "Could not find module in path" occurs when I am trying to use our product in codesandbox

## How has this issue affected you? What are you trying to accomplish?

Can't build any samples with our product.

### To Reproduce

Open  and run https://codesandbox.io/s/vue-drillthrough-dynamic-11644?file=/src/App.vue
the error appears

It does not appear outside of the codesandbox

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | chrome
| Operating System | windows

**Comment by lbogdan** [comment]
The error is

```
ModuleNotFoundError

Could not find module in path: '@grapecity/activereports/lib/node_modules/@grapecity/ar-js-designer/index.js'
relative to '/node_modules/@grapecity/activereports/reportdesigner/index.js'
```

Seems related to #4456 .

**Comment by DeMoorJasper** [comment]
Issue is that the [packager](https://github.com/codesandbox/dependency-packager) ignores all node_modules folders, assuming they're actually node_modules and not a folder as part of a module, gonna look into this soonish.

Probably the same as #4456 .
