### ISSUE TITLE
Cannot install a package containing build metadata in its version

### ISSUE THREAD

**Issue by Andarist** [codesandbox/codesandbox-client#5768]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

In [semver's summary](https://semver.org/#summary) we can find that:
> Additional labels for pre-release and **build metadata** are available as extensions to the MAJOR.MINOR.PATCH format.

Later on, they describe what that build metadata is: https://semver.org/#spec-item-10

This is the first time that I've seen this in the wild but it seems that [some packages](https://browse.unpkg.com/browse/@react-aria/focus@3.0.0-nightly.1037/package.json) are using that and I actually wanted to update my repro case with its nightly build to check if the issue is resolved now

## How has this issue affected you? What are you trying to accomplish?

I couldn't use a valid package in my repro: https://codesandbox.io/s/kind-bouman-pmg43?file=/src/App.js

### To Reproduce

Try to install `@react-aria/focus@3.0.0-nightly.1037`

**Comment by smhutch** [comment]
Thanks for reporting @Andarist. Taking a look into why this is happening.

**Comment by DeMoorJasper** [comment]
Should be resolved by #5800
