### ISSUE TITLE
DependencyNotFoundError: cannot resolve package dependency

### ISSUE THREAD

**Issue by dabuside** [codesandbox/codesandbox-client#5773]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

It shows DependencyNotFoundError **v8** due to [this](https://github.com/babel/babel/blob/9e241fc18051731ed05722c62b9a0ec1905d86c8/packages/babel-core/src/transformation/util/clone-deep.ts#L1)
**v8** is not direct dependency of this project
The suggested solutions _add v8 as dependency_ works but it's nonsense
## How has this issue affected you? What are you trying to accomplish?

There should be no compile error.
It used to work fine.

### To Reproduce
Open that sandbox created by hzoo below

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  production            |
| Browser          |   chrome 90           |
| Operating System |     windows 7          |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by smhutch** [comment]
@dabuside are you still experiencing this issue? I haven't been able to replicate it at my end.

**Comment by DeMoorJasper** [comment]
Forgot to link the PR that fixes this https://github.com/codesandbox/codesandbox-client/pull/5792
