### ISSUE TITLE
Neovim doesn't work

### ISSUE THREAD

**Issue by Ironimus** [codesandbox/codesandbox-client#5781]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Vim: Enable Neovim option doesn't work. If Neovim Path is left unedited (just says `nvim`) I get this error:

![image](https://user-images.githubusercontent.com/8076719/118125951-51c81980-b400-11eb-8dd5-1771a75d52b7.png)

If I change it to where nvim is installed on my system it doesn't work either (though I doubt it could work like that):
![image](https://user-images.githubusercontent.com/8076719/118126084-7cb26d80-b400-11eb-8c4e-fe7f3692702f.png)

If CodeSandbox can't just support neovim, it'd make sense to remove this option from settings

## How has this issue affected you? What are you trying to accomplish?

Tried to use neovim integration

### Your Environment

Tried both on mac and windows pc

| Software         | Name/Version | Name/Version |
| ---------------- | ------------ | -----------|
| Сodesandbox      |  Production  |  Production  |
| Browser          |  Google Chrome Version 90.0.4430.212 (Official Build) (64-bit)  |  Google Chrome Version 90.0.4430.212 (Official Build) (x86_64)  |
| Operating System | Windows 10 64bit |  Mac OS Big Sur 11.3.1 (Intel based)  |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by smhutch** [comment]
Thanks for reporting @Ironimus. I looked into this today, and was able to replicate by:

1. Open preferences
2. Visit "Editor" tab
3. Click "Open VSCode settings"
4. Search for "neovim"
5. Enable

I agree that we should remove this option from the settings if possible. Do you know if we can configure those @CompuIves?
