### ISSUE TITLE
GitHub connected Next.js sandbox shows old (previously deleted) files. How to keep it up-to-date?

### ISSUE THREAD

**Issue by gremo** [codesandbox/codesandbox-client#5809]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Sandbox is connected to a GitHub repository but still shows (old) deleted files in the source folder. Files are visible only in the terminal. Is there something I did wrong? Of course I can delete the files manually using the terminal, but it feels odd to me.I tried to restart the sandbox and the server but nothing changed. **This happens only if I'm logged in**.

More precisely:

- [This commit](https://github.com/gremo/nextjs-boilerplate/commit/22b73b5534ed6e785a6b4c704eb48e357c1b48e7) deleted (or better, renamed) 3 files in the `pages` folder:
  -  `pages/_app.js` → `pages/_app.tsx`
  -  `pages/_document.js` → `pages/_document.tsx`
  -  `pages/index.js` → `pages/index.tsx`
- [The sandbox](https://codesandbox.io/s/github/gremo/nextjs-boilerplate/tree/master) is supposed to be up-to-date. The file browser shows the correct files in the  `pages` folder:

![Sandbox `pages` folder](https://user-images.githubusercontent.com/1532616/118956010-83d8fe80-b95f-11eb-84e6-c4995ddb25ae.png)

While the terminal reveals also the deleted `.js` files in `pages`:

![Sandbox `pages` folder in terminal](https://user-images.githubusercontent.com/1532616/118956308-c569a980-b95f-11eb-9731-38723b9bc072.png)

Actually, you'll se only 2 files because for testing purposes I deleted yesterday `index.js` files.

## How has this issue affected you? What are you trying to accomplish?

The sandbox, in fact, show errors about duplicate Next.js pages.

![Next.js error](https://user-images.githubusercontent.com/1532616/118957240-a4558880-b960-11eb-95e9-a8fd970809a7.png)

### Link to sandbox: https://codesandbox.io/s/github/gremo/nextjs-boilerplate/tree/master

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by smhutch** [comment]
Thanks for reporting @gremo. It certainly looks like the renamed files are not being properly removed.

Did you rename these files, and push the changes to the repo outside of CodeSandbox?

**Comment by lbogdan** [comment]
This is a known standing issue. The challenge here is that every container sandbox has a persistent storage, and because we're not actually using git to pull changes inside the container, we only update the changed files and create the new ones, but have no easy way to know which existing files were actually deleted from the repo.

**Comment by gremo** [comment]
@smhutch i only changed the repo :)
@lbogdan  Oh I see, so it's a known issue. Pretty confusing but i'ts ok :)

How can i completely "destroy" the storage so Codesandbox can recreate and possibly update all the files? In other words, what happens if I do an `rm -rf *` from the terminal? 😆

**Comment by lbogdan** [comment]
You can indeed do a `rm -rf /sandbox/*` and then "Restart Server" from the "Server Control Panel" in the sidebar, which will restart the container, copy back the files from the sandbox, install packages and start the dev server.

**Comment by gremo** [comment]
Thank you! I've removed and restarted the server. I guess I should close this issue since it's a known issue and a resolution doesn't exist yet?
