### ISSUE TITLE
Sandboxes from CI are not fetching dependencies

### ISSUE THREAD

**Issue by wyze** [codesandbox/codesandbox-client#5823]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I have been receiving this error when submitting PRs to my repo and visiting the sandbox url generated from sandbox ci:

> Could not fetch dependencies, please try again in a couple seconds: Cannot read property 'content' of undefined

If I go to import the same sandbox as a new URL everything works as expected: https://codesandbox.io/s/github/plouc/nivo/tree/master/examples/codesandbox

Here is the link to one of the affected CI runs: https://ci.codesandbox.io/status/plouc/nivo/pr/1538/builds/132648

`nivo` sandbox is the one erroring. The `nivo-website` sandbox still works correctly.

## How has this issue affected you? What are you trying to accomplish?

Trying to view the sandbox after CI runs.

### To Reproduce

Submit a PR to the plouc/nivo repo.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 72d987691    |
| Browser          | Chrome 90    |
| Operating System | macOS 10.15  |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by lbogdan** [comment]
Hey @wyze ,

Thanks for your report!

I can reproduce this, we'll take a look at it and get back to you.
