### ISSUE TITLE
Embed: empty file shows as folder

### ISSUE THREAD

**Issue by ofergoli** [codesandbox/codesandbox-client#5824]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
     adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## How has this issue affected you? What are you trying to accomplish?

When creating a sandbox using the define api with empty string as fileContent, codesandbox "thinks" its a folder and not javascript empty file

### To Reproduce
[Link to Sandbox with that issue with define api](https://codesandbox.io/s/define-api-xhr-request-forked-w8x3s?file=/index.js)

take the sandbox id and go to
http://codesandbox.io/embed/#id
to see the issue

This link shows an example for that, 
the generated sandbox with a js file looks like a folder that cannot open/close

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |              |
| Operating System |              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by lbogdan** [comment]
Hey @ofergoli ,

Thanks for your report!

Indeed, it seems to be a bug in the embed - the file is created fine, as you can see in this [API request](https://codesandbox.io/api/v1/sandboxes/bxire), it also shows fine in the [editor](https://codesandbox.io/s/bxire), but it shows as a folder in the [embed](https://codesandbox.io/embed/bxire). We'll take a look at this and get back to you.

**Comment by ofergoli** [comment]
Thanks a lot! (:
