### ISSUE TITLE
Codesandbox doesnt work and show no error or problems

### ISSUE THREAD

**Issue by baermathias** [codesandbox/codesandbox-client#5828]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
No error, no problem, but doesn't codesandbox doesn't work

## How has this issue affected you? What are you trying to accomplish?
Creating a small Vue.js application. But can't do it because of the error.

### To Reproduce
https://codesandbox.io/s/boring-shape-b4lgk

**Comment by lbogdan** [comment]
Hey @baermathias ,

Thanks for your report!

It works for me if I leave it to run a bit after it loads:

![image](https://user-images.githubusercontent.com/2083930/119342962-75ac1a80-bc9e-11eb-9977-68b7dfa385bd.png)

Can you please try that and get back to us?

**Comment by baermathias** [comment]
@lbogdan You are right, it works if you wait long enough. I had to click `Wait` multiple times on the below dialog, so I thought it would work anymore:
![Screenshot from 2021-05-25 07-25-22](https://user-images.githubusercontent.com/45003352/119444017-db45e880-bd2a-11eb-98bf-d82f17ecba15.png)
