### ISSUE TITLE
TypeScript declaration files are not used unless opened in the IDE

### ISSUE THREAD

**Issue by carlosbaraza** [codesandbox/codesandbox-client#5829]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
If a declaration file is created for a custom file extension, it would throw IDE errors unless the declaration file is opened in the IDE.

global.d.ts
```typescript
declare module "*.frag" {
  const value: string;
  export default value;
}
```

Throws error in the IDE:
![Screenshot 2021-05-24 at 12 58 06](https://user-images.githubusercontent.com/1270425/119344571-bb151b80-bc8f-11eb-9e57-1680cc186a9d.png)

However, if I open the declaration file, the error is not shown. The actual compilation never fails:
![Screenshot 2021-05-24 at 12 58 13](https://user-images.githubusercontent.com/1270425/119344663-d54ef980-bc8f-11eb-85e4-9136e6a305b8.png)

Checkout the Sandbox:
https://codesandbox.io/s/declaration-files-ts-not-working-cxol1?file=/src/index.ts

### To Reproduce
Checkout the following Sandbox.
https://codesandbox.io/s/declaration-files-ts-not-working-cxol1?file=/src/index.ts

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/declaration-files-ts-not-working-cxol1?file=/src/index.ts

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |      Chrome 90        |
| Operating System |        OSX      |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by lbogdan** [comment]
Hey @carlosbaraza ,

Thanks for your report!

I can indeed reproduce this, we'll take a look at it and get back to you.
