### ISSUE TITLE
Promise state is displayed incorrectly on the console

### ISSUE THREAD

**Issue by arunroy** [codesandbox/codesandbox-client#5830]
For the below code snippet, I have observed that the status of Promises are displayed as 'pending' whereas originally they are 'fulfilled'.
const recordVideoOne = new Promise((resolve, reject) => {
  resolve("Video 1 Recorded");
});

const recordVideoTwo = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve("Video 2 Recorded");
  }, 2000);
});

const recordVideoThree = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve("Video 3 Recorded");
  }, 5000);
});

Promise.all([recordVideoOne, recordVideoTwo, recordVideoThree])
  .then((response) => {
    console.log(recordVideoOne);
    console.log(recordVideoTwo);
    console.log(recordVideoThree);
  })
  .catch((error) => console.log("recording failed"))
  .finally(() => {
    console.log(recordVideoOne);
    console.log(recordVideoTwo);
    console.log(recordVideoThree);
  });

**Comment by lbogdan** [comment]
Hey @arunroy ,

Thanks for your report!

Can you please provide a sandbox with a minimal reproduction?

**Comment by arunroy** [comment]
Thanks for your reply @lbogdan , below is the link
https://codesandbox.io/s/agitated-wilbur-u49ch?file=/src/index.js

**Comment by lbogdan** [comment]
Thanks! This is most probably coming from the dependency we're using for the console - [console-feed](https://github.com/samdenty/console-feed), I'll open an issue there.

**Comment by arunroy** [comment]
Cheers! @lbogdan

**Comment by arunroy** [comment]
thanks for the info.
