### ISSUE TITLE
Dashboard Keyboard Shortcut Broken on Windows 10 (Ctrl+Escape opens Start Menu)

### ISSUE THREAD

**Issue by Saeris** [codesandbox/codesandbox-client#5831]
Exactly as the title says. The listed keyboard shortcut for the Dashboard page from the Editor doesn't appear to work. See attached screencap for example.

https://user-images.githubusercontent.com/3144549/119453490-563bde80-bcec-11eb-92e9-11f66956ba86.mp4

Tried this on a relatively fresh install, no hotkeys for the global OS have been modified. Browser used was Microsoft Edge. Same problem appears to happen in Firefox as well. Looks like CodeSandbox just isn't capturing the keyboard event.

**Comment by lbogdan** [comment]
Hey @Saeris , long time no see! 🙂 

`Ctrl+Escape` is an OS global shortcut in Windows that opens the Start Menu, and I'm pretty sure it can't be overridden, so this most probably never worked on Windows.

Not sure what can we do here - change the shortcut on all platforms? Change it only on Windows? What do you think?

**Comment by Saeris** [comment]
Hmm, yeah seems like changing the shortcut to something universal is the only option I can think of!

I wonder if there is some resource out there that lists global OS specific shortcuts like these so you can avoid them in the future.

Guessing you want to stick with something that isn't dependent on full keyboards either. One of my first thoughts for an alternative might be `Ctrl + Home`. Maybe `Ctrl + ~` could work too, given that it has a similar keystroke distance.

Whatever you go with, I believe consistency across platforms is going to be your best bet, so if you change it, change it for all platforms. Chalk it up as an oversight in the design process and take note on how to avoid it in the future!
