### ISSUE TITLE
CodeSandbox scripts injected before doctype declaration

### ISSUE THREAD

**Issue by rikschennink** [codesandbox/codesandbox-client#5832]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Somehow for a single index.html file the client injects the codesandbox <script> tags before the doctype declaration instead of in the `<head>`

The browser won't be able to read the doctype and will switch to quirksmode which will cause weird rendering issues.

Not sure why it happens with sandbox below as it doesn't happen with other sandbox. The sandbox below was originally created with the codesandbox API.

## How has this issue affected you? What are you trying to accomplish?

To prevent support ticks my library checks if the doctype has been set correctly, when I decided to use codesandbox to offer code sandboxes via API I noticed the library would warn about a missing doctype declaration. Which led me to find the script tags before the doctype declaration.

### To Reproduce

View source of the app frame:
https://codesandbox.io/s/script-inject-issue-4b93g?file=/index.html

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |    on codesandbox.io          |
| Browser          |         tested on Firefox, safari, and chrome     |
| Operating System |     macos         |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by lbogdan** [comment]
Hey @rikschennink ,

Thanks for your report!

I can indeed replicate this, it seems to be a bug in how we're injecting the scripts, indeed. We'll take a look at it and get back to you.

**Comment by rikschennink** [comment]
@lbogdan thanks for the super fast response! : )

**Comment by lbogdan** [comment]
@rikschennink You're welcome! I opened an issue in our API (private) repository. I'll keep this issue posted with any developments there.

**Comment by rikschennink** [comment]
@sbinlondon Is it fixed? Still see the issue on the example sandbox.

**Comment by sbinlondon** [comment]
@rikschennink sorry about that! I forgot Github eagerly closes linked issues. I merged it last night but it isn't deployed yet - I'll be doing that tonight, so please give it a test tomorrow morning.

**Comment by rikschennink** [comment]
@sbinlondon will do! Thanks for reopening! : )

**Comment by rikschennink** [comment]
@sbinlondon It's fixed, super impressed that this was resolved so quickly. ❤️

**Comment by rikschennink** [comment]
Forgot to close : )
