### ISSUE TITLE
Support Node LTS version

### ISSUE THREAD

**Issue by rayfoss** [codesandbox/codesandbox-client#5865]
# 🌈 Feature

Node 16 is missing... 15 added lots of extremely useful features.

```
"container": {
  "node": "16"
},
```

`FROM node:16-alpine`

**Comment by lbogdan** [comment]
We're currently testing node 16 on staging, if everything goes smoothly (which it should), will be deploying it sometime this week.

**Comment by lbogdan** [comment]
Just deployed this, please test it and let us know if it works for you. Here's an example sandbox: https://codesandbox.io/s/node-16-qumou .

Related documentation PR: #6107 .

**Comment by rayfoss** [comment]
I just came to scream in Joy about this...

- The UI still list it, but it works if you manually ask for it in the sandbox.config.json.
- Would be nice if `.nvmrc` was used as the configuration of node version.

**Comment by dcousens** [comment]
For Node 22, are you tracking support anywhere?
