### ISSUE TITLE
😆 you can't create multiple profiles

### ISSUE THREAD

**Issue by Explosion-Scratch** [codesandbox/codesandbox-client#5873]
You can only have one profile in the codesandbox preferences section `preferences and profiles`

**Comment by DeMoorJasper** [comment]
Thanks for the feedback!

Currently we only support one profile, this is mentioned in the docs with plans to add the ability to allow multiple profiles in the future https://codesandbox.io/docs/preferences

**Comment by Explosion-Scratch** [comment]
> Thanks for the feedback!
> 
> Currently we only support one profile, this is mentioned in the docs with plans to add the ability to allow multiple profiles in the future https://codesandbox.io/docs/preferences

Cool! Thanks!

**Comment by Explosion-Scratch** [comment]
Also what about default profiles? You know, after multiple profiles are added, then just signing in would apply your default profile.
