### ISSUE TITLE
setImmediate and window.setImmediate are different functions, and only window.setImmediate works correctly

### ISSUE THREAD

**Issue by panick-carousel** [codesandbox/codesandbox-client#5878]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
window.setImmediate allows args to be passed in, but the global setImmediate does not.  If indeed a global is to be provided to the environment, it should be exactly the same was window.setImmediate, or at the very least have the same signature and be able to execute arguments successfully.

## How has this issue affected you? What are you trying to accomplish?
I want to use setImmediate to call a function and pass arguments to it

### To Reproduce
Go to https://codesandbox.io/s/elegant-smoke-erz2n?file=/src/index.js and observe the flow execution in index.js.
This shows the difference between the two functions.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest             |
| Browser          | chrome latest              |
| Operating System |  win10 latest            |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by DeMoorJasper** [comment]
Thanks for reporting this issue, gonna look into this tomorrow
