### ISSUE TITLE
Sandboxes generated by CI fail to load dependencies with CORS error

### ISSUE THREAD

**Issue by ecraig12345** [codesandbox/codesandbox-client#5895]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Sandboxes created from codesandbox CI fail to load dependencies with a CSP error. 

## How has this issue affected you? What are you trying to accomplish?

I can't test my PR with codesandbox

### To Reproduce

1. Go to https://ci.codesandbox.io/status/microsoft/fluentui/pr/18545/builds/139219
2. Select the "Fluent UI Button" sandbox *(note: the other two are broken for unrelated reasons)*
3. Observe that the sandbox won't render and there are many CORS-related errors in the browser console, for example:
> Access to fetch at 'https://ata.codesandbox.io/api/v8/%40fluentui%2Freact-button%40https%3A%2F%2Fpkg.csb.dev%2Fmicrosoft%2Ffluentui%2Fcommit%2F332ff784%2F%40fluentui%2Freact-button.json' from origin 'https://codesandbox.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I tried the CI sandboxes linked from #5872 too and they had the same problem. (The actual issue raised there seems unrelated, it was just a convenient way to get sandboxes from another repo to make sure it wasn't an issue on my project's end.)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  ?            |
| Browser          | Chrome 90.0.4430.212, same in other browsers |
| Operating System | Mac OS 10.15.7 |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by alexnm** [comment]
Hi @ecraig12345 sorry for taking longer to get back, it seems that this was caused by a temporary glitch in the system.

**Comment by ecraig12345** [comment]
Seems like this is fixed now.
