### ISSUE TITLE
unrelated console warnings when using package depending on @babel/runtime

### ISSUE THREAD

**Issue by eps1lon** [codesandbox/codesandbox-client#5916]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Installing a package depending on `@babel/runtime` logs unrelated console warnings. These unrelated warnings sometimes trigger more often. I was only able to reliable reproduce the warnings when adding `@material-ui/core@4.x`

```
Measurement for 'resolve-async:@babel/runtime/helpers/interopRequireDefault:/src/index.js' was requested, but never was started 
Measurement for 'resolve-async:/node_modules/@babel/runtime/package.json:/' was requested, but never was started 
```

## How has this issue affected you? What are you trying to accomplish?

It clutters the console

### To Reproduce

1. Create a new codesandbox via https://react.new
2. Add `@material-ui/core` (4.x) as a dependeny.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |351b85fd9|
| Browser          |Chrome 91|
| Operating System |Ubuntu 20.04|

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by lbogdan** [comment]
Hey @eps1lon ,

Trying to reproduce this, and failing to with just the two steps provided. Do I need to actually require / import the package?

**Comment by eps1lon** [comment]
Seems like it was fixed since it was reported 3 months ago.
