### ISSUE TITLE
core-js >=3.12 throws errors `Target is not iterable`

### ISSUE THREAD

**Issue by satanTime** [codesandbox/codesandbox-client#5943]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Local usage of `core-js >= 3.12` doesn't have issues, whereas `codesandbox` throws `Target is not iterable`.

## How has this issue affected you? What are you trying to accomplish?

I try to keep dependencies up to date.

### To Reproduce

- go to [https://codesandbox.io/](https://codesandbox.io/)
- click on `Angular angular-cli`
- wait when the app has been rendered
* change in `dependencies` the version of `core-js` to `3.11.3`
* click refresh in the builtin browser
* wait when the app has been rendered
- change in `dependencies` the version of `core-js` to `3.12.0`
- click refresh in the builtin browser
- the error appears

if you download the project and run it locally, it works correctly.

**Comment by rocifier** [comment]
Maybe this is a combination of package versions because every version of core-js I try is broken with that error

**Comment by rocifier** [comment]
Nevermind, I wasn't hitting refresh every time. Confirmed it is broken since 3.12.0

**Comment by NickMitrokhin** [comment]
Hi, Any news?

**Comment by satanTime** [comment]
Hi @smhutch,

I hope this finds you well.

Could you provide a brief update on this issue?

**Comment by zloirock** [comment]
From this version, `core-js` does not accept not pretty correct third-party `Symbol` polyfills that break `core-js`, so it's a conflict with another polyfill.

**Comment by satanTime** [comment]
The thing which confuses me is that it actually works locally with the same setup, or on stackblitz. The only place I see this error is codesandbox.

**Comment by lbogdan** [comment]
@DeMoorJasper can you please take a look at this?

**Comment by DeMoorJasper** [comment]
Seems to work fine to me, can somebody create a reproduction?

**Comment by babich-a** [comment]
@DeMoorJasper  https://codesandbox.io/s/jovial-hawking-lx4oy (just change "core-js": "3.12.0", in package.json from angular template as in the first post said)

**Comment by satanTime** [comment]
@DeMoorJasper, I would assume you forgot to refresh the builtin browser manually.

**Comment by DeMoorJasper** [comment]
> @DeMoorJasper  https://codesandbox.io/s/jovial-hawking-lx4oy (just change "core-js": "3.12.0", in package.json from angular template as in the first post said)

Thank you I can reproduce it now, will look into (and hopefully fix) it tomorrow

**Comment by satanTime** [comment]
Hi @DeMoorJasper,

could you provide an update on the issue?

**Comment by DeMoorJasper** [comment]
@satanTime looking into it today, something came up, preventing me from looking into this a bit more

**Comment by satanTime** [comment]
Hi @zloirock should we create an issue in `core-js` repo regarding what @DeMoorJasper is proposing?

> the ideal solution would be that core-js doesn't rely on nodeJS globals if it's in a browser environment...

**Comment by zloirock** [comment]
@satanTime the problem is that NodeJS also could emulate browser environment. We couldn't just stop check the V8 version in feature detection because it will cause a critical slowdown (100x+) in some cases even if nothing is polyfilled because of V8 whims like [this](https://github.com/zloirock/core-js/issues/677). I'll try to add a workaround, but mainly it should be fixed on NodeJS polyfills side - it's their bug - `.v8` should not be `'0.0'` anyway.

**Comment by babich-a** [comment]
It seems core-js@3.19.1 has a fix for this problem. @zloirock can you confirm?

**Comment by zloirock** [comment]
Yes, I added a workaround for [this](https://github.com/jvilk/bfs-process/issues/5) `bfs-process` bug.

**Comment by DeMoorJasper** [comment]
Thank you for fixing this @zloirock 🙏 will close this issue

**Comment by zloirock** [comment]
@DeMoorJasper it could be better to specify the actual `core-js` version in dependencies.
