### ISSUE TITLE
Project works localy but does not work in codesandbox.io

### ISSUE THREAD

**Issue by babich-a** [codesandbox/codesandbox-client#5946]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

After upgrade the `devextreme` library some sandboxes stop working with angular framework.

### To Reproduce

[Here](https://codesandbox.io/s/cocky-cdn-qxpq6?file=/package.json) a simple example made from vanilla-typescript template.
It works with `devextreme@21.1.3`, but does not work with `devextreme@21.1.4` (you can change it in package.json). It works with `devextreme@21.1.4` too if I download the project and build it with `npm run build`.

In most cases, I have the following error in console (BrowserModule is included):
```
Unhandled Promise rejection: No ErrorHandler. Is platform module (BrowserModule) included? ; Zone: <root> ; Task: Promise.then ; Value: Error: No ErrorHandler. Is platform module (BrowserModule) included?
```

Sometimes I get the following error:
```
Cannot use import statement outside a module
```

The same issue I have in angular project https://codesandbox.io/s/jolly-aryabhata-q6dnr?file=/package.json made from condesandbox angular template.
Only dependencies were added to the package.json
```
    "devextreme": "21.1.4",
    "devextreme-angular": "21.1.4"
```
and import to the app.module.ts
```
import { DxButtonModule } from "devextreme-angular";
....
imports: [BrowserModule, DxButtonModule],
```

I understand that most likely the problem is in the `devextreme` library. But I can't understand where.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |    Chrome 91, FF 89         |
| Operating System |   Windows 10           |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by DokaRus** [comment]
Seems to be the same issue as #5943 (some dependencies use core-js >= 3.12

**Comment by babich-a** [comment]
Can be closed with https://github.com/codesandbox/codesandbox-client/issues/5943
