### ISSUE TITLE
GitHub sandbox not syncing, and cannot be deleted

### ISSUE THREAD

**Issue by glen-84** [codesandbox/codesandbox-client#5963]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

The sandbox is not in sync with the GitHub repo, and I'm also unable to delete it.

## How has this issue affected you? What are you trying to accomplish?

I want to sync the sandbox/template with the GitHub repository. Failing that, I'd like to delete it and import it again.

### To Reproduce

See the link below.

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/vue3-vuetify3-5u2i6

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 3a7183451             |
| Browser          | Chrome             |
| Operating System | Windows 10             |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by lbogdan** [comment]
Hey @glen-84 ,

The sandbox you linked to (https://codesandbox.io/s/vue3-vuetify3-5u2i6) doesn't exist anymore. Can you please link to the GitHub repository you're having issues with? Thanks!

**Comment by glen-84** [comment]
Hi @lbogdan,

András deleted it for me.

It was this repo: https://github.com/glen-84/vue3-vuetify3.

I see there is now a delete option for templates. I haven't updated this recently, so I'm not sure whether or not the syncing problem is resolved, but I think that you can close this issue for now.

Thanks.

**Comment by lbogdan** [comment]
Looks like it imports and runs fine, so I'm closing this for now. Please re-open if you encounter further issues.
