### ISSUE TITLE
console logging fails when passing a BigInt ("Do not know how to serialize a BigInt")

### ISSUE THREAD

**Issue by dfahlander** [codesandbox/codesandbox-client#5981]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

My application logs an object using console.debug() where it passes a string message as first argument and the object as second argument. Object has a property that is of type BigInt. The application fails with "Do not know how to serialize a BigInt".

## How has this issue affected you? What are you trying to accomplish?

Trying to sync data and log the flow to console.debug().

### To Reproduce

```ts
const obj = {
  foo: 3n
};

console.log(obj);
```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |      Current prod as of 2021-07-22        |
| Browser          |     Opera Version:77.0.4054.203 (x86_64)         |
| Operating System |    MacOS Big Sur 11.4          |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by dfahlander** [comment]
I figured out this is rather an issue with the console-feed library so I've posted the issue there also https://github.com/samdenty/console-feed/issues/90. Just that when it has been fixed there, make sure to upgrade the dependency here.

**Comment by steveluscher** [comment]
Hey Codesandbox. I fixed this in https://github.com/samdenty/console-feed/pull/122. Want to pull `console-feed@3.5.0` into the product so that we can get `bigint` support in the console?

**Comment by steveluscher** [comment]
cc/ @olarclara.
