### ISSUE TITLE
Sass import fails in CodeSandbox, but works locally

### ISSUE THREAD

**Issue by y-nk** [codesandbox/codesandbox-client#5996]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I've a small project which is a Vue app without eslint, but somehow i've a React error on screen mentioning about a broken sass import. When running the code locally, it works fine.

## How has this issue affected you? What are you trying to accomplish?

It makes my app not runnable. I'm trying to use this app to communicate changes with my customers.

### To Reproduce

1. Install bulma in a Vue project
2. import bulma in a sass file

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  The web one  |
| Browser          | Chrome latest |
| Operating System | macOS latest |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by smhutch** [comment]
@y-nk Thanks for reporting. I updated the issue description since I think this is a bundler error related to the differences between the `Sass` and `SCSS` syntaxes ([reference](https://sass-lang.com/documentation/syntax#the-indented-syntax))

@DeMoorJasper do you have any ideas about how we can improve support for cases like this?

**Comment by y-nk** [comment]
@smhutch thanks a lot for support :)

**Comment by DeMoorJasper** [comment]
Just had a look into this and it appears to be a bit more challenging than I originally thought, the importer api of dart-sass does not allow us to specify the syntax nor does it extract it from the returned filepath (if content is also returned, which we do).

Will probably be forking the dart-sass library, so this will take a bit longer than expected

**Comment by y-nk** [comment]
@DeMoorJasper Thanks for the update and from what you say I can see the hard work. I can imagine what it'll take, thanks again for the support.
