### ISSUE TITLE
TypeError Path must be a string. Received null

### ISSUE THREAD

**Issue by Instinctlol** [codesandbox/codesandbox-client#6002]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Since today I get the following error in a vue sandbox:
TypeError
Path must be a string. Received null

I didn't modify the code in any way, but on friday (2021-07-23) and the day before it worked without issues.

## How has this issue affected you? What are you trying to accomplish?

I'm trying to solve a vue slot rendering bug and need the sandbox to share the code with co workers or, if no one is able to find a solution, with the devs of vue, because I expect this to be a bug with vue.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |              |
| Operating System |              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by vinayakkulkarni** [comment]
Yep, I am facing the same issue – [Codesandbox link](https://codesandbox.io/s/v-mapbox-persist-geojson-layer-on-basemap-change-stqc5)

**Comment by vinayakkulkarni** [comment]
Why'd you close this? I can still see the error in my codesandbox.

Codesandbox version: 4ca3232f8

**Comment by Instinctlol** [comment]
@vinayakkulkarni it's probaby not live yet.

**Comment by vinayakkulkarni** [comment]
Ahh, I can see the CI/CD being run – https://circleci.com/gh/codesandbox/codesandbox-client/98138

nvm, will check in a bit and revert.

**Comment by CompuIves** [comment]
Oh apologies! I thought I left a comment but I didn't. The sandbox should now work as expected, could you confirm this? I'll open the issue for now, so that you can close it in case it's fixed now! 😄

**Comment by Instinctlol** [comment]
@CompuIves works for me :)

**Comment by vinayakkulkarni** [comment]
Works fine. Thanks @CompuIves 🍻
