### ISSUE TITLE
Sandbox container hangs on initialization

### ISSUE THREAD

**Issue by StephenBarlow** [codesandbox/codesandbox-client#6025]
# 🐛 bug report

## Description of the problem

Hi there! [This particular sandbox's](https://codesandbox.io/s/github/apollographql/docs-examples/tree/main/apollo-server/v3/subscriptions) container is failing to finish initializing. Forks of the sandbox initialize fine. (I saw another issue of this nature here and hope this isn't a horribly wrong place to report 😄 ) 

Thanks!

### To Reproduce

[Open the sandbox](https://codesandbox.io/s/github/apollographql/docs-examples/tree/main/apollo-server/v3/subscriptions)

**Comment by CompuIves** [comment]
Oh, very interesting, this looks like a cache issue! I'll let the team know.

**Comment by CompuIves** [comment]
This should be fixed now! We reset the cache, we'll investigate why this happened in the first place.

**Comment by StephenBarlow** [comment]
Thanks so much @CompuIves!
