### ISSUE TITLE
module resolution issue in vue3

### ISSUE THREAD

**Issue by eunjae-lee** [codesandbox/codesandbox-client#6046]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

My sandbox fails to run with "ModuleNotFoundError".

![image](https://user-images.githubusercontent.com/499898/129863717-910da367-9c7e-4b0c-b9f5-0b6f2c40c1b3.png)

When I download the sandbox as zip, it works locally.

* related tweet: https://twitter.com/eunjae_lee/status/1427637534738337805

## How has this issue affected you? What are you trying to accomplish?

It should successfully resolve the module and run.

### To Reproduce

Visit the sandbox, and you will see the error right away.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | e37e8f3a5             |
| Browser          | Firefox 91.0 (64-bit)             |
| Operating System | macOS BigSur 11.5.2              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by DeMoorJasper** [comment]
Hey, thanks for reporting this error, will look into this later today and keep you updated

**Comment by eunjae-lee** [comment]
Thanks :)

**Comment by DeMoorJasper** [comment]
Went digging into the errors and found this file, which our resolver stumbles on as it thinks it's a json file: https://unpkg.com/browse/vue-instantsearch@4.0.0-beta.1/dist/vue3/es/package.json.js

Fixed it in https://github.com/codesandbox/codesandbox-client/pull/6050

**Comment by eunjae-lee** [comment]
@DeMoorJasper thanks, it works fine!
