### ISSUE TITLE
Static file importing in npm package is not working

### ISSUE THREAD

**Issue by awmleer** [codesandbox/codesandbox-client#6048]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

https://codesandbox.io/s/antd-mobile-static-file-test-1vv0d?file=/src/App.tsx

In this sandbox I used the `ErrorBlock` component from package `antd-mobile`. In the [`ErrorBlock`](https://unpkg.com/browse/antd-mobile@5.0.0-alpha.15/es/components/error-block/error.js) component, there is a svg file import:

```
import DefaultErrorIcon from '../../assets/default.svg';
```

But when I render this component in codesandbox, this svg image gets 404.

![image](https://user-images.githubusercontent.com/16526078/129897572-0747adde-78db-4f46-83f9-acaf25e0ccd5.png)

![image](https://user-images.githubusercontent.com/16526078/129898011-d7feddc6-f03d-4801-9a24-1d44b9b74e1d.png)

## How has this issue affected you? What are you trying to accomplish?

I'm the maintainer of antd-mobile package. I'd like to make some demos about antd-mobile v5 alpha using codesandbox. But currently the svg images are broken.

### To Reproduce

Just use the sandbox link below.

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/antd-mobile-static-file-test-1vv0d?file=/src/App.tsx

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |   Chrome 92.0.4515.131    |
| Operating System |   macOS 11.5.2 |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by DeMoorJasper** [comment]
We run svg's through `svgr` when using the react template, not sure how we should go about resolving this as I assume react-scripts has the same issue?

cc @CompuIves

**Comment by awmleer** [comment]
Seems like the behavior of create-react-app is:

`import { ReactComponent as Logo } from './logo.svg';` will import the svg image as `Logo` component.
`import logo from './logo.svg';` will import it as file link.

**Comment by awmleer** [comment]
It works now! Thanks so much!
