### ISSUE TITLE
Unable to import React components between files

### ISSUE THREAD

**Issue by Isoaxe** [codesandbox/codesandbox-client#6059]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I'm attempting to create a component using the `react-modal` package. If I create the component in a seperate file and import it, the app produces an error. However, when I implement it directly within `<App />` (i.e. without creating a seperate component), there is no issue. 

## How has this issue affected you? What are you trying to accomplish?

I'm attempting to modularise an app so that each component can be in a seperate file, and imported as needed. Doing so prevents the app from building and causes an error.

### To Reproduce

I've built two near-identical projects forked from the same source. 

1. The first is called "Modal Implemented Directly". As the name suggests, `react-modal` is implemented directly from `<App />`. This works perfectly.

2. The second is called "Modal as Imported Component". This extracts the `react-modal` logic to a component called `<EventModal />` in a seperate file of the same name. It is then imported to `<App />`. This fails with an error.

The two projects are identical in every other respect. 

**Aside:** As I was building these project to demonstrate the issue, the failing app started working for a few minutes. It soon stopped and the error reappeared when re-run.

### Link to sandbox:

1. [Modal Implemented Directly](https://codesandbox.io/s/3q4wx?file=/README.md) (builds).

2. [Modal as Imported Component](https://codesandbox.io/s/modal-as-imported-component-ql9ql?file=/README.md) (fails).

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Browser           | Firefox 91.0.1 (64-bit) |
| Operating System | MacOS Big Sur 11.5.1 |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by Isoaxe** [comment]
Here is the error, in case it is of some use.
```
The above error occurred in the <EventModal> component:
EventModal@https://ql9ql.sse.codesandbox.io/main.js:275:3
div
App@https://ql9ql.sse.codesandbox.io/main.js:227:66
Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

**Comment by Isoaxe** [comment]
As some further info, the working project will break if the `<EventModal />` component and file are created _even if they are not imported and implemented_. The mere presence of the file appears to cause the error.

**Comment by smhutch** [comment]
@Isoaxe thanks for the very detailed report and reproductions, that made this much easier to investigate.

I was able to fix the Sandbox by adding this line to EventModal.jsx:

```jsx
import React from 'react'
```

Here's a [forked Sandbox](https://codesandbox.io/s/modal-as-imported-component-forked-fl2lq?file=/src/EventModal.jsx) with the change.

For now I will close this issue, and open a new one to investigate why that log was not sent to the console in the CodeSandbox UI.
