### ISSUE TITLE
Collection pages

### ISSUE THREAD

**Issue by gautamarora** [codesandbox/codesandbox-client#609]
Starting an issue based on discussion in discord on Feb 2, 2018 for creating Collection pages...

As per discussion, there are 2 different types of Collections that are most interesting:
1. Personal collection pages
These are collections of your sandboxes (personal & private). One possibility would be to use `tags` as the collection mechanism, and then use the algolia search to get sandboxes for that tag. Here is an [example](https://codesandbox.io/search?query=gautamarora&refinementList%5Btags%5D%5B0%5D=jest&page=1) of jest sandboxes for my account. Thanks to @chakrihacker for the idea on using algolia for this. If this approach is workable, then we can consider making the url prettier e.g. `codesandbox.io/u/gautamarora/sandboxes/jest`

2. Project collection pages
These are collections of curated sandboxes for particular projects (e.g. glamorous, jest) that would make codesandbox the "central database for dependencies". The main issue to identify for this usecase is how to determine authors for a project collection. Some of the options shared for this are:
    1. back the collection with a github repo like `github/codesandbox-docs/glamorous` that has a markdown file with a list of sandboxes
    2. create it based on the tags across all sandboxes and show the most viewed
These collection pages can have the url format `codesandbox.io/p/glamorous`

Other issues that refer to a similar feature are:
https://github.com/CompuIves/codesandbox-client/issues/567
https://github.com/CompuIves/codesandbox-client/issues/121

cc @CompuIves @chakrihacker

**Comment by CompuIves** [comment]
> back the collection with a github repo like github/codesandbox-docs/glamorous that has a markdown file with a list of sandboxes

I really like this idea! Makes it much easier to collaborate and works outside of CodeSandbox as well. And would allow for generators too, possibilities are endless!

I also noticed that when users import a sandbox from GitHub they expect the sandbox to be on their profile, also something we could think about.

I love all the ideas mentioned. I also like the idea by @rajjejosefsson to have directories, I expect that many will find it much easier to organize their sandboxes that way.

Just some idea throwing 😄

**Comment by lbogdan** [comment]
@gautamarora Does the [CodeSandbox dashboard](https://medium.com/@compuives/announcing-codesandbox-dashboard-teams-876f5933160b) fulfill your needs here?
