### ISSUE TITLE
Vue Sandbox suddenly stopped working. Error "Could not find dependency: 'vue-style-loader' relative to '/package.json'"

### ISSUE THREAD

**Issue by hodgef** [codesandbox/codesandbox-client#6105]
# 🐛 bug report

## Preflight Checklist
- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Vue Sandbox is suddenly throwing error "Could not find dependency: 'vue-style-loader' relative to '/package.json'". Sandbox hasn't been updated in months so a breaking change in CodeSandbox is suspected.

## How has this issue affected you? What are you trying to accomplish?
This error breaks the sandbox.

### To Reproduce
Visit: https://codesandbox.io/s/github/hodgef/vue-simple-keyboard/tree/master

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |a819609e7 |
| Browser          |Edge 93.0.961.38|
| Operating System |Windows 10|

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by lbogdan** [comment]
Hey @hodgef ,

Thank you for your report!

@DeMoorJasper can you please take a look?

**Comment by DeMoorJasper** [comment]
Pinned this down to a change in the used library: `simple-keyboard` somewhere between v3.1.0 and v3.1.1, looking into it further. But it doesn't appear to be a breaking change in sandpack.

**Comment by hodgef** [comment]
Thanks for looking into this @DeMoorJasper,

I have diffed simple-keyboard [`3.0.70`](https://github.com/hodgef/simple-keyboard/commit/343b24af984efffe7ca1d8dd9e8293d066c7c88e)  and `master` and haven't seen a change that could cause this.

Sadly, this does strike me as something to do with CodeSandbox webpack or babel configuration, because as soon as I import my library in the [following default sandbox](https://codesandbox.io/s/vue) it breaks:

![image](https://user-images.githubusercontent.com/25509135/132438357-9f86e227-4306-4e0e-9367-4cbc15b615a3.png)
https://codesandbox.io/s/condescending-wright-hm79p?file=/src/components/HelloWorld.vue

And when I import the library in a fresh Vue project (`vue create hello-world`) it doesn't break:

![image](https://user-images.githubusercontent.com/25509135/132439319-55f4e1c7-7738-4dfe-9067-791a69437da2.png)

https://github.com/hodgef/simple-keyboard-vue-test

Between the versions checked there has been automatic updates to build dependencies, so perhaps this update led to a bundle that CodeSandbox is unable to process, while it does work on a base Vue project.

![image](https://user-images.githubusercontent.com/25509135/132439567-63b6893e-539c-4f1e-b3a6-e243e0f0efde.png)

What is interesting though is that this `import` issue is only seen in Vue sandboxes In other sandboxes, the import works perfectly fine, such as in this Vanilla JS one: https://codesandbox.io/s/github/hodgef/simple-keyboard-npm-demos/tree/master

Please let me know if you need more information on this. Thanks!

**Comment by DeMoorJasper** [comment]
@hodgef it was just an observation, it's definitely something in sandpack, still not entirely sure what the issue was but was able to fix it with the linked Pull Request.

Luckily that pull request also speeds up transpilation a bit, so win-win.

**Comment by hodgef** [comment]
Excellent, I can confirm it's fixed. Thanks a lot for resolving this so quickly!
