### ISSUE TITLE
%20 in GitHub urls no longer seems to be converted to +

### ISSUE THREAD

**Issue by Haroenv** [codesandbox/codesandbox-client#6109]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

%20 (and presumably other parameters) no longer get transformed to + correctly to be read

## How has this issue affected you? What are you trying to accomplish?

have to edit the url after submitting

### To Reproduce

this doesn't work: (changed github.com with https://codesandbox.io/s/github as I usually do)

https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/Vue%20InstantSearch/server-side-rendering

this works:

https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/Vue+InstantSearch/server-side-rendering

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |      8e4ea7567        |
| Browser          |      Safari        |
| Operating System |         macOS Big Sur 11.5.2 (20G95)     |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by lbogdan** [comment]
Hey @Haroenv ,

Do you know if this worked before? I'm assuming yes, as you said "no longer", but just wanted to make sure.

**Comment by Haroenv** [comment]
I definitely remember that it used to work up to maybe a month or two ago?

**Comment by sannek** [comment]
Hi - Thanks for reporting! 

I'm pretty sure I know what introduced this, so I'm going to have a look at fixing it right now. (It's a backend issue - so you won't se a PR here, but I'll be back to let you know / close this issue when the fix is live)

**Comment by lbogdan** [comment]
The fix was merged, but it's not deployed just yet.

**Comment by sannek** [comment]
Just deployed - so should be all good again 🎉

**Comment by Haroenv** [comment]
Thanks for being so quick @lbogdan and @sannek, those URLs seem to work for me!
