### ISSUE TITLE
React SVG Component Does Not Output Props

### ISSUE THREAD

**Issue by rfinni** [codesandbox/codesandbox-client#6123]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

When importing an SVG file into a React component using the `import { ReactComponent as SomeSvg }` syntax, passing props like className, height, width, etc. are not output onto the SVG element itself. However, React devtools displays them as props that were passed.
<img width="1073" alt="Screen Shot 2021-09-09 at 8 34 51 PM" src="https://user-images.githubusercontent.com/1593553/132784780-eb64e8b7-c2de-425f-832b-d2f6d48323ad.png">
<img width="744" alt="Screen Shot 2021-09-09 at 8 35 00 PM" src="https://user-images.githubusercontent.com/1593553/132784765-cc613710-44eb-4834-ad49-23ff09543163.png">

## How has this issue affected you? What are you trying to accomplish?
This was working previously, but several of my sandboxes are cosmetically broken now as the SVG icons don't have the proper class names. I'm not sure when this started happening.

### To Reproduce
1. Import an SVG into a React component like so: `import { ReactComponent as SomeSvg } from "./path/file.svg";`
2. Use that SVG as a component and try to pass props to it: `<SomeSvg className="test" />`.
3. Inspect the element using regular Chrome devtools elements inspector.
4. Notice that the props passed (className, etc.) are not on the SVG when its rendered.
4. Inspect the element using React devtools component inspector.
5. Notice that the props that were passed are visible in React devtools component inspector.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | df8e50121 |
| Browser          | Google Chrome 92.0.4515.159 |
| Operating System | Mac OS Big Sur |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by lbogdan** [comment]
This might be related to some SVG importing changes we just deployed, @DeMoorJasper can you please take a look?

**Comment by DeMoorJasper** [comment]
Fixed in #6125

**Comment by rfinni** [comment]
Thank you!
