### ISSUE TITLE
Upgraded to pro account but still cannot access private sandbox Pro feature

### ISSUE THREAD

**Issue by brandonmcconnell** [codesandbox/codesandbox-client#6141]
I have tried creating several different sandboxes and making any of them private since upgrading my account to Pro, but the private option is still greyed out with the accompanying message "Changing sandbox access is available with CodeSandbox Pro" (screenshot below).

Simultaneously, I can see both the "Pro" cadhe next to my username and this "Upgrade to Pro" message. Upon clicking the link to upgrade to Pro, I'm presented with the Pro options, and when I try to once again purchase the same plan, I am then correctly presented with the disabled button indicating I already have that plan.

![E_byd0gX0AQ0E1I](https://user-images.githubusercontent.com/5913254/133689352-3f442527-2120-4935-8462-cc5913f372c8.jpg)

**Comment by sannek** [comment]
Fixed by #6142

**Comment by brandonmcconnell** [comment]
Thank you, @sannek and @CompuIves 👏🏼
