### ISSUE TITLE
ESM: Support for Subpath patterns 

### ISSUE THREAD

**Issue by barelyhuman** [codesandbox/codesandbox-client#6147]
# 🌈 Feature

Ability to handle [subpath patterns](https://nodejs.org/api/packages.html#packages_subpath_patterns) 

### What is this feature? 
A few libraries with a lot of exports would prefer to use the above pattern while creating exports and this current breaks in CSB example sandbox https://codesandbox.io/s/kind-payne-i2eb3?file=/src/App.tsx for https://github.com/pmndrs/jotai 

The feature or maybe even a bug would be to add resolution handlers for the `exports` field to have glob patterns and absolute file paths.

### How the feature should work? 

> The feature or maybe even a bug would be to add resolution handlers for the `exports` field to have glob patterns and absolute file paths.

### You have examples or an idea how it can be implemented? 

You can follow the node docs https://nodejs.org/api/packages.html#packages_subpath_patterns , as this was added to both v12 and v14 and already supported by v16 

I wouldn't mind raising a PR but I was unable to find the point of generation for packages. I'm assuming it's the `sandpack` package code but I'm not sure

**Comment by DeMoorJasper** [comment]
We added support for this yesterday, but rolled it back due to issues, https://github.com/codesandbox/codesandbox-client/pull/6065

**Comment by barelyhuman** [comment]
> We added support for this yesterday, but rolled it back due to issues, #6065 will look into this again next week at the earliest as we really want to ensure everything works perfectly

@DeMoorJasper That makes sense, thanks

**Comment by vinothvk** [comment]
@DeMoorJasper any timeline when this is planned to be resolved ? thanks

**Comment by DeMoorJasper** [comment]
@vinothvk Shifted my focus to other projects within codesandbox for now, hoping to get to this by next week.

Sorry for the delay
