### ISSUE TITLE
Angular template unusable after download

### ISSUE THREAD

**Issue by y-nk** [codesandbox/codesandbox-client#6166]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

After cloning the angular template, I tried to download it (as zip) and run it with `npm install && npm start`.
The `start` script outputs the error message: `An unhandled exception occurred: No projects support the 'serve' target.`

I don't understand why the exact same project runs successfully on codesandbox.io but not offline on my computer.

## How has this issue affected you? What are you trying to accomplish?

Running locally a project which successfully run in codesandbox.io

### To Reproduce

1. Go to https://codesandbox.io/s/angular-angular
2. Download as zip
3. Unzip the archive
4. Inside the archive, run `npm install && npm start`

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  latest online |
| Browser          | irrelevant |
| Operating System | macOS latest |
| Node | 14.15 |
| NPM | 6.x |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
@y-nk Unfortunately we wouldn't be able to diagnose why this isn't working correctly on your local machine, inside a local environment. 

The 

>An unhandled exception occurred: No projects support the 'serve' target. 
 
 Error can often crop up due to misplaced } - So I'd recommend reviewing the code and making sure that the dependencies are linked properly :) as unlinked dependencies (and that template has a number of dependencies) could also be the cause.
