### ISSUE TITLE
Explicitly show who owns a codesandbox

### ISSUE THREAD

**Issue by eps1lon** [codesandbox/codesandbox-client#6186]
# 🌈 Feature

We had a codesandbox that was created by a member under their user account and then transferred to our org. 
We're pretty sure its owned by us now considering the used org switches when I navigate to the codesandbox (due to https://github.com/codesandbox/codesandbox-client/issues/5035).
But it's still not apparent since codesandbox only shows the creator and not the owner (at least I couldn't find that information).

Codesandbox: https://codesandbox.io/s/mimic-v4-button-default-color-bklx8?file=/src/Demo.tsx
![Screenshot from 2021-10-07 09-38-51](https://user-images.githubusercontent.com/12292047/136340675-4dd07963-27c9-43e3-9055-b51d7122c7af.png)
Client version: e6a3e092b

**Comment by CompuIves** [comment]
Ah this is an interesting UX/UI thing we need to look into. We currently show the creator, and then under it which team it belongs to. Maybe we should reverse it, because it's indeed the case that the team is the real _owner_.
