### ISSUE TITLE
Configuring which TypeScript to use? (part 2)

### ISSUE THREAD

**Issue by barrymay** [codesandbox/codesandbox-client#6201]
I wanted to re-raise this issue because the prior one was closed: https://github.com/codesandbox/codesandbox-client/issues/942

**Original question:**
Can we make it so that I can configure which version of TypeScript to use? Can I (for instance) install typescript@next and use that?

**My latest add-on:**
Issues showing up due to TS 4.1.2 are showing on recent projects when people expect behavior from 4.2+. (See [my reference to this issue here](https://github.com/react-hook-form/react-hook-form/pull/6753#issuecomment-939222107) for an example, which is causing issues with developers using CodeSandbox for sample creation.)

Suggestion - maybe this TS restriction is due to the sandbox template? If so is it possible as a temporary workaround for the CodeSandbox team to create new new TS templates based on latest TS (for the React-Scripts and vanilla TS ones at minimum, a next.js + TS example would be equally really nice, since create-next-app has taken off 🙂 )?

**Comment by JamesACS** [comment]
Hey @barrymay 

We already have an issue #5598 around updating TypeScript to support more versions in the Editor - it's something on our radar!
