### ISSUE TITLE
How to deploy a self host codesandbox from the source code?

### ISSUE THREAD

**Issue by lifubang** [codesandbox/codesandbox-client#6209]
Hi, this is a amazing project, but I can't find the guide to deploy a self host codesandbox from the source code. Could you help to provide the steps?

Before asking your help, I have tried yarn and docker build. But looks like there were all broken.
1. Yarn: It can only work with localhot, but can't work with a public ip;
2. Docker: The node version of base image is different from package.json .

**Comment by JamesACS** [comment]
Hey @lifubang - Unfortunately we wouldn't be able to assist you with self hosting as this isn't something we support at this time

**Comment by jschwartzenberg** [comment]
Are there any plans in this regard? Does the set of repositories provided allow self-hosting or are there parts of the hosted solution that have not been released?
