### ISSUE TITLE
CSS @import not working for node_modules resources

### ISSUE THREAD

**Issue by dhayab** [codesandbox/codesandbox-client#6211]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

In an Angular project in Codesandbox, CSS `@import` rules don't work for resources that are inside dependencies. Other methods of importing external styles still work though:
- using `<link>` tags in HTML files
- adding the style files in **angular.json**

## How has this issue affected you? What are you trying to accomplish?

I could not import external styles directly from a CSS file.

### To Reproduce

- create a Codesandbox using the official Angular template
- add **bootstrap** as a dependency
- add `@import "bootstrap/dist/css/bootstrap.css";` in **style.css** and some bootstrap-related markup in a component's HTML file

You'll find below a link that follows these steps.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  2556ada01            |
| Browser          |   Chrome 94.0.4606.81           |
| Operating System |   macOS 11.6           |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by adampweb** [comment]
This issue still exists on other templates (e.g.: React)
