### ISSUE TITLE
Allow code editor to be word wrapped

### ISSUE THREAD

**Issue by subins2000** [codesandbox/codesandbox-client#6230]
# 🌈 Feature

Word wrap code in editor. This is same as https://github.com/codesandbox/codesandbox-client/issues/4063 But that got closed because of being "stale".

Word wrap the code instead of having to horizontally scroll all the time which is very annoying.

Perhaps have a small setting somewhere whether to word wrap or not ? By this, people who like scrolling can still have that and folks who need word wrap can use that.

Thank you

**Comment by Shelagh-Lewins** [comment]
I had the same experience, that preferences > Prettier settings code wrap does nothing. This seems like a bug?

**Comment by JamesACS** [comment]
@Shelagh-Lewins - Yep, I've confirmed this as a bug on our end now and raised it.

In the meantime you can use the workaround above. Sorry for the trouble!

**Comment by Shelagh-Lewins** [comment]
Yes, I opened the main menu ("..." button top right of screen), chose Preferences > Appearance > Open VSCode Settings > Commonly Used > Editor > Word Wrap (scroll down to see it)

Posting these instructions as it took me about 5 minutes to find the setting...
