### ISSUE TITLE
How to delete payment info after resignation from pro plan?

### ISSUE THREAD

**Issue by vaalgrind** [codesandbox/codesandbox-client#6244]
# 🐛 Cannot delete payment info

## I would like to resign from pro plan, but to be honest it really unclear if I already did it.
Every time when I click downgrade plan, the same toast message pops up.
Additionally I don't see option to delete payment information (I have to delete it because it's company card).
When I hover invoice details I see this:
<img width="272" alt="Zrzut ekranu 2021-11-2 o 08 19 49" src="https://user-images.githubusercontent.com/16843232/139803070-5700b012-1296-4d20-ad86-84c8ca90ff77.png">

**Comment by JamesACS** [comment]
Hey @vaalgrind please could you contact us at support@codesandbox.io - then we can look into this for you 😊
