### ISSUE TITLE
"Cannot read properties of undefined (reading 'instantiations')" when using `as const`

### ISSUE THREAD

**Issue by sarahdayan** [codesandbox/codesandbox-client#6268]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I have a [TypeScript sandbox](https://codesandbox.io/s/epic-shadow-5yhv1) that's currently throwing a cryptic error.

After digging, I realized that the problem was caused by the `as const` in l. 218. When removing it, the [sandbox works](https://codesandbox.io/s/wizardly-surf-qf8x4?file=/app.tsx).

The error I get on Chrome:

```txt
"Cannot read properties of undefined (reading 'instantiations')"
```

![Capture d’écran 2021-11-10 à 18 47 30](https://user-images.githubusercontent.com/5370675/141165858-1417c8a2-556b-4ec8-a96d-ddc81eb60b53.png)

In Firefox, the error is:

```txt
e is undefined
```

![Capture d’écran 2021-11-10 à 18 48 19](https://user-images.githubusercontent.com/5370675/141165973-38f4e489-b17c-4cc1-9048-2481df561837.png)

## How has this issue affected you? What are you trying to accomplish?

The return type of my function is a tuple, not an array, so I'd like to type it as such from usage without declaring an explicit return type. For now I can't because this breaks the sandbox.

### To Reproduce

- Go to [this sandbox](https://codesandbox.io/s/epic-shadow-5yhv1) and see the error
- Remove `as const` in l. 218
- See the sandbox working

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 5fa791753             |
| Browser          | Firefox 5fa791753/Chrome 95.0.4638.69              |
| Operating System | macOS Big Sur 11.5.1             |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by CompuIves** [comment]
Super interesting, this is purely a type annotation, right? Then it seems like the TypeScript compiler is throwing for some reason. Checking more closely...

**Comment by CompuIves** [comment]
Okay, this is definitely a TypeScript issue because the transpiler we use has gone out of date. You can fix it for now by adding `"typescript": "4.4.4"` to the `devDependencies`, like I do here: https://codesandbox.io/s/floral-cookies-17yh6

**Comment by CompuIves** [comment]
I also made sure that the default vanilla template has this from now on as well 😄

**Comment by sarahdayan** [comment]
Thanks for this @CompuIves!
