### ISSUE TITLE
Codesandbox CI node version 16

### ISSUE THREAD

**Issue by bodinsamuel** [codesandbox/codesandbox-client#6271]
# 🌈 Feature

Hello team,

What is timeline to support NodeJS v16 in CodeSandbox CI?
The documentation does not mention it https://codesandbox.io/docs/ci

Incidentally testing with `node: "16"` does not produce any error but rollback to `10.24.1` (which also does not fit the documentation)

- Support NodeJS 16
- Validate more strictly "ci.json" node version

**Comment by lbogdan** [comment]
Hey @bodinsamuel ,

We'll upgrade all current node versions and add 16.x during the week. Also thanks for pointing the docs version mismatch, we'll make sure to update those, too!

Do you think it would be better to hard error if the version is not valid, instead of just falling back to 10.x?

**Comment by bodinsamuel** [comment]
I personally prefer explicit over implicit, so strong validation (in that case it would really help to understand the error) but that's up to you ☺️

**Comment by lbogdan** [comment]
We just upgraded node versions and added node 16, and also opened a PR to update the docs (not deployed yet, but you can preview it at https://pr6283.build.csb.dev/docs/ci ).

We're also hard-failing the build if the node version is set to something else than `'10'`, `'12'`, `'14'` or `'16'`.

Please give it a try and let us know if it work as expected. Thanks!

**Comment by bodinsamuel** [comment]
It works, thanks a lot ❤️

**Comment by lbogdan** [comment]
Glad it works!

Closing as solved.

**Comment by Haroenv** [comment]
@lbogdan, sorry for commenting on an old issue but I tried in other places already. Could you also add node 18 and 20 please? Thanks!
