### ISSUE TITLE
ModuleNotFoundError when importing from a subdirectory of a module

### ISSUE THREAD

**Issue by niieani** [codesandbox/codesandbox-client#6279]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

This is a very recent regression. A sandbox that worked correctly just last week no longer works.

When trying to import from a subdirectory of a module, I get a `ModuleNotFoundError`.

```
ModuleNotFoundError
Could not find module in path: '@zendesk/laika/esm/laika' relative to '/src/index.ts'
```

### To Reproduce

- Add `@zendesk/laika@1.0.0` as dependency
- `import { Laika } from '@zendesk/laika/esm/laika'` or `import { Laika } from '@zendesk/laika/cjs/laika'`
- either import will result in the ModuleNotFoundError error

### Link to sandbox: [link](https://codesandbox.io/s/laika-example-3yyq0)

For comparison, see the same code at [StackBlitz](https://stackblitz.com/edit/laika-example?file=index.tsx) working correctly

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |   2021-11-15   |
| Browser          |  any  |
| Operating System |   any  |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by DeMoorJasper** [comment]
Thanks for reporting this, will look into this right away, this is definitely a regression as we recently merged our new resolver to support more resolving strategies and improve performance
