### ISSUE TITLE
Every SolidJS Example is Suddently broken

### ISSUE THREAD

**Issue by ryansolid** [codesandbox/codesandbox-client#6288]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Not sure what happened but every [SolidJS](https://github.com/solidjs/solid) example stopped working a day or so ago. There are varying errors from issues with babel:

> babel-transpiler.88c24584.worker.js:2015 Error: Cannot find module 'babel-preset-solid' from 'babel-preset-solid'

To non-compiled examples complaining that imports aren't functions.

## How has this issue affected you? What are you trying to accomplish?

These examples have been up for years, and have been our main online examples historically. Some people in the community started mentioning our examples were broken, and this is what I encountered.

### Link to sandbox:

[Hello World Template](https://codesandbox.io/s/solid-hello-world-9v13b)
[Non-Compiled Tagged Template Literals](https://codesandbox.io/s/solid-tagged-template-literal-example-btgbk)
[Only Reactivity](https://codesandbox.io/s/reaction-5wyzu)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |  Chrome   |
| Operating System | MacOS  BigSur  |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by DeMoorJasper** [comment]
Probably related to our recent resolver changes, looking into it right now

**Comment by DeMoorJasper** [comment]
Found the issue and got a fix PR ready, this issue was caused by the `exports` field in `solid-js` having a nested object, which I apparently forgot to support in our resolver. We also had another issue in the Babel transformer as well regarding installing presets, which was a simple regression because of a refactor.

Tested the sandboxes and they all seem to be working now.

**Comment by ryansolid** [comment]
Thanks. It all looks good. Appreciate you getting this fixed so fast.
