### ISSUE TITLE
[Bug] DependencyNotFoundError

### ISSUE THREAD

**Issue by fantasticsoul** [codesandbox/codesandbox-client#6289]
# 🐛 bug report

## Description of the problem

DependencyNotFoundError
Could not find dependency: 'utils' relative to '/src/models/counter/reducer.js'

it seems the configs below not work( but is works before)
```
"compilerOptions": {
    "baseUrl": "src",
    "experimentalDecorators":true
  }
```

## Link
https://codesandbox.io/s/xvcej

**Comment by DeMoorJasper** [comment]
duplicate of #6286
