### ISSUE TITLE
Function called outside component initialization

### ISSUE THREAD

**Issue by hkscsheph** [codesandbox/codesandbox-client#6293]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
I am working on [this CSB](https://codesandbox.io/s/flamboyant-pond-wohvg?file=/App.svelte) with plain Svelte and a carousel library Siema.
It used to work fine (still works locally and on [Netlify](https://practical-raman-0bbcf6.netlify.app/))
Since today, an error ```Function called outside component initialization``` appears upon clicking the color div to show carousel.
As I follows the issue tracker, it seems to be caused by how CSB set up Svelte. (```/node_modules/svelte/internal/index.js```)
Another clue is the lint appearing on the very beginning ```<script>```
![](https://i.imgur.com/M5Y1SKb.png)

## How has this issue affected you? What are you trying to accomplish?
It affects the development environment in CSB

### To Reproduce
- Open [this CSB](https://codesandbox.io/s/flamboyant-pond-wohvg?file=/App.svelte)
- Click the color div (supposed to show a carousel)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |     Not sure         |
| Browser          |       Chrome and Brave       |
| Operating System |       Windows       |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by DeMoorJasper** [comment]
Can't seem to reproduce this with the linked sandbox, does it still happen? Might have been fixed already as we've released a bunch of bugfixes today

**Comment by DeMoorJasper** [comment]
Fixed in commit d97decacf0735f839230771558195bc034e79552

**Comment by hkscsheph** [comment]
Thank you, the major issue ```Function called outside component initialization``` is gone=)
Yet, the very beginning lint ```Cannot read properties of null (reading 'name')``` on ```<script>``` is still there, despite not affecting the functionality.
