### ISSUE TITLE
Error when import .less from node_modules

### ISSUE THREAD

**Issue by EastblueOkay** [codesandbox/codesandbox-client#6295]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
When i try to import less from node_modules, i got the following error message:
b.match is not a function

## How has this issue affected you? What are you trying to accomplish?
This will still be able to run normally before today.

### To Reproduce
https://codesandbox.io/s/import-less-from-modules-1z9q9?file=/src/App.tsx

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/import-less-from-modules-1z9q9?file=/src/App.tsx

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |       unsure       |
| Browser          |        chrome 95.0.4638.69      |
| Operating System |        macOS Monterey      |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by EastblueOkay** [comment]
I noticed that there seems to be some problems with the new less file management:
https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/sandbox/eval/transpilers/less/file-manager.js#L35

RegExp there is no 'match' method. There still to be other errors after adjustment.

**Comment by DeMoorJasper** [comment]
Not sure why this worked before today, but implemented fixes for this here: #6298

Should be working again after that fix is deployed, thanks for reporting this
