### ISSUE TITLE
Cannot read properties of undefined (reading 'registerSerializer')

### ISSUE THREAD

**Issue by drnextgis** [codesandbox/codesandbox-client#6313]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
![image](https://user-images.githubusercontent.com/866124/142949682-a338002c-a691-4736-8adc-96c1ae0bbc05.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |          Chromium    |
| Operating System |       Linux       |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by tanjing9406** [comment]
```
import OSM from 'ol/source/OSM'
import VectorSource from 'ol/source/Vector'
// import {OSM, Vector as VectorSource} from 'ol/source';
```

I replace them with this, it works for me, just try

**Comment by drnextgis** [comment]
@tanjing9406 could you please elaborate? There are no such lines in the sandbox I posted.

**Comment by EvertEt** [comment]
Seems to be caused by the 'geotiff' package (1.0.8). 
You can replicate it in a clean sandbox with `import "geotiff";`

**Comment by namedgraph** [comment]
Still experiencing this with OpenLayers code :/

**Comment by drnextgis** [comment]
@namedgraph the original issue I reported to OpenLayer has been closed and I can confirm that now everythyng works as expected. Could share a link to the example which is not working for you?

**Comment by namedgraph** [comment]
https://codesandbox.io/s/wkt-forked-1x4lw?file=/main.js

**Comment by drnextgis** [comment]
Check this example: https://codesandbox.io/s/bmzcjy
