### ISSUE TITLE
Unable to sign in with GitHub

### ISSUE THREAD

**Issue by aneeshbhatb** [codesandbox/codesandbox-client#6320]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
When trying to sign in via GitHub, it's prompting a message saying **"We found an existing account, please sign in with Google instead."**. So, if an existing account found, doesn't that mean I can log in?

https://user-images.githubusercontent.com/63218245/143782740-17073f09-2d87-4b8a-8c03-4c052008b0e9.mp4

## How has this issue affected you? What are you trying to accomplish?
Not able save or access any of my sandbox.

### To Reproduce
1. Should already have signed in with GitHub
2. Try Signing in again with the same GitHub account.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | online |
| Browser          |Chrome Version 96.0.4664.45 (Official Build) (64-bit)|
| Operating System | Ubntu 20.04|

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @aneeshbhatb - Please could you contact us at support@codesandbox.io? We'll sort this out for you :)

**Comment by paulpessoa** [comment]
I have the same issue.
I can't commit anything because of this.

**Comment by Salmanz18** [comment]
I'm also having the Same issue.

**Comment by kumarnishu** [comment]
Kumarnishu 
Having same issue

**Comment by BenjaminMcMahan** [comment]
I am receiving something similar - saying that an account already exists for the given email. Attempting to sign in with GitHub, I have signed in previously.

I believe a GH token expired recently - might this be the issue?

**Comment by kumarnishu** [comment]
Just go to your dashboard and link there you GitHub account first..


You can not create new account with that email again...

And unfortunately codesandbox have no account deletion feature, once
created.

**Comment by jcusick93** [comment]
I am having the same issue
