### ISSUE TITLE
Define API breaks binary files, sometimes before, sometimes after forking the newly created sandbox

### ISSUE THREAD

**Issue by marcelscruz** [codesandbox/codesandbox-client#6325]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I'm creating sandboxes programmatically from our dashboard.
Some files are sent as binary (e.g. `https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/.env.local.sample`), and some others are sent as strings because they need some data to be injected into them beforehand.

This works just fine for some demos we have until I fork the sandbox.
Once forked, the files sent as binary lose their content (code) once saved, and instead, they have the binary URL as the content. 
Sandbox link: https://codesandbox.io/s/v8v6r

https://user-images.githubusercontent.com/12413903/144043684-67ddbf4c-2909-4e54-af82-7cde90a65b73.mp4

For the `create-react-app` demo we have, this issue happens even before forking the newly created sandbox. Even though the files still have code in them, the app already crashes complaining that the content of the file is the binary URL.
Sandbox link: https://codesandbox.io/s/2m5mp

https://user-images.githubusercontent.com/12413903/144044047-507e8ca6-b2b3-453a-b572-35cb484d2be7.mp4

Here's part of one of the payloads:
```js
const files = {
    '.env.local.sample': {
        content: 'https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/.env.local.sample',
        isBinary: true,
    },
    '.gitignore': {
        content: 'https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/.gitignore',
        isBinary: true,
    },
    'README.md': {
        content: 'https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/README.md',
        isBinary: true,
    },
    'package.json': {
        content:
            '{\n  "name": "clerk-nextjs-starter",\n  "description": "Use Clerk\'s authentication and user management with Next.js",\n  "private": true,\n  "scripts": {\n    "dev": "next dev",\n    "build": "next build",\n    "start": "next start"\n  },\n  "dependencies": {\n    "@clerk/nextjs": "^2.0.1",\n    "next": "11.1.2",\n    "react": "17.0.2",\n    "react-dom": "17.0.2"\n  }\n}\n',
        isBinary: false,
    }
}

```

And here's how the request is made:
```js
const res = await fetch(
      'https://codesandbox.io/api/v1/sandboxes/define?json=1',
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Accept: 'application/json',
        },
        body: JSON.stringify({
          files,
        }),
      },
    );
const { sandbox_id } = await res.json();
```

Is this a known issue, or is there anything I can do from my end to fix it? 

---

Related question: is there a way to initialise a project from a GitHub repo and programmatically add more files to it or edit existing ones, on the fly? This would greatly simplify what we currently do, in which we need to fetch the list of files and sometimes their content beforehand, add some values where needed, and then pass everything to CodeSandbox at once, so the current user can access the demo with their env vars.

Thanks!

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |      Chrome 96       |
| Operating System |      macOS 11.6        |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by sannek** [comment]
Hi Marcel,

First of all, thank you for the elaborate issue. That is super helpful.

I will have to investigate what's up with the binary files, so I will get back to you on that in max a day or two. Are you setting `isBinary` to `true` because you want to load the file contents from a URL? Because files like `.md` and `.gitignore` are not formats that we would consider `binary files` (The distinction is roughly "can a test editor show the contents of this file normally or not"). I'm not sure until I have a better look, but this might be where the weirdness is coming from.

As for your other question: As far as I know it's not currently possible to initialise a sandbox from a github repo and also edit files on the fly. I'll have a look to see if there could be a good workaround  for you, but I'm not sure!

**Comment by lbogdan** [comment]
@marcelscruz Can you please provide a broken sandbox forked from https://codesandbox.io/s/v8v6r ?

**Comment by marcelscruz** [comment]
> @marcelscruz Can you please provide a broken sandbox forked from https://codesandbox.io/s/v8v6r ?

Here, this one is a broken fork: https://codesandbox.io/s/clerk-nextjs-starter-forked-iyjj2

Please do the following (like in the video below):
1. open any file that's not broken yet
2. save it
3. you'll now see the blue dot beside the file name on the tree
4. close the file
5. open it again

Thanks!

https://user-images.githubusercontent.com/12413903/144071430-48071623-ea57-4ae8-81d1-9a7961f06f13.mov

**Comment by lbogdan** [comment]
Oh, I see what you did there! 🙂 

I guess the shortest answer here is that we never thought about supporting "binary" code files, and the fact that the first linked sandbox works is just because of an implementation detail of how container sandboxes work, which breaks as soon as you try to save the file.

The assumption that code files are never binary runs quite deep, so it's challenging to fix, at least not short-term. Can you maybe fix it on your side, by not creating binary code files?

**Comment by marcelscruz** [comment]
@sannek Thanks for the answer.

I just tried passing some of these values as `isBinary: false`, but the problem persists.


<details>
  <summary>Here's the whole payload:</summary>


```json
{
    ".env.local.sample": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/.env.local.sample",
        "isBinary": false
    },
    ".gitignore": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/.gitignore",
        "isBinary": false
    },
    "README.md": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/README.md",
        "isBinary": false
    },
    "components/Header.js": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/components/Header.js",
        "isBinary": true
    },
    "components/Layout.js": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/components/Layout.js",
        "isBinary": true
    },
    "package.json": {
        "content": "{\n  \"name\": \"clerk-nextjs-starter\",\n  \"description\": \"Use Clerk's authentication and user management with Next.js\",\n  \"private\": true,\n  \"scripts\": {\n    \"dev\": \"next dev\",\n    \"build\": \"next build\",\n    \"start\": \"next start\"\n  },\n  \"dependencies\": {\n    \"@clerk/nextjs\": \"^2.0.1\",\n    \"next\": \"11.1.2\",\n    \"react\": \"17.0.2\",\n    \"react-dom\": \"17.0.2\"\n  }\n}\n",
        "isBinary": false
    },
    "pages/_app.js": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/pages/_app.js",
        "isBinary": true
    },
    "pages/api/getAuthenticatedUserId.js": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/pages/api/getAuthenticatedUserId.js",
        "isBinary": true
    },
    "pages/index.js": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/pages/index.js",
        "isBinary": true
    },
    "pages/sign-in/[[...index]].js": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/pages/sign-in/[[...index]].js",
        "isBinary": true
    },
    "pages/sign-up/[[...index]].js": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/pages/sign-up/[[...index]].js",
        "isBinary": true
    },
    "pages/user/[[...index]].js": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/pages/user/[[...index]].js",
        "isBinary": true
    },
    "public/clerk.svg": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/public/clerk.svg",
        "isBinary": true
    },
    "public/icons/arrow-right.svg": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/public/icons/arrow-right.svg",
        "isBinary": true
    },
    "public/icons/download.svg": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/public/icons/download.svg",
        "isBinary": true
    },
    "public/icons/external-link.svg": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/public/icons/external-link.svg",
        "isBinary": true
    },
    "public/icons/layout.svg": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/public/icons/layout.svg",
        "isBinary": true
    },
    "public/icons/server.svg": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/public/icons/server.svg",
        "isBinary": true
    },
    "public/icons/settings.svg": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/public/icons/settings.svg",
        "isBinary": true
    },
    "public/icons/user-plus.svg": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/public/icons/user-plus.svg",
        "isBinary": true
    },
    "public/logo.svg": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/public/logo.svg",
        "isBinary": true
    },
    "public/nextjs.svg": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/public/nextjs.svg",
        "isBinary": true
    },
    "public/vercel.svg": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/public/vercel.svg",
        "isBinary": true
    },
    "styles/Header.module.css": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/styles/Header.module.css",
        "isBinary": true
    },
    "styles/Home.module.css": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/styles/Home.module.css",
        "isBinary": true
    },
    "styles/globals.css": {
        "content": "https://raw.githubusercontent.com/clerkinc/clerk-nextjs-starter/main/styles/globals.css",
        "isBinary": true
    },
    ".env.local": {
        "content": "NEXT_PUBLIC_CLERK_FRONTEND_API=clerk.testsijgasodjfsd.com\nCLERK_API_KEY=live_HNbrbbTWIHukf0PsYgoSo9M44UYoyTt3kG",
        "binary": false
    },
    "sandbox.config.json": {
        "content": "{\"disableLogging\":false,\"hardReloadOnChange\":false,\"infiniteLoopProtection\":true,\"view\":\"browser\",\"container\":{\"node\":\"14\"}}",
        "isBinary": false
    }
}
```
</details>

And the sandbox: https://codesandbox.io/s/3fjlc?file=/.env.local.sample

In those files, it happens that the content ends up being only the URL of the hosted file.

And I'd love to hear from you in case you find a way to change files of a GitHub-generated sandbox on the fly. 🙏

**Comment by lbogdan** [comment]
When the files are not sent as binary, their contents needs to be the actual code, not the URL.

**Comment by marcelscruz** [comment]
@lbogdan Thanks for elaborating it! I see, so it seems a bit more of a complex thing to fix. :/

I'm not entirely sure what you mean by _not creating binary code files_, though.

You mean passing the `isBinary: false` to them?
If so, these files would end up with the hosted file URL instead of their content, like [here](https://codesandbox.io/s/3fjlc?file=/.env.local.sample).

Or if you meant fetching these files beforehand and then passing them as strings in the request, that's also not possible, as the payload becomes too big and CodeSandbox fails in the request.

Am I missing something here or is there another solution?
