### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by dobromirts** [codesandbox/codesandbox-client#6334]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Can't successfully update a project to Angular 13. After the update is done the error below is thrown.
![angular-update](https://user-images.githubusercontent.com/46093564/144426645-e8129399-cd84-4fc3-9264-f142851007b1.png)

### To Reproduce

1. Open codesandbox angular template
2. Update to 13
3. Observe errors

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/gifted-banzai-rylgr

**Comment by JamesACS** [comment]
Hey @dobromirts - Thank you for this bug report. 

I've managed to narrow down the issues Common, Compiler, Core and Platform-Browser-Dynamic modules, unfortunately, I haven't managed to narrow it down further than that but will add this to our bug board 👀
