### ISSUE TITLE
Cloudflare leads to unexpected popups, errors and behavior

### ISSUE THREAD

**Issue by rayfoss** [codesandbox/codesandbox-client#6336]
# 🐛 bug report

## Description of the problem

There are Cloudflare popups and numerous telemetry injections my code. Serving outdated unprediactable undebuggable gargage data that I have to deal with.

![Screenshot 2021-12-02 10 36 46](https://user-images.githubusercontent.com/876076/144464755-94cd5eb1-fe58-4f9a-a9b0-e202740233ba.png)

## How has this issue affected you? What are you trying to accomplish?

I'm trying to code. Please let me disable anything that deviates from what I would expect from a bare metal container. In development I should have the option to disable caches... caches in development are a real nightmare.

### To Reproduce

Code.

**Comment by JamesACS** [comment]
@rayfoss - Sorry to hear about the issues, is this something you're still dealing with now?

**Comment by rayfoss** [comment]
Yes... As I'm writing this my code is pushed to the right... whice the cache alert takes priorty. I could "hide this alert" but as I'm constantly clearing the application cache, since I'm developing, it's of no use.

![Screenshot from 2021-12-08 09-44-23](https://user-images.githubusercontent.com/876076/145238322-f8306848-2ed2-4fab-83a6-f8bece04ca4c.png)

**Comment by JamesACS** [comment]
Hey @rayfoss - We've done some cloudflare tweaks on our end. Please could you try again?

**Comment by rayfoss** [comment]
That fixed it!
