### ISSUE TITLE
React element $$typeof not shown correctly in logs

### ISSUE THREAD

**Issue by jayshah123** [codesandbox/codesandbox-client#6344]
# 🐛 bug report

## Preflight Checklist

- [X] I have read the [Contributing Guidelines][contributing] for this project.
- [X] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

When trying to log a react element and see its `$$typeof` property, it is not seen

### To Reproduce
https://codesandbox.io/s/zealous-mountain-tbz1j?file=/src/index.js
see the logs.

Works correctly if open the preview in a new tab

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/zealous-mountain-tbz1j?file=/src/index.js

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |    70b8a7a50          |
| Browser          |       Chrome 96       |
| Operating System |    MacOs 12.0.1          |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @jayshah123 - I'm afraid I haven't been able to replicate this. The Sandbox behaves normally in my browser with no issues?

**Comment by jayshah123** [comment]
Check the logs

**Comment by JamesACS** [comment]
I'm afraid I'm still not seeing anything @jayshah123

**Comment by jayshah123** [comment]
So in the logs $$typeof key is missing. Where as if you open the preview in a new i.e separate tab, that key is logged correctly

**Comment by jayshah123** [comment]
https://overreacted.io/why-do-react-elements-have-typeof-property/

**Comment by nakiostudio** [comment]
Hey @jayshah123 👋 - Unfortunately this is a known limitation of the [component](https://github.com/samdenty/console-feed) we use for the embedded web browser console. We will prioritise investigating a proper alternative or solution, in the meantime please continue using the browser devtools as a workaround.

**Comment by jayshah123** [comment]
Is there an faq where all known limitations are listed ?

**Comment by nakiostudio** [comment]
I'm afraid there's not but the main difference with Chrome's devtools is that objects are rendered eagerly so object mutations after printing aren't shown. The objects' serialisation that the library performs also affect the resulting output causing differences with the browser devtools logs.

**Comment by jayshah123** [comment]
Thanks for the explaination!
