### ISSUE TITLE
React: Inconsistent render due to reassignment

### ISSUE THREAD

**Issue by jjenzz** [codesandbox/codesandbox-client#6357]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

The problem is difficult to describe 🙈  maybe best to reference the code below.

## How has this issue affected you? What are you trying to accomplish?

I'm trying to create a `usePrevious` hook that updates its previous value only when the value passed to it has changed. The solution seems to work fine in our local storybook and stackblitz but not on CodeSandbox.

```jsx
function usePrevious(value) {
  const prevRef = React.useRef();
  return React.useMemo(() => {
    const prevValue = prevRef.current;
    // when this gets reassigned, the render will display this reassigned 
    // value instead of the value from the line above that is returned.
    prevRef.current = value;
    return prevValue;
  }, [value]);
}
```

### To Reproduce

- Go to CodeSandbox link
- The first time you click "Toggle":
    - Console logs `{ prevValue: false }` - Correct 🟢
    - Render displays "Previous: true" - Incorrect 🔴

I expect these two to have the same value, given that they are happening at the same time but they're not.

### Link to sandbox

https://codesandbox.io/s/loving-lamport-fimun?file=/src/App.js

The same code on stackblitz: 

Code: https://stackblitz.com/edit/react-ejzqys?file=src/App.js
Preview: https://react-ejzqys.stackblitz.io

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |       Latest      |
| Browser          |       Brave Browser       |
| Operating System |        MacOS Catalina      |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @jjenzz , I've been looking into this and it seems to be a known quirk of React - [I've found something that may help to explain how to work around this](https://dev.to/chrismilson/problems-with-useprevious-me). 

Let me know if it helps!

**Comment by jjenzz** [comment]
@JamesACS The version I have created solves the the same issues mentioned in that article however, in CodeSandbox, this line incorrectly mutates the **render value**:

```jsx
// const prevValue = prevRef.current;
prevRef.current = value;
// return prevValue;
```

This shouldn't happen because I am returning a locally scoped cached version of it. The same bug happens in CodeSandbox if we use global variables instead of refs:

https://codesandbox.io/s/awesome-proskuriakova-80sqg?file=/src/App.js

Both of these examples behave correctly in StackBlitz and a local React project so the issue appears to be related to CodeSandbox.

**Comment by JamesACS** [comment]
Hey @jjenzz - Sorry for the delay here. 

We've not been able to replicate the code working in a local environment - Could you confirm that you have this exact version working locally?

**Comment by jjenzz** [comment]
No worries, thank you for getting back to it :)

Hmm, I just spun up a local `create-react-app` and it is behaving the same as codesandbox. I don't have the previous example I was fiddling with anymore so must have been a mis-save.

Could this be a React bug instead then? I'm curious

**Comment by jjenzz** [comment]
No worries, thank you for getting back to it :)

Hmm, I just spun up a local `create-react-app` and it is behaving the same as codesandbox. I don't have the previous example I was fiddling with anymore so must have been a forgotten save somewhere 😅.

Could this be a React bug instead then? I'm baffled what's going on here.

**Comment by JamesACS** [comment]
I'm not sure @jjenzz - we've found that If you wrap line 8 in a setTimeout it works as expected though! We're continuing to explore this on our end

**Comment by jjenzz** [comment]
I assume this has something to do with it tbh:

> In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. Write your code so that it still works without useMemo — and then add it to optimize performance.

It's interesting that the log is out of sync but we ended up adjusting the code to follow the rules above which solved it.
https://codesandbox.io/s/charming-hill-o7xlq?file=/src/App.js

**Comment by JamesACS** [comment]
Great news - thank you for letting us know!
