### ISSUE TITLE
Same code in sandpack need dynamic fetch npm file, and in codesandbox.io don't need

### ISSUE THREAD

**Issue by mcuking** [codesandbox/codesandbox-client#6359]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I write react code which use [antd npm](https://www.npmjs.com/package/antd) in the codesandbox, and codesandbox will preload antd npm source code https://prod-packager-packages.codesandbox.io/v2/packages/antd/4.17.3.json. In the compilation of react code, it don't need to dynamic fetch antd-required npm file. Link to sandbox: 

https://codesandbox.io/s/vigilant-forest-h4x0l

But the same code in the sandpack, it will  dynamic fetch many antd-required npm file in the compilation,  although all the files is in the preload npm https://prod-packager-packages.codesandbox.io/v2/packages/antd/4.17.3.json. It makes the compilation time too long. Link to sandbox: 

https://codesandbox.io/s/festive-brown-7nd8h

The bundler code which [Codesandbox](https://codesandbox.io/) and [Sandpack](https://github.com/codesandbox/sandpack) uses  should be the same（https://github.com/codesandbox/codesandbox-client/tree/master/packages/sandpack-core）, why there are different behaviors?

![image](https://user-images.githubusercontent.com/22924912/146504227-3d395e29-2d69-4d47-b670-5ca3ae0cd850.png)

## How has this issue affected you? What are you trying to accomplish?

Using sandpack makes the compilation time too long.

### To Reproduce

https://codesandbox.io/s/vigilant-forest-h4x0l

![image](https://user-images.githubusercontent.com/22924912/146480325-6ee13a75-4fc8-4fa9-8b72-791ed225da78.png)

https://codesandbox.io/s/festive-brown-7nd8h

![image](https://user-images.githubusercontent.com/22924912/146480486-063e3b0d-47ed-46ba-a323-639569b34526.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |       Latest      |
| Browser          |      Chrome/96.0.4664.110        |
| Operating System |        MacOS/11.5.2      |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by mcuking** [comment]
FileResolver props for the Sanpack can solve the problem? 

https://sandpack.codesandbox.io/docs/api/client/interfaces/ClientOptions#fileresolver

![image](https://user-images.githubusercontent.com/22924912/146534743-27b63fb4-4662-461e-9cd9-ca6c7b557b55.png)

**Comment by CodeSandboxTeam** [comment]
Thank you for raising this issue - We're currently looking into it

—
James
Support
CodeSandbox.io

--- original message ---
On December 17, 2021, 11:01 AM GMT ***@***.*** wrote:



FileResolver props for the Sanpack can solve the problem?

https://sandpack.codesandbox.io/docs/api/client/interfaces/ClientOptions#fileresolver


—

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
--- end of original message ---

**Comment by JamesACS** [comment]
Hey @mcuking - Have you had any luck with FileResolver prompts?

**Comment by mcuking** [comment]
@JamesACS I don't know how to write readFile function of the FileResolve.😂

**Comment by JamesACS** [comment]
If you want to get some help implementing it, we have a Discord full of like minded devs that may be helpful! 

https://discord.gg/aKjYQwHK

**Comment by mcuking** [comment]
After looking into sanpack-core source code, I find the ResolveFile props of Sandpack has nothing to do with the probolem. The readFile function of ResolveFile is called when dependencies file is not in the transpiledModules. But in codesandbox.io, dependencies file is in the transpiledModules, so there is no dynamic fetch for  dependencies file and readFile function of ResolveFile would not be called.

So I am curious about the really reason of difference behaviors between codesandbox.io and sanpack bunlder.

Looking forward to a reply~

![image](https://user-images.githubusercontent.com/22924912/146660642-98d36c29-0225-4191-b031-cd576557582f.png)

**Comment by mcuking** [comment]
Solve the problem by make a PR 😎

https://github.com/codesandbox/dependency-packager/pull/38

This issue could be closed.
