### ISSUE TITLE
appsync with opensearch 

### ISSUE THREAD

**Issue by purushottam858** [codesandbox/codesandbox-client#6364]
# 🐛 bug report
https://github.com/aws/aws-appsync-community/issues/191 can you  guys help me here .

**Comment by JamesACS** [comment]
Hey @purushottam858 - If you've identified a bug please could you use our bug reporting template? 

If you'd just like some help with your code, we'd recommend checking out our Discord community: https://discord.gg/E7C4kT6q

**Comment by purushottam858** [comment]
last31777@gmail.com is my mail , can you please help me with the issue .

**Comment by JamesACS** [comment]
Hey @purushottam858 - Please remove your email from your comment - just to keep your information safe. 

You can email us at support@codesandbox.io if you've realised any issues with the platform and we'll look into them.

**Comment by sannek** [comment]
I hope you found the help you needed. I'm closing this issue since it's not CodeSandbox related.
