### ISSUE TITLE
Duplicate file

### ISSUE THREAD

**Issue by projektorius96** [codesandbox/codesandbox-client#6370]
# 🌈 Feature

Duplicate file just like in VSC . If it's complicated to implement, then at least have right click for copy-paste to cwd within file(s) outline.
Thank you

**Comment by sannek** [comment]
Thanks again for the feature request, I'll pass it on!

(And if you don't mind me asking, where _is_ the duplicate file option in VSCode? I've really wanted that before and cannot for the life of me find it. Or do you mean copy/paste from the outline?)

**Comment by projektorius96** [comment]
I meant copy-paste as duplicating , unless true duplicating could be implemented into Codesandbox IDE , then it definitely would be one little step over VSC ! Thanks
