### ISSUE TITLE
Export folder (directory)

### ISSUE THREAD

**Issue by projektorius96** [codesandbox/codesandbox-client#6372]
# 🌈 Feature

Exporting a single sandbox is fun, but would be fun someday to have an option to export e.g. zipped folder from viewport or outline .
Thanks.

**Comment by sannek** [comment]
Thanks for the feature request! 

Do you mean one folder from a sandbox, or do you mean a folder full of sandboxes from your dashboard?

**Comment by projektorius96** [comment]
The second one to have an option for bulky export whereas as you said "_a folder full of sandboxes_" . Thanks .
