### ISSUE TITLE
File download is disallowed in Chrome

### ISSUE THREAD

**Issue by andreifloricel** [codesandbox/codesandbox-client#6378]
# 🐛 bug report

## Description of the problem

Export doesn't work in Chrome because iframe doesn't have the allow-downloads attribute. You'll see the corresponding warning in the browser console:

> Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details.

This issue was once fixed (see #4739 & #5163) by adding the missing `allow-downloads` flag, but the adjustment was then reverted (see bb8176517289179b8375896870b37f0cb8c71cb6) - not sure if on purpose or accidentally.

### To Reproduce

https://codesandbox.io/s/react-filesaver-example-wc1k9

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |    Chrome          |
| Operating System |              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by andrasbacsai** [comment]
Hey @andreifloricel!

It will be reactivated in #6384 as soon as it's merged and deployed.

**Comment by andrasbacsai** [comment]
@andreifloricel could you please check it now?

**Comment by andreifloricel** [comment]
It works, thanks! 🎉
