### ISSUE TITLE
feature: custom sidebar widget + custom explanation modal

### ISSUE THREAD

**Issue by faceyspacey** [codesandbox/codesandbox-client#64]
I think it would be incredibly useful and save you from having to build lots of features if, for example, users could embed their own chatbox iframe in a sidebar WorkspaceItem.

I'd like to put chat in, and perhaps other things like a youtube video iframe, and wouldn't have to request these features if I could embed things *somewhere*.

Another place is your own modal where you can do all sorts of things, like provide pretty documentation, videos, etc. 

I'm not sure which is the better/higher_priority of the 2 options. I'm leaning toward the drawer item, and an ability to specify which item is opened by default in the URL params--this way you can guarantee users see it, whereas a modal requires clicking something and many users might never see it. To me, that's the driving factor, and perhaps why the drawer item is the better place to start. 

But from an implementation point of view, a modal is easier to develop. So you could just put a "more info" link in the sidebar for users that have decided to create such a page. It pops up in a modal and has 2 tabs: "Write" and "Preview" just like a github comment/issue. It's basically the "Talk" section of a wikipedia article. 

If this stuff is done correctly, it will become a highly used feature of Sandboxes, just like readmes on github. I think the trick is to make it feel like a readme, so it's familiar, and therefore likely to be used more. ...but it needs to be better than a readme. Iframe embeds need to be allowed basically. And support for more custom styles. And you should be able to develop it in React, not markdown! ...by the way, i think u should rename to *React Sandbox* or similar. Do you support Vue and Angular. Rename again once u have those areas tamed. Better to do one thing really well. Explode in popularity because of it, and then expand. But I'm sure u have other plans, especially if u already put the work to support Vue etc.

----

Wanna know something funny, both our repos are at exactly 274 stars as of this writing:

https://github.com/faceyspacey/redux-first-router
![screen shot 2017-07-18 at 1 11 15 pm](https://user-images.githubusercontent.com/154732/28337501-a9ac185a-6bba-11e7-9b47-639623d6b123.png)

**Comment by faceyspacey** [comment]
this feature needs a simple V1, which is just a markdown display of ur readme. thats it. But it needs a special tab or button to draw the user's attention to it, similar to how u have an Embed field in the ShareView which is the same as the Editor URL. Ur smart brother.  U get it. So just get that markdown renderer done, add a fancy button to view the README at the top of the sidebar, et voila.

**Comment by Saeris** [comment]
I've scoped down this request to be a simple Markdown Preview and added it to our public backlog. Closing this for now. Please check here for the status of this feature:

https://www.notion.so/Add-Markdown-Preview-764064a9cf3444e6bd7ac5d61145a704
