### ISSUE TITLE
Code refresh results in multiple requestAnimationFrame running in parralel

### ISSUE THREAD

**Issue by swingingtom** [codesandbox/codesandbox-client#6413]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Hi codesandbox team and followers !

When editing code files the preview is automatically being "refreshed". It do not acts as reload, and a currently running requestAnimationFrame is not cancelled during that "refresh" resulting in multiple requestAnimationFrame running in parralel.

I know about the `runonclick=1` options, and Im also aware of those issues #3899 and #3527. But I think they differ a bit because here it doesn't involve having user code issues generating browser hangs or infinite loops. 

## How has this issue affected you? What are you trying to accomplish?
Im trying to accomplish simple time updated sandboxes, and still being able to enjoy the auto-refresh feature.

### To Reproduce

- Generate a standard requestAnimationFrame loop that print in console
- Make some code changes
- Notice that multiple prints are in the console.

```javascript
// some id generated on runtime
const id = Math.random();

// raf
function loop() {
  console.log(id);
  requestAnimationFrame(loop);
}
requestAnimationFrame(loop);
```

Complete sample : 
```javascript
const id = Math.random();
function loop() {
  console.log(id);
  requestAnimationFrame(loop);
}
requestAnimationFrame(loop);

// When we reload the preview, it works fine (only one number in console)
// But, if we start modifying this file
// each refresh will add a new requestAnimationFrame
// We will notice multiple number in the console.
const editThisToRefreshPreview = 2;

// Some console cleanup to avoid freezes or browser hanging
setInterval(() => {
  console.clear();
}, 1500);

window.addEventListener("beforeunload", () => {
  console.log("Before unload");
});
```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |      918060405        |
| Browser          |      Chrome Version 97.0.4692.71 (Official Build) (64-bit)        |
| Operating System |      Windows10        |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @swingingtom - I believe this is because of a race condition with our HTML hydration logic and that script. 

This is a difficult fix as all sandboxes render once from the server and once from the client.

The issue can be resolved by refreshing the preview in most cases though - although it's not ideal does this work for you?

**Comment by JamesACS** [comment]
@swingingtom - Unfortunately it's not possible as it's a part of how CodeSandbox updates and renders previews 😞 - The only solution is refreshing the preview manually (and instructing other to do the same at the moment). But it's a known issue on our end.

**Comment by swingingtom** [comment]
Ok so I would close this issue.

> But it's a known issue on our end.

If you have the link, I would subscribe to its notifications. And share this issue reproduction if it can help.

**Comment by swingingtom** [comment]
Using `sandbox.config.json` with `Hard Reload on Change` set to `true` will be my current workaround

**Comment by JamesACS** [comment]
It's been raised on our internal board, so I'm afraid I don't have a link to share!
