### ISSUE TITLE
GitHub files don't seem fetched correctly

### ISSUE THREAD

**Issue by Haroenv** [codesandbox/codesandbox-client#6442]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Hey @sannek / @lbogdan, it seems that certain repositories no longer correctly seem fetched. No information or files can be found:

<img width="1414" alt="Screenshot 2022-02-03 at 13 18 45" src="https://user-images.githubusercontent.com/6270048/152341455-9098a170-5349-4030-962b-eee8c99971d0.png">

I think this may be the same issue as happened back in September in https://github.com/codesandbox/codesandbox-client/issues/6109

## How has this issue affected you? What are you trying to accomplish?

Examples in our documentation no longer work

### To Reproduce

- https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/React%20InstantSearch/injected-content
- https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/React+InstantSearch/injected-content

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |    54f46eeec          |
| Browser          |       Safari / Chrome       |
| Operating System |         macOS     |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @Haroenv - I've just viewed those Sandboxes on this end and they all seem to be working?

**Comment by Haroenv** [comment]
duplicate, sorry GitHub was down for a moment I think
