### ISSUE TITLE
Screenshots are disappearing from Github imported sandboxes

### ISSUE THREAD

**Issue by igordanchenko** [codesandbox/codesandbox-client#6444]
# 🐛 bug report

## Preflight Checklist

- [X] I have read the [Contributing Guidelines][contributing] for this project.
- [X] I agree to follow the [Code of Conduct][code_of_conduct] that this project adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Description of the problem

Several days ago I noticed 2 of my Github imported sandboxes lost their screenshots, and today another 2 sandboxes got their screenshots replaced with a default banner.

<img width="890" alt="Screen Shot 2022-02-03 at 3 36 23 PM" src="https://user-images.githubusercontent.com/64441155/152429707-a55a44ed-7959-4a88-9221-e58573258217.png">

Pinging https://codesandbox.io/api/v1/sandboxes/<sandbox_id>/screenshot.png to re-generate screenshots no longer seems to work.

## To Reproduce

Visit one of the following pages.
 - https://codesandbox.io/examples/package/react-photo-album
 - https://codesandbox.io/search?query=react%20photo%20album&page=1&configure%5BhitsPerPage%5D=12&refinementList%5Btags%5D%5B0%5D=react%20photo%20album

## Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  [`5ikre`](https://codesandbox.io/s/github/igordanchenko/react-photo-album/tree/main/examples/columns-layout)   |
| Browser          |  Safari / Chrome  |
| Operating System |  macOS  |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Thanks for raising this @igordanchenko - we're aware of a few issues with how CodeSandbox generates screenshots at the moment and are working on a fix!

**Comment by andrasbacsai** [comment]
Hey @igordanchenko,

We fixed our screenshot service, it should work now as expected!

**Comment by igordanchenko** [comment]
Thanks! 

Is there a way to re-generate a screenshot in case the system captured an incorrect one? For instance, the following screenshot captured black "installing dependencies" screen - https://codesandbox.io/api/v1/sandboxes/81r48/screenshot.png

The previously suggested endpoint https://codesandbox.io/api/v1/sandboxes/<sandbox_id>/screenshot.png to longer seems to work.

**Comment by igordanchenko** [comment]
Unfortunately I'm not seeing any effect after making a call to that endpoint.

```
curl -sSD - https://codesandbox.io/api/v1/sandboxes/81r48/screenshot.png -o /dev/null

HTTP/2 302 
date: Thu, 17 Feb 2022 15:29:25 GMT
content-type: text/html; charset=utf-8
location: https://screenshots.codesandbox.io/81r48/21.png
cache-control: private, max-age=0, no-cache, no-store
x-request-id: FtScbz5ZvHY2M-EwaRDB
via: 1.1 google
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
cf-cache-status: MISS
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 6df00d15fc821774-EWR
```

It does redirect to the current screenshot, but never updates it.

**Comment by igordanchenko** [comment]
Huh, that did the trick, thank you. I guess this approach is perfectly fine for hosted sandboxes, however it's a little cumbersome for GitHub-imported template repositories as every change requires a push to GitHub repository.

I'm closing this ticket since the original issue is resolved. Thanks again.

But on a side note I want to mentioned the following issues with screenshots that I observed while trying to re-generate my screenshots.

1) Quite often screenshot captures a black screen with "transpiling modules" or "installing dependencies" message.
2) The screenshots are displayed cropped out on horizontal axis on the package examples page (example - https://codesandbox.io/examples/package/react-photo-album)
3) Quite often screen shots are captured before the page is completely loaded (example - https://screenshots.codesandbox.io/kimxv/19.png)

**Comment by JamesACS** [comment]
No problem, glad it worked! As for the Github templates that would definitely be a bit more tricky but we've had a few screenshot issues recently so are working on a bit of an overhaul!
