### ISSUE TITLE
Cloudflare results in 429 errors for Team Pro / vite user

### ISSUE THREAD

**Issue by rayfoss** [codesandbox/codesandbox-client#6453]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

Trying to run some client side Vite code. The app won't even start as it can never load all dependencies in dev mode.

![Screenshot 2022-02-08 16 09 35](https://user-images.githubusercontent.com/876076/153084007-7a35691d-14cd-4bec-8598-a0e7948fa152.png)

I've seen about 200 of the Cloudflare checking your browser paywalls today. There seems to be no workaround but to wait for a VERY SLOW production build... which completely defeats the purpose of CSB. The problem happens in a breakout tab and in the built in browser... the built-in browser frequently returns the Chrome sad-face as Cloudflare has X-Frame-Options set to block on the captcha screen.

I have a Team Pro account, but the isPro() check doesn't seem to be working as I'll get a Pro emblem on the sandbox, but also an "Upgrade to Pro" advertisement under the 3 dot menu.

### To Reproduce

Run Vite in a large project with ~100 components. This causes CloudFlare to panic and starts blocking everything indiscriminately. Disabling Ublock Origin did not help.

### Link to sandbox: [Vite vuetify](https://codesandbox.io/s/vite-ts-fc4vg)

- This sandbox is very small, to reproduce the problem you may have to refresh the preview/tab 3 times to exhaust the quota and get 429 errors.
- The issue is much, MUCH, worse on vue2 vite projects which can't do tree shaking. At a point around 3 times the size of this example, the sandbox becomes unusable.
- Ignore the linting errors... this project uses SFC Script Setup, which (the deprecated since 2020 in favor of Volar) Vetur does not support.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |   1ca347c42 (2022-02-08)  |
| Browser          |   Chrome 98   |
| Operating System |   Chrome   |

### Notes

@HooK2000 also [encountered this issue](https://twitter.com/EliasGuenther/status/1487372060208807946)
![Screenshot 2022-02-09 12 26 12](https://user-images.githubusercontent.com/876076/153265821-ba26ad49-a99e-4ed9-9e49-9ee681018609.png)

**Comment by JamesACS** [comment]
Hey @rayfoss - I've just ran the Sandbox and haven't been able to reproduce the issue. Are you still experiencing it?

**Comment by rayfoss** [comment]
I hit refresh on the preview and I could still reproduce it. Your IP might be whitelisted in cloudflare. I'm based in Texas.

![Screenshot 2022-02-18 13 24 30](https://user-images.githubusercontent.com/876076/154748763-1bd57284-6d39-4190-b26a-5edcc7d2d9b3.png)

**Comment by lbogdan** [comment]
Hey @rayfoss ,

I can reproduce it on my side if quickly refreshing 2-3 times. We'll look into relaxing the rate-limit (although that's there for a reason).

What you can do in the meanwhile when this happens is to open the sandbox preview URL in a new tab - you should see a Cloudflare interstitial page, and then it should load again.

**Comment by rayfoss** [comment]
> Cloudflare` interstitial page

The page doesn't seem to help at all, it will show up 50 times an hour if you keep trying. The reproduction sandbox is a modern Webpack5 tree shaken minimal 3 module example. My real world Vite code makes around 200x more requests than that. It would be a great relief to remove the limit for Team Pro users.

This is an existential problem for me as Vite is vital lowering my cycle times from 1 minute to a second... and yet only the most gingerly Vite projects/prototypes will run on CSB SSE.

If your reverse-proxy/load balancer charges you per request, it's time to switch the architecture. Direct Nginx/Pod/Container communication vs Cloudflare stymied communication would be a selling point.

Thanks for acknowledging the issue!

**Comment by lbogdan** [comment]
@rayfoss We relaxed some rate-limits, can you please check again and let us know if you see any improvement?

**Comment by rayfoss** [comment]
It LIVES!

Webpack 5's deprecation of Node globals is a pita to work around
