### ISSUE TITLE
Unable to import vendor stylus files

### ISSUE THREAD

**Issue by aaronrosenthal** [codesandbox/codesandbox-client#646]
I am trying to import a vendor stylus file but I get an error like this:

    ReferenceError
    /node_modules/vuetify/src/stylus/main.styl:298:9
       294| 
       295| index(list, value)
       296|   for val, i in list
       297|     return i if val == value
       298| @import './app'
    ----------------^
       299| @import './components/*'
       300| 
    
    glob is not defined

Am I doing something wrong or is this not currently possible?

Reproduction link: https://codesandbox.io/s/3vmv7m3o16

**Comment by akki-jat** [comment]
I am getting the same error

**Comment by lisalemons** [comment]
I believe this is the solution to the problem, but given the nature of CodeSandbox, it isn't a fix I can execute. What are the possibilities this issue will be fixed?

https://stackoverflow.com/questions/44366614/nameerror-name-glob-is-not-defined

**Comment by Tuszy42** [comment]
I am also getting this error, cannot reproduce an error regarding Vuetify because of this error...
