### ISSUE TITLE
ModuleNotFoundError: Could not find module in path "" relative to ""

### ISSUE THREAD

**Issue by pksjce** [codesandbox/codesandbox-client#6473]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [ ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Seeing an error in https://codesandbox.io/s/ancient-rgb-70b30 with the latest @primer/react version. This is specifically after a [change](https://github.com/primer/react/pull/1771) that introduced subpath exports. 
The library version works fine on [stackblitz](https://stackblitz.com/edit/react-wupdy4) and on webpack powered builds in create-react-app and nextjs. I get the following error on codesandbox

`ModuleNotFoundError: Could not find module in path: '@primer/react/lib-esm/Button' relative to '/node_modules/@primer/react/lib-esm/Dialog/Dialog.js'`

![image](https://user-images.githubusercontent.com/417268/153783534-d391c6a6-d2f9-4f08-87bb-c3a7545b495c.png)

In the above error the relative path `../Button` inside `/node_modules/@primer/react/lib-esm/Dialog/Dialog.js`. During resolution, it becomes `@primer/react/lib-esm/Button` when expected path should be `node_modules/@primer/react/lib-esm/Button/index.js`. 
Do you think it may have something to do with the new resolver changes introduced in https://github.com/codesandbox/codesandbox-client/pull/6148 ?

Here is the issue tracked in `@primer/react` https://github.com/primer/react/issues/1863

I reported the same bug under https://github.com/codesandbox/codesandbox-client/issues/6172. 

## How has this issue affected you? What are you trying to accomplish?

We are unable to use @primer/react library in any codesandbox.

### To Reproduce

1. Create a react codesandbox
2. Import components from `@primer/react`. 
3. Use in the codesandbox to see the error pop up.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |              |
| Operating System |              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @pksjce - Have you tried updating the version of Primer in your Dependancies?

**Comment by pksjce** [comment]
Hey! yes, It actually works with an older version 34.3 but not with the newer 34.4 onwards.

**Comment by JamesACS** [comment]
Thanks @pksjce - So this is likely to be an issue with the newer versions. I'll raise it as a bug on our end so we can investigate!

**Comment by devanshj** [comment]
@JamesACS If you don't mind can I ask if there's an ETA for a fix? (I love using sandpack (thanks!) for my blog but stumbled upon this issue)

**Comment by JamesACS** [comment]
Hey @devanshj - I'm afraid we don't have a precise ETA, it's been added to our backlog but not allocated yet.

**Comment by devanshj** [comment]
Ah no problems, I hope it'll be fixed soon. Thanks!

(Also wait I just read above that older 34.3.0 version still works, ha that's good enough for my case, I'll use that version :P)

**Comment by pksjce** [comment]
Hey @devanshj - If you want to use the newer version of primer/react, you can test using https://stackblitz.com/edit/primer-react-v35-z28fze?file=index.tsx

**Comment by devanshj** [comment]
Thanks @pksjce, I was aware of that but as I said I wanted it to use it in sandpack for my blog which will need this issue to be resolved.

(Aside: I've already published the [article](https://devanshj.me/writings/what-if-view-was-tightly-coupled-to-logic). Turns out I wanted `Textarea` which was not in the older version so I ditched `@primer/react` for `@primer/css` as all I needed was a button and a textarea xD)

**Comment by pksjce** [comment]
Thanks so much for the fix @DeMoorJasper !
