### ISSUE TITLE
Cache busting issue

### ISSUE THREAD

**Issue by oliviertassinari** [codesandbox/codesandbox-client#6484]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Codesandbox resolves dependencies with the wrong version.

### To Reproduce

https://codesandbox.io/s/basicspeeddial-material-demo-forked-0pf9wf?file=/package.json

<img width="511" alt="Screenshot 2022-02-21 at 16 57 29" src="https://user-images.githubusercontent.com/3165635/154989429-37e0332a-3885-4879-b65b-7441cffeda5b.png">

Opening the same locally works.

This `import { registerStyles } from "@emotion/utils` API is new: https://github.com/emotion-js/emotion/search?q=registerStyles&type=. it was released in v1.1.0 https://unpkg.com/browse/@emotion/utils@1.1.0/src/index.js. However, even if @emotion/styled@11.8.1 asks for a minimum of @emotion/utils@v1.1.0 it seems to resolve v1.0.0 hence break.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest? |
| Browser          | Chrome 98 |
| Operating System | macOS |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @oliviertassinari - This seems like its an issue with an older version being pulled from somewhere, but loading up the sandbox I'm not getting the above error. Did you manage to fix this?

**Comment by oliviertassinari** [comment]
The error is no longer reproducible on my above link. I assume that the cache has TTL (time to live) that has expired.

**Comment by JamesACS** [comment]
@oliviertassinari - Given we've not been able to reproduce we'll close for now but if you run into it again please let us know so we can investigate further

**Comment by JamesACS** [comment]
Hey @karlhorky - I've just loaded that Sandbox and it's working, did you find a fix?

**Comment by karlhorky** [comment]
Didn't touch it hehe, maybe over time this error resolves itself.

If this is the case, it needs to be debugged quickly when it occurs...

**Comment by oliviertassinari** [comment]
A new instance of the caching issue: https://codesandbox.io/s/xjzph1?file=/demo.js

<img width="537" alt="Screenshot 2022-05-18 at 18 37 22" src="https://user-images.githubusercontent.com/3165635/169095855-05bd75e0-e6cf-4f8c-a67a-f0488c303f2a.png">

**Comment by karlhorky** [comment]
Yep, failing for me too, cc @JamesACS

**Comment by JamesACS** [comment]
Thanks both, this is likely due to how we pull updates for packages, it can sometimes take up to a few days for the updates to feed through (but usually only around a couple of hours).
