### ISSUE TITLE
Support for TypeScript version 4.5+

### ISSUE THREAD

**Issue by gvergnaud** [codesandbox/codesandbox-client#6497]
Hello! 

I'm the author of an open source library called [TS-Pattern](https://github.com/gvergnaud/ts-pattern) and I find Codesandbox immensely useful for documentation and bug reports. 

I'm about to release a new version of this library (https://github.com/gvergnaud/ts-pattern/pull/70) which makes use of [tail call elimination](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#tailrec-conditional) to provide better type inference. It works great on TS v4.5, but on  codesandbox's TS version (v4.4), type checking throws `type instantiation is excessively deep and possibly infinite` errors. 

Is upgrading typescript to version 4.5 or higher on your radar?

Thanks again for building such an amazing product!

**Comment by CompuIves** [comment]
Hey! Good notice, I've opened a PR for it that we should be able to merge soon!

**Comment by gvergnaud** [comment]
Amazing, thank you so much!
