### ISSUE TITLE
Dependency is not resolved correctly

### ISSUE THREAD

**Issue by dhayab** [codesandbox/codesandbox-client#6548]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Hi, there seems to be an issue with `instantsearch.js` not being correctly resolved in this sandbox. The app works locally and it seems the dependency is fetched as well (it is listed in Intellisense in `/sandbox/node_modules/instantsearch.js`).

The last screenshot (see below) made me wonder if the issue is related to the fact that this package ends with `.js`, and somehow some part of the tooling interprets it as `instantsearch.ts`?

## How has this issue affected you? What are you trying to accomplish?

The sandbox cannot be run at all.

### To Reproduce

Below you'll find a link to the sandbox in question and the screenshots of the errors I got.

### Link to sandbox: [link](https://codesandbox.io/s/github/algolia/autocomplete/tree/next/examples/instantsearch?file=/src/instantsearch.ts)

<img width="934" alt="image" src="https://user-images.githubusercontent.com/154633/158561948-233965d1-4264-4580-8491-fdd2ef1ce227.png">

<img width="943" alt="image" src="https://user-images.githubusercontent.com/154633/158561985-683c7a4a-fddb-44e3-9d6f-234d6ab5fb82.png">

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 143e16a13 |
| Browser          | Chrome |
| Operating System | macOS 12.2 |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @dhayab , 

I've just had a look and while I'm getting the Widgets error, I'm not seeing the dependency not found. Did you manage to resolve this issue?

**Comment by dhayab** [comment]
Doing a late spring cleaning on my opened issues, and this does not happen anymore.
