### ISSUE TITLE
TaskQueue: Error running task. Invalid regular expression: invalid group specifier name.

### ISSUE THREAD

**Issue by Haroenv** [codesandbox/codesandbox-client#6583]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I'm getting the following error in a toast:

```
TaskQueue: Error running task. Invalid regular expression: invalid group specifier name.
```

<img width="1419" alt="Screenshot 2022-03-29 at 09 53 50" src="https://user-images.githubusercontent.com/6270048/160561775-8436929e-306e-4832-960d-32834c5a7e46.png">

### To Reproduce

just load a sandbox

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |04dc773eb|
| Browser          |Safari TP Release 142 (Safari 15.4, WebKit 17614.1.5.16)|
| Operating System |      macOS        |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by Haroenv** [comment]
I still can reproduce this, but only on Safari

**Comment by JamesACS** [comment]
Hey @Haroenv - I'm afraid we'll need a link to the Sandbox to investigate this further, but this could be due to an extension such as an adblocker if it's only on a specific browser .

**Comment by JamesACS** [comment]
Hey @Haroenv - I'm still unable to reproduce this I'm afraid.

**Comment by Haroenv** [comment]
On further research this only happens in the Tech preview of Safari, and thus isn't really a bug in CodeSandbox, sorry for the distraction!
