### ISSUE TITLE
Undeterministic Error opening Vue 3 Sandbox template on Firefox 98

### ISSUE THREAD

**Issue by derMart** [codesandbox/codesandbox-client#6585]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Sometimes opening an unmodified Vue 3 template results in `import declarations may only appear on top level of a module`.
Refreshing the page the template sometimes works again.

### To Reproduce
Sadly undeterministic. Go to codesandbox.io -> create sandbox -> Vue 3 -> problem appears after loading completes sometimes

Here is a screenshot of the problem:
![Screenshot from 2022-03-29 17-08-36](https://user-images.githubusercontent.com/1069456/160643944-3bbef3be-988a-4bf8-b9c8-7333568280f7.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  codesandbox.io            |
| Browser          |    Firefox 98          |
| Operating System |   Ubuntu 21.10           |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @derMart - Thanks for flagging this. 

We're aware of a few issues with the Vue3/Angular templates at the moment and are working on a fix

**Comment by asvae** [comment]
Everything seems to be working for this version, so might be appropriate to close this. :)

**Comment by JamesACS** [comment]
Thanks for the heads up @asvae - Closing this now!
