### ISSUE TITLE
Missing border radius

### ISSUE THREAD

**Issue by jdbruxelles** [codesandbox/codesandbox-client#6620]
Hi, I noticed a missing border radius in the preferences modal. Here is a screenshot of how it is actually: 
![image](https://user-images.githubusercontent.com/18559798/162975186-ce782d58-1254-4905-a1b7-f698c40d8635.png)

And how it must be:
![image](https://user-images.githubusercontent.com/18559798/162974961-4ca476a0-d8f2-40eb-b1db-3e8ae32311a2.png)

by adding:
```css
border-radius: 8px 0 0 8px;
```

**Comment by JamesACS** [comment]
Thanks for flagging @jdbruxelles - Raised this!
