### ISSUE TITLE
Sandbox initialization hangs

### ISSUE THREAD

**Issue by StephenBarlow** [codesandbox/codesandbox-client#6625]
Sandbox URL: https://codesandbox.io/s/practical-snyder-48p1r2roz4 / https://48p1r2roz4.sse.codesandbox.io/

Hello! One of our Codesandbox instances is currently hanging on startup. Something similar happened with another of our sandboxes about [eight months ago](https://github.com/codesandbox/codesandbox-client/issues/6025) so maybe the fix is similar?

Any help would be greatly appreciated! 🙏

**Comment by JamesACS** [comment]
Hey @StephenBarlow - Sorry for the delay. This seems to be working now?

**Comment by StephenBarlow** [comment]
Ah yes sure enough! Thanks @JamesACS 🙏
