### ISSUE TITLE
Error: spawn xdg-open ENOENT

### ISSUE THREAD

**Issue by huturen** [codesandbox/codesandbox-client#6642]
# 🐛 bug report

## Preflight Checklist

- [X] I have read the [Contributing Guidelines][contributing] for this project.
- [X] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Could not start service in the codesandbox below, command line threw "Error: spawn xdg-open ENOENT" error.

<img width="589" alt="image" src="https://user-images.githubusercontent.com/5173298/163849741-2113f1c7-ba86-43a9-bfaa-a96c6b520296.png">

```
sandbox@sse-sandbox-gnbzrk:/sandbox$ yarn dev
yarn run v1.22.17
$ http-request-mock-cli -t es6 -e none -w "vite --config ./config/vite.config.dev.ts --host"
this.appRoot: /sandbox/
[http-request-mock] Watching: /sandbox/mock

  vite v2.9.5 dev server running at:

  > Local:    http://localhost:3000/
  > Network:  http://192.168.203.6:3000/

  ready in 388ms.

events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:3000/' ]
}

```

### To Reproduce

[Go to this link](https://codesandbox.io/s/github/huturen/http-request-mock-curd/tree/main)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |     https://codesandbox.io/s/github/huturen/http-request-mock-curd/tree/main         |
| Browser          |         Google Chrome 100.0.4896.88 (x86_64)     |
| Operating System |         MacOS     |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by huturen** [comment]
Many thanks. @JamesACS

**Comment by Fanxin-Yang** [comment]
Hi! I've got the same problem when I'm trying to run the application on a server with Ubuntu 20.04.4 LTS.
However it works fine on MacOS locally.

Can you please explain more about how to wrap the original spawn cell with a wrapped?

**Comment by Jiancong** [comment]
<img width="526" alt="1663226368438" src="https://user-images.githubusercontent.com/701159/190340628-94adaa90-6b3c-4d8a-b07b-f6e485849ba7.png">

Change this fix the issue.

**Comment by lee-bran** [comment]
I have the same problem and use the following command to solve it：

sudo` apt-get install xdg-utils

**Comment by stevenbdf** [comment]
> I have the same problem and use the following command to solve it：
> 
> sudo` apt-get install xdg-utils

For people having issues connecting to decontainers from JetBrain Gateway and IDEs. This worked for me ^ Thanks @lee-bran

**Comment by Pablitox26** [comment]
> I have the same problem and use the following command to solve it：
> 
> sudo` apt-get install xdg-utils

thx, it worked for me

**Comment by pypae** [comment]
> <img alt="1663226368438" width="526" src="https://user-images.githubusercontent.com/701159/190340628-94adaa90-6b3c-4d8a-b07b-f6e485849ba7.png">
> 
> Change this fix the issue.

I had to use `vite --no-open` for it to work.

**Comment by RampagerB** [comment]
I may found out why this happens.
In your `vite.config.ts` you may set `open: true` or in your package.json `"dev": "vite --open"`, this `open` means it'll try to open your browser after start the dev server, but in some server they don't have a browser, so error shows.

**Comment by bestii** [comment]
> I may found out why this happens. In your `vite.config.ts` you may set `open: true` or in your package.json `"dev": "vite --open"`, this `open` means it'll try to open your browser after start the dev server, but in some server they don't have a browser, so error shows.

Thank you this was the problem.

**Comment by Gautam-Hegde** [comment]
> I have the same problem and use the following command to solve it：
> 
> sudo` apt-get install xdg-utils

Additionally, using `host:true` in the Vite config worked for me
```` <code>export default defineConfig({
  plugins: [react()],
  server: {
    port: 3000,
    host: true, 
    open: true
  },
  },

**Comment by lucasquin** [comment]
add --host in my package.json in script solves for me:

`"docker-dev": "vite dev --host"`
