### ISSUE TITLE
Sandbox timeout message on a saved sandbox.

### ISSUE THREAD

**Issue by santiagopuentep** [codesandbox/codesandbox-client#6652]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Leaving the tab opened for some time shows a message of sandbox timed out with two options, "create new sandbox" or "fork sandbox". If I refresh the page I can still use the same sandbox, but all my tabs are closed.

I believe that message shouldn't appear at all on a saved sandbox, since I can refresh the page and keep using it.

## How has this issue affected you? What are you trying to accomplish?

I'm simply trying to work on code for more than a few hours.

### To Reproduce

Fork a sandbox and let the tab opened for a few hours, maybe half a day, to see the message.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |      ???        |
| Browser          |        Vivaldi 5.2.2623.39      |
| Operating System |       Windows 10       |

**Comment by JamesACS** [comment]
Hey @santiagopuentep - Would you be able to send us a screenshot of the exact error you encounter the next time it appears?

**Comment by santiagopuentep** [comment]
It's not happening anymore, I can't reproduce it again.

**Comment by JamesACS** [comment]
That's great to hear @santiagopuentep - we'll close this for now but please update us if it changes
