### ISSUE TITLE
Sandbox Error, refresh the page - Stuck at Initializing Sandbox Container

### ISSUE THREAD

**Issue by dpkreativ** [codesandbox/codesandbox-client#6663]
# 🐛 bug report

## Preflight Checklist

- [ ] I have read the [Contributing Guidelines][contributing] for this project.
- [ ] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [ ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
I have been trying to run my NextJS code on CodeSandbox without success. I keep getting stuck at "Initializing Sandbox Container."

## How has this issue affected you? What are you trying to accomplish?
This issue is causing me a lot of delays, and there is no error message to see what is wrong, it just keeps "Initializing Sandbox Container"

### To Reproduce
Attempt to create a new Sandbox with this GitHub repo: https://github.com/dpkreativ/nextjs-music-art-demo
Here's the CodeSandbox itself: https://codesandbox.io/s/zen-snowflake-s62fq6

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | This current one on the browser |
| Browser          | Google Chrome |
| Operating System | Windows 10              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @dpkreativ - I'm afraid I can't access that Sandbox, did you resolve the issue?

**Comment by dhamaniasad** [comment]
I get this ALL THE TIME. It never seems to work. I've tried across devices, browsers, incognito mode, unregistering service workers, clearing storage, etc. Been facing this for months.

**Comment by sjbuysse** [comment]
I'm having this too...

**Comment by JamesACS** [comment]
@sjbuysse Please could you create a new bug report for us?

**Comment by aboveyunhai** [comment]
@JamesACS 
here was the broken one while I was forking a working repo to answer a community question: 
https://codesandbox.io/s/wizardly-sea-n8rzyn?file=/src/main.tsx
The working one was broken after I added new packages into the package dependency.

**Comment by sangimed** [comment]
Same here with this sandbox https://codesandbox.io/s/sticky-vuetify-table-header-3o0km?from-embed=&file=/pages/index.vue
![image](https://github.com/codesandbox/codesandbox-client/assets/857405/b0505b27-d942-4e4e-9def-8f3f4696e801)

**Comment by prakhart111** [comment]
Getting a similar error, can anyone check this out? 
https://codesandbox.io/embed/66s923?fontsize=14&hidenavigation=1&theme=dark

Stuck at Initialization screen and getting some weird errors on the browser console.

![image](https://github.com/codesandbox/codesandbox-client/assets/86708181/31fc5071-ee0c-4532-91ab-9b53b5195461)

**Comment by seyedeliasfakoorian** [comment]
The commit @sangimed gave was the issue I had

**Comment by JamesACS** [comment]
Hello @prakhart111 -

It looks like this was created via our API and used an older configuration that created a V1 SSE environment. This shouldn't be able to happen. Our infrastructure no longer creates previews on this domain which is why the container isn't loading. We're currently looking on our end to figure out what parameter may have generated this result so we can prevent this occurring in the future. 

If you're trying to work using this environment please contact us at support@codesandbox.io with the URL of the fork you have created. We can manually upgrade the environment type so it will load in our current environments and editor.

**Comment by JamesACS** [comment]
For the original environment, this should now be working as expected (as should future forks)

**Comment by gachezra** [comment]
> Hello [@prakhart111](https://github.com/prakhart111) -
> 
> It looks like this was created via our API and used an older configuration that created a V1 SSE environment. This shouldn't be able to happen. Our infrastructure no longer creates previews on this domain which is why the container isn't loading. We're currently looking on our end to figure out what parameter may have generated this result so we can prevent this occurring in the future.
> 
> If you're trying to work using this environment please contact us at [support@codesandbox.io](mailto:support@codesandbox.io) with the URL of the fork you have created. We can manually upgrade the environment type so it will load in our current environments and editor.

Look harder, it's 2025 and I'm having the same issue. This is my third device trying to open my GitHub branch.
