### ISSUE TITLE
Dev Tools - Console outputs value by reference instead of an actual value at the time the code is being executed

### ISSUE THREAD

**Issue by timagixe** [codesandbox/codesandbox-client#6677]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Check code sample (or [sandbox](https://codesandbox.io/s/objective-snyder-cevg0q?file=/src/index.js)) below.

In console, after using in place sorting algorithm like `Array.prototype.sort()`, I expected to see following output, with arrays before and after sorting:

```text
BEFORE (10) [4, 1, 4, 8, 9, 2, 4, 6, 7, 5]
AFTER (10) [1, 2, 4, 4, 4, 5, 6, 7, 8, 9]
```

But for some reason the output in both cases is the same and it is the array after sorting:

```text
BEFORE (10) [1, 2, 4, 4, 4, 5, 6, 7, 8, 9]
AFTER (10) [1, 2, 4, 4, 4, 5, 6, 7, 8, 9]
```

<details>

<summary>
Screenshot
</summary>

<img width="1219" alt="Screen Shot 2022-05-07 at 7 12 52 PM" src="https://user-images.githubusercontent.com/60817786/167262866-37c57db2-b484-4153-a56d-888232e2b8a1.png">

</details>

In order to avoid this weird behavior with logging reference values in both time (before and after), I found meaningful to use `JSON.stringify()` - [link to the sandbox](https://codesandbox.io/s/optimistic-dewdney-bm8sgn?file=/src/index.js).

## How has this issue affected you? What are you trying to accomplish?
I expected to see different outputs, was confused by the current behavior.

### To Reproduce
1. Open https://codesandbox.io/s/objective-snyder-cevg0q?file=/src/index.js. 
2. Open console
3. Observe output

Code sample:
```js
const data = [4, 1, 4, 8, 9, 2, 4, 6, 7, 5];

console.log("BEFORE", data);

data.sort();

console.log("AFTER", data);
```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |      060861cf8        |
| Browser          |      Chrome Version 101.0.4951.54 (Official Build) (x86_64)        |
| Operating System |      MacOS        |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by timagixe** [comment]
Hi CodeSandbox Team!

The same applies to objects too. Code sample below.

```js
const data = { key: "value" };

console.log(data);

data["another_key"] = "another_value";

console.log(data);
```

Actual output:
```text
{key: "value", another_key: "another_value"}
{key: "value", another_key: "another_value"}
```

Expected output:
```text
{key: "value"}
{key: "value", another_key: "another_value"}
```

**Comment by JamesACS** [comment]
Hey @timagixe , 

This is due to a quirk of the third party library implementation for the CodeSandbox console. 

At the moment, entries are sent eagerly, to get the right order we'd need to make them lazy so they're only requesting the variables when you open the console. 

We're aware of the issue!

**Comment by timagixe** [comment]
Hello @JamesACS and thank you for the detailed explanation!

I am happy you are aware of this issue. I believe you are tracking this somewhere internally, that's why I am going to close this issue.
