### ISSUE TITLE
Codesandbox does not load any react project

### ISSUE THREAD

**Issue by slim-hmidi** [codesandbox/codesandbox-client#6686]
# 🐛 bug report

## Preflight Checklist

- [X] I have read the [Contributing Guidelines][contributing] for this project.
- [X] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
I open the codesandbox of any application and does not load the pag.

## How has this issue affected you? What are you trying to accomplish?

Use a codesandbox to test a react application.

### To Reproduce
Try to create a new sandbox react application or open any codesandbox example.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |      Chrome Version 101.0.4951.54 (Official Build) (x86_64)        |
| Operating System |       MacoS MONTEREY v12.3.1       |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @slim-hmidi , the Sandboxes seem to be working on this end?

**Comment by slim-hmidi** [comment]
yes it works now.
thanks
