### ISSUE TITLE
Unable to write Unit Tests for application - could not find dependency: '@testing-libarary/react' relative to '/src/tests/App.test.js'

### ISSUE THREAD

**Issue by theonly1me** [codesandbox/codesandbox-client#6698]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
I'm unable to write unit tests for my application and am experiencing the following error message when I try to import the @testing-library/react.

```
Could not find dependency: '@testing-libarary/react' relative to '/src/tests/App.test.js'

DependencyNotFoundError: Could not find dependency: '@testing-libarary/react' relative to '/src/tests/App.test.js'
``` 

## How has this issue affected you? What are you trying to accomplish?
I'm unable to add unit tests for my application

### To Reproduce
Uncomment the code in App.test.js and try to run the unit tests

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |     React/Typescript         |
| Browser          |         Chrome     |
| Operating System |          MacOS    |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @theonly1me 

It looks like you mispelled library (libarary) - if you fix this it solves the problem!

**Comment by theonly1me** [comment]
Hi James, 

Thanks for pointing that out, my apologies for raising such a trivial issue, not sure how I missed that. 

However, now that I've corrected the spelling, I'm still unable to run the tests because the any of the jest-dom methods such as 'toBeVisible()', 'toBeFalsy()' etc. are working on codesandbox. They work fine when I clone the repo locally and try to run them. On the sandbox however, I'm only able to use the toBe( ) method. Can you please let me know if I'm missing something?

Thanks,
Atchyut
