### ISSUE TITLE
Wrong Typescript declaration files resolution when using "latest" as package version

### ISSUE THREAD

**Issue by cherniavskii** [codesandbox/codesandbox-client#6701]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

In MUI we use Codesandbox for library demos. One of our packages is `@mui/x-data-grid` which is currently at version `5.11.0`.
For some reason, when setting package version to `"latest"` in package.json (`"@mui/x-data-grid": "latest"`) Codesandbox uses type declarations from package version `4.0.0`

## How has this issue affected you? What are you trying to accomplish?

We see typescript false positives - either missing declarations or wrong signatures.

### To Reproduce

- Go to this codesandbox: https://codesandbox.io/s/customloadingoverlaygrid-material-demo-forked-5x6r2e?file=/index.tsx
- Observe following error:
<img width="591" alt="Screenshot 2022-05-17 at 13 11 05" src="https://user-images.githubusercontent.com/13808724/168798662-2a044ed5-6cd7-4019-9c93-cbcce3c8fff4.png">

- Type declaration points to `/sandbox/node_modules/@mui/x-data-grid/dist/data-grid.d.ts` which does not exists in [version 5](https://unpkg.com/browse/@mui/x-data-grid@5.11.0/) of the package, but does exist in [version 4](https://unpkg.com/browse/@mui/x-data-grid@4.0.0/dist/data-grid.d.ts)
<img width="529" alt="Screenshot 2022-05-17 at 13 11 44" src="https://user-images.githubusercontent.com/13808724/168800131-b31c1db4-7375-406f-9597-92d2e9ab96a5.png">

It does resolve type declarations correctly when I change the package version in `package.json` (5.11.0 is currently latest version)

```diff
- "@mui/x-data-grid": "latest"
+ "@mui/x-data-grid": "5.11.0"
```
See https://codesandbox.io/s/customloadingoverlaygrid-material-demo-forked-800s03?file=/index.tsx:82-99
<img width="596" alt="Screenshot 2022-05-17 at 13 31 13" src="https://user-images.githubusercontent.com/13808724/168801224-043e3e63-3a4d-4059-bf2c-bd963e1b1c83.png">

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |   169bbc083       |
| Browser          |    Brave |
| Operating System |    MacOS     |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @cherniavskii ,

How long ago was the update? Our package search relies on Algolia, which can sometimes take up to a few days in rare cases to update to the latest version.

**Comment by cherniavskii** [comment]
Hey @JamesACS 
v5 stable was released in November 2021: https://github.com/mui/mui-x/releases/tag/v5.0.0

**Comment by cherniavskii** [comment]
@JamesACS to be clear, there's no issue with JS files, it's just type declarations file that is loaded from v4 for some reason
