### ISSUE TITLE
Website marked as phishing (again)

### ISSUE THREAD

**Issue by tiagorangel2011** [codesandbox/codesandbox-client#6707]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

My project has been marked as "phishing"

## How has this issue affected you? What are you trying to accomplish?

I am trying to make a demo of a platform I built, 1auth, but I can't use Code Sandbox. Migrating to glitch.com

### To Reproduce

Go to https://uyrw2q.csb.app/ (my sandbox's URL). You will see this:
![image](https://user-images.githubusercontent.com/70700766/169883786-bdc33900-51ab-4e7d-b6e2-14ce01ae0fd7.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 09ce8c24b |
| Browser          | Chrome (lastest version) |
| Operating System | Windows 11 |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by mirko314** [comment]
Just found this issue, sorry for hijaking! (Feel free to delete ) 
Thank you for building, we really enjoy using it!

Is there somewhere to report false positives for Phishing?
We use CSB for our open source examples and at least the following one got flagged as well as Phishing unfortunately.
See e.g. https://codesandbox.io/s/github/imgly/cesdk-web-examples/tree/v1.6.3/configure-presets-templates .
Github: https://github.com/imgly/cesdk-web-examples/tree/v1.6.3/configure-presets-templates
The examples are rather simple, so I do not know why they got flagged.

**Comment by tiagorangel2011** [comment]
Yes, this is very irritating

**Comment by tiagorangel2011** [comment]
Well, the problem continues... 😢

**Comment by tiagorangel2011** [comment]
I have created a new issue because this has happened again:
https://github.com/codesandbox/codesandbox-client/issues/6796

**Comment by Utwo** [comment]
> Just found this issue, sorry for hijaking! (Feel free to delete ) Thank you for building Codesandbox, we really enjoy using it!
> 
> Is there somewhere to report false positives for Phishing? We use CSB for our open source examples and at least the following one got flagged as well as Phishing unfortunately. See e.g. https://codesandbox.io/s/github/imgly/cesdk-web-examples/tree/v1.6.3/configure-presets-templates . Github: https://github.com/imgly/cesdk-web-examples/tree/v1.6.3/configure-presets-templates The examples are rather simple, so I do not know why exactly this one got flagged.

Sorry for the late response, this should work now.

**Comment by FirstWhack** [comment]
Do we want new GH issues for these or where are we to report this?

**Comment by Utwo** [comment]
For unbanning false positive sandboxes please use our support email address: support@codesandbox.io
