### ISSUE TITLE
Github Import bringing folders out of the path into files

### ISSUE THREAD

**Issue by lcschy** [codesandbox/codesandbox-client#6730]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

When trying to create a sandbox from a Github repo, and in a specific path, instead of only bringing files from the path, it's randomly bringing a folder that is on a directory above the specified path.

The folder marked below should not have been imported (It's in the upper directory):
<img width="422" alt="image" src="https://user-images.githubusercontent.com/9054729/171416692-76a948c3-4c83-4fea-bb6d-8cd2151d6754.png">

## How has this issue affected you? What are you trying to accomplish?

I'm trying to embed a working example in our guides but the sandbox will not work because of this additional unwanted folder.

### To Reproduce

Create a new sandbox using Github import from this path:
https://github.com/Basis-Theory/basis-theory-js-examples/tree/master/collect-cards-with-individual-elements

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |     Web     |
| Browser          |      Brave/1.39.111        |
| Operating System |     MacOS 12.4         |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by lcschy** [comment]
seems like the link is using a 'contains' approach for the path instead of exact match.

**Comment by aj-foster** [comment]
Yep, you're right. We have been having a few problems with the "new" importers, and recently changed back to the code found in `codesandbox-importers` as a result. Looks like you found a workaround for your code (nice debugging), but the current importers should work even if there are multiple folders matching the given path.
