### ISSUE TITLE
Errors are reported when using vue3 template setup

### ISSUE THREAD

**Issue by jerrywu001** [codesandbox/codesandbox-client#6762]
# Bug report

## Packages affected

-   [👉🏽 ] sandpack-react

## Description of the problem

**Errors are reported when using vue3 template setup**

```jsx
<Sandpack template="vue3"  />
```

```html
<template>
  <main id="app">
    <h1>{{ helloWorld }}</h1>
  </main>
</template>
                             
<script setup>
const helloWorld = ref("Hello World");
</script>
```

![image](https://user-images.githubusercontent.com/12525415/171375123-fb2bfd5f-14fa-4ceb-8171-e2384b25ae52.png)

**Comment by holazz** [comment]
same issue.

**Comment by Yoduh** [comment]
`<script setup>` seems impossible to use with codesandbox.  I hope this gets more attention as its becoming a more and more popular way to write components with Vue 3

**Comment by selucaciu** [comment]
same issue

**Comment by xiangrikuil** [comment]
same issue

**Comment by LowLifeArcade** [comment]
I wonder why this is still not working

**Comment by zymbth** [comment]
Looking forward to the support of vue3 syntax sugar `<script setup>`. At present, I have to convert my code by `setup()`

**Comment by zymbth** [comment]
您好，邮件已收到，谢谢！

**Comment by danilowoz** [comment]
We just merged a fix that address:
- Error on deleting a `script` or `style` tag;
- Support for `<script setup>`;

Here's a sandbox: https://codesandbox.io/s/charming-turing-oe2n17?file=/src/App.vue

Could someone please confirm that it's working?

**Comment by jerrywu001** [comment]
> We just merged a fix that address:
> 
> * Error on deleting a `script` or `style` tag;
> * Support for `<script setup>`;
> 
> Here's a sandbox: https://codesandbox.io/s/charming-turing-oe2n17?file=/src/App.vue
> 
> Could someone please confirm that it's working?

When will it be released?

**Comment by danilowoz** [comment]
It should already be live on CodeSandbox and Sandpack@1.17.1
