### ISSUE TITLE
requestFullscreen functionality not working

### ISSUE THREAD

**Issue by Arsikod** [codesandbox/codesandbox-client#6772]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Tried to implement full screen functionality on button click, received "fullscreen error" error

## How has this issue affected you? What are you trying to accomplish?
Cannt

### To Reproduce
click full screen button in sandbox

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |       Chrome       |
| Operating System |        mac      |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @Arsikod - This looks like an issue with the in-window preview. 

If you toggle the preview in a new window, the button works as expected
