### ISSUE TITLE
Sandbox marked as phishing (again)

### ISSUE THREAD

**Issue by tiagorangel2011** [codesandbox/codesandbox-client#6796]
### 🐛 bug report
# Website marked as phishing
This is the second time and it is very irritating. Original post: https://github.com/codesandbox/codesandbox-client/issues/6707

## Preflight Checklist

- [X] I have read the [Contributing Guidelines][contributing] for this project.
- [X] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
I am trying to make a demo of a platform I built, 1auth, but I can't use Code Sandbox. Migrating to glitch.com
Plus, this is the second time this happens, in the same sandbox. How? I don't know.
I would really like code sandbox to change it's patterns so we can type "login" in our sandbox.

## How has this issue affected you? What are you trying to accomplish?
Answer 1. I can't use codesandbox for this example.
Answer 2. Creating a new sandbox: nothing.

### To Reproduce
Go to https://uyrw2q.csb.app/ (my sandbox's URL). You will see this:

![image](https://user-images.githubusercontent.com/70700766/180613124-1af6c5b4-435c-4eeb-ae4d-4476a68fae19.png)

### Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | dfdabcd7c |
| Browser          | Chrome (lastest) |
| Operating System | Windows 11 |

Thank you!

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by Utwo** [comment]
The sandbox can be visited now as far as I can tell.
