### ISSUE TITLE
Downloading is disabled in Chrome in the Preview window

### ISSUE THREAD

**Issue by mohdashraf010897** [codesandbox/codesandbox-client#6831]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Export doesn't work in Chrome because iframe doesn't have the allow-downloads attribute. You'll see the corresponding warning in the browser console:

Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set.

## How has this issue affected you? What are you trying to accomplish?

We use CSB to demo our projects online. Customer demos are getting affected.

### To Reproduce

Click on any one of the given link-buttons that will let you save a CSV/ JSON file.
<img width="415" alt="image" src="https://user-images.githubusercontent.com/57627350/184840321-2fdf9c83-9ac3-4374-a50d-58f944932a97.png">

the console shows
<img width="313" alt="image" src="https://user-images.githubusercontent.com/57627350/184840456-e2e49b05-56f8-4416-b9b1-8cf098094e43.png">

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |        https://ohpo6e.sse.codesandbox.io/      |
| Browser          |     104.0.5112.79 (Official Build) (x86_64)         |
| Operating System |      MACOS - Monterey        |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Thanks for this report @mohdashraf010897 - I've passed it on to our team. 

Out of interest, have you checked out CodeSandbox Projects? It may work better for your use case.

**Comment by mohdashraf010897** [comment]
@JamesACS Works now! 👍🏻
