### ISSUE TITLE
ModuleNotFoundError Could not find module in path

### ISSUE THREAD

**Issue by yangg** [codesandbox/codesandbox-client#6855]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
ModuleNotFoundError after change draft name

### To Reproduce
open this sandbox https://codesandbox.io/s/hello1-80tfiw?file=/src/App.tsx
change it's name to something else, the preview refreshed with the error "ModuleNotFoundError
Could not find module in path: '@heroicons/react/solid' relative to '/src/pages/About.tsx'"

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |              |
| Operating System |              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by sannek** [comment]
Hi,
I can't reproduce your error. I have forked your sandbox and changed its name, but there are no problems. It just took a second for the dependencies to load.

If you're still having trouble, can you give more details about exactly what you are doing and what is going wrong?

**Comment by yangg** [comment]
![Sep-05-2022 23-21-08](https://user-images.githubusercontent.com/409225/188480636-0b18de95-2dad-4fc5-84b5-b38d6556858d.gif)
Here is the screen recording.
I've tested on the latest Chrome and Chrome Canary. Both reproduced

**Comment by sannek** [comment]
Strange! I still really cannot reproduce. I initially tried in Firefox, but Chrome also works just fine...

Does it ever resolve itself, after a refresh or anything -- It is very odd how renaming would have anything to do with the files bundling.

**Comment by yangg** [comment]
Yes. Refresh can solve the problem temporarily.

**Comment by sannek** [comment]
If refreshing solves the problem, and I cannot reproduce the error I don't think there's much I can do about it for now. Hopefully refreshing can at least unblock you, but I will make a ticket to see if someone can investigate this further, but it might take a while.

If you are really blocked, then please re-open this issue, because then I misunderstood.
