### ISSUE TITLE
After delete the file, the view is still displayed normally

### ISSUE THREAD

**Issue by xusang** [codesandbox/codesandbox-client#6859]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

In React component,If I delete a referenced file,After the view is automatically updated, everything is the same as before.

## How has this issue affected you? What are you trying to accomplish?

When i use @codesandbox/sandpack-react,I find this problem,it makes my code not work.I hope that when trying to update, it should throw an error.

### To Reproduce
Open this example,delete the test.js,the view is still displayed normally.

### Link to sandbox: [link]() (optional)

[https://codesandbox.io/s/smoosh-wind-1g171w?file=/src/test.js](https://codesandbox.io/s/smoosh-wind-1g171w?file=/src/test.js)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |       web       |
| Browser          |        104.0.5112.10      |
| Operating System |       macOs   Monterey 12.4    |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by sannek** [comment]
Hi, I don't really understand the question. What do you mean by displayed 'normally'? 

Is the preview not updating correctly?
