### ISSUE TITLE
Codesandbox  potential phishing page issue

### ISSUE THREAD

**Issue by WebDevloperAditya** [codesandbox/codesandbox-client#6876]
# 🐛 bug report

## Preflight Checklist

- [ x] I have read the [Contributing Guidelines][contributing] for this project.
- [ x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Why My Sandbox is Marked As potential phishing page,this is not collecting Any Information It is Just React Project Using Api CURD Operation. please unmark my sandbox as  potential phishing page, this is link: https://r1npi1.csb.app/

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |       Chrome       |
| Operating System |   Windows  11      |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by Utwo** [comment]
Hey, I reviewed the link and removed the banner. Sorry for any inconvenience.
