### ISSUE TITLE
Create new client sandbox using npx

### ISSUE THREAD

**Issue by mwisnicki** [codesandbox/codesandbox-client#6947]
# 🌈 Feature

I would like to be able to create new client sandbox for web project using npx generators such as create-react-app

User provides npx command to generate **client** project.

Perhaps this can be done by starting with container sandbox then switching to client sandbox but I wasn't able to figure it out.

**Comment by mwisnicki** [comment]
Looks like conversion is not possible as per #2111.

**Comment by alexnm** [comment]
Hey @mwisnicki, thanks for the suggestion, we have this on our list actually. we were discussing something like this for our new cloud sandbox experience. There you can technically start with [a blank sandbox](https://codesandbox.io/p/sandbox/blank-k8dsq1) cleanup existing template files and run any `npx` generator, we just need to make it a more first-class feature, as for now you need to run everything in a terminal yourself.
