### ISSUE TITLE
Could not find module in path: 'unmount-animation-clone' relative to '/App.js'

### ISSUE THREAD

**Issue by vilic** [codesandbox/codesandbox-client#6996]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

It was working previously, and no change has been made before it raises that error.

### Link to sandbox:

https://codesandbox.io/s/ich71?file=/App.js

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by alexnm** [comment]
Appears to be working again, maybe there was a temporary glitch with npm? can you re-open this please if it happens again?
