### ISSUE TITLE
Inline Preview not working on Firefox Mac BigSur

### ISSUE THREAD

**Issue by gregg-cbs** [codesandbox/codesandbox-client#7011]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
In the preview window also known as the inline browser, it is always blank and never seems to run in firefox.
<img width="1351" alt="Screenshot 2022-10-10 at 8 02 10 pm" src="https://user-images.githubusercontent.com/57114335/194928792-c72ec9df-ddff-4d6a-8af8-b6d77afcb7ea.png">

## How has this issue affected you? What are you trying to accomplish?
I cant code in codesandbox and see what i am doing.

### To Reproduce
Open a codesandbox project in firefox, toggle the inline viewer.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |      browser      |
| Browser          |      Firefox developer edition 106.0b3 (64-bit)        |
| Operating System |       macOS BigSur       |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by tristandubbeld** [comment]
Hi @gregg-cbs, thanks for the report and filling in the details! I've checked if it works for me, and it does, with FF Developer Edition (106.0b9) on macOS Monterey. Sadly I can't check it on BigSur at the moment, but I've asked around. Do you by any chance have plugins or extensions installed in your browser?

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/7533849/195048232-7ec05fc4-eb2f-4d01-a7dc-aebe613f52f5.png">

**Comment by gregg-cbs** [comment]
Thanks for checking this out! 
I checked this in incognito and had the same results, let me try disabled all browser plugins and get back to you.

The error in the console was something to do with 'storage not available'. I will post that as well when I am at my laptop again!

**Comment by alexnm** [comment]
Hey @gregg-cbs can you please  confirm if this is still an issue?
