### ISSUE TITLE
The console is printing wrong code

### ISSUE THREAD

**Issue by rakibulmd** [codesandbox/codesandbox-client#7021]
# 🐛 bug report

## Preflight Checklist

- [x ] I have read the [Contributing Guidelines][contributing] for this project.
- [ x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
console.log method printing wrong code without maintaining the sequence.

## How has this issue affected you? What are you trying to accomplish?

The sequence of printing console.log is not how JavaScript executes the code.

### Your Environment

| Software         | Name/Version |
| MS EDGE | Version 106.0.1370.42 (Official build) (64-bit) |
| Сodesandbox      |              |
| Browser          |        MS Edge      |
| Operating System |     windows 10         |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @rakibulmd ,

Due to the third party library that the CodeSandbox console uses, we send console entries eagerly. 

This can sometimes result in differences with local editors, where they send them lazily.
