### ISSUE TITLE
Unable to access project files or close instance / JSON parsing errors

### ISSUE THREAD

**Issue by pjborowiecki** [codesandbox/codesandbox-client#7029]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I have been testing Codesanbox Projects for the past three weeks, developing a MERN app and everything was fine. I closed my browser window and the SSH connection in my VSCode yesterday with no issues. Today, I am not able to reopen the project or access files. Loading takes a long time and in the end, I see one of three messages interchangeably: 

1) JSON.parse: unexpected character at line 2 column 1 of the JSON data
2) The string did not match the expected pattern.
3) Unexpected token '<', " <html><hea"... is not valid JSON

If this is something I did by accident when closing my work yesterday (e.g. pressed some buttons and altered code unknowingly), it would be great to be able to access the files at least and inspect them. As it stands, I am not able to respond to error messages above.

Trying to restart an instance with a button available on the error page results in the "closing instance..." message displaying forever without any outcomes.

## How has this issue affected you? What are you trying to accomplish?
I am trying to access project files and inspect them, copy them on my local machine or push them to GitHub. My work has halted because I am unable to access the code and I cannot do anything about it.

### Your Environment

| Software         | Name/Version                  |
| ---------------- | ----------------------------- |
| Сodesandbox      | 2b1d731                       |
| Browser          | Google Chrome 106.0.5249.118  |
| Operating System | MacOS Monterey 12.4           |

Version: 2b1d731
Environment: production
Event: PITCHER:ERROR
State: CONNECTING
Branch: ohogkz

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by pjborowiecki** [comment]
All working fine now. Thank you for resolving this quickly!

**Comment by alexnm** [comment]
Most likely a bug on the infrastructure layer, which the client didn't know how to process, a 500 error from there will show that JSON parsing error because the client expects all APIs to return json results.
