### ISSUE TITLE
Bug: 'Remove from CodeSandbox' is trying to delete branch

### ISSUE THREAD

**Issue by gregg-cbs** [codesandbox/codesandbox-client#7030]
# 🐛 bug report

## Description of the problem
When importing project using the github importer, I am then unable to remove the project from codesandbox and get a concerning error saying my git branch is trying to be deleted.

### To Reproduce
**Import project using github importer:**
![image](https://user-images.githubusercontent.com/57114335/196220338-05e2be16-5c99-453a-99a3-041eba677c28.png)

**After project loads and runs, go back to dashboard and try remove project from codesandbox, note the error that states the branch is trying to get deleted:**
![image](https://user-images.githubusercontent.com/57114335/196220855-2c7dc9cb-37c1-4939-8f16-ed64dff50049.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |      browser        |
| Browser          |     firefox         |
| Operating System |        windows      |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by olarclara** [comment]
Hello @gregg-cbs, thank you for the report. We published a fix to improve the experience when removing branches and repositories from CodeSandbox.

Now, branch cards have two options:

- Remove branch from CodeSandbox
  - Unavailable if the branch is the repository's default branch 
- Remove repository from CodeSandbox
  - Unavailable if the branch is a contribution branch 

![Screen Shot 2022-10-26 at 12 56 08](https://user-images.githubusercontent.com/24959348/198075514-2a696542-f092-43fb-b07c-2479151d9f9e.png)

We also renamed the remove option on repository cards, it's now 

![Screen Shot 2022-10-26 at 12 57 46](https://user-images.githubusercontent.com/24959348/198075886-d2bf1b25-5183-4a44-9cbf-c41fce41faf1.png)

**Comment by gregg-cbs** [comment]
Yeah thats nice thanks. Safer wording.

Appreciate the update! I will test it soon.

Cheers,
G
