### ISSUE TITLE
Adding Reagent / ClojureScript project support

### ISSUE THREAD

**Issue by 4mitch** [codesandbox/codesandbox-client#704]
Thank you for such great project!
I am wondering if you has plans for adding **Reagent ClojureScript** support? 
Since Reagent is based on React but in the same time is using very different base language ClojureScript which compiled to JavaScript, it will be very interesting to have ability to use you magnificent project to compare projects on both them.

I just thought that since there are such interactive snippets tool as [Klipse](http://blog.klipse.tech/reagent/2016/12/31/reagent-in-klipse.html) which works totally in browser, then this case will be suitable for Codesandbox project, isn't it?

**Comment by CompuIves** [comment]
Yeah this sounds like a great template to have! I'd be open for a PR adding this template. I will write documentation on how to write a custom template soon.

**Comment by 4mitch** [comment]
Great! Looking forward for such doc

**Comment by DjebbZ** [comment]
Any advance on the documentation? I'd love to give it a shot with time permitting.

**Comment by CompuIves** [comment]
Yes! I have some documentation here: https://github.com/CompuIves/codesandbox-client/blob/master/contributor-docs/adding-template.md.

**Comment by DjebbZ** [comment]
Thanks for the pointer. I prefer to say that I won't be working on it at all, so if someone wants to do it, fell free!

**Comment by SaraVieira** [comment]
Can someone here point me to Github Starter project for Reagent / ClojureScript?

**Comment by slifin** [comment]
@SaraVieira https://github.com/reagent-project/reagent#usage
