### ISSUE TITLE
Cannot set property {propertyName} of #<Object> which has only a getter

### ISSUE THREAD

**Issue by NicholasBoll** [codesandbox/codesandbox-client#7076]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

 The error is:

```
TypeError
Cannot set property colors of #<Object> which has only a getter
```

It seems to be a problem with how Codesandbox is bundling. Looking at the stack trace, it is erroring on this JavaScript code:
```js
exports.colors = 
```

`exports` is from a function wrapper and provided by the bundler. The same line successfully executed `export.borderRadius = `. I don't know if this means `colors` is a protected property or if `exports` is a protected object.

The original source code looks like:
```ts
export {
  borderRadius,
  colors,
  // ...
```

For convenience, the full file that is part of the error:
```js
(function $csb$eval(require, module, exports, process, global, __dirname, __filename, $csbImport) {"use strict";Object.defineProperty(exports, "__esModule", {value: true}); function _createStarExport(obj) { Object.keys(obj) .filter((key) => key !== "default" && key !== "__esModule") .forEach((key) => { if (exports.hasOwnProperty(key)) { return; } Object.defineProperty(exports, key, {enumerable: true, configurable: true, get: () => obj[key]}); }); }var _canvascolorsweb = require('@workday/canvas-colors-web'); _createStarExport(_canvascolorsweb);
var _radius = require('./lib/radius');
var _colorstypes = require('./lib/colors.types');
var _depth = require('./lib/depth');
var _space = require('./lib/space');
var _type = require('./lib/type');
var canvas = {
    buttonColors: _canvascolorsweb.buttonColors,
    chartingColorOffsets: _canvascolorsweb.chartingColorOffsets,
    chartingColors: _canvascolorsweb.chartingColors,
    colors: _canvascolorsweb.colors,
    commonColors: _canvascolorsweb.commonColors,
    depth: _depth.depth,
    fontFamily: _type.fontFamily,
    gradients: _canvascolorsweb.gradients,
    iconColors: _canvascolorsweb.iconColors,
    inputColors: _canvascolorsweb.inputColors,
    monoFontFamily: _type.monoFontFamily,
    space: _space.space,
    statusColors: _canvascolorsweb.statusColors,
    type: _type.type,
    typeColors: _canvascolorsweb.typeColors,
};

exports.borderRadius = _radius.borderRadius; exports.colors = _canvascolorsweb.colors; exports.gradients = _canvascolorsweb.gradients; exports.depth = _depth.depth; exports.space = _space.space; exports.spaceNumbers = _space.spaceNumbers; exports.type = _type.type; exports.fontFamily = _type.fontFamily; exports.monoFontFamily = _type.monoFontFamily; exports.BrandingColor = _colorstypes.BrandingColor;
exports. default = canvas;

//# sourceURL=https://3y5qh.csb.app/node_modules/@workday/canvas-kit-react/dist/es6/tokens/index.js
})
```

Full source code: https://github.com/Workday/canvas-kit/blob/feeef81b1ceba7ef4f0ff7b286772cfbadd265ef/modules/react/tokens/index.ts

The source code is transpiled into commonjs and es6 code and is not pre-bundled. For es6, the `export` and `import` keywords are left intact.

## How has this issue affected you? What are you trying to accomplish?

None of the codesandboxes I've created for our users work anymore.

### To Reproduce

Load up the linked sandbox. The error will happen after tranpilation.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  |
| Browser          | Microsoft Edge/v106.0.1370.52 |
| Operating System | Windows 11 |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by markerikson** [comment]
We appear to be seeing the same problem with Redux Toolkit's "RTK Query" examples as well:

https://redux-toolkit.js.org/rtk-query/usage/examples#kitchen-sink

https://codesandbox.io/s/github/reduxjs/redux-toolkit/tree/master/examples/query/react/kitchen-sink?from-embed

**Comment by markerikson** [comment]
Looks like this should be fixed now:

- https://twitter.com/CompuIves/status/1586752900239441921

**Comment by alanbsmith** [comment]
Thanks for the update, @markerikson! 🥳

**Comment by NicholasBoll** [comment]
I've verified the problem is fixed. Thank you!
