### ISSUE TITLE
On hover, package version is not the correct one

### ISSUE THREAD

**Issue by alexfauquette** [codesandbox/codesandbox-client#7101]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I was looking at this [codesandbox](https://codesandbox.io/s/year-view-business-days-sk5h3z?file=/demo.tsx) from https://github.com/mui/mui-x/issues/6653

As you can see this codesandbox uses the latest stable version of the `@mui/x-date-picker` (v5)

![image](https://user-images.githubusercontent.com/45398769/199518360-83524ee8-8b74-4bf1-b589-bc0294c3f84f.png)

But when the mouse is over the package, the select shows the latest version (v6 alpha)
![image](https://user-images.githubusercontent.com/45398769/199516764-ae338435-5e89-4df6-b1a9-d4e0aedd8aa4.png)

It's a problem because when looking for which version is installed, I use my mouse to help me browse the list of package, but the version displayed is not the one installed

### Step to reproduce

1. Go to the [codesandbox](https://codesandbox.io/s/year-view-business-days-sk5h3z?file=/demo.tsx) 
2. Look for `@mui/x-date-pickers` package version and see it's v5
3. Move the mouse over the package, the display version is now a v6

### Link to sandbox: [link](https://codesandbox.io/s/year-view-business-days-sk5h3z?file=/demo.tsx
)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |Chrome v107.0.5304.87 |
| Operating System | Ubuntu 22 |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by alexnm** [comment]
This was fixed meanwhile, but I can't really find the PR anymore, please reopen if it happens again
