### ISSUE TITLE
Security check preventing sandboxes from running - CORS errors aplenty and some 503s

### ISSUE THREAD

**Issue by philBrown** [codesandbox/codesandbox-client#7113]
# 🐛 bug report

Your new weird browser security check is blocking sandboxes from running.

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Attempting to load any sandbox results in a bunch of CORS related errors and nothing loading in the preview pane

These two are returning the security check page

> Access to script at 'https://codesandbox.io/static/js/whatever.js' from origin 'https://sandbox.preview.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

> Access to fetch at 'https://prod-packager-packages.codesandbox.io/v1/some/resource.json' from origin 'https://codesandbox.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

This one is returning a CloudFlare 503 error page

> Access to fetch at 'https://ata.codesandbox.io/api/v8/some-package.json' from origin 'https://codesandbox.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin'

## How has this issue affected you? What are you trying to accomplish?

Sandboxes are not running

### To Reproduce

Simply open a sandbox or try to create a new one. Incognito window will force the security checks to run.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |  Chrome 107.0.5304.87            |
| Operating System |              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by hillmychen** [comment]
me too

**Comment by ellenchialin** [comment]
same here

**Comment by rjschaffer** [comment]
Me, too.

**Comment by tientaidev** [comment]
Me too

**Comment by philBrown** [comment]
Please stop polluting this issue with useless comments. Just [add a reaction](https://github.com/dear-github/dear-github/issues/141) or subscribe if you want updates.

**Comment by wenshuangz** [comment]
me too

**Comment by Newadventure2022** [comment]
I have been blocked by codesandbox and I need it to submit my homework to SheCodes. 

How can I fix this issue? 

I transferred my code from my VS Code to the sandbox and now it will not accept my API key for my weather app. It said something about “Access to script at https://codesandbox.io/s/javascript-geolocation-api-forked-9t5si7 from origin https://87nms8.csb.app/ has been blocked by CORS policy: No ‘Access-Control-Allow-Origin’ header is present on 87nms8.csb.app/:1  and it has a bunch of other messages and it says something about phishing. 

UGH!! Please help!!

https://codesandbox.io/s/javascript-geolocation-api-forked-mps7b5?file=/src/index.js

**Comment by tristandubbeld** [comment]
Hello, thanks for reporting this! Sorry for the inconvenience. t should work again, can you confirm this?

**Comment by philBrown** [comment]
Yep, seems to be fixed now @tristandubbeld. Cheers

**Comment by Newadventure2022** [comment]
Thank You!!!!!!
