### ISSUE TITLE
HELP!!!

### ISSUE THREAD

**Issue by Newadventure2022** [codesandbox/codesandbox-client#7115]
I have been blocked by codesandbox and I need it to submit my homework to SheCodes.

How can I fix this issue?

I transferred my code from my VS Code to the sandbox and now it will not accept my API key for my weather app. It said something about “Access to script at https://codesandbox.io/s/javascript-geolocation-api-forked-9t5si7 from origin https://87nms8.csb.app/ has been blocked by CORS policy: No ‘Access-Control-Allow-Origin’ header is present on 87nms8.csb.app/:1 and it has a bunch of other messages and it says something about phishing.

UGH!! Please help!!

https://codesandbox.io/s/javascript-geolocation-api-forked-mps7b5?file=/src/index.js

# 🐛 bug report

## Preflight Checklist

- [X] I have read the [Contributing Guidelines][contributing] for this project.
- [X] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |              |
| Operating System |              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by tristandubbeld** [comment]
Hey! Sorry for the inconvenience and thanks for reporting this. You should be able to call the API again!

**Comment by Newadventure2022** [comment]
Thank you so much for fixing the issue. 

Regards,
Celia

**Comment by tristandubbeld** [comment]
Thanks again for reporting this, and good luck with the assignment!
