### ISSUE TITLE
TypeError Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by xiejay97** [codesandbox/codesandbox-client#7118]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

https://codesandbox.io/s/getting-started-dvzlf0
![image](https://user-images.githubusercontent.com/64340763/200482440-4a69ba8d-c908-4015-bf3e-b4b814fdde2e.png)

I tested locally and it's ok.
node 16.18.0, yarn 1.22.19, Ubuntu 20.04.4 LTS
![image](https://user-images.githubusercontent.com/64340763/200483049-57c2701c-262f-4aee-a811-ae3bc4a29fc9.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |    Chrome 107.0.5304.88          |
| Operating System |     Win11 22621.674         |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by FractalHQ** [comment]
I've been running into this a lot today:

https://codesandbox.io/s/clever-mountain-xmp468

Any related commits or explanations of why this problem occurs and how to fix it would be much appreciated!
