### ISSUE TITLE
Big Digital Team/Paid Upgrade Crash

### ISSUE THREAD

**Issue by bigdigitalteam** [codesandbox/codesandbox-client#7119]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > We were upgrading to Pro and made it through to payment but it appears to not have gone through and now we can't access our account at all.

  <h3>Link to sandbox:</h3> [Dashboard](https://codesandbox.io/dashboard/recent?workspace=862f9d2e-fda8-40a9-a962-cd74640dca6f)

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | safari | 15.5.0 | OS X 10.15.7           | 819f1651d          |

  **Route:**
  https://codesandbox.io/dashboard/recent

  **Error Code:**
8037f508b0e74a988d18accfad3387bc

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: e.getFullYear is not a function. (In 'e.getFullYear()', 'e.getFullYear' is undefined)
  @https://codesandbox.io/static/js/app.6ff849ba3.js?_sw-precache=a816a836c8c313bb18116e1c05817df5:9:775740
Gm@https://codesandbox.io/static/js/app.6ff849ba3.js?_sw-precache=a816a836c8c313bb18116e1c05817df5:9:775798
ua@https://codesandbox.io/static/js/common.1774518e7.chunk.js?_sw-precache=5b9237f23bab0e534f448405f576636f:1:1788855
Ka@https://codesandbox.io/static/js/common.1774518e7.chunk.js?_sw-precache=5b9237f23bab0e534f448405f576636f:1:1797121
ml@https://codesandbox.io/static/js/common.1774518e7.chunk.js?_sw-precache=5b9237f23bab0e534f448405f576636f:1:1819695
hl@https://codesandbox.io/static/js/common.1774518e7.chunk.js?_sw-precache=5b9237f23bab0e534f448405f576636f:1:1819620
il@https://codesandbox.io/static/js/common.1774518e7.chunk.js?_sw-precache=5b9237f23bab0e534f448405f576636f:1:1816948
il@[native code]
@https://codesandbox.io/static/js/common.1774518e7.chunk.js?_sw-precache=5b9237f23bab0e534f448405f576636f:1:1775130
@https://codesandbox.io/static/js/common.1774518e7.chunk.js?_sw-precache=5b9237f23bab0e534f448405f576636f:1:1850466
Xo@https://codesandbox.io/static/js/common.1774518e7.chunk.js?_sw-precache=5b9237f23bab0e534f448405f576636f:1:1775076
Yo@https://codesandbox.io/static/js/common.1774518e7.chunk.js?_sw-precache=5b9237f23bab0e534f448405f576636f:1:1775011
el@https://codesandbox.io/static/js/common.1774518e7.chunk.js?_sw-precache=5b9237f23bab0e534f448405f576636f:1:1813734
Sa@https://codesandbox.io/static/js/common.1774518e7.chunk.js?_sw-precache=5b9237f23bab0e534f448405f576636f:1:1792529
Sa@[native code]
@https://codesandbox.io/static/js/vendors~app.b7ac675ab.chunk.js?_sw-precache=8d16b6ab5b110b70ba6c1d2eaff1f86d:1:1007087
@https://codesandbox.io/static/js/vendors~app.b7ac675ab.chunk.js?_sw-precache=8d16b6ab5b110b70ba6c1d2eaff1f86d:1:1141936
flush@https://codesandbox.io/static/js/vendors~app.b7ac675ab.chunk.js?_sw-precache=8d16b6ab5b110b70ba6c1d2eaff1f86d:1:1144823
t@https://codesandbox.io/static/js/vendors~app.b7ac675ab.chunk.js?_sw-precache=8d16b6ab5b110b70ba6c1d2eaff1f86d:1:1014097
  
    in Gm
    in div
    in Dashboard___StyledElement2
    in t
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in De
    in Unknown
    in aw
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by necoline** [comment]
Thank you for reporting this @bigdigitalteam We are looking into this now

**Comment by bigdigitalteam** [comment]
@necoline great, thank you. Let me know if there is anything else I can do to help.

**Comment by necoline** [comment]
Thanks @bigdigitalteam 
We were able to find a bug from a recent release and push a fix. Can you let us know if you continue to run into any issues?

**Comment by bigdigitalteam** [comment]
@necoline to better specify, it works after logging in and I am on the Free Team, but when navigating to the Digital team we set up right after purchase is when we encounter the error. Which unfortunately also houses all of the code we just migrated over...

**Comment by alexnm** [comment]
Had a little miscommunication, the problem is fixed but the deploy pipeline is still running. Should be done in 10-15 minutes max

**Comment by bigdigitalteam** [comment]
@alexnm perfect. Thank you!

**Comment by bigdigitalteam** [comment]
@alexnm that's great, I will reply once it's working on my end.

**Comment by alexnm** [comment]
@bigdigitalteam you can refresh now, should work

**Comment by bigdigitalteam** [comment]
@alexnm bingo, working now. Thank you so much.
