### ISSUE TITLE
Out of date React typings

### ISSUE THREAD

**Issue by vezaynk** [codesandbox/codesandbox-client#7140]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

ReactDOM/client is missing types. This only happens in codesandbox. Adding @types/react-dom did not help.

![image](https://user-images.githubusercontent.com/10255546/201542654-c2fd752f-02e1-4059-9849-31bdc1baa4ac.png)

## How has this issue affected you? What are you trying to accomplish?

Using React with TypeScript

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/react-typescript-forked-yqun99

**Comment by OnkelTem** [comment]
I confirm. I wonder why it was not fixed yet. It's a critical bug which ruins all existing sandboxes and prevents the creation of new ones.  So now codesandbox is a brick.

**Comment by tristandubbeld** [comment]
Hey @vezaynk sorry for the late reply and thanks for raising this! And thank you @OnkelTem for mentioning this again. I looked into the template and the types (`@types/react` and `@types/react-dom`) weren't updated in the `devDependencies`. This is also why installing them as dependencies didn't work.

I've updated the template with the new types and you should be able to see the changes. I've successfully created [a sandbox from the updated template](https://codesandbox.io/s/objective-bell-jzbfqb?file=/src/index.tsx). Could you confirm that using the template works for you now too? Thanks!

**Comment by vezaynk** [comment]
@tristandubbeld Yes it works.

**Comment by tristandubbeld** [comment]
Thanks for getting back to us @vezaynk! Glad it's been resolved :)
