### ISSUE TITLE
path resolving issue

### ISSUE THREAD

**Issue by h5gq3** [codesandbox/codesandbox-client#7219]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

see this: https://github.com/puppeteer/puppeteer/issues/9380

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by alexnm** [comment]
Hey @h5gq3! from what I see there in the puppeteer report, you were trying this on a cloud sandbox, can you give us the link to that sandbox? looks like a problem on the VM.

**Comment by h5gq3** [comment]
hey, this one: https://codesandbox.io/p/sandbox/goofy-gianmarco-mw46ij?file=%2FREADME.md

**Comment by alexnm** [comment]
Thanks, will follow-up after I hear back from the infra team

**Comment by alexnm** [comment]
The suggestion is to use the new docker sandbox for things like puppeteer, as it gives you better support for running things in the VM. here's an example a colleague put together: https://codesandbox.io/p/sandbox/charming-feather-fpuf9t
