### ISSUE TITLE
Auto Import component is not working  properly 

### ISSUE THREAD

**Issue by Vishal101022** [codesandbox/codesandbox-client#7225]
# 🐛 bug report
## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

### Whenever I tried to import component, it autocomplete in the next line and leave the incomplete text as it is. as shown [line no.- 4]

![image](https://user-images.githubusercontent.com/13450751/206919732-f8790d72-5523-40fe-923d-839abe84b11d.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | quirky-ellis-3xmi8d |
| Browser          |  Chrome Version 108.0.5359.99 |
| Operating System | Window 10 |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by alexnm** [comment]
Hey @Vishal101022, is this still reproducing for you? the sandbox link you shared is not accessible, so if you have the same behavior on a public sandbox you can share, we could take a look
