### ISSUE TITLE
Unknown token in yarn.lock when opening GitHub subtree

### ISSUE THREAD

**Issue by cyco130** [codesandbox/codesandbox-client#7226]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

When I try to open a GitHub subtree sandbox that worked previously, I get a 502 error with the following message on the console:

`An unexpected error occurred: Unknown token: { line: 1, col: 0, type: 'INVALID', value: undefined } 1:0 in /sandbox/yarn.lock`

which is weird because I don't _have_ a `yarn.lock` file at all. The problem goes away if I fork it.

## How has this issue affected you? What are you trying to accomplish?

I'm trying to provide usage examples for [Rakkas](rakkasjs.org), a React metaframework powered by Vite. The examples on the website don't work anymore because of this issue.

### To Reproduce

Open the following sandbox. Notice the bug goes away if you fork it.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest |
| Browser          | Tried with the latest Chrome and Firefox |
| Operating System |  Linux Mint            |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by sannek** [comment]
Hi -- I did a hard reset of the sandbox on our end, and as far as I can tell it now no longer has any issues starting. Apologies for the inconvenience, and please let us know if there's anything else.

**Comment by cyco130** [comment]
Thank you @sannek. But I'm still getting the same error unfortunately :(
