### ISSUE TITLE
Dashboard page: search is scoped to my workspace

### ISSUE THREAD

**Issue by gregg-cbs** [codesandbox/codesandbox-client#7227]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
When using the search in my dashboard it seems to only ever search my workspace... i cant search for other sandboxes, friends or colleagues.

I expected the Discover page to be able to search for sandboxes across codesandbox but when i type in the search input it takes me to my workspace.

https://user-images.githubusercontent.com/57114335/207066941-df396cf5-3c57-4422-891d-87c0c50b55c6.mp4

### To Reproduce
1. Go to Discover page
2. Type in the search
3. Notice the result

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @gregg-cbs - This is intended behavior. The discover page is just what you see in the main page window. The search bar is a part of the dashboard UI and so only searches your sandboxes.
