### ISSUE TITLE
Add require.context for Vue automatic global component registration

### ISSUE THREAD

**Issue by JollyBrackets** [codesandbox/codesandbox-client#723]
**What I'm trying to do:**
I would like to use the automatic global component registration from Vue as outlined in this [guide](https://vuejs.org/v2/guide/components-registration.html#Automatic-Global-Registration-of-Base-Components).
This approach however relies on webpacks _require.context_ method, which is outlined [here](https://github.com/webpack/docs/wiki/context#requirecontext).

**Problem**
__require.context__ does not seem to be support by codesandbox (❤) yet, which is why it throws the following error:

![image](https://user-images.githubusercontent.com/3167756/38648149-133aad10-3df0-11e8-81eb-c440552fd4e9.png)

**My request**
Could you please add support for _require.context_, since this would enable global auto registration which allows us to omit tedious component imports everywhere and make it even easier for beginners to get started with Vue (imo).

**Codesandbox**
[https://codesandbox.io/s/github/MPH-Bali/green-village-project/tree/develop/public](https://codesandbox.io/s/github/MPH-Bali/green-village-project/tree/develop/public)

Software | Name/Version
-- | --
Сodesandbox | PROD-1523452809
Browser | Chrome/65.0.3325.181
Operating System | Windows/10.0.16299

**Comment by CompuIves** [comment]
Very good request, makes a lot of sense to add this. I'm actually surprised that we didn't see this request before 😄.

If I understand the behaviour of `require.context` well enough it should work like this:

```js
const req = require.context('./components', true, /.*\.vue$/)

// Now we have a 'context' that behaves the same as require but with context, soo

req.resolve('App.vue') // Will resolve components/App.vue
req.keys() // Will return all keys indexed by the context
req('App.vue') // Will `require` components/App.vue and return the module
```

**Comment by Napzu** [comment]
I made simple as possible example that [works fine in container sandbox](https://codesandbox.io/s/codesandbox-nuxt-hhh4s) but obviously not in client template.
```javascript
import Vue from "vue";

const requireComponent = require.context("../components", false, /\.vue$/);
requireComponent.keys().forEach(filename => {
  const component = requireComponent(filename)
  /* Get componenent name from filename IE. "/components/component-name.vue" to "ComponentName" */
  const componentName = filename.split("/").pop().replace(/\.\w+$/, "").replace(/-([a-z])/g,g=>g[1].toUpperCase()).replace(/(\b\w)/gi,m=>m.toUpperCase());
  Vue.component(componentName, component.default || component); /* Global component registration */
});
```


Any news if and when we could get require.context working on client templates?

**Comment by hendrul** [comment]
How is it doing? what's been done? anything on this issue? it is a very important feature, I depend on this to import lots of images, and other files.

**Comment by strophy** [comment]
Is there a workaround until this is implemented? Would love to be able to show off some work I have done, but can't figure out how to work around this error...

**Comment by Napzu** [comment]
Any change getting this feature implemented? This would really help people who is just starting to code. Also this feature would lower mental overhead, because all components would be automatically available when needed.

**Comment by unitedworx** [comment]
we practically can not do any real work on codesandbox if this is not supported! 

We are building a prototype of an SPA using Vue and Vuetify and we are to the point that we need to use require.context in several places but we obviously can't!

any updates on this? or workarounds at least???

**Comment by jonaskuske** [comment]
...just letting the bot know it's not resolved yet

**Comment by jonaskuske** [comment]
> ...just letting the bot know it's not resolved yet
> (if it works like that and doesn't need a maintainer to comment)

.

**Comment by rowild** [comment]
Jumping in... have the same problem with vuex store and modules setup.

**Comment by hendrul** [comment]
No need for this, it is way better and compatible to use import-all.macro instead
