### ISSUE TITLE
Use Copilot with own subscription

### ISSUE THREAD

**Issue by AlessandroAnnini** [codesandbox/codesandbox-client#7233]
# 🌈 Feature

It would be nice, and super-useful if I could use [Github Copilot](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot) inside Codesandbox web editor

If the user is logged via Github then the extension _should_ work automatically because it knows who is subscribed.

**Comment by sannek** [comment]
It's not on the roadmap for the web editor for the near future, but since you can work in CodeSandbox projects in your own VSCode editor, you might be able to use Copilot in there. I don't use it so have not verified, but it is probably worth a try.

**Comment by alexnm** [comment]
were gathering all feature requests for the roadmap beyond February
