### ISSUE TITLE
Support for the experimental syntax 'classPrivateMethods' isn't currently enabled

### ISSUE THREAD

**Issue by yusefnapora** [codesandbox/codesandbox-client#7244]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

When trying to run a codesandbox for one of our [example projects](https://codesandbox.io/s/github/web3-storage/w3ui/tree/main/examples/react/sign-up-in), I get a syntax error saying:

```
Support for the experimental syntax 'classPrivateMethods' isn't currently enabled
```

We are using the ES2022 `#privateMethod` syntax, and the example is loading an ESM module which contains some private methods.

## How has this issue affected you? What are you trying to accomplish?

We're trying to publish sandboxes of all the example projects in https://github.com/web3-storage/w3ui

This recently stopped working when we started depending on modules that use the private class method syntax.

We're currently looking at ways to workaround this by tweaking our babel config, but if it's possible for codesandbox to support the syntax natively, that would be ideal.

### To Reproduce

Opening the sandbox below should show the syntax error on load.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          | Firefox & Chrome  |
| Operating System | Win11       |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by sannek** [comment]
I have added it to our log of feature requests, but I don't know on what kind of timeline we could support this.
