### ISSUE TITLE
full pane view?

### ISSUE THREAD

**Issue by johnaweiss** [codesandbox/codesandbox-client#7278]
# 🌈 Full pane view

Browser should be another tab, just like HTML, CSS, JS

Able to drag the browser tab to the same pane as the other tabs. 

See jsitor.com and playcode.io

**Comment by alexnm** [comment]
Thanks for the suggestion! We are experimenting with this type of interface for the new editor for repositories and cloud sandboxes. Not sure if/when it will be available, but it definitely is on our radar
