### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Kuzovlev-Sanya** [codesandbox/codesandbox-client#7295]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I try (using copy-paste) useDrag example from use-guesture documentation in codesandbox but get an error "Cannot convert undefined or null to object". I asked the use-gestures support in Discord to check the error and they confirmed its presence.

## How has this issue affected you? What are you trying to accomplish?

I want to learn Gestures.

### To Reproduce

[Link to code](https://codesandbox.io/s/two-spring-animation-g2byh1)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Browser          |       Chrome      |
| Operating System |     Mac OS x      |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by DeMoorJasper** [comment]
Hey, I can't seem to reproduce this issue, what do I need to do to reproduce this?
