### ISSUE TITLE
snapshots failing due to style prop differences

### ISSUE THREAD

**Issue by kentcdodds** [codesandbox/codesandbox-client#731]
Hi :wave:

So these snapshots pass locally and in CI, but not in codesandbox. https://codesandbox.io/s/249l243k5j

All the differences are in the style prop:

```
-       style="display: flex;"
+       style="display: flex; justify-content: space-around; align-items: center;"
```

I'm not sure why though... Seems like a bug.

**Comment by CompuIves** [comment]
Heh that's indeed very weird... Also interesting to see that so many styles are different. Seems like `justify-content: space-around; align-items: center;` is constantly added for flex items for some reason... Maybe because it's ran for a second time in the same context?

I'll do some debugging on this!

**Comment by kentcdodds** [comment]
In the meantime I removed the use of the `style` prop in those components to side-step the issue :)

**Comment by lbogdan** [comment]
@kentcdodds @CompuIves 
Seems like there's an issue with the snapshots? For example, for test no. 12, the snapshot is
```js
exports[`renders a toggle component 1`] = `
<div>
  <div>
    <div
      style="display: flex;"
    >
      <nav>
        <ul
          style="display: flex; list-style: none; padding-left: 0px;"
        >
          <li>
            <a
              href="index.html"
            >
              Home
            </a>
          </li>
[...]
```
but if I run it locally, go to `/12/final` and take a look at the html it's actually
```html
<div>
  <div>
    <div>
      <div style="display: flex; justify-content: space-around; align-items: center;">
        <nav style="flex: 1 1 0%;">
          <ul style="display: flex; justify-content: space-around; list-style: none; padding-left: 0px;">
            <li>
              <a href="index.html">Home</a>
            </li>
[...]
```
It looks like, locally, jest's snapshot renderer is stripping CSS attributes related to flexbox.
