### ISSUE TITLE
CI randomly stopped working for repo

### ISSUE THREAD

**Issue by caseybaggz** [codesandbox/codesandbox-client#7328]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
[Our team](https://github.com/pluralsight/pando) has been successfully using the Codesandbox CI to validate our PR's before shipping. Towards the end of last year, the CI randomly stopped working (stalling out on builds). At the start of 2023, the CI began to work again - however, after we have renamed our repo (and re-authenticated with the new repo name), the CI is back to not working...except this time, it's not even showing up in the CI job list. Last year, it was at least showing up.

## How has this issue affected you? What are you trying to accomplish?
This is a major set back for our team to ensure we are shipping clean API changes for all of our libraries. We greatly need this back up and running to guarantee we are shipping successful features/bug fixes from our libraries. 

### To Reproduce
[Check out the PR history of our repo for all the details.](https://github.com/pluralsight/pando/pulls). I even just recently killed the codesandbox config and added it back just in case there was some meta caching going on. Still no longer showing up in CI list.

### Link to sandbox: [link]() (optional)
n/a

### Your Environment
Github Actions CI

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by lbogdan** [comment]
Hey @caseybaggz ,

Thanks for your report.

Just to make sure we're looking at the right thing, can you please tell us the old and new repository name?

**Comment by lbogdan** [comment]
Looking at the CI database, I can only see the `pluralsight/tva` repository, which, judging by the GitHub redirect, is the old name of `pluralsight/pando`. We indeed don't currently handle repository renames, but removing and re-adding the CI GitHub app should have worked.

Would you be available for a call to troubleshoot in real-time why that's not working?

**Comment by caseybaggz** [comment]
> Looking at the CI database, I can only see the `pluralsight/tva` repository, which, judging by the GitHub redirect, is the old name for `pluralsight/pando`. Can you please confirm?
> 
> We don't handle repository renames currently, but removing and re-adding the CI GitHub app should have worked.
> 
> Would you be available for a call to troubleshoot in real-time why that's not working?

100%. Let me know how we can set this up and I'll make it happen on my side.

**Comment by lbogdan** [comment]
I'm available all day today. You can find my on [our Discord server](https://discord.gg/npt8ZhCu), I'm **BogdanL#8136**.

**Comment by lbogdan** [comment]
Hey @caseybaggz , I messaged you on Discord, I'm around all day, if you have time to troubleshoot this!

**Comment by lbogdan** [comment]
@caseybaggz If everything works fine, can you please close this?

**Comment by caseybaggz** [comment]
> @caseybaggz If everything works fine, can you please close this?

Absolutely. Issue is resolved on our end. 🎉
