### ISSUE TITLE
I set a project as a template and now it's missing

### ISSUE THREAD

**Issue by UnknownWitcher** [codesandbox/codesandbox-client#7343]
# 🐛 bug report

## Preflight Checklist

- [ x] I have read the [Contributing Guidelines][contributing] for this project.
- [ x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [ x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
I spent an entire day working on a project in codesandbox, then I clicked "Make sandbox a template" and it just disappeared.

## How has this issue affected you? What are you trying to accomplish?
I'm going to have to spend an entire day re-writing and testing the code.

### To Reproduce
1. Click the three dots top right of the project.
2. Click "Make sandbox a template".

### Link to sandbox: [link]() (optional)
It was one of these as I renamed it prior to making it a template.
[tdarr-helper-v2](https://codesandbox.io/s/tdarr-helper-v2-9k1slq)
[tdarr-helper](https://codesandbox.io/s/tdarr-helper-9k1slq)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Browser          |  Firefox 109 on Windows 10    |
| Operating System |  Windows 10   |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by tristandubbeld** [comment]
Hey @UnknownWitcher, thanks for the report! For me it's showing up as deleted, can you check if if it's on [the recently deleted page](https://codesandbox.io/dashboard/deleted) for you? If it isn't I'll ask the team if we're able to recover it. Please let us know!

**Comment by UnknownWitcher** [comment]
Hey @tristandubbeld it's not showing up on my end, that was the first thing I checked. I did create another template using a random project to see if it would happen again but the second time it created the template and showed the template section but I can't see the one that went missing.

![image](https://user-images.githubusercontent.com/82295355/213935516-f1f7fc18-3702-46bb-9a09-5a2609861cf1.png)

**Comment by tristandubbeld** [comment]
Thanks for checking, going to look into it! I'll try to give you an update tomorrow.

**Comment by tristandubbeld** [comment]
Hey @UnknownWitcher, the sandbox has just been un-deleted. I can access both of the sandbox links you provided. Can you confirm it shows up in your dashboard again?

**Comment by UnknownWitcher** [comment]
You're a life saver thank you so much @tristandubbeld
