### ISSUE TITLE
Feature request: comments-section

### ISSUE THREAD

**Issue by drcmda** [codesandbox/codesandbox-client#735]
Forgive me if this has been asked for a thousand times, i've tried to search issues.

But that would be a major addition, because people could ask questions in there, or give hints, generally just interact with one another. I'd also love to receive input, if people are satisfied with, say, a component, or have further suggestions that could be discussed right there.

**Comment by CompuIves** [comment]
Good to have an issue for this open! Yep, certainly good to have a discussion around this. I'm curious what others think.

I'm certain that I want to add this feature, the main question now is 'how' to add it in the best possible way. I want to work on this starting next week.
