### ISSUE TITLE
CodeSandbox doesn't work on chrome Version 109.0.5414.87 

### ISSUE THREAD

**Issue by Jasminou** [codesandbox/codesandbox-client#7352]
# 🐛 bug report

## Preflight Checklist

- [ x] I have read the [Contributing Guidelines][contributing] for this project.
- [x ] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [ x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
opening any sandbox on google chrome  Version 109.0.5414.87 show black browser window

## How has this issue affected you? What are you trying to accomplish?
can't use any of sandbox on chrome.

### To Reproduce

update google chrome to the latest version 109.0.5414.87  using a Mac device.
open any sandbox link avaialble on the google search.
here you go :)

note that I tired to empty my cache and cookies ( still the same thing)

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/qtb578?file=/demo.tsx

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |     chrome         |
| Operating System |          IOS    |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by alexnm** [comment]
Hi @Jasminou. I have the same version installed and the sandbox link you sent works well. Can. you try again? and if it persists, can you please give us some more details? like any errors you see in the console?

**Comment by Jasminou** [comment]
Hi @alexnm thank you for the quick reply. You can find attached a screenshot and log file of my chrome console when I open the link attached in the log description above.

<img width="1044" alt="Screen Shot 2023-01-25 at 15 51 22" src="https://user-images.githubusercontent.com/14798195/214687865-e49470ee-ecca-4860-b68b-dab278edfa32.png">

[codesandbox.io-1674679703638.log](https://github.com/codesandbox/codesandbox-client/files/10503589/codesandbox.io-1674679703638.log)

Let me know if you need anything else.
