### ISSUE TITLE
Dynamic imports in node_modules don't work

### ISSUE THREAD

**Issue by marcofugaro** [codesandbox/codesandbox-client#7357]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

<img width="477" alt="image" src="https://user-images.githubusercontent.com/7217420/214552808-fe868c0e-1520-4c67-be20-676ab6d174e9.png">

Specifically related to create-react-app.
If you have dynamic imports in a library that is used as a dependency, it breaks on Codesandbox.
**However it works correctly when you hit "Export to ZIP" and launch create-react-app locally**.

The code is this: 
```js
import('./opentype.js')
```

The file `opentype.js` is sitting in the node_modules in the same folder of the file it's being imported from.

## How has this issue affected you? What are you trying to accomplish?

> How has this issue affected you?

We at [Spline](https://spline.design/) use CodeSandbox as a default sandbox environment for code exports. A lot of users notified us about this error happening in the sandbox environment when text is present in the scene.

> What are you trying to accomplish?

Dynamically import js files. (in this case based on the presence of text in the scene). It works everywhere but codesandbox.

### To Reproduce

Visit https://codesandbox.io/s/904j73?file=/src/App.js

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |     any         |
| Browser          |         any     |
| Operating System |      any        |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by alexnm** [comment]
Hey @marcofugaro thanks for reporting this, I'm going to pass it to the team. For a quick fix, you can try the new cloud sandbox for [React + Vite](https://github.com/codesandbox/codesandbox-client/issues/7357). this would install dependencies and run the packages in the same was as a local setup.

**Comment by marcofugaro** [comment]
Thanks @alexnm!
Glad there is better support for Vite now! Last time we tried it was slow to boot up and would error often.

Any idea how can use the new React + Vite template?
We are doing a request to `https://codesandbox.io/api/v1/sandboxes/define` with the parameters generated from:

```js
import { getParameters } from 'codesandbox/lib/api/define'
```

**Comment by alexnm** [comment]
Ah, for the define endpoint, I just talked with our backend team and coincidentally they just deployed an update in prod for that endpoint. you can now pass `environment: server` and it will get you a cloud sandbox. so there's no template, you pass the files the same way as you've done before.

**Comment by marcofugaro** [comment]
Thank you @alexnm worked perfectly! We will go online soon with the new React + Vite template.

**Comment by alexnm** [comment]
Great to hear that! Let us know if you have any questions regarding the new editor

**Comment by marcofugaro** [comment]
Sure! We don't have any questions but we can provide some feedback.
I apologize in advance if this not the right channel for this, as this is more UX related.

When creating a brand new sandbox, the most important thing for me (the user) is to see my app live on the right half of the screen. I don't particularly care about the console or the success message (since seeing my app running would indicate success as well). So I (still the user) would prefer my live app to occupy all the column, not just one third as shown here:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/7217420/214902597-0da11432-c3db-4cd7-96e6-eccff645e9ac.png">

That's all the feedback, thanks for helping and congratulations on the new version! 🥳

**Comment by alexnm** [comment]
Thanks, this is definitely on our roadmap. The devtools sidebar was originally developed for working on bigger projects (as the entire editor) so we're in the process of optimizing it for sandboxes
