### ISSUE TITLE
Make column headers sortable in Profile page

### ISSUE THREAD

**Issue by donavon** [codesandbox/codesandbox-client#74]
Clicking on the title of a column in my profile page will sort the list of sandboxes by that column. Currently, they are sorted by creation date (?).

**Comment by CompuIves** [comment]
Yes, also a good one. Profile page could use a lot of love in this sense. This can also be possible with Algolia.

**Comment by donavon** [comment]
May the profile page is simply the search page filtered to just this person's sandboxes? You can then drop the old code and any enhancements that search gets, the profile page will get.

**Comment by CompuIves** [comment]
Yep, that sounds good. Just reuse the search page component on the profile page in a way. Then we need to have a separate page for the private/unlisted sandboxes though, since the unlisted/private sandboxes are not in algolia.

**Comment by ValentinH** [comment]
I was going to open a duplicate of this issue...

I'd like to implement this but I'd first need to know how you'd like it to be done. Currently it's not using Algolia but a internal endpoint (https://codesandbox.io/api/v1/users/ValentinH/sandboxes for instance). 
If we keep this, we first need to support sorting on the API (I think it's closed source, isn't it?).
