### ISSUE TITLE
Black Pages on Embed Apis

### ISSUE THREAD

**Issue by ofergoli** [codesandbox/codesandbox-client#7401]
You have an issue on the embed api:
All pages are dark black
you can see it here:
https://codesandbox.io/docs/learn/sandboxes/embedding

<img width="558" alt="image" src="https://user-images.githubusercontent.com/8341557/216971834-25ddb27b-a5ae-4a09-9c8f-3c0daf1d0ce0.png">

Can we get a status on that please?

**Comment by tristandubbeld** [comment]
Hey @ofergoli, thanks for the report! I believe this has been resolved. Please let us know if you still encounter issues with your embeds!
