### ISSUE TITLE
Could not find module in path: 'd3-zoom' 

### ISSUE THREAD

**Issue by michael-chiang-dev5** [codesandbox/codesandbox-client#7410]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Getting the error below when trying to import d3-zoom:
`Could not find module in path: 'd3-zoom' relative to '/node_modules/svelvet/Containers/GraphView/index.svelte'`

## How has this issue affected you? What are you trying to accomplish?
We use codesandbox to demo components to users. All demos are now broken.

### To Reproduce

import d3-zoom (see codeSandbox below)

### Link to sandbox: [link]() (optional)

This is the minimal CodeSandbox that shows the error:
https://codesandbox.io/s/d3-import-bug-2ck16c?file=/App.svelte:23-24

This is an example of a CodeSandbox which was previously working and now is not:
https://codesandbox.io/s/custom-nodes-forked-1ml2fb?from-embed=&file=/App.svelte

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |   444b28619a4a0390b903526b74c55df5bb2906d2           |
| Browser          |      Version 109.0.5414.119 (Official Build) (x86_64)        |
| Operating System |      macOS Ventura version 13.1        |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by igordanchenko** [comment]
I'm experiencing the same issue with [react-photo-album](https://www.npmjs.com/package/react-photo-album) package.

Sample sandbox: https://codesandbox.io/s/github/igordanchenko/react-photo-album/tree/main/examples/columns-layout

The above sandbox was working just fine this morning, but now all my sandboxes using [react-photo-album](https://www.npmjs.com/package/react-photo-album) are throwing this error:

```
ModuleNotFoundError
Could not find module in path: 'react-photo-album' relative to '/src/App.tsx'
```

**Comment by michael-chiang-dev5** [comment]
Codesandbox is now working again with d3-zoom imports. I have also checked @igordanchenko's sandbox and his seems to be working as well, so I am closing the ticket. Thank you for your help.
