### ISSUE TITLE
Cannot sign in with GitHub

### ISSUE THREAD

**Issue by jcusick93** [codesandbox/codesandbox-client#7423]
# 🐛 bug report

## Preflight Checklist

- ✅ I have read the [Contributing Guidelines][contributing] for this project.
- ✅  I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- ✅  I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Can't sign in to Codesanbox w/ GitHub

### To Reproduce

https://user-images.githubusercontent.com/37253884/218237007-7ca8cd80-ce32-44a5-9d1f-a67b6fcdd871.mp4

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |    https://codesandbox.io/u/jcusick93          |
| Browser          |          Chrome & Safari    |
| Operating System |         MacOS     |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by jcusick93** [comment]
I have also cleared my cache and browser history - still won't work.

**Comment by JamesACS** [comment]
Hey @jcusick93 - You've contacted us via email so we'll continue this conversation there.
