### ISSUE TITLE
[Bug] Error: 1006 - Something went wrong across all sandboxes

### ISSUE THREAD

**Issue by RealSourceOfficial** [codesandbox/codesandbox-client#7434]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Unable to open any project, through both WebUI, Chrome Application, or Firefox on iOS

## How has this issue affected you? What are you trying to accomplish?

Unable to work on any projects

### To Reproduce

Open Codesandbox
Open any repository

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |       2c03fc6|
| Browser          |        Chrome|
| Operating System |      ChromeOS|

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by lbogdan** [comment]
Hey @RealSourceOfficial ,

Thank you for your report!

Can you please try setting your OS DNS server to a public one, e.g. Cloudflare's `1.1.1.1` (see https://1.1.1.1/dns/), restart your browser(s) and try again?

**Comment by RealSourceOfficial** [comment]
Do note this also happened on my phone, but I will try that when I get home. It may just be an issue with my district network so I'll keep this open for now.

**Comment by RealSourceOfficial** [comment]
Do note this also happened on my phone, but I will try that when I get home. It may just be an issue with my district network so I'll keep this open for now.

**Comment by RealSourceOfficial** [comment]
Update: trying things at home, it works completely fine. I'll change my DNS for tomorrow but if it doesn't work I'll re-open this ticket. Thanks for the help!
