### ISSUE TITLE
Cannot fix merge conflict; Cannot delete a repo

### ISSUE THREAD

**Issue by milichev** [codesandbox/codesandbox-client#7444]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I somehow got a git conflict between the local and remote `main` branches, which are both 1 commit ahead. Despite the "Protected" red label, the files are editable, but I never commit to the `main` branch in csb explicitly.

**Now, I cannot reset the local branch.**

* When on the main branch, the code is screwed up with the conflict marks, and the environment got in the infinite reload loop. 

Then I tried to:

1. Open another branch via the address bar like https://codesandbox.io/p/github/owner/repo/anotherbranch
2. In the terminal:
    ```shell
    git checkout main
    git reset --hard <remote main sha>
    ```
3. Switch the environment to the main, both via the branch chooser and address bar.
4. The code is still broken as if I didn't do step 2.

**Tried deleting the local branch and fetching it again - same.**

**Tried deleting the repository from codesandbox dashboard to re-import it again - no effect:**

* the preview link is alive returning stale content,
* the repo is still there by the editor link,
* the code is there broken as if nothing was deleted.

**Tried to rename `main` to `master` and re-import the repo:**

* csb stubbornly opens `main` which is still broken 😡 

After all, how could I delete the repo completely?

## How has this issue affected you? What are you trying to accomplish?

Restore the repo in codesandbox after the merge conflict.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |   [online](https://codesandbox.io)           |
| Browser          |  Chrome Version 110.0.5481.100 (Official Build) (x86_64)            |
| Operating System |  macOS 13.2.1 (22D68)            |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JayaKrishnaNamburu** [comment]
@milichev 

- For changing a default branch on what CSB uses, you need to change default branch in github settings. The branch rename doesn't propagate to the CSB.
- The only scenario that i could thing of from your description about the merge conflict it. You might have pushed to the `main` branch outside of csb environment. Which might have caused a change for the branch inside the VM.
- And for the second part
 
```
In the terminal:
git checkout main
git reset --hard <remote main sha>
Switch the environment to the main, both via the branch chooser and address bar.
 ```

Each branch VM is isolated instance, So, resetting master in a new URL and changing the branch to `main` from the branch switcher will not rest the `main` in your default branch. I will note this, maybe we should highlight this explicitly, the behaviours inside the VM will not reflect changes in any another VM that is running.

I checked your sandbox, and at the moment it seems to not have any conflicts. So, if you are do have any issues with remote branches. 

You can try resetting to local with the terminal, for the `default` branch itself. And not a different VM, or you can use the 
`Reset branch with Remote` option on the top menu.
<img width="279" alt="Screenshot 2023-02-22 at 13 47 48" src="https://user-images.githubusercontent.com/11075561/220623967-09276012-6186-414d-9cb2-f15aedf236e0.png">

If you still have any issues around the default branch. Please let know, i can help in looking at the behaviour 👍 
And we are actually working on removing the `protected` limitation on the default branches too. So users can pull and push from any branches all the time.

**Comment by milichev** [comment]
@JayaKrishnaNamburu, thanks for your explanations! Yes, somehow the repo self-cured. I tried to re-login today, and the repo seems clean and working.

Now, I understand a bit about how VMs and branches correlate. F.x. when I `git checkout another-branch`, the source code and the project structure in the left pane change. Then the interesting begins:
* Preview pane closes
* Installing dependencies,
* The dev server restarts,
* The "Syncing" badge displays and everything starts from the beginning. So the only way to stop this loop is to Restart the branch

Keep up the great work!

**Comment by JayaKrishnaNamburu** [comment]
Nice, good to know the explanation helped. Please feel to reach out anytime 😄. The way the repositories or sandboxes works is, single VM instance per branch. So you can have your isolated, front end,  backend running, seed data in databases without hurting any other branches 👍
