### ISSUE TITLE
Package dependencies from GitHub URLs Not Refreshing

### ISSUE THREAD

**Issue by JoshRosenstein** [codesandbox/codesandbox-client#750]
Hello, I am running into an issue of dependencies not updating when using gitHub URLs. For Example in Package json:
{
  "name": "foo",
  "version": "0.0.0",
  "dependencies": {
    "express": "expressjs/express",
    "mocha": "mochajs/mocha#4727d357ea",
    "module": "user/repo"
  }
}

If i make a commit on the master branch, my sandbox does not load the newest commit. I've tried removing it and re-adding it in package.json. I've tried changing the version and re-importing, but haven't had any luck. I started doing it this way for modules that arent production ready and dont want to publish to NPM for everychange in order to load in my sandboxes.

**Comment by lbogdan** [comment]
Hey @JoshRosenstein , can you please give us a link to your github repo and the corresponding sandbox so that we can take a look at what's happening? Thanks!

**Comment by CompuIves** [comment]
Hmm yes, I think our cache is flawed in this case. I believe we cache by branch name but should cache by commit sha. So before we request the dependency we need to find the latest commit sha and add it to the branch (`master#e49ajf` for example). This will make our cache slower but fixes this issue.

A workaround for now is to add the hash manually to the branch name @JoshRosenstein, I can take a look at it next week.

**Comment by JoshRosenstein** [comment]
@CompuIves 
10-4, i can just make a temp branch for each update, i'd rather do that than publish each time. 
However, i am not having luck with the "package": "username/package#branch" syntax .

[![Edit codesandbox-client/issues/750](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/040zjo8rrp)

**Comment by lbogdan** [comment]
@JoshRosenstein Hm, should that sandbox error or something? Because it seems to work here.

**Comment by JoshRosenstein** [comment]
@lbogdan  Sorry missed your comment, yeah, i had a copy of the package.json, that wasnt working, I updated the real package.json now to show the issue. Resolving Dependencies Loops..

**Comment by nikrowell** [comment]
@JoshRosenstein were you able to find a workaround for this?

**Comment by JoshRosenstein** [comment]
@nikrowell - no it did not. unfortunately even doing it manually by adding the branch or hash at then end, as @CompuIves recommended, codesandbox does not resolve.
JoshRosenstein/cshashTest - works
JoshRosenstein/cshashTest#equals3 - fails
JoshRosenstein/cshashTest#7b93551326b881e4d46dab276bbeec16ad98b32c- fails
tried with full repo links and git URI- none work.

**Comment by 100ideas** [comment]
I had the same problem: 

```jsonc
// in package.json
  "dependencies": {                                       // what happens on codesandbox?
    "overmind-forms": "100ideas/overmind-forms#hack",     // fail - desired branch
    "overmind-forms": "100ideas/overmind-forms#70fdc88",  // fail - commit-ish of hack 
    "overmind-forms": "100ideas/overmind-forms",          // works - but is master branch
```


https://github.com/100ideas/overmind-forms-example#21-feb-2019-patch-notes-100ideas

**Comment by rayfoss** [comment]
How would one add a public Gitlab dependency? say... https://gitlab.com/FossPrime/koremu.git
