### ISSUE TITLE
Console logs not being redirected to console in sandbox

### ISSUE THREAD

**Issue by madou** [codesandbox/codesandbox-client#752]
![image](https://user-images.githubusercontent.com/6801309/39156681-a5c06356-479a-11e8-82d9-f664bb2a971c.png)

Thanks for the service! It's great.

**Comment by CompuIves** [comment]
Interesting, so in this case the console message you enter in the console is not sent to the sandboxes if I understand correctly?

**Comment by lbogdan** [comment]
Hey @madou ,

Can you please give us more details, like how to reproduce this, what's the expected behaviour, what's the actual behaviour etc.?

**Comment by SaraVieira** [comment]
closed due to lack of activity
