### ISSUE TITLE
Bug: `@motionone/solid` causing an error

### ISSUE THREAD

**Issue by danilowoz** [codesandbox/codesandbox-client#7575]
# 🐛 bug report

Solid.js templates using `@motionone/solid` is throwing an error when trying to load it. Currently, this template has been used on [motion.dev](https://motion.dev/solid/quick-start#exit-animations) documentation, which is failing due to the following error:

<img width="1297" alt="Screenshot 2023-04-17 at 14 28 38" src="https://user-images.githubusercontent.com/4838076/232563644-7edd5a22-4fc3-43f2-84df-a345af49dd35.png">

## Debugging

I can see that this error is coming from a `@motionone/solid`. However, I couldn't find the `_standard` function on the [original source code](https://github.com/motiondivision/motionone/blob/main/packages/solid/src/motion.tsx#L108), so I guess it's an issue on our evaluation function, which is not including that function.

<img width="456" alt="Screenshot 2023-04-17 at 14 25 07" src="https://user-images.githubusercontent.com/4838076/232562980-66d60a3e-1a2d-4233-bb63-d5911ea27a15.png">

<img width="507" alt="Screenshot 2023-04-17 at 14 26 30" src="https://user-images.githubusercontent.com/4838076/232563239-4d46c681-f8cf-42e0-bc52-7ef239f2ee91.png">

### Link to sandbox: [link]() (optional)

You can run it here: https://codesandbox.io/s/sandpack-project-forked-ovjfhc?file=/package.json:132-148

**Comment by DeMoorJasper** [comment]
Strange, also don't find any reference to _standard, seems like some babel stuff is failing to load at first look, but will dig deeper into it later today

**Comment by DeMoorJasper** [comment]
Seems related to a bug in solid-refresh on all versions below `0.5.0`, will try and update our solid-refresh version

**Comment by DeMoorJasper** [comment]
Seems like the latest version has another issue `_$$component is not defined` created a repro to be sent to the solid-refresh team I guess: https://github.com/DeMoorJasper/solid-refresh-bug

**Comment by danilowoz** [comment]
Hey, @davedbase. We encountered a bug on solid-refresh, which can be reproduced on the repo mentioned above. 
What's the best way to address this issue? 

Thanks

**Comment by danilowoz** [comment]
Maybe @DeMoorJasper can clarify our current bundler setup

**Comment by davedbase** [comment]
Hi folks, we're getting a lot of flack from the broader Solid ecosystem on this topic. It's really hampering the perspective of Solid as a maintained ecosystem. I'm really apologetic to ask once again but we could really use support to solve this.

Thank you.

**Comment by DeMoorJasper** [comment]
@davedbase there's a repro in this thread that reproduces it consistently even locally

> Seems like the latest version has another issue _$$component is not defined created a repro to be sent to the solid-refresh team I guess: https://github.com/DeMoorJasper/solid-refresh-bug
> 
> For now I'll work around it by filtering out refresh plugins for node modules
