### ISSUE TITLE
404 error when committing changes to an organization github repo

### ISSUE THREAD

**Issue by MiguelAraCo** [codesandbox/codesandbox-client#758]
## Steps to reproduce:

- Create a sandbox based on a Github organization's repository (public)
- Make some changes
- Fill commit form
- Hit "Commit"

## Expected behavior

Loading modal appears and after a couple of seconds confirms that the commit was successful (or not).

## Actual behavior

- Loading modal appears ("Creating commit...")
- Toast appears saying: "Request failed with status code 404"
- Modal doesn't disappear
- The commit was unsuccessful

### Debug information

- The sandbox was previously saved
- The github account I'm using in codesandbox.io is part of the organization and has write access to the linked repository (including its branch)

Network request:

- The `POST` request done by codesandbox.io receives the following response:

    ```
    Status: 422
    {"errors":{"detail":["Request failed with status code 404"]}}
    ```

**Comment by MiguelAraCo** [comment]
Maybe the difference is that the fork you are creating is tied to a sandbox linked to a personal repository. And in my case the sandbox is linked to an organization repository.

Here's the info of the request/response info:

Request:
```
:authority: codesandbox.io
:method: POST
:path: /api/v1/sandboxes/q3rrrp2rl4/git/commit
:scheme: https
accept: application/json
accept-encoding: gzip, deflate, br
accept-language: es-419,es;q=0.9,en;q=0.8
authorization: #########
content-length: 57
content-type: application/json; charset=UTF-8
cookie: #########
origin: https://codesandbox.io
referer: https://codesandbox.io/s/q3rrrp2rl4
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
```

Response:
```
HTTP/1.1 422
status: 422
date: Thu, 26 Apr 2018 15:13:24 GMT
content-type: application/json; charset=utf-8
content-length: 61
cache-control: max-age=0, private, must-revalidate
x-request-id: 8o2vhtdmh3khavnf47hd0dlec97qqq73
via: 1.1 google
alt-svc: clear
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 4119fe387bd376be-LAX
```

**Comment by MiguelAraCo** [comment]
I don't know if the merge you referred to has already been deployed, but I just tested it again (after making a hard refresh) and it's still not working.

Still, thanks for your hard work! 😀

**Comment by CompuIves** [comment]
This is super good information @MiguelAraCo, we indeed need to add an extra check whether the user is part of the given organization. I'll give a closer look at it this week.

**Comment by MiguelAraCo** [comment]
Any update on this? Or is it something that can be fixed on the open source part of the codesandbox codebase? If so, if you could point me to where, I may be able to contribute with a PR :).

**Comment by luisherranz** [comment]
I'm having the same problem :(

**Comment by vitkon** [comment]
same problem with a commit to organization

**Comment by vitkon** [comment]
@CompuIves , happy to help with this issue, but I assume it's a check on the server. Do you have it open-sourced?

**Comment by vitkon** [comment]
Any update on this one, guys?

**Comment by OlivierJM** [comment]
I am still having the same issue, it works for a personal account but not for an organization even when you are the owner of the organization.

**Comment by bitpod-io** [comment]
We are facing the similar issue. Our sandbox is https://codesandbox.io/s/charming-tu-qqwnk. Every commit fails with the status 422 and the response has JSON message 
```
{"errors":{"detail":["Not Found"]}}
```
This is frustrating.

**Comment by christianalfoni** [comment]
Hi there and sorry for not being as responsive as we want on this.

It turns out that all you need is to give access.

1. Go to your settings on Github and open applications
![Screenshot 2020-09-01 at 13 49 06](https://user-images.githubusercontent.com/3956929/91845825-229abf00-ec5a-11ea-906f-3640ca81082a.png)

2. Click the third tab "Authorized OAuth apps" and Codesandbox
![Screenshot 2020-09-01 at 13 49 15](https://user-images.githubusercontent.com/3956929/91845851-321a0800-ec5a-11ea-82dd-e725b103ce2a.png)

3. Grant organization access
![Screenshot 2020-09-01 at 13 49 23](https://user-images.githubusercontent.com/3956929/91845892-45c56e80-ec5a-11ea-963b-a8b48dc09ec3.png)

**Note!** it can take a few minutes for this to trigger.

**Comment by christianalfoni** [comment]
Btw, we are improving the experience here with: https://github.com/codesandbox/codesandbox-client/pull/4801 , also updating the docs with information on the issue above 😄
