### ISSUE TITLE
Rainbow terminal

### ISSUE THREAD

**Issue by MansiAyer** [codesandbox/codesandbox-client#7581]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
I can't see any text in the console, it's all rainbows. The console is unusable. Same issue is also occurring with the dev:logs tab. I don't really understand what's going on with the terminal or how to fix it, so I'm sorry if this is a very basic question.
## How has this issue affected you? What are you trying to accomplish?
Can't use terminal. I was trying to use the terminal for a nextjs project. 
### To Reproduce
In a nextjs template, click the dropdown for devtools, and select new terminal

Rainbow terminal
![rainbow terminal](https://user-images.githubusercontent.com/42694815/234867768-d937abe3-1457-4c1f-9efb-a8beb26bf1cd.png)

Rainbow logs
![rainbow logs](https://user-images.githubusercontent.com/42694815/234867504-bd4d8b2e-6ddb-4e5e-b55d-adf6703dd3b7.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |d7668af       |
| Browser          | firefox       |
| Operating System |win 10         |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by CompuIves** [comment]
That looks _beautiful_! But I can imagine that's frustrating... I also notice that the tab title in general is pixelated, what kind of resolution are you running on? Do you have graphics acceleration enabled?

**Comment by MansiAyer** [comment]
Resolution 1366x768 and graphics acceleration enabled, but I also figured out why I was seeing rainbows.
I'd changed a few config settings on my browser a while back, and somehow that was messing with the codesandbox terminal. 
It got fixed after I changed my settings back to default 😄
