### ISSUE TITLE
Ctrl + Tab to switch between two files

### ISSUE THREAD

**Issue by GingerBear** [codesandbox/codesandbox-client#761]
Thanks for creating such a great tool that makes programming much easier and accessible.

One of my pain point of writing code on codesandbox is that, switching between two files is not very easy using keyboard shortcuts (like Ctrl + Tab on most editor). I need to use mouse to select the other files, or use cmd + p and type the file name.

**Comment by CompuIves** [comment]
Good one! I like this addition.

**Comment by grady-lad** [comment]
@CompuIves I can take a look at this one if it is still available?

**Comment by CompuIves** [comment]
That'd be great @grady-lad! It's still available.

We store keybindings here: https://github.com/CompuIves/codesandbox-client/blob/master/packages/common/utils/keybindings.js. These keybindings fire signals. The signals that are important are defined here: https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/store/modules/editor/sequences.js#L29-L36. 

Let me know if you have any questions along the way 😄

**Comment by lbogdan** [comment]
Maybe not Ctrl-Tab, though, as that's usually the native "next tab" browser keyboard shortcut, and it might not be over-writable across browsers.

**Comment by steppefox** [comment]
@SaraVieira does your comment mean that this issue could be closed too?

https://github.com/codesandbox/codesandbox-client/pull/817#issuecomment-478547908

**Comment by SaraVieira** [comment]
Thank you @steppefox 

Yes, we changed to VSCode so all our keybindings now come from VSCode 🗡 
https://code.visualstudio.com/docs/getstarted/keybindings
