### ISSUE TITLE
Codesandbox ignores `template` config, tries to render CRA app in parcel environment when mirroring a GitHub repository

### ISSUE THREAD

**Issue by alessbell** [codesandbox/codesandbox-client#7649]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Using the `https://codesandbox.io/s/github/${org/user}/${repositoryName}` syntax for opening a GitHub repository in Codesandbox was working on Thursday. Today, I'm getting the error "Could not find entry file: /index.html. You can specify one in package.json by defining a `main` property.": https://codesandbox.io/s/github/alessbell/nonreactive

The project is trying to use parcel to bundle the app, but it's a CRA project. This was seemingly automatically detected previously, and now even when I add

```
{
  "template": "create-react-app"
}
```

to a `sandbox.config.json` and push several new commits, I see the same error.

## How has this issue affected you? What are you trying to accomplish?

Trying to mirror a GitHub repo in Codesandbox.

### To Reproduce

See above.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |       Arc, Chrome       |
| Operating System |       MacOS       |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by alessbell** [comment]
Seems like it could be a duplicate of https://github.com/codesandbox/codesandbox-client/issues/6388.

**Comment by CompuIves** [comment]
Hey! Thanks for reporting this, will take a look at why this is happening.

**Comment by CompuIves** [comment]
Ah, okay, this one should be fixed now! I noticed that in your sandbox you get the error: `Could not find dependency: '@faker-js/faker' relative to '/src/schema.js'`, that should be fixed if you move that dependency to `dependencies` in `package.json`.
