### ISSUE TITLE
Bug: Error in the command input field in codesandbox cloud

### ISSUE THREAD

**Issue by majid-2002** [codesandbox/codesandbox-client#7666]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
I found this issue in codesandox cloud in its command installing input area where the changes in the input area is not shown correctly on the command area.

## How has this issue affected you? What are you trying to accomplish?
I tried to installing a package by using this command input area like `yarn add zustand` but when i press enter the package in the terminal it only shown like this `yarn add zustan`
![image](https://github.com/codesandbox/codesandbox-client/assets/76196721/b1f795bd-8f11-4ead-bb08-8cabf9f236b8)

### To Reproduce
Should show the changes typed in sync without any problem

![Screenshot (105)](https://github.com/codesandbox/codesandbox-client/assets/76196721/6fd62a3c-13e6-4ab5-8bed-394c1de0ea35)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |      Online        |
| Browser          |        Chrome      |
| Operating System |       Windows       |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by alexnm** [comment]
Hey @majid-2002 thanks for reporting this! I tried reproducing it this morning but I see the command being formed in sync with the input. Was this happening while you were typing very fast perhaps? I think there's a slight delay, but should be in sync eventually. Is it reproducing consistently for you? where the last character is not in the string?
