### ISSUE TITLE
Support email not working

### ISSUE THREAD

**Issue by audreyclark** [codesandbox/codesandbox-client#7674]
I recognize this is not the right place to record the issue, but I have no better way to get in contact with the company.

support@codesandbox.io is failing to receive messages. I've tried twice and checked for typos.

<img width="625" alt="Screen Shot 2023-06-04 at 4 51 29 PM" src="https://github.com/codesandbox/codesandbox-client/assets/22730299/e8ef7ccf-2068-4af4-ae54-c0cc47a12188">

Support page on your site: https://codesandbox.io/support

**Comment by aj-foster** [comment]
Hi @audreyclark — sorry about this. We did receive your email at our other address, and will help you with your issue there.

Would you mind forwarding the delivery failure message to us at that other address? We continue to receive email at our `support@` address regularly, so we weren't aware of any issues. It may be an issue with your particular email provider, in which case we'd love as much information as possible to address it. Thanks!
