### ISSUE TITLE
History API issue in Cloud Sandbox

### ISSUE THREAD

**Issue by wijionejs** [codesandbox/codesandbox-client#7696]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Differences between browser behaviour in Browser Sandbox and Cloud Sandbox.
There is a [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) which underlies every SPA framework's router (React, Vue, Angular etc).
This API allows to change url in address bar without reload using pushState and replaceState methods.
It is expected that moving back and forward between items in the history (which are added with pushState or replaceState methods from History API) using browser navigation buttons must be performed without page reload as well.
In Browser sandbox navigation works as expected whereas in Cloud Sandbox we can observe a page reload when using browser back/forward navigation buttons.

## How has this issue affected you? What are you trying to accomplish?
I tried to set up an SPA (which is expected to work without any page reload) in a Cloud Sandbox and I had issues with navigation and application state (it was erased due to page reload).

### To Reproduce
Setup any SPA application with router (e.g. default templates for Vue or React apps) in a Cloud Sandbox, move to any page, then try to click back button in the navigation bar of sandbox browser.
**Actual result**: user is returned to previous page with page reload, application state is lost.

**Expected result**: user is returned to previous page without page reload, application state is preserved

### Link to sandbox:
[Browser Sandbox](https://codesandbox.io/s/upbeat-elion-nt94yd) - works as expected.
[Cloud Sandbox](https://codesandbox.io/p/sandbox/bold-grass-lww29v?welcome=true) - doesn't work as expected.
Both examples have identical source code.

Steps to reproduce:
1. Click on "go to item 999".
2. Use back and forward arrows in sandbox browser navigation bar.
3. Observe the navigation process.
3.1. Browser sandbox will navigate user back and forward without page reload.
3.2. Cloud sandbox will perform page reload while navigating.

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by CompuIves** [comment]
This is a good issue. In our browser sandboxes, we inject a shim for the history api (because browsers share the `history` API of an iframe with the main window). We should do this for cloud sandboxes as well.

**Comment by CompuIves** [comment]
We need to make this work in cloud sandboxes: https://codesandbox.io/p/github/codesandbox/codesandbox-client/master?file=/packages/sandbox-hooks/url-listeners.js:1,1

**Comment by wijionejs** [comment]
@CompuIves , great, I hope it will get fixed soon!

**Comment by CompuIves** [comment]
I have opened a PR with a fix!

**Comment by wijionejs** [comment]
@CompuIves, out of curiosity, could you share a link for the PR? Can't find it there. I'd like to take a look where the issue was.

**Comment by CompuIves** [comment]
Unfortunately we haven't open sourced this part of the editor yet. We're planning to open source it (soon) though, probably in a couple months. It's been mostly a logistical challenge with how we're going to put the editor in this repo 😅 .

**Comment by wijionejs** [comment]
I got it. Anyway, thanks for the quick fix! Good luck :)
