### ISSUE TITLE
[Presets] Add @vue/cli 3.0 preset when it'll be released

### ISSUE THREAD

**Issue by lbogdan** [codesandbox/codesandbox-client#776]
Just a reminder issue to add a `@vue/cli` 3.0 preset when it will be released (it's currently 3.0.0-beta.9).

**Comment by u3u** [comment]
`@vue/cli` 3.0 has been officially released, when will it be updated to CodeSandBox?

**Comment by CompuIves** [comment]
I'm hoping to get the time this weekend to implement it!

**Comment by lbogdan** [comment]
The news is that I just updated https://codesandbox.io/s/github/lbogdan/cs-vue-cli-3 to the latest versions, so until we release the `@vue/cli` server template (which will probably be **very** similar), you can just fork this.
