### ISSUE TITLE
CR-EC-cdc1cd5a37234bd8b4944f8548073f59

### ISSUE THREAD

**Issue by alejandrosuarez** [codesandbox/codesandbox-client#7912]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | safari | 16.6.0 | OS X 10.15.7           | 788653761          |

  **Route:**
  https://codesandbox.io/s/runtime-violet-ky7lv

  **Error Code:**
cdc1cd5a37234bd8b4944f8548073f59

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: undefined is not an object (evaluating '(n=a).indexOf')
  @https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:640447
ua@https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1791395
xs@https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1836478
ml@https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1822082
hl@https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1822007
il@https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1819355
il@[native code]
@https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1777796
@https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1852778
Xo@https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1777742
Yo@https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1777677
se@https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1846554
Sn@https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1761350
Sn@[native code]
  
    in Unknown
    in bound 
    in div
    in li
    in Unknown
    in Unknown
    in ol
    in Unknown
    in he
    in t
    in Ie
    in div
    in Styled(div)
    in t
    in WithTheme(t)
    in t
    in WithTheme(t)
    in div
    in Styled(div)
    in div
    in Styled(div)
    in v
    in t
    in div
    in Styled(div)
    in v
    in t
    in div
    in elements__Messages
    in div
    in elements__Container
    in n
    in WithTheme(n)
    in div
    in elements__ContentContainer
    in div
    in elements__Container
    in n
    in div
    in div
    in t
    in div
    in t
    in div
    in De
    in on
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in Ry
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Hey! Thanks for reporting this, it looks like this happened because of an upgrade we did to the console-feed package. I've now reverted that update, so it should not happen again. In the upcoming weeks we're going to replace our console solution with a version that's powered by Chrome Devtools, so that will be a big upgrade when it comes to our logging experience, and will result in a more stable experience.

Apologies for the inconvenience, I've now pinned the version of console-feed in the meantime to make sure this won't happen again.
