### ISSUE TITLE
continual crashes when I try to open the console

### ISSUE THREAD

**Issue by rdhagerty** [codesandbox/codesandbox-client#8022]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | safari | 16.5.0 | OS X 10.15.7           | 816c1afb3          |

  **Route:**
  https://codesandbox.io/s/spot-environment-j86jjy?file=/src/components/DataFetcher.js

  **Error Code:**
5a78909f4b8c41c787a0de8550ffdff6

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: undefined is not an object (evaluating '(n=a).indexOf')
  @https://codesandbox.io/static/js/common.709bc413f.chunk.js:1:714133
ua@https://codesandbox.io/static/js/common.709bc413f.chunk.js:1:1865081
xs@https://codesandbox.io/static/js/common.709bc413f.chunk.js:1:1910164
ml@https://codesandbox.io/static/js/common.709bc413f.chunk.js:1:1895768
hl@https://codesandbox.io/static/js/common.709bc413f.chunk.js:1:1895693
il@https://codesandbox.io/static/js/common.709bc413f.chunk.js:1:1893041
il@[native code]
@https://codesandbox.io/static/js/common.709bc413f.chunk.js:1:1851482
@https://codesandbox.io/static/js/common.709bc413f.chunk.js:1:1926464
$o@https://codesandbox.io/static/js/common.709bc413f.chunk.js:1:1851428
Yo@https://codesandbox.io/static/js/common.709bc413f.chunk.js:1:1851363
se@https://codesandbox.io/static/js/common.709bc413f.chunk.js:1:1920240
Sn@https://codesandbox.io/static/js/common.709bc413f.chunk.js:1:1835036
Sn@[native code]
r@https://codesandbox.io/static/js/common.709bc413f.chunk.js:1:275691
  
    in Unknown
    in bound 
    in div
    in li
    in Unknown
    in Unknown
    in ol
    in Unknown
    in he
    in t
    in Re
    in div
    in Styled(div)
    in t
    in WithTheme(t)
    in t
    in WithTheme(t)
    in div
    in Styled(div)
    in div
    in Styled(div)
    in v
    in t
    in div
    in Styled(div)
    in v
    in t
    in div
    in elements__Messages
    in div
    in elements__Container
    in n
    in WithTheme(n)
    in div
    in elements__ContentContainer
    in div
    in elements__Container
    in n
    in div
    in div
    in t
    in div
    in t
    in div
    in Ie
    in on
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in Ie
    in Ay
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in Ie
    in c
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Hey! Thanks for reporting this, it looks like this happened because of an upgrade we did to the console-feed package. I've now reverted that update, so it should not happen again. In the upcoming weeks we're going to replace our console solution with a version that's powered by Chrome Devtools, so that will be a big upgrade when it comes to our logging experience, and will result in a more stable experience.

Apologies for the inconvenience, I've now pinned the version of console-feed in the meantime to make sure this won't happen again.
