### ISSUE TITLE
Cannot import "mobx"

### ISSUE THREAD

**Issue by OnkelTem** [codesandbox/codesandbox-client#8050]
https://codesandbox.io/s/suspicious-danilo-zgf699?file=/src/App.tsx

I've been waiting for ages until it works and reloaded the page a dozen times. But "mobx" won't resolve. 

![image](https://github.com/codesandbox/codesandbox-client/assets/114060/d2851870-e4e1-4dbc-a7a0-204605796b68)

**Comment by kubk** [comment]
<img width="762" alt="Screenshot 2023-09-05 at 16 23 10" src="https://github.com/codesandbox/codesandbox-client/assets/22447849/f0ab79c0-62ab-4cab-817c-34a075ca4d65">

Do you see the error message?

**Comment by CompuIves** [comment]
Right, as @kubk mentioned, by setting the `moduleResolution` to the correct value it'll work. I've also updated the default TS version to 5.2.2.

Here's a fixed sandbox: https://codesandbox.io/s/dark-hill-qpzzsy?file=/src/App.tsx
