### ISSUE TITLE
tsconfig paths not supported?

### ISSUE THREAD

**Issue by kamranayub** [codesandbox/codesandbox-client#807]
I am hoping to use CodeSandbox for an upcoming presentation to have an in-browser editor experience. I tried importing my (working) local TypeScript create-react-app repo: https://github.com/kamranayub/sample-react-ts-app (sandbox: https://codesandbox.io/s/n1kn3z5l9m)

When I import it into CodeSandbox, it doesn't like the tsconfig `paths` options. This is a useful feature for a lot of reasons (short imports, etc.). Any idea if that will be supported? It's supported in a vanilla CRA TS project.

**Comment by CompuIves** [comment]
We don't support this yet, but is definitely aligned with one of our goals. So it'd be great to have this.

We already have alias support in the sandbox compiler, so the one thing we need to do is have a way to be able to convert a path using the `paths` object. Something like

```js
getAliasedPath = (path: string) => {
  const { parsed } = this.configurations.tsconfig;
  // Now use parsed.paths to convert path
}
```

I expect that a similar function is already somewhere out there because it's used in the local `tsc` compiler.

**Comment by joseluisq** [comment]
I also have the same problem with custom `tsconfig` paths.
https://codesandbox.io/s/github/joseluisq/hyperapp-starter

```
DependencyNotFoundError
Could not find dependency: '@app/app' relative to '/src/main.tsx'
```

I hope you can fix soon!

**Comment by merkuriy** [comment]
+1
That would be very helpful to fix.

Example project [github/Angular-RU/angular-ngrx-starter](https://codesandbox.io/s/github/Angular-RU/angular-ngrx-starter)

**Comment by BeSpunky** [comment]
Anything new on this?

**Comment by vaalgrind** [comment]
Anything new on this??

**Comment by deadcoder0904** [comment]
Yep I thought it did work so [I asked again](https://github.com/codesandbox/codesandbox-client/issues/3884#issuecomment-749953478).

Would defo love this. Otherwise all the time goes in changing the imports which is boring work 😂

**Comment by MichaelDeBoey** [comment]
I just had this issue myself too

**Comment by DeMoorJasper** [comment]
This is gonna be fixed once we rewrite the resolver, which is planned to happen soonish
