### ISSUE TITLE
Console wrongly shows two useEffect execution although react useEffect should run only once

### ISSUE THREAD

**Issue by KErez** [codesandbox/codesandbox-client#8075]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
I create a simple code that has `useEffect` without dependencies and thus it should run once after component initialization and not on subsequent re-render.
However when pressing the reload button I see the console log in the useEffect print twice.
Note that if I change something in the code and it run again I see it only once so it has to relate somehow also to the reload button.

## How has this issue affected you? What are you trying to accomplish?
Run react correctly using useEffect
### To Reproduce
1. Run the following code below (react with typescript)
2. Reload the code using the reload button on the application (not the browser's reload)

Expected:
`Item Loaded` message is logged once on the console.
Actual:
`Item Loaded` message is logged twice.

Code:
```
import React, { useEffect, useState } from "react";
import "./styles.css";

export default function App() {
  const [itemId, setItemId] = useState(0);
  const [loading, setLoading] = useState(false);

  const updateItemId = () => {
    setItemId((prev) => prev + 1);
  };
  console.log("rendering");
  useEffect(() => {
    setTimeout(() => {
      console.log("item loaded");
      setLoading(false);
    }, 2000);
  }, []);

  return (
    <div className="App">
      <input
        onChange={updateItemId}
        placeholder="Change item id"
        value={itemId}
      />
      <button onClick={() => setLoading(true)}>Load Item</button>
    </div>
  );
}
```
### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/currying-worker-rqj6nw?file=/src/App.tsx:0-662
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |Chrome             |
| Operating System |     Windows 10         |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by CompuIves** [comment]
When using React Strict Mode, React will run a `useEffect` twice to detect any errors in dev mode. I think that's what you're seeing here. If you remove the `React.StrictMode` wrapper component, it should run only once.

It only updates once on code change, because on hot module reload (e.g. dynamic code update), they _do_ run it once because it's seen as a component update.

More info: https://stackoverflow.com/questions/60618844/react-hooks-useeffect-is-called-twice-even-if-an-empty-array-is-used-as-an-ar

**Comment by KErez** [comment]
Awesome @CompuIves, this was really the issue. Great to learn new things!!!
I'm closing the bug
