### ISSUE TITLE
React Typescript is broken right now

### ISSUE THREAD

**Issue by lciii** [codesandbox/codesandbox-client#8078]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

A new, unedited React Typescript sandbox doesn't recognize react and gives me this error:

![image](https://github.com/codesandbox/codesandbox-client/assets/8713721/671e9148-fb77-47f4-bbf6-c3918822eedf)

This is happening on brand new sandboxes and existing sandboxes

## How has this issue affected you? What are you trying to accomplish?

I'm not able to get types from react correctly.

### To Reproduce

Create a new React Typescript sandbox and observe error

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |       https://codesandbox.io/s/cocky-leavitt-86tygd       |
| Browser          |       Chrome       |
| Operating System |        Max OS      |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by gilbarbara** [comment]
I noticed that the VSCode TypeScript got updated to 5.2.2, which might be the cause for this behavior.
If I open the command palette (⌘⇧P) and select the `TypeScript: Reload Project`, the errors are gone.
Maybe the sandbox needs to call some hook after it's loaded?

**Comment by CompuIves** [comment]
Interesting, thanks for the investigation @gilbarbara. Could be indeed that the file watcher is not triggered correctly which causes these issues. We load in the types lazily, so I can imagine that TS starts throwing those errors from the start. I'll take a look.

**Comment by CompuIves** [comment]
Okay, I've created a fix for it. Basically what you suggested @gilbarbara  :).

I will wait for tests to pass, then merge it to `main`. Then a deploy will approximately take ~16 minutes. So expect the fix to be live in about half an hour!

**Comment by gilbarbara** [comment]
@CompuIves 
Awesome, thanks!

**Comment by CompuIves** [comment]
It's live now! Could you verify that it's working for you? I'll reopen the issue until we've gotten some confirmation that we're in the clear 😄 .

**Comment by lciii** [comment]
Working great now!

**Comment by gilbarbara** [comment]
Yes, it's working! 👏🏻
Here's an example: https://codesandbox.io/s/github/gilbarbara/react-inlinesvg/tree/main/demo

**Comment by CompuIves** [comment]
Great!
