### ISSUE TITLE
react-scripts v5 module error when running in browser sandbox, but not when running in cloud or locally 

### ISSUE THREAD

**Issue by isaac-mason** [codesandbox/codesandbox-client#8086]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## How has this issue affected you? What are you trying to accomplish?

On creating a browser sandbox and importing the npm package `recast-navigation`, I ran into a react-scripts bundler error:

```
Cannot use 'import.meta' outside a module
```

With the same sandbox converted to a cloud sandbox, or when downloading the sandbox and running it locally, I don't get this error.

I understand the package may not be correctly configured, and getting into that is definitely out of the scope of this issue, but at the very least I'd expect consistent behaviour.

### Link to sandbox:

Browser sandbox that errors when bundling: https://codesandbox.io/s/competent-thompson-tyrqc6

Cloud sandbox that doesn't get the error: https://codesandbox.io/p/sandbox/musing-tu-yc8ll2

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  *Unsure what to put here, sorry!*            |
| Browser          |  Chrome 115.0.5790.170            |
| Operating System |  macos 13.3.1            |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by isaac-mason** [comment]
I did find some PRs that looked like they could be related. Seemingly to support React Scripts V4 this PR was required, but the change hasn't been made for react-scripts v5: https://github.com/codesandbox/codesandbox-client/pull/5107/files#diff-83ec4ed2e4ccde980f299b2a1fd91cdd1bd5527a4c3d5143fcd913f5741077e6

**Comment by stephenhebert** [comment]
I am seeing this issue with Vite
