### ISSUE TITLE
All pages always open blank.

### ISSUE THREAD

**Issue by shaipetel** [codesandbox/codesandbox-client#8138]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

All samples I try to load are loading blank.
Even if I try to create a new sample it is just a blank screen.

![Screenshot 2023-10-19 140011](https://github.com/codesandbox/codesandbox-client/assets/6225881/08403edf-4f9b-4ab4-8981-3fadbc86b9e8)

## How has this issue affected you? What are you trying to accomplish?
I can't view any samples

### To Reproduce
- visit: https://react.fluentui.dev/?path=/docs/components-dropdown--default#controlled
- click on any of the samples "Open in CodeSandbox"
- get to https://codesandbox.io/s/njlsm2?file=/example.tsx
- page is blank

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/njlsm2?file=/example.tsx

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |    Edge  Version 119.0.2151.12 (Official build) stable app, beta channel (64-bit)         |
| Operating System |  Windows 11 Enterprise   23H2         |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hello @shaipetel - this should now be fixed. Sorry for the trouble.

**Comment by shaipetel** [comment]
Thanks @JamesACS , but it worked for 1 day, now back to all being broken again.

Here is another example:
https://codesandbox.io/s/jgps7v?file=/example.tsx

Every example I try to load, as well as a blank one I try to create always appear blank.

What was the issue?

**Comment by JamesACS** [comment]
Hello @shaipetel - I'm afraid I can't replicate the issue here. That Sandbox is loading as expected. 

Please could you clear your cookies and browser cache then try again?

**Comment by gregg-cbs** [comment]
Same here, no codesandbox is loading for me. Just a blank screen. I have opened another issue on this. I thought this was to do with the react app template but it seems no sandbox loads :/
