### ISSUE TITLE
Parsing error:  Unexpected token null

### ISSUE THREAD

**Issue by lucianvaduva** [codesandbox/codesandbox-client#8146]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Eslint throwing null error
![image](https://github.com/codesandbox/codesandbox-client/assets/15967122/dd8b5283-fbc0-4b5a-8816-c2520efc099d)

If file is closed and reopen, error is not there anymore. Any new line of code and the eslint error appears again.
https://codesandbox.io/s/redux-workshop-forked-f97tg5?file=/src/index.js

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  https://codesandbox.io/s/redux-workshop-forked-f97tg5 |
| Browser          |       Version 118.0.5993.96 (Official Build) (arm64)       |
| Operating System |        MAC Os      |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by CompuIves** [comment]
Can reproduce the error... Checking.
