### ISSUE TITLE
Cannot disable beta sandbox editor

### ISSUE THREAD

**Issue by ckifer** [codesandbox/codesandbox-client#8196]
# 🐛 bug report

## Preflight Checklist

- [X] I have read the [Contributing Guidelines][contributing] for this project.
- [X] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I can't disable the beta editor (which is an awful experience thus far)

## How has this issue affected you? What are you trying to accomplish?

Revert to old editor

### To Reproduce

Go into account -> Preferences -> Experiments -> Sandbox editor beta -> try to disable -> select a reason -> submit -> still enabled
<img width="716" alt="image" src="https://github.com/codesandbox/codesandbox-client/assets/25180830/3af2b2d9-e700-410e-8884-5483f909645e">

https://github.com/codesandbox/codesandbox-client/assets/25180830/f8b9b2cb-b2c9-4c13-ae59-8d5660bb26e6

### Link to sandbox: [link]() (optional) 
N/A

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |       unsure      |
| Browser          |     latest chrome       |
| Operating System |      latest OSX      |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by ckifer** [comment]
This code looks pretty sus https://github.com/codesandbox/codesandbox-client/blob/47bc3a937ae7b5f5f9e95bfb76ae9ae4e5681aea/packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/BetaSandboxEditor.tsx#L59-L60

**Comment by alexnm** [comment]
Hey @ckifer thanks for reporting this. the code you mentioned is ok, as it sets the experiment to true when you click on the switch. I'm looking into this to figure out why the value is not reset.  Do you happen to see an error in the console when you click on the `Disable` button.

PS: Sorry to hear you've had a hard time with the new editor, we had a few bumps today as it was a big release, but hoping to iron out any issues until the end of the week. We'd appreciate any other feedback on the editor experience.

PS2: If you're eager to fallback to the old editor, you can manually set this in localStorage to open your sandboxes in the old editor `localStorage.setItem("CSB/BETA_SANDBOX_EDITOR", "false")`

**Comment by ckifer** [comment]
Thanks for the workaround! I'll check when I get a chance and report back. 

I'll try to make a more in depth feedback report when I get a chance about the beta editor (and sorry for the blanket statement, I know a lot of work goes into changes like these). Appreciate the response!

**Comment by ckifer** [comment]
So it looks like the localstorage value does change but it does not update reactively and adjust the state of the button.

No error in the console I think its just a react issue - there needs to be a re-rendering and it isn't happening. In the react dev tools I can see the toggle state value is still `true` after updating the value in the code. I think the area where feedback state is set is still suspect here

**Comment by ckifer** [comment]
Thanks!
