### ISSUE TITLE
i cant login 

### ISSUE THREAD

**Issue by luishidalgoa** [codesandbox/codesandbox-client#8197]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 121.0.0 | Windows 10           | 47bc3a937          |

  **Route:**
  https://codesandbox.io/signup/oD3DSVnL-iKneLa8Y7_9qbq1b-kHI1SBRDKn7gs_BzY

  **Error Code:**
d8e18af7e3f345a5a5855b227b9f4962

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  SecurityError: Failed to read a named property 'origin' from 'Location': Blocked a frame with origin "https://codesandbox.io" from accessing a cross-origin frame.
  Error: Failed to read a named property 'origin' from 'Location': Blocked a frame with origin "https://codesandbox.io" from accessing a cross-origin frame.
    at https://codesandbox.io/static/js/page-signup.8615578fc.chunk.js:1:558
    at pa (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:1986042)
    at Cl (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:2010768)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:2028976)
    at qo (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:1953703)
    at wl (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:2010531)
    at https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:2010442
    at z (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:2028358)
    at A.port1.onmessage (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:2027102)
  
    in u
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in je
    in withRouter(je)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in Ie
    in c
    in t
  ```

  </details>

**Comment by alexnm** [comment]
Thanks for reporting, looking into it. Does this happen on all browsers?

**Comment by luishidalgoa** [comment]
i use Microsoft Edge

**Comment by alexnm** [comment]
If it's not too much, can you please confirm this does not happen in other browsers? Looking at the link, are you doing a fresh registration?
