### ISSUE TITLE
Local proxy http on the dev sandbox doesn't work

### ISSUE THREAD

**Issue by noam-honig** [codesandbox/codesandbox-client#8221]
# 🐛 bug report

## Description of the problem
I have two node js servers running no the sandbox - one uses vite, the other node js - there is a proxy definition in the vite.config.ts file that works great on my local machine but doesn't work in the devbox

I've tried replacing the local host, with 127.0.0.1 and with [::1] didn't work.
Only when I replaced it with the full temporary url it worked.

## How has this issue affected you? What are you trying to accomplish?
It prevents me from developing full stack apps on the devbox

### To Reproduce
I've created this simple sandbox to reproduce the problem - it's based on the vite template and I've added an express server
Please run: `npm run dev` for vite , and `npm run dev-node` for the express server

https://codesandbox.io/p/devbox/demo-proxy-not-working-on-sandbox-itself-wdtj85?

Open the browser that represents port 5173 and you'll see the errors for each method called.

Go to vite.config.ts, replace the localhost url with the browser url for the other preview and it'll work.
Look at 5173 and now you'll see an ok result

### Link to sandbox: [link]() (optional)
https://codesandbox.io/p/devbox/demo-proxy-not-working-on-sandbox-itself-wdtj85?

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |   0.0.126           |
| Browser          |          chrome    |
| Operating System |          windows 10    |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by alexnm** [comment]
There's a limitation currently with processes started from the terminal. Can you try configuring both `npm run dev` and `npm run dev-node` from a configured task in `.codesandbox/tasks.json`?

**Comment by noam-honig** [comment]
Hi @alexnm , thanks so much - works like a charm
