### ISSUE TITLE
Cookies do not work in the mini browser - but do work in the real browser

### ISSUE THREAD

**Issue by noam-honig** [codesandbox/codesandbox-client#8232]
# 🐛 bug report

## Description of the problem
I have a small app that sets a cookie on the server - the cookie is used to store the current user.

That cookie doesn't work when I use the mini browser, but when I open the mini brower url in a separate chrome tab - cookies do work

## How has this issue affected you? What are you trying to accomplish?

The signed in user is not preserved

### To Reproduce
Here's a sandbox:
https://codesandbox.io/p/devbox/compassionate-field-2kjj5h?file=%2Fsrc%2Fserver%2Fauth.ts%3A3%2C1

1. Click sign in
2. Set whatever name
3. refresh the mini browser 
4. see that the sign in link appears again and you are not signed in. (THE BUG)
5. copy the mini browser url(https://2kjj5h-5173.csb.app/ in my case)  and repeate the process there - the user stays signed in

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |     Chrome         |
| Operating System |         Windows     |

Version: 0.0.142
Environment: production
Sandbox: 2kjj5h
Pitcher: 0.328.2
Manager: 1.35.0
Cluster: fc-eu-0

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hello there, 

The in-editor preview is rendered within an iframe and has a different domain to the editor. As a result the cookies will be treated as a third party cookie while trying to use your application within the in-line preview. 

You'll need to adjust any cookies you have set to account for this as browsers treat first party and third party cookies differently.
