### ISSUE TITLE
Why am I stuck with the new version where I don't see the left icon sidebar anymore and don't know how to find deployment menu

### ISSUE THREAD

**Issue by dawei-dai-exa** [codesandbox/codesandbox-client#8238]
# 🐛 bug report

## Preflight Checklist

- [ ] I have read the [Contributing Guidelines][contributing] for this project.
- [ ] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [ ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |              |
| Operating System |              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hello @dawei-dai-exa 

You can find the answers to some of your questions in our [Sandbox FAQs](https://codesandbox.io/docs/learn/sandboxes/faq) in our documentation.

You can also find more information about the new editor and it's features, regardless of whether you're working in a Devbox or Sandbox from the relevant section [which can be selected from the side bar](https://codesandbox.io/docs/learn/devboxes/your-first-sandbox)
