### ISSUE TITLE
🌈Allow "anonymous" account access to LIVE editing

### ISSUE THREAD

**Issue by jamesopti** [codesandbox/codesandbox-client#825]
# 🌈 Feature

When using the LIVE feature, it would be great to be able to send out live links for editing without requiring the recipient be logged into Github.

I came from using [webpackbin](https://github.com/cerebral/webpackbin) where it was really easy to allow anonymous access.

When navigating to a LIVE link shared with you by a Patron, editing should be enabled via the link without having to login to a Github account.

Firebase supports anonymous user access out of the box. Im not sure what Codesandbox is hosted on.

**Comment by IAmNatch** [comment]
Wondering if there are any plans to allow this? 

Codesandbox is an awesome platform and we’d love to use it as a remote white boarding tool during interviews, but the lack of anonymous collaboration is a major pain point around this process when dealing with time sensitive interviews.

**Comment by pietrofxq** [comment]
+1 this is the only thing missing to allow codesandbox to be used for coding tests

**Comment by JamesACS** [comment]
@pietrofxq You can add any test candidates to your Sandboxes as a collaborator, which will only give them access to the single Sandbox!

**Comment by istvandesign** [comment]
> @pietrofxq You can add any test candidates to your Sandboxes as a collaborator, which will only give them access to the single Sandbox!

Yes, but the collaborator still needs to log in with a personal account.

**Comment by filipelima18** [comment]
Hi @istvandesign. Our live sessions feature currently only allows giving access to signed-in users. However, please do share that as a [feature request](https://www.codesandbox.community/c/feature-requests/) - if it gets upvoted by more users, it will become a higher priority in our roadmap.
