### ISSUE TITLE
Can't update  dependencies

### ISSUE THREAD

**Issue by noam-honig** [codesandbox/codesandbox-client#8257]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
I can't update dependencies in my code sand box.
The code sandbox is based on a github repo - and I created it like this:
https://githubbox.com/remult/react-vite-express-starter

In the dependencies are on the left, I click the update to latest button next to the `tsx` dev dependency:
It spins for a few seconds, but it doesn't update the package json, or the view in the dependencies

![image](https://github.com/codesandbox/codesandbox-client/assets/16635859/049b76aa-048b-4945-98e4-785748d203d6)

## How has this issue affected you? What are you trying to accomplish?
Makes it harder to use codesandbox for day to day stuff

### To Reproduce
Open:
https://codesandbox.io/p/devbox/fast-fire-66nwr4?workspaceId=7e9d0505-ea79-46f1-8973-50cadde4fa96

Click the update to latest button next to tsx

### Link to sandbox: [link]() (optional)
https://codesandbox.io/p/devbox/fast-fire-66nwr4?workspaceId=7e9d0505-ea79-46f1-8973-50cadde4fa96

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |              |
| Operating System |              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @noam-honig 

I'm sorry to hear about the trouble you experienced with our new editor.

To resolve the problem please could you try going to your browser devtools and under the applications tab unregister the CodeSandbox service worker?

When you then reload your project, a new version of the service worker with fixes and improvements will be registered. Which should hopefully resolve the problem.

**Comment by noam-honig** [comment]
I did as you've mentioned and tried it again.

It doesn't reflect the new version in the ui on the left, but npm ls did show it.

Maybe it has something  to do with the repo originally being created with npm.

**Comment by noam-honig** [comment]
Great - thanks for the update

**Comment by JamesACS** [comment]
Hey @noam-honig - This should now be fixed!

**Comment by noam-honig** [comment]
Hi @JamesACS  looks great - thnks
