### ISSUE TITLE
Unable to start the microVM

### ISSUE THREAD

**Issue by ismailyagci** [codesandbox/codesandbox-client#8272]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Version: | 0.0.162
Environment: | production
Event: | Initial connect to Pitcher
State: | ERROR
Branch: | tgpx85

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |              |
| Operating System |              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hello there, 

When this issue occurs we recommend waiting a few minutes and trying to load the project again, it seems this project is now working as expected.

**Comment by ismailyagci** [comment]
I've been getting this error for days. It never resolves. It is solved when
you log in with VPN. I am sending the link below. When I wait a few minutes
and restart, it doesn't resolve. It appears to be resolved for you.

https://codesandbox.io/p/devbox/fire-proton-api-pyjz49 _
<https://codesandbox.io/p/devbox/fire-proton-api-pyjz49>

James ***@***.***>, 15 Oca 2024 Pzt, 18:09 tarihinde şunu
yazdı:

**Comment by JamesACS** [comment]
Hello @ismailyagci -

I believe we're now discussing this in an email thread. We'll continue speaking there to try and resolve this.
