### ISSUE TITLE
Unable to use SVG as background image

### ISSUE THREAD

**Issue by rfinni** [codesandbox/codesandbox-client#8275]
# 🐛 bug report

## Preflight Checklist

- [x ] I have read the [Contributing Guidelines][contributing] for this project.
- [ x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [ x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
I'm noticing that I'm not able to use an SVG file as a background image in CSS with a React sandbox. For example:

```css
.some-element {
  background: url("./assets/test.svg");
}
```

There's no errors in the console but the SVG is not rendered.

The only way I can get it to work is if I inline the SVG like below.

```css
.some-element {
  background: url("data:image/svg+xml;utf8,<svg ...> </svg>");
}
```

This works correctly in a non-React HTML + CSS sandbox. [Reference](https://codesandbox.io/p/sandbox/cranky-matan-6hr944).

There's nothing wrong with the SVG from what I can tell, seeing as it works in the other sandbox I linked above.

## How has this issue affected you? What are you trying to accomplish?
Just trying to build out a demo and I'd rather not inline the SVGs if I can help it.

### To Reproduce
1. Create a new React sandbox.
2. Add a div
3. Add an SVG file
4. Try adding the SVG as a background to the div
5. Nothing is rendered

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | React Sandbox              |
| Browser          |  Chrome             |
| Operating System | MacOS Ventura             |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hello @rfinni - 

In the example link provided, there isn't a file called test.svg in the assets folder. Did you remove this?

**Comment by rfinni** [comment]
@JamesACS yes I removed it, but that could be substituted with any of the other SVGs in the `/assets` directory and you should be able to see the issue. For example, `background: url("./assets/car.svg");`

**Comment by rfinni** [comment]
@JamesACS any update on this?

**Comment by JamesACS** [comment]
Hello @rfinni, thank you for your patience. 

We've looked into this on our end, and it seems that loading svgs in this way is not compatible with our create-react-app bundler. 

However, if you convert this environment to a Devbox, it should work seamlessly!

**Comment by rfinni** [comment]
Thanks @JamesACS! I ended up inlining the SVGs and that worked for my needs.
