### ISSUE TITLE
Sandbox container hangs on initialization

### ISSUE THREAD

**Issue by brocode101** [codesandbox/codesandbox-client#8278]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Hi there! This following particular sandbox's container is failing to finish initialising:

### To Reproduce

[https://codesandbox.io/embed/s2cz89?fontsize=14&hidenavigation=1&theme=dark](url)

### Link to sandbox: [https://codesandbox.io/embed/s2cz89?fontsize=14&hidenavigation=1&theme=dark]

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hello there, 

This environment is now working again. Thank you for the report. 

In the future, for issues concerning specific environments rather than platform wide issues please contact us at support@codesandbox.io
