### ISSUE TITLE
Preview page doesn't load

### ISSUE THREAD

**Issue by YavuzAvcii** [codesandbox/codesandbox-client#8284]
# 🐛 I cannot see the preview of my code

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Whenever I try to see the result of my code it is not working. I tried opening another project, another browser but it didn't work. It says 5r373z.csb.app sent an invalid response.

## How has this issue affected you? What are you trying to accomplish?
I am trying to see the preview of my code

### Link to sandbox: [link]() (optional)
https://codesandbox.io/p/sandbox/react-dev-forked-gnvsm2?file=%2Fsrc%2Findex.js%3A9%2C15

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |       0.0.177       |
| Browser          |     Google Chrome        |
| Operating System |      Windows 10 |
![Ekran Görüntüsü (115)](https://github.com/codesandbox/codesandbox-client/assets/95363328/094928b9-d55c-4b78-9600-94c67dcb1a55)
     

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hello @YavuzAvcii 

It looks as though your internet service provider has blocked our csb.app domain.

Unfortunately, we can't do anything about this. We'd recommend contacting your ISP directly to request it be unblocked.
