### ISSUE TITLE
Add GitLab integration

### ISSUE THREAD

**Issue by AlessandroAnnini** [codesandbox/codesandbox-client#829]
# 🌈 Add GitLab integration
It should work just like the Github integration

**Comment by makmm** [comment]
Is this in any way beginner friendly? I haven't touched CodeSandbox codebase once, but I really want to have this feature

**Comment by CompuIves** [comment]
We're working on this :D

https://twitter.com/gatsbyjs/status/1006222610651230208?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1006222610651230208&ref_url=https%3A%2F%2Fmedium.com%2Fmedia%2F6ec50da7e9677a9bc8477e4ad92a890f%3FpostId%3D876f5933160b

**Comment by makmm** [comment]
@CompuIves 'this' as in GitLab integration, or Gatsby support?

**Comment by CompuIves** [comment]
Oh wow I responded to the wrong issue! I'm sorry. Regarding GitLab support, we'd require an equivalent version of this file for GitLab: https://github.com/codesandbox-app/codesandbox-importers/blob/master/packages/git-extractor/src/routes/github/pull/download.ts.

**Comment by makmm** [comment]
Okay, I could try to do that later. @CompuIves

**Comment by camflan** [comment]
@makmm you can use https://raw.githack.com/ instead of rawgit for creating the proper Content-Type headers in the download links.

Not sure if you've made any progress on this yet. If not, I can take a swing at it later or I can help on yours

**Comment by makmm** [comment]
@CompuIves I changed it to use raw.githack.com. Haven't tested as I'm pretty sure there's more to the implementation than just this. Here's the snippet: https://gitlab.com/snippets/1758936. If something is wrong hmu! and if it isn't *that* hard to make the full integration I could try making a PR :)

**Comment by ArsalaBangash** [comment]
Another +1 for Gitlab integration

**Comment by Aarstad** [comment]
+ 1 for gitlab!

**Comment by sulaqo** [comment]
+1

**Comment by lbogdan** [comment]
@makmm Are you still interested in pursuing this? If so, you could try taking a look at @SaraVieira 's PR here: https://github.com/codesandbox/codesandbox-importers/pull/19 .

**Comment by makmm** [comment]
@lbogdan honestly I don't care about it that much, but would be cool. what's wrong with SaraVieira's PR? I already some basic code a long time ago (see https://github.com/CompuIves/codesandbox-client/issues/829#issuecomment-426081070) but it kinda was ignored.

**Comment by nadendlaprasad** [comment]
any idea when integration with gitlab will be available ?

**Comment by binaryfire** [comment]
Is this still in the works?

**Comment by AndreiJirohHaliliDev2006** [comment]
:+1:

**Comment by CodeFreezr** [comment]
I would vote for complete Gitlab Support.

**Comment by Vinnl** [comment]
Might as well use this bump to share [a webcomic I like](https://thejenkinscomic.wordpress.com/):

![image](https://user-images.githubusercontent.com/4251/92250813-3d746a00-eecc-11ea-9ab6-05cc7de7d56d.png)

**Comment by SaraVieira** [comment]
10/10 

Removing the label as this would be awesome to add

**Comment by Vinnl** [comment]
Hmm, missed that previous notice. Does another bump reopen it?

**Comment by YoungElPaso** [comment]
Also think this would be great. Currently mirroring a repo to GH just to be able to bring it into CSB - which isn't really sustainable. The other solution is using  a container sandbox and then using git to pull my GL repo directly via the terminal...but then I run into file sync issues.

**Comment by rayfoss** [comment]
So what's the current process for importing from git? Gitter, Bitbucket, Kernel.org, Launchpad, Gitlab.com etc.

I pay for a Pro account thinking I could have private Git repositories but I don't see a way to do that without using GitHub

**Comment by osmar2008** [comment]
So, any news in this field? Can I try to help somehow?

**Comment by LeventHAN** [comment]
3 years and still nada?

**Comment by AmazingGinger** [comment]
> 3+ years and still nada?

Try Replit. They have been making progress towards supporting more got servers, GitHub is now a drop-down option in the git UI. You can also currently disable the UI and set a password/town using secrets. Which works well if you're the only developer on that sandbox.

```
REPLIT_GIT_ASKPASS=""
REPLIT_GIT_EDITOR=""
```

**Comment by edrcq** [comment]
https://github.com/codesandbox/codesandbox-importers/pull/19

They said "they are on it".

5 five laters I'm on Stackblitz because CSB is too old 😘
