### ISSUE TITLE
Define API `query` parameter regression

### ISSUE THREAD

**Issue by oliviertassinari** [codesandbox/codesandbox-client#8299]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

The `query` param described in https://codesandbox.io/docs/learn/sandboxes/cli-api#supported-parameters doesn't seem to work.

## How has this issue affected you? What are you trying to accomplish?

I noticed because in https://mui.com/material-ui/react-switch/#color opening a codesandbox does no longer set the file in focus. The DX could be better

Actual:

![Screenshot 2024-01-28 at 17 50 35](https://github.com/codesandbox/codesandbox-client/assets/3165635/299bcc59-8d45-438a-af7b-5f0830a0b959)

Expected:

![Screenshot 2024-01-28 at 17 50 40](https://github.com/codesandbox/codesandbox-client/assets/3165635/605710a2-6217-4270-a22c-695e79fc83b4)

### To Reproduce

https://codesandbox.io/p/sandbox/define-api-get-request-forked-v5zl4m?file=%2Findex.js%3A16%2C5

taken from https://codesandbox.io/docs/learn/sandboxes/cli-api#get-request. In practice, we use the POST API but I assume the bug is shared, as it seems to happen during an internal codesandbox redirection.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |              |
| Operating System |              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by CompuIves** [comment]
This is a regression! Fix is underway.

**Comment by CompuIves** [comment]
Hmm, I can't reproduce it yet. Does it work for you in an incognito?

**Comment by CompuIves** [comment]
I'm expecting that this could be a race condition, where the initial file is set too late (only after the editor is initialized), but I cannot repro it yet.

**Comment by oliviertassinari** [comment]
A recording in incognito with the provided reproduction sandbox:

https://github.com/codesandbox/codesandbox-client/assets/3165635/941242e7-417a-42d3-9dfe-6ee49a1df153

**Comment by oliviertassinari** [comment]
I can reproduce the regression on React's docs as well https://react.dev/learn#components.

**Comment by CompuIves** [comment]
Ohh, this is really helpful! It looks like the redirect to the v2 editor does not carry over the query params! Taking a look...

**Comment by CompuIves** [comment]
Just opened a PR with the fix. I was testing after the redirect, and there the query param was used. I didn't realise the redirect was before that. This PR should now pass on the query parameters properly 😄
