### ISSUE TITLE
Keyboard Layout Ignored (Possibly Reading `keyCode` Instead Of `key`)

### ISSUE THREAD

**Issue by fweth** [codesandbox/codesandbox-client#8320]
# 🐛 bug report

## Preflight Checklist

- [x ] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

It seems that my keyboard layout (Colemak) is not recognized by CodeSandbox for shortcuts (like Cmd+N, Cmd+K).  It seems to look at the `keyCode` and map it to some QWERTY layout instead of reading out the `key` property of a key event?

## How has this issue affected you? What are you trying to accomplish?

Almost impossible to use if all my shortcuts are gone. This is also a known problem with VSCode, but in the VSCode settings, `"keyboard.dispatch": "keyCode",` does the trick (which is unintuitive, should be the other way around, but anyway, it works).

### Your Environment

| Software | Name/Version |
| ---------------- | ------------ |
| Сodesandbox | |
| Browser | Firefox 122.0b9 |
| Operating System | Ubuntu 23.04 |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by CompuIves** [comment]
Good report, we use VSCode for these keybindings and we might be using the wrong default settings. Thanks for sharing the docs as well! Will investigatge.

**Comment by fweth** [comment]
Ah hey, I just realized that we can bring our own VSCode settings!  In this case I think you did nothing wrong, `key` is the default in VSCode so it makes sense for CSB to mirror that behaviour, as long as the users can change it :)

**Comment by tim-phillips** [comment]
Here's the relevant vscode issue: https://github.com/microsoft/vscode/issues/23991
