### ISSUE TITLE
ERROR Branch

### ISSUE THREAD

**Issue by JakeWForce** [codesandbox/codesandbox-client#8334]
Unable to start the microVM
Your changes were saved, but we could not start the microVM running your project. Please try restarting the microVM by clicking the "Restart microVM" button."
If the issue persists, please contact our support team at [support@codesandbox.io](mailto:support@codesandbox.io) for further assistance, making sure to copy the error details below.

Error: Timed out after 10000ms
Version: 0.0.202
Environment: production
Event: Initial connect to Pitcher
State: ERROR
Branch: 5m9wty

Hello, everything was fine. then an error abruptly appeared, and the restart does not help

**Comment by JamesACS** [comment]
Hello @JakeWForce - We had a temporary outage on one of our clusters earlier today. 

If you're still experiencing this issue, please contact us from your registered email at support@codesandbox.io
