### ISSUE TITLE
Can not attach sandbox via vs code

### ISSUE THREAD

**Issue by aliaksandrsen** [codesandbox/codesandbox-client#8348]
# 🐛 bug report

## Preflight Checklist

- [x ] I have read the [Contributing Guidelines][contributing] for this project.
- [ x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [ x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Can not attach sandbox via vs code (got error)
### To Reproduce

![image](https://github.com/codesandbox/codesandbox-client/assets/51503682/55fb7d21-0ee0-442c-91ec-fd20f716fce7)

### Link to sandbox: [link]() (optional)
![image](https://github.com/codesandbox/codesandbox-client/assets/51503682/03012fc1-4db8-4403-8317-6d3c9f390321)
https://codesandbox.io/p/devbox/gcksgx?file=%2Fpackage.json

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |        chrome      |
| Operating System |       macos       |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by CompuIves** [comment]
Hey! Thanks for this report, I'm investigating why it's happening.

**Comment by CompuIves** [comment]
Hmm, I'm not able to reproduce this error. Could you share the output log of CodeSandbox? You can get that inside VSCode by opening the Output tab (at the bottom) and selecting CodeSandbox in the dropdown after the error has occured.

**Comment by aliaksandrsen** [comment]
SSH connection: 167.235.8.252:39558
SSH proxy configuration changed to true
CLI already exists at /Users/t800/.config/codesandbox/csb-cli
Starting task: "Development"
<img width="1034" alt="Screenshot 2024-02-16 at 2 11 32 PM" src="https://github.com/codesandbox/codesandbox-client/assets/51503682/297e60c8-d24f-476f-af09-aa0108f9a75e">

**Comment by CompuIves** [comment]
Okay, this is really valuable. Thanks for sharing!

Could you go into VSCode settings, search for "CodeSandbox" and then change the settings to reflect this?
<img width="909" alt="image" src="https://github.com/codesandbox/codesandbox-client/assets/587016/4c73a26a-cfd8-4e27-8eeb-30fb1308fb43">


After changing those settings, could you restart VSCode and try again? I think that might fix it.

**Comment by aliaksandrsen** [comment]
No I can not 

I am trying open https://codesandbox.io/p/devbox/85tsvt?file=%2Fpackage.json

<img width="1205" alt="image" src="https://github.com/codesandbox/codesandbox-client/assets/51503682/8ca6ef5b-2f7c-4d58-a396-92227f78d75c">

May be I need remove some extensions!?

**Comment by CompuIves** [comment]
Hmm, could be, not 100% sure. Could you share the output of `Remote - SSH` as well? That one should give a more clear error on why it could not connect.

**Comment by CompuIves** [comment]
I believe that something is going wrong with the websocket connection, given that you can connect to the web editor, I wonder if something went wrong with the SSH configuration that we did to make the connection. Another check you can do is opening "Remote Explorer" in the sidebar, and checking if under "SSH" you see something like this:

<img width="451" alt="image" src="https://github.com/codesandbox/codesandbox-client/assets/587016/99b968cb-d6bb-4be3-aebe-6c31fe40f541">

**Comment by CompuIves** [comment]
In the meantime I'm creating a new build where Websocat is enabled by default :)

**Comment by aliaksandrsen** [comment]
<img width="403" alt="image" src="https://github.com/codesandbox/codesandbox-client/assets/51503682/6796db03-b9c8-4bd8-8ef5-20db9b4b702e">
Here
<img width="395" alt="image" src="https://github.com/codesandbox/codesandbox-client/assets/51503682/8384d5c1-ecb9-4b2d-8be5-a47c1a147a98">

**Comment by aliaksandrsen** [comment]
`[14:27:57.841] > channel 2: open failed: connect failed: open failed
[14:27:58.016] > channel 3: open failed: connect failed: open failed
[14:27:58.083] > channel 2: open failed: connect failed: open failed
[14:27:58.173] Opening exec server for ssh-remote+sandbox.85tsvt.csb
[14:27:58.174] Opening exec server for ssh-remote+sandbox.85tsvt.csb
[14:27:58.182] Initizing new exec server for ssh-remote+sandbox.85tsvt.csb
[14:27:58.184] Using commit id "903b1e9d8990623e3d7da1df3d33db3e42d80eda" and quality "stable" for server
[14:27:58.185] Install and start server if needed
[14:27:58.194] Running script with connection command: ssh -T -D 63183 -o ConnectTimeout=15 'sandbox.85tsvt.csb' bash
[14:27:58.925] > Warning: Permanently added '85tsvt-62534.csb.app' (ED25519) to the list of known hosts.
[14:27:58.925] Got some output, clearing connection timeout
[14:28:01.320] > 667f2b1be1da: running
[14:28:01.344] > Found existing installation at /root/.vscode-server...
> Starting VS Code CLI... "/root/.vscode-server/code-903b1e9d8990623e3d7da1df3d33db3e42d80eda" command-shell --cli-data-dir "/root/.vscode-server/cli" --on-port --parent-process-id 1949 &> "/root/.vscode-server/.cli.903b1e9d8990623e3d7da1df3d33db3e42d80eda.log" < /dev/null
> printenv:
>     SUPERVISOR_GROUP_NAME=pitcher-agent
>     FNM_ARCH=x64
>     SUPERVISOR_SERVER_URL=unix:///var/run/supervisord.sock
>     HOSTNAME=z58qm5
>     NPM_CONFIG_CACHE=/root/.cache/npm
>     CSB_SANDBOX_ID=z58qm5
>     FNM_NODE_DIST_MIRROR=https://nodejs.org/dist
>     CSB_BASE_PREVIEW_HOST=csb.app
>     YARN_VERSION=1.22.19
>     YARN_CACHE_FOLDER=/root/.cache/yarn
>     PWD=/workspaces/workspace
>     LOGNAME=pitcher-host
>     PROJECT_GID=1001
>     PITCHER_API_BASE_URL=https://codesandbox.io/api
>     PNPM_VERSION=7.1.0
>     HOME=/root
>     FNM_COREPACK_ENABLED=false
>     NVM_SYMLINK_CURRENT=true
>     PITCHER_CLIENTS_WSS_PORT=82
>     CODESANDBOX_HOST=z58qm5-$PORT.csb.app
>     CSB=true
>     VSCODE_AGENT_FOLDER=/root/.vscode-server
>     NVM_DIR=/usr/local/share/nvm
>     PITCHER_WORKSPACE_PATH=/project/sandbox
>     CSB_EXEC_ID=d1914db7-5135-4d4c-b5f0-305a617455a3
>     TERM=xterm-256color
>     SHLVL=1
>     FNM_VERSION_FILE_STRATEGY=local
>     LC_CTYPE=C.UTF-8
>     FNM_RESOLVE_ENGINES=false
>     WATCHMAN_VERSION=2022.05.30.00
>     SUPERVISOR_PROCESS_NAME=pitcher-agent
>     CSB_PITCHER_MANAGER_BASE_URL=http://10.43.0.254:8001
>     WORKSPACE_PATH=/project/sandbox
>     ZSH_DISABLE_COMPFIX=true
>     PATH=/usr/local/share/nvm/current/bin:/usr/local/share/npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
>     NPM_CONFIG_STORE_DIR=/root/.cache/pnpm
>     PERMISSION_WATCHER_VERSION=0.1.3
>     FNM_DIR=/usr/share/fnm
>     NODE_VERSION=20.9.0
>     FNM_MULTISHELL_PATH=/project/home/pitcher-host/.local/state/fnm_multishells/1062_1707736550532
>     FNM_LOGLEVEL=info
>     PITCHER_ENV=production
>     PITCHER_BIN_PATH=/pitcher/pitcher.cjs
>     OLDPWD=/project/sandbox
>     SUPERVISOR_ENABLED=1
>     _=/usr/bin/printenv
> Removing old logfile at /root/.vscode-server/.cli.903b1e9d8990623e3d7da1df3d33db3e42d80eda.log
> Spawned remote CLI: 1969
[14:28:01.365] > Waiting for server log...
[14:28:01.403] > 667f2b1be1da: start
> SSH_AUTH_SOCK====
> DISPLAY====
[14:28:01.418] > listeningOn==127.0.0.1:41553==
> osReleaseId==debian==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/tmp==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> serverStartTime==61==
> execServerToken==11aa11a1-1111-11a1-11aa-aaaaa111aa11==
> 667f2b1be1da: end
[14:28:01.418] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
listeningOn==127.0.0.1:41553==
osReleaseId==debian==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/tmp==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
serverStartTime==61==
execServerToken==11aa11a1-1111-11a1-11aa-aaaaa111aa11==

[14:28:01.418] Remote server is listening on port 41553
[14:28:01.418] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":41553},"osReleaseId":"debian","arch":"x86_64","sshAuthSock":"","display":"","tmpDir":"/tmp","platform":"linux","execServerToken":"11aa11a1-1111-11a1-11aa-aaaaa111aa11"},"serverStartTime":61,"installUnpackCode":""}
[14:28:01.420] Starting forwarding server. local port 63244 -> socksPort 63183 -> remotePort 41553
[14:28:01.420] Forwarding server listening on port 63244
[14:28:01.421] Waiting for ssh tunnel to be ready
[14:28:01.421] Tunneled port 41553 to local port 63244
[14:28:01.421] Resolved "ssh-remote+sandbox.85tsvt.csb" to "port 63244"
[14:28:01.421] Resolving exec server at port 63244
[14:28:01.422] [Forwarding server port 63244] Got connection 0
[14:28:01.422] [Forwarding server port 63244] Got connection 1
[14:28:01.709] Exec server for ssh-remote+sandbox.85tsvt.csb created and cached
[14:28:01.784] Verified and reusing cached exec server for ssh-remote+sandbox.85tsvt.csb`

**Comment by aliaksandrsen** [comment]
<img width="1236" alt="image" src="https://github.com/codesandbox/codesandbox-client/assets/51503682/d2656204-6157-479a-ab45-c74012036f05">
I can see myself on web interface

**Comment by aliaksandrsen** [comment]
A couple of minutes ago I installed vs code insiders and it works on my laptop.

**Comment by CompuIves** [comment]
This is incredible information @aliaksandrsen, thanks so much for sharing! I now think that the connection succeeds, but the folder (`/workspaces/workspace`) is not created, making me think you might not be connecting with the container. I'm going to ask a team-member to take a look with me.

**Comment by CompuIves** [comment]
It's interesting that VSCode Insiders works... Would you mind sharing your VSCode settings? I wonder if there's a configuration about default path or something that could influence this.

**Comment by aliaksandrsen** [comment]
just
{
  "codesandbox.currentWorkspace": "165091a3-7c46-4ec7-930f-107016549c62",
  "codesandbox.sshProxy": false,
  "codesandbox.websocat": true,
  "remote.SSH.remotePlatform": {
    "sandbox.2k96rf.csb": "linux"
  }
  I disabled everything else

**Comment by aliaksandrsen** [comment]
Now it is working! I also disabled all unnecessary extensions I will check later what is real root cause
@CompuIves thanks a lot

**Comment by aliaksandrsen** [comment]
@CompuIves I found real root cause, it is setting
`"remote.SSH.remoteServerListenOnSocket": true`
An intersting thing - after first connection with such setting my devcontainer (devbox) become broken and I need to create another one.

**Comment by CompuIves** [comment]
Thanks for this information! I'll make sure that we have a warning for that case.
