### ISSUE TITLE
Add support for custom .npmrc

### ISSUE THREAD

**Issue by schabluk** [codesandbox/codesandbox-client#836]
# Please add support for custom .npmrc file.

This feature allows to add configuration option to NPM. For example _authToken for private pakcages.

User should be able to create his own .npmrc file in the project root directory, or it could be added to the "Configuration Files" section.

**Comment by CompuIves** [comment]
I really like this idea. We've been talking about custom npm registry support before, but I didn't think of an implementation like this. This seems like the most simple and straightforward solution to it.

**Comment by zkwsk** [comment]
Would love to see this feature too!

**Comment by geneking** [comment]
Any progress for this?

**Comment by houmanMP** [comment]
I'd like to help implement this, but have absolutely no idea where to start from >~< For my specific use case, I'd be running the codesandbox client on a private infrastructure; not sure if that is relevant or not (probably not?)

**Comment by MarkHarper** [comment]
I'm also interested in contributing to this. I've setup my local for the client, but it does seem like there will have to be an update to the packager as well. I'm not sure how to get that service setup for testing.

**Comment by garethx** [comment]
We'd be keen to know how you use private npm registries so that we can build an implementation that fits your needs. In particular, do you use a service for your private npm registries? (Like GitHub Package Registry) and do you host your npm registry within a VPN? Thanks

**Comment by xuliuzhu1834** [comment]
a service of our private npm registries  @garethx

**Comment by garethx** [comment]
Sure, but which service and is it within a VPN?

**Comment by raunofreiberg** [comment]
If it's of any help, we are using https://verdaccio.org/ and the packages are available in our office networks (and via VPN).

**Comment by garethx** [comment]
It is, thanks! We're looking to get specifics from as many folks as possible to make sure our solution works for all.

**Comment by juanmendes** [comment]
I would like this feature too, at VMware, we have a number of internal libraries that use an internal registry only available within our VPN. That is, we set `registry=https://build-artifactory.eng.vmware.com/artifactory/api/npm/npm` We are building a library that displays angular editable example and are currently using stackblitz but would switch over if this is implemented [since they also don't support it](https://github.com/stackblitz/core/issues/313). See https://github.com/vmware/vmware-cloud-director-ui-components/tree/master/projects/doc-lib and live examples at https://vmware.github.io/vmware-cloud-director-ui-components/dataExporter

Please excuse some wrong information in the README, we haven't published this repo yet.

We don't need full npmrc support though, just the registry entry.

**Comment by iwarner** [comment]
Hi

I The need to import in FontAwesome Pro Icons requires a custom NPMRC
https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

Be great to have it live

**Comment by hhvys** [comment]
This will be a very helpful feature. We have a private npm registry accessible within VPN.
I found a similar issue #97 which was opened long back.

**Comment by CompuIves** [comment]
We're now finally working full-time on this, but we'd love to have your input so we can make sure that we cover all cases. If you're interested in helping us with this, could you send an email to ives@codesandbox.io and state how you use private npm packages?

We're interested in:

1. Do you self-host your registry?
2. Are you okay with setting CORS headers on the registry?
3. Is your registry only available through a CDN?

**Comment by xiaoxiangmoe** [comment]
1

**Comment by xiaoxiangmoe** [comment]
the issue has not been resolved

**Comment by xiaoxiangmoe** [comment]
the issue has not been resolved

**Comment by garethx** [comment]
This is now available to pilot users. Docs are here: https://codesandbox.io/docs/custom-npm-registry and you can register to join the pilot here: https://airtable.com/shrlgLSJWiX8rYqyG
