### ISSUE TITLE
Bundler Web Workers

### ISSUE THREAD

**Issue by CompuIves** [codesandbox/codesandbox-client#837]
# 🌈 Feature

We support web workers currently by placing them in the `public` folder, however they are sent 'as is'. It would be great if we'd bundle the web workers too, with something like a `worker-loader!` syntax like Webpack. This way you can import `npm` modules etc. in a web worker.

The challenge here is that we need to find a way to generate a smaller JS file with just the runtime logic and necessary files for our bundler.

**Comment by cristiano-belloni** [comment]
> We support web workers currently by placing them in the `public` folder

AFAIK, they're not supported, since [PUBLIC_URL is undefined](https://github.com/CompuIves/codesandbox-client/issues/1504). Or there's an alternative way to access the `public` folder?

**Comment by desean1625** [comment]
@CompuIves This is exactly what I'm looking for. Here is an example sandbox showing what I'm trying to do.

https://codesandbox.io/s/competent-turing-g994h

**Comment by Bnaya** [comment]
re-open? :)
