### ISSUE TITLE
codesandbox preview is not working

### ISSUE THREAD

**Issue by ozgurdrmz** [codesandbox/codesandbox-client#8380]
Hello, codesandbox preview is not working for a while and couldnt find any solution. 
Also I attached a picture related to issue.
Does anyone have any suggesiton?
Thanks.
![codesandbox](https://github.com/codesandbox/codesandbox-client/assets/142833817/069150cd-2795-4c28-bd95-39962c75b3e5)

**Comment by JamesACS** [comment]
Hello there, 

Please contact us at support@codesandbox.io with a link to the environment from your registered email and we'd be happy to look into this with you
