### ISSUE TITLE
The "Could not find module in path" error on an attempt to load a package that contains esm and cjs modules

### ISSUE THREAD

**Issue by artem-kurchenko** [codesandbox/codesandbox-client#8384]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

The CodeSandBox cannot load load the 'devextreme' package which is imported inside the 'devextreme-react' package

## How has this issue affected you? What are you trying to accomplish?

We used CodeSandBox to generate examples from our [demos](https://js.devexpress.com/React/Demos/WidgetsGallery/Demo/DataGrid/SimpleArray/MaterialBlueLight/). See "Copy To CodeSandBox" 

So, I'm unable to use CodeSandBox check issues or show demos to our clients.

### To Reproduce

Please open the example I shared below below.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Browser          |      Chrome   version 122      |
| Operating System |    Windows 11          |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

## Additional information

The issue doesn't specific to the "devextreme-react" package. The issue is the same for the "devextreme-angular" and "devextreme-vue" packages. It started on March 8 according to our experience. The example I shared below was created earlier and working fine for some time.

![CSB_Issue](https://github.com/codesandbox/codesandbox-client/assets/22076961/8c824cb1-3a38-4ade-a3a5-013c7a5a4351)

**Comment by alexreardon** [comment]
Here is a slimmed down version of this issue: https://codesandbox.io/s/testing-ds-lib-rhfrz6?file=/src/index.ts

> ModuleNotFoundError: Could not find module in path: '@atlaskit/ds-lib/warn-once' relative to '/src/index.ts'

Operating System: Mac@14.4

**Comment by CompuIves** [comment]
Thanks for the repro! I found the issue, it's a regression from a recent performance optimization in our resolver. Reverting that one now...
