### ISSUE TITLE
error failed to write new configuration file /persisted/.git/config.lock

### ISSUE THREAD

**Issue by YXGuan** [codesandbox/codesandbox-client#8391]
# 🐛 bug report

## Preflight Checklist

- [X] I have read the [Contributing Guidelines][contributing] for this project.
- [X] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

error failed to write new configuration file /persisted/.git/config.lock  as shown in the images below

![image](https://github.com/codesandbox/codesandbox-client/assets/55643200/738372cd-0d4f-402b-a228-a8b20ba6c457)

![image](https://github.com/codesandbox/codesandbox-client/assets/55643200/9e90f133-758e-4b46-96d8-2f402e81d82c)

## How has this issue affected you? What are you trying to accomplish?

The editor page won't load

### To Reproduce

The last operation I performed was that I added two environment variables from the project setup configuration.

Then I clicked restart, then it won't load anymore.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |     Devbox     |
| Browser          |     Chrome         |
| Operating System |      Ubuntu Linux 20.04        |

Thank you for your help!

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by hsu-w** [comment]
got the same bug
https://codesandbox.io/p/devbox/carouselscroll-mockup-2-sg6dfv

**Comment by CompuIves** [comment]
Hey! Apologies for the inconvenience and delay. For both projects it looks like the `.git` folder got filled up and took all space on the drive, I believe because the parcel cache got committed. I have freed up the necessary space and both VMs should run as expected again. I will also ensure that we don't commit parcel cache anymore.

**Comment by YXGuan** [comment]
@CompuIves 
Hey boss, would you mind helping free up the space for this repo as well? Here's the link: https://codesandbox.io/p/devbox/lang-chain-chat-bot-forked-qn2ypl
