### ISSUE TITLE
Unable to start the microVM

### ISSUE THREAD

**Issue by Andrew501-cmd** [codesandbox/codesandbox-client#8401]
# 🐛 bug report

## Description of the problem

Unable to start the microVM

## How has this issue affected you? What are you trying to accomplish?

I can't start

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Browser          |   Chrome           |
| Operating System |    Windows 11          |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by CompuIves** [comment]
Hey! This should be resolved? Can you verify that you can start it? Feel free to reopen if you still have issues.
