### ISSUE TITLE
Invalid left-hand side in assignment

### ISSUE THREAD

**Issue by andreifloricel** [codesandbox/codesandbox-client#8409]
# 🐛 bug report

## Description of the problem

Getting an error: `Invalid left-hand side in assignment`.
The root cause seems to be that this line from the `stylis` library:
[character = position > 0 ? charat(characters, --position) : 0](https://github.com/thysultan/stylis/blob/b8c0878307ce600c7ec5082f5f940febf663a722/src/Tokenizer.js#L54)
is transpiled as:
`exports.character = character = position > 0 ? (0, $csb___Utility_js.charat)(characters, --exports.position = position) : 0;`

### Link to sandbox: [link](https://codesandbox.io/s/sandpack-project-forked-hggljl?file=/package.json)

Similar previous issue: #4476

**Comment by declan-warn** [comment]
I'm getting the same error in this sandbox: https://codesandbox.io/p/sandbox/spring-frog-wd2rp7?file=%2Findex.js

**Comment by JonnyAdaptableTools** [comment]
Same issue here, causing a blocker in our ability to release product updates

**Comment by genepaul** [comment]
Also getting the error in [this sandbox](https://codesandbox.io/p/sandbox/mui-x-placeholder-bug-4jx2y2)

If you remove importing any external dependencies, it works. As soon as you import anything and use it, the error comes up. Completely blocking.

**Comment by bogdanpetru** [comment]
We are having the same issue. Thanks!

**Comment by radubrehar** [comment]
I get the same issue when using `react-select` - don't remember to have had this some while ago....

**Comment by infinite-table-admin** [comment]
Anyone has a solution to this? Thanks and appreciate all the hard work the team behind Codesandbox is putting into this. 🙌

**Comment by devmentor-js** [comment]
I get the same problem! 
The same code has no issue in StackBlitz...

**Comment by roblotter** [comment]
Same thing here - would appreciate a fix. Think it will affect other libraries out there as well.

**Comment by roblotter** [comment]
waww... that was fast! awesome team at Codesandbox! ❤️

**Comment by CompuIves** [comment]
It was a fun issue, a dependency started using this syntax and a lot of libraries use that dependency, haha. Happy to hear that it's fixed for everyone now 😄 .

**Comment by andreifloricel** [comment]
Thank you!
