### ISSUE TITLE
Broken links in pricing

### ISSUE THREAD

**Issue by danieldanielecki** [codesandbox/codesandbox-client#8424]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

[Learn more about Sandboxes.](https://codesandbox.io/docs/learn/devboxes/editors?tab=sandbox) & [Learn more about Devboxes.](https://codesandbox.io/docs/learn/devboxes/editors?tab=devbox) links are broken.

## How has this issue affected you? What are you trying to accomplish?

I tried to read the information about pricing.

### To Reproduce

1. Go to https://codesandbox.io/pricing
2. Click any of `Learn more about ...`

**Comment by CompuIves** [comment]
Thanks for the report!
