### ISSUE TITLE
Changing 'lib' compiler option to 'es2017' has no effect

### ISSUE THREAD

**Issue by MitchelSt** [codesandbox/codesandbox-client#8427]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

### To Reproduce

1. Open sendbox, check error on line 16 under `.values`: `Property 'values' does not exist on type 'ObjectConstructor'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2017' or later.typescript(2550)`
2. Go to the `tsconfig.json` file
3. => BUG: version is set to `es2017` but the error is still showing

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |       Mar 31, 2024       |
| Browser          |        Chrome 123      |
| Operating System |      macOS (Sonoma)        |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by CompuIves** [comment]
Hmm, looks like our in-browser TS is not working correctly. I'll take a look at fixing this. In the meantime it should work correctly in a devbox.

**Comment by steveluscher** [comment]
This and #8433 are quite probably related.

**Comment by CompuIves** [comment]
Not exactly, but I do know what's causing this now! I will create a fix for this today, probably deploy tomorrow.
