### ISSUE TITLE
Public folder not working

### ISSUE THREAD

**Issue by artsakenos** [codesandbox/codesandbox-client#8472]
# 🐛 bug report

## Preflight Checklist

- [X] I have read the [Contributing Guidelines][contributing] for this project.
- [X] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
I'm struggling rendering the assets from my public folder.
It always worked flawlessy, so I am not sure is some naming convention policy or folder structure changed, I didn't find anything about. **All my projects assets are now broken.**

## How has this issue affected you? What are you trying to accomplish?
I can't render assets from the public folder.

### To Reproduce
Create a react project, put an image in the public folder, e.g.,

    /public/images/house.png

Link the image to your page, e.g.,

    <a href="/images/house.png">House</a>

(I tried to put /public too)

### Link to sandbox: [link](https://codesandbox.io/p/sandbox/school-trainer-n9pm2x) (<-- Link to a public sandbox)

This sandbox is public.
You open the NavBar, the images are all broken.

![image](https://github.com/codesandbox/codesandbox-client/assets/5011392/d2dd0603-89f9-423f-8b3e-05ed3ee7d6de)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |      Web Version        |
| Browser          |        Chrome (Latest)      |
| Operating System |        Windows 10      |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by filipelima18** [comment]
Hi @artsakenos. I couldn't reproduce the issue on my end. Opening the URL you provided, I see the images rendered as expected.
![image](https://github.com/codesandbox/codesandbox-client/assets/45261568/ab1d113a-190b-4503-9946-d226a7ed0677)

Is it still not working on your end?

**Comment by artsakenos** [comment]
> Hi @artsakenos. I couldn't reproduce the issue on my end. Opening the URL you provided, I see the images rendered as expected 
> Is it still not working on your end?

@filipelima18 Thank you for answering.

Yes, actually now is working perfecly.
I don't know what happened, maybe some server glitch, no idea. 
Justs as a reference the public assets were not available across many projects.

Thanks again!
