### ISSUE TITLE
Failed to initialize VS Code Server Error

### ISSUE THREAD

**Issue by TheRedBandiCoot** [codesandbox/codesandbox-client#8474]
# 🐛 bug report

## Description of the problem
Failed to initialize VS Code Server: Error: Waiting for port timed out. We've opened VS Code in web-only in the meantime

## How has this issue affected you? What are you trying to accomplish?
most of the extensions are not working like Thunderclient, auto close tag etc.

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by filipelima18** [comment]
Hi @TheRedBandiCoot. We are currently investigating this issue and should have a fix soon. In the meantime, a workaround is to temporarily disable VS Code Web in the editor's Experiments tab.
