### ISSUE TITLE
Unable to share sandbox / devbox

### ISSUE THREAD

**Issue by moong23** [codesandbox/codesandbox-client#8523]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Not able to share codesandbox.

Seems like the url should change when the user changes the visibility of the project (between Public / Unlisted / Private).
But no API being sended to the server on network tab and no Share URL has changed

## How has this issue affected you? What are you trying to accomplish?

Need to report bug with the demo using codesandbox, but not able to share the project.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |      chrome        |
| Operating System |           mac   |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by CompuIves** [comment]
Thanks for reporting this! Indeed, this is a bug. Fix is going live now!

**Comment by moong23** [comment]
@CompuIves, thanks for all your hard work! :) Could you let me know in a comment if the bug has been fixed?

**Comment by CompuIves** [comment]
The fix is live! Could you verify that it works?

**Comment by moong23** [comment]
It works perfectly! I appreciate your swift resolution. I'll close this issue since the problem has solved 👍
