### ISSUE TITLE
Syntax highlighting no longer working on sveltekit/.svelte files?

### ISSUE THREAD

**Issue by stephaniedavidson** [codesandbox/codesandbox-client#8531]
# 🐛 bug report
It was working, now it isn't. If you make a new sveltekit project you can see it's all gray.

## Preflight Checklist

- [ ] I have read the [Contributing Guidelines][contributing] for this project.
- [ ] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [ ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |              |
| Operating System |              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by filipelima18** [comment]
Hi @stephaniedavidson. Today, we shipped a significant editor update that uses VS Code Web by default. This explains the change you're describing. You can re-enable Svelte syntax highlighting by installing an extension such as "Svelte for VS Code", using the VS Code Extension Marketplace that's now built-in to CodeSandbox.

**Comment by stephaniedavidson** [comment]
Thank you for your quick reply! Worked.
