### ISSUE TITLE
i  can't  see  why   error?

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [codesandbox/codesandbox-client#8555]
# 🐛 bug report

## Description of the problem

i  can't  see  why   error?
https://codesandbox.io/p/sandbox/ji-ben-yong-fa-ant-design-vue-3-2-20-7dtcnw    

![image](https://github.com/user-attachments/assets/59f20fdd-9ea4-4a62-8255-ae2575093b26)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |       Google Chrome       |
| Operating System |        win11      |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by filipelima18** [comment]
Hey @duoluodexiaoxiaoyuan. It looks like you might need to update your `package.json`. I forked your project, made some updates, and it works for me. See my updated `package.json` [here](https://codesandbox.io/p/sandbox/ji-ben-yong-fa-ant-design-vue-3-2-20-forked-kq58j6?file=%2Fpackage.json%3A10%2C34&workspaceId=642af90c-4717-4730-bad3-e4c1e37ca5e2).

**Comment by duoluodexiaoxiaoyuan** [comment]
> Hey @duoluodexiaoxiaoyuan. It looks like you might need to update your `package.json`. I forked your project, made some updates, and it works for me. See my updated `package.json` [here](https://codesandbox.io/p/sandbox/ji-ben-yong-fa-ant-design-vue-3-2-20-forked-kq58j6?file=%2Fpackage.json%3A10%2C34&workspaceId=642af90c-4717-4730-bad3-e4c1e37ca5e2).

thank you reply， this problem has troubled me for a long time
