### ISSUE TITLE
Can't get any sandbox to run due to CORS errors

### ISSUE THREAD

**Issue by kswedberg** [codesandbox/codesandbox-client#8571]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Can't see the preview in any sandbox/devbox due to a bunch of CORS errors. Tried in Chrome, Edge, Safari, and Firefox. 

Here's a screenshot of what it looks like in Firefox:
<img width="1724" alt="image" src="https://github.com/user-attachments/assets/29f5fbff-b9e8-403c-a8da-631f1790276f">

### To Reproduce

Take a look at this "devbox" (it was converted from sandbox to devbox when I made it public. doesn't affect the problem):
https://codesandbox.io/p/devbox/s34nmy

I used the "JavaScript" sandbox from the Popular tab to create it. I tried one with just HTML + CSS, but that didn't work either.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |    current          |
| Browser          |      any        |
| Operating System |    Mac          |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by filipelima18** [comment]
Hi @kswedberg. Are you still facing this issue? If so, can you change the Devbox privacy to "Unlisted" so I can open the URL to investigate?

**Comment by kswedberg** [comment]
It appears to be working now. Thanks! Just out of curiosity, do you know which commit fixed this?
