### ISSUE TITLE
Codesandbox not colour editing

### ISSUE THREAD

**Issue by MarineCrou** [codesandbox/codesandbox-client#8655]
# 🐛 bug report
The editor is showing only black and white with code sandbox on all the browsers. 

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
The editor is showing only black and white with code sandbox on all the browsers. 
Is there a setting in the sandbox to fix this issue ? If so, I haven't figured it out so far, unfortunately.

<img width="1168" alt="Reference photo showing editor displaying only black and white with code sandbox" src="https://github.com/user-attachments/assets/47476417-c19f-48f5-a22e-66e3eaa725ba">

## How has this issue affected you? What are you trying to accomplish?
The code is not formatted, so difficult to read the commented out sections as well as difficult to find errors and go-over code.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/p/sandbox/weatherapp-mc-forked-s5s74q

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |    Chrome Version 130.0.6723.117  |
| Operating System |    mac os sonoma 14.4.1          |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by filipelima18** [comment]
Hi @MarineCrou. You can directly change syntax highlighting by clicking "Plain Text" at the right of the editor's bottom bar, and then selecting the language mode you want, or "Auto detect". See a short recording below.
![brave_Usvlj3Nx9Z](https://github.com/user-attachments/assets/48fd84eb-a372-4f07-bf2d-ba152bd8d01a)

**Comment by MarineCrou** [comment]
Hello,
Thank you for your response. Sorry, I should have specified it on gitHub.
Unfortunately I've tried that. Auto Detect does not work and it's stuck on
`log`. Even using `json` doesn't work. I'm coding in JS.
Would love your help.
Thanks,
Marine

Le ven. 8 nov. 2024 à 12:50, Filipe Lima ***@***.***> a
écrit :

**Comment by filipelima18** [comment]
Hi @MarineCrou. Thank you for confirming. To help us investigate this, we need some additional details about the editor version you're running. Please follow the steps below:
1. With our editor opened, click the CodeSandbox icon at the top left.
2. Click the menu item that starts with "Version:"
3. Share a screenshot of the contents of the "Debug" modal that will appear in your screen.

**Comment by MarineCrou** [comment]
Hi,
Thanks for getting back to me.

Here is the requested info :





*Version: 0.0.371Environment: productionSandbox: m4xjlqmkxyPitcher:
browserManager: browserCluster: browser*

Thank you !
Marine


Le lun. 11 nov. 2024 à 16:18, Filipe Lima ***@***.***> a
écrit :

**Comment by rickhanlonii** [comment]
This was happening to me, the root cause was that the `codesandbox.editor.integration` extension was disabled for some reason. @filipelima18 might be something folks that have this issue should check.

**Comment by filipelima18** [comment]
Thanks for sharing this @MarineCrou and thanks also to @rickhanlonii for the note. We will investigate this.
