### ISSUE TITLE
Failed to initialize VS Code Server - Set ups fail

### ISSUE THREAD

**Issue by betawaxx** [codesandbox/codesandbox-client#8678]
# 🐛 bug report

## Preflight Checklist

- [x ] I have read the [Contributing Guidelines][contributing] for this project.
- [ x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [ x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

"Failed to initialize VS Code Server: Error: Critical unhandled error (Error) occured: connect ENOENT /run/user/1002/pitcher/fs-container.sock. We've opened VS Code in web-only in the meantime."

"Error: failed to get config: failed to get devcontainer json config: failed to parse config: invalid character '/' looking for beginning of value
Usage:
  pitcher containers exec run [flags]

Flags:
      --command string     Command to run
  -h, --help               help for run
      --id string          ID for the exec
      --interactive        Interactive session
      --tty                Allocate a pseudo-TTY
      --verbose            Verbose output
      --workspace string   Workspace path

Error: failed to get config: failed to get devcontainer json config: failed to parse config: invalid character '/' looking for beginning of value

"

## How has this issue affected you? What are you trying to accomplish?

Cant open any terminals or serve any code.

### To Reproduce

Open any CSB project and update to the latest version and it fails. This is really frustrating, every one of my boxes are dead.

### Link to sandbox: [link](https://codesandbox.io/p/devbox/stash-phase3-new-n793r4)

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JeffertGamer** [comment]
Yeah Same Problem Me too

**Comment by CompuIves** [comment]
Thanks for the report! Looking into this...

**Comment by CompuIves** [comment]
This is super valuable, thank you! Working on a fix now.

**Comment by CompuIves** [comment]
Created a fix, now testing it to staging before pushing it to prod

**Comment by CompuIves** [comment]
The fix is now live! If you restart the VM, it should start working. Apologies for this regression, I'm adding some tests so it doesn't happen again.
