### ISSUE TITLE
Feature Request: Allow project to be unlinked from account

### ISSUE THREAD

**Issue by riwu** [codesandbox/codesandbox-client#875]
I want the list of sandboxes under my profile to contain only important sandboxes (for easier access).
Please add a button to allow a sandbox to be dissociated from account, so that I can remove inactive sandboxes from my profile (rather than having to delete them).

**Comment by lbogdan** [comment]
Hey @riwu ,

Doesn't the [dashboard](https://medium.com/@compuives/announcing-codesandbox-dashboard-teams-876f5933160b) solve your sandbox management needs?

**Comment by SaraVieira** [comment]
Closed for lack of activity

We now have drafts in the dashboard that should solve this issue
