### ISSUE TITLE
CodeSandbox VPN private mode

### ISSUE THREAD

**Issue by philholden** [codesandbox/codesandbox-client#883]
# 🌈 Feature
If a sandbox is tagged as VPN private then no files are exposed to CodeSandbox servers. Allows people to use CodeSandbox to develop and present on a corporate network without exposing code and packages. 

**MVP**

- public packages can be loaded from public npm as normal
- private packages can be loaded from git repo (or tar) via https

```
"my-package" : "git+https://git.my-company.com/my-package#longmeaninglesshash"
```

- bundles and filesystem stored to IndexDB only
- file system can be exported / imported via zip

**Nice to have**

- filesystem (but not bundle) can be synced between browsers by via WebRTC so a user can present to a remote team while both are online
- CodeSandbox live using WebRTC not websockets (not sure if this is what it already does)

**More fully featured**

- Docker container companies can run to cache bundles and file system
- Ability to use internal npm registry

**Comment by FernandoGOT** [comment]
+1

**Comment by CharlieLau** [comment]
+1

**Comment by MuYunyun** [comment]
Is there any progress?

**Comment by xiaoxiangmoe** [comment]
@lbogdan can you reopen it?

**Comment by Bulletninja** [comment]
🤔
