### ISSUE TITLE
custom look & feel

### ISSUE THREAD

**Issue by geddski** [codesandbox/codesandbox-client#918]
# 🌈 Feature

Custom look & feel

I'd like to be able to customize the look of codesandbox to match my site's branding. Similar to how codepen pro lets you.

Allowing a custom CSS and JS file that lives in the codesandbox iframe would be an easy v1. Then we could customize it to our liking. 

For example on my site I don't ever want to show the devtools or the view changer, and rarely want to show the file selectors or name of the example.

I'd also customize the color scheme etc. 

![image](https://user-images.githubusercontent.com/515722/41627949-9e0fb410-73df-11e8-8cf3-c867c8ef5750.png)

I'd become a Patron to have this feature.

**Comment by CompuIves** [comment]
Yea, very good request. My biggest question is how we will make this work. Would we allow for a url as query param for the css? Or would we save the themes on a server and you have a team editor?

**Comment by geddski** [comment]
Any more thoughts on this? It would make Codesandbox sooo customizable and awesome.
