### ISSUE TITLE
devDependencies in package.json doesn't seem to be processed 

### ISSUE THREAD

**Issue by jamstooks** [codesandbox/codesandbox-client#924]
# 🐛 bug report: `devDependencies` not being fetched

## Description of the problem
It seems that `devDependencies` aren't being fetched. Here's an [example project](https://codesandbox.io/s/v8l922mo57) that has `"cross-fetch": "2.2.0",` in `devDependencies`. If I move cross-fetch up to `dependencies`, it works just fine.

## How has this issue affected you? What are you trying to accomplish?
This generally affects my testing process. I'd like to keep packages like `fetch-mock` in `devDependencies` instead of `dependencies` as I have to do at the moment.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | latest (online) |
| Browser | Chrome Version 67.0.3396.87 (Official Build) (32-bit) |
| Operating System | ChromeOS |

**Comment by baoduy** [comment]
Yes, I'm facing the same issues

**Comment by CompuIves** [comment]
Yeah, this is something we really need to add soon.

The biggest initial reason was to lower downloaded bundle size, as there are many projects with >20 dev dependencies and only using one dependency.

The way to fix it is to check during the initialization which `devDependencies` are used in the code and include those to the request. This means adding an extra pass during transpilation to the bundling. I will play a bit with this this month, in the meantime you can use a Server Sandbox to make it work.

**Comment by karlhorky** [comment]
@CompuIves was this ever fixed? Or is this a `wontfix` for now?

**Comment by CompuIves** [comment]
For now, but I recently refactored our dependency installation with this in mind, so we're much closer to supporting this. 

The biggest challenge is statically analyzing which dependencies are needed, and only installing those. Once we have that it will be both performant and consistent.

**Comment by eps1lon** [comment]
Bump

**Comment by eps1lon** [comment]
bump

**Comment by FractalHQ** [comment]
Most deps in Vite / Sveltekit projects rely on devDependencies.  What's the recommended work-around for this?

**Comment by DeMoorJasper** [comment]
Not sure if we should still really fix this as Bogdan already mentioned that `cross-fetch` should be in `dependencies`, a new resolver is on the roadmap however and might support this if we end up downloading dependencies on the fly.
