### ISSUE TITLE
Dependency could't resolve sass dependencies by .sassrc.js.

### ISSUE THREAD

**Issue by 2zH** [codesandbox/codesandbox-client#928]
# 🐛 bug report

## Description of the problem

```javascript
// src/index.js
import '@pluginjs/slider/src/css/slider.scss'
```
```scss
// node_modules/@pluginjs/slider/src/css/slider.scss
@import "@pluginjs/styles/variables.scss";
// ...
```
```sh
Error: Could not find /node_modules/@pluginjs/slider/src/css/node_modules/@pluginjs/styles/variables.scss
        on line 1 of /stdin
>> @import "@pluginjs/styles/variables.scss";
   --------^
```
```javascript
// node_modules/@pluginjs/slider/.sassrc.js
const pkg = require('./package.json')
const path = require('path')

const includePaths = ['../../node_modules', 'node_modules'].map(includePath => 
    path.resolve(includePath)
)
module.exports = {
  input: pkg.css.source,
  includePaths: includePaths,
  output: [
    { outputStyle: 'nested', file: pkg.css.min },
    { outputStyle: 'compressed', file: pkg.css.main }
  ]
}
```
Dependency could't resolve sass dependencies by includePaths.
It work fine in the local development environment. (real parcel environment)

## How has this issue affected you? What are you trying to accomplish?

I want to keep slider-samples synchronized bettween the local development environment and the codesandbox environment and view the version of the codesandbox via the GitHub link.
> https://codesandbox.io/s/github/pluginjs/plugin.js/tree/master/modules/slider/samples

Before resolve this issue, i was unable to import the scss file with dependencies from dependency.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | latest (online) |
| Browser | Chrome Version 69.0.3464.0 (Official Build) dev (64-bit) |
| Operating System | Arch Linux |

**Comment by bchoubert** [comment]
Any news on this ? ;) 
I encouter the same problem with my sandbox.

**Comment by lbogdan** [comment]
Hey @2zH ,

I tried running this locally, and I got the same error I'm getting in CodeSandbox:

![image](https://user-images.githubusercontent.com/2083930/62530482-e4f21980-b840-11e9-81cb-312e7a0c5a89.png)

**Comment by lbogdan** [comment]
@bchoubert Can you please link to a sandbox experiencing this issue?

**Comment by bchoubert** [comment]
Hi @lbogdan ,
I am unfortunately unable to provide you my sandbox URL, I deleted this project some monthes ago to develop with using other online solutions.

Sorry about that!

**Comment by esr360** [comment]
Is Codesandbox even looking to an existing `.sassrc` file? It doesn't seem to be from my experience. I'm not sure how I can configure Sass using Codesandbox.
