### ISSUE TITLE
Quokka Integration

### ISSUE THREAD

**Issue by johncokos** [codesandbox/codesandbox-client#950]
# 🌈 Feature

I really like the quokka plugin for VSCode (and Webstorm) as a way to have live code evaluation in the editor window.  https://quokkajs.com/

This is a VSCode plugin already, so I'm assuming you can somehow work on an integration for it. Essentially when you "turn it on", it evaluates your code in real time and shows the results next to the code thats running.  Very cool feature for testing and for instructional purposes.

**Comment by ealipio** [comment]
Agree, that will be amazing! any news about this ?
