### ISSUE TITLE
Import Github repo set react template by mistake

### ISSUE THREAD

**Issue by htammen** [codesandbox/codesandbox-client#956]
# 🐛 bug report

Import of this vanilla javascript [github repo](https://github.com/htammen/ValueHelpUI5.git) sets template to react. As a result the browser does not load my index.html. 

I'm a codesandbox newbie and in the end want to edit and test my [openui5](https://openui5.org/) projects within codesandbox.

###  Link to sandbox: [link](https://codesandbox.io/s/1z2ywjxp77)

**Comment by lbogdan** [comment]
I can still [replicate this](https://codesandbox.io/s/github/lbogdan/ValueHelpUI5), looks like a bug in the github importer.
