### ISSUE TITLE
Debounce function does not work as expected in sandbox

### ISSUE THREAD

**Issue by pjetrucha** [codesandbox/codesandbox-client#960]
# 🐛 bug report

## Description of the problem
Debounce function in codesandbox-client does not work as expected.

## How has this issue affected you? What are you trying to accomplish?
I'm trying to debounce resize and scroll events.

It seems doesn't work on Firefox:
![debounce](https://user-images.githubusercontent.com/9026680/42725094-76afec5c-877e-11e8-9f79-5dc9a95b1632.gif)

But everything works on Chrome:
![debounce-chrome](https://user-images.githubusercontent.com/9026680/42725216-62bea4c0-8780-11e8-9aed-8b5bb07e109b.gif)

Moreover when I download the source and open it from my PC it works correctly everywhere, so I assume it is a codesandbox-client's bug.

I tried to find out what caused this behavior, but without success.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1530978082-067f9fe
| Browser | Firefox 61.0.1 <br> Firefox 62.0b8 
| Operating System | Win10

**Comment by Temirtator** [comment]
+++. Will they fix this issue?

**Comment by pjetrucha** [comment]
@Temirtator I really don't know, but I don't have this behavior anymore. In 2018, if I remember correctly, they didn't fix it. Later I stopped following. I'm not sure if it's a Firefox update or a codesandbox update ;)
Is it happening to you now?

**Comment by Temirtator** [comment]
@pjetrucha that was my mistake. There is no bug)
