### ISSUE TITLE
Theme suggestion: Dracula

### ISSUE THREAD

**Issue by MarcelCutts** [codesandbox/codesandbox-client#966]
# 🌈 Feature

**What is this feature?**
[Dracula](https://draculatheme.com/) is a dark theme emphasising bold, contrasting colours that's available on a huge variety of platforms. It pairs nicely with dank mono and has earnt several, "what's that theme?" comment from random passers by in co-working spaces.

![screenshot 2018-07-16 at 16 12 59](https://user-images.githubusercontent.com/5721314/42766735-2784c472-8913-11e8-8248-e6c9423fa454.png)

**How should the feature should work?**
Select theme in codesandbox, receive pretty colours.

**You have examples or an idea how it can be implemented?**
Unfortunately I don't know how pre-installed themes get added or I'd help!

**Comment by CompuIves** [comment]
Heya! This seems like a great addition, could you add it to https://github.com/CompuIves/codesandbox-client/blob/master/packages/common/themes/index.js? That should be everything to add it.

**Comment by MarcelCutts** [comment]
I could extract the JSON version from VSCode and host it myself, which would bypass the necessity for a YAML parsing step - however the downside is should any big style updates happen they won't be captured automatically.

**Comment by SaraVieira** [comment]
I got this fams, I'm gonna fork that and convert it to JSON and use that url as the one codeSanbox uses. PR in 30

**Comment by SaraVieira** [comment]
@CompuIves got any idea why I get this error ?

<img width="1551" alt="screen shot 2018-07-17 at 15 08 06" src="https://user-images.githubusercontent.com/1051509/42822576-4a35f4e4-89d3-11e8-8779-d29bcdfa8586.png">

**Comment by lbogdan** [comment]
@SaraVieira Remove `packages/app/node_modules/styled-components`.

**Comment by CompuIves** [comment]
So sorry for that @SaraVieira, we need to automate that in the `postinstall` until it's fixed in Yarn.

**Comment by SaraVieira** [comment]
No need to apologize man! It happens. It's actually a styled components problem, it shouldn't be a problem, I had to switch to emotion once because of this
