### ISSUE TITLE
Specify private npm repo for scoped packages.

### ISSUE THREAD

**Issue by loliver** [codesandbox/codesandbox-client#97]
I've had a quick play around attempting to set this in .yarnrc and .npmrc but it appears the dependencies api call isn't parsing these when looking for a newly added dependency.

For example I ran `npm config set @myco:registry http://reg.example.com` (with correct details for our registry) but it's still looking at the official npm registry for `@myco` components.

**Comment by CompuIves** [comment]
Hmm, this is an interesting one. It should be possible if we add it as a config to the packager before we install, though we need to open an API to remember the custom registries per sandbox. I'll put it in the pipeline.

**Comment by angeliski** [comment]
Hey man, great job in the Codesandbox.
I would like that too

**Comment by jasonHzq** [comment]
Any progress on this?

**Comment by anyexinglu** [comment]
Any progress on this?

**Comment by garethx** [comment]
We'd be keen to know how you use private npm registries so that we can build an implementation that fits your needs. In particular, do you use a service for your private npm registries? (Like GitHub Package Registry) and do you host your npm registry within a VPN? Thanks

**Comment by loliver** [comment]
We use Artifactory to host npm registries inside a corporate firewall. I can't quite remember the exact details of what I was trying to accomplish at the time but our basic use-case is still the same.

I guess the main question is does Code Sandbox pull dependencies via the browser or the server. If it's the browser on the client machine then our own DNS would be able to point to the internal Artifactory but if it's the server then it's not possible to get our scenario to work.

**Comment by garethx** [comment]
We do both depending on the sandbox type, but we hope to be able to support client-side downloading for all types as we tackle this.

**Comment by donovanclarke** [comment]
@garethx I had a question about this. we currently have a set of private scoped packages that are on NPM. Is there anyway to access these via codesandbox?

**Comment by garethx** [comment]
@donovanclarke No, that will be covered as part of this work.

**Comment by roddds** [comment]
We use cloudsmith as the private registry, with credentials/settings stored in `.npmrc`:

```
always-auth=true
@myco:registry=https://npm.cloudsmith.io/myco/npm/
//npm.cloudsmith.io/myco/npm/:_authToken=AuThToKeNhErE
```

**Comment by idbartosz** [comment]
In our company we `Nexus Repository` to manage packages but it's accessible only via VPN. Nexus acts as proxy for public NPM packages and host for our private ones. 

Our `.npmrc` looks similar to this one:
```
registry=http://nexus.my.co/repository/npm-frontend/
always-auth=true
email=frontend@my.co
_auth=AuThToKeN(=
```

**Comment by CompuIves** [comment]
We're now finally working full-time on this, but we'd love to have your input so we can make sure that we cover all cases. If you're interested in helping us with this, could you send an email to ives@codesandbox.io and state how you use private npm packages?

We're interested in:

1. Do you self-host your registry?
2. Are you okay with setting CORS headers on the registry?
3. Is your registry only available through a CDN?

**Comment by roddds** [comment]
The issue has not been resolved? 😅

**Comment by iloveip** [comment]
Are there any updates on this? I would also like to use private packages with codesandbox.

**Comment by garethx** [comment]
This is now available to pilot users. Docs are here: https://codesandbox.io/docs/custom-npm-registry and you can register to join the pilot here: https://airtable.com/shrlgLSJWiX8rYqyG

**Comment by vaalgrind** [comment]
@garethx 
I joined into pilot on Friday, when I will be able to manage private npm registry on settings page? ( I have pro plan). Thanks in advance.

**Comment by garethx** [comment]
@vaalgrind I'll include you in the next cohort - will go out later this week. Thanks.
