### ISSUE TITLE
[typescript]: tsconfig doesn't support allowSyntheticDefaultImports

### ISSUE THREAD

**Issue by Hotell** [codesandbox/codesandbox-client#973]
# 🐛 bug report

## Description of the problem

tsconfig.json doesn't apply `allowSyntheticDefaultImports` flag

## How has this issue affected you? What are you trying to accomplish?
I wanna use `allowSyntheticDefaultImports` with TypeScript to properly resolve 3rd party ambient type definitions so I can do `import React from 'react'` instead of `import * as React from 'react'` 

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser |  latest chrome
| Operating System | OSX

**Comment by WolfspiritM** [comment]
This hit me aswell.
Anything new?

**Comment by ChuckJonas** [comment]
Same issue but with `experimentalDecorators`

**Comment by lbogdan** [comment]
@ChuckJonas Can you please point us to a sandbox experiencing the issue?

**Comment by SaraVieira** [comment]
Closed by lack of response
