### ISSUE TITLE
Google removes sandbox pereview for your clients based on their internal decisions 

### ISSUE THREAD

**Issue by ImanMh** [codesandbox/codesandbox-client#982]
# 🐛 bug report
Google gives me a 403 error when opening any sandbox code example. 
![googe 403](https://user-images.githubusercontent.com/4482199/42910646-94cb16ee-8afd-11e8-8ab4-fb35603c4b8d.png)

**Comment by emersonlaurentino** [comment]
hey, @ImanMh what your chrome version?

**Comment by ImanMh** [comment]
@emersonlaurentino any chrome or Firefox version, the fact is that Google selectively blocks users from certain countries. They don't understand nature of opensource, and take political arguments into Github and developers community. They are using open source community trust to achieve their targets. I think we should not let that happen.

**Comment by SaraVieira** [comment]
Hey!

Is this still happening?

**Comment by ImanMh** [comment]
@SaraVieira It's now worst! I can't even see the editor, I think the editor is now hosted on google too. This is what I see now: 

![image](https://user-images.githubusercontent.com/4482199/55609575-3e184680-5796-11e9-9b93-33bff300c8c6.png)

URL: https://j0y0vpz59.codesandbox.io/

**Comment by SaraVieira** [comment]
We host our app on google cloud yes, only the SSE part is somewhere else.

I really don't know what we can do about this :(

**Comment by ImanMh** [comment]
@SaraVieira the only solution is using a different service that has is less politically polluted than Google Cloud. This might be too much to ask but I just wanted you to know about it so if a future change is about to be made this issue is considered as well. Another reason for opening this issue is that Google people might see this and understand, how stupid these decisions(blocking everyone in a country) are and maybe they change something.

**Comment by ImanMh** [comment]
@SaraVieira anyway your attention is appreciated.

**Comment by ImanMh** [comment]
@SaraVieira This issue has been fixed. Thanks for using a better place than google to run your service on.
